**Please show your own effort. 
The objective of all assignments in this class is to learn and get better. You are not expected to code as a python expert. 
You are encouraged to explore other material to get a better understanding but copy code directly from online source or ChatGPT is not allowed. 
**

**--Q7(5 points)--**
#https://scikit-learn.org/stable/datasets/toy_dataset.html#diabetes-dataset
"""
1. load the iris dataset from sklearn toy datasets
2. Process the dataframe so that it only contains two target value indicate virginica or not virginica. 
   After the processing, the sample is virginica has a target value 1, and the sample is not virginica has a target value -1
   Based on the origin dataset, you will have 50 records with target value 1 and 100 with target value -1
3. Obtain two smaller data set. One (test_data) contains the five samples with target value 1 and five samples with target value -1. 
   The other (train_date) set contains the remaining records (140). (You can split the dataframe in the way you want, no restriction)
"""

In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np
iris = datasets.load_iris()
f_names = iris.feature_names
df = pd.DataFrame(data = iris.data, columns = f_names)
df['target'] = iris.target
for i in range(len(df['target'])):
    if df.at[i, 'target'] == 2:
        df.at[i, 'target'] = 1 ##iris-virginica
    else:
        df.at[i, 'target'] = -1 ##not iris-virginica
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,-1
1,4.9,3.0,1.4,0.2,-1
2,4.7,3.2,1.3,0.2,-1
3,4.6,3.1,1.5,0.2,-1
4,5.0,3.6,1.4,0.2,-1
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,1
146,6.3,2.5,5.0,1.9,1
147,6.5,3.0,5.2,2.0,1
148,6.2,3.4,5.4,2.3,1
149,5.9,3.0,5.1,1.8,1

In [2]:
test_data = df.head().append(df.tail())#smaller dataset to confirm the training of the algorithm
test_index = []
for x in range(10):
    test_index.append(x)
test_data.index = test_index
test_data

C:\Users\alexs\AppData\Local\Temp\ipykernel_3220\632463814.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_data = df.head().append(df.tail())#smaller dataset to confirm the training of the algorithm

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,-1
1,4.9,3.0,1.4,0.2,-1
2,4.7,3.2,1.3,0.2,-1
3,4.6,3.1,1.5,0.2,-1
4,5.0,3.6,1.4,0.2,-1
5,6.7,3.0,5.2,2.3,1
6,6.3,2.5,5.0,1.9,1
7,6.5,3.0,5.2,2.0,1
8,6.2,3.4,5.4,2.3,1
9,5.9,3.0,5.1,1.8,1

In [3]:
train_data = df[5:145] #large dataset to train the algorithm on
train_index = []
for x in range(140):
    train_index.append(x)
train_data.index = train_index
train_data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.4,3.9,1.7,0.4,-1
1,4.6,3.4,1.4,0.3,-1
2,5.0,3.4,1.5,0.2,-1
3,4.4,2.9,1.4,0.2,-1
4,4.9,3.1,1.5,0.1,-1
...,...,...,...,...,...
135,6.7,3.1,5.6,2.4,1
136,6.9,3.1,5.1,2.3,1
137,5.8,2.7,5.1,1.9,1
138,6.8,3.2,5.9,2.3,1
139,6.7,3.3,5.7,2.5,1

**--Q8(10 points)--**
"""Based on the discussion in class to implement your own non-OOP version Adaline algorithm, it can be a function accepts a dataframe, a learning rate, number of iterations and return the final SSE, learned weights and bias
You are allowed to implement your function based on author's OOP implementation. 
"""

In [4]:
def Adaline(data, rate, epoch):
    rgen = np.random.RandomState(1)
    weights = rgen.normal(loc = 0.0, scale = 0.01, size = data.shape[1])
    
    for i in range(epoch):
        predicted_output = np.dot(data[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']], weights[:4]) + weights[4]
        error = []
        SSE = 0
        for j in range(len(predicted_output)):
            error.append(data.at[j, 'target'] - predicted_output[j])
            SSE += ((data.at[j, 'target'] - predicted_output[j]) ** 2) / 4
            if SSE == 0:
                break
        weights[:4] += rate * np.dot(data[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']].transpose(), error)
        weights[4] += rate * sum(error)
        print(SSE)
        if SSE == 0:
            break
    
    bias = weights[4]
        
    return SSE, weights[:4], bias

**--Q9--(3 points)**
implement a function named predict that accept a sample, learned weights and bias to predict the output. If the calculated weighted sum is greater than threshold, return output 1, otherwise, return output -1

In [5]:
def Predict(data, weights, bias, threshold):
    results = []
    predict = np.dot(data[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']], weights) + bias
    for j in range(len(predict)):
        results.append(1 if predict[j] > threshold else -1)
    
    return results

**--Q10--(2 points)**
Using your implemented Adaline Algorithm to train the train data set that selected in Q7, keep the returned weights and bias

In [6]:
sse, l_weights, l_bias = Adaline(train_data, .0001, 100000)
print('Weights:', l_weights, '| Bias:', l_bias, '| Final SSE:', sse)

36.65242500012689
33.112167634528255
32.14549835645849
31.2689617638156
30.443079401022008
29.664428246418694
28.930278567587457
28.238065296855375
27.58537136319619
26.969919054010592
26.3895619787335
25.84227749731164
25.326159585246913
24.83941211001345
24.38034249512935
23.94735574953303
23.5389488412015
23.153705395163616
22.790290697204615
22.447446985636972
22.123989014529098
21.81879987274045
21.530827044014288
21.25907869423001
21.002620172717258
20.76057071529069
20.532100337374303
20.31642690625586
20.112813382143543
19.920565218292
19.739027911027076
19.567584691025935
19.405654347709017
19.25268917906877
19.10817305970301
18.97161962023788
18.842570531717794
18.720593888910802
18.60528268682603
18.496253385068908
18.393144554970206
18.295615604715827
18.203345577980887
18.11603202182947
18.03338991988694
17.95515068702113
17.881061221986233
17.81088301468754
17.744391304917553
17.681374289596157
17.621632375718097
17.564977476372427
17.511232347350816
17.460229962004195
17.411812922142843
17.36583290290145
17.322150129611078
17.28063288483265
17.241157043812887
17.203605636723942
17.16786843614253
17.133841568313528
17.101427146826246
17.070532927411808
17.0410719826432
17.012962395391106
16.986126969953514
16.960492959840806
16.935991811255352
16.91255892136119
16.890133410490858
16.86865790748591
16.84807834741376
16.828343780947367
16.80940619473546
16.7912203421292
16.77374358366881
16.756935736766795
16.74075893405802
16.72517748991665
16.710157774669224
16.695668096060054
16.681678587550888
16.668161103060758
16.65508911777469
16.642437634671346
16.63018309643995
16.618303302475713
16.60677733066096
16.59558546365602
16.584709119439914
16.574130785855733
16.563833958929933
16.553803084747802
16.54402350468025
16.534481403768435
16.52516376208453
16.516058308896653
16.507153479476507
16.49843837439738
16.489902721178737
16.481536838142333
16.473331600352132
16.46527840751809
16.45736915375036
16.449596199057428
16.441952342487536
16.434430796818578
16.427025164707388
16.419729416214043
16.412537867622092
16.40544516147991
16.398446247792755
16.391536366299214
16.38471102976951
16.37796600826679
16.371297314315786
16.36470118892664
16.358174088424462
16.351712672038293
16.345313790205623
16.338974473551193
16.332691922501255
16.32646349749659
16.32028670976986
16.31415921265463
16.308078793395463
16.302043365430325
16.29605096111777
16.29009972488358
16.284187906762483
16.278313856312195
16.2724760168784
16.26667292019041
16.26090318126823
16.25516549362353
16.249458624737056
16.24378141179696
16.238132757682717
16.232511627180628
16.226917043417576
16.2213480845003
16.21580388034844
16.21028360971025
16.20478649735029
16.19931181139925
16.193858860856626
16.18842699323733
16.183015592353986
16.177624076227136
16.172251895115807
16.166898529661772
16.161563489140683
16.156246309814062
16.150946553376365
16.145663805491484
16.140397674413652
16.135147789687895
16.129913800925355
16.124695376649242
16.119492203207347
16.114303983747103
16.109130437249952
16.10397129762124
16.09882631283258
16.09369524411373
16.088577865191006
16.083473961569542
16.078383329857083
16.073305777126613
16.0682411203158
16.063189185660992
16.058149808164004
16.05312283108935
16.048108105490805
16.043105489764958
16.0381148492307
16.033136055732815
16.02816898726855
16.023213527635598
16.018269566100393
16.013336997085602
16.008415719875487
16.00350563833846
15.998606660665349
15.993718699123024
15.988841669822017
15.983975492497663
15.979120090303761
15.974275389618224
15.969441319859866
15.964617813315659
15.959804804978173
15.9550022323922
15.950210035510208
15.945428156556277
15.940656539897674
15.93589513192402
15.93114388093327
15.926402737024329
15.921671651995855
15.916950579250866
15.91223947370686
15.907538291711086
15.902846990960738
15.898165530427724
15.893493870287699
15.888831971853339
15.884179797511292
15.879537310662865
15.874904475668083
15.87028125779295
15.865667623159833
15.861063538700572
15.856468972112385
15.851883891816284
15.847308266917842
15.842742067170294
15.8381852629397
15.833637825172126
15.829099725362711
15.824570935526534
15.8200514281711
15.815541176270496
15.811040153240924
15.806548332917702
15.802065689533633
15.797592197698483
15.793127832379776
15.788672568884566
15.784226382842384
15.779789250189067
15.775361147151486
15.770942050233302
15.766531936201389
15.76213078207308
15.757738565104159
15.753355262777566
15.748980852792632
15.744615313055093
15.740258621667534
15.735910756920463
15.731571697283865
15.727241421399215
15.722919908072015
15.71860713626466
15.714303085089792
15.710007733804016
15.705721061801915
15.701443048610484
15.697173673883826
15.692912917398163
15.688660759047162
15.684417178837489
15.680182156884538
15.675955673408614
15.671737708731149
15.667528243271134
15.663327257541871
15.659134732147807
15.654950647781542
15.650774985221128
15.646607725327334
15.64244884904121
15.638298337381716
15.634156171443493
15.630022332394804
15.625896801475509
15.621779559995199
15.617670589331471
15.613569870928169
15.609477386293875
15.605393117000395
15.601317044681322
15.59724915103074
15.593189417801923
15.589137826806118
15.5850943599115
15.581058999041996
15.577031726176335
15.573012523347058
15.569001372639601
15.56499825619147
15.56100315619139
15.557016054878503
15.553036934541678
15.54906577751881
15.545102566196125
15.541147283007572
15.537199910434197
15.533260431003628
15.52932882728947
15.52540508191086
15.521489177531903
15.517581096861248
15.513680822651637
15.509788337699488
15.505903624844505
15.502026666969234
15.498157446998734
15.494295947900289
15.490442152682933
15.486596044397253
15.48275760613501
15.478926821028914
15.475103672252224
15.471288143018633
15.467480216581881
15.46367987623556
15.4598871053129
15.45610188718645
15.452324205267983
15.44855404300815
15.444791383896401
15.441036211460675
15.437288509267301
15.433548260920746
15.429815450063465
15.426090060375746
15.42237207557549
15.418661479418118
15.414958255696353
15.411262388240111
15.407573860916315
15.40389265762877
15.400218762318056
15.396552158961308
15.392892831572176
15.38924076420062
15.385595940932836
15.381958345891096
15.378327963233657
15.374704777154625
15.37108877188382
15.367479931686715
15.363878240864253
15.36028368375284
15.356696244724105
15.353115908184916
15.349542658577203
15.34597648037788
15.34241735809875
15.338865276286393
15.335320219522053
15.331782172421606
15.328251119635407
15.32472704584819
15.321209935779008
15.317699774181152
15.314196545842014
15.31070023558302
15.307210828259588
15.30372830876094
15.3002526620101
15.296783872963786
15.293321926612336
15.289866807979566
15.286418502122745
15.28297699413252
15.279542269132783
15.276114312280626
15.272693108766251
15.269278643812894
15.265870902676737
15.262469870646818
15.259075533045008
15.255687875225844
15.252306882576512
15.24893254051679
15.245564834498895
15.24220375000746
15.238849272559468
15.235501387704149
15.232160081022878
15.228825338129173
15.225497144668577
15.222175486318566
15.218860348788507
15.215551717819585
15.212249579184702
15.208953918688442
15.205664722166937
15.202381975487896
15.199105664550428
15.195835775285017
15.19257229365344
15.18931520564875
15.18606449729511
15.182820154647759
15.179582163793032
15.176350510848113
15.173125181961135
15.169906163310987
15.166693441107311
15.163487001590441
15.160286831031268
15.157092915731234
15.153905242022256
15.150723796266595
15.147548564856876
15.144379534215961
15.1412166907969
15.138060021082865
15.134909511587079
15.13176514885272
15.128626919452937
15.12549480999069
15.122368807098708
15.119248897439459
15.116135067705057
15.113027304617198
15.109925594927079
15.106829925415358
15.103740282892067
15.10065665419656
15.097579026197455
15.094507385792527
15.091441719908696
15.088382015501928
15.08532825955719
15.082280439088358
15.079238541138174
15.076202552778188
15.073172461108665
15.07014825325854
15.067129916385381
15.064117437675261
15.061110804342734
15.058110003630766
15.055115022810696
15.05212584918213
15.049142470072896
15.046164872838974
15.043193044864468
15.040226973561472
15.037266646370101
15.034312050758338
15.03136317422206
15.028420004284856
15.025482528498106
15.022550734440818
15.019624609719603
15.016704141968603
15.01378931884945
15.010880128051182
15.007976557290196
15.005078594310174
15.002186226882028
14.999299442803851
14.996418229900833
14.99354257602523
14.990672469056273
14.987807896900117
14.984948847489802
14.982095308785167
14.979247268772811
14.976404715466002
14.973567636904662
14.970736021155258
14.967909856310794
14.965089130490707
14.962273831840852
14.95946394853338
14.956659468766736
14.953860380765605
14.95106667278078
14.94827833308922
14.94549534999384
14.942717711823637
14.939945406933472
14.937178423704076
14.934416750542008
14.931660375879575
14.92890928817479
14.926163475911268
14.923422927598242
14.920687631770459
14.917957576988137
14.915232751836882
14.91251314492768
14.909798744896817
14.907089540405769
14.904385520141254
14.901686672815112

14.898992987164236
14.896304451950524
14.893621055960878
14.890942788007042
14.888269636925692
14.885601591578203
14.882938640850771
14.880280773654222
14.877627978924046
14.874980245620291
14.872337562727513
14.869699919254748
14.867067304235437
14.864439706727387
14.861817115812672
14.859199520597656
14.856586910212863
14.853979273812977
14.851376600576755
14.848778879706982
14.846186100430439
14.843598251997808
14.841015323683663
14.838437304786373
14.8358641846281
14.833295952554694
14.83073259793566
14.82817411016415
14.825620478656823
14.82307169285385
14.820527742218866
14.817988616238873
14.815454304424271
14.812924796308684
14.810400081449032
14.807880149425397
14.805364989841
14.802854592322145
14.800348946518175
14.797848042101403
14.795351868767098
14.792860416233399
14.790373674241255
14.787891632554413
14.785414280959332
14.782941609265174
14.780473607303692
14.778010264929238
14.775551572018685
14.773097518471387
14.770648094209104
14.768203289175982
14.7657630933385
14.763327496685392
14.760896489227642
14.75847006099838
14.75604820205291
14.75363090246856
14.751218152344713
14.748809941802728
14.74640626098591
14.744007100059402
14.741612449210232
14.739222298647173
14.736836638600732
14.734455459323142
14.732078751088254
14.729706504191462
14.727338708949793
14.724975355701673
14.722616434807064
14.72026193664724
14.717911851624907
14.71556617016401
14.71322488270977
14.71088797972865
14.70855545170822
14.706227289157187
14.703903482605314
14.70158402260343
14.699268899723275
14.696958104557558
14.694651627719828
14.692349459844502
14.690051591586771
14.68775801362257
14.685468716648518
14.683183691381892
14.680902928560565
14.678626418942958
14.676354153308022
14.674086122455153
14.671822317204184
14.669562728395299
14.667307346889022
14.665056163566172
14.66280916932778
14.660566355095082
14.658327711809465
14.6560932304324
14.653862901945457
14.651636717350156
14.64941466766804
14.647196743940546
14.644982937229003
14.642773238614577
14.640567639198197
14.638366130100586
14.636168702462124
14.63397534744287
14.631786056222502
14.629600820000269
14.627419629994932
14.625242477444752
14.62306935360742
14.620900249760027
14.618735157199021
14.616574067240153
14.614416971218459
14.612263860488188
14.610114726422754
14.60796956041475
14.605828353875825
14.603691098236709
14.601557784947131
14.599428405475805
14.59730295131034
14.595181413957247
14.593063784941911
14.590950055808452
14.588840218119815
14.586734263457608
14.584632183422142
14.582533969632369
14.58043961372582
14.578349107358573
14.5762624422052
14.57417960995879
14.57210060233083
14.570025411051171
14.567954027868039
14.565886444547974
14.563822652875713
14.561762644654317
14.559706411704937
14.557653945866914
14.555605238997689
14.553560282972729
14.551519069685572
14.549481591047687
14.547447838988516
14.545417805455385
14.543391482413481
14.541368861845832
14.539349935753213
14.537334696154161
14.535323135084912
14.533315244599374
14.53131101676903
14.529310443683025
14.527313517447983
14.525320230188056
14.523330574044868
14.521344541177454
14.519362123762264
14.517383313993054
14.51540810408094
14.513436486254278
14.511468452758661
14.509503995856905
14.507543107828944
14.505585780971858
14.50363200759978
14.501681780043919
14.49973509065248
14.497791931790612
14.495852295840423
14.493916175200887
14.491983562287853
14.490054449533954
14.488128829388662
14.48620669431812
14.48428803680523
14.482372849349506
14.480461124467155
14.478552854690916
14.47664803257013
14.474746650670632
14.47284870157475
14.470954177881241
14.469063072205294
14.46717537717844
14.465291085448586
14.4634101896799
14.461532682552814
14.459658556764015
14.457787805026372
14.45592042006888
14.45405639463669
14.452195721491002
14.45033839340909
14.448484403184223
14.446633743625647
14.444786407558551
14.442942387824028
14.441101677279036
14.439264268796355
14.43743015526459
14.435599329588092
14.433771784686934
14.43194751349689
14.430126508969394
14.428308764071492
14.426494271785826
14.4246830251106
14.422875017059505
14.421070240661747
14.41926868896198
14.417470355020239
14.415675231911976
14.413883312727982
14.412094590574336
14.410309058572443
14.408526709858895
14.406747537585535
14.404971534919364
14.403198695042533
14.40142901115229
14.399662476460962
14.397899084195945
14.396138827599584
14.394381699929255
14.392627694457259
14.390876804470764
14.389129023271876
14.387384344177505
14.385642760519369
14.383904265643986
14.382168852912583
14.38043651570111
14.378707247400211
14.376981041415146
14.375257891165804
14.373537790086637
14.371820731626665
14.370106709249413
14.368395716432877
14.366687746669527
14.364982793466204
14.363280850344179
14.361581910839073
14.359885968500794
14.358193016893576
14.35650304959587
14.354816060200415
14.35313204231406
14.3514509895579
14.349772895567098
14.348097753990945
14.346425558492802
14.344756302750055
14.343089980454081
14.341426585310284
14.33976611103793
14.338108551370293
14.336453900054424
14.334802150851308
14.333153297535711
14.331507333896191
14.329864253735051
14.328224050868362
14.326586719125837
14.324952252350899
14.323320644400582
14.32169188914552
14.320065980469952
14.318442912271635
14.316822678461843
14.315205272965327
14.313590689720323
14.311978922678453
14.310369965804759
14.308763813077636
14.307160458488832
14.30555989604335
14.303962119759515
14.302367123668898
14.300774901816268
14.299185448259564
14.297598757069927
14.296014822331573
14.29443363814187
14.292855198611226
14.291279497863076
14.289706530033902
14.288136289273153
14.286568769743203
14.285003965619397
14.283441871089964
14.281882480355955
14.280325787631318
14.278771787142784
14.277220473129864
14.27567183984484
14.274125881552669
14.272582592531084
14.271041967070417
14.26950399947366
14.267968684056422
14.266436015146896
14.264905987085836
14.263378594226495
14.261853830934658
14.260331691588554
14.258812170578887
14.257295262308736
14.25578096119361
14.254269261661356
14.252760158152144
14.25125364511848
14.24974971702513
14.248248368349113
14.246749593579667
14.245253387218224
14.2437597437784
14.242268657785951
14.240780123778734
14.239294136306693
14.237810689931855
14.236329779228274
14.23485139878199
14.233375543191057
14.23190220706545
14.230431385027087
14.228963071709803
14.227497261759275
14.226033949833052
14.224573130600492
14.223114798742754
14.221658948952777
14.220205575935202
14.218754674406453
14.217306239094576
14.215860264739316
14.214416746092066
14.212975677915797
14.211537054985111
14.210100872086128
14.208667124016518
14.207235805585494
14.205806911613692
14.204380436933244
14.202956376387725
14.20153472483208
14.200115477132652
14.198698628167177
14.19728417282466
14.195872106005444
14.194462422621159
14.193055117594671
14.191650185860087
14.190247622362733
14.188847422059098
14.187449579916809
14.186054090914672
14.184660950042565
14.183270152301446
14.181881692703342
14.180495566271302
14.179111768039405
14.17773029305269
14.176351136367147
14.174974293049731
14.17359975817828
14.172227526841535
14.17085759413907
14.169489955181339
14.16812460508957
14.166761538995795
14.165400752042826
14.164042239384186
14.162685996184134
14.161332017617614
14.159980298870247
14.158630835138284
14.157283621628626
14.155938653558728
14.154595926156684
14.153255434661066
14.151917174321026
14.150581140396179
14.14924732815668
14.14791573288307
14.146586349866373
14.145259174408011
14.143934201819778
14.142611427423859
14.141290846552758
14.139972454549316
14.138656246766644
14.137342218568152
14.136030365327487
14.134720682428501
14.133413165265315
14.132107809242163
14.130804609773447
14.129503562283743
14.128204662207716
14.12690790499012
14.125613286085773
14.124320800959566
14.123030445086359
14.121742213951087
14.120456103048598
14.11917210788374
14.117890223971264
14.116610446835862
14.11533277201209
14.114057195044392
14.11278371148706
14.111512316904179
14.110243006869679
14.108975776967236
14.107710622790302
14.106447539942073
14.105186524035448
14.103927570693008
14.102670675547033
14.101415834239456
14.100163042421796
14.098912295755225
14.097663589910482
14.09641692056788
14.095172283417268
14.09392967415799
14.092689088498966
14.091450522158526
14.09021397086449
14.088979430354103
14.08774689637404
14.086516364680351
14.085287831038498
14.084061291223266
14.08283674101877
14.081614176218476
14.080393592625082
14.079174986050608
14.07795835231631
14.076743687252657
14.075530986699377
14.074320246505302
14.073111462528516
14.0719046306362
14.070699746704678
14.069496806619401
14.06829580627486
14.067096741574662
14.065899608431442
14.06470440276684
14.06351112051154
14.062319757605191
14.061130309996397
14.059942773642742
14.05875714451069
14.057573418575666
14.056391591821933
14.055211660242668
14.054033619839839
14.052857466624292
14.051683196615656
14.05051080584234
14.04934029034156
14.04817164615923
14.047004869350026
14.045839955977339
14.044676902113228
14.043515703838445
14.042356357242362
14.041198858423018
14.040043203487079
14.038889388549737
14.03773740973482
14.036587263174715
14.035438945010284
14.034292451390987
14.033147778474728
14.032004922427909
14.030863879425388
14.029724645650498
14.028587217294938
14.027451590558856
14.026317761650763
14.025185726787571
14.0240554821945
14.02292702410512
14.021800348761316
14.02067545241325
14.019552331319392
14.018430981746425
14.017311399969321
14.016193582271203
14.015077524943477
14.013963224285668
14.012850676605503
14.01173987821883
14.010630825449644
14.009523514630034
14.008417942100216
14.007314104208437
14.006211997311032
14.005111617772364
14.00401296196481
14.002916026268752
14.00182080707257
14.000727300772603
13.999635503773133
13.998545412486386
13.9974570233325
13.996370332739502
13.995285337143292
13.994202032987667
13.993120416724212
13.992040484812392
13.99096223371946
13.989885659920445
13.988810759898172
13.987737530143226
13.986665967153904
13.985596067436257
13.984527827504024
13.983461243878628
13.982396313089197
13.981333031672458
13.980271396172839
13.979211403142312
13.978153049140525
13.977096330734675
13.976041244499529
13.974987787017422
13.973935954878208
13.972885744679258
13.971837153025476
13.970790176529224
13.969744811810324
13.96870105549607
13.967658904221196
13.96661835462784
13.965579403365547
13.96454204709124
13.963506282469234
13.962472106171186
13.961439514876076
13.960408505270214
13.959379074047236
13.958351217908026
13.957324933560777
13.956300217720901
13.955277067111094
13.954255478461231
13.953235448508423
13.95221697399695
13.951200051678306
13.950184678311084
13.94917085066109
13.948158565501203
13.94714781961144
13.9461386097789
13.94513093279778
13.9441247854693
13.94312016460181
13.94211706701059
13.941115489518015
13.940115428953426
13.939116882153163
13.938119845960545
13.937124317225805
13.936130292806155
13.93513776956573
13.93414674437556
13.933157214113542
13.932169175664528
13.931182625920153
13.930197561778929
13.929213980146228
13.928231877934172
13.927251252061756
13.926272099454744
13.925294417045626
13.92431820177368
13.923343450584941
13.922370160432177
13.92139832827479
13.92042795107898
13.91945902581757
13.918491549470062
13.917525519022602
13.916560931467984
13.915597783805637
13.914636073041564
13.913675796188379
13.912716950265303
13.91175953229804
13.910803539318934
13.909848968366804
13.908895816487032
13.907944080731461
13.906993758158443
13.906044845832836
13.9050973408259
13.904151240215391
13.903206541085483
13.902263240526779
13.901321335636254
13.900380823517317
13.899441701279711
13.898503966039584
13.8975676149194
13.89663264504797
13.89569905356041
13.89476683759816
13.893835994308954
13.892906520846779
13.891978414371916
13.891051672050862
13.890126291056394
13.889202268567459
13.888279601769245
13.887358287853138

13.886438324016693
13.885519707463612
13.884602435403794
13.88368650505324
13.882771913634093
13.881858658374618
13.880946736509145
13.880036145278122
13.879126881928062
13.878218943711502
13.877312327887093
13.876407031719443
13.875503052479226
13.874600387443087
13.873699033893686
13.872798989119671
13.871900250415605
13.871002815082058
13.870106680425494
13.869211843758336
13.868318302398894
13.867426053671384
13.866535094905895
13.865645423438425
13.86475703661079
13.863869931770658
13.862984106271565
13.862099557472826
13.861216282739575
13.860334279442746
13.859453544959049
13.858574076670966
13.857695871966733
13.856818928240333
13.855943242891469
13.855068813325554
13.854195636953728
13.853323711192822
13.852453033465311
13.851583601199398
13.850715411828856
13.849848462793178
13.848982751537449
13.848118275512375
13.847255032174248
13.846393018984992
13.84553223341207
13.844672672928526
13.843814335012983
13.842957217149563
13.842101316827925
13.841246631543276
13.84039315879631
13.8395408960932
13.838689840945593
13.837839990870672
13.836991343390977
13.836143896034551
13.835297646334881
13.834452591830834
13.833608730066697
13.832766058592163
13.831924574962304
13.83108427673754
13.83024516148369
13.829407226771917
13.828570470178686
13.827734889285813
13.826900481680402
13.826067244954894
13.825235176706991
13.824404274539667
13.823574536061194
13.822745958885069
13.821918540630024
13.821092278920048
13.820267171384327
13.819443215657268
13.818620409378456
13.817798750192686
13.816978235749893
13.816158863705214
13.815340631718888
13.814523537456301
13.813707578588001
13.812892752789617
13.812079057741903
13.81126649113067
13.810455050646864
13.809644733986447
13.80883553885047
13.808027462945017
13.80722050398123
13.806414659675237
13.805609927748213
13.804806305926332
13.804003791940737
13.803202383527566
13.802402078427939
13.801602874387893
13.800804769158468
13.80000776049559
13.799211846160127
13.798417023917883
13.797623291539537
13.796830646800657
13.796039087481729
13.795248611368065
13.794459216249864
13.793670899922153
13.792883660184824
13.79209749484259
13.791312401704948
13.790528378586236
13.789745423305588
13.788963533686893
13.788182707558839
13.787402942754861
13.786624237113177
13.785846588476694
13.785069994693115
13.78429445361481
13.783519963098879
13.782746521007134
13.781974125206055
13.781202773566807
13.780432463965246
13.779663194281861
13.778894962401788
13.778127766214826
13.777361603615374
13.776596472502455
13.775832370779701
13.775069296355346
13.77430724714221
13.77354622105769
13.772786216023729
13.772027229966863
13.771269260818123
13.770512306513123
13.769756364991979
13.769001434199325
13.768247512084312
13.767494596600573
13.76674268570623
13.765991777363862
13.765241869540569
13.764492960207843
13.763745047341652
13.76299812892241
13.762252202934922
13.76150726736845
13.760763320216633
13.760020359477524
13.759278383153545
13.7585373892515
13.75779737578258
13.757058340762315
13.756320282210577
13.755583198151589
13.754847086613903
13.754111945630376
13.753377773238206
13.752644567478855
13.751912326398072
13.751181048045945
13.750450730476755
13.749721371749088
13.74899296992579
13.748265523073925
13.74753902926481
13.746813486573956
13.746088893081128
13.745365246870271
13.744642546029535
13.743920788651252
13.743199972831915
13.742480096672233
13.741761158277031
13.741043155755294
13.740326087220133
13.739609950788832
13.738894744582753
13.738180466727396
13.737467115352363
13.73675468859131
13.736043184582062
13.735332601466428
13.734622937390355
13.733914190503803
13.733206358960793
13.732499440919415
13.731793434541736
13.731088337993894
13.730384149446019
13.729680867072233
13.728978489050693
13.72827701356349
13.727576438796746
13.726876762940508
13.726177984188807
13.725480100739606
13.724783110794842
13.724087012560362
13.723391804245937
13.722697484065264
13.72200405023594
13.721311500979471
13.720619834521239
13.71992904909052
13.71923914292046
13.71855011424807
13.717861961314204
13.717174682363572
13.716488275644737
13.715802739410066
13.715118071915764
13.714434271421847
13.713751336192155
13.71306926449427
13.712388054599602
13.711707704783336
13.711028213324438
13.710349578505609
13.709671798613325
13.708994871937799
13.70831879677299
13.70764357141658
13.706969194169965
13.70629566333826
13.705622977230298
13.70495113415858
13.704280132439324
13.703609970392405
13.70294064634139
13.702272158613486
13.701604505539583
13.700937685454178
13.700271696695465
13.699606537605204
13.698942206528839
13.698278701815378
13.697616021817463
13.696954164891343
13.696293129396826
13.695632913697336
13.694973516159846
13.694314935154923
13.693657169056655
13.693000216242721
13.692344075094317
13.691688743996197
13.691034221336613
13.690380505507378
13.689727594903758
13.689075487924578
13.68842418297212
13.6877736784522
13.687123972774067
13.686475064350466
13.685826951597617
13.685179632935169
13.684533106786242
13.683887371577413
13.683242425738644
13.68259826770338
13.681954895908461
13.681312308794121
13.680670504804008
13.680029482385216
13.679389239988149
13.678749776066642
13.678111089077875
13.677473177482435
13.676836039744249
13.676199674330574
13.675564079712032
13.674929254362592
13.674295196759534
13.673661905383451
13.673029378718287
13.67239761525125
13.671766613472885
13.671136371877013
13.670506888960745
13.669878163224451
13.669250193171791
13.668622977309703
13.66799651414835
13.667370802201152
13.666745839984785
13.666121626019141
13.665498158827365
13.6648754369358
13.664253458873997
13.663632223174742
13.66301172837399
13.662391973010903
13.66177295562783
13.661154674770286
13.660537128986958
13.659920316829725
13.659304236853577
13.658688887616684
13.658074267680352
13.657460375609011
13.656847209970234
13.65623476933473
13.65562305227627
13.655012057371785
13.654401783201287
13.653792228347891
13.65318339139779
13.652575270940233
13.651967865567588
13.651361173875276
13.650755194461771
13.650149925928586
13.649545366880302
13.648941515924543
13.64833837167194
13.647735932736172
13.647134197733932
13.646533165284918
13.645932834011848
13.64533320254043
13.644734269499361
13.64413603352033
13.643538493238012
13.642941647290042
13.642345494317011
13.641750032962502
13.641155261873037
13.640561179698057
13.639967785089995
13.639375076704187
13.63878305319887
13.638191713235258
13.637601055477429
13.637011078592408
13.636421781250093
13.635833162123284
13.635245219887675
13.634657953221835
13.63407136080721
13.633485441328112
13.63290019347174
13.632315615928109
13.631731707390108
13.631148466553466
13.630565892116742
13.629983982781331
13.629402737251473
13.628822154234184
13.62824223243933
13.62766297057956
13.627084367370333
13.626506421529903
13.6259291317793
13.625352496842346
13.624776515445628
13.624201186318524
13.62362650819314
13.623052479804366
13.622479099889837
13.621906367189911
13.621334280447732
13.620762838409116
13.620192039822642
13.619621883439615
13.619052368014037
13.618483492302602
13.617915255064737
13.61734765506257
13.616780691060882
13.616214361827165
13.61564866613158
13.615083602746969
13.614519170448812
13.61395536801531
13.613392194227231
13.612829647868077
13.612267727723934
13.611706432583565
13.611145761238324
13.610585712482212
13.610026285111877
13.609467477926508
13.608909289727979
13.608351719320712
13.607794765511747
13.60723842711072
13.60668270292984
13.60612759178389
13.605573092490236
13.605019203868817
13.604465924742126
13.603913253935207
13.603361190275654
13.602809732593633
13.602258879721804
13.60170863049539
13.601158983752143
13.600609938332319
13.60006149307871
13.599513646836602
13.598966398453797
13.598419746780605
13.597873690669802
13.597328228976677
13.596783360559
13.596239084277011
13.595695398993437
13.595152303573435
13.594609796884672
13.59406787779724
13.593526545183687
13.592985797919017
13.592445634880656
13.591906054948472
13.59136705700476
13.590828639934251
13.590290802624077
13.589753543963795
13.589216862845356
13.588680758163134
13.588145228813875
13.587610273696741
13.587075891713246
13.586542081767313
13.586008842765244
13.585476173615685
13.584944073229675
13.584412540520598
13.58388157440418
13.583351173798533
13.582821337624077
13.582292064803582
13.581763354262156
13.581235204927248
13.580707615728588
13.58018058559828
13.57965411347068
13.579128198282522
13.578602838972776
13.578078034482763
13.577553783756054
13.57703008573853
13.576506939378373
13.575984343625967
13.575462297434083
13.574940799757655
13.57441984955394
13.573899445782445
13.573379587404888
13.572860273385286
13.572341502689873
13.571823274287107
13.571305587147721
13.570788440244645
13.570271832553033
13.569755763050248
13.569240230715897
13.568725234531758
13.568210773481834
13.567696846552328
13.567183452731626
13.56667059101031
13.566158260381112
13.565646459839007
13.565135188381097
13.564624445006649
13.564114228717125
13.56360453851613
13.563095373409412
13.562586732404883
13.562078614512606
13.56157101874476
13.561063944115693
13.560557389641861
13.560051354341834
13.559545837236348
13.55904083734819
13.558536353702323
13.558032385325786
13.557528931247726
13.557025990499378
13.556523562114084

13.556021645127275
13.555520238576442
13.555019341501204
13.554518952943202
13.55401907194619
13.553519697555927
13.553020828820324
13.552522464789256
13.552024604514715
13.551527247050718
13.551030391453315
13.550534036780606
13.550038182092718
13.549542826451816
13.54904796892208
13.548553608569732
13.548059744462961
13.547566375672021
13.54707350126916
13.546581120328598
13.546089231926576
13.545597835141342
13.545106929053125
13.5446165127441
13.54412658529847
13.543637145802409
13.543148193344043
13.542659727013474
13.542171745902763
13.541684249105943
13.541197235718972
13.540710704839805
13.540224655568307
13.539739087006277
13.539253998257472
13.538769388427582
13.538285256624224
13.537801601956918
13.537318423537132
13.53683572047823
13.536353491895508
13.535871736906138
13.535390454629228
13.534909644185756
13.534429304698618
13.533949435292593
13.533470035094334
13.532991103232392
13.532512638837181
13.532034641040998
13.531557108978022
13.531080041784266
13.530603438597625
13.530127298557849
13.529651620806547
13.52917640448716
13.528701648744983
13.528227352727157
13.527753515582644
13.527280136462258
13.526807214518636
13.526334748906221
13.525862738781303
13.52539118330196
13.524920081628121
13.524449432921482
13.523979236345582
13.52350949106571
13.523040196249017
13.522571351064386
13.522102954682513
13.521635006275892
13.521167505018779
13.520700450087203
13.520233840658985
13.519767675913704
13.519301955032688
13.518836677199076
13.518371841597688
13.517907447415173
13.517443493839867
13.516979980061896
13.51651690527311
13.516054268667085
13.515592069439156
13.515130306786366
13.514668979907496
13.514208088003056
13.513747630275244
13.513287605928005
13.512828014166981
13.512368854199522
13.51191012523469
13.511451826483228
13.510993957157584
13.510536516471916
13.510079503642034
13.509622917885466
13.509166758421404
13.508711024470713
13.508255715255958
13.507800830001324
13.507346367932723
13.506892328277674
13.506438710265398
13.505985513126737
13.505532736094208
13.505080378401965
13.504628439285817
13.504176917983175
13.503725813733151
13.503275125776437
13.502824853355369
13.502374995713927
13.501925552097683
13.501476521753856
13.501027903931266
13.500579697880339
13.500131902853115
13.49968451810325
13.49923754288597
13.498790976458153
13.498344818078209
13.497899067006157
13.49745372250365
13.497008783833847
13.496564250261548
13.496120121053094
13.495676395476423
13.49523307280102
13.494790152297947
13.494347633239832
13.49390551490086
13.49346379655677
13.493022477484837
13.492581556963923
13.492141034274404
13.491700908698183
13.491261179518748
13.490821846021097
13.490382907491753
13.48994436321877
13.489506212491742
13.489068454601766
13.488631088841467
13.488194114504987
13.487757530887965
13.48732133728757
13.48688553300245
13.486450117332767
13.486015089580206
13.485580449047887
13.485146195040485
13.484712326864113
13.484278843826397
13.483845745236453
13.483413030404837
13.48298069864363
13.482548749266321
13.482117181587936
13.481685994924923
13.481255188595199
13.480824761918157
13.480394714214619
13.479965044806882
13.479535753018677
13.479106838175182
13.47867829960303
13.478250136630294
13.477822348586475
13.47739493480248
13.476967894610702
13.476541227344915
13.47611493234035
13.475689008933632
13.475263456462818
13.474838274267364
13.474413461688178
13.473989018067503
13.473564942749057
13.473141235077932
13.472717894400617
13.472294920064984
13.47187231142034
13.471450067817338
13.471028188608026
13.470606673145852
13.470185520785652
13.469764730883586
13.469344302797241
13.468924235885558
13.468504529508866
13.4680851830288
13.467666195808434
13.46724756721213
13.46682929660567
13.466411383356133
13.46599382683199
13.465576626403049
13.465159781440432
13.464743291316642
13.464327155405512
13.463911373082173
13.463495943723142
13.463080866706227
13.46266614141058
13.462251767216692
13.46183774350632
13.461424069662602
13.461010745069942
13.46059776911409
13.460185141182084
13.459772860662275
13.459360926944328
13.458949339419181
13.458538097479096
13.458127200517604
13.457716647929571
13.457306439111097
13.45689657345961
13.456487050373802
13.456077869253644
13.455669029500394
13.45526053051658
13.454852371705984
13.454444552473705
13.454037072226052
13.45362993037064
13.453223126316319
13.452816659473209
13.452410529252678
13.45200473506736
13.451599276331114
13.451194152459076
13.450789362867594
13.45038490697428
13.44998078419799
13.449576993958779
13.449173535677978
13.448770408778122
13.44836761268299
13.447965146817575
13.44756301060808
13.447161203481961
13.446759724867857
13.446358574195656
13.445957750896428
13.445557254402452
13.44515708414722
13.444757239565456
13.444357720093032
13.443958525167062
13.44355965422583
13.443161106708814
13.442762882056696
13.44236497971135
13.441967399115814
13.441570139714317
13.441173200952267
13.440776582276253
13.440380283134036
13.43998430297455
13.4395886412479
13.439193297405355
13.438798270899353
13.43840356118348
13.438009167712512
13.437615089942312
13.437221327329995
13.436827879333757
13.436434745412965
13.43604192502813
13.435649417640906
13.435257222714096
13.434865339711623
13.434473768098572
13.434082507341147
13.43369155690669
13.433300916263645
13.432910584881617
13.432520562231318
13.43213084778459
13.43174144101439
13.431352341394787
13.43096354840096
13.430575061509218
13.430186880196961
13.429799003942703
13.429411432226065
13.429024164527755
13.428637200329598
13.428250539114508
13.427864180366505
13.427478123570666
13.427092368213197
13.426706913781373
13.426321759763555
13.425936905649197
13.425552350928807
13.425168095094007
13.424784137637467
13.424400478052936
13.424017115835218
13.42363405048023
13.423251281484923
13.422868808347307
13.42248663056645
13.422104747642505
13.42172315907667
13.421341864371186
13.420960863029356
13.420580154555534
13.42019973845512
13.41981961423454
13.419439781401282
13.419060239463885
13.418680987931904
13.418302026315924
13.4179233541276
13.417544970879577
13.417166876085549
13.416789069260236
13.416411549919394
13.416034317579763
13.41565737175914
13.415280711976322
13.414904337751139
13.414528248604412
13.414152444057963
13.413776923634677
13.413401686858371
13.413026733253938
13.412652062347231
13.412277673665095
13.411903566735408
13.411529741087014
13.411156196249758
13.41078293175448
13.41040994713301
13.410037241918172
13.409664815643735
13.409292667844506
13.40892079805624
13.408549205815667
13.408177890660507
13.407806852129438
13.407436089762133
13.407065603099204
13.40669539168226
13.406325455053858
13.405955792757513
13.405586404337729
13.405217289339934
13.404848447310513
13.404479877796845
13.404111580347225
13.40374355451092
13.403375799838118
13.40300831587997
13.402641102188591
13.402274158316995
13.401907483819175
13.401541078250029
13.401174941165431
13.400809072122144
13.400443470677883
13.4000781363913
13.399713068821965
13.399348267530389
13.398983732077962
13.39861946202705
13.398255456940912
13.39789171638373
13.397528239920593
13.397165027117497
13.396802077541393
13.396439390760074
13.39607696634229
13.395714803857684
13.395352902876791
13.394991262971082
13.39462988371288
13.394268764675429
13.393907905432869
13.393547305560228
13.39318696463343
13.392826882229285
13.392467057925499
13.392107491300644
13.391748181934203
13.391389129406525
13.391030333298819
13.39067179319322
13.390313508672689
13.389955479321106
13.389597704723185
13.38924018446452
13.38888291813159
13.388525905311722
13.388169145593121
13.38781263856484
13.387456383816808
13.387100380939795
13.386744629525447
13.38638912916625
13.386033879455555
13.38567887998754
13.385324130357269
13.384969630160622
13.38461537899435
13.384261376456013
13.383907622144056
13.383554115657734
13.383200856597137
13.382847844563216
13.38249507915774
13.382142559983325
13.381790286643378
13.381438258742174
13.381086475884821
13.380734937677225
13.380383643726114
13.380032593639065
13.37968178702445
13.379331223491478
13.378980902650149
13.378630824111314
13.378280987486606
13.377931392388465
13.377582038430178
13.377232925225801
13.376884052390212
13.376535419539074
13.376187026288909
13.375838872256955
13.375490957061334
13.375143280320884
13.374795841655288
13.37444864068504
13.37410167703135
13.373754950316293
13.3734084601627
13.373062206194186
13.372716188035158
13.3723704053108
13.372024857647093
13.371679544670775
13.371334466009369
13.370989621291193
13.370645010145308
13.37030063220156
13.369956487090583
13.369612574443765
13.369268893893242
13.368925445071959
13.36858222761359
13.36823924115259
13.36789648532416
13.36755395976428
13.367211664109663
13.366869597997797
13.36652776106692
13.366186152956015
13.365844773304818
13.36550362175383
13.365162697944285
13.36482200151814
13.364481532118143
13.36414128938776
13.363801272971191
13.363461482513392
13.36312191766004
13.362782578057567
13.362443463353145
13.362104573194618
13.361765907230648
13.36142746511056
13.361089246484449
13.360751251003101
13.360413478318076
13.360075928081583
13.35973859994664
13.359401493566908
13.359064608596817
13.358727944691502
13.358391501506771
13.358055278699233
13.357719275926133
13.357383492845452
13.357047929115879
13.356712584396822
13.356377458348385
13.35604255063136
13.355707860907277
13.35537338883834
13.355039134087443
13.354705096318236
13.354371275194987
13.35403767038274
13.353704281547154
13.35337110835463
13.353038150472253
13.35270540756778
13.352372879309673
13.352040565367078
13.351708465409809
13.351376579108374
13.351044906133982
13.350713446158508
13.35038219885446
13.350051163895104
13.34972034095433
13.349389729706708
13.349059329827483
13.348729140992592
13.34839916287862
13.348069395162817
13.34773983752311
13.347410489638087
13.347081351187022
13.346752421849798
13.34642370130701
13.346095189239891
13.345766885330338
13.345438789260912
13.345110900714797
13.344783219375872
13.344455744928643
13.344128477058268
13.343801415450558
13.343474559791979
13.343147909769648
13.3428214650713
13.342495225385337
13.342169190400805
13.341843359807365
13.341517733295355
13.341192310555726
13.340867091280069
13.340542075160613
13.34021726189022
13.339892651162383
13.33956824267124
13.33924403611153
13.338920031178652
13.338596227568617
13.338272624978055
13.337949223104225
13.337626021645026
13.337303020298945
13.336980218765122
13.3366576167433
13.33633521393384
13.336013010037712
13.335691004756521
13.33536919779247
13.335047588848376
13.33472617762766
13.334404963834391
13.334083947173179
13.3337631273493
13.3334425040686
13.333122077037558
13.332801845963223
13.332481810553269
13.332161970515964
13.33184232556018
13.331522875395363
13.331203619731594
13.330884558279502
13.330565690750358
13.330247016856001
13.329928536308843
13.329610248821929
13.329292154108845
13.328974251883809
13.328656541861584
13.328339023757543
13.32802169728764
13.327704562168407
13.32738761811695
13.327070864850972
13.32675430208873
13.326437929549085
13.326121746951443
13.325805754015821
13.325489950462757
13.325174336013427
13.324858910389532
13.324543673313341
13.32422862450772
13.323913763696074
13.323599090602404
13.323284604951235
13.322970306467685
13.322656194877418
13.32234226990668
13.32202853128225
13.321714978731505
13.321401611982317
13.321088430763156
13.32077543480306
13.320462623831585
13.320149997578852
13.319837555775543
13.319525298152866
13.31921322444261
13.318901334377083
13.318589627689157
13.31827810411224
13.317966763380298
13.317655605227804
13.317344629389808
13.317033835601901
13.316723223600176

13.31641279312131
13.31610254390248
13.315792475681414
13.315482588196376
13.315172881186163
13.314863354390107
13.314554007548052
13.314244840400391
13.313935852688042
13.31362704415245
13.313318414535575
13.31300996357992
13.312701691028492
13.312393596624847
13.312085680113027
13.311777941237635
13.311470379743767
13.311162995377034
13.310855787883572
13.310548757010059
13.310241902503625
13.309935224111982
13.309628721583314
13.30932239466633
13.309016243110241
13.30871026666477
13.30840446508015
13.308098838107133
13.307793385496947
13.307488107001351
13.307183002372604
13.306878071363455
13.306573313727165
13.306268729217502
13.30596431758871
13.30566007859555
13.305356011993267
13.305052117537628
13.30474839498486
13.304444844091716
13.304141464615414
13.303838256313675
13.303535218944736
13.303232352267262
13.302929656040474
13.30262713002403
13.302324773978114
13.302022587663354
13.301720570840905
13.301418723272377
13.301117044719852
13.300815534945935
13.300514193713674
13.300213020786622
13.299912015928774
13.299611178904636
13.299310509479174
13.299010007417841
13.298709672486543
13.29840950445169
13.298109503080118
13.297809668139184
13.297509999396679
13.297210496620878
13.296911159580526
13.296611988044813
13.296312981783421
13.29601414056649
13.295715464164603
13.295416952348846
13.295118604890721
13.294820421562221
13.29452240213579
13.294224546384322
13.293926854081183
13.29362932500019
13.293331958915614
13.293034755602172
13.292737714835049
13.292440836389877
13.29214412004274
13.29184756557018
13.291551172749157
13.291254941357124
13.29095887117194
13.290662961971949
13.29036721353592
13.290071625643062
13.289776198073048
13.289480930605958
13.289185823022354
13.288890875103231
13.288596086629981
13.2883014573845
13.288006987149073
13.287712675706443
13.287418522839785
13.287124528332711
13.286830691969264
13.286537013533913
13.28624349281159
13.285950129587608
13.285656923647755
13.285363874778225
13.285070982765655
13.284778247397085
13.284485668460018
13.284193245742353
13.283900979032433
13.283608868118993
13.283316912791229
13.283025112838747
13.282733468051562
13.282441978220117
13.28215064313528
13.281859462588342
13.281568436370982
13.281277564275324
13.2809868460939
13.28069628161965
13.280405870645936
13.280115612966533
13.279825508375621
13.279535556667792
13.279245757638057
13.278956111081825
13.278666616794933
13.278377274573597
13.278088084214453
13.277799045514561
13.277510158271353
13.27722142228268
13.276932837346807
13.276644403262376
13.276356119828462
13.276067986844518
13.275780004110404
13.27549217142637
13.275204488593074
13.274916955411577
13.274629571683315
13.274342337210138
13.27405525179429
13.273768315238387
13.273481527345451
13.273194887918917
13.272908396762585
13.27262205368066
13.272335858477712
13.272049810958714
13.271763910929055
13.271478158194446
13.27119255256107
13.2709070938354
13.270621781824362
13.270336616335252
13.270051597175726
13.269766724153845
13.269481997078037
13.269197415757114
13.268912980000282
13.268628689617106
13.268344544417518
13.26806054421186
13.26777668881083
13.267492978025508
13.267209411667341
13.266925989548154
13.266642711480134
13.266359577275876
13.266076586748293
13.265793739710714
13.265511035976806
13.265228475360635
13.264946057676593
13.264663782739486
13.26438165036445
13.264099660366997
13.263817812563031
13.263536106768774
13.263254542800833
13.262973120476197
13.262691839612167
13.26241070002647
13.262129701537129
13.261848843962563
13.261568127121555
13.261287550833199
13.261007114917026
13.26072681919283
13.260446663480842
13.260166647601592
13.25988677137598
13.25960703462528
13.259327437171082
13.259047978835362
13.258768659440424
13.258489478808926
13.258210436763886
13.25793153312866
13.257652767726945
13.257374140382808
13.257095650920636
13.256817299165181
13.256539084941531
13.25626100807512
13.255983068391723
13.255705265717458
13.255427599878786
13.255150070702513
13.254872678015778
13.254595421646046
13.254318301421172
13.254041317169284
13.253764468718883
13.253487755898801
13.253211178538226
13.252934736466644
13.252658429513872
13.252382257510112
13.252106220285848
13.251830317671937
13.251554549499524
13.251278915600103
13.251003415805528
13.250728049947941
13.25045281785983
13.250177719374008
13.249902754323603
13.249627922542102
13.249353223863295
13.249078658121284
13.248804225150536
13.248529924785794
13.248255756862156
13.247981721215037
13.247707817680169
13.24743404609359
13.247160406291702
13.246886898111173
13.24661352138903
13.246340275962595
13.246067161669515
13.245794178347763
13.245521325835606
13.245248603971655
13.244976012594815
13.24470355154429
13.24443122065965
13.244159019780723
13.243886948747681
13.243615007400983
13.243343195581428
13.243071513130111
13.24279995988842
13.242528535698076
13.242257240401093
13.241986073839817
13.241715035856854
13.241444126295148
13.241173344997966
13.24090269180884
13.240632166571611
13.240361769130448
13.240091499329813
13.239821357014467
13.239551342029465
13.239281454220169
13.239011693432252
13.23874205951166
13.238472552304673
13.238203171657839
13.237933917418006
13.237664789432342
13.23739578754828
13.237126911613585
13.23685816147628
13.2365895369847
13.23632103798748
13.236052664333538
13.235784415872073
13.235516292452614
13.235248293924942
13.234980420139133
13.234712670945585
13.234445046194946
13.23417754573816
13.233910169426498
13.233642917111462
13.233375788644878
13.233108783878839
13.232841902665742
13.232575144858254
13.232308510309343
13.232041998872212
13.231775610400426
13.231509344747758
13.231243201768311
13.230977181316447
13.230711283246805
13.230445507414336
13.230179853674224
13.22991432188197
13.229648911893317
13.229383623564338
13.229118456751323
13.228853411310885
13.228588487099891
13.228323683975473
13.228059001795081
13.227794440416371
13.227529999697326
13.2272656794962
13.227001479671499
13.226737400081987
13.226473440586755
13.226209601045097
13.225945881316624
13.22568228126119
13.225418800738936
13.225155439610267
13.224892197735839
13.224629074976608
13.22436607119376
13.224103186248762
13.223840420003352
13.223577772319524
13.223315243059558
13.223052832085951
13.222790539261517
13.222528364449296
13.222266307512593
13.222004368314993
13.221742546720332
13.221480842592682
13.22121925579643
13.22095778619617
13.220696433656778
13.220435198043386
13.220174079221364
13.219913077056384
13.21965219141432
13.21939142216134
13.219130769163861
13.21887023228854
13.218609811402294
13.218349506372302
13.218089317065978
13.217829243351012
13.217569285095342
13.217309442167123
13.217049714434804
13.216790101767058
13.216530604032831
13.216271221101293
13.216011952841882
13.215752799124267
13.215493759818381
13.215234834794376
13.214976023922711
13.21471732707401
13.214458744119204
13.214200274929432
13.213941919376124
13.213683677330893
13.21342554866563
13.213167533252479
13.2129096309638
13.21265184167221
13.21239416525056
13.21213660157195
13.211879150509704
13.211621811937421
13.211364585728886
13.211107471758167
13.210850469899565
13.210593580027586
13.210336802017007
13.210080135742842
13.2098235810803
13.209567137904884
13.209310806092285
13.209054585518452
13.208798476059563
13.208542477592037
13.2082865899925
13.20803081313784
13.207775146905172
13.207519591171826
13.20726414581538
13.20700881071362
13.20675358574461
13.206498470786586
13.206243465718039
13.205988570417695
13.205733784764503
13.205479108637643
13.205224541916508
13.204970084480722
13.204715736210153
13.204461496984866
13.204207366685198
13.20395334519164
13.203699432384969
13.203445628146158
13.203191932356415
13.202938344897152
13.202684865650033
13.202431494496906
13.202178231319884
13.201925076001256
13.201672028423573
13.201419088469558
13.201166256022217
13.200913530964716
13.20066091318046
13.20040840255309
13.200155998966439
13.19990370230458
13.199651512451775
13.199399429292535
13.19914745271155
13.198895582593769
13.198643818824307
13.198392161288528
13.198140609871988
13.197889164460499
13.197637824940017
13.197386591196771
13.197135463117176
13.196884440587873
13.196633523495668
13.196382711727649
13.196132005171064
13.195881403713374
13.195630907242291
13.195380515645668
13.195130228811637
13.194880046628477
13.19462996898472
13.194379995769067
13.194130126870482
13.19388036217806
13.193630701581165
13.193381144969337
13.193131692232313
13.192882343260065
13.192633097942755
13.192383956170714
13.192134917834542
13.191885982825
13.191637151033039
13.191388422349844
13.191139796666796
13.190891273875453
13.190642853867605
13.190394536535207
13.19014632177046
13.189898209465714
13.18965019951357
13.189402291806772
13.189154486238305
13.188906782701324
13.1886591810892
13.188411681295499
13.18816428321397
13.187916986738578
13.187669791763456
13.18742269818295
13.187175705891601
13.186928814784146
13.186682024755513

13.186435335700816
13.186188747515361
13.185942260094665
13.185695873334414
13.185449587130512
13.185203401379033
13.184957315976229
13.184711330818589
13.184465445802747
13.184219660825569
13.18397397578405
13.18372839057544
13.183482905097131
13.183237519246724
13.182992232922015
13.182747046020957
13.182501958441705
13.182256970082626
13.182012080842231
13.181767290619247
13.181522599312572
13.181278006821296
13.181033513044683
13.180789117882197
13.180544821233472
13.180300622998333
13.180056523076773
13.179812521369003
13.179568617775379
13.179324812196457
13.179081104532957
13.178837494685814
13.178593982556107
13.178350568045119
13.178107251054303
13.177864031485285
13.1776209092399
13.177377884220121
13.177134956328125
13.176892125466253
13.176649391537048
13.176406754443185
13.176164214087581
13.175921770373254
13.175679423203471
13.175437172481615
13.175195018111285
13.174952959996222
13.174710998040384
13.174469132147854
13.174227362222926
13.173985688170045
13.173744109893846
13.173502627299127
13.173261240290872
13.173019948774195
13.172778752654438
13.172537651837091
13.172296646227798
13.172055735732378
13.171814920256857
13.171574199707392
13.171333573990315
13.171093043012142
13.170852606679533
13.170612264899352
13.170372017578599
13.17013186462446
13.169891805944276
13.169651841445567
13.169411971036006
13.169172194623444
13.1689325121159
13.168692923421533
13.168453428448723
13.168214027105934
13.167974719301862
13.167735504945348
13.167496383945377
13.167257356211122
13.16701842165192
13.166779580177234
13.166540831696734
13.16630217612024
13.166063613357709
13.165825143319289
13.165586765915286
13.165348481056148
13.165110288652496
13.164872188615089
13.16463418085491
13.164396265283017
13.164158441810688
13.163920710349325
13.163683070810519
13.16344552310599
13.163208067147627
13.16297070284748
13.162733430117749
13.16249624887081
13.162259159019145
13.162022160475463
13.161785253152567
13.161548436963452
13.16131171182125
13.16107507763926
13.16083853433094
13.160602081809868
13.160365719989823
13.160129448784682
13.159893268108537
13.15965717787557
13.159421178000182
13.159185268396882
13.158949448980318
13.158713719665332
13.158478080366889
13.158242531000123
13.15800707148029
13.157771701722831
13.157536421643313
13.15730123115745
13.157066130181118
13.156831118630349
13.15659619642131
13.156361363470303
13.156126619693815
13.15589196500844
13.155657399330956
13.155422922578255
13.1551885346674
13.154954235515598
13.15472002504017
13.154485903158642
13.15425186978864
13.154017924847933
13.153784068254456
13.153550299926284
13.15331661978164
13.15308302773887
13.152849523716492
13.15261610763314
13.152382779407608
13.152149538958838
13.15191638620589
13.151683321067996
13.151450343464512
13.151217453314924
13.150984650538891
13.150751935056183
13.150519306786736
13.150286765650602
13.150054311568006
13.14982194445925
13.149589664244857
13.149357470845418
13.149125364181723
13.148893344174645
13.148661410745236
13.14842956381467
13.148197803304244
13.147966129135435
13.14773454122981
13.147503039509107
13.147271623895175
13.147040294310015
13.146809050675747
13.146577892914664
13.146346820949155
13.146115834701755
13.145884934095148
13.145654119052134
13.145423389495658
13.145192745348794
13.144962186534766
13.144731712976892
13.144501324598664
13.144271021323686
13.144040803075695
13.143810669778576
13.143580621356335
13.1433506577331
13.143120778833136
13.14289098458087
13.142661274900787
13.142431649717588
13.142202108956047
13.141972652541089
13.141743280397767
13.141513992451259
13.141284788626876
13.141055668850061
13.140826633046382
13.140597681141513
13.140368813061313
13.140140028731718
13.139911328078801
13.13968271102877
13.139454177507972
13.13922572744286
13.13899736076002
13.138769077386176
13.138540877248143
13.138312760272916
13.138084726387563
13.137856775519314
13.137628907595492
13.137401122543586
13.137173420291171
13.136945800765968
13.136718263895814
13.136490809608674
13.136263437832618
13.136036148495869
13.135808941526749
13.135581816853726
13.13535477440536
13.135127814110358
13.134900935897535
13.13467413969583
13.134447425434312
13.134220793042163
13.133994242448697
13.133767773583322
13.13354138637559
13.133315080755176
13.133088856651844
13.13286271399553
13.132636652716219
13.132410672744093
13.132184774009392
13.1319589564425
13.131733219973913
13.131507564534262
13.131281990054264
13.131056496464785
13.130831083696776
13.130605751681347
13.130380500349695
13.130155329633132
13.129930239463093
13.129705229771139
13.129480300488938
13.129255451548264
13.129030682881035
13.128805994419247
13.128581386095043
13.128356857840648
13.128132409588442
13.127908041270889
13.12768375282058
13.127459544170204
13.127235415252576
13.127011366000641
13.126787396347414
13.126563506226065
13.126339695569849
13.126115964312147
13.12589231238645
13.125668739726368
13.125445246265594
13.125221831937962
13.124998496677405
13.124775240417971
13.124552063093827
13.12432896463922
13.124105944988544
13.123883004076273
13.12366014183702
13.123437358205479
13.12321465311646
13.122992026504896
13.122769478305825
13.122547008454392
13.122324616885827
13.12210230353551
13.121880068338896
13.12165791123157
13.121435832149205
13.121213831027585
13.12099190780261
13.120770062410294
13.120548294786737
13.12032660486815
13.120104992590853
13.119883457891282
13.119662000705976
13.119440620971554
13.119219318624786
13.118998093602494
13.118776945841644
13.11855587527931
13.118334881852618
13.118113965498871
13.117893126155408
13.117672363759732
13.117451678249415
13.117231069562129
13.11701053763566
13.116790082407897
13.116569703816824
13.116349401800543
13.116129176297244
13.115909027245225
13.115688954582879
13.115468958248728
13.115249038181329
13.115029194319426
13.114809426601807
13.114589734967366
13.114370119355128
13.114150579704178
13.113931115953738
13.113711728043105
13.113492415911672
13.11327317949897
13.113054018744572
13.112834933588204
13.112615923969667
13.112396989828841
13.112178131105736
13.111959347740452
13.111740639673181
13.111522006844211
13.11130344919394
13.111084966662846
13.110866559191525
13.110648226720649
13.110429969191017
13.110211786543475
13.109993678719004
13.109775645658685
13.109557687303669
13.109339803595226
13.109121994474712
13.108904259883564
13.108686599763338
13.10846901405569
13.108251502702315
13.108034065645084
13.107816702825904
13.107599414186796
13.107382199669884
13.107165059217362
13.106947992771529
13.106731000274797
13.106514081669642
13.106297236898655
13.10608046590449
13.105863768629936
13.105647145017842
13.105430595011159
13.105214118552928
13.104997715586292
13.10478138605447
13.10456512990079
13.104348947068663
13.10413283750159
13.103916801143146
13.103700837937037
13.103484947827015
13.10326913075697
13.103053386670846
13.102837715512674
13.102622117226614
13.10240659175688
13.102191139047779
13.101975759043716
13.101760451689183
13.10154521692877
13.101330054707141
13.101114964969058
13.100899947659366
13.100685002722988
13.100470130104975
13.100255329750418
13.100040601604517
13.099825945612565
13.099611361719932
13.099396849872097
13.09918241001457
13.098968042093015
13.09875374605314
13.098539521840765
13.09832536940177
13.098111288682171
13.097897279627974
13.097683342185372
13.097469476300587
13.097255681919952
13.097041958989879
13.096828307456839
13.096614727267431
13.096401218368307
13.09618778070622
13.095974414227996
13.095761118880548
13.09554789461089
13.095334741366084
13.095121659093309
13.094908647739812
13.094695707252935
13.09448283758009
13.094270038668759
13.09405731046655
13.093844652921119
13.093632065980218
13.09341954959166
13.093207103703378
13.092994728263351
13.092782423219658
13.092570188520464
13.092358024113995
13.092145929948574
13.091933905972603
13.09172195213458
13.091510068383041
13.091298254666645
13.09108651093411
13.09087483713425
13.090663233215933
13.090451699128133
13.090240234819893
13.090028840240342
13.08981751533866
13.08960626006415
13.089395074366166
13.089183958194166
13.088972911497642
13.0887619342262
13.088551026329526
13.088340187757357
13.088129418459545
13.087918718386
13.08770808748669
13.087497525711694
13.087287033011158
13.087076609335293
13.086866254634412
13.08665596885887
13.08644575195915
13.086235603885752
13.086025524589289
13.085815514020455
13.085605572129992
13.08539569886874
13.085185894187614
13.084976158037602
13.084766490369752
13.0845568911352
13.084347360285172
13.084137897770962
13.08392850354392
13.083719177555478
13.08350991975716
13.083300730100548
13.083091608537302
13.082882555019157
13.08267356949793
13.0824646519255
13.082255802253814
13.082047020434919
13.081838306420925
13.081629660163987
13.081421081616375
13.081212570730395
13.081004127458467
13.080795751753044
13.080587443566673
13.080379202851969
13.080171029561626
13.079962923648393
13.07975488506511
13.079546913764677
13.079339009700064
13.07913117282433
13.078923403090588
13.078715700452012
13.078508064861891
13.078300496273531
13.078092994640363
13.077885559915826
13.077678192053483

13.077470891006962
13.077263656729915
13.077056489176128
13.076849388299397
13.076642354053646
13.076435386392818
13.076228485270958
13.07602165064216
13.075814882460605
13.075608180680533
13.075401545256247
13.075194976142148
13.074988473292658
13.07478203666232
13.074575666205698
13.07436936187746
13.07416312363232
13.073956951425064
13.073750845210572
13.073544804943742
13.073338830579587
13.073132922073151
13.072927079379587
13.07272130245407
13.072515591251868
13.072309945728325
13.072104365838815
13.071898851538814
13.071693402783842
13.071488019529502
13.071282701731466
13.07107744934545
13.070872262327248
13.070667140632716
13.070462084217803
13.070257093038489
13.07005216705082
13.069847306210917
13.069642510475
13.069437779799298
13.069233114140124
13.069028513453867
13.068823977696985
13.068619506825971
13.068415100797417
13.06821075956795
13.068006483094294
13.06780227133321
13.067598124241519
13.067394041776133
13.067190023894005
13.06698607055216
13.066782181707696
13.06657835731774
13.066374597339523
13.06617090173032
13.065967270447457
13.065763703448374
13.065560200690491
13.065356762131355
13.065153387728571
13.064950077439764
13.064746831222681
13.064543649035055
13.064340530834755
13.064137476579685
13.063934486227783
13.063731559737088
13.063528697065678
13.063325898171712
13.063123163013385
13.062920491548969
13.062717883736784
13.062515339535242
13.062312858902771
13.062110441797902
13.061908088179175
13.061705798005242
13.061503571234812
13.06130140782661
13.061099307739461
13.060897270932232
13.060695297363852
13.060493386993317
13.060291539779685
13.060089755682041
13.059888034659574
13.05968637667151
13.059484781677137
13.059283249635788
13.05908178050689
13.058880374249883
13.058679030824312
13.058477750189736
13.058276532305804
13.058075377132216
13.057874284628713
13.05767325475511
13.057472287471303
13.057271382737195
13.057070540512765
13.05686976075808
13.056669043433216
13.056468388498361
13.056267795913707
13.056067265639525
13.055866797636158
13.055666391863975
13.055466048283437
13.055265766855031
13.05506554753931
13.0548653902969
13.054665295088443
13.054465261874691
13.054265290616396
13.054065381274423
13.053865533809654
13.053665748183024
13.053466024355547
13.053266362288266
13.053066761942315
13.05286722327886
13.052667746259116
13.052468330844356
13.052268976995924
13.05206968467521
13.051870453843659
13.051671284462762
13.05147217649407
13.051273129899187
13.051074144639788
13.050875220677577
13.050676357974325
13.050477556491852
13.050278816192035
13.050080137036803
13.049881518988167
13.049682962008125
13.049484466058782
13.049286031102287
13.049087657100833
13.048889344016683
13.048691091812117
13.0484929004495
13.048294769891253
13.048096700099832
13.04789869103773
13.04770074266754
13.047502854951878
13.047305027853415
13.047107261334858
13.046909555358992
13.046711909888646
13.046514324886703
13.04631680031608
13.046119336139773
13.045921932320804
13.045724588822273
13.045527305607303
13.045330082639099
13.045132919880873
13.04493581729594
13.044738774847623
13.044541792499325
13.044344870214474
13.044148007956586
13.04395120568919
13.043754463375874
13.043557780980294
13.043361158466146
13.043164595797162
13.042968092937143
13.042771649849929
13.042575266499426
13.04237894284956
13.04218267886433
13.041986474507798
13.041790329744035
13.041594244537187
13.041398218851452
13.041202252651052
13.041006345900305
13.040810498563516
13.040614710605102
13.040418981989484
13.040223312681151
13.040027702644629
13.039832151844495
13.039636660245394
13.03944122781199
13.039245854509016
13.039050540301252
13.038855285153506
13.038660089030659
13.038464951897629
13.038269873719363
13.038074854460904
13.037879894087295
13.03768499256363
13.037490149855097
13.03729536592688
13.037100640744214
13.03690597427244
13.036711366476855
13.036516817322871
13.036322326775926
13.036127894801501
13.035933521365125
13.035739206432368
13.035544949968875
13.035350751940296
13.035156612312354
13.03496253105081
13.034768508121473
13.034574543490208
13.034380637122892
13.03418678898548
13.033992999043978
13.033799267264403
13.033605593612856
13.033411978055444
13.03321842055836
13.03302492108781
13.032831479610067
13.032638096091427
13.032444770498248
13.03225150279694
13.032058292953943
13.031865140935736
13.031672046708858
13.031479010239881
13.031286031495432
13.031093110442178
13.030900247046823
13.030707441276125
13.030514693096888
13.030322002475954
13.0301293693802
13.029936793776569
13.02974427563202
13.02955181491358
13.02935941158832
13.029167065623328
13.028974776985766
13.02878254564282
13.028590371561716
13.02839825470975
13.028206195054242
13.028014192562537
13.027822247202055
13.027630358940252
13.027438527744609
13.027246753582677
13.027055036422013
13.026863376230263
13.026671772975062
13.02648022662414
13.026288737145228
13.02609730450612
13.02590592867466
13.025714609618703
13.025523347306178
13.02533214170504
13.025140992783298
13.024949900508977
13.024758864850156
13.024567885774978
13.024376963251594
13.024186097248219
13.023995287733108
13.023804534674538
13.023613838040841
13.023423197800396
13.02323261392162
13.02304208637295
13.022851615122889
13.022661200139973
13.02247084139278
13.022280538849932
13.022090292480067
13.021900102251893
13.021709968134159
13.021519890095625
13.021329868105127
13.021139902131509
13.02094999214367
13.02076013811056
13.020570340001143
13.02038059778445
13.020190911429538
13.020001280905477
13.019811706181446
13.019622187226602
13.019432724010148
13.019243316501356
13.019053964669524
13.018864668483975
13.018675427914086
13.018486242929267
13.018297113498964
13.018108039592681
13.017919021179939
13.017730058230297
13.017541150713374
13.017352298598816
13.017163501856288
13.016974760455529
13.016786074366296
13.016597443558373
13.016408868001617
13.01622034766589
13.016031882521116
13.015843472537227
13.015655117684219
13.015466817932142
13.015278573251027
13.015090383610987
13.01490224898218
13.014714169334752
13.01452614463894
13.014338174864982
13.01415025998318
13.013962399963868
13.013774594777393
13.013586844394151
13.013399148784593
13.013211507919197
13.01302392176847
13.012836390302965
13.012648913493255
13.012461491309981
13.012274123723788
13.012086810705377
13.011899552225485
13.011712348254873
13.01152519876435
13.011338103724752
13.011151063106977
13.010964076881914
13.01077714502051
13.01059026749379
13.010403444272729
13.010216675328426
13.010029960631941
13.009843300154413
13.009656693867015
13.009470141740954
13.009283643747452
13.009097199857765
13.008910810043243
13.0087244742752
13.008538192525027
13.008351964764126
13.008165790963941
13.007979671095983
13.007793605131736
13.007607593042769
13.007421634800668
13.00723573037707
13.00704987974361
13.006864082871987
13.006678339733948
13.00649265030122
13.006307014545634
13.006121432438997
13.005935903953182
13.005750429060095
13.00556500773166
13.005379639939836
13.005194325656642
13.00500906485411
13.004823857504313
13.004638703579335
13.004453603051337
13.00426855589247
13.004083562074968
13.003898621571034
13.003713734352964
13.003528900393055
13.003344119663653
13.003159392137126
13.002974717785879
13.002790096582356
13.002605528499018
13.002421013508386
13.002236551582994
13.002052142695396
13.001867786818229
13.00168348392411
13.0014992339857
13.001315036975722
13.00113089286691
13.000946801632024
13.000762763243875
13.000578777675285
13.000394844899128
13.000210964888302
13.00002713761573
12.999843363054389
12.99965964117726
12.999475971957386
12.999292355367814
12.999108791381635
12.998925279971987
12.998741821112011
12.9985584147749
12.998375060933887
12.998191759562205
12.998008510633138
12.997825314120002
12.997642169996157
12.997459078234955
12.997276038809826
12.997093051694206
12.996910116861569
12.996727234285402
12.996544403939263
12.996361625796691
12.99617889983131
12.99599622601673
12.995813604326617
12.995631034734656
12.995448517214566
12.995266051740101
12.995083638285047
12.994901276823214
12.994718967328438
12.994536709774604
12.99435450413561
12.994172350385396
12.993990248497918
12.993808198447173
12.993626200207201
12.993444253752049
12.993262359055798
12.993080516092578
12.992898724836506
12.992716985261799
12.992535297342652
12.992353661053267
12.99217207636796
12.991990543260988
12.991809061706714
12.991627631679448
12.991446253153615
12.991264926103618
12.991083650503882
12.990902426328928
12.990721253553206
12.990540132151272
12.990359062097683
12.990178043367049
12.98999707593397
12.989816159773111
12.989635294859125
12.989454481166744
12.9892737186707
12.989093007345742
12.988912347166693
12.988731738108344
12.988551180145581
12.988370673253261
12.988190217406293
12.988009812579632
12.987829458748237
12.987649155887091
12.987468903971232
12.987288702975718
12.987108552875606
12.986928453646016
12.98674840526209
12.986568407699002
12.986388460931913
12.98620856493607
12.986028719686722
12.985848925159136
12.985669181328626
12.985489488170522
12.985309845660188
12.985130253772997
12.984950712484387
12.984771221769789
12.984591781604687
12.98441239196456
12.984233052824953
12.98405376416142
12.983874525949528
12.983695338164898
12.98351620078317
12.983337113780001
12.983158077131078
12.982979090812133
12.982800154798893
12.982621269067144
12.982442433592697
12.982263648351339
12.982084913318957
12.98190622847143
12.981727593784655
12.98154900923457
12.981370474797124
12.981191990448329
12.981013556164166
12.980835171920706
12.980656837694001
12.98047855346015
12.980300319195274
12.980122134875515
12.979944000477039
12.979765915976058
12.979587881348793
12.979409896571502
12.97923196162045
12.97905407647194
12.978876241102318
12.978698455487924
12.978520719605163
12.978343033430416
12.978165396940113
12.97798781011074
12.977810272918777
12.977632785340724
12.977455347353123
12.977277958932527
12.977100620055543
12.976923330698764
12.976746090838837
12.976568900452438
12.97639175951625
12.97621466800698
12.97603762590136
12.975860633176204
12.975683689808232
12.97550679577432
12.975329951051279
12.975153155615981
12.974976409445325
12.974799712516223
12.974623064805623
12.974446466290463
12.974269916947765
12.974093416754547
12.973916965687826
12.973740563724675
12.973564210842213
12.97338790701751
12.973211652227738
12.973035446450043
12.972859289661624
12.97268318183969
12.972507122961478
12.972331113004259
12.972155151945307
12.971979239761927
12.971803376431485
12.9716275619313
12.971451796238773
12.971276079331329
12.97110041118637
12.970924791781366
12.970749221093785
12.970573699101156
12.97039822578098
12.970222801110816
12.970047425068252
12.969872097630867
12.96969681877629
12.969521588482168
12.969346406726176
12.969171273486001
12.968996188739357
12.968821152463995
12.96864616463768
12.968471225238181
12.968296334243318
12.96812149163093
12.967946697378878
12.967771951465028
12.967597253867293

12.967422604563609
12.967248003531912
12.967073450750172
12.966898946196398
12.966724489848602
12.966550081684835
12.966375721683152
12.966201409821645
12.966027146078432
12.965852930431634
12.96567876285941
12.965504643339951
12.965330571851446
12.96515654837214
12.964982572880253
12.964808645354074
12.964634765771894
12.964460934112013
12.964287150352787
12.964113414472566
12.963939726449745
12.963766086262705
12.96359249388989
12.963418949309743
12.963245452500743
12.963072003441377
12.962898602110162
12.962725248485647
12.962551942546364
12.962378684270924
12.962205473637919
12.962032310625965
12.961859195213734
12.961686127379876
12.961513107103084
12.961340134362077
12.961167209135589
12.960994331402386
12.960821501141227
12.960648718330933
12.960475982950303
12.960303294978194
12.960130654393478
12.959958061175023
12.959785515301759
12.959613016752584
12.959440565506483
12.9592681615424
12.959095804839352
12.958923495376334
12.95875123313239
12.95857901808658
12.95840685021799
12.95823472950569
12.958062655928822
12.957890629466531
12.957718650097961
12.95754671780231
12.957374832558783
12.957202994346599
12.957031203145004
12.956859458933264
12.956687761690672
12.956516111396537
12.956344508030176
12.956172951570949
12.956001441998229
12.955829979291405
12.955658563429873
12.955487194393097
12.955315872160494
12.955144596711566
12.954973368025794
12.95480218608268
12.95463105086179
12.954459962342638
12.954288920504835
12.954117925327955
12.953946976791633
12.95377607487548
12.953605219559163
12.953434410822359
12.953263648644764
12.9530929330061
12.952922263886087
12.952751641264493
12.952581065121096
12.95241053543568
12.95224005218807
12.952069615358093
12.951899224925608
12.951728880870503
12.951558583172652
12.951388331811996
12.951218126768437
12.95104796802196
12.9508778555525
12.950707789340086
12.950537769364717
12.950367795606423
12.950197868045267
12.950027986661299
12.949858151434622
12.949688362345343
12.949518619373606
12.949348922499542
12.949179271703308
12.94900966696513
12.948840108265166
12.948670595583678
12.948501128900888
12.948331708197076
12.948162333452514
12.947993004647508
12.94782372176237
12.947654484777448
12.94748529367311
12.947316148429708
12.947147049027668
12.946977995447385
12.94680898766929
12.946640025673833
12.946471109441521
12.946302238952795
12.946133414188191
12.945964635128247
12.945795901753492
12.945627214044478
12.945458571981819
12.945289975546087
12.945121424717922
12.944952919477965
12.944784459806854
12.944616045685283
12.944447677093931
12.944279354013519
12.944111076424786
12.943942844308458
12.94377465764532
12.943606516416155
12.943438420601765
12.943270370182965
12.943102365140598
12.942934405455526
12.942766491108621
12.942598622080784
12.942430798352916
12.942263019905944
12.942095286720836
12.941927598778532
12.94175995606005
12.94159235854635
12.941424806218475
12.941257299057476
12.941089837044363
12.940922420160243
12.94075504838621
12.940587721703348
12.940420440092796
12.940253203535702
12.94008601201322
12.939918865506531
12.939751763996826
12.939584707465308
12.93941769589323
12.939250729261833
12.939083807552379
12.93891693074614
12.938750098824443
12.938583311768587
12.938416569559902
12.938249872179759
12.938083219609503
12.937916611830538
12.937750048824268
12.937583530572109
12.937417057055498
12.937250628255894
12.937084244154754
12.936917904733592
12.936751609973896
12.936585359857196
12.93641915436503
12.93625299347895
12.93608687718053
12.935920805451378
12.93575477827309
12.935588795627277
12.935422857495595
12.9352569638597
12.93509111470127
12.934925310001985
12.93475954974356
12.93459383390772
12.9344281624762
12.934262535430774
12.93409695275319
12.933931414425263
12.93376592042879
12.933600470745596
12.93343506535751
12.933269704246413
12.933104387394154
12.932939114782634
12.932773886393756
12.93260870220945
12.932443562211633
12.932278466382282
12.932113414703355
12.931948407156847
12.931783443724749
12.931618524389092
12.931453649131917
12.931288817935254
12.931124030781183
12.930959287651785
12.93079458852917
12.930629933395435
12.93046532223273
12.930300755023191
12.930136231748978
12.929971752392278
12.929807316935296
12.929642925360211
12.929478577649288
12.92931427378474
12.929150013748842
12.92898579752385
12.92882162509209
12.928657496435827
12.928493411537396
12.928329370379144
12.928165372943415
12.928001419212567
12.927837509169004
12.927673642795103
12.927509820073302
12.927346040986011
12.927182305515686
12.927018613644774
12.926854965355767
12.926691360631166
12.926527799453451
12.926364281805142
12.926200807668803
12.926037377026972
12.925873989862223
12.925710646157134
12.925547345894293
12.925384089056331
12.925220875625866
12.925057705585557
12.92489457891805
12.924731495606022
12.924568455632139
12.924405458979162
12.924242505629744
12.924079595566665
12.923916728772666
12.923753905230491
12.923591124922936
12.923428387832788
12.923265693942854
12.923103043235969
12.922940435694965
12.922777871302682
12.922615350042015
12.922452871895821
12.922290436847014
12.922128044878487
12.921965695973189
12.921803390114054
12.92164112728403
12.921478907466083
12.921316730643209
12.921154596798402
12.920992505914686
12.920830457975091
12.920668452962637
12.920506490860413
12.92034457165146
12.920182695318882
12.920020861845781
12.919859071215258
12.919697323410457
12.919535618414512
12.919373956210594
12.919212336781863
12.919050760111508
12.918889226182733
12.91872773497875
12.918566286482793
12.918404880678095
12.918243517547925
12.918082197075545
12.917920919244258
12.917759684037346
12.917598491438111
12.917437341429915
12.917276233996079
12.917115169119965
12.916954146784935
12.916793166974385
12.916632229671697
12.916471334860296
12.916310482523603
12.916149672645053
12.915988905208103
12.915828180196218
12.915667497592889
12.915506857381592
12.915346259545842
12.91518570406917
12.915025190935099
12.914864720127197
12.914704291629008
12.914543905424114
12.914383561496109
12.914223259828583
12.914063000405164
12.913902783209496
12.913742608225197
12.913582475435945
12.913422384825399
12.913262336377258
12.913102330075194
12.912942365902946
12.912782443844234
12.912622563882776
12.912462726002344
12.912302930186708
12.91214317641963
12.9119834646849
12.911823794966342
12.911664167247757
12.911504581512993
12.911345037745878
12.911185535930265
12.911026076050048
12.910866658089098
12.910707282031307
12.910547947860602
12.910388655560887
12.910229405116114
12.910070196510217
12.909911029727178
12.909751904750957
12.909592821565557
12.909433780154972
12.909274780503205
12.9091158225943
12.90895690641229
12.90879803194123
12.90863919916518
12.90848040806824
12.908321658634472
12.908162950847995
12.908004284692936
12.907845660153418
12.907687077213565
12.90752853585756
12.907370036069562
12.907211577833749
12.90705316113432
12.906894785955465
12.906736452281423
12.906578160096414
12.906419909384688
12.9062617001305
12.90610353231812
12.905945405931828
12.905787320955916
12.9056292773747
12.90547127517249
12.905313314333624
12.905155394842438
12.904997516683295
12.904839679840558
12.904681884298629
12.904524130041874
12.904366417054716
12.904208745321561
12.904051114826856
12.903893525555022
12.903735977490538
12.903578470617857
12.903421004921457
12.903263580385847
12.903106196995516
12.902948854734973
12.90279155358877
12.902634293541427
12.902477074577519
12.902319896681576
12.902162759838205
12.902005664031975
12.90184860924751
12.9016915954694
12.90153462268229
12.9013776908708
12.90122080001958
12.901063950113311
12.900907141136647
12.900750373074276
12.900593645910897
12.900436959631213
12.900280314219957
12.900123709661848
12.899967145941629
12.899810623044077
12.899654140953933
12.899497699655994
12.899341299135047
12.899184939375889
12.89902862036334
12.898872342082221
12.898716104517394
12.898559907653674
12.898403751475936
12.898247635969067
12.89809156111793
12.897935526907428
12.897779533322467
12.897623580347995
12.89746766796891
12.897311796170152
12.897155964936681
12.897000174253483
12.896844424105515
12.896688714477769
12.896533045355257
12.896377416722963
12.896221828565926
12.896066280869189
12.89591077361779
12.895755306796769
12.89559988039123
12.895444494386211
12.89528914876683
12.895133843518186
12.894978578625391
12.894823354073562
12.894668169847838
12.894513025933376
12.894357922315324
12.894202858978849
12.894047835909141
12.893892853091385
12.893737910510778
12.893583008152564
12.893428146001927
12.893273324044129
12.893118542264418
12.892963800648033
12.892809099180258
12.892654437846375
12.892499816631666
12.892345235521441
12.892190694501005
12.892036193555704
12.891881732670853
12.891727311831787
12.891572931023894
12.89141859023253
12.89126428944306
12.891110028640888
12.89095580781142
12.890801626940053
12.890647486012222
12.89049338501334
12.89033932392886
12.890185302744257
12.890031321444976
12.889877380016499
12.889723478444308
12.889569616713915
12.889415794810805
12.889262012720515
12.889108270428558
12.888954567920502
12.888800905181856
12.888647282198228
12.888493698955163
12.888340155438241
12.888186651633076
12.888033187525243
12.88787976310039
12.88772637834412
12.88757303324206
12.887419727779893
12.887266461943224
12.88711323571776
12.886960049089163
12.88680690204312
12.88665379456533
12.886500726641513
12.886347698257374
12.886194709398637
12.886041760051043
12.88588885020037
12.885735979832356
12.885583148932756
12.88543035748738
12.885277605482012
12.885124892902445
12.88497221973448
12.884819585963978
12.884666991576726
12.88451443655858
12.884361920895426
12.884209444573086
12.884057007577445
12.883904609894389
12.883752251509797
12.883599932409597
12.88344765257969
12.883295412006001
12.88314321067446
12.882991048571014
12.882838925681611
12.882686841992221
12.88253479748881
12.882382792157378
12.8822308259839
12.882078898954392
12.88192701105486
12.881775162271332
12.881623352589834
12.881471581996433
12.881319850477151
12.881168158018061
12.881016504605252
12.880864890224785
12.880713314862767
12.8805617785053
12.880410281138492
12.880258822748468
12.88010740332135
12.879956022843299
12.879804681300449
12.879653378678967
12.879502114965023
12.879350890144805
12.879199704204494
12.879048557130307
12.878897448908429
12.878746379525104
12.878595348966527
12.878444357218976
12.878293404268682
12.87814249010191
12.877991614704909
12.877840778063975
12.87768998016539
12.877539220995445
12.877388500540462
12.877237818786732
12.8770871757206
12.876936571328388
12.876786005596449
12.876635478511131
12.876484990058804
12.876334540225827
12.876184128998604
12.876033756363508
12.875883422306936
12.87573312681532
12.875582869875057
12.875432651472588
12.87528247159435
12.875132330226787
12.874982227356364
12.874832162969538
12.874682137052792
12.874532149592598

12.874382200575466
12.874232289987884
12.874082417816386
12.87393258404748
12.873782788667702
12.873633031663571
12.873483313021675
12.873333632728542
12.873183990770755
12.873034387134892
12.872884821807524
12.872735294775268
12.872585806024714
12.87243635554248
12.872286943315178
12.872137569329471
12.871988233571956
12.871838936029322
12.871689676688213
12.871540455535287
12.871391272557245
12.87124212774076
12.87109302107252
12.870943952539225
12.870794922127615
12.87064592982439
12.870496975616295
12.870348059490064
12.870199181432438
12.870050341430197
12.869901539470076
12.869752775538869
12.869604049623371
12.869455361710363
12.869306711786638
12.869158099839032
12.869009525854336
12.868860989819419
12.868712491721075
12.86856403154618
12.868415609281577
12.868267224914126
12.868118878430712
12.867970569818212
12.867822299063521
12.867674066153535
12.867525871075145
12.867377713815292
12.86722959436089
12.867081512698885
12.86693346881619
12.866785462699799
12.866637494336622
12.86648956371368
12.866341670817908
12.866193815636318
12.866045998155888
12.865898218363636
12.86575047624656
12.86560277179169
12.865455104986056
12.865307475816678
12.865159884270621
12.865012330334933
12.864864813996675
12.864717335242915
12.864569894060752
12.864422490437248
12.864275124359505
12.864127795814653
12.863980504789783
12.86383325127201
12.86368603524849
12.863538856706354
12.86339171563273
12.863244612014787
12.863097545839695
12.862950517094625
12.862803525766749
12.86265657184327
12.862509655311372
12.862362776158266
12.862215934371163
12.862069129937284
12.861922362843881
12.861775633078164
12.861628940627408
12.861482285478838
12.861335667619738
12.86118908703738
12.861042543719032
12.860896037651992
12.860749568823556
12.860603137221025
12.860456742831717
12.86031038564296
12.860164065642065
12.860017782816383
12.859871537153264
12.859725328640039
12.859579157264092
12.859433023012787
12.859286925873485
12.859140865833607
12.858994842880522
12.858848857001643
12.858702908184371
12.858556996416128
12.858411121684345
12.858265283976452
12.858119483279891
12.85797371958212
12.857827992870591
12.857682303132774
12.857536650356135
12.857391034528161
12.857245455636356
12.857099913668186
12.856954408611193
12.856808940452876
12.856663509180752
12.856518114782359
12.856372757245222
12.856227436556908
12.85608215270494
12.855936905676923
12.855791695460399
12.855646522042925
12.855501385412133
12.85535628555557
12.855211222460872
12.855066196115635
12.85492120650747
12.854776253624
12.85463133745286
12.854486457981702
12.854341615198152
12.854196809089881
12.854052039644543
12.853907306849807
12.853762610693362
12.853617951162887
12.853473328246073
12.853328741930621
12.85318419220424
12.853039679054655
12.852895202469583
12.852750762436754
12.852606358943905
12.8524619919788
12.85231766152917
12.8521733675828
12.852029110127445
12.851884889150888
12.851740704640907
12.851596556585303
12.85145244497188
12.851308369788427
12.851164331022773
12.851020328662738
12.85087636269616
12.85073243311086
12.850588539894696
12.850444683035526
12.85030086252119
12.850157078339567
12.850013330478536
12.849869618925979
12.84972594366978
12.849582304697833
12.849438701998057
12.84929513555835
12.849151605366638
12.849008111410848
12.848864653678918
12.848721232158793
12.848577846838404
12.848434497705723
12.848291184748708
12.848147907955328
12.848004667313571
12.847861462811412
12.847718294436849
12.847575162177879
12.847432066022533
12.847289005958785
12.847145981974691
12.847002994058261
12.846860042197541
12.846717126380579
12.846574246595406
12.846431402830108
12.846288595072734
12.846145823311357
12.84600308753406
12.845860387728933
12.845717723884075
12.845575095987568
12.845432504027546
12.845289947992107
12.845147427869389
12.845004943647504
12.844862495314596
12.84472008285881
12.844577706268318
12.844435365531249
12.844293060635783
12.844150791570094
12.844008558322354
12.843866360880755
12.843724199233492
12.843582073368767
12.843439983274779
12.843297928939762
12.84315591035192
12.843013927499497
12.842871980370711
12.842730068953824
12.842588193237077
12.842446353208722
12.842304548857031
12.842162780170286
12.842021047136747
12.841879349744701
12.841737687982453
12.841596061838292
12.841454471300525
12.841312916357458
12.841171396997423
12.841029913208745
12.840888464979756
12.840747052298791
12.840605675154205
12.840464333534348
12.840323027427582
12.84018175682227
12.840040521706799
12.839899322069535
12.83975815789889
12.839617029183222
12.839475935910967
12.839334878070513
12.839193855650294
12.83905286863872
12.838911917024218
12.83877100079523
12.8386301199402
12.838489274447577
12.838348464305804
12.838207689503372
12.838066950028729
12.837926245870353
12.837785577016714
12.83764494345634
12.837504345177697
12.837363782169295
12.837223254419648
12.837082761917268
12.836942304650671
12.83680188260842
12.836661495779003
12.836521144151003
12.836380827712947
12.836240546453398
12.836100300360924
12.835960089424077
12.835819913631463
12.835679772971643
12.835539667433206
12.835399597004761
12.8352595616749
12.835119561432231
12.834979596265374
12.834839666162955
12.8346997711136
12.834559911105936
12.834420086128615
12.834280296170292
12.834140541219597
12.834000821265205
12.833861136295802
12.833721486300032
12.833581871266583
12.833442291184165
12.833302746041445
12.83316323582713
12.83302376052993
12.832884320138556
12.832744914641737
12.83260554402818
12.832466208286641
12.83232690740583
12.832187641374519
12.832048410181452
12.831909213815365
12.831770052265053
12.83163092551928
12.831491833566796
12.831352776396427
12.831213753996924
12.831074766357112
12.830935813465784
12.83079689531173
12.830658011883791
12.830519163170782
12.830380349161523
12.83024156984485
12.830102825209606
12.82996411524464
12.829825439938805
12.829686799280946
12.829548193259946
12.829409621864654
12.829271085083981
12.829132582906789
12.828994115321974
12.828855682318428
12.828717283885064
12.828578920010772
12.828440590684492
12.828302295895115
12.828164035631602
12.828025809882865
12.827887618637847
12.827749461885501
12.827611339614766
12.827473251814613
12.827335198474012
12.827197179581912
12.827059195127312
12.826921245099175
12.826783329486508
12.826645448278297
12.826507601463545
12.826369789031256
12.826232010970452
12.826094267270147
12.825956557919358
12.825818882907129
12.825681242222508
12.8255436358545
12.825406063792197
12.825268526024628
12.82513102254088
12.824993553329994
12.824856118381053
12.824718717683146
12.824581351225353
12.824444018996761
12.824306720986483
12.824169457183611
12.824032227577254
12.823895032156527
12.82375787091056
12.823620743828473
12.823483650899405
12.823346592112504
12.823209567456901
12.823072576921753
12.822935620496212
12.822798698169455
12.822661809930642
12.822524955768948
12.82238813567355
12.822251349633657
12.822114597638443
12.821977879677107
12.821841195738857
12.82170454581291
12.821567929888468
12.821431347954775
12.821294800001041
12.821158286016505
12.821021805990407
12.820885359911996
12.820748947770532
12.820612569555237
12.820476225255417
12.820339914860321
12.820203638359223
12.820067395741413
12.819931186996168
12.81979501211278
12.819658871080549
12.819522763888783
12.8193866905268
12.819250650983893
12.819114645249401
12.818978673312635
12.818842735162953
12.818706830789663
12.818570960182122
12.818435123329689
12.818299320221707
12.818163550847547
12.818027815196563
12.817892113258141
12.817756445021644
12.817620810476466
12.817485209611995
12.817349642417643
12.817214108882787
12.817078608996821
12.816943142749201
12.816807710129316
12.816672311126586
12.816536945730457
12.816401613930347
12.816266315715719
12.816131051075995
12.815995820000637
12.815860622479104
12.815725458500847
12.81559032805536
12.815455231132086
12.815320167720527
12.815185137810156
12.815050141390465
12.814915178450963
12.814780248981133
12.814645352970494
12.81451049040857
12.81437566128485
12.81424086558887
12.814106103310177
12.813971374438282
12.813836678962733
12.813702016873084
12.813567388158878
12.813432792809687
12.81329823081505
12.813163702164543
12.813029206847752
12.812894744854242
12.8127603161736
12.812625920795421
12.812491558709292
12.812357229904828
12.812222934371615
12.812088672099282
12.811954443077441
12.811820247295714
12.811686084743725
12.811551955411103
12.811417859287507
12.81128379636256
12.811149766625924
12.811015770067248
12.81088180667619
12.810747876442422
12.81061397935562
12.810480115405435
12.810346284581582
12.81021248687372
12.810078722271559
12.809944990764802
12.809811292343134
12.809677626996274

12.80954399471393
12.809410395485825
12.809276829301684
12.809143296151243
12.809009796024219
12.808876328910365
12.808742894799424
12.80860949368115
12.808476125545297
12.808342790381625
12.808209488179903
12.808076218929898
12.8079429826214
12.807809779244181
12.807676608788027
12.80754347124274
12.80741036659811
12.807277294843948
12.80714425597005
12.80701124996624
12.806878276822344
12.806745336528174
12.806612429073558
12.806479554448337
12.806346712642366
12.806213903645459
12.806081127447493
12.80594838403831
12.805815673407768
12.805682995545745
12.805550350442106
12.80541773808672
12.805285158469488
12.80515261158027
12.805020097408981
12.804887615945509
12.804755167179746
12.80462275110162
12.804490367701016
12.80435801696789
12.80422569889213
12.804093413463672
12.803961160672454
12.803828940508401
12.80369675296149
12.803564598021637
12.803432475678793
12.803300385922936
12.80316832874402
12.803036304132005
12.802904312076883
12.802772352568628
12.802640425597202
12.802508531152611
12.802376669224847
12.80224483980391
12.802113042879807
12.801981278442527
12.80184954648211
12.801717846988554
12.801586179951894
12.801454545362159
12.801322943209374
12.801191373483578
12.801059836174824
12.800928331273159
12.800796858768631
12.800665418651295
12.800534010911225
12.800402635538495
12.800271292523162
12.8001399818553
12.80000870352501
12.799877457522378
12.79974624383749
12.799615062460445
12.799483913381346
12.799352796590309
12.799221712077436
12.799090659832853
12.79895963984668
12.798828652109044
12.798697696610075
12.798566773339921
12.798435882288711
12.798305023446597
12.79817419680373
12.79804340235028
12.797912640076376
12.797781909972231
12.79765121202798
12.797520546233814
12.797389912579925
12.797259311056466
12.797128741653658
12.79699820436169
12.796867699170758
12.796737226071063
12.796606785052825
12.79647637610626
12.796345999221584
12.796215654389018
12.796085341598802
12.795955060841152
12.79582481210633
12.795694595384568
12.795564410666113
12.795434257941222
12.795304137200153
12.79517404843316
12.795043991630529
12.79491396678252
12.794783973879415
12.794654012911495
12.794524083869051
12.794394186742354
12.794264321521743
12.794134488197475
12.79400468675988
12.79387491719925
12.793745179505924
12.793615473670206
12.793485799682431
12.793356157532921
12.793226547212011
12.793096968710037
12.792967422017345
12.79283790712429
12.792708424021221
12.792578972698482
12.79244955314646
12.792320165355507
12.792190809315995
12.792061485018298
12.791932192452805
12.7918029316099
12.791673702479963
12.791544505053393
12.791415339320608
12.791286205271993
12.791157102897962
12.791028032188912
12.790898993135283
12.790769985727497
12.790641009955976
12.790512065811148
12.790383153283448
12.790254272363333
12.790125423041232
12.789996605307596
12.789867819152889
12.78973906456757
12.789610341542092
12.789481650066936
12.789352990132564
12.78922436172946
12.789095764848119
12.78896719947899
12.78883866561261
12.788710163239443
12.788581692350007
12.788453252934794
12.788324844984324
12.788196468489106
12.788068123439661
12.787939809826511
12.787811527640189
12.787683276871203
12.787555057510122
12.787426869547476
12.787298712973813
12.787170587779668
12.787042493955607
12.786914431492185
12.786786400379981
12.786658400609547
12.78653043217145
12.786402495056292
12.78627458925463
12.78614671475706
12.786018871554173
12.785891059636569
12.785763278994837
12.785635529619583
12.785507811501423
12.785380124630956
12.785252468998813
12.785124844595623
12.78499725141198
12.784869689438548
12.784742158665937
12.784614659084797
12.784487190685773
12.784359753459515
12.784232347396674
12.784104972487903
12.783977628723862
12.783850316095226
12.783723034592654
12.783595784206824
12.78346856492842
12.783341376748115
12.783214219656612
12.783087093644596
12.782959998702763
12.782832934821801
12.782705901992424
12.782578900205362
12.782451929451305
12.78232498972097
12.782198081005086
12.782071203294379
12.78194435657958
12.781817540851435
12.781690756100666
12.781564002318023
12.781437279494265
12.781310587620133
12.781183926686376
12.781057296683777
12.780930697603079
12.780804129435092
12.780677592170525
12.78055108580022
12.780424610314926
12.780298165705435
12.780171751962536
12.780045369077033
12.77991901703972
12.779792695841405
12.779666405472895
12.779540145925003
12.779413917188545
12.779287719254343
12.77916155211321
12.779035415755994
12.778909310173516
12.778783235356633
12.77865719129616
12.778531177982963
12.77840519540789
12.778279243561785
12.77815332243553
12.778027432019966
12.777901572305975
12.777775743284412
12.777649944946168
12.777524177282118
12.777398440283143
12.777272733940144
12.777147058244
12.77702141318561
12.776895798755888
12.776770214945719
12.776644661746035
12.776519139147728
12.776393647141733
12.776268185718965
12.776142754870346
12.776017354586802
12.77589198485929
12.775766645678726
12.775641337036058
12.775516058922232
12.775390811328219
12.775265594244955
12.775140407663388
12.77501525157451
12.774890125969259
12.77476503083864
12.7746399661736
12.774514931965124
12.774389928204208
12.774264954881827
12.774140011989
12.774015099516667
12.773890217455895
12.773765365797642
12.773640544532933
12.773515753652786
12.773390993148197
12.773266263010214
12.773141563229844
12.773016893798111
12.772892254706063
12.772767645944729
12.77264306750516
12.77251851937838
12.772394001555469
12.772269514027448
12.772145056785392
12.772020629820366
12.771896233123405
12.77177186668562
12.771647530498061
12.771523224551819
12.771398948837957
12.771274703347574
12.771150488071749
12.77102630300158
12.770902148128178
12.770778023442617
12.770653928936026
12.770529864599503
12.77040583042417
12.770281826401133
12.770157852521518
12.770033908776462
12.769909995157079
12.7697861116545
12.769662258259874
12.76953843496434
12.769414641759049
12.769290878635129
12.769167145583754
12.769043442596073
12.768919769663238
12.768796126776438
12.768672513926807
12.768548931105558
12.768425378303847
12.768301855512853
12.768178362723749
12.768054899927758
12.767931467116044
12.767808064279809
12.767684691410254
12.767561348498594
12.767438035536026
12.767314752513775
12.767191499423033
12.767068276255038
12.766945083001016
12.766821919652182
12.766698786199774
12.766575682635036
12.766452608949193
12.766329565133496
12.76620655117919
12.766083567077526
12.76596061281976
12.765837688397148
12.765714793800955
12.765591929022447
12.765469094052893
12.76534628888357
12.765223513505763
12.765100767910749
12.76497805208979
12.76485536603421
12.764732709735293
12.76461008318432
12.764487486372605
12.76436491929145
12.76424238193218
12.764119874286083
12.763997396344484
12.763874948098707
12.763752529540072
12.763630140659913
12.763507781449555
12.763385451900339
12.763263152003598
12.763140881750683
12.763018641132929
12.762896430141693
12.76277424876833
12.762652097004203
12.76252997484066
12.762407882269084
12.762285819280839
12.762163785867294
12.762041782019827
12.761919807729814
12.761797862988645
12.76167594778772
12.761554062118421
12.761432205972133
12.761310379340275
12.761188582214233
12.761066814585421
12.760945076445253
12.760823367785145
12.760701688596505
12.760580038870778
12.760458418599367
12.760336827773703
12.760215266385227
12.76009373442538
12.759972231885582
12.75985075875731
12.759729315031977
12.759607900701061
12.759486515756016
12.759365160188276
12.759243833989345
12.75912253715065
12.759001269663681
12.758880031519919
12.758758822710812
12.758637643227882
12.758516493062578
12.758395372206406
12.758274280650866
12.758153218387443
12.758032185407638
12.757911181702951
12.757790207264891
12.757669262084972
12.757548346154714
12.757427459465625
12.757306602009235
12.757185773777055
12.757064974760635
12.756944204951488
12.756823464341169
12.756702752921198
12.75658207068314
12.756461417618526
12.756340793718902
12.756220198975843
12.756099633380893
12.75597909692562
12.755858589601583
12.755738111400362
12.755617662313513
12.75549724233263
12.755376851449286
12.755256489655059
12.75513615694154
12.755015853300316
12.754895578722982
12.754775333201152
12.754655116726397
12.754534929290354
12.754414770884612
12.754294641500783
12.754174541130492
12.754054469765354
12.753934427396988
12.75381441401703
12.753694429617104
12.753574474188833
12.753454547723871
12.753334650213864
12.753214781650435
12.753094942025246
12.752975131329945
12.752855349556173
12.752735596695604
12.752615872739907
12.752496177680746
12.752376511509773
12.752256874218665
12.752137265799096
12.752017686242771
12.75189813554135
12.751778613686518
12.751659120669977
12.751539656483406
12.751420221118526
12.751300814567015
12.751181436820593
12.75106208787095
12.750942767709812
12.750823476328893
12.750704213719906
12.750584979874574
12.750465774784622
12.750346598441787
12.750227450837787
12.750108331964373
12.74998924181327
12.749870180376227
12.749751147644986
12.749632143611306
12.749513168266938
12.749394221603632
12.749275303613143
12.74915641428725
12.749037553617722
12.748918721596311
12.748799918214804
12.748681143464973
12.748562397338603
12.748443679827465
12.748324990923367
12.748206330618093
12.748087698903433
12.747969095771179
12.747850521213147
12.747731975221138
12.74761345778695
12.747494968902402
12.74737650855932
12.747258076749507
12.747139673464789
12.747021298696994
12.74690295243794
12.746784634679482
12.746666345413445
12.746548084631657

12.746429852325967
12.746311648488229
12.74619347311027
12.746075326183979
12.74595720770118
12.745839117653754
12.745721056033538
12.745603022832425
12.745485018042269
12.745367041654957
12.74524909366234
12.745131174056324
12.745013282828776
12.744895419971595
12.744777585476653
12.74465977933587
12.744542001541113
12.744424252084299
12.744306530957335
12.744188838152105
12.744071173660545
12.743953537474557
12.743835929586059
12.743718349986965
12.743600798669208
12.743483275624698
12.743365780845398
12.743248314323205
12.743130876050074
12.74301346601794
12.742896084218756
12.74277873064446
12.742661405286993
12.742544108138322
12.742426839190413
12.742309598435204
12.742192385864666
12.742075201470763
12.741958045245479
12.741840917180772
12.74172381726863
12.741606745501013
12.741489701869922
12.741372686367342
12.741255698985253
12.741138739715655
12.741021808550547
12.740904905481928
12.740788030501792
12.740671183602151
12.740554364775011
12.740437574012399
12.740320811306306
12.740204076648777
12.740087370031807
12.739970691447445
12.73985404088772
12.73973741834465
12.739620823810274
12.739504257276634
12.739387718735767
12.739271208179728
12.739154725600551
12.739038270990315
12.738921844341043
12.738805445644807
12.738689074893674
12.738572732079698
12.738456417194952
12.738340130231515
12.738223871181448
12.738107640036835
12.737991436789756
12.73787526143229
12.737759113956542
12.737642994354584
12.73752690261851
12.737410838740429
12.737294802712428
12.737178794526628
12.737062814175122
12.736946861650011
12.736830936943432
12.736715040047482
12.736599170954294
12.73648332965598
12.736367516144664
12.736251730412498
12.736135972451574
12.736020242254062
12.735904539812081
12.73578886511779
12.73567321816331
12.73555759894082
12.73544200744244
12.735326443660353
12.735210907586689
12.735095399213629
12.734979918533332
12.73486446553796
12.734749040219683
12.734633642570671
12.73451827258312
12.73440293024919
12.734287615561081
12.734172328510951
12.734057069091028
12.73394183729346
12.73382663311047
12.73371145653427
12.733596307557024
12.73348118617097
12.733366092368291
12.733251026141215
12.733135987481951
12.733020976382718
12.732905992835741
12.732791036833223
12.732676108367405
12.732561207430534
12.732446334014805
12.732331488112496
12.732216669715804
12.732101878817009
12.731987115408335
12.731872379482027
12.731757671030351
12.731642990045563
12.731528336519897
12.731413710445644
12.731299111815058
12.73118454062039
12.731069996853929
12.730955480507943
12.73084099157471
12.7307265300465
12.730612095915609
12.73049768917431
12.730383309814899
12.730268957829663
12.730154633210907
12.730040335950914
12.729926066042
12.729811823476462
12.729697608246612
12.729583420344742
12.729469259763185
12.729355126494257
12.729241020530262
12.729126941863544
12.729012890486398
12.72889886639119
12.728784869570221
12.728670900015837
12.728556957720375
12.728443042676176
12.728329154875594
12.728215294310957
12.72810146097462
12.727987654858943
12.72787387595628
12.72776012425898
12.727646399759422
12.72753270244996
12.727419032322956
12.727305389370791
12.727191773585846
12.727078184960481
12.726964623487078
12.726851089158037
12.726737581965722
12.72662410190254
12.72651064896087
12.726397223133118
12.72628382441167
12.726170452788935
12.726057108257322
12.725943790809225
12.725830500437068
12.725717237133258
12.725604000890192
12.725490791700333
12.725377609556052
12.725264454449817
12.725151326374027
12.72503822532113
12.724925151283554
12.724812104253726
12.7246990842241
12.724586091187112
12.724473125135214
12.724360186060856
12.724247273956477
12.724134388814536
12.7240215306275
12.723908699387822
12.723795895087957
12.723683117720393
12.72357036727759
12.723457643752003
12.72334494713614
12.723232277422444
12.72311963460343
12.723007018671561
12.722894429619336
12.72278186743923
12.72266933212374
12.722556823665363
12.722444342056617
12.722331887289975
12.722219459357964
12.722107058253075
12.721994683967827
12.721882336494737
12.72177001582632
12.72165772195508
12.721545454873562
12.72143321457427
12.721321001049748
12.721208814292526
12.721096654295138
12.720984521050104
12.720872414549993
12.720760334787313
12.720648281754636
12.720536255444497
12.720424255849453
12.720312282962059
12.720200336774877
12.720088417280447
12.719976524471361
12.719864658340153
12.719752818879419
12.71964100608172
12.719529219939616
12.71941746044571
12.719305727592564
12.719194021372779
12.719082341778929
12.718970688803585
12.718859062439368
12.71874746267886
12.718635889514665
12.718524342939368
12.718412822945584
12.718301329525929
12.71818986267299
12.718078422379389
12.71796700863774
12.71785562144066
12.717744260780776
12.717632926650706
12.717521619043072
12.717410337950497
12.71729908336563
12.7171878552811
12.717076653689535
12.716965478583585
12.71685432995589
12.716743207799093
12.716632112105845
12.716521042868811
12.716410000080618
12.716298983733948
12.716187993821434
12.716077030335772
12.715966093269596
12.715855182615591
12.715744298366443
12.715633440514802
12.715522609053345
12.715411803974765
12.71530102527174
12.715190272936942
12.715079546963093
12.714968847342844
12.714858174068922
12.714747527134
12.714636906530789
12.714526312251984
12.714415744290287
12.714305202638432
12.714194687289107
12.714084198235033
12.713973735468906
12.713863298983467
12.71375288877143
12.713642504825529
12.713532147138475
12.71342181570301
12.713311510511872
12.713201231557777
12.713090978833472
12.712980752331717
12.712870552045226
12.712760377966756
12.71265023008907
12.712540108404902
12.712430012907014
12.712319943588179
12.712209900441128
12.712099883458647
12.71198989263349
12.71187992795843
12.711769989426248
12.7116600770297
12.711550190761576
12.711440330614648
12.711330496581704
12.711220688655532
12.711110906828909
12.711001151094639
12.710891421445506
12.710781717874307
12.71067204037384
12.710562388936916
12.710452763556331
12.7103431642249
12.710233590935431
12.71012404368072
12.710014522453601
12.709905027246887
12.709795558053397
12.709686114865958
12.709576697677399
12.709467306480542
12.709357941268214
12.709248602033261
12.70913928876851
12.709030001466807
12.708920740120996
12.708811504723917
12.70870229526843
12.708593111747366
12.70848395415359
12.708374822479966
12.708265716719339
12.708156636864562
12.70804758290852
12.707938554844084
12.707829552664098
12.707720576361453
12.707611625929017
12.707502701359667
12.707393802646283
12.707284929781757
12.707176082758965
12.707067261570794
12.706958466210146
12.706849696669902
12.706740952942969
12.70663223502223
12.706523542900596
12.706414876570996
12.7063062360263
12.70619762125943
12.706089032263298
12.705980469030834
12.705871931554928
12.705763419828514
12.70565493384453
12.705546473595875
12.705438039075496
12.705329630276315
12.705221247191277
12.705112889813297
12.705004558135334
12.704896252150323
12.704787971851195
12.70467971723092
12.704571488282435
12.704463284998686
12.704355107372646
12.704246955397258
12.704138829065482
12.704030728370286
12.703922653304643
12.703814603861499
12.703706580033836
12.703598581814637
12.703490609196859
12.703382662173507
12.703274740737532
12.703166844881935
12.703058974599697
12.702951129883806
12.702843310727252
12.702735517123042
12.702627749064167
12.702520006543613
12.702412289554387
12.702304598089516
12.702196932141977
12.7020892917048
12.70198167677098
12.701874087333549
12.701766523385519
12.701658984919897
12.701551471929724
12.70144398440802
12.70133652234781
12.701229085742126
12.701121674584002
12.70101428886646
12.70090692858256
12.700799593725339
12.700692284287827
12.700585000263095
12.70047774164416
12.700370508424088
12.700263300595939
12.700156118152764
12.700048961087614
12.699941829393559
12.699834723063669
12.699727642090995
12.69962058646862
12.699513556189606
12.69940655124704
12.699299571633981
12.69919261734353
12.699085688368749
12.698978784702733
12.698871906338562
12.698765053269343
12.698658225488149
12.698551422988078
12.698444645762237
12.698337893803718
12.698231167105629
12.69812446566107
12.698017789463139
12.697911138504969
12.697804512779662
12.697697912280324
12.697591337000084
12.697484786932053
12.697378262069376
12.697271762405151
12.697165287932517
12.69705883864461
12.69695241453455
12.696846015595481
12.696739641820535
12.696633293202872
12.696526969735604
12.696420671411904
12.696314398224901
12.696208150167756
12.696101927233629
12.695995729415651
12.695889556707
12.69578340910083
12.695677286590312
12.695571189168597
12.695465116828869
12.695359069564283
12.695253047368027
12.695147050233277
12.695041078153194
12.694935131120975

12.694829209129802
12.69472331217284
12.694617440243295
12.694511593334369
12.694405771439232
12.694299974551095
12.694194202663146
12.694088455768593
12.69398273386064
12.693877036932484
12.693771364977339
12.69366571798841
12.693560095958922
12.693454498882087
12.693348926751112
12.69324337955923
12.693137857299648
12.693032359965608
12.69292688755034
12.69282144004706
12.692716017449008
12.692610619749413
12.692505246941531
12.69239989901858
12.692294575973815
12.692189277800479
12.692084004491829
12.69197875604109
12.691873532441539
12.69176833368642
12.69166315976899
12.691558010682517
12.691452886420258
12.69134778697547
12.691242712341433
12.691137662511412
12.691032637478685
12.690927637236515
12.69082266177818
12.69071771109697
12.69061278518616
12.690507884039032
12.690403007648882
12.69029815600899
12.690193329112656
12.69008852695316
12.689983749523815
12.68987899681792
12.689774268828762
12.689669565549643
12.6895648869739
12.689460233094804
12.689355603905685
12.689250999399867
12.68914641957064
12.689041864411335
12.68893733391528
12.688832828075785
12.688728346886188
12.68862389033981
12.688519458429981
12.688415051150042
12.688310668493312
12.688206310453143
12.688101977022873
12.687997668195846
12.687893383965388
12.687789124324876
12.687684889267642
12.687580678787047
12.687476492876431
12.687372331529172
12.687268194738605
12.687164082498114
12.687059994801045
12.686955931640776
12.686851893010662
12.686747878904114
12.686643889314452
12.686539924235078
12.686435983659377
12.68633206758072
12.6862281759925
12.686124308888077
12.686020466260874
12.685916648104255
12.685812854411624
12.685709085176374
12.685605340391911
12.685501620051614
12.685397924148903
12.685294252677172
12.685190605629838
12.685086983000314
12.684983384781994
12.684879810968303
12.684776261552658
12.68467273652847
12.684569235889173
12.684465759628178
12.68436230773892
12.684258880214836
12.684155477049325
12.684052098235842
12.683948743767825
12.683845413638698
12.683742107841915
12.683638826370919
12.683535569219146
12.683432336380033
12.683329127847056
12.683225943613648
12.683122783673255
12.683019648019359
12.682916536645402
12.682813449544861
12.682710386711163
12.682607348137815
12.682504333818263
12.682401343745987
12.682298377914455
12.682195436317137
12.682092518947517
12.681989625799073
12.68188675686529
12.68178391213965
12.681681091615644
12.681578295286755
12.681475523146467
12.68137277518829
12.681270051405715
12.681167351792238
12.681064676341363
12.680962025046584
12.680859397901411
12.680756794899356
12.680654216033934
12.68055166129864
12.680449130686997
12.680346624192513
12.680244141808734
12.680141683529156
12.680039249347313
12.67993683925673
12.679834453250932
12.679732091323455
12.679629753467825
12.679527439677585
12.679425149946262
12.6793228842674
12.679220642634549
12.679118425041262
12.679016231481047
12.678914061947491
12.67881191643413
12.678709794934518
12.678607697442214
12.678505623950775
12.678403574453753
12.678301548944729
12.678199547417254
12.6780975698649
12.677995616281239
12.677893686659829
12.67779178099426
12.67768989927811
12.677588041504935
12.677486207668347
12.677384397761905
12.677282611779201
12.677180849713825
12.677079111559369
12.676977397309429
12.676875706957585
12.67677404049744
12.676672397922612
12.67657077922667
12.676469184403237
12.676367613445919
12.67626606634832
12.67616454310404
12.676063043706709
12.675961568149933
12.675860116427337
12.675758688532536
12.675657284459138
12.675555904200785
12.675454547751096
12.675353215103703
12.675251906252228
12.675150621190317
12.675049359911595
12.674948122409699
12.674846908678274
12.674745718710959
12.674644552501402
12.674543410043242
12.674442291330122
12.674341196355712
12.674240125113652
12.674139077597603
12.674038053801214
12.67393705371815
12.67383607734208
12.673735124666653
12.67363419568555
12.673533290392434
12.673432408780979
12.67333155084483
12.673230716577706
12.673129905973259
12.673029119025173
12.672928355727125
12.672827616072814
12.672726900055919
12.672626207670115
12.672525538909102
12.672424893766603
12.672324272236262
12.672223674311798
12.672123099986926
12.672022549255322
12.671922022110705
12.671821518546777
12.67172103855724
12.67162058213584
12.671520149276239
12.671419739972178
12.671319354217369
12.671218992005537
12.671118653330401
12.671018338185679
12.6709180465651
12.670817778462398
12.670717533871299
12.67061731278553
12.670517115198837
12.670416941104955
12.670316790497608
12.670216663370566
12.67011655971754
12.670016479532293
12.669916422808564
12.669816389540118
12.669716379720699
12.669616393344056
12.669516430403949
12.669416490894136
12.66931657480839
12.669216682140453
12.669116812884115
12.669016967033123
12.66891714458124
12.668817345522257
12.668717569849948
12.668617817558081
12.668518088640436
12.66841838309079
12.66831870090293
12.668219042070639
12.668119406587694
12.668019794447913
12.667920205645055
12.667820640172934
12.667721098025327
12.667621579196055
12.6675220836789
12.667422611467671
12.667323162556166
12.667223736938197
12.667124334607577
12.667024955558105
12.666925599783601
12.666826267277889
12.66672695803476
12.666627672048046
12.666528409311583
12.666429169819175
12.66632995356466
12.66623076054184
12.666131590744591
12.666032444166705
12.66593332080203
12.665834220644404
12.665735143687677
12.665636089925659
12.665537059352205
12.665438051961184
12.665339067746409
12.665240106701743
12.665141168821041
12.665042254098154
12.664943362526932
12.66484449410124
12.664745648814936
12.664646826661865
12.664548027635924
12.66444925173095
12.664350498940827
12.664251769259415
12.664153062680596
12.664054379198241
12.663955718806221
12.663857081498417
12.663758467268712
12.663659876110986
12.66356130801913
12.663462762987024
12.663364241008573
12.66326574207764
12.663167266188148
12.663068813333965
12.662970383509009
12.662871976707173
12.662773592922363
12.662675232148475
12.662576894379416
12.662478579609099
12.662380287831427
12.662282019040326
12.6621837732297
12.662085550393465
12.661987350525536
12.66188917361984
12.661791019670305
12.661692888670858
12.661594780615415
12.66149669549789
12.661398633312244
12.6613005940524
12.661202577712286
12.661104584285848
12.66100661376702
12.660908666149753
12.660810741427962
12.660712839595641
12.660614960646694
12.660517104575083
12.660419271374778
12.660321461039715
12.660223673563852
12.660125908941145
12.660028167165569
12.659930448231062
12.659832752131608
12.65973507886117
12.659637428413703
12.659539800783188
12.659442195963607
12.659344613948932
12.659247054733108
12.659149518310166
12.659052004674043
12.658954513818733
12.658857045738237
12.65875960042652
12.65866217787759
12.658564778085436
12.658467401044028
12.65837004674739
12.658272715189506
12.658175406364379
12.658078120265996
12.657980856888384
12.657883616225535
12.657786398271444
12.657689203020146
12.657592030465631
12.657494880601938
12.657397753423053
12.65730064892302
12.657203567095834
12.657106507935532
12.657009471436142
12.656912457591668
12.656815466396168
12.65671849784365
12.656621551928152
12.656524628643714
12.656427727984351
12.656330849944126
12.65623399451707
12.65613716169722
12.656040351478623
12.655943563855322
12.65584679882138
12.655750056370833
12.65565333649774
12.65555663919614
12.655459964460114
12.655363312283693
12.655266682660955
12.655170075585962
12.655073491052773
12.65497692905546
12.654880389588076
12.654783872644712
12.654687378219428
12.6545909063063
12.654494456899402
12.654398029992818
12.654301625580638
12.654205243656916
12.654108884215763
12.654012547251254
12.653916232757467
12.653819940728505
12.65372367115847
12.653627424041439
12.653531199371516
12.653434997142803
12.653338817349393
12.65324265998539
12.653146525044887
12.653050412522015
12.652954322410869
12.652858254705567
12.652762209400205
12.652666186488911
12.652570185965793
12.652474207824977
12.652378252060581
12.652282318666721
12.652186407637524
12.652090518967116
12.65199465264964
12.651898808679203
12.651802987049953
12.65170718775602
12.651611410791535
12.651515656150643
12.651419923827481
12.651324213816189
12.651228526110915
12.651132860705804
12.651037217594999
12.650941596772666
12.650845998232938
12.65075042196997
12.650654867977943
12.650559336250971
12.650463826783255
12.650368339568942
12.650272874602186
12.650177431877166
12.650082011388033
12.649986613128982
12.649891237094165
12.649795883277767
12.64970055167395
12.649605242276898

12.649509955080799
12.649414690079821
12.649319447268162
12.649224226639994
12.64912902818951
12.649033851910895
12.648938697798348
12.648843565846052
12.648748456048207
12.648653368399016
12.64855830289267
12.648463259523364
12.648368238285318
12.648273239172726
12.64817826217979
12.648083307300741
12.647988374529763
12.647893463861088
12.647798575288906
12.647703708807457
12.647608864410948
12.647514042093615
12.647419241849656
12.647324463673327
12.647229707558804
12.647134973500366
12.647040261492217
12.646945571528596
12.646850903603733
12.646756257711866
12.646661633847229
12.646567032004075
12.646472452176631
12.646377894359148
12.646283358545857
12.64618884473103
12.646094352908896
12.645999883073712
12.645905435219754
12.645811009341227
12.645716605432428
12.6456222234876
12.64552786350101
12.645433525466922
12.645339209379596
12.645244915233306
12.645150643022301
12.645056392740866
12.644962164383287
12.644867957943811
12.644773773416725
12.644679610796315
12.644585470076848
12.644491351252606
12.644397254317894
12.644303179266972
12.644209126094133
12.644115094793682
12.644021085359894
12.643927097787058
12.643833132069497
12.643739188201467
12.643645266177312
12.643551365991302
12.64345748763773
12.64336363111095
12.643269796405203
12.643175983514855
12.643082192434196
12.64298842315752
12.642894675679162
12.642800949993434
12.642707246094645
12.642613563977127
12.642519903635188
12.642426265063166
12.642332648255381
12.642239053206152
12.642145479909821
12.642051928360717
12.641958398553166
12.6418648904815
12.641771404140059
12.6416779395232
12.64158449662525
12.641491075440529
12.64139767596341
12.641304298188224
12.64121094210933
12.641117607721078
12.641024295017807
12.640931003993883
12.640837734643652
12.640744486961479
12.640651260941715
12.640558056578735
12.640464873866886
12.640371712800546
12.640278573374076
12.640185455581838
12.640092359418215
12.639999284877568
12.63990623195427
12.639813200642704
12.639720190937258
12.639627202832282
12.639534236322184
12.639441291401344
12.639348368064146
12.639255466304954
12.639162586118193
12.639069727498228
12.63897689043947
12.63888407493629
12.638791280983115
12.638698508574318
12.638605757704306
12.638513028367479
12.638420320558255
12.638327634271018
12.638234969500193
12.638142326240184
12.638049704485404
12.637957104230246
12.637864525469157
12.637771968196532
12.637679432406797
12.637586918094375
12.63749442525368
12.637401953879138
12.637309503965183
12.637217075506236
12.637124668496725
12.637032282931079
12.636939918803753
12.636847576109146
12.636755254841713
12.636662954995915
12.636570676566151
12.636478419546892
12.636386183932565
12.636293969717642
12.636201776896534
12.636109605463716
12.636017455413642
12.63592532674075
12.635833219439494
12.635741133504348
12.635649068929766
12.635557025710188
12.63546500384011
12.635373003313974
12.635281024126256
12.635189066271401
12.635097129743908
12.63500521453824
12.634913320648856
12.634821448070259
12.634729596796893
12.634637766823255
12.634545958143834
12.634454170753084
12.63436240464553
12.634270659815629
12.63417893625787
12.634087233966735
12.633995552936742
12.633903893162369
12.633812254638103
12.633720637358467
12.633629041317937
12.633537466511003
12.633445912932203
12.633354380576007
12.633262869436944
12.63317137950951
12.633079910788208
12.632988463267564
12.632897036942094
12.632805631806297
12.632714247854693
12.632622885081815
12.63253154348216
12.632440223050267
12.632348923780654
12.632257645667844
12.632166388706363
12.632075152890765
12.631983938215535
12.631892744675246
12.631801572264418
12.63171042097758
12.631619290809285
12.631528181754065
12.631437093806445
12.631346026961008
12.631254981212264
12.631163956554776
12.631072952983086
12.63098197049175
12.630891009075315
12.630800068728336
12.630709149445376
12.63061825122098
12.630527374049711
12.630436517926151
12.630345682844828
12.63025486880033
12.63016407578722
12.630073303800058
12.62998255283343
12.62989182288189
12.62980111394003
12.629710426002399
12.62961975906359
12.629529113118197
12.62943848816077
12.629347884185906
12.629257301188202
12.629166739162224
12.62907619810257
12.628985678003819
12.628895178860578
12.62880470066742
12.628714243418964
12.628623807109786
12.628533391734495
12.628442997287683
12.628352623763963
12.62826227115793
12.628171939464186
12.62808162867735
12.627991338792024
12.627901069802816
12.627810821704333
12.627720594491208
12.627630388158034
12.627540202699445
12.62745003811005
12.627359894384483
12.627269771517348
12.627179669503294
12.627089588336926
12.626999528012876
12.626909488525778
12.62681946987026
12.626729472040951
12.6266394950325
12.626549538839535
12.626459603456693
12.626369688878608
12.626279795099936
12.62618992211532
12.626100069919397
12.626010238506813
12.625920427872222
12.62583063801027
12.62574086891561
12.625651120582905
12.625561393006796
12.625471686181951
12.62538200010302
12.625292334764682
12.625202690161577
12.625113066288387
12.625023463139764
12.624933880710383
12.624844318994914
12.62475477798802
12.62466525768439
12.624575758078691
12.624486279165593
12.624396820939774
12.624307383395925
12.624217966528718
12.62412857033284
12.62403919480297
12.623949839933802
12.623860505720032
12.623771192156326
12.6236818992374
12.62359262695793
12.623503375312628
12.623414144296174
12.623324933903275
12.623235744128632
12.62314657496694
12.623057426412915
12.622968298461256
12.622879191106673
12.622790104343862
12.622701038167547
12.622611992572425
12.622522967553241
12.62243396310468
12.62234497922147
12.62225601589834
12.622167073129996
12.622078150911157
12.621989249236556
12.62190036810093
12.621811507498988
12.621722667425466
12.621633847875094
12.621545048842613
12.62145627032275
12.621367512310233
12.621278774799805
12.62119005778622
12.6211013612642
12.621012685228497
12.62092402967386
12.620835394595025
12.620746779986737
12.62065818584375
12.62056961216082
12.62048105893271
12.620392526154147
12.620304013819897
12.620215521924745
12.620127050463415
12.620038599430677
12.619950168821305
12.619861758630053
12.619773368851696
12.619684999481002
12.619596650512726
12.619508321941645
12.619420013762541
12.619331725970202
12.619243458559374
12.619155211524834
12.619066984861393
12.618978778563816
12.618890592626869
12.618802427045367
12.618714281814077
12.618626156927787
12.618538052381293
12.618449968169392
12.618361904286871
12.618273860728515
12.618185837489136
12.618097834563521
12.61800985194648
12.617921889632798
12.6178339476173
12.617746025894782
12.617658124460034
12.617570243307878
12.617482382433135
12.617394541830596
12.617306721495083
12.617218921421417
12.617131141604398
12.617043382038853
12.616955642719612
12.616867923641475
12.616780224799282
12.616692546187853
12.616604887802012
12.616517249636582
12.61642963168641
12.616342033946308
12.616254456411127
12.61616689907567
12.616079361934803
12.615991844983355
12.615904348216171
12.615816871628077
12.615729415213927
12.615641978968565
12.615554562886837
12.615467166963587
12.615379791193666
12.61529243557192
12.615205100093215
12.615117784752389
12.6150304895443
12.614943214463818
12.614855959505793
12.614768724665092
12.614681509936565
12.61459431531509
12.614507140795522
12.614419986372733
12.614332852041597
12.614245737796963
12.614158643633738
12.61407156954677
12.613984515530936
12.61389748158113
12.613810467692195
12.613723473859059
12.613636500076572
12.613549546339616
12.613462612643097
12.613375698981887
12.613288805350876
12.613201931744959
12.61311507815902
12.61302824458796
12.61294143102667
12.61285463747005
12.612767863912985
12.612681110350394
12.612594376777166
12.612507663188206
12.61242096957842
12.612334295942716
12.612247642275992
12.61216100857317
12.612074394829158
12.611987801038875
12.61190122719721
12.611814673299099
12.611728139339457
12.6116416253132
12.611555131215257
12.611468657040545
12.611382202783986
12.611295768440502
12.611209354005025
12.611122959472487
12.611036584837814
12.610950230095943
12.6108638952418
12.610777580270314
12.61069128517645
12.610605009955103
12.610518754601257
12.610432519109832
12.61034630347576
12.610260107694009
12.610173931759515
12.610087775667214
12.610001639412083
12.609915522989052
12.609829426393071
12.60974334961911
12.609657292662114
12.609571255517052
12.609485238178866

12.609399240642547
12.609313262903008
12.609227304955244
12.609141366794223
12.609055448414905
12.608969549812269
12.608883670981262
12.608797811916872
12.60871197261407
12.608626153067833
12.608540353273142
12.608454573224963
12.608368812918274
12.608283072348069
12.608197351509332
12.60811165039703
12.608025969006178
12.607940307331722
12.607854665368693
12.607769043112048
12.607683440556801
12.607597857697941
12.60751229453046
12.607426751049347
12.607341227249623
12.607255723126274
12.607170238674305
12.607084773888714
12.606999328764514
12.606913903296693
12.606828497480292
12.60674311131029
12.606657744781714
12.606572397889577
12.606487070628878
12.606401762994652
12.606316474981908
12.606231206585655
12.60614595780094
12.606060728622758
12.605975519046142
12.605890329066124
12.605805158677736
12.605720007875988
12.605634876655914
12.605549765012546
12.605464672940926
12.605379600436088
12.605294547493049
12.605209514106882
12.605124500272591
12.605039505985228
12.604954531239851
12.604869576031486
12.604784640355186
12.604699724205991
12.604614827578962
12.604529950469141
12.604445092871572
12.604360254781325
12.60427543619344
12.604190637102988
12.604105857505012
12.604021097394588
12.603936356766765
12.603851635616596
12.603766933939157
12.603682251729536
12.603597588982753
12.603512945693922
12.603428321858077
12.603343717470304
12.603259132525688
12.603174567019297
12.603090020946206
12.60300549430148
12.602920987080209
12.602836499277476
12.602752030888366
12.602667581907957
12.602583152331338
12.60249874215361
12.602414351369823
12.602329979975103
12.602245627964525
12.60216129533319
12.602076982076198
12.601992688188622
12.60190841366559
12.601824158502172
12.601739922693495
12.60165570623464
12.601571509120724
12.60148733134686
12.601403172908153
12.601319033799676
12.601234914016585
12.60115081355396
12.601066732406947
12.60098267057062
12.60089862804013
12.600814604810575
12.600730600877085
12.600646616234766
12.600562650878755
12.600478704804175
12.600394778006148
12.60031087047981
12.600226982220256
12.600143113222654
12.600059263482118
12.599975432993784
12.599891621752795
12.599807829754255
12.599724056993335
12.599640303465177
12.5995565691649
12.59947285408765
12.599389158228577
12.599305481582826
12.599221824145538
12.599138185911869
12.599054566876955
12.598970967035969
12.598887386384044
12.598803824916327
12.598720282628005
12.598636759514212
12.59855325557011
12.59846977079086
12.598386305171621
12.598302858707564
12.598219431393842
12.598136023225646
12.598052634198107
12.597969264306412
12.597885913545744
12.59780258191126
12.597719269398135
12.597635976001552
12.597552701716667
12.597469446538678
12.59738621046277
12.597302993484098
12.597219795597868
12.597136616799254
12.597053457083438
12.596970316445626
12.59688719488097
12.596804092384698
12.596721008951995
12.59663794457803
12.596554899258011
12.596471872987147
12.596388865760613
12.59630587757363
12.596222908421383
12.596139958299082
12.596057027201917
12.5959741151251
12.59589122206385
12.59580834801337
12.595725492968851
12.59564265692552
12.59555983987858
12.595477041823266
12.595394262754773
12.595311502668318
12.595228761559124
12.595146039422414
12.5950633362534
12.59498065204732
12.59489798679938
12.594815340504807
12.594732713158848
12.594650104756731
12.594567515293646
12.594484944764874
12.59440239316561
12.594319860491114
12.594237346736609
12.594154851897342
12.594072375968535
12.593989918945438
12.59390748082331
12.593825061597366
12.593742661262857
12.59366027981505
12.593577917249167
12.593495573560464
12.593413248744202
12.593330942795623
12.59324865570999
12.593166387482544
12.593084138108551
12.593001907583265
12.592919695901946
12.592837503059862
12.592755329052261
12.592673173874427
12.592591037521593
12.592508919989067
12.592426821272086
12.592344741365928
12.592262680265875
12.592180637967171
12.592098614465122
12.592016609754985
12.59193462383205
12.59185265669158
12.59177070832886
12.591688778739176
12.591606867917806
12.591524975860041
12.591443102561147
12.59136124801644
12.591279412221189
12.591197595170692
12.591115796860231
12.5910340172851
12.590952256440616
12.590870514322031
12.590788790924679
12.59070708624385
12.590625400274833
12.590543733012952
12.590462084453485
12.590380454591743
12.59029884342304
12.59021725094268
12.590135677145964
12.590054122028219
12.589972585584734
12.589891067810838
12.589809568701842
12.589728088253061
12.58964662645981
12.589565183317408
12.58948375882119
12.589402352966447
12.589320965748525
12.589239597162743
12.589158247204432
12.589076915868908
12.588995603151512
12.588914309047558
12.588833033552397
12.588751776661343
12.588670538369755
12.588589318672945
12.588508117566247
12.588426935045032
12.588345771104613
12.588264625740333
12.588183498947545
12.588102390721591
12.588021301057807
12.587940229951553
12.587859177398178
12.58777814339302
12.587697127931433
12.587616131008787
12.587535152620417
12.587454192761681
12.58737325142795
12.587292328614568
12.587211424316902
12.587130538530316
12.587049671250169
12.586968822471814
12.586887992190638
12.586807180401998
12.586726387101264
12.586645612283801
12.586564855944985
12.58648411808018
12.586403398684777
12.586322697754145
12.586242015283652
12.586161351268695
12.586080705704623
12.586000078586851
12.585919469910738
12.58583887967169
12.585758307865067
12.585677754486266
12.58559721953069
12.585516702993708
12.585436204870724
12.585355725157122
12.585275263848306
12.585194820939657
12.58511439642659
12.585033990304487
12.584953602568756
12.584873233214784
12.584792882238002
12.584712549633789
12.58463223539756
12.58455193952472
12.584471662010678
12.58439140285083
12.584311162040619
12.584230939575415
12.584150735450663
12.584070549661758
12.583990382204146
12.583910233073215
12.583830102264395
12.5837499897731
12.583669895594765
12.583589819724804
12.583509762158643
12.583429722891706
12.583349701919426
12.583269699237222
12.583189714840534
12.58310974872479
12.583029800885427
12.582949871317874
12.582869960017575
12.582790066979948
12.582710192200457
12.58263033567452
12.582550497397591
12.582470677365123
12.582390875572525
12.582311092015265
12.582231326688802
12.582151579588563
12.582071850710005
12.581992140048584
12.581912447599747
12.581832773358956
12.581753117321643
12.581673479483285
12.581593859839332
12.58151425838526
12.58143467511651
12.581355110028547
12.581275563116835
12.581196034376848
12.581116523804036
12.581037031393882
12.58095755714186
12.580878101043409
12.58079866309403
12.58071924328919
12.580639841624357
12.580560458095011
12.580481092696617
12.580401745424675
12.58032241627466
12.580243105242035
12.580163812322295
12.58008453751093
12.580005280803412
12.579926042195238
12.579846821681901
12.579767619258872
12.579688434921657
12.579609268665745
12.579530120486618
12.579450990379794
12.579371878340751
12.57929278436499
12.579213708448014
12.579134650585313
12.579055610772395
12.57897658900478
12.578897585277943
12.578818599587416
12.57873963192868
12.57866068229726
12.578581750688667
12.578502837098396
12.578423941521983
12.578345063954933
12.578266204392754
12.578187362830969
12.578108539265088
12.578029733690643
12.577950946103146
12.577872176498113
12.57779342487108
12.577714691217574
12.577635975533106
12.577557277813215
12.57747859805343
12.577399936249266
12.577321292396265
12.577242666489978
12.577164058525907
12.577085468499604
12.577006896406607
12.576928342242448
12.576849806002674
12.57677128768281
12.576692787278416
12.576614304785034
12.5765358401982
12.57645739351347
12.576378964726372
12.576300553832471
12.576222160827326
12.576143785706476
12.576065428465466
12.575987089099867
12.575908767605219
12.575830463977097
12.575752178211035
12.575673910302617
12.575595660247387
12.57551742804091
12.575439213678766
12.575361017156503
12.575282838469692
12.575204677613895
12.575126534584697
12.575048409377656
12.574970301988339
12.574892212412328
12.574814140645191
12.574736086682504
12.574658050519856
12.574580032152802
12.574502031576955
12.574424048787863
12.57434608378112
12.57426813655231
12.574190207097027
12.57411229541084
12.57403440148935
12.573956525328148
12.573878666922816
12.573800826268943
12.573723003362122
12.573645198197958
12.573567410772041
12.573489641079961
12.573411889117326
12.573334154879717
12.573256438362757
12.57317873956204
12.573101058473167
12.573023395091756
12.57294574941339
12.572868121433688
12.572790511148265
12.572712918552721
12.572635343642675
12.572557786413723
12.572480246861497
12.57240272498161
12.572325220769663
12.572247734221312
12.572170265332124
12.57209281409775
12.572015380513813
12.57193796457593
12.571860566279724
12.57178318562082
12.57170582259485
12.571628477197436
12.571551149424206
12.571473839270812
12.571396546732853
12.571319271805987
12.571242014485842
12.571164774768054
12.571087552648256
12.571010348122092
12.570933161185206
12.570855991833223
12.570778840061806
12.57070170586659
12.570624589243215
12.570547490187334
12.57047040869459
12.570393344760644
12.570316298381128
12.570239269551719
12.57016225826804
12.570085264525769
12.570008288320546
12.569931329648034
12.569854388503895
12.569777464883785
12.569700558783365
12.569623670198297
12.569546799124245
12.56946994555687
12.569393109491848
12.569316290924833
12.56923948985151
12.569162706267532
12.569085940168577
12.569009191550315
12.568932460408426
12.568855746738581
12.568779050536458
12.568702371797725
12.56862571051808
12.56854906669319
12.568472440318734
12.568395831390406
12.568319239903877
12.568242665854847
12.568166109238991
12.568089570052003
12.568013048289556
12.567936543947368
12.567860057021111
12.567783587506485
12.567707135399187
12.5676307006949
12.567554283389336
12.56747788347819
12.567401500957148
12.567325135821926
12.56724878806822
12.567172457691736
12.567096144688172
12.567019849053239
12.566943570782646
12.566867309872102
12.566791066317307
12.566714840113983
12.566638631257826
12.566562439744573
12.56648626556992
12.566410108729595
12.566333969219306
12.566257847034777
12.566181742171727
12.566105654625877
12.56602958439295
12.565953531468654
12.565877495848744
12.565801477528922
12.565725476504928
12.565649492772476
12.565573526327322
12.56549757716518
12.565421645281774
12.565345730672847
12.565269833334137
12.565193953261383
12.565118090450314
12.565042244896667
12.564966416596194
12.564890605544633
12.564814811737723
12.5647390351712
12.564663275840823
12.56458753374233
12.564511808871467
12.564436101223995
12.564360410795652
12.564284737582195
12.564209081579378
12.564133442782955
12.56405782118867
12.563982216792287
12.563906629589574
12.563831059576275
12.563755506748157
12.563679971100981
12.56360445263051
12.563528951332504
12.56345346720273
12.563378000236956
12.56330255043095
12.563227117780482
12.563151702281322
12.563076303929249
12.56300092272
12.5629255586494
12.562850211713194
12.562774881907163
12.562699569227078
12.562624273668735
12.562548995227901
12.56247373390036
12.562398489681907

12.562323262568304
12.56224805255535
12.562172859638833
12.562097683814532
12.562022525078254
12.56194738342576
12.56187225885286
12.561797151355353
12.561722060929002
12.561646987569652
12.561571931273063
12.561496892035036
12.561421869851369
12.56134686471788
12.561271876630354
12.561196905584593
12.561121951576403
12.561047014601604
12.560972094655982
12.56089719173535
12.560822305835515
12.560747436952306
12.560672585081514
12.560597750218948
12.560522932360438
12.560448131501799
12.560373347638832
12.560298580767352
12.5602238308832
12.56014909798218
12.560074382060114
12.559999683112828
12.559925001136152
12.559850336125901
12.559775688077895
12.559701056987974
12.55962644285196
12.559551845665682
12.559477265424977
12.559402702125672
12.559328155763609
12.559253626334609
12.559179113834512
12.559104618259166
12.559030139604385
12.558955677866042
12.558881233039948
12.558806805121963
12.558732394107922
12.558657999993663
12.558583622775053
12.558509262447913
12.558434919008107
12.558360592451486
12.558286282773896
12.558211989971186
12.558137714039207
12.558063454973821
12.557989212770876
12.557914987426235
12.557840778935756
12.557766587295282
12.557692412500701
12.557618254547851
12.5575441134326
12.557469989150825
12.557395881698367
12.557321791071123
12.557247717264923
12.557173660275671
12.557099620099216
12.557025596731442
12.55695159016821
12.5568776004054
12.556803627438883
12.556729671264527
12.556655731878237
12.556581809275862
12.55650790345331
12.556434014406419
12.556360142131112
12.556286286623255
12.556212447878734
12.556138625893434
12.556064820663236
12.555991032184037
12.55591726045174
12.555843505462203
12.555769767211345
12.555696045695042
12.555622340909188
12.555548652849687
12.555474981512443
12.555401326893334
12.555327688988267
12.555254067793147
12.55518046330387
12.555106875516334
12.555033304426463
12.554959750030132
12.554886212323272
12.554812691301777
12.554739186961559
12.55466569929853
12.554592228308591
12.554518773987668
12.55444533633166
12.554371915336503
12.554298510998084
12.554225123312344
12.554151752275187
12.554078397882536
12.554005060130313
12.553931739014438
12.553858434530833
12.553785146675425
12.553711875444137
12.553638620832889
12.553565382837618
12.553492161454258
12.553418956678716
12.553345768506956
12.553272596934875
12.553199441958435
12.55312630357355
12.553053181776159
12.552980076562214
12.552906987927647
12.552833915868392
12.552760860380388
12.552687821459587
12.55261479910192
12.552541793303329
12.552468804059782
12.5523958313672
12.552322875221547
12.552249935618756
12.552177012554797
12.552104106025608
12.552031216027139
12.551958342555352
12.5518854856062
12.551812645175637
12.551739821259622
12.551667013854106
12.551594222955057
12.551521448558429
12.551448690660186
12.551375949256306
12.551303224342726
12.551230515915424
12.551157823970373
12.551085148503537
12.551012489510873
12.550939846988369
12.550867220931984
12.550794611337697
12.550722018201478
12.550649441519298
12.550576881287144
12.550504337500984
12.550431810156795
12.550359299250564
12.550286804778263
12.55021432673587
12.550141865119393
12.550069419924785
12.549996991148047
12.549924578785177
12.549852182832133
12.549779803284924
12.54970744013954
12.549635093391965
12.54956276303819
12.549490449074211
12.54941815149602
12.549345870299627
12.549273605481005
12.549201357036177
12.549129124961125
12.549056909251858
12.548984709904367
12.548912526914664
12.548840360278756
12.548768209992632
12.54869607605231
12.5486239584538
12.548551857193107
12.548479772266235
12.5484077036692
12.548335651398013
12.54826361544869
12.548191595817235
12.548119592499681
12.54804760549202
12.547975634790294
12.547903680390517
12.54783174228869
12.547759820480858
12.547687914963026
12.547616025731234
12.547544152781485
12.547472296109822
12.54740045571227
12.54732863158485
12.547256823723597
12.547185032124535
12.54711325678371
12.547041497697133
12.546969754860847
12.546898028270894
12.546826317923301
12.546754623814126
12.546682945939375
12.546611284295102
12.54653963887735
12.546468009682167
12.546396396705582
12.546324799943642
12.546253219392403
12.546181655047906
12.546110106906186
12.546038574963308
12.545967059215316
12.545895559658259
12.545824076288195
12.545752609101177
12.545681158093245
12.54560972326047
12.545538304598908
12.545466902104614
12.545395515773635
12.545324145602041
12.545252791585902
12.545181453721264
12.545110132004206
12.545038826430789
12.544967536997062
12.544896263699114
12.544825006533003
12.544753765494793
12.544682540580558
12.54461133178638
12.544540139108326
12.544468962542453
12.544397802084866
12.544326657731602
12.54425552947878
12.54418441732245
12.5441133212587
12.544042241283613
12.543971177393264
12.543900129583742
12.543829097851136
12.543758082191513
12.543687082600966
12.543616099075594
12.543545131611474
12.543474180204703
12.543403244851364
12.543332325547551
12.543261422289358
12.543190535072876
12.543119663894212
12.54304880874944
12.542977969634675
12.542907146546018
12.54283633947956
12.542765548431397
12.542694773397644
12.542624014374384
12.542553271357741
12.542482544343818
12.542411833328714
12.542341138308528
12.542270459279399
12.542199796237409
12.542129149178674
12.542058518099306
12.541987902995427
12.54191730386313
12.541846720698567
12.541776153497823
12.541705602257021
12.541635066972296
12.541564547639744
12.541494044255497
12.541423556815682
12.541353085316421
12.541282629753836
12.54121219012404
12.541141766423175
12.541071358647363
12.541000966792733
12.540930590855417
12.540860230831546
12.54078988671725
12.540719558508659
12.540649246201909
12.540578949793138
12.540508669278477
12.540438404654068
12.540368155916054
12.540297923060567
12.540227706083753
12.540157504981746
12.540087319750699
12.540017150386745
12.539946996886048
12.539876859244725
12.539806737458951
12.539736631524855
12.539666541438619
12.53959646719635
12.539526408794227
12.539456366228388
12.539386339495005
12.539316328590226
12.539246333510198
12.539176354251083
12.539106390809048
12.53903644318025
12.53896651136083
12.538896595346975
12.538826695134842
12.538756810720594
12.538686942100393
12.538617089270394
12.538547252226794
12.538477430965726
12.538407625483387
12.538337835775929
12.538268061839545
12.538198303670383
12.538128561264633
12.538058834618466
12.537989123728062
12.53791942858959
12.537849749199232
12.537780085553164
12.537710437647576
12.537640805478635
12.537571189042543
12.53750158833546
12.537432003353581
12.53736243409311
12.537292880550204
12.537223342721072
12.537153820601896
12.537084314188862
12.537014823478174
12.536945348466014
12.536875889148567
12.536806445522041
12.536737017582634
12.536667605326537
12.536598208749943
12.536528827849057
12.536459462620083
12.536390113059218
12.53632077916266
12.536251460926604
12.536182158347286
12.536112871420878
12.536043600143596
12.535974344511665
12.535905104521271
12.535835880168635
12.535766671449965
12.535697478361472
12.535628300899367
12.535559139059878
12.535489992839198
12.535420862233558
12.53535174723917
12.535282647852252
12.535213564069032
12.535144495885715
12.535075443298544
12.535006406303724
12.534937384897484
12.53486837907605
12.534799388835637
12.534730414172488
12.534661455082823
12.534592511562877
12.534523583608877
12.534454671217041
12.53438577438363
12.534316893104851
12.534248027376947
12.534179177196156
12.534110342558714
12.534041523460859
12.533972719898834
12.533903931868867
12.533835159367207
12.533766402390095
12.533697660933768
12.533628934994487
12.533560224568474
12.533491529652002
12.533422850241287
12.533354186332602
12.533285537922186
12.533216905006292
12.533148287581165
12.533079685643074
12.533011099188252
12.532942528212974
12.532873972713478
12.532805432686036
12.532736908126896
12.532668399032316
12.532599905398563
12.5325314272219
12.532462964498585
12.532394517224867
12.532326085397028
12.532257669011331
12.532189268064037
12.532120882551428
12.532052512469747
12.53198415781529
12.531915818584313
12.531847494773094
12.531779186377886
12.531710893394994
12.531642615820674
12.531574353651202
12.531506106882869
12.531437875511934
12.531369659534686
12.53130145894741
12.531233273746377
12.531165103927872
12.531096949488186
12.531028810423589
12.530960686730376
12.53089257840484
12.530824485443253
12.530756407841915
12.530688345597111
12.530620298705136
12.530552267162273
12.530484250964822
12.530416250109075
12.530348264591332
12.530280294407868
12.530212339555016
12.530144400029043
12.530076475826263
12.530008566942968
12.529940673375467
12.52987279512006
12.529804932173043
12.529737084530733
12.52966925218941
12.529601435145423
12.529533633395054
12.529465846934594
12.529398075760385
12.529330319868714
12.529262579255915
12.529194853918273
12.529127143852126
12.529059449053777
12.528991769519552
12.528924105245752
12.5288564562287
12.528788822464728
12.528721203950138
12.528653600681267
12.528586012654422
12.528518439865923
12.528450882312125
12.528383339989318
12.528315812893846
12.52824830102204
12.52818080437021
12.528113322934713
12.528045856711833
12.527978405697954
12.527910969889382
12.52784354928244
12.52777614387349
12.52770875365885
12.527641378634856
12.527574018797853
12.527506674144176
12.527439344670162
12.527372030372163
12.527304731246499
12.527237447289535
12.527170178497606
12.527102924867053
12.527035686394223
12.526968463075471
12.52690125490714
12.526834061885564
12.526766884007122
12.526699721268146
12.526632573664992
12.526565441194013
12.526498323851552
12.526431221633986
12.526364134537655
12.526297062558921
12.526230005694142
12.52616296393968
12.526095937291895
12.526028925747145
12.525961929301785
12.525894947952192
12.525827981694723
12.525761030525752
12.525694094441631
12.525627173438735
12.525560267513438
12.525493376662084
12.52542650088108
12.525359640166782
12.52529279451555
12.525225963923768
12.525159148387822
12.525092347904069
12.525025562468898
12.524958792078666
12.524892036729778
12.524825296418607
12.524758571141524
12.524691860894917
12.524625165675163
12.52455848547865
12.524491820301764
12.524425170140892
12.524358534992416
12.524291914852727
12.524225309718203
12.524158719585259
12.524092144450254
12.524025584309605
12.523959039159692
12.523892508996914
12.52382599381767
12.523759493618353
12.523693008395338
12.523626538145052
12.523560082863886
12.523493642548232
12.523427217194499
12.523360806799086
12.523294411358394
12.52322803086884
12.523161665326796
12.523095314728712
12.52302897907096
12.522962658349948
12.522896352562123
12.52283006170387
12.522763785771586
12.522697524761695
12.522631278670618
12.522565047494757
12.52249883123054
12.522432629874366
12.522366443422666
12.522300271871854
12.522234115218351
12.522167973458563
12.522101846588937
12.522035734605868
12.5219696375058
12.52190355528515
12.521837487940326
12.521771435467784
12.521705397863927
12.521639375125202
12.521573367248022
12.52150737422883
12.521441396064041
12.521375432750096
12.521309484283439
12.52124355066047
12.521177631877674
12.521111727931459
12.521045838818248
12.520979964534503
12.520914105076658
12.520848260441138
12.5207824306244
12.52071661562288
12.52065081543302
12.520585030051269
12.52051925947407
12.520453503697869
12.520387762719109
12.520322036534248
12.52025632513972
12.520190628531982
12.520124946707485
12.520059279662695
12.519993627394033
12.51992798989798
12.519862367170985
12.519796759209491
12.519731166009972
12.51966558756888
12.519600023882676
12.519534474947804
12.519468940760747
12.519403421317959
12.519337916615887
12.519272426651012
12.5192069514198
12.519141490918713
12.51907604514421
12.519010614092778
12.518945197760853
12.518879796144946
12.518814409241493
12.518749037046984
12.518683679557887
12.518618336770665
12.518553008681812
12.518487695287792
12.518422396585095
12.518357112570172
12.51829184323952
12.518226588589625
12.51816134861695
12.51809612331798
12.51803091268921
12.517965716727115
12.517900535428174
12.517835368788878
12.517770216805722
12.51770507947518
12.517639956793747
12.517574848757896
12.517509755364147
12.517444676608969
12.517379612488874
12.517314563000328
12.51724952813985
12.517184507903917
12.517119502289036
12.517054511291699
12.516989534908404
12.516924573135658
12.516859625969945
12.516794693407784
12.516729775445668
12.516664872080097
12.51659998330759
12.516535109124632
12.516470249527737

12.516405404513419
12.516340574078168
12.516275758218518
12.516210956930951
12.516146170211996
12.51608139805816
12.516016640465963
12.515951897431908
12.515887168952506
12.515822455024288
12.515757755643754
12.515693070807442
12.51562840051185
12.51556374475351
12.515499103528933
12.515434476834638
12.51536986466717
12.515305267023027
12.515240683898751
12.515176115290853
12.515111561195862
12.515047021610323
12.514982496530742
12.514917985953652
12.514853489875591
12.514789008293073
12.514724541202654
12.514660088600866
12.514595650484221
12.514531226849272
12.51446681769254
12.514402423010585
12.514338042799912
12.514273677057085
12.514209325778637
12.514144988961103
12.514080666601036
12.514016358694976
12.51395206523945
12.513887786231026
12.51382352166622
12.51375927154161
12.513695035853727
12.51363081459913
12.513566607774353
12.513502415375957
12.513438237400479
12.513374073844497
12.513309924704545
12.513245789977177
12.513181669658946
12.51311756374643
12.513053472236159
12.512989395124702
12.512925332408617
12.512861284084465
12.51279725014881
12.512733230598203
12.512669225429212
12.512605234638396
12.512541258222335
12.512477296177591
12.512413348500704
12.512349415188273
12.512285496236855
12.512221591643021
12.512157701403323
12.512093825514357
12.512029963972692
12.511966116774888
12.511902283917529
12.511838465397169
12.51177466121042
12.511710871353841
12.51164709582401
12.5115833346175
12.51151958773089
12.51145585516077
12.511392136903714
12.511328432956315
12.511264743315156
12.511201067976797
12.511137406937847
12.511073760194895
12.511010127744518
12.5109465095833
12.51088290570783
12.510819316114711
12.510755740800525
12.510692179761863
12.51062863299533
12.5105651004975
12.51050158226497
12.510438078294362
12.510374588582247
12.510311113125232
12.510247651919904
12.51018420496288
12.51012077225075
12.510057353780109
12.509993949547583
12.509930559549746
12.509867183783225
12.509803822244612
12.50974047493051
12.509677141837546
12.509613822962308
12.5095505183014
12.509487227851453
12.509423951609067
12.509360689570855
12.509297441733423
12.509234208093396
12.509170988647384
12.509107783391997
12.509044592323848
12.508981415439568
12.508918252735771
12.508855104209069
12.508791969856084
12.508728849673442
12.508665743657758
12.508602651805663
12.508539574113774
12.508476510578722
12.50841346119713
12.508350425965613
12.50828740488081
12.508224397939347
12.508161405137862
12.508098426472976
12.508035461941315
12.507972511539515
12.507909575264227
12.507846653112052
12.507783745079648
12.50772085116364
12.507657971360674
12.507595105667374
12.507532254080399
12.507469416596381
12.507406593211934
12.50734378392374
12.507280988728406
12.507218207622612
12.507155440602965
12.507092687666134
12.507029948808757
12.506967224027488
12.506904513318958
12.506841816679831
12.506779134106742
12.506716465596359
12.506653811145325
12.506591170750287
12.506528544407912
12.506465932114832
12.506403333867736
12.506340749663252
12.506278179498041
12.506215623368764
12.506153081272078
12.506090553204661
12.506028039163139
12.505965539144194
12.505903053144495
12.50584058116069
12.505778123189456
12.50571567922746
12.50565324927135
12.5055908333178
12.505528431363482
12.505466043405066
12.505403669439229
12.505341309462619
12.50527896347193
12.505216631463822
12.505154313434966
12.505092009382054
12.50502971930174
12.504967443190717
12.504905181045645
12.504842932863227
12.504780698640113
12.504718478373004
12.504656272058568
12.504594079693494
12.504531901274458
12.504469736798153
12.504407586261246
12.504345449660441
12.504283326992422
12.504221218253862
12.504159123441465
12.50409704255191
12.504034975581884
12.503972922528087
12.503910883387208
12.503848858155939
12.503786846830964
12.503724849408988
12.503662865886715
12.503600896260822
12.503538940528022
12.503476998684988
12.503415070728444
12.50335315665508
12.503291256461598
12.503229370144702
12.503167497701087
12.503105639127467
12.503043794420536
12.502981963577
12.502920146593569
12.502858343466958
12.502796554193853
12.50273477877099
12.50267301719505
12.502611269462767
12.502549535570848
12.502487815515991
12.50242610929492
12.50236441690434
12.502302738340987
12.502241073601555
12.502179422682769
12.502117785581348
12.502056162294009
12.501994552817473
12.501932957148457
12.501871375283688
12.50180980721988
12.501748252953766
12.501686712482066
12.501625185801498
12.501563672908791
12.50150217380068
12.501440688473881
12.501379216925136
12.50131775915116
12.501256315148684
12.50119488491445
12.50113346844518
12.501072065737613
12.501010676788487
12.500949301594522
12.500887940152468
12.50082659245905
12.50076525851101
12.500703938305094
12.500642631838023
12.500581339106553
12.500520060107425
12.500458794837368
12.500397543293142
12.500336305471462
12.50027508136911
12.500213870982803
12.500152674309295
12.500091491345335
12.500030322087675
12.499969166533061
12.499908024678227
12.499846896519959
12.499785782054975
12.499724681280034
12.499663594191903
12.499602520787318
12.49954146106305
12.499480415015856
12.499419382642479
12.499358363939686
12.499297358904226
12.49923636753287
12.49917538982237
12.4991144257695
12.499053475371008
12.498992538623655
12.498931615524219
12.498870706069455
12.498809810256134
12.498748928081007
12.498688059540862
12.49862720463246
12.49856636335257
12.498505535697959
12.498444721665402
12.498383921251666
12.498323134453534
12.49826236126776
12.498201601691132
12.498140855720424
12.498080123352418
12.498019404583884
12.49795869941159
12.497898007832337
12.497837329842888
12.49777666544002
12.497716014620538
12.497655377381204
12.4975947537188
12.497534143630121
12.49747354711194
12.497412964161052
12.497352394774248
12.497291838948302
12.497231296680019
12.49717076796617
12.497110252803548
12.49704975118895
12.49698926311918
12.49692878859101
12.496868327601247
12.496807880146674
12.496747446224086
12.496687025830296
12.496626618962084
12.49656622561626
12.49650584578961
12.496445479478949
12.496385126681066
12.496324787392764
12.496264461610846
12.496204149332115
12.496143850553388
12.496083565271444
12.496023293483104
12.495963035185174
12.495902790374465
12.495842559047775
12.495782341201927
12.495722136833713
12.495661945939963
12.495601768517473
12.495541604563071
12.495481454073552
12.495421317045754
12.495361193476466
12.49530108336252
12.49524098670073
12.495180903487908
12.495120833720884
12.495060777396475
12.495000734511496
12.494940705062765
12.49488068904711
12.49482068646136
12.494760697302324
12.494700721566833
12.494640759251721
12.494580810353808
12.494520874869925
12.494460952796887
12.494401044131541
12.494341148870692
12.494281267011205
12.494221398549879
12.494161543483564
12.494101701809091
12.4940418735233
12.493982058623011
12.49392225710507
12.493862468966311
12.493802694203566
12.493742932813685
12.493683184793493
12.493623450139856
12.493563728849585
12.493504020919536
12.493444326346548
12.493384645127467
12.493324977259142
12.493265322738408
12.493205681562122
12.493146053727111
12.493086439230257
12.493026838068378
12.492967250238335
12.492907675736976
12.492848114561141
12.49278856670771
12.492729032173516
12.49266951095542
12.492610003050272
12.492550508454919
12.492491027166237
12.492431559181071
12.492372104496287
12.49231266310873
12.492253235015275
12.492193820212766
12.492134418698074
12.492075030468067
12.492015655519594
12.491956293849531
12.491896945454736
12.49183761033208
12.491778288478429
12.49171897989064
12.491659684565585
12.491600402500138
12.491541133691177
12.49148187813556
12.491422635830153
12.491363406771837
12.491304190957493
12.491244988383977
12.491185799048187
12.491126622946975
12.491067460077236
12.491008310435832
12.490949174019645
12.490890050825568
12.490830940850458
12.490771844091217
12.490712760544708
12.490653690207834
12.490594633077462
12.490535589150477
12.490476558423772
12.49041754089423
12.490358536558736
12.490299545414175
12.49024056745745
12.490181602685416
12.490122651095003
12.490063712683076
12.49000478744653
12.489945875382267
12.489886976487185
12.489828090758156
12.489769218192091
12.489710358785878
12.489651512536428
12.489592679440614
12.48953385949536
12.489475052697545
12.489416259044088
12.489357478531872
12.489298711157804
12.489239956918793
12.489181215811726
12.489122487833528
12.489063772981105
12.489005071251329
12.488946382641153
12.488887707147446
12.488829044767131
12.48877039549713
12.488711759334333

12.488653136275659
12.48859452631801
12.488535929458322
12.488477345693486
12.488418775020419
12.488360217436053
12.488301672937286
12.488243141521037
12.488184623184218
12.488126117923775
12.488067625736594
12.488009146619616
12.48795068056974
12.487892227583913
12.487833787659048
12.487775360792051
12.487716946979877
12.487658546219432
12.487600158507643
12.487541783841431
12.48748342221773
12.487425073633478
12.487366738085587
12.487308415570993
12.487250106086632
12.487191809629435
12.487133526196324
12.487075255784237
12.487016998390105
12.48695875401087
12.486900522643465
12.486842304284822
12.486784098931883
12.486725906581592
12.48666772723087
12.486609560876664
12.486551407515925
12.48649326714559
12.486435139762587
12.486377025363877
12.486318923946397
12.486260835507087
12.486202760042897
12.486144697550765
12.486086648027651
12.486028611470498
12.485970587876256
12.485912577241871
12.485854579564279
12.48579659484046
12.485738623067352
12.485680664241904
12.485622718361077
12.485564785421815
12.485506865421087
12.485448958355828
12.485391064223018
12.4853331830196
12.485275314742545
12.485217459388792
12.485159616955324
12.485101787439092
12.485043970837047
12.484986167146165
12.484928376363401
12.48487059848573
12.484812833510105
12.484755081433503
12.484697342252883
12.484639615965209
12.484581902567452
12.484524202056587
12.48446651442958
12.484408839683399
12.484351177815014
12.4842935288214
12.484235892699537
12.484178269446385
12.484120659058934
12.484063061534151
12.484005476869001
12.48394790506048
12.483890346105554
12.48383280000121
12.483775266744418
12.483717746332166
12.48366023876143
12.483602744029195
12.483545262132445
12.48348779306816
12.483430336833319
12.483372893424926
12.48331546283994
12.483258045075367
12.483200640128187
12.483143247995397
12.483085868673978
12.483028502160916
12.482971148453204
12.482913807547847
12.482856479441823
12.482799164132127
12.482741861615752
12.482684571889703
12.482627294950971
12.482570030796536
12.482512779423416
12.482455540828596
12.482398315009089
12.48234110196187
12.482283901683967
12.482226714172361
12.482169539424065
12.482112377436081
12.482055228205402
12.481998091729045
12.481940968004011
12.481883857027304
12.481826758795926
12.481769673306898
12.481712600557213
12.481655540543887
12.481598493263936
12.481541458714359
12.48148443689217
12.481427427794394
12.48137043141802
12.48131344776008
12.48125647681759
12.481199518587557
12.481142573067006
12.481085640252932
12.481028720142383
12.480971812732367
12.48091491801988
12.480858036001978
12.480801166675667
12.480744310037968
12.480687466085893
12.480630634816473
12.480573816226745
12.480517010313717
12.48046021707442
12.480403436505888
12.480346668605142
12.480289913369198
12.480233170795112
12.48017644087988
12.480119723620568
12.480063019014187
12.480006327057769
12.479949647748345
12.479892981082966
12.47983632705864
12.479779685672415
12.479723056921333
12.47966644080243
12.479609837312736
12.479553246449289
12.479496668209126
12.4794401025893
12.479383549586847
12.479327009198798
12.479270481422208
12.479213966254113
12.47915746369155
12.47910097373159
12.479044496371243
12.478988031607583
12.478931579437637
12.478875139858467
12.478818712867119
12.478762298460634
12.478705896636079
12.478649507390475
12.4785931307209
12.478536766624405
12.478480415098037
12.478424076138841
12.478367749743883
12.47831143591022
12.478255134634901
12.478198845914985
12.47814256974754
12.478086306129615
12.478030055058255
12.477973816530547
12.477917590543544
12.477861377094289
12.477805176179874
12.47774898779734
12.477692811943763
12.477636648616208
12.477580497811733
12.4775243595274
12.477468233760295
12.47741212050747
12.477356019766008
12.477299931532956
12.477243855805408
12.477187792580418
12.477131741855064
12.477075703626422
12.477019677891567
12.476963664647567
12.476907663891485
12.476851675620434
12.47679569983145
12.476739736521633
12.476683785688062
12.476627847327798
12.476571921437937
12.476516008015547
12.476460107057726
12.476404218561544
12.476348342524078
12.476292478942428
12.47623662781366
12.47618078913488
12.476124962903155
12.476069149115578
12.476013347769243
12.475957558861225
12.475901782388618
12.475846018348518
12.47579026673802
12.475734527554184
12.475678800794144
12.475623086454963
12.475567384533745
12.47551169502759
12.475456017933572
12.475400353248808
12.47534470097039
12.47528906109541
12.475233433620968
12.475177818544166
12.475122215862095
12.475066625571865
12.475011047670574
12.474955482155323
12.474899929023216
12.474844388271357
12.474788859896833
12.474733343896778
12.474677840268285
12.474622349008458
12.474566870114407
12.474511403583229
12.474455949412054
12.474400507597974
12.474345078138107
12.474289661029555
12.474234256269446
12.474178863854885
12.474123483782975
12.474068116050839
12.474012760655599
12.473957417594358
12.473902086864245
12.473846768462359
12.473791462385837
12.47373616863178
12.473680887197327
12.473625618079573
12.47357036127567
12.473515116782712
12.473459884597842
12.47340466471817
12.473349457140825
12.473294261862929
12.473239078881603
12.473183908193977
12.473128749797194
12.473073603688363
12.473018469864611
12.472963348323077
12.472908239060892
12.472853142075172
12.47279805736307
12.472742984921704
12.4726879247482
12.472632876839706
12.47257784119336
12.472522817806292
12.472467806675617
12.47241280779851
12.472357821172075
12.472302846793475
12.472247884659826
12.472192934768284
12.472137997115993
12.472083071700077
12.472028158517691
12.471973257565976
12.471918368842076
12.47186349234312
12.471808628066286
12.471753776008688
12.471698936167487
12.47164410853983
12.47158929312286
12.471534489913727
12.471479698909578
12.471424920107578
12.471370153504862
12.47131539909859
12.471260656885915
12.471205926863984
12.471151209029957
12.471096503380982
12.471041809914222
12.470987128626815
12.47093245951595
12.470877802578764
12.470823157812415
12.470768525214067
12.470713904780881
12.47065929651002
12.47060470039864
12.4705501164439
12.47049554464297
12.470440984993004
12.47038643749118
12.470331902134667
12.47027737892061
12.470222867846187
12.470168368908565
12.470113882104918
12.470059407432407
12.4700049448882
12.469950494469478
12.469896056173402
12.469841629997148
12.46978721593788
12.469732813992792
12.469678424159037
12.469624046433808
12.469569680814258
12.469515327297588
12.46946098588096
12.469406656561551
12.469352339336542
12.469298034203128
12.469243741158463
12.469189460199738
12.469135191324137
12.46908093452885
12.469026689811047
12.468972457167913
12.468918236596641
12.468864028094407
12.468809831658401
12.468755647285814
12.46870147497383
12.468647314719634
12.468593166520407
12.468539030373359
12.468484906275673
12.468430794224538
12.468376694217136
12.468322606250673
12.468268530322337
12.468214466429316
12.468160414568818
12.468106374738044
12.468052346934156
12.467998331154394
12.467944327395918
12.46789033565595
12.467836355931682
12.467782388220318
12.467728432519051
12.467674488825091
12.467620557135632
12.467566637447877
12.467512729759044
12.467458834066308
12.467404950366902
12.46735107865803
12.467297218936885
12.467243371200674
12.467189535446611
12.467135711671911
12.467081899873769
12.467028100049411
12.466974312196035
12.46692053631086
12.466866772391093
12.46681302043395
12.466759280436646
12.466705552396387
12.4666518363104
12.4665981321759
12.466544439990088
12.466490759750199
12.466437091453448
12.46638343509705
12.466329790678225
12.466276158194198
12.46622253764218
12.466168929019393
12.466115332323074
12.46606174755044
12.466008174698702
12.465954613765112
12.46590106474686
12.465847527641202
12.465794002445357
12.465740489156529
12.46568698777198
12.465633498288925
12.465580020704577
12.465526555016215
12.465473101221011
12.465419659316234
12.465366229299109
12.465312811166868
12.465259404916738
12.465206010545964
12.465152628051781
12.465099257431417
12.465045898682114
12.464992551801112
12.464939216785641
12.464885893632955
12.464832582340271
12.464779282904853
12.464725995323931
12.464672719594747
12.464619455714546
12.464566203680578
12.464512963490066
12.464459735140267
12.46440651862844
12.464353313951815
12.464300121107641
12.464246940093169
12.464193770905647
12.46414061354232
12.464087468000448
12.464034334277272
12.463981212370044
12.463928102276022
12.463875003992449
12.463821917516581
12.463768842845688
12.46371577997701
12.4636627289078
12.463609689635327
12.463556662156822
12.46350364646958
12.463450642570834
12.463397650457848
12.463344670127885
12.46329170157821
12.463238744806063
12.463185799808732
12.463132866583466
12.463079945127538
12.463027035438195
12.462974137512724
12.46292125134837
12.46286837694241
12.462815514292116
12.462762663394733
12.462709824247554
12.462656996847844
12.462604181192866
12.462551377279892
12.462498585106195
12.462445804669045
12.462393035965711
12.462340278993478
12.4622875337496
12.462234800231371
12.462182078436072
12.462129368360964
12.46207667000332
12.462023983360424
12.461971308429558
12.461918645208007
12.46186599369303
12.461813353881919
12.461760725771962
12.461708109360433
12.461655504644611
12.461602911621796
12.461550330289246
12.461497760644273
12.461445202684136
12.461392656406145
12.46134012180757
12.461287598885708
12.461235087637839
12.461182588061261
12.461130100153262
12.461077623911125
12.461025159332143
12.460972706413608
12.460920265152819
12.460867835547065
12.460815417593647
12.460763011289842
12.460710616632959
12.460658233620288
12.460605862249128
12.460553502516781
12.460501154420538
12.460448817957701
12.460396493125568
12.460344179921426

12.460291878342606
12.460239588386386
12.460187310050078
12.460135043330975
12.460082788226392
12.460030544733629
12.45997831284999
12.459926092572784
12.459873883899313
12.459821686826887
12.45976950135281
12.459717327474394
12.459665165188952
12.45961301449378
12.459560875386202
12.459508747863532
12.459456631923063
12.459404527562132
12.459352434778035
12.459300353568095
12.459248283929616
12.459196225859925
12.45914417935633
12.459092144416145
12.45904012103671
12.458988109215314
12.4589361089493
12.458884120235968
12.458832143072659
12.458780177456665
12.458728223385338
12.458676280855983
12.458624349865923
12.458572430412488
12.458520522493007
12.458468626104791
12.458416741245177
12.458364867911486
12.458313006101053
12.458261155811195
12.458209317039248
12.458157489782547
12.458105674038396
12.458053869804155
12.45800207707714
12.457950295854694
12.457898526134139
12.457846767912809
12.45779502118805
12.457743285957186
12.457691562217548
12.457639849966485
12.457588149201323
12.457536459919407
12.457484782118085
12.457433115794672
12.457381460946518
12.457329817570967
12.457278185665354
12.457226565227026
12.457174956253336
12.457123358741594
12.457071772689172
12.457020198093423
12.456968634951666
12.456917083261247
12.45686554301954
12.456814014223852
12.456762496871573
12.456710990960028
12.456659496486564
12.456608013448546
12.45655654184331
12.456505081668217
12.456453632920613
12.45640219559785
12.456350769697295
12.45629935521628
12.456247952152168
12.45619656050233
12.456145180264098
12.456093811434856
12.456042454011927
12.455991107992688
12.455939773374507
12.455888450154733
12.455837138330722
12.455785837899846
12.455734548859448
12.455683271206919
12.4556320049396
12.455580750054851
12.455529506550054
12.455478274422564
12.455427053669748
12.455375844288968
12.455324646277596
12.455273459632997
12.455222284352553
12.455171120433604
12.455119967873543
12.455068826669738
12.455017696819555
12.454966578320356
12.454915471169533
12.454864375364451
12.454813290902475
12.45476221778099
12.454711155997371
12.454660105548985
12.454609066433221
12.454558038647443
12.45450702218904
12.454456017055382
12.454405023243854
12.454354040751834
12.454303069576696
12.454252109715833
12.45420116116662
12.45415022392644
12.454099297992673
12.454048383362709
12.453997480033928
12.453946588003722
12.453895707269464
12.453844837828553
12.45379397967837
12.453743132816301
12.453692297239748
12.453641472946083
12.45359065993271
12.45353985819701
12.453489067736363
12.453438288548188
12.453387520629859
12.453336763978776
12.453286018592337
12.453235284467928
12.45318456160294
12.453133849994773
12.453083149640847
12.45303246053852
12.452981782685212
12.45293111607832
12.452880460715246
12.452829816593383
12.452779183710138
12.452728562062902
12.452677951649083
12.452627352466088
12.45257676451132
12.45252618778217
12.452475622276053
12.452425067990376
12.452374524922543
12.452323993069959
12.45227347243003
12.452222963000164
12.45217246477777
12.452121977760264
12.452071501945046
12.452021037329535
12.451970583911132
12.451920141687266
12.451869710655323
12.451819290812741
12.451768882156925
12.451718484685282
12.451668098395249
12.451617723284217
12.45156735934962
12.451517006588862
12.451466664999367
12.451416334578562
12.451366015323844
12.451315707232647
12.451265410302412
12.451215124530522
12.451164849914422
12.451114586451522
12.45106433413925
12.45101409297504
12.450963862956314
12.450913644080478
12.45086343634498
12.450813239747225
12.450763054284664
12.450712879954724
12.450662716754808
12.450612564682357
12.45056242373481
12.45051229390959
12.450462175204132
12.45041206761586
12.45036197114221
12.450311885780621
12.450261811528526
12.450211748383353
12.450161696342533
12.450111655403516
12.450061625563732
12.450011606820603
12.44996159917159
12.449911602614124
12.449861617145645
12.449811642763576
12.449761679465372
12.449711727248486
12.449661786110331
12.449611856048369
12.449561937060041
12.449512029142783
12.449462132294046
12.449412246511274
12.449362371791906
12.449312508133396
12.449262655533186
12.449212813988732
12.449162983497471
12.44911316405685
12.449063355664341
12.449013558317372
12.44896377201339
12.44891399674985
12.448864232524233
12.448814479333954
12.448764737176484
12.448715006049278
12.44866528594977
12.44861557687544
12.448565878823754
12.44851619179213
12.448466515778044
12.44841685077896
12.44836719679234
12.448317553815631
12.448267921846298
12.448218300881793
12.448168690919587
12.44811909195714
12.448069503991917
12.448019927021374
12.447970361042971
12.44792080605419
12.447871262052491
12.44782172903533
12.447772207000169
12.447722695944496
12.44767319586575
12.447623706761432
12.447574228628984
12.447524761465884
12.44747530526962
12.447425860037635
12.44737642576741
12.447327002456424
12.447277590102145
12.447228188702049
12.447178798253608
12.4471294187543
12.447080050201583
12.447030692592957
12.446981345925884
12.44693201019785
12.446882685406322
12.446833371548793
12.446784068622732
12.446734776625618
12.446685495554933
12.44663622540816
12.446586966182789
12.446537717876286
12.446488480486144
12.446439254009846
12.446390038444878
12.446340833788712
12.446291640038849
12.446242457192769
12.446193285247972
12.446144124201911
12.446094974052114
12.446045834796045
12.4459967064312
12.445947588955065
12.445898482365152
12.445849386658924
12.445800301833886
12.445751227887529
12.445702164817341
12.44565311262084
12.44560407129549
12.445555040838801
12.445506021248264
12.445457012521377
12.445408014655643
12.44535902764855
12.445310051497607
12.445261086200299
12.445212131754136
12.445163188156622
12.445114255405251
12.445065333497514
12.445016422430937
12.444967522203003
12.444918632811241
12.44486975425312
12.444820886526163
12.444772029627881
12.444723183555764
12.444674348307334
12.444625523880093
12.44457671027154
12.44452790747921
12.444479115500577
12.444430334333184
12.444381563974506
12.444332804422087
12.444284055673416
12.44423531772602
12.444186590577411
12.444137874225099
12.444089168666592
12.4440404738994
12.443991789921055
12.443943116729075
12.443894454320969
12.443845802694245
12.443797161846437
12.443748531775052
12.44369991247761
12.443651303951649
12.443602706194651
12.44355411920419
12.443505542977752
12.44345697751286
12.443408422807046
12.443359878857827
12.443311345662735
12.443262823219294
12.443214311525027
12.44316581057746
12.443117320374125
12.443068840912545
12.443020372190237
12.442971914204753
12.44292346695361
12.442875030434331
12.442826604644456
12.44277818958152
12.442729785243035
12.442681391626566
12.442633008729617
12.442584636549737
12.442536275084453
12.442487924331298
12.442439584287815
12.442391254951541
12.442342936320012
12.442294628390755
12.442246331161316
12.442198044629244
12.442149768792065
12.442101503647308
12.442053249192544
12.442005005425296
12.441956772343099
12.44190854994351
12.441860338224068
12.441812137182312
12.44176394681579
12.441715767122044
12.441667598098626
12.441619439743082
12.441571292052947
12.441523155025774
12.441475028659127
12.441426912950527
12.441378807897543
12.441330713497724
12.44128262974862
12.441234556647764
12.441186494192733
12.441138442381067
12.441090401210316
12.44104237067804
12.440994350781791
12.440946341519124
12.4408983428876
12.440850354884766
12.440802377508183
12.44075441075542
12.440706454624008
12.440658509111522
12.440610574215523
12.440562649933572
12.440514736263221
12.440466833202034
12.44041894074758
12.440371058897414
12.440323187649092
12.440275327000197
12.440227476948284
12.440179637490909
12.440131808625642
12.440083990350049
12.440036182661707
12.43998838555818
12.439940599037017
12.43989282309581
12.43984505773212
12.43979730294351
12.439749558727561
12.439701825081835
12.439654102003903
12.439606389491349
12.439558687541737
12.439510996152649
12.439463315321634
12.439415645046294
12.439367985324195
12.439320336152907
12.439272697530011
12.439225069453101
12.43917745191972
12.439129844927473
12.439082248473934
12.439034662556672
12.43898708717328
12.438939522321327
12.438891967998403
12.438844424202086
12.438796890929959
12.438749368179618
12.438701855948626
12.438654354234572
12.438606863035053
12.438559382347638
12.43851191216993
12.438464452499518
12.43841700333396
12.43836956467087
12.438322136507841
12.438274718842436
12.438227311672264
12.438179914994913
12.438132528807978
12.438085153109043
12.438037787895702
12.437990433165554
12.437943088916178
12.437895755145185
12.43784843185016
12.437801119028704
12.437753816678404
12.437706524796866
12.43765924338168
12.437611972430451
12.43756471194077
12.437517461910241
12.437470222336469
12.437422993217043
12.437375774549565

12.437328566331644
12.437281368560871
12.437234181234867
12.437187004351216
12.43713983790753
12.437092681901413
12.437045536330473
12.436998401192305
12.436951276484521
12.436904162204728
12.436857058350556
12.43680996491958
12.436762881909413
12.436715809317679
12.436668747141985
12.436621695379928
12.436574654029132
12.436527623087205
12.436480602551764
12.436433592420409
12.436386592690766
12.436339603360453
12.436292624427065
12.436245655888241
12.436198697741567
12.436151749984692
12.436104812615202
12.436057885630742
12.436010969028924
12.435964062807354
12.435917166963662
12.435870281495466
12.435823406400388
12.43577654167604
12.435729687320059
12.435682843330056
12.435636009703657
12.435589186438493
12.435542373532178
12.435495570982336
12.435448778786599
12.435401996942598
12.435355225447953
12.435308464300277
12.435261713497228
12.435214973036407
12.435168242915461
12.435121523132011
12.435074813683693
12.435028114568135
12.43498142578296
12.434934747325817
12.434888079194314
12.43484142138611
12.434794773898835
12.434748136730104
12.434701509877561
12.434654893338859
12.434608287111612
12.434561691193473
12.434515105582062
12.434468530275039
12.434421965270015
12.434375410564657
12.434328866156584
12.434282332043448
12.434235808222883
12.434189294692539
12.43414279145004
12.43409629849306
12.434049815819213
12.43400334342615
12.433956881311532
12.433910429472979
12.433863987908161
12.4338175566147
12.43377113559026
12.433724724832487
12.433678324339029
12.433631934107522
12.433585554135627
12.433539184420994
12.433492824961263
12.433446475754097
12.43340013679715
12.43335380808806
12.433307489624491
12.43326118140409
12.433214883424512
12.433168595683417
12.433122318178455
12.433076050907275
12.433029793867545
12.432983547056924
12.432937310473061
12.432891084113615
12.43284486797625
12.432798662058618
12.432752466358377
12.4327062808732
12.432660105600734
12.432613940538653
12.432567785684602
12.432521641036274
12.432475506591295
12.432429382347355
12.432383268302107
12.43233716445322
12.432291070798362
12.432244987335205
12.432198914061388
12.432152850974608
12.432106798072528
12.432060755352802
12.432014722813115
12.431968700451131
12.431922688264518
12.431876686250954
12.43183069440809
12.431784712733618
12.43173874122522
12.431692779880539
12.431646828697277
12.431600887673088
12.431554956805657
12.43150903609266
12.431463125531765
12.431417225120668
12.431371334857024
12.431325454738523
12.431279584762844
12.431233724927656
12.431187875230654
12.431142035669499
12.431096206241888
12.431050386945495
12.431004577778001
12.430958778737104
12.43091298982047
12.430867211025781
12.430821442350725
12.430775683793
12.430729935350275
12.430684197020236
12.430638468800595
12.430592750689009
12.430547042683175
12.430501344780781
12.430455656979523
12.430409979277087
12.430364311671148
12.43031865415943
12.43027300673959
12.430227369409343
12.430181742166367
12.430136125008353
12.430090517933023
12.430044920938037
12.429999334021097
12.429953757179915
12.429908190412176
12.429862633715574
12.429817087087816
12.429771550526578
12.429726024029584
12.429680507594519
12.429635001219083
12.429589504900974
12.429544018637895
12.429498542427552
12.429453076267636
12.429407620155864
12.429362174089933
12.429316738067538
12.42927131208638
12.429225896144182
12.429180490238648
12.429135094367465
12.42908970852835
12.42904433271901
12.428998966937145
12.428953611180479
12.428908265446701
12.428862929733528
12.42881760403868
12.42877228835986
12.428726982694771
12.42868168704113
12.428636401396663
12.428591125759052
12.42854586012604
12.428500604495305
12.428455358864612
12.428410123231632
12.428364897594097
12.428319681949725
12.42827447629623
12.42822928063133
12.428184094952734
12.428138919258172
12.42809375354535
12.428048597812007
12.428003452055844
12.427958316274601
12.427913190465974
12.427868074627705
12.427822968757505
12.427777872853103
12.427732786912214
12.427687710932574
12.427642644911897
12.42759758884791
12.42755254273834
12.42750750658092
12.427462480373364
12.427417464113415
12.427372457798784
12.427327461427206
12.427282474996408
12.427237498504132
12.427192531948101
12.427147575326035
12.427102628635671
12.427057691874746
12.42701276504099
12.426967848132145
12.42692294114592
12.426878044080075
12.426833156932325
12.426788279700423
12.426743412382088
12.426698554975076
12.426653707477106
12.426608869885904
12.42656404219925
12.426519224414848
12.426474416530452
12.426429618543793
12.426384830452616
12.426340052254654
12.426295283947674
12.42625052552938
12.426205776997538
12.42616103834989
12.426116309584167
12.426071590698145
12.426026881689536
12.425982182556089
12.425937493295566
12.425892813905701
12.425848144384238
12.42580348472894
12.425758834937543
12.425714195007798
12.42566956493745
12.425624944724257
12.425580334365966
12.425535733860327
12.425491143205097
12.425446562398028
12.425401991436862
12.425357430319355
12.425312879043254
12.425268337606347
12.42522380600635
12.425179284241038
12.425134772308159
12.425090270205477
12.425045777930745
12.42500129548172
12.424956822856162
12.424912360051827
12.424867907066481
12.424823463897868
12.424779030543766
12.424734607001929
12.424690193270115
12.424645789346096
12.424601395227619
12.42455701091246
12.424512636398386
12.424468271683143
12.424423916764525
12.424379571640262
12.424335236308146
12.424290910765942
12.4242465950114
12.424202289042304
12.424157992856413
12.424113706451495
12.424069429825334
12.424025162975685
12.423980905900313
12.423936658597015
12.42389242106354
12.423848193297662
12.423803975297158
12.423759767059808
12.423715568583377
12.42367137986564
12.423627200904363
12.423583031697333
12.423538872242341
12.423494722537132
12.423450582579497
12.42340645236722
12.423362331898074
12.423318221169836
12.423274120180285
12.423230028927199
12.42318594740837
12.423141875621559
12.42309781356457
12.423053761235165
12.423009718631148
12.422965685750283
12.422921662590353
12.422877649149159
12.422833645424463
12.42278965141408
12.422745667115766
12.422701692527328
12.42265772764655
12.4226137724712
12.422569826999087
12.422525891227997
12.42248196515572
12.422438048780034
12.422394142098739
12.422350245109616
12.422306357810479
12.422262480199095
12.422218612273266
12.422174754030785
12.42213090546945
12.42208706658705
12.422043237381384
12.421999417850232
12.421955607991405
12.421911807802703
12.421868017281897
12.421824236426824
12.421780465235251
12.421736703704982
12.421692951833828
12.421649209619568
12.421605477060027
12.421561754152988
12.421518040896263
12.421474337287638
12.421430643324936
12.421386959005936
12.421343284328463
12.421299619290311
12.421255963889287
12.421212318123192
12.421168681989826
12.421125055487012
12.421081438612557
12.42103783136424
12.420994233739894
12.420950645737323
12.420907067354328
12.420863498588734
12.42081993943832
12.420776389900938
12.420732849974373
12.420689319656447
12.420645798944953
12.420602287837719
12.420558786332567
12.420515294427286
12.420471812119716
12.420428339407646
12.420384876288919
12.420341422761332
12.420297978822697
12.420254544470856
12.420211119703593
12.42016770451875
12.420124298914141
12.420080902887586
12.420037516436889
12.419994139559888
12.419950772254404
12.419907414518251
12.419864066349241
12.419820727745217
12.419777398703987
12.419734079223387
12.41969076930122
12.419647468935343
12.419604178123544
12.419560896863674
12.419517625153551
12.419474362990998
12.419431110373846
12.419387867299923
12.419344633767059
12.419301409773079
12.419258195315814
12.419214990393096
12.419171795002754
12.419128609142613
12.419085432810501
12.419042266004276
12.41899910872174
12.418955960960735
12.418912822719108
12.41886969399468
12.418826574785276
12.418783465088767
12.418740364902954
12.418697274225678
12.418654193054794
12.418611121388116
12.4185680592235
12.418525006558783
12.418481963391791
12.418438929720361
12.41839590554236
12.418352890855608
12.41830988565795
12.418266889947217
12.41822390372127
12.418180926977948
12.418137959715072
12.418095001930517
12.418052053622107
12.41800911478769
12.417966185425115
12.417923265532227
12.417880355106874
12.41783745414691
12.417794562650153
12.41775168061448
12.417708808037734
12.41766594491775
12.417623091252397
12.417580247039517
12.417537412276959
12.417494586962565
12.41745177109421
12.41740896466972
12.417366167686968
12.417323380143797
12.417280602038057
12.417237833367619
12.417195074130325
12.41715232432403
12.41710958394659
12.417066852995864
12.41702413146971
12.416981419365989
12.41693871668255
12.416896023417246
12.41685333956796
12.416810665132529
12.416768000108824
12.416725344494708
12.416682698288028
12.416640061486659
12.416597434088455
12.416554816091278
12.41651220749302
12.416469608291488
12.416427018484605
12.416384438070192
12.416341867046143
12.416299305410305
12.416256753160553
12.416214210294767
12.416171676810787
12.416129152706496
12.416086637979769
12.416044132628446
12.416001636650442
12.415959150043593
12.41591667280578
12.415874204934868
12.415831746428744
12.415789297285265
12.415746857502306
12.415704427077749
12.415662006009459
12.415619594295316
12.415577191933197
12.415534798920955
12.415492415256502
12.41545004093768
12.415407675962381
12.4153653203285
12.41532297403388
12.415280637076425
12.415238309454
12.415195991164504
12.415153682205798
12.415111382575763
12.41506909227228
12.415026811293247
12.414984539636535
12.41494227730001
12.414900024281593
12.41485778057913
12.41481554619053
12.414773321113662
12.414731105346426
12.414688898886686
12.414646701732359
12.41460451388131
12.41456233533143
12.414520166080601
12.414478006126734
12.414435855467689
12.414393714101372
12.414351582025674
12.414309459238467
12.414267345737667
12.414225241521148
12.41418314658682
12.414141060932554
12.414098984556253
12.414056917455813
12.414014859629123

12.413972811074073
12.413930771788566
12.413888741770503
12.413846721017771
12.41380470952827
12.413762707299897
12.413720714330553
12.413678730618122
12.413636756160514
12.41359479095563
12.413552835001365
12.413510888295612
12.413468950836291
12.413427022621294
12.413385103648519
12.413343193915862
12.413301293421243
12.41325940216256
12.413217520137707
12.413175647344591
12.41313378378113
12.413091929445216
12.413050084334754
12.413008248447657
12.412966421781835
12.412924604335183
12.412882796105624
12.412840997091063
12.412799207289392
12.412757426698544
12.412715655316404
12.412673893140914
12.412632140169965
12.41259039640146
12.41254866183333
12.412506936463478
12.41246522028982
12.412423513310264
12.412381815522743
12.412340126925148
12.412298447515397
12.412256777291416
12.412215116251122
12.412173464392426
12.412131821713233
12.41209018821148
12.412048563885088
12.41200694873195
12.411965342750024
12.41192374593719
12.411882158291384
12.411840579810544
12.411799010492564
12.41175745033537
12.411715899336906
12.411674357495064
12.411632824807795
12.411591301273004
12.411549786888626
12.411508281652576
12.411466785562805
12.411425298617198
12.411383820813713
12.411342352150255
12.411300892624771
12.411259442235181
12.411218000979408
12.411176568855392
12.411135145861044
12.411093731994317
12.411052327253126
12.41101093163541
12.410969545139094
12.410928167762108
12.410886799502391
12.410845440357875
12.410804090326492
12.410762749406171
12.410721417594857
12.410680094890475
12.410638781290963
12.410597476794267
12.410556181398304
12.41051489510102
12.410473617900365
12.41043234979426
12.410391090780648
12.410349840857474
12.410308600022683
12.410267368274189
12.410226145609949
12.41018493202791
12.410143727526
12.410102532102169
12.410061345754364
12.41002016848052
12.409979000278584
12.409937841146496
12.409896691082201
12.409855550083643
12.409814418148773
12.409773295275546
12.409732181461887
12.409691076705755
12.409649981005096
12.409608894357854
12.40956781676198
12.409526748215432
12.409485688716144
12.409444638262075
12.409403596851181
12.409362564481393
12.409321541150687
12.409280526857001
12.409239521598284
12.40919852537251
12.409157538177608
12.409116560011542
12.409075590872268
12.409034630757724
12.408993679665905
12.408952737594726
12.408911804542164
12.408870880506173
12.408829965484705
12.408789059475735
12.408748162477202
12.408707274487071
12.408666395503303
12.408625525523854
12.408584664546702
12.408543812569773
12.408502969591062
12.408462135608515
12.408421310620106
12.40838049462378
12.408339687617511
12.408298889599275
12.408258100567004
12.408217320518695
12.408176549452305
12.408135787365783
12.408095034257125
12.408054290124277
12.408013554965201
12.407972828777886
12.407932111560283
12.40789140331037
12.407850704026117
12.407810013705472
12.407769332346449
12.407728659946981
12.40768799650506
12.407647342018645
12.40760669648572
12.407566059904244
12.407525432272204
12.407484813587562
12.407444203848298
12.40740360305239
12.40736301119781
12.407322428282539
12.407281854304552
12.407241289261806
12.407200733152312
12.407160185974018
12.407119647724926
12.407079118402986
12.407038598006213
12.40699808653257
12.406957583980022
12.406917090346573
12.406876605630195
12.406836129828868
12.40679566294057
12.4067552049633
12.406714755895026
12.406674315733751
12.40663388447743
12.406593462124068
12.406553048671638
12.406512644118147
12.406472248461554
12.406431861699868
12.406391483831056
12.406351114853122
12.406310754764052
12.406270403561827
12.406230061244438
12.406189727809881
12.406149403256148
12.406109087581218
12.406068780783084
12.406028482859742
12.405988193809192
12.40594791362941
12.4059076423184
12.405867379874156
12.40582712629466
12.40578688157792
12.405746645721921
12.405706418724677
12.405666200584157
12.405625991298376
12.40558579086532
12.405545599283004
12.405505416549406
12.405465242662533
12.405425077620382
12.405384921420964
12.405344774062257
12.405304635542274
12.405264505859025
12.405224385010493
12.405184272994688
12.405144169809608
12.405104075453274
12.40506398992366
12.405023913218791
12.404983845336671
12.404943786275291
12.404903736032674
12.40486369460681
12.40482366199571
12.404783638197376
12.404743623209827
12.404703617031075
12.404663619659107
12.404623631091933
12.404583651327588
12.404543680364052
12.404503718199356
12.404463764831496
12.404423820258495
12.40438388447836
12.404343957489097
12.404304039288725
12.404264129875255
12.404224229246708
12.40418433740108
12.404144454336404
12.404104580050676
12.404064714541937
12.404024857808178
12.403985009847423
12.403945170657702
12.403905340237015
12.40386551858339
12.403825705694835
12.403785901569375
12.403746106205038
12.403706319599829
12.403666541751775
12.403626772658892
12.403587012319216
12.403547260730752
12.403507517891528
12.403467783799565
12.403428058452887
12.403388341849524
12.403348633987484
12.403308934864807
12.403269244479512
12.403229562829624
12.403189889913167
12.403150225728183
12.403110570272665
12.403070923544677
12.403031285542228
12.402991656263353
12.402952035706067
12.402912423868422
12.402872820748424
12.402833226344125
12.40279364065354
12.402754063674703
12.402714495405654
12.402674935844423
12.402635384989031
12.402595842837512
12.402556309387922
12.402516784638271
12.40247726858661
12.402437761230955
12.402398262569365
12.40235877259986
12.40231929132047
12.402279818729246
12.402240354824226
12.402200899603443
12.402161453064938
12.402122015206745
12.402082586026909
12.40204316552346
12.402003753694448
12.401964350537908
12.401924956051886
12.401885570234422
12.401846193083557
12.401806824597335
12.401767464773798
12.40172811361099
12.40168877110695
12.401649437259733
12.401610112067374
12.401570795527926
12.401531487639433
12.401492188399928
12.401452897807483
12.401413615860134
12.401374342555911
12.401335077892892
12.401295821869107
12.401256574482616
12.401217335731454
12.401178105613688
12.401138884127361
12.401099671270517
12.401060467041216
12.401021271437518
12.400982084457457
12.400942906099099
12.400903736360494
12.40086457523969
12.400825422734753
12.400786278843734
12.400747143564677
12.400708016895656
12.400668898834715
12.400629789379913
12.400590688529316
12.400551596280962
12.400512512632929
12.40047343758327
12.400434371130043
12.400395313271298
12.40035626400511
12.400317223329537
12.400278191242627
12.400239167742457
12.400200152827084
12.400161146494563
12.400122148742973
12.400083159570368
12.400044178974802
12.400005206954344
12.399966243507068
12.399927288631039
12.399888342324322
12.399849404584975
12.399810475411066
12.399771554800665
12.399732642751847
12.399693739262673
12.399654844331199
12.399615957955518
12.399577080133684
12.399538210863769
12.399499350143843
12.39946049797198
12.399421654346257
12.399382819264732
12.399343992725484
12.39930517472659
12.399266365266119
12.39922756434214
12.399188771952732
12.399149988095967
12.399111212769931
12.399072445972681
12.399033687702309
12.398994937956873
12.398956196734481
12.39891746403318
12.398878739851064
12.398840024186203
12.39880131703667
12.398762618400571
12.39872392827596
12.398685246660923
12.398646573553536
12.398607908951897
12.398569252854077
12.398530605258152
12.398491966162219
12.398453335564348
12.398414713462623
12.398376099855128
12.398337494739968
12.3982988981152
12.398260309978918
12.398221730329215
12.398183159164171
12.398144596481863
12.3981060422804
12.39806749655786
12.398028959312322
12.397990430541887
12.397951910244629
12.39791339841865
12.397874895062039
12.397836400172887
12.39779791374928
12.397759435789306
12.397720966291063
12.397682505252655
12.397644052672144
12.397605608547646
12.39756717287725
12.397528745659045
12.397490326891127
12.397451916571606
12.397413514698552
12.39737512127008
12.397336736284275
12.397298359739239
12.397259991633081
12.397221631963872
12.397183280729719
12.39714493792874
12.397106603559015
12.397068277618649
12.397029960105739
12.39699165101839
12.396953350354702
12.396915058112764
12.396876774290694
12.3968384988866
12.396800231898562
12.396761973324695
12.39672372316311
12.396685481411895
12.396647248069165
12.396609023133028
12.396570806601574
12.39653259847293
12.396494398745187
12.396456207416454
12.396418024484845
12.396379849948463
12.39634168380541
12.396303526053812
12.396265376691762
12.396227235717365
12.396189103128753
12.39615097892402
12.396112863101282
12.396074755658647
12.396036656594235
12.395998565906144
12.395960483592496
12.395922409651407
12.395884344080992
12.395846286879356
12.395808238044614
12.395770197574889
12.395732165468285
12.395694141722933
12.395656126336934
12.395618119308425
12.395580120635495
12.395542130316288
12.395504148348898
12.395466174731473
12.395428209462112
12.395390252538931
12.39535230396006
12.395314363723616

12.395276431827725
12.395238508270507
12.395200593050069
12.39516268616455
12.395124787612064
12.39508689739075
12.395049015498714
12.395011141934079
12.394973276694987
12.394935419779548
12.394897571185888
12.394859730912135
12.394821898956426
12.394784075316867
12.394746259991598
12.394708452978742
12.394670654276437
12.394632863882808
12.394595081795982
12.394557308014079
12.394519542535237
12.39448178535759
12.394444036479264
12.39440629589839
12.394368563613105
12.394330839621531
12.394293123921807
12.39425541651208
12.394217717390452
12.394180026555091
12.394142344004104
12.394104669735633
12.394067003747818
12.394029346038792
12.393991696606701
12.393954055449674
12.393916422565834
12.393878797953345
12.393841181610325
12.393803573534925
12.393765973725277
12.393728382179516
12.39369079889579
12.393653223872244
12.393615657107008
12.393578098598217
12.393540548344031
12.393503006342579
12.39346547259201
12.393427947090464
12.39339042983609
12.393352920827013
12.393315420061393
12.393277927537373
12.393240443253106
12.393202967206719
12.393165499396368
12.393128039820201
12.393090588476372
12.393053145363012
12.393015710478275
12.392978283820307
12.39294086538727
12.392903455177299
12.392866053188547
12.392828659419163
12.392791273867296
12.392753896531108
12.392716527408739
12.392679166498343
12.392641813798079
12.39260446930609
12.392567133020533
12.392529804939556
12.392492485061323
12.392455173383992
12.39241786990571
12.392380574624625
12.392343287538898
12.392306008646699
12.39226873794616
12.392231475435459
12.392194221112746
12.392156974976182
12.392119737023908
12.392082507254106
12.392045285664928
12.392008072254532
12.391970867021064
12.391933669962722
12.391896481077628
12.391859300363963
12.391822127819887
12.39178496344356
12.39174780723315
12.39171065918681
12.391673519302717
12.39163638757902
12.391599264013893
12.3915621486055
12.391525041351999
12.391487942251569
12.391450851302377
12.391413768502572
12.391376693850336
12.391339627343836
12.391302568981232
12.391265518760695
12.391228476680396
12.391191442738519
12.391154416933208
12.391117399262646
12.391080389725
12.391043388318451
12.391006395041156
12.390969409891301
12.390932432867055
12.39089546396657
12.39085850318806
12.390821550529658
12.390784605989559
12.390747669565943
12.390710741256978
12.39067382106084
12.39063690897569
12.390600004999728
12.390563109131124
12.390526221368049
12.390489341708685
12.390452470151198
12.390415606693796
12.390378751334625
12.390341904071889
12.390305064903751
12.390268233828408
12.39023141084402
12.390194595948783
12.390157789140881
12.390120990418483
12.390084199779785
12.390047417222966
12.390010642746196
12.389973876347682
12.389937118025582
12.389900367778104
12.389863625603423
12.389826891499728
12.389790165465204
12.38975344749803
12.389716737596403
12.38968003575851
12.389643341982524
12.389606656266649
12.389569978609074
12.38953330900798
12.38949664746156
12.389459993968
12.389423348525499
12.389386711132241
12.389350081786414
12.38931346048622
12.38927684722984
12.389240242015472
12.389203644841313
12.389167055705554
12.389130474606374
12.38909390154199
12.38905733651059
12.389020779510357
12.388984230539505
12.38894768959621
12.388911156678688
12.388874631785123
12.388838114913707
12.388801606062664
12.388765105230169
12.388728612414413
12.38869212761362
12.38865565082597
12.388619182049673
12.388582721282932
12.388546268523939
12.388509823770901
12.388473387022012
12.388436958275488
12.388400537529508
12.388364124782296
12.388327720032047
12.388291323276972
12.388254934515261
12.38821855374513
12.388182180964785
12.388145816172422
12.388109459366259
12.388073110544488
12.388036769705327
12.388000436846974
12.387964111967644
12.387927795065545
12.387891486138885
12.387855185185861
12.387818892204697
12.387782607193607
12.387746330150785
12.387710061074445
12.387673799962807
12.38763754681408
12.387601301626455
12.387565064398176
12.38752883512744
12.387492613812464
12.387456400451457
12.387420195042633
12.387383997584216
12.387347808074404
12.387311626511428
12.387275452893496
12.387239287218827
12.38720312948563
12.38716697969214
12.387130837836551
12.387094703917091
12.387058577931986
12.387022459879448
12.386986349757692
12.386950247564942
12.386914153299426
12.386878066959344
12.386841988542932
12.38680591804841
12.386769855473991
12.386733800817918
12.38669775407838
12.386661715253634
12.386625684341885
12.386589661341352
12.386553646250276
12.386517639066865
12.386481639789354
12.386445648415972
12.386409664944932
12.386373689374475
12.386337721702812
12.38630176192818
12.386265810048807
12.386229866062916
12.38619392996873
12.386158001764505
12.386122081448434
12.38608616901877
12.386050264473734
12.38601436781156
12.385978479030479
12.385942598128725
12.385906725104524
12.385870859956107
12.38583500268171
12.38579915327957
12.385763311747912
12.385727478084977
12.385691652289003
12.385655834358204
12.385620024290839
12.38558422208514
12.385548427739327
12.385512641251642
12.385476862620335
12.385441091843635
12.38540532891977
12.385369573846996
12.385333826623546
12.385298087247639
12.38526235571754
12.38522663203148
12.385190916187701
12.385155208184447
12.38511950801994
12.385083815692441
12.385048131200186
12.385012454541418
12.384976785714374
12.384941124717308
12.384905471548462
12.38486982620606
12.384834188688364
12.384798558993621
12.384762937120067
12.384727323065968
12.384691716829538
12.384656118409042
12.384620527802724
12.384584945008838
12.384549370025617
12.384513802851316
12.3844782434842
12.384442691922496
12.384407148164453
12.384371612208337
12.384336084052375
12.384300563694847
12.38426505113398
12.384229546368038
12.384194049395271
12.384158560213933
12.384123078822265
12.384087605218532
12.384052139400978
12.38401668136787
12.383981231117449
12.38394578864798
12.383910353957708
12.383874927044905
12.383839507907812
12.383804096544692
12.383768692953794
12.38373329713339
12.383697909081723
12.383662528797057
12.38362715627765
12.383591791521761
12.383556434527643
12.383521085293577
12.383485743817806
12.383450410098582
12.383415084134196
12.38337976592287
12.383344455462899
12.383309152752526
12.383273857790025
12.383238570573656
12.383203291101662
12.383168019372345
12.383132755383945
12.383097499134735
12.383062250622963
12.383027009846924
12.382991776804866
12.38295655149505
12.382921333915748
12.38288612406524
12.382850921941772
12.382815727543637
12.382780540869076
12.382745361916378
12.382710190683806
12.382675027169615
12.382639871372108
12.382604723289532
12.382569582920153
12.382534450262254
12.382499325314113
12.382464208073985
12.382429098540154
12.382393996710887
12.382358902584466
12.38232381615916
12.382288737433237
12.382253666404978
12.382218603072651
12.38218354743455
12.382148499488926
12.382113459234066
12.382078426668256
12.382043401789769
12.38200838459687
12.381973375087844
12.381938373260974
12.381903379114531
12.381868392646794
12.38183341385605
12.381798442740577
12.381763479298654
12.381728523528556
12.38169357542858
12.381658634996985
12.381623702232073
12.381588777132112
12.381553859695389
12.381518949920196
12.381484047804816
12.381449153347518
12.381414266546583
12.381379387400314
12.381344515906997
12.381309652064912
12.381274795872342
12.381239947327566
12.381205106428885
12.381170273174588
12.38113544756294
12.38110062959225
12.381065819260801
12.381031016566892
12.380996221508783
12.380961434084796
12.380926654293201
12.38089188213231
12.380857117600371
12.380822360695719
12.38078761141663
12.380752869761393
12.380718135728308
12.380683409315662
12.380648690521737
12.380613979344863
12.380579275783303
12.380544579835341
12.380509891499312
12.38047521077347
12.38044053765614
12.380405872145603
12.38037121424016
12.38033656393812
12.380301921237754
12.380267286137386
12.380232658635286
12.380198038729779
12.38016342641916
12.380128821701717
12.380094224575751
12.380059635039576
12.380025053091472
12.379990478729756
12.379955911952733
12.379921352758684
12.379886801145927
12.379852257112756
12.37981772065747
12.379783191778406
12.379748670473822
12.379714156742045
12.379679650581378
12.379645151990143
12.379610660966602
12.379576177509099
12.379541701615931
12.379507233285407
12.379472772515811
12.379438319305478
12.379403873652695
12.379369435555795
12.37933500501307
12.379300582022816
12.379266166583376
12.379231758693036
12.379197358350105
12.379162965552899
12.379128580299742
12.379094202588922
12.379059832418761
12.379025469787582
12.378991114693688
12.378956767135387
12.378922427111007
12.378888094618839
12.378853769657209
12.378819452224443
12.37878514231884
12.378750839938727
12.378716545082415
12.37868225774821
12.378647977934442
12.378613705639426
12.378579440861474
12.378545183598913
12.378510933850043
12.378476691613205
12.378442456886702
12.378408229668866
12.378374009958005
12.37833979775245
12.3783055930505
12.378271395850506
12.37823720615076
12.378203023949622
12.378168849245368
12.37813468203636
12.378100522320889
12.378066370097304
12.378032225363915
12.37799808811905
12.377963958361033
12.377929836088189
12.377895721298835
12.377861613991321
12.377827514163931
12.377793421815033
12.377759336942939
12.377725259545976
12.377691189622473
12.377657127170746
12.377623072189147
12.377589024675975
12.377554984629597
12.377520952048311
12.377486926930453
12.377452909274352
12.37741889907836
12.377384896340795
12.377350901059968
12.377316913234239
12.37728293286193
12.377248959941381
12.37721499447092
12.377181036448873
12.377147085873586
12.377113142743381
12.377079207056605
12.377045278811586
12.37701135800666
12.376977444640163
12.376943538710448
12.376909640215816
12.376875749154642
12.376841865525229
12.376807989325945
12.37677412055511
12.376740259211077
12.376706405292172
12.376672558796727
12.3766387197231
12.37660488806963
12.376571063834655
12.376537247016513
12.376503437613543
12.37646963562408
12.376435841046487
12.376402053879097
12.376368274120251
12.376334501768296
12.376300736821563
12.37626697927842
12.376233229137187
12.376199486396228
12.376165751053867
12.376132023108486
12.376098302558379
12.37606458940194
12.37603088363749
12.375997185263397
12.375963494277975
12.375929810679615
12.375896134466625
12.375862465637383
12.375828804190224
12.375795150123492
12.375761503435553
12.375727864124755
12.375694232189442
12.375660607627964
12.375626990438679
12.37559338061994
12.375559778170086
12.375526183087485
12.375492595370476
12.37545901501743
12.375425442026698
12.375391876396609
12.375358318125555
12.375324767211868
12.375291223653901
12.37525768745002
12.375224158598582
12.37519063709794
12.375157122946453
12.375123616142467
12.375090116684353
12.37505662457047
12.375023139799172
12.37498966236881
12.374956192277763
12.374922729524377
12.374889274107007
12.374855826024026
12.374822385273783
12.374788951854656
12.374755525764991
12.374722107003153
12.374688695567515
12.37465529145643
12.374621894668257
12.374588505201368
12.374555123054131
12.374521748224897
12.374488380712046
12.37445502051393
12.37442166762892
12.374388322055381
12.374354983791681
12.374321652836187
12.374288329187255
12.374255012843278
12.374221703802592
12.374188402063591
12.37415510762463

12.374121820484081
12.374088540640313
12.374055268091698
12.37402200283661
12.373988744873412
12.373955494200478
12.373922250816172
12.373889014718875
12.37385578590696
12.373822564378791
12.373789350132745
12.373756143167205
12.373722943480532
12.373689751071097
12.373656565937281
12.373623388077466
12.373590217490017
12.373557054173315
12.37352389812573
12.373490749345637
12.373457607831423
12.373424473581462
12.373391346594115
12.373358226867783
12.373325114400833
12.37329200919164
12.373258911238597
12.373225820540073
12.373192737094445
12.373159660900098
12.373126591955405
12.37309353025876
12.373060475808538
12.373027428603127
12.372994388640885
12.372961355920225
12.372928330439512
12.372895312197128
12.372862301191473
12.372829297420912
12.37279630088383
12.372763311578636
12.372730329503684
12.372697354657387
12.3726643870381
12.37263142664424
12.372598473474172
12.372565527526293
12.372532588798995
12.37249965729065
12.372466732999658
12.372433815924392
12.37240090606327
12.37236800341466
12.372335107976953
12.372302219748539
12.372269338727811
12.372236464913172
12.372203598302987
12.37217073889567
12.372137886689599
12.372105041683177
12.372072203874785
12.372039373262822
12.37200654984568
12.371973733621758
12.371940924589454
12.371908122747142
12.371875328093234
12.371842540626126
12.371809760344199
12.37177698724586
12.371744221329507
12.371711462593542
12.371678711036347
12.371645966656322
12.371613229451876
12.37158049942139
12.37154777656329
12.371515060875936
12.37148235235777
12.37144965100716
12.37141695682252
12.371384269802254
12.371351589944753
12.37131891724842
12.371286251711659
12.371253593332868
12.371220942110451
12.371188298042824
12.37115566112837
12.371123031365514
12.37109040875264
12.371057793288161
12.371025184970478
12.370992583798001
12.370959989769132
12.370927402882288
12.370894823135842
12.370862250528234
12.370829685057863
12.37079712672314
12.37076457552245
12.370732031454237
12.370699494516872
12.370666964708796
12.370634442028397
12.370601926474082
12.370569418044283
12.370536916737393
12.370504422551823
12.370471935485995
12.370439455538307
12.370406982707179
12.370374516991022
12.370342058388259
12.37030960689727
12.370277162516498
12.370244725244351
12.370212295079236
12.37017987201958
12.370147456063783
12.370115047210266
12.370082645457444
12.370050250803747
12.370017863247556
12.36998548278732
12.369953109421454
12.369920743148356
12.369888383966462
12.369856031874177
12.369823686869923
12.369791348952127
12.3697590181192
12.369726694369563
12.36969437770163
12.369662068113843
12.369629765604602
12.369597470172334
12.369565181815451
12.369532900532388
12.369500626321564
12.36946835918141
12.369436099110322
12.369403846106763
12.369371600169112
12.369339361295827
12.369307129485318
12.36927490473601
12.369242687046336
12.369210476414716
12.369178272839568
12.369146076319325
12.369113886852427
12.369081704437281
12.369049529072322
12.36901736075598
12.368985199486676
12.368953045262847
12.368920898082916
12.36888875794532
12.36885662484847
12.368824498790811
12.368792379770781
12.368760267786795
12.36872816283729
12.368696064920698
12.36866397403544
12.368631890179966
12.368599813352697
12.368567743552079
12.368535680776525
12.36850362502448
12.368471576294372
12.36843953458465
12.368407499893726
12.368375472220059
12.368343451562065
12.368311437918196
12.368279431286876
12.368247431666545
12.368215439055641
12.368183453452604
12.368151474855855
12.36811950326386
12.368087538675033
12.368055581087825
12.368023630500673
12.367991686912013
12.367959750320296
12.367927820723947
12.36789589812141
12.367863982511132
12.367832073891558
12.367800172261108
12.367768277618255
12.36773638996142
12.367704509289048
12.367672635599591
12.367640768891478
12.36760890916316
12.367577056413088
12.367545210639703
12.367513371841442
12.36748154001676
12.367449715164103
12.367417897281905
12.367386086368626
12.367354282422705
12.367322485442584
12.367290695426723
12.367258912373567
12.367227136281555
12.367195367149153
12.367163604974797
12.36713184975693
12.367100101494009
12.367068360184494
12.367036625826817
12.367004898419443
12.366973177960814
12.366941464449384
12.366909757883615
12.366878058261944
12.366846365582827
12.366814679844728
12.366783001046086
12.36675132918537
12.366719664261014
12.36668800627149
12.36665635521523
12.36662471109072
12.366593073896391
12.36656144363071
12.366529820292143
12.366498203879129
12.36646659439012
12.366434991823587
12.366403396177988
12.366371807451772
12.366340225643407
12.366308650751355
12.366277082774058
12.366245521709992
12.366213967557593
12.366182420315347
12.366150879981701
12.366119346555125
12.366087820034073
12.366056300417007
12.3660247877024
12.36599328188869
12.36596178297436
12.365930290957866
12.365898805837677
12.365867327612246
12.365835856280048
12.36580439183954
12.365772934289193
12.365741483627453
12.365710039852821
12.365678602963735
12.365647172958676
12.365615749836088
12.36558433359447
12.365552924232263
12.365521521747944
12.365490126139985
12.365458737406858
12.36542735554701
12.365395980558935
12.36536461244108
12.365333251191938
12.365301896809965
12.36527054929364
12.36523920864143
12.365207874851787
12.365176547923216
12.365145227854168
12.365113914643123
12.365082608288558
12.36505130878892
12.36502001614271
12.364988730348394
12.364957451404456
12.364926179309347
12.36489491406156
12.364863655659564
12.36483240410183
12.364801159386838
12.364769921513071
12.364738690479
12.364707466283095
12.36467624892385
12.364645038399729
12.364613834709207
12.364582637850773
12.364551447822912
12.364520264624076
12.364489088252776
12.36445791870746
12.364426755986633
12.36439560008877
12.36436445101235
12.36433330875585
12.364302173317753
12.36427104469655
12.364239922890711
12.364208807898725
12.364177699719072
12.364146598350233
12.364115503790703
12.364084416038962
12.364053335093478
12.364022260952764
12.363991193615279
12.363960133079521
12.363929079343974
12.363898032407121
12.363866992267459
12.36383595892347
12.36380493237363
12.363773912616438
12.363742899650383
12.36371189347394
12.36368089408561
12.363649901483878
12.36361891566725
12.363587936634172
12.36355696438318
12.363525998912753
12.363495040221363
12.363464088307513
12.363433143169692
12.363402204806402
12.36337127321612
12.363340348397355
12.363309430348586
12.36327851906831
12.36324761455502
12.363216716807218
12.363185825823376
12.363154941602021
12.363124064141626
12.363093193440688
12.363062329497707
12.363031472311182
12.363000621879596
12.362969778201458
12.362938941275273
12.362908111099514
12.362877287672696
12.362846470993318
12.362815661059871
12.362784857870844
12.362754061424758
12.362723271720114
12.362692488755393
12.3626617125291
12.362630943039736
12.362600180285805
12.36256942426582
12.362538674978264
12.362507932421634
12.362477196594446
12.362446467495214
12.362415745122414
12.362385029474575
12.362354320550184
12.362323618347734
12.362292922865754
12.362262234102742
12.36223155205721
12.362200876727629
12.362170208112543
12.362139546210445
12.36210889101985
12.362078242539248
12.362047600767154
12.362016965702066
12.361986337342504
12.361955715686987
12.361925100734007
12.361894492482069
12.361863890929685
12.361833296075382
12.361802707917652
12.36177212645501
12.361741551685963
12.361710983609024
12.36168042222271
12.361649867525527
12.361619319515988
12.361588778192605
12.361558243553892
12.36152771559837
12.361497194324535
12.361466679730913
12.361436171816026
12.361405670578353
12.361375176016454
12.361344688128817
12.36131420691396
12.361283732370406
12.361253264496666
12.361222803291263
12.361192348752711
12.36116190087951
12.36113145967021
12.361101025123302
12.361070597237315
12.361040176010775
12.361009761442176
12.360979353530068
12.360948952272944
12.360918557669354
12.360888169717791
12.360857788416778
12.36082741376486
12.360797045760528
12.360766684402325
12.36073632968876
12.360705981618366
12.360675640189655
12.360645305401157
12.3606149772514
12.360584655738897
12.360554340862171
12.360524032619754
12.36049373101018
12.36046343603195
12.360433147683612
12.360402865963673
12.36037259087068
12.360342322403138
12.360312060559588
12.360281805338548
12.360251556738548
12.360221314758133
12.360191079395806
12.360160850650107
12.360130628519567
12.360100413002714
12.360070204098067
12.360040001804173
12.360009806119544
12.359979617042724
12.359949434572245
12.359919258706629
12.35988908944442
12.359858926784137
12.359828770724311
12.35979862126349
12.359768478400188
12.359738342132957
12.359708212460323
12.359678089380813
12.359647972892969
12.359617862995332
12.359587759686413
12.359557662964782
12.359527572828943
12.359497489277452
12.359467412308828
12.359437341921637
12.359407278114386
12.35937722088562
12.359347170233887
12.359317126157716
12.359287088655645
12.35925705772622
12.359227033367976

12.359197015579449
12.359167004359184
12.35913699970572
12.359107001617605
12.359077010093351
12.359047025131535
12.359017046730674
12.358987074889331
12.358957109606026
12.35892715087931
12.358897198707735
12.35886725308983
12.35883731402415
12.358807381509234
12.358777455543619
12.358747536125863
12.358717623254508
12.358687716928085
12.358657817145158
12.358627923904256
12.358598037203945
12.358568157042754
12.358538283419243
12.358508416331942
12.358478555779417
12.358448701760206
12.358418854272864
12.358389013315932
12.358359178887955
12.3583293509875
12.3582995296131
12.358269714763315
12.35823990643669
12.358210104631768
12.358180309347121
12.358150520581283
12.358120738332804
12.358090962600253
12.358061193382161
12.358031430677093
12.358001674483601
12.357971924800246
12.357942181625559
12.357912444958114
12.35788271479646
12.35785299113915
12.357823273984742
12.35779356333179
12.357763859178839
12.357734161524464
12.357704470367208
12.357674785705635
12.357645107538296
12.357615435863746
12.357585770680556
12.357556111987272
12.357526459782457
12.357496814064664
12.357467174832452
12.3574375420844
12.357407915819042
12.357378296034945
12.35734868273068
12.357319075904798
12.357289475555861
12.357259881682422
12.357230294283065
12.357200713356335
12.3571711389008
12.35714157091502
12.357112009397552
12.357082454346981
12.357052905761838
12.35702336364072
12.356993827982173
12.356964298784758
12.356934776047046
12.356905259767611
12.356875749944997
12.356846246577803
12.356816749664569
12.356787259203863
12.35675777519426
12.356728297634328
12.356698826522633
12.35666936185773
12.356639903638214
12.356610451862625
12.35658100652955
12.35655156763755
12.356522135185202
12.356492709171073
12.356463289593737
12.35643387645175
12.356404469743694
12.35637506946814
12.356345675623661
12.356316288208825
12.356286907222213
12.356257532662385
12.35622816452792
12.356198802817385
12.35616944752937
12.356140098662433
12.35611075621515
12.356081420186097
12.356052090573865
12.35602276737701
12.35599345059411
12.35596414022374
12.355934836264474
12.355905538714909
12.35587624757361
12.35584696283914
12.355817684510095
12.35578841258504
12.355759147062562
12.355729887941239
12.355700635219646
12.355671388896369
12.355642148969968
12.355612915439057
12.355583688302174
12.355554467557935
12.355525253204908
12.355496045241669
12.355466843666802
12.355437648478901
12.355408459676536
12.355379277258297
12.355350101222747
12.3553209315685
12.355291768294107
12.355262611398183
12.355233460879283
12.355204316736014
12.355175178966952
12.355146047570676
12.355116922545784
12.355087803890859
12.35505869160448
12.355029585685237
12.355000486131713
12.354971392942497
12.35494230611619
12.354913225651364
12.35488415154661
12.354855083800512
12.354826022411665
12.354796967378668
12.354767918700093
12.354738876374531
12.354709840400584
12.354680810776832
12.35465178750187
12.354622770574288
12.354593759992683
12.354564755755629
12.35453575786174
12.354506766309594
12.354477781097795
12.354448802224928
12.354419829689578
12.354390863490348
12.354361903625845
12.354332950094637
12.35430400289534
12.354275062026533
12.354246127486821
12.354217199274801
12.354188277389063
12.354159361828202
12.35413045259082
12.354101549675509
12.354072653080866
12.354043762805501
12.354014878847988
12.35398600120695
12.353957129880984
12.35392826486866
12.353899406168608
12.35387055377942
12.353841707699676
12.353812867927996
12.353784034462985
12.353755207303216
12.353726386447331
12.353697571893898
12.353668763641535
12.353639961688836
12.353611166034403
12.353582376676854
12.353553593614766
12.353524816846761
12.353496046371436
12.3534672821874
12.353438524293253
12.353409772687602
12.353381027369046
12.3533522883362
12.353323555587655
12.353294829122046
12.353266108937937
12.353237395033966
12.353208687408742
12.353179986060855
12.353151290988906
12.35312260219153
12.35309391966731
12.353065243414864
12.353036573432812
12.353007909719748
12.352979252274293
12.352950601095035
12.35292195618061
12.352893317529604
12.352864685140661
12.35283605901236
12.35280743914333
12.352778825532171
12.352750218177507
12.352721617077943
12.352693022232085
12.352664433638568
12.352635851295988
12.352607275202951
12.352578705358091
12.35255014176001
12.35252158440733
12.352493033298666
12.35246448843261
12.352435949807816
12.352407417422873
12.352378891276395
12.352350371367026
12.35232185769335
12.352293350254007
12.3522648490476
12.352236354072755
12.352207865328088
12.352179382812217
12.352150906523756
12.352122436461338
12.35209397262356
12.352065515009066
12.352037063616462
12.35200861844438
12.351980179491413
12.351951746756221
12.35192332023739
12.35189489993357
12.351866485843352
12.351838077965391
12.351809676298286
12.35178128084068
12.35175289159118
12.351724508548388
12.351696131710984
12.351667761077554
12.351639396646734
12.351611038417124
12.351582686387397
12.351554340556133
12.351526000921979
12.351497667483567
12.351469340239507
12.351441019188435
12.351412704328974
12.351384395659753
12.351356093179403
12.351327796886544
12.351299506779814
12.351271222857827
12.35124294511923
12.351214673562644
12.351186408186694
12.351158148990015
12.35112989597124
12.351101649128994
12.351073408461907
12.351045173968615
12.351016945647743
12.350988723497926
12.350960507517796
12.350932297705995
12.350904094061129
12.350875896581867
12.350847705266817
12.35081952011461
12.350791341123896
12.350763168293307
12.350735001621468
12.350706841107021
12.350678686748596
12.350650538544835
12.350622396494366
12.350594260595832
12.350566130847874
12.35053800724911
12.35050988979819
12.350481778493746
12.350453673334432
12.35042557431887
12.350397481445707
12.350369394713566
12.350341314121097
12.350313239666942
12.350285171349736
12.35025710916812
12.350229053120737
12.350201003206227
12.350172959423226
12.350144921770376
12.350116890246323
12.350088864849708
12.35006084557916
12.350032832433348
12.350004825410887
12.349976824510438
12.349948829730637
12.34992084107014
12.349892858527575
12.349864882101587
12.349836911790822
12.349808947593933
12.349780989509563
12.349753037536345
12.349725091672939
12.349697151917999
12.349669218270138
12.349641290728043
12.34961336929033
12.349585453955656
12.349557544722682
12.349529641590044
12.34950174455638
12.349473853620365
12.349445968780618
12.349418090035801
12.349390217384588
12.349362350825588
12.349334490357483
12.349306635978898
12.349278787688503
12.349250945484936
12.34922310936686
12.349195279332925
12.349167455381773
12.349139637512062
12.349111825722451
12.349084020011585
12.349056220378122
12.3490284268207
12.349000639337998
12.348972857928672
12.34894508259134
12.34891731332469
12.348889550127366
12.348861792998013
12.348834041935314
12.348806296937909
12.348778558004451
12.348750825133589
12.348723098324008
12.348695377574344
12.348667662883255
12.348639954249403
12.348612251671454
12.348584555148053
12.348556864677867
12.34852918025955
12.348501501891771
12.348473829573175
12.348446163302437
12.348418503078205
12.34839084889915
12.348363200763927
12.348335558671193
12.348307922619627
12.348280292607875
12.348252668634599
12.348225050698474
12.34819743879815
12.348169832932292
12.348142233099578
12.34811463929865
12.348087051528182
12.348059469786847
12.348031894073292
12.348004324386201
12.347976760724224
12.347949203086031
12.347921651470301
12.347894105875678
12.34786656630084
12.34783903274446
12.347811505205197
12.347783983681715
12.34775646817269
12.347728958676779
12.347701455192656
12.347673957719008
12.347646466254487
12.34761898079775
12.34759150134749
12.347564027902356
12.347536560461036
12.347509099022188
12.347481643584498
12.347454194146627
12.347426750707239
12.34739931326501
12.347371881818633
12.347344456366747
12.347317036908043
12.347289623441194
12.347262215964875
12.347234814477744
12.347207418978495
12.347180029465793
12.347152645938316
12.347125268394729
12.347097896833722
12.347070531253953
12.347043171654109
12.347015818032865
12.346988470388903
12.346961128720887
12.346933793027496
12.346906463307413
12.346879139559325
12.346851821781883
12.346824509973795
12.34679720413371
12.34676990426033
12.346742610352328
12.346715322408372
12.346688040427162
12.346660764407359
12.34663349434766
12.34660623024673
12.346578972103261
12.34655171991592
12.34652447368341
12.346497233404385
12.346469999077556
12.3464427707016
12.346415548275168
12.346388331796996
12.346361121265723
12.346333916680043
12.346306718038655
12.346279525340226
12.34625233858345
12.346225157767005
12.346197982889604
12.34617081394988
12.346143650946564
12.346116493878316
12.346089342743841
12.34606219754181
12.346035058270925
12.346007924929857
12.345980797517308
12.34595367603195
12.345926560472487
12.3458994508376
12.345872347125976
12.34584524933631
12.345818157467285
12.3457910715176

12.345763991485924
12.345736917370964
12.34570984917142
12.345682786885966
12.345655730513295
12.34562868005211
12.345601635501081
12.345574596858928
12.34554756412431
12.345520537295958
12.345493516372528
12.345466501352744
12.345439492235283
12.345412489018841
12.345385491702114
12.345358500283794
12.34533151476257
12.345304535137153
12.345277561406233
12.345250593568496
12.345223631622643
12.34519667556737
12.345169725401384
12.345142781123364
12.345115842732014
12.345088910226039
12.345061983604122
12.345035062864982
12.3450081480073
12.344981239029782
12.344954335931117
12.344927438710023
12.344900547365183
12.344873661895296
12.344846782299085
12.34481990857522
12.344793040722426
12.344766178739384
12.344739322624813
12.344712472377402
12.344685627995855
12.34465878947887
12.344631956825175
12.344605130033438
12.34457830910239
12.344551494030716
12.344524684817122
12.344497881460327
12.34447108395901
12.344444292311906
12.344417506517692
12.344390726575085
12.344363952482794
12.344337184239524
12.344310421843973
12.344283665294853
12.344256914590865
12.344230169730741
12.344203430713153
12.344176697536822
12.344149970200473
12.344123248702784
12.344096533042478
12.344069823218275
12.344043119228864
12.344016421072968
12.343989728749294
12.343963042256542
12.343936361593439
12.343909686758684
12.34388301775099
12.343856354569061
12.343829697211628
12.343803045677388
12.34377639996505
12.343749760073335
12.343723126000954
12.343696497746619
12.343669875309038
12.343643258686939
12.34361664787901
12.343590042883994
12.343563443700582
12.343536850327508
12.343510262763472
12.343483681007193
12.343457105057398
12.343430534912782
12.343403970572076
12.343377412033993
12.343350859297253
12.34332431236057
12.343297771222657
12.343271235882236
12.343244706338023
12.343218182588739
12.343191664633103
12.343165152469826
12.343138646097639
12.343112145515253
12.34308565072138
12.343059161714757
12.343032678494101
12.34300620105812
12.342979729405556
12.342953263535104
12.342926803445506
12.34290034913547
12.342873900603733
12.342847457848999
12.342821020870007
12.342794589665461
12.342768164234112
12.342741744574653
12.34271533068583
12.34268892256636
12.342662520214962
12.342636123630365
12.342609732811292
12.342583347756483
12.34255696846464
12.342530594934496
12.34250422716479
12.34247786515423
12.342451508901558
12.342425158405492
12.342398813664754
12.342372474678097
12.342346141444217
12.342319813961868
12.342293492229748
12.342267176246628
12.342240866011192
12.342214561522193
12.342188262778366
12.342161969778433
12.342135682521114
12.342109401005159
12.342083125229287
12.34205685519223
12.342030590892723
12.342004332329491
12.341978079501272
12.3419518324068
12.341925591044797
12.341899355414
12.341873125513155
12.34184690134097
12.341820682896218
12.341794470177575
12.341768263183825
12.341742061913694
12.341715866365897
12.341689676539183
12.341663492432293
12.341637314043943
12.341611141372885
12.341584974417847
12.341558813177583
12.341532657650804
12.341506507836266
12.341480363732693
12.34145422533883
12.34142809265342
12.34140196567519
12.341375844402886
12.341349728835246
12.341323618971012
12.341297514808911
12.341271416347698
12.341245323586099
12.341219236522866
12.341193155156736
12.341167079486452
12.34114100951075
12.34111494522837
12.341088886638046
12.341062833738553
12.341036786528601
12.341010745006937
12.340984709172325
12.340958679023478
12.340932654559166
12.340906635778113
12.340880622679077
12.340854615260787
12.340828613522005
12.340802617461469
12.340776627077922
12.340750642370104
12.340724663336765
12.340698689976659
12.340672722288533
12.340646760271117
12.340620803923175
12.340594853243442
12.340568908230672
12.340542968883618
12.34051703520101
12.34049110718161
12.340465184824165
12.34043926812743
12.340413357090135
12.340387451711052
12.340361551988918
12.34033565792249
12.340309769510501
12.34028388675173
12.3402580096449
12.340232138188771
12.340206272382112
12.340180412223647
12.340154557712152
12.340128708846366
12.34010286562504
12.340077028046936
12.3400511961108
12.340025369815393
12.339999549159467
12.339973734141768
12.339947924761045
12.339922121016073
12.33989632290559
12.339870530428373
12.33984474358315
12.339818962368676
12.339793186783735
12.339767416827069
12.339741652497436
12.339715893793581
12.339690140714278
12.339664393258273
12.33963865142433
12.339612915211202
12.339587184617653
12.339561459642438
12.33953574028432
12.339510026542046
12.339484318414389
12.33945861590011
12.339432918997955
12.339407227706683
12.339381542025082
12.339355861951883
12.339330187485867
12.33930451862577
12.339278855370386
12.339253197718463
12.339227545668756
12.33920189922003
12.33917625837105
12.339150623120583
12.33912499346739
12.339099369410238
12.33907375094788
12.33904813807909
12.339022530802634
12.338996929117268
12.338971333021762
12.33894574251488
12.338920157595386
12.338894578262053
12.338869004513647
12.338843436348924
12.338817873766667
12.338792316765613
12.338766765344557
12.338741219502271
12.338715679237499
12.338690144549023
12.338664615435606
12.338639091896026
12.338613573929045
12.33858806153344
12.338562554707966
12.338537053451397
12.338511557762509
12.338486067640071
12.338460583082854
12.338435104089635
12.338409630659164
12.338384162790234
12.338358700481612
12.338333243732075
12.338307792540371
12.3382823469053
12.338256906825624
12.338231472300109
12.338206043327538
12.338180619906682
12.338155202036331
12.33812978971523
12.338104382942168
12.338078981715924
12.338053586035276
12.33802819589898
12.338002811305836
12.337977432254602
12.337952058744055
12.337926690772985
12.337901328340157
12.33787597144435
12.33785062008435
12.337825274258922
12.337799933966856
12.33777459920692
12.3377492699779
12.33772394627856
12.337698628107706
12.3376733154641
12.337648008346513
12.337622706753754
12.33759741068457
12.337572120137766
12.3375468351121
12.337521555606369
12.337496281619355
12.337471013149841
12.337445750196594
12.337420492758419
12.337395240834075
12.337369994422351
12.337344753522046
12.337319518131924
12.337294288250778
12.337269063877384
12.337243845010534
12.337218631649014
12.3371934237916
12.337168221437086
12.337143024584247
12.337117833231876
12.337092647378755
12.337067467023676
12.337042292165423
12.337017122802775
12.336991958934528
12.336966800559468
12.336941647676362
12.336916500284037
12.336891358381248
12.336866221966808
12.33684109103948
12.336815965598074
12.33679084564136
12.336765731168144
12.336740622177205
12.33671551866734
12.336690420637341
12.33666532808598
12.33664024101207
12.3366151594144
12.336590083291743
12.33656501264291
12.33653994746667
12.336514887761844
12.336489833527205
12.33646478476156
12.336439741463684
12.336414703632377
12.33638967126644
12.336364644364659
12.336339622925834
12.336314606948743
12.33628959643221
12.336264591374999
12.336239591775934
12.336214597633777
12.336189608947354
12.336164625715442
12.33613964793685
12.336114675610363
12.336089708734795
12.336064747308926
12.336039791331551
12.33601484080148
12.335989895717509
12.335964956078431
12.335940021883046
12.335915093130147
12.335890169818555
12.335865251947045
12.33584033951442
12.335815432519487
12.335790530961049
12.335765634837895
12.335740744148831
12.335715858892664
12.335690979068186
12.335666104674202
12.335641235709515
12.33561637217293
12.335591514063246
12.335566661379254
12.335541814119779
12.335516972283596
12.335492135869538
12.33546730487639
12.335442479302962
12.335417659148055
12.33539284441048
12.335368035089022
12.335343231182515
12.335318432689752
12.335293639609532
12.335268851940663
12.335244069681952
12.335219292832225
12.335194521390248
12.335169755354869
12.335144994724857
12.335120239499046
12.33509548967624
12.33507074525525
12.335046006234858
12.335021272613902
12.33499654439118
12.334971821565507
12.33494710413568
12.334922392100532
12.334897685458838
12.33487298420943
12.334848288351118
12.334823597882709
12.334798912803013
12.334774233110837
12.334749558805017
12.334724889884326
12.334700226347604
12.334675568193653
12.334650915421285
12.334626268029327
12.334601626016566
12.334576989381832
12.334552358123943
12.334527732241702
12.334503111733932
12.334478496599441
12.334453886837043
12.334429282445551
12.334404683423797
12.33438008977058
12.334355501484714
12.334330918565025
12.33430634101033
12.334281768819439
12.334257201991162
12.334232640524334
12.334208084417753
12.334183533670258
12.334158988280658
12.334134448247765
12.334109913570389
12.33408538424738

12.334060860277528
12.334036341659669
12.334011828392603
12.33398732047517
12.333962817906192
12.33393832068447
12.333913828808837
12.333889342278113
12.33386486109111
12.33384038524667
12.333815914743596
12.333791449580719
12.333766989756851
12.33374253527083
12.333718086121465
12.333693642307582
12.333669203828018
12.333644770681577
12.333620342867093
12.333595920383384
12.333571503229283
12.333547091403604
12.333522684905187
12.333498283732846
12.333473887885402
12.333449497361691
12.333425112160532
12.333400732280758
12.333376357721196
12.333351988480661
12.33332762455799
12.333303265952019
12.333278912661548
12.333254564685424
12.333230222022477
12.333205884671537
12.33318155263141
12.333157225900964
12.333132904478989
12.333108588364336
12.333084277555828
12.333059972052297
12.333035671852567
12.333011376955483
12.332987087359871
12.332962803064545
12.332938524068359
12.332914250370127
12.332889981968698
12.332865718862887
12.332841461051535
12.33281720853348
12.332792961307543
12.332768719372565
12.332744482727374
12.332720251370809
12.332696025301704
12.33267180451888
12.332647589021198
12.33262337880747
12.332599173876538
12.332574974227233
12.332550779858405
12.33252659076887
12.332502406957476
12.332478228423065
12.332454055164453
12.332429887180492
12.332405724470021
12.332381567031877
12.332357414864896
12.332333267967908
12.33230912633974
12.332284989979271
12.332260858885304
12.332236733056694
12.33221261249227
12.332188497190886
12.33216438715137
12.332140282372567
12.332116182853316
12.33209208859245
12.33206799958882
12.332043915841263
12.332019837348621
12.331995764109738
12.331971696123457
12.331947633388607
12.331923575904057
12.331899523668618
12.331875476681146
12.331851434940491
12.331827398445492
12.331803367194993
12.331779341187824
12.331755320422856
12.331731304898922
12.331707294614855
12.331683289569519
12.331659289761737
12.331635295190367
12.331611305854267
12.331587321752266
12.331563342883214
12.331539369245963
12.331515400839345
12.331491437662228
12.331467479713451
12.331443526991855
12.33141957949628
12.331395637225608
12.331371700178654
12.331347768354288
12.331323841751342
12.331299920368668
12.331276004205138
12.331252093259566
12.33122818753083
12.33120428701777
12.33118039171923
12.331156501634071
12.331132616761142
12.331108737099296
12.331084862647375
12.331060993404238
12.331037129368738
12.331013270539724
12.330989416916045
12.33096556849657
12.33094172528014
12.330917887265608
12.330894054451827
12.330870226837645
12.330846404421935
12.330822587203537
12.33079877518131
12.330774968354111
12.330751166720784
12.330727370280195
12.330703579031207
12.330679792972655
12.330656012103406
12.330632236422327
12.330608465928258
12.33058470062006
12.330560940496602
12.33053718555672
12.330513435799297
12.330489691223175
12.330465951827211
12.330442217610273
12.330418488571203
12.330394764708888
12.330371046022162
12.330347332509893
12.330323624170953
12.330299921004174
12.330276223008447
12.330252530182612
12.330228842525536
12.330205160036087
12.330181482713114
12.330157810555482
12.330134143562066
12.330110481731712
12.330086825063292
12.330063173555663
12.330039527207683
12.330015886018233
12.329992249986166
12.329968619110337
12.329944993389624
12.329921372822882
12.329897757408975
12.329874147146777
12.329850542035144
12.329826942072957
12.329803347259057
12.329779757592323
12.329756173071628
12.329732593695827
12.329709019463786
12.329685450374381
12.329661886426472
12.329638327618929
12.329614773950626
12.329591225420407
12.329567682027164
12.32954414376976
12.329520610647064
12.329497082657939
12.329473559801258
12.329450042075898
12.329426529480704
12.329403022014581
12.329379519676364
12.329356022464951
12.3293325303792
12.329309043417982
12.32928556158017
12.329262084864636
12.32923861327025
12.32921514679588
12.329191685440406
12.329168229202706
12.32914477808163
12.329121332076067
12.329097891184908
12.329074455406989
12.3290510247412
12.329027599186423
12.329004178741517
12.328980763405376
12.328957353176857
12.32893394805485
12.328910548038204
12.328887153125837
12.328863763316582
12.328840378609335
12.328816999002973
12.328793624496376
12.328770255088406
12.328746890777953
12.328723531563892
12.328700177445093
12.328676828420448
12.32865348448882
12.328630145649097
12.328606811900146
12.32858348324086
12.328560159670111
12.328536841186779
12.328513527789749
12.328490219477889
12.32846691625009
12.328443618105219
12.32842032504219
12.32839703705984
12.32837375415707
12.328350476332758
12.328327203585804
12.328303935915063
12.32828067331943
12.328257415797792
12.328234163349014
12.328210915971995
12.328187673665616
12.328164436428757
12.328141204260305
12.328117977159142
12.32809475512414
12.328071538154202
12.328048326248208
12.32802511940504
12.328001917623581
12.32797872090272
12.327955529241338
12.327932342638332
12.32790916109258
12.32788598460296
12.327862813168371
12.327839646787691
12.32781648545982
12.327793329183649
12.327770177958032
12.32774703178189
12.327723890654108
12.32770075457356
12.327677623539135
12.327654497549739
12.327631376604247
12.327608260701554
12.327585149840539
12.327562044020105
12.32753894323914
12.327515847496539
12.327492756791177
12.327469671121952
12.327446590487767
12.327423514887498
12.327400444320036
12.327377378784286
12.327354318279134
12.327331262803469
12.327308212356186
12.327285166936187
12.32726212654235
12.327239091173563
12.327216060828746
12.327193035506772
12.327170015206553
12.327146999926956
12.327123989666909
12.327100984425263
12.32707798420097
12.327054988992883
12.327031998799901
12.327009013620934
12.326986033454885
12.326963058300628
12.326940088157068
12.326917123023106
12.32689416289764
12.32687120777956
12.326848257667772
12.326825312561173
12.32680237245865
12.326779437359127
12.32675650726146
12.326733582164584
12.326710662067404
12.32668774696878
12.326664836867652
12.32664193176289
12.326619031653411
12.326596136538106
12.326573246415887
12.326550361285651
12.32652748114629
12.32650460599672
12.326481735835833
12.326458870662519
12.326436010475716
12.326413155274286
12.326390305057151
12.326367459823219
12.326344619571392
12.326321784300557
12.326298954009633
12.326276128697536
12.326253308363139
12.32623049300536
12.32620768262311
12.326184877215283
12.326162076780793
12.326139281318541
12.326116490827435
12.326093705306384
12.326070924754283
12.32604814917005
12.326025378552593
12.3260026129008
12.325979852213605
12.325957096489892
12.325934345728573
12.325911599928569
12.325888859088781
12.325866123208106
12.325843392285476
12.325820666319775
12.325797945309928
12.325775229254845
12.32575251815342
12.325729812004584
12.325707110807231
12.325684414560282
12.325661723262632
12.325639036913206
12.325616355510917
12.325593679054668
12.325571007543372
12.325548340975937
12.325525679351287
12.32550302266832
12.325480370925952
12.325457724123103
12.325435082258691
12.325412445331615
12.325389813340793
12.325367186285137
12.325344564163574
12.325321946975002
12.325299334718343
12.325276727392508
12.325254124996405
12.325231527528972
12.325208934989101
12.32518634737573
12.325163764687751
12.3251411869241
12.32511861408368
12.32509604616542
12.325073483168214
12.325050925091011
12.325028371932714
12.325005823692226
12.324983280368478
12.324960741960398
12.324938208466891
12.324915679886873
12.324893156219275
12.32487063746301
12.324848123616997
12.324825614680153
12.324803110651414
12.324780611529679
12.324758117313873
12.324735628002918
12.324713143595742
12.324690664091259
12.3246681894884
12.324645719786075
12.324623254983202
12.324600795078716
12.324578340071533
12.324555889960584
12.324533444744777
12.32451100442305
12.324488568994306
12.324466138457488
12.324443712811515
12.32442129205531
12.324398876187791
12.324376465207886
12.324354059114524
12.324331657906631
12.324309261583121
12.324286870142942
12.324264483584994
12.324242101908215
12.324219725111528
12.324197353193862
12.324174986154144
12.3241526239913
12.324130266704259
12.324107914291949
12.324085566753292
12.32406322408722
12.324040886292659
12.324018553368536
12.323996225313785
12.323973902127335
12.323951583808109
12.323929270355041
12.32390696176705
12.323884658043085
12.323862359182067
12.323840065182912
12.323817776044574
12.323795491765976
12.323773212346039
12.323750937783709
12.323728668077905
12.323706403227565
12.323684143231619
12.323661888089003
12.323639637798642
12.323617392359486
12.32359515177044
12.323572916030463
12.323550685138475
12.323528459093414
12.323506237894204
12.3234840215398
12.323461810029114
12.3234396033611
12.323417401534675
12.323395204548788
12.323373012402364
12.323350825094346
12.323328642623673
12.323306464989269
12.323284292190088
12.323262124225034
12.323239961093089
12.323217802793149
12.323195649324175
12.323173500685092
12.32315135687486
12.323129217892385
12.32310708373662
12.323084954406522
12.323062829901
12.323040710219004
12.323018595359477
12.322996485321363
12.322974380103586
12.32295227970509
12.322930184124832
12.322908093361715
12.322886007414727
12.322863926282789
12.322841849964833
12.322819778459802
12.322797711766658
12.322775649884312
12.322753592811727
12.322731540547835
12.322709493091585
12.322687450441922
12.322665412597779
12.32264337955811
12.322621351321853
12.322599327887954
12.322577309255355
12.322555295422996
12.322533286389836
12.32251128215479
12.322489282716843
12.322467288074915
12.322445298227947
12.322423313174903
12.322401332914712
12.322379357446332
12.322357386768704
12.32233542088078
12.322313459781498
12.322291503469813
12.322269551944666
12.322247605205009
12.322225663249784
12.322203726077952
12.322181793688442
12.322159866080217
12.322137943252228
12.322116025203409
12.322094111932717
12.322072203439102
12.322050299721525
12.322028400778917
12.32200650661023
12.32198461721442
12.321962732590455
12.321940852737256
12.321918977653784
12.321897107339
12.321875241791844
12.321853381011277
12.321831524996247
12.321809673745697
12.321787827258591
12.321765985533887
12.32174414857052
12.321722316367447
12.321700488923646
12.32167866623804
12.3216568483096
12.32163503513728
12.321613226720022
12.321591423056791
12.321569624146536
12.321547829988221
12.321526040580784
12.321504255923202
12.321482476014422
12.321460700853397
12.321438930439083
12.321417164770443
12.321395403846422
12.321373647665993
12.321351896228098
12.32133014953171
12.32130840757577
12.321286670359243
12.321264937881082
12.321243210140258
12.32122148713573
12.32119976886645
12.321178055331357
12.32115634652945
12.321134642459661
12.321112943120955
12.321091248512305
12.321069558632646
12.321047873480957
12.32102619305621
12.32100451735734
12.320982846383314
12.320961180133098
12.320939518605657
12.320917861799954
12.320896209714947
12.320874562349594
12.32085291970287
12.320831281773716
12.320809648561124
12.320788020064038
12.320766396281423
12.32074477721225
12.32072316285547
12.320701553210064
12.320679948274982
12.320658348049186
12.320636752531671
12.32061516172137
12.32059357561726
12.320571994218312

12.320550417523489
12.320528845531745
12.320507278242047
12.320485715653376
12.320464157764706
12.320442604574973
12.320421056083173
12.320399512288265
12.320377973189206
12.320356438784977
12.320334909074539
12.320313384056861
12.320291863730915
12.320270348095681
12.320248837150096
12.320227330893152
12.320205829323823
12.32018433244106
12.32016284024386
12.320141352731167
12.320119869901962
12.320098391755225
12.320076918289908
12.32005544950499
12.320033985399453
12.320012525972247
12.319991071222374
12.319969621148783
12.319948175750449
12.31992673502635
12.319905298975454
12.31988386759674
12.319862440889176
12.319841018851738
12.319819601483397
12.31979818878314
12.319776780749917
12.319755377382725
12.319733978680523
12.319712584642293
12.319691195267014
12.31966981055366
12.31964843050119
12.319627055108612
12.319605684374874
12.319584318298968
12.319562956879848
12.319541600116516
12.319520248007942
12.3194989005531
12.319477557750975
12.319456219600529
12.319434886100755
12.319413557250623
12.319392233049102
12.319370913495202
12.319349598587879
12.319328288326105
12.319306982708877
12.319285681735165
12.319264385403953
12.31924309371421
12.319221806664931
12.319200524255086
12.31917924648366
12.319157973349643
12.319136704852001
12.31911544098972
12.31909418176178
12.319072927167172
12.319051677204868
12.319030431873857
12.31900919117312
12.318987955101631
12.318966723658383
12.318945496842357
12.318924274652534
12.318903057087892
12.318881844147434
12.318860635830134
12.318839432134958
12.31881823306092
12.318797038606988
12.318775848772145
12.318754663555392
12.31873348295569
12.318712306972051
12.318691135603459
12.318669968848875
12.318648806707294
12.318627649177724
12.318606496259134
12.318585347950505
12.318564204250837
12.318543065159117
12.31852193067433
12.318500800795457
12.318479675521498
12.318458554851437
12.318437438784255
12.318416327318952
12.318395220454512
12.318374118189928
12.318353020524182
12.318331927456269
12.318310838985173
12.318289755109902
12.318268675829415
12.318247601142737
12.31822653104884
12.318205465546718
12.31818440463537
12.31816334831377
12.31814229658092
12.318121249435817
12.31810020687745
12.31807916890481
12.318058135516884
12.318037106712673
12.318016082491171
12.317995062851363
12.317974047792257
12.317953037312833
12.317932031412091
12.317911030089016
12.317890033342612
12.317869041171885
12.317848053575812
12.317827070553385
12.317806092103623
12.317785118225496
12.317764148918013
12.317743184180168
12.317722224010964
12.317701268409378
12.317680317374428
12.317659370905105
12.317638429000397
12.317617491659309
12.317596558880838
12.317575630663985
12.317554707007739
12.317533787911113
12.317512873373094
12.317491963392682
12.317471057968879
12.317450157100684
12.31742926078709
12.317408369027106
12.317387481819734
12.317366599163957
12.317345721058786
12.31732484750324
12.317303978496291
12.317283114036952
12.317262254124222
12.317241398757105
12.31722054793459
12.317199701655706
12.317178859919435
12.317158022724787
12.317137190070754
12.317116361956362
12.317095538380592
12.317074719342454
12.317053904840952
12.317033094875091
12.317012289443866
12.316991488546288
12.31697069218137
12.316949900348114
12.316929113045509
12.31690833027257
12.316887552028305
12.316866778311722
12.31684600912181
12.316825244457613
12.316804484318078
12.316783728702262
12.316762977609168
12.316742231037768
12.316721488987088
12.316700751456159
12.316680018443959
12.316659289949506
12.316638565971793
12.316617846509857
12.316597131562677
12.316576421129282
12.316555715208677
12.316535013799863
12.316514316901864
12.316493624513676
12.316472936634305
12.316452253262783
12.316431574398102
12.31641090003927
12.316390230185316
12.316369564835222
12.31634890398803
12.316328247642739
12.316307595798357
12.316286948453895
12.316266305608371
12.316245667260791
12.316225033410165
12.316204404055528
12.316183779195859
12.316163158830205
12.316142542957552
12.316121931576918
12.316101324687338
12.316080722287808
12.31606012437734
12.316039530954951
12.316018942019669
12.315998357570491
12.315977777606442
12.315957202126526
12.315936631129777
12.3159160646152
12.31589550258181
12.315874945028614
12.315854391954657
12.31583384335893
12.315813299240467
12.315792759598265
12.31577222443135
12.315751693738745
12.315731167519475
12.315710645772539
12.315690128496962
12.31566961569176
12.315649107355966
12.315628603488591
12.315608104088641
12.315587609155155
12.315567118687136
12.315546632683613
12.315526151143608
12.315505674066134
12.315485201450212
12.315464733294872
12.315444269599121
12.315423810361994
12.315403355582507
12.315382905259673
12.315362459392524
12.315342017980074
12.315321581021358
12.315301148515378
12.31528072046118
12.315260296857769
12.31523987770418
12.315219462999423
12.315199052742537
12.315178646932534
12.315158245568433
12.315137848649279
12.315117456174075
12.315097068141865
12.315076684551657
12.315056305402491
12.315035930693382
12.315015560423346
12.314995194591424
12.314974833196642
12.314954476238015
12.314934123714579
12.314913775625362
12.314893431969377
12.314873092745671
12.314852757953263
12.31483242759116
12.314812101658413
12.314791780154044
12.3147714630771
12.314751150426574
12.314730842201508
12.314710538400936
12.314690239023884
12.314669944069392
12.314649653536469
12.314629367424155
12.314609085731478
12.314588808457481
12.31456853560117
12.314548267161582
12.31452800313778
12.314507743528747
12.314487488333542
12.314467237551193
12.314446991180715
12.314426749221166
12.314406511671562
12.314386278530932
12.314366049798332
12.314345825472762
12.314325605553272
12.314305390038903
12.314285178928664
12.314264972221613
12.314244769916781
12.314224572013178
12.314204378509855
12.314184189405852
12.314164004700192
12.314143824391929
12.314123648480072
12.314103476963675
12.31408330984177
12.31406314711338
12.314042988777564
12.314022834833327
12.314002685279732
12.31398254011581
12.313962399340591
12.31394226295312
12.313922130952411
12.31390200333753
12.313881880107505
12.313861761261379
12.313841646798183
12.313821536716947
12.313801431016719
12.313781329696546
12.313761232755457
12.31374114019248
12.313721052006677
12.313700968197079
12.313680888762729
12.313660813702647
12.313640743015888
12.313620676701504
12.31360061475852
12.313580557185977
12.313560503982925
12.313540455148392
12.313520410681434
12.313500370581083
12.31348033484639
12.31346030347639
12.31344027647012
12.313420253826623
12.313400235544973
12.313380221624152
12.313360212063268
12.313340206861332
12.313320206017378
12.313300209530475
12.313280217399644
12.313260229623939
12.31324024620242
12.313220267134112
12.31320029241806
12.313180322053311
12.313160356038921
12.313140394373923
12.31312043705737
12.31310048408831
12.31308053546577
12.313060591188833
12.31304065125651
12.313020715667859
12.313000784421929
12.312980857517777
12.312960934954432
12.312941016730955
12.31292110284639
12.312901193299794
12.312881288090198
12.312861387216655
12.312841490678219
12.312821598473944
12.312801710602866
12.312781827064052
12.31276194785652
12.31274207297935
12.312722202431592
12.312702336212276
12.31268247432046
12.31266261675521
12.312642763515557
12.31262291460056
12.312603070009276
12.312583229740744
12.312563393794024
12.312543562168164
12.312523734862214
12.312503911875245
12.31248409320628
12.31246427885439
12.312444468818631
12.31242466309805
12.312404861691693
12.31238506459863
12.312365271817894
12.31234548334856
12.31232569918967
12.312305919340286
12.31228614379944
12.312266372566231
12.31224660563968
12.312226843018848
12.312207084702788
12.312187330690561
12.312167580981239
12.312147835573846
12.312128094467456
12.312108357661128
12.312088625153905
12.312068896944865
12.312049173033053
12.312029453417525
12.312009738097343
12.31199002707156
12.311970320339235
12.31195061789944
12.311930919751203
12.311911225893619
12.311891536325717
12.311871851046567
12.311852170055234
12.311832493350781
12.311812820932252
12.31179315279871
12.311773488949227
12.311753829382857
12.311734174098667
12.31171452309569
12.311694876373018
12.311675233929709
12.311655595764812
12.311635961877395
12.311616332266516
12.31159670693124
12.311577085870628
12.31155746908375
12.311537856569654
12.311518248327422
12.311498644356103
12.31147904465476
12.311459449222454
12.311439858058266
12.311420271161253
12.311400688530462
12.311381110164984
12.311361536063853
12.311341966226161
12.311322400650957
12.31130283933732
12.311283282284299
12.311263729490971
12.311244180956404
12.311224636679654
12.311205096659798
12.311185560895886
12.311166029386996
12.311146502132205
12.311126979130556
12.311107460381136
12.31108794588301
12.311068435635239
12.311048929636888
12.311029427887034
12.31100993038474
12.310990437129089
12.310970948119119
12.310951463353923
12.310931982832571
12.31091250655412
12.310893034517647
12.310873566722215
12.310854103166907
12.310834643850779
12.310815188772912
12.310795737932372
12.310776291328228
12.310756848959548
12.310737410825418
12.310717976924904
12.310698547257058
12.310679121820977
12.310659700615721
12.310640283640366
12.310620870893981
12.310601462375642
12.310582058084421
12.310562658019393
12.310543262179625
12.310523870564198
12.31050448317218
12.310485100002644
12.310465721054678
12.310446346327343
12.310426975819716
12.310407609530865
12.310388247459882
12.310368889605824
12.310349535967775
12.310330186544814
12.310310841336022
12.310291500340455
12.310272163557192
12.310252830985338
12.310233502623936
12.31021417847208
12.310194858528847
12.31017554279331
12.310156231264545
12.310136923941625
12.310117620823645
12.31009832190966
12.310079027198773
12.310059736690041
12.310040450382562
12.3100211682754
12.310001890367634
12.30998261665835
12.309963347146635
12.30994408183155
12.309924820712192
12.309905563787623
12.309886311056946
12.309867062519226
12.309847818173548
12.309828578018989
12.30980934205463
12.309790110279561
12.30977088269286
12.309751659293601
12.309732440080872
12.309713225053752
12.309694014211344
12.309674807552698
12.309655605076918
12.309636406783081
12.309617212670265
12.30959802273756
12.309578836984057
12.309559655408819
12.309540478010947
12.309521304789524
12.309502135743628
12.309482970872342
12.309463810174762
12.309444653649962
12.309425501297039
12.309406353115063
12.309387209103125
12.309368069260318
12.309348933585722
12.309329802078425
12.309310674737524
12.309291551562076
12.309272432551206
12.309253317703968
12.309234207019472
12.30921510049679
12.30919599813502
12.309176899933245
12.309157805890557
12.309138716006041

12.30911963027879
12.309100548707873
12.309081471292409
12.309062398031475
12.309043328924158
12.309024263969533
12.309005203166716
12.308986146514798
12.308967094012845
12.308948045659957
12.308929001455226
12.308909961397754
12.308890925486601
12.3088718937209
12.30885286609971
12.308833842622134
12.308814823287266
12.308795808094189
12.30877679704202
12.30875779012982
12.308738787356692
12.308719788721733
12.308700794224032
12.30868180386269
12.308662817636796
12.308643835545434
12.308624857587715
12.308605883762715
12.308586914069549
12.308567948507289
12.30854898707505
12.308530029771909
12.308511076596973
12.30849212754933
12.308473182628086
12.30845424183232
12.308435305161142
12.308416372613646
12.308397444188918
12.308378519886075
12.308359599704188
12.308340683642372
12.308321771699717
12.30830286387532
12.308283960168286
12.308265060577707
12.308246165102677
12.308227273742292
12.308208386495664
12.308189503361882
12.308170624340041
12.308151749429257
12.3081328786286
12.308114011937198
12.308095149354134
12.30807629087851
12.308057436509435
12.308038586246
12.308019740087307
12.308000898032457
12.307982060080542
12.307963226230681
12.307944396481965
12.307925570833497
12.307906749284376
12.3078879318337
12.307869118480571
12.307850309224104
12.307831504063394
12.307812702997538
12.30779390602565
12.30777511314682
12.307756324360144
12.307737539664759
12.30771875905974
12.307699982544191
12.307681210117236
12.30766244177797
12.307643677525482
12.307624917358892
12.307606161277295
12.307587409279805
12.30756866136552
12.307549917533558
12.307531177783007
12.307512442112985
12.307493710522593
12.307474983010938
12.307456259577126
12.307437540220262
12.30741882493946
12.307400113733815
12.307381406602437
12.307362703544442
12.307344004558917
12.307325309645005
12.307306618801793
12.307287932028384
12.307269249323886
12.307250570687419
12.307231896118079
12.307213225614989
12.30719455917725
12.307175896803967
12.30715723849426
12.307138584247227
12.307119934061978
12.307101287937641
12.307082645873312
12.307064007868101
12.30704537392113
12.307026744031482
12.3070081181983
12.306989496420684
12.306970878697735
12.306952265028581
12.306933655412323
12.306915049848076
12.306896448334951
12.306877850872063
12.306859257458514
12.306840668093441
12.306822082775946
12.306803501505117
12.306784924280095
12.306766351099997
12.306747781963924
12.30672921687099
12.306710655820314
12.306692098811016
12.306673545842193
12.306654996912973
12.306636452022468
12.306617911169806
12.30659937435407
12.3065808415744
12.306562312829918
12.306543788119717
12.306525267442934
12.306506750798667
12.306488238186052
12.30646972960419
12.306451225052204
12.30643272452921
12.306414228034331
12.306395735566678
12.306377247125372
12.306358762709523
12.306340282318265
12.306321805950702
12.306303333605952
12.306284865283148
12.306266400981395
12.306247940699828
12.306229484437544
12.306211032193684
12.30619258396735
12.306174139757667
12.306155699563769
12.30613726338476
12.306118831219763
12.306100403067905
12.306081978928301
12.306063558800076
12.306045142682347
12.306026730574242
12.306008322474877
12.305989918383377
12.30597151829886
12.305953122220455
12.30593473014728
12.305916342078458
12.305897958013103
12.305879577950362
12.305861201889341
12.305842829829157
12.30582446176895
12.305806097707833
12.305787737644932
12.305769381579376
12.305751029510281
12.305732681436771
12.30571433735799
12.305695997273045
12.30567766118106
12.305659329081168
12.305641000972495
12.30562267685417
12.305604356725302
12.305586040585032
12.305567728432491
12.305549420266784
12.305531116087057
12.305512815892435
12.305494519682043
12.305476227454989
12.305457939210433
12.305439654947488
12.305421374665276
12.305403098362937
12.30538482603958
12.305366557694365
12.305348293326391
12.305330032934801
12.30531177651872
12.305293524077275
12.305275275609608
12.305257031114827
12.30523879059209
12.305220554040494
12.305202321459202
12.305184092847325
12.305165868203995
12.305147647528347
12.305129430819509
12.305111218076616
12.305093009298803
12.305074804485196
12.30505660363491
12.305038406747112
12.305020213820898
12.305002024855431
12.304983839849829
12.304965658803233
12.304947481714759
12.304929308583558
12.30491113940875
12.304892974189478
12.304874812924876
12.30485665561407
12.30483850225619
12.304820352850385
12.304802207395792
12.304784065891527
12.304765928336746
12.304747794730563
12.304729665072125
12.304711539360566
12.304693417595022
12.30467529977463
12.30465718589852
12.30463907596583
12.304620969975712
12.304602867927276
12.30458476981968
12.30456667565205
12.304548585423523
12.304530499133246
12.30451241678035
12.30449433836397
12.304476263883249
12.304458193337322
12.304440126725334
12.304422064046408
12.304404005299697
12.304385950484342
12.30436789959947
12.304349852644235
12.304331809617757
12.304313770519194
12.304295735347669
12.304277704102338
12.304259676782333
12.3042416533868
12.304223633914868
12.304205618365692
12.304187606738411
12.304169599032154
12.304151595246072
12.30413359537931
12.304115599431
12.304097607400298
12.304079619286314
12.304061635088235
12.304043654805165
12.304025678436275
12.304007705980707
12.303989737437572
12.303971772806053
12.303953812085265
12.303935855274364
12.303917902372488
12.303899953378798
12.303882008292415
12.303864067112503
12.303846129838185
12.303828196468622
12.303810267002964
12.303792341440348
12.303774419779906
12.303756502020812
12.303738588162187
12.30372067820318
12.303702772142959
12.303684869980648
12.303666971715401
12.30364907734637
12.303631186872689
12.303613300293517
12.303595417607989
12.303577538815265
12.303559663914497
12.303541792904818
12.30352392578538
12.303506062555327
12.303488203213833
12.303470347760017
12.303452496193028
12.303434648512043
12.303416804716186
12.303398964804613
12.303381128776461
12.303363296630916
12.303345468367096
12.303327643984161
12.303309823481266
12.303292006857546
12.303274194112166
12.303256385244278
12.303238580253023
12.303220779137556
12.303202981897035
12.303185188530609
12.303167399037426
12.30314961341663
12.303131831667395
12.303114053788857
12.303096279780169
12.303078509640486
12.30306074336897
12.303042980964761
12.303025222427031
12.303007467754911
12.302989716947565
12.302971970004146
12.302954226923813
12.302936487705711
12.302918752348996
12.302901020852834
12.302883293216368
12.302865569438753
12.302847849519154
12.302830133456725
12.302812421250605
12.302794712899976
12.302777008403982
12.302759307761757
12.302741610972499
12.302723918035328
12.302706228949436
12.302688543713943
12.302670862328025
12.302653184790843
12.302635511101549
12.302617841259295
12.302600175263247
12.302582513112567
12.302564854806398
12.302547200343916
12.302529549724266
12.302511902946613
12.302494260010107
12.302476620913929
12.302458985657218
12.302441354239141
12.302423726658853
12.302406102915532
12.302388483008311
12.302370866936355
12.302353254698854
12.302335646294935
12.302318041723773
12.302300440984528
12.302282844076364
12.302265250998431
12.302247661749911
12.302230076329947
12.302212494737706
12.302194916972354
12.30217734303305
12.302159772918957
12.302142206629236
12.302124644163047
12.30210708551957
12.302089530697966
12.302071979697375
12.302054432516975
12.302036889155929
12.302019349613404
12.302001813888566
12.301984281980571
12.301966753888593
12.301949229611795
12.301931709149327
12.301914192500366
12.301896679664083
12.301879170639642
12.3018616654262
12.30184416402293
12.301826666428994
12.301809172643555
12.301791682665787
12.301774196494858
12.301756714129924
12.301739235570171
12.30172176081474
12.30170428986282
12.301686822713577
12.301669359366159
12.301651899819756
12.301634444073537
12.301616992126641
12.301599543978265
12.301582099627574
12.301564659073733
12.301547222315902
12.301529789353266
12.301512360184987
12.301494934810231
12.30147751322817
12.301460095437974
12.301442681438825
12.301425271229876
12.301407864810304
12.30139046217927
12.301373063335973
12.301355668279557
12.301338277009206
12.301320889524083
12.301303505823373
12.301286125906229
12.301268749771838
12.301251377419373
12.301234008847988
12.301216644056874
12.301199283045204
12.301181925812136
12.30116457235686
12.301147222678532
12.301129876776344
12.30111253464946
12.30109519629705
12.301077861718293
12.301060530912364
12.30104320387844
12.301025880615688
12.301008561123288
12.30099124540041
12.300973933446233
12.30095662525993
12.30093932084068
12.300922020187663
12.300904723300041
12.300887430176997
12.300870140817715
12.30085285522136
12.30083557338712
12.300818295314158
12.30080102100166
12.3007837504488
12.30076648365475
12.300749220618696
12.300731961339826
12.30071470581729
12.3006974540503
12.300680206037997
12.300662961779585
12.300645721274238
12.300628484521132
12.300611251519445
12.30059402226835
12.300576796767048
12.300559575014695
12.300542357010483
12.300525142753594
12.300507932243194
12.300490725478474
12.300473522458615
12.300456323182798
12.300439127650199
12.300421935860003
12.300404747811388
12.300387563503532
12.300370382935624
12.300353206106843
12.300336033016379
12.300318863663396
12.300301698047086
12.300284536166629
12.300267378021223
12.300250223610028
12.300233072932244
12.30021592598704
12.300198782773604
12.300181643291124
12.300164507538783
12.300147375515767
12.300130247221256
12.300113122654437

12.300096001814488
12.300078884700598
12.300061771311952
12.30004466164773
12.300027555707139
12.300010453489326
12.299993354993509
12.299976260218852
12.299959169164566
12.29994208182981
12.299924998213784
12.299907918315684
12.299890842134674
12.29987376966996
12.299856700920712
12.299839635886133
12.299822574565399
12.2998055169577
12.299788463062242
12.299771412878185
12.299754366404724
12.299737323641057
12.299720284586376
12.299703249239842
12.299686217600675
12.299669189668053
12.299652165441163
12.299635144919195
12.299618128101326
12.299601114986777
12.299584105574706
12.299567099864325
12.29955009785481
12.299533099545357
12.299516104935163
12.299499114023407
12.299482126809282
12.29946514329198
12.299448163470704
12.299431187344622
12.299414214912952
12.299397246174866
12.299380281129572
12.299363319776248
12.299346362114091
12.299329408142295
12.299312457860053
12.299295511266553
12.299278568360995
12.299261629142569
12.299244693610468
12.299227761763895
12.299210833602029
12.29919390912406
12.299176988329203
12.299160071216642
12.299143157785572
12.299126248035183
12.299109341964666
12.299092439573231
12.299075540860077
12.29905864582437
12.299041754465337
12.299024866782155
12.299007982774025
12.298991102440146
12.298974225779714
12.298957352791918
12.298940483475958
12.298923617831038
12.298906755856356
12.2988898975511
12.29887304291446
12.298856191945642
12.298839344643866
12.298822501008301
12.298805661038148
12.298788824732616
12.298771992090897
12.298755163112196
12.298738337795706
12.298721516140619
12.298704698146146
12.298687883811478
12.298671073135827
12.298654266118383
12.298637462758345
12.298620663054912
12.298603867007296
12.298587074614684
12.298570285876272
12.298553500791284
12.298536719358907
12.29851994157834
12.298503167448779
12.298486396969452
12.29846963013952
12.298452866958218
12.298436107424733
12.298419351538278
12.298402599298035
12.298385850703234
12.298369105753055
12.29835236444671
12.298335626783404
12.298318892762333
12.298302162382711
12.298285435643724
12.298268712544594
12.29825199308452
12.298235277262703
12.298218565078354
12.298201856530659
12.298185151618842
12.298168450342098
12.298151752699644
12.298135058690667
12.298118368314391
12.29810168157001
12.298084998456723
12.298068318973758
12.298051643120306
12.298034970895568
12.298018302298754
12.298001637329087
12.297984975985754
12.297968318267973
12.297951664174947
12.297935013705876
12.297918366859987
12.29790172363647
12.297885084034526
12.297868448053388
12.297851815692248
12.29783518695031
12.297818561826809
12.297801940320928
12.297785322431885
12.297768708158872
12.297752097501123
12.297735490457832
12.29771888702822
12.297702287211496
12.297685691006853
12.297669098413525
12.297652509430698
12.297635924057602
12.297619342293432
12.297602764137418
12.297586189588756
12.297569618646651
12.297553051310336
12.297536487579015
12.297519927451885
12.29750337092817
12.297486818007078
12.297470268687828
12.297453722969632
12.297437180851693
12.297420642333233
12.29740410741345
12.297387576091579
12.297371048366815
12.29735452423839
12.297338003705494
12.297321486767359
12.297304973423197
12.297288463672219
12.297271957513628
12.297255454946654
12.297238955970508
12.297222460584404
12.297205968787559
12.297189480579172
12.29717299595848
12.297156514924698
12.297140037477028
12.297123563614694
12.297107093336905
12.29709062664289
12.297074163531844
12.297057704003006
12.297041248055596
12.297024795688793
12.297008346901858
12.296991901693985
12.296975460064397
12.296959022012311
12.296942587536938
12.296926156637516
12.296909729313239
12.296893305563342
12.296876885387036
12.29686046878354
12.296844055752082
12.296827646291856
12.296811240402114
12.296794838082052
12.296778439330899
12.296762044147869
12.296745652532199
12.296729264483082
12.296712879999758
12.296696499081433
12.296680121727345
12.2966637479367
12.296647377708723
12.296631011042647
12.296614647937668
12.296598288393028
12.296581932407944
12.296565579981637
12.296549231113326
12.296532885802234
12.296516544047588
12.296500205848607
12.296483871204515
12.296467540114525
12.29645121257788
12.296434888593785
12.296418568161469
12.296402251280162
12.296385937949072
12.296369628167435
12.296353321934472
12.296337019249428
12.296320720111487
12.296304424519889
12.296288132473878
12.29627184397265
12.296255559015451
12.296239277601513
12.296222999730034
12.296206725400252
12.296190454611391
12.296174187362686
12.296157923653356
12.296141663482635
12.29612540684973
12.296109153753887
12.29609290419433
12.296076658170279
12.296060415680957
12.296044176725607
12.296027941303436
12.296011709413694
12.295995481055588
12.295979256228371
12.29596303493125
12.295946817163456
12.295930602924216
12.295914392212767
12.29589818502834
12.295881981370146
12.295865781237431
12.29584958462943
12.29583339154535
12.295817201984446
12.295801015945921
12.295784833429021
12.295768654432976
12.295752478957011
12.295736307000364
12.29572013856226
12.295703973641924
12.295687812238596
12.295671654351514
12.295655499979887
12.29563934912297
12.29562320177999
12.295607057950155
12.295590917632737
12.295574780826929
12.295558647531989
12.295542517747128
12.29552639147161
12.295510268704652
12.29549414944548
12.295478033693328
12.295461921447437
12.295445812707035
12.29542970747136
12.295413605739638
12.295397507511124
12.295381412785028
12.295365321560595
12.295349233837062
12.295333149613652
12.295317068889613
12.295300991664174
12.295284917936566
12.295268847706042
12.29525278097182
12.295236717733133
12.29522065798924
12.295204601739343
12.295188548982718
12.295172499718571
12.295156453946152
12.29514041166468
12.295124372873428
12.29510833757161
12.295092305758446
12.295076277433202
12.295060252595102
12.295044231243406
12.295028213377318
12.295012198996096
12.294996188098969
12.29498018068518
12.294964176753973
12.294948176304585
12.29493217933624
12.294916185848198
12.294900195839686
12.294884209309943
12.294868226258231
12.294852246683751
12.294836270585773
12.294820297963524
12.294804328816253
12.294788363143192
12.294772400943575
12.294756442216663
12.294740486961688
12.294724535177888
12.294708586864507
12.294692642020786
12.294676700645963
12.294660762739289
12.294644828299992
12.29462889732733
12.294612969820538
12.294597045778852
12.294581125201521
12.294565208087802
12.294549294436916
12.294533384248108
12.29451747752063
12.294501574253719
12.294485674446632
12.294469778098595
12.294453885208867
12.294437995776688
12.294422109801298
12.294406227281936
12.294390348217856
12.294374472608306
12.294358600452528
12.294342731749758
12.294326866499256
12.294311004700255
12.294295146352015
12.29427929145376
12.294263440004752
12.29424759200424
12.294231747451464
12.294215906345665
12.294200068686097
12.294184234472016
12.29416840370264
12.29415257637724
12.294136752495065
12.294120932055343
12.294105115057354
12.294089301500314
12.294073491383482
12.294057684706114
12.294041881467443
12.294026081666733
12.294010285303225
12.293994492376164
12.293978702884807
12.2939629168284
12.293947134206201
12.293931355017438
12.293915579261377
12.293899806937274
12.293884038044355
12.293868272581893
12.293852510549119
12.293836751945308
12.293820996769691
12.293805245021531
12.293789496700068
12.293773751804553
12.293758010334255
12.293742272288403
12.293726537666263
12.29371080646708
12.293695078690112
12.293679354334607
12.293663633399817
12.293647915884998
12.293632201789398
12.293616491112276
12.29360078385288
12.293585080010455
12.293569379584275
12.29355368257358
12.29353798897762
12.293522298795665
12.29350661202695
12.29349092867074
12.293475248726288
12.293459572192845
12.29344389906967
12.293428229356017
12.293412563051142
12.293396900154304
12.293381240664736
12.293365584581723
12.29334993190451
12.29333428263234
12.293318636764482
12.29330299430019
12.293287355238725
12.293271719579343
12.293256087321286
12.293240458463826
12.293224833006217
12.293209210947703
12.293193592287563
12.293177977025037
12.29316236515939
12.293146756689895
12.293131151615773
12.293115549936314
12.293099951650754
12.293084356758374
12.293068765258427
12.293053177150155
12.29303759243284
12.29302201110571
12.293006433168053
12.292990858619133
12.292975287458184
12.292959719684474
12.292944155297265
12.292928594295828
12.292913036679419
12.292897482447279
12.292881931598684
12.2928663841329
12.292850840049173
12.29283529934678
12.29281976202497
12.292804228083014
12.292788697520162
12.29277317033569
12.292757646528845
12.292742126098899
12.29272660904511
12.292711095366748
12.292695585063061
12.292680078133332
12.2926645745768
12.292649074392742
12.292633577580425
12.2926180841391
12.292602594068038
12.292587107366508
12.292571624033762
12.292556144069074
12.292540667471696
12.292525194240907
12.292509724375957
12.292494257876129
12.292478794740672
12.29246333496885
12.29244787855994
12.292432425513198
12.292416975827894
12.292401529503298
12.292386086538666
12.292370646933273
12.292355210686372
12.292339777797244
12.292324348265144
12.292308922089354
12.292293499269116
12.292278079803719
12.292262663692417
12.292247250934494
12.292231841529201
12.29221643547581
12.292201032773589
12.292185633421806
12.292170237419727
12.292154844766628
12.292139455461767
12.292124069504425
12.292108686893853
12.292093307629345
12.292077931710136
12.292062559135529
12.292047189904773
12.292031824017142
12.292016461471915
12.292001102268346
12.291985746405718
12.291970393883295
12.291955044700343
12.291939698856147
12.291924356349961
12.29190901718107
12.291893681348727
12.291878348852222
12.291863019690824
12.291847693863792
12.291832371370404
12.291817052209934
12.291801736381649
12.29178642388483
12.291771114718744
12.29175580888266
12.291740506375858
12.291725207197603
12.291709911347178
12.291694618823838
12.291679329626875
12.291664043755558
12.291648761209155
12.29163348198694
12.291618206088184
12.291602933512179
12.291587664258182
12.291572398325469
12.291557135713312
12.291541876421007
12.291526620447804
12.29151136779299
12.291496118455832
12.291480872435606
12.291465629731603
12.291450390343078
12.29143515426933
12.291419921509616
12.291404692063207
12.291389465929395
12.291374243107452
12.291359023596657
12.29134380739628
12.291328594505604
12.2913133849239
12.291298178650448
12.291282975684531
12.291267776025418
12.291252579672399
12.291237386624728
12.291222196881707

12.2912070104426
12.291191827306696
12.291176647473275
12.291161470941594
12.291146297710956
12.291131127780627
12.291115961149895
12.291100797818023
12.29108563778431
12.291070481048035
12.291055327608458
12.29104017746487
12.291025030616556
12.291009887062792
12.290994746802864
12.290979609836048
12.290964476161614
12.290949345778865
12.290934218687067
12.290919094885487
12.290903974373443
12.290888857150188
12.290873743215025
12.290858632567218
12.290843525206045
12.290828421130808
12.290813320340776
12.290798222835239
12.290783128613475
12.290768037674763
12.29075295001839
12.290737865643642
12.290722784549802
12.290707706736155
12.290692632201964
12.290677560946545
12.290662492969165
12.290647428269104
12.290632366845653
12.29061730869809
12.290602253825721
12.290587202227796
12.29057215390363
12.290557108852488
12.29054206707367
12.290527028566446
12.290511993330117
12.290496961363957
12.29048193266727
12.29046690723931
12.290451885079401
12.290436866186802
12.290421850560799
12.290406838200699
12.290391829105769
12.290376823275302
12.290361820708593
12.29034682140492
12.290331825363577
12.290316832583848
12.290301843065018
12.290286856806382
12.290271873807216
12.29025689406682
12.290241917584492
12.290226944359484
12.290211974391116
12.290197007678671
12.290182044221432
12.290167084018691
12.290152127069739
12.290137173373855
12.290122222930355
12.290107275738501
12.290092331797588
12.290077391106921
12.29006245366578
12.290047519473445
12.290032588529233
12.290017660832408
12.290002736382275
12.289987815178126
12.28997289721924
12.28995798250491
12.289943071034447
12.289928162807136
12.289913257822247
12.289898356079098
12.289883457576959
12.289868562315146
12.28985367029293
12.289838781509616
12.289823895964494
12.289809013656852
12.289794134585994
12.289779258751206
12.289764386151774
12.289749516787007
12.289734650656179
12.289719787758603
12.289704928093576
12.289690071660363
12.289675218458298
12.289660368486627
12.289645521744688
12.289630678231774
12.289615837947146
12.289601000890132
12.28958616706
12.289571336456063
12.289556509077618
12.289541684923954
12.28952686399437
12.289512046288161
12.28949723180462
12.289482420543044
12.289467612502731
12.289452807682988
12.289438006083092
12.289423207702354
12.28940841254007
12.28939362059553
12.289378831868033
12.289364046356877
12.289349264061372
12.2893344849808
12.289319709114455
12.289304936461662
12.28929016702169
12.289275400793858
12.289260637777454
12.289245877971785
12.289231121376131
12.289216367989804
12.28920161781212
12.289186870842347
12.2891721270798
12.289157386523787
12.28914264917359
12.289127915028526
12.289113184087883
12.28909845635096
12.289083731817069
12.289069010485502
12.289054292355564
12.289039577426559
12.289024865697781
12.289010157168539
12.28899545183811
12.28898074970584
12.288966050770988
12.288951355032875
12.288936662490807
12.288921973144076
12.28890728699199
12.288892604033855
12.288877924268963
12.288863247696629
12.288848574316154
12.288833904126824
12.28881923712796
12.28880457331886
12.288789912698835
12.288775255267172
12.2887606010232
12.288745949966199
12.288731302095478
12.288716657410355
12.28870201591012
12.288687377594076
12.288672742461547
12.28865811051181
12.2886434817442
12.288628856158006
12.288614233752531
12.288599614527087
12.28858499848097
12.2885703856135
12.288555775923985
12.288541169411708
12.288526566075992
12.288511965916152
12.288497368931482
12.28848277512128
12.288468184484872
12.288453597021563
12.288439012730638
12.28842443161142
12.28840985366324
12.28839527888536
12.288380707277128
12.288366138837828
12.288351573566775
12.288337011463279
12.28832245252665
12.288307896756184
12.288293344151208
12.288278794711005
12.28826424843492
12.288249705322242
12.288235165372276
12.288220628584343
12.288206094957744
12.288191564491791
12.288177037185784
12.28816251303906
12.288147992050915
12.288133474220656
12.288118959547587
12.288104448031039
12.288089939670304
12.288075434464696
12.288060932413536
12.288046433516135
12.288031937771793
12.288017445179825
12.288002955739564
12.287988469450285
12.287973986311329
12.287959506321995
12.287945029481595
12.287930555789446
12.287916085244866
12.287901617847167
12.287887153595644
12.287872692489634
12.287858234528436
12.287843779711357
12.287829328037736
12.28781487950687
12.287800434118068
12.287785991870654
12.287771552763935
12.287757116797238
12.28774268396986
12.287728254281129
12.287713827730366
12.287699404316857
12.287684984039942
12.287670566898932
12.28765615289314
12.28764174202189
12.28762733428448
12.287612929680243
12.28759852820849
12.287584129868518
12.287569734659677
12.28755534258126
12.287540953632593
12.287526567812984
12.287512185121768
12.287497805558253
12.287483429121743
12.28746905581157
12.287454685627045
12.287440318567496
12.287425954632234
12.287411593820565
12.287397236131826
12.287382881565327
12.287368530120395
12.28735418179633
12.28733983659247
12.287325494508126
12.287311155542616
12.287296819695255
12.28728248696537
12.287268157352282
12.287253830855303
12.287239507473759
12.287225187206966
12.287210870054249
12.287196556014928
12.287182245088314
12.287167937273736
12.287153632570519
12.28713933097797
12.28712503249542
12.28711073712219
12.2870964448576
12.287082155700967
12.287067869651624
12.287053586708886
12.287039306872057
12.287025030140494
12.28701075651349
12.286996485990386
12.286982218570497
12.286967954253143
12.286953693037658
12.286939434923351
12.28692517990956
12.286910927995585
12.286896679180767
12.286882433464426
12.286868190845892
12.286853951324488
12.286839714899516
12.286825481570334
12.286811251336244
12.286797024196575
12.286782800150652
12.28676857919781
12.286754361337339
12.28674014656861
12.286725934890926
12.28671172630361
12.286697520805996
12.286683318397408
12.286669119077155
12.286654922844589
12.286640729699018
12.286626539639776
12.28661235266619
12.286598168777582
12.286583987973291
12.286569810252622
12.286555635614917
12.286541464059507
12.2865272955857
12.286513130192848
12.286498967880252
12.286484808647264
12.286470652493199
12.286456499417392
12.28644234941917
12.286428202497856
12.286414058652772
12.286399917883264
12.286385780188654
12.286371645568272
12.286357514021434
12.286343385547486
12.286329260145758
12.286315137815556
12.286301018556237
12.286286902367126
12.286272789247537
12.286258679196813
12.286244572214276
12.286230468299273
12.286216367451122
12.28620226966915
12.286188174952693
12.286174083301084
12.286159994713653
12.286145909189726
12.286131826728646
12.286117747329733
12.286103670992325
12.286089597715751
12.28607552749935
12.28606146034244
12.286047396244367
12.286033335204456
12.286019277222035
12.28600522229646
12.285991170427039
12.285977121613113
12.285963075854012
12.285949033149077
12.285934993497639
12.285920956899023
12.285906923352576
12.285892892857643
12.285878865413514
12.28586484101956
12.285850819675106
12.285836801379487
12.285822786132035
12.285808773932088
12.28579476477898
12.285780758672045
12.285766755610616
12.285752755594036
12.285738758621639
12.285724764692755
12.285710773806723
12.285696785962879
12.285682801160565
12.285668819399095
12.285654840677836
12.285640864996099
12.285626892353237
12.28561292274859
12.285598956181477
12.285584992651248
12.28557103215724
12.285557074698785
12.285543120275221
12.28552916888589
12.285515220530126
12.285501275207274
12.285487332916661
12.285473393657634
12.285459457429532
12.285445524231685
12.285431594063443
12.285417666924141
12.285403742813111
12.285389821729707
12.285375903673245
12.285361988643087
12.285348076638565
12.285334167659013
12.28532026170378
12.285306358772194
12.285292458863612
12.285278561977366
12.285264668112795
12.285250777269237
12.28523688944604
12.285223004642537
12.28520912285808
12.285195244092003
12.285181368343645
12.285167495612352
12.285153625897461
12.285139759198323
12.285125895514277
12.285112034844655
12.28509817718881
12.28508432254608
12.285070470915812
12.285056622297343
12.285042776690016
12.285028934093186
12.28501509450617
12.285001257928343
12.284987424359022
12.284973593797574
12.284959766243325
12.284945941695627
12.284932120153803
12.28491830161723
12.284904486085239
12.284890673557173
12.28487686403237
12.28486305751019
12.284849253989961
12.28483545347104
12.284821655952772
12.284807861434489
12.284794069915558
12.284780281395312
12.284766495873091
12.284752713348247
12.284738933820133
12.284725157288083
12.284711383751448
12.28469761320958
12.284683845661823
12.284670081107514
12.284656319546011
12.284642560976659
12.2846288053988
12.28461505281179
12.284601303214965
12.284587556607692
12.284573812989297
12.284560072359133
12.28454633471656
12.284532600060913
12.284518868391551
12.284505139707814
12.284491414009056
12.284477691294613
12.28446397156386
12.284450254816113
12.284436541050747
12.284422830267108
12.28440912246453
12.284395417642381
12.284381715799999
12.28436801693674
12.284354321051945
12.284340628144975
12.28432693821517
12.284313251261898
12.28429956728449
12.28428588628231
12.2842722082547
12.28425853320102
12.284244861120602
12.28423119201283
12.284217525877034
12.284203862712562
12.28419020251878
12.284176545295026
12.284162891040655
12.284149239755026
12.284135591437485
12.284121946087387
12.28410830370409
12.28409466428694
12.28408102783529
12.284067394348495
12.284053763825908
12.284040136266883
12.284026511670774
12.284012890036927
12.283999271364708
12.28398565565347
12.283972042902551
12.283958433111318
12.28394482627913
12.283931222405327
12.283917621489273
12.28390402353033
12.28389042852784
12.283876836481157
12.283863247389654
12.283849661252653
12.283836078069546
12.283822497839667
12.283808920562374
12.283795346237037
12.283781774862987
12.28376820643961
12.28375464096624
12.28374107844224
12.283727518866968
12.283713962239787
12.283700408560032
12.283686857827085
12.283673310040296
12.283659765199015
12.2836462233026
12.283632684350406
12.283619148341817
12.283605615276159
12.283592085152799
12.28357855797109
12.283565033730415
12.283551512430115
12.283537994069544
12.283524478648067
12.283510966165043
12.28349745661983
12.283483950011785
12.283470446340278
12.283456945604648
12.283443447804274
12.283429952938501
12.283416461006702
12.283402972008222
12.283389485942443
12.283376002808708
12.283362522606385
12.283349045334825
12.283335570993398
12.283322099581458
12.283308631098373
12.283295165543503
12.283281702916206
12.28326824321585
12.283254786441788
12.283241332593379
12.283227881669998
12.283214433670992
12.28320098859574
12.28318754644358
12.283174107213904
12.283160670906058
12.283147237519406
12.283133807053305
12.28312037950714
12.283106954880243
12.283093533171993
12.283080114381765
12.283066698508899
12.283053285552777
12.283039875512749
12.283026468388199
12.28301306417846
12.28299966288293
12.282986264500952
12.282972869031902
12.28295947647513
12.282946086830014
12.28293270009591
12.282919316272194
12.282905935358219
12.282892557353362
12.282879182256979
12.28286581006844
12.282852440787108
12.282839074412358
12.282825710943552
12.28281235038004
12.2827989927212
12.282785637966409
12.282772286115016
12.282758937166403
12.282745591119921
12.282732247974957
12.282718907730862
12.282705570387009
12.282692235942763
12.282678904397496
12.28266557575057
12.282652250001357
12.282638927149225
12.282625607193545
12.282612290133674
12.282598975968991
12.282585664698859
12.282572356322646
12.282559050839732
12.282545748249477
12.282532448551247

12.282519151744417
12.282505857828353
12.282492566802425
12.282479278666
12.282465993418462
12.282452711059163
12.282439431587482
12.28242615500279
12.282412881304445
12.28239961049184
12.282386342564326
12.282373077521278
12.282359815362076
12.282346556086084
12.282333299692667
12.28232004618121
12.282306795551072
12.282293547801633
12.28228030293226
12.282267060942338
12.282253821831222
12.28224058559829
12.282227352242904
12.28221412176445
12.282200894162301
12.282187669435826
12.282174447584397
12.282161228607391
12.282148012504177
12.282134799274125
12.282121588916608
12.282108381431014
12.28209517681671
12.282081975073046
12.28206877619943
12.282055580195221
12.282042387059803
12.28202919679253
12.282016009392793
12.282002824859967
12.28198964319341
12.281976464392523
12.281963288456652
12.281950115385197
12.281936945177522
12.281923777832997
12.281910613351016
12.281897451730934
12.281884292972133
12.281871137073999
12.281857984035899
12.281844833857217
12.281831686537313
12.281818542075575
12.281805400471391
12.281792261724116
12.281779125833141
12.281765992797842
12.28175286261758
12.281739735291756
12.281726610819735
12.281713489200905
12.28170037043462
12.281687254520284
12.281674141457254
12.281661031244932
12.28164792388267
12.281634819369865
12.281621717705884
12.281608618890122
12.281595522921947
12.281582429800732
12.281569339525864
12.281556252096724
12.281543167512693
12.281530085773138
12.28151700687746
12.281503930825002
12.281490857615179
12.281477787247358
12.281464719720933
12.281451655035259
12.281438593189733
12.281425534183734
12.281412478016637
12.281399424687834
12.281386374196696
12.281373326542612
12.28136028172495
12.28134723974311
12.28133420059646
12.281321164284378
12.281308130806265
12.281295100161486
12.281282072349423
12.281269047369468
12.281256025221005
12.281243005903404
12.281229989416069
12.281216975758353
12.281203964929661
12.281190956929358
12.281177951756852
12.281164949411503
12.281151949892717
12.28113895319986
12.281125959332323
12.281112968289479
12.281099980070726
12.28108699467545
12.281074012103018
12.281061032352833
12.281048055424261
12.281035081316709
12.281022110029546
12.281009141562159
12.280996175913934
12.280983213084273
12.280970253072521
12.28095729587811
12.280944341500387
12.280931389938774
12.280918441192625
12.28090549526135
12.280892552144309
12.280879611840911
12.280866674350538
12.280853739672564
12.280840807806394
12.280827878751406
12.280814952506983
12.280802029072525
12.280789108447408
12.280776190631018
12.280763275622741
12.280750363421985
12.280737454028118
12.280724547440538
12.280711643658618
12.280698742681766
12.280685844509353
12.28067294914077
12.280660056575426
12.28064716681269
12.280634279851954
12.280621395692613
12.28060851433405
12.280595635775656
12.280582760016824
12.280569887056943
12.280557016895392
12.280544149531563
12.280531284964866
12.280518423194666
12.280505564220375
12.280492708041374
12.28047985465704
12.280467004066788
12.28045415626999
12.280441311266047
12.28042846905434
12.280415629634275
12.280402793005228
12.280389959166614
12.280377128117799
12.280364299858176
12.28035147438715
12.28033865170411
12.280325831808444
12.280313014699544
12.280300200376812
12.280287388839628
12.280274580087394
12.280261774119497
12.280248970935332
12.280236170534291
12.28022337291577
12.280210578079158
12.280197786023852
12.280184996749242
12.280172210254722
12.28015942653969
12.28014664560354
12.280133867445665
12.280121092065457
12.280108319462313
12.280095549635625
12.280082782584786
12.280070018309202
12.280057256808249
12.280044498081345
12.280031742127855
12.280018988947214
12.280006238538785
12.279993490901969
12.279980746036177
12.27996800394079
12.279955264615198
12.279942528058829
12.27992979427105
12.279917063251263
12.279904334998877
12.279891609513264
12.279878886793844
12.279866166840002
12.279853449651135
12.279840735226653
12.279828023565946
12.27981531466839
12.279802608533425
12.279789905160417
12.279777204548777
12.279764506697896
12.27975181160717
12.279739119276007
12.279726429703798
12.279713742889951
12.27970105883385
12.279688377534908
12.279675698992515
12.279663023206066
12.279650350174984
12.279637679898634
12.279625012376433
12.27961234760779
12.27959968559208
12.279587026328729
12.279574369817126
12.279561716056659
12.279549065046748
12.279536416786792
12.279523771276173
12.279511128514311
12.2794984885006
12.279485851234424
12.279473216715214
12.279460584942354
12.27944795591526
12.279435329633307
12.279422706095916
12.279410085302489
12.279397467252414
12.279384851945105
12.279372239379967
12.27935962955638
12.279347022473768
12.279334418131539
12.279321816529077
12.279309217665794
12.279296621541096
12.279284028154368
12.279271437505033
12.279258849592491
12.279246264416136
12.279233681975379
12.27922110226963
12.279208525298282
12.279195951060728
12.279183379556402
12.279170810784684
12.279158244744986
12.279145681436713
12.279133120859274
12.279120563012066
12.279108007894491
12.279095455505978
12.279082905845893
12.279070358913671
12.279057814708702
12.279045273230405
12.279032734478177
12.279020198451422
12.279007665149559
12.278995134571977
12.27898260671809
12.278970081587296
12.27895755917902
12.278945039492655
12.278932522527608
12.278920008283293
12.278907496759109
12.278894987954464
12.27888248186877
12.278869978501422
12.278857477851844
12.27884497991943
12.278832484703607
12.278819992203765
12.27880750241931
12.278795015349662
12.278782530994228
12.278770049352406
12.278757570423613
12.278745094207263
12.27873262070275
12.278720149909487
12.27870768182689
12.278695216454365
12.278682753791323
12.27867029383717
12.278657836591314
12.278645382053165
12.278632930222141
12.278620481097645
12.27860803467908
12.278595590965873
12.278583149957425
12.278570711653142
12.278558276052445
12.278545843154733
12.27853341295943
12.278520985465939
12.278508560673663
12.278496138582026
12.278483719190445
12.278471302498309
12.278458888505057
12.278446477210077
12.27843406861278
12.278421662712605
12.278409259508944
12.278396859001205
12.278384461188821
12.27837206607118
12.278359673647705
12.278347283917817
12.278334896880914
12.27832251253643
12.278310130883742
12.278297751922308
12.278285375651508
12.278273002070774
12.278260631179501
12.278248262977131
12.278235897463055
12.278223534636684
12.278211174497455
12.278198817044755
12.278186462278029
12.278174110196659
12.278161760800089
12.278149414087709
12.278137070058953
12.278124728713228
12.278112390049944
12.278100054068524
12.278087720768388
12.278075390148945
12.278063062209599
12.278050736949785
12.278038414368908
12.278026094466389
12.27801377724165
12.278001462694094
12.277989150823137
12.277976841628217
12.277964535108728
12.277952231264095
12.277939930093735
12.277927631597064
12.27791533577351
12.27790304262248
12.277890752143376
12.277878464335638
12.277866179198687
12.27785389673193
12.277841616934781
12.277829339806669
12.277817065346994
12.2778047935552
12.277792524430694
12.277780257972887
12.277767994181204
12.27775573305507
12.277743474593892
12.277731218797095
12.277718965664107
12.277706715194338
12.277694467387207
12.27768222224214
12.277669979758546
12.277657739935847
12.277645502773474
12.277633268270845
12.277621036427373
12.277608807242478
12.27759658071559
12.277584356846113
12.277572135633482
12.277559917077118
12.277547701176443
12.277535487930862
12.277523277339812
12.277511069402715
12.277498864118993
12.27748666148805
12.27747446150933
12.277462264182239
12.27745006950621
12.27743787748066
12.277425688105014
12.277413501378696
12.277401317301116
12.277389135871713
12.277376957089905
12.277364780955104
12.277352607466755
12.27734043662426
12.277328268427055
12.277316102874552
12.277303939966192
12.277291779701377
12.277279622079545
12.277267467100122
12.277255314762535
12.277243165066189
12.277231018010527
12.277218873594963
12.277206731818934
12.277194592681848
12.277182456183139
12.27717032232223
12.277158191098545
12.277146062511523
12.277133936560574
12.277121813245115
12.277109692564604
12.27709757451843
12.277085459106042
12.27707334632685
12.277061236180307
12.277049128665821
12.277037023782805
12.277024921530716
12.277012821908954
12.277000724916961
12.27698863055417
12.276976538819985
12.276964449713844
12.276952363235182
12.27694027938341
12.276928198157982
12.276916119558301
12.276904043583809
12.276891970233923
12.276879899508073
12.2768678314057
12.276855765926213
12.276843703069067
12.276831642833653
12.276819585219434
12.276807530225822
12.276795477852248
12.276783428098136
12.276771380962929
12.27675933644605
12.276747294546926
12.276735255264986
12.276723218599658
12.276711184550384
12.276699153116578
12.276687124297682
12.276675098093115
12.27666307450232
12.276651053524715
12.276639035159741
12.276627019406826
12.276615006265397
12.276602995734887
12.276590987814728
12.276578982504352
12.276566979803182
12.276554979710658
12.276542982226209
12.276530987349268
12.276518995079266
12.276507005415635
12.276495018357819
12.276483033905215
12.27647105205729
12.27645907281347
12.276447096173172
12.276435122135842
12.276423150700914
12.276411181867811
12.276399215635978
12.276387252004834
12.276375290973828
12.276363332542383
12.27635137670993
12.276339423475921
12.276327472839771
12.276315524800912
12.276303579358792
12.276291636512841
12.276279696262486
12.276267758607174
12.276255823546318
12.276243891079375
12.27623196120577
12.27622003392494
12.276208109236329
12.27619618713935
12.276184267633456
12.276172350718069
12.276160436392637
12.276148524656598
12.276136615509369
12.276124708950412
12.27611280497914
12.276100903595
12.27608900479743
12.27607710858586
12.276065214959734
12.276053323918482
12.276041435461531
12.27602954958834
12.276017666298339
12.276005785590959
12.275993907465638
12.275982031921819
12.275970158958932
12.275958288576415
12.275946420773726
12.275934555550265
12.275922692905505
12.275910832838868
12.275898975349792
12.27588712043772
12.275875268102086
12.275863418342336
12.275851571157899
12.275839726548222
12.275827884512731
12.275816045050895
12.275804208162114
12.275792373845855
12.27578054210155
12.275768712928631
12.275756886326551
12.275745062294744
12.275733240832647
12.275721421939698
12.275709605615344
12.275697791859029
12.275685980670177
12.275674172048237
12.275662365992662
12.275650562502866
12.275638761578332
12.275626963218453
12.275615167422705
12.275603374190515
12.27559158352132
12.275579795414572
12.275568009869714
12.275556226886176
12.275544446463414
12.27553266860085
12.275520893297946
12.275509120554137
12.27549735036886
12.275485582741567
12.2754738176717
12.275462055158693
12.275450295201995
12.275438537801048
12.275426782955293
12.275415030664183

12.275403280927147
12.275391533743644
12.275379789113105
12.275368047034968
12.275356307508705
12.275344570533735
12.2753328361095
12.275321104235465
12.275309374911055
12.275297648135727
12.275285923908925
12.275274202230078
12.275262483098643
12.275250766514079
12.2752390524758
12.27522734098328
12.275215632035948
12.275203925633255
12.275192221774647
12.275180520459562
12.275168821687464
12.275157125457769
12.275145431769953
12.275133740623449
12.275122052017696
12.275110365952164
12.275098682426266
12.275087001439474
12.275075322991235
12.275063647080986
12.275051973708175
12.27504030287225
12.27502863457267
12.275016968808856
12.275005305580281
12.274993644886377
12.274981986726603
12.274970331100402
12.274958678007213
12.274947027446506
12.274935379417702
12.274923733920279
12.274912090953665
12.274900450517306
12.274888812610667
12.274877177233193
12.274865544384308
12.2748539140635
12.2748422862702
12.274830661003847
12.2748190382639
12.274807418049804
12.274795800361037
12.274784185197017
12.274772572557191
12.27476096244103
12.274749354847973
12.274737749777469
12.274726147228979
12.274714547201945
12.27470294969581
12.274691354710038
12.274679762244082
12.274668172297382
12.27465658486939
12.274644999959566
12.274633417567365
12.27462183769221
12.274610260333596
12.274598685490933
12.274587113163703
12.274575543351343
12.274563976053301
12.27455241126905
12.274540848998019
12.27452928923968
12.27451773199347
12.27450617725885
12.274494625035274
12.274483075322193
12.27447152811904
12.274459983425315
12.274448441240423
12.274436901563849
12.274425364395027
12.274413829733424
12.27440229757849
12.27439076792967
12.274379240786438
12.274367716148234
12.274356194014517
12.274344674384729
12.274333157258333
12.274321642634801
12.274310130513566
12.274298620894083
12.274287113775816
12.274275609158208
12.274264107040747
12.274252607422845
12.274241110303977
12.274229615683602
12.274218123561177
12.274206633936144
12.274195146807974
12.274183662176123
12.274172180040038
12.274160700399174
12.274149223253
12.274137748600955
12.274126276442505
12.27411480677711
12.27410333960423
12.274091874923313
12.274080412733825
12.27406895303521
12.274057495826938
12.274046041108441
12.274034588879223
12.27402313913871
12.27401169188636
12.274000247121641
12.273988804844006
12.273977365052922
12.273965927747822
12.273954492928201
12.273943060593483
12.273931630743155
12.273920203376655
12.273908778493457
12.273897356093
12.273885936174764
12.273874518738207
12.273863103782778
12.273851691307936
12.273840281313145
12.273828873797884
12.273817468761566
12.273806066203687
12.273794666123703
12.27378326852107
12.273771873395257
12.273760480745699
12.273749090571895
12.273737702873262
12.273726317649295
12.273714934899443
12.273703554623163
12.273692176819925
12.273680801489188
12.273669428630402
12.273658058243038
12.273646690326567
12.273635324880443
12.27362396190411
12.273612601397065
12.273601243358733
12.27358988778861
12.273578534686136
12.27356718405078
12.273555835882004
12.273544490179276
12.273533146942054
12.2735218061698
12.273510467861977
12.273499132018058
12.273487798637484
12.273476467719743
12.273465139264284
12.273453813270573
12.273442489738082
12.273431168666256
12.273419850054587
12.27340853390251
12.273397220209516
12.273385908975047
12.273374600198583
12.273363293879576
12.273351990017504
12.273340688611823
12.273329389661997
12.273318093167497
12.273306799127774
12.273295507542308
12.273284218410575
12.27327293173202
12.273261647506118
12.273250365732324
12.273239086410115
12.273227809538954
12.273216535118307
12.27320526314764
12.273193993626418
12.273182726554106
12.273171461930177
12.273160199754098
12.273148940025331
12.273137682743346
12.273126427907602
12.273115175517573
12.273103925572727
12.27309267807253
12.273081433016456
12.273070190403956
12.273058950234514
12.273047712507593
12.273036477222664
12.273025244379186
12.273014013976635
12.273002786014466
12.272991560492168
12.272980337409194
12.27296911676502
12.272957898559119
12.27294668279095
12.272935469459988
12.2729242585657
12.272913050107553
12.272901844085027
12.27289064049758
12.272879439344674
12.2728682406258
12.272857044340423
12.272845850487998
12.272834659068
12.272823470079924
12.272812283523205
12.272801099397327
12.272789917701777
12.272778738436008
12.272767561599485
12.27275638719169
12.272745215212097
12.272734045660167
12.272722878535387
12.272711713837207
12.272700551565105
12.272689391718567
12.272678234297052
12.27266707930003
12.272655926726985
12.272644776577378
12.272633628850675
12.272622483546378
12.27261134066393
12.272600200202808
12.272589062162496
12.27257792654245
12.272566793342161
12.2725556625611
12.272544534198719
12.27253340825452
12.272522284727955
12.272511163618514
12.272500044925655
12.272488928648857
12.272477814787601
12.272466703341344
12.272455594309587
12.272444487691777
12.2724333834874
12.27242228169594
12.272411182316858
12.272400085349629
12.272388990793731
12.272377898648635
12.272366808913825
12.272355721588774
12.272344636672948
12.272333554165838
12.272322474066895
12.27231139637562
12.272300321091475
12.272289248213939
12.27227817774249
12.272267109676603
12.272256044015752
12.272244980759403
12.272233919907055
12.27222286145817
12.272211805412214
12.272200751768699
12.27218970052707
12.272178651686813
12.272167605247395
12.272156561208325
12.27214551956905
12.272134480329049
12.272123443487818
12.27211240904482
12.272101376999526
12.272090347351442
12.272079320100017
12.272068295244736
12.272057272785094
12.27204625272055
12.272035235050577
12.272024219774682
12.272013206892327
12.272002196402983
12.27199118830614
12.27198018260127
12.271969179287865
12.271958178365397
12.271947179833324
12.271936183691164
12.271925189938361
12.271914198574423
12.271903209598817
12.271892223011013
12.271881238810519
12.271870256996786
12.271859277569298
12.271848300527555
12.271837325871026
12.271826353599192
12.271815383711523
12.27180441620751
12.271793451086642
12.271782488348395
12.271771527992232
12.271760570017662
12.271749614424158
12.271738661211181
12.27172771037824
12.2717167619248
12.271705815850346
12.271694872154367
12.271683930836343
12.271672991895752
12.271662055332065
12.27165112114478
12.271640189333384
12.271629259897354
12.271618332836159
12.271607408149302
12.27159648583626
12.271585565896505
12.271574648329535
12.271563733134826
12.271552820311857
12.271541909860122
12.271531001779096
12.271520096068278
12.271509192727125
12.27149829175514
12.271487393151814
12.271476496916607
12.271465603049021
12.271454711548541
12.271443822414634
12.27143293564681
12.271422051244533
12.271411169207303
12.27140028953459
12.271389412225895
12.271378537280691
12.271367664698474
12.271356794478711
12.271345926620905
12.271335061124534
12.271324197989099
12.271313337214062
12.271302478798917
12.271291622743156
12.271280769046262
12.271269917707729
12.271259068727025
12.271248222103651
12.271237377837089
12.271226535926846
12.271215696372362
12.271204859173166
12.271194024328734
12.271183191838539
12.271172361702089
12.271161533918866
12.27115070848834
12.271139885410028
12.271129064683391
12.271118246307934
12.271107430283134
12.271096616608492
12.271085805283477
12.271074996307597
12.27106418968033
12.271053385401173
12.271042583469603
12.271031783885114
12.271020986647194
12.271010191755343
12.270999399209023
12.270988609007762
12.270977821151016
12.270967035638286
12.270956252469068
12.270945471642847
12.270934693159107
12.270923917017342
12.270913143217058
12.270902371757709
12.270891602638816
12.270880835859861
12.270870071420328
12.270859309319713
12.270848549557506
12.27083779213321
12.270827037046297
12.270816284296266
12.270805533882601
12.270794785804815
12.270784040062374
12.27077329665477
12.270762555581522
12.270751816842091
12.270741080435988
12.270730346362692
12.270719614621713
12.270708885212526
12.270698158134625
12.270687433387513
12.27067671097068
12.270665990883604
12.270655273125788
12.270644557696736
12.270633844595926
12.270623133822857
12.270612425377012
12.270601719257893
12.270591015465007
12.270580313997831
12.270569614855843
12.27055891803857
12.270548223545486
12.270537531376092
12.270526841529879
12.270516154006348
12.270505468804982
12.270494785925278
12.270484105366737
12.270473427128849
12.270462751211104
12.270452077613005
12.270441406334044
12.270430737373728
12.270420070731516
12.270409406406948
12.27039874439949
12.270388084708655
12.270377427333921
12.270366772274796
12.270356119530769
12.270345469101345
12.270334820986012
12.270324175184268
12.270313531695603
12.270302890519536
12.27029225165554
12.270281615103123
12.270270980861776
12.270260348930996
12.27024971931028
12.270239091999128

12.27022846699704
12.270217844303508
12.270207223918032
12.270196605840104
12.270185990069226
12.270175376604897
12.27016476544662
12.270154156593879
12.270143550046177
12.270132945803017
12.2701223438639
12.270111744228302
12.27010114689576
12.270090551865737
12.270079959137748
12.270069368711303
12.270058780585872
12.270048194760971
12.270037611236098
12.27002703001075
12.270016451084434
12.270005874456643
12.269995300126876
12.269984728094629
12.269974158359403
12.269963590920717
12.269953025778044
12.269942462930905
12.269931902378785
12.269921344121187
12.269910788157627
12.269900234487578
12.269889683110568
12.269879134026075
12.269868587233614
12.26985804273268
12.26984750052278
12.269836960603413
12.269826422974083
12.269815887634275
12.269805354583507
12.26979482382128
12.269784295347087
12.269773769160444
12.26976324526084
12.26975272364778
12.269742204320764
12.269731687279302
12.269721172522898
12.269710660051045
12.26970014986324
12.26968964195901
12.269679136337833
12.26966863299923
12.26965813194268
12.269647633167711
12.269637136673824
12.26962664246051
12.269616150527273
12.269605660873635
12.269595173499074
12.26958468840311
12.269574205585242
12.26956372504499
12.26955324678182
12.26954277079528
12.269532297084847
12.269521825650017
12.269511356490327
12.269500889605268
12.269490424994332
12.269479962657039
12.26946950259288
12.269459044801375
12.269448589282026
12.269438136034331
12.269427685057796
12.26941723635193
12.269406789916252
12.269396345750248
12.269385903853427
12.2693754642253
12.269365026865373
12.269354591773148
12.26934415894814
12.269333728389851
12.269323300097776
12.269312874071439
12.269302450310333
12.269292028813982
12.269281609581872
12.269271192613528
12.269260777908444
12.269250365466128
12.269239955286102
12.269229547367852
12.269219141710913
12.269208738314761
12.269198337178931
12.269187938302927
12.269177541686235
12.26916714732838
12.269156755228884
12.269146365387217
12.269135977802918
12.269125592475492
12.269115209404443
12.269104828589283
12.269094450029517
12.269084073724645
12.269073699674196
12.269063327877666
12.269052958334573
12.269042591044409
12.269032226006699
12.269021863220958
12.269011502686677
12.269001144403388
12.268990788370582
12.268980434587784
12.268970083054485
12.268959733770206
12.26894938673447
12.268939041946759
12.268928699406613
12.268918359113526
12.268908021067016
12.268897685266582
12.268887351711752
12.268877020402021
12.268866691336918
12.268856364515935
12.268846039938596
12.26883571760441
12.268825397512906
12.268815079663547
12.2688047640559
12.26879445068943
12.26878413956369
12.26877383067817
12.26876352403239
12.26875321962585
12.268742917458072
12.268732617528569
12.268722319836861
12.26871202438245
12.26870173116484
12.268691440183575
12.268681151438138
12.268670864928064
12.268660580652835
12.268650298611998
12.268640018805058
12.268629741231516
12.268619465890904
12.268609192782721
12.26859892190648
12.268588653261713
12.26857838684792
12.268568122664611
12.268557860711317
12.268547600987533
12.268537343492781
12.268527088226591
12.268516835188466
12.268506584377912
12.268496335794461
12.268486089437609
12.268475845306888
12.268465603401806
12.268455363721882
12.268445126266638
12.268434891035566
12.268424658028202
12.268414427244062
12.268404198682656
12.268393972343498
12.268383748226107
12.268373526330013
12.2683633066547
12.268353089199715
12.268342873964558
12.268332660948756
12.26832245015182
12.268312241573273
12.268302035212624
12.26829183106939
12.268281629143097
12.268271429433257
12.26826123193939
12.268251036661006
12.268240843597638
12.268230652748793
12.268220464113982
12.26821027769274
12.268200093484564
12.268189911488996
12.268179731705533
12.268169554133717
12.268159378773051
12.268149205623054
12.26813903468324
12.268128865953136
12.268118699432268
12.268108535120144
12.26809837301629
12.268088213120214
12.268078055431449
12.268067899949493
12.268057746673895
12.268047595604152
12.2680374467398
12.268027300080352
12.268017155625317
12.268007013374245
12.267996873326625
12.267986735481992
12.267976599839864
12.267966466399754
12.267956335161198
12.26794620612371
12.267936079286804
12.267925954650014
12.26791583221285
12.267905711974837
12.267895593935494
12.267885478094353
12.267875364450916
12.26786525300473
12.267855143755291
12.267845036702132
12.267834931844785
12.267824829182764
12.267814728715585
12.26780463044277
12.267794534363851
12.267784440478344
12.267774348785784
12.267764259285666
12.267754171977543
12.26774408686092
12.267734003935331
12.267723923200286
12.26771384465532
12.267703768299945
12.267693694133694
12.26768362215609
12.267673552366661
12.26766348476491
12.267653419350381
12.26764335612259
12.26763329508106
12.267623236225328
12.2676131795549
12.267603125069314
12.267593072768085
12.26758302265074
12.2675729747168
12.267562928965813
12.267552885397269
12.267542844010707
12.26753280480567
12.267522767781658
12.267512732938204
12.267502700274841
12.267492669791094
12.267482641486474
12.267472615360525
12.26746259141276
12.267452569642709
12.267442550049898
12.267432532633856
12.267422517394097
12.267412504330165
12.267402493441574
12.26739248472786
12.267382478188543
12.267372473823157
12.267362471631214
12.267352471612249
12.2673424737658
12.267332478091374
12.267322484588508
12.267312493256734
12.267302504095575
12.26729251710457
12.26728253228322
12.267272549631068
12.267262569147647
12.267252590832486
12.267242614685099
12.267232640705023
12.267222668891792
12.267212699244915
12.267202731763945
12.267192766448401
12.267182803297809
12.267172842311695
12.267162883489585
12.267152926831026
12.26714297233553
12.267133020002627
12.267123069831866
12.267113121822751
12.267103175974823
12.267093232287612
12.267083290760644
12.267073351393458
12.267063414185579
12.26705347913653
12.267043546245842
12.26703361551305
12.267023686937689
12.267013760519282
12.267003836257365
12.266993914151469
12.266983994201118
12.266974076405843
12.266964160765182
12.266954247278662
12.266944335945816
12.266934426766174
12.266924519739263
12.266914614864627
12.266904712141779
12.266894811570268
12.26688491314962
12.266875016879359
12.266865122759032
12.266855230788169
12.26684534096627
12.266835453292915
12.266825567767608
12.266815684389888
12.266805803159293
12.26679592407534
12.266786047137582
12.266776172345539
12.266766299698741
12.266756429196741
12.266746560839051
12.266736694625207
12.266726830554754
12.266716968627222
12.266707108842139
12.266697251199039
12.266687395697458
12.266677542336932
12.26666769111699
12.266657842037175
12.266647995097008
12.266638150296028
12.266628307633786
12.266618467109797
12.266608628723588
12.266598792474717
12.266588958362721
12.266579126387121
12.26656929654744
12.266559468843234
12.266549643274027
12.266539819839362
12.266529998538767
12.26652017937179
12.266510362337955
12.266500547436802
12.266490734667876
12.266480924030688
12.26647111552479
12.266461309149726
12.26645150490502
12.266441702790209
12.266431902804833
12.266422104948433
12.266412309220534
12.266402515620682
12.26639272414841
12.266382934803254
12.266373147584767
12.266363362492465
12.266353579525887
12.26634379868458
12.266334019968085
12.266324243375921
12.266314468907641
12.266304696562782
12.266294926340882
12.266285158241464
12.266275392264088
12.266265628408282
12.266255866673577
12.266246107059526
12.266236349565652
12.266226594191505
12.266216840936629
12.266207089800552
12.26619734078281
12.266187593882949
12.266177849100503
12.266168106435021
12.266158365886032
12.26614862745308
12.266138891135707
12.266129156933447
12.266119424845833
12.266109694872428
12.266099967012758
12.266090241266363
12.26608051763277
12.266070796111542
12.266061076702197
12.266051359404303
12.266041644217378
12.266031931140976
12.26602222017463
12.266012511317886
12.266002804570268
12.265993099931341
12.265983397400635
12.26597369697769
12.265963998662052
12.265954302453261
12.265944608350843
12.265934916354373
12.265925226463365
12.265915538677369
12.26590585299592
12.26589616941859
12.265886487944877
12.26587680857435
12.265867131306553
12.265857456141017
12.26584778307728
12.2658381121149
12.265828443253412
12.265818776492363
12.2658091118313
12.265799449269748
12.265789788807261
12.265780130443385
12.265770474177662
12.265760820009634
12.265751167938843
12.265741517964843
12.265731870087153
12.265722224305339
12.265712580618946
12.265702939027495
12.265693299530561
12.265683662127664
12.265674026818363
12.2656643936022
12.26565476247871
12.265645133447444
12.265635506507941
12.26562588165977
12.265616258902437
12.265606638235518
12.265597019658548
12.26558740317107
12.265577788772623
12.265568176462777
12.265558566241051
12.265548958106999
12.265539352060168
12.265529748100109
12.26552014622636
12.265510546438465
12.265500948735983
12.265491353118453
12.265481759585416
12.26547216813643
12.265462578771025
12.265452991488758
12.265443406289183
12.265433823171831
12.265424242136268
12.265414663182005
12.265405086308645
12.265395511515683
12.265385938802693
12.26537636816921
12.265366799614792
12.265357233138989
12.265347668741342
12.2653381064214
12.265328546178708
12.265318988012803
12.26530943192326
12.265299877909609
12.265290325971401
12.265280776108195
12.265271228319518
12.265261682604935
12.26525213896399
12.265242597396242
12.265233057901224
12.265223520478495
12.2652139851276
12.26520445184808
12.265194920639487
12.265185391501399
12.265175864433333
12.265166339434838
12.265156816505492
12.26514729564481
12.265137776852368
12.265128260127701
12.265118745470375
12.26510923287992
12.265099722355895
12.26509021389786
12.265080707505353
12.265071203177925
12.265061700915139
12.265052200716529
12.265042702581658
12.265033206510074
12.265023712501312
12.265014220554953
12.265004730670533
12.264995242847597
12.264985757085702
12.264976273384411
12.264966791743253
12.264957312161794
12.264947834639592
12.264938359176181
12.264928885771134
12.264919414423979
12.264909945134281
12.264900477901609
12.264891012725483
12.264881549605471
12.26487208854113
12.264862629532008

12.264853172577666
12.26484371767763
12.264834264831489
12.264824814038775
12.264815365299043
12.264805918611849
12.264796473976746
12.264787031393292
12.264777590861042
12.264768152379535
12.264758715948327
12.264749281566992
12.264739849235072
12.264730418952107
12.264720990717667
12.26471156453131
12.264702140392572
12.264692718301033
12.26468329825622
12.264673880257716
12.264664464305044
12.264655050397788
12.26464563853549
12.264636228717706
12.264626820943997
12.264617415213898
12.264608011526988
12.264598609882814
12.264589210280915
12.26457981272088
12.264570417202235
12.264561023724559
12.26455163228739
12.264542242890286
12.264532855532817
12.26452347021453
12.264514086934975
12.264504705693719
12.264495326490318
12.264485949324323
12.264476574195292
12.264467201102772
12.264457830046343
12.264448461025548
12.264439094039941
12.264429729089084
12.264420366172537
12.264411005289853
12.264401646440595
12.264392289624302
12.264382934840556
12.264373582088904
12.26436423136891
12.26435488268012
12.264345536022102
12.264336191394413
12.264326848796603
12.264317508228242
12.264308169688881
12.264298833178076
12.26428949869539
12.264280166240395
12.264270835812622
12.264261507411648
12.264252181037032
12.264242856688325
12.264233534365095
12.264224214066903
12.264214895793282
12.264205579543832
12.264196265318084
12.264186953115606
12.264177642935968
12.264168334778713
12.264159028643409
12.26414972452961
12.26414042243689
12.264131122364791
12.264121824312893
12.264112528280743
12.264103234267903
12.264093942273941
12.264084652298402
12.264075364340869
12.264066078400882
12.264056794478014
12.264047512571826
12.264038232681878
12.264028954807731
12.26401967894894
12.264010405105061
12.264001133275698
12.263991863460355
12.26398259565863
12.263973329870069
12.263964066094248
12.263954804330712
12.263945544579036
12.26393628683879
12.263927031109505
12.263917777390782
12.263908525682151
12.263899275983201
12.263890028293476
12.263880782612544
12.263871538939979
12.263862297275319
12.26385305761815
12.263843819968029
12.263834584324517
12.26382535068718
12.263816119055575
12.26380688942928
12.263797661807834
12.263788436190827
12.263779212577814
12.26376999096835
12.263760771362012
12.26375155375836
12.263742338156955
12.263733124557367
12.263723912959142
12.263714703361872
12.263705495765105
12.263696290168411
12.263687086571352
12.263677884973498
12.263668685374403
12.263659487773642
12.263650292170784
12.26364109856538
12.263631906957015
12.263622717345235
12.263613529729618
12.263604344109723
12.263595160485114
12.26358597885537
12.263576799220045
12.263567621578709
12.263558445930926
12.263549272276268
12.2635401006143
12.263530930944567
12.263521763266674
12.263512597580156
12.2635034338846
12.26349427217957
12.263485112464608
12.263475954739313
12.263466799003242
12.263457645255958
12.263448493497025
12.26343934372603
12.263430195942513
12.26342105014606
12.263411906336222
12.263402764512595
12.263393624674723
12.263384486822181
12.263375350954535
12.263366217071367
12.263357085172228
12.263347955256682
12.263338827324322
12.263329701374694
12.263320577407375
12.263311455421942
12.263302335417945
12.263293217394969
12.263284101352578
12.263274987290337
12.263265875207818
12.263256765104599
12.263247656980237
12.263238550834314
12.263229446666378
12.263220344476014
12.263211244262799
12.263202146026282
12.263193049766063
12.263183955481674
12.26317486317272
12.263165772838754
12.263156684479336
12.263147598094067
12.263138513682485
12.263129431244188
12.263120350778724
12.26311127228568
12.26310219576462
12.263093121215112
12.263084048636738
12.263074978029055
12.263065909391651
12.263056842724076
12.263047778025923
12.263038715296746
12.263029654536128
12.263020595743642
12.263011538918844
12.263002484061317
12.262993431170651
12.262984380246383
12.262975331288112
12.262966284295402
12.262957239267815
12.262948196204938
12.262939155106338
12.262930115971573
12.262921078800257
12.262912043591921
12.262903010346156
12.262893979062536
12.262884949740627
12.262875922380003
12.262866896980253
12.262857873540923
12.262848852061607
12.26283983254188
12.262830814981303
12.262821799379449
12.26281278573591
12.26280377405024
12.262794764322026
12.262785756550834
12.262776750736247
12.262767746877836
12.262758744975166
12.262749745027822
12.262740747035382
12.262731750997407
12.262722756913474
12.26271376478318
12.262704774606066
12.262695786381736
12.262686800109748
12.26267781578969
12.262668833421122
12.262659853003642
12.262650874536792
12.26264189802018
12.262632923453369
12.262623950835925
12.262614980167443
12.26260601144749
12.262597044675635
12.26258807985147
12.262579116974553
12.262570156044477
12.262561197060807
12.262552240023126
12.262543284931008
12.26253433178403
12.262525380581776
12.262516431323805
12.262507484009715
12.262498538639067
12.262489595211443
12.262480653726435
12.262471714183585
12.262462776582517
12.262453840922763
12.262444907203937
12.262435975425602
12.262427045587332
12.262418117688707
12.262409191729308
12.262400267708712
12.262391345626497
12.262382425482246
12.26237350727553
12.262364591005934
12.262355676673025
12.2623467642764
12.262337853815621
12.262328945290282
12.262320038699935
12.262311134044191
12.262302231322614
12.262293330534792
12.262284431680296
12.262275534758702
12.262266639769592
12.262257746712553
12.262248855587163
12.262239966392993
12.262231079129627
12.262222193796653
12.262213310393637
12.262204428920178
12.262195549375834
12.262186671760212
12.262177796072866
12.262168922313387
12.262160050481357
12.262151180576359
12.262142312597963
12.262133446545766
12.262124582419341
12.262115720218269
12.26210685994213
12.262098001590493
12.262089145162973
12.262080290659119
12.262071438078532
12.262062587420777
12.262053738685454
12.262044891872133
12.262036046980398
12.262027204009842
12.26201836296002
12.26200952383054
12.262000686620974
12.261991851330905
12.261983017959928
12.261974186507588
12.261965356973521
12.26195652935727
12.261947703658425
12.26193887987659
12.261930058011309
12.261921238062204
12.26191242002884
12.261903603910802
12.261894789707679
12.261885977419045
12.261877167044485
12.261868358583591
12.261859552035942
12.261850747401114
12.26184194467871
12.261833143868294
12.261824344969463
12.261815547981787
12.261806752904873
12.261797959738278
12.261789168481616
12.261780379134448
12.261771591696368
12.26176280616696
12.261754022545812
12.261745240832504
12.261736461026617
12.261727683127743
12.261718907135469
12.261710133049368
12.261701360869052
12.261692590594084
12.26168382222405
12.261675055758541
12.261666291197136
12.261657528539429
12.261648767785008
12.26164000893346
12.26163125198436
12.261622496937296
12.26161374379186
12.26160499254764
12.261596243204218
12.261587495761171
12.261578750218119
12.261570006574615
12.26156126483025
12.261552524984628
12.261543787037315
12.261535050987918
12.261526316836008
12.261517584581183
12.261508854223033
12.261500125761131
12.261491399195076
12.261482674524453
12.261473951748851
12.261465230867854
12.26145651188105
12.261447794788024
12.261439079588378
12.261430366281695
12.261421654867547
12.26141294534554
12.261404237715256
12.26139553197628
12.26138682812822
12.261378126170635
12.261369426103137
12.26136072792531
12.261352031636735
12.26134333723701
12.261334644725714
12.261325954102443
12.261317265366788
12.261308578518339
12.26129989355668
12.26129121048139
12.261282529292089
12.261273849988347
12.261265172569761
12.261256497035893
12.26124782338638
12.26123915162079
12.261230481738691
12.261221813739713
12.261213147623424
12.261204483389417
12.261195821037283
12.26118716056661
12.261178501976996
12.261169845268029
12.261161190439298
12.261152537490398
12.261143886420916
12.261135237230443
12.261126589918575
12.261117944484903
12.261109300929016
12.261100659250495
12.26109201944894
12.261083381523951
12.261074745475119
12.261066111302032
12.261057479004265
12.261048848581446
12.26104022003314
12.261031593358933
12.261022968558452
12.261014345631255
12.261005724576943
12.26099710539512
12.26098848808538
12.260979872647303
12.260971259080486
12.260962647384513
12.260954037559005
12.260945429603515
12.260936823517671
12.260928219301054
12.260919616953256
12.260911016473873
12.2609024178625
12.260893821118717
12.260885226242141
12.260876633232352
12.260868042088942
12.260859452811514
12.260850865399652
12.260842279852955
12.260833696171026
12.260825114353437
12.260816534399801
12.260807956309714
12.260799380082753
12.260790805718536
12.260782233216645
12.260773662576684
12.260765093798234
12.260756526880886
12.260747961824254
12.260739398627928
12.260730837291495
12.260722277814562
12.26071372019672
12.260705164437557
12.260696610536675
12.260688058493674
12.260679508308149
12.260670959979683
12.260662413507886
12.260653868892355
12.260645326132678
12.260636785228446
12.260628246179273
12.260619708984747
12.260611173644461
12.260602640158016
12.260594108525014
12.260585578745042
12.260577050817707
12.260568524742586
12.2605600005193
12.260551478147443
12.260542957626592
12.260534438956363
12.260525922136345
12.260517407166141
12.260508894045357
12.26050038277356
12.260491873350391
12.260483365775412
12.26047486004825
12.260466356168466
12.26045785413569
12.260449353949515
12.260440855609525
12.260432359115338
12.260423864466532
12.260415371662727
12.260406880703506
12.260398391588476
12.260389904317227
12.260381418889367
12.26037293530449
12.2603644535622
12.260355973662094
12.260347495603764
12.260339019386825
12.260330545010866
12.260322072475487
12.260313601780286
12.260305132924868
12.26029666590883
12.260288200731772
12.260279737393294
12.26027127589301
12.260262816230494
12.260254358405357
12.260245902417209
12.260237448265636
12.260228995950257
12.260220545470654
12.26021209682644
12.260203650017202
12.260195205042566
12.260186761902103
12.260178320595433
12.260169881122144
12.260161443481861
12.260153007674168
12.260144573698662
12.260136141554954
12.260127711242632
12.26011928276132
12.260110856110606
12.260102431290093
12.260094008299397
12.260085587138082
12.260077167805788
12.260068750302112
12.260060334626644
12.260051920778984
12.260043508758745
12.260035098565528
12.260026690198929
12.260018283658564
12.260009878944025
12.26000147605492
12.259993074990842
12.259984675751408
12.259976278336218
12.259967882744858
12.25995948897696
12.259951097032106
12.259942706909902
12.259934318609968
12.259925932131882
12.259917547475274
12.259909164639724
12.259900783624854
12.259892404430266
12.259884027055552
12.25987565150033
12.259867277764192
12.259858905846757
12.259850535747605
12.25984216746637
12.259833801002637
12.259825436356019
12.259817073526117
12.259808712512545
12.259800353314898
12.259791995932769

12.259783640365804
12.259775286613564
12.259766934675675
12.259758584551738
12.25975023624138
12.259741889744161
12.259733545059724
12.259725202187665
12.259716861127588
12.2597085218791
12.259700184441803
12.259691848815311
12.259683514999223
12.259675182993153
12.25966685279669
12.259658524409465
12.259650197831068
12.259641873061112
12.259633550099196
12.259625228944934
12.25961690959794
12.259608592057807
12.259600276324147
12.259591962396573
12.259583650274683
12.259575339958083
12.259567031446391
12.259558724739211
12.259550419836142
12.259542116736808
12.259533815440797
12.259525515947738
12.25951721825722
12.259508922368864
12.25950062828227
12.259492335997049
12.259484045512812
12.259475756829163
12.25946746994571
12.259459184862072
12.259450901577846
12.259442620092639
12.259434340406067
12.259426062517731
12.25941778642726
12.25940951213424
12.259401239638294
12.25939296893902
12.259384700036039
12.25937643292895
12.259368167617367
12.259359904100899
12.259351642379158
12.259343382451762
12.2593351243183
12.259326867978393
12.25931861343165
12.259310360677684
12.259302109716113
12.259293860546524
12.259285613168545
12.25927736758178
12.25926912378585
12.259260881780346
12.259252641564895
12.2592444031391
12.25923616650258
12.259227931654932
12.259219698595775
12.259211467324723
12.259203237841387
12.25919501014537
12.259186784236293
12.259178560113764
12.2591703377774
12.259162117226799
12.259153898461573
12.259145681481352
12.259137466285729
12.259129252874336
12.259121041246756
12.259112831402629
12.259104623341548
12.259096417063137
12.259088212567018
12.259080009852767
12.259071808920035
12.25906360976841
12.259055412397526
12.259047216806971
12.259039022996374
12.259030830965347
12.259022640713498
12.259014452240455
12.2590062655458
12.258998080629173
12.258989897490178
12.258981716128428
12.258973536543541
12.258965358735132
12.258957182702803
12.258949008446175
12.258940835964868
12.258932665258495
12.258924496326655
12.258916329168985
12.258908163785069
12.258900000174545
12.258891838337032
12.258883678272122
12.258875519979451
12.25886736345861
12.258859208709243
12.258851055730933
12.25884290452332
12.258834755086012
12.25882660741862
12.258818461520763
12.258810317392053
12.258802175032102
12.258794034440541
12.25878589561697
12.258777758561004
12.258769623272276
12.258761489750384
12.258753357994944
12.258745228005582
12.258737099781913
12.258728973323551
12.258720848630093
12.258712725701194
12.258704604536433
12.25869648513545
12.25868836749786
12.258680251623263
12.258672137511294
12.25866402516155
12.258655914573678
12.258647805747255
12.258639698681941
12.258631593377315
12.25862348983303
12.258615388048668
12.25860728802386
12.258599189758234
12.258591093251395
12.258582998502968
12.25857490551256
12.258566814279806
12.258558724804312
12.258550637085692
12.258542551123575
12.258534466917578
12.258526384467306
12.258518303772378
12.258510224832438
12.25850214764709
12.25849407221594
12.258485998538612
12.258477926614727
12.258469856443917
12.258461788025775
12.258453721359947
12.258445656446026
12.258437593283652
12.258429531872444
12.258421472212016
12.258413414301964
12.25840535814194
12.25839730373155
12.25838925107042
12.258381200158164
12.258373150994391
12.258365103578743
12.258357057910818
12.258349013990266
12.25834097181667
12.258332931389678
12.258324892708895
12.258316855773966
12.25830882058447
12.258300787140056
12.258292755440337
12.25828472548494
12.258276697273475
12.25826867080558
12.258260646080862
12.25825262309893
12.258244601859431
12.258236582361963
12.258228564606174
12.258220548591659
12.258212534318055
12.258204521784979
12.258196510992056
12.258188501938893
12.258180494625131
12.258172489050386
12.258164485214266
12.25815648311642
12.258148482756445
12.258140484133971
12.258132487248627
12.258124492100029
12.258116498687796
12.258108507011558
12.25810051707093
12.258092528865559
12.258084542395018
12.258076557658981
12.258068574657043
12.258060593388832
12.258052613853966
12.25804463605209
12.2580366599828
12.258028685645733
12.258020713040517
12.25801274216676
12.258004773024098
12.257996805612148
12.257988839930537
12.257980875978898
12.257972913756827
12.257964953263981
12.257956994499967
12.257949037464405
12.257941082156922
12.257933128577156
12.257925176724717
12.257917226599243
12.257909278200344
12.257901331527641
12.257893386580763
12.257885443359353
12.257877501863009
12.257869562091388
12.257861624044073
12.257853687720731
12.257845753120959
12.257837820244387
12.257829889090658
12.257821959659372
12.257814031950167
12.257806105962667
12.257798181696502
12.257790259151301
12.25778233832668
12.257774419222264
12.257766501837677
12.257758586172569
12.257750672226525
12.25774275999921
12.257734849490236
12.257726940699218
12.257719033625797
12.257711128269595
12.25770322463024
12.257695322707363
12.25768742250058
12.257679524009525
12.257671627233822
12.25766373217309
12.257655838826976
12.257647947195094
12.257640057277076
12.257632169072547
12.257624282581132
12.257616397802469
12.25760851473616
12.257600633381866
12.257592753739196
12.25758487580778
12.257576999587242
12.257569125077222
12.25756125227734
12.25755338118722
12.257545511806502
12.257537644134796
12.257529778171758
12.257521913916996
12.257514051370137
12.257506190530828
12.257498331398669
12.257490473973323
12.25748261825439
12.25747476424151
12.257466911934324
12.257459061332439
12.257451212435496
12.257443365243125
12.257435519754962
12.257427675970614
12.25741983388973
12.257411993511935
12.25740415483686
12.257396317864131
12.257388482593377
12.257380649024237
12.257372817156329
12.257364986989293
12.257357158522753
12.25734933175634
12.25734150668968
12.257333683322415
12.257325861654184
12.257318041684584
12.257310223413272
12.257302406839873
12.257294591964007
12.257286778785323
12.257278967303433
12.257271157517994
12.257263349428609
12.25725554303493
12.257247738336577
12.257239935333187
12.257232134024381
12.257224334409814
12.257216536489091
12.257208740261852
12.257200945727734
12.257193152886373
12.257185361737392
12.257177572280426
12.257169784515106
12.257161998441058
12.257154214057941
12.257146431365358
12.257138650362945
12.257130871050341
12.257123093427188
12.257115317493097
12.257107543247718
12.257099770690681
12.257091999821613
12.25708423064015
12.257076463145934
12.257068697338587
12.257060933217737
12.257053170783033
12.257045410034092
12.257037650970572
12.257029893592078
12.257022137898264
12.257014383888754
12.257006631563181
12.256998880921183
12.256991131962396
12.256983384686455
12.25697563909298
12.256967895181619
12.256960152951997
12.256952412403763
12.256944673536543
12.256936936349973
12.256929200843672
12.256921467017303
12.256913734870476
12.256906004402847
12.256898275614029
12.256890548503678
12.256882823071408
12.256875099316868
12.256867377239697
12.256859656839522
12.256851938115963
12.2568442210687
12.256836505697324
12.256828792001489
12.256821079980833
12.25681336963499
12.25680566096359
12.256797953966275
12.25679024864268
12.256782544992436
12.256774843015195
12.25676714271057
12.256759444078213
12.256751747117754
12.256744051828832
12.256736358211093
12.25672866626416
12.256720975987669
12.25671328738127
12.256705600444583
12.256697915177256
12.256690231578927
12.256682549649232
12.256674869387803
12.256667190794282
12.2566595138683
12.256651838609507
12.256644165017534
12.256636493092005
12.256628822832578
12.256621154238891
12.256613487310563
12.256605822047248
12.256598158448574
12.256590496514198
12.256582836243728
12.25657517763683
12.256567520693128
12.256559865412257
12.256552211793862
12.256544559837591
12.256536909543069
12.256529260909938
12.25652161393783
12.256513968626402
12.256506324975284
12.256498682984104
12.256491042652511
12.256483403980154
12.256475766966643
12.256468131611664
12.256460497914803
12.25645286587574
12.256445235494096
12.256437606769518
12.25642997970164
12.25642235429011
12.256414730534548
12.256407108434612
12.256399487989949
12.25639186920018
12.25638425206495
12.256376636583918
12.256369022756688
12.256361410582935
12.256353800062282
12.256346191194384
12.256338583978865
12.256330978415363
12.256323374503543
12.256315772243019
12.256308171633451
12.256300572674474
12.25629297536572
12.256285379706846
12.25627778569749
12.256270193337286
12.256262602625874
12.256255013562894
12.256247426148006
12.256239840380836
12.25623225626104
12.256224673788235
12.256217092962087
12.256209513782226
12.256201936248283
12.256194360359927

12.256186786116778
12.256179213518497
12.256171642564714
12.256164073255079
12.256156505589225
12.256148939566799
12.25614137518744
12.256133812450802
12.25612625135652
12.25611869190423
12.25611113409359
12.25610357792423
12.256096023395806
12.256088470507946
12.256080919260318
12.256073369652533
12.256065821684254
12.256058275355125
12.256050730664784
12.25604318761288
12.256035646199047
12.256028106422942
12.256020568284196
12.256013031782462
12.256005496917382
12.255997963688595
12.255990432095762
12.255982902138502
12.25597537381648
12.255967847129336
12.25596032207671
12.255952798658242
12.255945276873582
12.255937756722386
12.255930238204282
12.255922721318926
12.255915206065959
12.25590769244503
12.25590018045577
12.255892670097841
12.255885161370879
12.255877654274544
12.255870148808455
12.255862644972277
12.255855142765657
12.255847642188229
12.255840143239645
12.25583264591955
12.255825150227595
12.255817656163424
12.25581016372667
12.255802672917
12.25579518373405
12.255787696177466
12.255780210246892
12.255772725941982
12.255765243262374
12.255757762207724
12.255750282777669
12.255742804971863
12.255735328789951
12.255727854231576
12.255720381296392
12.255712909984037
12.25570544029418
12.255697972226441
12.255690505780473
12.25568304095594
12.255675577752474
12.255668116169725
12.255660656207343
12.255653197864984
12.255645741142283
12.255638286038891
12.255630832554457
12.255623380688629
12.255615930441058
12.255608481811388
12.255601034799271
12.255593589404354
12.255586145626278
12.255578703464716
12.25557126291928
12.25556382398964
12.25555638667545
12.255548950976362
12.255541516891984
12.255534084422017
12.25552665356608
12.25551922432383
12.255511796694929
12.255504370679011
12.255496946275718
12.255489523484712
12.255482102305642
12.255474682738154
12.255467264781899
12.255459848436532
12.255452433701697
12.25544502057705
12.255437609062229
12.255430199156898
12.255422790860692
12.255415384173274
12.255407979094283
12.255400575623376
12.2553931737602
12.25538577350442
12.255378374855685
12.255370977813618
12.255363582377896
12.255356188548163
12.255348796324062
12.255341405705247
12.25533401669138
12.255326629282106
12.255319243477071
12.25531185927594
12.255304476678338
12.255297095683945
12.255289716292397
12.255282338503351
12.255274962316452
12.255267587731357
12.25526021474772
12.255252843365191
12.255245473583427
12.25523810540206
12.255230738820766
12.255223373839181
12.255216010456964
12.255208648673777
12.255201288489248
12.25519392990305
12.255186572914837
12.25517921752425
12.255171863730943
12.255164511534575
12.255157160934793
12.255149811931252
12.255142464523608
12.255135118711506
12.25512777449461
12.255120431872573
12.255113090845027
12.255105751411653
12.255098413572094
12.255091077325998
12.25508374267303
12.255076409612833
12.255069078145059
12.255061748269378
12.25505441998542
12.255047093292866
12.255039768191347
12.25503244468053
12.25502512276007
12.255017802429604
12.255010483688816
12.255003166537337
12.254995850974826
12.254988537000942
12.25498122461535
12.254973913817677
12.254966604607606
12.254959296984767
12.254951990948836
12.254944686499448
12.254937383636282
12.254930082358964
12.254922782667187
12.254915484560575
12.254908188038797
12.254900893101507
12.254893599748351
12.254886307979001
12.254879017793098
12.254871729190311
12.25486444217028
12.254857156732674
12.254849872877145
12.254842590603351
12.254835309910943
12.254828030799581
12.254820753268916
12.25481347731862
12.254806202948329
12.254798930157717
12.254791658946429
12.254784389314128
12.254777121260464
12.254769854785104
12.2547625898877
12.254755326567912
12.254748064825378
12.25474080465977
12.254733546070758
12.254726289057983
12.25471903362111
12.254711779759782
12.254704527473674
12.25469727676243
12.254690027625724
12.254682780063206
12.254675534074524
12.25466828965935
12.25466104681733
12.254653805548125
12.254646565851411
12.254639327726817
12.254632091174022
12.254624856192674
12.254617622782446
12.254610390942979
12.254603160673934
12.254595931974983
12.254588704845766
12.25458147928596
12.254574255295209
12.25456703287318
12.254559812019535
12.254552592733923
12.254545375016015
12.254538158865454
12.254530944281912
12.25452373126505
12.254516519814526
12.254509309929986
12.254502101611111
12.254494894857533
12.254487689668954
12.25448048604499
12.254473283985329
12.254466083489614
12.254458884557513
12.254451687188691
12.2544444913828
12.2544372971395
12.254430104458464
12.254422913339331
12.254415723781785
12.254408535785464
12.254401349350047
12.254394164475183
12.254386981160543
12.254379799405768
12.254372619210546
12.254365440574517
12.254358263497357
12.254351087978717
12.254343914018266
12.254336741615655
12.254329570770548
12.254322401482616
12.254315233751512
12.254308067576895
12.25430090295844
12.254293739895793
12.254286578388626
12.254279418436607
12.254272260039366
12.254265103196614
12.25425794790797
12.25425079417312
12.254243641991712
12.254236491363429
12.254229342287909
12.254222194764825
12.254215048793847
12.254207904374631
12.254200761506837
12.254193620190135
12.254186480424172
12.254179342208626
12.254172205543163
12.254165070427439
12.254157936861112
12.254150804843855
12.254143674375323
12.254136545455182
12.2541294180831
12.254122292258737
12.254115167981762
12.254108045251824
12.254100924068604
12.254093804431756
12.254086686340942
12.254079569795834
12.254072454796093
12.254065341341386
12.25405822943136
12.254051119065705
12.254044010244069
12.254036902966114
12.25402979723152
12.254022693039936
12.254015590391035
12.25400848928448
12.254001389719935
12.253994291697063
12.253987195215538
12.253980100275015
12.253973006875164
12.253965915015646
12.25395882469612
12.253951735916283
12.25394464867575
12.253937562974224
12.253930478811359
12.253923396186828
12.253916315100287
12.253909235551406
12.253902157539855
12.253895081065286
12.253888006127374
12.253880932725785
12.253873860860189
12.25386679053024
12.253859721735614
12.253852654475981
12.253845588751
12.25383852456034
12.253831461903662
12.25382440078064
12.253817341190935
12.253810283134216
12.253803226610165
12.253796171618417
12.253789118158661
12.253782066230563
12.25377501583377
12.253767966967986
12.253760919632853
12.253753873828042
12.253746829553222
12.253739786808058
12.253732745592217
12.253725705905376
12.253718667747183
12.253711631117335
12.253704596015474
12.253697562441277
12.25369053039441
12.253683499874555
12.253676470881356
12.253669443414491
12.253662417473636
12.253655393058457
12.253648370168627
12.253641348803791
12.253634328963642
12.253627310647847
12.253620293856054
12.253613278587947
12.253606264843201
12.253599252621465
12.253592241922435
12.253585232745762
12.253578225091116
12.253571218958164
12.253564214346584
12.253557211256043
12.253550209686214
12.253543209636746
12.253536211107336
12.253529214097636
12.253522218607324
12.253515224636057
12.25350823218353
12.253501241249381
12.253494251833311
12.253487263934966
12.253480277554031
12.25347329269017
12.253466309343054
12.253459327512358
12.253452347197728
12.25344536839888
12.253438391115449
12.253431415347109
12.25342444109355
12.253417468354424
12.2534104971294
12.253403527418158
12.253396559220382
12.25338959253572
12.25338262736386
12.25337566370445
12.253368701557186
12.253361740921731
12.25335478179775
12.253347824184921
12.25334086808292
12.253333913491414
12.253326960410064
12.253320008838555
12.253313058776559
12.253306110223736
12.253299163179772
12.25329221764433
12.253285273617085
12.253278331097722
12.253271390085883
12.253264450581275
12.25325751258354
12.253250576092372
12.253243641107435
12.253236707628398
12.253229775654942
12.253222845186738
12.253215916223452
12.253208988764758
12.25320206281034
12.253195138359864
12.253188215413
12.253181293969426
12.253174374028806
12.253167455590827
12.253160538655155
12.25315362322147
12.253146709289434
12.253139796858724
12.253132885929023
12.253125976499991
12.253119068571317
12.25311216214267
12.253105257213708
12.253098353784123
12.253091451853582
12.253084551421775
12.253077652488349
12.253070755053
12.253063859115384
12.253056964675201
12.253050071732096
12.253043180285767
12.253036290335874
12.253029401882099
12.253022514924115
12.253015629461597
12.253008745494226
12.253001863021666
12.252994982043589
12.2529881025597
12.252981224569638
12.25297434807309
12.252967473069749
12.252960599559263
12.252953727541327
12.252946857015607
12.252939987981783
12.252933120439534
12.252926254388527
12.252919389828445
12.252912526758964
12.252905665179744
12.252898805090489
12.252891946490855
12.252885089380527
12.25287823375917
12.252871379626486
12.252864526982112
12.252857675825764
12.252850826157097
12.252843977975791
12.252837131281527
12.25283028607397
12.252823442352808
12.25281660011772
12.252809759368379
12.252802920104449
12.252796082325636
12.252789246031591
12.252782411222011
12.252775577896548
12.252768746054914
12.252761915696743
12.25275508682177
12.252748259429618
12.25274143351999
12.252734609092569
12.25272778614701
12.252720964683014
12.252714144700244
12.25270732619839
12.252700509177124
12.252693693636129
12.25268687957507
12.252680066993637
12.25267325589151
12.252666446268357
12.252659638123868
12.25265283145771
12.252646026269574
12.252639222559132
12.252632420326066
12.252625619570049
12.252618820290767
12.252612022487895
12.25260522616111
12.2525984313101
12.252591637934534
12.252584846034095
12.25257805560847
12.252571266657323
12.252564479180348
12.252557693177216
12.252550908647606
12.252544125591214
12.252537344007699
12.25253056389675
12.252523785258045
12.252517008091264
12.252510232396084
12.252503458172201
12.252496685419272
12.252489914136998
12.252483144325039
12.252476375983102
12.252469609110847
12.252462843707955
12.252456079774113
12.252449317309006
12.252442556312303
12.252435796783699
12.252429038722852
12.252422282129475
12.25241552700322
12.25240877334379
12.252402021150845
12.252395270424081
12.252388521163187
12.252381773367818
12.252375027037683
12.252368282172448
12.252361538771792
12.252354796835407
12.252348056362978
12.252341317354167
12.252334579808679
12.252327843726173
12.252321109106358
12.252314375948892
12.252307644253474
12.252300914019779
12.252294185247486
12.252287457936278
12.252280732085838
12.252274007695863
12.25226728476601
12.25226056329599
12.252253843285457
12.252247124734115
12.252240407641642
12.252233692007712
12.252226977832022
12.252220265114241
12.252213553854057
12.252206844051157
12.252200135705229
12.252193428815945
12.252186723382989
12.252180019406065
12.252173316884818
12.252166615818963
12.252159916208186
12.252153218052143
12.252146521350543
12.252139826103056
12.252133132309371

12.252126439969189
12.252119749082157
12.252113059647984
12.252106371666356
12.252099685136947
12.252093000059444
12.252086316433536
12.252079634258902
12.25207295353523
12.25206627426221
12.252059596439516
12.252052920066832
12.252046245143848
12.252039571670256
12.25203289964574
12.25202622906997
12.252019559942639
12.252012892263439
12.252006226032046
12.251999561248159
12.251992897911444
12.251986236021603
12.251979575578302
12.25197291658126
12.251966259030127
12.25195960292461
12.251952948264384
12.25194629504915
12.251939643278572
12.251932992952355
12.251926344070174
12.251919696631722
12.251913050636672
12.25190640608474
12.251899762975576
12.25189312130889
12.251886481084368
12.251879842301685
12.251873204960534
12.251866569060605
12.25185993460158
12.251853301583136
12.251846670004973
12.251840039866789
12.251833411168242
12.251826783909053
12.251820158088877
12.251813533707427
12.251806910764364
12.251800289259398
12.251793669192212
12.251787050562482
12.251780433369904
12.251773817614179
12.251767203294971
12.251760590411976
12.251753978964894
12.251747368953382
12.251740760377176
12.251734153235914
12.25172754752932
12.25172094325707
12.25171434041885
12.251707739014352
12.251701139043254
12.251694540505257
12.251687943400048
12.25168134772731
12.251674753486737
12.251668160678019
12.251661569300836
12.251654979354889
12.251648390839861
12.251641803755431
12.2516352181013
12.25162863387716
12.251622051082695
12.251615469717594
12.251608889781542
12.251602311274237
12.251595734195366
12.25158915854462
12.251582584321676
12.251576011526238
12.251569440157988
12.25156287021663
12.25155630170183
12.251549734613299
12.251543168950725
12.251536604713783
12.251530041902175
12.251523480515585
12.251516920553717
12.251510362016242
12.251503804902873
12.251497249213275
12.251490694947144
12.251484142104204
12.251477590684098
12.251471040686555
12.251464492111225
12.25145794495784
12.251451399226074
12.251444854915619
12.251438312026156
12.251431770557405
12.251425230509017
12.25141869188072
12.251412154672177
12.251405618883092
12.251399084513164
12.251392551562077
12.251386020029518
12.251379489915193
12.251372961218772
12.251366433939973
12.251359908078461
12.25135338363395
12.251346860606123
12.25134033899466
12.251333818799285
12.25132730001966
12.251320782655496
12.251314266706464
12.251307752172282
12.251301239052628
12.251294727347199
12.251288217055679
12.251281708177775
12.251275200713168
12.251268694661563
12.251262190022638
12.251255686796089
12.251249184981624
12.251242684578928
12.251236185587683
12.251229688007596
12.251223191838356
12.251216697079652
12.251210203731196
12.251203711792655
12.251197221263727
12.251190732144117
12.25118424443352
12.251177758131627
12.251171273238127
12.251164789752709
12.25115830767509
12.251151827004945
12.251145347741966
12.251138869885853
12.2511323934363
12.25112591839301
12.251119444755664
12.251112972523957
12.251106501697599
12.251100032276272
12.251093564259664
12.251087097647481
12.251080632439418
12.251074168635165
12.251067706234421
12.251061245236876
12.251054785642234
12.251048327450187
12.251041870660416
12.251035415272632
12.251028961286531
12.251022508701798
12.251016057518143
12.25100960773524
12.251003159352798
12.250996712370513
12.250990266788088
12.250983822605207
12.25097737982157
12.250970938436865
12.2509644984508
12.250958059863068
12.25095162267336
12.250945186881378
12.250938752486814
12.250932319489367
12.250925887888739
12.250919457684617
12.25091302887669
12.250906601464678
12.25090017544827
12.250893750827142
12.250887327601006
12.250880905769566
12.250874485332513
12.250868066289543
12.250861648640353
12.250855232384641
12.250848817522098
12.250842404052435
12.250835991975341
12.250829581290514
12.250823171997647
12.250816764096445
12.250810357586596
12.250803952467809
12.250797548739772
12.250791146402197
12.25078474545476
12.25077834589718
12.250771947729154
12.250765550950355
12.25075915556051
12.250752761559294
12.250746368946423
12.250739977721596
12.250733587884504
12.250727199434836
12.250720812372313
12.250714426696602
12.250708042407437
12.250701659504491
12.250695277987484
12.250688897856094
12.250682519110034
12.250676141748992
12.25066976577268
12.250663391180776
12.25065701797301
12.25065064614906
12.250644275708618
12.250637906651418
12.250631538977123
12.250625172685446
12.250618807776092
12.250612444248743
12.250606082103124
12.250599721338917
12.250593361955826
12.250587003953552
12.250580647331793
12.250574292090251
12.25056793822863
12.250561585746624
12.250555234643931
12.250548884920258
12.250542536575297
12.25053618960876
12.250529844020344
12.250523499809738
12.250517156976663
12.250510815520801
12.250504475441867
12.250498136739546
12.250491799413558
12.25048546346358
12.250479128889332
12.250472795690513
12.250466463866818
12.250460133417947
12.25045380434362
12.250447476643513
12.250441150317334
12.250434825364795
12.250428501785589
12.250422179579415
12.250415858745988
12.250409539285
12.250403221196155
12.250396904479143
12.25039058913369
12.250384275159472
12.250377962556211
12.250371651323599
12.250365341461338
12.250359032969142
12.250352725846701
12.25034642009372
12.250340115709896
12.25033381269494
12.250327511048557
12.250321210770437
12.250314911860286
12.25030861431784
12.250302318142754
12.250296023334743
12.250289729893524
12.250283437818792
12.250277147110253
12.250270857767607
12.250264569790563
12.250258283178807
12.250251997932072
12.250245714050033
12.250239431532403
12.250233150378888
12.250226870589197
12.250220592163021
12.250214315100079
12.250208039400057
12.250201765062675
12.25019549208763
12.250189220474619
12.250182950223358
12.250176681333542
12.250170413804879
12.25016414763708
12.250157882829841
12.250151619382866
12.250145357295862
12.250139096568528
12.250132837200582
12.25012657919171
12.25012032254164
12.250114067250063
12.250107813316673
12.250101560741193
12.250095309523317
12.250089059662757
12.250082811159215
12.250076564012396
12.250070318222011
12.25006407378775
12.250057830709338
12.250051588986462
12.25004534861885
12.250039109606181
12.250032871948177
12.250026635644534
12.250020400694975
12.250014167099186
12.250007934856887
12.250001703967774
12.249995474431556
12.24998924624795
12.249983019416641
12.249976793937353
12.249970569809786
12.249964347033641
12.249958125608632
12.24995190553447
12.249945686810843
12.249939469437468
12.24993325341406
12.249927038740307
12.249920825415938
12.24991461344065
12.249908402814144
12.24990219353613
12.24989598560632
12.249889779024416
12.249883573790118
12.249877369903153
12.249871167363214
12.249864966170012
12.249858766323246
12.249852567822646
12.2498463706679
12.249840174858717
12.249833980394808
12.249827787275875
12.249821595501638
12.249815405071802
12.249809215986065
12.249803028244141
12.249796841845743
12.249790656790571
12.249784473078332
12.249778290708736
12.249772109681503
12.249765929996332
12.249759751652933
12.249753574651004
12.249747398990268
12.249741224670423
12.249735051691188
12.249728880052267
12.249722709753366
12.249716540794195
12.249710373174471
12.249704206893883
12.249698041952167
12.249691878349005
12.249685716084125
12.249679555157238
12.24967339556804
12.249667237316231
12.24966108040155
12.249654924823691
12.249648770582365
12.249642617677276
12.249636466108143
12.249630315874677
12.249624166976574
12.249618019413548
12.249611873185325
12.2496057282916
12.24959958473209
12.249593442506487
12.249587301614527
12.249581162055902
12.249575023830332
12.249568886937517
12.249562751377182
12.249556617149029
12.24955048425277
12.249544352688117
12.249538222454778
12.249532093552459
12.249525965980878
12.249519839739751
12.249513714828783
12.249507591247667
12.249501468996144
12.249495348073921
12.24948922848069
12.249483110216174
12.249476993280073
12.24947087767213
12.249464763392023
12.249458650439472
12.249452538814197
12.249446428515904
12.2494403195443
12.24943421189911
12.249428105580034
12.249422000586792
12.249415896919082
12.249409794576632
12.249403693559149
12.249397593866341
12.249391495497928
12.249385398453608
12.249379302733102
12.249373208336138
12.249367115262405
12.249361023511613
12.2493549330835
12.249348843977753
12.249342756194107
12.249336669732257
12.249330584591926
12.249324500772818
12.24931841827465
12.249312337097132
12.249306257239994
12.24930017870293
12.249294101485651
12.249288025587889
12.249281951009351
12.249275877749735
12.249269805808776
12.249263735186172
12.249257665881649
12.249251597894894
12.24924553122565
12.249239465873623
12.249233401838525
12.249227339120074
12.249221277717972
12.249215217631944
12.2492091588617
12.249203101406946
12.249197045267413
12.249190990442806
12.24918493693284
12.249178884737233
12.249172833855692
12.249166784287938
12.249160736033678
12.249154689092633
12.249148643464519
12.24914259914905
12.249136556145938
12.249130514454901
12.249124474075646
12.249118435007903
12.249112397251366
12.249106360805763
12.249100325670812
12.249094291846228
12.249088259331717
12.249082228127007
12.249076198231796
12.24907016964582
12.249064142368773
12.249058116400391
12.249052091740374
12.249046068388457
12.249040046344325
12.249034025607724
12.249028006178355
12.249021988055938
12.249015971240189
12.24900995573082
12.24900394152756
12.248997928630105
12.24899191703818
12.248985906751505
12.248979897769798
12.248973890092769
12.24896788372014
12.248961878651635
12.248955874886951
12.248949872425811
12.248943871267938
12.248937871413048
12.248931872860854
12.248925875611077
12.248919879663433
12.24891388501763
12.248907891673397
12.248901899630457
12.248895908888509
12.248889919447283
12.248883931306493
12.248877944465848
12.248871958925081

12.248865974683897
12.248859991742014
12.248854010099171
12.248848029755061
12.248842050709415
12.248836072961932
12.24883009651235
12.248824121360382
12.248818147505753
12.248812174948162
12.24880620368734
12.248800233723012
12.248794265054874
12.248788297682662
12.248782331606098
12.248776366824892
12.248770403338755
12.248764441147419
12.248758480250602
12.248752520648024
12.248746562339386
12.248740605324421
12.248734649602852
12.248728695174396
12.248722742038762
12.248716790195674
12.248710839644856
12.248704890386016
12.248698942418892
12.248692995743191
12.248687050358631
12.248681106264934
12.248675163461824
12.248669221949015
12.248663281726223
12.248657342793178
12.248651405149598
12.248645468795196
12.2486395337297
12.248633599952813
12.248627667464278
12.2486217362638
12.248615806351106
12.24860987772591
12.248603950387956
12.24859802433692
12.248592099572555
12.248586176094577
12.248580253902706
12.248574332996649
12.248568413376148
12.248562495040911
12.248556577990653
12.248550662225108
12.248544747743992
12.248538834547027
12.248532922633931
12.248527012004423
12.248521102658234
12.248515194595068
12.248509287814667
12.248503382316738
12.248497478101006
12.24849157516719
12.248485673515027
12.248479773144222
12.24847387405449
12.248467976245573
12.248462079717182
12.248456184469037
12.248450290500864
12.248444397812394
12.24843850640333
12.248432616273394
12.24842672742233
12.24842083984984
12.248414953555654
12.24840906853949
12.248403184801084
12.248397302340141
12.248391421156395
12.248385541249567
12.24837966261937
12.248373785265535
12.248367909187776
12.248362034385833
12.248356160859412
12.248350288608254
12.248344417632056
12.248338547930569
12.248332679503493
12.248326812350562
12.248320946471495
12.248315081866027
12.248309218533873
12.248303356474743
12.24829749568838
12.248291636174514
12.24828577793283
12.2482799209631
12.248274065265013
12.248268210838305
12.248262357682703
12.24825650579792
12.248250655183691
12.24824480583973
12.248238957765777
12.24823311096153
12.24822726542675
12.248221421161126
12.24821557816441
12.248209736436296
12.248203895976538
12.248198056784839
12.24819221886094
12.248186382204546
12.248180546815401
12.24817471269322
12.248168879837731
12.248163048248658
12.248157217925721
12.248151388868656
12.248145561077182
12.248139734551023
12.248133909289901
12.248128085293551
12.248122262561688
12.248116441094027
12.248110620890326
12.248104801950285
12.248098984273632
12.248093167860102
12.24808735270942
12.248081538821294
12.248075726195479
12.248069914831682
12.248064104729625
12.248058295889038
12.248052488309654
12.248046681991184
12.248040876933379
12.248035073135947
12.248029270598616
12.248023469321108
12.248017669303168
12.248011870544499
12.248006073044843
12.248000276803914
12.247994481821452
12.247988688097173
12.24798289563081
12.247977104422091
12.247971314470742
12.247965525776477
12.247959738339052
12.247953952158154
12.247948167233545
12.247942383564935
12.247936601152043
12.247930819994634
12.24792504009238
12.247919261445047
12.247913484052365
12.247907707914036
12.247901933029809
12.247896159399398
12.247890387022537
12.247884615898952
12.247878846028367
12.247873077410523
12.247867310045123
12.24786154393193
12.247855779070646
12.247850015460997
12.247844253102729
12.247838491995559
12.247832732139207
12.247826973533426
12.247821216177933
12.247815460072434
12.247809705216687
12.247803951610408
12.247798199253335
12.247792448145175
12.24778669828568
12.247780949674565
12.247775202311566
12.247769456196409
12.247763711328824
12.247757967708536
12.247752225335287
12.24774648420879
12.247740744328771
12.24773500569498
12.24772926830713
12.247723532164962
12.247717797268185
12.247712063616554
12.24770633120978
12.247700600047597
12.247694870129749
12.247689141455929
12.247683414025905
12.247677687839397
12.247671962896135
12.24766623919583
12.24766051673824
12.247654795523074
12.247649075550065
12.247643356818955
12.247637639329465
12.247631923081332
12.247626208074271
12.247620494308032
12.24761478178233
12.247609070496896
12.247603360451485
12.247597651645803
12.247591944079574
12.247586237752554
12.247580532664452
12.247574828815011
12.247569126203963
12.247563424831032
12.247557724695953
12.247552025798454
12.247546328138274
12.247540631715133
12.247534936528773
12.247529242578906
12.247523549865289
12.247517858387637
12.247512168145683
12.247506479139176
12.24750079136782
12.247495104831366
12.247489419529536
12.247483735462064
12.247478052628693
12.247472371029138
12.247466690663135
12.247461011530433
12.24745533363073
12.247449656963791
12.247443981529337
12.247438307327096
12.247432634356805
12.247426962618189
12.247421292110987
12.247415622834936
12.247409954789758
12.247404287975188
12.24739862239097
12.24739295803683
12.24738729491248
12.247381633017689
12.247375972352167
12.247370312915649
12.247364654707875
12.247358997728579
12.247353341977485
12.247347687454331
12.247342034158848
12.247336382090774
12.24733073124983
12.24732508163578
12.247319433248325
12.247313786087206
12.247308140152168
12.24730249544293
12.247296851959236
12.247291209700816
12.247285568667408
12.24727992885874
12.247274290274552
12.247268652914567
12.247263016778534
12.24725738186618
12.24725174817723
12.247246115711434
12.24724048446851
12.247234854448218
12.247229225650258
12.2472235980744
12.247217971720348
12.247212346587856
12.247206722676644
12.247201099986462
12.247195478517039
12.247189858268108
12.247184239239392
12.247178621430658
12.247173004841613
12.247167389471993
12.247161775321544
12.247156162390002
12.247150550677096
12.24714494018256
12.247139330906132
12.247133722847545
12.247128116006543
12.247122510382859
12.247116905976213
12.247111302786363
12.247105700813028
12.247100100055953
12.247094500514875
12.247088902189523
12.24708330507963
12.247077709184936
12.247072114505185
12.247066521040104
12.247060928789441
12.247055337752906
12.247049747930264
12.247044159321234
12.247038571925573
12.247032985742976
12.24702740077322
12.247021817016027
12.247016234471129
12.24701065313827
12.247005073017197
12.246999494107614
12.246993916409286
12.246988339921945
12.246982764645317
12.246977190579159
12.246971617723178
12.246966046077139
12.246960475640767
12.246954906413805
12.246949338395986
12.24694377158704
12.246938205986712
12.246932641594753
12.246927078410877
12.246921516434826
12.246915955666358
12.246910396105186
12.246904837751051
12.246899280603712
12.246893724662883
12.246888169928313
12.246882616399738
12.246877064076894
12.246871512959531
12.246865963047366
12.246860414340155
12.246854866837623
12.246849320539521
12.24684377544557
12.24683823155553
12.246832688869139
12.246827147386105
12.246821607106195
12.24681606802914
12.246810530154685
12.246804993482552
12.246799458012498
12.246793923744255
12.24678839067755
12.246782858812146
12.24677732814776
12.246771798684145
12.246766270421036
12.246760743358161
12.246755217495286
12.246749692832125
12.246744169368428
12.24673864710393
12.246733126038379
12.2467276061715
12.24672208750305
12.246716570032758
12.246711053760365
12.246705538685612
12.246700024808247
12.246694512127988
12.24668900064459
12.246683490357793
12.246677981267336
12.246672473372964
12.246666966674406
12.246661461171412
12.246655956863716
12.246650453751053
12.24664495183318
12.246639451109825
12.246633951580733
12.246628453245638
12.246622956104298
12.24661746015643
12.246611965401792
12.24660647184012
12.246600979471154
12.246595488294634
12.2465899983103
12.246584509517902
12.24657902191717
12.246573535507848
12.246568050289673
12.246562566262401
12.246557083425762
12.246551601779496
12.246546121323359
12.246540642057058
12.24653516398038
12.246529687093037
12.24652421139478
12.246518736885339
12.24651326356447
12.246507791431918
12.246502320487414
12.246496850730695
12.246491382161517
12.246485914779614
12.246480448584736
12.246474983576611
12.246469519754996
12.246464057119622
12.246458595670237
12.24645313540658
12.2464476763284
12.246442218435439
12.246436761727425
12.246431306204123
12.246425851865254
12.24642039871057
12.246414946739828
12.246409495952738
12.246404046349081
12.246398597928575
12.246393150690965
12.246387704636005
12.246382259763422
12.24637681607298
12.246371373564399
12.246365932237442
12.246360492091837
12.246355053127337
12.246349615343686
12.246344178740623
12.246338743317892
12.246333309075235
12.246327876012403
12.246322444129131
12.246317013425172
12.246311583900267
12.246306155554146
12.24630072838657
12.246295302397279
12.246289877586012
12.246284453952521
12.246279031496542
12.246273610217832
12.246268190116117
12.246262771191146
12.246257353442678
12.246251936870442

12.246246521474193
12.246241107253667
12.246235694208607
12.24623028233877
12.246224871643888
12.246219462123713
12.24621405377799
12.24620864660646
12.24620324060887
12.24619783578496
12.246192432134483
12.24618702965718
12.246181628352812
12.246176228221092
12.246170829261782
12.246165431474633
12.246160034859379
12.246154639415778
12.246149245143572
12.2461438520425
12.246138460112313
12.246133069352753
12.246127679763555
12.246122291344502
12.2461169040953
12.246111518015713
12.24610613310548
12.246100749364349
12.246095366792073
12.246089985388398
12.246084605153069
12.246079226085811
12.246073848186402
12.246068471454564
12.246063095890054
12.246057721492628
12.246052348262014
12.246046976197977
12.246041605300244
12.246036235568576
12.246030867002702
12.24602549960239
12.246020133367384
12.246014768297421
12.246009404392252
12.246004041651622
12.245998680075289
12.24599331966298
12.245987960414455
12.245982602329471
12.24597724540775
12.245971889649066
12.245966535053146
12.245961181619741
12.245955829348613
12.245950478239488
12.245945128292133
12.245939779506289
12.24593443188169
12.245929085418103
12.245923740115263
12.24591839597293
12.24591305299084
12.245907711168755
12.245902370506403
12.24589703100354
12.245891692659937
12.245886355475305
12.245881019449428
12.24587568458202
12.24587035087285
12.245865018321659
12.245859686928206
12.245854356692224
12.245849027613469
12.245843699691697
12.245838372926642
12.245833047318067
12.245827722865714
12.245822399569334
12.245817077428661
12.245811756443468
12.245806436613496
12.24580111793848
12.245795800418193
12.245790484052362
12.245785168840749
12.245779854783096
12.245774541879163
12.24576923012869
12.245763919531429
12.245758610087124
12.24575330179553
12.245747994656409
12.245742688669484
12.245737383834525
12.24573208015128
12.245726777619492
12.245721476238913
12.245716176009283
12.245710876930382
12.24570557900192
12.245700282223686
12.245694986595401
12.24568969211683
12.245684398787715
12.24567910660782
12.245673815576877
12.245668525694644
12.245663236960885
12.24565794937533
12.245652662937728
12.245647377647849
12.245642093505436
12.245636810510241
12.245631528662008
12.245626247960491
12.245620968405442
12.245615689996606
12.245610412733742
12.245605136616605
12.245599861644937
12.24559458781849
12.24558931513702
12.245584043600276
12.245578773208008
12.245573503959967
12.24556823585591
12.245562968895577
12.245557703078724
12.245552438405117
12.245547174874481
12.24554191248659
12.245536651241194
12.245531391138034
12.245526132176874
12.245520874357453
12.245515617679532
12.245510362142847
12.245505107747178
12.245499854492266
12.245494602377851
12.245489351403695
12.24548410156955
12.245478852875163
12.245473605320296
12.245468358904697
12.245463113628118
12.245457869490311
12.245452626491026
12.245447384630028
12.245442143907052
12.245436904321858
12.245431665874209
12.245426428563848
12.245421192390516
12.245415957354
12.245410723454027
12.24540549069035
12.245400259062727
12.245395028570911
12.245389799214658
12.245384570993721
12.245379343907857
12.245374117956796
12.245368893140327
12.245363669458179
12.245358446910114
12.245353225495887
12.245348005215261
12.245342786067951
12.245337568053756
12.245332351172413
12.245327135423665
12.245321920807282
12.245316707323015
12.245311494970611
12.24530628374982
12.245301073660416
12.24529586470214
12.245290656874738
12.24528545017799
12.245280244611624
12.245275040175402
12.245269836869092
12.245264634692434
12.245259433645186
12.245254233727103
12.245249034937938
12.245243837277451
12.245238640745393
12.245233445341512
12.245228251065585
12.245223057917343
12.24521786589655
12.245212675002973
12.245207485236348
12.245202296596439
12.245197109083003
12.245191922695781
12.24518673743455
12.245181553299053
12.245176370289048
12.245171188404289
12.245166007644535
12.245160828009542
12.24515564949906
12.24515047211285
12.245145295850666
12.245140120712268
12.2451349466974
12.245129773805823
12.245124602037311
12.245119431391586
12.24511426186843
12.245109093467597
12.245103926188836
12.245098760031901
12.245093594996568
12.24508843108256
12.245083268289653
12.245078106617608
12.245072946066175
12.245067786635113
12.24506262832417
12.245057471133121
12.245052315061697
12.245047160109682
12.245042006276815
12.245036853562851
12.245031701967566
12.245026551490703
12.245021402132013
12.24501625389127
12.24501110676821
12.245005960762612
12.245000815874233
12.24499567210279
12.244990529448101
12.244985387909894
12.244980247487904
12.244975108181933
12.244969969991704
12.244964832916985
12.24495969695754
12.24495456211312
12.244949428383494
12.24494429576841
12.244939164267626
12.244934033880886
12.244928904607981
12.244923776448637
12.244918649402651
12.244913523469743
12.244908398649674
12.244903274942223
12.24489815234714
12.244893030864176
12.244887910493105
12.244882791233659
12.244877673085623
12.244872556048751
12.244867440122789
12.244862325307505
12.244857211602653
12.244852099008002
12.2448469875233
12.244841877148309
12.244836767882786
12.244831659726499
12.244826552679193
12.244821446740636
12.244816341910582
12.244811238188802
12.244806135575054
12.244801034069077
12.244795933670655
12.244790834379524
12.244785736195462
12.24478063911823
12.244775543147556
12.244770448283253
12.244765354525043
12.244760261872685
12.244755170325949
12.244750079884602
12.244744990548387
12.244739902317082
12.244734815190435
12.244729729168206
12.244724644250164
12.244719560436053
12.244714477725651
12.244709396118706
12.244704315614982
12.244699236214245
12.24469415791625
12.244689080720754
12.244684004627526
12.244678929636319
12.2446738557469
12.244668782959025
12.244663711272457
12.244658640686952
12.244653571202285
12.244648502818192
12.244643435534458
12.244638369350842
12.24463330426708
12.244628240282962
12.244623177398234
12.244618115612672
12.244613054926011
12.244607995338042
12.244602936848503
12.24459787945716
12.244592823163789
12.244587767968133
12.244582713869972
12.244577660869055
12.24457260896515
12.24456755815801
12.244562508447393
12.244557459833079
12.244552412314818
12.244547365892378
12.244542320565525
12.244537276333995
12.244532233197582
12.244527191156033
12.244522150209107
12.244517110356579
12.244512071598201
12.24450703393373
12.244501997362946
12.244496961885602
12.244491927501455
12.244486894210272
12.244481862011826
12.244476830905858
12.24447180089216
12.244466771970462
12.24446174414054
12.244456717402164
12.244451691755094
12.244446667199094
12.244441643733916
12.244436621359348
12.244431600075117
12.244426579881019
12.2444215607768
12.244416542762218
12.24441152583705
12.244406510001062
12.244401495254003
12.244396481595647
12.24439146902575
12.24438645754408
12.244381447150403
12.244376437844485
12.244371429626078
12.244366422494952
12.244361416450877
12.24435641149361
12.244351407622915
12.244346404838563
12.244341403140295
12.244336402527908
12.244331403001146
12.244326404559775
12.24432140720356
12.244316410932276
12.244311415745678
12.244306421643516
12.244301428625581
12.244296436691634
12.244291445841428
12.244286456074715
12.244281467391298
12.244276479790905
12.244271493273324
12.244266507838304
12.24426152348562
12.244256540215034
12.244251558026312
12.244246576919217
12.244241596893513
12.244236617948975
12.244231640085351
12.244226663302413
12.244221687599941
12.244216712977677
12.244211739435402
12.244206766972884
12.244201795589872
12.244196825286139
12.244191856061454
12.244186887915586
12.244181920848298
12.244176954859343
12.24417198994851
12.244167026115544
12.244162063360228
12.244157101682307
12.24415214108156
12.244147181557748
12.244142223110654
12.244137265740028
12.244132309445641
12.244127354227254
12.244122400084635
12.244117447017565
12.244112495025782
12.24410754410907
12.244102594267204
12.244097645499927
12.244092697807035
12.244087751188268
12.244082805643403
12.244077861172203
12.244072917774439
12.24406797544988
12.244063034198303
12.24405809401945
12.244053154913109
12.244048216879023
12.244043279916992
12.244038344026746
12.244033409208088
12.244028475460766
12.244023542784545
12.244018611179204
12.244013680644509
12.244008751180216
12.244003822786096
12.243998895461928
12.243993969207466
12.24398904402248
12.243984119906745
12.243979196860026
12.243974274882092
12.243969353972702
12.243964434131643
12.243959515358654

12.243954597653518
12.243949681016018
12.243944765445896
12.243939850942942
12.243934937506904
12.243930025137578
12.2439251138347
12.243920203598055
12.24391529442741
12.243910386322542
12.243905479283205
12.24390057330918
12.243895668400214
12.243890764556108
12.243885861776608
12.243880960061478
12.243876059410512
12.243871159823463
12.24386626130009
12.243861363840189
12.243856467443498
12.243851572109806
12.243846677838881
12.243841784630483
12.24383689248439
12.243832001400373
12.243827111378188
12.243822222417617
12.243817334518422
12.243812447680375
12.243807561903246
12.243802677186807
12.243797793530826
12.243792910935078
12.243788029399319
12.243783148923315
12.243778269506866
12.24377339114971
12.243768513851634
12.243763637612416
12.243758762431804
12.243753888309573
12.243749015245507
12.243744143239363
12.24373927229092
12.243734402399944
12.243729533566198
12.243724665789465
12.243719799069508
12.243714933406098
12.243710068799013
12.24370520524801
12.243700342752877
12.243695481313361
12.243690620929263
12.24368576160033
12.243680903326336
12.243676046107069
12.243671189942264
12.243666334831731
12.243661480775224
12.243656627772507
12.243651775823373
12.243646924927573
12.243642075084884
12.243637226295084
12.243632378557932
12.2436275318732
12.243622686240666
12.243617841660116
12.243612998131292
12.243608155653982
12.243603314227965
12.243598473852986
12.24359363452885
12.243588796255297
12.243583959032124
12.243579122859085
12.243574287735969
12.243569453662547
12.243564620638562
12.243559788663823
12.24355495773807
12.243550127861111
12.243545299032684
12.243540471252587
12.243535644520565
12.243530818836419
12.243525994199903
12.2435211706108
12.243516348068884
12.243511526573906
12.243506706125666
12.243501886723921
12.243497068368441
12.243492251059012
12.243487434795403
12.243482619577374
12.243477805404726
12.243472992277194
12.243468180194576
12.243463369156647
12.243458559163164
12.243453750213918
12.243448942308664
12.243444135447191
12.243439329629263
12.243434524854658
12.243429721123142
12.243424918434503
12.243420116788505
12.243415316184908
12.243410516623515
12.243405718104071
12.243400920626376
12.24339612419019
12.24339132879528
12.243386534441433
12.243381741128411
12.243376948855998
12.243372157623963
12.243367367432086
12.24336257828013
12.243357790167881
12.2433530030951
12.243348217061579
12.243343432067066
12.243338648111374
12.243333865194236
12.243329083315459
12.2433243024748
12.243319522672031
12.24331474390694
12.24330996617929
12.24330518948886
12.243300413835433
12.243295639218765
12.243290865638645
12.24328609309485
12.243281321587144
12.243276551115304
12.243271781679123
12.243267013278349
12.243262245912767
12.243257479582166
12.243252714286305
12.243247950024955
12.243243186797917
12.243238424604938
12.243233663445809
12.243228903320299
12.243224144228195
12.243219386169262
12.243214629143274
12.243209873149999
12.243205118189247
12.243200364260748
12.24319561136431
12.243190859499705
12.243186108666693
12.243181358865073
12.243176610094592
12.243171862355055
12.243167115646214
12.243162369967873
12.243157625319782
12.243152881701725
12.243148139113481
12.243143397554825
12.24313865702554
12.243133917525386
12.24312917905415
12.243124441611617
12.243119705197554
12.243114969811733
12.24311023545394
12.243105502123944
12.24310076982153
12.243096038546472
12.243091308298544
12.243086579077529
12.24308185088319
12.24307712371531
12.243072397573679
12.243067672458054
12.24306294836823
12.243058225303976
12.243053503265083
12.243048782251298
12.24304406226242
12.243039343298229
12.243034625358487
12.243029908442981
12.243025192551489
12.243020477683794
12.24301576383966
12.24301105101887
12.243006339221216
12.243001628446445
12.242996918694363
12.242992209964735
12.242987502257352
12.242982795571962
12.242978089908382
12.242973385266358
12.24296868164569
12.24296397904615
12.242959277467502
12.242954576909542
12.24294987737205
12.242945178854779
12.242940481357536
12.242935784880087
12.242931089422209
12.242926394983684
12.242921701564297
12.24291700916381
12.242912317782016
12.24290762741869
12.24290293807361
12.242898249746547
12.242893562437299
12.242888876145637
12.24288419087133
12.242879506614164
12.242874823373915
12.242870141150364
12.242865459943301
12.242860779752483
12.242856100577704
12.242851422418749
12.242846745275388
12.242842069147404
12.242837394034561
12.242832719936667
12.242828046853479
12.242823374784786
12.242818703730364
12.242814033689989
12.242809364663453
12.242804696650529
12.242800029650999
12.242795363664637
12.242790698691234
12.242786034730544
12.242781371782389
12.242776709846519
12.242772048922717
12.242767389010767
12.242762730110444
12.242758072221543
12.242753415343838
12.242748759477102
12.242744104621117
12.242739450775668
12.242734797940537
12.242730146115504
12.24272549530034
12.242720845494834
12.242716196698767
12.242711548911922
12.24270690213407
12.242702256365005
12.242697611604488
12.242692967852326
12.24268832510829
12.242683683372144
12.242679042643696
12.242674402922706
12.242669764208964
12.242665126502256
12.24266048980235
12.242655854109046
12.24265121942211
12.242646585741326
12.242641953066473
12.24263732139735
12.242632690733714
12.242628061075365
12.242623432422075
12.242618804773631
12.242614178129815
12.242609552490396
12.242604927855172
12.24260030422392
12.242595681596427
12.242591059972463
12.242586439351816
12.242581819734271
12.242577201119603
12.242572583507604
12.242567966898049
12.242563351290716
12.242558736685398
12.242554123081884
12.242549510479929
12.242544898879332
12.242540288279887
12.242535678681353
12.242531070083533
12.242526462486198
12.24252185588914
12.242517250292124
12.242512645694957
12.242508042097391
12.242503439499243
12.242498837900273
12.242494237300281
12.242489637699029
12.242485039096318
12.242480441491924
12.242475844885625
12.242471249277221
12.24246665466648
12.242462061053175
12.242457468437127
12.242452876818078
12.242448286195835
12.242443696570174
12.242439107940887
12.242434520307755
12.242429933670548
12.24242534802907
12.24242076338309
12.242416179732388
12.242411597076769
12.242407015415996
12.242402434749867
12.242397855078156
12.242393276400643
12.24238869871713
12.242384122027397
12.242379546331218
12.242374971628374
12.24237039791866
12.242365825201865
12.242361253477755
12.242356682746136
12.242352113006767
12.242347544259463
12.242342976503998
12.242338409740121
12.242333843967671
12.242329279186404
12.242324715396101
12.24232015259656
12.242315590787557
12.2423110299689
12.24230647014033
12.242301911301672
12.242297353452692
12.242292796593173
12.24228824072291
12.242283685841691
12.24227913194928
12.242274579045489
12.242270027130086
12.242265476202851
12.242260926263587
12.242256377312083
12.2422518293481
12.24224728237145
12.2422427363819
12.242238191379228
12.242233647363243
12.242229104333715
12.242224562290449
12.24222002123321
12.242215481161779
12.242210942075971
12.242206403975558
12.242201866860308
12.242197330730024
12.242192795584495
12.242188261423497
12.242183728246829
12.242179196054275
12.242174664845598
12.242170134620606
12.242165605379089
12.242161077120818
12.242156549845593
12.242152023553196
12.242147498243408
12.242142973916023
12.24213845057082
12.242133928207597
12.242129406826137
12.242124886426215
12.242120367007635
12.242115848570172
12.242111331113607
12.242106814637747
12.242102299142367
12.242097784627259
12.242093271092202
12.242088758536983
12.242084246961408
12.242079736365236
12.242075226748273
12.24207071811031
12.242066210451119
12.24206170377049
12.242057198068217
12.242052693344094
12.242048189597902
12.242043686829422
12.242039185038438
12.242034684224766
12.242030184388152
12.242025685528423
12.242021187645344
12.2420166907387
12.242012194808296
12.242007699853906
12.242003205875335
12.24199871287236
12.241994220844758
12.241989729792335
12.241985239714863
12.241980750612157
12.241976262483972
12.24197177533012
12.241967289150377
12.241962803944547
12.241958319712392
12.241953836453717
12.241949354168323
12.241944872855978
12.241940392516474
12.241935913149613
12.241931434755172
12.241926957332934
12.24192248088271
12.241918005404262
12.2419135308974
12.241909057361902
12.241904584797556
12.241900113204165
12.241895642581497
12.241891172929357
12.241886704247538
12.241882236535812
12.241877769793978
12.241873304021828
12.241868839219139
12.241864375385722
12.24185991252135
12.241855450625808
12.241850989698905
12.241846529740418
12.241842070750144
12.24183761272786
12.241833155673358
12.241828699586438
12.241824244466889
12.24181979031449
12.241815337129042
12.241810884910329
12.24180643365815
12.241801983372277
12.24179753405252
12.241793085698651
12.241788638310478
12.241784191887776
12.241779746430344
12.241775301937974
12.241770858410447
12.241766415847563
12.241761974249108
12.241757533614871
12.241753093944652
12.241748655238222
12.241744217495404
12.24173978071595
12.241735344899674
12.24173091004637
12.241726476155815
12.241722043227806
12.241717611262139
12.241713180258602
12.241708750216977
12.241704321137068
12.24169989301866
12.241695465861541
12.241691039665513
12.24168661443036
12.241682190155867
12.241677766841832
12.241673344488056
12.241668923094311
12.241664502660406
12.241660083186119
12.241655664671251
12.24165124711559
12.24164683051893
12.241642414881056
12.24163800020176
12.24163358648085
12.2416291737181
12.241624761913315
12.241620351066276
12.241615941176775
12.24161153224461
12.241607124269576
12.241602717251453
12.241598311190048
12.241593906085145
12.241589501936534
12.241585098744013
12.24158069650737
12.241576295226393
12.24157189490089
12.241567495530644
12.241563097115442
12.241558699655082
12.241554303149355
12.241549907598067
12.241545513000993
12.241541119357933
12.241536726668677
12.241532334933027
12.241527944150757
12.241523554321672
12.241519165445581
12.241514777522244
12.241510390551479
12.241506004533068
12.241501619466804
12.241497235352488
12.241492852189916
12.241488469978867
12.241484088719139
12.24147970841053
12.24147532905283
12.241470950645835
12.241466573189335
12.241462196683129
12.241457821127005
12.241453446520762
12.241449072864183
12.241444700157075
12.241440328399227
12.241435957590433
12.241431587730482
12.241427218819183
12.241422850856306

12.241418483841658
12.241414117775046
12.24140975265624
12.24140538848506
12.241401025261277
12.241396662984682
12.241392301655097
12.241387941272295
12.241383581836079
12.24137922334624
12.241374865802563
12.241370509204863
12.241366153552923
12.241361798846532
12.241357445085495
12.241353092269607
12.241348740398653
12.241344389472438
12.24134003949075
12.241335690453386
12.241331342360146
12.241326995210827
12.241322649005191
12.241318303743075
12.24131395942426
12.241309616048547
12.2413052736157
12.241300932125556
12.24129659157789
12.241292251972501
12.241287913309177
12.241283575587723
12.241279238807929
12.241274902969597
12.241270568072512
12.241266234116475
12.241261901101291
12.241257569026745
12.241253237892616
12.241248907698736
12.24124457844488
12.241240250130852
12.241235922756433
12.241231596321438
12.241227270825641
12.241222946268863
12.241218622650887
12.241214299971508
12.241209978230522
12.24120565742772
12.24120133756292
12.241197018635889
12.241192700646454
12.241188383594384
12.241184067479498
12.241179752301578
12.241175438060417
12.241171124755823
12.241166812387592
12.241162500955507
12.241158190459377
12.241153880899004
12.241149572274178
12.241145264584683
12.24114095783035
12.241136652010935
12.241132347126257
12.24112804317611
12.241123740160301
12.241119438078607
12.241115136930837
12.241110836716787
12.241106537436252
12.241102239089027
12.241097941674928
12.241093645193725
12.241089349645234
12.241085055029245
12.241080761345554
12.241076468593961
12.241072176774262
12.241067885886261
12.241063595929743
12.24105930690453
12.241055018810394
12.241050731647146
12.241046445414574
12.241042160112487
12.241037875740682
12.241033592298946
12.24102930978709
12.2410250282049
12.241020747552186
12.241016467828745
12.24101218903436
12.241007911168843
12.241003634231994
12.240999358223599
12.24099508314348
12.240990808991405
12.240986535767195
12.240982263470634
12.240977992101527
12.240973721659673
12.240969452144869
12.24096518355692
12.240960915895615
12.240956649160758
12.240952383352147
12.240948118469591
12.24094385451287
12.240939591481792
12.240935329376164
12.240931068195769
12.240926807940411
12.240922548609898
12.24091829020402
12.240914032722577
12.240909776165376
12.240905520532209
12.240901265822883
12.240897012037186
12.240892759174926
12.240888507235894
12.240884256219898
12.240880006126737
12.240875756956205
12.24087150870811
12.240867261382245
12.240863014978414
12.240858769496404
12.24085452493603
12.240850281297098
12.240846038579384
12.240841796782698
12.24083755590685
12.240833315951638
12.240829076916844
12.240824838802286
12.240820601607764
12.240816365333067
12.240812129978005
12.240807895542373
12.240803662025971
12.240799429428598
12.240795197750074
12.240790966990176
12.240786737148705
12.240782508225472
12.240778280220274
12.240774053132915
12.240769826963186
12.240765601710901
12.240761377375858
12.24075715395784
12.240752931456672
12.240748709872138
12.240744489204046
12.2407402694522
12.240736050616402
12.24073183269644
12.240727615692133
12.240723399603263
12.24071918442964
12.240714970171076
12.240710756827358
12.240706544398288
12.240702332883673
12.240698122283321
12.240693912597017
12.240689703824573
12.240685495965783
12.240681289020463
12.240677082988402
12.2406728778694
12.24066867366327
12.240664470369804
12.240660267988808
12.240656066520081
12.240651865963438
12.24064766631866
12.240643467585562
12.240639269763946
12.240635072853609
12.24063087685435
12.240626681765981
12.240622487588299
12.240618294321111
12.240614101964212
12.240609910517401
12.240605719980497
12.24060153035328
12.240597341635585
12.240593153827175
12.240588966927874
12.240584780937489
12.24058059585582
12.240576411682653
12.240572228417813
12.240568046061085
12.240563864612286
12.240559684071215
12.240555504437669
12.240551325711454
12.24054714789237
12.240542970980231
12.240538794974828
12.24053461987597
12.240530445683456
12.240526272397098
12.240522100016692
12.240517928542038
12.240513757972941
12.24050958830921
12.240505419550658
12.240501251697065
12.24049708474825
12.240492918704003
12.240488753564145
12.240484589328464
12.240480425996765
12.24047626356888
12.240472102044581
12.240467941423674
12.240463781705973
12.240459622891276
12.240455464979402
12.240451307970124
12.240447151863282
12.240442996658647
12.240438842356049
12.240434688955274
12.240430536456136
12.240426384858447
12.240422234162
12.240418084366592
12.240413935472036
12.240409787478137
12.24040564038471
12.240401494191532
12.24039734889844
12.24039320450521
12.240389061011665
12.2403849184176
12.240380776722823
12.240376635927142
12.240372496030359
12.24036835703228
12.240364218932699
12.240360081731433
12.240355945428295
12.24035181002307
12.240347675515574
12.240343541905617
12.240339409192984
12.240335277377504
12.240331146458965
12.240327016437181
12.240322887311958
12.240318759083097
12.240314631750408
12.240310505313687
12.240306379772745
12.240302255127393
12.240298131377436
12.240294008522666
12.240289886562898
12.240285765497937
12.24028164532759
12.24027752605167
12.240273407669969
12.240269290182303
12.240265173588467
12.240261057888276
12.240256943081528
12.240252829168035
12.240248716147612
12.240244604020043
12.240240492785153
12.240236382442742
12.240232272992616
12.240228164434583
12.240224056768438
12.240219949994014
12.240215844111084
12.240211739119472
12.240207635018988
12.240203531809426
12.240199429490607
12.24019532806233
12.240191227524399
12.240187127876622
12.240183029118816
12.240178931250767
12.240174834272299
12.240170738183215
12.240166642983315
12.240162548672426
12.240158455250326
12.240154362716844
12.240150271071778
12.240146180314941
12.240142090446122
12.240138001465155
12.240133913371828
12.240129826165958
12.240125739847338
12.240121654415796
12.240117569871131
12.240113486213152
12.240109403441654
12.240105321556447
12.240101240557362
12.240097160444193
12.24009308121672
12.24008900287479
12.240084925418202
12.24008084884675
12.240076773160245
12.240072698358498
12.240068624441323
12.240064551408528
12.240060479259911
12.240056407995286
12.240052337614465
12.240048268117237
12.240044199503437
12.240040131772849
12.240036064925308
12.240031998960594
12.240027933878533
12.240023869678923
12.240019806361591
12.240015743926323
12.240011682372936
12.240007621701238
12.240003561911045
12.239999503002156
12.23999544497438
12.239991387827525
12.239987331561412
12.239983276175842
12.239979221670614
12.239975168045557
12.23997111530046
12.239967063435142
12.239963012449415
12.239958962343087
12.239954913115945
12.239950864767831
12.239946817298536
12.23994277070787
12.239938724995664
12.239934680161687
12.239930636205768
12.23992659312772
12.239922550927359
12.23991850960448
12.239914469158903
12.239910429590429
12.239906390898865
12.23990235308404
12.23989831614574
12.239894280083794
12.239890244897998
12.239886210588164
12.239882177154103
12.239878144595641
12.239874112912561
12.239870082104675
12.23986605217182
12.239862023113785
12.239857994930377
12.239853967621418
12.239849941186716
12.239845915626073
12.2398418909393
12.239837867126216
12.239833844186634
12.23982982212035
12.239825800927175
12.239821780606938
12.239817761159442
12.239813742584477
12.239809724881876
12.239805708051446
12.239801692092993
12.239797677006335
12.239793662791259
12.239789649447612
12.239785636975181
12.239781625373778
12.239777614643225
12.239773604783316
12.239769595793879
12.239765587674725
12.23976158042565
12.239757574046473
12.239753568537
12.239749563897051
12.239745560126444
12.239741557224969
12.23973755519245
12.2397335540287
12.239729553733527
12.23972555430674
12.239721555748146
12.239717558057563
12.239713561234822
12.239709565279693
12.239705570192017
12.239701575971601
12.239697582618252
12.239693590131777
12.239689598512006
12.239685607758734
12.239681617871783
12.239677628850956
12.239673640696067
12.239669653406928
12.23966566698336
12.239661681425169
12.23965769673216
12.239653712904147
12.23964972994095
12.239645747842378
12.239641766608246
12.239637786238363
12.23963380673253
12.239629828090575
12.239625850312324
12.239621873397553
12.239617897346102
12.239613922157767
12.239609947832372
12.239605974369729
12.23960200176965
12.23959803003194
12.239594059156417
12.2395900891429
12.239586119991186
12.239582151701098
12.239578184272455
12.239574217705055
12.239570251998726
12.23956628715327
12.239562323168514
12.239558360044247
12.239554397780301
12.239550436376492
12.23954647583262
12.239542516148505
12.239538557323963
12.239534599358795
12.23953064225283
12.239526686005881
12.239522730617749
12.239518776088254
12.2395148224172
12.239510869604423
12.23950691764972
12.239502966552903
12.239499016313802
12.239495066932209
12.23949111840795
12.239487170740839
12.239483223930687
12.239479277977315
12.239475332880524
12.239471388640137
12.23946744525597
12.23946350272783
12.23945956105553
12.239455620238898
12.239451680277726
12.239447741171848
12.239443802921075
12.239439865525215
12.23943592898408
12.239431993297499
12.23942805846526
12.23942412448721
12.239420191363143
12.23941625909288
12.239412327676227
12.239408397113017
12.239404467403041
12.23940053854613
12.239396610542096
12.239392683390747
12.239388757091913
12.23938483164539
12.239380907051011
12.239376983308572
12.239373060417913
12.23936913837882
12.23936521719113
12.239361296854646
12.23935737736919
12.239353458734577
12.239349540950611
12.239345624017117
12.239341707933923
12.239337792700818
12.239333878317638
12.239329964784185
12.23932605210028
12.239322140265749
12.23931822928039
12.239314319144018
12.239310409856467
12.239306501417541
12.239302593827059
12.239298687084831
12.23929478119067
12.239290876144407
12.239286971945848
12.239283068594816
12.239279166091114
12.23927526443457
12.239271363624992
12.239267463662193
12.239263564546008
12.239259666276235
12.239255768852699
12.239251872275197
12.23924797654358
12.23924408165764
12.239240187617197
12.239236294422073
12.239232402072082
12.23922851056704
12.239224619906755
12.239220730091056
12.239216841119761
12.239212952992677
12.239209065709625
12.23920517927042
12.239201293674872
12.239197408922815
12.239193525014056
12.23918964194841
12.2391857597257
12.239181878345736
12.239177997808342
12.23917411811333
12.239170239260517
12.239166361249723
12.23916248408076
12.239158607753454
12.23915473226762
12.239150857623065
12.239146983819612
12.239143110857087
12.239139238735303
12.239135367454065
12.239131497013215
12.239127627412545
12.239123758651887
12.23911989073105
12.239116023649865
12.239112157408144
12.239108292005692
12.239104427442333
12.239100563717898
12.239096700832201
12.239092838785059
12.239088977576268
12.239085117205667
12.239081257673076
12.239077398978305
12.239073541121176
12.239069684101507
12.23906582791911
12.239061972573808
12.239058118065426
12.239054264393776
12.239050411558669
12.239046559559938
12.239042708397378
12.23903885807084

12.239035008580121
12.239031159925034
12.239027312105415
12.239023465121075
12.239019618971836
12.239015773657513
12.239011929177927
12.23900808553289
12.239004242722213
12.239000400745752
12.23899655960329
12.238992719294657
12.23898887981967
12.238985041178147
12.23898120336993
12.238977366394801
12.238973530252595
12.238969694943144
12.238965860466248
12.238962026821737
12.238958194009424
12.238954362029128
12.238950530880675
12.23894670056388
12.238942871078576
12.238939042424553
12.238935214601659
12.238931387609698
12.238927561448488
12.238923736117863
12.23891991161763
12.238916087947615
12.23891226510764
12.238908443097507
12.23890462191706
12.2389008015661
12.238896982044459
12.23889316335195
12.238889345488404
12.23888552845362
12.238881712247437
12.238877896869672
12.23887408232013
12.238870268598655
12.238866455705049
12.238862643639143
12.238858832400751
12.23885502198969
12.238851212405791
12.238847403648863
12.238843595718738
12.238839788615232
12.238835982338163
12.238832176887346
12.238828372262615
12.238824568463777
12.238820765490667
12.2388169633431
12.238813162020891
12.238809361523861
12.23880556185183
12.238801763004643
12.238797964982089
12.238794167784
12.238790371410195
12.238786575860507
12.238782781134745
12.238778987232731
12.2387751941543
12.238771401899244
12.238767610467415
12.238763819858617
12.238760030072669
12.238756241109417
12.238752452968642
12.238748665650201
12.238744879153908
12.238741093479558
12.238737308627012
12.238733524596068
12.238729741386546
12.238725958998277
12.23872217743108
12.23871839668478
12.238714616759193
12.238710837654132
12.238707059369446
12.238703281904934
12.238699505260419
12.238695729435733
12.238691954430697
12.23868818024512
12.238684406878846
12.238680634331677
12.238676862603445
12.23867309169397
12.238669321603064
12.238665552330573
12.238661783876298
12.238658016240075
12.238654249421717
12.238650483421049
12.238646718237899
12.23864295387207
12.238639190323413
12.238635427591738
12.23863166567686
12.23862790457861
12.238624144296802
12.23862038483128
12.23861662618184
12.238612868348321
12.23860911133054
12.238605355128332
12.238601599741497
12.238597845169883
12.238594091413283
12.238590338471559
12.238586586344491
12.238582835031936
12.238579084533699
12.238575334849617
12.2385715859795
12.238567837923185
12.238564090680471
12.238560344251209
12.238556598635205
12.238552853832294
12.238549109842296
12.238545366665015
12.238541624300304
12.23853788274797
12.238534142007842
12.238530402079748
12.238526662963498
12.238522924658929
12.238519187165858
12.23851545048411
12.238511714613507
12.238507979553873
12.238504245305034
12.238500511866826
12.238496779239048
12.238493047421539
12.238489316414125
12.238485586216628
12.238481856828857
12.238478128250666
12.23847440048185
12.238470673522253
12.238466947371682
12.238463222029985
12.238459497496967
12.238455773772456
12.238452050856276
12.238448328748268
12.238444607448226
12.238440886955997
12.238437167271405
12.238433448394263
12.238429730324409
12.238426013061648
12.238422296605828
12.238418580956765
12.23841486611428
12.238411152078196
12.23840743884834
12.238403726424547
12.23840001480663
12.23839630399441
12.238392593987735
12.238388884786406
12.238385176390258
12.238381468799124
12.238377762012801
12.238374056031152
12.23837035085398
12.23836664648111
12.238362942912364
12.238359240147588
12.238355538186598
12.238351837029205
12.238348136675253
12.238344437124551
12.238340738376946
12.23833704043224
12.238333343290275
12.23832964695087
12.238325951413858
12.238322256679051
12.238318562746292
12.238314869615397
12.238311177286183
12.238307485758497
12.238303795032149
12.23830010510696
12.238296415982777
12.23829272765941
12.238289040136705
12.238285353414453
12.2382816674925
12.238277982370684
12.238274298048806
12.238270614526721
12.238266931804239
12.238263249881184
12.238259568757384
12.238255888432663
12.238252208906871
12.238248530179801
12.238244852251292
12.238241175121182
12.238237498789282
12.238233823255424
12.238230148519442
12.238226474581154
12.238222801440385
12.23821912909697
12.238215457550732
12.238211786801495
12.238208116849092
12.238204447693354
12.238200779334088
12.238197111771145
12.238193445004335
12.238189779033485
12.23818611385844
12.238182449479012
12.238178785895037
12.23817512310633
12.238171461112728
12.238167799914056
12.238164139510138
12.238160479900804
12.238156821085889
12.238153163065217
12.238149505838594
12.23814584940588
12.238142193766882
12.238138538921437
12.238134884869378
12.238131231610508
12.23812757914469
12.238123927471719
12.238120276591442
12.238116626503675
12.238112977208262
12.238109328705022
12.238105680993767
12.23810203407437
12.238098387946604
12.238094742610318
12.238091098065365
12.238087454311552
12.238083811348703
12.238080169176655
12.23807652779522
12.238072887204265
12.238069247403573
12.238065608392992
12.238061970172351
12.238058332741486
12.238054696100203
12.238051060248367
12.238047425185771
12.238043790912258
12.238040157427658
12.2380365247318
12.238032892824505
12.238029261705607
12.238025631374942
12.238022001832324
12.238018373077598
12.238014745110583
12.238011117931102
12.238007491538998
12.238003865934093
12.23800024111621
12.23799661708519
12.23799299384087
12.237989371383051
12.237985749711573
12.237982128826276
12.237978508726991
12.237974889413533
12.237971270885737
12.237967653143432
12.23796403618645
12.237960420014623
12.237956804627771
12.237953190025731
12.237949576208331
12.237945963175397
12.23794235092677
12.237938739462265
12.23793512878172
12.237931518884972
12.23792790977183
12.237924301442137
12.237920693895727
12.237917087132416
12.237913481152054
12.237909875954456
12.23790627153945
12.237902667906885
12.237899065056567
12.237895462988341
12.237891861702035
12.237888261197469
12.23788466147449
12.23788106253291
12.237877464372579
12.23787386699331
12.237870270394952
12.237866674577326
12.237863079540258
12.237859485283574
12.237855891807119
12.237852299110713
12.237848707194189
12.237845116057386
12.23784152570013
12.237837936122233
12.237834347323565
12.23783075930392
12.237827172063136
12.237823585601063
12.23781999991752
12.237816415012329
12.237812830885336
12.237809247536358
12.23780566496526
12.237802083171816
12.237798502155895
12.237794921917319
12.23779134245594
12.237787763771562
12.237784185864019
12.237780608733154
12.237777032378785
12.237773456800761
12.237769881998899
12.237766307973034
12.237762734723008
12.237759162248627
12.237755590549744
12.237752019626193
12.237748449477783
12.237744880104382
12.237741311505784
12.237737743681844
12.237734176632378
12.23773061035724
12.237727044856236
12.237723480129228
12.237719916176019
12.237716352996447
12.237712790590358
12.23770922895757
12.237705668097927
12.23770210801125
12.237698548697367
12.23769499015614
12.237691432387367
12.237687875390902
12.237684319166563
12.237680763714192
12.23767720903361
12.237673655124661
12.237670101987176
12.23766654962098
12.237662998025923
12.23765944720181
12.237655897148501
12.237652347865813
12.237648799353583
12.23764525161163
12.237641704639815
12.237638158437957
12.23763461300588
12.237631068343413
12.237627524450414
12.23762398132671
12.23762043897211
12.23761689738647
12.237613356569613
12.237609816521381
12.237606277241593
12.237602738730097
12.237599200986718
12.237595664011286
12.237592127803643
12.237588592363611
12.237585057691037
12.237581523785755
12.237577990647576
12.237574458276358
12.237570926671925
12.237567395834116
12.237563865762745
12.237560336457664
12.237556807918715
12.237553280145706
12.237549753138493
12.237546226896898
12.237542701420754
12.2375391767099
12.237535652764167
12.237532129583391
12.237528607167407
12.237525085516046
12.237521564629136
12.237518044506523
12.237514525148034
12.237511006553511
12.237507488722775
12.237503971655668
12.237500455352025
12.237496939811686
12.237493425034463
12.23748991102021
12.23748639776876
12.237482885279947
12.237479373553592
12.237475862589552
12.237472352387645
12.237468842947703
12.23746533426958
12.237461826353082
12.237458319198067
12.23745481280437
12.237451307171805
12.237447802300228
12.237444298189462
12.237440794839346
12.23743729224971
12.237433790420402
12.237430289351243
12.237426789042066
12.237423289492726
12.237419790703044
12.23741629267285
12.237412795401982
12.237409298890285
12.237405803137584
12.237402308143709
12.237398813908516
12.237395320431823
12.237391827713473
12.237388335753291
12.237384844551128
12.237381354106812
12.237377864420178
12.237374375491054
12.237370887319289
12.237367399904718
12.237363913247156
12.237360427346466
12.237356942202464
12.237353457815002
12.237349974183898
12.237346491309001
12.237343009190147
12.237339527827158
12.237336047219877
12.237332567368155
12.237329088271805
12.237325609930677
12.237322132344602
12.23731865551341
12.237315179436958
12.23731170411506
12.237308229547565
12.237304755734309
12.237301282675109
12.23729781036982
12.237294338818286
12.237290868020324
12.237287397975779
12.237283928684487
12.237280460146286
12.237276992361009
12.23727352532849
12.237270059048573
12.237266593521097
12.23726312874589
12.237259664722776
12.237256201451624
12.237252738932256
12.237249277164498
12.237245816148194
12.237242355883192
12.237238896369318
12.237235437606406
12.237231979594293
12.23722852233283
12.237225065821836
12.237221610061159
12.23721815505063
12.2372147007901
12.237211247279388
12.237207794518334
12.237204342506793
12.237200891244584
12.237197440731544
12.237193990967521
12.237190541952346
12.237187093685856
12.237183646167885
12.237180199398294
12.237176753376882
12.237173308103516
12.237169863578023
12.237166419800252
12.237162976770014
12.237159534487173
12.237156092951553
12.237152652162996
12.237149212121343
12.237145772826429
12.237142334278087
12.237138896476168
12.237135459420488
12.237132023110899
12.237128587547247
12.237125152729359
12.237121718657075
12.237118285330226
12.23711485274867
12.23711142091222

12.237107989820737
12.237104559474039
12.237101129871986
12.237097701014395
12.237094272901118
12.237090845531984
12.237087418906842
12.237083993025538
12.237080567887881
12.237077143493728
12.237073719842924
12.237070296935292
12.237066874770678
12.237063453348929
12.237060032669872
12.23705661273335
12.237053193539191
12.237049775087252
12.237046357377363
12.237042940409369
12.237039524183103
12.237036108698392
12.237032693955106
12.237029279953056
12.237025866692088
12.23702245417205
12.237019042392768
12.237015631354094
12.237012221055853
12.237008811497901
12.237005402680067
12.23700199460219
12.236998587264118
12.236995180665675
12.236991774806713
12.23698836968706
12.236984965306572
12.23698156166509
12.236978158762417
12.236974756598444
12.236971355172969
12.236967954485852
12.236964554536929
12.236961155326044
12.236957756853036
12.236954359117728
12.236950962119987
12.23694756585962
12.236944170336495
12.236940775550448
12.236937381501303
12.236933988188925
12.236930595613128
12.236927203773766
12.236923812670675
12.236920422303704
12.236917032672688
12.236913643777456
12.23691025561786
12.236906868193735
12.236903481504926
12.236900095551272
12.236896710332605
12.236893325848795
12.23688994209964
12.236886559085
12.23688317680474
12.23687979525866
12.236876414446618
12.236873034368456
12.236869655024018
12.236866276413135
12.236862898535653
12.236859521391407
12.236856144980248
12.236852769302015
12.236849394356543
12.236846020143677
12.236842646663264
12.236839273915121
12.236835901899118
12.236832530615079
12.236829160062852
12.236825790242275
12.236822421153189
12.236819052795436
12.236815685168859
12.2368123182733
12.236808952108596
12.236805586674596
12.236802221971121
12.236798857998037
12.236795494755167
12.236792132242371
12.23678877045948
12.236785409406325
12.23678204908277
12.236778689488638
12.236775330623788
12.23677197248804
12.236768615081257
12.236765258403258
12.236761902453907
12.236758547233038
12.236755192740489
12.2367518389761
12.236748485939716
12.236745133631182
12.236741782050334
12.236738431197029
12.236735081071092
12.236731731672364
12.236728383000703
12.236725035055947
12.236721687837923
12.23671834134649
12.236714995581488
12.236711650542741
12.236708306230108
12.236704962643428
12.236701619782556
12.236698277647319
12.236694936237553
12.236691595553125
12.236688255593855
12.236684916359591
12.236681577850186
12.236678240065467
12.236674903005293
12.23667156666949
12.236668231057912
12.236664896170401
12.236661562006788
12.236658228566942
12.236654895850679
12.23665156385785
12.236648232588305
12.236644902041874
12.236641572218419
12.236638243117765
12.236634914739764
12.236631587084252
12.23662826015109
12.236624933940103
12.236621608451125
12.236618283684033
12.236614959638638
12.23661163631482
12.236608313712376
12.236604991831177
12.236601670671062
12.236598350231874
12.236595030513458
12.236591711515661
12.23658839323831
12.23658507568127
12.236581758844357
12.236578442727447
12.236575127330369
12.23657181265297
12.236568498695082
12.236565185456568
12.236561872937253
12.236558561136986
12.23655525005562
12.236551939692987
12.236548630048942
12.23654532112333
12.23654201291598
12.236538705426748
12.236535398655471
12.236532092601996
12.236528787266176
12.236525482647842
12.23652217874684
12.236518875563021
12.236515573096225
12.236512271346301
12.236508970313093
12.236505669996435
12.236502370396176
12.236499071512167
12.23649577334426
12.23649247589227
12.236489179156056
12.23648588313549
12.236482587830377
12.236479293240578
12.236475999365936
12.236472706206305
12.236469413761522
12.236466122031425
12.236462831015865
12.236459540714693
12.236456251127747
12.236452962254862
12.23644967409591
12.236446386650707
12.236443099919116
12.236439813900978
12.236436528596144
12.236433244004438
12.236429960125733
12.236426676959848
12.236423394506643
12.236420112765972
12.23641683173766
12.236413551421567
12.236410271817537
12.236406992925398
12.236403714745013
12.236400437276227
12.236397160518884
12.236393884472818
12.236390609137894
12.236387334513951
12.236384060600821
12.236380787398375
12.236377514906426
12.23637424312484
12.236370972053463
12.236367701692147
12.23636443204072
12.236361163099039
12.236357894866941
12.236354627344285
12.236351360530909
12.236348094426663
12.236344829031387
12.236341564344931
12.236338300367148
12.236335037097863
12.236331774536954
12.236328512684238
12.23632525153957
12.236321991102804
12.236318731373784
12.236315472352345
12.236312214038351
12.236308956431627
12.236305699532052
12.236302443339442
12.23629918785364
12.236295933074512
12.236292679001913
12.236289425635661
12.23628617297562
12.236282921021642
12.23627966977355
12.236276419231226
12.236273169394481
12.23626992026318
12.236266671837164
12.2362634241163
12.236260177100402
12.236256930789343
12.236253685182957
12.236250440281085
12.236247196083596
12.236243952590325
12.23624070980111
12.236237467715817
12.23623422633427
12.236230985656338
12.236227745681852
12.236224506410666
12.23622126784264
12.236218029977607
12.2362147928154
12.236211556355896
12.236208320598926
12.23620508554435
12.236201851191993
12.236198617541723
12.236195384593374
12.23619215234681
12.236188920801856
12.236185689958385
12.236182459816224
12.236179230375233
12.236176001635254
12.236172773596133
12.236169546257717
12.236166319619871
12.236163093682423
12.236159868445231
12.236156643908126
12.236153420070995
12.236150196933643
12.236146974495936
12.23614375275773
12.236140531718867
12.236137311379181
12.236134091738544
12.23613087279678
12.236127654553759
12.236124437009318
12.23612122016331
12.236118004015584
12.236114788565978
12.236111573814346
12.236108359760548
12.236105146404414
12.236101933745811
12.236098721784574
12.236095510520553
12.236092299953606
12.236089090083558
12.236085880910286
12.236082672433634
12.236079464653429
12.236076257569536
12.236073051181808
12.236069845490093
12.236066640494228
12.236063436194074
12.236060232589466
12.236057029680275
12.23605382746633
12.236050625947486
12.236047425123594
12.2360442249945
12.236041025560064
12.236037826820123
12.23603462877453
12.236031431423136
12.236028234765786
12.23602503880233
12.236021843532626
12.236018648956506
12.236015455073836
12.236012261884458
12.23600906938821
12.236005877584985
12.236002686474572
12.235999496056866
12.2359963063317
12.235993117298921
12.235989928958388
12.23598674130994
12.235983554353433
12.235980368088716
12.235977182515644
12.235973997634057
12.235970813443808
12.235967629944739
12.235964447136723
12.235961265019593
12.2359580835932
12.235954902857394
12.235951722812027
12.235948543456955
12.235945364792018
12.235942186817066
12.235939009531966
12.235935832936539
12.235932657030665
12.235929481814184
12.23592630728693
12.23592313344878
12.235919960299563
12.235916787839145
12.23591361606736
12.235910444984079
12.235907274589136
12.235904104882378
12.235900935863679
12.235897767532869
12.235894599889804
12.235891432934347
12.235888266666322
12.235885101085598
12.23588193619203
12.235878771985453
12.235875608465722
12.23587244563271
12.235869283486227
12.235866122026165
12.235862961252355
12.235859801164645
12.235856641762895
12.235853483046952
12.235850325016663
12.235847167671885
12.235844011012478
12.23584085503827
12.235837699749132
12.235834545144904
12.23583139122544
12.2358282379906
12.235825085440215
12.235821933574165
12.235818782392283
12.235815631894418
12.235812482080426
12.235809332950167
12.23580618450348
12.235803036740226
12.235799889660244
12.235796743263403
12.235793597549538
12.23579045251852
12.235787308170178
12.23578416450438
12.235781021520971
12.235777879219807
12.235774737600737
12.235771596663616
12.235768456408293
12.235765316834613
12.235762177942435
12.235759039731613
12.235755902202005
12.235752765353451
12.235749629185808
12.235746493698926
12.23574335889267
12.235740224766872
12.235737091321381
12.235733958556088
12.235730826470805
12.235727695065394
12.23572456433972
12.235721434293621
12.235718304926966
12.235715176239585
12.235712048231349
12.235708920902107
12.235705794251706
12.23570266828
12.235699542986849
12.23569641837209
12.235693294435592
12.235690171177199
12.23568704859677
12.235683926694154
12.235680805469194
12.235677684921772
12.235674565051703
12.235671445858873
12.235668327343111
12.235665209504283
12.235662092342233
12.23565897585682
12.235655860047903
12.23565274491533
12.235649630458944
12.235646516678623
12.235643403574187
12.235640291145515
12.235637179392452
12.235634068314848
12.235630957912564
12.23562784818545
12.23562473913335
12.235621630756134
12.23561852305364
12.235615416025741
12.235612309672263
12.235609203993087
12.235606098988042
12.235602994656999
12.235599890999817
12.23559678801633
12.235593685706398
12.235590584069898
12.235587483106643
12.235584382816517
12.235581283199368
12.235578184255033
12.23557508598339
12.235571988384274

12.23556889145756
12.235565795203089
12.235562699620697
12.23555960471027
12.23555651047165
12.235553416904686
12.235550324009234
12.235547231785157
12.2355441402323
12.23554104935051
12.23553795913966
12.235534869599592
12.235531780730172
12.235528692531235
12.235525605002655
12.235522518144279
12.23551943195595
12.235516346437535
12.235513261588894
12.23551017740987
12.235507093900326
12.235504011060105
12.235500928889069
12.235497847387078
12.23549476655399
12.235491686389631
12.235488606893885
12.235485528066608
12.235482449907636
12.235479372416831
12.235476295594047
12.23547321943915
12.23547014395198
12.235467069132408
12.235463994980265
12.235460921495434
12.235457848677749
12.235454776527082
12.23545170504327
12.235448634226179
12.235445564075674
12.235442494591585
12.235439425773786
12.23543635762213
12.235433290136468
12.235430223316657
12.235427157162553
12.235424091674014
12.23542102685089
12.235417962693038
12.23541489920032
12.23541183637258
12.235408774209692
12.235405712711486
12.235402651877838
12.235399591708596
12.235396532203625
12.23539347336276
12.235390415185874
12.23538735767282
12.235384300823457
12.235381244637638
12.235378189115208
12.235375134256033
12.235372080059975
12.235369026526877
12.2353659736566
12.235362921449006
12.235359869903949
12.235356819021279
12.23535376880085
12.23535071924253
12.235347670346181
12.235344622111628
12.235341574538756
12.235338527627409
12.235335481377447
12.235332435788735
12.235329390861114
12.235326346594453
12.235323302988588
12.2353202600434
12.235317217758734
12.235314176134446
12.235311135170397
12.235308094866445
12.23530505522244
12.23530201623824
12.235298977913706
12.2352959402487
12.235292903243066
12.235289866896652
12.23528683120934
12.235283796180983
12.235280761811422
12.23527772810052
12.23527469504815
12.235271662654142
12.235268630918377
12.2352655998407
12.235262569420968
12.235259539659035
12.235256510554768
12.235253482108023
12.235250454318644
12.23524742718651
12.235244400711466
12.235241374893363
12.23523834973207
12.235235325227434
12.23523230137932
12.235229278187582
12.235226255652092
12.235223233772684
12.235220212549223
12.235217191981576
12.235214172069602
12.235211152813136
12.235208134212062
12.235205116266215
12.235202098975478
12.235199082339681
12.2351960663587
12.235193051032393
12.235190036360612
12.23518702234321
12.235184008980058
12.235180996271012
12.23517798421591
12.235174972814633
12.235171962067033
12.235168951972964
12.23516594253229
12.235162933744864
12.235159925610551
12.235156918129197
12.235153911300667
12.235150905124817
12.235147899601515
12.23514489473061
12.235141890511969
12.235138886945432
12.235135884030877
12.235132881768152
12.235129880157114
12.235126879197628
12.235123878889556
12.235120879232749
12.235117880227074
12.235114881872368
12.23511188416852
12.23510888711536
12.235105890712761
12.235102894960587
12.235099899858692
12.23509690540693
12.23509391160516
12.235090918453254
12.235087925951051
12.235084934098436
12.235081942895244
12.235078952341338
12.235075962436584
12.235072973180838
12.23506998457396
12.235066996615808
12.235064009306239
12.23506102264512
12.235058036632301
12.235055051267643
12.235052066551019
12.235049082482265
12.235046099061258
12.235043116287839
12.235040134161906
12.23503715268328
12.23503417185183
12.235031191667417
12.235028212129912
12.23502523323915
12.23502225499501
12.235019277397354
12.235016300446027
12.23501332414091
12.23501034848183
12.235007373468678
12.235004399101292
12.235001425379547
12.234998452303296
12.234995479872396
12.234992508086718
12.234989536946106
12.234986566450432
12.234983596599559
12.23498062739333
12.23497765883163
12.234974690914294
12.234971723641195
12.234968757012194
12.234965791027138
12.234962825685914
12.23495986098835
12.23495689693433
12.2349539335237
12.234950970756326
12.23494800863208
12.234945047150806
12.234942086312369
12.234939126116624
12.234936166563447
12.23493320765268
12.234930249384192
12.23492729175785
12.234924334773506
12.234921378431029
12.234918422730267
12.234915467671092
12.234912513253356
12.234909559476916
12.234906606341656
12.234903653847418
12.234900701994068
12.234897750781455
12.234894800209458
12.234891850277933
12.23488890098673
12.234885952335727
12.234883004324772
12.234880056953722
12.234877110222456
12.234874164130822
12.234871218678686
12.234868273865901
12.234865329692349
12.234862386157857
12.234859443262323
12.234856501005591
12.234853559387519
12.23485061840797
12.234847678066807
12.234844738363895
12.234841799299085
12.234838860872255
12.234835923083255
12.23483298593195
12.2348300494182
12.234827113541863
12.23482417830281
12.234821243700893
12.234818309735983
12.234815376407928
12.234812443716603
12.234809511661867
12.234806580243587
12.234803649461607
12.2348007193158
12.234797789806027
12.234794860932155
12.234791932694035
12.234789005091542
12.234786078124538
12.234783151792865
12.234780226096406
12.234777301035013
12.234774376608549
12.234771452816874
12.234768529659869
12.23476560713737
12.234762685249255
12.234759763995374
12.234756843375605
12.234753923389796
12.234751004037824
12.234748085319536
12.2347451672348
12.234742249783487
12.234739332965448
12.234736416780555
12.23473350122866
12.234730586309643
12.234727672023341
12.234724758369628
12.234721845348377
12.234718932959453
12.23471602120269
12.234713110077982
12.23471019958517
12.234707289724128
12.234704380494717
12.234701471896807
12.234698563930245
12.2346956565949
12.234692749890643
12.234689843817335
12.234686938374827
12.234684033562992
12.234681129381697
12.234678225830796
12.234675322910158
12.234672420619638
12.23466951895911
12.234666617928431
12.234663717527468
12.234660817756087
12.234657918614129
12.234655020101492
12.234652122218012
12.23464922496357
12.234646328338016
12.23464343234122
12.23464053697304
12.23463764223335
12.23463474812201
12.234631854638886
12.234628961783823
12.234626069556706
12.234623177957387
12.234620286985741
12.23461739664163
12.234614506924897
12.234611617835435
12.234608729373077
12.234605841537727
12.234602954329214
12.234600067747408
12.234597181792182
12.2345942964634
12.23459141176093
12.234588527684611
12.234585644234336
12.23458276140996
12.234579879211344
12.23457699763835
12.234574116690851
12.234571236368696
12.234568356671762
12.234565477599912
12.234562599153008
12.234559721330916
12.234556844133504
12.234553967560618
12.234551091612142
12.234548216287942
12.234545341587868
12.234542467511787
12.234539594059576
12.234536721231082
12.234533849026187
12.234530977444741
12.234528106486623
12.23452523615168
12.234522366439796
12.234519497350828
12.234516628884636
12.234513761041086
12.234510893820037
12.234508027221377
12.234505161244941
12.234502295890616
12.234499431158262
12.234496567047744
12.234493703558918
12.234490840691647
12.234487978445815
12.23448511682127
12.234482255817891
12.234479395435535
12.234476535674064
12.234473676533353
12.23447081801325
12.234467960113644
12.234465102834385
12.234462246175333
12.234459390136378
12.234456534717355
12.234453679918145
12.234450825738612
12.234447972178625
12.234445119238044
12.234442266916732
12.234439415214567
12.2344365641314
12.234433713667103
12.23443086382155
12.234428014594597
12.2344251659861
12.234422317995943
12.234419470623976
12.234416623870093
12.234413777734119
12.234410932215953
12.234408087315451
12.234405243032477
12.234402399366886
12.23439955631856
12.23439671388736
12.234393872073154
12.234391030875802
12.234388190295174
12.234385350331136
12.23438251098356
12.234379672252299
12.23437683413723
12.23437399663822
12.234371159755126
12.234368323487823
12.234365487836167
12.23436265280003
12.234359818379287
12.234356984573802
12.234354151383416
12.234351318808034
12.234348486847498
12.234345655501674
12.234342824770444
12.234339994653666
12.234337165151196
12.234334336262917
12.234331507988689
12.234328680328382
12.234325853281863
12.234323026848989
12.234320201029632
12.234317375823666
12.234314551230945
12.234311727251361
12.23430890388475
12.234306081130983
12.234303258989943
12.234300437461501
12.234297616545504
12.234294796241818
12.23429197655033
12.2342891574709
12.234286339003388
12.234283521147672
12.234280703903599
12.23427788727106
12.234275071249908

12.234272255840013
12.234269441041246
12.234266626853476
12.234263813276558
12.234261000310378
12.234258187954781
12.234255376209655
12.234252565074854
12.23424975455025
12.234246944635707
12.234244135331112
12.234241326636301
12.234238518551166
12.234235711075565
12.234232904209366
12.234230097952436
12.234227292304642
12.234224487265863
12.234221682835948
12.234218879014787
12.234216075802225
12.234213273198142
12.234210471202411
12.234207669814888
12.234204869035448
12.234202068863956
12.23419926930028
12.234196470344298
12.23419367199585
12.23419087425484
12.234188077121114
12.234185280594552
12.234182484675015
12.23417968936237
12.23417689465648
12.234174100557222
12.234171307064472
12.234168514178087
12.234165721897932
12.234162930223889
12.234160139155811
12.234157348693572
12.234154558837053
12.234151769586106
12.234148980940608
12.234146192900427
12.234143405465423
12.234140618635472
12.234137832410447
12.234135046790207
12.234132261774624
12.234129477363567
12.234126693556915
12.234123910354528
12.234121127756264
12.234118345762
12.23411556437161
12.234112783584973
12.23411000340193
12.234107223822374
12.234104444846158
12.234101666473169
12.234098888703254
12.234096111536287
12.23409333497216
12.23409055901071
12.234087783651834
12.234085008895379
12.234082234741232
12.234079461189248
12.234076688239305
12.234073915891269
12.234071144145016
12.234068373000397
12.234065602457303
12.234062832515585
12.23406006317513
12.234057294435791
12.234054526297452
12.234051758759978
12.234048991823233
12.23404622548709
12.234043459751412
12.234040694616088
12.234037930080977
12.234035166145933
12.234032402810842
12.234029640075573
12.234026877940002
12.234024116403985
12.234021355467405
12.234018595130102
12.23401583539199
12.234013076252912
12.234010317712741
12.234007559771351
12.234004802428611
12.234002045684385
12.233999289538554
12.233996533990979
12.233993779041539
12.233991024690095
12.233988270936521
12.233985517780683
12.233982765222464
12.23398001326172
12.233977261898325
12.233974511132155
12.233971760963076
12.233969011390966
12.233966262415668
12.233963514037091
12.233960766255088
12.233958019069526
12.233955272480275
12.233952526487204
12.233949781090196
12.233947036289115
12.233944292083827
12.2339415484742
12.23393880546012
12.233936063041448
12.23393332121806
12.23393057998981
12.233927839356591
12.233925099318254
12.233922359874688
12.233919621025754
12.23391688277132
12.233914145111264
12.233911408045461
12.233908671573763
12.233905935696063
12.233903200412216
12.233900465722108
12.233897731625586
12.233894998122551
12.23389226521286
12.233889532896372
12.233886801172977
12.233884070042542
12.233881339504933
12.23387860956003
12.233875880207691
12.233873151447805
12.233870423280225
12.23386769570483
12.23386496872149
12.233862242330083
12.233859516530476
12.233856791322529
12.233854066706147
12.233851342681168
12.233848619247468
12.233845896404935
12.233843174153431
12.23384045249282
12.233837731422994
12.233835010943814
12.233832291055135
12.233829571756846
12.233826853048825
12.233824134930943
12.233821417403053
12.233818700465049
12.233815984116784
12.23381326835814
12.233810553188984
12.2338078386092
12.23380512461865
12.233802411217207
12.233799698404741
12.23379698618113
12.233794274546243
12.233791563499953
12.233788853042135
12.233786143172635
12.233783433891372
12.233780725198189
12.233778017092957
12.233775309575572
12.233772602645873
12.23376989630376
12.233767190549086
12.233764485381739
12.23376178080158
12.233759076808488
12.233756373402333
12.233753670582983
12.23375096835032
12.233748266704213
12.233745565644535
12.233742865171152
12.233740165283944
12.233737465982786
12.233734767267547
12.23373206913809
12.233729371594311
12.23372667463606
12.233723978263233
12.233721282475672
12.233718587273271
12.233715892655901
12.233713198623438
12.233710505175743
12.2337078123127
12.233705120034173
12.233702428340058
12.233699737230184
12.233697046704467
12.23369435676276
12.233691667404937
12.233688978630884
12.233686290440453
12.233683602833537
12.233680915809995
12.233678229369705
12.233675543512547
12.233672858238391
12.233670173547111
12.233667489438565
12.233664805912651
12.233662122969225
12.233659440608163
12.233656758829357
12.233654077632659
12.233651397017947
12.2336487169851
12.233646037533989
12.23364335866448
12.233640680376466
12.233638002669812
12.233635325544377
12.233632649000034
12.233629973036695
12.233627297654195
12.233624622852428
12.233621948631255
12.233619274990563
12.23361660193021
12.233613929450087
12.233611257550058
12.233608586229996
12.233605915489782
12.23360324532929
12.233600575748389
12.233597906746947
12.233595238324849
12.233592570481973
12.233589903218185
12.233587236533348
12.233584570427363
12.233581904900083
12.233579239951393
12.23357657558116
12.233573911789279
12.233571248575593
12.233568585939992
12.233565923882356
12.233563262402546
12.233560601500448
12.233557941175937
12.233555281428874
12.233552622259149
12.23354996366662
12.233547305651188
12.233544648212709
12.233541991351066
12.233539335066117
12.23353667935774
12.23353402422584
12.233531369670262
12.233528715690879
12.233526062287586
12.233523409460242
12.233520757208735
12.233518105532923
12.233515454432705
12.233512803907937
12.233510153958491
12.233507504584244
12.233504855785098
12.23350220756089
12.233499559911525
12.233496912836864
12.233494266336773
12.233491620411142
12.233488975059858
12.233486330282759
12.233483686079753
12.2334810424507
12.233478399395482
12.233475756913972
12.233473115006053
12.23347047367158
12.233467832910451
12.233465192722528
12.23346255310769
12.233459914065817
12.233457275596786
12.233454637700467
12.23345200037672
12.233449363625455
12.233446727446522
12.233444091839802
12.23344145680518
12.233438822342523
12.23343618845171
12.233433555132608
12.233430922385104
12.233428290209066
12.233425658604387
12.233423027570932
12.233420397108565
12.233417767217173
12.233415137896634
12.233412509146818
12.233409880967606
12.233407253358875
12.233404626320507
12.233401999852358
12.233399373954326
12.233396748626273
12.233394123868075
12.233391499679623
12.233388876060781
12.233386253011423
12.233383630531431
12.233381008620675
12.233378387279046
12.233375766506413
12.233373146302643
12.233370526667628
12.233367907601234
12.233365289103334
12.233362671173833
12.233360053812557
12.23335743701943
12.233354820794295
12.233352205137061
12.23334959004758
12.233346975525734
12.233344361571412
12.233341748184461
12.233339135364798
12.233336523112266
12.233333911426763
12.233331300308153
12.233328689756316
12.233326079771144
12.233323470352493
12.233320861500241
12.233318253214279
12.233315645494477
12.23331303834072
12.23331043175286
12.233307825730806
12.233305220274408
12.233302615383577
12.233300011058152
12.233297407298034
12.233294804103085
12.233292201473196
12.233289599408247
12.2332869979081
12.233284396972634
12.233281796601746
12.2332791967953
12.233276597553159
12.233273998875221
12.23327140076136
12.233268803211446
12.233266206225379
12.233263609803004
12.233261013944212
12.233258418648893
12.233255823916897
12.233253229748131
12.233250636142461
12.233248043099758
12.233245450619917
12.233242858702793
12.233240267348284
12.233237676556259
12.233235086326593
12.23323249665916
12.233229907553856
12.233227319010545
12.233224731029111
12.23322214360943
12.233219556751378
12.233216970454828
12.233214384719671
12.233211799545781
12.233209214933021
12.233206630881295
12.233204047390464
12.233201464460405
12.233198882091019
12.233196300282158
12.233193719033693
12.233191138345532
12.23318855821755
12.233185978649598
12.233183399641575
12.233180821193368
12.233178243304836
12.233175665975862
12.23317308920633
12.233170512996118
12.233167937345106
12.233165362253171
12.233162787720179
12.233160213746025
12.233157640330585
12.233155067473737
12.233152495175359
12.233149923435318
12.233147352253509
12.233144781629813
12.233142211564093
12.233139642056242
12.23313707310612
12.23313450471363
12.233131936878632
12.23312936960102
12.233126802880667
12.233124236717446
12.233121671111236
12.233119106061926
12.233116541569395
12.233113977633508
12.23311141425416
12.233108851431219
12.233106289164574
12.233103727454095
12.233101166299665
12.233098605701164
12.233096045658478
12.233093486171462
12.233090927240031
12.233088368864033
12.233085811043368
12.233083253777902
12.233080697067523
12.233078140912113
12.233075585311536
12.233073030265698
12.233070475774444
12.233067921837673
12.233065368455287
12.233062815627111
12.233060263353073
12.23305771163304
12.23305516046687
12.23305260985448
12.233050059795712
12.233047510290467
12.233044961338626
12.233042412940073
12.233039865094678
12.233037317802307
12.233034771062862
12.233032224876213
12.23302967924225

12.233027134160846
12.233024589631874
12.233022045655227
12.233019502230778
12.233016959358412
12.233014417038001
12.233011875269439
12.23300933405259
12.233006793387334
12.23300425327357
12.233001713711156
12.232999174699993
12.232996636239948
12.232994098330904
12.232991560972744
12.232989024165342
12.232986487908578
12.232983952202355
12.232981417046526
12.232978882440985
12.232976348385604
12.232973814880275
12.232971281924865
12.232968749519259
12.232966217663348
12.232963686357003
12.232961155600105
12.232958625392543
12.23295609573418
12.232953566624909
12.232951038064625
12.232948510053184
12.232945982590476
12.232943455676377
12.232940929310788
12.23293840349356
12.232935878224595
12.232933353503771
12.232930829330963
12.232928305706062
12.232925782628932
12.232923260099467
12.232920738117548
12.232918216683048
12.232915695795862
12.232913175455856
12.232910655662925
12.232908136416945
12.232905617717789
12.232903099565341
12.23290058195949
12.232898064900114
12.232895548387102
12.232893032420321
12.232890516999658
12.23288800212499
12.232885487796207
12.23288297401319
12.232880460775817
12.232877948083972
12.232875435937535
12.23287292433639
12.232870413280407
12.232867902769478
12.232865392803495
12.232862883382314
12.232860374505844
12.232857866173937
12.232855358386503
12.232852851143406
12.232850344444543
12.232847838289779
12.232845332679
12.232842827612101
12.232840323088949
12.232837819109436
12.232835315673434
12.23283281278084
12.23283031043152
12.23282780862535
12.23282530736225
12.232822806642066
12.232820306464689
12.23281780683
12.232815307737889
12.23281280918823
12.23281031118091
12.23280781371581
12.232805316792811
12.232802820411804
12.232800324572649
12.232797829275261
12.232795334519489
12.232792840305242
12.232790346632385
12.232787853500811
12.2327853609104
12.232782868861037
12.23278037735259
12.232777886384955
12.232775395958013
12.232772906071647
12.232770416725733
12.23276792792017
12.232765439654816
12.232762951929574
12.23276046474432
12.232757978098942
12.232755491993306
12.232753006427314
12.232750521400831
12.232748036913762
12.232745552965977
12.232743069557356
12.232740586687777
12.232738104357153
12.232735622565324
12.232733141312208
12.232730660597671
12.232728180421605
12.23272570078388
12.232723221684388
12.232720743123018
12.23271826509964
12.232715787614149
12.232713310666421
12.232710834256336
12.232708358383798
12.232705883048657
12.232703408250824
12.232700933990166
12.232698460266572
12.232695987079937
12.232693514430125
12.23269104231703
12.232688570740534
12.232686099700516
12.232683629196883
12.232681159229482
12.232678689798213
12.23267622090296
12.232673752543613
12.232671284720048
12.232668817432165
12.232666350679805
12.232663884462903
12.232661418781305
12.232658953634918
12.232656489023615
12.23265402494728
12.232651561405797
12.232649098399063
12.232646635926946
12.232644173989327
12.232641712586096
12.232639251717154
12.23263679138236
12.23263433158161
12.232631872314785
12.232629413581774
12.232626955382456
12.232624497716712
12.232622040584436
12.232619583985501
12.2326171279198
12.232614672387214
12.23261221738762
12.232609762920912
12.23260730898698
12.232604855585695
12.232602402716951
12.23259995038062
12.232597498576602
12.232595047304768
12.232592596565013
12.23259014635721
12.232587696681259
12.232585247537036
12.232582798924415
12.232580350843305
12.232577903293564
12.232575456275109
12.232573009787782
12.232570563831505
12.232568118406142
12.232565673511584
12.23256322914772
12.232560785314426
12.232558342011593
12.232555899239108
12.23255345699685
12.232551015284699
12.232548574102559
12.232546133450297
12.2325436933278
12.232541253734972
12.23253881467167
12.2325363761378
12.232533938133226
12.232531500657853
12.232529063711569
12.232526627294238
12.23252419140576
12.232521756046019
12.232519321214893
12.232516886912283
12.232514453138052
12.232512019892095
12.232509587174306
12.232507154984566
12.232504723322755
12.232502292188757
12.232499861582475
12.232497431503765
12.232495001952538
12.232492572928669
12.232490144432045
12.23248771646254
12.232485289020069
12.232482862104492
12.232480435715695
12.23247800985358
12.232475584518022
12.232473159708904
12.232470735426118
12.23246831166955
12.232465888439082
12.232463465734595
12.232461043555984
12.23245862190313
12.232456200775934
12.232453780174255
12.232451360097992
12.232448940547034
12.232446521521265
12.23244410302057
12.232441685044838
12.232439267593954
12.232436850667789
12.232434434266255
12.232432018389224
12.232429603036577
12.232427188208213
12.232424773904006
12.23242236012386
12.232419946867644
12.232417534135246
12.232415121926554
12.232412710241459
12.232410299079856
12.232407888441609
12.232405478326616
12.232403068734756
12.232400659665931
12.232398251120015
12.23239584309691
12.232393435596475
12.232391028618617
12.232388622163226
12.232386216230172
12.232383810819357
12.232381405930656
12.232379001563963
12.232376597719147
12.232374194396131
12.232371791594765
12.232369389314963
12.232366987556595
12.232364586319553
12.23236218560372
12.232359785408994
12.232357385735241
12.232354986582367
12.23235258795026
12.232350189838794
12.232347792247872
12.232345395177362
12.232342998627159
12.232340602597153
12.23233820708723
12.232335812097283
12.232333417627174
12.232331023676823
12.232328630246101
12.232326237334902
12.232323844943094
12.232321453070595
12.23231906171727
12.232316670883003
12.232314280567698
12.232311890771234
12.232309501493491
12.232307112734375
12.23230472449376
12.232302336771541
12.232299949567592
12.23229756288181
12.232295176714086
12.232292791064307
12.232290405932353
12.23228802131811
12.23228563722148
12.232283253642336
12.232280870580576
12.232278488036068
12.232276106008733
12.232273724498437
12.23227134350506
12.232268963028506
12.232266583068665
12.232264203625414
12.232261824698643
12.232259446288243
12.2322570683941
12.232254691016104
12.23225231415414
12.232249937808092
12.232247561977857
12.232245186663324
12.232242811864372
12.232240437580895
12.232238063812778
12.232235690559909
12.232233317822178
12.232230945599476
12.232228573891689
12.232226202698696
12.232223832020402
12.232221461856689
12.23221909220743
12.232216723072533
12.23221435445188
12.232211986345355
12.232209618752862
12.232207251674268
12.232204885109477
12.232202519058369
12.232200153520838
12.232197788496764
12.232195423986045
12.232193059988571
12.232190696504215
12.232188333532886
12.232185971074463
12.232183609128821
12.232181247695873
12.232178886775497
12.232176526367578
12.23217416647201
12.232171807088678
12.232169448217476
12.232167089858285
12.232164732011004
12.232162374675509
12.23216001785171
12.232157661539473
12.232155305738686
12.232152950449263
12.23215059567108
12.23214824140402
12.232145887647967
12.232143534402832
12.232141181668485
12.232138829444818
12.23213647773173
12.232134126529106
12.232131775836828
12.232129425654787
12.232127075982886
12.232124726820999
12.232122378169016
12.23212003002683
12.232117682394332
12.23211533527141
12.232112988657963
12.23211064255386
12.232108296958994
12.232105951873278
12.232103607296573
12.232101263228794
12.232098919669804
12.23209657661951
12.23209423407779
12.23209189204456
12.232089550519678
12.232087209503046
12.232084868994553
12.232082528994093
12.232080189501552
12.232077850516813
12.232075512039776
12.232073174070337
12.232070836608367
12.232068499653767
12.232066163206419
12.232063827266229
12.232061491833074
12.232059156906846
12.232056822487438
12.232054488574729
12.232052155168628
12.232049822269014
12.232047489875765
12.232045157988791
12.232042826607984
12.23204049573321
12.232038165364385
12.232035835501394
12.232033506144106
12.232031177292432
12.232028848946257
12.232026521105475
12.232024193769972
12.232021866939633
12.232019540614354
12.23201721479403
12.232014889478549
12.2320125646678
12.232010240361667
12.23200791656005
12.232005593262832
12.232003270469914
12.232000948181167
12.231998626396512
12.231996305115816
12.231993984338962
12.231991664065868
12.2319893442964
12.23198702503048
12.231984706267959
12.23198238800875
12.23198007025274
12.23197775299983
12.231975436249888
12.231973120002827
12.231970804258527
12.231968489016879
12.231966174277776
12.23196386004111
12.231961546306762
12.231959233074646
12.231956920344631
12.231954608116615
12.231952296390487
12.231949985166139
12.231947674443463
12.231945364222359
12.231943054502704
12.231940745284405
12.231938436567324
12.23193612835138
12.231933820636465
12.231931513422444
12.231929206709227
12.231926900496711
12.231924594784779
12.231922289573324
12.23191998486223
12.2319176806514
12.231915376940716
12.231913073730071
12.231910771019374
12.231908468808484
12.23190616709732
12.23190386588575
12.231901565173688
12.23189926496102
12.231896965247623
12.23189466603341
12.231892367318263
12.231890069102064
12.23188777138472
12.231885474166116
12.231883177446145
12.231880881224694
12.231878585501656
12.231876290276931
12.231873995550409
12.231871701321975
12.231869407591518
12.231867114358936
12.231864821624123
12.23186252938697
12.231860237647366
12.231857946405219
12.231855655660388
12.23185336541279
12.231851075662311
12.231848786408847
12.231846497652272
12.231844209392504
12.231841921629417
12.231839634362911
12.231837347592885
12.231835061319222
12.231832775541799
12.23183049026054
12.231828205475312
12.231825921186026
12.231823637392557
12.231821354094814
12.231819071292678
12.231816788986043
12.231814507174803
12.231812225858846
12.231809945038076
12.231807664712372
12.231805384881637
12.23180310554576
12.231800826704633
12.231798548358146
12.2317962705062
12.231793993148681
12.23179171628547
12.231789439916486
12.231787164041604
12.231784888660721
12.231782613773735
12.231780339380524
12.231778065480993
12.231775792075032
12.231773519162536
12.231771246743396
12.231768974817498
12.231766703384757
12.231764432445035
12.231762161998235
12.231759892044272
12.231757622583018
12.231755353614364
12.23175308513822
12.23175081715446
12.231748549662987
12.231746282663691
12.231744016156473
12.23174175014122
12.231739484617819
12.231737219586174
12.231734955046168
12.231732690997706
12.231730427440679
12.231728164374964
12.231725901800484
12.231723639717103
12.231721378124735
12.231719117023259
12.231716856412579
12.231714596292582
12.231712336663158
12.231710077524214
12.231707818875632
12.231705560717316
12.231703303049146
12.231701045871027
12.231698789182845
12.231696532984493
12.231694277275874
12.231692022056869
12.231689767327392
12.231687513087307

12.231685259336533
12.231683006074954
12.231680753302474
12.231678501018967
12.231676249224343
12.231673997918483
12.231671747101293
12.23166949677267
12.231667246932487
12.231664997580646
12.231662748717058
12.231660500341606
12.231658252454181
12.23165600505467
12.23165375814299
12.231651511719017
12.231649265782647
12.231647020333783
12.231644775372306
12.231642530898116
12.231640286911116
12.23163804341119
12.231635800398239
12.231633557872144
12.231631315832809
12.231629074280129
12.231626833213987
12.231624592634313
12.231622352540954
12.23162011293384
12.231617873812839
12.231615635177876
12.231613397028818
12.231611159365563
12.23160892218801
12.23160668549607
12.231604449289609
12.231602213568545
12.231599978332754
12.231597743582148
12.23159550931661
12.231593275536047
12.231591042240328
12.231588809429375
12.231586577103071
12.23158434526131
12.231582113903992
12.231579883031003
12.231577652642255
12.231575422737626
12.231573193317015
12.23157096438032
12.23156873592743
12.231566507958245
12.231564280472673
12.23156205347058
12.23155982695189
12.231557600916465
12.231555375364232
12.231553150295083
12.231550925708884
12.231548701605558
12.231546477984997
12.231544254847082
12.23154203219173
12.231539810018814
12.231537588328244
12.231535367119909
12.231533146393696
12.231530926149532
12.231528706387275
12.231526487106843
12.231524268308117
12.231522049991003
12.231519832155392
12.23151761480118
12.231515397928268
12.231513181536542
12.231510965625906
12.231508750196248
12.231506535247467
12.231504320779463
12.23150210679212
12.231499893285354
12.231497680259036
12.23149546771308
12.231493255647377
12.231491044061809
12.231488832956291
12.231486622330706
12.231484412184976
12.231482202518956
12.231479993332568
12.231477784625703
12.231475576398257
12.231473368650121
12.2314711613812
12.231468954591382
12.231466748280571
12.231464542448654
12.23146233709552
12.23146013222109
12.231457927825241
12.231455723907874
12.231453520468886
12.231451317508164
12.23144911502563
12.231446913021152
12.231444711494648
12.231442510445984
12.231440309875083
12.231438109781847
12.231435910166145
12.231433711027885
12.231431512366965
12.231429314183293
12.231427116476757
12.231424919247244
12.231422722494655
12.231420526218892
12.23141833041985
12.231416135097419
12.231413940251507
12.231411745882005
12.231409551988802
12.231407358571804
12.231405165630902
12.231402973165993
12.23140078117699
12.231398589663755
12.231396398626234
12.231394208064275
12.231392017977793
12.23138982836669
12.231387639230867
12.23138545057021
12.231383262384616
12.231381074673983
12.231378887438224
12.231376700677206
12.23137451439085
12.231372328579047
12.231370143241689
12.231367958378675
12.231365773989907
12.231363590075276
12.231361406634672
12.231359223668013
12.23135704117518
12.231354859156076
12.231352677610596
12.231350496538633
12.23134831594009
12.231346135814873
12.231343956162853
12.23134177698396
12.23133959827807
12.231337420045085
12.231335242284903
12.231333064997413
12.23133088818254
12.231328711840142
12.231326535970142
12.231324360572437
12.231322185646915
12.231320011193482
12.231317837212025
12.231315663702444
12.231313490664656
12.23131131809853
12.231309146003982
12.231306974380907
12.231304803229188
12.231302632548747
12.231300462339465
12.231298292601235
12.23129612333398
12.231293954537572
12.231291786211923
12.231289618356916
12.231287450972472
12.231285284058465
12.231283117614819
12.231280951641397
12.231278786138123
12.231276621104898
12.231274456541597
12.23127229244815
12.231270128824416
12.23126796567031
12.231265802985755
12.231263640770617
12.231261479024804
12.231259317748213
12.231257156940744
12.231254996602306
12.231252836732777
12.231250677332069
12.23124851840007
12.231246359936684
12.231244201941815
12.231242044415348
12.231239887357198
12.23123773076724
12.2312355746454
12.231233418991563
12.231231263805617
12.231229109087474
12.231226954837036
12.231224801054186
12.231222647738843
12.231220494890879
12.231218342510218
12.231216190596744
12.231214039150357
12.231211888170963
12.231209737658448
12.231207587612724
12.231205438033689
12.231203288921229
12.23120114027525
12.231198992095658
12.23119684438234
12.231194697135198
12.231192550354132
12.231190404039046
12.231188258189823
12.231186112806382
12.231183967888615
12.23118182343642
12.231179679449687
12.231177535928326
12.231175392872244
12.231173250281318
12.231171108155449
12.231168966494556
12.231166825298526
12.231164684567254
12.231162544300652
12.231160404498599
12.231158265161014
12.231156126287784
12.23115398787882
12.23115184993401
12.231149712453258
12.231147575436468
12.231145438883523
12.231143302794335
12.231141167168802
12.231139032006825
12.231136897308305
12.231134763073124
12.23113262930122
12.231130495992439
12.231128363146722
12.231126230763952
12.231124098844033
12.23112196738687
12.231119836392345
12.231117705860367
12.231115575790845
12.231113446183674
12.231111317038737
12.231109188355962
12.231107060135225
12.231104932376434
12.231102805079491
12.231100678244292
12.231098551870735
12.231096425958732
12.231094300508168
12.231092175518947
12.231090050990977
12.231087926924152
12.231085803318368
12.231083680173526
12.231081557489533
12.231079435266276
12.231077313503675
12.23107519220162
12.231073071359997
12.23107095097872
12.231068831057685
12.23106671159681
12.23106459259597
12.231062474055074
12.23106035597403
12.231058238352723
12.231056121191058
12.231054004488946
12.231051888246288
12.231049772462965
12.231047657138891
12.231045542273964
12.231043427868084
12.231041313921144
12.231039200433061
12.231037087403717
12.231034974833031
12.23103286272089
12.231030751067198
12.231028639871862
12.231026529134764
12.231024418855828
12.231022309034943
12.231020199672002
12.231018090766923
12.231015982319585
12.231013874329909
12.23101176679779
12.23100965972313
12.23100755310582
12.231005446945762
12.231003341242861
12.231001235997024
12.230999131208149
12.230997026876128
12.230994923000868
12.230992819582271
12.23099071662023
12.230988614114665
12.230986512065451
12.230984410472509
12.230982309335733
12.23098020865503
12.230978108430277
12.230976008661417
12.23097390934831
12.230971810490871
12.230969712089012
12.230967614142621
12.230965516651617
12.230963419615877
12.230961323035322
12.230959226909832
12.230957131239336
12.230955036023708
12.230952941262878
12.230950846956711
12.230948753105142
12.23094665970805
12.230944566765352
12.230942474276937
12.230940382242718
12.23093829066258
12.230936199536439
12.2309341088642
12.230932018645746
12.230929928880991
12.230927839569835
12.230925750712178
12.230923662307928
12.230921574356971
12.230919486859232
12.230917399814588
12.230915313222955
12.230913227084235
12.23091114139832
12.23090905616513
12.230906971384544
12.230904887056473
12.230902803180827
12.230900719757502
12.230898636786394
12.230896554267407
12.230894472200447
12.23089239058542
12.230890309422213
12.23088822871075
12.230886148450908
12.230884068642606
12.23088198928575
12.23087991038022
12.230877831925936
12.230875753922792
12.230873676370692
12.230871599269543
12.230869522619242
12.2308674464197
12.2308653706708
12.230863295372465
12.230861220524588
12.230859146127065
12.230857072179809
12.230854998682723
12.230852925635697
12.230850853038639
12.230848780891451
12.230846709194042
12.23084463794631
12.230842567148148
12.230840496799477
12.230838426900185
12.230836357450183
12.230834288449358
12.230832219897648
12.230830151794912
12.230828084141079
12.230826016936046
12.230823950179708
12.230821883871972
12.230819818012748
12.230817752601931
12.230815687639426
12.23081362312514
12.230811559058964
12.230809495440816
12.230807432270588
12.23080536954819
12.230803307273503
12.230801245446466
12.230799184066942
12.230797123134876
12.230795062650142
12.230793002612646
12.230790943022296
12.230788883878997
12.23078682518264
12.230784766933162
12.230782709130425
12.230780651774346
12.230778594864837
12.230776538401782
12.230774482385108
12.230772426814706
12.23077037169047
12.230768317012314
12.230766262780152
12.23076420899387
12.230762155653379
12.230760102758577
12.230758050309365
12.230755998305654
12.230753946747344
12.23075189563434
12.23074984496654
12.230747794743863
12.230745744966192
12.230743695633437
12.23074164674551
12.230739598302304
12.230737550303733
12.230735502749681
12.230733455640076
12.230731408974805
12.230729362753772
12.230727316976894
12.230725271644063
12.230723226755183
12.230721182310164
12.230719138308908
12.230717094751308
12.230715051637285
12.230713008966726
12.23071096673954
12.23070892495564
12.23070688361492
12.23070484271729
12.230702802262645
12.2307007622509
12.230698722681959
12.230696683555706
12.230694644872068
12.230692606630928
12.23069056883221
12.230688531475817
12.230686494561633
12.230684458089591
12.230682422059571
12.230680386471484
12.23067835132523
12.230676316620722
12.230674282357866
12.230672248536552
12.230670215156694
12.230668182218194
12.230666149720964
12.230664117664894
12.230662086049902
12.230660054875878
12.230658024142734
12.23065599385039
12.230653963998705
12.23065193458764
12.230649905617057
12.23064787708688
12.230645848997009
12.230643821347346
12.230641794137805
12.23063976736828
12.230637741038672
12.2306357151489
12.230633689698852
12.230631664688449
12.230629640117591
12.230627615986167
12.230625592294107
12.230623569041295
12.230621546227647
12.230619523853065
12.230617501917447

12.230615480420708
12.230613459362743
12.230611438743464
12.23060941856278
12.230607398820592
12.230605379516792
12.230603360651298
12.230601342224015
12.230599324234834
12.230597306683675
12.230595289570447
12.23059327289505
12.23059125665737
12.230589240857338
12.230587225494846
12.230585210569798
12.230583196082108
12.230581182031674
12.230579168418412
12.230577155242202
12.230575142502975
12.23057313020062
12.230571118335053
12.230569106906165
12.23056709591388
12.230565085358096
12.230563075238708
12.230561065555637
12.230559056308772
12.230557047498037
12.230555039123319
12.230553031184536
12.230551023681592
12.230549016614376
12.230547009982828
12.230545003786812
12.23054299802627
12.230540992701084
12.230538987811167
12.230536983356425
12.23053497933676
12.230532975752082
12.230530972602294
12.23052896988731
12.23052696760701
12.230524965761333
12.230522964350175
12.230520963373422
12.230518962830997
12.230516962722803
12.230514963048746
12.230512963808733
12.230510965002665
12.23050896663045
12.230506968692007
12.230504971187216
12.230502974116
12.230500977478252
12.230498981273898
12.230496985502834
12.230494990164955
12.230492995260184
12.230491000788419
12.230489006749565
12.230487013143529
12.230485019970219
12.230483027229539
12.230481034921397
12.230479043045703
12.23047705160235
12.230475060591257
12.230473070012328
12.230471079865465
12.230469090150569
12.230467100867557
12.230465112016338
12.230463123596804
12.230461135608872
12.230459148052443
12.230457160927429
12.230455174233729
12.230453187971248
12.23045120213992
12.230449216739613
12.230447231770244
12.230445247231735
12.230443263123972
12.230441279446891
12.230439296200364
12.23043731338432
12.230435330998654
12.23043334904327
12.230431367518108
12.230429386423024
12.230427405757958
12.230425425522803
12.230423445717479
12.230421466341873
12.230419487395904
12.230417508879487
12.230415530792518
12.23041355313489
12.230411575906542
12.230409599107361
12.230407622737248
12.230405646796124
12.230403671283891
12.230401696200456
12.23039972154572
12.230397747319602
12.230395773522002
12.230393800152823
12.230391827211973
12.230389854699363
12.230387882614897
12.230385910958491
12.23038393973005
12.23038196892946
12.230379998556657
12.230378028611522
12.230376059093997
12.230374090003954
12.230372121341317
12.230370153105982
12.230368185297879
12.23036621791689
12.23036425096293
12.230362284435927
12.230360318335759
12.23035835266234
12.230356387415588
12.230354422595408
12.2303524582017
12.230350494234381
12.230348530693346
12.230346567578513
12.230344604889783
12.230342642627063
12.230340680790281
12.230338719379313
12.230336758394085
12.230334797834509
12.230332837700475
12.230330877991891
12.230328918708695
12.230326959850755
12.230325001418008
12.230323043410346
12.230321085827676
12.23031912866992
12.23031717193698
12.230315215628751
12.230313259745156
12.230311304286092
12.230309349251481
12.230307394641216
12.230305440455211
12.230303486693384
12.230301533355608
12.230299580441832
12.230297627951954
12.230295675885866
12.230293724243486
12.230291773024728
12.23028982222949
12.230287871857678
12.230285921909214
12.230283972383997
12.230282023281937
12.230280074602934
12.230278126346914
12.230276178513767
12.230274231103405
12.230272284115749
12.230270337550692
12.230268391408151
12.23026644568803
12.230264500390241
12.230262555514692
12.230260611061293
12.230258667029938
12.230256723420553
12.230254780233052
12.23025283746731
12.230250895123268
12.23024895320082
12.230247011699882
12.230245070620354
12.230243129962151
12.230241189725175
12.230239249909344
12.230237310514564
12.230235371540731
12.23023343298777
12.230231494855586
12.230229557144082
12.230227619853165
12.230225682982756
12.230223746532758
12.23022181050307
12.230219874893612
12.230217939704291
12.230216004935015
12.230214070585685
12.230212136656215
12.230210203146527
12.230208270056508
12.230206337386086
12.230204405135165
12.230202473303642
12.230200541891422
12.230198610898452
12.230196680324603
12.230194750169801
12.230192820433942
12.230190891116955
12.230188962218723
12.23018703373918
12.23018510567822
12.230183178035757
12.230181250811704
12.230179324005963
12.230177397618439
12.230175471649064
12.230173546097724
12.23017162096434
12.23016969624881
12.230167771951052
12.230165848070977
12.230163924608497
12.230162001563501
12.230160078935931
12.230158156725661
12.23015623493262
12.230154313556728
12.230152392597862
12.230150472055975
12.230148551930931
12.230146632222679
12.2301447129311
12.230142794056118
12.230140875597645
12.230138957555573
12.230137039929827
12.230135122720313
12.230133205926938
12.23013128954962
12.230129373588257
12.230127458042764
12.230125542913047
12.230123628199035
12.230121713900614
12.230119800017695
12.23011788655021
12.230115973498043
12.230114060861117
12.23011214863934
12.230110236832626
12.230108325440872
12.230106414464007
12.230104503901925
12.230102593754541
12.230100684021766
12.230098774703503
12.230096865799672
12.230094957310184
12.230093049234942
12.23009114157386
12.230089234326845
12.230087327493804
12.230085421074664
12.230083515069316
12.230081609477676
12.23007970429965
12.230077799535165
12.230075895184113
12.230073991246412
12.230072087721977
12.23007018461071
12.23006828191251
12.230066379627319
12.230064477755025
12.23006257629554
12.230060675248781
12.23005877461465
12.230056874393071
12.230054974583938
12.230053075187167
12.23005117620267
12.230049277630373
12.230047379470165
12.230045481721953
12.230043584385662
12.230041687461204
12.230039790948481
12.230037894847412
12.230035999157892
12.230034103879843
12.230032209013181
12.230030314557803
12.230028420513635
12.230026526880575
12.230024633658543
12.230022740847444
12.23002084844719
12.230018956457684
12.230017064878856
12.2300151737106
12.230013282952827
12.230011392605467
12.230009502668402
12.230007613141572
12.23000572402487
12.230003835318215
12.230001947021506
12.230000059134664
12.229998171657602
12.229996284590229
12.229994397932439
12.229992511684177
12.229990625845323
12.229988740415807
12.22998685539553
12.229984970784411
12.229983086582358
12.229981202789283
12.229979319405082
12.22997743642969
12.229975553863005
12.229973671704949
12.229971789955417
12.229969908614333
12.229968027681606
12.229966147157132
12.229964267040856
12.229962387332662
12.229960508032471
12.22995862914018
12.229956750655722
12.229954872579002
12.22995299490993
12.229951117648401
12.22994924079436
12.229947364347689
12.229945488308314
12.229943612676147
12.229941737451092
12.229939862633074
12.229937988221982
12.22993611421774
12.229934240620272
12.229932367429479
12.229930494645263
12.22992862226754
12.229926750296244
12.229924878731259
12.229923007572495
12.2299211368199
12.229919266473352
12.22991739653278
12.229915526998075
12.229913657869169
12.229911789145964
12.229909920828387
12.22990805291632
12.229906185409707
12.229904318308447
12.229902451612443
12.229900585321616
12.229898719435885
12.22989685395515
12.22989498887932
12.229893124208319
12.229891259942065
12.229889396080452
12.2298875326234
12.229885669570821
12.22988380692262
12.229881944678725
12.229880082839038
12.22987822140348
12.229876360371954
12.22987449974437
12.229872639520643
12.229870779700688
12.229868920284428
12.229867061271753
12.229865202662594
12.229863344456847
12.229861486654439
12.229859629255277
12.229857772259269
12.229855915666334
12.229854059476388
12.229852203689326
12.22985034830508
12.229848493323557
12.229846638744656
12.229844784568312
12.229842930794424
12.229841077422906
12.229839224453679
12.22983737188664
12.229835519721714
12.229833667958806
12.229831816597834
12.22982996563872
12.229828115081352
12.229826264925661
12.229824415171553
12.22982256581896
12.229820716867767
12.229818868317889
12.229817020169266
12.22981517242179
12.229813325075368
12.229811478129923
12.229809631585377
12.22980778544162
12.229805939698588
12.229804094356178
12.22980224941432
12.229800404872897
12.22979856073185
12.229796716991084
12.229794873650519
12.229793030710049
12.229791188169601
12.229789346029094
12.229787504288431
12.229785662947522
12.22978382200629
12.229781981464646
12.229780141322491
12.229778301579755
12.22977646223634
12.229774623292167
12.229772784747148
12.229770946601185
12.229769108854216
12.229767271506129
12.229765434556855
12.229763598006295
12.229761761854377
12.229759926100998
12.229758090746076
12.229756255789521
12.229754421231258
12.229752587071198
12.229750753309254
12.22974891994534
12.229747086979353
12.229745254411226
12.229743422240881
12.229741590468207
12.229739759093118
12.229737928115552
12.22973609753541
12.229734267352606
12.22973243756704
12.229730608178649
12.229728779187328
12.22972695059301
12.229725122395582
12.229723294594988
12.229721467191114
12.229719640183898
12.22971781357324
12.229715987359056
12.229714161541262
12.229712336119777
12.229710511094497
12.22970868646535
12.229706862232256
12.229705038395108
12.22970321495385
12.229701391908367
12.229699569258585
12.22969774700442
12.229695925145785
12.2296941036826
12.229692282614764
12.229690461942205
12.229688641664826
12.229686821782556
12.229685002295291
12.22968318320296
12.229681364505472
12.229679546202739
12.229677728294682
12.229675910781204
12.22967409366224
12.229672276937674
12.229670460607448
12.229668644671463
12.229666829129634
12.229665013981876
12.229663199228105
12.229661384868239
12.229659570902179
12.229657757329868
12.22965594415118
12.229654131366065
12.229652318974416
12.229650506976162
12.229648695371212
12.22964688415948
12.229645073340876
12.229643262915328
12.22964145288273
12.229639643243011
12.229637833996076
12.229636025141865
12.22963421668026
12.229632408611195
12.229630600934584
12.229628793650331
12.22962698675837
12.2296251802586
12.22962337415093
12.229621568435281
12.229619763111588
12.229617958179738
12.22961615363966
12.229614349491268
12.229612545734474
12.229610742369188
12.229608939395346
12.229607136812835
12.229605334621592
12.229603532821518
12.229601731412535
12.22959993039456
12.229598129767504
12.229596329531274
12.229594529685802
12.229592730230987
12.229590931166756
12.229589132493022
12.229587334209711
12.229585536316703
12.229583738813941
12.22958194170135
12.229580144978817

12.229578348646283
12.22957655270364
12.229574757150823
12.229572961987744
12.2295711672143
12.229569372830431
12.22956757883603
12.229565785231033
12.22956399201535
12.229562199188896
12.229560406751563
12.2295586147033
12.229556823044017
12.229555031773618
12.229553240892006
12.229551450399128
12.229549660294893
12.229547870579191
12.22954608125197
12.229544292313122
12.229542503762575
12.22954071560023
12.229538927826036
12.229537140439877
12.229535353441673
12.229533566831341
12.229531780608816
12.229529994773996
12.229528209326789
12.229526424267135
12.229524639594931
12.229522855310101
12.229521071412549
12.229519287902198
12.22951750477899
12.229515722042802
12.229513939693563
12.229512157731193
12.229510376155611
12.229508594966724
12.229506814164445
12.22950503374871
12.229503253719416
12.22950147407649
12.229499694819848
12.229497915949395
12.229496137465048
12.229494359366747
12.229492581654368
12.229490804327867
12.229489027387139
12.229487250832094
12.229485474662672
12.229483698878775
12.229481923480312
12.229480148467218
12.229478373839383
12.22947659959675
12.229474825739215
12.229473052266725
12.229471279179162
12.229469506476448
12.229467734158519
12.229465962225277
12.229464190676637
12.229462419512531
12.229460648732852
12.229458878337528
12.229457108326478
12.229455338699625
12.229453569456876
12.22945180059815
12.229450032123356
12.229448264032426
12.229446496325263
12.229444729001788
12.229442962061917
12.229441195505574
12.229439429332674
12.229437663543122
12.229435898136835
12.229434133113758
12.229432368473773
12.229430604216812
12.229428840342795
12.229427076851637
12.22942531374325
12.229423551017543
12.229421788674458
12.22942002671389
12.229418265135767
12.229416503940003
12.229414743126513
12.229412982695221
12.229411222646027
12.22940946297887
12.229407703693655
12.229405944790296
12.229404186268717
12.229402428128836
12.22940067037057
12.229398912993824
12.229397155998528
12.229395399384597
12.229393643151948
12.229391887300492
12.229390131830153
12.229388376740857
12.229386622032495
12.229384867705008
12.229383113758303
12.229381360192304
12.229379607006926
12.229377854202081
12.229376101777692
12.229374349733671
12.229372598069943
12.229370846786425
12.229369095883019
12.229367345359663
12.229365595216267
12.229363845452744
12.22936209606902
12.229360347064995
12.229358598440612
12.229356850195769
12.229355102330386
12.229353354844397
12.229351607737694
12.22934986101022
12.22934811466188
12.229346368692587
12.229344623102268
12.229342877890833
12.229341133058199
12.229339388604306
12.229337644529048
12.229335900832343
12.229334157514126
12.229332414574284
12.229330672012768
12.229328929829482
12.229327188024344
12.229325446597278
12.229323705548191
12.229321964877
12.229320224583635
12.229318484668008
12.229316745130044
12.229315005969646
12.22931326718674
12.22931152878124
12.229309790753083
12.229308053102162
12.229306315828419
12.229304578931744
12.229302842412078
12.22930110626932
12.22929937050341
12.22929763511425
12.22929590010177
12.229294165465875
12.229292431206497
12.229290697323542
12.229288963816943
12.229287230686596
12.229285497932436
12.229283765554387
12.229282033552353
12.229280301926254
12.229278570676012
12.229276839801543
12.229275109302778
12.229273379179617
12.22927164943199
12.229269920059807
12.229268191063001
12.22926646244148
12.22926473419515
12.229263006323952
12.229261278827801
12.229259551706607
12.229257824960293
12.229256098588777
12.22925437259198
12.229252646969801
12.229250921722198
12.229249196849048
12.229247472350298
12.229245748225868
12.229244024475658
12.22924230109959
12.22924057809759
12.229238855469577
12.229237133215463
12.229235411335184
12.229233689828643
12.229231968695757
12.22923024793644
12.22922852755064
12.229226807538247
12.229225087899199
12.229223368633393
12.22922164974077
12.22921993122124
12.229218213074715
12.229216495301126
12.229214777900394
12.229213060872414
12.229211344217132
12.229209627934456
12.229207912024314
12.229206196486613
12.229204481321263
12.229202766528207
12.229201052107367
12.229199338058631
12.22919762438195
12.229195911077214
12.229194198144368
12.22919248558332
12.229190773393993
12.229189061576292
12.229187350130163
12.22918563905551
12.22918392835224
12.229182218020297
12.22918050805959
12.229178798470029
12.229177089251541
12.229175380404042
12.229173671927468
12.229171963821718
12.229170256086729
12.229168548722406
12.229166841728661
12.229165135105443
12.229163428852646
12.2291617229702
12.229160017458023
12.22915831231604
12.229156607544153
12.229154903142309
12.229153199110405
12.229151495448365
12.22914979215611
12.229148089233567
12.22914638668065
12.229144684497275
12.229142982683365
12.229141281238856
12.229139580163633
12.229137879457644
12.229136179120804
12.22913447915302
12.229132779554227
12.229131080324343
12.229129381463283
12.229127682970963
12.229125984847299
12.229124287092235
12.229122589705666
12.229120892687522
12.229119196037733
12.229117499756194
12.229115803842857
12.22911410829761
12.22911241312039
12.229110718311123
12.229109023869709
12.229107329796088
12.229105636090175
12.229103942751893
12.229102249781146
12.229100557177862
12.22909886494198
12.229097173073384
12.229095481572026
12.229093790437819
12.229092099670673
12.229090409270523
12.229088719237275
12.22908702957086
12.229085340271183
12.229083651338177
12.229081962771767
12.22908027457187
12.229078586738405
12.229076899271284
12.229075212170438
12.22907352543578
12.22907183906724
12.229070153064725
12.229068467428174
12.229066782157489
12.229065097252594
12.229063412713433
12.229061728539893
12.229060044731911
12.229058361289404
12.229056678212306
12.229054995500517
12.229053313153969
12.229051631172586
12.22904994955628
12.229048268304973
12.229046587418594
12.22904490689705
12.229043226740277
12.229041546948192
12.229039867520694
12.229038188457743
12.22903650975923
12.229034831425087
12.229033153455235
12.22903147584959
12.229029798608076
12.229028121730613
12.229026445217121
12.229024769067527
12.229023093281743
12.229021417859698
12.229019742801308
12.229018068106507
12.229016393775193
12.229014719807301
12.229013046202752
12.229011372961471
12.229009700083363
12.229008027568366
12.229006355416395
12.229004683627371
12.22900301220121
12.229001341137844
12.228999670437181
12.228998000099164
12.22899633012369
12.22899466051069
12.22899299126009
12.228991322371812
12.22898965384577
12.228987985681892
12.228986317880084
12.228984650440278
12.228982983362402
12.228981316646376
12.228979650292107
12.228977984299533
12.228976318668572
12.22897465339914
12.228972988491158
12.228971323944556
12.228969659759242
12.228967995935152
12.228966332472197
12.22896466937031
12.228963006629401
12.228961344249399
12.228959682230222
12.228958020571794
12.22895635927403
12.228954698336866
12.22895303776021
12.228951377543982
12.228949717688112
12.228948058192525
12.22894639905714
12.228944740281865
12.228943081866646
12.228941423811396
12.228939766116019
12.22893810878046
12.228936451804625
12.228934795188453
12.228933138931845
12.228931483034742
12.228929827497053
12.228928172318707
12.228926517499625
12.228924863039728
12.228923208938935
12.228921555197163
12.22891990181436
12.228918248790414
12.22891659612527
12.228914943818845
12.228913291871057
12.22891164028182
12.22890998905109
12.22890833817875
12.228906687664745
12.228905037508984
12.228903387711402
12.228901738271901
12.228900089190429
12.228898440466892
12.22889679210122
12.228895144093325
12.228893496443147
12.228891849150587
12.22889020221559
12.228888555638061
12.228886909417923
12.228885263555105
12.228883618049526
12.228881972901121
12.228880328109788
12.228878683675468
12.228877039598085
12.228875395877544
12.228873752513783
12.228872109506723
12.228870466856279
12.228868824562388
12.22886718262495
12.228865541043906
12.22886389981918
12.228862258950675
12.228860618438333
12.228858978282084
12.228857338481816
12.228855699037474
12.22885405994899
12.228852421216274
12.22885078283925
12.228849144817836
12.22884750715197
12.22884586984156
12.228844232886534
12.22884259628682
12.228840960042328
12.228839324152995
12.22883768861873
12.228836053439476
12.228834418615138
12.228832784145636
12.228831150030908
12.228829516270874
12.22882788286545
12.228826249814563
12.228824617118143
12.228822984776095
12.228821352788353
12.228819721154851
12.228818089875492
12.228816458950211
12.228814828378916
12.22881319816156
12.22881156829804
12.22880993878829
12.228808309632232
12.22880668082978
12.228805052380878
12.228803424285429
12.228801796543364
12.228800169154606
12.228798542119087
12.228796915436712
12.22879528910742
12.228793663131118
12.228792037507752
12.228790412237236
12.228788787319484
12.228787162754426
12.228785538541985
12.228783914682083
12.228782291174651
12.228780668019605
12.228779045216868
12.228777422766372
12.228775800668028
12.228774178921778
12.22877255752753
12.228770936485203
12.22876931579473
12.228767695456037
12.228766075469037
12.228764455833671
12.228762836549846
12.228761217617498
12.228759599036547
12.228757980806906
12.228756362928513
12.228754745401284
12.228753128225149
12.228751511400027
12.228749894925834
12.22874827880251
12.228746663029971
12.228745047608136
12.22874343253694
12.228741817816305
12.22874020344614
12.228738589426374
12.228736975756949
12.228735362437778
12.228733749468779
12.228732136849885
12.228730524581012
12.228728912662087
12.228727301093036
12.228725689873782
12.228724079004255
12.228722468484351
12.228720858314043
12.228719248493201
12.2287176390218
12.228716029899726
12.228714421126934
12.228712812703316
12.228711204628807
12.228709596903352
12.228707989526853
12.228706382499244
12.228704775820443
12.228703169490378
12.228701563508965
12.228699957876144
12.228698352591834
12.228696747655944
12.228695143068416
12.228693538829178
12.228691934938137
12.228690331395233
12.228688728200382
12.228687125353495
12.228685522854523
12.228683920703384
12.22868231889999
12.22868071744428
12.228679116336158
12.228677515575578
12.228675915162441
12.22867431509668
12.228672715378217
12.228671116006979
12.228669516982892
12.22866791830588
12.228666319975856
12.228664721992768
12.228663124356522

12.228661527067041
12.228659930124268
12.22865833352811
12.228656737278506
12.228655141375373
12.228653545818629
12.228651950608208
12.228650355744032
12.228648761226028
12.228647167054126
12.228645573228235
12.2286439797483
12.228642386614217
12.228640793825948
12.228639201383393
12.228637609286475
12.228636017535136
12.22863442612929
12.228632835068868
12.22863124435378
12.228629653983973
12.22862806395935
12.228626474279853
12.228624884945406
12.228623295955922
12.228621707311339
12.228620119011572
12.228618531056558
12.228616943446212
12.228615356180454
12.228613769259232
12.228612182682443
12.228610596450034
12.228609010561915
12.228607425018023
12.22860583981827
12.2286042549626
12.228602670450924
12.22860108628317
12.228599502459275
12.228597918979146
12.228596335842719
12.228594753049915
12.22859317060066
12.228591588494881
12.228590006732501
12.228588425313465
12.228586844237661
12.228585263505042
12.228583683115527
12.228582103069035
12.228580523365503
12.228578944004857
12.228577364987006
12.228575786311884
12.228574207979422
12.228572629989548
12.228571052342181
12.22856947503724
12.22856789807466
12.22856632145437
12.228564745176287
12.228563169240347
12.22856159364646
12.228560018394559
12.228558443484582
12.228556868916437
12.22855529469006
12.228553720805373
12.228552147262299
12.228550574060769
12.228549001200712
12.22854742868205
12.228545856504706
12.228544284668605
12.22854271317368
12.228541142019855
12.228539571207051
12.22853800073519
12.228536430604212
12.228534860814033
12.228533291364585
12.228531722255797
12.228530153487574
12.228528585059882
12.228527016972592
12.228525449225678
12.228523881819036
12.228522314752619
12.22852074802633
12.228519181640102
12.228517615593873
12.228516049887562
12.228514484521083
12.22851291949438
12.228511354807349
12.228509790459965
12.228508226452117
12.22850666278374
12.228505099454768
12.228503536465114
12.228501973814708
12.228500411503495
12.228498849531379
12.228497287898296
12.228495726604173
12.22849416564892
12.228492605032487
12.228491044754794
12.228489484815762
12.228487925215312
12.228486365953385
12.2284848070299
12.228483248444782
12.228481690197967
12.228480132289361
12.228478574718915
12.228477017486545
12.228475460592175
12.228473904035736
12.228472347817139
12.228470791936342
12.228469236393252
12.228467681187785
12.228466126319885
12.228464571789475
12.228463017596475
12.228461463740834
12.22845991022245
12.228458357041262
12.228456804197203
12.228455251690178
12.228453699520143
12.228452147687012
12.228450596190706
12.228449045031166
12.228447494208298
12.228445943722043
12.228444393572335
12.228442843759082
12.228441294282224
12.22843974514169
12.2284381963374
12.228436647869275
12.228435099737247
12.228433551941263
12.228432004481213
12.228430457357057
12.228428910568713
12.228427364116103
12.228425817999144
12.228424272217785
12.22842272677193
12.228421181661524
12.228419636886487
12.228418092446763
12.228416548342251
12.228415004572891
12.228413461138613
12.228411918039342
12.228410375274997
12.228408832845531
12.228407290750852
12.228405748990879
12.228404207565552
12.228402666474807
12.228401125718547
12.22839958529671
12.22839804520924
12.228396505456045
12.228394966037063
12.228393426952206
12.228391888201415
12.228390349784618
12.228388811701738
12.2283872739527
12.228385736537437
12.228384199455881
12.228382662707945
12.228381126293565
12.228379590212672
12.228378054465184
12.228376519051041
12.228374983970161
12.228373449222486
12.228371914807918
12.228370380726409
12.228368846977867
12.22836731356223
12.22836578047944
12.228364247729397
12.228362715312041
12.228361183227307
12.228359651475117
12.228358120055395
12.228356588968069
12.228355058213078
12.228353527790334
12.228351997699782
12.228350467941334
12.228348938514921
12.228347409420481
12.228345880657937
12.228344352227218
12.228342824128244
12.22834129636094
12.228339768925261
12.228338241821092
12.22833671504841
12.228335188607105
12.228333662497132
12.228332136718382
12.228330611270819
12.228329086154366
12.228327561368934
12.228326036914469
12.228324512790882
12.228322988998121
12.228321465536098
12.228319942404742
12.22831841960399
12.228316897133771
12.228315374993999
12.228313853184623
12.228312331705562
12.228310810556728
12.228309289738068
12.228307769249513
12.228306249090982
12.228304729262407
12.228303209763714
12.228301690594826
12.228300171755686
12.228298653246213
12.228297135066338
12.22829561721599
12.228294099695084
12.228292582503576
12.228291065641358
12.228289549108398
12.228288032904603
12.2282865170299
12.228285001484222
12.228283486267499
12.228281971379657
12.228280456820627
12.228278942590338
12.228277428688717
12.228275915115688
12.228274401871182
12.228272888955143
12.228271376367482
12.228269864108121
12.22826835217701
12.228266840574069
12.228265329299223
12.228263818352401
12.228262307733539
12.228260797442559
12.228259287479391
12.228257777843961
12.228256268536205
12.228254759556055
12.228253250903434
12.228251742578257
12.228250234580477
12.228248726910005
12.228247219566786
12.228245712550734
12.22824420586179
12.228242699499871
12.228241193464914
12.228239687756842
12.228238182375593
12.228236677321089
12.22823517259326
12.228233668192036
12.228232164117355
12.228230660369128
12.228229156947297
12.22822765385179
12.228226151082525
12.228224648639458
12.228223146522478
12.22822164473155
12.228220143266595
12.228218642127533
12.2282171413143
12.228215640826809
12.228214140665012
12.228212640828831
12.22821114131819
12.228209642133026
12.228208143273259
12.228206644738837
12.22820514652965
12.228203648645668
12.228202151086812
12.228200653853001
12.228199156944171
12.22819766036025
12.228196164101158
12.228194668166838
12.228193172557209
12.228191677272212
12.228190182311767
12.22818868767582
12.228187193364276
12.228185699377077
12.228184205714156
12.228182712375432
12.228181219360842
12.22817972667033
12.228178234303794
12.228176742261185
12.228175250542426
12.228173759147449
12.228172268076184
12.22817077732857
12.22816928690451
12.228167796803962
12.228166307026836
12.228164817573079
12.2281633284426
12.228161839635357
12.228160351151248
12.228158862990227
12.228157375152213
12.228155887637138
12.228154400444936
12.228152913575526
12.228151427028859
12.228149940804839
12.228148454903407
12.228146969324497
12.22814548406804
12.228143999133955
12.228142514522178
12.228141030232651
12.228139546265279
12.228138062620017
12.228136579296777
12.228135096295508
12.228133613616109
12.228132131258544
12.228130649222734
12.228129167508587
12.228127686116053
12.228126205045067
12.228124724295549
12.228123243867428
12.228121763760637
12.228120283975116
12.228118804510782
12.228117325367569
12.228115846545412
12.22811436804422
12.228112889863961
12.228111412004537
12.228109934465886
12.228108457247933
12.228106980350628
12.228105503773879
12.228104027517622
12.228102551581793
12.228101075966327
12.228099600671142
12.228098125696171
12.22809665104134
12.228095176706603
12.228093702691861
12.22809222899707
12.22809075562214
12.228089282567009
12.22808780983161
12.228086337415878
12.228084865319728
12.2280833935431
12.22808192208593
12.228080450948143
12.228078980129673
12.22807750963044
12.228076039450391
12.22807456958945
12.228073100047535
12.228071630824603
12.228070161920561
12.22806869333535
12.228067225068898
12.228065757121135
12.22806428949199
12.228062822181407
12.2280613551893
12.228059888515604
12.228058422160272
12.228056956123199
12.228055490404335
12.228054025003624
12.228052559920965
12.22805109515631
12.228049630709593
12.228048166580729
12.228046702769667
12.22804523927632
12.228043776100634
12.228042313242527
12.228040850701941
12.228039388478797
12.228037926573043
12.2280364649846
12.228035003713387
12.228033542759361
12.228032082122425
12.228030621802525
12.228029161799592
12.228027702113563
12.22802624274436
12.228024783691916
12.228023324956165
12.228021866537041
12.228020408434466
12.228018950648368
12.228017493178697
12.228016036025366
12.228014579188313
12.228013122667479
12.228011666462775
12.228010210574157
12.228008755001524
12.228007299744853
12.228005844804029
12.228004390179018
12.22800293586971
12.228001481876086
12.228000028198059
12.227998574835548
12.227997121788484
12.227995669056819
12.22799421664047
12.227992764539373
12.227991312753458
12.227989861282655

12.227988410126898
12.227986959286122
12.227985508760248
12.227984058549223
12.22798260865296
12.227981159071394
12.227979709804483
12.227978260852124
12.227976812214276
12.227975363890842
12.227973915881782
12.22797246818701
12.227971020806478
12.227969573740094
12.227968126987793
12.22796668054952
12.227965234425197
12.227963788614767
12.227962343118138
12.227960897935269
12.22795945306607
12.227958008510491
12.22795656426846
12.227955120339901
12.227953676724752
12.227952233422943
12.227950790434397
12.227949347759063
12.22794790539687
12.22794646334774
12.22794502161161
12.22794358018842
12.227942139078074
12.227940698280545
12.22793925779573
12.227937817623598
12.227936377764038
12.227934938217007
12.227933498982432
12.227932060060253
12.227930621450387
12.227929183152781
12.227927745167364
12.227926307494055
12.227924870132812
12.227923433083532
12.22792199634618
12.227920559920676
12.227919123806938
12.227917688004919
12.227916252514554
12.227914817335757
12.227913382468465
12.227911947912624
12.227910513668155
12.227909079734987
12.227907646113056
12.227906212802308
12.227904779802651
12.227903347114045
12.227901914736384
12.227900482669641
12.227899050913718
12.227897619468576
12.227896188334126
12.227894757510308
12.227893326997055
12.227891896794295
12.227890466901963
12.227889037319994
12.227887608048322
12.227886179086882
12.22788475043559
12.227883322094392
12.227881894063225
12.227880466342006
12.22787903893068
12.227877611829188
12.227876185037442
12.227874758555386
12.227873332382947
12.227871906520072
12.227870480966683
12.22786905572271
12.227867630788085
12.227866206162744
12.227864781846625
12.227863357839661
12.227861934141774
12.22786051075291
12.227859087672993
12.22785766490196
12.22785624243975
12.227854820286279
12.227853398441487
12.227851976905313
12.227850555677687
12.227849134758547
12.227847714147806
12.227846293845433
12.227844873851325
12.227843454165436
12.227842034787688
12.227840615718023
12.227839196956372
12.227837778502659
12.227836360356829
12.227834942518813
12.227833524988545
12.227832107765947
12.227830690850961
12.22782927424352
12.22782785794356
12.227826441951004
12.227825026265798
12.227823610887878
12.22782219581716
12.227820781053593
12.227819366597092
12.227817952447607
12.22781653860507
12.227815125069402
12.227813711840557
12.22781229891845
12.227810886303022
12.22780947399421
12.227808061991933
12.227806650296134
12.22780523890676
12.227803827823724
12.227802417046965
12.227801006576408
12.227799596412016
12.227798186553693
12.227796777001394
12.227795367755029
12.227793958814543
12.227792550179874
12.227791141850956
12.227789733827713
12.227788326110085
12.227786918698008
12.22778551159141
12.227784104790233
12.227782698294405
12.227781292103858
12.227779886218524
12.227778480638342
12.227777075363248
12.227775670393171
12.22777426572804
12.227772861367805
12.227771457312375
12.227770053561716
12.227768650115738
12.227767246974372
12.227765844137569
12.227764441605258
12.227763039377368
12.22776163745383
12.227760235834584
12.227758834519557
12.227757433508694
12.227756032801924
12.227754632399177
12.227753232300394
12.227751832505508
12.227750433014444
12.22774903382715
12.22774763494355
12.227746236363576
12.227744838087172
12.227743440114267
12.227742042444788
12.227740645078683
12.227739248015876
12.227737851256311
12.227736454799906
12.227735058646605
12.22773366279635
12.227732267249063
12.227730872004686
12.227729477063143
12.22772808242438
12.227726688088325
12.227725294054919
12.227723900324083
12.22772250689576
12.22772111376989
12.227719720946402
12.227718328425215
12.22771693620629
12.227715544289541
12.227714152674913
12.22771276136234
12.227711370351757
12.227709979643098
12.227708589236284
12.227707199131265
12.227705809327983
12.227704419826344
12.2277030306263
12.227701641727796
12.227700253130754
12.2276988648351
12.227697476840792
12.227696089147742
12.227694701755894
12.227693314665178
12.227691927875547
12.227690541386911
12.227689155199219
12.2276877693124
12.227686383726393
12.227684998441124
12.227683613456541
12.22768222877257
12.227680844389145
12.227679460306206
12.227678076523686
12.227676693041513
12.227675309859633
12.227673926977975
12.22767254439647
12.227671162115065
12.227669780133686
12.227668398452256
12.227667017070738
12.227665635989045
12.227664255207115
12.227662874724894
12.227661494542302
12.227660114659294
12.227658735075774
12.22765735579171
12.227655976807025
12.227654598121639
12.227653219735506
12.227651841648553
12.227650463860723
12.227649086371933
12.22764770918214
12.227646332291263
12.227644955699239
12.22764357940602
12.227642203411524
12.227640827715689
12.227639452318442
12.227638077219726
12.227636702419499
12.227635327917664
12.227633953714163
12.22763257980894
12.227631206201933
12.22762983289306
12.227628459882268
12.227627087169493
12.22762571475466
12.227624342637723
12.22762297081861
12.227621599297237
12.227620228073569
12.227618857147517
12.22761748651904
12.227616116188054
12.227614746154503
12.227613376418308
12.227612006979435
12.227610637837794
12.227609268993326
12.227607900445973
12.227606532195663
12.227605164242341
12.227603796585923
12.227602429226367
12.2276010621636
12.227599695397547
12.227598328928165
12.227596962755369
12.227595596879103
12.227594231299314
12.227592866015913
12.227591501028854
12.227590136338073
12.227588771943495
12.227587407845075
12.227586044042713
12.227584680536381
12.227583317326003
12.227581954411509
12.22758059179284
12.227579229469923
12.22757786744271
12.227576505711118
12.227575144275095
12.227573783134584
12.227572422289496
12.227571061739791
12.227569701485404
12.22756834152625
12.227566981862276
12.227565622493428
12.227564263419623
12.227562904640816
12.227561546156938
12.227560187967924
12.227558830073692
12.22755747247421
12.227556115169389
12.227554758159169
12.227553401443501
12.227552045022307
12.227550688895517
12.227549333063088
12.227547977524939
12.227546622281029
12.227545267331259
12.227543912675591
12.22754255831395
12.227541204246275
12.227539850472503
12.227538496992576
12.227537143806417
12.22753579091397
12.22753443831518
12.227533086009965
12.227531733998275
12.227530382280035
12.227529030855191
12.227527679723684
12.227526328885434
12.227524978340389
12.227523628088486
12.22752227812965
12.227520928463836
12.227519579090968
12.227518230010965
12.227516881223805
12.227515532729385
12.227514184527662
12.227512836618574
12.227511489002051
12.227510141678035
12.227508794646452
12.227507447907247
12.227506101460351
12.227504755305711
12.227503409443253
12.227502063872919
12.227500718594632
12.227499373608353
12.227498028914003
12.227496684511518
12.227495340400841
12.227493996581904
12.227492653054647
12.227491309818996
12.227489966874902
12.227488624222305
12.227487281861128
12.227485939791308
12.227484598012792
12.22748325652551
12.227481915329403
12.227480574424408
12.227479233810447
12.227477893487478
12.227476553455418
12.227475213714225
12.227473874263822
12.227472535104145
12.227471196235149
12.227469857656743
12.22746851936888
12.227467181371498
12.22746584366453
12.22746450624792
12.227463169121584
12.227461832285485
12.227460495739544
12.227459159483702
12.227457823517906
12.227456487842078
12.227455152456162
12.227453817360084
12.227452482553796
12.227451148037234
12.227449813810331
12.227448479873022
12.227447146225247
12.227445812866943
12.227444479798054
12.2274431470185
12.227441814528234
12.227440482327182
12.227439150415286
12.227437818792493
12.227436487458725
12.22743515641392
12.227433825658029
12.22743249519098
12.227431165012703
12.227429835123152
12.22742850552226
12.227427176209956
12.227425847186172
12.227424518450864
12.227423190003952
12.227421861845391
12.22742053397511
12.227419206393042
12.227417879099129
12.227416552093308
12.227415225375514
12.227413898945683
12.227412572803757
12.22741124694968
12.227409921383378
12.227408596104793
12.227407271113861
12.227405946410514
12.2274046219947
12.227403297866356
12.227401974025423
12.227400650471825
12.227399327205504
12.227398004226401
12.227396681534456
12.2273953591296
12.227394037011775
12.227392715180924
12.227391393636971
12.227390072379865
12.227388751409535
12.22738743072593
12.227386110328979
12.227384790218627
12.227383470394802
12.22738215085744
12.227380831606501
12.227379512641905
12.227378193963586
12.227376875571489
12.227375557465551
12.227374239645707
12.227372922111908
12.227371604864084
12.227370287902161
12.227368971226095
12.227367654835799
12.22736633873124
12.227365022912345
12.227363707379046
12.227362392131294
12.227361077169018
12.227359762492142
12.227358448100636
12.227357133994415
12.227355820173418
12.227354506637594
12.227353193386868
12.227351880421189
12.227350567740498
12.227349255344711
12.227347943233802
12.227346631407675
12.227345319866286
12.227344008609565
12.22734269763746
12.227341386949895
12.227340076546824
12.227338766428192
12.227337456593897
12.227336147043921
12.227334837778177
12.22733352879662
12.227332220099177
12.22733091168578
12.227329603556381
12.227328295710917
12.227326988149319
12.227325680871527
12.227324373877494
12.227323067167132
12.227321760740407
12.227320454597233
12.227319148737564
12.227317843161341
12.22731653786848
12.227315232858944
12.227313928132661
12.22731262368957
12.227311319529607
12.227310015652723
12.227308712058838
12.227307408747908
12.22730610571987
12.227304802974636
12.227303500512182
12.22730219833242
12.227300896435308
12.22729959482076
12.227298293488746
12.22729699243918
12.227295691672008
12.22729439118717
12.227293090984608
12.227291791064257
12.227290491426048
12.227289192069927
12.22728789299585
12.227286594203731
12.227285295693507
12.227283997465136
12.227282699518545
12.227281401853679
12.227280104470465
12.227278807368858
12.227277510548781
12.227276214010194
12.227274917753011
12.22727362177719
12.227272326082657
12.227271030669357
12.22726973553723
12.22726844068622
12.227267146116244
12.22726585182727
12.22726455781922
12.227263264092032
12.227261970645653
12.227260677480027
12.227259384595069
12.22725809199074
12.227256799666975
12.227255507623711
12.22725421586089
12.227252924378432
12.227251633176298
12.22725034225443
12.22724905161276
12.227247761251226
12.227246471169758
12.227245181368307
12.227243891846811
12.227242602605214
12.227241313643436
12.227240024961437
12.227238736559144
12.227237448436508
12.22723616059346

12.22723487302994
12.227233585745878
12.227232298741233
12.227231012015931
12.227229725569911
12.22722843940313
12.227227153515498
12.227225867906974
12.227224582577495
12.227223297526999
12.227222012755416
12.227220728262706
12.227219444048803
12.227218160113628
12.227216876457133
12.227215593079267
12.227214309979955
12.227213027159133
12.227211744616756
12.227210462352762
12.227209180367081
12.227207898659652
12.227206617230433
12.227205336079336
12.227204055206322
12.227202774611323
12.227201494294272
12.227200214255129
12.227198934493815
12.22719765501027
12.22719637580444
12.227195096876262
12.227193818225679
12.227192539852636
12.227191261757058
12.227189983938906
12.227188706398085
12.227187429134572
12.22718615214829
12.227184875439177
12.227183599007168
12.227182322852217
12.227181046974259
12.22717977137322
12.227178496049078
12.227177221001723
12.227175946231124
12.227174671737211
12.227173397519941
12.227172123579242
12.227170849915048
12.227169576527302
12.227168303415954
12.227167030580928
12.227165758022181
12.227164485739635
12.227163213733254
12.227161942002956
12.227160670548681
12.227159399370386
12.227158128468005
12.227156857841463
12.227155587490726
12.227154317415723
12.227153047616374
12.227151778092646
12.227150508844474
12.22714923987179
12.227147971174535
12.227146702752664
12.227145434606092
12.227144166734776
12.227142899138657
12.227141631817668
12.227140364771751
12.22713909800086
12.227137831504917
12.227136565283862
12.227135299337654
12.227134033666216
12.227132768269495
12.227131503147426
12.227130238299955
12.22712897372703
12.227127709428565
12.227126445404528
12.22712518165485
12.227123918179473
12.22712265497833
12.227121392051357
12.227120129398516
12.22711886701974
12.227117604914957
12.227116343084115
12.227115081527158
12.227113820244023
12.227112559234653
12.227111298498988
12.227110038036962
12.227108777848526
12.227107517933614
12.227106258292165
12.227104998924125
12.227103739829435
12.227102481008028
12.227101222459861
12.227099964184854
12.227098706182957
12.227097448454112
12.227096190998259
12.227094933815344
12.227093676905302
12.227092420268065
12.227091163903589
12.227089907811804
12.227088651992663
12.227087396446093
12.227086141172048
12.227084886170454
12.227083631441264
12.227082376984407
12.22708112279985
12.227079868887493
12.227078615247315
12.227077361879235
12.227076108783208
12.227074855959154
12.227073603407035
12.227072351126791
12.227071099118353
12.227069847381653
12.22706859591666
12.227067344723281
12.227066093801481
12.227064843151197
12.227063592772376
12.227062342664949
12.227061092828855
12.22705984326404
12.227058593970444
12.227057344948006
12.227056096196677
12.227054847716389
12.227053599507085
12.227052351568705
12.227051103901204
12.22704985650449
12.227048609378539
12.227047362523276
12.227046115938643
12.227044869624576
12.227043623581029
12.227042377807946
12.227041132305242
12.227039887072893
12.227038642110823
12.22703739741896
12.227036152997258
12.227034908845676
12.227033664964127
12.227032421352568
12.227031178010934
12.227029934939168
12.227028692137225
12.227027449605021
12.227026207342508
12.227024965349635
12.227023723626337
12.227022482172556
12.227021240988236
12.227020000073317
12.227018759427738
12.227017519051447
12.227016278944381
12.227015039106476
12.227013799537675
12.227012560237945
12.227011321207184
12.227010082445371
12.22700884395242
12.227007605728296
12.227006367772926
12.227005130086257
12.22700389266823
12.227002655518787
12.227001418637863
12.22700018202541
12.226998945681371
12.226997709605662
12.226996473798266
12.226995238259093
12.226994002988103
12.226992767985223
12.22699153325041
12.226990298783585
12.22698906458471
12.226987830653718
12.226986596990553
12.22698536359516
12.226984130467466
12.226982897607446
12.226981665015
12.226980432690093
12.226979200632663
12.226977968842663
12.226976737320017
12.226975506064665
12.226974275076573
12.226973044355663
12.226971813901885
12.226970583715174
12.226969353795482
12.226968124142736
12.226966894756897
12.226965665637895
12.226964436785673
12.22696320820018
12.226961979881352
12.22696075182913
12.226959524043457
12.22695829652427
12.22695706927153
12.226955842285165
12.226954615565106
12.226953389111323
12.226952162923736
12.226950937002297
12.22694971134694
12.226948485957617
12.226947260834274
12.226946035976836
12.226944811385257
12.226943587059488
12.226942362999443
12.226941139205081
12.226939915676356
12.226938692413194
12.226937469415551
12.22693624668335
12.22693502421655
12.226933802015095
12.226932580078902
12.22693135840795
12.226930137002151
12.226928915861462
12.226927694985829
12.226926474375182
12.226925254029467
12.226924033948643
12.226922814132623
12.22692159458137
12.226920375294826
12.226919156272928
12.226917937515628
12.226916719022851
12.226915500794549
12.226914282830668
12.22691306513115
12.22691184769593
12.226910630524964
12.226909413618177
12.22690819697552
12.226906980596947
12.226905764482385
12.226904548631786
12.226903333045074
12.226902117722217
12.226900902663155
12.226899687867812
12.226898473336146
12.226897259068092
12.2268960450636
12.226894831322605
12.22689361784506
12.226892404630904
12.226891191680066
12.226889978992508
12.226888766568166
12.226887554406979
12.226886342508891
12.226885130873843
12.226883919501796
12.226882708392662
12.22688149754641
12.226880286962981
12.226879076642307
12.22687786658432
12.226876656788987
12.226875447256251
12.226874237986031
12.22687302897829
12.226871820232969
12.226870611749996
12.226869403529333
12.226868195570919
12.226866987874686
12.226865780440589
12.22686457326857
12.226863366358565
12.22686215971052
12.226860953324381
12.226859747200097
12.226858541337597
12.226857335736826
12.226856130397742
12.22685492532026
12.22685372050437
12.226852515949965
12.226851311657018
12.226850107625456
12.226848903855242
12.2268477003463
12.226846497098585
12.226845294112028
12.22684409138659
12.226842888922205
12.226841686718805
12.22684048477635
12.226839283094787
12.226838081674044
12.226836880514066
12.226835679614808
12.226834478976205
12.226833278598201
12.226832078480738
12.226830878623767
12.226829679027222
12.22682847969105
12.226827280615197
12.226826081799606
12.226824883244214
12.22682368494897
12.22682248691382
12.22682128913871
12.226820091623575
12.226818894368362
12.226817697373011
12.22681650063748
12.22681530416168
12.226814107945597
12.226812911989146
12.226811716292278
12.22681052085494
12.226809325677067
12.226808130758611
12.226806936099516
12.226805741699723
12.226804547559174
12.226803353677816
12.226802160055588
12.22680096669245
12.22679977358832
12.226798580743152
12.226797388156896
12.226796195829495
12.226795003760888
12.22679381195103
12.226792620399834
12.22679142910728
12.2267902380733
12.22678904729782
12.226787856780813
12.226786666522212
12.226785476521945
12.226784286779978
12.226783097296236
12.226781908070688
12.226780719103251
12.226779530393877
12.22677834194252
12.226777153749117
12.226775965813621
12.226774778135951
12.22677359071609
12.226772403553936
12.22677121664947
12.226770030002625
12.22676884361333
12.226767657481552
12.22676647160722
12.22676528599028
12.22676410063069
12.226762915528374
12.226761730683295
12.226760546095388
12.22675936176459
12.226758177690856
12.226756993874128
12.226755810314339
12.226754627011449
12.226753443965396
12.22675226117612
12.226751078643582
12.226749896367703
12.226748714348444
12.226747532585733
12.22674635107953
12.226745169829776
12.226743988836422
12.226742808099399
12.226741627618642
12.226740447394123
12.226739267425774
12.226738087713532
12.226736908257351
12.226735729057172
12.226734550112933
12.226733371424594
12.226732192992092
12.22673101481536
12.226729836894357
12.226728659229028
12.226727481819307
12.226726304665139
12.226725127766493
12.226723951123265
12.22672277473545
12.226721598602964
12.226720422725755
12.226719247103777
12.22671807173697
12.22671689662528
12.226715721768638
12.226714547167006
12.226713372820324
12.22671219872853
12.226711024891578
12.226709851309408
12.226708677981966
12.226707504909193
12.226706332091037
12.226705159527445
12.226703987218357
12.226702815163716
12.226701643363475
12.226700471817583
12.226699300525958
12.226698129488577
12.226696958705368
12.226695788176274
12.226694617901249
12.226693447880233
12.22669227811317
12.226691108600004
12.226689939340686
12.226688770335146
12.22668760158335
12.22668643308523
12.226685264840736
12.226684096849805
12.226682929112394
12.22668176162844
12.22668059439789
12.226679427420684
12.226678260696772
12.226677094226098
12.226675928008614
12.226674762044256
12.226673596332969
12.2266724308747
12.226671265669397
12.226670100717001
12.22666893601747
12.226667771570725
12.226666607376721
12.226665443435413
12.22666427974674
12.226663116310647
12.226661953127074
12.226660790195986
12.226659627517302
12.226658465090974
12.226657302916957
12.226656140995193
12.226654979325616
12.226653817908199
12.226652656742845
12.226651495829532
12.22665033516822
12.2266491747588
12.226648014601258
12.226646854695526
12.226645695041544
12.226644535639279
12.226643376488669

12.22664221758964
12.226641058942157
12.226639900546166
12.226638742401594
12.226637584508408
12.226636426866538
12.226635269475938
12.22663411233655
12.226632955448318
12.226631798811193
12.226630642425112
12.226629486290028
12.226628330405882
12.226627174772622
12.226626019390194
12.226624864258556
12.226623709377625
12.226622554747365
12.226621400367716
12.226620246238634
12.226619092360044
12.226617938731923
12.226616785354183
12.226615632226789
12.226614479349678
12.226613326722804
12.226612174346105
12.226611022219531
12.226609870343037
12.226608718716552
12.226607567340027
12.22660641621341
12.226605265336644
12.226604114709682
12.22660296433246
12.226601814204932
12.226600664327036
12.22659951469872
12.22659836531994
12.226597216190635
12.226596067310744
12.226594918680217
12.226593770299004
12.226592622167038
12.226591474284293
12.22659032665068
12.22658917926617
12.226588032130705
12.226586885244213
12.226585738606666
12.226584592217998
12.226583446078147
12.226582300187076
12.226581154544716
12.22658000915102
12.226578864005928
12.226577719109395
12.226576574461356
12.22657543006177
12.226574285910583
12.226573142007714
12.22657199835315
12.22657085494681
12.226569711788652
12.226568568878612
12.226567426216643
12.22656628380269
12.2265651416367
12.226563999718623
12.226562858048386
12.22656171662596
12.226560575451273
12.226559434524292
12.226558293844938
12.22655715341317
12.226556013228942
12.226554873292187
12.22655373360285
12.226552594160896
12.226551454966245
12.226550316018873
12.226549177318706
12.226548038865682
12.226546900659768
12.2265457627009
12.226544624989039
12.22654348752411
12.226542350306064
12.226541213334858
12.226540076610426
12.226538940132734
12.226537803901701
12.226536667917303
12.226535532179458
12.226534396688134
12.226533261443267
12.2265321264448
12.226530991692691
12.22652985718688
12.226528722927311
12.226527588913934
12.226526455146704
12.226525321625553
12.226524188350428
12.22652305532129
12.226521922538076
12.226520790000732
12.226519657709206
12.226518525663446
12.226517393863393
12.226516262308998
12.226515131000212
12.226513999936975
12.226512869119242
12.226511738546948
12.22651060822005
12.226509478138475
12.226508348302197
12.226507218711161
12.226506089365287
12.226504960264544
12.22650383140887
12.226502702798227
12.22650157443254
12.226500446311766
12.226499318435852
12.226498190804746
12.226497063418392
12.226495936276734
12.226494809379725
12.226493682727314
12.226492556319442
12.226491430156056
12.226490304237101
12.22648917856254
12.226488053132295
12.226486927946329
12.226485803004588
12.226484678307008
12.22648355385356
12.226482429644157
12.226481305678778
12.226480181957356
12.226479058479834
12.226477935246166
12.226476812256289
12.226475689510167
12.22647456700774
12.226473444748947
12.226472322733738
12.226471200962068
12.22647007943388
12.22646895814912
12.226467837107725
12.226466716309664
12.22646559575487
12.226464475443299
12.226463355374888
12.226462235549587
12.226461115967346
12.226459996628108
12.226458877531831
12.22645775867845
12.226456640067914
12.22645552170018
12.226454403575186
12.226453285692877
12.226452168053207
12.226451050656125
12.226449933501572
12.226448816589503
12.226447699919856
12.226446583492573
12.226445467307636
12.226444351364949
12.226443235664492
12.226442120206183
12.226441004989987
12.226439890015852
12.226438775283727
12.22643766079355
12.22643654654528
12.226435432538857
12.226434318774224
12.226433205251341
12.226432091970144
12.226430978930594
12.226429866132616
12.226428753576185
12.226427641261218
12.226426529187695
12.226425417355543
12.226424305764716
12.226423194415162
12.226422083306828
12.226420972439659
12.226419861813604
12.226418751428607
12.226417641284627
12.226416531381599
12.226415421719478
12.226414312298203
12.22641320311774
12.22641209417802
12.226410985479
12.22640987702062
12.226408768802829
12.226407660825583
12.226406553088827
12.226405445592498
12.226404338336557
12.22640323132095
12.226402124545611
12.226401018010504
12.22639991171556
12.226398805660752
12.226397699846014
12.226396594271288
12.226395488936532
12.226394383841685
12.2263932789867
12.22639217437153
12.226391069996115
12.226389965860408
12.226388861964338
12.226387758307888
12.226386654890977
12.226385551713562
12.22638444877561
12.22638334607704
12.2263822436178
12.226381141397864
12.226380039417153
12.226378937675639
12.226377836173265
12.22637673490996
12.22637563388569
12.226374533100394
12.226373432554029
12.226372332246534
12.22637123217786
12.226370132347965
12.226369032756779
12.226367933404264
12.226366834290365
12.226365735415023
12.226364636778197
12.226363538379838
12.226362440219878
12.226361342298281
12.226360244614986
12.226359147169942
12.226358049963093
12.226356952994406
12.226355856263803
12.226354759771255
12.226353663516704
12.226352567500086
12.226351471721372
12.226350376180488
12.226349280877397
12.226348185812038
12.226347090984365
12.226345996394315
12.226344902041859
12.226343807926934
12.22634271404949
12.226341620409457
12.226340527006808
12.226339433841481
12.226338340913427
12.226337248222599
12.226336155768928
12.226335063552389
12.226333971572917
12.226332879830439
12.226331788324941
12.226330697056346
12.22632960602462
12.226328515229708
12.226327424671538
12.226326334350082
12.226325244265285
12.226324154417087
12.226323064805431
12.226321975430295
12.226320886291603
12.226319797389305
12.226318708723355
12.226317620293697
12.226316532100288
12.226315444143076
12.226314356421996
12.226313268937016
12.226312181688062
12.226311094675099
12.226310007898086
12.226308921356948
12.226307835051648
12.226306748982125
12.226305663148342
12.226304577550234
12.226303492187755
12.226302407060855
12.226301322169485
12.22630023751359
12.22629915309313
12.22629806890803
12.226296984958253
12.226295901243757
12.226294817764478
12.226293734520366
12.226292651511374
12.226291568737446
12.22629048619855
12.226289403894608
12.226288321825583
12.226287239991418
12.226286158392075
12.226285077027478
12.226283995897603
12.226282915002383
12.22628183434178
12.226280753915724
12.226279673724182
12.226278593767098
12.226277514044412
12.226276434556079
12.226275355302052
12.226274276282288
12.226273197496713
12.226272118945294
12.226271040627974
12.226269962544706
12.226268884695438
12.226267807080108
12.226266729698684
12.226265652551108
12.22626457563732
12.226263498957275
12.226262422510933
12.226261346298223
12.226260270319113
12.226259194573542
12.226258119061464
12.226257043782837
12.226255968737584
12.226254893925677
12.226253819347049
12.226252745001668
12.226251670889473
12.226250597010416
12.226249523364448
12.226248449951507
12.226247376771555
12.226246303824533
12.226245231110399
12.2262441586291
12.22624308638058
12.226242014364788
12.22624094258169
12.226239871031213
12.226238799713313
12.226237728627956
12.226236657775068
12.226235587154617
12.226234516766535
12.226233446610793
12.226232376687316
12.226231306996077
12.226230237537001
12.226229168310077
12.226228099315207
12.226227030552371
12.226225962021509
12.226224893722566
12.226223825655508
12.226222757820276
12.226221690216807
12.226220622845068
12.226219555704999
12.226218488796556
12.22621742211968
12.22621635567434
12.226215289460463
12.226214223478006
12.22621315772693
12.226212092207168
12.226211026918682
12.226209961861416
12.226208897035315
12.226207832440348
12.22620676807645
12.226205703943563
12.226204640041642
12.226203576370658
12.22620251293054
12.226201449721229
12.226200386742702
12.226199323994885
12.226198261477752
12.22619719919122
12.22619613713527
12.22619507530984
12.226194013714878
12.226192952350333
12.226191891216155
12.22619083031231
12.226189769638726
12.226188709195354
12.226187648982163
12.22618658899909
12.226185529246083
12.22618446972309
12.226183410430078
12.226182351366987
12.226181292533763
12.226180233930355
12.226179175556725
12.226178117412804
12.226177059498566
12.226176001813936
12.226174944358881
12.226173887133355
12.22617283013729
12.226171773370654
12.226170716833392
12.22616966052545
12.22616860444677
12.226167548597324
12.226166492977036
12.226165437585879
12.226164382423796
12.22616332749074
12.226162272786656
12.226161218311487
12.2261601640652
12.226159110047742
12.22615805625906
12.226157002699095
12.226155949367808
12.226154896265143
12.226153843391062
12.226152790745498
12.226151738328415
12.226150686139766
12.22614963417949
12.22614858244754
12.226147530943878
12.226146479668433
12.226145428621175
12.226144377802052
12.226143327210998
12.226142276847979
12.226141226712944
12.22614017680584
12.226139127126615
12.226138077675234
12.226137028451626
12.22613597945576
12.226134930687572

12.226133882147028
12.22613283383406
12.226131785748636
12.2261307378907
12.226129690260196
12.226128642857086
12.226127595681312
12.22612654873283
12.226125502011588
12.226124455517532
12.226123409250631
12.226122363210807
12.226121317398038
12.226120271812258
12.226119226453427
12.226118181321485
12.22611713641639
12.226116091738097
12.226115047286548
12.226114003061701
12.226112959063492
12.226111915291897
12.226110871746842
12.226109828428305
12.226108785336207
12.226107742470512
12.22610669983118
12.226105657418145
12.226104615231375
12.2261035732708
12.226102531536396
12.226101490028089
12.22610044874585
12.226099407689611
12.22609836685934
12.226097326254987
12.226096285876492
12.22609524572382
12.226094205796896
12.226093166095708
12.226092126620182
12.226091087370264
12.226090048345915
12.226089009547099
12.22608797097375
12.226086932625822
12.226085894503276
12.226084856606048
12.226083818934091
12.22608278148737
12.226081744265823
12.226080707269404
12.22607967049807
12.226078633951758
12.226077597630434
12.226076561534049
12.22607552566254
12.226074490015868
12.226073454593987
12.226072419396846
12.2260713844244
12.226070349676586
12.226069315153369
12.226068280854687
12.226067246780515
12.226066212930778
12.226065179305444
12.226064145904454
12.226063112727765
12.226062079775328
12.226061047047093
12.22606001454301
12.226058982263035
12.226057950207123
12.226056918375214
12.22605588676726
12.226054855383223
12.226053824223039
12.226052793286682
12.226051762574082
12.2260507320852
12.226049701819974
12.22604867177839
12.226047641960362
12.22604661236586
12.226045582994828
12.22604455384722
12.226043524923002
12.226042496222098
12.226041467744482
12.226040439490104
12.226039411458888
12.22603838365082
12.226037356065833
12.226036328703891
12.22603530156493
12.226034274648917
12.226033247955796
12.226032221485507
12.226031195238026
12.226030169213292
12.22602914341126
12.226028117831861
12.226027092475084
12.226026067340852
12.226025042429127
12.226024017739856
12.226022993273002
12.226021969028505
12.226020945006326
12.226019921206397
12.22601889762869
12.226017874273154
12.22601685113974
12.226015828228391
12.22601480553907
12.226013783071721
12.2260127608263
12.226011738802748
12.226010717001037
12.226009695421116
12.226008674062916
12.226007652926414
12.226006632011536
12.22600561131825
12.226004590846516
12.226003570596273
12.226002550567463
12.22600153076006
12.226000511174007
12.225999491809251
12.225998472665749
12.225997453743457
12.225996435042319
12.225995416562291
12.225994398303325
12.22599338026538
12.225992362448384
12.22599134485232
12.225990327477117
12.225989310322738
12.225988293389127
12.225987276676255
12.225986260184053
12.225985243912485
12.22598422786149
12.225983212031029
12.225982196421057
12.22598118103153
12.225980165862385
12.225979150913592
12.225978136185093
12.225977121676829
12.225976107388773
12.22597509332087
12.225974079473064
12.225973065845311
12.225972052437585
12.225971039249801
12.225970026281942
12.225969013533936
12.225968001005757
12.225966988697348
12.225965976608647
12.225964964739632
12.225963953090242
12.225962941660425
12.22596193045015
12.22596091945935
12.225959908687983
12.22595889813601
12.225957887803375
12.225956877690033
12.225955867795946
12.225954858121042
12.225953848665304
12.22595283942865
12.22595183041106
12.225950821612477
12.225949813032845
12.225948804672145
12.225947796530301
12.22594678860727
12.22594578090302
12.22594477341748
12.225943766150623
12.225942759102379
12.225941752272727
12.225940745661614
12.22593973926897
12.225938733094782
12.225937727138966
12.2259367214015
12.225935715882333
12.225934710581411
12.225933705498692
12.225932700634123
12.225931695987665
12.225930691559256
12.225929687348868
12.22592868335644
12.225927679581929
12.225926676025288
12.225925672686467
12.225924669565423
12.225923666662114
12.225922663976473
12.225921661508474
12.225920659258053
12.225919657225175
12.225918655409789
12.225917653811845
12.225916652431302
12.225915651268098
12.225914650322213
12.225913649593576
12.22591264908214
12.225911648787873
12.225910648710723
12.225909648850635
12.22590864920757
12.22590764978147
12.2259066505723
12.225905651580009
12.22590465280455
12.225903654245876
12.225902655903942
12.225901657778694
12.22590065987009
12.225899662178078
12.225898664702617
12.225897667443661
12.225896670401157
12.225895673575058
12.225894676965343
12.225893680571922
12.225892684394768
12.22589168843384
12.225890692689084
12.225889697160449
12.225888701847897
12.225887706751388
12.225886711870851
12.22588571720626
12.225884722757547
12.2258837285247
12.22588273450765
12.22588174070634
12.225880747120737
12.225879753750798
12.22587876059647
12.225877767657689
12.225876774934441
12.225875782426662
12.225874790134304
12.22587379805733
12.225872806195687
12.225871814549322
12.225870823118187
12.225869831902251
12.225868840901462
12.225867850115762
12.22586685954511
12.225865869189477
12.225864879048782
12.225863889123016
12.2258628994121
12.225861909915999
12.225860920634682
12.225859931568085
12.225858942716153
12.225857954078858
12.22585696565614
12.225855977447969
12.225854989454287
12.225854001675051
12.22585301411021
12.225852026759718
12.225851039623533
12.225850052701604
12.225849065993893
12.22584807950034
12.225847093220906
12.225846107155547
12.225845121304204
12.225844135666858
12.22584315024344
12.225842165033898
12.225841180038199
12.225840195256295
12.225839210688141
12.225838226333684
12.22583724219288
12.225836258265685
12.225835274552058
12.225834291051937
12.225833307765289
12.225832324692064
12.225831341832217
12.22583035918569
12.22582937675246
12.22582839453246
12.225827412525648
12.225826430731987
12.225825449151422
12.225824467783912
12.225823486629402
12.225822505687857
12.225821524959224
12.225820544443458
12.22581956414051
12.225818584050337
12.22581760417289
12.22581662450813
12.225815645056008
12.225814665816479
12.225813686789479
12.225812707974988
12.225811729372952
12.225810750983324
12.225809772806047
12.225808794841083
12.225807817088391
12.22580683954792
12.225805862219625
12.22580488510345
12.225803908199374
12.22580293150732
12.225801955027265
12.225800978759146
12.225800002702936
12.225799026858576
12.225798051226029
12.225797075805245
12.225796100596158
12.225795125598747
12.225794150812963
12.225793176238767
12.225792201876088
12.225791227724894
12.225790253785144
12.225789280056789
12.225788306539775
12.225787333234079
12.22578636013962
12.225785387256378
12.225784414584309
12.225783442123344
12.225782469873458
12.225781497834603
12.225780526006725
12.225779554389783
12.225778582983734
12.225777611788528
12.225776640804112
12.225775670030455
12.225774699467497
12.225773729115204
12.225772758973532
12.225771789042426
12.225770819321848
12.225769849811742
12.22576888051207
12.225767911422782
12.225766942543835
12.22576597387519
12.225765005416783
12.225764037168588
12.225763069130544
12.225762101302616
12.225761133684756
12.22576016627692
12.225759199079063
12.22575823209113
12.225757265313083
12.225756298744864
12.225755332386461
12.225754366237798
12.225753400298833
12.225752434569518
12.225751469049825
12.225750503739702
12.225749538639084
12.225748573747955
12.225747609066254
12.225746644593938
12.225745680330954
12.225744716277271
12.225743752432832
12.225742788797588
12.225741825371509
12.225740862154543
12.225739899146644
12.225738936347762
12.225737973757855
12.225737011376882
12.225736049204787
12.225735087241539
12.225734125487078
12.225733163941376
12.225732202604371
12.225731241476023
12.22573028055629
12.225729319845122
12.22572835934248
12.225727399048317
12.225726438962582
12.225725479085227
12.22572451941623
12.225723559955512
12.225722600703053
12.2257216416588
12.225720682822706
12.22571972419473
12.225718765774822
12.225717807562937
12.22571684955904
12.225715891763064
12.22571493417499
12.225713976794754
12.225713019622317
12.225712062657642
12.225711105900665
12.225710149351357
12.225709193009672
12.225708236875558
12.225707280948967
12.22570632522988
12.22570536971821
12.225704414413931
12.225703459317023
12.225702504427396
12.225701549745041
12.2257005952699
12.225699641001924
12.225698686941074
12.225697733087294
12.225696779440558
12.225695826000816
12.225694872768006
12.225693919742104
12.22569296692305
12.225692014310802
12.225691061905327
12.225690109706562
12.225689157714484
12.225688205929025
12.22568725435016
12.22568630297783
12.225685351812
12.225684400852616
12.225683450099638
12.225682499553018
12.225681549212718
12.225680599078688
12.225679649150893
12.22567869942928
12.225677749913787
12.22567680060439
12.225675851501043
12.22567490260371
12.225673953912322
12.225673005426856
12.225672057147255
12.225671109073481
12.225670161205484
12.225669213543217
12.225668266086641
12.22566731883572
12.225666371790384
12.225665424950623
12.225664478316359
12.225663531887571
12.2256625856642
12.225661639646205
12.225660693833552
12.225659748226173
12.225658802824052
12.225657857627128
12.22565691263535
12.225655967848692
12.225655023267093
12.22565407889052
12.225653134718927
12.225652190752262
12.225651246990484
12.225650303433545
12.225649360081414
12.225648416934028
12.225647473991364
12.22564653125336
12.225645588719972

12.22564464639117
12.2256437042669
12.225642762347105
12.225641820631767
12.22564087912083
12.225639937814229
12.22563899671196
12.225638055813953
12.225637115120156
12.225636174630543
12.225635234345061
12.22563429426368
12.225633354386325
12.225632414712983
12.225631475243594
12.225630535978123
12.22562959691651
12.22562865805872
12.225627719404718
12.22562678095444
12.225625842707853
12.225624904664919
12.225623966825584
12.225623029189812
12.225622091757543
12.225621154528755
12.22562021750339
12.225619280681402
12.225618344062752
12.225617407647391
12.225616471435288
12.225615535426387
12.225614599620648
12.225613664018022
12.22561272861847
12.225611793421944
12.225610858428402
12.225609923637808
12.2256089890501
12.22560805466524
12.225607120483202
12.225606186503928
12.225605252727368
12.22560431915348
12.22560338578224
12.225602452613565
12.225601519647453
12.22560058688383
12.22559965432267
12.225598721963912
12.225597789807535
12.225596857853482
12.225595926101702
12.225594994552162
12.22559406320482
12.225593132059624
12.225592201116523
12.225591270375489
12.225590339836474
12.225589409499436
12.225588479364315
12.225587549431095
12.225586619699708
12.225585690170119
12.22558476084229
12.225583831716168
12.225582902791716
12.225581974068874
12.225581045547628
12.225580117227908
12.225579189109688
12.225578261192899
12.225577333477535
12.225576405963514
12.225575478650825
12.225574551539404
12.225573624629208
12.225572697920194
12.225571771412325
12.225570845105556
12.225569918999849
12.22556899309515
12.225568067391412
12.225567141888595
12.225566216586667
12.225565291485578
12.225564366585282
12.225563441885726
12.225562517386882
12.225561593088699
12.225560668991134
12.225559745094142
12.225558821397685
12.22555789790172
12.225556974606198
12.225556051511068
12.225555128616302
12.225554205921854
12.225553283427667
12.225552361133714
12.225551439039949
12.225550517146313
12.225549595452783
12.22554867395931
12.22554775266583
12.225546831572338
12.225545910678756
12.225544989985059
12.225544069491193
12.22554314919712
12.225542229102802
12.225541309208182
12.225540389513231
12.225539470017907
12.225538550722149
12.22553763162592
12.225536712729195
12.225535794031911
12.225534875534027
12.225533957235509
12.22553303913629
12.225532121236364
12.225531203535654
12.225530286034143
12.22552936873177
12.225528451628495
12.225527534724282
12.225526618019082
12.225525701512847
12.22552478520554
12.225523869097124
12.225522953187546
12.225522037476766
12.225521121964741
12.225520206651426
12.225519291536786
12.225518376620762
12.225517461903324
12.225516547384428
12.225515633064028
12.22551471894207
12.225513805018533
12.22551289129337
12.225511977766516
12.22551106443795
12.225510151307628
12.225509238375489
12.225508325641512
12.22550741310563
12.225506500767825
12.225505588628039
12.225504676686237
12.225503764942358
12.225502853396394
12.225501942048268
12.225501030897949
12.225500119945398
12.225499209190568
12.225498298633415
12.225497388273903
12.225496478111978
12.225495568147611
12.225494658380743
12.225493748811347
12.225492839439378
12.225491930264779
12.225491021287517
12.225490112507552
12.225489203924832
12.225488295539325
12.225487387350979
12.225486479359759
12.225485571565612
12.225484663968503
12.225483756568394
12.225482849365234
12.225481942358975
12.225481035549592
12.22548012893702
12.22547922252124
12.225478316302187
12.22547741027984
12.225476504454141
12.225475598825044
12.22547469339252
12.22547378815652
12.225472883116991
12.22547197827392
12.22547107362723
12.2254701691769
12.22546926492288
12.225468360865124
12.225467457003603
12.225466553338254
12.225465649869047
12.225464746595948
12.225463843518893
12.225462940637852
12.225462037952786
12.225461135463643
12.225460233170384
12.225459331072976
12.22545842917136
12.225457527465503
12.225456625955362
12.225455724640895
12.225454823522057
12.2254539225988
12.2254530218711
12.225452121338899
12.225451221002158
12.225450320860832
12.225449420914883
12.22544852116427
12.225447621608938
12.225446722248863
12.22544582308399
12.225444924114289
12.225444025339694
12.225443126760197
12.225442228375718
12.22544133018624
12.22544043219172
12.225439534392104
12.225438636787358
12.225437739377433
12.225436842162292
12.225435945141884
12.22543504831619
12.225434151685135
12.225433255248703
12.225432359006842
12.22543146295951
12.225430567106665
12.225429671448266
12.225428775984264
12.22542788071462
12.225426985639311
12.22542609075826
12.22542519607145
12.225424301578826
12.225423407280354
12.225422513175992
12.225421619265697
12.225420725549421
12.22541983202712
12.225418938698768
12.225418045564313
12.225417152623702
12.225416259876917
12.225415367323896
12.225414474964596
12.225413582798991
12.225412690827032
12.22541179904867
12.225410907463873
12.22541001607259
12.225409124874794
12.225408233870418
12.22540734305944
12.225406452441806
12.225405562017489
12.225404671786432
12.225403781748614
12.225402891903965
12.225402002252451
12.225401112794048
12.225400223528695
12.225399334456354
12.225398445576996
12.22539755689056
12.22539666839702
12.225395780096322
12.225394891988435
12.225394004073303
12.2253931163509
12.225392228821178
12.225391341484091
12.225390454339596
12.22538956738766
12.225388680628239
12.225387794061284
12.22538690768676
12.225386021504619
12.22538513551483
12.225384249717345
12.22538336411212
12.225382478699114
12.225381593478287
12.225380708449594
12.225379823613011
12.225378938968465
12.22537805451594
12.225377170255376
12.225376286186744
12.225375402310004
12.22537451862511
12.225373635132007
12.225372751830681
12.225371868721064
12.22537098580313
12.22537010307684
12.225369220542131
12.225368338198988
12.225367456047351
12.22536657408719
12.225365692318457
12.225364810741105
12.225363929355105
12.225363048160409
12.22536216715698
12.225361286344755
12.225360405723734
12.225359525293834
12.225358645055044
12.2253577650073
12.225356885150577
12.225356005484825
12.225355126009998
12.225354246726058
12.225353367632975
12.225352488730701
12.225351610019185
12.225350731498398
12.2253498531683
12.22534897502882
12.225348097079957
12.225347219321657
12.225346341753866
12.22534546437655
12.22534458718967
12.225343710193187
12.225342833387067
12.225341956771233
12.225341080345682
12.225340204110354
12.225339328065207
12.22533845221021
12.225337576545325
12.225336701070493
12.225335825785695
12.225334950690863
12.225334075785979
12.225333201070992
12.225332326545859
12.225331452210536
12.225330578064986
12.225329704109187
12.225328830343066
12.225327956766598
12.22532708337975
12.225326210182454
12.225325337174695
12.225324464356417
12.225323591727578
12.225322719288155
12.225321847038096
12.225320974977347
12.225320103105881
12.225319231423663
12.225318359930636
12.225317488626764
12.225316617512012
12.225315746586336
12.225314875849687
12.225314005302048
12.225313134943347
12.225312264773562
12.225311394792639
12.225310525000554
12.225309655397256
12.2253087859827
12.225307916756865
12.225307047719678
12.225306178871124
12.225305310211148
12.225304441739718
12.225303573456785
12.225302705362312
12.225301837456263
12.2253009697386
12.225300102209266
12.225299234868222
12.225298367715444
12.225297500750887
12.225296633974493
12.225295767386239
12.225294900986073
12.22529403477396
12.225293168749856
12.225292302913724
12.225291437265534
12.225290571805207
12.225289706532743
12.225288841448084
12.22528797655119
12.225287111842027
12.225286247320545
12.225285382986712
12.22528451884047
12.225283654881794
12.225282791110656
12.225281927526982
12.225281064130764
12.22528020092193
12.225279337900448
12.225278475066307
12.22527761241944
12.225276749959804
12.225275887687358
12.22527502560208
12.22527416370391
12.225273301992816
12.225272440468757
12.225271579131688
12.225270717981573
12.225269857018384
12.22526899624205
12.22526813565255
12.225267275249843
12.225266415033879
12.225265555004642
12.225264695162055
12.225263835506114
12.225262976036742
12.225262116753937
12.22526125765762
12.225260398747782
12.225259540024371
12.225258681487341
12.225257823136657
12.225256964972283
12.225256106994152
12.225255249202268
12.225254391596561
12.225253534176998
12.225252676943533
12.225251819896126
12.225250963034759
12.225250106359354
12.225249249869902
12.225248393566346
12.225247537448656
12.225246681516776
12.22524582577068
12.225244970210325

12.225244114835668
12.225243259646664
12.225242404643295
12.225241549825492
12.225240695193225
12.225239840746456
12.225238986485147
12.22523813240925
12.225237278518748
12.225236424813563
12.225235571293677
12.225234717959056
12.225233864809644
12.22523301184541
12.225232159066316
12.225231306472306
12.225230454063356
12.225229601839418
12.225228749800468
12.225227897946445
12.225227046277318
12.225226194793038
12.225225343493582
12.225224492378896
12.22522364144894
12.225222790703684
12.225221940143074
12.22522108976708
12.225220239575668
12.225219389568792
12.225218539746397
12.225217690108463
12.225216840654939
12.225215991385788
12.225215142300975
12.225214293400452
12.225213444684183
12.225212596152131
12.225211747804254
12.2252108996405
12.225210051660852
12.225209203865248
12.22520835625366
12.225207508826053
12.225206661582368
12.22520581452258
12.225204967646656
12.22520412095453
12.225203274446194
12.225202428121582
12.225201581980667
12.225200736023412
12.225199890249764
12.225199044659693
12.225198199253157
12.225197354030113
12.22519650899053
12.225195664134365
12.225194819461565
12.225193974972104
12.225193130665946
12.225192286543036
12.225191442603347
12.225190598846838
12.225189755273458
12.22518891188318
12.225188068675955
12.225187225651759
12.225186382810529
12.225185540152243
12.22518469767685
12.225183855384326
12.225183013274622
12.22518217134768
12.22518132960349
12.225180488042
12.225179646663172
12.22517880546697
12.225177964453334
12.22517712362225
12.225176282973662
12.225175442507542
12.225174602223843
12.225173762122527
12.225172922203559
12.225172082466885
12.22517124291248
12.2251704035403
12.225169564350308
12.22516872534246
12.225167886516713
12.225167047873045
12.225166209411398
12.22516537113173
12.225164533034032
12.225163695118221
12.22516285738429
12.225162019832187
12.225161182461866
12.225160345273311
12.225159508266458
12.225158671441271
12.225157834797729
12.22515699833578
12.225156162055372
12.225155325956484
12.225154490039078
12.225153654303105
12.225152818748521
12.225151983375296
12.225151148183388
12.225150313172769
12.22514947834337
12.225148643695187
12.225147809228158
12.225146974942247
12.225146140837413
12.225145306913628
12.225144473170852
12.22514363960903
12.225142806228137
12.225141973028128
12.225141140008962
12.225140307170609
12.225139474513005
12.225138642036155
12.225137809739978
12.225136977624452
12.225136145689534
12.22513531393519
12.225134482361375
12.225133650968063
12.225132819755194
12.22513198872275
12.225131157870676
12.225130327198922
12.225129496707478
12.225128666396301
12.225127836265333
12.225127006314548
12.225126176543892
12.22512534695336
12.225124517542875
12.225123688312404
12.225122859261935
12.225122030391402
12.225121201700773
12.225120373190025
12.22511954485909
12.225118716707954
12.225117888736552
12.225117060944877
12.225116233332862
12.225115405900482
12.225114578647702
12.225113751574481
12.225112924680769
12.225112097966527
12.225111271431738
12.22511044507634
12.225109618900305
12.225108792903574
12.225107967086148
12.225107141447952
12.225106315988969
12.225105490709142
12.225104665608448
12.225103840686836
12.225103015944288
12.22510219138073
12.22510136699616
12.2251005427905
12.22509971876375
12.225098894915858
12.225098071246771
12.225097247756471
12.225096424444901
12.22509560131204
12.225094778357827
12.225093955582246
12.22509313298524
12.22509231056678
12.225091488326829
12.225090666265347
12.225089844382282
12.225089022677617
12.225088201151305
12.225087379803293
12.225086558633565
12.22508573764207
12.225084916828765
12.22508409619361
12.225083275736589
12.22508245545764
12.225081635356739
12.225080815433836
12.22507999568889
12.22507917612188
12.22507835673275
12.225077537521472
12.225076718487989
12.22507589963229
12.225075080954333
12.225074262454058
12.225073444131437
12.225072625986437
12.225071808019011
12.225070990229126
12.225070172616743
12.225069355181818
12.225068537924322
12.225067720844208
12.225066903941443
12.225066087215984
12.225065270667793
12.225064454296836
12.225063638103077
12.225062822086468
12.225062006246974
12.225061190584555
12.225060375099174
12.225059559790802
12.225058744659382
12.225057929704898
12.225057114927296
12.225056300326536
12.225055485902589
12.22505467165541
12.225053857584964
12.225053043691204
12.225052229974107
12.225051416433628
12.225050603069722
12.22504978988236
12.225048976871498
12.225048164037101
12.22504735137913
12.225046538897546
12.225045726592311
12.225044914463384
12.22504410251073
12.225043290734314
12.225042479134082
12.225041667710016
12.225040856462076
12.2250400453902
12.225039234494371
12.225038423774564
12.225037613230711
12.225036802862784
12.225035992670742
12.225035182654558
12.225034372814193
12.22503356314959
12.225032753660738
12.225031944347577
12.225031135210084
12.225030326248204
12.225029517461925
12.225028708851172
12.225027900415938
12.225027092156179
12.22502628407184
12.225025476162896
12.225024668429318
12.225023860871056
12.225023053488082
12.225022246280334
12.225021439247797
12.225020632390427
12.22501982570818
12.225019019201028
12.225018212868921
12.225017406711839
12.225016600729726
12.225015794922555
12.225014989290274
12.22501418383286
12.22501337855028
12.22501257344248
12.225011768509424
12.225010963751078
12.225010159167413
12.225009354758365
12.225008550523931
12.225007746464048
12.225006942578691
12.225006138867814
12.22500533533138
12.225004531969354
12.225003728781692
12.225002925768367
12.22500212292934
12.225001320264562
12.225000517774005
12.22499971545763
12.22499891331539
12.224998111347263
12.224997309553185
12.224996507933154
12.224995706487112
12.224994905215022
12.22499410411685
12.224993303192553
12.22499250244209
12.224991701865436
12.224990901462553
12.224990101233384
12.22498930117791
12.224988501296089
12.224987701587873
12.224986902053246
12.224986102692153
12.224985303504562
12.224984504490427
12.22498370564973
12.22498290698241
12.224982108488444
12.22498131016779
12.224980512020416
12.224979714046265
12.224978916245327
12.22497811861755
12.224977321162898
12.224976523881327
12.224975726772813
12.224974929837307
12.224974133074774
12.22497333648518
12.224972540068476
12.22497174382465
12.224970947753636
12.224970151855416
12.224969356129943
12.224968560577182
12.224967765197093
12.224966969989636
12.224966174954782
12.2249653800925
12.22496458540274
12.224963790885454
12.224962996540633
12.224962202368221
12.224961408368163
12.224960614540462
12.224959820885053
12.224959027401912
12.224958234090991
12.224957440952267
12.22495664798569
12.22495585519122
12.224955062568817
12.224954270118474
12.22495347784012
12.224952685733733
12.224951893799268
12.224951102036698
12.224950310445976
12.224949519027065
12.224948727779939
12.224947936704549
12.22494714580085
12.224946355068834
12.224945564508431
12.224944774119631
12.22494398390238
12.224943193856646
12.224942403982386
12.22494161427958
12.22494082474816
12.224940035388123
12.224939246199401
12.224938457181977
12.22493766833582
12.224936879660875
12.224936091157108
12.224935302824491
12.224934514662978
12.224933726672536
12.224932938853122
12.224932151204714
12.224931363727253
12.224930576420713
12.224929789285069
12.224929002320259
12.224928215526273
12.224927428903047
12.224926642450566
12.22492585616878
12.22492507005765
12.224924284117153
12.22492349834725
12.224922712747889
12.224921927319048
12.224921142060687
12.224920356972753
12.224919572055228
12.22491878730807
12.224918002731238
12.224917218324698
12.224916434088412
12.224915650022346
12.224914866126452
12.224914082400723
12.22491329884508
12.224912515459513
12.224911732243985
12.224910949198454
12.224910166322875
12.224909383617227
12.224908601081465
12.224907818715542
12.22490703651945
12.224906254493106
12.224905472636518
12.224904690949634
12.224903909432397
12.2249031280848
12.224902346906797
12.224901565898346
12.224900785059406
12.224900004389955
12.22489922388994
12.22489844355934
12.22489766339811
12.224896883406199
12.224896103583598
12.224895323930262
12.224894544446139
12.224893765131206
12.224892985985418
12.224892207008743
12.224891428201152
12.2248906495626
12.224889871093044
12.224889092792463
12.224888314660802
12.224887536698038
12.224886758904134
12.22488598127905
12.22488520382274
12.224884426535182
12.224883649416332
12.224882872466162
12.224882095684624
12.22488131907169
12.224880542627309
12.224879766351462
12.2248789902441
12.224878214305193
12.224877438534708
12.224876662932596
12.224875887498843
12.224875112233384
12.224874337136194
12.224873562207256
12.224872787446492
12.224872012853902
12.224871238429435
12.224870464173055
12.224869690084734
12.224868916164414
12.224868142412086
12.224867368827699
12.224866595411207
12.224865822162597
12.224865049081814
12.224864276168832
12.224863503423606
12.224862730846098
12.22486195843629
12.224861186194124
12.224860414119583
12.22485964221261
12.224858870473188
12.224858098901258
12.224857327496801
12.224856556259782
12.22485578519016
12.224855014287899
12.22485424355296
12.2248534729853
12.224852702584904
12.22485193235172
12.22485116228571
12.224850392386848
12.22484962265509
12.224848853090391
12.22484808369274
12.22484731446208
12.224846545398384
12.224845776501608
12.224845007771728
12.22484423920869
12.224843470812473
12.224842702583038
12.224841934520345
12.224841166624357
12.22484039889504
12.224839631332364
12.224838863936279
12.22483809670677
12.224837329643771
12.224836562747273
12.22483579601723
12.224835029453601
12.224834263056357
12.224833496825456
12.22483273076087
12.224831964862545
12.22483119913047
12.224830433564593
12.22482966816488
12.224828902931305
12.224828137863808
12.224827372962386
12.22482660822697
12.224825843657552
12.224825079254071
12.224824315016514
12.224823550944818
12.22482278703898
12.224822023298938
12.224821259724669
12.224820496316136
12.224819733073296
12.224818969996116
12.224818207084574
12.224817444338607
12.224816681758202
12.224815919343303
12.224815157093888

12.22481439500993
12.224813633091372
12.22481287133819
12.224812109750353
12.22481134832781
12.224810587070545
12.224809825978491
12.224809065051643
12.224808304289954
12.224807543693384
12.2248067832619
12.224806022995473
12.224805262894057
12.224804502957625
12.224803743186134
12.224802983579556
12.224802224137834
12.224801464860962
12.224800705748882
12.224799946801575
12.224799188018993
12.2247984294011
12.22479767094787
12.224796912659269
12.224796154535248
12.224795396575765
12.224794638780809
12.224793881150333
12.224793123684305
12.224792366382667
12.22479160924541
12.224790852272486
12.224790095463865
12.224789338819509
12.224788582339386
12.22478782602346
12.224787069871672
12.224786313884021
12.224785558060455
12.224784802400933
12.224784046905436
12.22478329157392
12.224782536406341
12.224781781402674
12.22478102656288
12.224780271886925
12.224779517374758
12.224778763026384
12.224778008841719
12.22477725482075
12.224776500963447
12.224775747269767
12.224774993739672
12.22477424037314
12.224773487170122
12.22477273413058
12.224771981254488
12.224771228541812
12.224770475992507
12.224769723606537
12.224768971383881
12.224768219324492
12.224767467428332
12.224766715695377
12.224765964125586
12.224765212718918
12.224764461475337
12.22476371039482
12.224762959477324
12.224762208722812
12.22476145813125
12.224760707702607
12.224759957436843
12.224759207333925
12.224758457393818
12.224757707616478
12.224756958001878
12.22475620854999
12.224755459260752
12.22475471013417
12.224753961170167
12.224753212368737
12.224752463729823
12.224751715253404
12.224750966939448
12.224750218787916
12.22474947079876
12.22474872297196
12.22474797530747
12.22474722780526
12.224746480465297
12.224745733287543
12.224744986271968
12.224744239418527
12.224743492727182
12.224742746197917
12.224741999830686
12.224741253625453
12.224740507582176
12.224739761700834
12.22473901598138
12.22473827042379
12.224737525028017
12.224736779794041
12.224736034721806
12.224735289811294
12.224734545062464
12.224733800475283
12.22473305604971
12.224732311785717
12.224731567683264
12.224730823742316
12.224730079962836
12.224729336344812
12.224728592888175
12.224727849592902
12.22472710645896
12.224726363486337
12.224725620674946
12.224724878024785
12.224724135535828
12.224723393208032
12.224722651041347
12.224721909035747
12.224721167191207
12.224720425507678
12.224719683985136
12.224718942623541
12.22471820142285
12.224717460383037
12.224716719504066
12.224715978785913
12.224715238228528
12.224714497831874
12.224713757595929
12.224713017520646
12.224712277606002
12.224711537851952
12.224710798258464
12.224710058825499
12.224709319553039
12.22470858044103
12.224707841489453
12.224707102698254
12.224706364067416
12.224705625596894
12.22470488728666
12.224704149136674
12.224703411146901
12.224702673317305
12.224701935647861
12.224701198138522
12.224700460789268
12.22469972360005
12.224698986570832
12.224698249701593
12.224697512992282
12.224696776442888
12.224696040053358
12.224695303823658
12.224694567753744
12.224693831843604
12.224693096093194
12.224692360502484
12.224691625071417
12.224690889799993
12.22469015468814
12.224689419735855
12.224688684943084
12.224687950309805
12.224687215835973
12.224686481521562
12.224685747366534
12.224685013370847
12.224684279534486
12.224683545857392
12.224682812339536
12.224682078980907
12.224681345781445
12.224680612741121
12.224679879859904
12.224679147137754
12.224678414574655
12.22467768217055
12.224676949925408
12.224676217839201
12.224675485911902
12.224674754143447
12.224674022533842
12.224673291083024
12.224672559790974
12.22467182865764
12.224671097683
12.224670366867016
12.224669636209667
12.224668905710896
12.224668175370686
12.224667445188988
12.224666715165776
12.224665985301016
12.224665255594669
12.22466452604671
12.224663796657103
12.224663067425803
12.22466233835278
12.224661609438005
12.224660880681443
12.224660152083048
12.224659423642807
12.224658695360665
12.224657967236595
12.22465723927058
12.22465651146255
12.224655783812489
12.224655056320374
12.224654328986158
12.224653601809814
12.224652874791294
12.224652147930584
12.224651421227623
12.224650694682401
12.22464996829488
12.22464924206502
12.224648515992774
12.224647790078132
12.22464706432104
12.22464633872149
12.224645613279426
12.224644887994804
12.224644162867607
12.224643437897821
12.224642713085363
12.22464198843024
12.224641263932396
12.224640539591809
12.224639815408441
12.224639091382246
12.224638367513208
12.224637643801291
12.224636920246443
12.224636196848648
12.22463547360786
12.224634750524057
12.224634027597189
12.22463330482725
12.22463258221417
12.22463185975794
12.224631137458514
12.224630415315875
12.224629693329966
12.224628971500765
12.22462824982824
12.224627528312345
12.224626806953058
12.224626085750351
12.224625364704167
12.224624643814494
12.224623923081285
12.224623202504516
12.224622482084142
12.224621761820137
12.224621041712462
12.224620321761092
12.22461960196598
12.2246188823271
12.224618162844424
12.224617443517902
12.22461672434751
12.224616005333214
12.224615286474991
12.22461456777278
12.224613849226564
12.224613130836316
12.224612412601994
12.22461169452356
12.224610976600987
12.224610258834238
12.22460954122327
12.224608823768069
12.224608106468594
12.224607389324804
12.224606672336668
12.224605955504146
12.224605238827225
12.224604522305857
12.224603805939994
12.224603089729637
12.224602373674724
12.224601657775233
12.224600942031126
12.224600226442375
12.224599511008934
12.224598795730785
12.224598080607883
12.22459736564019
12.224596650827687
12.224595936170335
12.224595221668094
12.22459450732094
12.224593793128827
12.224593079091738
12.224592365209629
12.22459165148247
12.224590937910202
12.224590224492836
12.224589511230326
12.224588798122612
12.224588085169675
12.224587372371486
12.224586659728024
12.22458594723923
12.22458523490508
12.224584522725534
12.224583810700576
12.224583098830164
12.22458238711426
12.224581675552836
12.224580964145844
12.22458025289328
12.22457954179508
12.22457883085123
12.22457812006168
12.224577409426413
12.224576698945388
12.224575988618579
12.22457527844593
12.224574568427437
12.224573858563055
12.224573148852736
12.224572439296473
12.224571729894205
12.224571020645914
12.224570311551568
12.224569602611137
12.224568893824582
12.224568185191853
12.224567476712942
12.2245667683878
12.224566060216409
12.22456535219872
12.224564644334704
12.224563936624328
12.224563229067556
12.224562521664373
12.22456181441472
12.224561107318584
12.224560400375921
12.224559693586691
12.224558986950871
12.224558280468433
12.224557574139332
12.224556867963535
12.224556161941022
12.224555456071746
12.224554750355674
12.224554044792784
12.224553339383032
12.224552634126386
12.224551929022821
12.224551224072288
12.224550519274782
12.224549814630235
12.224549110138632
12.224548405799949
12.224547701614142
12.224546997581166
12.224546293701003
12.224545589973623
12.224544886398984
12.22454418297705
12.22454347970779
12.22454277659118
12.224542073627182
12.224541370815759
12.224540668156896
12.224539965650521
12.22453926329664
12.224538561095192
12.224537859046167
12.224537157149516
12.224536455405218
12.224535753813216
12.224535052373517
12.224534351086048
12.224533649950796
12.224532948967735
12.224532248136804
12.224531547458
12.224530846931271
12.2245301465566
12.22452944633393
12.22452874626326
12.224528046344535
12.224527346577718
12.224526646962788
12.22452594749971
12.224525248188455
12.224524549028974
12.22452385002125
12.224523151165247
12.22452245246092
12.224521753908265
12.224521055507223
12.224520357257765
12.224519659159862
12.224518961213478
12.224518263418588
12.224517565775148
12.224516868283137
12.224516170942511
12.224515473753247
12.224514776715308
12.224514079828651
12.22451338309326
12.224512686509092
12.224511990076126
12.224511293794306
12.224510597663619
12.224509901684028
12.224509205855494
12.224508510177992
12.224507814651497
12.224507119275946
12.224506424051334
12.224505728977626
12.224505034054774
12.224504339282761
12.22450364466154
12.224502950191095
12.224502255871382
12.224501561702366
12.224500867684014
12.224500173816311
12.224499480099206
12.224498786532672
12.224498093116669
12.224497399851185
12.224496706736161
12.224496013771583
12.22449532095741
12.224494628293607
12.224493935780163
12.224493243417013
12.224492551204147
12.224491859141523
12.224491167229106
12.224490475466881
12.224489783854784
12.224489092392817
12.224488401080919
12.224487709919078
12.224487018907245
12.224486328045401
12.224485637333508
12.224484946771533
12.224484256359444
12.224483566097206
12.224482875984789
12.224482186022161
12.224481496209291
12.224480806546136
12.224480117032684
12.224479427668886
12.224478738454712
12.22447804939013
12.224477360475115
12.224476671709624
12.224475983093628
12.224475294627089
12.224474606309997
12.22447391814229
12.224473230123955
12.224472542254949
12.224471854535253
12.224471166964815
12.224470479543626
12.224469792271629
12.224469105148804
12.224468418175123
12.224467731350554
12.224467044675057
12.224466358148602
12.224465671771151
12.224464985542685
12.224464299463156
12.224463613532551
12.224462927750814
12.224462242117939
12.224461556633864
12.22446087129859
12.224460186112053
12.224459501074245
12.224458816185118
12.224458131444653
12.224457446852801
12.224456762409533
12.224456078114834
12.224455393968663
12.224454709970981
12.224454026121759
12.22445334242097

12.224452658868572
12.224451975464532
12.224451292208848
12.224450609101442
12.224449926142313
12.224449243331415
12.224448560668726
12.224447878154203
12.224447195787816
12.224446513569545
12.224445831499342
12.22444514957719
12.224444467803046
12.224443786176876
12.224443104698649
12.224442423368352
12.224441742185915
12.22444106115134
12.224440380264584
12.224439699525611
12.224439018934403
12.224438338490891
12.224437658195086
12.224436978046944
12.224436298046419
12.22443561819348
12.22443493848812
12.224434258930282
12.224433579519932
12.224432900257057
12.224432221141612
12.224431542173571
12.224430863352895
12.224430184679557
12.224429506153532
12.224428827774771
12.224428149543257
12.22442747145895
12.224426793521827
12.22442611573184
12.224425438088973
12.224424760593184
12.224424083244452
12.224423406042725
12.224422728987992
12.224422052080222
12.224421375319354
12.22442069870539
12.224420022238277
12.224419345918001
12.224418669744516
12.224417993717777
12.224417317837789
12.224416642104494
12.224415966517869
12.224415291077877
12.224414615784491
12.224413940637668
12.224413265637391
12.224412590783627
12.224411916076324
12.224411241515487
12.224410567101051
12.224409892832995
12.224409218711289
12.2244085447359
12.224407870906802
12.22440719722395
12.224406523687325
12.22440585029689
12.224405177052612
12.224404503954455
12.224403831002412
12.224403158196422
12.224402485536464
12.224401813022508
12.224401140654514
12.224400468432457
12.224399796356321
12.224399124426037
12.224398452641603
12.224397781002981
12.224397109510134
12.22439643816304
12.224395766961644
12.22439509590596
12.224394424995914
12.224393754231482
12.224393083612643
12.224392413139372
12.224391742811612
12.224391072629352
12.22439040259255
12.22438973270118
12.22438906295522
12.22438839335462
12.224387723899353
12.224387054589398
12.22438638542471
12.224385716405255
12.224385047531023
12.224384378801963
12.224383710218056
12.224383041779259
12.224382373485547
12.224381705336892
12.224381037333254
12.224380369474604
12.22437970176092
12.224379034192157
12.224378366768288
12.224377699489281
12.224377032355106
12.224376365365742
12.224375698521138
12.224375031821276
12.224374365266117
12.224373698855633
12.224373032589796
12.224372366468568
12.224371700491925
12.22437103465983
12.22437036897225
12.224369703429158
12.224369038030527
12.224368372776315
12.2243677076665
12.224367042701036
12.224366377879912
12.224365713203083
12.224365048670524
12.224364384282195
12.224363720038083
12.224363055938136
12.224362391982332
12.224361728170633
12.224361064503023
12.224360400979455
12.224359737599908
12.224359074364342
12.224358411272734
12.224357748325055
12.224357085521268
12.224356422861328
12.224355760345228
12.224355097972921
12.22435443574439
12.224353773659592
12.2243531117185
12.224352449921073
12.224351788267294
12.224351126757128
12.224350465390541
12.224349804167508
12.224349143087982
12.224348482151944
12.224347821359375
12.224347160710215
12.224346500204453
12.224345839842055
12.224345179622985
12.224344519547222
12.224343859614722
12.224343199825453
12.224342540179409
12.224341880676526
12.224341221316791
12.224340562100167
12.224339903026628
12.224339244096134
12.224338585308681
12.224337926664191
12.224337268162673
12.224336609804075
12.224335951588374
12.224335293515546
12.22433463558554
12.224333977798354
12.224333320153919
12.224332662652243
12.224332005293268
12.224331348076987
12.224330691003335
12.224330034072304
12.22432937728386
12.224328720637972
12.224328064134614
12.22432740777374
12.22432675155534
12.224326095479363
12.224325439545785
12.22432478375458
12.224324128105716
12.224323472599158
12.224322817234881
12.22432216201284
12.224321506933025
12.224320851995387
12.224320197199908
12.22431954254655
12.224318888035285
12.224318233666068
12.224317579438893
12.224316925353722
12.224316271410512
12.22431561760924
12.224314963949874
12.224314310432392
12.224313657056742
12.224313003822921
12.224312350730875
12.224311697780589
12.224311044972014
12.224310392305132
12.224309739779917
12.224309087396332
12.224308435154347
12.224307783053925
12.224307131095044
12.224306479277669
12.224305827601762
12.224305176067318
12.224304524674276
12.224303873422627
12.224303222312322
12.224302571343348
12.224301920515655
12.224301269829235
12.224300619284048
12.22429996888005
12.224299318617229
12.224298668495544
12.224298018514967
12.224297368675467
12.224296718977019
12.224296069419585
12.224295420003132
12.224294770727631
12.224294121593068
12.224293472599392
12.224292823746577
12.224292175034595
12.224291526463418
12.224290878033008
12.224290229743355
12.224289581594395
12.224288933586122
12.224288285718497
12.224287637991493
12.22428699040507
12.224286342959214
12.224285695653885
12.224285048489042
12.224284401464676
12.224283754580746
12.224283107837215
12.224282461234063
12.224281814771267
12.224281168448766
12.224280522266564
12.224279876224603
12.22427923032286
12.224278584561322
12.224277938939942
12.2242772934587
12.22427664811755
12.224276002916467
12.22427535785543
12.224274712934404
12.224274068153363
12.224273423512257
12.224272779011079
12.224272134649793
12.224271490428357
12.22427084634676
12.224270202404941
12.224269558602895
12.224268914940597
12.224268271417998
12.22426762803507
12.224266984791797
12.224266341688136
12.22426569872405
12.224265055899535
12.22426441321453
12.224263770669033
12.224263128262992
12.224262485996384
12.224261843869177
12.224261201881347
12.224260560032858
12.224259918323682
12.224259276753795
12.224258635323142
12.224257994031731
12.224257352879498
12.224256711866438
12.224256070992498
12.224255430257669
12.224254789661906
12.22425414920518
12.224253508887465
12.224252868708735
12.22425222866895
12.224251588768096
12.224250949006127
12.22425030938301
12.224249669898724
12.224249030553242
12.224248391346531
12.224247752278552
12.22424711334929
12.224246474558703
12.224245835906755
12.22424519739344
12.22424455901871
12.224243920782527
12.22424328268489
12.224242644725734
12.224242006905072
12.224241369222828
12.224240731679002
12.224240094273545
12.224239457006439
12.224238819877655
12.224238182887154
12.224237546034916
12.224236909320906
12.224236272745092
12.224235636307446
12.224235000007937
12.22423436384653
12.22423372782321
12.224233091937936
12.22423245619068
12.224231820581423
12.22423118511011
12.224230549776731
12.22422991458124
12.224229279523636
12.224228644603858
12.224228009821886
12.224227375177698
12.22422674067126
12.224226106302543
12.224225472071518
12.224224837978142
12.224224204022399
12.224223570204257
12.224222936523681
12.224222302980651
12.224221669575128
12.224221036307085
12.224220403176489
12.224219770183316
12.224219137327532
12.224218504609107
12.224217872028019
12.22421723958423
12.224216607277713
12.22421597510843
12.224215343076366
12.22421471118148
12.224214079423746
12.224213447803141
12.224212816319621
12.224212184973162
12.224211553763746
12.22421092269132
12.224210291755885
12.224209660957378
12.224209030295786
12.224208399771088
12.224207769383241
12.224207139132217
12.224206509017996
12.224205879040529
12.224205249199807
12.224204619495785
12.224203989928442
12.224203360497741
12.224202731203667
12.224202102046172
12.224201473025236
12.224200844140835
12.22420021539293
12.22419958678149
12.224198958306488
12.224198329967905
12.224197701765693
12.22419707369984
12.224196445770303
12.22419581797706
12.224195190320073
12.224194562799324
12.224193935414771
12.224193308166395
12.224192681054165
12.224192054078046
12.224191427238015
12.224190800534036
12.224190173966079
12.224189547534124
12.224188921238131
12.224188295078076
12.22418766905394
12.224187043165662
12.224186417413252
12.224185791796645
12.224185166315836
12.224184540970784
12.224183915761454
12.224183290687836
12.224182665749892
12.22418204094758
12.224181416280889
12.224180791749776
12.224180167354216
12.224179543094182
12.22417891896964
12.224178294980575
12.224177671126938
12.2241770474087
12.224176423825854
12.22417580037835
12.224175177066162
12.224174553889267
12.22417393084763
12.224173307941225
12.224172685170014
12.224172062533983
12.224171440033087
12.224170817667309
12.224170195436617
12.224169573340982
12.224168951380364
12.22416832955475
12.224167707864092
12.224167086308382
12.224166464887576
12.224165843601641
12.224165222450562
12.224164601434309
12.22416398055283
12.224163359806132
12.224162739194153
12.22416211871689
12.224161498374285
12.224160878166343
12.224160258092994
12.22415963815425
12.22415901835006
12.224158398680382
12.22415777914522
12.224157159744525
12.224156540478269
12.224155921346423
12.224155302348953
12.224154683485839

12.224154064757052
12.224153446162559
12.22415282770233
12.22415220937633
12.224151591184553
12.224150973126944
12.224150355203497
12.22414973741415
12.224149119758895
12.224148502237705
12.224147884850554
12.2241472675974
12.224146650478225
12.224146033492982
12.22414541664167
12.224144799924234
12.224144183340664
12.224143566890916
12.224142950574977
12.224142334392813
12.224141718344372
12.22414110242965
12.224140486648615
12.224139871001235
12.22413925548748
12.22413864010732
12.224138024860718
12.224137409747671
12.22413679476813
12.22413617992207
12.224135565209458
12.224134950630269
12.224134336184477
12.224133721872045
12.224133107692948
12.224132493647161
12.224131879734651
12.224131265955396
12.22413065230935
12.224130038796499
12.224129425416812
12.224128812170266
12.224128199056814
12.22412758607644
12.224126973229112
12.22412636051481
12.224125747933483
12.224125135485128
12.22412452316969
12.224123910987164
12.224123298937512
12.224122687020703
12.224122075236716
12.224121463585503
12.224120852067058
12.224120240681339
12.22411962942833
12.224119018307983
12.224118407320278
12.224117796465192
12.22411718574269
12.224116575152737
12.224115964695317
12.224115354370397
12.224114744177948
12.224114134117942
12.224113524190344
12.224112914395143
12.224112304732282
12.22411169520175
12.224111085803523
12.224110476537557
12.224109867403836
12.22410925840233
12.224108649533004
12.224108040795823
12.224107432190781
12.22410682371783
12.22410621537695
12.224105607168111
12.224104999091281
12.22410439114643
12.224103783333534
12.22410317565257
12.224102568103497
12.224101960686287
12.224101353400927
12.22410074624737
12.224100139225591
12.224099532335575
12.224098925577279
12.224098318950682
12.224097712455748
12.22409710609245
12.224096499860773
12.224095893760671
12.224095287792123
12.224094681955112
12.224094076249576
12.224093470675522
12.224092865232908
12.22409225992169
12.224091654741871
12.224091049693389
12.224090444776248
12.224089839990393
12.224089235335814
12.224088630812473
12.224088026420334
12.224087422159382
12.224086818029598
12.22408621403092
12.224085610163348
12.22408500642684
12.224084402821383
12.224083799346928
12.22408319600345
12.224082592790943
12.224081989709362
12.224081386758666
12.224080783938849
12.224080181249874
12.224079578691708
12.224078976264328
12.224078373967705
12.224077771801811
12.22407716976661
12.224076567862086
12.2240759660882
12.224075364444932
12.224074762932242
12.224074161550124
12.224073560298525
12.224072959177438
12.224072358186813
12.224071757326636
12.224071156596864
12.224070555997496
12.224069955528481
12.224069355189794
12.224068754981413
12.224068154903303
12.224067554955447
12.2240669551378
12.224066355450354
12.22406575589306
12.224065156465894
12.224064557168845
12.224063958001867
12.224063358964944
12.224062760058038
12.22406216128112
12.224061562634166
12.224060964117152
12.224060365730049
12.224059767472815
12.224059169345425
12.224058571347877
12.224057973480114
12.224057375742122
12.224056778133864
12.224056180655321
12.224055583306455
12.224054986087243
12.224054388997654
12.22405379203767
12.224053195207256
12.22405259850638
12.224052001935007
12.224051405493134
12.224050809180708
12.224050212997719
12.22404961694413
12.22404902101991
12.224048425225039
12.224047829559483
12.224047234023207
12.224046638616207
12.224046043338424
12.224045448189852
12.224044853170463
12.224044258280212
12.224043663519081
12.224043068887047
12.224042474384076
12.224041880010136
12.224041285765214
12.224040691649268
12.224040097662275
12.224039503804208
12.22403891007503
12.224038316474724
12.224037723003262
12.224037129660609
12.224036536446736
12.224035943361624
12.224035350405241
12.224034757577563
12.224034164878542
12.22403357230818
12.224032979866436
12.224032387553267
12.224031795368665
12.22403120331261
12.224030611385045
12.224030019585951
12.224029427915317
12.224028836373105
12.224028244959285
12.22402765367383
12.224027062516708
12.224026471487907
12.224025880587376
12.2240252898151
12.224024699171059
12.22402410865522
12.224023518267542
12.224022928008008
12.224022337876587
12.22402174787327
12.224021157997996
12.224020568250749
12.22401997863152
12.22401938914026
12.22401879977695
12.224018210541555
12.224017621434067
12.224017032454425
12.224016443602634
12.224015854878651
12.22401526628245
12.224014677813994
12.224014089473275
12.22401350126025
12.2240129131749
12.224012325217185
12.224011737387091
12.224011149684582
12.224010562109646
12.224009974662222
12.224009387342313
12.22400880014988
12.224008213084893
12.224007626147335
12.224007039337167
12.224006452654363
12.224005866098908
12.22400527967075
12.224004693369887
12.224004107196274
12.224003521149895
12.22400293523071
12.224002349438702
12.224001763773837
12.22400117823609
12.224000592825442
12.22400000754184
12.223999422385285
12.22399883735574
12.223998252453164
12.223997667677539
12.223997083028852
12.223996498507057
12.223995914112129
12.22399532984404
12.223994745702772
12.223994161688289
12.223993577800574
12.223992994039579
12.223992410405296
12.22399182689768
12.223991243516721
12.223990660262386
12.223990077134646
12.223989494133468
12.223988911258838
12.223988328510707
12.223987745889069
12.223987163393886
12.223986581025136
12.223985998782787
12.223985416666814
12.223984834677188
12.223984252813883
12.223983671076867
12.22398308946612
12.223982507981612
12.223981926623306
12.223981345391191
12.223980764285235
12.223980183305393
12.223979602451665
12.223979021724002
12.223978441122393
12.223977860646801
12.223977280297197
12.22397670007356
12.223976119975859
12.223975540004071
12.223974960158156
12.223974380438106
12.22397380084387
12.223973221375454
12.223972642032791
12.22397206281589
12.2239714837247
12.223970904759195
12.223970325919362
12.223969747205164
12.223969168616573
12.223968590153564
12.223968011816115
12.223967433604185
12.223966855517768
12.223966277556812
12.223965699721301
12.223965122011219
12.223964544426522
12.223963966967194
12.22396338963319
12.2239628124245
12.223962235341098
12.22396165838295
12.223961081550033
12.223960504842308
12.223959928259758
12.22395935180236
12.223958775470091
12.223958199262897
12.223957623180773
12.2239570472237
12.22395647139161
12.223955895684524
12.223955320102394
12.223954744645182
12.223954169312881
12.223953594105456
12.223953019022874
12.223952444065121
12.22395186923215
12.223951294523951
12.223950719940495
12.22395014548175
12.223949571147692
12.22394899693829
12.223948422853516
12.223947848893351
12.223947275057764
12.22394670134673
12.223946127760211
12.223945554298195
12.223944980960647
12.223944407747537
12.223943834658844
12.22394326169454
12.2239426888546
12.223942116138987
12.223941543547692
12.223940971080669
12.223940398737899
12.223939826519354
12.223939254425018
12.223938682454849
12.223938110608824
12.223937538886918
12.223936967289102
12.223936395815356
12.223935824465642
12.223935253239938
12.223934682138214
12.223934111160466
12.223933540306628
12.22393296957671
12.223932398970652
12.223931828488453
12.223931258130074
12.22393068789548
12.223930117784677
12.223929547797594
12.223928977934243
12.223928408194567
12.223927838578554
12.223927269086186
12.223926699717419
12.223926130472227
12.223925561350606
12.223924992352494
12.223924423477891
12.223923854726756
12.223923286099076
12.223922717594808
12.223922149213935
12.223921580956429
12.223921012822272
12.223920444811414
12.22391987692384
12.223919309159538
12.223918741518462
12.223918174000591
12.223917606605905
12.22391703933436
12.22391647218595
12.223915905160634
12.223915338258399
12.223914771479198
12.22391420482303
12.223913638289837
12.223913071879615
12.223912505592338
12.223911939427968
12.223911373386485
12.223910807467853
12.223910241672064
12.223909675999073
12.223909110448863
12.223908545021404
12.223907979716671
12.223907414534636
12.223906849475277
12.223906284538575
12.223905719724465
12.22390515503296
12.223904590464016
12.223904026017617
12.223903461693732
12.223902897492328
12.223902333413381
12.22390176945687
12.22390120562277
12.223900641911044
12.223900078321666
12.223899514854628
12.223898951509875
12.223898388287406
12.223897825187182
12.22389726220917
12.22389669935336
12.223896136619713
12.223895574008207
12.223895011518817
12.223894449151523
12.223893886906275
12.223893324783074
12.223892762781867
12.223892200902643
12.22389163914539
12.223891077510052
12.223890515996617
12.22388995460506
12.223889393335357
12.223888832187473
12.223888271161394
12.223887710257069
12.223887149474495
12.223886588813642
12.223886028274478
12.223885467856972
12.223884907561104
12.223884347386852
12.223883787334184
12.223883227403073
12.223882667593502
12.223882107905428
12.223881548338845
12.223880988893708
12.223880429569991
12.223879870367684
12.223879311286753
12.223878752327165

12.223878193488895
12.223877634771924
12.223877076176228
12.22387651770176
12.223875959348513
12.223875401116464
12.223874843005575
12.22387428501582
12.223873727147177
12.223873169399617
12.223872611773116
12.22387205426765
12.223871496883193
12.223870939619708
12.223870382477177
12.223869825455576
12.223869268554878
12.223868711775049
12.223868155116069
12.22386759857792
12.223867042160553
12.223866485863972
12.22386592968812
12.223865373632991
12.223864817698557
12.22386426188478
12.223863706191645
12.223863150619126
12.223862595167185
12.22386203983581
12.22386148462497
12.223860929534633
12.223860374564786
12.223859819715383
12.22385926498642
12.223858710377849
12.223858155889662
12.223857601521829
12.22385704727432
12.223856493147096
12.223855939140163
12.223855385253467
12.223854831486987
12.223854277840713
12.223853724314607
12.223853170908638
12.223852617622788
12.223852064457018
12.223851511411326
12.223850958485661
12.22385040568001
12.223849852994352
12.223849300428645
12.223848747982869
12.223848195657013
12.223847643451029
12.223847091364908
12.223846539398608
12.223845987552115
12.223845435825403
12.223844884218444
12.223844332731202
12.22384378136366
12.223843230115797
12.22384267898759
12.223842127978989
12.22384157708999
12.22384102632056
12.22384047567067
12.223839925140313
12.223839374729431
12.22383882443802
12.223838274266045
12.22383772421349
12.223837174280327
12.223836624466522
12.223836074772048
12.223835525196893
12.223834975741019
12.2238344264044
12.223833877187012
12.223833328088842
12.223832779109845
12.223832230250006
12.223831681509296
12.223831132887689
12.223830584385158
12.223830036001681
12.223829487737229
12.223828939591778
12.223828391565302
12.22382784365778
12.223827295869166
12.223826748199459
12.223826200648618
12.223825653216627
12.223825105903453
12.223824558709078
12.223824011633457
12.223823464676594
12.223822917838442
12.223822371118967
12.223821824518172
12.223821278036016
12.22382073167246
12.223820185427506
12.223819639301103
12.223819093293242
12.223818547403901
12.22381800163303
12.223817455980623
12.223816910446645
12.223816365031078
12.223815819733904
12.223815274555067
12.22381472949457
12.223814184552367
12.22381363972846
12.223813095022797
12.223812550435358
12.223812005966128
12.22381146161508
12.223810917382163
12.223810373267384
12.223809829270708
12.223809285392093
12.223808741631535
12.223808197989003
12.223807654464462
12.223807111057893
12.22380656776926
12.223806024598566
12.223805481545762
12.223804938610815
12.223804395793717
12.223803853094443
12.22380331051296
12.22380276804924
12.223802225703263
12.223801683475
12.223801141364419
12.223800599371511
12.223800057496248
12.223799515738591
12.223798974098525
12.223798432576013
12.223797891171037
12.223797349883586
12.22379680871361
12.223796267661095
12.223795726726019
12.223795185908354
12.223794645208063
12.223794104625135
12.22379356415955
12.223793023811258
12.223792483580253
12.223791943466507
12.223791403469987
12.223790863590676
12.223790323828542
12.22378978418356
12.22378924465572
12.223788705244976
12.223788165951316
12.223787626774696
12.223787087715115
12.223786548772527
12.223786009946927
12.223785471238264
12.22378493264654
12.223784394171712
12.22378385581376
12.223783317572654
12.223782779448374
12.223782241440894
12.22378170355019
12.223781165776233
12.223780628118995
12.223780090578469
12.223779553154591
12.223779015847382
12.223778478656794
12.223777941582787
12.223777404625357
12.22377686778448
12.223776331060112
12.223775794452251
12.223775257960856
12.223774721585906
12.223774185327375
12.223773649185244
12.223773113159474
12.223772577250049
12.22377204145694
12.223771505780132
12.223770970219581
12.223770434775277
12.223769899447193
12.223769364235304
12.223768829139578
12.223768294159994
12.223767759296534
12.223767224549151
12.223766689917841
12.223766155402572
12.22376562100332
12.223765086720055
12.223764552552764
12.223764018501404
12.223763484565964
12.223762950746409
12.223762417042725
12.223761883454877
12.223761349982851
12.223760816626601
12.22376028338612
12.223759750261383
12.223759217252368
12.22375868435903
12.223758151581352
12.223757618919324
12.223757086372899
12.223756553942069
12.223756021626803
12.223755489427074
12.223754957342855
12.223754425374127
12.223753893520856
12.22375336178303
12.223752830160606
12.223752298653592
12.223751767261914
12.223751235985597
12.223750704824576
12.223750173778859
12.223749642848395
12.223749112033166
12.223748581333156
12.22374805074833
12.223747520278666
12.223746989924143
12.223746459684737
12.223745929560408
12.223745399551149
12.223744869656926
12.223744339877712
12.223743810213493
12.223743280664234
12.223742751229912
12.223742221910506
12.223741692705978
12.223741163616323
12.223740634641503
12.223740105781497
12.22373957703628
12.223739048405825
12.223738519890109
12.223737991489113
12.223737463202799
12.223736935031146
12.223736406974139
12.22373587903174
12.223735351203935
12.22373482349068
12.223734295891989
12.223733768407802
12.223733241038097
12.223732713782868
12.223732186642062
12.223731659615689
12.223731132703696
12.223730605906077
12.22373007922279
12.223729552653822
12.223729026199154
12.22372849985874
12.22372797363257
12.223727447520618
12.223726921522866
12.223726395639273
12.22372586986982
12.223725344214483
12.22372481867325
12.223724293246073
12.223723767932949
12.223723242733838
12.223722717648725
12.223722192677577
12.223721667820362
12.22372114307709
12.223720618447702
12.223720093932181
12.223719569530504
12.223719045242655
12.223718521068601
12.223717997008306
12.223717473061777
12.22371694922896
12.223716425509842
12.223715901904392
12.223715378412583
12.223714855034416
12.223714331769838
12.223713808618834
12.22371328558138
12.223712762657449
12.223712239847018
12.223711717150067
12.223711194566564
12.22371067209649
12.223710149739805
12.223709627496508
12.22370910536656
12.223708583349932
12.223708061446615
12.223707539656578
12.223707017979802
12.223706496416236
12.22370597496589
12.223705453628725
12.223704932404708
12.22370441129382
12.22370389029604
12.223703369411343
12.223702848639702
12.223702327981108
12.223701807435502
12.22370128700289
12.223700766683235
12.223700246476517
12.223699726382703
12.22369920640178
12.223698686533714
12.223698166778487
12.223697647136078
12.223697127606448
12.223696608189584
12.223696088885463
12.223695569694051
12.223695050615332
12.223694531649274
12.223694012795855
12.223693494055052
12.223692975426852
12.223692456911214
12.223691938508123
12.223691420217532
12.223690902039454
12.223690383973846
12.223689866020676
12.223689348179928
12.22368883045158
12.223688312835606
12.223687795331971
12.22368727794067
12.223686760661657
12.22368624349493
12.223685726440449
12.223685209498187
12.223684692668138
12.223684175950256
12.223683659344534
12.22368314285093
12.22368262646944
12.223682110200029
12.22368159404268
12.223681077997343
12.223680562064033
12.223680046242691
12.223679530533314
12.22367901493587
12.22367849945034
12.223677984076698
12.223677468814905
12.223676953664961
12.223676438626812
12.223675923700466
12.22367540888588
12.223674894183038
12.223674379591898
12.223673865112469
12.223673350744704
12.223672836488564
12.223672322344061
12.223671808311138
12.223671294389796
12.223670780579997
12.223670266881719
12.223669753294944
12.223669239819634
12.223668726455767
12.22366821320334
12.22366770006231
12.223667187032644
12.223666674114348
12.223666161307367
12.223665648611693
12.223665136027307
12.223664623554175
12.223664111192267
12.22366359894157
12.223663086802057
12.223662574773702
12.22366206285648
12.22366155105037
12.22366103935535
12.223660527771393
12.223660016298481
12.223659504936565
12.22365899368565
12.223658482545705
12.2236579715167
12.223657460598606
12.2236569497914
12.22365643909508
12.223655928509615
12.22365541803495
12.223654907671092
12.223654397418004
12.223653887275667
12.223653377244059
12.223652867323144
12.223652357512924
12.22365184781334
12.223651338224396
12.223650828746049
12.223650319378295
12.223649810121088
12.223649300974422
12.223648791938265
12.223648283012588
12.223647774197373
12.223647265492602
12.22364675689824
12.22364624841426
12.223645740040658
12.223645231777393
12.223644723624448
12.223644215581801
12.223643707649417
12.223643199827272
12.223642692115373
12.22364218451365
12.223641677022103
12.223641169640711
12.223640662369442
12.223640155208285
12.223639648157203
12.223639141216172
12.223638634385168
12.223638127664174
12.223637621053173
12.223637114552126
12.223636608161005
12.223636101879805
12.223635595708492
12.22363508964704
12.22363458369543
12.223634077853632
12.223633572121628
12.223633066499396
12.223632560986903
12.22363205558414
12.223631550291062
12.223631045107666
12.223630540033913
12.223630035069794
12.223629530215263
12.223629025470325
12.223628520834932
12.223628016309075
12.223627511892733
12.22362700758585
12.223626503388438
12.223625999300461
12.223625495321903
12.223624991452724
12.223624487692911
12.22362398404243
12.223623480501288
12.22362297706942
12.223622473746826
12.223621970533479
12.223621467429354
12.223620964434424
12.223620461548672
12.223619958772067
12.223619456104599
12.223618953546218
12.223618451096922
12.22361794875669
12.223617446525477
12.223616944403286
12.223616442390073
12.223615940485825
12.223615438690508
12.223614937004106
12.223614435426603
12.223613933957965
12.223613432598171
12.223612931347182
12.223612430205003
12.223611929171586
12.223611428246926
12.22361092743099
12.223610426723749
12.223609926125187
12.223609425635292
12.22360892525401
12.223608424981343
12.22360792481726
12.22360742476174
12.223606924814758
12.22360642497628
12.223605925246293
12.22360542562478
12.223604926111697
12.223604426707038
12.223603927410773
12.223603428222887
12.223602929143345
12.223602430172122
12.223601931309203
12.223601432554558
12.223600933908173
12.223600435370019
12.223599936940072
12.223599438618303
12.2235989404047
12.22359844229923
12.223597944301867

12.223597446412596
12.223596948631407
12.223596450958247
12.223595953393103
12.223595455935971
12.223594958586794
12.223594461345568
12.223593964212276
12.223593467186877
12.223592970269362
12.223592473459707
12.223591976757877
12.223591480163853
12.223590983677623
12.223590487299154
12.223589991028415
12.223589494865394
12.22358899881006
12.223588502862405
12.223588007022387
12.223587511289995
12.223587015665196
12.223586520147975
12.223586024738303
12.223585529436155
12.223585034241529
12.223584539154366
12.223584044174666
12.223583549302411
12.223583054537551
12.223582559880096
12.223582065329994
12.223581570887225
12.223581076551786
12.223580582323637
12.22358008820277
12.223579594189145
12.223579100282736
12.223578606483542
12.223578112791516
12.223577619206655
12.223577125728923
12.223576632358293
12.223576139094757
12.22357564593828
12.223575152888833
12.223574659946417
12.223574167110987
12.223573674382525
12.223573181761008
12.223572689246417
12.223572196838722
12.223571704537898
12.223571212343947
12.223570720256806
12.223570228276483
12.223569736402938
12.223569244636158
12.223568752976101
12.223568261422775
12.223567769976132
12.223567278636166
12.223566787402836
12.223566296276127
12.223565805256023
12.223565314342494
12.223564823535508
12.223564332835055
12.223563842241113
12.22356335175364
12.223562861372638
12.223562371098078
12.223561880929925
12.223561390868154
12.223560900912764
12.223560411063708
12.223559921320971
12.22355943168454
12.223558942154385
12.223558452730474
12.2235579634128
12.223557474201328
12.223556985096039
12.223556496096908
12.223556007203918
12.22355551841704
12.223555029736241
12.223554541161535
12.223554052692844
12.22355356433019
12.223553076073534
12.223552587922844
12.223552099878118
12.223551611939321
12.223551124106423
12.223550636379413
12.223550148758267
12.223549661242949
12.22354917383345
12.223548686529742
12.223548199331809
12.223547712239613
12.223547225253148
12.223546738372372
12.223546251597275
12.223545764927843
12.22354527836403
12.22354479190583
12.223544305553217
12.223543819306164
12.223543333164649
12.223542847128652
12.223542361198147
12.22354187537311
12.22354138965353
12.223540904039364
12.223540418530606
12.223539933127217
12.2235394478292
12.223538962636507
12.223538477549123
12.223537992567028
12.2235375076902
12.223537022918606
12.22353653825224
12.223536053691072
12.223535569235075
12.223535084884217
12.223534600638505
12.223534116497884
12.223533632462358
12.223533148531878
12.223532664706434
12.223532180986014
12.223531697370584
12.223531213860115
12.2235307304546
12.223530247153993
12.223529763958297
12.223529280867481
12.22352879788151
12.223528315000378
12.223527832224045
12.22352734955251
12.223526866985724
12.223526384523687
12.223525902166365
12.223525419913743
12.223524937765792
12.223524455722481
12.223523973783811
12.223523491949736
12.223523010220244
12.223522528595314
12.223522047074912
12.223521565659036
12.223521084347649
12.22352060314072
12.223520122038234
12.223519641040175
12.223519160146523
12.223518679357245
12.223518198672322
12.22351771809172
12.22351723761544
12.223516757243441
12.223516276975705
12.223515796812219
12.223515316752938
12.223514836797865
12.223514356946968
12.223513877200217
12.223513397557586
12.223512918019068
12.223512438584635
12.223511959254258
12.223511480027913
12.2235110009056
12.223510521887276
12.223510042972917
12.223509564162512
12.22350908545602
12.223508606853432
12.223508128354736
12.22350764995989
12.223507171668876
12.223506693481674
12.223506215398263
12.223505737418627
12.22350525954273
12.223504781770563
12.223504304102088
12.223503826537288
12.223503349076141
12.223502871718631
12.223502394464733
12.223501917314419
12.223501440267666
12.223500963324465
12.223500486484781
12.223500009748589
12.223499533115877
12.223499056586617
12.223498580160783
12.223498103838361
12.223497627619315
12.223497151503645
12.223496675491305
12.223496199582295
12.223495723776567
12.223495248074117
12.223494772474918
12.223494296978947
12.223493821586182
12.223493346296605
12.22349287111017
12.223492396026888
12.22349192104672
12.223491446169657
12.223490971395648
12.223490496724695
12.223490022156772
12.223489547691846
12.22348907332991
12.22348859907093
12.223488124914887
12.223487650861758
12.223487176911524
12.223486703064154
12.223486229319638
12.223485755677945
12.223485282139057
12.22348480870295
12.2234843353696
12.22348386213899
12.22348338901108
12.223482915985882
12.22348244306334
12.223481970243451
12.223481497526187
12.223481024911521
12.223480552399433
12.223480079989912
12.223479607682929
12.223479135478447
12.223478663376463
12.223478191376948
12.22347771947988
12.223477247685237
12.223476775992992
12.223476304403135
12.223475832915627
12.223475361530463
12.223474890247601
12.223474419067042
12.223473947988754
12.223473477012696
12.22347300613888
12.22347253536726
12.223472064697814
12.223471594130535
12.223471123665385
12.223470653302355
12.223470183041412
12.223469712882542
12.223469242825718
12.223468772870925
12.223468303018127
12.223467833267307
12.22346736361845
12.223466894071528
12.223466424626535
12.223465955283416
12.223465486042175
12.223465016902777
12.223464547865214
12.223464078929446
12.223463610095468
12.223463141363242
12.223462672732754
12.223462204203981
12.223461735776905
12.2234612674515
12.223460799227745
12.223460331105622
12.223459863085097
12.223459395166152
12.22345892734877
12.22345845963293
12.223457992018613
12.223457524505788
12.223457057094432
12.223456589784526
12.223456122576055
12.223455655468975
12.223455188463292
12.223454721558976
12.223454254755998
12.223453788054336
12.223453321453974
12.223452854954887
12.223452388557046
12.223451922260448
12.223451456065055
12.223450989970841
12.223450523977798
12.223450058085898
12.223449592295117
12.223449126605432
12.22344866101683
12.22344819552928
12.223447730142775
12.22344726485727
12.223446799672748
12.22344633458921
12.223445869606605
12.223445404724927
12.223444939944157
12.22344447526425
12.22344401068523
12.223443546207019
12.223443081829645
12.223442617553042
12.223442153377222
12.223441689302147
12.2234412253278
12.223440761454157
12.223440297681197
12.223439834008898
12.223439370437235
12.223438906966202
12.223438443595752
12.223437980325876
12.22343751715656
12.223437054087771
12.223436591119485
12.223436128251693
12.22343566548436
12.22343520281748
12.223434740251015
12.223434277784936
12.223433815419254
12.223433353153915
12.223432890988933
12.223432428924237
12.223431966959845
12.223431505095709
12.223431043331829
12.223430581668177
12.223430120104723
12.223429658641448
12.22342919727834
12.223428736015364
12.223428274852516
12.22342781378975
12.223427352827061
12.223426891964422
12.223426431201814
12.223425970539212
12.223425509976611
12.223425049513954
12.223424589151248
12.223424128888464
12.223423668725577
12.22342320866257
12.223422748699416
12.223422288836097
12.223421829072594
12.223421369408873
12.223420909844933
12.22342045038073
12.223419991016259
12.22341953175149
12.22341907258641
12.223418613520986
12.223418154555196
12.22341769568904
12.223417236922462
12.22341677825547
12.223416319688033
12.223415861220117
12.223415402851721
12.223414944582803
12.223414486413354
12.223414028343358
12.223413570372772
12.223413112501595
12.223412654729799
12.223412197057366
12.223411739484268
12.223411282010478
12.223410824635986
12.223410367360774
12.223409910184806
12.22340945310807
12.22340899613054
12.223408539252196
12.22340808247301
12.223407625792973
12.223407169212061
12.223406712730249
12.223406256347522
12.223405800063833
12.223405343879193
12.22340488779356
12.223404431806935
12.223403975919268
12.223403520130546
12.223403064440761
12.223402608849888
12.223402153357888
12.223401697964757
12.22340124267047
12.223400787475002
12.223400332378334
12.223399877380448
12.223399422481313
12.223398967680918
12.223398512979232
12.22339805837625
12.223397603871913
12.22339714946625
12.223396695159204
12.223396240950764
12.223395786840907
12.223395332829625
12.223394878916885
12.22339442510266
12.223393971386939
12.223393517769692
12.223393064250896
12.22339261083054
12.223392157508608
12.22339170428506
12.223391251159876
12.223390798133053
12.223390345204562
12.22338989237438
12.223389439642476
12.223388987008834
12.223388534473441
12.223388082036271
12.223387629697298
12.223387177456512
12.223386725313873
12.223386273269377
12.223385821322992
12.223385369474707
12.223384917724486
12.223384466072332
12.223384014518196
12.22338356306208
12.223383111703939
12.223382660443766
12.223382209281548
12.223381758217249
12.22338130725085
12.223380856382336
12.22338040561168
12.223379954938864
12.223379504363868
12.223379053886672
12.223378603507243
12.223378153225577
12.223377703041638
12.22337725295541
12.22337680296687
12.223376353076004
12.223375903282792
12.223375453587193
12.22337500398921
12.223374554488812
12.223374105085968
12.223373655780676
12.223373206572898
12.22337275746262
12.223372308449829
12.223371859534486
12.223371410716586
12.223370961996098
12.223370513373009
12.223370064847288
12.223369616418918

12.223369168087883
12.223368719854157
12.223368271717716
12.22336782367854
12.223367375736611
12.223366927891915
12.223366480144419
12.223366032494107
12.22336558494095
12.223365137484949
12.223364690126054
12.223364242864257
12.223363795699536
12.223363348631887
12.223362901661261
12.223362454787654
12.22336200801103
12.223361561331394
12.223361114748691
12.223360668262933
12.223360221874083
12.22335977558211
12.22335932938702
12.223358883288764
12.223358437287335
12.223357991382716
12.223357545574872
12.22335709986379
12.22335665424945
12.22335620873183
12.223355763310915
12.223355317986677
12.223354872759087
12.223354427628141
12.223353982593803
12.223353537656058
12.2233530928149
12.223352648070287
12.223352203422207
12.223351758870624
12.223351314415543
12.22335087005693
12.223350425794761
12.223349981629017
12.223349537559683
12.223349093586728
12.223348649710134
12.223348205929902
12.223347762245973
12.223347318658355
12.223346875167005
12.223346431771926
12.223345988473078
12.223345545270453
12.223345102164016
12.223344659153765
12.223344216239665
12.223343773421696
12.223343330699848
12.223342888074079
12.223342445544386
12.223342003110744
12.223341560773134
12.223341118531536
12.223340676385927
12.223340234336272
12.22333979238257
12.22333935052479
12.22333890876293
12.22333846709693
12.223338025526807
12.223337584052528
12.223337142674069
12.223336701391403
12.22333626020452
12.223335819113396
12.223335378118016
12.22333493721835
12.223334496414381
12.223334055706086
12.22333361509345
12.223333174576442
12.223332734155047
12.22333229382925
12.223331853599026
12.223331413464356
12.223330973425206
12.223330533481565
12.223330093633429
12.22332965388075
12.223329214223519
12.223328774661715
12.223328335195317
12.223327895824307
12.223327456548661
12.22332701736835
12.223326578283377
12.223326139293706
12.22332570039931
12.223325261600177
12.223324822896284
12.223324384287615
12.223323945774137
12.223323507355849
12.22332306903271
12.223322630804711
12.223322192671821
12.223321754634043
12.223321316691331
12.223320878843674
12.223320441091047
12.223320003433448
12.223319565870831
12.223319128403194
12.22331869103049
12.223318253752739
12.22331781656989
12.223317379481925
12.22331694248884
12.223316505590596
12.22331606878718
12.223315632078583
12.223315195464759
12.223314758945701
12.223314322521393
12.223313886191807
12.223313449956938
12.223313013816739
12.223312577771212
12.223312141820324
12.22331170596406
12.223311270202405
12.223310834535322
12.223310398962802
12.22330996348482
12.223309528101359
12.223309092812398
12.223308657617915
12.223308222517899
12.223307787512312
12.22330735260114
12.22330691778438
12.223306483061975
12.223306048433937
12.22330561390022
12.223305179460835
12.223304745115747
12.223304310864929
12.223303876708359
12.22330344264602
12.223303008677906
12.223302574803972
12.223302141024217
12.223301707338607
12.223301273747136
12.223300840249765
12.22330040684649
12.22329997353728
12.223299540322124
12.223299107200996
12.223298674173874
12.223298241240743
12.223297808401579
12.223297375656353
12.223296943005067
12.223296510447684
12.223296077984187
12.223295645614545
12.223295213338764
12.223294781156799
12.223294349068636
12.223293917074264
12.223293485173642
12.223293053366792
12.223292621653641
12.223292190034195
12.223291758508433
12.223291327076337
12.22329089573788
12.22329046449304
12.223290033341812
12.223289602284162
12.223289171320065
12.223288740449519
12.22328830967248
12.223287878988947
12.22328744839889
12.223287017902292
12.22328658749914
12.223286157189403
12.223285726973065
12.223285296850108
12.223284866820496
12.22328443688423
12.22328400704127
12.223283577291616
12.22328314763524
12.223282718072122
12.223282288602235
12.223281859225564
12.223281429942087
12.223281000751792
12.223280571654655
12.223280142650637
12.223279713739746
12.22327928492194
12.223278856197213
12.223278427565551
12.22327799902691
12.223277570581285
12.223277142228659
12.223276713969003
12.223276285802294
12.22327585772853
12.223275429747664
12.223275001859692
12.2232745740646
12.223274146362366
12.223273718752957
12.223273291236364
12.223272863812547
12.22327243648151
12.223272009243237
12.22327158209768
12.223271155044847
12.223270728084692
12.223270301217221
12.223269874442394
12.223269447760195
12.22326902117061
12.223268594673616
12.223268168269193
12.223267741957315
12.223267315737981
12.22326688961114
12.2232664635768
12.223266037634929
12.223265611785502
12.223265186028508
12.22326476036393
12.223264334791738
12.223263909311916
12.223263483924441
12.223263058629296
12.223262633426458
12.223262208315916
12.223261783297641
12.223261358371612
12.223260933537821
12.223260508796232
12.223260084146839
12.223259659589607
12.223259235124534
12.223258810751576
12.223258386470746
12.223257962281995
12.223257538185315
12.22325711418068
12.223256690268087
12.22325626644749
12.223255842718897
12.223255419082259
12.223254995537571
12.223254572084826
12.223254148723973
12.223253725455026
12.223253302277946
12.22325287919271
12.223252456199312
12.22325203329771
12.223251610487912
12.22325118776988
12.2232507651436
12.223250342609035
12.2232499201662
12.223249497815043
12.223249075555563
12.223248653387738
12.223248231311535
12.223247809326946
12.223247387433954
12.223246965632528
12.223246543922647
12.223246122304305
12.223245700777477
12.223245279342128
12.22324485799827
12.223244436745851
12.223244015584868
12.223243594515296
12.223243173537115
12.223242752650307
12.223242331854859
12.223241911150735
12.22324149053793
12.223241070016416
12.223240649586172
12.223240229247184
12.223239808999436
12.2232393888429
12.223238968777551
12.223238548803387
12.223238128920372
12.223237709128483
12.223237289427727
12.22323686981806
12.22323645029946
12.223236030871929
12.22323561153542
12.223235192289934
12.223234773135442
12.223234354071932
12.223233935099378
12.223233516217762
12.223233097427055
12.223232678727259
12.223232260118332
12.223231841600265
12.223231423173035
12.223231004836633
12.223230586591015
12.22323016843619
12.223229750372122
12.223229332398786
12.223228914516183
12.22322849672428
12.223228079023047
12.223227661412487
12.223227243892556
12.223226826463259
12.223226409124551
12.223225991876436
12.223225574718887
12.223225157651871
12.223224740675384
12.223224323789404
12.223223906993907
12.223223490288873
12.223223073674275
12.22322265715012
12.223222240716359
12.223221824372988
12.223221408119988
12.22322099195734
12.223220575884998
12.223220159902983
12.223219744011248
12.223219328209787
12.223218912498565
12.22321849687759
12.223218081346806
12.22321766590622
12.223217250555805
12.22321683529554
12.223216420125409
12.223216005045392
12.223215590055458
12.223215175155604
12.223214760345803
12.223214345626028
12.223213930996279
12.223213516456513
12.22321310200673
12.223212687646907
12.223212273377014
12.223211859197043
12.223211445106958
12.223211031106763
12.22321061719642
12.223210203375919
12.223209789645226
12.223209376004345
12.223208962453237
12.223208548991893
12.22320813562029
12.22320772233841
12.223207309146233
12.223206896043731
12.223206483030893
12.22320607010771
12.223205657274143
12.223205244530181
12.223204831875805
12.223204419310992
12.223204006835735
12.223203594450002
12.22320318215376
12.223202769947031
12.223202357829758
12.22320194580194
12.223201533863536
12.223201122014554
12.223200710254977
12.223200298584754
12.223199887003885
12.223199475512356
12.223199064110137
12.223198652797215
12.223198241573561
12.223197830439169
12.223197419394003
12.223197008438056
12.223196597571315
12.223196186793752
12.223195776105339
12.223195365506086
12.223194954995925
12.223194544574882
12.22319413424291
12.223193724000005
12.223193313846142
12.2231929037813
12.223192493805467
12.223192083918613
12.22319167412073
12.223191264411797
12.223190854791778
12.223190445260675
12.223190035818462
12.223189626465109
12.223189217200607
12.223188808024936
12.223188398938085
12.223187989940016
12.223187581030722
12.223187172210183
12.223186763478372
12.223186354835276
12.223185946280879
12.22318553781516
12.223185129438095
12.223184721149666
12.223184312949856
12.223183904838654
12.223183496816013
12.223183088881955
12.223182681036427
12.223182273279425
12.223181865610917
12.223181458030897
12.223181050539349
12.223180643136235
12.223180235821557
12.223179828595278
12.223179421457392
12.223179014407874
12.223178607446703
12.22317820057386
12.223177793789338
12.223177387093095
12.22317698048514
12.223176573965421
12.223176167533953
12.223175761190692
12.223175354935627
12.223174948768746
12.223174542690016
12.223174136699424
12.22317373079695
12.223173324982582
12.223172919256292
12.223172513618069
12.223172108067885
12.223171702605717
12.223171297231573
12.2231708919454
12.223170486747204
12.223170081636948
12.223169676614619
12.223169271680206
12.223168866833676
12.22316846207502
12.223168057404212
12.22316765282125
12.2231672483261
12.22316684391873
12.223166439599156
12.223166035367324
12.223165631223239
12.223165227166868
12.223164823198196
12.223164419317204
12.22316401552387
12.223163611818187
12.223163208200127
12.223162804669677
12.223162401226796
12.223161997871504
12.223161594603742
12.223161191423507
12.223160788330794
12.223160385325558
12.223159982407806
12.223159579577493
12.223159176834626

12.223158774179177
12.223158371611111
12.223157969130432
12.223157566737102
12.223157164431116
12.223156762212446
12.223156360081092
12.223155958036998
12.22315555608017
12.223155154210602
12.223154752428252
12.2231543507331
12.22315394912515
12.223153547604355
12.22315314617071
12.223152744824205
12.22315234356481
12.2231519423925
12.223151541307267
12.22315114030909
12.22315073939795
12.223150338573818
12.2231499378367
12.223149537186554
12.22314913662337
12.223148736147122
12.223148335757806
12.223147935455385
12.223147535239853
12.223147135111185
12.22314673506937
12.223146335114375
12.223145935246196
12.223145535464806
12.223145135770178
12.223144736162322
12.223144336641186
12.223143937206771
12.223143537859057
12.223143138598013
12.223142739423634
12.223142340335889
12.223141941334767
12.22314154242025
12.223141143592313
12.223140744850944
12.223140346196118
12.223139947627821
12.223139549146039
12.223139150750736
12.223138752441908
12.223138354219536
12.223137956083596
12.22313755803407
12.223137160070939
12.223136762194192
12.223136364403798
12.223135966699731
12.223135569082002
12.22313517155057
12.223134774105427
12.223134376746538
12.2231339794739
12.223133582287494
12.223133185187297
12.223132788173286
12.223132391245448
12.223131994403754
12.223131597648207
12.22313120097877
12.223130804395426
12.223130407898164
12.223130011486951
12.223129615161792
12.223129218922647
12.223128822769507
12.223128426702354
12.223128030721174
12.223127634825927
12.223127239016604
12.223126843293203
12.22312644765569
12.22312605210405
12.22312565663826
12.223125261258312
12.223124865964177
12.223124470755838
12.223124075633278
12.22312368059649
12.223123285645427
12.223122890780099
12.223122496000482
12.223122101306535
12.223121706698262
12.223121312175632
12.223120917738648
12.223120523387262
12.223120129121476
12.223119734941267
12.223119340846607
12.223118946837483
12.223118552913885
12.223118159075787
12.22311776532317
12.223117371656016
12.22311697807431
12.223116584578015
12.223116191167149
12.223115797841661
12.223115404601545
12.223115011446781
12.223114618377348
12.223114225393232
12.22311383249442
12.223113439680876
12.223113046952605
12.223112654309562
12.223112261751739
12.223111869279123
12.223111476891695
12.223111084589439
12.223110692372327
12.223110300240343
12.223109908193473
12.223109516231693
12.223109124354991
12.223108732563354
12.223108340856738
12.22310794923515
12.223107557698562
12.223107166246953
12.223106774880314
12.223106383598621
12.223105992401846
12.223105601289987
12.223105210263014
12.223104819320922
12.223104428463673
12.223104037691263
12.223103647003668
12.22310325640087
12.223102865882854
12.2231024754496
12.223102085101088
12.223101694837302
12.223101304658218
12.22310091456383
12.2231005245541
12.223100134629025
12.223099744788588
12.223099355032758
12.223098965361531
12.22309857577487
12.223098186272777
12.22309779685522
12.223097407522195
12.223097018273673
12.22309662910963
12.223096240030051
12.223095851034927
12.223095462124228
12.223095073297955
12.22309468455607
12.223094295898552
12.223093907325401
12.223093518836587
12.223093130432094
12.223092742111906
12.22309235387599
12.22309196572435
12.223091577656957
12.223091189673793
12.223090801774841
12.223090413960085
12.223090026229496
12.223089638583069
12.223089251020772
12.223088863542607
12.223088476148535
12.223088088838548
12.223087701612625
12.223087314470753
12.2230869274129
12.223086540439061
12.223086153549222
12.22308576674335
12.22308538002144
12.22308499338346
12.2230846068294
12.223084220359242
12.22308383397297
12.223083447670561
12.223083061451987
12.223082675317261
12.223082289266339
12.223081903299203
12.22308151741584
12.223081131616233
12.223080745900374
12.223080360268224
12.22307997471977
12.223079589255002
12.223079203873908
12.223078818576452
12.223078433362627
12.22307804823241
12.223077663185782
12.223077278222725
12.223076893343228
12.22307650854728
12.223076123834833
12.223075739205898
12.223075354660446
12.223074970198459
12.223074585819914
12.2230742015248
12.223073817313098
12.223073433184798
12.22307304913985
12.223072665178274
12.223072281300027
12.223071897505104
12.22307151379349
12.223071130165149
12.223070746620085
12.223070363158266
12.223069979779671
12.223069596484292
12.223069213272094
12.223068830143092
12.22306844709724
12.22306806413452
12.223067681254934
12.223067298458439
12.22306691574504
12.2230665331147
12.223066150567417
12.22306576810316
12.223065385721917
12.22306500342367
12.223064621208394
12.223064239076082
12.223063857026718
12.223063475060263
12.223063093176728
12.223062711376077
12.223062329658289
12.223061948023354
12.223061566471255
12.22306118500197
12.223060803615478
12.223060422311777
12.223060041090827
12.223059659952616
12.22305927889714
12.223058897924364
12.223058517034287
12.223058136226877
12.223057755502122
12.223057374859994
12.223056994300496
12.223056613823594
12.223056233429269
12.223055853117513
12.223055472888294
12.223055092741617
12.223054712677452
12.223054332695765
12.22305395279656
12.223053572979813
12.223053193245503
12.223052813593611
12.223052434024117
12.223052054537021
12.223051675132274
12.223051295809897
12.223050916569843
12.223050537412108
12.223050158336653
12.223049779343484
12.223049400432572
12.223049021603904
12.223048642857458
12.223048264193224
12.22304788561118
12.223047507111303
12.223047128693578
12.223046750357991
12.223046372104516
12.223045993933148
12.223045615843855
12.223045237836628
12.223044859911438
12.223044482068289
12.22304410430714
12.223043726627994
12.223043349030814
12.223042971515598
12.223042594082314
12.223042216730956
12.223041839461498
12.22304146227393
12.223041085168221
12.223040708144373
12.223040331202352
12.223039954342147
12.223039577563735
12.223039200867106
12.223038824252242
12.223038447719116
12.223038071267716
12.223037694898021
12.223037318610032
12.223036942403702
12.223036566279022
12.223036190235986
12.22303581427458
12.22303543839477
12.223035062596534
12.223034686879872
12.223034311244753
12.223033935691177
12.223033560219104
12.223033184828532
12.223032809519431
12.223032434291786
12.223032059145604
12.223031684080828
12.223031309097463
12.223030934195497
12.223030559374894
12.223030184635656
12.22302980997774
12.223029435401148
12.223029060905859
12.223028686491855
12.22302831215911
12.223027937907613
12.22302756373736
12.223027189648313
12.223026815640461
12.223026441713788
12.22302606786827
12.223025694103892
12.223025320420648
12.223024946818509
12.223024573297462
12.223024199857479
12.223023826498562
12.223023453220664
12.223023080023804
12.223022706907939
12.223022333873052
12.22302196091914
12.223021588046167
12.223021215254139
12.223020842543018
12.2230204699128
12.223020097363442
12.223019724894971
12.22301935250732
12.223018980200507
12.22301860797451
12.223018235829294
12.223017863764856
12.223017491781162
12.223017119878218
12.223016748055992
12.22301637631447
12.223016004653635
12.223015633073464
12.223015261573941
12.223014890155067
12.223014518816795
12.22301414755913
12.223013776382032
12.223013405285506
12.223013034269528
12.223012663334078
12.223012292479135
12.223011921704689
12.22301155101072
12.22301118039721
12.223010809864133
12.223010439411487
12.223010069039237
12.223009698747388
12.22300932853591
12.22300895840478
12.223008588353993
12.223008218383516
12.223007848493348
12.22300747868346
12.223007108953839
12.223006739304472
12.223006369735332
12.2230060002464
12.223005630837676
12.223005261509122
12.223004892260732
12.223004523092495
12.223004154004379
12.22300378499638
12.223003416068465
12.223003047220628
12.223002678452849
12.22300230976511
12.223001941157394
12.223001572629682
12.22300120418196
12.223000835814215
12.223000467526413
12.223000099318556
12.222999731190614
12.222999363142579
12.222998995174416
12.222998627286133
12.22299825947769
12.22299789174908
12.22299752410029
12.222997156531292
12.222996789042078
12.222996421632633
12.222996054302918
12.222995687052945
12.222995319882674
12.222994952792103
12.222994585781208
12.222994218849976
12.222993851998366
12.2229934852264
12.222993118534037
12.222992751921261
12.222992385388064
12.22299201893442
12.222991652560305
12.222991286265716
12.22299092005064
12.22299055391504
12.222990187858915
12.222989821882235
12.222989455984992
12.222989090167179
12.22298872442875
12.222988358769706
12.22298799319003
12.222987627689701
12.222987262268703
12.222986896927024
12.222986531664642
12.222986166481542
12.222985801377694
12.222985436353095
12.22298507140773
12.22298470654157
12.222984341754605
12.222983977046812
12.222983612418183
12.222983247868699
12.222982883398338
12.222982519007077
12.222982154694911
12.222981790461823
12.222981426307785
12.222981062232794
12.22298069823681
12.222980334319852
12.222979970481871
12.22297960672285
12.222979243042793
12.222978879441673
12.222978515919472
12.222978152476173
12.222977789111752
12.222977425826205
12.222977062619503
12.222976699491644
12.222976336442592
12.222975973472344
12.22297561058088
12.222975247768172
12.222974885034214
12.222974522378994
12.222974159802492
12.222973797304679
12.22297343488554
12.22297307254507
12.222972710283244
12.222972348100047
12.22297198599546
12.222971623969467
12.222971262022053
12.222970900153202
12.22297053836289
12.2229701766511
12.222969815017821
12.222969453463028
12.222969091986728
12.222968730588871
12.222968369269458
12.222968008028477
12.222967646865891
12.22296728578171
12.222966924775887
12.222966563848425
12.222966202999295
12.2229658422285
12.222965481536002
12.222965120921785
12.222964760385848
12.222964399928156
12.222964039548716
12.222963679247485
12.222963319024458
12.222962958879627
12.222962598812945
12.22296223882443
12.222961878914044
12.22296151908178
12.222961159327603
12.22296079965153
12.222960440053516
12.222960080533545
12.222959721091618
12.222959361727701
12.222959002441785
12.222958643233852
12.222958284103884
12.222957925051864
12.222957566077772
12.222957207181608
12.222956848363333

12.222956489622936
12.222956130960403
12.222955772375725
12.222955413868863
12.222955055439828
12.222954697088587
12.222954338815121
12.222953980619417
12.222953622501462
12.222953264461234
12.222952906498726
12.222952548613911
12.222952190806769
12.222951833077284
12.222951475425447
12.222951117851242
12.222950760354639
12.222950402935643
12.222950045594219
12.22294968833035
12.222949331144031
12.222948974035232
12.22294861700395
12.222948260050154
12.222947903173845
12.222947546374987
12.222947189653574
12.222946833009587
12.22294647644301
12.222946119953816
12.222945763542008
12.222945407207558
12.222945050950447
12.222944694770655
12.22294433866819
12.222943982642995
12.222943626695084
12.222943270824432
12.22294291503102
12.222942559314841
12.222942203675851
12.222941848114061
12.222941492629444
12.222941137221992
12.222940781891667
12.222940426638473
12.222940071462396
12.222939716363392
12.222939361341476
12.222939006396603
12.222938651528782
12.222938296737974
12.22293794202418
12.22293758738738
12.222937232827547
12.222936878344678
12.222936523938728
12.222936169609719
12.222935815357612
12.222935461182404
12.22293510708406
12.222934753062574
12.222934399117921
12.2229340452501
12.222933691459083
12.222933337744866
12.222932984107397
12.222932630546701
12.222932277062748
12.22293192365551
12.222931570324985
12.222931217071151
12.222930863893977
12.222930510793471
12.2229301577696
12.222929804822357
12.22292945195172
12.222929099157664
12.22292874644019
12.222928393799265
12.222928041234884
12.22292768874704
12.222927336335692
12.222926984000821
12.222926631742443
12.22292627956051
12.222925927455021
12.222925575425968
12.222925223473306
12.222924871597046
12.222924519797145
12.222924168073616
12.222923816426425
12.222923464855558
12.222923113360988
12.222922761942723
12.222922410600734
12.222922059334998
12.222921708145511
12.222921357032233
12.222921005995167
12.222920655034308
12.222920304149612
12.22291995334108
12.222919602608686
12.22291925195242
12.222918901372267
12.222918550868192
12.22291820044021
12.22291785008828
12.222917499812393
12.22291714961254
12.222916799488692
12.222916449440834
12.222916099468963
12.22291574957305
12.222915399753074
12.222915050009027
12.2229147003409
12.22291435074866
12.2229140012323
12.222913651791796
12.22291330242715
12.22291295313833
12.222912603925318
12.222912254788099
12.22291190572667
12.222911556741007
12.222911207831077
12.222910858996881
12.222910510238403
12.222910161555614
12.222909812948508
12.22290946441708
12.222909115961292
12.222908767581135
12.222908419276589
12.222908071047657
12.222907722894288
12.222907374816492
12.222907026814246
12.222906678887542
12.222906331036347
12.222905983260647
12.222905635560435
12.2229052879357
12.222904940386412
12.222904592912547
12.222904245514108
12.222903898191083
12.22290355094343
12.222903203771152
12.222902856674219
12.222902509652647
12.222902162706363
12.222901815835401
12.222901469039726
12.222901122319323
12.222900775674168
12.222900429104255
12.222900082609566
12.222899736190081
12.222899389845786
12.222899043576668
12.222898697382705
12.222898351263884
12.22289800522019
12.222897659251595
12.222897313358095
12.222896967539672
12.222896621796314
12.222896276127992
12.222895930534701
12.222895585016422
12.22289523957313
12.222894894204824
12.222894548911464
12.222894203693063
12.222893858549593
12.222893513481031
12.22289316848736
12.222892823568577
12.222892478724654
12.222892133955588
12.22289178926134
12.222891444641915
12.222891100097284
12.222890755627441
12.22289041123237
12.222890066912036
12.22288972266644
12.22288937849557
12.222889034399396
12.222888690377909
12.222888346431093
12.222888002558921
12.222887658761392
12.222887315038484
12.22288697139017
12.222886627816465
12.222886284317319
12.222885940892727
12.222885597542687
12.222885254267162
12.222884911066133
12.22288456793962
12.222884224887563
12.222883881909977
12.222883539006824
12.222883196178108
12.222882853423789
12.222882510743865
12.22288216813833
12.22288182560715
12.22288148315032
12.22288114076782
12.222880798459624
12.222880456225738
12.222880114066129
12.22287977198078
12.222879429969684
12.222879088032817
12.222878746170183
12.222878404381735
12.222878062667471
12.222877721027386
12.222877379461437
12.222877037969633
12.222876696551953
12.22287635520837
12.222876013938878
12.222875672743454
12.222875331622095
12.222874990574768
12.222874649601472
12.222874308702174
12.222873967876875
12.222873627125557
12.222873286448188
12.222872945844768
12.22287260531526
12.222872264859687
12.222871924478
12.222871584170187
12.222871243936243
12.222870903776144
12.222870563689886
12.222870223677432
12.222869883738767
12.222869543873898
12.222869204082803
12.222868864365445
12.222868524721827
12.222868185151933
12.222867845655735
12.222867506233229
12.22286716688439
12.222866827609206
12.222866488407668
12.222866149279753
12.222865810225436
12.222865471244717
12.222865132337573
12.22286479350399
12.222864454743945
12.222864116057426
12.222863777444422
12.222863438904906
12.222863100438879
12.222862762046313
12.222862423727197
12.222862085481504
12.222861747309238
12.222861409210363
12.222861071184875
12.222860733232752
12.22286039535399
12.22286005754855
12.22285971981644
12.222859382157631
12.222859044572111
12.222858707059865
12.222858369620875
12.222858032255125
12.222857694962597
12.222857357743285
12.22285702059715
12.222856683524205
12.22285634652442
12.222856009597786
12.222855672744267
12.222855335963876
12.22285499925657
12.222854662622355
12.222854326061203
12.222853989573096
12.22285365315803
12.222853316815977
12.22285298054693
12.222852644350874
12.22285230822778
12.222851972177647
12.222851636200453
12.222851300296176
12.222850964464804
12.222850628706333
12.222850293020734
12.222849957408
12.2228496218681
12.222849286401035
12.222848951006782
12.222848615685326
12.222848280436656
12.222847945260742
12.222847610157578
12.222847275127153
12.222846940169438
12.222846605284436
12.222846270472118
12.222845935732465
12.222845601065474
12.222845266471111
12.222844931949377
12.222844597500245
12.222844263123715
12.22284392881976
12.222843594588356
12.2228432604295
12.222842926343173
12.222842592329364
12.222842258388045
12.222841924519203
12.222841590722837
12.222841256998919
12.222840923347436
12.222840589768374
12.222840256261694
12.222839922827426
12.222839589465522
12.222839256175972
12.222838922958752
12.22283858981387
12.2228382567413
12.22283792374101
12.222837590813002
12.222837257957261
12.222836925173754
12.222836592462487
12.222836259823424
12.222835927256567
12.222835594761897
12.222835262339396
12.222834929989043
12.222834597710824
12.222834265504721
12.22283393337073
12.222833601308825
12.222833269318992
12.222832937401215
12.222832605555492
12.222832273781785
12.22283194208009
12.222831610450397
12.222831278892677
12.222830947406921
12.222830615993113
12.222830284651243
12.222829953381288
12.222829622183225
12.222829291057067
12.222828960002763
12.222828629020317
12.222828298109716
12.222827967270938
12.22282763650396
12.222827305808782
12.22282697518538
12.222826644633738
12.22282631415384
12.22282598374567
12.222825653409217
12.222825323144464
12.222824992951397
12.222824662829991
12.222824332780245
12.222824002802135
12.222823672895645
12.222823343060758
12.222823013297457
12.222822683605736
12.222822353985572
12.222822024436956
12.22282169495987
12.22282136555429
12.222821036220214
12.222820706957613
12.222820377766471
12.222820048646785
12.222819719598542
12.222819390621703
12.222819061716285
12.222818732882246
12.222818404119582
12.222818075428275
12.222817746808312
12.222817418259668
12.222817089782342
12.222816761376304
12.222816433041555
12.222816104778072
12.22281577658583
12.222815448464825
12.222815120415047
12.222814792436457
12.222814464529058
12.222814136692826
12.222813808927762
12.22281348123383
12.222813153611025
12.222812826059332
12.222812498578739
12.222812171169224
12.222811843830769
12.222811516563356
12.222811189366977
12.222810862241618
12.22281053518727
12.2228102082039
12.222809881291502
12.222809554450054
12.222809227679551
12.222808900979985
12.222808574351319
12.222808247793537
12.222807921306645
12.222807594890615
12.222807268545427
12.222806942271081
12.222806616067551
12.222806289934809
12.22280596387287
12.222805637881699
12.222805311961276
12.2228049861116
12.22280466033265
12.22280433462441
12.222804008986863
12.222803683419993
12.222803357923791
12.222803032498241
12.222802707143305
12.222802381859003
12.22280205664529
12.222801731502184
12.22280140642963
12.222801081427646
12.222800756496206
12.222800431635294
12.222800106844872
12.222799782124959
12.222799457475523
12.222799132896547
12.222798808388024
12.222798483949946
12.222798159582275
12.22279783528501
12.222797511058124
12.222797186901627
12.222796862815477
12.222796538799676
12.222796214854194
12.222795890979032
12.22279556717416
12.222795243439574
12.222794919775259
12.222794596181185
12.222794272657342
12.222793949203732
12.222793625820325
12.222793302507103
12.222792979264055
12.222792656091173
12.22279233298843
12.222792009955812
12.222791686993315
12.222791364100917
12.222791041278596
12.222790718526348
12.222790395844148
12.222790073231995
12.222789750689854
12.222789428217721
12.222789105815579
12.222788783483418
12.222788461221224
12.22278813902897
12.222787816906656
12.222787494854243
12.22278717287174
12.222786850959121
12.222786529116377
12.222786207343482
12.222785885640427
12.2227855640072
12.222785242443782
12.222784920950165
12.222784599526316
12.222784278172234
12.222783956887909
12.222783635673315
12.222783314528433
12.222782993453263
12.22278267244778
12.222782351511967
12.222782030645819
12.222781709849317
12.22278138912243
12.222781068465167
12.222780747877492
12.222780427359409
12.222780106910896
12.222779786531932
12.2227794662225
12.222779145982601
12.2227788258122
12.222778505711304
12.222778185679866
12.222777865717905
12.222777545825386
12.222777226002307
12.222776906248635
12.222776586564372
12.222776266949493
12.222775947403989
12.222775627927831
12.222775308521022
12.222774989183538
12.222774669915369
12.222774350716497
12.2227740315869
12.222773712526578
12.222773393535505
12.222773074613666
12.222772755761051
12.222772436977637
12.222772118263418
12.222771799618375
12.222771481042505
12.222771162535764
12.22277084409816
12.222770525729675
12.222770207430283
12.22276988919999
12.222769571038759
12.22276925294659
12.22276893492346
12.222768616969356
12.222768299084263
12.222767981268165
12.222767663521054
12.222767345842902
12.222767028233704
12.22276671069345
12.222766393222104
12.22276607581967
12.222765758486132
12.222765441221473
12.222765124025669
12.22276480689871
12.222764489840591
12.222764172851285
12.22276385593078
12.222763539079063
12.222763222296113
12.22276290558193
12.222762588936483
12.222762272359768
12.222761955851762
12.22276163941245
12.222761323041818
12.22276100673987
12.222760690506561
12.22276037434189
12.222760058245852
12.222759742218408
12.222759426259564
12.222759110369308
12.222758794547602
12.222758478794445
12.222758163109836
12.222757847493726
12.222757531946126
12.222757216467025
12.222756901056385
12.222756585714217
12.222756270440488
12.222755955235188
12.222755640098296
12.22275532502981
12.222755010029712
12.222754695097985
12.222754380234614
12.222754065439576
12.222753750712867
12.222753436054468
12.222753121464374
12.222752806942557
12.222752492488997
12.222752178103688
12.222751863786627
12.222751549537788
12.222751235357146
12.22275092124472
12.222750607200439
12.222750293224326
12.22274997931638

12.222749665476558
12.222749351704854
12.222749038001252
12.222748724365735
12.222748410798301
12.222748097298929
12.22274778386759
12.222747470504281
12.222747157208989
12.222746843981712
12.222746530822405
12.22274621773107
12.222745904707693
12.222745591752256
12.222745278864751
12.222744966045154
12.222744653293452
12.222744340609633
12.222744027993683
12.222743715445578
12.222743402965326
12.22274309055289
12.222742778208259
12.222742465931418
12.22274215372237
12.222741841581083
12.222741529507541
12.222741217501735
12.222740905563644
12.222740593693263
12.222740281890577
12.222739970155557
12.222739658488214
12.222739346888503
12.222739035356431
12.222738723891979
12.222738412495122
12.222738101165863
12.222737789904174
12.222737478710036
12.222737167583446
12.222736856524392
12.222736545532848
12.222736234608812
12.222735923752246
12.222735612963163
12.222735302241535
12.222734991587345
12.222734681000587
12.222734370481227
12.222734060029275
12.222733749644709
12.22273343932751
12.222733129077659
12.222732818895151
12.22273250877997
12.222732198732096
12.222731888751515
12.22273157883823
12.22273126899219
12.222730959213413
12.222730649501866
12.222730339857549
12.222730030280436
12.222729720770525
12.222729411327782
12.222729101952195
12.222728792643771
12.222728483402477
12.22272817422831
12.222727865121241
12.222727556081262
12.222727247108372
12.222726938202534
12.222726629363747
12.222726320591986
12.22272601188725
12.222725703249509
12.222725394678774
12.222725086175004
12.222724777738195
12.222724469368329
12.222724161065397
12.222723852829379
12.222723544660264
12.222723236558041
12.222722928522682
12.222722620554196
12.22272231265253
12.222722004817715
12.222721697049712
12.22272138934851
12.222721081714086
12.222720774146435
12.222720466645544
12.222720159211395
12.222719851843975
12.222719544543267
12.222719237309258
12.222718930141934
12.222718623041283
12.222718316007285
12.222718009039923
12.222717702139192
12.222717395305082
12.222717088537559
12.222716781836626
12.222716475202255
12.222716168634443
12.222715862133168
12.222715555698421
12.222715249330186
12.222714943028448
12.22271463679319
12.222714330624397
12.222714024522066
12.222713718486164
12.222713412516699
12.222713106613629
12.22271280077696
12.222712495006679
12.222712189302753
12.222711883665198
12.222711578093959
12.222711272589057
12.22271096715046
12.222710661778171
12.22271035647214
12.222710051232397
12.222709746058888
12.22270944095162
12.222709135910582
12.222708830935746
12.222708526027105
12.222708221184654
12.222707916408353
12.222707611698224
12.222707307054208
12.22270700247633
12.222706697964556
12.222706393518873
12.222706089139276
12.22270578482574
12.22270548057825
12.2227051763968
12.222704872281367
12.222704568231954
12.222704264248529
12.222703960331081
12.2227036564796
12.222703352694067
12.222703048974475
12.222702745320797
12.222702441733041
12.222702138211156
12.22270183475516
12.222701531365034
12.222701228040744
12.22270092478231
12.222700621589683
12.222700318462874
12.222700015401857
12.222699712406605
12.22269940947713
12.222699106613403
12.222698803815408
12.222698501083142
12.22269819841658
12.222697895815717
12.22269759328052
12.222697290810995
12.222696988407119
12.222696686068884
12.222696383796267
12.222696081589255
12.222695779447838
12.222695477372007
12.222695175361737
12.222694873417018
12.222694571537835
12.222694269724169
12.222693967976022
12.22269366629336
12.222693364676182
12.222693063124455
12.222692761638195
12.222692460217374
12.222692158861975
12.22269185757197
12.222691556347373
12.222691255188153
12.222690954094308
12.222690653065802
12.222690352102646
12.222690051204792
12.222689750372268
12.222689449605033
12.222689148903067
12.222688848266392
12.222688547694958
12.222688247188763
12.222687946747778
12.222687646372023
12.222687346061457
12.22268704581607
12.222686745635853
12.22268644552079
12.222686145470865
12.222685845486065
12.222685545566389
12.222685245711794
12.22268494592228
12.222684646197843
12.222684346538456
12.222684046944122
12.222683747414802
12.222683447950494
12.222683148551187
12.222682849216861
12.222682549947514
12.22268225074312
12.222681951603665
12.22268165252914
12.22268135351952
12.222681054574812
12.222680755694984
12.22268045688003
12.22268015812993
12.222679859444673
12.222679560824249
12.222679262268631
12.222678963777822
12.222678665351795
12.22267836699054
12.222678068694057
12.222677770462305
12.222677472295285
12.222677174192976
12.222676876155383
12.222676578182474
12.222676280274236
12.222675982430662
12.222675684651739
12.22267538693744
12.222675089287758
12.222674791702687
12.22267449418221
12.222674196726295
12.222673899334954
12.22267360200816
12.222673304745904
12.222673007548158
12.222672710414919
12.222672413346174
12.22267211634191
12.222671819402105
12.222671522526756
12.222671225715844
12.222670928969354
12.22267063228727
12.222670335669578
12.222670039116268
12.222669742627335
12.222669446202737
12.222669149842492
12.222668853546558
12.222668557314947
12.222668261147621
12.222667965044584
12.22266766900581
12.222667373031303
12.222667077121027
12.222666781274976
12.222666485493148
12.22266618977551
12.222665894122061
12.222665598532785
12.222665303007663
12.22266500754668
12.222664712149829
12.2226644168171
12.222664121548467
12.222663826343926
12.222663531203452
12.222663236127044
12.222662941114672
12.22266264616633
12.222662351282027
12.22266205646171
12.222661761705385
12.222661467013044
12.222661172384662
12.22266087782023
12.222660583319735
12.222660288883151
12.222659994510481
12.222659700201698
12.2226594059568
12.222659111775764
12.222658817658582
12.222658523605235
12.22265822961571
12.222657935690002
12.222657641828082
12.222657348029955
12.22265705429559
12.22265676062498
12.222656467018114
12.222656173474975
12.222655879995536
12.222655586579805
12.222655293227762
12.222654999939397
12.222654706714675
12.222654413553602
12.222654120456157
12.222653827422333
12.222653534452116
12.222653241545483
12.222652948702418
12.22265265592292
12.222652363206969
12.222652070554552
12.22265177796565
12.222651485440258
12.22265119297836
12.22265090057994
12.222650608244981
12.222650315973478
12.222650023765407
12.222649731620763
12.222649439539525
12.22264914752168
12.222648855567213
12.222648563676133
12.222648271848396
12.222647980084002
12.222647688382931
12.222647396745176
12.222647105170724
12.222646813659551
12.222646522211654
12.222646230827017
12.222645939505613
12.222645648247456
12.222645357052505
12.222645065920759
12.222644774852208
12.222644483846825
12.22264419290461
12.222643902025542
12.222643611209607
12.222643320456799
12.22264302976709
12.222642739140484
12.222642448576945
12.22264215807648
12.222641867639073
12.222641577264694
12.222641286953351
12.222640996705012
12.222640706519677
12.222640416397322
12.22264012633794
12.222639836341516
12.222639546408024
12.222639256537466
12.22263896672984
12.222638676985095
12.222638387303252
12.222638097684273
12.222637808128164
12.222637518634901
12.222637229204471
12.22263693983686
12.222636650532056
12.222636361290052
12.22263607211082
12.22263578299435
12.222635493940645
12.222635204949672
12.222634916021418
12.222634627155882
12.222634338353048
12.222634049612886
12.222633760935409
12.222633472320585
12.222633183768396
12.22263289527884
12.2226326068519
12.22263231848756
12.222632030185816
12.22263174194664
12.22263145377003
12.222631165655969
12.222630877604445
12.22263058961544
12.222630301688948
12.222630013824938
12.222629726023413
12.222629438284354
12.222629150607755
12.222628862993583
12.222628575441847
12.222628287952533
12.222628000525592
12.222627713161058
12.222627425858882
12.222627138619075
12.222626851441614
12.22262656432648
12.222626277273656
12.222625990283145
12.222625703354927
12.22262541648898
12.222625129685301
12.222624842943869
12.222624556264673
12.22262426964771
12.222623983092943
12.222623696600381
12.222623410170003
12.222623123801785
12.22262283749573
12.222622551251822
12.22262226507003
12.222621978950354
12.22262169289279
12.222621406897309
12.222621120963897
12.222620835092565
12.222620549283256
12.222620263535998
12.222619977850757
12.222619692227523
12.222619406666285
12.222619121167027
12.22261883572973
12.222618550354396
12.222618265040998
12.222617979789531
12.22261769459997
12.222617409472305
12.222617124406538
12.222616839402637
12.222616554460593
12.222616269580397
12.222615984762056

12.222615700005507
12.222615415310775
12.222615130677825
12.222614846106673
12.222614561597261
12.22261427714962
12.222613992763717
12.222613708439528
12.222613424177057
12.222613139976287
12.222612855837205
12.222612571759795
12.222612287744038
12.22261200378993
12.222611719897452
12.22261143606659
12.222611152297333
12.222610868589676
12.222610584943594
12.222610301359065
12.222610017836098
12.22260973437467
12.222609450974765
12.22260916763637
12.22260888435948
12.222608601144069
12.222608317990119
12.222608034897643
12.222607751866603
12.222607468897003
12.222607185988812
12.222606903142028
12.222606620356636
12.222606337632623
12.222606054969976
12.222605772368677
12.22260548982872
12.222605207350085
12.222604924932762
12.222604642576734
12.222604360281991
12.22260407804853
12.222603795876314
12.222603513765357
12.222603231715611
12.222602949727102
12.222602667799796
12.222602385933675
12.222602104128736
12.22260182238496
12.222601540702335
12.222601259080852
12.222600977520496
12.22260069602125
12.222600414583107
12.222600133206052
12.222599851890047
12.222599570635122
12.222599289441236
12.22259900830839
12.222598727236553
12.222598446225726
12.222598165275897
12.222597884387048
12.222597603559155
12.222597322792222
12.222597042086232
12.22259676144116
12.222596480857007
12.222596200333756
12.222595919871393
12.222595639469896
12.22259535912926
12.222595078849483
12.22259479863053
12.222594518472398
12.222594238375079
12.222593958338555
12.222593678362811
12.222593398447836
12.222593118593608
12.222592838800132
12.22259255906737
12.22259227939534
12.222591999784008
12.222591720233368
12.222591440743393
12.222591161314096
12.222590881945438
12.222590602637414
12.222590323390019
12.22259004420323
12.222589765077045
12.222589486011431
12.2225892070064
12.222588928061931
12.222588649177993
12.222588370354602
12.222588091591712
12.222587812889326
12.222587534247443
12.222587255666044
12.222586977145099
12.222586698684609
12.222586420284554
12.222586141944925
12.222585863665724
12.222585585446915
12.222585307288478
12.222585029190434
12.222584751152741
12.222584473175402
12.222584195258392
12.222583917401709
12.22258363960533
12.222583361869248
12.222583084193442
12.222582806577924
12.222582529022644
12.222582251527614
12.22258197409281
12.222581696718215
12.22258141940384
12.222581142149645
12.222580864955635
12.222580587821781
12.222580310748084
12.222580033734529
12.222579756781087
12.222579479887765
12.22257920305454
12.222578926281408
12.222578649568343
12.222578372915335
12.22257809632239
12.222577819789459
12.222577543316554
12.222577266903663
12.222576990550762
12.222576714257855
12.222576438024893
12.222576161851903
12.222575885738863
12.222575609685737
12.222575333692536
12.222575057759231
12.22257478188583
12.222574506072293
12.222574230318626
12.22257395462482
12.222573678990841
12.222573403416694
12.22257312790236
12.222572852447817
12.222572577053068
12.222572301718092
12.222572026442883
12.222571751227415
12.222571476071678
12.222571200975676
12.22257092593937
12.222570650962776
12.222570376045852
12.222570101188591
12.222569826391014
12.222569551653061
12.222569276974736
12.222569002356035
12.222568727796945
12.222568453297441
12.222568178857516
12.222567904477161
12.22256763015637
12.2225673558951
12.222567081693368
12.222566807551148
12.222566533468441
12.222566259445212
12.22256598548146
12.222565711577179
12.222565437732342
12.222565163946948
12.222564890220966
12.222564616554404
12.222564342947242
12.222564069399466
12.222563795911062
12.222563522482012
12.222563249112318
12.222562975801955
12.222562702550917
12.22256242935918
12.222562156226749
12.222561883153586
12.22256161013972
12.22256133718508
12.222561064289698
12.222560791453548
12.222560518676609
12.222560245958885
12.22255997330035
12.222559700701
12.222559428160812
12.22255915567979
12.222558883257888
12.222558610895128
12.22255833859149
12.222558066346938
12.22255779416149
12.22255752203511
12.222557249967812
12.222556977959547
12.222556706010318
12.222556434120124
12.222556162288951
12.22255589051677
12.222555618803574
12.222555347149354
12.222555075554105
12.222554804017797
12.222554532540423
12.22255426112198
12.222553989762442
12.222553718461802
12.222553447220056
12.222553176037168
12.22255290491315
12.222552633847986
12.222552362841641
12.222552091894123
12.222551821005416
12.222551550175503
12.222551279404378
12.22255100869201
12.222550738038418
12.222550467443561
12.222550196907427
12.22254992643003
12.222549656011333
12.222549385651323
12.222549115349995
12.22254884510735
12.222548574923355
12.222548304797991
12.22254803473127
12.222547764723156
12.222547494773655
12.222547224882742
12.222546955050406
12.222546685276644
12.222546415561427
12.22254614590476
12.222545876306617
12.222545606766996
12.222545337285872
12.222545067863239
12.222544798499083
12.222544529193385
12.222544259946147
12.222543990757357
12.222543721626977
12.222543452555025
12.22254318354147
12.2225429145863
12.222542645689513
12.222542376851091
12.222542108071009
12.222541839349278
12.222541570685857
12.222541302080758
12.222541033533957
12.22254076504544
12.222540496615217
12.222540228243242
12.222539959929513
12.222539691674028
12.22253942347676
12.222539155337717
12.222538887256858
12.222538619234196
12.222538351269698
12.222538083363373
12.222537815515187
12.222537547725143
12.22253727999322
12.222537012319407
12.222536744703698
12.222536477146063
12.222536209646513
12.222535942205019
12.222535674821566
12.222535407496155
12.222535140228764
12.222534873019386
12.222534605867997
12.2225343387746
12.222534071739176
12.222533804761712
12.222533537842201
12.222533270980607
12.222533004176938
12.222532737431193
12.222532470743335
12.222532204113362
12.222531937541262
12.22253167102701
12.222531404570619
12.222531138172055
12.222530871831307
12.222530605548382
12.222530339323251
12.222530073155896
12.222529807046314
12.222529540994492
12.222529275000422
12.222529009064072
12.222528743185443
12.222528477364541
12.222528211601318
12.222527945895788
12.222527680247929
12.222527414657721
12.222527149125169
12.222526883650232
12.222526618232935
12.222526352873233
12.222526087571127
12.222525822326618
12.22252555713967
12.222525292010282
12.22252502693844
12.222524761924133
12.222524496967342
12.222524232068062
12.222523967226278
12.222523702441984
12.222523437715154
12.222523173045785
12.222522908433852
12.222522643879365
12.222522379382296
12.222522114942633
12.222521850560366
12.222521586235489
12.222521321967978
12.222521057757826
12.22252079360502
12.222520529509552
12.222520265471395
12.222520001490562
12.222519737567012
12.222519473700753
12.222519209891763
12.22251894614004
12.222518682445552
12.222518418808304
12.222518155228272
12.222517891705463
12.222517628239848
12.222517364831413
12.222517101480147
12.222516838186042
12.222516574949088
12.22251631176927
12.222516048646575
12.222515785580983
12.222515522572493
12.222515259621089
12.222514996726762
12.222514733889493
12.222514471109276
12.222514208386087
12.222513945719921
12.222513683110778
12.222513420558625
12.222513158063464
12.22251289562527
12.222512633244047
12.222512370919768
12.222512108652417
12.222511846442005
12.222511584288489
12.222511322191886
12.222511060152172
12.222510798169324
12.222510536243346
12.22251027437422
12.222510012561939
12.22250975080646
12.222509489107804
12.222509227465954
12.222508965880897
12.22250870435261
12.222508442881095
12.222508181466319
12.222507920108288
12.222507658806988
12.222507397562403
12.222507136374523
12.222506875243322
12.222506614168804
12.222506353150955
12.222506092189755
12.222505831285208
12.22250557043727
12.22250530964597
12.222505048911264
12.222504788233143
12.222504527611612
12.222504267046647
12.22250400653823
12.222503746086364
12.222503485691018
12.222503225352204
12.2225029650699
12.222502704844079
12.22250244467474
12.222502184561868
12.222501924505446
12.222501664505485
12.222501404561948
12.222501144674832
12.222500884844125
12.222500625069815
12.222500365351896
12.222500105690338
12.222499846085139
12.222499586536294
12.222499327043776
12.222499067607577
12.2224988082277
12.22249854890411
12.222498289636816
12.222498030425786
12.22249777127102
12.222497512172504
12.22249725313023
12.222496994144173
12.222496735214335

12.222496476340698
12.222496217523238
12.22249595876196
12.222495700056847
12.222495441407883
12.222495182815063
12.222494924278367
12.222494665797793
12.22249440737331
12.222494149004921
12.222493890692613
12.222493632436368
12.222493374236185
12.222493116092034
12.222492858003918
12.222492599971812
12.222492341995721
12.222492084075618
12.222491826211504
12.222491568403347
12.222491310651154
12.22249105295491
12.222490795314592
12.22249053773019
12.222490280201711
12.222490022729106
12.222489765312408
12.222489507951567
12.222489250646584
12.222488993397466
12.222488736204163
12.222488479066692
12.22248822198504
12.222487964959175
12.222487707989103
12.222487451074803
12.222487194216269
12.222486937413478
12.222486680666433
12.222486423975118
12.222486167339506
12.222485910759609
12.222485654235395
12.222485397766865
12.222485141353987
12.222484884996781
12.222484628695202
12.222484372449262
12.222484116258935
12.222483860124212
12.222483604045095
12.222483348021546
12.222483092053567
12.22248283614115
12.222482580284279
12.222482324482938
12.222482068737119
12.22248181304681
12.222481557412005
12.222481301832675
12.222481046308816
12.222480790840425
12.22248053542748
12.222480280069979
12.222480024767897
12.222479769521225
12.222479514329953
12.222479259194072
12.222479004113579
12.222478749088436
12.22247849411865
12.22247823920421
12.22247798434509
12.222477729541293
12.2224774747928
12.2224772200996
12.222476965461679
12.22247671087902
12.222476456351627
12.222476201879473
12.222475947462563
12.222475693100863
12.222475438794364
12.22247518454308
12.222474930346973
12.222474676206039
12.222474422120271
12.222474168089642
12.22247391411415
12.222473660193796
12.22247340632854
12.22247315251839
12.222472898763325
12.222472645063354
12.222472391418428
12.222472137828566
12.222471884293745
12.22247163081395
12.22247137738917
12.222471124019403
12.222470870704619
12.222470617444825
12.222470364239998
12.222470111090134
12.222469857995208
12.222469604955217
12.22246935197015
12.222469099039985
12.222468846164734
12.222468593344358
12.222468340578857
12.22246808786822
12.222467835212436
12.22246758261149
12.22246733006536
12.222467077574057
12.222466825137555
12.22246657275584
12.222466320428902
12.22246606815674
12.222465815939326
12.222465563776655
12.222465311668724
12.22246505961551
12.222464807616994
12.222464555673175
12.222464303784042
12.222464051949588
12.22246380016979
12.222463548444646
12.222463296774126
12.222463045158243
12.222462793596963
12.22246254209029
12.222462290638202
12.222462039240694
12.222461787897752
12.222461536609362
12.222461285375516
12.222461034196195
12.222460783071398
12.222460532001099
12.222460280985306
12.222460030023978
12.222459779117141
12.222459528264752
12.22245927746681
12.222459026723303
12.222458776034228
12.222458525399551
12.222458274819274
12.222458024293399
12.2224577738219
12.22245752340475
12.222457273041957
12.222457022733519
12.222456772479397
12.222456522279598
12.2224562721341
12.222456022042898
12.222455772005969
12.222455522023324
12.222455272094926
12.222455022220787
12.222454772400871
12.222454522635179
12.222454272923699
12.222454023266426
12.222453773663338
12.22245352411442
12.222453274619673
12.222453025179064
12.22245277579261
12.222452526460284
12.22245227718207
12.22245202795797
12.222451778787947
12.222451529672025
12.222451280610166
12.22245103160236
12.222450782648604
12.22245053374889
12.222450284903191
12.2224500361115
12.222449787373815
12.222449538690121
12.222449290060393
12.222449041484637
12.222448792962831
12.222448544494979
12.222448296081042
12.222448047721022
12.222447799414914
12.222447551162698
12.222447302964373
12.222447054819902
12.222446806729304
12.222446558692548
12.222446310709635
12.222446062780538
12.222445814905253
12.222445567083776
12.222445319316085
12.222445071602174
12.22244482394202
12.222444576335624
12.222444328782979
12.222444081284056
12.22244383383885
12.222443586447362
12.222443339109564
12.222443091825445
12.222442844595006
12.222442597418228
12.222442350295097
12.222442103225598
12.222441856209734
12.222441609247477
12.222441362338833
12.222441115483768
12.222440868682286
12.222440621934375
12.222440375240021
12.222440128599214
12.222439882011935
12.22243963547817
12.222439388997923
12.222439142571172
12.22243889619792
12.222438649878134
12.2224384036118
12.22243815739893
12.222437911239497
12.222437665133485
12.222437419080906
12.22243717308172
12.222436927135929
12.22243668124352
12.222436435404491
12.22243618961881
12.222435943886484
12.222435698207494
12.222435452581822
12.222435207009461
12.222434961490407
12.222434716024633
12.22243447061215
12.222434225252929
12.222433979946958
12.22243373469423
12.22243348949474
12.222433244348466
12.222432999255394
12.22243275421554
12.222432509228852
12.222432264295342
12.222432019414997
12.222431774587802
12.222431529813749
12.22243128509282
12.222431040425016
12.222430795810308
12.222430551248687
12.222430306740156
12.2224300622847
12.22242981788229
12.222429573532931
12.222429329236613
12.222429084993319
12.222428840803035
12.222428596665758
12.222428352581456
12.222428108550147
12.2224278645718
12.222427620646409
12.222427376773956
12.222427132954433
12.222426889187837
12.222426645474146
12.222426401813363
12.222426158205453
12.222425914650426
12.222425671148256
12.22242542769894
12.222425184302462
12.222424940958819
12.222424697668
12.222424454429971
12.222424211244743
12.222423968112297
12.222423725032618
12.22242348200571
12.222423239031537
12.222422996110115
12.222422753241402
12.222422510425416
12.222422267662132
12.222422024951538
12.222421782293626
12.222421539688371
12.222421297135787
12.222421054635843
12.222420812188526
12.22242056979384
12.22242032745177
12.22242008516229
12.222419842925408
12.222419600741098
12.22241935860935
12.222419116530165
12.222418874503516
12.222418632529399
12.222418390607798
12.222418148738711
12.222417906922125
12.222417665158021
12.22241742344639
12.222417181787227
12.222416940180517
12.222416698626231
12.222416457124389
12.22241621567496
12.22241597427794
12.22241573293331
12.222415491641069
12.22241525040119
12.22241500921368
12.222414768078522
12.222414526995701
12.2224142859652
12.222414044987024
12.22241380406114
12.22241356318756
12.22241332236625
12.222413081597217
12.222412840880436
12.222412600215918
12.222412359603616
12.222412119043554
12.222411878535699
12.22241163808004
12.222411397676577
12.222411157325286
12.222410917026172
12.222410676779216
12.222410436584404
12.222410196441722
12.22240995635116
12.222409716312713
12.222409476326371
12.22240923639211
12.222408996509921
12.22240875667981
12.222408516901755
12.222408277175735
12.222408037501745
12.222407797879791
12.222407558309834
12.22240731879187
12.2224070793259
12.222406839911908
12.222406600549878
12.222406361239804
12.222406121981669
12.222405882775467
12.22240564362118
12.222405404518799
12.222405165468318
12.22240492646972
12.222404687523005
12.22240444862815
12.222404209785134
12.222403970993977
12.222403732254643
12.222403493567121
12.22240325493141
12.222403016347489
12.222402777815356
12.222402539334995
12.222402300906401
12.222402062529559
12.22240182420445
12.222401585931069
12.222401347709402
12.222401109539444
12.222400871421181
12.222400633354608
12.222400395339701
12.22240015737645
12.22239991946485
12.222399681604898
12.22239944379656
12.222399206039842
12.222398968334733
12.222398730681212
12.222398493079274
12.222398255528905
12.222398018030106
12.22239778058285
12.222397543187133
12.222397305842941
12.222397068550261
12.222396831309089
12.22239659411941
12.222396356981207
12.222396119894476
12.222395882859205
12.222395645875388
12.222395408943004
12.222395172062042
12.222394935232503
12.222394698454368
12.222394461727609
12.222394225052243
12.222393988428236
12.222393751855606
12.222393515334314
12.22239327886436
12.222393042445729
12.222392806078416
12.222392569762395
12.22239233349769
12.222392097284246
12.22239186112207
12.222391625011172
12.222391388951502
12.222391152943073
12.22239091698587
12.222390681079883
12.222390445225095
12.222390209421501
12.222389973669088
12.22238973796785
12.222389502317764
12.222389266718832
12.222389031171025
12.22238879567435
12.222388560228788
12.222388324834336
12.222388089490964
12.222387854198681
12.222387618957457
12.222387383767307
12.222387148628194
12.222386913540127
12.22238667850308
12.222386443517044
12.222386208582016
12.222385973697978
12.222385738864922
12.222385504082837
12.222385269351706
12.222385034671527
12.222384800042287
12.222384565463962
12.222384330936563
12.222384096460072
12.222383862034462
12.222383627659744
12.22238339333589
12.222383159062899
12.222382924840748
12.22238269066944
12.222382456548956
12.222382222479293
12.222381988460441
12.222381754492364
12.222381520575077
12.22238128670856
12.22238105289281
12.222380819127803
12.222380585413534
12.222380351749997
12.222380118137183
12.222379884575057
12.222379651063633
12.222379417602898
12.222379184192826
12.222378950833422
12.22237871752466
12.22237848426655
12.222378251059062
12.222378017902185
12.222377784795917
12.22237755174025
12.222377318735163
12.22237708578065
12.222376852876703
12.222376620023306
12.222376387220438
12.222376154468115
12.2223759217663
12.222375689115003
12.222375456514198
12.222375223963875
12.222374991464031
12.22237475901465
12.222374526615708
12.22237429426723
12.22237406196917
12.222373829721532
12.222373597524305
12.22237336537747
12.222373133281028
12.22237290123496
12.222372669239256
12.222372437293904
12.222372205398901
12.22237197355423
12.222371741759883
12.222371510015838
12.222371278322099
12.222371046678642
12.222370815085482
12.22237058354256
12.222370352049913
12.222370120607502
12.222369889215335
12.222369657873386
12.222369426581652

12.22236919534011
12.222368964148767
12.222368733007604
12.222368501916613
12.222368270875767
12.222368039885074
12.222367808944513
12.222367578054097
12.222367347213774
12.22236711642357
12.222366885683448
12.222366654993413
12.222366424353439
12.222366193763532
12.222365963223675
12.222365732733852
12.222365502294062
12.222365271904284
12.222365041564515
12.22236481127474
12.222364581034954
12.22236435084513
12.222364120705278
12.222363890615373
12.222363660575406
12.22236343058537
12.222363200645255
12.222362970755048
12.22236274091473
12.222362511124313
12.222362281383765
12.222362051693082
12.222361822052257
12.22236159246127
12.222361362920118
12.22236113342878
12.222360903987258
12.22236067459554
12.222360445253607
12.222360215961452
12.222359986719061
12.222359757526439
12.22235952838355
12.222359299290398
12.222359070246974
12.22235884125326
12.22235861230925
12.22235838341494
12.2223581545703
12.222357925775334
12.222357697030032
12.22235746833437
12.222357239688344
12.222357011091958
12.22235678254518
12.222356554048007
12.222356325600435
12.222356097202434
12.22235586885402
12.222355640555172
12.222355412305868
12.222355184106094
12.22235495595587
12.222354727855157
12.222354499803956
12.222354271802246
12.222354043850029
12.222353815947294
12.222353588094002
12.222353360290189
12.222353132535819
12.22235290483087
12.222352677175344
12.222352449569241
12.22235222201254
12.222351994505228
12.222351767047288
12.222351539638728
12.22235131227952
12.22235108496965
12.222350857709133
12.222350630497939
12.222350403336057
12.222350176223474
12.2223499491602
12.222349722146204
12.22234949518148
12.222349268266017
12.22234904139981
12.222348814582833
12.222348587815102
12.222348361096577
12.22234813442727
12.222347907807157
12.222347681236233
12.222347454714493
12.222347228241905
12.222347001818477
12.2223467754442
12.222346549119047
12.222346322843025
12.222346096616109
12.222345870438305
12.22234564430958
12.222345418229953
12.222345192199379
12.222344966217868
12.222344740285418
12.222344514401994
12.222344288567609
12.222344062782224
12.222343837045853
12.222343611358475
12.222343385720102
12.222343160130677
12.222342934590232
12.222342709098724
12.222342483656176
12.222342258262556
12.22234203291785
12.222341807622064
12.222341582375169
12.222341357177166
12.222341132028046
12.222340906927789
12.222340681876391
12.222340456873837
12.222340231920134
12.222340007015246
12.222339782159171
12.222339557351898
12.222339332593428
12.222339107883734
12.222338883222818
12.222338658610663
12.222338434047254
12.222338209532598
12.222337985066655
12.222337760649458
12.222337536280948
12.22233731196114
12.222337087690027
12.222336863467582
12.222336639293816
12.2223364151687
12.222336191092236
12.222335967064394
12.222335743085187
12.222335519154598
12.222335295272602
12.222335071439213
12.222334847654391
12.22233462391815
12.222334400230467
12.222334176591337
12.222333953000746
12.222333729458681
12.222333505965146
12.222333282520111
12.222333059123578
12.222332835775537
12.222332612475968
12.222332389224862
12.222332166022218
12.22233194286802
12.222331719762256
12.222331496704916
12.222331273695984
12.222331050735468
12.222330827823335
12.22233060495959
12.222330382144216
12.222330159377202
12.222329936658547
12.222329713988218
12.22232949136623
12.222329268792567
12.222329046267198
12.22232882379014
12.222328601361363
12.222328378980874
12.222328156648636
12.222327934364662
12.22232771212894
12.222327489941454
12.22232726780218
12.222327045711133
12.22232682366829
12.222326601673634
12.222326379727168
12.22232615782888
12.222325935978747
12.22232571417676
12.222325492422922
12.222325270717214
12.22232504905963
12.222324827450159
12.22232460588878
12.222324384375481
12.222324162910281
12.222323941493142
12.222323720124063
12.222323498803023
12.222323277530036
12.222323056305067
12.222322835128109
12.222322613999165
12.222322392918217
12.222322171885251
12.222321950900259
12.22232172996324
12.222321509074161
12.222321288233033
12.222321067439838
12.222320846694565
12.222320625997204
12.222320405347741
12.222320184746177
12.222319964192485
12.222319743686674
12.222319523228714
12.222319302818617
12.222319082456355
12.222318862141908
12.222318641875301
12.222318421656489
12.222318201485477
12.222317981362254
12.222317761286817
12.22231754125913
12.22231732127921
12.222317101347032
12.222316881462595
12.222316661625879
12.222316441836881
12.22231622209559
12.222316002401982
12.222315782756073
12.222315563157832
12.22231534360725
12.222315124104323
12.22231490464904
12.222314685241395
12.22231446588136
12.222314246568944
12.222314027304124
12.2223138080869
12.222313588917261
12.222313369795184
12.22231315072067
12.222312931693708
12.222312712714292
12.222312493782388
12.222312274898014
12.222312056061144
12.22231183727178
12.222311618529895
12.222311399835485
12.222311181188553
12.222310962589072
12.222310744037044
12.222310525532443
12.222310307075267
12.22231008866551
12.222309870303155
12.222309651988205
12.222309433720634
12.222309215500436
12.222308997327596
12.222308779202132
12.222308561124002
12.2223083430932
12.222308125109723
12.222307907173555
12.2223076892847
12.22230747144312
12.222307253648843
12.222307035901828
12.222306818202064
12.222306600549567
12.222306382944302
12.22230616538627
12.222305947875471
12.222305730411863
12.222305512995465
12.222305295626258
12.22230507830423
12.222304861029361
12.222304643801667
12.222304426621116
12.222304209487696
12.222303992401411
12.222303775362235
12.22230355837018
12.222303341425224
12.222303124527345
12.222302907676555
12.222302690872823
12.222302474116152
12.222302257406527
12.222302040743932
12.222301824128362
12.222301607559814
12.222301391038277
12.222301174563729
12.22230095813617
12.222300741755587
12.222300525421955
12.222300309135298
12.22230009289558
12.222299876702788
12.22229966055693
12.222299444457981
12.222299228405932
12.222299012400779
12.222298796442518
12.222298580531127
12.222298364666585
12.222298148848909
12.22229793307808
12.222297717354069
12.222297501676898
12.22229728604652
12.222297070462956
12.222296854926183
12.22229663943619
12.222296423992972
12.222296208596505
12.222295993246806
12.22229577794384
12.2222955626876
12.222295347478092
12.222295132315283
12.222294917199191
12.22229470212978
12.222294487107044
12.222294272130982
12.22229405720158
12.22229384231883
12.222293627482719
12.222293412693245
12.222293197950375
12.22229298325412
12.222292768604474
12.222292554001408
12.22229233944494
12.222292124935011
12.222291910471656
12.22229169605485
12.222291481684579
12.222291267360845
12.22229105308362
12.2222908388529
12.222290624668693
12.222290410530972
12.22229019643972
12.222289982394937
12.222289768396614
12.222289554444737
12.222289340539309
12.222289126680293
12.222288912867706
12.22228869910153
12.222288485381739
12.222288271708347
12.222288058081324
12.22228784450067
12.222287630966376
12.222287417478428
12.222287204036812
12.222286990641532
12.222286777292561
12.222286563989904
12.222286350733542
12.222286137523461
12.222285924359666
12.222285711242131
12.222285498170857
12.22228528514583
12.222285072167042
12.222284859234465
12.222284646348117
12.222284433507976
12.22228422071403
12.22228400796627
12.222283795264696
12.222283582609275
12.22228337000001
12.2222831574369
12.222282944919922
12.222282732449067
12.222282520024338
12.222282307645708
12.222282095313174
12.222281883026728
12.222281670786353
12.22228145859206
12.222281246443808
12.222281034341616
12.22228082228545
12.222280610275305
12.222280398311192
12.222280186393075
12.222279974520957
12.222279762694827
12.222279550914674
12.222279339180483
12.222279127492257
12.222278915849978
12.222278704253625
12.2222784927032
12.222278281198692
12.222278069740101
12.222277858327395
12.222277646960581
12.222277435639649
12.222277224364555
12.222277013135349
12.222276801951985
12.222276590814449
12.222276379722748
12.22227616867686
12.222275957676782
12.222275746722497
12.222275535814001
12.222275324951287
12.222275114134332
12.222274903363141
12.222274692637694
12.222274481957989
12.222274271324006
12.222274060735742
12.222273850193194
12.222273639696331
12.222273429245158
12.22227321883967
12.222273008479846
12.222272798165681
12.22227258789717
12.222272377674287
12.222272167497037
12.2222719573654
12.222271747279384
12.22227153723896
12.222271327244119
12.222271117294868
12.222270907391186
12.222270697533055
12.22227048772047
12.222270277953436
12.222270068231927
12.22226985855594
12.222269648925463
12.222269439340478
12.22226922980098
12.22226902030698
12.222268810858449
12.222268601455358
12.222268392097737
12.222268182785541
12.22226797351879
12.22226776429745
12.222267555121531
12.222267345991005
12.222267136905867
12.222266927866121
12.222266718871737
12.222266509922726
12.22226630101905
12.222266092160737
12.222265883347749
12.22226567458007
12.222265465857722
12.22226525718066
12.222265048548904
12.222264839962433
12.222264631421229
12.222264422925292
12.222264214474592
12.222264006069162
12.222263797708951
12.222263589393966
12.222263381124195
12.222263172899629
12.222262964720253
12.222262756586074
12.222262548497069
12.222262340453215
12.222262132454528
12.222261924500971
12.222261716592575
12.222261508729297
12.222261300911123
12.222261093138068
12.222260885410112
12.222260677727233
12.222260470089433
12.222260262496706
12.222260054949036
12.222259847446404
12.222259639988822
12.22225943257626
12.22225922520872
12.222259017886186
12.22225881060865
12.222258603376114
12.222258396188543
12.222258189045942
12.222257981948315
12.222257774895631
12.222257567887887
12.222257360925074
12.222257154007186
12.222256947134204
12.222256740306118
12.222256533522932
12.222256326784624
12.222256120091195
12.22225591344262
12.222255706838903
12.222255500280033
12.222255293765976
12.222255087296764
12.222254880872358
12.22225467449275
12.222254468157951
12.22225426186793
12.222254055622683
12.222253849422197
12.22225364326647
12.222253437155493
12.22225323108925
12.22225302506773
12.222252819090922
12.222252613158828
12.222252407271435
12.222252201428716
12.222251995630687
12.222251789877319
12.222251584168607
12.222251378504547
12.22225117288513
12.222250967310341
12.222250761780167
12.222250556294613
12.222250350853646
12.222250145457284
12.222249940105492
12.222249734798275
12.22224952953562
12.222249324317517
12.222249119143948
12.222248914014932
12.222248708930428
12.222248503890425
12.222248298894934
12.22224809394394
12.222247889037428
12.222247684175391
12.222247479357826
12.222247274584706
12.222247069856033
12.222246865171801
12.222246660531988
12.222246455936595
12.22224625138561
12.222246046879022
12.222245842416825
12.222245637999002
12.222245433625547
12.22224522929645
12.222245025011706
12.222244820771309
12.222244616575232
12.222244412423475
12.222244208316033
12.222244004252886
12.222243800234029
12.222243596259462
12.222243392329162
12.22224318844313
12.222242984601346
12.222242780803809
12.222242577050512
12.222242373341428
12.222242169676562
12.222241966055904
12.222241762479443
12.222241558947154
12.22224135545906
12.222241152015123
12.222240948615342
12.222240745259716
12.222240541948223
12.222240338680848
12.22224013545761
12.222239932278468
12.222239729143432
12.222239526052485
12.22223932300562
12.22223912000282
12.222238917044082
12.222238714129405
12.22223851125877
12.222238308432155
12.222238105649573
12.222237902911003
12.222237700216441
12.22223749756587
12.222237294959276
12.222237092396664
12.22223688987802
12.222236687403326
12.222236484972584
12.222236282585783
12.222236080242908
12.222235877943943
12.222235675688893
12.222235473477745
12.222235271310478
12.222235069187093
12.222234867107579
12.222234665071928
12.222234463080127
12.222234261132174
12.222234059228047
12.222233857367742
12.222233655551252
12.222233453778568
12.222233252049673
12.22223305036457
12.222232848723237
12.22223264712567
12.222232445571871
12.222232244061807
12.222232042595481
12.222231841172883
12.22223163979401
12.222231438458834
12.222231237167373
12.222231035919586
12.222230834715493
12.222230633555066
12.222230432438293
12.22223023136518
12.22223003033571
12.222229829349864
12.222229628407652
12.222229427509056
12.222229226654056
12.222229025842653
12.222228825074836
12.222228624350599
12.222228423669929
12.222228223032815
12.22222802243924
12.222227821889213
12.222227621382713

12.222227420919728
12.222227220500262
12.222227020124295
12.222226819791818
12.222226619502823
12.222226419257295
12.222226219055239
12.222226018896624
12.22222581878146
12.22222561870973
12.222225418681434
12.22222521869654
12.222225018755061
12.222224818856974
12.222224619002278
12.222224419190967
12.22222421942301
12.222224019698418
12.222223820017179
12.222223620379273
12.222223420784703
12.222223221233456
12.222223021725517
12.22222282226089
12.222222622839553
12.222222423461488
12.222222224126709
12.222222024835187
12.222221825586939
12.222221626381925
12.222221427220148
12.222221228101596
12.222221029026265
12.22222082999414
12.222220631005214
12.222220432059489
12.222220233156937
12.222220034297566
12.22221983548134
12.222219636708273
12.222219437978348
12.222219239291572
12.222219040647905
12.222218842047354
12.222218643489912
12.222218444975564
12.222218246504305
12.222218048076137
12.22221784969102
12.222217651348965
12.22221745304996
12.222217254793996
12.222217056581067
12.222216858411155
12.222216660284253
12.222216462200372
12.222216264159464
12.222216066161547
12.222215868206607
12.222215670294636
12.222215472425608
12.222215274599534
12.222215076816402
12.222214879076196
12.222214681378915
12.222214483724535
12.222214286113065
12.22221408854447
12.222213891018772
12.22221369353594
12.222213496095973
12.222213298698867
12.222213101344591
12.222212904033155
12.22221270676455
12.222212509538759
12.222212312355776
12.222212115215596
12.222211918118203
12.222211721063585
12.22221152405173
12.222211327082656
12.222211130156321
12.222210933272725
12.222210736431874
12.222210539633737
12.222210342878322
12.222210146165606
12.222209949495587
12.22220975286826
12.222209556283604
12.22220935974162
12.222209163242292
12.22220896678562
12.222208770371585
12.222208574000186
12.222208377671402
12.22220818138523
12.222207985141667
12.222207788940697
12.222207592782311
12.222207396666496
12.22220720059326
12.22220700456257
12.22220680857443
12.222206612628833
12.222206416725763
12.222206220865212
12.222206025047168
12.22220582927164
12.222205633538593
12.222205437848038
12.222205242199939
12.22220504659433
12.222204851031167
12.222204655510449
12.222204460032161
12.222204264596312
12.222204069202874
12.222203873851853
12.222203678543234
12.222203483277
12.222203288053153
12.222203092871675
12.222202897732561
12.2222027026358
12.222202507581393
12.222202312569314
12.222202117599561
12.22220192267213
12.222201727787011
12.222201532944181
12.222201338143643
12.2222011433854
12.22220094866942
12.222200753995702
12.222200559364234
12.222200364775013
12.222200170228026
12.222199975723278
12.222199781260729
12.2221995868404
12.222199392462258
12.222199198126315
12.22219900383255
12.22219880958096
12.222198615371521
12.222198421204238
12.222198227079112
12.222198032996099
12.222197838955225
12.22219764495647
12.222197450999808
12.22219725708526
12.222197063212784
12.2221968693824
12.222196675594097
12.22219648184784
12.222196288143632
12.222196094481466
12.222195900861347
12.222195707283243
12.222195513747161
12.222195320253082
12.222195126801005
12.222194933390904
12.222194740022791
12.222194546696652
12.222194353412466
12.222194160170234
12.222193966969957
12.222193773811604
12.222193580695174
12.22219338762066
12.222193194588057
12.222193001597347
12.222192808648527
12.222192615741582
12.22219242287651
12.222192230053299
12.222192037271936
12.222191844532423
12.222191651834748
12.22219145917889
12.222191266564854
12.222191073992612
12.222190881462176
12.222190688973525
12.222190496526649
12.222190304121558
12.222190111758206
12.222189919436628
12.222189727156778
12.22218953491867
12.22218934272229
12.222189150567615
12.222188958454662
12.22218876638339
12.22218857435382
12.222188382365921
12.222188190419697
12.222187998515135
12.222187806652224
12.22218761483095
12.222187423051315
12.22218723131331
12.222187039616916
12.222186847962133
12.222186656348942
12.222186464777359
12.222186273247345
12.222186081758894
12.222185890312009
12.222185698906687
12.222185507542896
12.22218531622065
12.222185124939921
12.222184933700706
12.222184742503014
12.222184551346816
12.222184360232108
12.222184169158885
12.222183978127116
12.222183787136826
12.222183596187987
12.222183405280601
12.222183214414631
12.222183023590107
12.22218283280699
12.222182642065285
12.22218245136498
12.222182260706075
12.222182070088538
12.222181879512384
12.22218168897759
12.222181498484154
12.222181308032061
12.222181117621306
12.222180927251886
12.222180736923775
12.222180546636976
12.222180356391481
12.222180166187279
12.222179976024364
12.222179785902716
12.222179595822338
12.22217940578321
12.22217921578534
12.222179025828705
12.222178835913303
12.222178646039106
12.22217845620613
12.222178266414362
12.222178076663788
12.222177886954391
12.222177697286176
12.222177507659126
12.222177318073237
12.222177128528498
12.22217693902489
12.222176749562433
12.222176560141083
12.222176370760845
12.222176181421714
12.222175992123686
12.222175802866744
12.222175613650862
12.222175424476063
12.222175235342334
12.222175046249648
12.222174857197997
12.22217466818738
12.222174479217793
12.222174290289217
12.22217410140165
12.222173912555085
12.2221737237495
12.222173534984904
12.22217334626128
12.22217315757861
12.222172968936892
12.222172780336118
12.222172591776285
12.222172403257378
12.222172214779398
12.22217202634231
12.222171837946128
12.222171649590845
12.222171461276435
12.222171273002896
12.222171084770231
12.222170896578413
12.222170708427443
12.222170520317313
12.22217033224801
12.222170144219536
12.222169956231866
12.22216976828499
12.222169580378917
12.222169392513631
12.222169204689116
12.222169016905374
12.222168829162383
12.222168641460142
12.222168453798641
12.222168266177878
12.222168078597832
12.222167891058504
12.22216770355988
12.222167516101948
12.222167328684709
12.222167141308146
12.222166953972245
12.222166766677017
12.22216657942244
12.222166392208498
12.222166205035194
12.22216601790252
12.222165830810455
12.222165643759002
12.22216545674815
12.22216526977789
12.222165082848209
12.222164895959098
12.222164709110555
12.222164522302565
12.222164335535117
12.222164148808217
12.222163962121838
12.22216377547598
12.222163588870632
12.222163402305787
12.22216321578144
12.22216302929757
12.22216284285418
12.22216265645127
12.222162470088794
12.222162283766783
12.22216209748521
12.222161911244067
12.222161725043353
12.222161538883048
12.22216135276315
12.222161166683652
12.222160980644547
12.222160794645804
12.222160608687437
12.222160422769441
12.222160236891789
12.222160051054487
12.222159865257522
12.222159679500882
12.222159493784556
12.222159308108543
12.222159122472828
12.222158936877408
12.222158751322272
12.222158565807405
12.222158380332813
12.222158194898471
12.222158009504382
12.222157824150532
12.222157638836904
12.222157453563506
12.222157268330317
12.222157083137338
12.222156897984553
12.22215671287195
12.222156527799532
12.222156342767272
12.222156157775187
12.222155972823243
12.222155787911447
12.222155603039793
12.222155418208255
12.222155233416842
12.222155048665531
12.222154863954325
12.222154679283204
12.222154494652168
12.222154310061216
12.222154125510318
12.22215394099948
12.222153756528682
12.22215357209793
12.222153387707216
12.22215320335651
12.222153019045827
12.222152834775137
12.222152650544455
12.22215246635375
12.222152282203027
12.222152098092277
12.222151914021486
12.222151729990646
12.222151545999749
12.222151362048786
12.222151178137757
12.222150994266638
12.222150810435432
12.222150626644115
12.222150442892701
12.22215025918117
12.222150075509512
12.22214989187771
12.22214970828578
12.222149524733693
12.22214934122144
12.222149157749014
12.222148974316424
12.222148790923649
12.222148607570666
12.222148424257487
12.222148240984087
12.222148057750472
12.222147874556635
12.22214769140255
12.22214750828822
12.222147325213637
12.222147142178796
12.222146959183673
12.222146776228273
12.222146593312582
12.222146410436583
12.22214622760029
12.222146044803678
12.222145862046741
12.222145679329476
12.222145496651859
12.222145314013892
12.222145131415573
12.222144948856894
12.22214476633782
12.222144583858377
12.222144401418541
12.222144219018292
12.222144036657635
12.222143854336563
12.222143672055067
12.222143489813133
12.222143307610743
12.222143125447916
12.222142943324611
12.222142761240844
12.222142579196598
12.22214239719187
12.22214221522663
12.222142033300907
12.222141851414657
12.22214166956788
12.22214148776058
12.222141305992743
12.222141124264356
12.222140942575415
12.222140760925909
12.222140579315829
12.222140397745159
12.222140216213907
12.222140034722054
12.222139853269596
12.222139671856525
12.222139490482821
12.222139309148488
12.22213912785352
12.222138946597887
12.222138765381594
12.222138584204643
12.222138403067019
12.222138221968704
12.222138040909698
12.222137859889992
12.22213767890957
12.222137497968438
12.222137317066574
12.222137136203974
12.222136955380634
12.222136774596546
12.222136593851676
12.222136413146059
12.222136232479654
12.222136051852463
12.222135871264474
12.222135690715692
12.222135510206083
12.222135329735668
12.222135149304412
12.222134968912322
12.222134788559389
12.22213460824559
12.222134427970943
12.222134247735411
12.222134067539017
12.222133887381716
12.222133707263525
12.222133527184424
12.222133347144412
12.222133167143474
12.222132987181618
12.222132807258813
12.222132627375062
12.222132447530347
12.222132267724676
12.222132087958027
12.222131908230397
12.222131728541775
12.22213154889215
12.22213136928153
12.222131189709883
12.222131010177222
12.222130830683522
12.222130651228778
12.222130471812989
12.222130292436143
12.22213011309822
12.222129933799229
12.22212975453916
12.222129575317991
12.22212939613572
12.222129216992352
12.22212903788786
12.222128858822243
12.222128679795487

12.222128500807587
12.222128321858548
12.222128142948337
12.22212796407697
12.222127785244417
12.222127606450682
12.222127427695762
12.222127248979628
12.22212707030229
12.222126891663729
12.222126713063947
12.22212653450293
12.222126355980661
12.22212617749716
12.222125999052379
12.222125820646333
12.222125642279005
12.222125463950396
12.222125285660494
12.222125107409287
12.22212492919678
12.222124751022946
12.222124572887783
12.222124394791285
12.222124216733441
12.222124038714242
12.222123860733687
12.222123682791768
12.222123504888451
12.222123327023768
12.222123149197683
12.22212297141019
12.222122793661292
12.222122615950964
12.222122438279222
12.222122260646035
12.222122083051406
12.222121905495321
12.22212172797777
12.222121550498755
12.222121373058254
12.222121195656282
12.222121018292803
12.222120840967824
12.222120663681336
12.22212048643332
12.222120309223785
12.222120132052694
12.222119954920077
12.222119777825904
12.22211960077016
12.222119423752844
12.222119246773962
12.222119069833484
12.222118892931414
12.222118716067737
12.22211853924246
12.222118362455555
12.222118185707007
12.222118008996839
12.222117832325024
12.222117655691541
12.222117479096418
12.222117302539614
12.22211712602113
12.222116949540956
12.222116773099097
12.222116596695528
12.222116420330245
12.222116244003242
12.222116067714513
12.222115891464048
12.22211571525183
12.222115539077874
12.22211536294214
12.222115186844643
12.222115010785371
12.222114834764309
12.222114658781452
12.222114482836792
12.22211430693032
12.222114131062034
12.222113955231903
12.222113779439956
12.222113603686145
12.2221134279705
12.222113252292978
12.222113076653594
12.222112901052332
12.222112725489186
12.22211254996415
12.222112374477202
12.222112199028341
12.22211202361757
12.222111848244865
12.222111672910223
12.222111497613637
12.222111322355108
12.222111147134612
12.222110971952137
12.22211079680771
12.222110621701285
12.222110446632861
12.222110271602435
12.22211009661001
12.22210992165556
12.222109746739086
12.222109571860571
12.222109397020022
12.222109222217417
12.222109047452747
12.222108872726018
12.22210869803721
12.222108523386314
12.222108348773327
12.222108174198246
12.222107999661052
12.222107825161743
12.2221076507003
12.22210747627674
12.222107301891027
12.222107127543165
12.22210695323315
12.222106778960963
12.2221066047266
12.22210643053005
12.22210625637132
12.222106082250395
12.222105908167245
12.222105734121895
12.222105560114315
12.222105386144506
12.222105212212448
12.22210503831815
12.222104864461599
12.222104690642777
12.222104516861677
12.222104343118298
12.22210416941263
12.22210399574467
12.222103822114406
12.222103648521822
12.222103474966922
12.222103301449685
12.222103127970112
12.222102954528198
12.222102781123915
12.222102607757282
12.222102434428272
12.222102261136882
12.222102087883107
12.222101914666936
12.222101741488363
12.22210156834738
12.22210139524397
12.222101222178138
12.222101049149867
12.222100876159157
12.222100703205975
12.222100530290355
12.222100357412248
12.222100184571683
12.222100011768616
12.222099839003059
12.222099666275009
12.22209949358445
12.222099320931367
12.222099148315753
12.22209897573761
12.22209880319692
12.222098630693685
12.222098458227896
12.222098285799538
12.222098113408592
12.22209794105508
12.222097768738962
12.22209759646026
12.222097424218951
12.222097252015011
12.22209707984846
12.222096907719273
12.222096735627446
12.22209656357297
12.222096391555842
12.222096219576049
12.222096047633586
12.222095875728442
12.222095703860612
12.222095532030075
12.22209536023684
12.222095188480887
12.222095016762225
12.222094845080825
12.222094673436699
12.222094501829817
12.222094330260184
12.222094158727787
12.222093987232622
12.22209381577468
12.222093644353965
12.222093472970444
12.222093301624124
12.222093130314992
12.22209295904305
12.222092787808268
12.222092616610658
12.222092445450215
12.22209227432692
12.222092103240758
12.222091932191738
12.222091761179843
12.222091590205055
12.222091419267391
12.222091248366825
12.222091077503347
12.222090906676959
12.222090735887651
12.222090565135414
12.222090394420231
12.222090223742098
12.222090053101018
12.222089882496975
12.222089711929959
12.222089541399967
12.222089370906989
12.222089200451018
12.222089030032034
12.222088859650043
12.222088689305046
12.222088518997005
12.22208834872593
12.222088178491822
12.222088008294651
12.222087838134435
12.22208766801114
12.222087497924774
12.222087327875329
12.222087157862791
12.222086987887154
12.222086817948412
12.222086648046554
12.222086478181563
12.222086308353454
12.2220861385622
12.2220859688078
12.222085799090246
12.222085629409522
12.222085459765632
12.222085290158569
12.22208512058831
12.22208495105486
12.222084781558204
12.222084612098339
12.222084442675259
12.222084273288942
12.222084103939393
12.222083934626601
12.222083765350556
12.222083596111265
12.222083426908696
12.222083257742856
12.222083088613727
12.222082919521313
12.222082750465601
12.22208258144658
12.222082412464243
12.222082243518587
12.222082074609602
12.222081905737273
12.222081736901597
12.222081568102567
12.222081399340171
12.222081230614412
12.22208106192527
12.222080893272746
12.222080724656832
12.222080556077506
12.222080387534774
12.222080219028625
12.222080050559049
12.222079882126028
12.22207971372958
12.222079545369683
12.222079377046326
12.222079208759492
12.22207904050919
12.222078872295407
12.222078704118138
12.222078535977378
12.2220783678731
12.222078199805303
12.222078031773998
12.222077863779164
12.22207769582079
12.222077527898868
12.222077360013392
12.222077192164356
12.222077024351757
12.222076856575578
12.222076688835813
12.22207652113246
12.222076353465505
12.22207618583494
12.222076018240758
12.222075850682955
12.22207568316152
12.222075515676448
12.222075348227722
12.222075180815338
12.222075013439296
12.222074846099586
12.222074678796195
12.222074511529112
12.22207434429834
12.222074177103863
12.22207400994567
12.222073842823765
12.222073675738132
12.22207350868876
12.222073341675642
12.222073174698796
12.222073007758167
12.22207284085378
12.222072673985629
12.22207250715369
12.222072340357949
12.222072173598434
12.222072006875099
12.222071840187953
12.222071673536991
12.222071506922191
12.222071340343563
12.222071173801089
12.222071007294756
12.222070840824573
12.222070674390514
12.222070507992589
12.22207034163077
12.222070175305065
12.222070009015459
12.222069842761945
12.222069676544518
12.222069510363164
12.222069344217884
12.222069178108669
12.222069012035496
12.222068845998377
12.22206867999729
12.222068514032241
12.222068348103207
12.22206818221019
12.222068016353191
12.222067850532179
12.22206768474716
12.222067518998125
12.22206735328506
12.222067187607978
12.222067021966845
12.222066856361655
12.222066690792424
12.22206652525912
12.22206635976175
12.222066194300304
12.222066028874771
12.222065863485135
12.222065698131399
12.222065532813556
12.222065367531595
12.222065202285506
12.222065037075286
12.222064871900923
12.22206470676241
12.222064541659742
12.222064376592911
12.222064211561902
12.222064046566716
12.222063881607347
12.222063716683767
12.222063551795989
12.222063386944004
12.2220632221278
12.222063057347372
12.222062892602713
12.222062727893798
12.222062563220636
12.22206239858322
12.222062233981532
12.222062069415578
12.222061904885342
12.22206174039082
12.222061575931987
12.22206141150886
12.22206124712142
12.222061082769656
12.22206091845357
12.222060754173148
12.222060589928379
12.222060425719262
12.222060261545787
12.222060097407939
12.222059933305724
12.222059769239133
12.222059605208132
12.222059441212748
12.22205927725296
12.222059113328752
12.222058949440123
12.22205878558707
12.222058621769586
12.222058457987647
12.222058294241268
12.222058130530419
12.22205796685511
12.22205780321532
12.222057639611059
12.222057476042297
12.222057312509042
12.222057149011288
12.222056985549006
12.222056822122218
12.222056658730894
12.22205649537503
12.222056332054624
12.222056168769674
12.222056005520168
12.222055842306084
12.222055679127426
12.222055515984186
12.22205535287636
12.222055189803935
12.222055026766906
12.222054863765258
12.22205470079899
12.222054537868095
12.22205437497257
12.222054212112386
12.222054049287568
12.222053886498086
12.222053723743933
12.222053561025106
12.222053398341595
12.222053235693402
12.222053073080506
12.222052910502898
12.222052747960593
12.222052585453552
12.222052422981795
12.222052260545295
12.222052098144053
12.222051935778058
12.222051773447316
12.22205161115179
12.222051448891499
12.222051286666428
12.222051124476563
12.222050962321896
12.222050800202434
12.222050638118162
12.222050476069068
12.222050314055137
12.222050152076383
12.222049990132785
12.222049828224328
12.222049666351012
12.222049504512846
12.22204934270979
12.22204918094186
12.22204901920904
12.22204885751132
12.222048695848706
12.222048534221175
12.222048372628727
12.222048211071346
12.222048049549034
12.22204788806178
12.22204772660958
12.22204756519242
12.222047403810294
12.222047242463194
12.222047081151128
12.222046919874062
12.222046758632008
12.222046597424946
12.222046436252867
12.222046275115773
12.222046114013656
12.222045952946516
12.222045791914324
12.222045630917089
12.222045469954796
12.222045309027441
12.22204514813501
12.222044987277501
12.222044826454912
12.222044665667223
12.22204450491443
12.222044344196531
12.222044183513537
12.222044022865388
12.222043862252121
12.222043701673709
12.222043541130152
12.22204338062145
12.222043220147578
12.222043059708541
12.222042899304318
12.222042738934917
12.222042578600323
12.22204241830053
12.22204225803553
12.222042097805316
12.222041937609873
12.222041777449212
12.222041617323304
12.22204145723215
12.222041297175746
12.222041137154083
12.222040977167154
12.222040817214953
12.222040657297466
12.222040497414676
12.222040337566606
12.222040177753223
12.222040017974535
12.22203985823052
12.222039698521172
12.222039538846497
12.222039379206478
12.222039219601106
12.222039060030376
12.222038900494276
12.222038740992817
12.222038581525963
12.222038422093723
12.222038262696097
12.222038103333059
12.222037944004615
12.222037784710757
12.222037625451456
12.222037466226741
12.222037307036576
12.222037147880966
12.222036988759893
12.222036829673366
12.222036670621367
12.22203651160389
12.222036352620918
12.22203619367247
12.222036034758512
12.222035875879044
12.222035717034068
12.222035558223563
12.222035399447527
12.222035240705956
12.22203508199884
12.22203492332617
12.222034764687935
12.222034606084136
12.222034447514762
12.222034288979804
12.222034130479251
12.222033972013111
12.222033813581362
12.222033655183994
12.222033496821014
12.2220333384924
12.22203318019816
12.222033021938271
12.222032863712728
12.222032705521533
12.222032547364682
12.222032389242141
12.222032231153928
12.222032073100026
12.222031915080438
12.222031757095136
12.222031599144131
12.222031441227411
12.22203128334496
12.222031125496777
12.222030967682864
12.222030809903199
12.222030652157772
12.2220304944466
12.222030336769638
12.22203017912691
12.222030021518405
12.222029863944096

12.222029706403998
12.222029548898089
12.222029391426371
12.222029233988831
12.222029076585457
12.222028919216246
12.2220287618812
12.222028604580286
12.222028447313532
12.222028290080907
12.222028132882413
12.222027975718033
12.222027818587765
12.222027661491607
12.22202750442955
12.22202734740157
12.222027190407672
12.22202703344786
12.222026876522117
12.22202671963043
12.222026562772799
12.222026405949205
12.222026249159654
12.222026092404134
12.222025935682634
12.222025778995162
12.222025622341683
12.222025465722213
12.22202530913674
12.222025152585246
12.222024996067741
12.222024839584195
12.222024683134624
12.222024526719007
12.22202437033734
12.222024213989622
12.222024057675831
12.22202390139596
12.222023745150022
12.222023588937999
12.22202343275987
12.222023276615642
12.222023120505312
12.222022964428856
12.222022808386278
12.222022652377577
12.222022496402728
12.22202234046174
12.222022184554595
12.222022028681293
12.22202187284182
12.22202171703617
12.22202156126434
12.222021405526315
12.222021249822102
12.222021094151676
12.222020938515039
12.22202078291219
12.22202062734311
12.222020471807785
12.222020316306235
12.222020160838428
12.222020005404366
12.22201985000404
12.22201969463745
12.22201953930458
12.222019384005412
12.222019228739963
12.222019073508207
12.222018918310166
12.222018763145783
12.222018608015093
12.222018452918062
12.222018297854698
12.222018142824995
12.222017987828947
12.22201783286653
12.222017677937751
12.222017523042593
12.22201736818106
12.222017213353142
12.222017058558832
12.222016903798114
12.222016749070992
12.22201659437744
12.222016439717473
12.222016285091069
12.222016130498243
12.222015975938955
12.222015821413223
12.222015666921017
12.222015512462358
12.222015358037215
12.22201520364559
12.222015049287483
12.222014894962873
12.222014740671769
12.222014586414133
12.222014432189988
12.22201427799933
12.222014123842115
12.222013969718375
12.222013815628088
12.222013661571243
12.222013507547834
12.222013353557859
12.222013199601301
12.222013045678162
12.222012891788436
12.22201273793211
12.222012584109173
12.222012430319626
12.222012276563461
12.222012122840663
12.222011969151241
12.222011815495163
12.22201166187244
12.22201150828306
12.22201135472703
12.222011201204316
12.222011047714924
12.222010894258853
12.222010740836089
12.222010587446619
12.222010434090441
12.222010280767554
12.222010127477944
12.222009974221601
12.22200982099853
12.222009667808695
12.222009514652145
12.222009361528812
12.222009208438719
12.222009055381854
12.222008902358214
12.22200874936778
12.22200859641056
12.222008443486537
12.222008290595706
12.222008137738056
12.222007984913589
12.222007832122284
12.222007679364152
12.222007526639164
12.222007373947331
12.22200722128865
12.222007068663089
12.22200691607065
12.222006763511354
12.222006610985153
12.222006458492066
12.22200630603207
12.222006153605163
12.222006001211351
12.222005848850605
12.222005696522928
12.222005544228324
12.222005391966771
12.222005239738268
12.222005087542804
12.222004935380372
12.222004783250963
12.222004631154583
12.222004479091204
12.222004327060837
12.22200417506347
12.22200402309909
12.222003871167697
12.222003719269278
12.222003567403819
12.222003415571342
12.222003263771809
12.222003112005229
12.222002960271572
12.222002808570863
12.222002656903085
12.222002505268215
12.222002353666262
12.222002202097217
12.222002050561061
12.222001899057801
12.222001747587424
12.22200159614992
12.222001444745295
12.222001293373522
12.222001142034612
12.222000990728544
12.22200083945532
12.222000688214923
12.22200053700736
12.222000385832613
12.222000234690684
12.22200008358154
12.221999932505218
12.221999781461683
12.221999630450924
12.221999479472936
12.221999328527735
12.221999177615277
12.221999026735594
12.221998875888652
12.221998725074444
12.221998574292979
12.221998423544237
12.221998272828216
12.221998122144893
12.221997971494291
12.221997820876389
12.221997670291165
12.221997519738647
12.221997369218787
12.221997218731607
12.221997068277087
12.221996917855218
12.221996767466
12.221996617109438
12.22199646678549
12.22199631649417
12.221996166235488
12.221996016009411
12.221995865815936
12.221995715655058
12.221995565526782
12.221995415431083
12.22199526536797
12.22199511533742
12.221994965339436
12.22199481537401
12.221994665441136
12.221994515540798
12.221994365672998
12.221994215837736
12.221994066034982
12.221993916264754
12.22199376652703
12.2219936168218
12.221993467149064
12.221993317508815
12.221993167901049
12.221993018325758
12.221992868782923
12.221992719272542
12.221992569794631
12.221992420349151
12.221992270936116
12.221992121555498
12.221991972207311
12.221991822891535
12.221991673608176
12.221991524357213
12.221991375138646
12.221991225952465
12.221991076798666
12.221990927677236
12.221990778588175
12.22199062953148
12.221990480507129
12.221990331515128
12.221990182555462
12.221990033628137
12.221989884733125
12.221989735870435
12.221989587040058
12.22198943824198
12.221989289476198
12.221989140742709
12.221988992041492
12.221988843372566
12.2219886947359
12.221988546131495
12.221988397559347
12.221988249019445
12.221988100511782
12.22198795203636
12.221987803593155
12.221987655182168
12.221987506803398
12.22198735845683
12.221987210142467
12.221987061860297
12.221986913610301
12.22198676539249
12.221986617206845
12.221986469053371
12.221986320932038
12.221986172842863
12.221986024785839
12.221985876760936
12.221985728768173
12.221985580807525
12.221985432878995
12.221985284982562
12.221985137118248
12.221984989286021
12.22198484148587
12.221984693717813
12.22198454598182
12.221984398277892
12.221984250606022
12.221984102966218
12.221983955358446
12.221983807782713
12.221983660239015
12.22198351272734
12.221983365247675
12.22198321780004
12.221983070384391
12.221982923000738
12.221982775649078
12.221982628329398
12.221982481041701
12.22198233378597
12.221982186562194
12.22198203937038
12.221981892210506
12.221981745082578
12.221981597986588
12.221981450922513
12.221981303890368
12.221981156890134
12.221981009921805
12.221980862985374
12.221980716080832
12.221980569208188
12.221980422367416
12.221980275558515
12.221980128781475
12.221979982036295
12.221979835322967
12.221979688641484
12.221979541991832
12.221979395374019
12.221979248788019
12.221979102233842
12.221978955711478
12.221978809220905
12.221978662762131
12.22197851633515
12.221978369939945
12.221978223576517
12.221978077244865
12.221977930944966
12.221977784676826
12.22197763844043
12.221977492235766
12.22197734606285
12.22197719992165
12.221977053812177
12.221976907734406
12.221976761688348
12.221976615673993
12.22197646969133
12.22197632374035
12.221976177821043
12.221976031933417
12.22197588607744
12.221975740253145
12.221975594460474
12.221975448699464
12.221975302970082
12.221975157272336
12.221975011606217
12.221974865971712
12.22197472036881
12.221974574797516
12.221974429257822
12.221974283749718
12.221974138273188
12.221973992828238
12.22197384741485
12.221973702033031
12.221973556682764
12.22197341136405
12.221973266076875
12.221973120821232
12.221972975597108
12.221972830404514
12.221972685243438
12.221972540113864
12.221972395015788
12.221972249949204
12.221972104914114
12.221971959910503
12.22197181493836
12.22197166999768
12.221971525088467
12.221971380210706
12.221971235364379
12.221971090549502
12.22197094576605
12.22197080101403
12.221970656293422
12.221970511604225
12.221970366946437
12.22197022232004
12.22197007772504
12.22196993316143
12.221969788629185
12.22196964412832
12.221969499658806
12.221969355220663
12.22196921081386
12.221969066438403
12.221968922094293
12.2219687777815
12.221968633500035
12.221968489249878
12.221968345031042
12.2219682008435
12.221968056687258
12.221967912562299
12.22196776846863
12.221967624406231
12.221967480375103
12.221967336375236
12.221967192406618
12.221967048469262
12.22196690456313
12.221966760688245
12.221966616844584
12.221966473032154
12.221966329250916
12.221966185500905
12.221966041782089
12.221965898094465
12.221965754438022
12.221965610812772
12.221965467218698
12.221965323655768
12.221965180124016
12.221965036623416
12.221964893153961
12.22196474971564
12.22196460630846
12.221964462932403
12.221964319587466
12.221964176273648
12.221964032990927
12.221963889739305
12.221963746518778
12.221963603329339
12.221963460170981
12.221963317043688
12.221963173947463
12.221963030882295
12.221962887848187
12.221962744845115
12.221962601873079
12.221962458932087
12.221962316022116
12.221962173143158
12.22196203029522
12.221961887478287
12.221961744692342
12.22196160193739
12.221961459213432
12.221961316520442
12.221961173858432
12.221961031227377
12.221960888627292
12.221960746058146
12.221960603519946
12.221960461012687
12.221960318536361
12.221960176090953
12.221960033676472
12.2219598912929
12.221959748940227
12.221959606618444
12.221959464327572
12.22195932206757
12.22195917983844
12.221959037640188
12.221958895472804
12.221958753336272
12.221958611230594
12.22195846915576
12.221958327111766
12.221958185098586
12.221958043116244
12.221957901164721
12.221957759243994
12.221957617354084
12.221957475494966
12.221957333666642
12.221957191869091
12.22195705010233
12.221956908366339
12.221956766661094
12.221956624986625
12.221956483342899
12.22195634172991
12.221956200147668
12.22195605859615
12.221955917075357
12.221955775585286
12.221955634125914
12.221955492697257
12.221955351299293
12.221955209932023
12.221955068595424
12.221954927289513
12.221954786014273
12.221954644769692
12.22195450355577
12.221954362372495
12.221954221219857
12.221954080097868
12.221953939006502
12.221953797945767
12.221953656915645
12.221953515916127
12.221953374947228
12.221953234008915
12.221953093101188
12.221952952224054
12.22195281137749
12.221952670561505
12.221952529776088
12.221952389021213
12.2219522482969
12.221952107603117
12.221951966939884
12.221951826307183
12.221951685704992
12.221951545133335
12.221951404592177
12.221951264081524
12.22195112360138
12.221950983151718
12.22195084273254
12.22195070234384
12.22195056198561
12.221950421657855
12.221950281360543
12.221950141093695
12.22195000085728
12.221949860651305
12.221949720475765
12.221949580330653
12.221949440215958
12.221949300131675
12.221949160077784
12.221949020054312
12.221948880061227
12.22194874009852
12.221948600166186
12.221948460264231
12.221948320392642
12.221948180551415
12.221948040740529
12.221947900960004
12.221947761209815
12.221947621489953
12.22194748180042

12.221947342141203
12.221947202512302
12.221947062913705
12.221946923345405
12.221946783807406
12.221946644299685
12.22194650482225
12.221946365375084
12.221946225958192
12.22194608657155
12.221945947215167
12.221945807889039
12.221945668593138
12.221945529327476
12.221945390092046
12.22194525088683
12.22194511171183
12.221944972567035
12.221944833452449
12.221944694368048
12.221944555313836
12.22194441628982
12.221944277295961
12.221944138332274
12.221943999398757
12.221943860495388
12.221943721622171
12.221943582779108
12.221943443966163
12.221943305183348
12.221943166430663
12.221943027708088
12.221942889015626
12.22194275035326
12.221942611721001
12.221942473118826
12.221942334546743
12.22194219600472
12.22194205749278
12.221941919010904
12.221941780559073
12.2219416421373
12.221941503745581
12.221941365383898
12.221941227052232
12.221941088750599
12.221940950478988
12.221940812237381
12.22194067402578
12.22194053584418
12.221940397692572
12.221940259570948
12.221940121479301
12.221939983417633
12.221939845385933
12.221939707384188
12.221939569412386
12.221939431470544
12.22193929355864
12.221939155676665
12.221939017824614
12.221938880002488
12.221938742210275
12.22193860444798
12.221938466715578
12.221938329013069
12.221938191340442
12.221938053697706
12.22193791608485
12.22193777850185
12.221937640948719
12.221937503425437
12.221937365932016
12.221937228468425
12.221937091034679
12.221936953630765
12.22193681625666
12.221936678912385
12.221936541597914
12.221936404313256
12.221936267058386
12.221936129833308
12.221935992638011
12.221935855472507
12.22193571833676
12.221935581230778
12.22193544415456
12.221935307108096
12.221935170091367
12.221935033104398
12.221934896147141
12.221934759219618
12.221934622321816
12.221934485453728
12.221934348615342
12.221934211806653
12.221934075027674
12.221933938278372
12.22193380155875
12.221933664868802
12.22193352820853
12.221933391577915
12.221933254976957
12.221933118405648
12.22193298186397
12.221932845351947
12.22193270886954
12.221932572416762
12.221932435993612
12.221932299600047
12.221932163236104
12.221932026901753
12.221931890597002
12.221931754321826
12.221931618076232
12.221931481860201
12.221931345673745
12.221931209516844
12.221931073389499
12.221930937291695
12.221930801223435
12.221930665184702
12.221930529175504
12.221930393195825
12.221930257245658
12.221930121325006
12.22192998543384
12.221929849572184
12.221929713740009
12.221929577937322
12.221929442164106
12.22192930642035
12.22192917070607
12.221929035021248
12.221928899365869
12.221928763739934
12.221928628143434
12.221928492576376
12.221928357038728
12.22192822153051
12.221928086051703
12.221927950602304
12.221927815182292
12.22192767979168
12.221927544430454
12.221927409098607
12.22192727379613
12.221927138523021
12.221927003279275
12.221926868064886
12.221926732879844
12.221926597724147
12.221926462597771
12.221926327500732
12.221926192433022
12.221926057394619
12.221925922385534
12.221925787405754
12.22192565245526
12.22192551753406
12.221925382642151
12.221925247779513
12.221925112946153
12.221924978142056
12.221924843367216
12.221924708621623
12.221924573905289
12.221924439218188
12.221924304560325
12.221924169931679
12.221924035332266
12.221923900762054
12.221923766221066
12.221923631709275
12.22192349722667
12.22192336277327
12.221923228349043
12.221923093953977
12.221922959588106
12.221922825251388
12.221922690943835
12.221922556665422
12.221922422416164
12.221922288196042
12.221922154005052
12.221922019843188
12.221921885710442
12.221921751606803
12.221921617532276
12.22192148348685
12.221921349470525
12.221921215483283
12.22192108152513
12.221920947596034
12.221920813696016
12.221920679825065
12.221920545983167
12.221920412170318
12.221920278386518
12.221920144631742
12.221920010906016
12.221919877209297
12.221919743541605
12.221919609902926
12.221919476293255
12.221919342712576
12.221919209160903
12.221919075638208
12.221918942144496
12.221918808679762
12.221918675243991
12.221918541837189
12.221918408459333
12.221918275110431
12.221918141790477
12.221918008499458
12.22191787523735
12.221917742004194
12.221917608799941
12.221917475624606
12.221917342478179
12.22191720936064
12.221917076271994
12.221916943212245
12.221916810181376
12.221916677179365
12.221916544206236
12.221916411261974
12.221916278346558
12.221916145459994
12.221916012602271
12.221915879773388
12.221915746973327
12.221915614202098
12.221915481459677
12.221915348746084
12.221915216061292
12.22191508340529
12.221914950778082
12.221914818179673
12.221914685610034
12.22191455306916
12.22191442055706
12.221914288073727
12.221914155619146
12.221914023193316
12.221913890796234
12.221913758427872
12.221913626088256
12.22191349377736
12.221913361495176
12.221913229241713
12.221913097016943
12.221912964820874
12.221912832653514
12.221912700514828
12.221912568404827
12.221912436323494
12.22191230427084
12.22191217224683
12.221912040251485
12.221911908284799
12.221911776346738
12.221911644437323
12.221911512556542
12.22191138070438
12.221911248880843
12.221911117085913
12.22191098531959
12.22191085358187
12.221910721872733
12.22191059019219
12.221910458540236
12.221910326916847
12.221910195322021
12.221910063755773
12.221909932218075
12.221909800708918
12.221909669228308
12.221909537776247
12.221909406352705
12.221909274957694
12.221909143591194
12.221909012253217
12.221908880943747
12.221908749662775
12.22190861841029
12.221908487186305
12.221908355990795
12.221908224823759
12.221908093685203
12.221907962575099
12.221907831493452
12.221907700440262
12.221907569415508
12.221907438419212
12.221907307451334
12.221907176511888
12.221907045600851
12.221906914718238
12.221906783864027
12.221906653038223
12.221906522240813
12.22190639147179
12.221906260731155
12.22190613001889
12.221905999334998
12.221905868679483
12.22190573805231
12.221905607453492
12.221905476883029
12.221905346340904
12.221905215827103
12.221905085341637
12.221904954884492
12.221904824455661
12.221904694055143
12.221904563682926
12.221904433339011
12.221904303023377
12.221904172736028
12.221904042476966
12.221903912246173
12.221903782043645
12.221903651869379
12.221903521723373
12.221903391605595
12.22190326151608
12.22190313145479
12.221903001421738
12.2219028714169
12.221902741440294
12.22190261149188
12.221902481571679
12.221902351679681
12.221902221815862
12.22190209198024
12.221901962172803
12.221901832393542
12.22190170264244
12.221901572919501
12.221901443224718
12.221901313558096
12.221901183919611
12.221901054309255
12.221900924727038
12.221900795172942
12.221900665646967
12.221900536149121
12.22190040667936
12.22190027723771
12.221900147824158
12.22190001843869
12.221899889081309
12.221899759752004
12.221899630450764
12.22189950117759
12.22189937193248
12.221899242715422
12.22189911352641
12.221898984365431
12.221898855232496
12.221898726127577
12.221898597050696
12.221898468001815
12.221898338980951
12.221898209988101
12.221898081023236
12.221897952086357
12.221897823177477
12.22189769429657
12.221897565443632
12.221897436618663
12.221897307821664
12.221897179052613
12.221897050311519
12.221896921598358
12.221896792913139
12.221896664255846
12.221896535626483
12.221896407025044
12.221896278451501
12.221896149905879
12.221896021388153
12.221895892898313
12.221895764436377
12.221895636002314
12.221895507596132
12.221895379217818
12.221895250867373
12.221895122544785
12.22189499425004
12.221894865983149
12.221894737744101
12.22189460953288
12.221894481349478
12.22189435319392
12.221894225066164
12.221894096966228
12.221893968894078
12.22189384084974
12.221893712833193
12.221893584844427
12.221893456883446
12.22189332895024
12.221893201044793
12.22189307316711
12.221892945317181
12.221892817495004
12.221892689700574
12.22189256193388
12.221892434194919
12.221892306483682
12.22189217880016
12.221892051144353
12.221891923516257
12.221891795915859
12.221891668343153
12.221891540798152
12.221891413280822
12.221891285791168
12.221891158329194
12.22189103089488
12.22189090348823
12.221890776109225
12.22189064875787
12.221890521434155
12.221890394138077
12.221890266869636
12.221890139628806
12.221890012415603
12.22188988523
12.221889758072013
12.221889630941622
12.221889503838828
12.221889376763622
12.221889249715993
12.221889122695938
12.221888995703459
12.221888868738533
12.22188874180117
12.221888614891359
12.221888488009103
12.221888361154365
12.221888234327183
12.221888107527514
12.22188798075537
12.221887854010745
12.22188772729362
12.221887600604012
12.22188747394189
12.221887347307268
12.221887220700125
12.221887094120476
12.221886967568286
12.221886841043567
12.221886714546317
12.221886588076513
12.221886461634167
12.221886335219263
12.221886208831796
12.221886082471762
12.22188595613916
12.221885829833964
12.221885703556186
12.221885577305827
12.221885451082864
12.22188532488729
12.221885198719116
12.221885072578322
12.221884946464913
12.221884820378868
12.221884694320202
12.221884568288885
12.221884442284937
12.221884316308321
12.221884190359054
12.221884064437125
12.221883938542524
12.221883812675248
12.221883686835291
12.221883561022654
12.221883435237325
12.221883309479303
12.221883183748556
12.221883058045115
12.221882932368944
12.22188280672006
12.221882681098451
12.22188255550409
12.221882429937017
12.221882304397187
12.221882178884595
12.22188205339926
12.221881927941144
12.221881802510275
12.221881677106621
12.22188155173019
12.221881426380968
12.221881301058948
12.22188117576414
12.221881050496533
12.221880925256103
12.221880800042854
12.221880674856791
12.221880549697893
12.221880424566162
12.221880299461585
12.221880174384172
12.221880049333908
12.221879924310777
12.221879799314783
12.22187967434592
12.22187954940418
12.22187942448957
12.221879299602058
12.221879174741659
12.221879049908356
12.221878925102155
12.221878800323045
12.221878675571007
12.221878550846053
12.221878426148173
12.221878301477346
12.221878176833593
12.221878052216887
12.221877927627228
12.221877803064617
12.221877678529042
12.221877554020486
12.221877429538962
12.221877305084453
12.221877180656962
12.22187705625648
12.221876931882987
12.221876807536502
12.221876683216998
12.221876558924475
12.221876434658938
12.221876310420365
12.221876186208762
12.221876062024114
12.221875937866429
12.221875813735698
12.22187568963189
12.221875565555028
12.221875441505096
12.221875317482084
12.221875193485998
12.221875069516825
12.221874945574555
12.22187482165919
12.221874697770719
12.22187457390914
12.221874450074447
12.22187432626662
12.221874202485669
12.221874078731593
12.221873955004368
12.22187383130401
12.221873707630486
12.221873583983818
12.221873460363987
12.221873336770981
12.221873213204805
12.221873089665449
12.221872966152896
12.22187284266716
12.221872719208225
12.221872595776095
12.221872472370745

12.221872348992175
12.221872225640398
12.221872102315386
12.22187197901714
12.22187185574566
12.22187173250094
12.221871609282958
12.22187148609173
12.221871362927239
12.22187123978948
12.221871116678447
12.221870993594138
12.221870870536529
12.22187074750565
12.221870624501467
12.221870501523979
12.221870378573179
12.221870255649074
12.22187013275165
12.2218700098809
12.221869887036808
12.221869764219388
12.221869641428633
12.221869518664521
12.221869395927051
12.221869273216228
12.221869150532031
12.221869027874462
12.221868905243527
12.221868782639204
12.221868660061489
12.221868537510382
12.221868414985869
12.221868292487956
12.221868170016629
12.221868047571892
12.221867925153722
12.221867802762121
12.221867680397088
12.22186755805861
12.221867435746697
12.221867313461324
12.221867191202492
12.2218670689702
12.221866946764436
12.221866824585188
12.221866702432466
12.22186658030626
12.221866458206554
12.221866336133358
12.22186621408666
12.221866092066438
12.221865970072706
12.221865848105466
12.221865726164683
12.22186560425037
12.221865482362526
12.221865360501129
12.221865238666181
12.22186511685768
12.22186499507562
12.221864873319992
12.221864751590788
12.221864629888001
12.221864508211638
12.221864386561688
12.221864264938132
12.221864143340975
12.221864021770216
12.221863900225838
12.221863778707844
12.22186365721622
12.221863535750975
12.221863414312093
12.22186329289955
12.221863171513379
12.221863050153553
12.221862928820066
12.221862807512911
12.221862686232084
12.22186256497759
12.22186244374941
12.22186232254753
12.221862201371968
12.221862080222714
12.221861959099746
12.22186183800306
12.221861716932676
12.221861595888557
12.221861474870714
12.221861353879136
12.22186123291382
12.22186111197477
12.22186099106196
12.221860870175385
12.221860749315061
12.221860628480963
12.221860507673096
12.221860386891448
12.221860266136014
12.221860145406797
12.22186002470377
12.22185990402695
12.221859783376322
12.221859662751875
12.221859542153627
12.221859421581538
12.221859301035623
12.221859180515878
12.22185906002229
12.221858939554853
12.221858819113558
12.221858698698417
12.221858578309398
12.221858457946517
12.221858337609754
12.221858217299118
12.221858097014588
12.221857976756171
12.221857856523854
12.22185773631763
12.221857616137502
12.221857495983452
12.22185737585549
12.221857255753594
12.221857135677773
12.221857015628013
12.221856895604299
12.221856775606653
12.221856655635035
12.221856535689469
12.221856415769931
12.221856295876426
12.221856176008936
12.221856056167471
12.221855936352014
12.221855816562558
12.221855696799107
12.221855577061657
12.221855457350188
12.2218553376647
12.221855218005187
12.22185509837165
12.221854978764084
12.221854859182477
12.22185473962682
12.221854620097124
12.221854500593357
12.22185438111554
12.221854261663646
12.221854142237687
12.221854022837638
12.221853903463511
12.221853784115298
12.221853664792981
12.221853545496566
12.221853426226046
12.221853306981407
12.221853187762658
12.221853068569787
12.221852949402788
12.221852830261644
12.221852711146365
12.221852592056928
12.221852472993357
12.221852353955624
12.22185223494372
12.221852115957654
12.221851996997412
12.22185187806299
12.221851759154381
12.221851640271584
12.221851521414589
12.221851402583388
12.221851283777982
12.221851164998366
12.221851046244522
12.221850927516462
12.221850808814175
12.221850690137638
12.221850571486865
12.221850452861853
12.22185033426258
12.221850215689058
12.221850097141262
12.2218499786192
12.221849860122866
12.221849741652251
12.221849623207342
12.221849504788143
12.221849386394657
12.22184926802686
12.221849149684756
12.221849031368333
12.2218489130776
12.221848794812532
12.221848676573144
12.221848558359413
12.221848440171334
12.221848322008919
12.221848203872142
12.221848085761012
12.221847967675519
12.221847849615653
12.221847731581416
12.221847613572788
12.221847495589774
12.221847377632383
12.221847259700583
12.221847141794381
12.221847023913782
12.22184690605875
12.221846788229303
12.221846670425435
12.221846552647142
12.221846434894399
12.221846317167218
12.22184619946559
12.221846081789517
12.221845964138982
12.221845846513986
12.221845728914506
12.221845611340564
12.221845493792134
12.221845376269222
12.221845258771811
12.221845141299905
12.2218450238535
12.221844906432587
12.221844789037156
12.221844671667213
12.221844554322733
12.221844437003739
12.221844319710192
12.22184420244211
12.221844085199487
12.221843967982306
12.221843850790567
12.221843733624258
12.22184361648339
12.221843499367933
12.221843382277912
12.221843265213291
12.221843148174097
12.221843031160292
12.221842914171884
12.221842797208875
12.22184268027125
12.221842563358999
12.221842446472136
12.221842329610636
12.221842212774499
12.221842095963723
12.221841979178302
12.22184186241823
12.221841745683497
12.221841628974103
12.22184151229004
12.221841395631309
12.221841278997891
12.221841162389788
12.221841045806997
12.22184092924951
12.221840812717314
12.22184069621043
12.221840579728815
12.221840463272489
12.221840346841443
12.221840230435669
12.221840114055153
12.221839997699895
12.221839881369906
12.221839765065154
12.221839648785656
12.221839532531387
12.221839416302345
12.22183930009854
12.221839183919956
12.221839067766586
12.221838951638432
12.221838835535474
12.221838719457729
12.221838603405166
12.221838487377802
12.221838371375622
12.221838255398609
12.221838139446769
12.221838023520105
12.221837907618603
12.221837791742253
12.22183767589105
12.221837560065003
12.221837444264084
12.221837328488304
12.221837212737652
12.221837097012132
12.221836981311718
12.221836865636417
12.221836749986235
12.221836634361146
12.22183651876116
12.221836403186252
12.22183628763643
12.2218361721117
12.221836056612045
12.221835941137448
12.221835825687915
12.221835710263454
12.221835594864029
12.22183547948966
12.221835364140334
12.221835248816038
12.22183513351678
12.221835018242544
12.22183490299332
12.221834787769122
12.221834672569932
12.221834557395741
12.22183444224655
12.221834327122362
12.221834212023152
12.22183409694892
12.221833981899668
12.2218338668754
12.221833751876071
12.221833636901724
12.22183352195232
12.221833407027876
12.221833292128371
12.221833177253796
12.221833062404174
12.22183294757946
12.221832832779684
12.221832718004817
12.221832603254867
12.221832488529818
12.221832373829663
12.221832259154406
12.221832144504054
12.221832029878577
12.221831915277978
12.221831800702256
12.221831686151399
12.221831571625406
12.221831457124274
12.221831342647988
12.221831228196566
12.221831113769962
12.221830999368205
12.221830884991283
12.221830770639171
12.221830656311887
12.221830542009425
12.221830427731765
12.221830313478906
12.221830199250858
12.221830085047594
12.221829970869118
12.22182985671542
12.221829742586507
12.221829628482357
12.221829514402978
12.221829400348371
12.22182928631851
12.221829172313385
12.221829058333023
12.221828944377393
12.221828830446503
12.221828716540333
12.221828602658885
12.221828488802165
12.221828374970144
12.221828261162832
12.221828147380235
12.221828033622328
12.221827919889114
12.221827806180578
12.221827692496719
12.22182757883755
12.221827465203038
12.221827351593202
12.221827238008014
12.221827124447477
12.221827010911598
12.221826897400353
12.221826783913757
12.221826670451783
12.221826557014442
12.22182644360172
12.221826330213608
12.221826216850113
12.22182610351122
12.22182599019693
12.221825876907236
12.22182576364213
12.221825650401609
12.221825537185657
12.221825423994288
12.22182531082749
12.221825197685241
12.221825084567566
12.221824971474433
12.221824858405846
12.221824745361811
12.221824632342296
12.221824519347315
12.221824406376866
12.221824293430938
12.221824180509525
12.221824067612609
12.221823954740213
12.221823841892308
12.221823729068904
12.221823616269976
12.221823503495532
12.221823390745568
12.221823278020087
12.221823165319057
12.221823052642492
12.221822939990389
12.221822827362738
12.221822714759528
12.221822602180765
12.221822489626424
12.221822377096526
12.221822264591042
12.221822152109977
12.221822039653327
12.221821927221102
12.221821814813262
12.221821702429821
12.221821590070775
12.221821477736118
12.221821365425845
12.221821253139947
12.22182114087842
12.221821028641251
12.221820916428456
12.22182080424001
12.221820692075923
12.22182057993617
12.221820467820763
12.221820355729683
12.22182024366293
12.221820131620513
12.221820019602418
12.221819907608625
12.221819795639139
12.221819683693965
12.221819571773075
12.221819459876487
12.221819348004182
12.221819236156167
12.221819124332425
12.221819012532954
12.221818900757734
12.22181878900679
12.221818677280101
12.221818565577667
12.221818453899465
12.221818342245513
12.221818230615785
12.221818119010283
12.221818007429022
12.221817895871968
12.221817784339128
12.221817672830497
12.22181756134607
12.221817449885835
12.221817338449801
12.221817227037947
12.221817115650278
12.22181700428679
12.22181689294747
12.221816781632308
12.22181667034131
12.221816559074476
12.221816447831783
12.22181633661324
12.221816225418838
12.221816114248565
12.221816003102425
12.221815891980407
12.221815780882514
12.221815669808725
12.221815558759054
12.221815447733478
12.221815336732
12.221815225754625
12.22181511480133
12.221815003872115
12.221814892966984
12.221814782085922
12.22181467122891
12.221814560395984
12.221814449587109
12.221814338802272
12.22181422804149
12.221814117304751
12.221814006592039
12.221813895903358
12.221813785238705
12.221813674598076
12.22181356398146
12.221813453388844
12.221813342820242
12.221813232275634
12.22181312175502
12.221813011258387
12.221812900785746
12.221812790337083
12.221812679912388
12.221812569511666
12.221812459134904
12.221812348782098
12.221812238453243
12.221812128148343
12.221812017867377
12.221811907610347
12.221811797377244
12.221811687168078
12.221811576982821
12.221811466821487
12.221811356684062
12.221811246570537
12.221811136480916
12.221811026415192
12.221810916373364
12.221810806355409
12.22181069636134
12.221810586391133
12.221810476444805
12.22181036652234
12.221810256623728

12.221810146748979
12.221810036898061
12.221809927071007
12.221809817267783
12.221809707488383
12.22180959773282
12.221809488001082
12.221809378293154
12.221809268609036
12.221809158948735
12.221809049312222
12.221808939699509
12.221808830110596
12.22180872054546
12.221808611004112
12.221808501486532
12.221808391992734
12.221808282522687
12.221808173076408
12.221808063653882
12.221807954255116
12.221807844880079
12.221807735528785
12.221807626201239
12.221807516897407
12.2218074076173
12.221807298360925
12.221807189128254
12.221807079919285
12.221806970734038
12.221806861572475
12.22180675243461
12.221806643320432
12.22180653422994
12.221806425163125
12.221806316119979
12.221806207100506
12.221806098104688
12.221805989132532
12.221805880184027
12.221805771259177
12.221805662357962
12.221805553480383
12.221805444626428
12.221805335796118
12.221805226989408
12.221805118206333
12.221805009446866
12.221804900711001
12.22180479199873
12.221804683310063
12.22180457464499
12.221804466003498
12.221804357385587
12.221804248791248
12.221804140220481
12.221804031673285
12.22180392314964
12.221803814649551
12.22180370617302
12.221803597720028
12.221803489290568
12.221803380884662
12.221803272502266
12.221803164143408
12.221803055808055
12.221802947496224
12.221802839207905
12.221802730943091
12.221802622701771
12.22180251448394
12.2218024062896
12.221802298118748
12.221802189971365
12.22180208184747
12.22180197374703
12.221801865670056
12.221801757616547
12.22180164958648
12.221801541579879
12.221801433596706
12.221801325636969
12.22180121770067
12.221801109787794
12.221801001898335
12.221800894032308
12.22180078618968
12.221800678370462
12.221800570574652
12.221800462802237
12.221800355053219
12.22180024732758
12.221800139625318
12.221800031946438
12.221799924290934
12.221799816658793
12.221799709050014
12.221799601464587
12.221799493902514
12.221799386363784
12.221799278848398
12.221799171356354
12.221799063887637
12.221798956442237
12.221798849020164
12.221798741621411
12.221798634245957
12.221798526893828
12.221798419564994
12.221798312259443
12.221798204977187
12.221798097718219
12.221797990482536
12.221797883270119
12.221797776080974
12.221797668915105
12.221797561772489
12.22179745465312
12.22179734755701
12.221797240484145
12.221797133434526
12.22179702640813
12.221796919404962
12.22179681242503
12.22179670546831
12.221796598534809
12.221796491624522
12.221796384737422
12.221796277873539
12.221796171032851
12.221796064215336
12.221795957421019
12.221795850649881
12.221795743901922
12.221795637177122
12.22179553047549
12.22179542379702
12.2217953171417
12.221795210509532
12.221795103900497
12.221794997314621
12.221794890751871
12.221794784212248
12.221794677695753
12.221794571202366
12.221794464732112
12.221794358284955
12.221794251860901
12.221794145459945
12.22179403908209
12.221793932727325
12.22179382639564
12.221793720087037
12.221793613801502
12.22179350753904
12.221793401299646
12.221793295083298
12.221793188890016
12.221793082719783
12.221792976572589
12.221792870448438
12.221792764347317
12.22179265826923
12.22179255221416
12.221792446182112
12.221792340173083
12.221792234187054
12.221792128224044
12.221792022284019
12.221791916366993
12.221791810472956
12.221791704601902
12.22179159875383
12.22179149292873
12.221791387126597
12.221791281347436
12.221791175591223
12.22179106985797
12.221790964147665
12.221790858460308
12.221790752795885
12.221790647154393
12.22179054153584
12.221790435940212
12.221790330367494
12.221790224817694
12.221790119290809
12.221790013786821
12.221789908305738
12.221789802847544
12.22178969741224
12.221789591999832
12.221789486610295
12.221789381243617
12.22178927589983
12.2217891705789
12.221789065280827
12.221788960005616
12.221788854753253
12.221788749523727
12.22178864431706
12.221788539133202
12.221788433972193
12.221788328834009
12.221788223718638
12.221788118626076
12.221788013556337
12.221787908509388
12.22178780348525
12.221787698483903
12.221787593505356
12.221787488549591
12.2217873836166
12.221787278706385
12.221787173818948
12.22178706895427
12.221786964112347
12.22178685929319
12.221786754496785
12.221786649723116
12.22178654497219
12.221786440244012
12.221786335538559
12.221786230855821
12.221786126195825
12.221786021558524
12.221785916943944
12.221785812352069
12.221785707782903
12.221785603236425
12.221785498712642
12.221785394211542
12.221785289733123
12.22178518527739
12.221785080844322
12.221784976433918
12.221784872046182
12.221784767681097
12.221784663338669
12.22178455901889
12.221784454721746
12.221784350447242
12.221784246195378
12.221784141966133
12.221784037759521
12.221783933575509
12.221783829414127
12.22178372527535
12.221783621159176
12.221783517065589
12.22178341299461
12.221783308946211
12.221783204920397
12.221783100917161
12.221782996936499
12.221782892978414
12.22178278904288
12.221782685129906
12.221782581239498
12.221782477371631
12.221782373526311
12.221782269703523
12.221782165903276
12.22178206212556
12.221781958370364
12.221781854637698
12.221781750927542
12.221781647239894
12.221781543574746
12.221781439932103
12.22178133631195
12.221781232714296
12.221781129139124
12.221781025586436
12.22178092205622
12.221780818548481
12.221780715063206
12.221780611600385
12.221780508160021
12.221780404742118
12.221780301346659
12.221780197973642
12.221780094623055
12.221779991294907
12.221779887989184
12.221779784705877
12.221779681444996
12.221779578206528
12.221779474990466
12.221779371796798
12.221779268625543
12.22177916547667
12.221779062350185
12.221778959246096
12.22177885616437
12.221778753105017
12.22177865006805
12.221778547053438
12.221778444061183
12.221778341091285
12.221778238143738
12.221778135218534
12.221778032315664
12.221777929435136
12.221777826576929
12.22177772374106
12.2217776209275
12.221777518136264
12.221777415367331
12.221777312620704
12.221777209896382
12.221777107194361
12.221777004514626
12.221776901857174
12.221776799222008
12.221776696609117
12.221776594018495
12.221776491450148
12.221776388904061
12.221776286380234
12.221776183878646
12.221776081399314
12.221775978942231
12.221775876507376
12.221775774094766
12.221775671704375
12.221775569336211
12.221775466990259
12.221775364666533
12.221775262365007
12.221775160085688
12.22177505782857
12.221774955593641
12.221774853380907
12.221774751190363
12.221774649021993
12.221774546875803
12.221774444751786
12.221774342649926
12.221774240570225
12.221774138512693
12.221774036477296
12.22177393446405
12.221773832472957
12.221773730503998
12.22177362855716
12.22177352663246
12.221773424729875
12.221773322849414
12.22177322099107
12.221773119154825
12.221773017340684
12.221772915548643
12.221772813778692
12.221772712030837
12.22177261030506
12.22177250860137
12.221772406919753
12.221772305260206
12.22177220362272
12.221772102007295
12.221772000413923
12.221771898842604
12.221771797293334
12.221771695766101
12.221771594260904
12.221771492777748
12.221771391316606
12.221771289877491
12.221771188460398
12.22177108706531
12.221770985692233
12.221770884341154
12.221770783012081
12.221770681704996
12.221770580419902
12.221770479156788
12.221770377915657
12.221770276696503
12.221770175499309
12.221770074324091
12.221769973170826
12.221769872039516
12.221769770930152
12.221769669842745
12.221769568777274
12.221769467733736
12.221769366712131
12.221769265712455
12.221769164734688
12.221769063778856
12.221768962844926
12.221768861932908
12.221768761042789
12.221768660174574
12.22176855932825
12.221768458503812
12.221768357701254
12.221768256920585
12.221768156161778
12.221768055424846
12.221767954709783
12.221767854016576
12.22176775334523
12.221767652695728
12.221767552068071
12.221767451462258
12.221767350878281
12.22176725031613
12.22176714977582
12.22176704925732
12.221766948760642
12.221766848285776
12.221766747832715
12.221766647401461
12.221766546992008
12.221766446604343
12.221766346238468
12.221766245894377
12.221766145572065
12.221766045271533
12.221765944992766
12.221765844735765
12.221765744500521
12.22176564428704
12.221765544095307
12.221765443925317
12.221765343777067
12.221765243650568
12.22176514354579
12.221765043462742
12.221764943401421
12.221764843361816
12.221764743343913
12.221764643347731
12.221764543373252
12.221764443420467
12.221764343489374
12.22176424357998
12.221764143692274
12.221764043826239
12.221763943981877
12.221763844159197
12.22176374435818
12.221763644578822
12.221763544821119
12.221763445085074
12.22176334537067
12.22176324567791
12.221763146006792
12.221763046357312
12.221762946729449
12.221762847123218
12.221762747538605
12.221762647975604
12.221762548434215
12.22176244891443
12.221762349416247
12.221762249939658
12.221762150484661
12.221762051051243
12.221761951639417
12.22176185224917
12.221761752880488
12.22176165353338
12.221761554207838
12.221761454903842
12.221761355621403
12.221761256360523
12.221761157121177
12.22176105790337
12.221760958707108
12.221760859532372
12.221760760379164
12.221760661247469
12.221760562137296
12.22176046304863
12.221760363981481
12.221760264935824
12.221760165911665
12.221760066909004
12.221759967927838
12.221759868968146
12.221759770029927
12.221759671113197
12.221759572217922
12.221759473344129
12.221759374491786
12.221759275660895
12.221759176851455
12.221759078063469
12.221758979296931
12.221758880551814
12.22175878182814
12.221758683125888
12.221758584445064
12.221758485785651
12.22175838714766
12.221758288531074
12.221758189935892
12.221758091362108
12.221757992809726
12.221757894278728
12.221757795769124
12.22175769728089
12.221757598814042
12.221757500368563
12.221757401944448
12.22175730354171
12.221757205160314
12.221757106800279
12.22175700846159
12.221756910144242
12.22175681184824
12.22175671357357
12.221756615320231
12.22175651708822
12.221756418877519
12.221756320688153
12.221756222520087
12.221756124373327
12.221756026247883
12.221755928143718
12.221755830060854
12.22175573199928
12.221755633958992
12.22175553593998
12.221755437942242
12.221755339965773
12.221755242010579
12.221755144076633
12.221755046163953
12.221754948272519
12.22175485040234
12.221754752553394
12.221754654725693
12.221754556919224
12.221754459133988
12.221754361369975
12.221754263627172
12.221754165905582
12.221754068205206
12.221753970526047
12.221753872868085
12.221753775231313
12.221753677615732
12.221753580021344
12.221753482448129
12.221753384896106
12.221753287365248
12.22175318985556
12.221753092367038
12.221752994899676
12.221752897453465
12.221752800028408
12.221752702624494
12.221752605241731
12.221752507880097
12.221752410539592
12.221752313220213
12.221752215921972
12.22175211864484
12.221752021388808

12.2217519241539
12.221751826940096
12.221751729747398
12.221751632575787
12.221751535425275
12.22175143829584
12.221751341187488
12.221751244100211
12.221751147034016
12.22175104998888
12.221750952964806
12.221750855961806
12.221750758979848
12.221750662018945
12.221750565079077
12.221750468160254
12.221750371262475
12.221750274385723
12.221750177529989
12.221750080695294
12.221749983881603
12.221749887088931
12.221749790317267
12.22174969356661
12.221749596836956
12.221749500128286
12.221749403440612
12.221749306773916
12.221749210128209
12.221749113503476
12.22174901689973
12.22174892031693
12.221748823755103
12.22174872721423
12.221748630694316
12.221748534195354
12.221748437717336
12.22174834126025
12.22174824482411
12.2217481484089
12.221748052014608
12.221747955641247
12.221747859288804
12.221747762957262
12.221747666646637
12.221747570356918
12.221747474088094
12.221747377840167
12.221747281613133
12.221747185406988
12.221747089221708
12.221746993057314
12.221746896913798
12.221746800791145
12.22174670468936
12.221746608608434
12.221746512548346
12.221746416509125
12.221746320490748
12.221746224493204
12.221746128516495
12.221746032560631
12.221745936625585
12.221745840711359
12.22174574481796
12.221745648945358
12.221745553093578
12.2217454572626
12.221745361452419
12.221745265663039
12.221745169894449
12.221745074146641
12.221744978419613
12.221744882713372
12.221744787027891
12.22174469136318
12.221744595719247
12.221744500096067
12.221744404493634
12.22174430891196
12.221744213351025
12.221744117810838
12.221744022291388
12.221743926792657
12.22174383131467
12.221743735857409
12.221743640420847
12.22174354500501
12.221743449609882
12.22174335423547
12.221743258881741
12.221743163548721
12.221743068236394
12.22174297294474
12.22174287767378
12.221742782423494
12.221742687193888
12.22174259198494
12.221742496796672
12.221742401629053
12.221742306482092
12.221742211355783
12.221742116250129
12.221742021165108
12.221741926100727
12.22174183105698
12.221741736033865
12.221741641031366
12.221741546049497
12.221741451088235
12.2217413561476
12.221741261227553
12.22174116632811
12.221741071449275
12.221740976591025
12.22174088175337
12.221740786936296
12.221740692139802
12.221740597363887
12.22174050260854
12.221740407873758
12.221740313159543
12.221740218465879
12.221740123792774
12.221740029140205
12.221739934508197
12.221739839896722
12.221739745305781
12.22173965073537
12.221739556185483
12.221739461656126
12.221739367147284
12.221739272658949
12.221739178191124
12.221739083743815
12.221738989316995
12.221738894910665
12.221738800524834
12.221738706159488
12.221738611814628
12.221738517490236
12.221738423186334
12.221738328902875
12.221738234639892
12.221738140397372
12.221738046175311
12.221737951973688
12.221737857792517
12.221737763631793
12.221737669491498
12.221737575371643
12.221737481272212
12.22173738719321
12.221737293134616
12.221737199096454
12.22173710507869
12.221737011081336
12.221736917104389
12.22173682314783
12.22173672921167
12.221736635295901
12.221736541400515
12.221736447525506
12.22173635367087
12.221736259836609
12.22173616602271
12.22173607222918
12.221735978456003
12.221735884703184
12.221735790970707
12.221735697258582
12.22173560356679
12.221735509895339
12.221735416244218
12.221735322613426
12.221735229002954
12.221735135412786
12.221735041842956
12.22173494829342
12.221734854764193
12.221734761255272
12.221734667766633
12.221734574298297
12.221734480850255
12.221734387422472
12.221734294014983
12.22173420062777
12.221734107260817
12.221734013914139
12.221733920587713
12.221733827281547
12.221733733995638
12.221733640729957
12.221733547484549
12.22173345425936
12.221733361054412
12.221733267869691
12.221733174705193
12.221733081560929
12.221732988436866
12.221732895333021
12.221732802249385
12.221732709185963
12.221732616142713
12.22173252311968
12.22173243011683
12.221732337134167
12.221732244171688
12.221732151229387
12.22173205830726
12.221731965405295
12.221731872523497
12.22173177966186
12.22173168682038
12.221731593999047
12.221731501197857
12.221731408416826
12.221731315655918
12.221731222915142
12.221731130194508
12.221731037493987
12.221730944813592
12.221730852153314
12.221730759513148
12.221730666893084
12.221730574293128
12.221730481713266
12.221730389153512
12.221730296613828
12.221730204094237
12.221730111594729
12.2217300191153
12.221729926655943
12.221729834216651
12.221729741797427
12.221729649398261
12.221729557019149
12.221729464660084
12.22172937232107
12.221729280002096
12.221729187703161
12.221729095424253
12.221729003165379
12.221728910926537
12.22172881870771
12.221728726508893
12.221728634330091
12.221728542171299
12.221728450032506
12.221728357913719
12.221728265814916
12.221728173736107
12.221728081677288
12.221727989638445
12.221727897619587
12.22172780562069
12.221727713641764
12.221727621682804
12.221727529743804
12.221727437824761
12.221727345925657
12.221727254046513
12.221727162187307
12.221727070348043
12.221726978528705
12.221726886729304
12.221726794949815
12.221726703190264
12.221726611450618
12.221726519730888
12.221726428031062
12.22172633635114
12.221726244691117
12.221726153050996
12.221726061430756
12.221725969830402
12.221725878249936
12.221725786689346
12.221725695148626
12.221725603627776
12.221725512126785
12.221725420645667
12.221725329184387
12.221725237742968
12.221725146321406
12.221725054919668
12.221724963537786
12.22172487217573
12.221724780833505
12.221724689511111
12.221724598208526
12.221724506925765
12.22172441566282
12.221724324419666
12.221724233196346
12.2217241419928
12.221724050809057
12.221723959645116
12.22172386850095
12.221723777376576
12.221723686271972
12.221723595187148
12.22172350412208
12.221723413076786
12.22172332205126
12.221723231045486
12.221723140059467
12.221723049093193
12.221722958146666
12.221722867219874
12.22172277631282
12.2217226854255
12.221722594557905
12.221722503710037
12.22172241288188
12.221722322073434
12.221722231284703
12.221722140515674
12.221722049766354
12.221721959036724
12.221721868326787
12.221721777636553
12.22172168696599
12.221721596315103
12.221721505683902
12.221721415072368
12.221721324480495
12.221721233908292
12.22172114335575
12.221721052822854
12.221720962309602
12.221720871816014
12.22172078134206
12.221720690887743
12.221720600453056
12.221720510037995
12.221720419642569
12.221720329266748
12.221720238910557
12.221720148573976
12.221720058256995
12.221719967959627
12.221719877681846
12.22171978742367
12.221719697185073
12.221719606966074
12.221719516766656
12.22171942658681
12.221719336426537
12.221719246285831
12.221719156164701
12.221719066063121
12.221718975981103
12.22171888591863
12.22171879587571
12.221718705852334
12.221718615848502
12.221718525864201
12.221718435899424
12.221718345954185
12.22171825602846
12.221718166122256
12.221718076235561
12.22171798636838
12.221717896520719
12.22171780669254
12.221717716883866
12.221717627094684
12.221717537324986
12.22171744757477
12.221717357844044
12.221717268132798
12.221717178441011
12.221717088768694
12.22171699911584
12.221716909482447
12.221716819868508
12.221716730274022
12.221716640698986
12.221716551143382
12.221716461607219
12.221716372090487
12.221716282593192
12.221716193115322
12.221716103656863
12.221716014217833
12.221715924798204
12.221715835397998
12.221715746017175
12.221715656655775
12.221715567313762
12.221715477991129
12.2217153886879
12.221715299404043
12.221715210139573
12.221715120894475
12.221715031668742
12.22171494246238
12.221714853275387
12.221714764107736
12.221714674959452
12.22171458583051
12.22171449672092
12.221714407630662
12.221714318559748
12.22171422950816
12.221714140475905
12.22171405146298
12.221713962469364
12.22171387349507
12.221713784540087
12.221713695604414
12.22171360668804
12.221713517790972
12.221713428913187
12.2217133400547
12.221713251215501
12.221713162395583
12.22171307359494
12.221712984813578
12.221712896051484
12.221712807308649
12.22171271858508
12.221712629880768
12.221712541195707
12.221712452529898
12.221712363883334
12.221712275255998
12.221712186647919
12.22171209805906
12.221712009489435
12.22171192093903
12.221711832407847
12.221711743895877
12.22171165540312
12.22171156692957
12.221711478475223
12.221711390040069
12.221711301624115
12.221711213227357
12.22171112484977
12.221711036491373
12.221710948152163
12.221710859832116
12.221710771531248
12.221710683249535
12.221710594986996
12.221710506743598
12.221710418519368
12.221710330314274
12.22171024212833
12.221710153961535
12.221710065813863
12.221709977685332
12.221709889575935
12.22170980148565
12.221709713414493
12.221709625362436
12.221709537329502
12.22170944931567
12.221709361320952
12.221709273345327
12.221709185388798
12.221709097451361
12.22170900953301
12.221708921633748
12.221708833753548
12.221708745892439
12.221708658050384
12.221708570227404
12.221708482423491
12.22170839463862
12.221708306872815
12.221708219126052
12.221708131398339
12.221708043689668
12.221707956000039
12.221707868329437
12.221707780677859
12.221707693045312
12.221707605431783
12.221707517837272
12.221707430261773
12.221707342705269
12.221707255167793
12.221707167649303
12.22170708014981
12.221706992669311
12.221706905207792
12.221706817765268
12.221706730341712
12.221706642937137
12.221706555551535
12.221706468184896
12.221706380837224
12.221706293508506
12.221706206198744
12.221706118907933
12.22170603163607
12.221705944383144
12.221705857149159
12.22170576993411
12.221705682737987
12.221705595560795
12.221705508402517
12.221705421263165
12.221705334142722
12.221705247041188
12.221705159958562
12.221705072894826
12.22170498585
12.221704898824063
12.221704811817018
12.221704724828854
12.221704637859563
12.221704550909164
12.22170446397762
12.22170437706496
12.221704290171168
12.22170420329622
12.22170411644014
12.221704029602902
12.221703942784524
12.221703855984973
12.221703769204273
12.221703682442408
12.221703595699367
12.221703508975159
12.22170342226978
12.22170333558321
12.221703248915466
12.221703162266522
12.221703075636396
12.221702989025065
12.22170290243253
12.221702815858798
12.221702729303848
12.221702642767701
12.221702556250325
12.221702469751724
12.221702383271902
12.221702296810852
12.221702210368562
12.221702123945036
12.221702037540267
12.221701951154259
12.221701864786993
12.221701778438476
12.221701692108708
12.22170160579767
12.221701519505366
12.221701433231793
12.221701346976939
12.221701260740815
12.221701174523409
12.221701088324712
12.221701002144727
12.221700915983442
12.221700829840866
12.221700743716985
12.221700657611791
12.221700571525284
12.221700485457474
12.221700399408336
12.22170031337788
12.22170022736609

12.22170014137298
12.221700055398522
12.221699969442726
12.22169988350559
12.22169979758711
12.221699711687272
12.221699625806087
12.221699539943524
12.221699454099618
12.221699368274336
12.221699282467682
12.221699196679657
12.221699110910249
12.221699025159458
12.221698939427272
12.221698853713702
12.221698768018731
12.22169868234236
12.221698596684584
12.22169851104541
12.221698425424815
12.221698339822805
12.22169825423938
12.22169816867452
12.22169808312824
12.221697997600526
12.221697912091374
12.221697826600783
12.221697741128743
12.221697655675264
12.221697570240327
12.221697484823933
12.221697399426079
12.221697314046759
12.221697228685978
12.221697143343713
12.221697058019977
12.22169697271476
12.221696887428052
12.22169680215987
12.221696716910188
12.221696631679
12.221696546466315
12.22169646127214
12.221696376096443
12.221696290939239
12.221696205800514
12.221696120680265
12.221696035578498
12.221695950495198
12.22169586543037
12.221695780384003
12.221695695356095
12.221695610346641
12.221695525355631
12.221695440383082
12.221695355428972
12.221695270493296
12.221695185576065
12.221695100677254
12.221695015796875
12.221694930934921
12.221694846091385
12.221694761266262
12.221694676459546
12.221694591671246
12.22169450690134
12.221694422149843
12.221694337416734
12.22169425270202
12.221694168005687
12.221694083327748
12.22169399866818
12.22169391402699
12.221693829404177
12.22169374479972
12.22169366021363
12.22169357564591
12.22169349109653
12.221693406565507
12.221693322052827
12.22169323755849
12.221693153082501
12.221693068624841
12.221692984185522
12.221692899764514
12.221692815361838
12.22169273097748
12.221692646611443
12.221692562263717
12.22169247793429
12.22169239362317
12.221692309330356
12.221692225055833
12.221692140799592
12.221692056561654
12.22169197234199
12.221691888140619
12.221691803957514
12.22169171979268
12.221691635646112
12.221691551517814
12.22169146740777
12.221691383315981
12.221691299242451
12.221691215187164
12.221691131150125
12.221691047131321
12.221690963130763
12.221690879148424
12.22169079518432
12.221690711238441
12.221690627310776
12.22169054340133
12.221690459510102
12.221690375637083
12.221690291782263
12.221690207945644
12.22169012412723
12.221690040326989
12.221689956544942
12.221689872781097
12.221689789035423
12.221689705307925
12.2216896215986
12.221689537907439
12.22168945423445
12.221689370579623
12.221689286942949
12.221689203324425
12.221689119724056
12.221689036141827
12.221688952577745
12.221688869031805
12.221688785503988
12.221688701994303
12.22168861850274
12.221688535029315
12.221688451573984
12.221688368136787
12.221688284717699
12.221688201316706
12.221688117933812
12.221688034569027
12.22168795122234
12.221687867893728
12.22168778458321
12.22168770129077
12.221687618016421
12.22168753476013
12.221687451521932
12.22168736830178
12.2216872850997
12.22168720191567
12.221687118749701
12.221687035601786
12.221686952471916
12.221686869360084
12.221686786266297
12.22168670319055
12.221686620132834
12.221686537093138
12.221686454071461
12.221686371067808
12.221686288082175
12.221686205114558
12.22168612216494
12.22168603923333
12.221685956319714
12.221685873424095
12.221685790546479
12.221685707686852
12.221685624845197
12.221685542021527
12.221685459215836
12.221685376428116
12.221685293658368
12.22168521090658
12.221685128172757
12.221685045456892
12.221684962758982
12.22168488007902
12.221684797417
12.221684714772914
12.221684632146776
12.221684549538574
12.221684466948295
12.221684384375955
12.221684301821526
12.221684219285015
12.221684136766417
12.221684054265737
12.221683971782962
12.221683889318086
12.221683806871102
12.221683724442022
12.221683642030833
12.221683559637528
12.221683477262115
12.221683394904575
12.22168331256491
12.221683230243125
12.221683147939197
12.221683065653131
12.221682983384927
12.221682901134582
12.221682818902096
12.22168273668745
12.221682654490655
12.221682572311693
12.221682490150561
12.221682408007274
12.221682325881819
12.221682243774179
12.221682161684374
12.221682079612371
12.221681997558193
12.221681915521819
12.221681833503256
12.221681751502485
12.221681669519525
12.221681587554338
12.221681505606966
12.221681423677365
12.221681341765546
12.221681259871517
12.221681177995254
12.221681096136772
12.221681014296053
12.221680932473094
12.221680850667887
12.22168076888045
12.221680687110762
12.221680605358813
12.221680523624624
12.221680441908157
12.221680360209435
12.221680278528442
12.221680196865186
12.221680115219653
12.221680033591834
12.221679951981733
12.22167987038935
12.221679788814685
12.22167970725771
12.221679625718437
12.221679544196872
12.221679462692997
12.221679381206808
12.221679299738309
12.221679218287498
12.221679136854357
12.221679055438889
12.221678974041104
12.221678892660972
12.22167881129851
12.221678729953716
12.221678648626565
12.221678567317069
12.22167848602523
12.221678404751025
12.22167832349446
12.22167824225554
12.22167816103425
12.221678079830582
12.221677998644555
12.221677917476137
12.221677836325336
12.221677755192148
12.221677674076576
12.221677592978597
12.221677511898234
12.221677430835458
12.221677349790287
12.221677268762708
12.221677187752706
12.221677106760295
12.221677025785455
12.2216769448282
12.221676863888513
12.221676782966393
12.221676702061833
12.221676621174838
12.221676540305403
12.221676459453507
12.221676378619177
12.221676297802377
12.221676217003127
12.221676136221411
12.221676055457234
12.221675974710582
12.221675893981459
12.221675813269847
12.221675732575763
12.221675651899194
12.221675571240137
12.221675490598583
12.221675409974532
12.221675329367985
12.221675248778922
12.221675168207364
12.221675087653288
12.221675007116692
12.221674926597583
12.221674846095949
12.22167476561179
12.221674685145091
12.221674604695872
12.221674524264099
12.221674443849789
12.221674363452937
12.22167428307353
12.22167420271157
12.221674122367062
12.221674042039975
12.221673961730332
12.22167388143812
12.221673801163332
12.22167372090598
12.221673640666035
12.221673560443504
12.221673480238392
12.22167340005069
12.221673319880386
12.22167323972749
12.221673159591985
12.221673079473877
12.221672999373155
12.221672919289825
12.221672839223865
12.221672759175291
12.22167267914409
12.221672599130265
12.221672519133795
12.2216724391547
12.221672359192954
12.221672279248574
12.221672199321544
12.221672119411858
12.221672039519515
12.22167195964452
12.221671879786847
12.221671799946522
12.221671720123528
12.221671640317851
12.221671560529495
12.221671480758458
12.221671401004734
12.22167132126832
12.221671241549215
12.221671161847418
12.221671082162914
12.22167100249571
12.221670922845789
12.22167084321316
12.221670763597814
12.221670683999758
12.221670604418962
12.221670524855451
12.221670445309206
12.221670365780229
12.221670286268509
12.221670206774043
12.221670127296843
12.221670047836874
12.221669968394174
12.221669888968703
12.22166980956048
12.221669730169486
12.221669650795729
12.2216695714392
12.221669492099887
12.221669412777802
12.22166933347293
12.221669254185274
12.221669174914824
12.221669095661586
12.22166901642554
12.221668937206697
12.22166885800505
12.221668778820595
12.221668699653316
12.221668620503232
12.221668541370315
12.221668462254586
12.221668383156024
12.221668304074626
12.221668225010395
12.221668145963331
12.221668066933413
12.22166798792066
12.221667908925049
12.221667829946592
12.221667750985267
12.221667672041091
12.221667593114041
12.221667514204132
12.221667435311339
12.221667356435667
12.221667277577128
12.221667198735695
12.221667119911379
12.221667041104169
12.221666962314067
12.221666883541063
12.221666804785162
12.221666726046351
12.221666647324623
12.221666568619991
12.221666489932439
12.221666411261968
12.221666332608565
12.221666253972234
12.221666175352981
12.221666096750791
12.221666018165655
12.221665939597584
12.22166586104655
12.221665782512583
12.221665703995647
12.22166562549576
12.221665547012918
12.221665468547101
12.221665390098313
12.221665311666559
12.221665233251823
12.221665154854113
12.22166507647342
12.22166499810973
12.221664919763057
12.221664841433386
12.221664763120721
12.221664684825052
12.221664606546364
12.221664528284682
12.221664450039983
12.221664371812256
12.22166429360152
12.22166421540776
12.221664137230965
12.221664059071141
12.221663980928286
12.22166390280239
12.221663824693444
12.22166374660145
12.22166366852642
12.221663590468324
12.221663512427167
12.221663434402963
12.22166335639568
12.221663278405336
12.221663200431928
12.221663122475434

12.221663044535859
12.221662966613204
12.221662888707453
12.221662810818621
12.221662732946694
12.221662655091665
12.221662577253538
12.221662499432309
12.221662421627963
12.221662343840507
12.221662266069934
12.221662188316243
12.22166211057943
12.22166203285949
12.221661955156415
12.221661877470206
12.22166179980085
12.221661722148367
12.221661644512736
12.22166156689394
12.221661489292007
12.221661411706915
12.221661334138666
12.221661256587247
12.22166117905266
12.221661101534906
12.221661024033974
12.221660946549862
12.221660869082571
12.22166079163209
12.221660714198412
12.221660636781564
12.221660559381505
12.221660481998246
12.221660404631779
12.221660327282121
12.221660249949228
12.221660172633134
12.221660095333817
12.221660018051276
12.221659940785518
12.22165986353652
12.221659786304286
12.221659709088826
12.221659631890128
12.221659554708177
12.22165947754298
12.22165940039453
12.221659323262832
12.221659246147869
12.221659169049646
12.22165909196816
12.221659014903395
12.22165893785537
12.22165886082405
12.221658783809465
12.221658706811592
12.221658629830431
12.221658552865984
12.221658475918222
12.221658398987179
12.22165832207284
12.22165824517517
12.221658168294217
12.221658091429932
12.221658014582339
12.221657937751427
12.221657860937192
12.22165778413962
12.221657707358721
12.221657630594494
12.221657553846917
12.221657477116004
12.221657400401744
12.221657323704141
12.22165724702318
12.221657170358863
12.221657093711185
12.22165701708014
12.22165694046573
12.221656863867956
12.221656787286804
12.22165671072227
12.221656634174346
12.221656557643056
12.221656481128365
12.221656404630286
12.221656328148805
12.221656251683926
12.221656175235644
12.221656098803958
12.221656022388858
12.22165594599034
12.221655869608414
12.221655793243068
12.221655716894286
12.221655640562078
12.22165556424644
12.221655487947368
12.221655411664848
12.221655335398893
12.221655259149488
12.221655182916644
12.22165510670033
12.221655030500566
12.221654954317344
12.221654878150646
12.221654802000486
12.221654725866863
12.22165464974976
12.22165457364917
12.22165449756511
12.221654421497554
12.221654345446513
12.22165426941198
12.221654193393938
12.221654117392411
12.221654041407362
12.221653965438826
12.221653889486769
12.221653813551196
12.22165373763211
12.221653661729496
12.221653585843374
12.221653509973699
12.221653434120496
12.221653358283765
12.221653282463498
12.221653206659672
12.221653130872305
12.22165305510139
12.221652979346924
12.221652903608899
12.221652827887317
12.221652752182154
12.221652676493434
12.221652600821146
12.221652525165275
12.221652449525823
12.221652373902792
12.221652298296178
12.221652222705973
12.221652147132172
12.22165207157478
12.221651996033781
12.22165192050918
12.221651845000972
12.221651769509153
12.221651694033714
12.221651618574661
12.221651543132
12.221651467705692
12.22165139229577
12.221651316902207
12.221651241525011
12.221651166164172
12.22165109081969
12.221651015491569
12.221650940179794
12.221650864884372
12.221650789605278
12.221650714342532
12.221650639096115
12.221650563866037
12.221650488652287
12.221650413454862
12.22165033827376
12.221650263108973
12.221650187960499
12.221650112828337
12.22165003771248
12.221649962612936
12.221649887529678
12.221649812462733
12.221649737412065
12.221649662377695
12.221649587359611
12.221649512357802
12.221649437372282
12.221649362403031
12.221649287450058
12.221649212513352
12.221649137592905
12.221649062688721
12.221648987800794
12.221648912929133
12.221648838073714
12.221648763234544
12.221648688411612
12.221648613604927
12.221648538814469
12.221648464040255
12.221648389282265
12.221648314540511
12.22164823981497
12.221648165105647
12.221648090412549
12.221648015735648
12.221647941074963
12.221647866430489
12.2216477918022
12.221647717190129
12.221647642594247
12.221647568014554
12.221647493451043
12.221647418903713
12.221647344372574
12.221647269857602
12.221647195358816
12.221647120876186
12.221647046409736
12.221646971959434
12.221646897525304
12.221646823107319
12.221646748705496
12.221646674319826
12.22164659995029
12.221646525596894
12.22164645125964
12.221646376938521
12.221646302633534
12.221646228344675
12.221646154071939
12.221646079815327
12.221646005574835
12.221645931350448
12.221645857142176
12.221645782950004
12.221645708773947
12.221645634613985
12.221645560470115
12.22164548634234
12.221645412230659
12.221645338135064
12.221645264055539
12.221645189992103
12.221645115944742
12.221645041913447
12.22164496789824
12.221644893899068
12.221644819915978
12.221644745948932
12.221644671997959
12.221644598063019
12.221644524144136
12.22164445024129
12.22164437635449
12.221644302483725
12.221644228628996
12.221644154790306
12.221644080967629
12.221644007160972
12.221643933370341
12.221643859595728
12.221643785837127
12.221643712094536
12.22164363836794
12.22164356465736
12.221643490962776
12.22164341728418
12.221643343621576
12.221643269974969
12.221643196344345
12.221643122729699
12.221643049131035
12.221642975548336
12.221642901981623
12.22164282843086
12.221642754896077
12.221642681377242
12.221642607874372
12.221642534387454
12.22164246091648
12.221642387461458
12.221642314022388
12.221642240599234
12.221642167192046
12.221642093800773
12.221642020425428
12.22164194706602
12.221641873722527
12.221641800394956
12.221641727083295
12.221641653787547
12.221641580507713
12.221641507243787
12.221641433995755
12.221641360763634
12.221641287547394
12.221641214347043
12.22164114116259
12.22164106799402
12.221640994841325
12.221640921704514
12.221640848583576
12.221640775478503
12.221640702389301
12.221640629315965
12.22164055625849
12.221640483216863
12.221640410191112
12.22164033718119
12.221640264187117
12.221640191208893
12.221640118246507
12.22164004529996
12.221639972369243
12.22163989945435
12.221639826555293
12.221639753672054
12.221639680804634
12.22163960795303
12.22163953511724
12.22163946229725
12.221639389493074
12.221639316704701
12.221639243932126
12.221639171175337
12.221639098434341
12.221639025709154
12.221638952999731
12.221638880306097
12.22163880762824
12.221638734966161
12.221638662319847
12.221638589689302
12.22163851707452
12.2216384444755
12.221638371892244
12.221638299324733
12.221638226772972
12.221638154236969
12.221638081716705
12.221638009212173
12.221637936723392
12.22163786425034
12.221637791793015
12.221637719351415
12.221637646925538
12.221637574515382
12.221637502120945
12.221637429742223
12.22163735737921
12.221637285031898
12.221637212700289
12.221637140384383
12.221637068084174
12.221636995799654
12.221636923530829
12.221636851277678
12.221636779040216
12.221636706818439
12.221636634612336
12.2216365624219
12.22163649024714
12.221636418088046
12.221636345944596
12.221636273816816
12.221636201704696
12.22163612960822
12.221636057527395
12.22163598546222
12.22163591341268
12.221635841378788
12.221635769360523
12.221635697357886
12.22163562537088
12.2216355533995
12.221635481443743
12.2216354095036
12.221635337579071
12.221635265670159
12.221635193776855
12.221635121899142
12.221635050037055
12.221634978190549
12.22163490635963
12.221634834544314
12.22163476274458
12.22163469096043
12.221634619191859
12.221634547438875
12.221634475701451
12.221634403979607
12.221634332273322
12.221634260582613
12.221634188907457
12.221634117247858
12.221634045603817
12.221633973975319
12.22163390236237
12.22163383076497
12.221633759183106
12.221633687616773
12.221633616065983
12.221633544530718
12.221633473010973
12.221633401506761
12.221633330018072
12.221633258544896
12.221633187087233
12.22163311564507
12.221633044218422
12.22163297280728
12.221632901411635
12.221632830031483
12.221632758666821
12.221632687317658
12.221632615983976
12.221632544665773
12.221632473363055
12.221632402075809
12.221632330804042
12.221632259547752
12.221632188306911
12.221632117081539
12.221632045871623
12.22163197467717
12.221631903498158
12.221631832334607
12.221631761186499
12.221631690053833
12.221631618936605
12.221631547834814
12.22163147674845
12.22163140567752
12.221631334622021
12.221631263581946
12.221631192557277
12.221631121548032
12.221631050554208
12.221630979575773
12.221630908612754
12.221630837665137
12.221630766732916
12.221630695816094
12.221630624914667
12.221630554028627
12.221630483157972
12.2216304123027
12.221630341462808
12.221630270638283
12.22163019982914
12.221630129035365
12.221630058256947
12.221629987493912
12.22162991674622
12.221629846013883
12.221629775296895
12.221629704595268
12.221629633908979
12.221629563238041
12.221629492582421
12.221629421942158
12.221629351317215

12.221629280707608
12.221629210113331
12.221629139534365
12.221629068970719
12.221628998422402
12.221628927889379
12.221628857371673
12.221628786869278
12.221628716382186
12.221628645910386
12.221628575453883
12.221628505012673
12.221628434586753
12.22162836417612
12.221628293780766
12.221628223400694
12.221628153035898
12.221628082686378
12.221628012352122
12.221627942033129
12.221627871729408
12.221627801440935
12.221627731167723
12.22162766090977
12.221627590667058
12.221627520439597
12.22162745022737
12.221627380030396
12.221627309848644
12.22162723968214
12.221627169530853
12.221627099394802
12.221627029273968
12.221626959168358
12.221626889077953
12.221626819002765
12.221626748942793
12.221626678898028
12.221626608868462
12.221626538854089
12.221626468854925
12.221626398870946
12.22162632890216
12.221626258948564
12.221626189010138
12.221626119086904
12.22162604917885
12.22162597928596
12.22162590940825
12.221625839545695
12.221625769698308
12.221625699866086
12.221625630049017
12.221625560247102
12.221625490460344
12.221625420688728
12.221625350932245
12.22162528119092
12.221625211464717
12.221625141753655
12.221625072057721
12.221625002376916
12.221624932711235
12.221624863060676
12.221624793425239
12.221624723804913
12.221624654199701
12.221624584609582
12.22162451503458
12.22162444547469
12.221624375929874
12.221624306400164
12.221624236885544
12.221624167386013
12.221624097901564
12.221624028432206
12.221623958977919
12.221623889538703
12.221623820114557
12.22162375070549
12.221623681311478
12.22162361193253
12.221623542568654
12.221623473219822
12.221623403886039
12.221623334567312
12.221623265263624
12.221623195974985
12.221623126701372
12.221623057442805
12.22162298819928
12.22162291897077
12.22162284975729
12.22162278055883
12.22162271137539
12.221622642206963
12.221622573053555
12.221622503915155
12.221622434791762
12.22162236568337
12.221622296589986
12.221622227511586
12.221622158448186
12.221622089399773
12.221622020366352
12.221621951347913
12.221621882344454
12.221621813355968
12.221621744382457
12.221621675423924
12.221621606480351
12.221621537551737
12.221621468638098
12.221621399739405
12.221621330855664
12.22162126198689
12.221621193133052
12.221621124294154
12.221621055470216
12.221620986661206
12.221620917867119
12.221620849087989
12.221620780323766
12.221620711574472
12.221620642840099
12.22162057412065
12.22162050541612
12.221620436726488
12.221620368051786
12.221620299391969
12.221620230747064
12.221620162117063
12.22162009350195
12.221620024901727
12.221619956316399
12.221619887745954
12.2216198191904
12.221619750649728
12.221619682123917
12.221619613612985
12.221619545116926
12.221619476635732
12.221619408169413
12.221619339717938
12.221619271281323
12.22161920285957
12.221619134452668
12.221619066060615
12.221618997683379
12.221618929321023
12.221618860973487
12.221618792640786
12.221618724322918
12.221618656019881
12.221618587731669
12.221618519458259
12.221618451199689
12.221618382955938
12.221618314726989
12.221618246512842
12.22161817831351
12.221618110128986
12.221618041959251
12.221617973804316
12.221617905664173
12.22161783753883
12.221617769428258
12.221617701332471
12.221617633251476
12.221617565185246
12.221617497133794
12.221617429097112
12.221617361075202
12.221617293068048
12.221617225075656
12.221617157098034
12.22161708913515
12.221617021187022
12.221616953253644
12.221616885335006
12.221616817431123
12.22161674954196
12.221616681667546
12.221616613807871
12.221616545962904
12.221616478132677
12.221616410317164
12.221616342516375
12.2216162747303
12.221616206958938
12.221616139202288
12.221616071460343
12.221616003733102
12.221615936020564
12.22161586832271
12.221615800639563
12.221615732971106
12.221615665317332
12.221615597678229
12.221615530053827
12.221615462444108
12.221615394849048
12.221615327268655
12.221615259702943
12.221615192151887
12.2216151246155
12.221615057093775
12.221614989586696
12.22161492209427
12.2216148546165
12.221614787153369
12.221614719704892
12.221614652271038
12.221614584851825
12.221614517447252
12.221614450057304
12.22161438268199
12.221614315321288
12.221614247975223
12.221614180643757
12.221614113326916
12.22161404602468
12.221613978737054
12.221613911464031
12.221613844205617
12.2216137769618
12.221613709732571
12.221613642517937
12.221613575317892
12.221613508132432
12.221613440961551
12.221613373805264
12.221613306663537
12.221613239536385
12.22161317242381
12.221613105325797
12.221613038242355
12.221612971173462
12.22161290411914
12.221612837079363
12.221612770054127
12.221612703043453
12.22161263604732
12.221612569065723
12.221612502098678
12.221612435146154
12.22161236820817
12.22161230128471
12.221612234375778
12.221612167481364
12.221612100601481
12.221612033736108
12.22161196688524
12.22161190004889
12.221611833227042
12.221611766419702
12.221611699626855
12.221611632848514
12.221611566084658
12.221611499335305
12.221611432600435
12.221611365880054
12.221611299174146
12.221611232482717
12.221611165805763
12.221611099143287
12.221611032495277
12.221610965861732
12.221610899242652
12.221610832638031
12.221610766047862
12.22161069947215
12.221610632910888
12.22161056636407
12.2216104998317
12.22161043331377
12.221610366810278
12.221610300321222
12.221610233846596
12.221610167386391
12.221610100940623
12.221610034509265
12.221609968092327
12.221609901689815
12.22160983530172
12.221609768928015
12.221609702568726
12.221609636223834
12.221609569893353
12.22160950357726
12.22160943727557
12.221609370988263
12.22160930471535
12.221609238456816
12.221609172212657
12.221609105982886
12.22160903976749
12.221608973566463
12.221608907379808
12.22160884120751
12.221608775049589
12.221608708906007
12.221608642776795
12.221608576661936
12.221608510561426
12.221608444475262
12.221608378403445
12.221608312345964
12.22160824630283
12.221608180274025
12.221608114259539
12.221608048259398
12.221607982273575
12.22160791630208
12.221607850344894
12.221607784402037
12.221607718473482
12.221607652559237
12.221607586659301
12.221607520773665
12.221607454902333
12.221607389045296
12.221607323202562
12.221607257374114
12.221607191559945
12.221607125760066
12.221607059974474
12.221606994203162
12.221606928446109
12.221606862703345
12.221606796974859
12.221606731260618
12.22160666556065
12.22160659987494
12.221606534203483
12.221606468546286
12.221606402903332
12.221606337274642
12.221606271660185
12.221606206059969
12.221606140473993
12.22160607490225
12.221606009344747
12.221605943801466
12.22160587827241
12.221605812757574
12.221605747256977
12.221605681770578
12.221605616298396
12.221605550840433
12.221605485396672
12.221605419967105
12.221605354551754
12.221605289150597
12.221605223763634
12.22160515839086
12.221605093032277
12.221605027687886
12.221604962357665
12.221604897041637
12.221604831739782
12.221604766452103
12.22160470117859
12.221604635919244
12.221604570674069
12.221604505443041
12.221604440226189
12.221604375023489
12.221604309834925
12.22160424466052
12.221604179500265
12.221604114354156
12.22160404922217
12.221603984104338
12.22160391900064
12.22160385391106
12.221603788835612
12.22160372377429
12.221603658727089
12.221603593694
12.22160352867504
12.221603463670183
12.22160339867944
12.221603333702797
12.221603268740262
12.221603203791817
12.221603138857484
12.221603073937231
12.221603009031094
12.221602944139015
12.22160287926104
12.22160281439714
12.221602749547314
12.221602684711568
12.221602619889888
12.221602555082287
12.221602490288747
12.221602425509273
12.221602360743864
12.221602295992499
12.2216022312552
12.221602166531948
12.221602101822738
12.221602037127584
12.221601972446468
12.221601907779394
12.221601843126344
12.22160177848734
12.221601713862352
12.221601649251403
12.221601584654472
12.221601520071559
12.221601455502677
12.221601390947804
12.221601326406928
12.221601261880073
12.221601197367225
12.221601132868372
12.22160106838353
12.221601003912673
12.221600939455806
12.221600875012939
12.221600810584052
12.22160074616916
12.221600681768239
12.221600617381304
12.221600553008342
12.221600488649353
12.22160042430432
12.221600359973277
12.221600295656172
12.221600231353044
12.221600167063864
12.221600102788644
12.221600038527365
12.221599974280041
12.221599910046656
12.221599845827221
12.22159978162172
12.22159971743016
12.221599653252527
12.22159958908882
12.221599524939053
12.221599460803194
12.221599396681267
12.22159933257325
12.221599268479151
12.221599204398967
12.221599140332685
12.221599076280311
12.22159901224184
12.22159894821727
12.221598884206589
12.22159882020981
12.221598756226916
12.221598692257917
12.221598628302798
12.22159856436156
12.22159850043419
12.221598436520711
12.221598372621097
12.221598308735354
12.221598244863477
12.221598181005469
12.221598117161307
12.221598053331014
12.22159798951458
12.221597925711986
12.221597861923236
12.221597798148343
12.22159773438729
12.221597670640074
12.221597606906695
12.22159754318714
12.221597479481431
12.22159741578954
12.22159735211148
12.221597288447233
12.221597224796811
12.2215971611602
12.221597097537401
12.221597033928415
12.221596970333227
12.221596906751847
12.221596843184269
12.221596779630481
12.2215967160905
12.221596652564298
12.221596589051895
12.221596525553274
12.221596462068428
12.221596398597374
12.221596335140072
12.221596271696571
12.221596208266826
12.221596144850857
12.221596081448643
12.221596018060195
12.221595954685508
12.221595891324572
12.221595827977389
12.221595764643954
12.221595701324269
12.221595638018325
12.221595574726122
12.221595511447653
12.22159544818293
12.221595384931929
12.22159532169465
12.221595258471112
12.22159519526128
12.221595132065179
12.221595068882795
12.221595005714113
12.221594942559152
12.221594879417903
12.221594816290347
12.221594753176499
12.221594690076355
12.221594626989896
12.22159456391714
12.221594500858064
12.22159443781268
12.221594374780977
12.221594311762962
12.221594248758613
12.221594185767954
12.221594122790956
12.221594059827632
12.221593996877974
12.221593933941977
12.221593871019644
12.221593808110955
12.221593745215928
12.221593682334555
12.221593619466839
12.22159355661276
12.221593493772314
12.221593430945514
12.221593368132359
12.221593305332826
12.221593242546934
12.221593179774654
12.221593117016011
12.221593054270981
12.221592991539584
12.221592928821792
12.221592866117609
12.22159280342704
12.22159274075008
12.221592678086727
12.22159261543697
12.221592552800816
12.221592490178251
12.22159242756928
12.221592364973896
12.221592302392102
12.221592239823899
12.221592177269267
12.221592114728216
12.221592052200732
12.22159198968682

12.221591927186475
12.22159186469971
12.221591802226492
12.221591739766843
12.221591677320745
12.22159161488821
12.221591552469215
12.221591490063764
12.22159142767187
12.221591365293518
12.2215913029287
12.221591240577427
12.221591178239674
12.221591115915452
12.221591053604762
12.221590991307599
12.221590929023966
12.221590866753832
12.221590804497222
12.221590742254124
12.221590680024537
12.221590617808461
12.22159055560589
12.221590493416807
12.221590431241228
12.221590369079143
12.221590306930556
12.221590244795456
12.221590182673843
12.221590120565716
12.221590058471053
12.221589996389888
12.221589934322184
12.22158987226796
12.221589810227202
12.221589748199909
12.221589686186075
12.221589624185711
12.221589562198801
12.221589500225338
12.221589438265333
12.221589376318775
12.221589314385664
12.221589252465993
12.22158919055976
12.221589128666965
12.221589066787608
12.22158900492167
12.221588943069174
12.221588881230085
12.221588819404433
12.221588757592198
12.22158869579338
12.221588634007974
12.221588572235975
12.22158851047739
12.221588448732199
12.22158838700042
12.221588325282033
12.22158826357705
12.221588201885455
12.221588140207249
12.221588078542437
12.221588016890996
12.221587955252943
12.221587893628275
12.221587832016978
12.221587770419045
12.221587708834493
12.221587647263302
12.22158758570548
12.221587524161015
12.221587462629907
12.221587401112158
12.221587339607757
12.221587278116711
12.221587216639005
12.221587155174646
12.221587093723631
12.22158703228594
12.221586970861603
12.221586909450586
12.221586848052903
12.22158678666855
12.221586725297511
12.2215866639398
12.221586602595405
12.221586541264319
12.221586479946538
12.221586418642083
12.221586357350928
12.221586296073083
12.221586234808525
12.221586173557268
12.221586112319315
12.221586051094647
12.221585989883259
12.221585928685167
12.22158586750036
12.22158580632882
12.221585745170572
12.221585684025593
12.221585622893883
12.22158556177544
12.221585500670265
12.221585439578359
12.221585378499705
12.221585317434311
12.221585256382168
12.22158519534328
12.221585134317634
12.221585073305246
12.221585012306083
12.22158495132018
12.221584890347494
12.221584829388057
12.221584768441847
12.221584707508871
12.221584646589108
12.221584585682571
12.221584524789257
12.221584463909162
12.221584403042275
12.22158434218861
12.221584281348141
12.221584220520878
12.221584159706826
12.221584098905963
12.221584038118298
12.221583977343828
12.221583916582562
12.221583855834467
12.22158379509957
12.221583734377843
12.221583673669302
12.221583612973937
12.221583552291744
12.221583491622724
12.22158343096687
12.221583370324185
12.221583309694672
12.221583249078307
12.221583188475094
12.221583127885042
12.221583067308126
12.221583006744385
12.221582946193774
12.221582885656304
12.221582825131978
12.221582764620784
12.221582704122724
12.221582643637799
12.221582583166006
12.22158252270733
12.221582462261786
12.22158240182935
12.221582341410034
12.221582281003837
12.221582220610754
12.221582160230763
12.22158209986389
12.221582039510121
12.221581979169445
12.221581918841869
12.22158185852738
12.221581798225987
12.221581737937692
12.221581677662476
12.22158161740033
12.22158155715128
12.221581496915304
12.221581436692396
12.221581376482563
12.2215813162858
12.221581256102102
12.221581195931469
12.221581135773883
12.221581075629368
12.221581015497915
12.221580955379489
12.221580895274123
12.221580835181808
12.221580775102533
12.221580715036291
12.221580654983098
12.22158059494293
12.221580534915796
12.221580474901694
12.221580414900616
12.221580354912561
12.221580294937525
12.221580234975503
12.221580175026508
12.221580115090509
12.22158005516753
12.221579995257565
12.221579935360591
12.221579875476616
12.22157981560564
12.221579755747658
12.221579695902669
12.221579636070672
12.221579576251669
12.22157951644564
12.22157945665259
12.221579396872517
12.221579337105428
12.221579277351298
12.221579217610149
12.221579157881967
12.221579098166737
12.221579038464478
12.221578978775186
12.221578919098834
12.22157885943544
12.221578799784993
12.221578740147502
12.22157868052294
12.221578620911327
12.221578561312658
12.221578501726926
12.221578442154115
12.221578382594245
12.221578323047297
12.221578263513274
12.22157820399217
12.221578144483992
12.22157808498872
12.221578025506368
12.221577966036929
12.221577906580391
12.221577847136766
12.221577787706046
12.221577728288215
12.221577668883281
12.221577609491243
12.221577550112102
12.221577490745842
12.221577431392467
12.221577372051978
12.221577312724362
12.221577253409636
12.221577194107773
12.221577134818776
12.22157707554266
12.221577016279408
12.221576957029024
12.221576897791492
12.221576838566815
12.221576779354997
12.221576720156024
12.221576660969916
12.221576601796638
12.221576542636209
12.22157648348862
12.221576424353866
12.22157636523195
12.221576306122877
12.221576247026624
12.221576187943192
12.221576128872595
12.221576069814809
12.221576010769848
12.221575951737707
12.221575892718368
12.221575833711848
12.221575774718131
12.221575715737218
12.221575656769112
12.221575597813793
12.221575538871278
12.221575479941558
12.221575421024617
12.221575362120484
12.221575303229113
12.221575244350548
12.22157518548475
12.221575126631723
12.22157506779148
12.221575008964003
12.22157495014929
12.221574891347352
12.221574832558177
12.221574773781755
12.2215747150181
12.22157465626719
12.22157459752904
12.221574538803624
12.221574480090961
12.22157442139105
12.22157436270388
12.221574304029435
12.221574245367734
12.221574186718756
12.221574128082525
12.221574069459015
12.221574010848224
12.221573952250154
12.221573893664804
12.221573835092174
12.221573776532246
12.221573717985038
12.221573659450542
12.22157360092874
12.221573542419643
12.221573483923247
12.221573425439548
12.221573366968538
12.221573308510223
12.221573250064605
12.221573191631656
12.221573133211402
12.22157307480382
12.221573016408918
12.221572958026693
12.221572899657144
12.221572841300253
12.221572782956029
12.221572724624473
12.221572666305576
12.221572607999333
12.221572549705751
12.221572491424839
12.221572433156545
12.221572374900912
12.221572316657925
12.221572258427587
12.221572200209863
12.221572142004796
12.221572083812358
12.22157202563255
12.221571967465373
12.221571909310814
12.221571851168882
12.221571793039573
12.221571734922865
12.221571676818781
12.22157161872732
12.221571560648457
12.2215715025822
12.221571444528543
12.221571386487488
12.221571328459035
12.221571270443174
12.221571212439898
12.221571154449231
12.221571096471138
12.221571038505628
12.221570980552698
12.221570922612353
12.221570864684574
12.221570806769378
12.221570748866744
12.221570690976682
12.221570633099192
12.221570575234255
12.221570517381883
12.221570459542063
12.221570401714796
12.221570343900094
12.22157028609792
12.221570228308297
12.221570170531226
12.22157011276669
12.221570055014697
12.221569997275234
12.221569939548305
12.221569881833911
12.221569824132029
12.22156976644269
12.221569708765859
12.221569651101543
12.221569593449749
12.221569535810476
12.22156947818369
12.221569420569434
12.221569362967687
12.221569305378429
12.221569247801671
12.22156919023742
12.221569132685653
12.221569075146382
12.221569017619597
12.221568960105296
12.221568902603483
12.221568845114142
12.221568787637294
12.221568730172914
12.22156867272101
12.221568615281571
12.221568557854598
12.221568500440089
12.221568443038048
12.221568385648458
12.221568328271333
12.22156827090665
12.221568213554423
12.221568156214655
12.221568098887326
12.221568041572434
12.221567984269985
12.221567926979974
12.221567869702401
12.221567812437252
12.221567755184546
12.221567697944247
12.221567640716389
12.22156758350094
12.221567526297914
12.221567469107306
12.221567411929112
12.221567354763327
12.221567297609948
12.221567240468975
12.221567183340401
12.221567126224228
12.221567069120454
12.221567012029078
12.221566954950097
12.221566897883497
12.221566840829281
12.221566783787457
12.221566726757997
12.221566669740934
12.221566612736234
12.22156655574391
12.221566498763963
12.22156644179638
12.221566384841157
12.221566327898305
12.221566270967806
12.221566214049657
12.221566157143869
12.221566100250444
12.221566043369346
12.221565986500599
12.221565929644203
12.221565872800147
12.221565815968424
12.221565759149042
12.22156570234199
12.221565645547265
12.22156558876487
12.221565531994791
12.221565475237048
12.221565418491613
12.221565361758506
12.221565305037702
12.221565248329224
12.221565191633035
12.221565134949156
12.22156507827759
12.221565021618312
12.221564964971343
12.221564908336664
12.221564851714282
12.221564795104182
12.221564738506379
12.22156468192085
12.22156462534761
12.221564568786645
12.221564512237967
12.221564455701543
12.221564399177407
12.221564342665534
12.221564286165917
12.221564229678576
12.221564173203493
12.221564116740666
12.221564060290092
12.221564003851777
12.221563947425713
12.221563891011884
12.221563834610306
12.221563778220968
12.221563721843866
12.22156366547902
12.221563609126397
12.221563552785998
12.221563496457831
12.221563440141894
12.221563383838172
12.221563327546676
12.221563271267396
12.221563215000334
12.221563158745482
12.221563102502842
12.221563046272415
12.22156299005419
12.221562933848162
12.221562877654328
12.221562821472697
12.221562765303265
12.22156270914602
12.221562653000959
12.221562596868097
12.221562540747406
12.221562484638909
12.221562428542574
12.221562372458427
12.221562316386448
12.221562260326639
12.221562204278998
12.221562148243526
12.221562092220214
12.221562036209061
12.221561980210064
12.221561924223222
12.221561868248532
12.221561812285998
12.221561756335591
12.221561700397352
12.221561644471233
12.221561588557265
12.221561532655434
12.221561476765732
12.221561420888166
12.221561365022723
12.22156130916941
12.221561253328211
12.22156119749914
12.221561141682182
12.221561085877342
12.22156103008461
12.221560974303994

12.221560918535484
12.22156086277908
12.221560807034775
12.221560751302563
12.221560695582456
12.221560639874443
12.221560584178517
12.221560528494683
12.221560472822928
12.221560417163268
12.22156036151568
12.221560305880168
12.221560250256744
12.221560194645381
12.221560139046092
12.221560083458874
12.221560027883712
12.221559972320627
12.221559916769595
12.221559861230615
12.22155980570369
12.221559750188826
12.22155969468601
12.22155963919523
12.221559583716505
12.221559528249816
12.221559472795168
12.221559417352557
12.221559361921981
12.221559306503428
12.221559251096913
12.221559195702413
12.221559140319954
12.221559084949499
12.221559029591067
12.221558974244653
12.221558918910254
12.221558863587859
12.221558808277473
12.221558752979098
12.221558697692716
12.22155864241834
12.221558587155956
12.221558531905572
12.221558476667182
12.221558421440772
12.221558366226363
12.221558311023921
12.221558255833468
12.221558200655
12.221558145488505
12.221558090333984
12.221558035191425
12.221557980060851
12.221557924942228
12.221557869835577
12.221557814740889
12.221557759658154
12.221557704587372
12.221557649528542
12.221557594481666
12.221557539446739
12.221557484423762
12.221557429412716
12.22155737441362
12.221557319426465
12.221557264451228
12.221557209487933
12.221557154536569
12.22155709959713
12.221557044669611
12.221556989754022
12.221556934850351
12.221556879958591
12.221556825078755
12.221556770210826
12.221556715354804
12.221556660510686
12.221556605678478
12.221556550858159
12.221556496049747
12.221556441253238
12.22155638646862
12.221556331695885
12.221556276935043
12.221556222186084
12.221556167449013
12.221556112723814
12.221556058010506
12.221556003309063
12.2215559486195
12.221555893941803
12.221555839275977
12.221555784622014
12.221555729979906
12.221555675349668
12.221555620731285
12.221555566124758
12.221555511530083
12.221555456947248
12.221555402376268
12.221555347817139
12.221555293269839
12.221555238734386
12.22155518421076
12.221555129698993
12.221555075199035
12.221555020710907
12.221554966234615
12.221554911770147
12.221554857317495
12.221554802876666
12.221554748447648
12.221554694030447
12.22155463962506
12.221554585231473
12.221554530849701
12.221554476479717
12.221554422121555
12.221554367775179
12.2215543134406
12.221554259117818
12.221554204806823
12.221554150507622
12.22155409622019
12.221554041944565
12.221553987680712
12.22155393342863
12.221553879188322
12.221553824959795
12.221553770743036
12.221553716538041
12.221553662344817
12.221553608163347
12.221553553993648
12.221553499835698
12.221553445689501
12.221553391555064
12.221553337432374
12.221553283321425
12.22155322922223
12.221553175134773
12.221553121059051
12.221553066995073
12.221553012942827
12.221552958902317
12.221552904873525
12.221552850856483
12.221552796851146
12.22155274285753
12.221552688875633
12.22155263490547
12.221552580947
12.221552527000249
12.221552473065204
12.22155241914187
12.221552365230242
12.221552311330319
12.221552257442092
12.221552203565556
12.221552149700718
12.221552095847565
12.221552042006103
12.221551988176332
12.22155193435824
12.221551880551834
12.221551826757098
12.221551772974045
12.22155171920267
12.221551665442961
12.22155161169492
12.221551557958536
12.22155150423383
12.221551450520776
12.221551396819379
12.221551343129649
12.221551289451567
12.221551235785133
12.221551182130339
12.221551128487206
12.221551074855709
12.221551021235845
12.221550967627634
12.221550914031058
12.221550860446108
12.22155080687278
12.22155075331109
12.22155069976103
12.221550646222589
12.221550592695765
12.221550539180559
12.221550485676968
12.221550432184994
12.22155037870463
12.221550325235874
12.22155027177873
12.221550218333173
12.22155016489922
12.221550111476873
12.221550058066118
12.221550004666948
12.221549951279377
12.22154989790339
12.221549844539002
12.221549791186177
12.221549737844944
12.221549684515276
12.22154963119719
12.221549577890684
12.221549524595737
12.22154947131236
12.221549418040562
12.221549364780307
12.221549311531618
12.22154925829449
12.221549205068918
12.22154915185489
12.221549098652421
12.221549045461494
12.22154899228211
12.221548939114285
12.22154888595798
12.221548832813223
12.22154877968
12.221548726558305
12.221548673448138
12.221548620349509
12.2215485672624
12.221548514186807
12.221548461122747
12.221548408070195
12.221548355029157
12.221548301999642
12.221548248981627
12.221548195975119
12.22154814298012
12.221548089996624
12.221548037024624
12.221547984064125
12.221547931115119
12.221547878177601
12.221547825251578
12.221547772337043
12.221547719433987
12.221547666542431
12.221547613662343
12.221547560793733
12.221547507936595
12.22154745509093
12.221547402256736
12.221547349434015
12.22154729662275
12.221547243822958
12.221547191034624
12.221547138257739
12.221547085492316
12.221547032738341
12.221546979995825
12.221546927264741
12.221546874545117
12.221546821836933
12.221546769140184
12.22154671645488
12.221546663781004
12.221546611118562
12.221546558467548
12.221546505827973
12.221546453199815
12.221546400583074
12.221546347977764
12.221546295383868
12.221546242801393
12.221546190230315
12.221546137670657
12.22154608512241
12.22154603258557
12.221545980060132
12.22154592754609
12.221545875043452
12.2215458225522
12.221545770072344
12.22154571760389
12.22154566514681
12.221545612701116
12.221545560266815
12.221545507843885
12.221545455432347
12.22154540303217
12.22154535064338
12.221545298265951
12.221545245899891
12.221545193545202
12.221545141201865
12.221545088869902
12.221545036549292
12.221544984240042
12.221544931942137
12.221544879655589
12.221544827380393
12.22154477511654
12.221544722864028
12.221544670622858
12.22154461839303
12.221544566174538
12.221544513967377
12.221544461771554
12.221544409587052
12.221544357413885
12.221544305252028
12.221544253101507
12.221544200962303
12.221544148834408
12.221544096717839
12.22154404461257
12.221543992518612
12.22154394043597
12.221543888364629
12.221543836304578
12.221543784255836
12.221543732218395
12.221543680192239
12.221543628177391
12.221543576173818
12.221543524181532
12.221543472200539
12.221543420230823
12.221543368272386
12.221543316325231
12.22154326438935
12.221543212464743
12.221543160551402
12.221543108649326
12.221543056758522
12.22154300487898
12.221542953010697
12.221542901153674
12.221542849307902
12.22154279747339
12.221542745650115
12.221542693838105
12.22154264203733
12.2215425902478
12.221542538469512
12.221542486702464
12.221542434946654
12.221542383202065
12.22154233146872
12.221542279746604
12.221542228035702
12.22154217633603
12.22154212464758
12.221542072970353
12.221542021304339
12.22154196964954
12.221541918005949
12.22154186637357
12.2215418147524
12.221541763142437
12.221541711543665
12.221541659956102
12.221541608379733
12.221541556814547
12.221541505260575
12.221541453717773
12.221541402186167
12.221541350665753
12.221541299156508
12.221541247658454
12.221541196171563
12.221541144695864
12.221541093231325
12.221541041777957
12.221540990335768
12.221540938904738
12.221540887484867
12.221540836076171
12.221540784678616
12.221540733292214
12.221540681916986
12.221540630552893
12.221540579199951
12.221540527858156
12.221540476527505
12.221540425208003
12.221540373899632
12.221540322602396
12.221540271316295
12.221540220041325
12.221540168777492
12.221540117524773
12.221540066283186
12.221540015052726
12.221539963833377
12.221539912625149
12.221539861428026
12.221539810242026
12.221539759067126
12.221539707903341
12.221539656750672
12.221539605609085
12.221539554478612
12.221539503359224
12.221539452250946
12.22153940115375
12.221539350067642
12.221539298992637
12.221539247928701
12.221539196875865
12.221539145834102
12.221539094803424
12.221539043783809
12.221538992775265
12.221538941777805
12.221538890791415
12.221538839816091
12.22153878885182
12.221538737898614
12.221538686956487
12.221538636025386
12.221538585105355
12.221538534196375
12.221538483298444
12.221538432411565
12.221538381535728
12.221538330670935
12.221538279817178
12.221538228974454
12.22153817814278
12.221538127322129
12.221538076512504
12.221538025713917
12.221537974926353
12.22153792414981
12.221537873384289
12.221537822629799
12.221537771886304
12.221537721153833
12.221537670432365
12.221537619721925
12.221537569022475
12.221537518334033
12.221537467656594
12.221537416990154
12.221537366334708
12.221537315690263
12.221537265056801
12.221537214434338
12.221537163822864
12.221537113222373
12.221537062632857
12.22153701205433
12.22153696148678
12.221536910930201
12.221536860384596
12.221536809849963
12.221536759326305
12.221536708813604
12.22153665831188
12.221536607821093
12.221536557341283
12.221536506872432
12.22153645641452
12.22153640596757
12.22153635553157
12.22153630510651
12.221536254692406
12.221536204289244
12.221536153897002
12.221536103515712
12.221536053145357
12.221536002785934
12.221535952437446
12.22153590209988
12.221535851773245
12.221535801457527
12.221535751152732
12.221535700858853
12.221535650575898
12.221535600303858
12.221535550042715
12.221535499792482
12.221535449553166
12.221535399324754
12.221535349107247
12.22153529890063
12.221535248704924
12.221535198520103
12.221535148346172
12.221535098183136
12.221535048030983
12.22153499788972
12.221534947759334
12.221534897639836
12.221534847531212
12.221534797433463
12.221534747346594
12.221534697270593
12.221534647205463
12.221534597151189
12.22153454710778
12.22153449707525
12.221534447053564
12.221534397042745
12.221534347042779
12.221534297053662
12.22153424707539
12.221534197107976
12.221534147151404
12.221534097205664
12.221534047270783
12.221533997346732
12.221533947433509
12.22153389753113
12.221533847639584
12.22153379775886
12.221533747888964
12.221533698029894
12.22153364818164
12.221533598344214
12.221533548517593
12.2215334987018
12.221533448896816
12.221533399102638
12.221533349319268
12.22153329954671
12.221533249784944
12.221533200033994
12.22153315029383
12.221533100564466
12.22153305084589
12.221533001138104
12.221532951441125
12.22153290175492
12.221532852079497
12.221532802414863
12.221532752761
12.221532703117923
12.221532653485616
12.221532603864086
12.221532554253322
12.22153250465333
12.221532455064096
12.221532405485632
12.221532355917926
12.221532306360976
12.221532256814783
12.22153220727935
12.221532157754668
12.221532108240735
12.221532058737548
12.2215320092451
12.221531959763395
12.221531910292434
12.221531860832206
12.221531811382718
12.221531761943968
12.221531712515944
12.22153166309864
12.22153161369207
12.221531564296217
12.221531514911089
12.22153146553668
12.221531416173
12.221531366820019
12.22153131747775
12.221531268146197
12.221531218825348
12.22153116951521
12.221531120215765
12.221531070927023
12.221531021648984
12.22153097238163
12.221530923124986
12.221530873879017
12.221530824643748
12.221530775419158
12.221530726205257
12.221530677002038
12.221530627809503
12.221530578627627
12.221530529456444
12.221530480295927

12.22153043114607
12.221530382006897
12.221530332878386
12.221530283760533
12.22153023465335
12.22153018555682
12.221530136470948
12.221530087395726
12.221530038331158
12.221529989277242
12.221529940233962
12.221529891201335
12.221529842179354
12.221529793168001
12.2215297441673
12.22152969517723
12.221529646197792
12.221529597228987
12.221529548270802
12.22152949932325
12.221529450386326
12.221529401460012
12.221529352544328
12.22152930363926
12.2215292547448
12.221529205860962
12.221529156987726
12.221529108125106
12.221529059273083
12.22152901043167
12.221528961600852
12.221528912780636
12.22152886397101
12.221528815171995
12.221528766383557
12.221528717605704
12.22152866883845
12.221528620081775
12.221528571335686
12.221528522600174
12.221528473875235
12.22152842516088
12.221528376457101
12.221528327763883
12.221528279081245
12.221528230409163
12.221528181747654
12.221528133096704
12.221528084456311
12.22152803582648
12.2215279872072
12.221527938598468
12.221527890000287
12.221527841412668
12.221527792835586
12.221527744269045
12.22152769571305
12.221527647167589
12.221527598632672
12.221527550108274
12.221527501594426
12.221527453091102
12.221527404598305
12.221527356116026
12.221527307644278
12.221527259183055
12.221527210732338
12.221527162292144
12.221527113862468
12.22152706544329
12.221527017034637
12.221526968636487
12.221526920248841
12.221526871871696
12.221526823505043
12.221526775148904
12.221526726803253
12.221526678468091
12.221526630143421
12.22152658182924
12.221526533525557
12.221526485232346
12.221526436949617
12.221526388677367
12.221526340415595
12.221526292164306
12.221526243923488
12.221526195693137
12.22152614747325
12.22152609926384
12.221526051064886
12.221526002876386
12.221525954698366
12.22152590653079
12.221525858373669
12.221525810227007
12.221525762090785
12.22152571396502
12.221525665849692
12.221525617744808
12.221525569650366
12.221525521566369
12.22152547349281
12.221525425429677
12.221525377376974
12.221525329334712
12.221525281302876
12.221525233281449
12.221525185270462
12.22152513726989
12.22152508927973
12.2215250413
12.221524993330677
12.221524945371767
12.221524897423254
12.221524849485172
12.221524801557477
12.221524753640189
12.221524705733298
12.221524657836815
12.221524609950714
12.22152456207502
12.221524514209714
12.221524466354792
12.221524418510253
12.221524370676116
12.22152432285235
12.221524275038965
12.221524227235957
12.221524179443326
12.221524131661065
12.221524083889175
12.221524036127656
12.221523988376498
12.221523940635711
12.221523892905294
12.221523845185217
12.22152379747552
12.221523749776162
12.221523702087156
12.221523654408507
12.22152360674021
12.221523559082254
12.221523511434649
12.221523463797375
12.221523416170443
12.22152336855385
12.221523320947593
12.221523273351675
12.22152322576607
12.221523178190813
12.221523130625874
12.221523083071263
12.221523035526968
12.22152298799299
12.221522940469335
12.221522892955985
12.221522845452967
12.221522797960237
12.221522750477835
12.221522703005734
12.22152265554392
12.22152260809243
12.221522560651229
12.221522513220323
12.221522465799714
12.221522418389398
12.221522370989376
12.221522323599642
12.221522276220183
12.221522228851011
12.221522181492128
12.221522134143525
12.22152208680519
12.221522039477135
12.221521992159351
12.221521944851844
12.221521897554592
12.22152185026761
12.221521802990898
12.221521755724444
12.221521708468247
12.221521661222308
12.22152161398663
12.221521566761199
12.221521519546014
12.221521472341088
12.221521425146387
12.221521377961952
12.22152133078775
12.221521283623774
12.221521236470062
12.22152118932656
12.221521142193302
12.221521095070273
12.221521047957467
12.221521000854894
12.221520953762546
12.221520906680414
12.221520859608496
12.221520812546805
12.221520765495322
12.221520718454057
12.221520671422992
12.221520624402148
12.2215205773915
12.22152053039106
12.221520483400816
12.221520436420782
12.221520389450939
12.221520342491296
12.221520295541834
12.221520248602566
12.221520201673494
12.221520154754598
12.22152010784589
12.221520060947366
12.221520014059013
12.221519967180846
12.221519920312854
12.22151987345503
12.221519826607373
12.221519779769894
12.221519732942575
12.221519686125419
12.221519639318428
12.221519592521595
12.221519545734916
12.221519498958392
12.221519452192029
12.221519405435803
12.221519358689735
12.221519311953815
12.221519265228034
12.221519218512398
12.221519171806891
12.22151912511153
12.22151907842631
12.221519031751217
12.22151898508625
12.221518938431412
12.221518891786713
12.221518845152126
12.221518798527663
12.221518751913328
12.221518705309105
12.221518658714988
12.221518612130998
12.22151856555711
12.221518518993339
12.221518472439664
12.221518425896102
12.221518379362642
12.221518332839278
12.221518286326011
12.221518239822842
12.221518193329764
12.221518146846776
12.221518100373887
12.221518053911074
12.221518007458352
12.221517961015712
12.22151791458315
12.221517868160662
12.221517821748265
12.221517775345925
12.221517728953668
12.221517682571474
12.221517636199344
12.221517589837285
12.221517543485287
12.221517497143347
12.221517450811469
12.221517404489646
12.221517358177879
12.221517311876168
12.221517265584497
12.221517219302878
12.221517173031298
12.221517126769779
12.221517080518286
12.221517034276829
12.221516988045414
12.221516941824031
12.221516895612686
12.22151684941137
12.221516803220078
12.221516757038813
12.221516710867572
12.22151666470636
12.22151661855516
12.221516572413972
12.221516526282805
12.22151648016165
12.22151643405051
12.221516387949366
12.221516341858239
12.221516295777112
12.22151624970599
12.221516203644859
12.221516157593738
12.221516111552603
12.221516065521461
12.221516019500319
12.221515973489158
12.221515927487987
12.221515881496792
12.221515835515586
12.221515789544373
12.22151574358311
12.221515697631846
12.221515651690543
12.221515605759219
12.221515559837862
12.221515513926466
12.221515468025045
12.221515422133583
12.221515376252077
12.221515330380539
12.221515284518944
12.221515238667319
12.221515192825631
12.221515146993907
12.22151510117212
12.221515055360284
12.221515009558402
12.221514963766436
12.22151491798442
12.221514872212344
12.221514826450198
12.221514780697994
12.221514734955711
12.22151468922336
12.221514643500935
12.221514597788433
12.221514552085855
12.221514506393195
12.221514460710452
12.221514415037634
12.22151436937471
12.22151432372171
12.221514278078617
12.221514232445427
12.221514186822144
12.22151414120877
12.22151409560529
12.221514050011697
12.22151400442802
12.221513958854226
12.221513913290327
12.22151386773632
12.221513822192197
12.221513776657954
12.2215137311336
12.22151368561913
12.221513640114532
12.221513594619813
12.22151354913497
12.221513503660002
12.221513458194893
12.221513412739666
12.221513367294296
12.221513321858795
12.221513276433157
12.221513231017369
12.22151318561145
12.221513140215377
12.221513094829167
12.221513049452797
12.221513004086285
12.22151295872961
12.221512913382785
12.221512868045805
12.221512822718656
12.22151277740136
12.221512732093887
12.221512686796256
12.221512641508445
12.221512596230484
12.221512550962332
12.221512505704025
12.22151246045552
12.22151241521685
12.221512369987991
12.22151232476895
12.221512279559729
12.221512234360306
12.221512189170703
12.221512143990916
12.221512098820927
12.22151205366074
12.221512008510356
12.22151196336978
12.22151191823899
12.221511873118004
12.221511828006813
12.22151178290541
12.221511737813795
12.22151169273197
12.221511647659925
12.221511602597664
12.221511557545188
12.221511512502484
12.221511467469565
12.221511422446415
12.221511377433032
12.221511332429431
12.22151128743559
12.221511242451513
12.221511197477207
12.221511152512653
12.221511107557864
12.22151106261283
12.221511017677559
12.221510972752032
12.22151092783626
12.221510882930245
12.221510838033955
12.221510793147427
12.221510748270637
12.221510703403581
12.221510658546277
12.221510613698705
12.221510568860856
12.221510524032748
12.221510479214373
12.221510434405728
12.221510389606795
12.221510344817595
12.221510300038116
12.221510255268353
12.221510210508319
12.221510165757978
12.221510121017367
12.221510076286458
12.22151003156527
12.221509986853777
12.221509942151984
12.221509897459914
12.22150985277752
12.22150980810484
12.221509763441853
12.22150971878856
12.221509674144949
12.221509629511043
12.22150958488682
12.221509540272278
12.221509495667421
12.221509451072253
12.221509406486762
12.221509361910933
12.221509317344797
12.221509272788328
12.221509228241526
12.221509183704399
12.221509139176934
12.221509094659142
12.221509050151008
12.221509005652523
12.221508961163703
12.22150891668455
12.221508872215042
12.221508827755187
12.221508783304975
12.221508738864419
12.221508694433513
12.22150865001224
12.221508605600622
12.22150856119863
12.221508516806281
12.221508472423563
12.221508428050482
12.221508383687036
12.22150833933322
12.221508294989013
12.221508250654443
12.221508206329512
12.221508162014175
12.221508117708469
12.221508073412373
12.221508029125905

12.221507984849044
12.221507940581793
12.221507896324137
12.221507852076098
12.221507807837671
12.221507763608832
12.221507719389594
12.22150767517996
12.221507630979916
12.221507586789466
12.221507542608611
12.221507498437353
12.221507454275672
12.221507410123575
12.221507365981065
12.221507321848144
12.22150727772479
12.221507233611007
12.221507189506807
12.221507145412184
12.22150710132713
12.221507057251642
12.221507013185727
12.221506969129365
12.221506925082569
12.22150688104534
12.221506837017674
12.221506792999548
12.221506748990981
12.221506704991967
12.221506661002504
12.221506617022584
12.221506573052217
12.22150652909139
12.221506485140107
12.221506441198363
12.221506397266156
12.22150635334349
12.22150630943034
12.221506265526738
12.221506221632666
12.221506177748104
12.221506133873076
12.221506090007574
12.221506046151589
12.22150600230513
12.221505958468184
12.221505914640748
12.221505870822828
12.221505827014425
12.22150578321553
12.22150573942613
12.221505695646245
12.221505651875853
12.221505608114965
12.221505564363577
12.221505520621692
12.221505476889293
12.22150543316638
12.221505389452961
12.221505345749039
12.2215053020546
12.221505258369636
12.221505214694158
12.221505171028161
12.22150512737164
12.221505083724596
12.22150504008703
12.221504996458936
12.221504952840297
12.221504909231138
12.221504865631434
12.221504822041211
12.221504778460439
12.221504734889123
12.221504691327262
12.221504647774866
12.22150460423191
12.221504560698424
12.221504517174365
12.221504473659765
12.221504430154608
12.221504386658891
12.221504343172619
12.22150429969579
12.22150425622839
12.221504212770427
12.22150416932189
12.22150412588279
12.221504082453112
12.221504039032872
12.221503995622054
12.221503952220646
12.221503908828668
12.22150386544611
12.221503822072965
12.221503778709229
12.22150373535491
12.221503692010002
12.221503648674497
12.2215036053484
12.221503562031712
12.221503518724417
12.22150347542654
12.22150343213804
12.221503388858949
12.221503345589237
12.22150330232893
12.22150325907801
12.221503215836467
12.221503172604326
12.221503129381555
12.221503086168175
12.22150304296417
12.22150299976954
12.221502956584294
12.221502913408411
12.2215028702419
12.221502827084766
12.221502783936991
12.221502740798586
12.221502697669543
12.22150265454986
12.221502611439535
12.221502568338568
12.221502525246967
12.221502482164706
12.221502439091793
12.221502396028242
12.221502352974024
12.22150230992916
12.221502266893632
12.221502223867459
12.22150218085061
12.221502137843101
12.221502094844933
12.221502051856092
12.221502008876573
12.221501965906393
12.221501922945544
12.221501879994022
12.221501837051804
12.221501794118922
12.221501751195355
12.221501708281103
12.221501665376167
12.221501622480544
12.221501579594225
12.22150153671722
12.22150149384952
12.22150145099113
12.221501408142027
12.22150136530225
12.221501322471752
12.221501279650543
12.221501236838632
12.221501194036033
12.221501151242718
12.221501108458682
12.221501065683928
12.221501022918469
12.221500980162292
12.22150093741539
12.221500894677764
12.221500851949422
12.221500809230346
12.221500766520542
12.221500723820014
12.221500681128754
12.22150063844676
12.22150059577403
12.22150055311056
12.221500510456353
12.2215004678114
12.221500425175702
12.221500382549268
12.221500339932074
12.22150029732413
12.221500254725433
12.221500212135993
12.2215001695558
12.221500126984832
12.221500084423122
12.221500041870632
12.221499999327387
12.221499956793377
12.221499914268596
12.221499871753046
12.221499829246723
12.221499786749623
12.221499744261754
12.221499701783106
12.221499659313672
12.221499616853466
12.221499574402465
12.221499531960681
12.221499489528115
12.22149944710475
12.221499404690594
12.221499362285645
12.221499319889904
12.221499277503366
12.221499235126016
12.221499192757873
12.221499150398923
12.22149910804918
12.221499065708608
12.221499023377246
12.221498981055062
12.221498938742055
12.221498896438247
12.221498854143611
12.221498811858151
12.221498769581888
12.221498727314788
12.221498685056861
12.221498642808115
12.221498600568529
12.22149855833811
12.221498516116858
12.221498473904779
12.221498431701864
12.221498389508097
12.221498347323497
12.221498305148055
12.221498262981761
12.221498220824612
12.221498178676622
12.221498136537775
12.221498094408084
12.221498052287526
12.221498010176116
12.221497968073844
12.221497925980719
12.221497883896713
12.22149784182185
12.221497799756127
12.221497757699526
12.221497715652054
12.221497673613712
12.22149763158449
12.221497589564395
12.221497547553415
12.221497505551561
12.221497463558809
12.22149742157518
12.221497379600663
12.22149733763526
12.221497295678969
12.221497253731767
12.221497211793693
12.221497169864698
12.221497127944824
12.22149708603404
12.221497044132349
12.221497002239765
12.221496960356252
12.221496918481847
12.221496876616532
12.221496834760302
12.221496792913143
12.22149675107508
12.221496709246093
12.221496667426186
12.221496625615357
12.221496583813607
12.22149654202092
12.221496500237311
12.221496458462777
12.221496416697295
12.221496374940886
12.221496333193544
12.221496291455257
12.221496249726027
12.221496208005862
12.221496166294752
12.221496124592694
12.221496082899684
12.221496041215723
12.221495999540824
12.221495957874945
12.221495916218116
12.22149587457034
12.221495832931602
12.221495791301896
12.221495749681226
12.221495708069591
12.221495666466994
12.221495624873407
12.22149558328887
12.221495541713352
12.221495500146853
12.221495458589375
12.221495417040929
12.221495375501497
12.221495333971074
12.221495292449665
12.221495250937275
12.221495209433897
12.221495167939512
12.221495126454148
12.221495084977779
12.221495043510425
12.221495002052057
12.221494960602694
12.221494919162328
12.221494877730956
12.221494836308572
12.221494794895188
12.221494753490779
12.221494712095373
12.221494670708946
12.221494629331502
12.221494587963035
12.221494546603546
12.221494505253036
12.221494463911505
12.221494422578944
12.221494381255358
12.221494339940739
12.221494298635074
12.221494257338392
12.221494216050663
12.221494174771907
12.221494133502103
12.221494092241262
12.221494050989364
12.221494009746433
12.221493968512446
12.221493927287403
12.22149388607132
12.22149384486418
12.221493803665977
12.221493762476735
12.22149372129641
12.221493680125032
12.221493638962587
12.221493597809081
12.221493556664512
12.221493515528865
12.221493474402141
12.221493433284353
12.221493392175493
12.221493351075544
12.221493309984526
12.221493268902426
12.221493227829232
12.22149318676496
12.221493145709601
12.221493104663159
12.221493063625621
12.221493022596995
12.221492981577256
12.221492940566439
12.22149289956452
12.221492858571494
12.221492817587375
12.22149277661214
12.221492735645805
12.221492694688365
12.2214926537398
12.221492612800144
12.221492571869355
12.221492530947463
12.221492490034453
12.221492449130313
12.22149240823506
12.221492367348677
12.221492326471175
12.221492285602537
12.221492244742773
12.221492203891875
12.221492163049845
12.221492122216688
12.221492081392395
12.22149204057695
12.22149199977037
12.221491958972642
12.22149191818377
12.221491877403762
12.2214918366326
12.221491795870282
12.221491755116812
12.221491714372188
12.221491673636411
12.221491632909471
12.221491592191377
12.221491551482112
12.221491510781693
12.221491470090102
12.221491429407346
12.221491388733421
12.221491348068323
12.221491307412045
12.221491266764597
12.22149122612597
12.221491185496166
12.221491144875174
12.221491104263006
12.221491063659652
12.221491023065113
12.22149098247938
12.22149094190245
12.221490901334334
12.221490860775026
12.221490820224515
12.221490779682824
12.221490739149907
12.221490698625805
12.22149065811049
12.221490617603964
12.221490577106241
12.221490536617305
12.22149049613716
12.22149045566579
12.221490415203206
12.221490374749413
12.221490334304399
12.221490293868172
12.2214902534407
12.22149021302201
12.2214901726121
12.221490132210958
12.221490091818586
12.221490051434976
12.221490011060139
12.221489970694051
12.221489930336741
12.221489889988186
12.221489849648384
12.22148980931733
12.221489768995044
12.221489728681505
12.221489688376717
12.221489648080688
12.221489607793393
12.221489567514837
12.221489527245026
12.22148948698396
12.221489446731637
12.221489406488043
12.221489366253193
12.221489326027056

12.221489285809671
12.221489245601001
12.22148920540107
12.221489165209857
12.221489125027366
12.2214890848536
12.22148904468856
12.221489004532225
12.221488964384612
12.221488924245717
12.221488884115532
12.221488843994049
12.221488803881277
12.221488763777218
12.221488723681858
12.221488683595211
12.22148864351725
12.221488603447998
12.221488563387442
12.221488523335571
12.221488483292395
12.22148844325792
12.221488403232135
12.221488363215034
12.221488323206609
12.22148828320688
12.22148824321583
12.221488203233461
12.221488163259762
12.221488123294744
12.221488083338405
12.221488043390737
12.221488003451741
12.221487963521403
12.22148792359974
12.221487883686745
12.22148784378241
12.221487803886731
12.221487763999718
12.22148772412136
12.221487684251652
12.221487644390603
12.22148760453821
12.221487564694463
12.221487524859361
12.221487485032906
12.2214874452151
12.221487405405933
12.221487365605412
12.221487325813527
12.221487286030275
12.221487246255657
12.221487206489673
12.221487166732313
12.2214871269836
12.22148708724351
12.22148704751203
12.221487007789197
12.221486968074966
12.22148692836936
12.221486888672374
12.221486848984004
12.221486809304254
12.22148676963311
12.221486729970573
12.221486690316645
12.221486650671329
12.221486611034617
12.221486571406514
12.221486531786997
12.22148649217609
12.221486452573782
12.221486412980067
12.221486373394937
12.221486333818408
12.221486294250479
12.221486254691122
12.221486215140356
12.221486175598177
12.221486136064573
12.221486096539564
12.22148605702312
12.221486017515256
12.221485978015972
12.221485938525257
12.22148589904312
12.22148585956954
12.221485820104533
12.2214857806481
12.221485741200226
12.221485701760914
12.221485662330153
12.221485622907958
12.221485583494326
12.221485544089228
12.221485504692705
12.221485465304728
12.221485425925295
12.22148538655441
12.221485347192074
12.221485307838279
12.221485268493034
12.221485229156317
12.22148518982814
12.221485150508492
12.221485111197394
12.221485071894813
12.221485032600786
12.221484993315267
12.221484954038283
12.221484914769821
12.221484875509887
12.221484836258467
12.221484797015565
12.221484757781178
12.22148471855532
12.22148467933797
12.22148464012913
12.22148460092881
12.221484561736986
12.221484522553672
12.221484483378866
12.221484444212562
12.221484405054753
12.221484365905448
12.22148432676464
12.221484287632327
12.221484248508506
12.221484209393171
12.221484170286342
12.221484131187982
12.221484092098123
12.221484053016752
12.22148401394385
12.221483974879428
12.2214839358235
12.221483896776036
12.221483857737054
12.221483818706545
12.221483779684501
12.221483740670934
12.221483701665829
12.221483662669199
12.22148362368103
12.221483584701303
12.22148354573006
12.22148350676727
12.221483467812936
12.22148342886706
12.221483389929631
12.221483351000657
12.221483312080132
12.221483273168053
12.221483234264422
12.221483195369233
12.22148315648249
12.221483117604187
12.221483078734318
12.221483039872888
12.221483001019887
12.221482962175324
12.221482923339195
12.221482884511499
12.22148284569222
12.221482806881372
12.221482768078948
12.221482729284944
12.221482690499357
12.221482651722196
12.221482612953443
12.221482574193114
12.221482535441195
12.221482496697682
12.221482457962585
12.221482419235887
12.221482380517601
12.22148234180771
12.221482303106239
12.221482264413156
12.221482225728467
12.22148218705218
12.221482148384284
12.22148210972479
12.221482071073682
12.221482032430961
12.221481993796631
12.221481955170688
12.221481916553115
12.221481877943933
12.221481839343141
12.221481800750706
12.221481762166665
12.221481723590998
12.221481685023692
12.221481646464774
12.221481607914209
12.221481569372013
12.221481530838195
12.221481492312726
12.22148145379563
12.221481415286888
12.221481376786508
12.22148133829448
12.221481299810808
12.221481261335487
12.22148122286852
12.221481184409903
12.221481145959634
12.22148110751771
12.221481069084131
12.221481030658879
12.221480992241986
12.221480953833415
12.221480915433201
12.221480877041298
12.221480838657756
12.221480800282523
12.221480761915627
12.221480723557058
12.221480685206815
12.221480646864894
12.221480608531298
12.221480570206015
12.221480531889055
12.221480493580422
12.221480455280096
12.221480416988072
12.221480378704369
12.221480340428988
12.221480302161895
12.221480263903107
12.221480225652629
12.221480187410457
12.221480149176585
12.221480110951013
12.22148007273373
12.221480034524745
12.221479996324048
12.221479958131654
12.22147991994754
12.221479881771725
12.22147984360419
12.221479805444941
12.221479767293962
12.22147972915128
12.221479691016867
12.221479652890734
12.221479614772884
12.221479576663294
12.221479538561983
12.221479500468934
12.221479462384167
12.221479424307656
12.221479386239409
12.22147934817943
12.221479310127705
12.221479272084245
12.221479234049042
12.221479196022091
12.221479158003394
12.221479119992956
12.221479081990758
12.221479043996816
12.22147900601112
12.221478968033665
12.221478930064453
12.221478892103478
12.221478854150757
12.221478816206258
12.221478778269999
12.221478740341983
12.221478702422187
12.221478664510629
12.2214786266073
12.221478588712197
12.221478550825314
12.221478512946652
12.22147847507622
12.221478437213996
12.221478399360006
12.221478361514222
12.22147832367666
12.221478285847306
12.221478248026157
12.221478210213226
12.221478172408496
12.221478134611978
12.221478096823658
12.221478059043545
12.221478021271622
12.221477983507901
12.221477945752387
12.221477908005062
12.221477870265922
12.221477832534982
12.22147779481224
12.221477757097663
12.221477719391286
12.221477681693088
12.221477644003079
12.221477606321242
12.221477568647591
12.22147753098211
12.221477493324807
12.22147745567568
12.221477418034727
12.221477380401934
12.221477342777318
12.221477305160864
12.221477267552585
12.221477229952455
12.221477192360492
12.221477154776695
12.22147711720104
12.221477079633553
12.221477042074213
12.221477004523031
12.22147696697999
12.221476929445108
12.22147689191837
12.221476854399771
12.22147681688932
12.221476779387016
12.22147674189284
12.22147670440681
12.221476666928922
12.221476629459161
12.221476591997531
12.22147655454403
12.221476517098662
12.22147647966142
12.221476442232312
12.22147640481132
12.22147636739845
12.2214763299937
12.221476292597073
12.221476255208556
12.22147621782816
12.221476180455877
12.221476143091712
12.221476105735638
12.221476068387688
12.221476031047843
12.2214759937161
12.221475956392457
12.221475919076916
12.221475881769477
12.221475844470133
12.22147580717888
12.221475769895736
12.221475732620675
12.221475695353702
12.22147565809481
12.22147562084402
12.221475583601311
12.221475546366685
12.221475509140141
12.221475471921677
12.221475434711286
12.221475397508973
12.221475360314743
12.22147532312858
12.22147528595049
12.221475248780465
12.221475211618518
12.221475174464628
12.221475137318805
12.221475100181037
12.22147506305134
12.221475025929697
12.221474988816109
12.221474951710583
12.221474914613104
12.221474877523681
12.22147484044231
12.221474803368977
12.221474766303697
12.22147472924647
12.221474692197276
12.22147465515614
12.221474618123022
12.221474581097949
12.221474544080914
12.221474507071918
12.221474470070946
12.221474433078008
12.221474396093102
12.221474359116222
12.22147432214736
12.22147428518654
12.221474248233733
12.221474211288937
12.221474174352172
12.221474137423424
12.221474100502684
12.22147406358996
12.221474026685252
12.221473989788546
12.221473952899863
12.221473916019171
12.221473879146483
12.221473842281814
12.22147380542513
12.221473768576466
12.221473731735784
12.221473694903098
12.22147365807841
12.221473621261714
12.221473584453006
12.221473547652296
12.22147351085957
12.221473474074823
12.221473437298071
12.221473400529291
12.221473363768492
12.221473327015682
12.221473290270845
12.221473253533983
12.221473216805089
12.221473180084175
12.221473143371222
12.221473106666242
12.221473069969228
12.221473033280185
12.221472996599099
12.221472959925974
12.221472923260823
12.22147288660361
12.221472849954367
12.221472813313069
12.221472776679727
12.221472740054342
12.221472703436902
12.2214726668274
12.221472630225861
12.221472593632251
12.221472557046598
12.221472520468879
12.221472483899094
12.221472447337247

12.221472410783347
12.22147237423737
12.221472337699335
12.221472301169229
12.221472264647044
12.22147222813279
12.22147219162646
12.221472155128062
12.221472118637571
12.221472082155017
12.221472045680365
12.221472009213642
12.221471972754822
12.221471936303928
12.22147189986094
12.221471863425862
12.221471826998698
12.22147179057943
12.221471754168071
12.221471717764619
12.221471681369074
12.22147164498141
12.22147160860165
12.22147157222979
12.221471535865826
12.221471499509752
12.221471463161569
12.221471426821278
12.221471390488873
12.22147135416435
12.221471317847719
12.221471281538959
12.221471245238092
12.221471208945099
12.221471172659983
12.221471136382744
12.221471100113373
12.221471063851881
12.221471027598259
12.221470991352502
12.221470955114611
12.221470918884588
12.221470882662432
12.221470846448135
12.2214708102417
12.221470774043114
12.221470737852401
12.221470701669537
12.221470665494525
12.22147062932736
12.221470593168055
12.221470557016588
12.221470520872973
12.2214704847372
12.221470448609265
12.221470412489184
12.221470376376939
12.221470340272536
12.221470304175954
12.221470268087218
12.221470232006313
12.221470195933243
12.221470159868002
12.221470123810587
12.221470087760995
12.221470051719223
12.221470015685288
12.221469979659165
12.22146994364086
12.22146990763038
12.221469871627713
12.22146983563285
12.221469799645819
12.221469763666587
12.221469727695162
12.221469691731546
12.221469655775737
12.221469619827733
12.221469583887536
12.221469547955142
12.221469512030538
12.221469476113736
12.221469440204723
12.221469404303512
12.221469368410089
12.221469332524467
12.22146929664661
12.221469260776553
12.221469224914294
12.221469189059805
12.221469153213091
12.221469117374175
12.22146908154303
12.221469045719672
12.22146900990407
12.221468974096256
12.221468938296214
12.221468902503934
12.221468866719427
12.221468830942687
12.221468795173708
12.221468759412502
12.221468723659047
12.221468687913362
12.221468652175425
12.221468616445257
12.221468580722838
12.22146854500817
12.221468509301257
12.221468473602094
12.221468437910676
12.221468402227012
12.221468366551086
12.221468330882907
12.221468295222468
12.221468259569763
12.22146822392481
12.22146818828759
12.221468152658101
12.221468117036343
12.221468081422323
12.22146804581603
12.221468010217462
12.22146797462662
12.22146793904351
12.221467903468122
12.221467867900454
12.221467832340505
12.221467796788268
12.221467761243758
12.221467725706951
12.221467690177876
12.2214676546565
12.221467619142839
12.221467583636889
12.221467548138625
12.221467512648081
12.221467477165247
12.221467441690104
12.221467406222667
12.221467370762928
12.221467335310876
12.22146729986653
12.221467264429869
12.221467229000897
12.221467193579624
12.221467158166034
12.221467122760131
12.221467087361914
12.22146705197138
12.221467016588532
12.221466981213352
12.221466945845858
12.22146691048604
12.221466875133897
12.221466839789429
12.221466804452627
12.221466769123499
12.221466733802034
12.221466698488243
12.221466663182111
12.221466627883643
12.221466592592842
12.221466557309688
12.221466522034204
12.221466486766374
12.221466451506194
12.22146641625367
12.221466381008806
12.221466345771587
12.22146631054201
12.221466275320077
12.221466240105801
12.221466204899162
12.221466169700166
12.221466134508805
12.221466099325088
12.221466064149004
12.221466028980556
12.221465993819741
12.221465958666553
12.221465923521006
12.221465888383081
12.22146585325278
12.221465818130111
12.221465783015054
12.221465747907628
12.221465712807817
12.221465677715631
12.221465642631054
12.2214656075541
12.221465572484757
12.221465537423029
12.221465502368899
12.221465467322382
12.221465432283479
12.221465397252178
12.221465362228473
12.221465327212373
12.221465292203883
12.221465257202983
12.221465222209675
12.221465187223965
12.221465152245862
12.22146511727534
12.22146508231241
12.221465047357063
12.221465012409306
12.22146497746914
12.221464942536555
12.221464907611548
12.221464872694122
12.221464837784275
12.221464802882007
12.22146476798732
12.221464733100193
12.221464698220649
12.22146466334868
12.221464628484275
12.221464593627429
12.221464558778155
12.22146452393645
12.221464489102301
12.221464454275708
12.221464419456682
12.221464384645214
12.221464349841305
12.221464315044933
12.221464280256129
12.221464245474872
12.221464210701157
12.22146417593501
12.221464141176389
12.221464106425314
12.221464071681783
12.221464036945802
12.221464002217365
12.221463967496444
12.221463932783076
12.221463898077234
12.221463863378931
12.221463828688151
12.221463794004904
12.221463759329186
12.22146372466099
12.22146369000033
12.22146365534719
12.221463620701568
12.221463586063457
12.221463551432876
12.221463516809807
12.221463482194254
12.221463447586219
12.221463412985687
12.221463378392674
12.221463343807164
12.22146330922915
12.221463274658658
12.221463240095666
12.221463205540168
12.22146317099219
12.221463136451687
12.221463101918692
12.221463067393188
12.22146303287518
12.221462998364666
12.221462963861638
12.221462929366103
12.221462894878053
12.221462860397489
12.221462825924405
12.221462791458807
12.22146275700069
12.221462722550056
12.221462688106902
12.22146265367121
12.221462619242999
12.22146258482226
12.221462550408992
12.221462516003202
12.221462481604867
12.221462447214002
12.221462412830611
12.221462378454667
12.221462344086191
12.221462309725174
12.221462275371618
12.221462241025517
12.221462206686871
12.221462172355675
12.221462138031935
12.221462103715645
12.221462069406803
12.221462035105409
12.221462000811453
12.221461966524943
12.221461932245882
12.22146189797425
12.221461863710068
12.22146182945332
12.221461795203997
12.22146176096211
12.221461726727668
12.221461692500649
12.221461658281054
12.221461624068889
12.221461589864159
12.221461555666842
12.221461521476954
12.221461487294485
12.221461453119431
12.221461418951796
12.22146138479158
12.221461350638783
12.221461316493388
12.221461282355413
12.221461248224841
12.221461214101685
12.221461179985928
12.221461145877566
12.221461111776627
12.221461077683081
12.221461043596937
12.221461009518196
12.221460975446837
12.221460941382887
12.221460907326332
12.221460873277152
12.221460839235366
12.221460805200985
12.221460771173987
12.221460737154366
12.22146070314213
12.221460669137278
12.2214606351398
12.221460601149712
12.221460567166993
12.22146053319166
12.2214604992237
12.221460465263103
12.22146043130988
12.221460397364028
12.221460363425544
12.22146032949443
12.221460295570676
12.221460261654292
12.221460227745265
12.221460193843594
12.221460159949283
12.22146012606233
12.221460092182733
12.221460058310491
12.221460024445602
12.221459990588063
12.221459956737863
12.221459922895022
12.221459889059515
12.221459855231357
12.221459821410548
12.221459787597064
12.221459753790933
12.22145971999214
12.22145968620067
12.221459652416547
12.22145961863976
12.221459584870294
12.221459551108149
12.221459517353347
12.221459483605875
12.221459449865726
12.221459416132891
12.22145938240739
12.221459348689189
12.221459314978329
12.221459281274768
12.221459247578528
12.221459213889606
12.221459180207994
12.221459146533691
12.221459112866695
12.22145907920702
12.22145904555463
12.221459011909557
12.221458978271778
12.221458944641311
12.221458911018136
12.221458877402267
12.221458843793682
12.221458810192406
12.221458776598412
12.221458743011711
12.2214587094323
12.221458675860179
12.221458642295344
12.221458608737791
12.221458575187532
12.221458541644541
12.22145850810884
12.221458474580421
12.22145844105928
12.221458407545406
12.221458374038804
12.221458340539481
12.221458307047424
12.22145827356264
12.221458240085122
12.221458206614878
12.221458173151895
12.221458139696171
12.221458106247706
12.221458072806506
12.221458039372566
12.22145800594587
12.221457972526448
12.221457939114275
12.221457905709347
12.221457872311673
12.221457838921244
12.221457805538066
12.221457772162129
12.221457738793447
12.221457705432
12.221457672077788
12.221457638730827
12.221457605391102
12.221457572058608
12.221457538733354
12.221457505415335
12.22145747210454
12.221457438800986
12.221457405504646
12.221457372215541
12.22145733893366
12.221457305659003
12.221457272391573
12.221457239131352
12.221457205878353
12.221457172632576
12.221457139394019
12.221457106162672
12.221457072938529
12.221457039721617
12.221457006511894
12.221456973309392
12.221456940114091
12.221456906925997
12.221456873745115
12.221456840571422
12.22145680740493
12.221456774245645
12.221456741093554
12.221456707948654
12.221456674810952
12.221456641680437
12.221456608557114
12.221456575440989
12.221456542332042
12.221456509230295
12.22145647613572
12.221456443048334
12.221456409968123
12.221456376895098
12.221456343829251
12.221456310770582
12.221456277719074
12.22145624467476
12.221456211637607
12.221456178607632
12.221456145584813
12.221456112569177
12.221456079560697
12.221456046559387
12.22145601356524
12.221455980578247
12.221455947598427
12.221455914625754
12.221455881660233
12.221455848701877
12.221455815750671
12.22145578280661
12.22145574986971
12.22145571693996
12.221455684017352
12.221455651101893
12.22145561819358
12.221455585292404
12.221455552398373
12.221455519511476
12.221455486631719
12.221455453759102
12.221455420893623
12.22145538803527
12.221455355184052
12.22145532233996
12.221455289503005
12.221455256673174
12.221455223850468
12.221455191034876
12.221455158226423
12.221455125425084
12.221455092630869
12.221455059843763
12.221455027063781
12.221454994290912
12.22145496152516
12.221454928766502
12.221454896014972
12.221454863270548
12.221454830533228
12.221454797803021
12.221454765079905
12.221454732363904

12.22145469965499
12.221454666953184
12.221454634258473
12.221454601570859
12.221454568890342
12.221454536216916
12.221454503550587
12.221454470891343
12.221454438239192
12.221454405594121
12.221454372956151
12.221454340325245
12.221454307701425
12.221454275084698
12.221454242475046
12.221454209872467
12.221454177276964
12.221454144688535
12.221454112107192
12.221454079532904
12.2214540469657
12.22145401440555
12.221453981852482
12.221453949306465
12.221453916767523
12.221453884235647
12.22145385171081
12.221453819193059
12.22145378668235
12.221453754178704
12.221453721682112
12.22145368919258
12.221453656710082
12.221453624234652
12.221453591766252
12.221453559304916
12.221453526850619
12.221453494403365
12.221453461963158
12.221453429529987
12.221453397103865
12.221453364684772
12.221453332272718
12.221453299867697
12.221453267469714
12.221453235078762
12.22145320269484
12.22145317031795
12.221453137948078
12.22145310558523
12.221453073229405
12.221453040880622
12.221453008538846
12.221452976204096
12.22145294387636
12.221452911555641
12.221452879241935
12.221452846935255
12.221452814635574
12.221452782342903
12.22145275005725
12.221452717778599
12.221452685506952
12.221452653242315
12.221452620984676
12.221452588734037
12.221452556490403
12.221452524253765
12.22145249202413
12.221452459801489
12.221452427585826
12.22145239537716
12.221452363175505
12.221452330980826
12.221452298793135
12.22145226661243
12.221452234438706
12.221452202271982
12.221452170112224
12.221452137959444
12.221452105813649
12.221452073674827
12.22145204154299
12.221452009418117
12.221451977300227
12.2214519451893
12.221451913085348
12.221451880988361
12.221451848898333
12.221451816815282
12.221451784739186
12.221451752670058
12.22145172060789
12.221451688552678
12.22145165650443
12.221451624463134
12.221451592428785
12.221451560401393
12.221451528380957
12.22145149636747
12.221451464360936
12.221451432361343
12.221451400368688
12.221451368382994
12.221451336404233
12.22145130443241
12.221451272467522
12.22145124050959
12.221451208558578
12.22145117661451
12.221451144677365
12.221451112747163
12.22145108082389
12.22145104890754
12.221451016998127
12.221450985095627
12.221450953200062
12.221450921311419
12.221450889429692
12.221450857554888
12.221450825686999
12.221450793826035
12.221450761971974
12.22145073012484
12.221450698284611
12.221450666451284
12.221450634624885
12.221450602805392
12.22145057099279
12.2214505391871
12.221450507388308
12.221450475596432
12.221450443811449
12.221450412033361
12.221450380262175
12.221450348497886
12.221450316740485
12.221450284989983
12.221450253246372
12.221450221509654
12.22145018977982
12.221450158056872
12.221450126340805
12.221450094631628
12.22145006292933
12.221450031233925
12.221449999545381
12.221449967863721
12.221449936188943
12.221449904521041
12.221449872860015
12.221449841205853
12.221449809558557
12.221449777918139
12.221449746284582
12.2214497146579
12.221449683038065
12.221449651425118
12.22144961981901
12.22144958821978
12.221449556627393
12.221449525041876
12.22144949346321
12.221449461891396
12.22144943032643
12.221449398768328
12.221449367217065
12.221449335672654
12.221449304135083
12.22144927260437
12.22144924108049
12.22144920956346
12.22144917805327
12.221449146549915
12.221449115053387
12.221449083563716
12.221449052080873
12.221449020604867
12.221448989135675
12.221448957673328
12.221448926217805
12.221448894769118
12.221448863327245
12.221448831892202
12.221448800463985
12.22144876904259
12.221448737628004
12.221448706220242
12.221448674819298
12.221448643425173
12.221448612037861
12.221448580657361
12.221448549283663
12.22144851791678
12.221448486556712
12.221448455203449
12.221448423856986
12.221448392517322
12.22144836118448
12.221448329858417
12.221448298539167
12.221448267226707
12.221448235921049
12.22144820462219
12.221448173330108
12.221448142044828
12.221448110766337
12.221448079494639
12.221448048229728
12.221448016971602
12.221447985720257
12.221447954475687
12.221447923237916
12.221447892006909
12.221447860782698
12.221447829565255
12.221447798354587
12.221447767150693
12.221447735953573
12.221447704763225
12.221447673579645
12.221447642402836
12.221447611232788
12.221447580069508
12.221447548912991
12.221447517763247
12.221447486620253
12.221447455484027
12.221447424354551
12.221447393231827
12.221447362115867
12.221447331006663
12.221447299904204
12.221447268808502
12.221447237719541
12.221447206637338
12.221447175561865
12.221447144493158
12.221447113431172
12.221447082375946
12.221447051327463
12.221447020285707
12.22144698925069
12.221446958222415
12.221446927200864
12.22144689618606
12.221446865177976
12.221446834176627
12.221446803182012
12.22144677219412
12.221446741212949
12.221446710238506
12.221446679270784
12.221446648309788
12.221446617355515
12.221446586407948
12.22144655546711
12.221446524532983
12.221446493605567
12.221446462684874
12.221446431770884
12.221446400863599
12.221446369963035
12.221446339069162
12.221446308182017
12.221446277301563
12.22144624642781
12.221446215560757
12.221446184700397
12.221446153846747
12.221446122999795
12.221446092159534
12.22144606132597
12.22144603049909
12.221445999678913
12.221445968865421
12.22144593805861
12.221445907258492
12.221445876465062
12.221445845678309
12.221445814898237
12.221445784124851
12.22144575335814
12.221445722598125
12.221445691844758
12.221445661098086
12.221445630358076
12.221445599624735
12.221445568898076
12.221445538178084
12.221445507464754
12.221445476758099
12.221445446058107
12.221445415364776
12.221445384678102
12.221445353998087
12.221445323324737
12.22144529265805
12.221445261998023
12.221445231344633
12.2214452006979
12.221445170057828
12.221445139424398
12.221445108797617
12.221445078177492
12.22144504756401
12.221445016957171
12.221444986356973
12.221444955763419
12.221444925176506
12.221444894596225
12.221444864022592
12.221444833455584
12.22144480289522
12.221444772341485
12.221444741794382
12.221444711253907
12.221444680720072
12.221444650192852
12.221444619672257
12.221444589158287
12.221444558650953
12.221444528150228
12.22144449765613
12.221444467168647
12.221444436687777
12.22144440621352
12.22144437574589
12.221444345284871
12.221444314830451
12.221444284382658
12.221444253941467
12.221444223506875
12.221444193078893
12.221444162657523
12.221444132242748
12.221444101834589
12.221444071433012
12.22144404103804
12.221444010649673
12.221443980267889
12.221443949892702
12.22144391952411
12.221443889162108
12.221443858806703
12.221443828457875
12.221443798115645
12.221443767779993
12.221443737450928
12.221443707128445
12.221443676812543
12.221443646503232
12.221443616200482
12.221443585904325
12.22144355561473
12.22144352533172
12.221443495055281
12.221443464785407
12.221443434522104
12.221443404265383
12.22144337401521
12.221443343771611
12.221443313534575
12.221443283304101
12.221443253080194
12.221443222862844
12.22144319265205
12.221443162447821
12.221443132250139
12.221443102059023
12.221443071874434
12.221443041696421
12.22144301152495
12.221442981360036
12.221442951201658
12.221442921049833
12.22144289090455
12.221442860765814
12.221442830633606
12.22144280050794
12.221442770388832
12.221442740276249
12.221442710170198
12.221442680070686
12.221442649977718
12.221442619891258
12.221442589811344
12.221442559737952
12.22144252967109
12.221442499610758
12.221442469556937
12.221442439509662
12.221442409468894
12.221442379434643
12.221442349406914
12.22144231938571
12.22144228937101
12.221442259362838
12.221442229361172
12.221442199366018
12.221442169377372
12.221442139395243
12.221442109419602
12.221442079450496
12.221442049487875
12.221442019531764
12.221441989582154
12.221441959639039
12.221441929702427
12.221441899772314
12.221441869848702
12.221441839931574
12.221441810020945
12.221441780116809
12.22144175021916
12.221441720328004
12.221441690443339
12.221441660565157
12.22144163069346
12.22144160082824
12.221441570969505
12.22144154111726
12.221441511271479
12.221441481432189
12.221441451599375
12.221441421773035
12.221441391953164
12.221441362139771
12.221441332332844
12.221441302532396
12.2214412727384
12.22144124295088
12.221441213169824
12.221441183395235
12.221441153627108
12.22144112386543
12.221441094110224
12.221441064361471
12.221441034619186
12.221441004883342
12.221440975153962
12.221440945431034
12.221440915714556
12.221440886004526
12.221440856300944
12.221440826603805
12.221440796913122
12.22144076722888
12.221440737551081
12.221440707879717
12.221440678214798
12.221440648556316
12.221440618904273
12.221440589258668
12.221440559619495
12.221440529986754
12.221440500360439
12.22144047074057
12.22144044112712
12.221440411520096
12.221440381919507
12.22144035232533
12.22144032273758
12.221440293156265
12.221440263581357
12.221440234012867
12.221440204450806
12.221440174895154
12.221440145345921
12.2214401158031
12.221440086266695
12.221440056736686
12.221440027213093
12.22143999769591
12.221439968185138
12.221439938680776
12.221439909182797
12.221439879691243
12.221439850206071
12.221439820727314
12.221439791254946
12.221439761788986
12.221439732329417
12.221439702876227
12.221439673429447
12.221439643989047
12.221439614555049
12.221439585127431
12.221439555706207
12.221439526291356
12.221439496882905
12.221439467480831
12.221439438085135
12.221439408695822
12.221439379312885
12.22143934993632
12.22143932056615
12.22143929120235
12.221439261844916
12.221439232493854
12.221439203149163
12.221439173810841
12.221439144478888
12.221439115153306
12.22143908583408
12.221439056521223
12.221439027214732
12.2214389979146
12.221438968620825
12.221438939333405
12.221438910052346
12.22143888077764
12.221438851509294
12.221438822247286
12.22143879299165
12.22143876374235
12.2214387344994
12.2214387052628
12.221438676032543
12.221438646808627
12.22143861759107
12.221438588379842
12.221438559174953
12.221438529976409
12.2214385007842
12.22143847159832
12.221438442418785
12.221438413245583
12.221438384078704
12.221438354918158
12.221438325763948
12.221438296616066
12.221438267474504
12.221438238339264
12.221438209210355
12.221438180087777
12.221438150971506
12.221438121861555
12.22143809275792
12.221438063660617
12.22143803456962
12.221438005484938
12.221437976406575
12.221437947334508
12.221437918268757
12.221437889209318
12.221437860156186
12.221437831109366

12.221437802068843
12.221437773034616
12.221437744006705
12.221437714985084
12.221437685969764
12.221437656960743
12.22143762795803
12.221437598961598
12.221437569971465
12.221437540987619
12.22143751201007
12.221437483038809
12.221437454073836
12.221437425115141
12.221437396162736
12.221437367216623
12.221437338276791
12.221437309343235
12.221437280415964
12.221437251494969
12.221437222580251
12.221437193671811
12.221437164769643
12.221437135873744
12.221437106984116
12.22143707810077
12.221437049223686
12.221437020352878
12.221436991488325
12.221436962630044
12.221436933778019
12.221436904932267
12.221436876092765
12.221436847259525
12.221436818432545
12.221436789611833
12.22143676079736
12.22143673198914
12.221436703187194
12.221436674391482
12.221436645602022
12.221436616818808
12.221436588041856
12.221436559271135
12.221436530506654
12.22143650174843
12.221436472996439
12.2214364442507
12.22143641551119
12.221436386777917
12.221436358050896
12.221436329330093
12.221436300615528
12.221436271907194
12.221436243205094
12.221436214509225
12.22143618581959
12.221436157136171
12.221436128458981
12.221436099788018
12.221436071123268
12.221436042464758
12.221436013812456
12.221435985166371
12.221435956526507
12.221435927892854
12.22143589926543
12.22143587064421
12.221435842029207
12.221435813420406
12.221435784817823
12.22143575622145
12.221435727631265
12.2214356990473
12.221435670469548
12.221435641897985
12.221435613332623
12.221435584773467
12.221435556220506
12.221435527673737
12.221435499133179
12.221435470598808
12.221435442070627
12.221435413548646
12.221435385032851
12.221435356523248
12.221435328019835
12.221435299522597
12.221435271031545
12.221435242546686
12.221435214068011
12.22143518559551
12.221435157129195
12.221435128669055
12.221435100215084
12.221435071767305
12.221435043325695
12.22143501489025
12.221434986460975
12.22143495803789
12.221434929620958
12.221434901210202
12.2214348728056
12.221434844407174
12.221434816014908
12.221434787628812
12.22143475924887
12.221434730875094
12.221434702507468
12.221434674146005
12.221434645790698
12.221434617441544
12.221434589098543
12.22143456076168
12.221434532430992
12.221434504106439
12.221434475788046
12.221434447475783
12.22143441916967
12.2214343908697
12.221434362575874
12.221434334288189
12.221434306006651
12.22143427773125
12.221434249461979
12.221434221198852
12.221434192941851
12.22143416469098
12.221434136446247
12.221434108207644
12.221434079975177
12.221434051748828
12.221434023528609
12.221433995314513
12.221433967106547
12.221433938904696
12.221433910708969
12.221433882519364
12.221433854335874
12.221433826158512
12.221433797987252
12.22143376982211
12.221433741663084
12.221433713510162
12.221433685363357
12.22143365722267
12.221433629088077
12.221433600959593
12.221433572837222
12.221433544720949
12.221433516610773
12.221433488506705
12.221433460408743
12.22143343231687
12.221433404231092
12.221433376151419
12.22143334807784
12.221433320010345
12.22143329194895
12.221433263893655
12.221433235844426
12.2214332078013
12.22143317976426
12.221433151733308
12.221433123708433
12.221433095689644
12.221433067676932
12.221433039670307
12.221433011669754
12.221432983675282
12.221432955686883
12.221432927704562
12.221432899728317
12.221432871758143
12.221432843794043
12.221432815835998
12.221432787884035
12.221432759938137
12.22143273199831
12.221432704064531
12.22143267613682
12.221432648215178
12.221432620299595
12.221432592390066
12.221432564486602
12.221432536589194
12.221432508697829
12.22143248081253
12.221432452933282
12.221432425060085
12.221432397192928
12.221432369331835
12.221432341476778
12.22143231362777
12.22143228578481
12.221432257947882
12.221432230117005
12.221432202292167
12.22143217447337
12.221432146660598
12.221432118853887
12.2214320910532
12.221432063258547
12.221432035469928
12.221432007687332
12.22143197991077
12.221431952140238
12.221431924375745
12.221431896617267
12.221431868864812
12.221431841118385
12.221431813377974
12.221431785643594
12.221431757915227
12.221431730192878
12.221431702476549
12.221431674766233
12.221431647061932
12.22143161936365
12.221431591671376
12.221431563985112
12.221431536304861
12.221431508630614
12.221431480962368
12.221431453300132
12.221431425643903
12.22143139799368
12.221431370349448
12.221431342711218
12.221431315078986
12.221431287452761
12.221431259832519
12.221431232218285
12.22143120461004
12.221431177007789
12.221431149411535
12.221431121821253
12.221431094236973
12.22143106665867
12.221431039086363
12.22143101152003
12.221430983959696
12.221430956405328
12.221430928856948
12.221430901314548
12.22143087377812
12.221430846247683
12.221430818723208
12.22143079120471
12.221430763692185
12.221430736185635
12.221430708685055
12.221430681190437
12.221430653701796
12.221430626219107
12.221430598742394
12.221430571271643
12.221430543806852
12.221430516348025
12.221430488895168
12.221430461448252
12.221430434007303
12.221430406572306
12.22143037914326
12.221430351720182
12.221430324303041
12.221430296891858
12.22143026948663
12.221430242087338
12.221430214693994
12.221430187306607
12.221430159925156
12.221430132549653
12.221430105180085
12.221430077816459
12.221430050458778
12.221430023107033
12.221429995761218
12.221429968421345
12.221429941087402
12.221429913759392
12.22142988643732
12.221429859121171
12.221429831810953
12.221429804506666
12.221429777208293
12.221429749915856
12.221429722629349
12.221429695348752
12.221429668074085
12.221429640805333
12.221429613542501
12.221429586285582
12.221429559034592
12.221429531789497
12.221429504550327
12.221429477317068
12.221429450089726
12.221429422868285
12.221429395652759
12.221429368443127
12.221429341239412
12.221429314041602
12.221429286849686
12.221429259663687
12.221429232483585
12.221429205309379
12.22142917814106
12.221429150978656
12.221429123822132
12.221429096671512
12.221429069526778
12.221429042387944
12.221429015255
12.221428988127936
12.221428961006769
12.221428933891492
12.221428906782092
12.221428879678577
12.22142885258094
12.221428825489195
12.221428798403323
12.221428771323332
12.221428744249215
12.221428717180984
12.22142869011862
12.221428663062133
12.221428636011522
12.221428608966775
12.221428581927901
12.221428554894898
12.221428527867761
12.221428500846484
12.221428473831079
12.221428446821534
12.221428419817856
12.221428392820043
12.221428365828077
12.221428338841978
12.22142831186173
12.221428284887342
12.221428257918811
12.221428230956128
12.2214282039993
12.221428177048326
12.2214281501032
12.221428123163927
12.221428096230495
12.22142806930291
12.221428042381167
12.221428015465268
12.221427988555208
12.221427961650994
12.221427934752624
12.221427907860084
12.221427880973383
12.221427854092518
12.22142782721749
12.22142780034829
12.221427773484926
12.221427746627393
12.221427719775685
12.221427692929813
12.221427666089758
12.22142763925554
12.221427612427135
12.221427585604562
12.2214275587878
12.221427531976865
12.221427505171754
12.221427478372453
12.22142745157898
12.221427424791308
12.221427398009466
12.221427371233425
12.221427344463203
12.221427317698778
12.221427290940172
12.221427264187376
12.221427237440382
12.221427210699202
12.221427183963813
12.221427157234235
12.22142713051046
12.221427103792475
12.221427077080298
12.221427050373917
12.221427023673334
12.221426996978547
12.221426970289546
12.221426943606346
12.221426916928934
12.22142689025732
12.221426863591487
12.221426836931435
12.221426810277181
12.22142678362871
12.221426756986022
12.221426730349117
12.221426703717992
12.221426677092655
12.221426650473086
12.221426623859296
12.221426597251293
12.221426570649058
12.221426544052589
12.221426517461907
12.221426490876993
12.221426464297842
12.221426437724457
12.22142641115685
12.221426384595011
12.22142635803893
12.221426331488619
12.221426304944062
12.221426278405273
12.221426251872245
12.22142622534497
12.221426198823465
12.221426172307696
12.221426145797693
12.221426119293454
12.22142609279496
12.221426066302213
12.22142603981522
12.221426013333971
12.221425986858478
12.221425960388725
12.221425933924726
12.221425907466458
12.221425881013936
12.221425854567176
12.221425828126137
12.22142580169083
12.221425775261274
12.22142574883745
12.221425722419358
12.221425696007007
12.221425669600388
12.221425643199495
12.221425616804332
12.221425590414906
12.221425564031197
12.221425537653221
12.221425511280973
12.221425484914448
12.221425458553643
12.221425432198554
12.221425405849194
12.221425379505561
12.221425353167614
12.221425326835414
12.221425300508919
12.221425274188135
12.22142524787308
12.221425221563722
12.221425195260077
12.22142516896214
12.221425142669904
12.221425116383394
12.221425090102572
12.221425063827466
12.221425037558056
12.221425011294347
12.221424985036341
12.221424958784036
12.221424932537433
12.221424906296507
12.221424880061297
12.221424853831774
12.22142482760795
12.221424801389805
12.221424775177358
12.221424748970604
12.22142472276954
12.221424696574148
12.221424670384451
12.22142464420044
12.221424618022105
12.221424591849466
12.221424565682502

12.221424539521218
12.221424513365596
12.221424487215675
12.221424461071415
12.22142443493283
12.22142440879993
12.221424382672689
12.221424356551132
12.221424330435228
12.221424304325005
12.22142427822044
12.221424252121551
12.221424226028313
12.22142419994075
12.22142417385885
12.221424147782615
12.221424121712024
12.221424095647098
12.221424069587837
12.221424043534224
12.22142401748626
12.221423991443965
12.221423965407318
12.221423939376317
12.221423913350975
12.221423887331268
12.22142386131722
12.22142383530881
12.22142380930605
12.221423783308932
12.221423757317456
12.221423731331628
12.221423705351427
12.221423679376883
12.221423653407962
12.221423627444684
12.22142360148704
12.22142357553503
12.221423549588659
12.221423523647909
12.221423497712797
12.221423471783309
12.22142344585945
12.22142341994121
12.221423394028607
12.221423368121627
12.221423342220266
12.221423316324529
12.221423290434416
12.221423264549916
12.221423238671042
12.221423212797774
12.221423186930132
12.221423161068103
12.221423135211687
12.22142310936087
12.221423083515681
12.221423057676102
12.221423031842114
12.22142300601374
12.221422980190981
12.22142295437383
12.22142292856227
12.221422902756313
12.221422876955963
12.221422851161215
12.221422825372057
12.221422799588506
12.221422773810549
12.221422748038183
12.221422722271402
12.221422696510228
12.22142267075464
12.221422645004644
12.221422619260235
12.22142259352142
12.221422567788181
12.221422542060536
12.221422516338471
12.221422490621993
12.22142246491109
12.221422439205778
12.221422413506028
12.22142238781187
12.221422362123286
12.22142233644028
12.22142231076284
12.22142228509098
12.2214222594247
12.22142223376398
12.221422208108828
12.221422182459245
12.22142215681523
12.221422131176787
12.2214221055439
12.221422079916586
12.22142205429483
12.221422028678635
12.221422003067994
12.221421977462922
12.221421951863398
12.221421926269441
12.221421900681039
12.22142187509818
12.221421849520878
12.221421823949125
12.221421798382929
12.221421772822287
12.221421747267176
12.221421721717613
12.221421696173607
12.221421670635149
12.221421645102224
12.221421619574846
12.221421594052996
12.221421568536702
12.221421543025938
12.221421517520712
12.221421492021024
12.221421466526872
12.221421441038252
12.221421415555156
12.221421390077605
12.221421364605574
12.22142133913907
12.221421313678107
12.221421288222658
12.221421262772738
12.22142123732834
12.22142121188946
12.221421186456114
12.221421161028276
12.221421135605972
12.221421110189164
12.221421084777887
12.221421059372124
12.221421033971875
12.221421008577144
12.221420983187917
12.221420957804206
12.221420932426001
12.2214209070533
12.221420881686115
12.22142085632443
12.221420830968261
12.221420805617582
12.221420780272403
12.221420754932733
12.22142072959857
12.221420704269889
12.221420678946721
12.221420653629037
12.221420628316851
12.22142060301017
12.22142057770897
12.221420552413258
12.221420527123046
12.221420501838326
12.221420476559086
12.22142045128533
12.22142042601707
12.221420400754289
12.221420375496994
12.22142035024518
12.221420324998839
12.22142029975799
12.221420274522606
12.221420249292713
12.221420224068291
12.221420198849342
12.221420173635869
12.221420148427857
12.22142012322533
12.221420098028268
12.221420072836684
12.221420047650556
12.2214200224699
12.221419997294708
12.221419972124984
12.221419946960717
12.221419921801917
12.22141989664857
12.221419871500698
12.221419846358268
12.2214198212213
12.221419796089794
12.22141977096374
12.221419745843127
12.22141972072798
12.22141969561828
12.221419670514031
12.221419645415233
12.221419620321878
12.22141959523397
12.22141957015151
12.221419545074491
12.221419520002923
12.221419494936791
12.221419469876096
12.221419444820839
12.221419419771031
12.221419394726649
12.221419369687712
12.221419344654207
12.22141931962613
12.221419294603487
12.221419269586281
12.221419244574504
12.22141921956815
12.221419194567227
12.221419169571734
12.221419144581658
12.221419119597014
12.221419094617794
12.221419069643982
12.221419044675601
12.221419019712636
12.221418994755094
12.221418969802956
12.22141894485625
12.221418919914955
12.221418894979072
12.2214188700486
12.22141884512354
12.221418820203883
12.221418795289647
12.221418770380808
12.221418745477385
12.221418720579361
12.221418695686735
12.221418670799531
12.22141864591771
12.221418621041295
12.221418596170285
12.221418571304664
12.221418546444447
12.221418521589628
12.221418496740199
12.22141847189616
12.221418447057513
12.22141842222427
12.221418397396397
12.221418372573934
12.221418347756847
12.221418322945159
12.221418298138834
12.221418273337898
12.221418248542367
12.221418223752197
12.221418198967411
12.221418174188006
12.221418149413985
12.221418124645334
12.221418099882067
12.221418075124165
12.22141805037164
12.221418025624487
12.221418000882707
12.2214179761463
12.221417951415258
12.221417926689583
12.221417901969282
12.221417877254334
12.22141785254476
12.221417827840545
12.221417803141696
12.221417778448203
12.221417753760075
12.221417729077308
12.221417704399887
12.221417679727825
12.221417655061119
12.221417630399772
12.221417605743776
12.22141758109313
12.221417556447825
12.221417531807882
12.221417507173285
12.221417482544037
12.221417457920133
12.221417433301568
12.221417408688351
12.221417384080478
12.22141735947794
12.221417334880742
12.221417310288896
12.221417285702373
12.22141726112119
12.221417236545346
12.221417211974831
12.221417187409653
12.221417162849807
12.221417138295294
12.221417113746101
12.221417089202246
12.22141706466371
12.221417040130513
12.221417015602626
12.221416991080067
12.22141696656283
12.221416942050922
12.221416917544332
12.221416893043054
12.221416868547099
12.221416844056458
12.221416819571134
12.221416795091134
12.221416770616441
12.221416746147046
12.221416721682981
12.221416697224221
12.221416672770761
12.221416648322617
12.221416623879776
12.221416599442236
12.221416575010016
12.22141655058309
12.221416526161459
12.221416501745136
12.22141647733411
12.221416452928382
12.22141642852795
12.221416404132826
12.221416379742987
12.22141635535844
12.221416330979185
12.221416306605214
12.221416282236548
12.221416257873166
12.221416233515077
12.221416209162278
12.22141618481475
12.221416160472517
12.221416136135563
12.221416111803896
12.221416087477511
12.22141606315639
12.221416038840557
12.221416014530005
12.221415990224733
12.221415965924736
12.221415941630006
12.221415917340552
12.221415893056376
12.221415868777466
12.221415844503818
12.221415820235448
12.22141579597234
12.22141577171451
12.221415747461933
12.22141572321462
12.221415698972582
12.221415674735791
12.22141565050427
12.221415626278
12.221415602056995
12.221415577841244
12.221415553630747
12.221415529425514
12.221415505225531
12.22141548103079
12.221415456841315
12.221415432657086
12.221415408478105
12.221415384304372
12.221415360135877
12.221415335972642
12.22141531181465
12.22141528766189
12.22141526351438
12.221415239372108
12.22141521523508
12.221415191103299
12.22141516697674
12.221415142855417
12.221415118739339
12.22141509462849
12.221415070522877
12.221415046422502
12.221415022327347
12.221414998237432
12.221414974152733
12.221414950073273
12.221414925999037
12.221414901930016
12.221414877866236
12.221414853807666
12.221414829754329
12.221414805706202
12.221414781663299
12.221414757625611
12.221414733593145
12.221414709565899
12.221414685543863
12.221414661527032
12.221414637515428
12.221414613509031
12.22141458950784
12.221414565511862
12.221414541521096
12.22141451753553
12.221414493555175
12.221414469580022
12.221414445610078
12.221414421645333
12.221414397685786
12.221414373731445
12.221414349782304
12.221414325838353
12.221414301899607
12.221414277966051
12.221414254037699
12.221414230114526
12.221414206196552
12.221414182283773
12.221414158376184
12.221414134473783
12.221414110576571
12.221414086684538
12.221414062797702
12.221414038916047
12.221414015039578
12.221413991168284
12.221413967302171
12.221413943441242
12.221413919585498
12.22141389573492
12.221413871889522
12.221413848049298
12.221413824214261
12.221413800384388
12.221413776559684
12.221413752740155
12.2214137289258
12.221413705116605
12.221413681312587
12.221413657513729
12.22141363372004
12.221413609931513
12.22141358614815
12.221413562369955
12.22141353859691
12.221413514829026
12.22141349106631
12.221413467308745
12.221413443556342
12.221413419809092
12.221413396066993
12.221413372330042
12.221413348598254
12.221413324871616
12.221413301150118
12.221413277433783
12.221413253722588
12.221413230016541
12.221413206315637
12.221413182619878
12.221413158929264
12.221413135243786
12.221413111563452
12.221413087888264
12.221413064218204
12.221413040553294
12.221413016893512
12.221412993238857
12.221412969589354
12.221412945944977
12.221412922305728
12.221412898671618
12.221412875042635
12.221412851418773
12.221412827800044
12.221412804186443

12.221412780577966
12.221412756974615
12.221412733376381
12.221412709783273
12.22141268619529
12.221412662612419
12.22141263903467
12.221412615462034
12.22141259189453
12.221412568332127
12.221412544774841
12.221412521222662
12.221412497675601
12.221412474133652
12.221412450596816
12.221412427065081
12.221412403538462
12.221412380016943
12.221412356500526
12.221412332989223
12.221412309483023
12.221412285981922
12.221412262485918
12.221412238995015
12.221412215509204
12.221412192028497
12.221412168552884
12.221412145082375
12.221412121616952
12.22141209815663
12.221412074701389
12.221412051251244
12.221412027806196
12.22141200436623
12.22141198093135
12.221411957501566
12.221411934076857
12.221411910657237
12.221411887242693
12.221411863833238
12.221411840428868
12.221411817029567
12.221411793635346
12.221411770246219
12.221411746862149
12.221411723483158
12.221411700109254
12.221411676740415
12.221411653376643
12.22141163001795
12.22141160666432
12.221411583315767
12.221411559972278
12.221411536633848
12.221411513300486
12.221411489972201
12.221411466648973
12.221411443330801
12.221411420017695
12.221411396709655
12.22141137340666
12.221411350108738
12.221411326815863
12.221411303528043
12.221411280245277
12.221411256967572
12.221411233694917
12.22141121042731
12.221411187164755
12.221411163907247
12.221411140654782
12.22141111740738
12.221411094165017
12.221411070927694
12.221411047695417
12.221411024468184
12.221411001245988
12.22141097802884
12.221410954816724
12.221410931609652
12.221410908407613
12.221410885210606
12.221410862018642
12.22141083883171
12.22141081564981
12.221410792472934
12.221410769301098
12.22141074613429
12.221410722972513
12.221410699815753
12.221410676664023
12.221410653517323
12.22141063037564
12.221410607238981
12.221410584107359
12.221410560980734
12.221410537859152
12.221410514742578
12.221410491631021
12.221410468524468
12.22141044542295
12.221410422326429
12.221410399234935
12.221410376148444
12.22141035306697
12.221410329990505
12.221410306919045
12.22141028385259
12.221410260791147
12.221410237734709
12.22141021468328
12.221410191636847
12.221410168595419
12.221410145558991
12.221410122527564
12.221410099501135
12.221410076479707
12.221410053463275
12.221410030451834
12.221410007445396
12.221409984443945
12.221409961447483
12.221409938456016
12.221409915469543
12.221409892488055
12.221409869511557
12.221409846540043
12.221409823573516
12.22140980061198
12.221409777655419
12.221409754703844
12.221409731757248
12.221409708815637
12.221409685879001
12.221409662947352
12.221409640020674
12.221409617098967
12.221409594182232
12.22140957127049
12.221409548363713
12.221409525461896
12.221409502565066
12.221409479673204
12.2214094567863
12.221409433904377
12.2214094110274
12.221409388155408
12.221409365288366
12.221409342426302
12.221409319569194
12.221409296717043
12.221409273869867
12.221409251027628
12.221409228190355
12.221409205358048
12.221409182530683
12.221409159708282
12.221409136890827
12.221409114078332
12.22140909127079
12.221409068468185
12.221409045670546
12.221409022877845
12.221409000090095
12.22140897730728
12.22140895452943
12.221408931756512
12.221408908988536
12.2214088862255
12.22140886346741
12.22140884071426
12.221408817966042
12.221408795222771
12.221408772484427
12.221408749751026
12.221408727022553
12.221408704299021
12.221408681580415
12.221408658866741
12.22140863615799
12.22140861345418
12.221408590755301
12.221408568061337
12.221408545372302
12.221408522688186
12.221408500009002
12.22140847733474
12.221408454665392
12.221408432000976
12.221408409341466
12.221408386686884
12.221408364037213
12.221408341392465
12.221408318752628
12.221408296117707
12.221408273487695
12.221408250862595
12.221408228242412
12.221408205627132
12.221408183016763
12.221408160411308
12.221408137810743
12.221408115215095
12.221408092624346
12.22140807003851
12.221408047457574
12.221408024881542
12.221408002310396
12.221407979744152
12.221407957182818
12.221407934626376
12.221407912074818
12.22140788952816
12.221407866986397
12.22140784444954
12.22140782191756
12.221407799390475
12.22140777686828
12.22140775435097
12.221407731838553
12.221407709331015
12.221407686828373
12.221407664330604
12.221407641837722
12.221407619349725
12.221407596866602
12.221407574388364
12.221407551914995
12.221407529446527
12.221407506982917
12.22140748452419
12.22140746207033
12.221407439621347
12.221407417177243
12.221407394738003
12.221407372303636
12.221407349874141
12.221407327449521
12.221407305029746
12.221407282614853
12.22140726020482
12.221407237799653
12.221407215399347
12.2214071930039
12.22140717061333
12.221407148227602
12.221407125846747
12.22140710347074
12.221407081099589
12.221407058733304
12.221407036371858
12.221407014015279
12.22140699166354
12.22140696931666
12.221406946974632
12.221406924637446
12.221406902305116
12.221406879977632
12.221406857654996
12.221406835337193
12.221406813024249
12.221406790716141
12.221406768412875
12.221406746114454
12.221406723820866
12.22140670153213
12.221406679248208
12.221406656969146
12.221406634694912
12.22140661242551
12.221406590160939
12.221406567901203
12.221406545646301
12.22140652339622
12.221406501150982
12.221406478910561
12.221406456674979
12.221406434444214
12.221406412218277
12.221406389997163
12.22140636778087
12.221406345569402
12.221406323362757
12.22140630116093
12.22140627896393
12.221406256771733
12.221406234584355
12.221406212401796
12.221406190224053
12.221406168051123
12.221406145883002
12.221406123719703
12.22140610156121
12.221406079407515
12.22140605725865
12.221406035114578
12.22140601297531
12.221405990840855
12.221405968711204
12.221405946586351
12.221405924466307
12.221405902351053
12.221405880240608
12.221405858134958
12.221405836034114
12.22140581393805
12.221405791846795
12.221405769760334
12.221405747678663
12.22140572560178
12.221405703529705
12.221405681462414
12.22140565939991
12.221405637342187
12.221405615289255
12.221405593241121
12.221405571197765
12.221405549159195
12.221405527125407
12.2214055050964
12.221405483072186
12.22140546105273
12.221405439038067
12.221405417028183
12.221405395023082
12.221405373022742
12.221405351027185
12.221405329036399
12.22140530705038
12.221405285069148
12.221405263092684
12.221405241120985
12.22140521915405
12.221405197191896
12.221405175234505
12.221405153281873
12.22140513133401
12.221405109390906
12.221405087452569
12.221405065518988
12.221405043590183
12.22140502166613
12.221404999746829
12.221404977832293
12.221404955922514
12.221404934017482
12.221404912117205
12.221404890221697
12.221404868330918
12.221404846444907
12.221404824563646
12.221404802687129
12.221404780815355
12.221404758948337
12.221404737086067
12.221404715228527
12.221404693375751
12.221404671527704
12.221404649684413
12.221404627845851
12.221404606012022
12.22140458418295
12.221404562358613
12.221404540539005
12.221404518724137
12.221404496913998
12.221404475108603
12.221404453307938
12.221404431511996
12.221404409720792
12.221404387934323
12.221404366152576
12.22140434437556
12.22140432260327
12.221404300835694
12.221404279072855
12.221404257314738
12.221404235561344
12.221404213812665
12.221404192068718
12.221404170329478
12.22140414859497
12.221404126865167
12.221404105140083
12.221404083419719
12.221404061704066
12.22140403999313
12.221404018286895
12.221403996585384
12.221403974888586
12.22140395319649
12.221403931509094
12.221403909826419
12.221403888148444
12.221403866475173
12.221403844806607
12.221403823142754
12.221403801483591
12.22140377982913
12.221403758179369
12.22140373653432
12.22140371489395
12.221403693258283
12.221403671627328
12.221403650001045
12.221403628379466
12.221403606762582
12.221403585150382
12.221403563542884
12.221403541940067
12.22140352034194
12.22140349874851
12.22140347715976
12.221403455575691
12.221403433996317
12.221403412421617
12.221403390851602
12.221403369286275
12.221403347725623
12.221403326169652
12.221403304618358
12.221403283071739
12.2214032615298
12.221403239992542
12.22140321845995
12.221403196932037
12.221403175408806
12.221403153890224
12.22140313237633
12.221403110867103
12.22140308936254
12.221403067862646
12.221403046367419
12.221403024876857
12.22140300339096
12.221402981909725
12.221402960433156
12.221402938961244
12.221402917493998
12.221402896031401
12.221402874573478
12.22140285312019
12.22140283167158
12.221402810227609
12.221402788788307
12.221402767353656
12.221402745923648
12.221402724498303
12.221402703077597
12.221402681661555
12.22140266025015
12.22140263884339
12.221402617441282
12.221402596043818
12.221402574650991
12.221402553262822
12.221402531879288
12.22140251050039
12.221402489126138
12.221402467756533
12.22140244639155
12.221402425031217
12.221402403675508
12.22140238232444
12.221402360978013
12.221402339636214
12.221402318299042
12.221402296966504
12.221402275638603
12.221402254315327
12.221402232996683
12.221402211682657
12.221402190373256
12.22140216906849
12.221402147768343
12.221402126472826
12.221402105181918
12.22140208389564
12.221402062613981
12.221402041336944
12.221402020064522
12.221401998796715
12.22140197753353
12.221401956274956
12.221401935020994
12.221401913771643

12.221401892526915
12.221401871286792
12.221401850051276
12.221401828820369
12.221401807594084
12.221401786372391
12.221401765155314
12.22140174394283
12.221401722734957
12.221401701531684
12.22140168033302
12.221401659138952
12.221401637949487
12.221401616764622
12.221401595584346
12.221401574408675
12.221401553237603
12.221401532071127
12.221401510909235
12.221401489751944
12.221401468599232
12.22140144745114
12.221401426307608
12.221401405168681
12.221401384034339
12.22140136290458
12.221401341779405
12.221401320658831
12.221401299542832
12.221401278431411
12.22140125732457
12.22140123622232
12.221401215124644
12.221401194031552
12.221401172943036
12.221401151859098
12.221401130779729
12.22140110970495
12.221401088634735
12.221401067569097
12.22140104650803
12.221401025451536
12.221401004399606
12.22140098335225
12.221400962309461
12.221400941271241
12.221400920237588
12.221400899208497
12.221400878183967
12.221400857164008
12.221400836148606
12.221400815137768
12.221400794131496
12.221400773129773
12.221400752132606
12.221400731140013
12.221400710151965
12.221400689168467
12.221400668189535
12.221400647215157
12.221400626245323
12.221400605280042
12.221400584319312
12.221400563363137
12.22140054241151
12.221400521464426
12.22140050052189
12.221400479583902
12.221400458650445
12.221400437721543
12.221400416797184
12.22140039587737
12.221400374962096
12.221400354051354
12.221400333145144
12.221400312243492
12.221400291346363
12.221400270453776
12.221400249565711
12.221400228682196
12.221400207803203
12.221400186928747
12.221400166058817
12.221400145193426
12.221400124332563
12.221400103476219
12.221400082624417
12.221400061777127
12.221400040934357
12.221400020096121
12.221399999262406
12.221399978433208
12.221399957608538
12.221399936788389
12.221399915972754
12.221399895161639
12.221399874355038
12.221399853552956
12.221399832755386
12.22139981196233
12.221399791173793
12.22139977038976
12.221399749610246
12.221399728835237
12.22139970806475
12.221399687298753
12.221399666537268
12.221399645780297
12.221399625027825
12.221399604279858
12.221399583536389
12.221399562797428
12.221399542062974
12.22139952133301
12.221399500607554
12.221399479886587
12.22139945917013
12.221399438458159
12.221399417750689
12.221399397047707
12.221399376349218
12.22139935565523
12.221399334965737
12.221399314280722
12.221399293600202
12.221399272924167
12.22139925225263
12.221399231585574
12.221399210922998
12.221399190264915
12.221399169611313
12.221399148962195
12.221399128317556
12.2213991076774
12.221399087041723
12.22139906641052
12.221399045783807
12.221399025161558
12.221399004543802
12.221398983930499
12.221398963321686
12.22139894271734
12.221398922117464
12.22139890152207
12.22139888093114
12.221398860344669
12.221398839762676
12.22139881918516
12.221398798612089
12.221398778043492
12.221398757479369
12.22139873691969
12.221398716364494
12.221398695813745
12.221398675267471
12.221398654725647
12.22139863418828
12.221398613655373
12.22139859312692
12.221398572602924
12.221398552083391
12.221398531568308
12.221398511057675
12.221398490551488
12.221398470049756
12.221398449552478
12.221398429059642
12.221398408571261
12.221398388087318
12.22139836760783
12.221398347132785
12.221398326662182
12.221398306196027
12.221398285734306
12.221398265277033
12.221398244824192
12.2213982243758
12.221398203931841
12.221398183492317
12.22139816305724
12.221398142626587
12.221398122200368
12.221398101778595
12.221398081361244
12.221398060948324
12.221398040539839
12.221398020135778
12.221397999736153
12.22139797934095
12.221397958950183
12.221397938563832
12.221397918181912
12.221397897804412
12.22139787743133
12.221397857062684
12.221397836698449
12.221397816338637
12.221397795983235
12.221397775632267
12.221397755285704
12.221397734943563
12.221397714605834
12.221397694272524
12.221397673943624
12.221397653619132
12.221397633299055
12.221397612983386
12.221397592672133
12.221397572365285
12.221397552062843
12.221397531764806
12.221397511471185
12.221397491181962
12.221397470897138
12.221397450616724
12.221397430340707
12.22139741006909
12.221397389801881
12.22139736953906
12.221397349280641
12.22139732902663
12.221397308777002
12.221397288531776
12.221397268290941
12.2213972480545
12.221397227822449
12.22139720759479
12.221397187371524
12.221397167152649
12.221397146938152
12.221397126728053
12.221397106522337
12.221397086321007
12.221397066124062
12.2213970459315
12.221397025743324
12.221397005559519
12.22139698538011
12.221396965205072
12.221396945034414
12.221396924868133
12.221396904706232
12.221396884548705
12.22139686439555
12.221396844246776
12.22139682410237
12.22139680396234
12.221396783826677
12.221396763695388
12.221396743568473
12.221396723445919
12.221396703327734
12.221396683213918
12.22139666310447
12.221396642999373
12.221396622898654
12.221396602802297
12.221396582710298
12.221396562622655
12.221396542539383
12.221396522460466
12.221396502385907
12.2213964823157
12.22139646224985
12.221396442188356
12.221396422131225
12.221396402078437
12.221396382030006
12.221396361985926
12.221396341946202
12.221396321910813
12.221396301879787
12.221396281853094
12.221396261830758
12.221396241812775
12.221396221799116
12.221396201789817
12.221396181784863
12.221396161784247
12.221396141787974
12.221396121796033
12.221396101808434
12.22139608182518
12.221396061846255
12.221396041871667
12.221396021901425
12.2213960019355
12.221395981973924
12.22139596201667
12.221395942063753
12.221395922115173
12.221395902170913
12.221395882230986
12.221395862295378
12.221395842364108
12.221395822437165
12.221395802514541
12.221395782596241
12.22139576268227
12.221395742772621
12.221395722867282
12.221395702966273
12.221395683069588
12.22139566317722
12.22139564328916
12.221395623405417
12.221395603525995
12.22139558365089
12.2213955637801
12.22139554391362
12.221395524051442
12.221395504193582
12.221395484340043
12.221395464490794
12.221395444645866
12.221395424805246
12.221395404968934
12.221395385136912
12.221395365309208
12.221395345485805
12.221395325666707
12.221395305851914
12.221395286041412
12.221395266235211
12.221395246433321
12.22139522663572
12.221395206842411
12.221395187053398
12.221395167268694
12.221395147488268
12.221395127712148
12.221395107940307
12.221395088172766
12.221395068409524
12.221395048650551
12.221395028895882
12.2213950091455
12.221394989399403
12.221394969657593
12.221394949920064
12.221394930186818
12.22139491045785
12.22139489073318
12.221394871012782
12.221394851296662
12.221394831584822
12.221394811877266
12.22139479217398
12.221394772474978
12.221394752780256
12.22139473308979
12.22139471340361
12.221394693721697
12.22139467404407
12.2213946543707
12.221394634701607
12.22139461503678
12.221394595376221
12.221394575719934
12.221394556067906
12.22139453642015
12.221394516776657
12.221394497137418
12.221394477502452
12.221394457871748
12.221394438245298
12.221394418623118
12.221394399005185
12.221394379391523
12.221394359782114
12.22139434017696
12.221394320576048
12.221394300979407
12.221394281387015
12.221394261798876
12.221394242214984
12.221394222635347
12.221394203059951
12.221394183488819
12.221394163921927
12.221394144359289
12.22139412480089
12.221394105246732
12.221394085696822
12.221394066151158
12.221394046609742
12.221394027072561
12.221394007539608
12.221393988010906
12.221393968486444
12.221393948966218
12.22139392945023
12.22139390993848
12.221393890430962
12.221393870927676
12.221393851428617
12.221393831933808
12.221393812443226
12.221393792956865
12.221393773474734
12.22139375399684
12.221393734523161
12.221393715053718
12.221393695588501
12.221393676127516
12.22139365667074
12.221393637218194
12.221393617769873
12.221393598325767
12.221393578885886
12.221393559450224
12.221393540018774
12.221393520591555
12.221393501168533
12.221393481749745
12.221393462335163
12.221393442924796
12.22139342351864
12.221393404116705
12.221393384718981
12.221393365325449
12.221393345936143
12.22139332655104
12.221393307170143
12.221393287793463
12.221393268420977
12.221393249052696
12.221393229688626
12.221393210328744
12.221393190973082
12.221393171621612
12.221393152274358
12.221393132931277
12.22139311359241
12.221393094257735
12.221393074927256
12.221393055600974
12.221393036278895
12.221393016961002
12.221392997647305
12.2213929783378
12.22139295903248
12.221392939731354
12.221392920434424
12.22139290114167
12.221392881853117
12.221392862568734
12.221392843288548
12.221392824012543
12.221392804740727
12.221392785473089
12.221392766209627
12.221392746950366
12.221392727695266
12.221392708444348
12.221392689197614
12.22139266995506
12.22139265071667
12.221392631482464
12.221392612252442
12.221392593026582
12.221392573804897
12.22139255458738
12.221392535374049
12.22139251616487
12.221392496959865
12.221392477759032
12.221392458562374
12.22139243936987
12.221392420181541
12.221392400997368
12.221392381817358
12.221392362641526
12.221392343469843
12.221392324302329
12.221392305138963
12.221392285979762
12.221392266824724
12.221392247673846
12.22139222852711
12.221392209384545
12.221392190246124
12.221392171111862
12.221392151981757
12.221392132855794
12.221392113733996
12.221392094616336
12.221392075502834
12.221392056393471
12.221392037288263
12.221392018187203
12.221391999090285
12.221391979997508
12.221391960908885
12.221391941824402
12.221391922744052
12.221391903667858
12.221391884595798
12.221391865527876
12.221391846464101
12.221391827404446
12.221391808348937
12.221391789297574
12.221391770250333
12.221391751207227
12.221391732168257
12.22139171313342
12.221391694102714
12.221391675076138
12.221391656053695
12.221391637035381
12.2213916180212
12.221391599011135
12.221391580005193
12.22139156100339
12.221391542005696
12.221391523012137
12.221391504022693
12.22139148503738
12.221391466056177
12.221391447079107
12.221391428106141
12.221391409137304
12.221391390172576
12.22139137121197
12.221391352255477
12.221391333303092
12.221391314354833
12.221391295410685
12.221391276470639
12.221391257534707
12.221391238602896
12.221391219675189
12.22139120075159
12.221391181832091
12.221391162916698
12.221391144005421
12.221391125098249
12.221391106195172
12.2213910872962
12.221391068401333
12.221391049510562
12.221391030623895
12.22139101174133
12.221390992862855
12.22139097398849
12.22139095511821
12.22139093625203
12.221390917389947
12.221390898531956
12.221390879678054
12.221390860828253
12.221390841982537
12.221390823140908
12.221390804303375
12.221390785469932
12.221390766640573
12.221390747815304
12.221390728994116
12.221390710177019

12.221390691364002
12.221390672555067
12.221390653750209
12.22139063494945
12.221390616152764
12.221390597360147
12.22139057857162
12.221390559787176
12.2213905410068
12.221390522230497
12.221390503458283
12.221390484690126
12.221390465926053
12.221390447166055
12.221390428410121
12.221390409658275
12.221390390910475
12.221390372166764
12.221390353427111
12.22139033469152
12.221390315960004
12.221390297232558
12.22139027850917
12.22139025978984
12.221390241074586
12.221390222363388
12.221390203656243
12.22139018495317
12.221390166254158
12.221390147559191
12.221390128868295
12.221390110181453
12.221390091498657
12.221390072819933
12.221390054145248
12.221390035474624
12.221390016808057
12.221389998145535
12.22138997948706
12.221389960832642
12.221389942182268
12.221389923535945
12.221389904893664
12.221389886255436
12.221389867621244
12.221389848991102
12.221389830365007
12.221389811742961
12.221389793124947
12.221389774510984
12.22138975590104
12.22138973729515
12.2213897186933
12.221389700095486
12.221389681501705
12.221389662911962
12.221389644326244
12.221389625744575
12.221389607166937
12.221389588593313
12.221389570023744
12.221389551458193
12.221389532896673
12.221389514339194
12.221389495785727
12.221389477236293
12.221389458690888
12.2213894401495
12.22138942161214
12.221389403078811
12.22138938454949
12.221389366024196
12.22138934750293
12.221389328985678
12.221389310472452
12.221389291963243
12.221389273458039
12.221389254956863
12.2213892364597
12.221389217966554
12.221389199477423
12.221389180992299
12.221389162511189
12.22138914403409
12.221389125561
12.221389107091921
12.221389088626859
12.221389070165788
12.22138905170874
12.22138903325569
12.221389014806645
12.22138899636161
12.221388977920572
12.221388959483543
12.221388941050511
12.221388922621472
12.22138890419644
12.22138888577541
12.221388867358389
12.221388848945349
12.221388830536306
12.221388812131265
12.22138879373022
12.22138877533316
12.221388756940096
12.221388738551031
12.221388720165944
12.221388701784868
12.221388683407765
12.221388665034658
12.221388646665533
12.221388628300403
12.221388609939245
12.221388591582087
12.221388573228907
12.221388554879717
12.221388536534496
12.221388518193272
12.221388499856026
12.221388481522748
12.22138846319346
12.22138844486815
12.221388426546808
12.221388408229457
12.221388389916058
12.221388371606663
12.22138835330123
12.221388334999766
12.221388316702276
12.221388298408762
12.221388280119214
12.22138826183364
12.22138824355203
12.22138822527439
12.221388207000722
12.22138818873101
12.221388170465273
12.221388152203495
12.221388133945679
12.221388115691829
12.221388097441945
12.221388079196029
12.221388060954052
12.22138804271604
12.221388024481993
12.221388006251907
12.221387988025773
12.221387969803589
12.221387951585367
12.221387933371094
12.221387915160781
12.221387896954422
12.221387878752013
12.221387860553548
12.221387842359041
12.221387824168483
12.221387805981864
12.2213877877992
12.221387769620478
12.2213877514457
12.221387733274875
12.221387715107989
12.221387696945047
12.221387678786046
12.221387660630986
12.221387642479868
12.221387624332694
12.221387606189461
12.22138758805015
12.221387569914794
12.221387551783367
12.221387533655868
12.221387515532316
12.221387497412683
12.221387479296995
12.221387461185232
12.221387443077404
12.22138742497351
12.221387406873534
12.221387388777497
12.221387370685381
12.221387352597201
12.221387334512944
12.221387316432605
12.221387298356197
12.221387280283711
12.221387262215146
12.221387244150504
12.221387226089778
12.221387208032978
12.22138718998009
12.221387171931134
12.221387153886088
12.221387135844955
12.22138711780774
12.221387099774445
12.221387081745055
12.221387063719586
12.221387045698032
12.221387027680377
12.22138700966664
12.221386991656818
12.221386973650898
12.221386955648882
12.22138693765078
12.221386919656595
12.221386901666293
12.221386883679916
12.221386865697426
12.221386847718845
12.221386829744173
12.221386811773403
12.221386793806525
12.221386775843547
12.221386757884478
12.221386739929288
12.22138672197801
12.221386704030623
12.221386686087135
12.221386668147536
12.221386650211844
12.221386632280025
12.221386614352113
12.221386596428085
12.221386578507953
12.22138656059171
12.221386542679356
12.221386524770883
12.221386506866304
12.221386488965605
12.221386471068797
12.221386453175876
12.221386435286828
12.221386417401668
12.221386399520396
12.221386381643002
12.221386363769483
12.221386345899845
12.22138632803409
12.221386310172202
12.221386292314211
12.221386274460075
12.221386256609824
12.221386238763445
12.221386220920941
12.221386203082302
12.221386185247544
12.221386167416663
12.221386149589643
12.221386131766495
12.221386113947213
12.221386096131795
12.221386078320254
12.221386060512568
12.221386042708748
12.221386024908808
12.221386007112718
12.221385989320488
12.221385971532127
12.221385953747626
12.22138593596699
12.221385918190204
12.221385900417276
12.221385882648208
12.221385864882995
12.221385847121647
12.221385829364143
12.221385811610507
12.221385793860705
12.221385776114776
12.22138575837268
12.221385740634444
12.221385722900061
12.22138570516952
12.22138568744284
12.22138566971999
12.221385652000995
12.221385634285847
12.221385616574551
12.221385598867089
12.221385581163469
12.221385563463707
12.221385545767763
12.221385528075677
12.221385510387424
12.221385492703016
12.221385475022437
12.221385457345706
12.2213854396728
12.221385422003744
12.221385404338516
12.22138538667712
12.221385369019561
12.221385351365829
12.221385333715936
12.22138531606986
12.22138529842763
12.221385280789223
12.221385263154646
12.221385245523905
12.221385227896972
12.221385210273876
12.221385192654603
12.22138517503916
12.221385157427523
12.22138513981972
12.221385122215745
12.221385104615585
12.221385087019241
12.221385069426724
12.221385051838023
12.22138503425314
12.221385016672079
12.221384999094825
12.221384981521378
12.221384963951763
12.221384946385959
12.22138492882396
12.221384911265762
12.221384893711397
12.221384876160837
12.221384858614082
12.221384841071133
12.221384823532
12.221384805996662
12.221384788465139
12.221384770937414
12.221384753413508
12.221384735893398
12.221384718377085
12.221384700864576
12.221384683355874
12.221384665850957
12.221384648349858
12.22138463085255
12.221384613359048
12.221384595869331
12.221384578383411
12.221384560901289
12.221384543422962
12.221384525948418
12.221384508477684
12.221384491010733
12.221384473547584
12.221384456088208
12.221384438632628
12.221384421180842
12.221384403732845
12.22138438628863
12.2213843688482
12.221384351411553
12.2213843339787
12.221384316549624
12.221384299124333
12.221384281702818
12.221384264285097
12.221384246871144
12.221384229460979
12.221384212054582
12.221384194651977
12.221384177253144
12.22138415985809
12.221384142466805
12.22138412507929
12.221384107695561
12.221384090315604
12.221384072939406
12.221384055567007
12.22138403819835
12.221384020833472
12.221384003472375
12.221383986115033
12.221383968761458
12.221383951411655
12.221383934065614
12.221383916723342
12.221383899384833
12.221383882050082
12.221383864719094
12.221383847391879
12.221383830068419
12.221383812748714
12.221383795432773
12.221383778120593
12.221383760812163
12.221383743507488
12.221383726206577
12.221383708909418
12.221383691616015
12.22138367432636
12.221383657040462
12.221383639758322
12.221383622479928
12.221383605205283
12.221383587934385
12.221383570667236
12.221383553403834
12.221383536144192
12.22138351888828
12.221383501636119
12.221383484387701
12.221383467143026
12.221383449902095
12.221383432664913
12.221383415431472
12.221383398201763
12.221383380975794
12.22138336375356
12.221383346535076
12.221383329320322
12.221383312109312
12.221383294902031
12.221383277698486
12.221383260498675
12.221383243302594
12.221383226110254
12.221383208921633
12.221383191736754
12.221383174555601
12.22138315737818
12.221383140204475
12.221383123034512
12.221383105868274
12.221383088705755
12.221383071546969
12.221383054391898
12.221383037240557
12.221383020092937
12.22138300294905
12.22138298580886
12.221382968672405
12.221382951539667
12.221382934410652
12.221382917285345
12.221382900163766
12.221382883045898

12.221382865931744
12.221382848821312
12.221382831714585
12.22138281461157
12.221382797512277
12.221382780416684
12.221382763324806
12.221382746236646
12.221382729152186
12.221382712071428
12.221382694994391
12.221382677921053
12.221382660851425
12.221382643785498
12.22138262672327
12.221382609664763
12.221382592609944
12.221382575558824
12.22138255851142
12.221382541467703
12.221382524427687
12.22138250739137
12.221382490358764
12.221382473329843
12.221382456304609
12.221382439283078
12.221382422265247
12.221382405251115
12.221382388240658
12.221382371233904
12.221382354230839
12.221382337231463
12.221382320235781
12.221382303243786
12.221382286255478
12.221382269270858
12.221382252289926
12.221382235312676
12.221382218339116
12.221382201369234
12.22138218440304
12.221382167440524
12.221382150481691
12.221382133526546
12.221382116575075
12.221382099627286
12.22138208268317
12.221382065742736
12.221382048805975
12.2213820318729
12.221382014943481
12.22138199801775
12.2213819810957
12.221381964177306
12.221381947262593
12.221381930351551
12.221381913444178
12.221381896540478
12.221381879640443
12.221381862744082
12.221381845851376
12.221381828962352
12.221381812076986
12.221381795195272
12.22138177831725
12.221381761442874
12.221381744572168
12.221381727705122
12.221381710841728
12.221381693981998
12.221381677125928
12.221381660273519
12.221381643424769
12.221381626579676
12.221381609738234
12.221381592900455
12.221381576066324
12.22138155923585
12.221381542409025
12.221381525585858
12.221381508766337
12.221381491950472
12.221381475138248
12.221381458329681
12.22138144152476
12.22138142472349
12.221381407925866
12.221381391131889
12.22138137434155
12.221381357554858
12.221381340771812
12.221381323992407
12.221381307216639
12.221381290444517
12.22138127367603
12.221381256911194
12.221381240149995
12.221381223392425
12.221381206638497
12.22138118988821
12.221381173141557
12.221381156398525
12.221381139659144
12.221381122923393
12.221381106191272
12.22138108946278
12.221381072737923
12.221381056016687
12.221381039299091
12.221381022585122
12.221381005874782
12.221380989168063
12.221380972464985
12.221380955765511
12.221380939069668
12.22138092237745
12.221380905688868
12.221380889003896
12.221380872322541
12.221380855644814
12.221380838970703
12.221380822300215
12.221380805633348
12.221380788970093
12.221380772310447
12.221380755654431
12.221380739002022
12.221380722353226
12.221380705708054
12.221380689066494
12.221380672428536
12.22138065579419
12.221380639163465
12.221380622536335
12.22138060591283
12.221380589292922
12.221380572676624
12.221380556063929
12.221380539454845
12.221380522849362
12.221380506247487
12.221380489649212
12.221380473054543
12.221380456463477
12.221380439876002
12.22138042329214
12.22138040671187
12.221380390135204
12.221380373562141
12.221380356992665
12.221380340426784
12.221380323864494
12.221380307305811
12.221380290750723
12.221380274199223
12.221380257651315
12.221380241106997
12.221380224566273
12.221380208029139
12.221380191495596
12.22138017496564
12.221380158439263
12.221380141916491
12.221380125397289
12.221380108881682
12.221380092369653
12.221380075861214
12.22138005935636
12.221380042855078
12.221380026357389
12.221380009863275
12.22137999337273
12.221379976885782
12.2213799604024
12.22137994392261
12.221379927446385
12.22137991097374
12.221379894504674
12.22137987803918
12.221379861577251
12.221379845118904
12.221379828664132
12.221379812212927
12.22137979576529
12.221379779321227
12.221379762880735
12.221379746443802
12.221379730010444
12.221379713580648
12.221379697154422
12.22137968073177
12.221379664312666
12.221379647897134
12.22137963148517
12.221379615076764
12.221379598671918
12.221379582270623
12.221379565872905
12.221379549478737
12.221379533088127
12.22137951670108
12.221379500317589
12.221379483937648
12.221379467561261
12.221379451188438
12.221379434819163
12.221379418453436
12.22137940209127
12.221379385732645
12.22137936937758
12.22137935302607
12.221379336678108
12.22137932033368
12.221379303992807
12.22137928765549
12.2213792713217
12.221379254991463
12.221379238664781
12.221379222341628
12.221379206022021
12.221379189705964
12.221379173393448
12.221379157084467
12.221379140779025
12.221379124477123
12.221379108178763
12.221379091883936
12.221379075592647
12.221379059304896
12.22137904302068
12.221379026739996
12.221379010462853
12.221378994189232
12.221378977919146
12.221378961652592
12.221378945389567
12.221378929130085
12.221378912874124
12.221378896621687
12.221378880372779
12.221378864127402
12.221378847885543
12.22137883164722
12.221378815412413
12.221378799181132
12.221378782953375
12.221378766729135
12.221378750508425
12.221378734291237
12.221378718077558
12.2213787018674
12.221378685660763
12.221378669457648
12.221378653258048
12.221378637061958
12.221378620869391
12.221378604680337
12.221378588494805
12.221378572312773
12.221378556134251
12.221378539959254
12.221378523787752
12.221378507619773
12.221378491455292
12.22137847529433
12.221378459136872
12.221378442982921
12.221378426832473
12.221378410685526
12.221378394542098
12.221378378402164
12.22137836226574
12.221378346132811
12.221378330003382
12.221378313877457
12.22137829775504
12.221378281636117
12.22137826552069
12.221378249408763
12.221378233300328
12.221378217195396
12.221378201093964
12.221378184996013
12.221378168901564
12.22137815281061
12.221378136723143
12.221378120639171
12.221378104558692
12.221378088481705
12.221378072408195
12.221378056338189
12.22137804027167
12.221378024208617
12.22137800814907
12.221377992093007
12.221377976040431
12.221377959991331
12.221377943945715
12.221377927903585
12.22137791186493
12.221377895829772
12.221377879798087
12.221377863769883
12.221377847745151
12.221377831723906
12.221377815706127
12.221377799691831
12.221377783681001
12.22137776767366
12.221377751669793
12.221377735669396
12.221377719672473
12.221377703679018
12.221377687689039
12.221377671702527
12.22137765571948
12.221377639739913
12.221377623763814
12.221377607791174
12.221377591822007
12.22137757585631
12.221377559894073
12.221377543935292
12.221377527979982
12.221377512028143
12.22137749607976
12.221377480134834
12.221377464193381
12.221377448255371
12.221377432320827
12.221377416389744
12.22137740046212
12.221377384537961
12.22137736861724
12.221377352699992
12.221377336786183
12.221377320875838
12.221377304968946
12.221377289065499
12.221377273165517
12.221377257268976
12.221377241375887
12.221377225486254
12.221377209600051
12.221377193717316
12.22137717783802
12.221377161962165
12.221377146089774
12.221377130220818
12.221377114355302
12.221377098493235
12.221377082634605
12.22137706677942
12.221377050927671
12.22137703507937
12.22137701923451
12.221377003393084
12.2213769875551
12.221376971720554
12.221376955889445
12.221376940061772
12.22137692423753
12.221376908416728
12.22137689259935
12.221376876785415
12.221376860974912
12.221376845167832
12.22137682936419
12.221376813563982
12.221376797767192
12.22137678197384
12.22137676618391
12.221376750397416
12.221376734614342
12.221376718834698
12.221376703058471
12.22137668728568
12.221376671516305
12.221376655750353
12.221376639987817
12.221376624228716
12.221376608473024
12.221376592720748
12.221376576971908
12.221376561226474
12.221376545484457
12.221376529745859
12.221376514010686
12.221376498278918
12.221376482550557
12.221376466825623
12.221376451104094
12.221376435385984
12.221376419671294
12.221376403960006
12.221376388252116
12.22137637254765
12.221376356846585
12.221376341148934
12.221376325454688
12.221376309763846
12.221376294076414
12.221376278392388
12.221376262711761
12.221376247034534
12.221376231360713
12.221376215690293
12.221376200023283
12.22137618435967
12.221376168699459
12.221376153042632
12.221376137389221
12.221376121739201
12.221376106092574
12.221376090449342
12.221376074809514
12.22137605917307
12.221376043540033
12.22137602791038
12.221376012284122
12.221375996661255
12.22137598104178
12.221375965425697
12.221375949812993
12.221375934203685
12.221375918597765
12.221375902995234
12.221375887396093
12.22137587180033
12.221375856207953
12.221375840618958
12.221375825033363
12.221375809451137
12.221375793872289
12.221375778296832
12.221375762724744
12.221375747156046
12.221375731590726
12.221375716028783
12.221375700470213
12.221375684915031
12.221375669363221
12.22137565381478
12.221375638269718
12.221375622728036
12.221375607189712
12.221375591654771
12.221375576123204
12.221375560594996
12.221375545070178
12.221375529548716
12.221375514030624
12.221375498515902
12.221375483004547
12.221375467496559
12.221375451991936
12.221375436490684
12.221375420992791
12.221375405498259
12.221375390007099
12.221375374519297
12.221375359034855
12.221375343553774
12.221375328076043
12.221375312601689
12.221375297130686
12.221375281663045
12.221375266198754
12.221375250737827
12.221375235280249
12.221375219826033
12.221375204375171
12.221375188927656
12.22137517348349
12.221375158042681
12.221375142605234
12.22137512717113
12.221375111740372
12.221375096312967
12.221375080888906
12.221375065468198
12.22137505005084
12.22137503463682
12.221375019226155
12.221375003818826
12.221374988414842
12.221374973014214
12.221374957616915
12.221374942222955
12.221374926832343
12.22137491144508
12.221374896061137
12.22137488068055
12.221374865303291
12.221374849929376
12.221374834558793
12.221374819191553
12.221374803827645
12.22137478846707
12.221374773109835
12.221374757755925
12.221374742405349
12.221374727058107
12.2213747117142
12.221374696373612
12.221374681036362
12.22137466570244
12.221374650371851
12.221374635044581
12.221374619720645
12.221374604400028
12.221374589082735
12.221374573768772
12.221374558458137
12.221374543150818

12.221374527846827
12.22137451254615
12.221374497248796
12.221374481954756
12.221374466664056
12.221374451376654
12.221374436092594
12.221374420811827
12.221374405534387
12.221374390260268
12.221374374989448
12.221374359721954
12.221374344457775
12.221374329196905
12.221374313939345
12.221374298685111
12.221374283434175
12.221374268186544
12.221374252942235
12.221374237701232
12.221374222463531
12.221374207229134
12.221374191998056
12.221374176770285
12.22137416154581
12.221374146324639
12.221374131106776
12.221374115892214
12.22137410068096
12.221374085472997
12.221374070268341
12.221374055066983
12.221374039868927
12.221374024674164
12.221374009482714
12.221373994294554
12.221373979109687
12.221373963928112
12.221373948749834
12.22137393357485
12.221373918403174
12.221373903234774
12.221373888069675
12.221373872907865
12.221373857749352
12.221373842594112
12.221373827442171
12.221373812293521
12.221373797148159
12.221373782006085
12.221373766867297
12.221373751731795
12.221373736599572
12.221373721470634
12.22137370634498
12.221373691222619
12.22137367610353
12.221373660987735
12.22137364587521
12.221373630765962
12.221373615659994
12.221373600557317
12.221373585457911
12.22137357036178
12.22137355526893
12.221373540179355
12.221373525093046
12.22137351001003
12.221373494930267
12.221373479853789
12.221373464780577
12.22137344971065
12.22137343464398
12.221373419580587
12.221373404520465
12.221373389463604
12.221373374410016
12.221373359359694
12.221373344312637
12.22137332926885
12.221373314228323
12.221373299191068
12.221373284157073
12.22137326912634
12.22137325409886
12.221373239074659
12.221373224053714
12.22137320903602
12.221373194021597
12.221373179010428
12.221373164002522
12.221373148997868
12.22137313399647
12.221373118998331
12.221373104003444
12.221373089011815
12.22137307402344
12.221373059038319
12.221373044056437
12.22137302907783
12.221373014102458
12.221372999130338
12.22137298416147
12.221372969195855
12.22137295423348
12.221372939274357
12.221372924318482
12.221372909365854
12.221372894416463
12.22137287947033
12.221372864527437
12.221372849587778
12.221372834651369
12.2213728197182
12.221372804788272
12.221372789861586
12.221372774938141
12.221372760017937
12.221372745100965
12.22137273018723
12.221372715276743
12.221372700369477
12.22137268546546
12.221372670564673
12.221372655667114
12.221372640772795
12.221372625881706
12.221372610993853
12.221372596109235
12.221372581227833
12.22137256634967
12.22137255147474
12.221372536603045
12.221372521734567
12.221372506869317
12.221372492007287
12.22137247714849
12.22137246229292
12.221372447440567
12.221372432591446
12.221372417745538
12.22137240290286
12.221372388063404
12.221372373227165
12.221372358394149
12.221372343564349
12.221372328737766
12.221372313914417
12.22137229909427
12.221372284277356
12.22137226946364
12.221372254653144
12.221372239845866
12.22137222504179
12.221372210240936
12.221372195443298
12.22137218064887
12.22137216585765
12.221372151069643
12.221372136284844
12.221372121503252
12.221372106724877
12.221372091949704
12.221372077177737
12.221372062408982
12.221372047643422
12.221372032881074
12.22137201812192
12.221372003365985
12.221371988613237
12.22137197386371
12.221371959117372
12.221371944374233
12.221371929634302
12.221371914897563
12.221371900164026
12.221371885433692
12.221371870706545
12.221371855982602
12.221371841261854
12.2213718265443
12.221371811829934
12.221371797118767
12.221371782410799
12.221371767706021
12.221371753004428
12.22137173830602
12.221371723610815
12.221371708918804
12.221371694229969
12.221371679544328
12.221371664861874
12.221371650182611
12.221371635506525
12.221371620833628
12.221371606163917
12.221371591497387
12.221371576834045
12.221371562173879
12.22137154751691
12.221371532863104
12.22137151821249
12.22137150356505
12.221371488920797
12.22137147427971
12.22137145964182
12.221371445007081
12.22137143037553
12.221371415747168
12.221371401121969
12.221371386499944
12.221371371881098
12.22137135726542
12.221371342652919
12.221371328043572
12.221371313437421
12.221371298834429
12.221371284234607
12.221371269637954
12.221371255044472
12.221371240454152
12.221371225867001
12.221371211283019
12.221371196702199
12.221371182124537
12.22137116755005
12.221371152978723
12.221371138410566
12.221371123845566
12.221371109283721
12.221371094725038
12.221371080169513
12.22137106561716
12.221371051067955
12.221371036521914
12.221371021979023
12.221371007439293
12.221370992902713
12.221370978369292
12.221370963839028
12.221370949311918
12.22137093478796
12.221370920267155
12.221370905749488
12.221370891234994
12.221370876723649
12.221370862215435
12.221370847710382
12.221370833208477
12.221370818709715
12.2213708042141
12.221370789721636
12.22137077523232
12.221370760746145
12.221370746263117
12.221370731783225
12.22137071730648
12.221370702832875
12.221370688362413
12.221370673895104
12.221370659430923
12.22137064496988
12.221370630511977
12.221370616057204
12.221370601605582
12.221370587157095
12.221370572711741
12.22137055826952
12.221370543830437
12.221370529394488
12.221370514961675
12.221370500531988
12.221370486105442
12.221370471682016
12.221370457261726
12.221370442844561
12.22137042843053
12.22137041401963
12.221370399611859
12.221370385207205
12.221370370805692
12.221370356407293
12.22137034201202
12.221370327619876
12.221370313230853
12.221370298844956
12.221370284462182
12.221370270082524
12.221370255705997
12.221370241332576
12.221370226962286
12.221370212595113
12.221370198231059
12.22137018387012
12.221370169512296
12.22137015515759
12.221370140806005
12.221370126457533
12.221370112112167
12.221370097769931
12.221370083430791
12.221370069094766
12.221370054761856
12.221370040432067
12.221370026105374
12.221370011781792
12.221369997461318
12.221369983143965
12.22136996882971
12.221369954518563
12.221369940210524
12.221369925905597
12.221369911603752
12.221369897305033
12.221369883009409
12.221369868716884
12.221369854427476
12.221369840141154
12.221369825857941
12.221369811577826
12.221369797300804
12.221369783026882
12.221369768756077
12.221369754488345
12.221369740223729
12.2213697259622
12.22136971170377
12.221369697448425
12.221369683196182
12.221369668947029
12.221369654700977
12.221369640458004
12.221369626218134
12.221369611981345
12.221369597747652
12.221369583517047
12.221369569289529
12.221369555065099
12.221369540843767
12.221369526625512
12.221369512410346
12.221369498198268
12.221369483989273
12.221369469783347
12.221369455580522
12.221369441380768
12.221369427184108
12.221369412990521
12.221369398800025
12.221369384612595
12.221369370428256
12.221369356246983
12.221369342068805
12.221369327893692
12.221369313721667
12.221369299552697
12.221369285386821
12.22136927122401
12.221369257064282
12.22136924290762
12.22136922875403
12.221369214603518
12.221369200456076
12.2213691863117
12.221369172170403
12.22136915803217
12.221369143896998
12.221369129764904
12.221369115635872
12.22136910150991
12.221369087387012
12.22136907326718
12.221369059150415
12.221369045036708
12.22136903092607
12.221369016818507
12.221369002713974
12.221368988612527
12.221368974514135
12.2213689604188
12.22136894632652
12.221368932237311
12.221368918151162
12.221368904068061
12.22136888998802
12.221368875911027
12.221368861837096
12.22136884776622
12.221368833698397
12.22136881963363
12.22136880557191
12.221368791513251
12.221368777457634
12.221368763405076
12.22136874935556
12.221368735309103
12.221368721265682
12.221368707225322
12.221368693187994
12.221368679153729
12.221368665122508
12.221368651094325
12.221368637069183
12.2213686230471
12.22136860902805
12.221368595012041
12.221368580999076
12.221368566989163
12.221368552982284
12.221368538978439
12.221368524977644
12.221368510979877
12.221368496985159
12.221368482993473
12.221368469004826
12.221368455019203
12.221368441036619
12.221368427057085
12.221368413080576
12.221368399107101
12.221368385136657
12.22136837116925
12.221368357204874
12.221368343243533
12.22136832928521
12.22136831532992
12.221368301377662
12.221368287428433
12.221368273482232
12.221368259539057
12.221368245598907
12.221368231661785
12.22136821772769
12.221368203796615
12.22136818986856
12.221368175943535
12.22136816202153
12.221368148102552
12.221368134186585
12.221368120273649
12.221368106363723
12.221368092456823
12.221368078552933
12.221368064652074
12.221368050754224
12.221368036859392
12.221368022967575
12.221368009078764
12.221367995192985
12.221367981310214
12.221367967430455
12.221367953553704
12.221367939679963
12.221367925809245
12.221367911941531
12.221367898076831
12.22136788421513
12.221367870356447
12.221367856500768
12.2213678426481
12.221367828798439
12.221367814951783
12.221367801108132
12.22136778726748
12.221367773429845
12.2213677595952
12.221367745763562
12.22136773193492
12.221367718109294
12.221367704286656
12.221367690467021
12.221367676650397
12.221367662836757
12.221367649026128
12.221367635218485
12.221367621413847
12.2213676076122
12.221367593813548
12.221367580017898
12.221367566225238
12.221367552435574
12.221367538648895
12.221367524865222
12.22136751108453
12.22136749730683
12.221367483532124
12.221367469760397
12.221367455991675
12.221367442225924
12.221367428463179
12.221367414703419
12.221367400946635
12.221367387192842
12.221367373442032
12.221367359694208
12.221367345949371
12.221367332207516
12.221367318468639
12.221367304732757
12.22136729099984
12.221367277269907
12.221367263542964
12.221367249818991
12.221367236097999
12.221367222379987

12.221367208664953
12.22136719495289
12.221367181243812
12.2213671675377
12.22136715383457
12.221367140134411
12.221367126437224
12.221367112743017
12.22136709905178
12.221367085363507
12.221367071678221
12.221367057995884
12.221367044316537
12.221367030640147
12.221367016966733
12.221367003296274
12.221366989628795
12.221366975964283
12.221366962302723
12.221366948644143
12.221366934988511
12.221366921335855
12.22136690768617
12.221366894039429
12.221366880395664
12.22136686675485
12.22136685311701
12.221366839482123
12.221366825850192
12.221366812221225
12.221366798595215
12.221366784972155
12.221366771352065
12.221366757734915
12.221366744120736
12.221366730509503
12.221366716901228
12.2213667032959
12.221366689693532
12.221366676094123
12.221366662497656
12.221366648904139
12.221366635313572
12.221366621725963
12.221366608141299
12.221366594559585
12.221366580980806
12.221366567404985
12.221366553832118
12.22136654026219
12.221366526695197
12.221366513131168
12.221366499570072
12.221366486011922
12.221366472456719
12.221366458904443
12.22136644535512
12.221366431808741
12.221366418265298
12.22136640472479
12.221366391187225
12.221366377652593
12.221366364120913
12.22136635059216
12.221366337066339
12.221366323543453
12.221366310023521
12.221366296506503
12.221366282992436
12.221366269481289
12.221366255973079
12.221366242467797
12.221366228965449
12.221366215466029
12.221366201969541
12.221366188475983
12.22136617498536
12.221366161497665
12.221366148012885
12.221366134531035
12.221366121052124
12.221366107576124
12.221366094103047
12.221366080632908
12.221366067165684
12.221366053701388
12.221366040240017
12.22136602678156
12.221366013326026
12.22136599987342
12.221365986423722
12.221365972976947
12.221365959533088
12.221365946092154
12.221365932654138
12.221365919219034
12.221365905786843
12.221365892357571
12.221365878931213
12.221365865507769
12.221365852087247
12.221365838669628
12.221365825254926
12.22136581184313
12.22136579843426
12.221365785028283
12.221365771625221
12.221365758225067
12.221365744827832
12.221365731433492
12.22136571804206
12.22136570465354
12.221365691267922
12.221365677885208
12.221365664505408
12.221365651128506
12.221365637754502
12.221365624383408
12.221365611015221
12.221365597649923
12.22136558428754
12.22136557092805
12.221365557571454
12.22136554421776
12.221365530866969
12.22136551751907
12.221365504174067
12.221365490831966
12.221365477492766
12.22136546415645
12.221365450823033
12.221365437492516
12.221365424164887
12.221365410840146
12.221365397518296
12.221365384199352
12.221365370883289
12.221365357570113
12.221365344259837
12.22136533095244
12.221365317647935
12.221365304346325
12.221365291047594
12.221365277751747
12.221365264458786
12.221365251168713
12.221365237881521
12.221365224597218
12.221365211315797
12.22136519803726
12.221365184761606
12.221365171488829
12.221365158218942
12.22136514495192
12.221365131687799
12.221365118426531
12.221365105168157
12.221365091912658
12.221365078660037
12.221365065410296
12.22136505216343
12.22136503891943
12.221365025678312
12.221365012440067
12.221364999204694
12.221364985972192
12.221364972742562
12.221364959515814
12.221364946291922
12.221364933070907
12.221364919852766
12.221364906637488
12.221364893425084
12.221364880215535
12.221364867008864
12.221364853805056
12.22136484060412
12.22136482740605
12.221364814210826
12.221364801018488
12.221364787829003
12.221364774642378
12.221364761458622
12.221364748277722
12.221364735099684
12.221364721924507
12.221364708752192
12.221364695582745
12.221364682416135
12.221364669252399
12.22136465609151
12.221364642933482
12.221364629778309
12.221364616625996
12.221364603476543
12.221364590329927
12.221364577186174
12.221364564045265
12.221364550907225
12.221364537772018
12.221364524639664
12.221364511510185
12.22136449838353
12.221364485259741
12.221364472138792
12.221364459020682
12.22136444590544
12.221364432793028
12.221364419683463
12.221364406576749
12.221364393472879
12.22136438037185
12.221364367273667
12.221364354178325
12.22136434108583
12.22136432799617
12.221364314909357
12.221364301825387
12.22136428874425
12.221364275665959
12.2213642625905
12.221364249517872
12.221364236448094
12.22136422338115
12.221364210317047
12.221364197255769
12.221364184197332
12.221364171141731
12.221364158088953
12.221364145039018
12.221364131991916
12.221364118947646
12.221364105906199
12.22136409286759
12.221364079831806
12.221364066798856
12.221364053768735
12.221364040741442
12.221364027716977
12.22136401469533
12.221364001676514
12.22136398866053
12.221363975647368
12.22136396263703
12.221363949629517
12.22136393662482
12.221363923622953
12.221363910623907
12.22136389762768
12.221363884634274
12.221363871643689
12.22136385865593
12.221363845670975
12.221363832688855
12.221363819709547
12.22136380673305
12.221363793759377
12.22136378078852
12.221363767820463
12.221363754855238
12.221363741892823
12.221363728933225
12.221363715976434
12.221363703022453
12.221363690071295
12.221363677122932
12.22136366417739
12.221363651234658
12.221363638294738
12.221363625357606
12.221363612423309
12.221363599491799
12.221363586563111
12.221363573637218
12.221363560714142
12.221363547793857
12.221363534876382
12.221363521961718
12.22136350904985
12.221363496140786
12.221363483234523
12.221363470331063
12.2213634574304
12.221363444532535
12.221363431637476
12.221363418745208
12.22136340585575
12.221363392969085
12.22136338008521
12.221363367204145
12.221363354325865
12.221363341450378
12.2213633285777
12.221363315707805
12.221363302840695
12.221363289976404
12.221363277114879
12.221363264256164
12.221363251400222
12.221363238547081
12.221363225696729
12.221363212849164
12.221363200004394
12.2213631871624
12.221363174323205
12.221363161486785
12.22136314865317
12.221363135822328
12.221363122994271
12.221363110169
12.221363097346506
12.221363084526804
12.221363071709888
12.221363058895744
12.221363046084374
12.221363033275798
12.221363020470006
12.221363007666985
12.221362994866748
12.221362982069282
12.221362969274594
12.22136295648269
12.221362943693562
12.221362930907203
12.221362918123626
12.22136290534282
12.221362892564791
12.221362879789531
12.221362867017048
12.221362854247339
12.221362841480385
12.221362828716224
12.221362815954825
12.221362803196195
12.221362790440335
12.221362777687249
12.22136276493692
12.221362752189362
12.22136273944457
12.221362726702552
12.221362713963297
12.221362701226797
12.221362688493066
12.221362675762112
12.221362663033899
12.221362650308471
12.221362637585788
12.221362624865884
12.22136261214872
12.221362599434325
12.221362586722691
12.221362574013819
12.2213625613077
12.22136254860435
12.221362535903738
12.221362523205897
12.221362510510806
12.221362497818479
12.221362485128896
12.221362472442067
12.221362459758
12.221362447076677
12.221362434398117
12.22136242172231
12.221362409049236
12.22136239637893
12.221362383711368
12.221362371046546
12.221362358384495
12.22136234572518
12.221362333068612
12.221362320414789
12.22136230776372
12.221362295115386
12.221362282469814
12.221362269826972
12.22136225718687
12.221362244549528
12.22136223191492
12.221362219283055
12.221362206653929
12.221362194027549
12.221362181403912
12.221362168783005
12.221362156164846
12.221362143549417
12.221362130936736
12.22136211832679
12.221362105719573
12.2213620931151
12.221362080513362
12.221362067914358
12.221362055318092
12.221362042724552
12.221362030133749
12.221362017545689
12.221362004960351
12.221361992377751
12.221361979797871
12.221361967220727
12.221361954646314
12.221361942074632
12.22136192950567
12.22136191693944
12.221361904375959
12.221361891815171
12.221361879257124
12.221361866701804
12.221361854149215
12.221361841599341
12.221361829052189
12.221361816507764
12.22136180396607
12.221361791427077
12.221361778890824
12.221361766357292
12.221361753826473
12.221361741298377
12.221361728772997
12.221361716250346
12.221361703730398
12.221361691213172
12.221361678698669
12.221361666186883
12.22136165367781
12.221361641171445
12.2213616286678
12.221361616166874
12.221361603668653
12.221361591173146
12.221361578680353
12.221361566190264
12.221361553702893
12.22136154121824
12.221361528736283
12.221361516257051
12.221361503780516
12.221361491306691
12.221361478835577
12.221361466367167
12.221361453901459
12.22136144143846
12.22136142897817
12.22136141652058
12.221361404065695
12.221361391613515
12.221361379164037
12.22136136671726
12.221361354273176
12.221361341831805
12.221361329393137
12.22136131695715
12.221361304523882
12.221361292093304
12.221361279665429
12.221361267240244
12.221361254817761
12.221361242397977
12.221361229980882
12.221361217566479
12.221361205154784
12.221361192745773
12.221361180339459
12.221361167935834
12.221361155534904
12.221361143136669
12.221361130741117
12.221361118348268
12.221361105958094
12.221361093570623
12.221361081185826
12.221361068803736
12.221361056424316
12.221361044047585
12.221361031673544
12.221361019302194
12.221361006933515
12.221360994567535
12.22136098220424
12.221360969843614
12.221360957485674
12.221360945130433
12.221360932777863
12.22136092042797
12.221360908080758
12.22136089573623
12.221360883394375
12.2213608710552
12.221360858718718
12.221360846384908
12.221360834053758
12.221360821725295
12.22136080939951
12.221360797076402
12.22136078475597
12.221360772438212
12.221360760123112
12.22136074781071
12.22136073550096
12.221360723193888
12.221360710889487
12.221360698587764
12.2213606862887
12.221360673992313
12.22136066169859
12.221360649407536
12.22136063711915
12.221360624833439
12.22136061255039
12.221360600270009
12.221360587992276
12.221360575717231
12.221360563444833
12.221360551175112
12.221360538908042
12.221360526643641
12.221360514381907
12.221360502122828
12.221360489866415
12.221360477612652
12.221360465361553
12.221360453113116
12.221360440867342
12.22136042862421
12.221360416383755
12.221360404145942
12.221360391910792
12.221360379678302
12.221360367448458
12.22136035522128
12.22136034299674
12.22136033077486
12.221360318555638
12.221360306339065
12.22136029412514
12.221360281913872
12.221360269705249
12.221360257499278
12.221360245295962
12.22136023309528
12.221360220897255
12.221360208701876
12.22136019650915
12.22136018431907
12.221360172131625
12.221360159946835
12.221360147764685
12.221360135585181
12.221360123408319
12.221360111234102
12.221360099062528
12.221360086893592
12.221360074727304
12.22136006256365
12.221360050402645
12.221360038244264
12.221360026088528
12.221360013935444
12.22136000178498
12.22135998963716
12.221359977491984
12.221359965349428
12.221359953209518
12.221359941072247
12.221359928937602
12.221359916805602
12.22135990467622
12.221359892549474
12.221359880425366
12.221359868303896
12.221359856185048
12.221359844068829
12.221359831955237
12.221359819844281
12.221359807735949
12.221359795630246
12.221359783527182
12.221359771426727
12.221359759328909
12.221359747233715
12.221359735141144
12.221359723051195
12.221359710963878
12.221359698879178
12.221359686797102
12.221359674717657
12.221359662640817
12.221359650566612
12.221359638495029

12.221359626426057
12.221359614359706
12.221359602295985
12.221359590234867
12.221359578176376
12.221359566120501
12.221359554067238
12.221359542016593
12.22135952996857
12.221359517923153
12.221359505880356
12.221359493840176
12.221359481802605
12.22135946976764
12.221359457735293
12.221359445705565
12.221359433678433
12.221359421653926
12.221359409632017
12.221359397612733
12.221359385596044
12.221359373581969
12.2213593615705
12.22135934956164
12.22135933755538
12.22135932555173
12.221359313550684
12.22135930155224
12.221359289556405
12.22135927756317
12.221359265572545
12.221359253584527
12.221359241599096
12.22135922961628
12.22135921763605
12.221359205658436
12.221359193683412
12.221359181710984
12.221359169741167
12.22135915777394
12.221359145809313
12.221359133847278
12.221359121887843
12.221359109931006
12.221359097976757
12.221359086025108
12.22135907407605
12.221359062129592
12.221359050185718
12.221359038244444
12.22135902630576
12.22135901436966
12.221359002436163
12.221358990505255
12.221358978576925
12.221358966651197
12.221358954728046
12.221358942807493
12.221358930889515
12.221358918974126
12.221358907061338
12.221358895151122
12.221358883243504
12.22135887133846
12.221358859436002
12.221358847536127
12.221358835638833
12.221358823744128
12.221358811851996
12.221358799962443
12.221358788075479
12.221358776191094
12.221358764309292
12.221358752430062
12.221358740553406
12.221358728679334
12.221358716807847
12.221358704938924
12.221358693072583
12.221358681208827
12.221358669347625
12.22135865748901
12.221358645632963
12.221358633779497
12.221358621928601
12.22135861008028
12.221358598234533
12.221358586391345
12.221358574550733
12.221358562712693
12.221358550877218
12.221358539044312
12.22135852721398
12.22135851538621
12.221358503561014
12.221358491738386
12.22135847991832
12.22135846810082
12.221358456285877
12.22135844447351
12.221358432663703
12.221358420856454
12.221358409051767
12.221358397249649
12.22135838545009
12.221358373653093
12.221358361858655
12.221358350066778
12.221358338277462
12.221358326490705
12.221358314706505
12.221358302924862
12.221358291145776
12.221358279369248
12.221358267595289
12.221358255823862
12.221358244055008
12.221358232288692
12.221358220524934
12.221358208763743
12.22135819700509
12.221358185248993
12.221358173495442
12.221358161744453
12.221358149996007
12.221358138250125
12.22135812650678
12.221358114765984
12.221358103027743
12.221358091292046
12.221358079558888
12.221358067828284
12.221358056100234
12.221358044374709
12.221358032651752
12.22135802093133
12.221358009213448
12.22135799749811
12.221357985785316
12.221357974075067
12.22135796236736
12.221357950662194
12.221357938959564
12.221357927259476
12.221357915561928
12.221357903866918
12.221357892174444
12.221357880484511
12.221357868797119
12.221357857112263
12.221357845429937
12.221357833750156
12.221357822072905
12.221357810398185
12.221357798726
12.221357787056354
12.221357775389233
12.221357763724649
12.221357752062593
12.22135774040307
12.221357728746087
12.221357717091617
12.22135770543969
12.221357693790289
12.22135768214341
12.221357670499064
12.221357658857247
12.221357647217957
12.2213576355812
12.22135762394695
12.221357612315236
12.221357600686055
12.221357589059389
12.221357577435247
12.221357565813621
12.221357554194526
12.221357542577948
12.221357530963898
12.221357519352367
12.22135750774335
12.22135749613686
12.221357484532891
12.221357472931437
12.22135746133249
12.221357449736074
12.221357438142167
12.221357426550782
12.221357414961917
12.221357403375562
12.221357391791726
12.2213573802104
12.221357368631578
12.221357357055286
12.221357345481508
12.221357333910225
12.221357322341465
12.221357310775213
12.22135729921147
12.221357287650244
12.221357276091515
12.221357264535307
12.22135725298159
12.221357241430402
12.221357229881711
12.22135721833553
12.221357206791849
12.221357195250672
12.22135718371202
12.221357172175859
12.22135716064219
12.22135714911104
12.221357137582398
12.221357126056235
12.221357114532584
12.221357103011442
12.221357091492793
12.221357079976652
12.221357068463004
12.221357056951854
12.221357045443208
12.221357033937052
12.221357022433397
12.221357010932241
12.221356999433578
12.22135698793741
12.221356976443744
12.22135696495257
12.221356953463891
12.2213569419777
12.221356930494006
12.221356919012809
12.2213569075341
12.22135689605787
12.221356884584152
12.221356873112908
12.221356861644168
12.221356850177907
12.221356838714136
12.221356827252855
12.221356815794064
12.22135680433776
12.221356792883933
12.221356781432606
12.221356769983746
12.221356758537395
12.221356747093514
12.221356735652115
12.221356724213209
12.221356712776778
12.221356701342835
12.221356689911365
12.221356678482378
12.22135666705587
12.221356655631853
12.221356644210312
12.221356632791242
12.221356621374664
12.221356609960552
12.221356598548928
12.221356587139772
12.221356575733092
12.22135656432889
12.221356552927157
12.221356541527912
12.221356530131134
12.22135651873683
12.221356507344996
12.221356495955643
12.22135648456875
12.221356473184343
12.221356461802396
12.221356450422924
12.22135643904591
12.221356427671381
12.221356416299322
12.221356404929717
12.221356393562594
12.22135638219793
12.221356370835737
12.221356359476006
12.22135634811874
12.221356336763941
12.221356325411607
12.221356314061735
12.221356302714339
12.22135629136939
12.221356280026907
12.221356268686895
12.221356257349335
12.221356246014237
12.221356234681606
12.221356223351432
12.2213562120237
12.221356200698454
12.22135618937565
12.221356178055299
12.221356166737415
12.221356155421981
12.221356144109008
12.221356132798496
12.221356121490436
12.22135611018482
12.221356098881659
12.221356087580958
12.221356076282706
12.221356064986916
12.221356053693569
12.221356042402675
12.221356031114233
12.22135601982824
12.221356008544696
12.221355997263604
12.221355985984955
12.22135597470876
12.221355963435009
12.221355952163705
12.22135594089485
12.221355929628437
12.221355918364468
12.221355907102954
12.221355895843873
12.221355884587227
12.221355873333048
12.2213558620813
12.221355850831994
12.221355839585136
12.221355828340709
12.22135581709873
12.221355805859197
12.221355794622086
12.221355783387423
12.221355772155198
12.221355760925405
12.22135574969806
12.22135573847315
12.221355727250673
12.221355716030635
12.22135570481303
12.221355693597861
12.221355682385127
12.22135567117482
12.221355659966951
12.221355648761515
12.221355637558515
12.221355626357939
12.221355615159803
12.221355603964085
12.221355592770802
12.221355581579948
12.221355570391529
12.221355559205534
12.221355548021968
12.221355536840832
12.221355525662114
12.221355514485834
12.22135550331197
12.221355492140539
12.221355480971527
12.22135546980494
12.221355458640776
12.22135544747904
12.22135543631972
12.221355425162834
12.22135541400835
12.221355402856302
12.22135539170668
12.221355380559464
12.22135536941468
12.221355358272298
12.221355347132347
12.221355335994808
12.221355324859685
12.221355313726992
12.221355302596702
12.22135529146883
12.221355280343378
12.221355269220345
12.221355258099713
12.221355246981501
12.221355235865703
12.221355224752312
12.221355213641342
12.221355202532775
12.221355191426634
12.22135518032289
12.221355169221559
12.221355158122641
12.221355147026125
12.221355135932022
12.221355124840322
12.221355113751034
12.22135510266415
12.221355091579678
12.22135508049761
12.221355069417953
12.221355058340693
12.221355047265838
12.221355036193382
12.221355025123334
12.22135501405569
12.221355002990444
12.221354991927607
12.221354980867162
12.22135496980912
12.221354958753485
12.221354947700258
12.221354936649409
12.221354925600965
12.22135491455492
12.221354903511278
12.221354892470028
12.221354881431173
12.22135487039472
12.221354859360655
12.22135484832899
12.221354837299716
12.221354826272844
12.221354815248358
12.221354804226264
12.221354793206569
12.221354782189257
12.22135477117434
12.221354760161818
12.221354749151677
12.22135473814393
12.221354727138573
12.22135471613562
12.221354705135033
12.221354694136839
12.221354683141037
12.221354672147617
12.221354661156587
12.221354650167932
12.221354639181673
12.2213546281978
12.221354617216301
12.221354606237195
12.22135459526047
12.221354584286123
12.221354573314159
12.221354562344583
12.221354551377376
12.22135454041256
12.221354529450123
12.221354518490065
12.221354507532382
12.221354496577078
12.221354485624156
12.221354474673614
12.221354463725433
12.221354452779645
12.221354441836237
12.221354430895184
12.221354419956514
12.221354409020222
12.221354398086293
12.221354387154749
12.221354376225575
12.221354365298769
12.221354354374336
12.221354343452276
12.22135433253258
12.221354321615271
12.221354310700322
12.221354299787741
12.221354288877523
12.221354277969686
12.221354267064209
12.221354256161101
12.221354245260354
12.221354234361977
12.221354223465966
12.221354212572322
12.221354201681036
12.221354190792116
12.221354179905555
12.22135416902137
12.221354158139542
12.221354147260078
12.221354136382963
12.22135412550822
12.221354114635833
12.22135410376581
12.221354092898148
12.22135408203284
12.221354071169886
12.221354060309295
12.221354049451064
12.221354038595193
12.221354027741663
12.2213540168905
12.22135400604169
12.22135399519523
12.221353984351135
12.221353973509382
12.221353962669992
12.221353951832949
12.221353940998265
12.221353930165922
12.221353919335938
12.221353908508302
12.221353897683018
12.221353886860083
12.221353876039489
12.221353865221257
12.221353854405365
12.221353843591817
12.221353832780627
12.221353821971773
12.221353811165269
12.221353800361117
12.221353789559307
12.221353778759838
12.22135376796271
12.221353757167927
12.221353746375488
12.221353735585398
12.221353724797643
12.22135371401223
12.22135370322916
12.22135369244843
12.221353681670038
12.221353670893992
12.221353660120275
12.221353649348906
12.221353638579867
12.221353627813174
12.221353617048809
12.221353606286783
12.221353595527098
12.221353584769743
12.221353574014724
12.22135356326204
12.22135355251169
12.221353541763666
12.221353531017986
12.221353520274633
12.22135350953361
12.221353498794922
12.221353488058558
12.221353477324536
12.221353466592836
12.221353455863468
12.221353445136431
12.221353434411721
12.221353423689335
12.221353412969277
12.221353402251545
12.221353391536146
12.221353380823064
12.221353370112316
12.221353359403883
12.221353348697782
12.221353337994005
12.221353327292547
12.221353316593413
12.2213533058966
12.221353295202114
12.221353284509942
12.221353273820094
12.221353263132567
12.221353252447352
12.221353241764461
12.221353231083894
12.221353220405643
12.221353209729708
12.221353199056084
12.221353188384793
12.221353177715814
12.221353167049136
12.221353156384788
12.221353145722743
12.221353135063021
12.221353124405619
12.221353113750512
12.221353103097725
12.221353092447256

12.22135308179909
12.221353071153235
12.221353060509701
12.221353049868476
12.221353039229557
12.221353028592953
12.221353017958641
12.221353007326652
12.221352996696966
12.221352986069585
12.221352975444512
12.221352964821751
12.221352954201288
12.221352943583137
12.221352932967287
12.221352922353727
12.221352911742496
12.22135290113355
12.221352890526912
12.221352879922584
12.22135286932054
12.221352858720802
12.221352848123377
12.221352837528245
12.221352826935426
12.221352816344881
12.221352805756645
12.22135279517072
12.221352784587074
12.221352774005732
12.221352763426692
12.221352752849949
12.22135274227549
12.221352731703341
12.221352721133476
12.2213527105659
12.22135270000063
12.221352689437657
12.22135267887696
12.221352668318566
12.221352657762468
12.221352647208649
12.221352636657125
12.221352626107887
12.221352615560948
12.22135260501629
12.221352594473926
12.22135258393385
12.221352573396064
12.221352562860558
12.221352552327346
12.221352541796417
12.22135253126777
12.221352520741414
12.221352510217336
12.221352499695541
12.221352489176041
12.221352478658817
12.221352468143879
12.22135245763122
12.22135244712085
12.22135243661275
12.221352426106938
12.221352415603397
12.221352405102152
12.221352394603182
12.221352384106483
12.22135237361206
12.221352363119925
12.221352352630062
12.221352342142477
12.22135233165717
12.221352321174132
12.221352310693376
12.221352300214894
12.221352289738682
12.221352279264751
12.221352268793083
12.221352258323703
12.221352247856583
12.221352237391736
12.22135222692916
12.221352216468857
12.221352206010828
12.221352195555072
12.221352185101575
12.221352174650354
12.221352164201395
12.221352153754705
12.221352143310288
12.221352132868134
12.22135212242825
12.221352111990628
12.221352101555278
12.221352091122181
12.22135208069136
12.221352070262798
12.221352059836505
12.221352049412472
12.22135203899069
12.221352028571179
12.221352018153931
12.221352007738947
12.221351997326213
12.221351986915744
12.221351976507545
12.221351966101595
12.221351955697909
12.221351945296473
12.221351934897292
12.221351924500377
12.221351914105712
12.221351903713309
12.221351893323162
12.221351882935267
12.221351872549633
12.221351862166248
12.221351851785121
12.221351841406241
12.221351831029613
12.221351820655238
12.221351810283116
12.221351799913245
12.221351789545631
12.22135177918026
12.221351768817144
12.22135175845627
12.221351748097648
12.221351737741271
12.221351727387146
12.22135171703527
12.221351706685637
12.221351696338257
12.221351685993119
12.221351675650226
12.221351665309573
12.221351654971173
12.221351644635018
12.221351634301097
12.221351623969424
12.221351613639987
12.22135160331281
12.221351592987855
12.221351582665148
12.221351572344682
12.221351562026452
12.22135155171047
12.22135154139672
12.221351531085213
12.221351520775945
12.221351510468908
12.221351500164118
12.221351489861554
12.221351479561235
12.221351469263139
12.221351458967291
12.221351448673673
12.221351438382284
12.221351428093142
12.221351417806227
12.221351407521546
12.221351397239093
12.221351386958874
12.221351376680886
12.221351366405125
12.221351356131597
12.221351345860294
12.221351335591232
12.221351325324386
12.221351315059787
12.2213513047974
12.221351294537241
12.22135128427931
12.221351274023617
12.221351263770135
12.221351253518883
12.22135124326986
12.221351233023057
12.221351222778477
12.221351212536126
12.221351202296
12.221351192058096
12.221351181822406
12.221351171588942
12.221351161357697
12.221351151128676
12.221351140901874
12.221351130677293
12.22135112045493
12.221351110234789
12.221351100016859
12.221351089801155
12.221351079587665
12.221351069376388
12.22135105916733
12.221351048960491
12.221351038755857
12.221351028553451
12.221351018353252
12.221351008155274
12.221350997959497
12.22135098776594
12.221350977574593
12.221350967385469
12.221350957198537
12.221350947013839
12.22135093683134
12.221350926651041
12.221350916472971
12.221350906297095
12.221350896123438
12.221350885951988
12.221350875782734
12.221350865615692
12.221350855450867
12.22135084528823
12.221350835127817
12.2213508249696
12.221350814813595
12.221350804659783
12.221350794508188
12.221350784358783
12.221350774211594
12.221350764066598
12.221350753923813
12.221350743783225
12.221350733644833
12.221350723508642
12.221350713374653
12.221350703242871
12.221350693113278
12.221350682985888
12.221350672860696
12.221350662737693
12.2213506526169
12.221350642498297
12.221350632381897
12.221350622267693
12.22135061215568
12.221350602045856
12.221350591938242
12.221350581832795
12.221350571729559
12.22135056162852
12.221350551529671
12.22135054143301
12.221350531338537
12.221350521246267
12.221350511156174
12.221350501068272
12.221350490982577
12.221350480899051
12.22135047081772
12.22135046073858
12.221350450661626
12.221350440586864
12.221350430514274
12.221350420443889
12.22135041037568
12.221350400309651
12.221350390245814
12.221350380184159
12.221350370124695
12.22135036006741
12.221350350012301
12.221350339959377
12.221350329908645
12.221350319860083
12.221350309813708
12.221350299769512
12.221350289727493
12.221350279687657
12.221350269650001
12.22135025961453
12.221350249581228
12.221350239550093
12.22135022952115
12.221350219494385
12.221350209469794
12.22135019944738
12.221350189427131
12.22135017940907
12.221350169393178
12.22135015937946
12.221350149367924
12.22135013935854
12.22135012935134
12.221350119346313
12.221350109343462
12.221350099342773
12.221350089344256
12.221350079347912
12.22135006935374
12.22135005936174
12.221350049371901
12.22135003938423
12.221350029398733
12.221350019415402
12.221350009434245
12.22134999945524
12.22134998947841
12.221349979503735
12.221349969531227
12.221349959560895
12.221349949592726
12.221349939626712
12.221349929662859
12.221349919701185
12.221349909741654
12.221349899784292
12.221349889829092
12.221349879876058
12.22134986992518
12.221349859976453
12.221349850029888
12.22134984008549
12.221349830143254
12.221349820203162
12.22134981026524
12.221349800329472
12.22134979039586
12.2213497804644
12.221349770535094
12.221349760607952
12.22134975068296
12.221349740760123
12.221349730839432
12.221349720920905
12.22134971100453
12.221349701090299
12.221349691178228
12.221349681268302
12.221349671360537
12.22134966145491
12.221349651551439
12.221349641650116
12.221349631750947
12.22134962185392
12.221349611959049
12.221349602066311
12.221349592175741
12.221349582287298
12.221349572401017
12.221349562516869
12.221349552634877
12.221349542755023
12.221349532877314
12.221349523001757
12.221349513128335
12.221349503257052
12.221349493387923
12.22134948352092
12.221349473656076
12.221349463793368
12.221349453932799
12.22134944407437
12.221349434218082
12.221349424363934
12.22134941451192
12.221349404662044
12.221349394814313
12.221349384968716
12.221349375125252
12.221349365283928
12.22134935544474
12.221349345607686
12.22134933577277
12.221349325939988
12.221349316109333
12.221349306280828
12.221349296454438
12.221349286630192
12.221349276808079
12.2213492669881
12.221349257170248
12.221349247354526
12.221349237540926
12.221349227729462
12.22134921792014
12.22134920811294
12.22134919830786
12.221349188504924
12.221349178704099
12.221349168905402
12.221349159108843
12.221349149314403
12.22134913952209
12.221349129731903
12.221349119943845
12.221349110157904
12.221349100374091
12.221349090592405
12.221349080812837
12.221349071035391
12.221349061260069
12.221349051486872
12.221349041715794
12.221349031946835
12.221349022179998
12.221349012415278
12.221349002652683
12.221348992892196
12.22134898313384
12.221348973377593
12.221348963623472
12.221348953871463
12.221348944121575
12.2213489343738
12.221348924628138
12.221348914884592
12.221348905143167
12.221348895403848
12.221348885666654
12.221348875931563
12.221348866198584
12.221348856467722
12.221348846738975
12.221348837012336
12.221348827287802
12.22134881756539
12.221348807845086
12.22134879812689
12.221348788410799
12.221348778696818
12.221348768984946
12.221348759275182
12.22134874956753
12.221348739861982
12.221348730158539
12.221348720457204
12.22134871075797
12.221348701060856
12.221348691365835
12.22134868167292
12.221348671982106
12.221348662293403
12.221348652606794
12.221348642922296
12.221348633239895
12.221348623559596
12.221348613881396
12.221348604205296
12.221348594531298
12.221348584859408

12.221348575189607
12.221348565521911
12.221348555856302
12.221348546192802
12.221348536531396
12.221348526872086
12.221348517214876
12.22134850755976
12.221348497906744
12.221348488255812
12.22134847860698
12.221348468960242
12.221348459315601
12.221348449673053
12.221348440032601
12.221348430394233
12.221348420757955
12.221348411123783
12.221348401491687
12.221348391861698
12.221348382233785
12.221348372607965
12.221348362984239
12.221348353362595
12.221348343743045
12.22134833412558
12.221348324510206
12.221348314896915
12.221348305285716
12.221348295676595
12.22134828606956
12.221348276464617
12.221348266861753
12.221348257260974
12.221348247662283
12.221348238065671
12.221348228471147
12.221348218878695
12.221348209288339
12.221348199700056
12.22134819011386
12.22134818052974
12.22134817094769
12.22134816136774
12.221348151789858
12.221348142214058
12.221348132640328
12.221348123068696
12.221348113499117
12.221348103931632
12.221348094366222
12.221348084802875
12.221348075241618
12.221348065682434
12.22134805612532
12.221348046570288
12.221348037017322
12.221348027466423
12.221348017917606
12.22134800837087
12.221347998826193
12.221347989283593
12.221347979743067
12.221347970204604
12.221347960668217
12.221347951133895
12.221347941601648
12.221347932071462
12.221347922543357
12.221347913017311
12.221347903493335
12.221347893971421
12.221347884451593
12.22134787493381
12.221347865418094
12.22134785590446
12.22134784639287
12.221347836883355
12.221347827375908
12.221347817870514
12.221347808367199
12.221347798865935
12.221347789366728
12.221347779869596
12.221347770374521
12.221347760881498
12.22134775139055
12.221347741901651
12.221347732414815
12.221347722930036
12.221347713447313
12.221347703966655
12.221347694488053
12.221347685011509
12.221347675537022
12.221347666064597
12.221347656594222
12.221347647125901
12.221347637659637
12.221347628195426
12.221347618733265
12.221347609273167
12.221347599815115
12.221347590359118
12.22134758090518
12.221347571453286
12.221347562003436
12.221347552555653
12.221347543109918
12.221347533666233
12.221347524224587
12.221347514785
12.221347505347456
12.22134749591197
12.221347486478518
12.221347477047123
12.221347467617775
12.221347458190474
12.221347448765215
12.221347439342006
12.221347429920838
12.221347420501713
12.221347411084638
12.221347401669608
12.22134739225662
12.221347382845671
12.221347373436766
12.22134736402991
12.221347354625085
12.221347345222314
12.221347335821573
12.221347326422885
12.221347317026224
12.2213473076316
12.221347298239028
12.22134728884848
12.221347279459977
12.221347270073506
12.221347260689091
12.221347251306698
12.221347241926342
12.221347232548027
12.221347223171746
12.221347213797502
12.22134720442529
12.22134719505511
12.22134718568697
12.221347176320858
12.221347166956782
12.221347157594735
12.22134714823472
12.22134713887674
12.221347129520787
12.221347120166866
12.221347110814973
12.22134710146512
12.221347092117291
12.221347082771482
12.22134707342771
12.22134706408597
12.221347054746255
12.221347045408558
12.221347036072899
12.221347026739265
12.221347017407655
12.221347008078064
12.221346998750498
12.221346989424962
12.221346980101455
12.221346970779969
12.221346961460492
12.221346952143056
12.221346942827633
12.221346933514239
12.221346924202864
12.221346914893502
12.221346905586168
12.221346896280856
12.221346886977562
12.221346877676288
12.22134686837703
12.221346859079791
12.221346849784574
12.221346840491362
12.221346831200178
12.221346821911
12.221346812623857
12.221346803338722
12.221346794055599
12.221346784774486
12.221346775495395
12.221346766218312
12.221346756943246
12.2213467476702
12.221346738399156
12.221346729130133
12.221346719863114
12.221346710598105
12.221346701335122
12.221346692074132
12.221346682815152
12.221346673558203
12.221346664303235
12.221346655050297
12.221346645799354
12.221346636550425
12.221346627303504
12.221346618058591
12.221346608815688
12.221346599574783
12.221346590335889
12.221346581098993
12.221346571864107
12.221346562631233
12.22134655340035
12.221346544171482
12.221346534944603
12.221346525719737
12.221346516496874
12.221346507276005
12.221346498057144
12.221346488840284
12.221346479625426
12.221346470412563
12.221346461201698
12.221346451992845
12.221346442785977
12.221346433581108
12.221346424378236
12.22134641517737
12.221346405978503
12.221346396781623
12.221346387586744
12.221346378393857
12.221346369202964
12.221346360014076
12.221346350827167
12.221346341642278
12.221346332459355
12.221346323278437
12.22134631409951
12.221346304922573
12.22134629574763
12.221346286574677
12.221346277403724
12.221346268234756
12.221346259067774
12.221346249902782
12.221346240739779
12.221346231578778
12.22134622241975
12.221346213262716
12.221346204107665
12.22134619495461
12.221346185803535
12.221346176654448
12.221346167507349
12.22134615836223
12.221346149219094
12.221346140077944
12.221346130938793
12.221346121801604
12.221346112666414
12.221346103533193
12.221346094401955
12.221346085272705
12.221346076145446
12.221346067020159
12.221346057896856
12.221346048775521
12.22134603965618
12.22134603053882
12.221346021423429
12.221346012310018
12.221346003198583
12.221345994089138
12.221345984981653
12.221345975876154
12.22134596677263
12.221345957671081
12.221345948571512
12.221345939473911
12.221345930378295
12.221345921284643
12.22134591219297
12.221345903103273
12.221345894015538
12.221345884929779
12.221345875846
12.221345866764198
12.221345857684351
12.22134584860647
12.221345839530574
12.221345830456647
12.221345821384686
12.221345812314699
12.221345803246674
12.221345794180616
12.221345785116537
12.221345776054406
12.221345766994265
12.221345757936074
12.221345748879854
12.221345739825594
12.221345730773306
12.221345721722988
12.221345712674617
12.221345703628227
12.221345694583794
12.221345685541328
12.221345676500816
12.22134566746227
12.22134565842569
12.221345649391068
12.221345640358413
12.221345631327715
12.22134562229897
12.221345613272188
12.22134560424737
12.221345595224506
12.221345586203599
12.221345577184652
12.221345568167667
12.221345559152633
12.221345550139562
12.221345541128446
12.221345532119296
12.221345523112076
12.22134551410682
12.221345505103526
12.221345496102181
12.2213454871028
12.221345478105357
12.221345469109874
12.22134546011634
12.221345451124764
12.221345442135139
12.221345433147453
12.221345424161731
12.221345415177963
12.221345406196138
12.221345397216263
12.221345388238333
12.221345379262356
12.221345370288327
12.221345361316253
12.221345352346109
12.221345343377926
12.221345334411687
12.221345325447384
12.221345316485035
12.22134530752464
12.221345298566174
12.221345289609653
12.221345280655086
12.221345271702463
12.221345262751779
12.22134525380304
12.221345244856236
12.221345235911377
12.221345226968461
12.221345218027494
12.221345209088463
12.221345200151356
12.221345191216209
12.221345182282997
12.22134517335172
12.221345164422381
12.221345155494987
12.221345146569524
12.221345137645995
12.221345128724415
12.221345119804758
12.221345110887041
12.221345101971265
12.221345093057423
12.221345084145513
12.221345075235536
12.221345066327492
12.221345057421392
12.221345048517216
12.221345039614969
12.221345030714657
12.221345021816283
12.22134501291984
12.221345004025322
12.22134499513273
12.221344986242077
12.221344977353352
12.22134496846656
12.221344959581689
12.221344950698748
12.22134494181774
12.221344932938662
12.221344924061498
12.221344915186274
12.221344906312972
12.221344897441591
12.22134488857214
12.221344879704617
12.22134487083901
12.22134486197534
12.22134485311358
12.221344844253753
12.221344835395847
12.22134482653986
12.221344817685804
12.221344808833663
12.221344799983443
12.22134479113514
12.221344782288762
12.22134477344431
12.221344764601769
12.221344755761153
12.221344746922453
12.221344738085662
12.221344729250808
12.221344720417857
12.221344711586832
12.221344702757717
12.221344693930522
12.221344685105239
12.221344676281879
12.221344667460428
12.221344658640895
12.221344649823275
12.22134464100757
12.221344632193782
12.221344623381896
12.221344614571935
12.221344605763873
12.221344596957733
12.221344588153498
12.221344579351177
12.221344570550762
12.221344561752264
12.221344552955681
12.221344544160992
12.221344535368223
12.221344526577365
12.221344517788404
12.221344509001348
12.221344500216217
12.221344491432973
12.22134448265165
12.221344473872225
12.221344465094715
12.221344456319098
12.221344447545393
12.221344438773599
12.221344430003692
12.221344421235697
12.221344412469609
12.221344403705412
12.221344394943129
12.221344386182745
12.221344377424261
12.221344368667678
12.221344359912992
12.221344351160214
12.221344342409328
12.221344333660348
12.221344324913266
12.221344316168079
12.221344307424797
12.221344298683404
12.221344289943913
12.22134428120632
12.221344272470619
12.221344263736817
12.221344255004908
12.221344246274896
12.221344237546784
12.221344228820557
12.221344220096233
12.221344211373792
12.221344202653254
12.2213441939346

12.221344185217845
12.221344176502983
12.22134416779001
12.221344159078923
12.221344150369738
12.221344141662431
12.22134413295702
12.221344124253505
12.22134411555187
12.221344106852134
12.22134409815428
12.221344089458311
12.221344080764224
12.221344072072036
12.221344063381727
12.221344054693303
12.221344046006774
12.221344037322119
12.221344028639349
12.221344019958478
12.22134401127948
12.22134400260236
12.221343993927144
12.221343985253796
12.221343976582332
12.221343967912748
12.221343959245049
12.221343950579241
12.221343941915306
12.22134393325324
12.221343924593068
12.221343915934767
12.221343907278348
12.221343898623816
12.221343889971157
12.221343881320374
12.221343872671463
12.22134386402444
12.221343855379295
12.221343846736016
12.22134383809462
12.221343829455101
12.22134382081745
12.221343812181681
12.221343803547777
12.221343794915757
12.221343786285612
12.22134377765732
12.221343769030927
12.221343760406397
12.221343751783733
12.22134374316294
12.221343734544027
12.22134372592698
12.221343717311795
12.221343708698498
12.221343700087065
12.221343691477488
12.22134368286979
12.221343674263958
12.221343665659996
12.221343657057902
12.22134364845767
12.22134363985931
12.221343631262814
12.221343622668185
12.221343614075423
12.221343605484527
12.221343596895482
12.221343588308311
12.221343579723015
12.221343571139567
12.221343562557989
12.221343553978267
12.221343545400407
12.221343536824422
12.22134352825029
12.221343519678019
12.221343511107607
12.22134350253906
12.221343493972364
12.221343485407532
12.221343476844567
12.22134346828346
12.221343459724196
12.221343451166794
12.221343442611259
12.221343434057578
12.221343425505752
12.221343416955785
12.221343408407668
12.221343399861398
12.221343391316998
12.221343382774439
12.22134337423375
12.221343365694905
12.221343357157922
12.221343348622792
12.221343340089502
12.221343331558073
12.221343323028492
12.221343314500768
12.221343305974885
12.22134329745085
12.22134328892868
12.221343280408359
12.221343271889886
12.221343263373246
12.221343254858473
12.221343246345542
12.221343237834455
12.221343229325216
12.22134322081782
12.22134321231228
12.221343203808587
12.221343195306735
12.22134318680673
12.221343178308565
12.221343169812249
12.221343161317778
12.22134315282515
12.221343144334357
12.22134313584542
12.221343127358319
12.221343118873063
12.221343110389643
12.221343101908065
12.22134309342833
12.221343084950444
12.221343076474385
12.221343068000174
12.221343059527806
12.221343051057262
12.221343042588568
12.221343034121707
12.22134302565668
12.2213430171935
12.22134300873215
12.221343000272643
12.221342991814975
12.22134298335913
12.221342974905124
12.221342966452953
12.22134295800263
12.221342949554124
12.221342941107462
12.221342932662624
12.221342924219625
12.221342915778457
12.221342907339121
12.22134289890162
12.221342890465941
12.221342882032108
12.221342873600097
12.221342865169916
12.221342856741565
12.221342848315038
12.22134283989035
12.221342831467483
12.221342823046443
12.221342814627235
12.221342806209858
12.221342797794309
12.221342789380572
12.221342780968682
12.221342772558605
12.221342764150354
12.22134275574393
12.221342747339328
12.221342738936553
12.221342730535603
12.221342722136471
12.221342713739174
12.221342705343693
12.221342696950025
12.221342688558185
12.221342680168165
12.221342671779972
12.2213426633936
12.221342655009035
12.221342646626303
12.221342638245385
12.221342629866301
12.22134262148901
12.221342613113555
12.221342604739904
12.221342596368086
12.221342587998075
12.221342579629889
12.221342571263511
12.221342562898949
12.221342554536204
12.221342546175283
12.22134253781616
12.221342529458866
12.221342521103379
12.221342512749702
12.22134250439785
12.221342496047805
12.221342487699571
12.221342479353154
12.221342471008537
12.221342462665739
12.221342454324747
12.221342445985577
12.221342437648206
12.221342429312646
12.221342420978905
12.221342412646957
12.221342404316825
12.221342395988506
12.221342387661991
12.221342379337283
12.22134237101438
12.22134236269328
12.221342354373991
12.221342346056511
12.221342337740827
12.22134232942696
12.221342321114887
12.221342312804623
12.22134230449616
12.221342296189505
12.221342287884653
12.221342279581606
12.221342271280351
12.221342262980896
12.221342254683247
12.221342246387408
12.221342238093367
12.221342229801117
12.221342221510671
12.22134221322202
12.22134220493518
12.22134219665013
12.221342188366881
12.221342180085431
12.221342171805771
12.22134216352792
12.221342155251856
12.221342146977596
12.221342138705126
12.22134213043445
12.221342122165566
12.221342113898492
12.2213421056332
12.2213420973697
12.221342089108006
12.221342080848098
12.221342072589984
12.22134206433366
12.221342056079125
12.221342047826393
12.221342039575442
12.221342031326285
12.221342023078915
12.221342014833347
12.221342006589552
12.221341998347555
12.221341990107348
12.221341981868928
12.221341973632295
12.221341965397448
12.221341957164393
12.22134194893313
12.22134194070364
12.22134193247594
12.221341924250032
12.221341916025905
12.221341907803568
12.221341899583006
12.22134189136424
12.221341883147252
12.221341874932044
12.221341866718625
12.221341858506982
12.221341850297131
12.221341842089055
12.221341833882757
12.22134182567825
12.22134181747551
12.221341809274572
12.221341801075393
12.221341792878006
12.221341784682387
12.221341776488558
12.221341768296496
12.221341760106224
12.22134175191773
12.221341743731008
12.221341735546062
12.221341727362892
12.221341719181497
12.22134171100188
12.221341702824041
12.22134169464798
12.221341686473695
12.221341678301174
12.221341670130425
12.221341661961453
12.221341653794259
12.22134164562884
12.221341637465185
12.221341629303303
12.221341621143198
12.221341612984867
12.221341604828282
12.22134159667349
12.22134158852047
12.221341580369208
12.221341572219728
12.221341564072
12.221341555926061
12.221341547781872
12.221341539639466
12.221341531498817
12.22134152335993
12.221341515222816
12.221341507087473
12.2213414989539
12.221341490822073
12.221341482692019
12.221341474563738
12.221341466437208
12.22134145831246
12.221341450189458
12.221341442068228
12.221341433948757
12.221341425831051
12.221341417715111
12.221341409600926
12.2213414014885
12.221341393377841
12.221341385268934
12.221341377161798
12.221341369056418
12.221341360952785
12.22134135285093
12.221341344750831
12.221341336652477
12.221341328555889
12.22134132046106
12.221341312367977
12.221341304276665
12.221341296187102
12.2213412880993
12.221341280013247
12.221341271928958
12.221341263846416
12.221341255765614
12.221341247686583
12.22134123960931
12.221341231533781
12.221341223460012
12.221341215387993
12.221341207317723
12.221341199249204
12.221341191182436
12.221341183117424
12.221341175054159
12.221341166992646
12.221341158932882
12.221341150874869
12.221341142818602
12.221341134764073
12.221341126711307
12.221341118660291
12.221341110611013
12.221341102563485
12.22134109451771
12.221341086473668
12.221341078431383
12.221341070390842
12.221341062352042
12.221341054314992
12.221341046279685
12.221341038246115
12.221341030214292
12.221341022184218
12.221341014155886
12.221341006129297
12.221340998104445
12.22134099008134
12.221340982059965
12.22134097404034
12.221340966022455
12.22134095800632
12.221340949991916
12.221340941979243
12.22134093396832
12.221340925959135
12.221340917951686
12.221340909945976
12.221340901941998
12.221340893939763
12.221340885939265
12.2213408779405
12.221340869943473
12.22134086194818
12.22134085395463
12.221340845962816
12.221340837972724
12.221340829984369
12.22134082199775
12.221340814012867
12.221340806029717
12.221340798048299
12.221340790068611
12.221340782090657
12.22134077411444
12.221340766139939
12.221340758167187
12.221340750196152
12.221340742226857
12.221340734259282
12.221340726293443
12.221340718329335
12.221340710366949
12.221340702406293
12.221340694447369
12.22134068649017
12.221340678534691
12.221340670580947
12.22134066262893
12.221340654678642
12.221340646730061
12.221340638783229
12.221340630838107
12.221340622894717
12.221340614953043
12.2213406070131
12.221340599074878
12.221340591138375
12.221340583203604
12.221340575270547
12.22134056733921
12.221340559409603
12.221340551481717
12.221340543555547
12.221340535631088
12.221340527708362
12.221340519787358
12.221340511868066
12.221340503950493
12.221340496034646
12.221340488120507
12.221340480208097
12.22134047229739
12.221340464388415
12.221340456481142
12.22134044857559
12.22134044067176
12.221340432769644
12.22134042486923
12.221340416970548
12.221340409073571
12.221340401178319
12.221340393284763
12.221340385392937
12.22134037750281
12.221340369614415
12.221340361727716
12.22134035384273
12.22134034595946
12.221340338077896
12.221340330198043
12.221340322319904
12.22134031444347
12.221340306568756
12.22134029869574
12.221340290824442
12.221340282954852
12.221340275086963
12.221340267220787
12.221340259356305
12.221340251493546
12.221340243632495
12.221340235773141
12.2213402279155
12.22134022005955
12.22134021220532

12.221340204352785
12.22134019650196
12.221340188652844
12.221340180805424
12.221340172959707
12.221340165115691
12.221340157273389
12.221340149432775
12.221340141593872
12.221340133756664
12.221340125921168
12.221340118087369
12.221340110255266
12.221340102424858
12.221340094596163
12.221340086769152
12.221340078943857
12.221340071120249
12.22134006329834
12.221340055478132
12.22134004765961
12.221340039842795
12.221340032027687
12.221340024214259
12.221340016402532
12.221340008592502
12.221340000784165
12.22133999297752
12.221339985172573
12.221339977369315
12.221339969567772
12.221339961767887
12.221339953969728
12.22133994617324
12.221339938378453
12.221339930585357
12.221339922793952
12.221339915004235
12.221339907216217
12.22133989942988
12.22133989164524
12.221339883862287
12.221339876081025
12.22133986830144
12.221339860523559
12.221339852747372
12.221339844972855
12.221339837200034
12.221339829428892
12.221339821659447
12.221339813891687
12.221339806125599
12.221339798361214
12.221339790598517
12.221339782837482
12.221339775078153
12.221339767320497
12.221339759564525
12.221339751810246
12.221339744057637
12.221339736306724
12.221339728557487
12.221339720809926
12.221339713064058
12.221339705319862
12.22133969757735
12.221339689836524
12.221339682097373
12.221339674359895
12.221339666624107
12.221339658889997
12.22133965115757
12.22133964342681
12.221339635697733
12.221339627970327
12.221339620244612
12.221339612520564
12.221339604798183
12.221339597077503
12.22133958935848
12.221339581641134
12.221339573925468
12.221339566211478
12.221339558499158
12.22133955078851
12.221339543079543
12.221339535372245
12.221339527666617
12.221339519962665
12.221339512260384
12.221339504559786
12.221339496860844
12.22133948916358
12.22133948146798
12.22133947377406
12.221339466081801
12.221339458391213
12.221339450702304
12.221339443015056
12.221339435329465
12.221339427645557
12.221339419963318
12.22133941228275
12.221339404603837
12.221339396926592
12.22133938925102
12.221339381577106
12.221339373904865
12.221339366234286
12.221339358565373
12.221339350898129
12.221339343232536
12.22133933556862
12.221339327906358
12.221339320245765
12.22133931258683
12.221339304929563
12.221339297273962
12.221339289620015
12.221339281967722
12.221339274317106
12.221339266668139
12.221339259020839
12.2213392513752
12.221339243731212
12.221339236088884
12.22133922844822
12.221339220809208
12.221339213171866
12.221339205536172
12.221339197902136
12.22133919026976
12.221339182639033
12.221339175009968
12.221339167382558
12.22133915975681
12.221339152132707
12.221339144510265
12.221339136889483
12.221339129270346
12.221339121652862
12.221339114037034
12.221339106422862
12.221339098810345
12.22133909119947
12.221339083590255
12.221339075982684
12.221339068376766
12.221339060772511
12.221339053169892
12.221339045568929
12.221339037969614
12.221339030371947
12.221339022775936
12.221339015181574
12.221339007588847
12.221338999997773
12.22133899240836
12.221338984820578
12.221338977234453
12.221338969649972
12.221338962067136
12.221338954485953
12.221338946906405
12.221338939328497
12.221338931752246
12.221338924177635
12.221338916604674
12.22133890903335
12.221338901463666
12.221338893895632
12.22133888632924
12.221338878764493
12.221338871201379
12.221338863639913
12.22133885608008
12.221338848521897
12.221338840965355
12.221338833410444
12.221338825857183
12.221338818305561
12.221338810755574
12.221338803207225
12.221338795660516
12.221338788115444
12.221338780572006
12.221338773030203
12.221338765490053
12.221338757951525
12.221338750414642
12.221338742879386
12.221338735345777
12.221338727813796
12.221338720283448
12.22133871275473
12.221338705227657
12.221338697702206
12.221338690178403
12.221338682656228
12.221338675135685
12.221338667616767
12.221338660099484
12.22133865258384
12.221338645069826
12.221338637557437
12.221338630046684
12.221338622537557
12.221338615030062
12.221338607524196
12.221338600019955
12.221338592517352
12.221338585016369
12.22133857751702
12.221338570019295
12.221338562523197
12.221338555028725
12.221338547535883
12.221338540044664
12.221338532555077
12.221338525067111
12.22133851758077
12.22133851009606
12.221338502612964
12.221338495131501
12.221338487651655
12.221338480173438
12.221338472696841
12.221338465221868
12.221338457748514
12.221338450276786
12.221338442806687
12.221338435338195
12.22133842787134
12.22133842040609
12.221338412942465
12.22133840548046
12.22133839802008
12.221338390561307
12.22133838310417
12.22133837564864
12.221338368194731
12.221338360742438
12.221338353291769
12.221338345842707
12.221338338395269
12.221338330949454
12.22133832350524
12.221338316062644
12.221338308621677
12.221338301182307
12.221338293744571
12.221338286308438
12.221338278873912
12.22133827144102
12.22133826400972
12.221338256580047
12.221338249151978
12.221338241725523
12.221338234300681
12.221338226877453
12.221338219455836
12.221338212035823
12.221338204617428
12.221338197200637
12.221338189785463
12.221338182371893
12.221338174959936
12.221338167549582
12.22133816014085
12.221338152733715
12.221338145328188
12.221338137924265
12.221338130521954
12.22133812312126
12.221338115722164
12.221338108324659
12.221338100928772
12.221338093534495
12.221338086141824
12.221338078750746
12.221338071361279
12.221338063973414
12.22133805658716
12.221338049202497
12.22133804181944
12.221338034437995
12.221338027058145
12.2213380196799
12.221338012303246
12.2213380049282
12.221337997554754
12.221337990182906
12.22133798281267
12.221337975444023
12.221337968076977
12.221337960711528
12.221337953347685
12.221337945985438
12.221337938624774
12.22133793126573
12.221337923908273
12.221337916552406
12.221337909198144
12.221337901845482
12.221337894494408
12.221337887144939
12.22133787979705
12.22133787245077
12.221337865106072
12.221337857762975
12.22133785042148
12.221337843081571
12.221337835743252
12.221337828406527
12.221337821071396
12.221337813737856
12.221337806405906
12.22133779907555
12.221337791746793
12.221337784419612
12.221337777094035
12.221337769770045
12.221337762447636
12.221337755126815
12.221337747807599
12.221337740489957
12.221337733173906
12.221337725859442
12.221337718546568
12.22133771123529
12.221337703925586
12.221337696617468
12.221337689310946
12.221337682006011
12.22133767470265
12.221337667400883
12.221337660100689
12.2213376528021
12.221337645505079
12.221337638209643
12.221337630915801
12.221337623623535
12.221337616332846
12.221337609043752
12.221337601756224
12.22133759447029
12.221337587185932
12.221337579903157
12.221337572621959
12.221337565342353
12.221337558064315
12.221337550787862
12.221337543512993
12.2213375362397
12.221337528967975
12.221337521697833
12.221337514429274
12.221337507162302
12.221337499896887
12.22133749263306
12.221337485370809
12.221337478110133
12.22133747085103
12.22133746359351
12.221337456337555
12.221337449083183
12.221337441830377
12.221337434579159
12.221337427329507
12.221337420081433
12.221337412834924
12.221337405589994
12.221337398346627
12.221337391104843
12.221337383864633
12.221337376625987
12.221337369388912
12.22133736215341
12.221337354919477
12.221337347687113
12.22133734045632
12.221337333227103
12.221337325999448
12.221337318773365
12.221337311548849
12.221337304325901
12.221337297104519
12.221337289884701
12.221337282666457
12.22133727544978
12.22133726823467
12.221337261021127
12.221337253809134
12.221337246598729
12.22133723938987
12.221337232182586
12.221337224976866
12.221337217772707
12.221337210570113
12.22133720336908
12.221337196169616
12.221337188971699
12.22133718177537
12.221337174580583
12.221337167387363
12.221337160195704
12.221337153005608
12.221337145817065
12.221337138630098
12.221337131444674
12.221337124260819
12.22133711707852
12.221337109897782
12.221337102718596
12.22133709554099
12.22133708836492
12.221337081190413
12.221337074017464
12.221337066846065
12.221337059676234
12.221337052507952
12.221337045341235
12.221337038176062
12.221337031012448
12.22133702385039
12.221337016689883
12.221337009530934
12.221337002373543
12.221336995217701
12.221336988063415
12.221336980910674
12.22133697375949
12.221336966609854
12.221336959461771
12.221336952315244
12.221336945170272
12.221336938026848
12.221336930884965
12.221336923744637
12.22133691660587
12.221336909468636
12.221336902332961
12.221336895198831
12.221336888066256
12.221336880935228
12.221336873805738
12.2213368666778
12.221336859551412
12.22133685242657
12.221336845303272
12.221336838181522
12.221336831061317
12.221336823942664
12.22133681682554
12.22133680970997
12.221336802595946
12.221336795483465
12.221336788372525
12.221336781263146
12.221336774155281
12.221336767048982
12.22133675994421
12.221336752840987
12.221336745739306
12.221336738639174
12.221336731540566
12.221336724443512
12.221336717347981
12.221336710254004
12.221336703161574
12.221336696070669
12.221336688981314
12.221336681893494
12.221336674807207
12.221336667722474
12.221336660639254
12.221336653557582
12.22133664647746
12.22133663939886
12.221336632321803
12.221336625246282
12.221336618172288
12.221336611099842
12.221336604028918
12.221336596959537
12.221336589891687
12.221336582825371
12.221336575760596
12.22133656869735
12.221336561635635
12.221336554575453
12.221336547516806
12.221336540459689
12.221336533404102
12.221336526350047
12.221336519297523
12.221336512246536
12.221336505197078
12.221336498149142

12.221336491102738
12.221336484057867
12.221336477014518
12.221336469972716
12.221336462932426
12.221336455893676
12.221336448856436
12.221336441820736
12.221336434786563
12.221336427753904
12.221336420722789
12.2213364136932
12.221336406665122
12.221336399638586
12.221336392613564
12.221336385590059
12.221336378568095
12.221336371547649
12.221336364528723
12.221336357511333
12.221336350495449
12.221336343481092
12.221336336468266
12.221336329456955
12.221336322447165
12.221336315438903
12.221336308432157
12.22133630142694
12.221336294423228
12.221336287421053
12.221336280420385
12.221336273421237
12.22133626642362
12.221336259427511
12.221336252432922
12.221336245439849
12.221336238448302
12.22133623145827
12.221336224469754
12.221336217482754
12.22133621049727
12.221336203513305
12.221336196530856
12.221336189549918
12.221336182570488
12.22133617559259
12.221336168616201
12.221336161641327
12.221336154667952
12.221336147696105
12.221336140725773
12.221336133756955
12.22133612678964
12.221336119823846
12.221336112859555
12.22133610589678
12.221336098935511
12.22133609197577
12.221336085017523
12.221336078060785
12.22133607110556
12.221336064151851
12.221336057199647
12.221336050248956
12.221336043299765
12.22133603635209
12.221336029405924
12.221336022461267
12.221336015518107
12.221336008576465
12.22133600163633
12.221335994697684
12.221335987760561
12.221335980824934
12.221335973890813
12.221335966958204
12.2213359600271
12.221335953097494
12.221335946169388
12.221335939242797
12.221335932317709
12.221335925394115
12.221335918472041
12.221335911551451
12.221335904632372
12.221335897714786
12.221335890798711
12.221335883884127
12.221335876971054
12.221335870059479
12.221335863149404
12.22133585624083
12.221335849333755
12.221335842428177
12.221335835524096
12.221335828621513
12.221335821720432
12.22133581482085
12.22133580792277
12.221335801026173
12.221335794131083
12.221335787237496
12.221335780345385
12.221335773454783
12.221335766565677
12.22133575967806
12.22133575279195
12.221335745907323
12.221335739024191
12.221335732142563
12.221335725262419
12.22133571838377
12.221335711506619
12.22133570463096
12.221335697756782
12.221335690884109
12.221335684012919
12.221335677143225
12.221335670275023
12.221335663408308
12.221335656543092
12.221335649679354
12.221335642817113
12.221335635956361
12.221335629097098
12.22133562223932
12.22133561538303
12.221335608528229
12.22133560167492
12.22133559482309
12.221335587972758
12.221335581123906
12.22133557427655
12.221335567430671
12.221335560586283
12.221335553743378
12.221335546901951
12.221335540062023
12.221335533223574
12.221335526386595
12.221335519551122
12.221335512717122
12.221335505884609
12.221335499053575
12.221335492224025
12.221335485395954
12.221335478569374
12.221335471744272
12.22133546492065
12.22133545809851
12.221335451277845
12.221335444458667
12.221335437640965
12.221335430824745
12.22133542401
12.221335417196745
12.221335410384961
12.221335403574667
12.221335396765832
12.221335389958488
12.221335383152615
12.221335376348213
12.221335369545297
12.221335362743865
12.2213353559439
12.221335349145404
12.221335342348397
12.221335335552855
12.221335328758794
12.221335321966203
12.221335315175105
12.221335308385456
12.221335301597293
12.221335294810602
12.221335288025374
12.221335281241632
12.221335274459353
12.22133526767856
12.221335260899231
12.221335254121373
12.221335247344978
12.221335240570072
12.221335233796625
12.221335227024646
12.22133522025414
12.221335213485094
12.221335206717528
12.221335199951433
12.221335193186809
12.221335186423637
12.221335179661944
12.221335172901718
12.221335166142959
12.221335159385669
12.221335152629841
12.221335145875484
12.221335139122589
12.221335132371165
12.221335125621199
12.221335118872705
12.22133511212567
12.221335105380101
12.221335098636
12.22133509189336
12.221335085152182
12.221335078412476
12.221335071674227
12.221335064937431
12.22133505820211
12.221335051468248
12.221335044735843
12.221335038004906
12.221335031275423
12.221335024547404
12.221335017820838
12.221335011095746
12.221335004372103
12.221334997649928
12.221334990929208
12.221334984209946
12.22133497749214
12.221334970775798
12.221334964060912
12.221334957347468
12.221334950635502
12.221334943924981
12.221334937215927
12.221334930508327
12.221334923802171
12.221334917097481
12.22133491039424
12.22133490369246
12.221334896992138
12.221334890293264
12.221334883595842
12.22133487689987
12.221334870205355
12.2213348635123
12.221334856820697
12.221334850130537
12.221334843441849
12.22133483675459
12.221334830068791
12.221334823384444
12.221334816701548
12.2213348100201
12.221334803340104
12.221334796661553
12.221334789984455
12.221334783308802
12.22133477663461
12.221334769961862
12.221334763290555
12.221334756620701
12.221334749952302
12.221334743285341
12.221334736619836
12.22133472995577
12.221334723293142
12.22133471663198
12.221334709972249
12.22133470331397
12.221334696657124
12.22133469000174
12.221334683347791
12.221334676695289
12.221334670044236
12.221334663394618
12.221334656746446
12.221334650099722
12.221334643454428
12.221334636810587
12.221334630168183
12.221334623527227
12.221334616887711
12.22133461024964
12.221334603612995
12.2213345969778
12.221334590344052
12.221334583711728
12.221334577080848
12.221334570451406
12.221334563823406
12.221334557196858
12.22133455057173
12.221334543948045
12.221334537325808
12.221334530705
12.221334524085623
12.221334517467692
12.221334510851195
12.221334504236124
12.221334497622507
12.221334491010317
12.221334484399552
12.221334477790231
12.221334471182345
12.221334464575895
12.221334457970881
12.221334451367289
12.22133444476514
12.221334438164423
12.221334431565136
12.221334424967289
12.221334418370864
12.221334411775874
12.221334405182315
12.22133439859019
12.221334391999497
12.221334385410223
12.221334378822391
12.221334372235992
12.221334365651005
12.221334359067466
12.221334352485346
12.221334345904651
12.221334339325393
12.221334332747565
12.221334326171156
12.221334319596176
12.221334313022625
12.221334306450505
12.221334299879807
12.221334293310528
12.221334286742684
12.221334280176267
12.221334273611276
12.221334267047704
12.221334260485555
12.221334253924837
12.221334247365538
12.221334240807671
12.22133423425122
12.221334227696191
12.221334221142586
12.221334214590405
12.221334208039641
12.221334201490302
12.221334194942399
12.221334188395891
12.22133418185082
12.221334175307172
12.221334168764932
12.221334162224123
12.221334155684723
12.221334149146752
12.2213341426102
12.221334136075065
12.221334129541347
12.221334123009047
12.221334116478166
12.2213341099487
12.221334103420656
12.221334096894015
12.22133409036881
12.221334083845017
12.221334077322625
12.221334070801666
12.221334064282113
12.22133405776398
12.221334051247252
12.221334044731947
12.22133403821806
12.221334031705581
12.221334025194516
12.221334018684862
12.221334012176625
12.221334005669796
12.221333999164381
12.22133399266038
12.221333986157795
12.22133397965662
12.221333973156849
12.221333966658488
12.221333960161546
12.221333953665999
12.221333947171882
12.22133394067916
12.221333934187863
12.221333927697957
12.221333921209474
12.221333914722386
12.221333908236712
12.221333901752455
12.221333895269593
12.221333888788143
12.221333882308095
12.221333875829455
12.22133386935222
12.221333862876401
12.221333856401973
12.221333849928959
12.221333843457348
12.221333836987146
12.221333830518345
12.221333824050953
12.22133381758495
12.221333811120363
12.221333804657174
12.221333798195388
12.22133379173501
12.221333785276036
12.221333778818456
12.221333772362271
12.221333765907502
12.221333759454131
12.221333753002156
12.221333746551583
12.221333740102411
12.22133373365464
12.221333727208265
12.221333720763292
12.221333714319721
12.221333707877536
12.221333701436762
12.221333694997382
12.2213336885594
12.22133368212281
12.221333675687625
12.221333669253834
12.221333662821438
12.221333656390438
12.221333649960831
12.221333643532626
12.221333637105815
12.22133363068039
12.221333624256372
12.221333617833748
12.221333611412502
12.221333604992662
12.221333598574228
12.221333592157162
12.221333585741505
12.221333579327238
12.221333572914357
12.221333566502876
12.221333560092784
12.221333553684088
12.221333547276766
12.22133354087085
12.22133353446632
12.221333528063173
12.221333521661425
12.221333515261074
12.2213335088621
12.221333502464514
12.22133349606832
12.221333489673512
12.221333483280095
12.221333476888068
12.22133347049742
12.221333464108172
12.221333457720299
12.221333451333816
12.221333444948723
12.22133343856501
12.221333432182695
12.221333425801747
12.221333419422187
12.221333413044025
12.221333406667235
12.221333400291833

12.22133339391782
12.22133338754518
12.221333381173933
12.22133337480407
12.221333368435577
12.221333362068478
12.221333355702756
12.22133334933842
12.221333342975461
12.221333336613878
12.22133333025368
12.22133332389487
12.221333317537429
12.221333311181377
12.2213333048267
12.221333298473402
12.221333292121484
12.221333285770944
12.221333279421781
12.221333273073997
12.221333266727596
12.221333260382574
12.221333254038916
12.221333247696645
12.221333241355744
12.221333235016228
12.221333228678082
12.221333222341306
12.221333216005924
12.221333209671906
12.22133320333926
12.221333197007985
12.22133319067809
12.221333184349575
12.221333178022428
12.221333171696651
12.221333165372249
12.221333159049225
12.221333152727563
12.221333146407277
12.221333140088365
12.221333133770827
12.221333127454654
12.221333121139853
12.221333114826429
12.221333108514372
12.22133310220368
12.22133309589436
12.221333089586418
12.221333083279843
12.221333076974624
12.22133307067078
12.22133306436831
12.221333058067206
12.221333051767463
12.221333045469095
12.221333039172094
12.221333032876455
12.221333026582185
12.221333020289277
12.221333013997734
12.221333007707564
12.221333001418767
12.22133299513131
12.221332988845234
12.221332982560524
12.221332976277179
12.221332969995187
12.221332963714566
12.221332957435308
12.221332951157404
12.221332944880865
12.221332938605702
12.2213329323319
12.221332926059441
12.221332919788358
12.221332913518639
12.22133290725027
12.221332900983263
12.221332894717623
12.221332888453336
12.221332882190417
12.22133287592885
12.22133286966864
12.221332863409796
12.221332857152309
12.221332850896184
12.221332844641404
12.22133283838799
12.221332832135941
12.221332825885234
12.221332819635894
12.221332813387901
12.22133280714127
12.221332800896
12.22133279465208
12.221332788409509
12.221332782168302
12.221332775928447
12.221332769689946
12.221332763452796
12.221332757217006
12.221332750982565
12.221332744749482
12.221332738517752
12.221332732287367
12.221332726058337
12.221332719830658
12.22133271360434
12.221332707379366
12.221332701155738
12.221332694933464
12.22133268871256
12.221332682492976
12.22133267627475
12.221332670057887
12.221332663842366
12.221332657628185
12.221332651415365
12.221332645203894
12.221332638993768
12.221332632784994
12.221332626577555
12.221332620371467
12.221332614166732
12.22133260796334
12.221332601761297
12.221332595560602
12.221332589361248
12.221332583163232
12.221332576966581
12.221332570771267
12.221332564577297
12.221332558384667
12.221332552193381
12.221332546003445
12.22133253981484
12.221332533627594
12.221332527441685
12.22133252125712
12.221332515073897
12.221332508892013
12.221332502711466
12.221332496532264
12.221332490354413
12.22133248417789
12.22133247800272
12.221332471828877
12.221332465656385
12.22133245948522
12.22133245331541
12.221332447146928
12.221332440979786
12.221332434813993
12.221332428649527
12.221332422486404
12.221332416324616
12.22133241016417
12.221332404005057
12.221332397847283
12.22133239169084
12.221332385535739
12.22133237938197
12.221332373229538
12.221332367078448
12.221332360928685
12.221332354780255
12.221332348633158
12.221332342487411
12.221332336342979
12.221332330199902
12.221332324058142
12.221332317917723
12.22133231177863
12.221332305640871
12.221332299504445
12.221332293369356
12.221332287235594
12.221332281103159
12.221332274972056
12.22133226884229
12.221332262713844
12.221332256586745
12.221332250460959
12.221332244336512
12.221332238213396
12.221332232091601
12.221332225971137
12.221332219852004
12.2213322137342
12.221332207617726
12.22133220150257
12.221332195388749
12.221332189276252
12.221332183165076
12.221332177055247
12.22133217094673
12.221332164839545
12.221332158733668
12.22133215262913
12.221332146525915
12.221332140424026
12.22133213432346
12.22133212822422
12.2213321221263
12.221332116029707
12.221332109934439
12.221332103840489
12.221332097747865
12.221332091656565
12.221332085566587
12.221332079477918
12.221332073390586
12.221332067304566
12.221332061219867
12.221332055136498
12.221332049054443
12.221332042973705
12.221332036894292
12.221332030816189
12.221332024739423
12.221332018663968
12.22133201258983
12.221332006517011
12.221332000445503
12.221331994375328
12.221331988306458
12.221331982238912
12.221331976172676
12.221331970107768
12.221331964044165
12.22133195798188
12.221331951920915
12.221331945861266
12.221331939802926
12.221331933745908
12.2213319276902
12.22133192163581
12.22133191558273
12.221331909530962
12.221331903480511
12.22133189743138
12.221331891383551
12.221331885337037
12.221331879291837
12.221331873247946
12.221331867205375
12.221331861164115
12.22133185512416
12.221331849085526
12.221331843048182
12.221331837012167
12.221331830977464
12.221331824944052
12.221331818911963
12.221331812881184
12.221331806851698
12.22133180082354
12.221331794796685
12.221331788771133
12.221331782746896
12.221331776723966
12.221331770702339
12.221331764682025
12.221331758663009
12.2213317526453
12.221331746628906
12.221331740613811
12.221331734600023
12.221331728587547
12.221331722576359
12.221331716566494
12.221331710557926
12.221331704550655
12.2213316985447
12.221331692540039
12.22133168653669
12.221331680534634
12.221331674533891
12.22133166853445
12.2213316625363
12.221331656539464
12.221331650543918
12.221331644549682
12.221331638556752
12.22133163256512
12.221331626574768
12.221331620585735
12.221331614598006
12.22133160861157
12.22133160262643
12.221331596642584
12.221331590660053
12.221331584678815
12.221331578698871
12.221331572720226
12.221331566742876
12.221331560766831
12.221331554792084
12.221331548818616
12.221331542846464
12.221331536875605
12.22133153090604
12.221331524937764
12.221331518970787
12.221331513005113
12.221331507040722
12.22133150107763
12.221331495115836
12.221331489155332
12.221331483196126
12.221331477238204
12.221331471281585
12.221331465326251
12.22133145937222
12.221331453419472
12.221331447468025
12.221331441517856
12.221331435568992
12.22133142962141
12.221331423675132
12.221331417730127
12.221331411786425
12.221331405844001
12.221331399902878
12.221331393963043
12.221331388024494
12.221331382087232
12.221331376151255
12.221331370216586
12.221331364283195
12.221331358351081
12.221331352420266
12.221331346490734
12.22133134056249
12.22133133463553
12.221331328709859
12.221331322785472
12.22133131686238
12.221331310940565
12.22133130502003
12.221331299100793
12.22133129318284
12.221331287266155
12.22133128135078
12.221331275436661
12.221331269523844
12.221331263612301
12.221331257702047
12.221331251793085
12.221331245885393
12.221331239978976
12.221331234073858
12.221331228170014
12.221331222267448
12.221331216366165
12.221331210466161
12.22133120456744
12.22133119867
12.221331192773846
12.22133118687897
12.221331180985358
12.221331175093043
12.221331169202001
12.221331163312232
12.22133115742376
12.221331151536543
12.221331145650614
12.221331139765956
12.221331133882595
12.221331128000488
12.221331122119668
12.221331116240119
12.221331110361858
12.221331104484861
12.221331098609141
12.221331092734703
12.221331086861538
12.221331080989637
12.221331075119021
12.22133106924968
12.22133106338161
12.221331057514819
12.2213310516493
12.221331045785046
12.221331039922068
12.221331034060368
12.221331028199936
12.221331022340774
12.22133101648289
12.221331010626262
12.221331004770926
12.221330998916848
12.221330993064045
12.22133098721251
12.221330981362247
12.221330975513254
12.221330969665528
12.221330963819076
12.221330957973892
12.221330952129978
12.221330946287322
12.221330940445938
12.221330934605838
12.221330928766983
12.221330922929408
12.221330917093098
12.221330911258054
12.221330905424274
12.221330899591763
12.221330893760516
12.221330887930538
12.221330882101817
12.221330876274374
12.221330870448199
12.22133086462327
12.22133085879962
12.221330852977223
12.221330847156088
12.22133084133623
12.221330835517628
12.221330829700292
12.221330823884214
12.221330818069406
12.22133081225585
12.221330806443564
12.221330800632533
12.22133079482277
12.221330789014262
12.221330783207016
12.221330777401032
12.221330771596303
12.22133076579284
12.221330759990641
12.221330754189696
12.221330748390013
12.221330742591581
12.221330736794407
12.221330730998494
12.221330725203844
12.221330719410451
12.221330713618316
12.221330707827434
12.221330702037811
12.221330696249444
12.22133069046234
12.221330684676486
12.221330678891881
12.221330673108543
12.221330667326448
12.221330661545615
12.221330655766042
12.22133064998772
12.221330644210642
12.22133063843483
12.221330632660273
12.221330626886957
12.221330621114905
12.221330615344097
12.221330609574553
12.221330603806253
12.221330598039213
12.221330592273413
12.221330586508877
12.221330580745578
12.22133057498354
12.221330569222753
12.221330563463203
12.221330557704922
12.221330551947881
12.221330546192092
12.221330540437549
12.221330534684261
12.221330528932214
12.221330523181424
12.22133051743188
12.221330511683576
12.221330505936514
12.221330500190723
12.221330494446162
12.221330488702852
12.221330482960788
12.221330477219984
12.22133047148041
12.221330465742085
12.221330460005008
12.221330454269172
12.221330448534578
12.22133044280123
12.221330437069138
12.221330431338286
12.221330425608661
12.221330419880305
12.221330414153172
12.221330408427294
12.221330402702646
12.22133039697926
12.221330391257098
12.22133038553619
12.22133037981652
12.221330374098091
12.221330368380904
12.221330362664956
12.221330356950247
12.221330351236777
12.221330345524555
12.221330339813571
12.221330334103826
12.221330328395315
12.221330322688049
12.221330316982014
12.22133031127722
12.221330305573671
12.221330299871358
12.221330294170277
12.22133028847044
12.221330282771838
12.221330277074472
12.221330271378344
12.221330265683447
12.2213302599898
12.221330254297367
12.221330248606176
12.221330242916231
12.221330237227512
12.221330231540042
12.221330225853793
12.22133022016878
12.221330214484997
12.22133020880246
12.221330203121143
12.221330197441072
12.221330191762227
12.221330186084614
12.22133018040823
12.221330174733083
12.221330169059168
12.22133016338648
12.221330157715023
12.221330152044805
12.22133014637581
12.221330140708044
12.22133013504152
12.221330129376218
12.221330123712146
12.221330118049302
12.221330112387694
12.221330106727306
12.221330101068151
12.22133009541022
12.221330089753524
12.221330084098055
12.221330078443808
12.221330072790787
12.221330067139009
12.221330061488443
12.221330055839097
12.221330050190994
12.221330044544107
12.221330038898454
12.221330033254013
12.221330027610806
12.221330021968825
12.221330016328062

12.221330010688533
12.221330005050214
12.221329999413124
12.221329993777273
12.221329988142621
12.221329982509205
12.221329976877016
12.221329971246044
12.221329965616288
12.221329959987763
12.221329954360458
12.221329948734372
12.221329943109515
12.221329937485873
12.221329931863444
12.221329926242234
12.221329920622255
12.221329915003494
12.22132990938596
12.221329903769634
12.221329898154528
12.221329892540648
12.221329886927982
12.221329881316526
12.221329875706298
12.221329870097287
12.22132986448949
12.221329858882907
12.221329853277544
12.2213298476734
12.221329842070467
12.221329836468763
12.221329830868266
12.221329825268985
12.221329819670913
12.221329814074066
12.221329808478432
12.221329802884007
12.221329797290803
12.221329791698805
12.221329786108022
12.221329780518461
12.22132977493011
12.22132976934297
12.22132976375704
12.22132975817233
12.221329752588826
12.22132974700653
12.221329741425448
12.22132973584559
12.221329730266936
12.22132972468949
12.22132971911325
12.221329713538221
12.221329707964411
12.221329702391806
12.221329696820405
12.221329691250226
12.22132968568124
12.22132968011347
12.221329674546915
12.221329668981559
12.221329663417425
12.221329657854485
12.221329652292754
12.221329646732235
12.22132964117292
12.221329635614808
12.221329630057909
12.221329624502214
12.221329618947719
12.221329613394447
12.221329607842364
12.221329602291478
12.22132959674181
12.221329591193353
12.221329585646092
12.221329580100042
12.221329574555181
12.221329569011536
12.221329563469094
12.221329557927842
12.22132955238781
12.22132954684897
12.221329541311329
12.221329535774904
12.221329530239673
12.22132952470564
12.22132951917281
12.221329513641175
12.221329508110752
12.221329502581526
12.221329497053501
12.221329491526673
12.221329486001041
12.22132948047662
12.22132947495339
12.221329469431359
12.221329463910525
12.221329458390896
12.22132945287245
12.221329447355219
12.221329441839176
12.22132943632434
12.221329430810687
12.221329425298237
12.221329419786986
12.22132941427693
12.221329408768064
12.221329403260405
12.221329397753934
12.221329392248661
12.221329386744575
12.22132938124169
12.221329375740003
12.221329370239506
12.221329364740201
12.221329359242096
12.221329353745181
12.22132934824946
12.221329342754924
12.221329337261592
12.221329331769446
12.221329326278497
12.221329320788726
12.221329315300162
12.22132930981278
12.221329304326597
12.221329298841605
12.221329293357792
12.221329287875177
12.221329282393752
12.22132927691352
12.22132927143447
12.221329265956616
12.221329260479944
12.221329255004463
12.22132924953018
12.221329244057078
12.221329238585156
12.221329233114425
12.221329227644892
12.22132922217654
12.221329216709371
12.221329211243395
12.221329205778606
12.221329200314997
12.221329194852572
12.221329189391335
12.221329183931282
12.221329178472427
12.221329173014738
12.221329167558244
12.221329162102933
12.221329156648808
12.221329151195865
12.221329145744104
12.221329140293522
12.221329134844137
12.221329129395922
12.221329123948902
12.221329118503052
12.221329113058388
12.22132910761491
12.221329102172609
12.221329096731491
12.221329091291548
12.221329085852794
12.22132908041522
12.221329074978824
12.221329069543602
12.221329064109568
12.221329058676703
12.221329053245029
12.22132904781453
12.221329042385205
12.22132903695706
12.221329031530097
12.221329026104314
12.22132902067971
12.221329015256268
12.22132900983402
12.221329004412949
12.221328998993041
12.22132899357432
12.221328988156772
12.221328982740397
12.2213289773252
12.22132897191118
12.221328966498332
12.221328961086659
12.22132895567616
12.221328950266841
12.221328944858692
12.221328939451725
12.221328934045923
12.22132892864129
12.221328923237838
12.221328917835553
12.22132891243444
12.221328907034506
12.221328901635749
12.221328896238148
12.221328890841729
12.221328885446475
12.221328880052399
12.221328874659495
12.221328869267753
12.221328863877188
12.221328858487787
12.221328853099557
12.221328847712506
12.22132884232661
12.22132883694189
12.221328831558338
12.221328826175961
12.221328820794744
12.2213288154147
12.221328810035818
12.221328804658105
12.22132879928156
12.221328793906185
12.221328788531977
12.221328783158933
12.221328777787047
12.221328772416344
12.221328767046797
12.221328761678414
12.221328756311205
12.221328750945144
12.221328745580259
12.221328740216535
12.221328734853985
12.22132872949259
12.221328724132361
12.221328718773297
12.221328713415389
12.22132870805865
12.221328702703074
12.221328697348655
12.22132869199541
12.221328686643318
12.221328681292384
12.221328675942623
12.221328670594005
12.22132866524656
12.221328659900278
12.22132865455516
12.22132864921119
12.22132864386838
12.221328638526737
12.221328633186248
12.221328627846928
12.221328622508768
12.221328617171743
12.221328611835895
12.221328606501206
12.221328601167674
12.221328595835296
12.221328590504069
12.221328585174016
12.221328579845103
12.22132857451736
12.221328569190756
12.221328563865322
12.221328558541044
12.221328553217926
12.221328547895954
12.221328542575142
12.221328537255474
12.221328531936978
12.221328526619624
12.221328521303423
12.221328515988384
12.221328510674494
12.221328505361766
12.221328500050172
12.22132849473975
12.221328489430467
12.221328484122342
12.221328478815376
12.221328473509551
12.221328468204886
12.221328462901361
12.221328457598995
12.221328452297785
12.221328446997717
12.221328441698802
12.22132843640104
12.221328431104423
12.22132842580896
12.221328420514649
12.221328415221475
12.221328409929457
12.221328404638582
12.221328399348865
12.221328394060295
12.22132838877287
12.22132838348659
12.221328378201463
12.221328372917482
12.221328367634642
12.221328362352956
12.221328357072418
12.221328351793014
12.221328346514758
12.221328341237658
12.221328335961699
12.221328330686887
12.22132832541322
12.221328320140696
12.221328314869305
12.221328309599077
12.22132830432998
12.221328299062034
12.221328293795228
12.221328288529568
12.221328283265048
12.221328278001675
12.221328272739436
12.221328267478341
12.221328262218393
12.221328256959586
12.221328251701916
12.221328246445394
12.221328241190005
12.221328235935756
12.221328230682653
12.221328225430693
12.221328220179874
12.221328214930184
12.221328209681635
12.221328204434236
12.221328199187973
12.221328193942838
12.221328188698848
12.221328183456
12.221328178214277
12.221328172973704
12.221328167734265
12.221328162495968
12.2213281572588
12.221328152022773
12.221328146787885
12.221328141554126
12.22132813632151
12.221328131090026
12.221328125859676
12.221328120630462
12.22132811540239
12.221328110175444
12.221328104949636
12.221328099724962
12.221328094501423
12.221328089279016
12.221328084057753
12.221328078837606
12.221328073618599
12.221328068400725
12.221328063183984
12.221328057968382
12.221328052753902
12.221328047540556
12.221328042328343
12.221328037117262
12.221328031907307
12.221328026698485
12.221328021490805
12.221328016284241
12.221328011078809
12.221328005874517
12.221328000671345
12.2213279954693
12.221327990268389
12.221327985068605
12.221327979869951
12.221327974672429
12.221327969476027
12.221327964280757
12.221327959086617
12.22132795389361
12.221327948701713
12.221327943510964
12.221327938321322
12.221327933132812
12.221327927945431
12.221327922759173
12.221327917574051
12.221327912390048
12.22132790720716
12.221327902025413
12.221327896844778
12.221327891665267
12.221327886486895
12.22132788130963
12.2213278761335
12.221327870958488
12.221327865784609
12.221327860611842
12.221327855440196
12.221327850269683
12.221327845100287
12.221327839932012
12.221327834764866
12.221327829598827
12.22132782443392
12.221327819270135
12.221327814107466
12.221327808945912
12.22132780378549
12.221327798626184
12.221327793467996
12.221327788310933
12.221327783154985
12.22132777800015
12.22132777284645
12.221327767693849
12.221327762542376
12.221327757392022
12.221327752242779
12.221327747094664
12.221327741947665
12.22132773680178
12.221327731657006
12.221327726513351
12.221327721370832
12.221327716229398
12.2213277110891
12.221327705949912
12.221327700811841
12.221327695674885
12.221327690539043
12.221327685404317
12.221327680270702
12.221327675138209
12.221327670006827
12.221327664876553
12.221327659747397
12.221327654619353
12.22132764949242
12.221327644366601
12.221327639241895
12.221327634118307
12.221327628995823
12.221327623874453
12.221327618754195
12.221327613635049
12.221327608517017
12.22132760340009
12.221327598284278
12.221327593169576
12.221327588055981
12.221327582943498
12.221327577832131
12.221327572721863
12.221327567612708
12.221327562504662
12.22132755739772
12.221327552291896
12.221327547187169
12.221327542083559
12.221327536981052
12.221327531879657
12.221327526779373
12.221327521680184
12.221327516582113
12.22132751148514
12.221327506389274
12.221327501294521
12.22132749620087
12.221327491108323
12.221327486016875
12.22132748092654
12.221327475837308
12.221327470749191

12.221327465662164
12.221327460576248
12.221327455491435
12.22132745040772
12.221327445325118
12.221327440243615
12.221327435163209
12.221327430083912
12.221327425005724
12.221327419928622
12.221327414852631
12.221327409777745
12.221327404703956
12.221327399631262
12.221327394559681
12.221327389489197
12.221327384419816
12.22132737935153
12.221327374284355
12.221327369218255
12.221327364153277
12.221327359089385
12.221327354026602
12.221327348964916
12.221327343904326
12.221327338844828
12.221327333786439
12.221327328729146
12.221327323672948
12.221327318617849
12.221327313563851
12.221327308510936
12.221327303459136
12.22132729840842
12.221327293358812
12.221327288310283
12.22132728326286
12.22132727821654
12.221327273171305
12.221327268127165
12.22132726308412
12.221327258042175
12.221327253001318
12.221327247961565
12.221327242922893
12.22132723788532
12.221327232848838
12.221327227813457
12.221327222779161
12.221327217745962
12.221327212713852
12.22132720768284
12.22132720265291
12.22132719762408
12.221327192596346
12.221327187569688
12.221327182544133
12.221327177519665
12.221327172496288
12.221327167474003
12.221327162452805
12.221327157432691
12.221327152413686
12.221327147395753
12.22132714237892
12.221327137363167
12.2213271323485
12.221327127334932
12.221327122322453
12.22132711731105
12.221327112300738
12.22132710729152
12.221327102283388
12.221327097276339
12.221327092270379
12.221327087265507
12.221327082261718
12.22132707725902
12.221327072257406
12.22132706725687
12.221327062257425
12.221327057259064
12.221327052261795
12.221327047265598
12.221327042270493
12.221327037276478
12.221327032283531
12.221327027291679
12.221327022300919
12.221327017311221
12.22132701232262
12.221327007335105
12.221327002348659
12.221326997363306
12.221326992379039
12.221326987395837
12.221326982413729
12.2213269774327
12.221326972452747
12.221326967473882
12.221326962496093
12.221326957519384
12.221326952543759
12.22132694756921
12.221326942595747
12.221326937623353
12.22132693265205
12.221326927681824
12.22132692271267
12.221326917744594
12.221326912777613
12.221326907811688
12.221326902846856
12.221326897883092
12.221326892920416
12.221326887958803
12.221326882998278
12.221326878038825
12.22132687308045
12.221326868123148
12.221326863166931
12.221326858211782
12.221326853257708
12.221326848304713
12.221326843352788
12.221326838401941
12.221326833452169
12.221326828503473
12.221326823555849
12.2213268186093
12.221326813663827
12.221326808719423
12.221326803776092
12.221326798833832
12.221326793892645
12.221326788952538
12.2213267840135
12.221326779075522
12.221326774138635
12.221326769202815
12.221326764268062
12.221326759334378
12.221326754401769
12.22132674947022
12.221326744539759
12.221326739610356
12.221326734682032
12.221326729754766
12.221326724828579
12.221326719903454
12.221326714979407
12.221326710056424
12.221326705134503
12.221326700213652
12.221326695293879
12.221326690375166
12.221326685457532
12.221326680540951
12.221326675625432
12.221326670710997
12.22132666579762
12.22132666088532
12.221326655974075
12.2213266510639
12.221326646154788
12.221326641246733
12.221326636339755
12.221326631433843
12.221326626528993
12.221326621625211
12.221326616722484
12.221326611820828
12.221326606920229
12.221326602020712
12.221326597122241
12.221326592224841
12.221326587328502
12.221326582433218
12.221326577539003
12.221326572645857
12.221326567753763
12.221326562862734
12.22132655797277
12.221326553083864
12.22132654819601
12.221326543309235
12.22132653842351
12.22132653353885
12.221326528655247
12.22132652377271
12.22132651889122
12.221326514010798
12.221326509131437
12.221326504253128
12.221326499375886
12.221326494499696
12.221326489624571
12.221326484750495
12.221326479877481
12.221326475005528
12.221326470134628
12.221326465264791
12.221326460396009
12.22132645552828
12.221326450661614
12.221326445795999
12.221326440931438
12.221326436067937
12.221326431205489
12.221326426344106
12.221326421483761
12.22132641662449
12.221326411766258
12.221326406909093
12.221326402052972
12.221326397197911
12.221326392343897
12.221326387490944
12.22132638263904
12.221326377788182
12.221326372938387
12.221326368089644
12.221326363241952
12.221326358395311
12.221326353549728
12.221326348705192
12.221326343861708
12.221326339019278
12.22132633417789
12.22132632933756
12.22132632449828
12.221326319660049
12.221326314822871
12.221326309986738
12.22132630515166
12.221326300317621
12.221326295484639
12.221326290652708
12.221326285821826
12.221326280991986
12.2213262761632
12.221326271335464
12.221326266508768
12.22132626168313
12.221326256858536
12.221326252034977
12.221326247212481
12.221326242391026
12.221326237570619
12.22132623275125
12.221326227932936
12.221326223115664
12.221326218299433
12.221326213484259
12.22132620867012
12.221326203857034
12.221326199044983
12.221326194233985
12.22132618942403
12.221326184615112
12.221326179807246
12.221326175000424
12.221326170194642
12.2213261653899
12.221326160586207
12.221326155783546
12.221326150981946
12.221326146181374
12.221326141381837
12.221326136583356
12.221326131785915
12.221326126989512
12.221326122194146
12.22132611739983
12.221326112606544
12.221326107814301
12.221326103023111
12.221326098232952
12.221326093443823
12.221326088655752
12.221326083868707
12.221326079082703
12.22132607429774
12.221326069513808
12.221326064730933
12.221326059949089
12.221326055168275
12.221326050388498
12.22132604560976
12.221326040832066
12.221326036055409
12.221326031279775
12.2213260265052
12.221326021731638
12.221326016959127
12.221326012187648
12.221326007417206
12.221326002647787
12.221325997879426
12.221325993112083
12.22132598834578
12.22132598358051
12.221325978816271
12.221325974053078
12.22132596929091
12.221325964529772
12.221325959769663
12.22132595501061
12.221325950252567
12.221325945495572
12.2213259407396
12.221325935984668
12.22132593123076
12.221325926477885
12.221325921726041
12.221325916975237
12.221325912225451
12.22132590747672
12.221325902728996
12.22132589798231
12.221325893236656
12.221325888492034
12.221325883748428
12.221325879005866
12.221325874264329
12.221325869523815
12.221325864784337
12.221325860045889
12.22132585530847
12.221325850572075
12.221325845836711
12.221325841102374
12.221325836369052
12.221325831636772
12.221325826905527
12.221325822175297
12.22132581744609
12.221325812717915
12.221325807990768
12.221325803264639
12.221325798539539
12.221325793815478
12.221325789092429
12.221325784370404
12.221325779649403
12.221325774929436
12.221325770210484
12.221325765492573
12.22132576077566
12.221325756059791
12.221325751344938
12.221325746631114
12.221325741918298
12.22132573720652
12.221325732495755
12.221325727786024
12.2213257230773
12.22132571836962
12.221325713662939
12.221325708957298
12.221325704252664
12.221325699549059
12.221325694846472
12.22132569014491
12.221325685444357
12.221325680744831
12.221325676046334
12.221325671348847
12.221325666652376
12.221325661956929
12.221325657262506
12.221325652569105
12.221325647876707
12.221325643185333
12.22132563849499
12.221325633805648
12.22132562911733
12.221325624430031
12.221325619743752
12.221325615058491
12.221325610374238
12.221325605691012
12.221325601008791
12.221325596327599
12.221325591647416
12.221325586968247
12.221325582290095
12.221325577612957
12.221325572936843
12.221325568261737
12.22132556358764
12.22132555891457
12.221325554242503
12.221325549571459
12.221325544901426
12.221325540232405
12.221325535564395
12.221325530897401
12.221325526231423
12.221325521566454
12.221325516902503
12.221325512239552
12.221325507577621
12.221325502916699
12.221325498256794
12.221325493597892
12.221325488940009
12.221325484283144
12.221325479627266
12.221325474972417
12.221325470318583
12.22132546566575
12.221325461013926
12.221325456363111
12.221325451713312
12.221325447064508
12.221325442416727
12.221325437769954
12.221325433124191
12.22132542847943
12.221325423835676
12.22132541919293
12.221325414551199
12.221325409910465
12.221325405270756
12.221325400632036
12.221325395994318
12.221325391357613
12.221325386721924
12.221325382087239
12.221325377453562
12.221325372820885
12.221325368189211
12.221325363558545
12.221325358928885
12.221325354300234
12.221325349672577
12.221325345045937
12.221325340420293
12.22132533579566
12.221325331172025
12.221325326549385
12.22132532192777
12.221325317307134
12.221325312687506
12.221325308068897
12.221325303451282
12.221325298834667
12.22132529421905
12.221325289604444
12.221325284990838
12.221325280378224
12.221325275766624
12.221325271156015
12.22132526654641
12.22132526193781
12.221325257330198
12.2213252527236
12.221325248117996
12.221325243513395
12.221325238909786
12.221325234307184
12.221325229705574
12.221325225104968
12.221325220505356
12.221325215906745
12.221325211309138
12.22132520671252
12.2213252021169
12.221325197522281
12.221325192928658
12.221325188336033
12.221325183744407
12.221325179153776
12.22132517456414
12.221325169975497
12.221325165387848
12.221325160801209
12.221325156215556
12.2213251516309
12.221325147047235
12.221325142464574
12.221325137882898
12.221325133302217
12.221325128722533
12.221325124143844
12.221325119566155
12.221325114989448
12.22132511041374
12.22132510583902
12.221325101265302
12.221325096692574
12.221325092120832
12.221325087550092
12.221325082980336
12.221325078411574
12.221325073843806
12.221325069277023
12.221325064711236
12.221325060146443
12.22132505558264
12.221325051019823
12.221325046458
12.221325041897163
12.221325037337316
12.221325032778466
12.221325028220596
12.221325023663724
12.221325019107836
12.22132501455294
12.221325009999035
12.221325005446113
12.221325000894176
12.221324996343233
12.221324991793274
12.221324987244307
12.221324982696322
12.221324978149328
12.22132497360332
12.221324969058298
12.221324964514258
12.221324959971213
12.221324955429152
12.221324950888068
12.221324946347991
12.22132494180888
12.22132493727076
12.221324932733623
12.22132492819747
12.221324923662307
12.221324919128126
12.221324914594923
12.221324910062709
12.221324905531487
12.22132490100124
12.221324896471977
12.221324891943699
12.221324887416387
12.221324882890078
12.221324878364754
12.221324873840398
12.22132486931703
12.221324864794653
12.221324860273244
12.22132485575282
12.22132485123338
12.221324846714912
12.221324842197435
12.221324837680935
12.221324833165419
12.221324828650873
12.221324824137316
12.221324819624737
12.221324815113132
12.221324810602509
12.22132480609287
12.221324801584208
12.221324797076521
12.221324792569815
12.221324788064088
12.221324783559337
12.22132477905556
12.221324774552766
12.221324770050954
12.221324765550113
12.221324761050242
12.221324756551367
12.221324752053446
12.221324747556517
12.221324743060558
12.221324738565578
12.221324734071564
12.221324729578537
12.221324725086482
12.221324720595396
12.221324716105295
12.221324711616164
12.221324707128003
12.221324702640814
12.221324698154605
12.221324693669374
12.221324689185113
12.221324684701818
12.22132468021951
12.221324675738162
12.2213246712578
12.2213246667784
12.221324662299969
12.22132465782252
12.221324653346041
12.221324648870526
12.221324644395985
12.221324639922416

12.221324635449825
12.221324630978199
12.221324626507542
12.221324622037855
12.22132461756914
12.221324613101404
12.221324608634616
12.221324604168812
12.221324599703982
12.221324595240112
12.221324590777217
12.221324586315287
12.22132458185433
12.22132457739433
12.221324572935304
12.22132456847725
12.221324564020167
12.221324559564033
12.221324555108877
12.221324550654693
12.221324546201467
12.221324541749219
12.221324537297933
12.221324532847609
12.221324528398254
12.221324523949866
12.221324519502438
12.221324515055976
12.221324510610481
12.221324506165956
12.221324501722389
12.221324497279777
12.221324492838153
12.22132448839748
12.221324483957776
12.221324479519026
12.22132447508125
12.221324470644433
12.221324466208577
12.221324461773676
12.221324457339747
12.221324452906789
12.221324448474777
12.221324444043736
12.221324439613657
12.221324435184536
12.221324430756372
12.221324426329177
12.221324421902931
12.221324417477666
12.22132441305335
12.221324408629997
12.221324404207598
12.221324399786166
12.221324395365691
12.221324390946174
12.221324386527616
12.221324382110017
12.221324377693382
12.221324373277698
12.22132436886298
12.221324364449217
12.221324360036405
12.221324355624564
12.22132435121367
12.221324346803739
12.22132434239476
12.221324337986747
12.221324333579682
12.221324329173576
12.221324324768428
12.221324320364234
12.221324315960997
12.221324311558718
12.221324307157383
12.221324302757019
12.221324298357603
12.22132429395914
12.221324289561641
12.221324285165093
12.221324280769489
12.221324276374848
12.22132427198116
12.221324267588427
12.221324263196637
12.221324258805815
12.221324254415936
12.221324250027013
12.221324245639037
12.22132424125202
12.221324236865954
12.221324232480844
12.221324228096682
12.221324223713472
12.22132421933121
12.221324214949897
12.221324210569538
12.22132420619013
12.221324201811685
12.221324197434171
12.221324193057624
12.221324188682011
12.22132418430736
12.221324179933656
12.221324175560898
12.221324171189089
12.22132416681823
12.221324162448324
12.22132415807936
12.221324153711343
12.22132414934428
12.221324144978162
12.221324140612998
12.221324136248764
12.221324131885495
12.22132412752316
12.22132412316178
12.221324118801352
12.221324114441865
12.221324110083318
12.221324105725726
12.221324101369072
12.221324097013364
12.221324092658607
12.221324088304799
12.221324083951933
12.221324079600004
12.221324075249028
12.221324070898987
12.221324066549903
12.221324062201747
12.221324057854545
12.22132405350829
12.221324049162968
12.221324044818601
12.221324040475164
12.221324036132678
12.22132403179114
12.221324027450532
12.221324023110872
12.221324018772153
12.221324014434378
12.221324010097536
12.221324005761643
12.221324001426694
12.221323997092684
12.221323992759602
12.221323988427477
12.22132398409628
12.22132397976604
12.221323975436723
12.221323971108351
12.221323966780917
12.221323962454434
12.22132395812887
12.22132395380426
12.221323949480587
12.221323945157849
12.221323940836047
12.221323936515196
12.221323932195267
12.221323927876274
12.221323923558229
12.221323919241122
12.221323914924943
12.221323910609708
12.221323906295403
12.221323901982043
12.221323897669608
12.22132389335812
12.221323889047564
12.221323884737943
12.221323880429258
12.22132387612151
12.221323871814693
12.221323867508811
12.22132386320387
12.221323858899861
12.221323854596779
12.221323850294636
12.221323845993432
12.221323841693149
12.221323837393811
12.2213238330954
12.22132382879792
12.22132382450138
12.221323820205768
12.221323815911093
12.221323811617346
12.221323807324529
12.221323803032643
12.221323798741695
12.221323794451674
12.22132379016259
12.221323785874432
12.221323781587206
12.22132377730091
12.221323773015545
12.221323768731104
12.221323764447593
12.221323760165022
12.221323755883377
12.22132375160266
12.22132374732287
12.221323743044014
12.221323738766074
12.22132373448907
12.221323730213003
12.221323725937857
12.221323721663639
12.221323717390348
12.221323713117986
12.22132370884655
12.221323704576042
12.221323700306455
12.22132369603781
12.22132369177008
12.221323687503281
12.221323683237399
12.221323678972452
12.22132367470843
12.221323670445328
12.221323666183153
12.22132366192191
12.221323657661584
12.221323653402184
12.221323649143706
12.221323644886162
12.22132364062953
12.22132363637383
12.22132363211905
12.221323627865202
12.221323623612266
12.22132361936026
12.221323615109176
12.221323610859004
12.221323606609772
12.22132360236145
12.221323598114056
12.221323593867588
12.221323589622024
12.221323585377398
12.221323581133692
12.2213235768909
12.221323572649036
12.221323568408074
12.221323564168058
12.221323559928953
12.221323555690768
12.221323551453501
12.221323547217155
12.221323542981722
12.221323538747221
12.221323534513633
12.221323530280966
12.221323526049208
12.22132352181838
12.221323517588464
12.22132351335946
12.221323509131391
12.221323504904229
12.22132350067799
12.221323496452657
12.221323492228253
12.22132348800476
12.221323483782186
12.221323479560526
12.221323475339776
12.221323471119957
12.22132346690105
12.22132346268305
12.22132345846598
12.221323454249811
12.221323450034559
12.221323445820222
12.221323441606804
12.221323437394306
12.221323433182711
12.221323428972036
12.221323424762266
12.221323420553423
12.221323416345498
12.221323412138467
12.221323407932353
12.22132340372716
12.22132339952289
12.221323395319509
12.221323391117057
12.221323386915508
12.221323382714873
12.221323378515148
12.221323374316341
12.22132337011844
12.221323365921453
12.221323361725373
12.22132335753021
12.221323353335952
12.221323349142606
12.221323344950168
12.22132334075865
12.221323336568037
12.221323332378333
12.221323328189527
12.221323324001643
12.221323319814669
12.2213233156286
12.221323311443431
12.22132330725918
12.221323303075836
12.221323298893395
12.221323294711869
12.221323290531247
12.22132328635154
12.221323282172728
12.221323277994829
12.221323273817838
12.221323269641752
12.221323265466577
12.221323261292296
12.221323257118936
12.22132325294647
12.221323248774908
12.221323244604262
12.221323240434517
12.221323236265677
12.221323232097735
12.221323227930707
12.22132322376458
12.221323219599363
12.221323215435046
12.221323211271628
12.22132320710912
12.221323202947515
12.221323198786813
12.221323194627006
12.221323190468114
12.221323186310107
12.22132318215302
12.22132317799683
12.221323173841549
12.221323169687151
12.221323165533674
12.221323161381088
12.221323157229406
12.22132315307862
12.221323148928748
12.22132314477976
12.22132314063168
12.221323136484504
12.221323132338231
12.221323128192845
12.221323124048372
12.221323119904794
12.22132311576211
12.221323111620336
12.22132310747945
12.221323103339461
12.221323099200385
12.2213230950622
12.221323090924907
12.221323086788521
12.221323082653027
12.221323078518436
12.221323074384733
12.22132307025194
12.221323066120036
12.221323061989027
12.221323057858923
12.221323053729709
12.221323049601397
12.22132304547397
12.221323041347445
12.221323037221815
12.221323033097079
12.221323028973247
12.221323024850303
12.221323020728251
12.221323016607094
12.22132301248684
12.22132300836747
12.221323004248998
12.221323000131429
12.22132299601474
12.221322991898962
12.221322987784061
12.22132298367005
12.221322979556943
12.221322975444728
12.221322971333406
12.221322967222967
12.22132296311343
12.221322959004773
12.221322954897028
12.221322950790164
12.221322946684186
12.221322942579103
12.221322938474911
12.22132293437161
12.2213229302692
12.221322926167682
12.221322922067047
12.221322917967315
12.221322913868466
12.221322909770501
12.22132290567343
12.221322901577244
12.221322897481958
12.22132289338756
12.221322889294042
12.221322885201413
12.22132288110968
12.221322877018832
12.221322872928866
12.221322868839795
12.221322864751603
12.221322860664309
12.2213228565779
12.221322852492376
12.221322848407736
12.221322844323975
12.221322840241108
12.22132283615914
12.221322832078043
12.221322827997838
12.22132282391851
12.22132281984008
12.221322815762521
12.221322811685853
12.221322807610074
12.221322803535188
12.221322799461172
12.221322795388042
12.2213227913158
12.221322787244432
12.221322783173957
12.221322779104373
12.221322775035656
12.221322770967834
12.221322766900883
12.221322762834827
12.221322758769643
12.221322754705353
12.221322750641935
12.221322746579403
12.221322742517758
12.221322738456983
12.221322734397102
12.221322730338098
12.221322726279965
12.221322722222721
12.221322718166364
12.221322714110878
12.221322710056278
12.22132270600255
12.221322701949715
12.22132269789774
12.22132269384666
12.221322689796464
12.22132268574713
12.221322681698682
12.221322677651118
12.22132267360443
12.221322669558615
12.221322665513688
12.221322661469632
12.221322657426452
12.22132265338416
12.221322649342731
12.221322645302187
12.221322641262514
12.221322637223727
12.221322633185807
12.221322629148768
12.22132262511261
12.221322621077318
12.22132261704291
12.221322613009379
12.22132260897672
12.221322604944936
12.221322600914025
12.221322596883997
12.221322592854833
12.221322588826554
12.221322584799138
12.221322580772604
12.221322576746937
12.221322572722153
12.22132256869824
12.221322564675196
12.221322560653029
12.221322556631732
12.221322552611307
12.221322548591765
12.22132254457308
12.221322540555281
12.22132253653835
12.22132253252228
12.221322528507104
12.22132252449278
12.221322520479339
12.221322516466758
12.22132251245505
12.221322508444212
12.221322504434257
12.22132250042516
12.221322496416942
12.221322492409588
12.221322488403102
12.221322484397483
12.221322480392748
12.221322476388872
12.221322472385856
12.221322468383727
12.221322464382459
12.221322460382062
12.221322456382525
12.221322452383864
12.221322448386067
12.221322444389143
12.221322440393086
12.221322436397887
12.221322432403563
12.221322428410106
12.221322424417508
12.221322420425784
12.221322416434926
12.221322412444929
12.221322408455814
12.22132240446754
12.221322400480148
12.221322396493619
12.221322392507954
12.221322388523149
12.221322384539217

12.221322380556153
12.221322376573948
12.2213223725926
12.221322368612126
12.221322364632517
12.221322360653767
12.221322356675875
12.221322352698856
12.221322348722694
12.221322344747405
12.221322340772973
12.2213223367994
12.221322332826684
12.221322328854848
12.221322324883861
12.221322320913734
12.221322316944471
12.221322312976081
12.221322309008542
12.221322305041863
12.221322301076045
12.221322297111096
12.221322293146999
12.22132228918377
12.221322285221397
12.221322281259878
12.22132227729923
12.221322273339439
12.221322269380504
12.221322265422433
12.22132226146521
12.221322257508854
12.221322253553357
12.221322249598712
12.221322245644934
12.221322241692013
12.22132223773994
12.221322233788735
12.221322229838389
12.22132222588889
12.221322221940255
12.22132221799248
12.221322214045557
12.221322210099496
12.221322206154285
12.221322202209938
12.221322198266432
12.22132219432379
12.221322190382017
12.221322186441082
12.221322182501012
12.221322178561792
12.221322174623435
12.221322170685916
12.221322166749275
12.221322162813474
12.221322158878527
12.221322154944433
12.221322151011186
12.221322147078808
12.221322143147283
12.22132213921661
12.221322135286787
12.221322131357818
12.221322127429694
12.221322123502429
12.221322119576023
12.22132211565046
12.22132211172575
12.221322107801887
12.221322103878883
12.221322099956737
12.221322096035433
12.221322092114985
12.221322088195377
12.221322084276633
12.221322080358728
12.22132207644169
12.221322072525489
12.22132206861014
12.221322064695645
12.221322060781999
12.221322056869202
12.221322052957248
12.221322049046146
12.221322045135894
12.221322041226488
12.22132203731794
12.22132203341023
12.221322029503366
12.221322025597363
12.221322021692197
12.221322017787882
12.221322013884418
12.221322009981794
12.221322006080024
12.221322002179097
12.221321998279018
12.22132199437978
12.2213219904814
12.221321986583865
12.221321982687154
12.221321978791313
12.221321974896314
12.221321971002148
12.221321967108842
12.221321963216376
12.221321959324746
12.221321955433968
12.22132195154404
12.221321947654946
12.221321943766705
12.2213219398793
12.221321935992743
12.221321932107037
12.221321928222164
12.221321924338127
12.221321920454947
12.221321916572608
12.221321912691108
12.221321908810449
12.221321904930633
12.221321901051667
12.221321897173537
12.221321893296249
12.221321889419801
12.221321885544196
12.221321881669432
12.221321877795505
12.221321873922431
12.221321870050188
12.22132186617878
12.221321862308228
12.2213218584385
12.221321854569622
12.221321850701585
12.221321846834378
12.221321842968015
12.221321839102488
12.221321835237818
12.221321831373965
12.221321827510959
12.22132182364878
12.22132181978746
12.221321815926972
12.221321812067316
12.221321808208497
12.221321804350522
12.221321800493378
12.22132179663707
12.221321792781604
12.221321788926971
12.221321785073181
12.221321781220219
12.221321777368104
12.22132177351682
12.221321769666377
12.221321765816755
12.221321761967983
12.221321758120038
12.221321754272928
12.221321750426663
12.221321746581218
12.22132174273662
12.221321738892842
12.221321735049921
12.221321731207814
12.22132172736655
12.22132172352612
12.221321719686522
12.221321715847756
12.221321712009827
12.221321708172725
12.221321704336455
12.221321700501026
12.22132169666642
12.22132169283266
12.221321688999726
12.221321685167617
12.221321681336349
12.221321677505903
12.22132167367629
12.221321669847514
12.221321666019568
12.221321662192452
12.22132165836617
12.22132165454071
12.221321650716087
12.221321646892287
12.221321643069322
12.221321639247192
12.221321635425879
12.221321631605408
12.221321627785755
12.221321623966938
12.221321620148949
12.221321616331798
12.221321612515451
12.221321608699954
12.221321604885283
12.221321601071434
12.221321597258413
12.221321593446213
12.22132158963485
12.221321585824315
12.22132158201461
12.221321578205721
12.221321574397663
12.221321570590437
12.221321566784034
12.22132156297846
12.2213215591737
12.221321555369773
12.221321551566675
12.2213215477644
12.221321543962947
12.221321540162323
12.221321536362531
12.221321532563552
12.2213215287654
12.22132152496807
12.221321521171571
12.22132151737589
12.221321513581039
12.221321509787005
12.2213215059938
12.221321502201423
12.221321498409862
12.221321494619117
12.221321490829197
12.221321487040111
12.221321483251844
12.221321479464404
12.22132147567777
12.221321471891965
12.22132146810698
12.221321464322825
12.221321460539494
12.221321456756966
12.221321452975278
12.221321449194399
12.221321445414343
12.221321441635105
12.221321437856695
12.221321434079101
12.221321430302329
12.221321426526371
12.221321422751227
12.221321418976915
12.221321415203423
12.221321411430745
12.221321407658888
12.221321403887847
12.221321400117622
12.22132139634822
12.22132139257964
12.221321388811873
12.221321385044924
12.221321381278786
12.22132137751347
12.221321373748973
12.221321369985304
12.221321366222435
12.22132136246039
12.22132135869916
12.221321354938745
12.221321351179146
12.221321347420368
12.221321343662398
12.221321339905247
12.221321336148915
12.2213213323934
12.221321328638695
12.221321324884807
12.221321321131729
12.22132131737947
12.221321313628026
12.221321309877393
12.221321306127578
12.221321302378577
12.221321298630386
12.221321294883007
12.221321291136451
12.221321287390698
12.221321283645766
12.221321279901636
12.221321276158328
12.221321272415834
12.221321268674146
12.221321264933271
12.221321261193207
12.221321257453956
12.221321253715525
12.221321249977892
12.221321246241077
12.221321242505073
12.221321238769876
12.221321235035504
12.221321231301918
12.221321227569161
12.221321223837217
12.221321220106068
12.221321216375742
12.221321212646213
12.2213212089175
12.221321205189593
12.2213212014625
12.221321197736216
12.221321194010738
12.221321190286075
12.221321186562212
12.221321182839159
12.221321179116924
12.221321175395484
12.221321171674855
12.221321167955033
12.221321164236027
12.221321160517817
12.221321156800412
12.221321153083826
12.221321149368046
12.221321145653059
12.22132114193889
12.221321138225525
12.221321134512966
12.221321130801206
12.221321127090258
12.221321123380113
12.221321119670778
12.221321115962258
12.221321112254522
12.221321108547597
12.221321104841474
12.221321101136162
12.221321097431648
12.221321093727946
12.221321090025047
12.221321086322945
12.221321082621651
12.221321078921163
12.221321075221477
12.221321071522588
12.22132106782451
12.22132106412722
12.221321060430755
12.221321056735075
12.221321053040203
12.221321049346129
12.221321045652859
12.22132104196039
12.22132103826873
12.221321034577866
12.221321030887795
12.221321027198538
12.221321023510072
12.221321019822405
12.221321016135557
12.221321012449494
12.221321008764233
12.221321005079767
12.22132100139611
12.221320997713248
12.221320994031187
12.221320990349927
12.221320986669463
12.221320982989793
12.221320979310926
12.221320975632857
12.221320971955588
12.221320968279116
12.22132096460345
12.221320960928571
12.22132095725449
12.221320953581214
12.221320949908732
12.221320946237036
12.221320942566154
12.221320938896055
12.221320935226764
12.221320931558262
12.22132092789056
12.221320924223654
12.221320920557538
12.221320916892227
12.221320913227702
12.22132090956398
12.221320905901049
12.221320902238915
12.221320898577574
12.221320894917032
12.221320891257278
12.221320887598335
12.221320883940159
12.221320880282795
12.221320876626221
12.221320872970441
12.221320869315456
12.221320865661259
12.221320862007863
12.221320858355254
12.221320854703437
12.221320851052415
12.221320847402184
12.221320843752753
12.221320840104108
12.221320836456245
12.221320832809191
12.22132082916292
12.221320825517436
12.221320821872752
12.221320818228861
12.22132081458575
12.221320810943443
12.221320807301906
12.221320803661179
12.221320800021228
12.221320796382079
12.221320792743715
12.221320789106139
12.221320785469361
12.22132078183336
12.221320778198152
12.221320774563742
12.22132077093012
12.221320767297275
12.221320763665224
12.221320760033963
12.221320756403477
12.221320752773797
12.221320749144896
12.221320745516786
12.221320741889468
12.221320738262929
12.221320734637183
12.221320731012215
12.221320727388044
12.221320723764658
12.221320720142058
12.22132071652024
12.221320712899203
12.221320709278963
12.221320705659506
12.221320702040831
12.22132069842295
12.221320694805843
12.221320691189531
12.221320687574002
12.221320683959249
12.221320680345288
12.221320676732104
12.221320673119711
12.221320669508101
12.221320665897279
12.221320662287235
12.221320658677978
12.221320655069498
12.22132065146181
12.2213206478549
12.221320644248774
12.221320640643427
12.221320637038867
12.221320633435099
12.221320629832094
12.221320626229877
12.221320622628447
12.221320619027798
12.221320615427938
12.221320611828846
12.221320608230531
12.221320604633007
12.22132060103626
12.221320597440295
12.221320593845116
12.221320590250713
12.221320586657098
12.221320583064246
12.221320579472188
12.221320575880902
12.221320572290388
12.22132056870067
12.221320565111721
12.221320561523548
12.221320557936169
12.22132055434956
12.22132055076373
12.221320547178673
12.2213205435944
12.221320540010906
12.221320536428182
12.221320532846248
12.221320529265078
12.221320525684696
12.221320522105081
12.221320518526259
12.221320514948198
12.221320511370921
12.221320507794417
12.221320504218689
12.22132050064374
12.221320497069565
12.221320493496162
12.221320489923544
12.221320486351702
12.221320482780627
12.221320479210325
12.221320475640798
12.221320472072053
12.221320468504084
12.221320464936882
12.221320461370468
12.22132045780482
12.22132045423993
12.22132045067583
12.2213204471125
12.221320443549946
12.221320439988169
12.22132043642716
12.221320432866928
12.221320429307463
12.221320425748772
12.221320422190855
12.2213204186337
12.221320415077331
12.221320411521726
12.221320407966903
12.221320404412838
12.221320400859554
12.22132039730704
12.221320393755288
12.221320390204319
12.221320386654108
12.221320383104675
12.221320379556015
12.221320376008126
12.221320372461001
12.221320368914645
12.221320365369065
12.221320361824253
12.221320358280208
12.221320354736934
12.221320351194429
12.221320347652698
12.221320344111724
12.221320340571525
12.221320337032099
12.221320333493429
12.221320329955535
12.221320326418416
12.221320322882057
12.221320319346468
12.22132031581164
12.221320312277578
12.221320308744287
12.221320305211771
12.22132030168001
12.221320298149019
12.221320294618796
12.221320291089345
12.221320287560651
12.221320284032723
12.221320280505564
12.221320276979172
12.221320273453543
12.221320269928679
12.221320266404582
12.221320262881248
12.221320259358684
12.221320255836883
12.221320252315843
12.221320248795562
12.221320245276058
12.221320241757311
12.221320238239322
12.221320234722102
12.221320231205642
12.221320227689954

12.221320224175027
12.221320220660845
12.221320217147452
12.221320213634808
12.22132021012293
12.221320206611816
12.221320203101456
12.221320199591867
12.221320196083033
12.221320192574959
12.22132018906766
12.221320185561105
12.221320182055313
12.221320178550293
12.221320175046039
12.221320171542521
12.22132016803979
12.221320164537797
12.221320161036575
12.221320157536116
12.221320154036416
12.221320150537466
12.221320147039282
12.221320143541853
12.221320140045199
12.221320136549288
12.22132013305414
12.221320129559746
12.221320126066116
12.221320122573244
12.221320119081135
12.221320115589783
12.221320112099173
12.221320108609333
12.221320105120245
12.221320101631918
12.22132009814435
12.221320094657543
12.221320091171476
12.221320087686186
12.221320084201645
12.22132008071785
12.221320077234832
12.221320073752553
12.221320070271034
12.221320066790277
12.221320063310268
12.221320059831006
12.221320056352507
12.221320052874784
12.22132004939778
12.221320045921557
12.221320042446079
12.221320038971351
12.221320035497385
12.221320032024167
12.221320028551709
12.221320025080011
12.221320021609044
12.221320018138845
12.2213200146694
12.221320011200705
12.22132000773276
12.221320004265575
12.221320000799135
12.221319997333453
12.221319993868525
12.221319990404337
12.221319986940912
12.221319983478239
12.221319980016316
12.221319976555142
12.221319973094724
12.22131996963505
12.221319966176134
12.221319962717963
12.221319959260544
12.22131995580387
12.221319952347958
12.221319948892786
12.221319945438367
12.2213199419847
12.221319938531783
12.221319935079613
12.2213199316282
12.22131992817753
12.221319924727608
12.221319921278427
12.221319917830005
12.221319914382327
12.221319910935403
12.221319907489226
12.221319904043794
12.221319900599106
12.22131989715517
12.221319893711986
12.221319890269543
12.221319886827851
12.221319883386906
12.22131987994671
12.221319876507252
12.221319873068541
12.221319869630587
12.221319866193376
12.221319862756904
12.22131985932118
12.221319855886204
12.221319852451968
12.221319849018489
12.221319845585747
12.221319842153754
12.221319838722506
12.221319835291991
12.221319831862234
12.221319828433218
12.221319825004947
12.22131982157742
12.221319818150636
12.221319814724593
12.221319811299297
12.221319807874742
12.221319804450935
12.22131980102787
12.221319797605553
12.221319794183964
12.221319790763133
12.221319787343033
12.221319783923676
12.221319780505063
12.221319777087194
12.221319773670063
12.221319770253679
12.221319766838036
12.221319763423136
12.221319760008964
12.221319756595546
12.22131975318287
12.22131974977093
12.221319746359725
12.221319742949268
12.22131973953956
12.221319736130576
12.221319732722339
12.221319729314837
12.221319725908078
12.22131972250206
12.221319719096781
12.22131971569224
12.22131971228844
12.221319708885375
12.22131970548305
12.221319702081466
12.221319698680615
12.221319695280505
12.221319691881135
12.221319688482504
12.221319685084607
12.221319681687447
12.221319678291025
12.22131967489534
12.221319671500398
12.221319668106181
12.221319664712714
12.221319661319972
12.221319657927971
12.221319654536705
12.221319651146176
12.221319647756392
12.221319644367334
12.221319640979008
12.221319637591417
12.221319634204573
12.221319630818465
12.221319627433072
12.221319624048428
12.221319620664527
12.221319617281344
12.221319613898903
12.221319610517188
12.221319607136225
12.22131960375598
12.221319600376471
12.221319596997706
12.22131959361966
12.22131959024235
12.221319586865782
12.221319583489938
12.221319580114837
12.221319576740466
12.221319573366818
12.221319569993904
12.221319566621725
12.22131956325028
12.22131955987957
12.221319556509581
12.221319553140328
12.221319549771815
12.221319546404017
12.221319543036962
12.221319539670636
12.221319536305039
12.221319532940173
12.221319529576038
12.221319526212625
12.221319522849953
12.221319519488011
12.221319516126801
12.221319512766305
12.221319509406545
12.221319506047521
12.221319502689225
12.221319499331651
12.221319495974807
12.221319492618695
12.221319489263315
12.221319485908655
12.22131948255472
12.221319479201524
12.221319475849059
12.221319472497312
12.221319469146295
12.221319465795998
12.221319462446438
12.221319459097607
12.221319455749494
12.221319452402112
12.221319449055455
12.221319445709533
12.221319442364322
12.22131943901985
12.221319435676103
12.22131943233308
12.221319428990771
12.2213194256492
12.221319422308355
12.22131941896823
12.221319415628832
12.221319412290155
12.221319408952215
12.221319405614983
12.221319402278478
12.221319398942704
12.221319395607647
12.221319392273324
12.221319388939726
12.221319385606845
12.221319382274688
12.221319378943244
12.221319375612541
12.221319372282544
12.221319368953287
12.221319365624746
12.221319362296923
12.221319358969822
12.221319355643447
12.22131935231779
12.221319348992857
12.221319345668652
12.221319342345163
12.22131933902239
12.221319335700342
12.221319332379018
12.221319329058412
12.221319325738536
12.221319322419369
12.221319319100923
12.2213193157832
12.221319312466196
12.221319309149916
12.221319305834355
12.221319302519513
12.221319299205387
12.221319295891986
12.221319292579297
12.221319289267326
12.221319285956085
12.221319282645553
12.221319279335741
12.221319276026653
12.221319272718278
12.22131926941063
12.221319266103686
12.221319262797461
12.221319259491967
12.221319256187185
12.221319252883115
12.221319249579762
12.221319246277135
12.221319242975209
12.221319239674019
12.22131923637353
12.221319233073759
12.221319229774705
12.221319226476377
12.221319223178758
12.221319219881854
12.221319216585666
12.221319213290196
12.221319209995444
12.221319206701395
12.22131920340808
12.221319200115465
12.221319196823561
12.221319193532382
12.22131919024191
12.221319186952156
12.221319183663116
12.221319180374792
12.221319177087175
12.22131917380028
12.221319170514093
12.221319167228618
12.221319163943866
12.221319160659815
12.221319157376483
12.221319154093866
12.221319150811958
12.221319147530755
12.221319144250279
12.22131914097051
12.22131913769144
12.221319134413097
12.22131913113546
12.22131912785853
12.221319124582324
12.221319121306824
12.22131911803202
12.221319114757945
12.22131911148458
12.221319108211915
12.221319104939962
12.22131910166873
12.221319098398197
12.221319095128385
12.221319091859272
12.221319088590866
12.221319085323183
12.221319082056196
12.221319078789922
12.221319075524361
12.221319072259503
12.221319068995358
12.221319065731924
12.221319062469185
12.221319059207168
12.221319055945857
12.221319052685253
12.22131904942536
12.221319046166165
12.221319042907682
12.221319039649906
12.221319036392835
12.221319033136469
12.221319029880819
12.221319026625876
12.22131902337164
12.221319020118093
12.22131901686527
12.221319013613142
12.221319010361727
12.221319007111012
12.221319003861005
12.221319000611711
12.221318997363122
12.221318994115228
12.221318990868042
12.22131898762156
12.221318984375783
12.22131898113071
12.221318977886341
12.221318974642688
12.221318971399722
12.221318968157464
12.221318964915916
12.221318961675077
12.221318958434924
12.221318955195489
12.221318951956748
12.221318948718718
12.22131894548138
12.221318942244753
12.221318939008823
12.221318935773594
12.22131893253908
12.221318929305257
12.221318926072138
12.221318922839723
12.221318919608011
12.221318916376989
12.22131891314668
12.22131890991707
12.221318906688158
12.22131890345995
12.221318900232442
12.221318897005636
12.221318893779523
12.221318890554123
12.221318887329414
12.2213188841054
12.2213188808821
12.221318877659492
12.221318874437582
12.221318871216374
12.221318867995857
12.22131886477605
12.22131886155693
12.22131885833853
12.22131885512081
12.22131885190379
12.221318848687474
12.221318845471858
12.221318842256931
12.221318839042699
12.221318835829187
12.221318832616351
12.221318829404217
12.221318826192782
12.221318822982044
12.221318819772002
12.221318816562661
12.22131881335401
12.221318810146068
12.221318806938806
12.221318803732252
12.22131880052638
12.221318797321212
12.221318794116748
12.221318790912973
12.22131878770988
12.221318784507503
12.22131878130581
12.221318778104814
12.221318774904521
12.221318771704913
12.221318768506004
12.221318765307783
12.221318762110265
12.221318758913434
12.221318755717299
12.221318752521864
12.2213187493271
12.22131874613305
12.221318742939683
12.221318739747028
12.221318736555055
12.221318733363768
12.221318730173174
12.221318726983274
12.221318723794065
12.221318720605558
12.221318717417745
12.221318714230618
12.221318711044177
12.221318707858433
12.221318704673376
12.221318701489022
12.221318698305348
12.221318695122363
12.221318691940082
12.221318688758474
12.221318685577568
12.221318682397355
12.221318679217822
12.221318676038994
12.221318672860832
12.221318669683379
12.221318666506615
12.221318663330536
12.221318660155147
12.22131865698045
12.221318653806431
12.221318650633116
12.221318647460482
12.221318644288539
12.22131864111728
12.22131863794672
12.221318634776834
12.221318631607643
12.221318628439139
12.221318625271321
12.221318622104185
12.221318618937762
12.221318615771995
12.22131861260694
12.221318609442557
12.221318606278858
12.221318603115849
12.221318599953538
12.221318596791903
12.221318593630956
12.221318590470693
12.221318587311123
12.221318584152232
12.221318580994023
12.221318577836504
12.221318574679678
12.22131857152353
12.221318568368067
12.221318565213293
12.221318562059198
12.221318558905796
12.221318555753063
12.221318552601026
12.22131854944967
12.221318546298994
12.22131854314901
12.221318539999713
12.221318536851092
12.22131853370315
12.221318530555896
12.221318527409327
12.221318524263442
12.221318521118238
12.221318517973714
12.221318514829873
12.221318511686716
12.221318508544243
12.221318505402444

12.221318502261335
12.221318499120908
12.22131849598116
12.221318492842098
12.221318489703707
12.221318486566002
12.221318483428979
12.221318480292641
12.221318477156979
12.221318474021993
12.221318470887704
12.221318467754081
12.221318464621138
12.221318461488883
12.221318458357302
12.221318455226404
12.221318452096178
12.221318448966638
12.221318445837772
12.221318442709597
12.221318439582094
12.221318436455267
12.221318433329118
12.221318430203647
12.221318427078865
12.22131842395475
12.22131842083132
12.22131841770857
12.221318414586486
12.221318411465091
12.221318408344365
12.22131840522432
12.221318402104957
12.221318398986265
12.221318395868247
12.221318392750918
12.22131838963425
12.221318386518275
12.221318383402958
12.221318380288329
12.221318377174372
12.221318374061092
12.22131837094849
12.221318367836568
12.221318364725313
12.221318361614738
12.221318358504835
12.221318355395606
12.221318352287055
12.221318349179173
12.221318346071977
12.22131834296545
12.221318339859593
12.221318336754413
12.2213183336499
12.22131833054607
12.221318327442914
12.221318324340423
12.221318321238615
12.221318318137488
12.22131831503701
12.221318311937226
12.2213183088381
12.221318305739652
12.221318302641883
12.221318299544775
12.221318296448347
12.221318293352583
12.221318290257503
12.221318287163086
12.221318284069342
12.221318280976279
12.221318277883872
12.221318274792138
12.221318271701088
12.221318268610705
12.221318265520985
12.221318262431943
12.221318259343565
12.22131825625586
12.221318253168828
12.221318250082458
12.221318246996768
12.221318243911744
12.221318240827385
12.221318237743699
12.22131823466068
12.221318231578332
12.221318228496669
12.221318225415645
12.221318222335311
12.221318219255643
12.221318216176643
12.221318213098302
12.221318210020643
12.221318206943643
12.221318203867307
12.22131820079164
12.221318197716647
12.221318194642315
12.22131819156865
12.221318188495662
12.221318185423332
12.221318182351675
12.221318179280683
12.221318176210353
12.221318173140688
12.2213181700717
12.221318167003371
12.221318163935717
12.221318160868703
12.221318157802383
12.22131815473671
12.221318151671719
12.221318148607383
12.22131814554371
12.221318142480708
12.221318139418365
12.221318136356693
12.221318133295684
12.221318130235344
12.221318127175664
12.221318124116642
12.22131812105828
12.221318118000596
12.221318114943571
12.221318111887205
12.221318108831507
12.221318105776474
12.221318102722098
12.221318099668391
12.22131809661534
12.221318093562955
12.22131809051123
12.22131808746017
12.221318084409775
12.221318081360037
12.22131807831097
12.221318075262557
12.221318072214812
12.221318069167717
12.221318066121295
12.221318063075524
12.221318060030422
12.221318056985975
12.221318053942195
12.221318050899077
12.221318047856611
12.221318044814806
12.221318041773666
12.221318038733191
12.22131803569336
12.221318032654207
12.2213180296157
12.221318026577862
12.22131802354067
12.221318020504157
12.221318017468286
12.221318014433079
12.22131801139853
12.22131800836465
12.221318005331417
12.22131800229884
12.221317999266924
12.221317996235681
12.221317993205071
12.221317990175136
12.221317987145857
12.221317984117231
12.221317981089259
12.221317978061952
12.2213179750353
12.221317972009306
12.221317968983971
12.221317965959285
12.221317962935252
12.221317959911893
12.221317956889175
12.221317953867121
12.221317950845723
12.221317947824966
12.221317944804884
12.221317941785447
12.221317938766667
12.221317935748544
12.22131793273107
12.221317929714262
12.221317926698093
12.221317923682598
12.221317920667754
12.221317917653554
12.221317914640009
12.22131791162713
12.221317908614894
12.221317905603316
12.221317902592382
12.221317899582107
12.221317896572497
12.22131789356353
12.221317890555218
12.221317887547556
12.221317884540554
12.221317881534198
12.221317878528493
12.221317875523445
12.221317872519048
12.22131786951531
12.221317866512203
12.221317863509766
12.221317860507977
12.22131785750684
12.221317854506356
12.221317851506527
12.22131784850734
12.221317845508805
12.22131784251092
12.221317839513691
12.221317836517109
12.221317833521177
12.221317830525903
12.221317827531273
12.22131782453729
12.221317821543964
12.221317818551281
12.221317815559242
12.221317812567868
12.221317809577128
12.22131780658704
12.221317803597614
12.221317800608828
12.22131779762069
12.221317794633203
12.221317791646364
12.221317788660166
12.221317785674625
12.221317782689736
12.221317779705485
12.221317776721882
12.221317773738928
12.221317770756626
12.221317767774972
12.22131776479396
12.221317761813594
12.221317758833877
12.221317755854804
12.221317752876388
12.221317749898606
12.221317746921478
12.221317743944994
12.221317740969152
12.221317737993958
12.22131773501941
12.221317732045513
12.221317729072263
12.221317726099647
12.22131772312768
12.221317720156364
12.221317717185697
12.221317714215663
12.221317711246277
12.22131770827753
12.221317705309438
12.221317702341986
12.221317699375176
12.221317696409013
12.221317693443494
12.221317690478612
12.221317687514375
12.221317684550787
12.221317681587852
12.221317678625539
12.221317675663888
12.221317672702869
12.22131766974249
12.221317666782754
12.22131766382366
12.221317660865214
12.221317657907411
12.221317654950248
12.221317651993726
12.22131764903785
12.221317646082607
12.221317643128002
12.221317640174043
12.221317637220737
12.221317634268063
12.221317631316033
12.221317628364641
12.22131762541389
12.221317622463772
12.221317619514306
12.221317616565473
12.221317613617291
12.221317610669736
12.221317607722828
12.22131760477655
12.221317601830918
12.221317598885923
12.221317595941567
12.221317592997858
12.221317590054781
12.22131758711235
12.221317584170556
12.221317581229384
12.221317578288863
12.221317575348982
12.221317572409742
12.221317569471134
12.22131756653316
12.22131756359583
12.221317560659138
12.221317557723085
12.221317554787666
12.22131755185288
12.221317548918734
12.221317545985231
12.221317543052349
12.221317540120125
12.221317537188522
12.221317534257565
12.22131753132723
12.221317528397547
12.221317525468493
12.22131752254008
12.221317519612297
12.221317516685145
12.221317513758635
12.22131751083276
12.22131750790752
12.221317504982903
12.221317502058936
12.221317499135596
12.221317496212901
12.221317493290826
12.221317490369392
12.221317487448598
12.221317484528422
12.221317481608898
12.221317478689997
12.22131747577173
12.221317472854096
12.2213174699371
12.22131746702073
12.221317464105006
12.221317461189907
12.22131745827543
12.221317455361598
12.2213174524484
12.221317449535833
12.221317446623896
12.221317443712588
12.221317440801915
12.221317437891877
12.221317434982465
12.221317432073683
12.221317429165543
12.221317426258024
12.22131742335114
12.22131742044488
12.221317417539263
12.221317414634266
12.22131741172991
12.221317408826181
12.221317405923076
12.2213174030206
12.221317400118771
12.221317397217547
12.221317394316971
12.221317391417022
12.221317388517695
12.221317385619006
12.221317382720935
12.221317379823498
12.221317376926695
12.221317374030518
12.221317371134978
12.221317368240047
12.221317365345762
12.221317362452096
12.22131735955906
12.221317356666649
12.221317353774868
12.221317350883718
12.221317347993187
12.221317345103294
12.221317342214036
12.221317339325381
12.221317336437362
12.221317333549981
12.221317330663215
12.22131732777708
12.22131732489157
12.221317322006682
12.221317319122427
12.22131731623879
12.221317313355781
12.221317310473415
12.221317307591653
12.221317304710535
12.221317301830027
12.22131729895015
12.221317296070888
12.221317293192264
12.221317290314273
12.221317287436886
12.221317284560136
12.221317281684003
12.221317278808492
12.221317275933613
12.221317273059357
12.221317270185725
12.22131726731271
12.221317264440325
12.221317261568563
12.221317258697422
12.22131725582691
12.221317252957018
12.221317250087745
12.221317247219098
12.22131724435108
12.221317241483668
12.221317238616884
12.221317235750735
12.2213172328852
12.221317230020286
12.221317227155998
12.221317224292324
12.22131722142927
12.221317218566842
12.221317215705046
12.221317212843857
12.221317209983294
12.221317207123349
12.221317204264032
12.221317201405324
12.221317198547244
12.221317195689787
12.221317192832949
12.221317189976729
12.22131718712112
12.221317184266146
12.22131718141178
12.221317178558051
12.221317175704916
12.221317172852414
12.221317170000535
12.221317167149266
12.221317164298625
12.221317161448596
12.221317158599183
12.221317155750398
12.221317152902229
12.221317150054672
12.221317147207735
12.221317144361418
12.221317141515726
12.221317138670644
12.221317135826176
12.221317132982328
12.221317130139097
12.22131712729648
12.221317124454487
12.22131712161311
12.221317118772355
12.221317115932202
12.221317113092677
12.221317110253759
12.221317107415459
12.221317104577773
12.221317101740713
12.221317098904265
12.221317096068434
12.22131709323322
12.221317090398617
12.22131708756463
12.221317084731256
12.221317081898501
12.221317079066356
12.221317076234824
12.221317073403918
12.221317070573608
12.221317067743936
12.221317064914858
12.221317062086412
12.22131705925856
12.221317056431337
12.221317053604722
12.221317050778723
12.221317047953333
12.22131704512856
12.221317042304397
12.221317039480844
12.221317036657908
12.221317033835597
12.221317031013884
12.221317028192786
12.221317025372297
12.221317022552427
12.221317019733167
12.221317016914512
12.22131701409647
12.221317011279044
12.22131700846223
12.221317005646034
12.22131700283044
12.221317000015459
12.22131699720109
12.221316994387333
12.221316991574186
12.221316988761643
12.221316985949716
12.221316983138395
12.22131698032769
12.221316977517601
12.221316974708108
12.221316971899226
12.221316969090964
12.221316966283313
12.221316963476262
12.221316960669823
12.22131695786399
12.221316955058771
12.221316952254156
12.221316949450154
12.221316946646759
12.221316943843975
12.221316941041794
12.22131693824023
12.221316935439273
12.221316932638912
12.22131692983917
12.221316927040029
12.221316924241494
12.221316921443577
12.221316918646261
12.221316915849556
12.221316913053455
12.22131691025795
12.22131690746306
12.221316904668786
12.22131690187511
12.221316899082042
12.22131689628958

12.221316893497724
12.221316890706472
12.221316887915828
12.221316885125788
12.221316882336351
12.221316879547523
12.22131687675931
12.221316873971693
12.221316871184683
12.221316868398269
12.221316865612469
12.221316862827274
12.22131686004268
12.221316857258689
12.221316854475306
12.221316851692523
12.221316848910345
12.221316846128774
12.221316843347806
12.221316840567438
12.22131683778768
12.221316835008519
12.221316832229967
12.221316829452014
12.221316826674663
12.22131682389792
12.221316821121768
12.221316818346224
12.221316815571292
12.221316812796957
12.221316810023218
12.22131680725009
12.221316804477558
12.221316801705628
12.2213167989343
12.22131679616358
12.221316793393447
12.221316790623924
12.221316787855004
12.221316785086685
12.22131678231897
12.22131677955185
12.221316776785333
12.221316774019412
12.221316771254092
12.221316768489375
12.221316765725266
12.221316762961745
12.221316760198826
12.221316757436508
12.221316754674794
12.221316751913664
12.22131674915315
12.221316746393232
12.221316743633912
12.22131674087519
12.221316738117064
12.221316735359533
12.221316732602613
12.22131672984629
12.221316727090551
12.221316724335422
12.221316721580884
12.221316718826943
12.221316716073604
12.221316713320872
12.221316710568729
12.221316707817179
12.221316705066231
12.221316702315887
12.221316699566122
12.221316696816967
12.221316694068406
12.221316691320446
12.22131668857307
12.221316685826299
12.22131668308013
12.221316680334548
12.221316677589565
12.221316674845173
12.221316672101386
12.221316669358185
12.221316666615586
12.221316663873582
12.221316661132171
12.22131665839135
12.221316655651133
12.221316652911506
12.22131665017248
12.221316647434035
12.221316644696197
12.221316641958945
12.221316639222291
12.22131663648623
12.221316633750773
12.2213166310159
12.22131662828162
12.221316625547935
12.221316622814845
12.22131662008234
12.22131661735044
12.221316614619116
12.221316611888396
12.221316609158267
12.221316606428744
12.221316603699803
12.221316600971448
12.221316598243684
12.221316595516518
12.22131659278995
12.221316590063962
12.221316587338574
12.221316584613778
12.221316581889567
12.22131657916595
12.221316576442925
12.221316573720495
12.22131657099865
12.221316568277398
12.22131656555674
12.221316562836671
12.221316560117183
12.221316557398293
12.221316554679996
12.221316551962275
12.221316549245165
12.221316546528627
12.221316543812687
12.22131654109734
12.22131653838257
12.221316535668397
12.22131653295482
12.221316530241817
12.221316527529417
12.221316524817592
12.221316522106378
12.22131651939573
12.221316516685675
12.221316513976218
12.221316511267341
12.221316508559049
12.221316505851345
12.221316503144239
12.221316500437714
12.221316497731772
12.221316495026425
12.221316492321662
12.221316489617486
12.221316486913896
12.221316484210895
12.221316481508486
12.221316478806658
12.221316476105404
12.22131647340475
12.221316470704684
12.221316468005197
12.221316465306307
12.221316462607986
12.221316459910266
12.221316457213122
12.221316454516561
12.221316451820591
12.221316449125213
12.22131644643041
12.221316443736194
12.221316441042568
12.22131643834952
12.221316435657068
12.221316432965182
12.22131643027389
12.221316427583188
12.221316424893056
12.221316422203513
12.221316419514565
12.221316416826182
12.221316414138391
12.22131641145119
12.221316408764562
12.221316406078527
12.221316403393075
12.2213164007082
12.221316398023903
12.221316395340198
12.22131639265706
12.221316389974522
12.221316387292562
12.22131638461119
12.22131638193039
12.221316379250174
12.221316376570535
12.221316373891492
12.221316371213014
12.221316368535122
12.221316365857811
12.221316363181087
12.221316360504947
12.22131635782938
12.221316355154398
12.221316352479992
12.221316349806168
12.221316347132923
12.221316344460263
12.221316341788182
12.221316339116678
12.221316336445756
12.221316333775404
12.221316331105646
12.221316328436462
12.22131632576786
12.221316323099835
12.221316320432388
12.221316317765517
12.221316315099232
12.221316312433524
12.221316309768394
12.221316307103837
12.221316304439856
12.221316301776465
12.221316299113647
12.22131629645141
12.221316293789751
12.221316291128664
12.22131628846815
12.22131628580822
12.221316283148871
12.221316280490095
12.22131627783189
12.221316275174273
12.22131627251723
12.221316269860758
12.221316267204868
12.221316264549555
12.221316261894819
12.221316259240654
12.22131625658707
12.22131625393406
12.221316251281628
12.221316248629774
12.221316245978484
12.221316243327783
12.221316240677641
12.22131623802809
12.221316235379112
12.221316232730704
12.22131623008287
12.22131622743561
12.221316224788936
12.221316222142823
12.221316219497286
12.221316216852324
12.22131621420794
12.22131621156413
12.22131620892089
12.22131620627823
12.221316203636132
12.221316200994622
12.221316198353671
12.22131619571331
12.221316193073509
12.221316190434287
12.221316187795626
12.221316185157544
12.22131618252005
12.221316179883107
12.221316177246745
12.221316174610966
12.22131617197574
12.221316169341096
12.221316166707025
12.221316164073519
12.221316161440598
12.22131615880823
12.221316156176451
12.22131615354523
12.221316150914586
12.221316148284515
12.221316145655011
12.221316143026078
12.221316140397716
12.221316137769927
12.221316135142702
12.221316132516053
12.22131612988997
12.22131612726446
12.221316124639516
12.221316122015141
12.221316119391352
12.221316116768119
12.221316114145456
12.221316111523354
12.221316108901837
12.221316106280879
12.22131610366049
12.221316101040673
12.221316098421429
12.221316095802745
12.221316093184631
12.221316090567091
12.221316087950113
12.2213160853337
12.221316082717866
12.221316080102598
12.221316077487888
12.221316074873755
12.221316072260182
12.221316069647182
12.221316067034746
12.221316064422881
12.22131606181158
12.221316059200843
12.221316056590677
12.221316053981079
12.221316051372044
12.221316048763574
12.22131604615567
12.221316043548338
12.221316040941565
12.221316038335356
12.221316035729721
12.221316033124642
12.221316030520134
12.221316027916192
12.22131602531282
12.221316022710008
12.22131602010776
12.221316017506076
12.221316014904954
12.221316012304404
12.221316009704406
12.221316007104996
12.221316004506125
12.221316001907834
12.221315999310107
12.221315996712933
12.221315994116324
12.221315991520283
12.221315988924802
12.221315986329891
12.221315983735538
12.221315981141753
12.22131597854853
12.221315975955859
12.221315973363767
12.22131597077223
12.221315968181255
12.221315965590842
12.22131596300099
12.221315960411708
12.221315957822977
12.221315955234815
12.22131595264721
12.221315950060166
12.221315947473695
12.22131594488778
12.221315942302422
12.221315939717627
12.221315937133388
12.221315934549715
12.22131593196661
12.221315929384051
12.22131592680206
12.221315924220628
12.221315921639768
12.221315919059448
12.221315916479703
12.221315913900508
12.22131591132188
12.221315908743813
12.2213159061663
12.221315903589348
12.22131590101295
12.221315898437117
12.221315895861853
12.221315893287128
12.221315890712974
12.221315888139372
12.221315885566336
12.221315882993853
12.22131588042194
12.221315877850575
12.221315875279762
12.22131587270952
12.221315870139826
12.221315867570688
12.221315865002117
12.221315862434105
12.221315859866642
12.22131585729974
12.221315854733396
12.221315852167606
12.221315849602378
12.221315847037703
12.221315844473585
12.221315841910014
12.221315839347016
12.221315836784564
12.22131583422267
12.221315831661332
12.221315829100552
12.221315826540328
12.221315823980659
12.22131582142155
12.221315818862985
12.221315816304982
12.221315813747541
12.221315811190644
12.221315808634301
12.221315806078522
12.221315803523291
12.22131580096862
12.221315798414507
12.221315795860933
12.22131579330793
12.221315790755478
12.221315788203581
12.22131578565223
12.221315783101426
12.221315780551185
12.2213157780015
12.221315775452362
12.221315772903779
12.221315770355758
12.221315767808287
12.221315765261352
12.221315762715001
12.22131576016917
12.221315757623914
12.221315755079202
12.221315752535043
12.221315749991437
12.221315747448386
12.22131574490588
12.221315742363926
12.221315739822531
12.221315737281685
12.221315734741394
12.22131573220164
12.22131572966245
12.221315727123816
12.221315724585718
12.221315722048173
12.221315719511185
12.221315716974747
12.22131571443886
12.221315711903516
12.22131570936874
12.221315706834503
12.221315704300803
12.221315701767669
12.221315699235085
12.221315696703048
12.221315694171565
12.221315691640614
12.221315689110234
12.221315686580391
12.221315684051099
12.221315681522354
12.221315678994163
12.221315676466517
12.221315673939415
12.221315671412873
12.221315668886875
12.221315666361429
12.221315663836524
12.221315661312172
12.221315658788358
12.221315656265102
12.22131565374239
12.221315651220229
12.221315648698614
12.221315646177544
12.221315643657023
12.221315641137044
12.221315638617614
12.221315636098735
12.221315633580405
12.22131563106262
12.221315628545373
12.221315626028677
12.221315623512533
12.221315620996933
12.22131561848187
12.221315615967367
12.221315613453399
12.221315610939975
12.221315608427112
12.221315605914775
12.221315603402996
12.221315600891762
12.22131559838107
12.221315595870916
12.221315593361316
12.22131559085225
12.221315588343742
12.221315585835768
12.221315583328346
12.22131558082146
12.221315578315123
12.221315575809339
12.221315573304086
12.22131557079938
12.221315568295218
12.221315565791604
12.221315563288528
12.221315560786
12.221315558284017
12.221315555782564
12.221315553281666
12.221315550781311
12.221315548281494
12.221315545782215
12.221315543283486
12.221315540785298
12.221315538287646
12.221315535790538
12.221315533293984
12.221315530797966
12.221315528302483
12.221315525807546
12.221315523313153
12.221315520819298
12.221315518325978
12.22131551583321
12.22131551334098
12.221315510849287
12.221315508358137
12.221315505867533
12.221315503377463
12.22131550088794
12.221315498398955
12.221315495910504
12.221315493422598
12.221315490935233
12.221315488448397
12.221315485962112
12.221315483476367
12.221315480991164
12.221315478506487

12.221315476022367
12.22131547353878
12.221315471055721
12.221315468573213
12.221315466091234
12.221315463609802
12.221315461128905
12.221315458648549
12.221315456168726
12.221315453689444
12.221315451210707
12.22131544873251
12.221315446254833
12.221315443777703
12.22131544130112
12.221315438825064
12.221315436349547
12.22131543387457
12.221315431400127
12.22131542892622
12.221315426452852
12.221315423980025
12.221315421507727
12.221315419035966
12.221315416564751
12.221315414094061
12.221315411623918
12.221315409154297
12.221315406685221
12.221315404216684
12.221315401748683
12.221315399281211
12.221315396814274
12.221315394347881
12.221315391882017
12.221315389416688
12.221315386951902
12.221315384487637
12.221315382023912
12.221315379560739
12.22131537709807
12.221315374635964
12.22131537217437
12.221315369713324
12.2213153672528
12.221315364792828
12.22131536233338
12.221315359874469
12.22131535741608
12.221315354958236
12.221315352500921
12.221315350044142
12.221315347587893
12.221315345132187
12.221315342677
12.221315340222349
12.221315337768237
12.221315335314658
12.22131533286161
12.221315330409091
12.22131532795711
12.221315325505651
12.221315323054734
12.22131532060434
12.221315318154486
12.221315315705159
12.221315313256364
12.221315310808107
12.22131530836038
12.221315305913173
12.221315303466504
12.22131530102037
12.221315298574766
12.221315296129683
12.221315293685146
12.221315291241133
12.221315288797642
12.221315286354695
12.221315283912267
12.221315281470378
12.22131527902902
12.221315276588182
12.221315274147882
12.221315271708104
12.22131526926886
12.22131526683015
12.221315264391967
12.221315261954313
12.221315259517185
12.221315257080578
12.221315254644514
12.22131525220897
12.221315249773962
12.221315247339477
12.221315244905531
12.221315242472093
12.221315240039202
12.221315237606829
12.221315235174988
12.221315232743668
12.22131523031288
12.221315227882618
12.221315225452893
12.221315223023689
12.221315220595011
12.221315218166858
12.221315215739239
12.221315213312144
12.221315210885573
12.221315208459533
12.221315206034015
12.221315203609027
12.221315201184561
12.221315198760617
12.221315196337212
12.22131519391433
12.221315191491978
12.221315189070143
12.22131518664883
12.221315184228047
12.22131518180779
12.221315179388057
12.22131517696886
12.221315174550174
12.221315172132016
12.221315169714382
12.221315167297282
12.221315164880696
12.22131516246464
12.221315160049109
12.221315157634105
12.221315155219614
12.221315152805653
12.221315150392217
12.221315147979308
12.221315145566916
12.22131514315505
12.22131514074371
12.221315138332896
12.221315135922596
12.221315133512825
12.221315131103573
12.221315128694853
12.221315126286646
12.22131512387897
12.221315121471802
12.221315119065169
12.22131511665906
12.221315114253464
12.22131511184839
12.22131510944386
12.221315107039823
12.22131510463632
12.221315102233339
12.221315099830887
12.22131509742894
12.221315095027524
12.221315092626634
12.221315090226252
12.221315087826401
12.221315085427074
12.221315083028264
12.221315080629966
12.221315078232193
12.221315075834948
12.221315073438216
12.221315071042003
12.221315068646321
12.221315066251142
12.221315063856498
12.221315061462361
12.221315059068749
12.221315056675659
12.221315054283103
12.221315051891041
12.221315049499506
12.221315047108494
12.221315044717997
12.22131504232802
12.221315039938569
12.221315037549626
12.221315035161204
12.221315032773305
12.221315030385917
12.221315027999056
12.221315025612707
12.221315023226879
12.221315020841573
12.221315018456773
12.221315016072495
12.221315013688738
12.221315011305496
12.22131500892277
12.221315006540562
12.221315004158871
12.221315001777706
12.221314999397048
12.221314997016911
12.221314994637286
12.221314992258181
12.221314989879588
12.221314987501515
12.221314985123952
12.221314982746911
12.221314980370387
12.221314977994378
12.221314975618888
12.221314973243906
12.221314970869447
12.221314968495498
12.22131496612207
12.22131496374915
12.221314961376745
12.221314959004852
12.221314956633481
12.221314954262628
12.221314951892278
12.221314949522458
12.221314947153141
12.221314944784348
12.221314942416056
12.22131494004829
12.221314937681022
12.221314935314286
12.22131493294805
12.221314930582343
12.221314928217131
12.221314925852443
12.221314923488267
12.221314921124602
12.221314918761449
12.22131491639882
12.22131491403669
12.221314911675078
12.221314909313977
12.221314906953387
12.22131490459332
12.221314902233745
12.221314899874702
12.221314897516162
12.221314895158137
12.221314892800615
12.221314890443617
12.221314888087134
12.221314885731152
12.221314883375678
12.221314881020728
12.221314878666282
12.22131487631235
12.22131487395892
12.22131487160601
12.221314869253606
12.22131486690171
12.22131486455033
12.221314862199458
12.221314859849098
12.221314857499241
12.221314855149906
12.221314852801083
12.221314850452757
12.22131484810494
12.221314845757645
12.221314843410852
12.221314841064565
12.221314838718795
12.221314836373525
12.221314834028774
12.22131483168453
12.221314829340788
12.221314826997563
12.221314824654835
12.221314822312626
12.221314819970923
12.22131481762972
12.22131481528904
12.221314812948865
12.221314810609192
12.221314808270025
12.221314805931367
12.221314803593225
12.22131480125559
12.221314798918447
12.221314796581815
12.221314794245709
12.221314791910102
12.22131478957499
12.221314787240395
12.221314784906301
12.221314782572714
12.221314780239632
12.22131477790706
12.221314775574989
12.221314773243448
12.221314770912386
12.221314768581838
12.221314766251805
12.22131476392227
12.221314761593238
12.221314759264704
12.221314756936692
12.221314754609168
12.221314752282169
12.22131474995566
12.221314747629666
12.221314745304173
12.221314742979184
12.221314740654694
12.221314738330717
12.221314736007244
12.221314733684267
12.221314731361801
12.221314729039841
12.221314726718376
12.221314724397422
12.22131472207698
12.221314719757023
12.221314717437592
12.221314715118643
12.221314712800218
12.221314710482275
12.221314708164845
12.221314705847917
12.22131470353149
12.221314701215558
12.221314698900146
12.221314696585232
12.221314694270813
12.2213146919569
12.221314689643494
12.221314687330585
12.221314685018179
12.22131468270628
12.221314680394874
12.221314678083976
12.221314675773566
12.22131467346367
12.221314671154277
12.22131466884538
12.221314666536992
12.221314664229102
12.221314661921703
12.221314659614812
12.221314657308428
12.221314655002532
12.221314652697147
12.221314650392255
12.221314648087867
12.22131464578398
12.221314643480587
12.221314641177704
12.22131463887531
12.221314636573426
12.22131463427204
12.22131463197114
12.22131462967075
12.221314627370868
12.221314625071477
12.221314622772576
12.221314620474189
12.221314618176287
12.22131461587889
12.221314613581994
12.221314611285594
12.221314608989694
12.221314606694293
12.221314604399387
12.221314602104986
12.221314599811077
12.221314597517667
12.221314595224761
12.221314592932341
12.221314590640418
12.22131458834901
12.221314586058078
12.221314583767654
12.221314581477731
12.2213145791883
12.221314576899362
12.221314574610924
12.221314572322989
12.221314570035547
12.221314567748603
12.221314565462146
12.221314563176197
12.221314560890734
12.221314558605771
12.221314556321305
12.221314554037328
12.22131455175386
12.221314549470879
12.221314547188392
12.221314544906404
12.22131454262491
12.221314540343919
12.221314538063409
12.221314535783405
12.221314533503893
12.221314531224877
12.221314528946355
12.221314526668323
12.221314524390788
12.221314522113751
12.221314519837204
12.221314517561146
12.221314515285588
12.221314513010519
12.22131451073595
12.221314508461882
12.221314506188298
12.221314503915206
12.221314501642608
12.22131449937051
12.221314497098895
12.221314494827785
12.22131449255716
12.221314490287027
12.221314488017379
12.221314485748241
12.221314483479592
12.22131448121143
12.22131447894377
12.221314476676586
12.221314474409903
12.221314472143714
12.221314469878017
12.221314467612801
12.221314465348087
12.22131446308386
12.221314460820132
12.221314458556881
12.221314456294136
12.221314454031871
12.221314451770107
12.22131444950883
12.22131444724804
12.221314444987746
12.22131444272794
12.221314440468626
12.221314438209792
12.221314435951461
12.221314433693616
12.22131443143626
12.221314429179394
12.22131442692302
12.221314424667137
12.221314422411739
12.22131442015683
12.22131441790242
12.221314415648491
12.221314413395058
12.22131441114211
12.221314408889647
12.221314406637672
12.221314404386188
12.221314402135205
12.221314399884701
12.22131439763468
12.221314395385148
12.221314393136106
12.221314390887557
12.221314388639485
12.221314386391919
12.22131438414483
12.221314381898232
12.221314379652124
12.2213143774065
12.221314375161354
12.221314372916705
12.221314370672546
12.221314368428862
12.221314366185675
12.221314363942975
12.221314361700758
12.221314359459033
12.221314357217787
12.221314354977038
12.221314352736766
12.22131435049698
12.221314348257682
12.221314346018868
12.221314343780554
12.221314341542714
12.221314339305357
12.22131433706849
12.221314334832108
12.221314332596215
12.221314330360794
12.221314328125867
12.22131432589143
12.221314323657486
12.221314321424005
12.221314319191015
12.221314316958512
12.221314314726499
12.221314312494968
12.221314310263912
12.221314308033355
12.221314305803268
12.221314303573676
12.221314301344567
12.221314299115935
12.221314296887789
12.22131429466013
12.221314292432947
12.221314290206248
12.221314287980048
12.221314285754323
12.221314283529072
12.221314281304307
12.221314279080032
12.221314276856239
12.221314274632924
12.22131427241009
12.221314270187749
12.221314267965875
12.22131426574449
12.221314263523594
12.22131426130317
12.22131425908323
12.221314256863783
12.22131425464481
12.221314252426314
12.221314250208298
12.221314247990776
12.22131424577373
12.221314243557158
12.221314241341078
12.221314239125466
12.22131423691034
12.221314234695699
12.221314232481536
12.221314230267856
12.221314228054661
12.221314225841938
12.221314223629694
12.221314221417936
12.221314219206654
12.22131421699585
12.221314214785528
12.221314212575688
12.221314210366334
12.221314208157455
12.22131420594904
12.221314203741128
12.221314201533676
12.221314199326715
12.22131419712023
12.22131419491422
12.22131419270869

12.221314190503646
12.221314188299072
12.221314186094979
12.221314183891364
12.221314181688236
12.221314179485576
12.221314177283391
12.221314175081693
12.221314172880472
12.22131417067972
12.22131416847946
12.221314166279667
12.221314164080361
12.22131416188152
12.221314159683155
12.221314157485276
12.221314155287876
12.221314153090942
12.221314150894496
12.221314148698523
12.221314146503028
12.221314144308005
12.221314142113464
12.221314139919397
12.221314137725798
12.221314135532687
12.221314133340048
12.221314131147885
12.221314128956195
12.221314126764984
12.221314124574247
12.22131412238399
12.2213141201942
12.221314118004894
12.22131411581605
12.2213141136277
12.221314111439806
12.221314109252399
12.221314107065467
12.221314104879005
12.221314102693018
12.22131410050751
12.22131409832247
12.221314096137908
12.221314093953824
12.221314091770203
12.22131408958706
12.221314087404394
12.221314085222206
12.221314083040484
12.221314080859239
12.221314078678466
12.221314076498166
12.221314074318347
12.221314072138986
12.221314069960108
12.221314067781698
12.221314065603769
12.221314063426302
12.221314061249315
12.2213140590728
12.221314056896762
12.221314054721189
12.221314052546088
12.221314050371456
12.221314048197302
12.221314046023618
12.221314043850407
12.221314041677667
12.221314039505405
12.2213140373336
12.221314035162278
12.221314032991419
12.221314030821038
12.22131402865113
12.221314026481686
12.221314024312719
12.221314022144217
12.221314019976191
12.221314017808625
12.221314015641548
12.221314013474931
12.22131401130878
12.221314009143105
12.221314006977897
12.22131400481316
12.221314002648894
12.221314000485101
12.221313998321765
12.221313996158907
12.221313993996525
12.2213139918346
12.221313989673158
12.221313987512174
12.221313985351665
12.221313983191617
12.221313981032047
12.221313978872942
12.221313976714303
12.22131397455614
12.221313972398432
12.221313970241201
12.22131396808444
12.221313965928145
12.221313963772312
12.221313961616962
12.221313959462064
12.221313957307649
12.221313955153686
12.221313953000202
12.22131395084718
12.221313948694629
12.221313946542539
12.221313944390916
12.221313942239773
12.221313940089082
12.221313937938866
12.221313935789114
12.221313933639824
12.221313931491009
12.22131392934265
12.22131392719477
12.221313925047347
12.221313922900388
12.221313920753904
12.221313918607883
12.221313916462329
12.221313914317241
12.221313912172606
12.221313910028451
12.221313907884761
12.221313905741521
12.221313903598766
12.221313901456464
12.221313899314639
12.221313897173273
12.221313895032365
12.221313892891924
12.221313890751956
12.221313888612439
12.221313886473396
12.221313884334814
12.221313882196693
12.221313880059032
12.221313877921855
12.221313875785127
12.221313873648862
12.221313871513068
12.22131386937773
12.22131386724286
12.221313865108451
12.22131386297451
12.221313860841027
12.221313858708012
12.22131385657545
12.221313854443364
12.221313852311736
12.221313850180566
12.22131384804986
12.221313845919621
12.22131384378984
12.221313841660526
12.221313839531668
12.221313837403276
12.221313835275343
12.221313833147882
12.221313831020865
12.221313828894322
12.221313826768231
12.221313824642616
12.221313822517452
12.221313820392755
12.22131381826852
12.221313816144734
12.221313814021418
12.221313811898566
12.221313809776166
12.221313807654237
12.221313805532757
12.221313803411746
12.221313801291203
12.221313799171098
12.221313797051469
12.221313794932303
12.221313792813577
12.221313790695326
12.221313788577536
12.221313786460207
12.22131378434333
12.22131378222691
12.221313780110963
12.221313777995464
12.221313775880427
12.221313773765855
12.221313771651733
12.221313769538074
12.221313767424876
12.221313765312136
12.221313763199849
12.221313761088023
12.221313758976656
12.221313756865744
12.221313754755297
12.221313752645306
12.221313750535764
12.22131374842669
12.221313746318069
12.221313744209917
12.221313742102206
12.221313739994962
12.221313737888176
12.221313735781846
12.22131373367597
12.221313731570552
12.221313729465596
12.221313727361087
12.22131372525704
12.221313723153456
12.221313721050318
12.221313718947643
12.221313716845419
12.22131371474366
12.221313712642345
12.221313710541496
12.221313708441103
12.221313706341173
12.22131370424168
12.22131370214265
12.22131370004408
12.221313697945963
12.221313695848306
12.221313693751092
12.22131369165434
12.221313689558047
12.221313687462198
12.221313685366814
12.221313683271894
12.221313681177413
12.22131367908338
12.221313676989812
12.221313674896706
12.221313672804042
12.221313670711837
12.221313668620088
12.221313666528799
12.221313664437949
12.221313662347562
12.221313660257623
12.221313658168143
12.221313656079108
12.221313653990537
12.221313651902419
12.22131364981475
12.22131364772753
12.221313645640778
12.221313643554458
12.221313641468603
12.221313639383201
12.22131363729825
12.221313635213752
12.22131363312971
12.221313631046105
12.221313628962973
12.221313626880281
12.221313624798043
12.22131362271626
12.221313620634927
12.221313618554042
12.221313616473608
12.221313614393635
12.221313612314107
12.221313610235027
12.221313608156406
12.221313606078228
12.221313604000507
12.221313601923232
12.22131359984642
12.221313597770052
12.22131359569413
12.221313593618667
12.221313591543652
12.221313589469077
12.221313587394963
12.221313585321294
12.221313583248078
12.221313581175314
12.22131357910299
12.221313577031125
12.22131357495971
12.221313572888745
12.221313570818221
12.22131356874815
12.221313566678528
12.221313564609366
12.221313562540638
12.221313560472371
12.221313558404544
12.22131355633717
12.22131355427024
12.221313552203766
12.221313550137735
12.221313548072157
12.221313546007025
12.221313543942344
12.221313541878105
12.221313539814318
12.221313537750971
12.221313535688086
12.221313533625644
12.221313531563641
12.221313529502085
12.221313527440996
12.221313525380335
12.221313523320134
12.221313521260377
12.221313519201056
12.221313517142196
12.221313515083768
12.221313513025795
12.221313510968276
12.2213135089112
12.221313506854568
12.221313504798383
12.221313502742644
12.221313500687353
12.221313498632497
12.221313496578095
12.22131349452414
12.221313492470628
12.221313490417566
12.221313488364954
12.221313486312782
12.22131348426105
12.221313482209766
12.221313480158928
12.221313478108536
12.22131347605859
12.221313474009088
12.221313471960025
12.221313469911424
12.22131346786325
12.221313465815532
12.221313463768247
12.221313461721419
12.22131345967503
12.22131345762909
12.221313455583573
12.221313453538519
12.221313451493911
12.221313449449738
12.221313447406013
12.221313445362732
12.221313443319895
12.221313441277495
12.221313439235537
12.221313437194034
12.221313435152966
12.22131343311234
12.221313431072161
12.221313429032426
12.221313426993136
12.221313424954278
12.221313422915866
12.221313420877904
12.22131341884038
12.221313416803293
12.221313414766653
12.221313412730456
12.221313410694703
12.221313408659384
12.221313406624516
12.221313404590086
12.221313402556094
12.221313400522545
12.221313398489428
12.221313396456765
12.221313394424543
12.221313392392767
12.221313390361425
12.22131338833052
12.221313386300055
12.22131338427004
12.22131338224046
12.22131338021133
12.22131337818263
12.22131337615436
12.221313374126547
12.221313372099166
12.221313370072235
12.221313368045738
12.221313366019672
12.22131336399406
12.221313361968871
12.221313359944137
12.22131335791984
12.221313355895978
12.221313353872562
12.221313351849576
12.221313349827033
12.22131334780493
12.221313345783265
12.221313343762045
12.221313341741265
12.221313339720904
12.221313337701002
12.221313335681522
12.221313333662494
12.221313331643902
12.221313329625747
12.221313327608023
12.221313325590746
12.2213133235739
12.2213133215575
12.221313319541526
12.221313317525992
12.221313315510905
12.221313313496253
12.221313311482028
12.22131330946825
12.221313307454903
12.221313305442
12.221313303429529
12.2213133014175
12.221313299405894
12.221313297394738
12.221313295384013
12.221313293373727
12.221313291363874
12.221313289354468
12.221313287345493
12.221313285336947
12.221313283328849
12.221313281321164
12.22131327931394
12.22131327730714
12.221313275300773
12.221313273294843
12.221313271289352
12.221313269284297
12.221313267279674
12.221313265275484
12.221313263271732
12.22131326126842
12.221313259265536
12.221313257263088
12.221313255261071
12.221313253259487
12.22131325125835
12.22131324925765
12.221313247257372
12.22131324525753
12.221313243258129
12.221313241259152
12.22131323926061
12.221313237262503
12.221313235264832
12.221313233267598
12.221313231270797
12.221313229274417
12.221313227278486
12.221313225282973
12.221313223287906
12.221313221293274
12.221313219299061
12.221313217305289
12.22131321531195
12.221313213319046
12.221313211326565
12.221313209334525
12.221313207342922
12.221313205351734
12.221313203360987
12.221313201370679
12.221313199380804
12.221313197391346
12.221313195402335
12.221313193413751
12.221313191425597
12.221313189437865
12.221313187450578
12.221313185463723
12.221313183477289
12.221313181491295
12.221313179505728
12.22131317752059
12.221313175535887
12.221313173551614
12.221313171567763
12.221313169584354
12.221313167601375
12.221313165618824
12.221313163636697
12.221313161655003
12.221313159673748
12.22131315769292
12.221313155712522
12.221313153732542
12.221313151753002
12.221313149773886
12.221313147795207
12.221313145816957
12.221313143839135
12.221313141861739
12.221313139884776
12.221313137908238
12.221313135932128
12.221313133956448
12.221313131981208
12.221313130006385
12.221313128031996
12.221313126058027
12.221313124084492
12.221313122111388
12.22131312013871
12.221313118166458
12.221313116194642
12.221313114223245
12.221313112252279
12.22131311028174
12.221313108311625
12.22131310634195
12.221313104372685
12.221313102403863
12.22131310043546
12.221313098467487
12.221313096499939
12.221313094532817
12.221313092566133
12.221313090599867
12.221313088634021
12.221313086668616
12.221313084703628
12.221313082739073
12.221313080774939
12.221313078811228
12.22131307684795
12.221313074885098
12.221313072922676
12.221313070960669
12.221313068999088
12.221313067037945
12.221313065077213
12.221313063116915
12.221313061157044
12.221313059197596
12.221313057238575
12.221313055279975
12.221313053321799
12.221313051364053
12.22131304940673
12.221313047449831
12.221313045493364
12.221313043537315
12.22131304158169
12.221313039626486
12.22131303767172
12.221313035717365
12.221313033763442
12.221313031809935
12.221313029856857
12.221313027904193
12.221313025951963
12.221313024000159
12.221313022048774
12.221313020097824
12.221313018147281
12.221313016197172
12.221313014247482
12.221313012298213
12.22131301034937
12.221313008400953
12.221313006452954
12.221313004505376
12.221313002558226
12.22131300061149
12.221312998665184
12.221312996719305
12.221312994773841
12.221312992828805
12.221312990884192
12.221312988939989
12.221312986996221
12.221312985052865
12.221312983109932
12.221312981167424
12.22131297922534
12.221312977283677
12.221312975342428
12.221312973401607
12.22131297146121
12.221312969521223
12.22131296758167
12.221312965642527
12.221312963703815
12.221312961765516
12.221312959827642
12.221312957890188
12.221312955953156
12.221312954016538
12.221312952080346
12.22131295014457
12.221312948209217

12.221312946274288
12.221312944339774
12.221312942405678
12.221312940472012
12.221312938538754
12.221312936605916
12.221312934673502
12.221312932741506
12.221312930809932
12.221312928878772
12.22131292694804
12.22131292501772
12.22131292308783
12.221312921158338
12.221312919229284
12.221312917300633
12.221312915372405
12.221312913444603
12.221312911517222
12.22131290959024
12.221312907663698
12.221312905737562
12.221312903811853
12.221312901886554
12.221312899961672
12.221312898037205
12.221312896113169
12.221312894189543
12.221312892266333
12.221312890343542
12.221312888421172
12.221312886499222
12.221312884577674
12.22131288265655
12.221312880735848
12.221312878815565
12.22131287689569
12.221312874976231
12.221312873057197
12.22131287113857
12.22131286922037
12.22131286730258
12.221312865385208
12.221312863468254
12.221312861551718
12.221312859635583
12.221312857719886
12.221312855804584
12.221312853889705
12.22131285197525
12.2213128500612
12.221312848147578
12.221312846234355
12.221312844321567
12.221312842409173
12.22131284049721
12.22131283858565
12.22131283667452
12.221312834763781
12.221312832853476
12.221312830943582
12.221312829034106
12.221312827125033
12.221312825216382
12.221312823308146
12.22131282140032
12.221312819492917
12.221312817585916
12.221312815679335
12.221312813773167
12.221312811867408
12.221312809962074
12.22131280805715
12.22131280615264
12.221312804248528
12.221312802344851
12.22131280044157
12.22131279853871
12.221312796636267
12.221312794734237
12.221312792832608
12.221312790931398
12.221312789030598
12.221312787130222
12.221312785230248
12.221312783330692
12.221312781431543
12.221312779532807
12.221312777634484
12.221312775736573
12.22131277383908
12.221312771941989
12.22131277004532
12.221312768149058
12.2213127662532
12.221312764357759
12.221312762462734
12.221312760568118
12.221312758673912
12.221312756780115
12.22131275488673
12.221312752993759
12.221312751101193
12.221312749209039
12.221312747317306
12.221312745425976
12.221312743535051
12.221312741644542
12.221312739754445
12.221312737864753
12.221312735975479
12.221312734086611
12.221312732198156
12.221312730310105
12.221312728422475
12.221312726535242
12.221312724648428
12.22131272276201
12.221312720876009
12.221312718990415
12.22131271710524
12.221312715220472
12.221312713336104
12.221312711452146
12.221312709568604
12.221312707685467
12.221312705802738
12.221312703920423
12.221312702038503
12.221312700157007
12.22131269827591
12.221312696395223
12.22131269451495
12.221312692635083
12.221312690755617
12.221312688876564
12.221312686997917
12.221312685119681
12.22131268324185
12.22131268136443
12.221312679487413
12.22131267761081
12.221312675734612
12.22131267385881
12.221312671983428
12.221312670108446
12.221312668233884
12.221312666359713
12.221312664485954
12.221312662612608
12.22131266073966
12.221312658867118
12.221312656994987
12.221312655123263
12.221312653251946
12.221312651381027
12.22131264951051
12.221312647640424
12.22131264577072
12.22131264390144
12.22131264203255
12.22131264016408
12.221312638296
12.221312636428332
12.221312634561079
12.221312632694216
12.221312630827772
12.22131262896172
12.221312627096074
12.22131262523084
12.221312623366012
12.22131262150158
12.221312619637569
12.221312617773947
12.221312615910733
12.221312614047921
12.221312612185521
12.221312610323524
12.221312608461925
12.221312606600737
12.22131260473995
12.221312602879557
12.221312601019578
12.221312599160013
12.221312597300837
12.22131259544206
12.221312593583695
12.221312591725734
12.221312589868177
12.221312588011026
12.221312586154271
12.221312584297923
12.221312582441978
12.221312580586428
12.22131257873129
12.22131257687655
12.221312575022214
12.221312573168277
12.221312571314746
12.22131256946162
12.221312567608885
12.22131256575657
12.221312563904641
12.221312562053129
12.221312560202001
12.221312558351284
12.221312556500974
12.221312554651059
12.22131255280154
12.221312550952437
12.221312549103729
12.221312547255419
12.221312545407516
12.221312543560007
12.2213125417129
12.221312539866194
12.221312538019895
12.221312536173995
12.221312534328488
12.221312532483385
12.221312530638688
12.22131252879439
12.221312526950491
12.22131252510699
12.221312523263897
12.221312521421192
12.221312519578891
12.221312517736996
12.221312515895496
12.221312514054391
12.22131251221369
12.22131251037339
12.221312508533483
12.22131250669398
12.221312504854884
12.221312503016183
12.221312501177875
12.221312499339971
12.22131249750246
12.22131249566535
12.221312493828641
12.221312491992336
12.221312490156423
12.221312488320912
12.221312486485795
12.221312484651074
12.221312482816762
12.221312480982833
12.221312479149313
12.221312477316193
12.22131247548347
12.22131247365113
12.2213124718192
12.22131246998767
12.221312468156535
12.221312466325799
12.221312464495458
12.221312462665509
12.22131246083596
12.22131245900681
12.22131245717806
12.221312455349697
12.221312453521746
12.22131245169418
12.221312449867026
12.221312448040246
12.221312446213874
12.221312444387898
12.221312442562322
12.22131244073714
12.221312438912348
12.22131243708796
12.221312435263961
12.221312433440369
12.221312431617159
12.221312429794352
12.221312427971943
12.221312426149922
12.221312424328303
12.221312422507076
12.221312420686248
12.22131241886581
12.221312417045773
12.221312415226128
12.221312413406878
12.221312411588023
12.221312409769563
12.22131240795149
12.22131240613383
12.221312404316539
12.221312402499663
12.22131240068318
12.221312398867084
12.221312397051381
12.221312395236072
12.221312393421163
12.221312391606642
12.221312389792526
12.221312387978791
12.221312386165454
12.221312384352515
12.221312382539963
12.221312380727811
12.221312378916055
12.221312377104672
12.221312375293705
12.221312373483123
12.221312371672932
12.22131236986313
12.22131236805373
12.221312366244714
12.221312364436098
12.22131236262787
12.22131236082004
12.221312359012595
12.221312357205552
12.221312355398895
12.221312353592623
12.221312351786764
12.221312349981275
12.221312348176182
12.221312346371489
12.221312344567176
12.221312342763266
12.221312340959747
12.221312339156619
12.221312337353876
12.221312335551533
12.221312333749575
12.221312331948004
12.221312330146823
12.221312328346047
12.221312326545663
12.22131232474565
12.221312322946039
12.221312321146817
12.221312319347984
12.221312317549549
12.221312315751497
12.221312313953833
12.221312312156574
12.22131231035969
12.221312308563197
12.221312306767107
12.221312304971395
12.22131230317608
12.221312301381142
12.221312299586605
12.221312297792448
12.221312295998692
12.221312294205317
12.221312292412337
12.221312290619744
12.221312288827539
12.221312287035717
12.221312285244297
12.221312283453262
12.221312281662605
12.221312279872341
12.221312278082475
12.221312276292997
12.221312274503898
12.22131227271519
12.22131227092687
12.221312269138945
12.2213122673514
12.221312265564244
12.221312263777481
12.221312261991105
12.221312260205108
12.221312258419513
12.22131225663429
12.221312254849467
12.221312253065026
12.22131225128097
12.221312249497304
12.221312247714023
12.221312245931129
12.221312244148631
12.221312242366508
12.221312240584785
12.221312238803439
12.221312237022483
12.2213122352419
12.221312233461717
12.221312231681917
12.221312229902512
12.221312228123486
12.221312226344846
12.221312224566594
12.221312222788722
12.221312221011244
12.221312219234136
12.221312217457433
12.22131221568111
12.221312213905168
12.221312212129618
12.221312210354448
12.221312208579661
12.221312206805266
12.221312205031253
12.221312203257629
12.221312201484375
12.22131219971152
12.221312197939053
12.221312196166961
12.221312194395253
12.221312192623943
12.221312190852991
12.221312189082456
12.22131218731229
12.221312185542503
12.221312183773103
12.221312182004098
12.221312180235469
12.221312178467217
12.221312176699362
12.221312174931883
12.221312173164785
12.221312171398079
12.221312169631744
12.221312167865802
12.221312166100248
12.221312164335062
12.22131216257027
12.22131216080585
12.221312159041824
12.221312157278183
12.221312155514912
12.221312153752034
12.221312151989537
12.221312150227421
12.221312148465689
12.221312146704342
12.221312144943377
12.221312143182782
12.221312141422587
12.221312139662764
12.221312137903325
12.221312136144268
12.22131213438559
12.221312132627292
12.221312130869384
12.221312129111853
12.221312127354704
12.221312125597931
12.22131212384154
12.221312122085541
12.221312120329918
12.221312118574676
12.221312116819812
12.22131211506533
12.221312113311225
12.221312111557506
12.221312109804165
12.221312108051208
12.22131210629863
12.22131210454643
12.221312102794606
12.22131210104318
12.22131209929212
12.221312097541437
12.221312095791147
12.221312094041222
12.221312092291695
12.221312090542531
12.221312088793747
12.22131208704536
12.221312085297336
12.221312083549694
12.221312081802436
12.221312080055563
12.221312078309051
12.221312076562924
12.221312074817183
12.221312073071822
12.221312071326834
12.221312069582225
12.221312067837994
12.221312066094148
12.221312064350675
12.221312062607577
12.221312060864864
12.221312059122525
12.221312057380574
12.22131205563899
12.221312053897792
12.221312052156959
12.221312050416515
12.221312048676452
12.221312046936758
12.221312045197442
12.221312043458513
12.221312041719948
12.221312039981767
12.221312038243966
12.221312036506534
12.221312034769484
12.221312033032815
12.221312031296518
12.221312029560595
12.221312027825057
12.221312026089892
12.221312024355102
12.221312022620692
12.221312020886657

12.221312019152993
12.221312017419713
12.22131201568681
12.221312013954277
12.221312012222112
12.221312010490339
12.221312008758936
12.221312007027912
12.221312005297259
12.221312003566979
12.22131200183708
12.221312000107556
12.221311998378411
12.221311996649634
12.22131199492123
12.221311993193202
12.22131199146556
12.221311989738286
12.221311988011387
12.221311986284869
12.221311984558705
12.22131198283294
12.221311981107542
12.221311979382516
12.221311977657866
12.221311975933583
12.22131197420968
12.221311972486152
12.221311970763002
12.221311969040222
12.221311967317819
12.221311965595785
12.221311963874118
12.221311962152841
12.22131196043193
12.22131195871139
12.221311956991228
12.221311955271435
12.22131195355202
12.221311951832975
12.221311950114302
12.221311948396002
12.221311946678073
12.221311944960526
12.221311943243347
12.22131194152654
12.221311939810098
12.221311938094033
12.221311936378342
12.221311934663028
12.221311932948085
12.221311931233515
12.221311929519317
12.22131192780549
12.221311926092028
12.22131192437894
12.221311922666231
12.221311920953893
12.22131191924193
12.22131191753033
12.221311915819093
12.221311914108249
12.221311912397757
12.221311910687644
12.221311908977906
12.221311907268529
12.221311905559537
12.221311903850914
12.221311902142652
12.221311900434769
12.221311898727249
12.221311897020094
12.221311895313331
12.221311893606929
12.221311891900893
12.221311890195228
12.221311888489943
12.221311886785013
12.221311885080459
12.221311883376273
12.221311881672467
12.221311879969022
12.221311878265945
12.221311876563238
12.221311874860913
12.221311873158943
12.221311871457345
12.221311869756123
12.22131186805526
12.221311866354773
12.221311864654652
12.221311862954904
12.221311861255526
12.221311859556513
12.221311857857865
12.221311856159604
12.221311854461694
12.221311852764158
12.22131185106699
12.221311849370187
12.221311847673755
12.221311845977691
12.221311844281988
12.221311842586662
12.221311840891707
12.221311839197117
12.221311837502896
12.221311835809033
12.221311834115541
12.22131183242242
12.221311830729666
12.22131182903728
12.221311827345264
12.22131182565361
12.221311823962324
12.221311822271415
12.22131182058086
12.221311818890667
12.221311817200858
12.22131181551141
12.221311813822329
12.221311812133616
12.22131181044526
12.221311808757278
12.221311807069654
12.221311805382411
12.221311803695523
12.221311802009005
12.221311800322848
12.221311798637062
12.221311796951648
12.221311795266585
12.2213117935819
12.221311791897577
12.221311790213612
12.221311788530024
12.221311786846803
12.221311785163941
12.221311783481442
12.221311781799304
12.22131178011755
12.221311778436139
12.2213117767551
12.221311775074437
12.221311773394124
12.221311771714184
12.221311770034607
12.2213117683554
12.221311766676552
12.221311764998058
12.221311763319951
12.221311761642193
12.2213117599648
12.221311758287777
12.221311756611101
12.221311754934812
12.22131175325888
12.221311751583304
12.221311749908097
12.221311748233255
12.221311746558769
12.221311744884652
12.221311743210896
12.22131174153751
12.22131173986448
12.221311738191815
12.221311736519512
12.221311734847578
12.221311733176002
12.221311731504793
12.221311729833943
12.221311728163457
12.221311726493328
12.221311724823563
12.221311723154168
12.22131172148513
12.22131171981645
12.221311718148144
12.221311716480193
12.221311714812597
12.221311713145381
12.221311711478519
12.221311709812014
12.221311708145867
12.221311706480083
12.22131170481467
12.221311703149613
12.221311701484915
12.221311699820582
12.221311698156608
12.221311696492997
12.221311694829751
12.221311693166857
12.22131169150433
12.22131168984216
12.221311688180352
12.22131168651891
12.221311684857822
12.221311683197097
12.221311681536724
12.22131167987673
12.221311678217077
12.221311676557798
12.221311674898873
12.221311673240315
12.22131167158211
12.221311669924267
12.221311668266782
12.22131166660966
12.221311664952893
12.22131166329649
12.221311661640446
12.221311659984762
12.221311658329435
12.221311656674459
12.221311655019857
12.221311653365609
12.22131165171172
12.221311650058187
12.221311648405008
12.221311646752202
12.221311645099744
12.221311643447656
12.221311641795914
12.221311640144537
12.221311638493516
12.221311636842856
12.221311635192551
12.221311633542614
12.221311631893021
12.221311630243784
12.221311628594918
12.221311626946399
12.221311625298245
12.221311623650454
12.22131162200302
12.221311620355928
12.221311618709203
12.221311617062831
12.221311615416827
12.22131161377118
12.221311612125875
12.221311610480944
12.22131160883635
12.221311607192137
12.221311605548262
12.221311603904748
12.221311602261594
12.221311600618796
12.22131159897636
12.221311597334275
12.221311595692539
12.221311594051173
12.221311592410162
12.221311590769494
12.221311589129193
12.221311587489248
12.221311585849655
12.221311584210419
12.221311582571541
12.221311580933017
12.221311579294849
12.221311577657026
12.221311576019579
12.221311574382476
12.22131157274573
12.221311571109338
12.221311569473306
12.221311567837619
12.2213115662023
12.22131156456733
12.221311562932705
12.221311561298446
12.221311559664537
12.221311558030987
12.221311556397785
12.221311554764936
12.221311553132452
12.221311551500323
12.221311549868537
12.221311548237113
12.221311546606033
12.221311544975325
12.22131154334496
12.221311541714945
12.22131154008529
12.221311538455994
12.22131153682704
12.221311535198451
12.221311533570205
12.221311531942312
12.221311530314777
12.221311528687602
12.221311527060768
12.221311525434292
12.221311523808172
12.221311522182408
12.221311520556986
12.221311518931927
12.221311517307212
12.22131151568285
12.221311514058852
12.221311512435193
12.221311510811898
12.221311509188942
12.221311507566348
12.221311505944097
12.221311504322205
12.22131150270067
12.221311501079477
12.221311499458647
12.221311497838164
12.22131149621803
12.221311494598249
12.221311492978813
12.221311491359732
12.221311489741012
12.221311488122645
12.221311486504607
12.221311484886934
12.221311483269622
12.221311481652638
12.22131148003603
12.221311478419755
12.221311476803837
12.221311475188271
12.22131147357305
12.221311471958185
12.221311470343675
12.221311468729507
12.221311467115694
12.22131146550222
12.221311463889117
12.22131146227635
12.22131146066393
12.221311459051874
12.221311457440153
12.221311455828792
12.221311454217775
12.221311452607113
12.221311450996797
12.221311449386832
12.221311447777218
12.221311446167947
12.22131144455903
12.221311442950464
12.221311441342245
12.22131143973437
12.221311438126849
12.221311436519672
12.221311434912844
12.221311433306374
12.221311431700254
12.221311430094472
12.221311428489045
12.221311426883958
12.221311425279227
12.221311423674848
12.221311422070805
12.22131142046712
12.221311418863786
12.221311417260788
12.221311415658144
12.221311414055853
12.221311412453899
12.221311410852298
12.221311409251047
12.22131140765014
12.22131140604959
12.221311404449377
12.22131140284951
12.221311401249997
12.221311399650828
12.221311398052013
12.221311396453531
12.221311394855398
12.221311393257626
12.221311391660189
12.221311390063102
12.221311388466361
12.221311386869973
12.22131138527392
12.22131138367822
12.221311382082867
12.221311380487856
12.22131137889319
12.221311377298878
12.221311375704907
12.221311374111288
12.221311372518004
12.221311370925072
12.221311369332481
12.221311367740244
12.221311366148349
12.2213113645568
12.2213113629656
12.221311361374731
12.22131135978422
12.221311358194054
12.221311356604236
12.22131135501475
12.221311353425625
12.221311351836835
12.221311350248385
12.221311348660288
12.221311347072529
12.221311345485121
12.221311343898064
12.221311342311338
12.221311340724965
12.221311339138934
12.221311337553244
12.221311335967897
12.221311334382904
12.22131133279824
12.22131133121393
12.22131132962997
12.221311328046347
12.221311326463066
12.22131132488013
12.221311323297533
12.221311321715282
12.221311320133381
12.22131131855182
12.2213113169706
12.221311315389727
12.22131131380919
12.221311312229004
12.221311310649154
12.22131130906965
12.221311307490485
12.221311305911673
12.221311304333199
12.221311302755057
12.221311301177264
12.221311299599828
12.221311298022718
12.221311296445956
12.221311294869533
12.221311293293457
12.22131129171772
12.221311290142317
12.221311288567266
12.221311286992556
12.221311285418185
12.22131128384416
12.221311282270475
12.221311280697131
12.221311279124132
12.221311277551465
12.221311275979149
12.221311274407169
12.221311272835532
12.221311271264236
12.221311269693278
12.221311268122664
12.22131126655239
12.221311264982457
12.221311263412867
12.221311261843615
12.221311260274705
12.221311258706132
12.221311257137915
12.221311255570015
12.221311254002467
12.221311252435257
12.22131125086838
12.221311249301856
12.221311247735668
12.221311246169819
12.221311244604314
12.22131124303914
12.22131124147432
12.221311239909825
12.221311238345676
12.221311236781869
12.22131123521839
12.221311233655255
12.221311232092464
12.221311230530016
12.221311228967908
12.221311227406131
12.221311225844692
12.221311224283598
12.221311222722834
12.221311221162416
12.221311219602335
12.221311218042585
12.22131121648319
12.221311214924121
12.221311213365396
12.221311211807011
12.22131121024896
12.221311208691244
12.221311207133871
12.221311205576832
12.22131120402013
12.221311202463779
12.221311200907746
12.221311199352069
12.221311197796727
12.221311196241707
12.22131119468704
12.221311193132705
12.221311191578708
12.22131119002505
12.221311188471725
12.221311186918737
12.221311185366096
12.221311183813773
12.22131118226181
12.221311180710169
12.221311179158867
12.221311177607907
12.221311176057277
12.221311174506978

12.221311172957021
12.221311171407411
12.221311169858124
12.221311168309187
12.22131116676058
12.221311165212308
12.221311163664364
12.221311162116757
12.221311160569494
12.221311159022575
12.221311157475975
12.221311155929719
12.221311154383795
12.221311152838213
12.221311151292957
12.221311149748047
12.221311148203455
12.221311146659222
12.221311145115306
12.22131114357173
12.221311142028489
12.221311140485584
12.221311138943017
12.221311137400779
12.221311135858876
12.221311134317315
12.221311132776087
12.221311131235183
12.221311129694623
12.221311128154394
12.22131112661451
12.221311125074939
12.22131112353571
12.221311121996827
12.221311120458262
12.221311118920047
12.221311117382152
12.221311115844607
12.22131111430737
12.221311112770486
12.221311111233934
12.221311109697709
12.22131110816183
12.221311106626263
12.221311105091045
12.221311103556163
12.221311102021613
12.221311100487382
12.221311098953496
12.22131109741995
12.221311095886712
12.221311094353823
12.221311092821265
12.22131109128904
12.221311089757153
12.221311088225592
12.221311086694365
12.22131108516347
12.221311083632907
12.221311082102671
12.221311080572779
12.221311079043211
12.22131107751398
12.221311075985074
12.221311074456507
12.221311072928266
12.221311071400361
12.221311069872785
12.22131106834554
12.221311066818625
12.22131106529205
12.2213110637658
12.221311062239876
12.221311060714296
12.221311059189038
12.221311057664114
12.221311056139522
12.221311054615251
12.221311053091327
12.221311051567723
12.221311050044447
12.221311048521512
12.221311046998906
12.221311045476622
12.221311043954678
12.221311042433054
12.221311040911763
12.221311039390814
12.221311037870183
12.221311036349878
12.221311034829915
12.221311033310279
12.221311031790975
12.221311030271984
12.221311028753338
12.221311027235025
12.221311025717036
12.221311024199371
12.221311022682046
12.221311021165047
12.221311019648367
12.22131101813203
12.221311016616015
12.221311015100325
12.221311013584977
12.221311012069947
12.221311010555246
12.22131100904088
12.221311007526836
12.221311006013124
12.221311004499738
12.221311002986688
12.221311001473959
12.221310999961567
12.221310998449495
12.221310996937756
12.221310995426343
12.221310993915251
12.221310992404495
12.221310990894068
12.221310989383966
12.221310987874189
12.221310986364744
12.221310984855629
12.221310983346834
12.221310981838375
12.221310980330236
12.22131097882243
12.221310977314943
12.221310975807798
12.221310974300955
12.221310972794472
12.221310971288291
12.221310969782447
12.221310968276926
12.221310966771739
12.221310965266865
12.221310963762324
12.22131096225812
12.221310960754225
12.22131095925067
12.221310957747434
12.221310956244531
12.221310954741945
12.221310953239694
12.221310951737767
12.22131095023616
12.221310948734889
12.221310947233935
12.221310945733306
12.221310944233009
12.22131094273303
12.221310941233385
12.22131093973406
12.221310938235062
12.221310936736394
12.221310935238046
12.221310933740021
12.221310932242325
12.221310930744956
12.22131092924791
12.221310927751187
12.221310926254793
12.221310924758713
12.22131092326298
12.221310921767548
12.221310920272451
12.221310918777675
12.221310917283239
12.221310915789104
12.221310914295305
12.221310912801822
12.221310911308683
12.221310909815843
12.221310908323348
12.221310906831166
12.221310905339307
12.221310903847778
12.221310902356569
12.221310900865689
12.221310899375124
12.221310897884889
12.22131089639497
12.221310894905377
12.221310893416108
12.22131089192717
12.221310890438545
12.22131088895025
12.221310887462275
12.221310885974624
12.221310884487295
12.221310883000283
12.221310881513602
12.221310880027241
12.221310878541203
12.221310877055487
12.221310875570095
12.221310874085027
12.221310872600272
12.221310871115847
12.221310869631747
12.221310868147961
12.221310866664505
12.221310865181367
12.221310863698553
12.221310862216056
12.221310860733887
12.221310859252029
12.221310857770497
12.221310856289296
12.22131085480841
12.221310853327847
12.221310851847607
12.221310850367685
12.221310848888082
12.221310847408795
12.22131084592984
12.221310844451207
12.221310842972887
12.221310841494892
12.22131084001722
12.221310838539866
12.221310837062825
12.221310835586118
12.221310834109731
12.221310832633653
12.2213108311579
12.221310829682464
12.221310828207356
12.22131082673257
12.221310825258097
12.221310823783947
12.22131082231012
12.221310820836608
12.221310819363419
12.221310817890545
12.221310816417992
12.221310814945756
12.221310813473842
12.221310812002253
12.221310810530982
12.221310809060029
12.221310807589386
12.22131080611908
12.221310804649079
12.221310803179405
12.221310801710043
12.221310800241001
12.221310798772286
12.221310797303882
12.221310795835805
12.221310794368026
12.221310792900585
12.221310791433462
12.22131078996665
12.221310788500162
12.221310787033989
12.22131078556813
12.221310784102588
12.221310782637378
12.221310781172471
12.22131077970789
12.221310778243625
12.221310776779683
12.22131077531606
12.221310773852746
12.221310772389753
12.221310770927076
12.221310769464724
12.221310768002681
12.221310766540954
12.22131076507955
12.221310763618458
12.221310762157684
12.221310760697227
12.221310759237092
12.22131075777727
12.221310756317768
12.221310754858578
12.221310753399711
12.22131075194115
12.22131075048292
12.221310749025
12.221310747567383
12.221310746110104
12.221310744653128
12.221310743196483
12.221310741740137
12.221310740284116
12.221310738828409
12.221310737373015
12.221310735917942
12.221310734463179
12.221310733008735
12.22131073155461
12.2213107301008
12.221310728647305
12.221310727194119
12.221310725741253
12.22131072428871
12.221310722836469
12.221310721384546
12.221310719932939
12.221310718481647
12.221310717030674
12.221310715580026
12.22131071412967
12.221310712679644
12.221310711229927
12.221310709780523
12.221310708331435
12.221310706882662
12.221310705434203
12.221310703986061
12.221310702538235
12.221310701090722
12.22131069964352
12.221310698196634
12.221310696750061
12.221310695303808
12.221310693857854
12.221310692412228
12.221310690966913
12.22131068952191
12.221310688077214
12.22131068663284
12.221310685188778
12.221310683745031
12.2213106823016
12.221310680858476
12.221310679415664
12.221310677973168
12.221310676530981
12.221310675089113
12.221310673647562
12.221310672206322
12.221310670765385
12.221310669324767
12.221310667884463
12.221310666444467
12.221310665004784
12.221310663565419
12.221310662126363
12.22131066068762
12.221310659249188
12.221310657811067
12.221310656373264
12.221310654935772
12.221310653498593
12.221310652061717
12.221310650625158
12.2213106491889
12.221310647752976
12.221310646317349
12.221310644882037
12.221310643447039
12.221310642012346
12.221310640577972
12.221310639143905
12.221310637710147
12.221310636276709
12.221310634843572
12.221310633410752
12.221310631978238
12.221310630546038
12.221310629114159
12.22131062768257
12.221310626251306
12.22131062482035
12.221310623389707
12.221310621959372
12.221310620529346
12.22131061909963
12.221310617670229
12.221310616241121
12.221310614812346
12.221310613383878
12.221310611955706
12.221310610527858
12.221310609100312
12.221310607673075
12.221310606246158
12.221310604819537
12.22131060339323
12.221310601967236
12.221310600541553
12.221310599116176
12.221310597691103
12.221310596266354
12.2213105948419
12.221310593417769
12.221310591993936
12.221310590570416
12.221310589147205
12.221310587724297
12.2213105863017
12.221310584879411
12.221310583457445
12.22131058203577
12.221310580614409
12.22131057919336
12.221310577772616
12.22131057635219
12.221310574932058
12.221310573512232
12.221310572092733
12.221310570673522
12.221310569254632
12.221310567836039
12.221310566417776
12.221310564999802
12.221310563582138
12.221310562164785
12.221310560747733
12.221310559331
12.221310557914569
12.22131055649844
12.221310555082626
12.221310553667102
12.221310552251913
12.221310550837025
12.221310549422428
12.221310548008152
12.221310546594175
12.22131054518051
12.221310543767146
12.22131054235409
12.221310540941351
12.221310539528902
12.221310538116775
12.221310536704953
12.221310535293421
12.221310533882209
12.221310532471305
12.221310531060695
12.221310529650403
12.221310528240412
12.221310526830731
12.22131052542135
12.221310524012278
12.221310522603517
12.221310521195054
12.221310519786902
12.22131051837905
12.221310516971505
12.221310515564275
12.221310514157338
12.221310512750707
12.221310511344388
12.221310509938377
12.221310508532664
12.221310507127257
12.221310505722156
12.221310504317358
12.221310502912868
12.22131050150868
12.221310500104796
12.221310498701225
12.22131049729795
12.221310495894977
12.22131049449232
12.221310493089966
12.221310491687909
12.22131049028616
12.221310488884715
12.221310487483567
12.221310486082738
12.221310484682201
12.22131048328197
12.22131048188204
12.221310480482426
12.221310479083103
12.22131047768409
12.221310476285383
12.22131047488697
12.221310473488867
12.221310472091071
12.221310470693574
12.221310469296377
12.221310467899492
12.221310466502905
12.221310465106626
12.221310463710642
12.221310462314959
12.221310460919586
12.22131045952451
12.221310458129741
12.22131045673528
12.221310455341118
12.22131045394726
12.221310452553697
12.221310451160443
12.221310449767484
12.221310448374835
12.221310446982484
12.221310445590445
12.221310444198702
12.221310442807255
12.221310441416113
12.221310440025274
12.221310438634738
12.221310437244501
12.221310435854575
12.221310434464934
12.221310433075612
12.221310431686584
12.22131043029785
12.221310428909426
12.221310427521304
12.221310426133478
12.221310424745969
12.221310423358739
12.221310421971825
12.221310420585205
12.221310419198888
12.22131041781287
12.221310416427153
12.221310415041737
12.22131041365662

12.221310412271814
12.221310410887297
12.221310409503083
12.221310408119178
12.221310406735565
12.22131040535225
12.22131040396924
12.22131040258653
12.22131040120412
12.221310399822013
12.221310398440192
12.221310397058689
12.221310395677476
12.221310394296566
12.22131039291596
12.22131039153564
12.221310390155638
12.221310388775914
12.221310387396498
12.22131038601739
12.221310384638576
12.221310383260063
12.221310381881837
12.221310380503937
12.221310379126312
12.221310377748988
12.221310376371976
12.221310374995255
12.221310373618834
12.22131037224271
12.221310370866881
12.221310369491361
12.221310368116123
12.221310366741196
12.22131036536657
12.221310363992242
12.221310362618203
12.22131036124447
12.221310359871032
12.22131035849789
12.22131035712505
12.221310355752502
12.22131035438026
12.221310353008315
12.221310351636655
12.221310350265313
12.221310348894255
12.221310347523497
12.221310346153034
12.221310344782882
12.22131034341301
12.221310342043443
12.221310340674178
12.221310339305202
12.22131033793653
12.221310336568147
12.221310335200071
12.22131033383228
12.221310332464803
12.221310331097607
12.221310329730715
12.221310328364115
12.221310326997806
12.221310325631809
12.221310324266106
12.221310322900694
12.221310321535572
12.22131032017076
12.221310318806237
12.221310317442004
12.221310316078076
12.221310314714447
12.221310313351106
12.22131031198806
12.22131031062531
12.22131030926287
12.221310307900708
12.221310306538848
12.221310305177289
12.221310303816022
12.221310302455041
12.221310301094366
12.221310299733979
12.221310298373897
12.22131029701411
12.221310295654613
12.22131029429541
12.221310292936499
12.221310291577895
12.22131029021957
12.221310288861549
12.221310287503824
12.221310286146398
12.221310284789256
12.22131028343241
12.22131028207586
12.22131028071961
12.221310279363657
12.221310278007985
12.221310276652614
12.22131027529754
12.221310273942763
12.221310272588271
12.221310271234072
12.221310269880169
12.221310268526572
12.221310267173253
12.22131026582023
12.221310264467508
12.221310263115075
12.221310261762932
12.221310260411089
12.221310259059546
12.22131025770827
12.221310256357315
12.221310255006646
12.221310253656263
12.221310252306171
12.221310250956387
12.221310249606878
12.221310248257682
12.22131024690876
12.221310245560144
12.221310244211816
12.221310242863776
12.221310241516038
12.22131024016859
12.221310238821427
12.22131023747456
12.221310236127984
12.221310234781699
12.221310233435716
12.221310232090024
12.221310230744615
12.22131022939951
12.221310228054682
12.221310226710148
12.221310225365922
12.221310224021972
12.221310222678323
12.221310221334958
12.221310219991887
12.221310218649108
12.22131021730662
12.221310215964417
12.221310214622518
12.22131021328091
12.22131021193959
12.221310210598553
12.22131020925781
12.221310207917364
12.221310206577206
12.221310205237339
12.22131020389776
12.22131020255848
12.221310201219477
12.22131019988078
12.22131019854236
12.221310197204236
12.221310195866403
12.221310194528863
12.221310193191613
12.221310191854656
12.22131019051798
12.221310189181596
12.221310187845502
12.22131018650971
12.221310185174193
12.221310183838977
12.221310182504036
12.2213101811694
12.221310179835053
12.22131017850098
12.221310177167208
12.221310175833722
12.221310174500532
12.221310173167623
12.221310171835015
12.221310170502676
12.221310169170646
12.2213101678389
12.221310166507436
12.221310165176268
12.22131016384539
12.2213101625148
12.221310161184489
12.221310159854475
12.221310158524755
12.221310157195306
12.221310155866165
12.221310154537298
12.221310153208732
12.221310151880447
12.221310150552448
12.221310149224742
12.221310147897317
12.221310146570191
12.221310145243347
12.2213101439168
12.221310142590529
12.221310141264553
12.221310139938861
12.221310138613452
12.221310137288338
12.221310135963511
12.22131013463897
12.221310133314724
12.221310131990752
12.221310130667069
12.22131012934368
12.22131012802058
12.22131012669776
12.221310125375227
12.221310124052987
12.221310122731031
12.22131012140936
12.221310120087981
12.221310118766892
12.221310117446079
12.22131011612556
12.221310114805322
12.221310113485378
12.221310112165716
12.221310110846332
12.221310109527247
12.221310108208446
12.221310106889932
12.221310105571696
12.221310104253757
12.221310102936098
12.221310101618734
12.221310100301634
12.221310098984839
12.221310097668322
12.221310096352092
12.221310095036152
12.221310093720493
12.221310092405126
12.221310091090038
12.221310089775235
12.22131008846072
12.221310087146488
12.221310085832545
12.221310084518887
12.221310083205505
12.221310081892423
12.221310080579615
12.221310079267095
12.221310077954861
12.22131007664291
12.221310075331246
12.221310074019865
12.221310072708766
12.22131007139796
12.22131007008743
12.221310068777196
12.221310067467233
12.221310066157555
12.22131006484817
12.221310063539057
12.221310062230241
12.221310060921704
12.22131005961345
12.221310058305484
12.221310056997794
12.2213100556904
12.221310054383279
12.221310053076449
12.221310051769892
12.221310050463627
12.221310049157651
12.221310047851945
12.221310046546536
12.221310045241388
12.22131004393654
12.221310042631982
12.221310041327698
12.221310040023694
12.221310038719977
12.22131003741654
12.221310036113396
12.221310034810523
12.221310033507946
12.221310032205638
12.221310030903618
12.221310029601879
12.221310028300419
12.221310026999253
12.221310025698362
12.221310024397754
12.221310023097425
12.221310021797391
12.221310020497624
12.22131001919814
12.221310017898942
12.221310016600032
12.221310015301393
12.221310014003041
12.221310012704976
12.221310011407198
12.221310010109685
12.221310008812457
12.221310007515525
12.221310006218854
12.221310004922477
12.22131000362638
12.221310002330565
12.221310001035027
12.221309999739768
12.221309998444797
12.221309997150104
12.221309995855695
12.221309994561558
12.221309993267715
12.221309991974143
12.221309990680854
12.221309989387855
12.221309988095129
12.221309986802675
12.22130998551051
12.221309984218633
12.221309982927018
12.2213099816357
12.221309980344653
12.221309979053887
12.221309977763402
12.221309976473195
12.221309975183281
12.221309973893634
12.221309972604269
12.221309971315181
12.221309970026383
12.221309968737858
12.221309967449615
12.221309966161643
12.22130996487396
12.221309963586558
12.221309962299426
12.221309961012583
12.221309959726014
12.221309958439731
12.221309957153714
12.221309955867985
12.221309954582539
12.221309953297363
12.22130995201247
12.221309950727854
12.22130994944352
12.221309948159458
12.221309946875685
12.22130994559218
12.221309944308961
12.221309943026014
12.221309941743357
12.221309940460968
12.22130993917887
12.221309937897031
12.221309936615489
12.221309935334212
12.221309934053215
12.221309932772499
12.221309931492062
12.221309930211898
12.22130992893202
12.221309927652422
12.221309926373083
12.221309925094038
12.221309923815268
12.221309922536772
12.221309921258557
12.22130991998061
12.221309918702955
12.221309917425568
12.221309916148465
12.22130991487164
12.22130991359508
12.221309912318802
12.221309911042802
12.221309909767081
12.221309908491635
12.221309907216467
12.221309905941574
12.221309904666962
12.221309903392624
12.221309902118563
12.221309900844776
12.221309899571269
12.221309898298038
12.221309897025078
12.221309895752398
12.221309894479997
12.221309893207872
12.221309891936016
12.221309890664445
12.221309889393144
12.221309888122128
12.221309886851373
12.221309885580911
12.221309884310713
12.221309883040785
12.221309881771143
12.22130988050177
12.221309879232678
12.22130987796387
12.221309876695326
12.221309875427057
12.221309874159065
12.221309872891345
12.221309871623903
12.221309870356736
12.221309869089849
12.221309867823233
12.221309866556895
12.221309865290824
12.221309864025033
12.221309862759517
12.221309861494271
12.221309860229299
12.22130985896461
12.221309857700188
12.221309856436049
12.221309855172176
12.221309853908583
12.221309852645263
12.221309851382212
12.221309850119443
12.221309848856945
12.221309847594718
12.221309846332765
12.221309845071087
12.221309843809685
12.221309842548555
12.2213098412877
12.22130984002712
12.221309838766812
12.221309837506778
12.22130983624702
12.221309834987531
12.221309833728316
12.22130983246937
12.2213098312107
12.221309829952313
12.22130982869419
12.22130982743634
12.221309826178766
12.221309824921468
12.221309823664445
12.221309822407678
12.221309821151193
12.221309819894978
12.221309818639039
12.221309817383375
12.22130981612799
12.221309814872859
12.221309813618017
12.22130981236344
12.22130981110913
12.221309809855102
12.221309808601342
12.221309807347858
12.22130980609463
12.221309804841697
12.22130980358903
12.221309802336618
12.221309801084496
12.22130979983264
12.221309798581059
12.221309797329745

12.221309796078712
12.22130979482794
12.221309793577445
12.221309792327215
12.221309791077255
12.221309789827574
12.22130978857816
12.221309787329021
12.221309786080145
12.221309784831542
12.221309783583225
12.221309782335167
12.221309781087385
12.221309779839869
12.221309778592618
12.221309777345645
12.221309776098936
12.221309774852514
12.221309773606345
12.221309772360451
12.22130977111483
12.221309769869478
12.221309768624398
12.221309767379585
12.221309766135038
12.221309764890782
12.221309763646778
12.221309762403045
12.22130976115959
12.221309759916398
12.22130975867348
12.22130975743083
12.221309756188443
12.221309754946335
12.221309753704496
12.221309752462924
12.221309751221618
12.22130974998059
12.22130974873982
12.221309747499324
12.221309746259106
12.221309745019145
12.221309743779456
12.221309742540038
12.221309741300896
12.221309740062015
12.2213097388234
12.221309737585054
12.22130973634698
12.221309735109182
12.221309733871646
12.221309732634378
12.221309731397376
12.221309730160648
12.221309728924188
12.221309727687993
12.221309726452066
12.221309725216413
12.221309723981019
12.221309722745906
12.221309721511048
12.221309720276466
12.221309719042148
12.221309717808102
12.221309716574323
12.2213097153408
12.22130971410756
12.22130971287458
12.221309711641867
12.221309710409423
12.221309709177254
12.221309707945341
12.221309706713711
12.221309705482328
12.221309704251222
12.221309703020394
12.221309701789822
12.221309700559512
12.221309699329474
12.221309698099713
12.2213096968702
12.221309695640967
12.221309694411996
12.221309693183297
12.221309691954865
12.221309690726692
12.22130968949879
12.22130968827115
12.22130968704378
12.221309685816673
12.22130968458983
12.221309683363266
12.221309682136962
12.221309680910927
12.221309679685154
12.221309678459642
12.22130967723441
12.221309676009437
12.221309674784726
12.221309673560276
12.221309672336105
12.221309671112195
12.22130966988855
12.221309668665162
12.221309667442053
12.221309666219202
12.22130966499662
12.2213096637743
12.22130966255225
12.221309661330462
12.22130966010893
12.221309658887682
12.221309657666687
12.221309656445959
12.221309655225499
12.221309654005307
12.221309652785365
12.221309651565704
12.221309650346303
12.221309649127157
12.221309647908278
12.221309646689676
12.221309645471337
12.22130964425325
12.221309643035443
12.221309641817882
12.221309640600596
12.221309639383566
12.221309638166812
12.221309636950322
12.221309635734093
12.221309634518123
12.221309633302424
12.221309632086975
12.221309630871804
12.221309629656892
12.221309628442246
12.221309627227866
12.221309626013744
12.221309624799883
12.221309623586292
12.221309622372962
12.221309621159895
12.221309619947085
12.221309618734551
12.221309617522277
12.221309616310261
12.221309615098509
12.221309613887021
12.221309612675796
12.221309611464834
12.221309610254139
12.221309609043693
12.221309607833522
12.221309606623604
12.221309605413964
12.221309604204576
12.221309602995458
12.221309601786597
12.221309600577996
12.22130959936966
12.221309598161577
12.221309596953773
12.221309595746217
12.221309594538942
12.22130959333191
12.22130959212514
12.221309590918652
12.2213095897124
12.221309588506426
12.221309587300714
12.221309586095254
12.221309584890061
12.221309583685127
12.22130958248046
12.221309581276051
12.221309580071908
12.221309578868018
12.221309577664398
12.221309576461032
12.221309575257926
12.221309574055091
12.22130957285251
12.221309571650195
12.22130957044814
12.221309569246346
12.2213095680448
12.221309566843528
12.221309565642521
12.221309564441766
12.221309563241265
12.221309562041034
12.22130956084106
12.221309559641345
12.221309558441904
12.221309557242709
12.221309556043785
12.221309554845117
12.221309553646702
12.221309552448544
12.221309551250656
12.221309550053032
12.221309548855661
12.22130954765855
12.221309546461699
12.221309545265111
12.221309544068784
12.22130954287271
12.221309541676899
12.22130954048134
12.221309539286054
12.221309538091013
12.221309536896243
12.221309535701726
12.221309534507471
12.22130953331348
12.221309532119738
12.221309530926261
12.22130952973305
12.221309528540091
12.221309527347387
12.221309526154945
12.221309524962763
12.221309523770834
12.221309522579174
12.221309521387763
12.221309520196625
12.221309519005729
12.22130951781509
12.221309516624721
12.221309515434605
12.221309514244753
12.221309513055166
12.221309511865815
12.221309510676734
12.221309509487908
12.221309508299344
12.22130950711104
12.221309505922996
12.2213095047352
12.221309503547662
12.22130950236039
12.221309501173366
12.221309499986608
12.22130949880011
12.221309497613861
12.22130949642788
12.221309495242139
12.22130949405667
12.221309492871452
12.221309491686496
12.221309490501788
12.221309489317346
12.221309488133159
12.221309486949227
12.221309485765559
12.221309484582134
12.221309483398981
12.221309482216077
12.22130948103343
12.221309479851037
12.221309478668909
12.221309477487033
12.221309476305414
12.221309475124048
12.22130947394294
12.221309472762092
12.221309471581499
12.221309470401158
12.22130946922108
12.221309468041255
12.22130946686168
12.221309465682374
12.221309464503316
12.221309463324506
12.221309462145964
12.221309460967674
12.221309459789644
12.221309458611863
12.221309457434339
12.221309456257071
12.221309455080062
12.221309453903306
12.2213094527268
12.221309451550557
12.221309450374566
12.221309449198836
12.221309448023353
12.221309446848135
12.221309445673166
12.221309444498432
12.221309443323987
12.221309442149778
12.221309440975832
12.221309439802138
12.221309438628694
12.221309437455519
12.221309436282576
12.221309435109896
12.22130943393748
12.221309432765311
12.221309431593403
12.221309430421739
12.22130942925034
12.221309428079188
12.221309426908293
12.22130942573765
12.22130942456726
12.22130942339713
12.221309422227256
12.221309421057624
12.221309419888259
12.221309418719134
12.221309417550271
12.221309416381665
12.221309415213302
12.221309414045198
12.221309412877352
12.22130941170976
12.22130941054241
12.221309409375317
12.22130940820849
12.221309407041902
12.221309405875571
12.221309404709496
12.221309403543676
12.2213094023781
12.221309401212784
12.22130940004772
12.221309398882912
12.22130939771835
12.221309396554048
12.221309395389989
12.221309394226193
12.221309393062645
12.221309391899345
12.22130939073631
12.221309389573516
12.221309388410974
12.221309387248688
12.221309386086656
12.22130938492488
12.22130938376335
12.22130938260207
12.221309381441039
12.221309380280273
12.221309379119752
12.221309377959484
12.221309376799457
12.221309375639702
12.22130937448018
12.221309373320924
12.221309372161913
12.221309371003157
12.22130936984465
12.221309368686383
12.221309367528386
12.221309366370633
12.221309365213127
12.221309364055882
12.221309362898875
12.221309361742133
12.221309360585632
12.221309359429391
12.221309358273386
12.221309357117642
12.221309355962156
12.22130935480691
12.221309353651915
12.221309352497181
12.221309351342683
12.221309350188447
12.221309349034447
12.221309347880707
12.221309346727224
12.221309345573989
12.221309344420996
12.221309343268265
12.221309342115775
12.221309340963531
12.221309339811551
12.221309338659813
12.221309337508323
12.22130933635709
12.221309335206097
12.22130933405537
12.221309332904864
12.221309331754638
12.221309330604644
12.221309329454902
12.221309328305418
12.221309327156176
12.221309326007184
12.221309324858442
12.221309323709953
12.221309322561716
12.221309321413715
12.221309320265973
12.221309319118475
12.221309317971231
12.221309316824232
12.221309315677493
12.221309314530991
12.221309313384737
12.221309312238734
12.221309311092982
12.221309309947474
12.221309308802224
12.221309307657215
12.221309306512461
12.221309305367953
12.221309304223688
12.221309303079671
12.221309301935904
12.221309300792392
12.22130929964912
12.221309298506107
12.221309297363334
12.22130929622081
12.221309295078528
12.221309293936502
12.221309292794725
12.221309291653187
12.221309290511904
12.22130928937087
12.221309288230078
12.221309287089536
12.22130928594924
12.221309284809195
12.221309283669394
12.221309282529846
12.221309281390534
12.221309280251486
12.221309279112669
12.22130927797411
12.221309276835791
12.221309275697726
12.221309274559909
12.221309273422321
12.221309272285016
12.221309271147923
12.221309270011076
12.22130926887449
12.221309267738162
12.221309266602063
12.221309265466212
12.221309264330609
12.221309263195257
12.221309262060148
12.221309260925288
12.22130925979067
12.221309258656309
12.221309257522183
12.221309256388304
12.221309255254683
12.221309254121289
12.22130925298816
12.221309251855262

12.221309250722612
12.221309249590211
12.221309248458056
12.221309247326147
12.221309246194487
12.221309245063061
12.22130924393189
12.221309242800967
12.221309241670294
12.221309240539846
12.221309239409658
12.221309238279717
12.22130923715002
12.22130923602056
12.221309234891345
12.221309233762383
12.22130923263366
12.221309231505186
12.221309230376958
12.221309229248975
12.221309228121234
12.22130922699374
12.221309225866488
12.221309224739485
12.221309223612721
12.221309222486209
12.221309221359931
12.221309220233906
12.221309219108122
12.221309217982586
12.221309216857286
12.221309215732244
12.22130921460743
12.221309213482874
12.221309212358547
12.221309211234482
12.221309210110645
12.221309208987064
12.221309207863724
12.22130920674062
12.221309205617763
12.22130920449516
12.221309203372781
12.221309202250662
12.22130920112879
12.221309200007145
12.221309198885756
12.221309197764608
12.221309196643695
12.221309195523034
12.221309194402615
12.221309193282432
12.221309192162503
12.221309191042803
12.221309189923366
12.221309188804161
12.221309187685202
12.22130918656648
12.221309185448005
12.221309184329776
12.221309183211782
12.22130918209403
12.221309180976528
12.22130917985927
12.221309178742253
12.221309177625473
12.221309176508937
12.221309175392644
12.22130917427659
12.22130917316078
12.22130917204522
12.221309170929896
12.221309169814807
12.221309168699975
12.221309167585368
12.22130916647102
12.221309165356901
12.221309164243024
12.221309163129408
12.22130916201601
12.221309160902857
12.221309159789955
12.221309158677292
12.221309157564875
12.221309156452685
12.221309155340741
12.221309154229045
12.221309153117597
12.221309152006377
12.221309150895403
12.221309149784666
12.221309148674175
12.221309147563918
12.221309146453915
12.221309145344149
12.221309144234615
12.221309143125326
12.221309142016278
12.221309140907474
12.22130913979891
12.221309138690584
12.221309137582494
12.221309136474655
12.221309135367054
12.22130913425969
12.221309133152568
12.221309132045683
12.221309130939044
12.221309129832633
12.221309128726476
12.22130912762055
12.221309126514873
12.221309125409423
12.221309124304229
12.221309123199262
12.22130912209454
12.221309120990059
12.221309119885825
12.221309118781818
12.221309117678052
12.221309116574533
12.22130911547125
12.2213091143682
12.221309113265395
12.221309112162832
12.221309111060501
12.221309109958417
12.221309108856573
12.221309107754951
12.221309106653594
12.22130910555246
12.221309104451567
12.221309103350912
12.221309102250498
12.221309101150318
12.221309100050389
12.221309098950687
12.221309097851227
12.221309096752007
12.221309095653025
12.221309094554286
12.221309093455782
12.221309092357505
12.221309091259476
12.221309090161693
12.221309089064142
12.221309087966823
12.221309086869752
12.221309085772912
12.221309084676315
12.221309083579957
12.22130908248384
12.221309081387945
12.221309080292302
12.221309079196894
12.221309078101726
12.221309077006788
12.221309075912094
12.221309074817635
12.22130907372341
12.221309072629428
12.22130907153567
12.221309070442176
12.221309069348903
12.221309068255874
12.221309067163077
12.22130906607051
12.221309064978195
12.221309063886103
12.221309062794257
12.221309061702646
12.221309060611269
12.221309059520138
12.221309058429231
12.22130905733857
12.221309056248142
12.221309055157949
12.221309054068
12.221309052978286
12.221309051888799
12.221309050799553
12.221309049710541
12.221309048621777
12.22130904753324
12.221309046444945
12.221309045356886
12.221309044269052
12.22130904318146
12.221309042094104
12.221309041006986
12.221309039920106
12.221309038833457
12.22130903774705
12.221309036660871
12.221309035574928
12.221309034489227
12.221309033403763
12.221309032318528
12.221309031233533
12.221309030148769
12.221309029064246
12.22130902797996
12.221309026895899
12.221309025812083
12.221309024728498
12.221309023645142
12.221309022562036
12.221309021479149
12.221309020396506
12.221309019314099
12.221309018231926
12.221309017149988
12.221309016068284
12.221309014986822
12.221309013905577
12.221309012824577
12.221309011743811
12.221309010663278
12.221309009582981
12.221309008502924
12.221309007423093
12.22130900634351
12.221309005264136
12.221309004185027
12.22130900310613
12.22130900202747
12.221309000949049
12.22130899987086
12.221308998792905
12.221308997715182
12.221308996637696
12.22130899556045
12.221308994483433
12.221308993406645
12.22130899233009
12.221308991253775
12.221308990177695
12.221308989101848
12.22130898802623
12.221308986950845
12.221308985875698
12.221308984800777
12.221308983726095
12.221308982651651
12.221308981577426
12.22130898050344
12.221308979429693
12.221308978356177
12.221308977282899
12.221308976209844
12.221308975137026
12.221308974064435
12.221308972992087
12.221308971919962
12.221308970848078
12.221308969776423
12.221308968705
12.22130896763381
12.221308966562855
12.221308965492133
12.22130896442164
12.22130896335137
12.221308962281354
12.22130896121156
12.221308960141993
12.22130895907266
12.221308958003558
12.221308956934699
12.221308955866059
12.221308954797653
12.221308953729482
12.221308952661548
12.221308951593844
12.221308950526371
12.221308949459122
12.221308948392117
12.221308947325324
12.221308946258791
12.221308945192456
12.221308944126381
12.221308943060523
12.221308941994902
12.22130894092951
12.221308939864352
12.221308938799408
12.221308937734717
12.221308936670248
12.221308935606013
12.221308934542003
12.221308933478236
12.221308932414692
12.221308931351379
12.221308930288297
12.22130892922544
12.221308928162825
12.221308927100434
12.221308926038267
12.221308924976348
12.221308923914647
12.221308922853186
12.221308921791945
12.221308920730934
12.221308919670161
12.221308918609605
12.221308917549296
12.221308916489207
12.221308915429349
12.221308914369734
12.221308913310331
12.22130891225116
12.221308911192226
12.221308910133521
12.221308909075045
12.221308908016802
12.221308906958775
12.221308905900992
12.221308904843434
12.221308903786106
12.221308902729014
12.221308901672137
12.221308900615497
12.221308899559087
12.22130889850291
12.221308897446947
12.22130889639123
12.221308895335737
12.22130889428047
12.221308893225432
12.221308892170633
12.221308891116049
12.221308890061707
12.221308889007584
12.221308887953692
12.22130888690002
12.221308885846595
12.221308884793386
12.22130888374041
12.221308882687655
12.221308881635146
12.221308880582852
12.221308879530794
12.22130887847896
12.221308877427353
12.221308876375975
12.221308875324821
12.2213088742739
12.221308873223208
12.221308872172742
12.221308871122503
12.221308870072495
12.22130886902271
12.221308867973164
12.22130886692383
12.221308865874741
12.221308864825868
12.221308863777223
12.221308862728806
12.221308861680626
12.22130886063266
12.221308859584932
12.221308858537432
12.221308857490142
12.22130885644309
12.22130885539627
12.221308854349669
12.221308853303308
12.221308852257165
12.221308851211251
12.221308850165562
12.221308849120101
12.221308848074859
12.22130884702986
12.22130884598508
12.221308844940529
12.221308843896198
12.2213088428521
12.221308841808227
12.221308840764577
12.221308839721162
12.221308838677965
12.221308837634995
12.221308836592248
12.221308835549742
12.221308834507454
12.221308833465391
12.221308832423556
12.221308831381945
12.221308830340558
12.221308829299408
12.221308828258469
12.221308827217765
12.221308826177285
12.221308825137035
12.221308824097008
12.221308823057202
12.221308822017628
12.221308820978278
12.22130881993915
12.221308818900251
12.22130881786157
12.221308816823123
12.221308815784905
12.221308814746902
12.221308813709138
12.221308812671575
12.221308811634257
12.221308810597156
12.221308809560286
12.221308808523643
12.221308807487215
12.22130880645102
12.221308805415044
12.221308804379301
12.221308803343783
12.221308802308476
12.221308801273416
12.221308800238562
12.22130879920393
12.221308798169524
12.221308797135357
12.221308796101402
12.22130879506768
12.221308794034178
12.2213087930009
12.221308791967848
12.221308790935018
12.221308789902418
12.221308788870033
12.221308787837875
12.22130878680594
12.221308785774232
12.221308784742758
12.221308783711482
12.22130878268045
12.221308781649643
12.221308780619045
12.221308779588691
12.221308778558539
12.221308777528622
12.221308776498928
12.221308775469454
12.221308774440214
12.221308773411186
12.221308772382384
12.221308771353804
12.221308770325448
12.221308769297318
12.221308768269406
12.22130876724172
12.221308766214264
12.221308765187018
12.221308764160005
12.221308763133214
12.221308762106643
12.221308761080298
12.221308760054171
12.221308759028267
12.221308758002593
12.221308756977132
12.221308755951897
12.221308754926884
12.221308753902102
12.22130875287752
12.221308751853188
12.221308750829062
12.221308749805159
12.221308748781489
12.221308747758028
12.221308746734795
12.221308745711776
12.221308744688992
12.221308743666423
12.221308742644089
12.221308741621954
12.221308740600055
12.22130873957838
12.221308738556923
12.221308737535677
12.221308736514672
12.221308735493876
12.221308734473297
12.22130873345296
12.221308732432826
12.221308731412915
12.221308730393236
12.221308729373767
12.221308728354527
12.221308727335503
12.221308726316703
12.221308725298123
12.221308724279762
12.221308723261625
12.221308722243709
12.221308721226013
12.22130872020854
12.221308719191292
12.221308718174253
12.221308717157443
12.221308716140854
12.221308715124476
12.221308714108325
12.2213087130924
12.221308712076679
12.221308711061202
12.221308710045928
12.22130870903089
12.22130870801606
12.221308707001453
12.221308705987063
12.221308704972897
12.221308703958947
12.22130870294522
12.221308701931713
12.221308700918424
12.221308699905359
12.221308698892516
12.221308697879891
12.221308696867478
12.221308695855287
12.221308694843323
12.221308693831581
12.221308692820045
12.221308691808739
12.221308690797642
12.221308689786774
12.221308688776132
12.22130868776569
12.221308686755489
12.22130868574549
12.22130868473571
12.22130868372616
12.221308682716831
12.221308681707715
12.221308680698808
12.221308679690132
12.221308678681673
12.221308677673434
12.221308676665405
12.221308675657607
12.221308674650023
12.221308673642664
12.22130867263551
12.22130867162858
12.221308670621871
12.221308669615386
12.221308668609113
12.221308667603054
12.221308666597226
12.221308665591604
12.221308664586209
12.221308663581024
12.221308662576053
12.221308661571312
12.221308660566788
12.221308659562483
12.22130865855838
12.22130865755452
12.221308656550859
12.221308655547425
12.221308654544204
12.221308653541197
12.221308652538418
12.221308651535852
12.22130865053351
12.221308649531371
12.221308648529462
12.22130864752776
12.221308646526287
12.221308645525022
12.221308644523983
12.22130864352315
12.221308642522537
12.221308641522144
12.221308640521972
12.221308639522015
12.221308638522272
12.22130863752275
12.22130863652345
12.221308635524352
12.221308634525485
12.221308633526824
12.221308632528393
12.221308631530162
12.22130863053216

12.221308629534372
12.221308628536793
12.22130862753944
12.221308626542296
12.221308625545378
12.221308624548664
12.221308623552181
12.221308622555902
12.221308621559842
12.221308620564002
12.221308619568376
12.221308618572968
12.221308617577767
12.221308616582794
12.221308615588029
12.221308614593474
12.221308613599154
12.221308612605043
12.221308611611144
12.221308610617465
12.221308609623986
12.221308608630743
12.221308607637708
12.221308606644879
12.221308605652272
12.221308604659885
12.22130860366771
12.22130860267575
12.22130860168401
12.221308600692476
12.221308599701167
12.221308598710072
12.221308597719187
12.22130859672852
12.221308595738062
12.22130859474783
12.221308593757803
12.221308592768002
12.221308591778412
12.221308590789029
12.221308589799865
12.221308588810919
12.221308587822183
12.221308586833663
12.221308585845355
12.221308584857258
12.221308583869389
12.221308582881731
12.221308581894279
12.221308580907047
12.221308579920025
12.22130857893322
12.221308577946635
12.221308576960263
12.221308575974096
12.221308574988148
12.221308574002409
12.22130857301689
12.221308572031585
12.221308571046492
12.221308570061616
12.221308569076948
12.221308568092496
12.221308567108267
12.221308566124241
12.221308565140426
12.22130856415683
12.221308563173451
12.221308562190277
12.221308561207328
12.22130856022458
12.22130855924205
12.221308558259736
12.221308557277636
12.221308556295739
12.221308555314069
12.221308554332602
12.221308553351353
12.221308552370315
12.221308551389487
12.221308550408875
12.221308549428475
12.22130854844829
12.221308547468325
12.221308546488553
12.22130854550901
12.221308544529673
12.221308543550547
12.22130854257163
12.221308541592942
12.221308540614455
12.22130853963618
12.221308538658121
12.221308537680272
12.221308536702635
12.221308535725212
12.221308534747987
12.221308533771007
12.221308532794207
12.221308531817632
12.221308530841275
12.221308529865128
12.221308528889177
12.221308527913452
12.221308526937932
12.221308525962629
12.221308524987533
12.221308524012654
12.221308523037987
12.221308522063527
12.221308521089279
12.221308520115246
12.221308519141422
12.221308518167811
12.221308517194407
12.221308516221221
12.221308515248234
12.221308514275465
12.221308513302914
12.22130851233057
12.22130851135844
12.221308510386505
12.221308509414795
12.221308508443297
12.221308507472003
12.221308506500927
12.221308505530061
12.2213085045594
12.221308503588952
12.221308502618722
12.22130850164869
12.221308500678871
12.221308499709265
12.22130849873987
12.22130849777069
12.221308496801713
12.221308495832945
12.221308494864392
12.22130849389605
12.221308492927916
12.221308491959995
12.221308490992286
12.22130849002478
12.221308489057483
12.221308488090406
12.221308487123533
12.221308486156872
12.221308485190416
12.22130848422417
12.221308483258136
12.221308482292319
12.221308481326702
12.2213084803613
12.221308479396097
12.221308478431107
12.221308477466339
12.221308476501765
12.221308475537413
12.221308474573261
12.221308473609323
12.221308472645593
12.221308471682077
12.22130847071876
12.221308469755662
12.221308468792767
12.221308467830077
12.22130846686761
12.221308465905336
12.22130846494328
12.221308463981426
12.221308463019788
12.221308462058357
12.22130846109714
12.22130846013612
12.22130845917531
12.221308458214718
12.221308457254334
12.221308456294148
12.22130845533418
12.221308454374416
12.221308453414856
12.221308452455517
12.221308451496379
12.221308450537446
12.221308449578725
12.221308448620212
12.2213084476619
12.221308446703805
12.221308445745912
12.221308444788233
12.221308443830756
12.221308442873493
12.221308441916431
12.221308440959577
12.221308440002945
12.221308439046501
12.221308438090272
12.221308437134248
12.22130843617844
12.221308435222834
12.221308434267428
12.221308433312242
12.221308432357263
12.221308431402484
12.22130843044792
12.221308429493558
12.221308428539396
12.221308427585454
12.221308426631708
12.221308425678178
12.221308424724848
12.221308423771733
12.221308422818824
12.221308421866114
12.221308420913614
12.22130841996132
12.221308419009237
12.221308418057356
12.221308417105682
12.221308416154217
12.221308415202962
12.22130841425191
12.22130841330106
12.221308412350414
12.221308411399976
12.221308410449767
12.221308409499734
12.221308408549916
12.221308407600315
12.221308406650904
12.221308405701707
12.22130840475272
12.221308403803937
12.22130840285536
12.221308401906988
12.221308400958819
12.221308400010853
12.221308399063105
12.22130839811555
12.221308397168206
12.221308396221067
12.221308395274134
12.221308394327412
12.221308393380886
12.221308392434569
12.221308391488456
12.221308390542555
12.221308389596848
12.221308388651355
12.221308387706067
12.221308386760981
12.221308385816101
12.221308384871437
12.221308383926953
12.221308382982693
12.221308382038634
12.221308381094781
12.221308380151136
12.221308379207688
12.22130837826444
12.22130837732141
12.22130837637858
12.221308375435946
12.221308374493535
12.221308373551315
12.2213083726093
12.22130837166749
12.221308370725891
12.221308369784486
12.221308368843301
12.2213083679023
12.221308366961518
12.22130836602094
12.221308365080558
12.221308364140382
12.221308363200416
12.22130836226064
12.221308361321082
12.221308360381727
12.221308359442576
12.221308358503627
12.221308357564883
12.221308356626336
12.221308355687993
12.22130835474986
12.221308353811935
12.221308352874207
12.221308351936674
12.221308350999351
12.221308350062237
12.221308349125314
12.221308348188614
12.221308347252107
12.221308346315793
12.2213083453797
12.221308344443804
12.221308343508104
12.22130834257261
12.221308341637325
12.221308340702233
12.22130833976735
12.221308338832673
12.221308337898195
12.221308336963927
12.221308336029855
12.221308335095983
12.221308334162318
12.221308333228862
12.221308332295587
12.221308331362534
12.221308330429675
12.221308329497031
12.221308328564588
12.22130832763233
12.22130832670028
12.22130832576844
12.221308324836798
12.221308323905363
12.221308322974124
12.22130832204309
12.221308321112263
12.22130832018162
12.221308319251195
12.221308318320967
12.221308317390946
12.221308316461117
12.221308315531504
12.22130831460208
12.221308313672868
12.221308312743847
12.221308311815037
12.221308310886418
12.221308309958006
12.221308309029794
12.221308308101793
12.221308307173986
12.221308306246371
12.221308305318969
12.221308304391775
12.221308303464767
12.221308302537972
12.221308301611373
12.221308300684973
12.221308299758777
12.221308298832785
12.221308297906983
12.221308296981384
12.221308296056
12.221308295130804
12.221308294205812
12.221308293281021
12.221308292356428
12.221308291432042
12.221308290507853
12.221308289583867
12.221308288660076
12.221308287736486
12.2213082868131
12.221308285889917
12.221308284966925
12.221308284044142
12.221308283121564
12.221308282199177
12.221308281276984
12.22130828035501
12.221308279433217
12.221308278511641
12.221308277590255
12.221308276669069
12.221308275748088
12.221308274827305
12.221308273906718
12.22130827298633
12.22130827206615
12.221308271146158
12.221308270226379
12.221308269306789
12.221308268387395
12.22130826746821
12.22130826654923
12.221308265630435
12.221308264711842
12.221308263793453
12.221308262875267
12.221308261957276
12.221308261039495
12.221308260121898
12.2213082592045
12.22130825828731
12.22130825737032
12.221308256453526
12.221308255536929
12.221308254620523
12.22130825370433
12.221308252788324
12.221308251872522
12.221308250956916
12.22130825004152
12.22130824912632
12.221308248211304
12.2213082472965
12.22130824638189
12.221308245467487
12.22130824455327
12.221308243639255
12.221308242725438
12.22130824181182
12.221308240898397
12.221308239985184
12.221308239072162
12.221308238159338
12.221308237246712
12.22130823633428
12.221308235422052
12.22130823451002
12.221308233598185
12.22130823268655
12.22130823177511
12.221308230863874
12.221308229952822
12.221308229041984
12.22130822813134
12.221308227220883
12.22130822631064
12.221308225400582
12.221308224490727
12.221308223581065
12.221308222671603
12.221308221762337
12.221308220853274
12.221308219944405
12.22130821903573
12.221308218127257
12.221308217218978
12.221308216310899
12.22130821540302
12.22130821449533
12.22130821358784
12.221308212680537
12.22130821177345
12.22130821086655
12.221308209959844
12.221308209053337
12.221308208147025
12.221308207240925
12.221308206335006
12.221308205429278
12.221308204523767
12.221308203618442
12.221308202713308
12.221308201808382
12.221308200903646
12.221308199999099
12.221308199094754
12.221308198190602
12.221308197286655
12.221308196382905
12.22130819547934
12.22130819457598
12.221308193672817
12.22130819276985
12.22130819186708
12.221308190964496
12.221308190062121
12.221308189159926
12.22130818825794
12.221308187356144
12.221308186454543
12.221308185553138
12.221308184651928
12.221308183750915
12.2213081828501
12.221308181949476
12.221308181049059
12.221308180148826
12.221308179248792
12.221308178348943
12.221308177449306
12.221308176549858
12.221308175650604
12.221308174751544
12.22130817385267
12.221308172954004
12.221308172055535
12.221308171157265
12.221308170259173
12.221308169361285
12.22130816846359
12.221308167566098
12.221308166668793
12.221308165771681
12.221308164874761
12.221308163978044
12.221308163081522
12.221308162185194
12.221308161289063
12.221308160393114
12.221308159497367
12.221308158601824
12.22130815770646
12.221308156811299
12.221308155916333
12.221308155021543
12.221308154126968
12.221308153232583
12.221308152338386
12.22130815144439
12.221308150550588
12.221308149656975
12.221308148763555
12.22130814787033
12.221308146977307
12.221308146084477
12.221308145191836
12.221308144299377
12.22130814340713
12.221308142515058
12.2213081416232
12.221308140731526
12.22130813984005
12.221308138948762
12.221308138057672
12.221308137166767
12.221308136276066
12.22130813538555
12.221308134495233
12.221308133605108
12.221308132715176
12.221308131825438
12.221308130935883
12.221308130046545
12.221308129157377

12.221308128268412
12.221308127379627
12.221308126491056
12.221308125602668
12.221308124714469
12.221308123826473
12.221308122938655
12.221308122051035
12.221308121163617
12.221308120276385
12.221308119389338
12.221308118502504
12.221308117615838
12.22130811672937
12.221308115843108
12.221308114957035
12.221308114071142
12.22130811318545
12.221308112299953
12.221308111414645
12.221308110529524
12.221308109644594
12.221308108759871
12.221308107875338
12.22130810699099
12.221308106106825
12.22130810522286
12.221308104339094
12.22130810345551
12.221308102572122
12.221308101688923
12.221308100805917
12.221308099923096
12.221308099040474
12.221308098158053
12.221308097275816
12.221308096393763
12.221308095511914
12.221308094630244
12.221308093748773
12.221308092867483
12.221308091986398
12.221308091105497
12.221308090224792
12.221308089344273
12.221308088463946
12.221308087583807
12.22130808670387
12.22130808582412
12.221308084944551
12.221308084065182
12.221308083185997
12.221308082307008
12.221308081428218
12.221308080549614
12.221308079671182
12.221308078792969
12.221308077914923
12.221308077037081
12.22130807615943
12.221308075281964
12.22130807440469
12.221308073527606
12.221308072650707
12.221308071774008
12.221308070897496
12.221308070021175
12.221308069145039
12.221308068269105
12.221308067393352
12.221308066517791
12.221308065642418
12.221308064767234
12.221308063892245
12.22130806301744
12.221308062142828
12.221308061268413
12.22130806039417
12.221308059520135
12.221308058646276
12.221308057772612
12.221308056899147
12.221308056025862
12.221308055152765
12.22130805427986
12.221308053407142
12.22130805253462
12.221308051662287
12.221308050790139
12.221308049918175
12.221308049046412
12.221308048174828
12.221308047303442
12.22130804643224
12.22130804556123
12.221308044690405
12.221308043819771
12.221308042949328
12.221308042079068
12.221308041209003
12.221308040339126
12.221308039469434
12.22130803859993
12.221308037730621
12.221308036861501
12.221308035992564
12.221308035123819
12.22130803425526
12.221308033386894
12.221308032518712
12.221308031650713
12.221308030782914
12.221308029915305
12.221308029047876
12.221308028180632
12.221308027313585
12.221308026446712
12.221308025580049
12.221308024713563
12.221308023847266
12.221308022981152
12.221308022115235
12.221308021249497
12.221308020383955
12.221308019518593
12.221308018653417
12.221308017788438
12.22130801692364
12.221308016059034
12.22130801519461
12.221308014330386
12.221308013466333
12.221308012602485
12.221308011738813
12.221308010875331
12.221308010012036
12.221308009148931
12.221308008286016
12.22130800742328
12.221308006560735
12.221308005698376
12.221308004836208
12.221308003974228
12.221308003112426
12.22130800225082
12.221308001389392
12.221308000528154
12.221307999667104
12.22130799880625
12.221307997945573
12.221307997085086
12.221307996224787
12.221307995364674
12.221307994504743
12.221307993645004
12.22130799278544
12.221307991926079
12.221307991066894
12.2213079902079
12.221307989349093
12.221307988490475
12.221307987632025
12.221307986773784
12.221307985915718
12.221307985057841
12.221307984200157
12.221307983342651
12.221307982485335
12.221307981628195
12.221307980771247
12.221307979914487
12.221307979057915
12.221307978201525
12.221307977345324
12.221307976489305
12.22130797563348
12.221307974777828
12.221307973922375
12.221307973067095
12.221307972212008
12.221307971357103
12.221307970502385
12.221307969647858
12.221307968793512
12.221307967939355
12.22130796708538
12.221307966231581
12.221307965377985
12.221307964524566
12.221307963671327
12.221307962818278
12.221307961965412
12.221307961112737
12.221307960260248
12.221307959407936
12.221307958555812
12.22130795770387
12.221307956852117
12.22130795600055
12.221307955149172
12.221307954297972
12.221307953446953
12.22130795259612
12.221307951745478
12.221307950895016
12.221307950044743
12.221307949194648
12.22130794834474
12.221307947495024
12.22130794664548
12.221307945796136
12.221307944946968
12.221307944097976
12.221307943249174
12.221307942400552
12.221307941552125
12.221307940703873
12.221307939855816
12.221307939007938
12.221307938160242
12.22130793731273
12.221307936465394
12.221307935618253
12.2213079347713
12.221307933924525
12.22130793307792
12.221307932231507
12.221307931385292
12.22130793053925
12.221307929693399
12.221307928847722
12.22130792800222
12.221307927156925
12.221307926311793
12.221307925466864
12.221307924622103
12.221307923777532
12.221307922933137
12.221307922088933
12.221307921244911
12.221307920401069
12.221307919557418
12.221307918713931
12.22130791787065
12.221307917027536
12.221307916184617
12.22130791534187
12.221307914499311
12.221307913656934
12.221307912814744
12.221307911972737
12.221307911130902
12.22130791028926
12.221307909447804
12.221307908606516
12.221307907765425
12.221307906924498
12.221307906083773
12.221307905243227
12.221307904402854
12.221307903562666
12.221307902722668
12.221307901882847
12.221307901043213
12.221307900203758
12.22130789936448
12.221307898525387
12.221307897686483
12.221307896847748
12.221307896009208
12.221307895170849
12.221307894332668
12.221307893494664
12.221307892656851
12.221307891819219
12.22130789098176
12.221307890144493
12.221307889307397
12.221307888470491
12.221307887633767
12.22130788679722
12.22130788596086
12.22130788512467
12.221307884288679
12.221307883452853
12.221307882617214
12.221307881781765
12.221307880946489
12.22130788011139
12.221307879276479
12.221307878441747
12.221307877607197
12.221307876772826
12.22130787593864
12.221307875104639
12.221307874270808
12.221307873437162
12.221307872603697
12.221307871770419
12.221307870937316
12.221307870104397
12.221307869271651
12.22130786843909
12.221307867606708
12.22130786677452
12.2213078659425
12.221307865110663
12.221307864279007
12.221307863447528
12.221307862616232
12.221307861785114
12.221307860954184
12.221307860123433
12.221307859292851
12.22130785846246
12.22130785763225
12.221307856802218
12.221307855972363
12.221307855142689
12.221307854313196
12.221307853483886
12.22130785265475
12.221307851825797
12.221307850997023
12.22130785016843
12.221307849340018
12.221307848511787
12.22130784768373
12.221307846855858
12.221307846028159
12.221307845200643
12.221307844373312
12.221307843546155
12.221307842719185
12.22130784189238
12.221307841065771
12.221307840239328
12.221307839413072
12.221307838586988
12.221307837761099
12.221307836935367
12.221307836109832
12.221307835284476
12.221307834459292
12.22130783363428
12.22130783280946
12.221307831984811
12.221307831160345
12.221307830336055
12.221307829511947
12.22130782868802
12.221307827864273
12.221307827040702
12.221307826217304
12.221307825394092
12.22130782457105
12.221307823748203
12.22130782292552
12.221307822103018
12.221307821280694
12.221307820458549
12.221307819636582
12.2213078188148
12.221307817993189
12.221307817171757
12.221307816350501
12.221307815529428
12.22130781470854
12.221307813887822
12.221307813067295
12.221307812246927
12.221307811426744
12.221307810606735
12.221307809786905
12.221307808967259
12.221307808147793
12.221307807328495
12.221307806509383
12.221307805690449
12.221307804871689
12.221307804053108
12.2213078032347
12.221307802416472
12.221307801598426
12.221307800780554
12.221307799962863
12.221307799145345
12.22130779832801
12.22130779751084
12.221307796693857
12.221307795877054
12.221307795060431
12.221307794243973
12.2213077934277
12.221307792611597
12.221307791795676
12.221307790979933
12.221307790164365
12.221307789348984
12.221307788533766
12.22130778771873
12.221307786903873
12.221307786089183
12.221307785274675
12.221307784460356
12.221307783646203
12.221307782832236
12.221307782018433
12.22130778120481
12.221307780391363
12.221307779578101
12.221307778765
12.22130777795209
12.221307777139351
12.221307776326785
12.221307775514406
12.221307774702192
12.221307773890164
12.221307773078303
12.221307772266616
12.22130777145512
12.221307770643778
12.221307769832627
12.221307769021655
12.22130776821086
12.221307767400235
12.221307766589785
12.221307765779509
12.22130776496942
12.221307764159492
12.22130776334975
12.22130776254018
12.221307761730788
12.221307760921574
12.221307760112529
12.221307759303656
12.221307758494977
12.221307757686448
12.221307756878108
12.221307756069946
12.221307755261954
12.221307754454138
12.221307753646503
12.221307752839037
12.22130775203175
12.221307751224641
12.221307750417704
12.221307749610935
12.221307748804342
12.22130774799794
12.221307747191702
12.221307746385635
12.221307745579747
12.221307744774041
12.22130774396851
12.221307743163136
12.221307742357943
12.221307741552925
12.221307740748095
12.221307739943438
12.221307739138947
12.221307738334627
12.221307737530495
12.22130773672652
12.221307735922734
12.221307735119119
12.221307734315674
12.221307733512397
12.221307732709313
12.221307731906387
12.221307731103645
12.221307730301078
12.22130772949868
12.221307728696464
12.221307727894416
12.221307727092539
12.221307726290839
12.221307725489313
12.221307724687962
12.221307723886781
12.221307723085777
12.221307722284953
12.221307721484292
12.221307720683809
12.221307719883502
12.22130771908336
12.221307718283404
12.221307717483617
12.221307716684002
12.221307715884565
12.221307715085292
12.221307714286201
12.221307713487278
12.221307712688533
12.221307711889956
12.221307711091564
12.221307710293324
12.221307709495276
12.221307708697397
12.221307707899685
12.221307707102158
12.221307706304794
12.221307705507606
12.221307704710599
12.221307703913748
12.221307703117077
12.22130770232058
12.221307701524259
12.221307700728113
12.221307699932131
12.221307699136325
12.221307698340695
12.221307697545237
12.221307696749948
12.221307695954835
12.221307695159892
12.221307694365128
12.221307693570527
12.221307692776106
12.221307691981858
12.221307691187771
12.221307690393864
12.221307689600133
12.22130768880657
12.221307688013173
12.221307687219962
12.221307686426917
12.221307685634045
12.22130768484135
12.221307684048812
12.221307683256448
12.221307682464271
12.221307681672256
12.221307680880411
12.221307680088742
12.221307679297249
12.22130767850592
12.221307677714762
12.221307676923786
12.221307676132973
12.221307675342334
12.221307674551872
12.22130767376157
12.221307672971438
12.221307672181487
12.221307671391713
12.2213076706021
12.221307669812663
12.221307669023396
12.221307668234292
12.221307667445377
12.221307666656616
12.221307665868036
12.22130766507963
12.221307664291393
12.221307663503318

12.221307662715422
12.221307661927685
12.221307661140136
12.221307660352748
12.221307659565543
12.221307658778493
12.221307657991622
12.221307657204926
12.221307656418391
12.221307655632028
12.221307654845836
12.221307654059817
12.22130765327397
12.221307652488294
12.221307651702784
12.221307650917451
12.221307650132276
12.221307649347283
12.22130764856246
12.221307647777806
12.221307646993328
12.221307646209006
12.221307645424867
12.221307644640884
12.221307643857086
12.22130764307345
12.221307642289986
12.22130764150669
12.221307640723568
12.221307639940619
12.22130763915783
12.221307638375217
12.221307637592778
12.221307636810506
12.2213076360284
12.22130763524647
12.221307634464694
12.221307633683097
12.221307632901677
12.221307632120414
12.221307631339332
12.221307630558414
12.221307629777666
12.221307628997094
12.221307628216683
12.221307627436447
12.221307626656369
12.221307625876472
12.22130762509673
12.22130762431718
12.221307623537784
12.22130762275856
12.221307621979506
12.221307621200621
12.221307620421904
12.221307619643357
12.221307618864982
12.221307618086769
12.22130761730874
12.221307616530856
12.221307615753148
12.221307614975625
12.221307614198254
12.221307613421063
12.221307612644027
12.221307611867179
12.221307611090484
12.221307610313959
12.221307609537613
12.221307608761418
12.221307607985407
12.221307607209555
12.221307606433879
12.221307605658364
12.221307604883028
12.221307604107846
12.221307603332848
12.221307602558017
12.221307601783336
12.22130760100884
12.221307600234505
12.221307599460328
12.221307598686334
12.221307597912507
12.221307597138841
12.221307596365353
12.221307595592016
12.221307594818867
12.221307594045877
12.221307593273059
12.221307592500397
12.22130759172792
12.221307590955588
12.221307590183443
12.221307589411465
12.221307588639645
12.22130758786799
12.221307587096508
12.221307586325192
12.22130758555405
12.221307584783075
12.221307584012251
12.22130758324162
12.221307582471137
12.221307581700824
12.22130758093069
12.221307580160715
12.221307579390892
12.221307578621255
12.221307577851784
12.221307577082474
12.221307576313329
12.221307575544358
12.221307574775553
12.221307574006913
12.221307573238452
12.221307572470133
12.221307571701999
12.221307570934025
12.221307570166216
12.221307569398574
12.221307568631103
12.2213075678638
12.221307567096664
12.221307566329688
12.221307565562876
12.221307564796241
12.221307564029772
12.22130756326346
12.22130756249732
12.221307561731342
12.221307560965531
12.221307560199895
12.221307559434418
12.221307558669103
12.221307557903957
12.221307557138983
12.221307556374171
12.221307555609526
12.22130755484505
12.221307554080731
12.221307553316585
12.221307552552608
12.221307551788787
12.221307551025133
12.221307550261649
12.221307549498334
12.22130754873518
12.221307547972186
12.221307547209364
12.221307546446708
12.221307545684216
12.22130754492189
12.221307544159735
12.22130754339774
12.221307542635913
12.221307541874248
12.221307541112742
12.221307540351415
12.221307539590244
12.221307538829244
12.221307538068402
12.221307537307737
12.221307536547222
12.221307535786892
12.221307535026705
12.221307534266696
12.221307533506847
12.221307532747167
12.221307531987641
12.221307531228291
12.221307530469105
12.221307529710078
12.22130752895122
12.221307528192522
12.221307527433996
12.221307526675636
12.221307525917437
12.221307525159395
12.221307524401526
12.221307523643818
12.221307522886281
12.22130752212891
12.221307521371692
12.221307520614644
12.22130751985776
12.221307519101035
12.22130751834448
12.221307517588096
12.221307516831866
12.221307516075797
12.221307515319902
12.221307514564167
12.221307513808592
12.221307513053187
12.221307512297944
12.22130751154287
12.221307510787947
12.2213075100332
12.22130750927861
12.22130750852419
12.221307507769929
12.221307507015835
12.221307506261894
12.221307505508126
12.221307504754526
12.22130750400108
12.221307503247798
12.221307502494692
12.221307501741727
12.221307500988946
12.221307500236316
12.221307499483862
12.221307498731562
12.221307497979428
12.221307497227446
12.221307496475655
12.221307495724004
12.221307494972525
12.2213074942212
12.221307493470048
12.221307492719061
12.22130749196823
12.221307491217559
12.221307490467053
12.221307489716722
12.22130748896654
12.221307488216523
12.221307487466676
12.221307486716976
12.221307485967458
12.221307485218095
12.221307484468888
12.221307483719846
12.221307482970973
12.221307482222258
12.221307481473707
12.221307480725315
12.221307479977096
12.221307479229024
12.221307478481128
12.221307477733387
12.221307476985809
12.221307476238398
12.221307475491145
12.221307474744053
12.221307473997127
12.221307473250356
12.221307472503755
12.221307471757314
12.221307471011025
12.22130747026491
12.221307469518962
12.221307468773158
12.221307468027534
12.221307467282056
12.221307466536757
12.221307465791604
12.22130746504662
12.221307464301798
12.221307463557133
12.22130746281263
12.221307462068294
12.22130746132412
12.221307460580102
12.221307459836249
12.221307459092554
12.221307458349026
12.221307457605663
12.221307456862446
12.221307456119403
12.221307455376518
12.22130745463379
12.221307453891226
12.221307453148825
12.22130745240659
12.221307451664504
12.221307450922584
12.221307450180834
12.221307449439228
12.221307448697795
12.221307447956518
12.22130744721541
12.221307446474453
12.221307445733665
12.221307444993027
12.22130744425256
12.221307443512258
12.2213074427721
12.221307442032108
12.221307441292286
12.221307440552616
12.221307439813108
12.221307439073756
12.221307438334577
12.221307437595547
12.221307436856682
12.221307436117984
12.221307435379437
12.221307434641057
12.221307433902828
12.221307433164762
12.221307432426862
12.221307431689116
12.221307430951533
12.22130743021411
12.221307429476845
12.221307428739745
12.221307428002799
12.221307427266014
12.221307426529396
12.221307425792933
12.221307425056626
12.221307424320486
12.221307423584504
12.221307422848676
12.221307422113016
12.22130742137751
12.221307420642159
12.22130741990698
12.221307419171948
12.221307418437084
12.221307417702379
12.221307416967829
12.221307416233445
12.221307415499211
12.221307414765148
12.221307414031232
12.221307413297485
12.221307412563894
12.22130741183046
12.221307411097191
12.221307410364064
12.221307409631118
12.22130740889832
12.221307408165686
12.221307407433216
12.221307406700891
12.22130740596873
12.221307405236733
12.221307404504888
12.2213074037732
12.221307403041685
12.221307402310321
12.221307401579114
12.221307400848058
12.221307400117174
12.221307399386447
12.221307398655869
12.221307397925452
12.2213073971952
12.221307396465107
12.221307395735163
12.221307395005383
12.221307394275762
12.221307393546308
12.221307392817003
12.221307392087853
12.221307391358863
12.22130739063004
12.221307389901364
12.221307389172857
12.221307388444501
12.221307387716307
12.221307386988261
12.221307386260378
12.221307385532656
12.22130738480509
12.221307384077683
12.221307383350434
12.22130738262335
12.221307381896407
12.221307381169634
12.221307380443015
12.221307379716562
12.221307378990257
12.221307378264108
12.22130737753812
12.221307376812298
12.221307376086612
12.221307375361109
12.221307374635746
12.221307373910545
12.221307373185507
12.22130737246062
12.22130737173589
12.22130737101132
12.221307370286908
12.221307369562652
12.22130736883855
12.221307368114608
12.221307367390828
12.2213073666672
12.221307365943723
12.221307365220412
12.221307364497257
12.221307363774265
12.221307363051418
12.221307362328732
12.221307361606206
12.221307360883829
12.221307360161614
12.221307359439564
12.221307358717656
12.221307357995906
12.221307357274325
12.22130735655289
12.221307355831618
12.221307355110499
12.221307354389534
12.221307353668728
12.221307352948077
12.221307352227592
12.221307351507248
12.221307350787068
12.22130735006705
12.221307349347185
12.221307348627471
12.221307347907917
12.22130734718851
12.221307346469272
12.221307345750187
12.221307345031256
12.221307344312484
12.22130734359386
12.2213073428754
12.22130734215709
12.22130734143894
12.221307340720948
12.22130734000311
12.221307339285437
12.2213073385679
12.221307337850538
12.221307337133313
12.221307336416258
12.22130733569935
12.221307334982603
12.221307334266008
12.221307333549579
12.22130733283329
12.221307332117169
12.221307331401192
12.221307330685375
12.221307329969717
12.221307329254207
12.221307328538861
12.221307327823668
12.22130732710862
12.22130732639374
12.221307325679014
12.221307324964437
12.22130732425002
12.221307323535763
12.221307322821646
12.221307322107696
12.221307321393894
12.22130732068025
12.221307319966764
12.22130731925343
12.221307318540243
12.221307317827227
12.221307317114356
12.221307316401637
12.22130731568908
12.22130731497668
12.221307314264427
12.221307313552325
12.221307312840382
12.221307312128598
12.221307311416965
12.221307310705487
12.22130730999416
12.22130730928299
12.221307308571976
12.221307307861105
12.221307307150411
12.221307306439856
12.221307305729463
12.221307305019215
12.221307304309123
12.221307303599191
12.221307302889405
12.22130730217978
12.221307301470304
12.221307300760992
12.221307300051825
12.22130729934281
12.221307298633949
12.221307297925248
12.221307297216702
12.221307296508298
12.221307295800054
12.221307295091963
12.221307294384044
12.221307293676256
12.221307292968625
12.221307292261157
12.221307291553826
12.221307290846665
12.221307290139649
12.221307289432785
12.221307288726083
12.221307288019531
12.221307287313131
12.221307286606882
12.221307285900789
12.221307285194852
12.221307284489065
12.221307283783432
12.22130728307795
12.221307282372626
12.22130728166744
12.221307280962423
12.221307280257559
12.221307279552843
12.22130727884828
12.221307278143868
12.221307277439623
12.221307276735509

12.221307276031562
12.221307275327757
12.221307274624118
12.221307273920623
12.221307273217288
12.22130727251409
12.221307271811066
12.22130727110818
12.22130727040545
12.221307269702876
12.221307269000446
12.22130726829818
12.221307267596053
12.221307266894089
12.221307266192277
12.22130726549061
12.221307264789099
12.22130726408775
12.221307263386532
12.221307262685487
12.221307261984586
12.221307261283837
12.22130726058324
12.221307259882789
12.221307259182499
12.221307258482359
12.22130725778237
12.221307257082534
12.22130725638285
12.221307255683312
12.221307254983929
12.221307254284708
12.221307253585625
12.221307252886705
12.221307252187925
12.221307251489305
12.221307250790824
12.221307250092512
12.221307249394346
12.221307248696332
12.22130724799846
12.221307247300745
12.221307246603185
12.221307245905779
12.221307245208514
12.221307244511404
12.221307243814454
12.221307243117655
12.221307242420993
12.221307241724489
12.22130724102814
12.22130724033194
12.221307239635887
12.22130723893999
12.221307238244252
12.22130723754864
12.221307236853201
12.221307236157902
12.221307235462756
12.221307234767767
12.221307234072935
12.221307233378234
12.2213072326837
12.221307231989314
12.221307231295073
12.22130723060098
12.221307229907039
12.221307229213256
12.22130722851962
12.22130722782613
12.221307227132801
12.221307226439619
12.221307225746575
12.221307225053701
12.221307224360965
12.22130722366838
12.22130722297595
12.221307222283658
12.221307221591536
12.22130722089955
12.221307220207718
12.221307219516042
12.221307218824505
12.221307218133116
12.221307217441892
12.221307216750812
12.221307216059882
12.221307215369102
12.221307214678463
12.221307213987986
12.221307213297655
12.221307212607474
12.221307211917443
12.221307211227558
12.221307210537828
12.221307209848236
12.221307209158805
12.221307208469522
12.221307207780386
12.221307207091408
12.221307206402573
12.221307205713885
12.221307205025349
12.221307204336961
12.22130720364873
12.221307202960642
12.221307202272707
12.221307201584914
12.221307200897279
12.221307200209782
12.22130719952245
12.221307198835255
12.221307198148212
12.221307197461316
12.221307196774575
12.221307196087968
12.221307195401529
12.221307194715239
12.221307194029086
12.221307193343085
12.221307192657237
12.221307191971531
12.221307191285979
12.22130719060057
12.221307189915324
12.221307189230215
12.221307188545252
12.221307187860447
12.221307187175785
12.221307186491272
12.221307185806904
12.221307185122695
12.221307184438627
12.221307183754707
12.221307183070934
12.221307182387319
12.221307181703846
12.221307181020528
12.221307180337343
12.22130717965432
12.221307178971445
12.22130717828871
12.221307177606123
12.221307176923686
12.221307176241401
12.221307175559259
12.221307174877268
12.221307174195431
12.22130717351374
12.221307172832185
12.221307172150787
12.221307171469537
12.221307170788432
12.221307170107478
12.221307169426675
12.221307168746005
12.2213071680655
12.22130716738514
12.221307166704923
12.221307166024848
12.221307165344932
12.22130716466516
12.22130716398553
12.22130716330606
12.221307162626717
12.221307161947536
12.221307161268506
12.221307160589612
12.221307159910868
12.22130715923228
12.221307158553827
12.221307157875534
12.221307157197376
12.221307156519378
12.221307155841512
12.221307155163803
12.22130715448624
12.221307153808814
12.22130715313156
12.22130715245443
12.221307151777456
12.221307151100618
12.221307150423947
12.221307149747407
12.22130714907102
12.221307148394772
12.221307147718681
12.221307147042735
12.221307146366938
12.221307145691277
12.221307145015764
12.22130714434041
12.221307143665195
12.221307142990126
12.221307142315208
12.221307141640432
12.221307140965804
12.221307140291314
12.221307139616982
12.221307138942795
12.22130713826875
12.221307137594845
12.2213071369211
12.221307136247495
12.221307135574035
12.221307134900728
12.221307134227558
12.22130713355454
12.22130713288167
12.221307132208938
12.22130713153636
12.22130713086392
12.221307130191633
12.221307129519486
12.221307128847487
12.221307128175642
12.22130712750394
12.221307126832372
12.221307126160962
12.221307125489693
12.221307124818567
12.22130712414758
12.221307123476757
12.221307122806067
12.221307122135528
12.22130712146514
12.221307120794883
12.22130712012478
12.221307119454828
12.221307118785006
12.221307118115336
12.221307117445814
12.221307116776442
12.221307116107212
12.221307115438119
12.221307114769182
12.22130711410038
12.22130711343173
12.221307112763233
12.221307112094864
12.221307111426656
12.221307110758577
12.221307110090654
12.221307109422872
12.221307108755235
12.221307108087741
12.221307107420394
12.221307106753189
12.22130710608614
12.221307105419234
12.221307104752459
12.221307104085843
12.221307103419365
12.221307102753027
12.221307102086838
12.2213071014208
12.221307100754904
12.221307100089145
12.221307099423532
12.221307098758073
12.221307098092746
12.221307097427571
12.221307096762535
12.221307096097645
12.22130709543291
12.221307094768305
12.22130709410385
12.22130709343954
12.221307092775373
12.221307092111351
12.221307091447475
12.221307090783736
12.221307090120147
12.2213070894567
12.221307088793393
12.221307088130244
12.221307087467224
12.221307086804359
12.22130708614163
12.221307085479042
12.221307084816607
12.221307084154313
12.221307083492157
12.221307082830155
12.22130708216829
12.22130708150657
12.221307080844985
12.221307080183559
12.221307079522278
12.221307078861127
12.22130707820012
12.22130707753926
12.221307076878546
12.221307076217972
12.221307075557538
12.221307074897263
12.221307074237117
12.221307073577124
12.221307072917263
12.221307072257545
12.221307071597977
12.221307070938558
12.221307070279273
12.221307069620126
12.221307068961137
12.221307068302282
12.221307067643561
12.221307066985002
12.221307066326576
12.221307065668292
12.221307065010155
12.221307064352155
12.221307063694306
12.221307063036589
12.221307062379028
12.221307061721603
12.22130706106432
12.22130706040718
12.221307059750185
12.221307059093329
12.221307058436619
12.221307057780043
12.221307057123626
12.221307056467337
12.221307055811195
12.221307055155203
12.221307054499338
12.221307053843619
12.221307053188045
12.221307052532621
12.221307051877327
12.221307051222183
12.221307050567178
12.22130704991232
12.221307049257597
12.221307048603027
12.221307047948589
12.221307047294292
12.221307046640145
12.22130704598613
12.221307045332269
12.221307044678547
12.221307044024956
12.221307043371523
12.221307042718218
12.22130704206506
12.221307041412041
12.221307040759163
12.221307040106435
12.221307039453844
12.221307038801395
12.22130703814909
12.22130703749692
12.221307036844896
12.221307036193018
12.22130703554128
12.221307034889675
12.221307034238217
12.221307033586902
12.221307032935721
12.221307032284685
12.221307031633799
12.221307030983047
12.22130703033243
12.221307029681965
12.221307029031625
12.221307028381442
12.221307027731397
12.221307027081494
12.22130702643173
12.221307025782107
12.221307025132628
12.221307024483286
12.221307023834083
12.221307023185025
12.221307022536104
12.221307021887329
12.221307021238694
12.221307020590197
12.221307019941843
12.221307019293633
12.22130701864556
12.221307017997622
12.221307017349828
12.221307016702179
12.221307016054666
12.221307015407296
12.221307014760066
12.22130701411298
12.221307013466024
12.221307012819219
12.221307012172549
12.221307011526031
12.22130701087963
12.221307010233387
12.221307009587276
12.221307008941313
12.221307008295486
12.221307007649802
12.221307007004262
12.221307006358845
12.221307005713582
12.221307005068454
12.221307004423473
12.221307003778625
12.22130700313392
12.22130700248935
12.221307001844924
12.221307001200636
12.221307000556493
12.221306999912487
12.221306999268617
12.221306998624891
12.2213069979813
12.221306997337855
12.221306996694551
12.221306996051378
12.221306995408352
12.221306994765461
12.221306994122715
12.221306993480107
12.22130699283763
12.221306992195299
12.221306991553115
12.221306990911055
12.221306990269143
12.221306989627372
12.221306988985734
12.22130698834424
12.221306987702885
12.221306987061666
12.221306986420585
12.221306985779647
12.221306985138845
12.22130698449819
12.221306983857668
12.221306983217291
12.221306982577044
12.221306981936944
12.221306981296973
12.22130698065715
12.22130698001746
12.221306979377905
12.2213069787385
12.221306978099225
12.2213069774601
12.221306976821104
12.221306976182246
12.221306975543527
12.221306974904955
12.221306974266513
12.221306973628215
12.221306972990051
12.221306972352027
12.221306971714142
12.221306971076391
12.2213069704388
12.221306969801326
12.221306969163988
12.221306968526793
12.22130696788974
12.22130696725282
12.221306966616048
12.221306965979409
12.2213069653429
12.22130696470654
12.221306964070314
12.221306963434225
12.221306962798275
12.221306962162467
12.221306961526789
12.221306960891262
12.221306960255863
12.221306959620595
12.22130695898548
12.221306958350489
12.221306957715647
12.221306957080937
12.221306956446373
12.221306955811936
12.221306955177639
12.221306954543486
12.221306953909464
12.221306953275588
12.221306952641841
12.221306952008224
12.221306951374755
12.221306950741434
12.221306950108236
12.221306949475181

12.221306948842258
12.22130694820948
12.221306947576835
12.221306946944328
12.221306946311955
12.221306945679725
12.22130694504762
12.221306944415675
12.221306943783848
12.221306943152156
12.221306942520616
12.221306941889203
12.22130694125793
12.2213069406268
12.221306939995795
12.221306939364935
12.221306938734203
12.221306938103627
12.221306937473166
12.221306936842852
12.221306936212672
12.221306935582632
12.221306934952732
12.22130693432296
12.22130693369333
12.22130693306384
12.221306932434482
12.221306931805257
12.221306931176176
12.221306930547227
12.22130692991842
12.22130692928974
12.221306928661203
12.2213069280328
12.221306927404534
12.221306926776403
12.221306926148412
12.221306925520556
12.221306924892833
12.221306924265248
12.2213069236378
12.221306923010495
12.221306922383313
12.221306921756279
12.221306921129377
12.221306920502606
12.221306919875975
12.221306919249479
12.221306918623128
12.221306917996893
12.22130691737081
12.221306916744862
12.22130691611904
12.221306915493367
12.221306914867817
12.221306914242406
12.22130691361714
12.221306912992006
12.221306912367002
12.221306911742136
12.221306911117404
12.221306910492821
12.221306909868355
12.221306909244031
12.221306908619844
12.221306907995785
12.221306907371874
12.221306906748088
12.221306906124452
12.221306905500942
12.221306904877563
12.221306904254321
12.221306903631207
12.22130690300825
12.221306902385416
12.221306901762718
12.221306901140151
12.221306900517732
12.221306899895442
12.221306899273266
12.221306898651251
12.221306898029358
12.221306897407603
12.221306896785983
12.221306896164501
12.22130689554315
12.221306894921947
12.221306894300858
12.22130689367992
12.221306893059106
12.221306892438436
12.221306891817896
12.221306891197496
12.22130689057722
12.22130688995708
12.22130688933708
12.221306888717214
12.221306888097478
12.221306887477889
12.221306886858422
12.221306886239093
12.221306885619898
12.221306885000837
12.221306884381915
12.221306883763123
12.221306883144461
12.22130688252594
12.221306881907553
12.2213068812893
12.221306880671175
12.221306880053193
12.221306879435337
12.221306878817618
12.221306878200043
12.221306877582595
12.22130687696527
12.221306876348091
12.221306875731049
12.221306875114134
12.221306874497358
12.22130687388071
12.221306873264197
12.221306872647823
12.221306872031564
12.221306871415464
12.22130687079948
12.221306870183641
12.221306869567922
12.22130686895236
12.221306868336907
12.221306867721605
12.221306867106437
12.221306866491386
12.221306865876482
12.221306865261704
12.221306864647065
12.221306864032556
12.221306863418176
12.221306862803942
12.22130686218983
12.221306861575858
12.221306860962022
12.221306860348307
12.221306859734735
12.221306859121293
12.221306858507981
12.221306857894808
12.221306857281764
12.221306856668857
12.221306856056081
12.221306855443443
12.221306854830924
12.22130685421855
12.221306853606304
12.221306852994196
12.221306852382217
12.221306851770377
12.221306851158658
12.221306850547075
12.221306849935628
12.22130684932431
12.22130684871313
12.221306848102083
12.22130684749117
12.221306846880386
12.221306846269735
12.22130684565921
12.221306845048822
12.22130684443857
12.221306843828453
12.221306843218459
12.2213068426086
12.221306841998883
12.221306841389291
12.221306840779823
12.221306840170497
12.221306839561302
12.221306838952245
12.221306838343313
12.221306837734513
12.221306837125846
12.221306836517316
12.221306835908909
12.221306835300641
12.221306834692502
12.221306834084489
12.221306833476618
12.221306832868876
12.221306832261261
12.22130683165379
12.221306831046443
12.221306830439227
12.221306829832141
12.221306829225188
12.221306828618378
12.221306828011684
12.22130682740512
12.221306826798706
12.221306826192412
12.221306825586252
12.221306824980221
12.221306824374318
12.221306823768552
12.221306823162921
12.221306822557416
12.221306821952043
12.221306821346804
12.221306820741697
12.221306820136713
12.221306819531865
12.221306818927156
12.221306818322569
12.221306817718121
12.221306817113799
12.221306816509596
12.221306815905542
12.221306815301615
12.221306814697817
12.221306814094156
12.221306813490614
12.221306812887208
12.22130681228394
12.221306811680796
12.22130681107778
12.2213068104749
12.221306809872155
12.221306809269533
12.221306808667041
12.221306808064696
12.221306807462467
12.221306806860364
12.221306806258395
12.221306805656564
12.221306805054857
12.221306804453286
12.221306803851846
12.221306803250528
12.221306802649355
12.2213068020483
12.221306801447374
12.221306800846587
12.221306800245923
12.2213067996454
12.221306799044996
12.221306798444726
12.221306797844592
12.22130679724458
12.221306796644697
12.221306796044946
12.221306795445335
12.221306794845853
12.22130679424649
12.221306793647265
12.221306793048164
12.221306792449194
12.221306791850363
12.221306791251655
12.221306790653077
12.221306790054635
12.221306789456309
12.22130678885813
12.221306788260062
12.221306787662135
12.22130678706434
12.22130678646667
12.221306785869134
12.221306785271722
12.221306784674443
12.221306784077292
12.221306783480271
12.221306782883378
12.221306782286614
12.22130678168999
12.221306781093487
12.221306780497112
12.221306779900866
12.22130677930475
12.221306778708776
12.221306778112911
12.221306777517194
12.221306776921594
12.221306776326124
12.221306775730788
12.221306775135576
12.221306774540503
12.221306773945546
12.221306773350724
12.221306772756032
12.221306772161473
12.221306771567042
12.221306770972738
12.221306770378565
12.221306769784512
12.221306769190585
12.221306768596808
12.221306768003148
12.221306767409617
12.22130676681621
12.221306766222936
12.221306765629784
12.221306765036775
12.221306764443886
12.221306763851123
12.221306763258493
12.221306762665995
12.22130676207363
12.221306761481376
12.221306760889266
12.22130676029727
12.221306759705415
12.221306759113688
12.221306758522088
12.221306757930616
12.221306757339265
12.221306756748055
12.221306756156965
12.221306755566001
12.221306754975167
12.221306754384464
12.221306753793884
12.221306753203443
12.22130675261312
12.221306752022931
12.22130675143287
12.221306750842936
12.22130675025313
12.221306749663439
12.221306749073893
12.221306748484473
12.221306747895175
12.221306747306013
12.221306746716973
12.22130674612806
12.221306745539277
12.221306744950624
12.221306744362094
12.221306743773695
12.221306743185425
12.221306742597273
12.221306742009261
12.221306741421364
12.221306740833603
12.221306740245971
12.221306739658461
12.22130673907108
12.221306738483834
12.2213067378967
12.221306737309712
12.221306736722847
12.221306736136093
12.221306735549483
12.221306734963001
12.22130673437664
12.221306733790403
12.221306733204296
12.221306732618322
12.221306732032478
12.221306731446749
12.221306730861146
12.221306730275678
12.221306729690337
12.221306729105121
12.221306728520027
12.22130672793507
12.22130672735024
12.221306726765528
12.22130672618095
12.221306725596497
12.22130672501217
12.221306724427965
12.221306723843893
12.221306723259943
12.22130672267613
12.221306722092432
12.22130672150886
12.221306720925417
12.22130672034211
12.221306719758925
12.22130671917586
12.221306718592931
12.221306718010121
12.221306717427447
12.221306716844897
12.22130671626246
12.221306715680162
12.221306715097983
12.221306714515936
12.221306713934014
12.221306713352218
12.221306712770554
12.221306712189005
12.221306711607587
12.221306711026296
12.221306710445123
12.221306709864093
12.221306709283182
12.221306708702397
12.22130670812173
12.221306707541203
12.221306706960792
12.221306706380515
12.221306705800352
12.221306705220323
12.22130670464042
12.221306704060641
12.221306703480982
12.221306702901465
12.22130670232206
12.221306701742785
12.22130670116364
12.221306700584606
12.221306700005716
12.221306699426938
12.221306698848291
12.221306698269776
12.221306697691377
12.221306697113096
12.221306696534954
12.221306695956937
12.221306695379047
12.221306694801267
12.221306694223637
12.221306693646113
12.221306693068717
12.221306692491458
12.221306691914323
12.221306691337299
12.221306690760406
12.221306690183638
12.221306689606996
12.221306689030488
12.221306688454089
12.221306687877826
12.221306687301682
12.221306686725667
12.221306686149777
12.221306685574012
12.221306684998382
12.221306684422856
12.22130668384747
12.22130668327221
12.221306682697064
12.221306682122048
12.221306681547162
12.22130668097239
12.221306680397747
12.221306679823229
12.221306679248835
12.221306678674571
12.221306678100428
12.221306677526423
12.22130667695252
12.221306676378745
12.221306675805106
12.221306675231583
12.221306674658193
12.221306674084923
12.221306673511771
12.22130667293875
12.221306672365852
12.221306671793073

12.22130667122043
12.221306670647897
12.2213066700755
12.221306669503226
12.22130666893107
12.221306668359045
12.221306667787141
12.221306667215359
12.221306666643706
12.22130666607217
12.221306665500762
12.22130666492948
12.221306664358327
12.221306663787285
12.221306663216374
12.221306662645587
12.221306662074918
12.221306661504382
12.221306660933962
12.221306660363682
12.221306659793512
12.221306659223462
12.22130665865354
12.22130665808374
12.221306657514074
12.221306656944522
12.221306656375091
12.22130665580579
12.221306655236615
12.221306654667556
12.22130665409862
12.221306653529808
12.22130665296113
12.221306652392565
12.221306651824127
12.221306651255814
12.221306650687618
12.221306650119551
12.221306649551611
12.221306648983791
12.221306648416094
12.22130664784851
12.221306647281056
12.221306646713728
12.221306646146534
12.22130664557944
12.221306645012486
12.221306644445647
12.221306643878933
12.22130664331234
12.221306642745873
12.221306642179531
12.221306641613312
12.221306641047208
12.22130664048124
12.221306639915378
12.221306639349658
12.221306638784041
12.221306638218563
12.221306637653194
12.221306637087956
12.221306636522849
12.221306635957843
12.221306635392976
12.221306634828228
12.22130663426361
12.2213066336991
12.221306633134715
12.22130663257045
12.221306632006321
12.221306631442312
12.22130663087842
12.221306630314652
12.221306629751004
12.221306629187474
12.221306628624074
12.221306628060798
12.221306627497638
12.221306626934602
12.22130662637169
12.2213066258089
12.221306625246228
12.221306624683692
12.221306624121262
12.221306623558965
12.221306622996783
12.221306622434719
12.221306621872786
12.221306621310971
12.221306620749276
12.221306620187715
12.221306619626262
12.221306619064931
12.221306618503727
12.221306617942648
12.22130661738169
12.22130661682084
12.221306616260136
12.221306615699532
12.221306615139056
12.221306614578705
12.221306614018468
12.221306613458362
12.22130661289838
12.221306612338507
12.221306611778765
12.221306611219145
12.221306610659637
12.221306610100251
12.221306609540997
12.221306608981864
12.221306608422847
12.221306607863955
12.221306607305184
12.221306606746525
12.22130660618799
12.221306605629591
12.221306605071305
12.221306604513126
12.221306603955082
12.221306603397158
12.22130660283935
12.22130660228167
12.221306601724107
12.221306601166667
12.221306600609347
12.22130660005215
12.221306599495069
12.22130659893811
12.22130659838128
12.221306597824551
12.221306597267965
12.221306596711493
12.221306596155145
12.221306595598904
12.221306595042796
12.221306594486805
12.221306593930933
12.221306593375179
12.221306592819554
12.221306592264051
12.221306591708663
12.2213065911534
12.221306590598251
12.221306590043215
12.22130658948832
12.221306588933528
12.221306588378868
12.22130658782432
12.2213065872699
12.221306586715594
12.221306586161413
12.221306585607346
12.221306585053407
12.221306584499581
12.221306583945884
12.221306583392296
12.221306582838842
12.221306582285498
12.221306581732266
12.221306581179165
12.221306580626186
12.221306580073326
12.221306579520583
12.22130657896796
12.221306578415463
12.22130657786308
12.22130657731081
12.221306576758677
12.221306576206654
12.22130657565475
12.221306575102972
12.221306574551308
12.221306573999765
12.221306573448341
12.221306572897037
12.221306572345846
12.221306571794788
12.221306571243845
12.221306570693017
12.221306570142314
12.221306569591727
12.221306569041257
12.221306568490911
12.221306567940685
12.221306567390577
12.22130656684059
12.221306566290721
12.221306565740967
12.221306565191338
12.221306564641823
12.22130656409243
12.221306563543159
12.221306562994007
12.221306562444973
12.221306561896055
12.22130656134726
12.221306560798585
12.221306560250026
12.221306559701581
12.221306559153264
12.221306558605054
12.22130655805698
12.22130655750902
12.22130655696117
12.221306556413449
12.221306555865842
12.221306555318359
12.221306554770996
12.221306554223737
12.22130655367661
12.221306553129589
12.221306552582696
12.221306552035928
12.221306551489265
12.221306550942735
12.221306550396307
12.221306549850006
12.221306549303828
12.221306548757763
12.221306548211816
12.221306547666002
12.221306547120282
12.221306546574695
12.221306546029226
12.221306545483875
12.221306544938638
12.221306544393522
12.22130654384853
12.221306543303653
12.22130654275889
12.221306542214245
12.221306541669717
12.221306541125317
12.22130654058103
12.221306540036851
12.221306539492808
12.221306538948866
12.221306538405054
12.221306537861356
12.221306537317776
12.221306536774321
12.221306536230971
12.221306535687747
12.221306535144642
12.221306534601645
12.221306534058783
12.221306533516023
12.221306532973388
12.221306532430868
12.221306531888464
12.221306531346183
12.221306530804025
12.22130653026197
12.221306529720044
12.221306529178223
12.221306528636534
12.221306528094956
12.2213065275535
12.221306527012153
12.221306526470926
12.221306525929819
12.22130652538883
12.22130652484796
12.22130652430721
12.221306523766565
12.221306523226039
12.22130652268564
12.22130652214536
12.221306521605188
12.221306521065143
12.221306520525202
12.221306519985383
12.221306519445687
12.221306518906108
12.221306518366635
12.221306517827294
12.221306517288058
12.22130651674894
12.221306516209946
12.221306515671065
12.221306515132298
12.221306514593657
12.221306514055128
12.221306513516712
12.221306512978417
12.221306512440238
12.221306511902172
12.221306511364228
12.2213065108264
12.221306510288686
12.221306509751095
12.221306509213612
12.221306508676259
12.221306508139008
12.22130650760188
12.221306507064877
12.221306506527979
12.221306505991194
12.221306505454528
12.221306504917987
12.22130650438156
12.221306503845252
12.221306503309046
12.221306502772965
12.22130650223701
12.22130650170116
12.221306501165428
12.221306500629815
12.221306500094318
12.221306499558935
12.221306499023664
12.221306498488508
12.221306497953483
12.221306497418563
12.221306496883756
12.221306496349081
12.221306495814513
12.22130649528005
12.221306494745713
12.221306494211495
12.221306493677387
12.221306493143395
12.22130649260952
12.221306492075772
12.221306491542126
12.221306491008598
12.22130649047519
12.221306489941897
12.22130648940872
12.221306488875657
12.221306488342702
12.221306487809878
12.221306487277158
12.22130648674456
12.221306486212075
12.221306485679708
12.221306485147453
12.221306484615312
12.221306484083287
12.221306483551382
12.221306483019587
12.221306482487917
12.221306481956352
12.221306481424913
12.221306480893572
12.22130648036236
12.221306479831263
12.221306479300278
12.221306478769405
12.221306478238652
12.221306477708023
12.221306477177489
12.221306476647083
12.221306476116789
12.221306475586609
12.221306475056545
12.221306474526607
12.22130647399677
12.221306473467049
12.221306472937442
12.221306472407957
12.221306471878588
12.221306471349328
12.22130647082019
12.221306470291154
12.221306469762247
12.221306469233443
12.221306468704764
12.221306468176188
12.22130646764773
12.22130646711939
12.221306466591164
12.221306466063066
12.221306465535068
12.221306465007187
12.221306464479417
12.221306463951768
12.221306463424229
12.22130646289681
12.221306462369496
12.221306461842302
12.221306461315214
12.221306460788254
12.221306460261403
12.221306459734665
12.221306459208044
12.221306458681532
12.221306458155146
12.221306457628858
12.221306457102692
12.221306456576645
12.22130645605071
12.22130645552489
12.221306454999176
12.22130645447358
12.221306453948104
12.221306453422736
12.221306452897492
12.221306452372344
12.221306451847324
12.221306451322414
12.221306450797615
12.221306450272934
12.221306449748367
12.221306449223905
12.221306448699568
12.221306448175339
12.22130644765123
12.221306447127226
12.221306446603345
12.221306446079566
12.221306445555907
12.221306445032361
12.221306444508933
12.221306443985618
12.221306443462417
12.221306442939323
12.221306442416346
12.221306441893478
12.221306441370734
12.221306440848096
12.22130644032557
12.221306439803161
12.221306439280864
12.221306438758676
12.221306438236612
12.221306437714652
12.221306437192816
12.22130643667108
12.22130643614947
12.221306435627964
12.221306435106575
12.221306434585294
12.221306434064141
12.221306433543083
12.221306433022137
12.221306432501315
12.221306431980617
12.221306431460016
12.221306430939524
12.221306430419153
12.221306429898894
12.221306429378748
12.221306428858714
12.221306428338792
12.221306427818979
12.221306427299288
12.221306426779703
12.221306426260245
12.221306425740876
12.22130642522164
12.221306424702501
12.221306424183487
12.221306423664583
12.221306423145789
12.221306422627102
12.221306422108539
12.221306421590079
12.22130642107174
12.22130642055351
12.221306420035388
12.22130641951738
12.22130641899949
12.221306418481708
12.221306417964046
12.221306417446486
12.221306416929036
12.221306416411707
12.221306415894494
12.22130641537738
12.221306414860388
12.221306414343509
12.221306413826735
12.22130641331008
12.221306412793528
12.221306412277094

12.221306411760782
12.221306411244568
12.221306410728475
12.221306410212485
12.221306409696604
12.221306409180846
12.221306408665201
12.221306408149662
12.221306407634234
12.221306407118915
12.221306406603722
12.221306406088623
12.221306405573644
12.221306405058785
12.221306404544023
12.221306404029386
12.22130640351485
12.221306403000431
12.221306402486121
12.221306401971923
12.22130640145784
12.22130640094387
12.22130640043
12.221306399916257
12.221306399402613
12.221306398889089
12.221306398375672
12.221306397862362
12.22130639734918
12.221306396836097
12.221306396323122
12.221306395810261
12.221306395297509
12.221306394784884
12.221306394272359
12.22130639375994
12.221306393247637
12.221306392735444
12.221306392223363
12.221306391711396
12.221306391199537
12.221306390687795
12.22130639017615
12.221306389664626
12.221306389153215
12.221306388641915
12.221306388130731
12.221306387619638
12.221306387108669
12.221306386597812
12.221306386087065
12.221306385576428
12.221306385065908
12.22130638455549
12.221306384045183
12.221306383534982
12.221306383024901
12.221306382514939
12.221306382005068
12.221306381495316
12.22130638098568
12.221306380476143
12.221306379966725
12.22130637945742
12.221306378948215
12.221306378439126
12.22130637793015
12.221306377421282
12.221306376912528
12.221306376403883
12.221306375895349
12.221306375386918
12.221306374878607
12.221306374370396
12.22130637386231
12.221306373354324
12.22130637284645
12.221306372338699
12.22130637183103
12.221306371323484
12.221306370816063
12.221306370308735
12.221306369801525
12.221306369294416
12.221306368787427
12.221306368280542
12.221306367773773
12.221306367267113
12.221306366760558
12.221306366254113
12.22130636574778
12.221306365241558
12.221306364735447
12.221306364229443
12.221306363723551
12.22130636321777
12.221306362712099
12.221306362206526
12.22130636170107
12.221306361195733
12.2213063606905
12.221306360185372
12.221306359680352
12.221306359175454
12.221306358670656
12.221306358165965
12.221306357661403
12.221306357156925
12.221306356652557
12.221306356148308
12.221306355644177
12.221306355140152
12.221306354636225
12.221306354132413
12.221306353628712
12.221306353125124
12.22130635262163
12.221306352118262
12.221306351615002
12.221306351111844
12.221306350608796
12.221306350105861
12.221306349603028
12.221306349100317
12.221306348597698
12.22130634809521
12.221306347592808
12.221306347090533
12.221306346588362
12.221306346086292
12.221306345584342
12.221306345082498
12.221306344580757
12.221306344079128
12.221306343577613
12.221306343076202
12.221306342574898
12.221306342073708
12.22130634157262
12.221306341071644
12.221306340570777
12.22130634007002
12.221306339569365
12.221306339068823
12.22130633856839
12.221306338068077
12.221306337567855
12.22130633706775
12.221306336567752
12.221306336067865
12.221306335568084
12.221306335068418
12.221306334568848
12.221306334069393
12.221306333570046
12.221306333070805
12.221306332571674
12.221306332072654
12.221306331573734
12.22130633107494
12.221306330576246
12.22130633007765
12.221306329579168
12.221306329080797
12.22130632858253
12.221306328084372
12.22130632758633
12.221306327088389
12.22130632659055
12.221306326092833
12.221306325595213
12.22130632509771
12.221306324600311
12.221306324103024
12.221306323605836
12.221306323108758
12.22130632261179
12.221306322114932
12.221306321618181
12.221306321121533
12.221306320625
12.221306320128571
12.221306319632248
12.221306319136028
12.221306318639929
12.22130631814392
12.221306317648038
12.221306317152253
12.22130631665658
12.221306316161009
12.221306315665558
12.221306315170205
12.221306314674957
12.221306314179818
12.221306313684787
12.221306313189867
12.221306312695058
12.22130631220034
12.221306311705735
12.221306311211247
12.22130631071686
12.221306310222586
12.221306309728412
12.22130630923435
12.22130630874039
12.221306308246543
12.2213063077528
12.221306307259171
12.221306306765634
12.221306306272218
12.221306305778901
12.2213063052857
12.2213063047926
12.221306304299604
12.221306303806719
12.221306303313941
12.221306302821272
12.221306302328712
12.221306301836247
12.221306301343892
12.22130630085165
12.221306300359517
12.221306299867484
12.221306299375557
12.221306298883745
12.221306298392033
12.221306297900428
12.22130629740894
12.221306296917547
12.221306296426262
12.221306295935095
12.22130629544401
12.221306294953049
12.221306294462197
12.221306293971443
12.221306293480803
12.22130629299026
12.221306292499834
12.221306292009508
12.22130629151929
12.221306291029181
12.221306290539175
12.221306290049277
12.221306289559482
12.221306289069787
12.221306288580214
12.221306288090737
12.22130628760138
12.22130628711211
12.22130628662296
12.221306286133915
12.221306285644971
12.22130628515613
12.2213062846674
12.221306284178773
12.221306283690263
12.221306283201846
12.221306282713533
12.22130628222534
12.221306281737245
12.221306281249252
12.221306280761375
12.221306280273595
12.221306279785919
12.221306279298366
12.2213062788109
12.221306278323544
12.221306277836302
12.221306277349157
12.221306276862121
12.221306276375197
12.221306275888374
12.221306275401645
12.221306274915033
12.221306274428526
12.221306273942126
12.221306273455827
12.221306272969636
12.221306272483558
12.22130627199757
12.22130627151169
12.221306271025934
12.22130627054027
12.221306270054708
12.221306269569254
12.221306269083907
12.221306268598664
12.22130626811353
12.221306267628497
12.22130626714358
12.22130626665875
12.221306266174038
12.221306265689426
12.221306265204923
12.221306264720516
12.221306264236224
12.221306263752036
12.221306263267948
12.221306262783967
12.221306262300097
12.221306261816325
12.221306261332664
12.221306260849097
12.221306260365646
12.221306259882295
12.221306259399057
12.221306258915916
12.221306258432879
12.221306257949953
12.221306257467118
12.2213062569844
12.221306256501785
12.221306256019274
12.221306255536865
12.221306255054563
12.221306254572369
12.221306254090273
12.221306253608288
12.221306253126409
12.221306252644625
12.221306252162956
12.221306251681384
12.221306251199909
12.22130625071856
12.221306250237301
12.22130624975615
12.221306249275107
12.221306248794164
12.221306248313322
12.221306247832594
12.221306247351958
12.221306246871434
12.221306246391014
12.221306245910698
12.22130624543049
12.221306244950377
12.221306244470368
12.221306243990472
12.221306243510679
12.22130624303099
12.221306242551398
12.221306242071913
12.221306241592536
12.221306241113258
12.221306240634087
12.221306240155025
12.221306239676059
12.221306239197208
12.221306238718451
12.221306238239796
12.221306237761251
12.221306237282803
12.221306236804466
12.22130623632622
12.2213062358481
12.221306235370065
12.221306234892147
12.221306234414325
12.221306233936604
12.221306233458993
12.221306232981483
12.221306232504075
12.221306232026778
12.221306231549582
12.22130623107249
12.22130623059549
12.221306230118607
12.221306229641822
12.221306229165142
12.22130622868856
12.221306228212079
12.22130622773571
12.22130622725945
12.22130622678328
12.221306226307217
12.22130622583126
12.2213062253554
12.221306224879658
12.22130622440402
12.22130622392846
12.221306223453025
12.221306222977686
12.221306222502456
12.221306222027321
12.221306221552291
12.221306221077363
12.221306220602544
12.221306220127829
12.221306219653211
12.221306219178693
12.221306218704283
12.221306218229973
12.221306217755771
12.221306217281663
12.221306216807674
12.221306216333769
12.221306215859984
12.221306215386297
12.221306214912712
12.221306214439224
12.221306213965844
12.221306213492563
12.221306213019385
12.221306212546308
12.221306212073344
12.221306211600472
12.22130621112771
12.221306210655044
12.221306210182489
12.221306209710033
12.22130620923768
12.221306208765428
12.22130620829327
12.22130620782122
12.221306207349278
12.221306206877438
12.221306206405695
12.22130620593406
12.221306205462515
12.22130620499109
12.221306204519761
12.221306204048533
12.221306203577411
12.22130620310638
12.221306202635459
12.221306202164639
12.221306201693928
12.221306201223303
12.22130620075279
12.221306200282386
12.221306199812071
12.221306199341859
12.221306198871764
12.22130619840175
12.221306197931856
12.221306197462054
12.221306196992366
12.221306196522772
12.221306196053279
12.221306195583887
12.2213061951146
12.221306194645413
12.221306194176323
12.22130619370734
12.221306193238467
12.221306192769678
12.221306192300995
12.22130619183243
12.22130619136395
12.221306190895577
12.221306190427308
12.221306189959135
12.221306189491068
12.221306189023101
12.221306188555241
12.221306188087471
12.221306187619811
12.221306187152253
12.221306186684789
12.221306186217435
12.221306185750178
12.221306185283025
12.221306184815973
12.221306184349016
12.22130618388217
12.221306183415424
12.221306182948773
12.221306182482223
12.221306182015786
12.221306181549435
12.221306181083188
12.221306180617049
12.221306180151004
12.221306179685069
12.221306179219233
12.221306178753496
12.221306178287854
12.22130617782233
12.221306177356894
12.22130617689156
12.221306176426324
12.221306175961193
12.221306175496164
12.221306175031234
12.22130617456641
12.221306174101679
12.221306173637048
12.221306173172529
12.221306172708102
12.221306172243773
12.221306171779554
12.221306171315437
12.221306170851408
12.221306170387486
12.221306169923674
12.22130616945995
12.22130616899633
12.221306168532823
12.2213061680694
12.22130616760608
12.221306167142863
12.221306166679748
12.221306166216728
12.221306165753825
12.221306165291008
12.221306164828285
12.221306164365675
12.221306163903165
12.221306163440747
12.221306162978431
12.221306162516225
12.22130616205411
12.221306161592102
12.221306161130196
12.221306160668377
12.221306160206666
12.221306159745064
12.221306159283554
12.221306158822136
12.221306158360832
12.221306157899619
12.2213061574385
12.221306156977493
12.221306156516595
12.221306156055782
12.221306155595073
12.22130615513446
12.22130615467395
12.221306154213549
12.221306153753236
12.221306153293025
12.221306152832918
12.221306152372904
12.22130615191299
12.22130615145319
12.221306150993472
12.221306150533863
12.221306150074355
12.22130614961494
12.221306149155627
12.221306148696415
12.221306148237309
12.221306147778288
12.22130614731938
12.221306146860568
12.221306146401853
12.22130614594324
12.221306145484723
12.22130614502631
12.221306144567992
12.221306144109782
12.221306143651663
12.221306143193644
12.221306142735731
12.22130614227791
12.221306141820184
12.221306141362573
12.221306140905048
12.221306140447627
12.221306139990306
12.221306139533077
12.221306139075956
12.221306138618933
12.22130613816201
12.221306137705184
12.221306137248456
12.22130613679183
12.221306136335306
12.221306135878882
12.221306135422543
12.221306134966314
12.221306134510181
12.22130613405415
12.221306133598215
12.221306133142383
12.22130613268664
12.221306132231007
12.221306131775464
12.221306131320029
12.221306130864694

12.221306130409447
12.221306129954302
12.22130612949926
12.22130612904431
12.221306128589466
12.221306128134717
12.221306127680062
12.221306127225512
12.221306126771067
12.221306126316708
12.221306125862455
12.221306125408304
12.221306124954245
12.221306124500286
12.221306124046421
12.221306123592658
12.221306123139003
12.221306122685428
12.221306122231969
12.221306121778598
12.22130612132533
12.221306120872157
12.221306120419081
12.221306119966112
12.221306119513233
12.221306119060461
12.221306118607778
12.221306118155196
12.221306117702714
12.221306117250325
12.221306116798036
12.221306116345849
12.221306115893757
12.22130611544177
12.221306114989877
12.221306114538066
12.221306114086374
12.22130611363478
12.221306113183276
12.221306112731876
12.221306112280566
12.221306111829353
12.22130611137825
12.221306110927236
12.221306110476316
12.22130611002551
12.22130610957478
12.221306109124162
12.221306108673636
12.221306108223217
12.22130610777289
12.22130610732266
12.221306106872524
12.221306106422489
12.22130610597256
12.221306105522718
12.221306105072971
12.221306104623329
12.221306104173788
12.221306103724336
12.221306103274982
12.221306102825737
12.221306102376571
12.221306101927514
12.221306101478557
12.221306101029699
12.221306100580929
12.221306100132258
12.221306099683687
12.22130609923521
12.22130609878684
12.22130609833855
12.221306097890375
12.221306097442287
12.221306096994303
12.221306096546408
12.221306096098616
12.221306095650927
12.22130609520333
12.221306094755818
12.221306094308416
12.221306093861106
12.2213060934139
12.221306092966788
12.221306092519773
12.221306092072854
12.221306091626033
12.22130609117931
12.22130609073267
12.22130609028615
12.221306089839704
12.22130608939337
12.221306088947125
12.221306088500988
12.221306088054947
12.22130608760899
12.221306087163132
12.221306086717385
12.221306086271717
12.221306085826162
12.221306085380697
12.22130608493532
12.221306084490047
12.221306084044867
12.221306083599798
12.221306083154817
12.22130608270992
12.22130608226514
12.221306081820442
12.221306081375841
12.221306080931349
12.221306080486935
12.221306080042632
12.22130607959842
12.221306079154308
12.22130607871029
12.221306078266364
12.221306077822543
12.221306077378815
12.221306076935177
12.221306076491645
12.221306076048206
12.221306075604858
12.221306075161614
12.221306074718463
12.221306074275406
12.22130607383245
12.221306073389586
12.221306072946815
12.22130607250414
12.221306072061575
12.221306071619093
12.221306071176706
12.221306070734423
12.221306070292238
12.221306069850142
12.221306069408138
12.221306068966236
12.221306068524422
12.22130606808272
12.221306067641102
12.221306067199581
12.22130606675816
12.221306066316835
12.2213060658756
12.221306065434462
12.221306064993422
12.221306064552484
12.221306064111626
12.221306063670879
12.221306063230221
12.221306062789665
12.221306062349191
12.221306061908825
12.221306061468544
12.221306061028365
12.221306060588287
12.221306060148292
12.221306059708402
12.221306059268597
12.221306058828901
12.221306058389297
12.221306057949782
12.221306057510368
12.221306057071052
12.221306056631828
12.22130605619269
12.221306055753656
12.221306055314715
12.221306054875868
12.221306054437125
12.221306053998475
12.221306053559914
12.221306053121447
12.221306052683076
12.221306052244815
12.221306051806634
12.22130605136855
12.221306050930567
12.221306050492672
12.221306050054874
12.221306049617171
12.221306049179564
12.22130604874205
12.221306048304637
12.22130604786731
12.221306047430094
12.22130604699295
12.221306046555913
12.22130604611897
12.221306045682125
12.221306045245367
12.221306044808706
12.221306044372156
12.22130604393568
12.221306043499306
12.221306043063025
12.221306042626846
12.221306042190754
12.221306041754758
12.221306041318853
12.221306040883057
12.221306040447342
12.221306040011724
12.221306039576193
12.221306039140766
12.221306038705436
12.221306038270198
12.221306037835058
12.22130603740001
12.221306036965048
12.221306036530189
12.22130603609542
12.221306035660755
12.221306035226176
12.22130603479168
12.2213060343573
12.221306033923
12.221306033488805
12.221306033054702
12.221306032620689
12.221306032186762
12.221306031752942
12.221306031319216
12.221306030885582
12.221306030452038
12.221306030018594
12.221306029585238
12.22130602915197
12.22130602871881
12.22130602828574
12.221306027852764
12.221306027419876
12.221306026987092
12.221306026554393
12.221306026121795
12.221306025689284
12.22130602525687
12.22130602482455
12.221306024392321
12.221306023960196
12.221306023528156
12.221306023096217
12.22130602266436
12.221306022232607
12.221306021800938
12.221306021369367
12.221306020937888
12.221306020506509
12.221306020075222
12.221306019644025
12.221306019212932
12.221306018781911
12.221306018351
12.221306017920186
12.22130601748946
12.221306017058817
12.221306016628276
12.22130601619783
12.221306015767476
12.221306015337218
12.22130601490705
12.221306014476983
12.221306014047
12.221306013617115
12.221306013187316
12.221306012757616
12.22130601232801
12.221306011898504
12.221306011469073
12.22130601103975
12.221306010610515
12.221306010181378
12.221306009752329
12.221306009323373
12.221306008894514
12.221306008465746
12.221306008037068
12.221306007608483
12.221306007179994
12.2213060067516
12.221306006323303
12.221306005895087
12.221306005466962
12.221306005038947
12.221306004611014
12.221306004183177
12.221306003755432
12.221306003327769
12.221306002900223
12.221306002472744
12.221306002045376
12.221306001618089
12.221306001190898
12.221306000763803
12.221306000336797
12.221305999909891
12.22130599948307
12.221305999056357
12.221305998629719
12.221305998203176
12.221305997776723
12.221305997350367
12.22130599692411
12.221305996497932
12.221305996071864
12.221305995645869
12.221305995219982
12.221305994794172
12.221305994368473
12.221305993942853
12.221305993517337
12.2213059930919
12.221305992666563
12.221305992241314
12.221305991816171
12.221305991391102
12.221305990966128
12.221305990541257
12.221305990116472
12.221305989691782
12.221305989267176
12.221305988842667
12.22130598841825
12.221305987993933
12.221305987569703
12.22130598714556
12.221305986721513
12.221305986297551
12.221305985873693
12.221305985449915
12.22130598502623
12.221305984602653
12.221305984179148
12.221305983755757
12.221305983332437
12.221305982909225
12.221305982486093
12.221305982063056
12.221305981640112
12.221305981217254
12.221305980794495
12.221305980371827
12.221305979949253
12.221305979526763
12.221305979104368
12.221305978682068
12.221305978259858
12.221305977837732
12.22130597741571
12.221305976993765
12.221305976571928
12.22130597615017
12.221305975728505
12.221305975306938
12.221305974885464
12.221305974464073
12.221305974042782
12.221305973621579
12.22130597320046
12.221305972779444
12.221305972358513
12.221305971937676
12.221305971516935
12.221305971096271
12.221305970675703
12.22130597025523
12.221305969834853
12.22130596941456
12.221305968994361
12.221305968574264
12.22130596815424
12.221305967734315
12.221305967314482
12.221305966894738
12.22130596647508
12.221305966055521
12.221305965636052
12.221305965216665
12.221305964797379
12.221305964378185
12.221305963959082
12.221305963540065
12.221305963121138
12.22130596270231
12.22130596228356
12.221305961864916
12.22130596144635
12.221305961027882
12.221305960609502
12.221305960191218
12.221305959773012
12.221305959354911
12.22130595893689
12.221305958518963
12.221305958101137
12.221305957683395
12.221305957265736
12.221305956848175
12.2213059564307
12.221305956013316
12.221305955596028
12.22130595517883
12.221305954761725
12.221305954344704
12.221305953927775
12.221305953510933
12.221305953094191
12.22130595267753
12.221305952260959
12.22130595184449
12.221305951428105
12.2213059510118
12.221305950595605
12.221305950179488
12.221305949763464
12.221305949347526
12.22130594893168
12.221305948515937
12.22130594810027
12.221305947684687
12.221305947269213
12.221305946853816
12.221305946438516
12.221305946023298
12.22130594560818
12.221305945193151
12.22130594477821
12.221305944363355
12.221305943948591
12.221305943533919
12.22130594311934
12.22130594270485
12.22130594229044
12.221305941876135
12.221305941461912
12.22130594104778
12.221305940633739
12.221305940219782
12.221305939805923
12.221305939392144
12.221305938978459
12.22130593856487
12.22130593815137
12.221305937737954
12.22130593732463
12.221305936911392
12.221305936498249
12.221305936085196
12.22130593567223
12.221305935259355
12.221305934846567
12.221305934433872
12.221305934021265
12.221305933608754
12.221305933196318
12.221305932783984
12.22130593237173
12.221305931959574
12.221305931547503
12.221305931135532
12.221305930723629
12.22130593031183
12.22130592990012
12.221305929488496
12.221305929076962
12.22130592866552
12.22130592825417
12.221305927842895
12.22130592743172
12.221305927020632
12.221305926609633
12.221305926198731
12.221305925787911
12.221305925377184
12.221305924966542
12.221305924555985
12.221305924145526
12.22130592373515
12.221305923324868
12.221305922914665
12.221305922504566
12.221305922094542
12.221305921684609
12.221305921274773
12.221305920865026
12.221305920455361
12.221305920045792
12.2213059196363
12.221305919226914
12.2213059188176
12.221305918408383
12.221305917999262
12.221305917590218
12.221305917181267
12.221305916772401

12.221305916363633
12.221305915954948
12.221305915546354
12.221305915137844
12.221305914729424
12.221305914321093
12.22130591391286
12.221305913504699
12.221305913096637
12.221305912688658
12.221305912280775
12.221305911872978
12.221305911465267
12.221305911057645
12.221305910650115
12.221305910242668
12.221305909835312
12.221305909428049
12.221305909020868
12.221305908613767
12.221305908206766
12.22130590779985
12.221305907393035
12.22130590698629
12.221305906579648
12.221305906173077
12.221305905766608
12.221305905360222
12.221305904953924
12.221305904547718
12.221305904141596
12.221305903735562
12.22130590332962
12.221305902923758
12.22130590251799
12.221305902112316
12.221305901706721
12.22130590130122
12.221305900895807
12.221305900490481
12.22130590008524
12.221305899680084
12.221305899275022
12.221305898870048
12.221305898465165
12.221305898060363
12.221305897655647
12.221305897251018
12.221305896846495
12.221305896442042
12.221305896037675
12.221305895633401
12.221305895229218
12.221305894825127
12.22130589442111
12.221305894017188
12.221305893613355
12.221305893209607
12.221305892805947
12.22130589240237
12.22130589199889
12.221305891595497
12.221305891192191
12.22130589078897
12.221305890385832
12.221305889982784
12.221305889579831
12.221305889176959
12.221305888774173
12.221305888371473
12.221305887968867
12.221305887566347
12.221305887163913
12.22130588676156
12.221305886359307
12.221305885957133
12.221305885555047
12.221305885153052
12.221305884751137
12.221305884349318
12.221305883947585
12.221305883545933
12.221305883144366
12.221305882742891
12.221305882341502
12.22130588194021
12.22130588153899
12.221305881137868
12.221305880736825
12.221305880335871
12.221305879935008
12.221305879534231
12.221305879133546
12.22130587873293
12.221305878332425
12.221305877931984
12.221305877531643
12.221305877131392
12.221305876731222
12.221305876331137
12.221305875931142
12.221305875531229
12.22130587513142
12.22130587473167
12.22130587433202
12.221305873932463
12.221305873532987
12.221305873133595
12.221305872734304
12.221305872335089
12.221305871935954
12.221305871536913
12.22130587113796
12.221305870739096
12.22130587034031
12.221305869941608
12.221305869543002
12.221305869144484
12.221305868746045
12.2213058683477
12.221305867949436
12.221305867551258
12.221305867153168
12.221305866755166
12.221305866357248
12.221305865959412
12.221305865561673
12.221305865164013
12.221305864766437
12.22130586436895
12.221305863971551
12.221305863574246
12.221305863177012
12.221305862779875
12.221305862382813
12.221305861985838
12.221305861588965
12.22130586119217
12.221305860795463
12.221305860398838
12.221305860002301
12.221305859605847
12.221305859209481
12.221305858813203
12.221305858417004
12.221305858020896
12.221305857624882
12.221305857228941
12.221305856833094
12.221305856437333
12.221305856041655
12.22130585564607
12.221305855250549
12.22130585485513
12.221305854459802
12.221305854064553
12.221305853669389
12.221305853274313
12.221305852879324
12.221305852484408
12.221305852089591
12.221305851694858
12.22130585130021
12.221305850905647
12.221305850511177
12.22130585011678
12.221305849722475
12.221305849328255
12.221305848934115
12.221305848540064
12.221305848146107
12.221305847752225
12.221305847358437
12.221305846964729
12.221305846571104
12.221305846177566
12.221305845784116
12.221305845390752
12.221305844997476
12.22130584460428
12.221305844211171
12.221305843818142
12.221305843425206
12.221305843032345
12.22130584263958
12.221305842246894
12.221305841854297
12.221305841461788
12.221305841069352
12.221305840677028
12.22130584028476
12.221305839892592
12.221305839500499
12.221305839108497
12.22130583871658
12.221305838324746
12.221305837933011
12.221305837541342
12.22130583714977
12.221305836758276
12.221305836366865
12.221305835975551
12.22130583558431
12.22130583519316
12.221305834802097
12.22130583441111
12.221305834020214
12.221305833629406
12.221305833238679
12.221305832848024
12.221305832457467
12.221305832066996
12.221305831676618
12.221305831286305
12.221305830896092
12.221305830505962
12.2213058301159
12.221305829725939
12.221305829336057
12.22130582894626
12.221305828556554
12.221305828166926
12.221305827777382
12.221305827387921
12.22130582699856
12.221305826609267
12.221305826220062
12.221305825830944
12.221305825441904
12.221305825052957
12.221305824664087
12.221305824275312
12.221305823886611
12.221305823497998
12.221305823109473
12.221305822721027
12.221305822332669
12.221305821944389
12.2213058215562
12.221305821168098
12.22130582078007
12.22130582039214
12.221305820004277
12.221305819616509
12.22130581922882
12.221305818841216
12.2213058184537
12.221305818066268
12.221305817678916
12.221305817291656
12.221305816904483
12.221305816517377
12.221305816130366
12.22130581574344
12.221305815356576
12.221305814969828
12.221305814583157
12.221305814196556
12.221305813810048
12.221305813423626
12.221305813037276
12.22130581265102
12.221305812264847
12.221305811878752
12.221305811492737
12.221305811106829
12.221305810720985
12.22130581033524
12.221305809949557
12.22130580956397
12.221305809178466
12.221305808793046
12.221305808407715
12.221305808022459
12.221305807637286
12.2213058072522
12.2213058068672
12.221305806482281
12.221305806097444
12.221305805712698
12.22130580532802
12.221305804943437
12.221305804558941
12.22130580417452
12.22130580379019
12.221305803405933
12.221305803021773
12.221305802637682
12.221305802253687
12.221305801869773
12.221305801485933
12.221305801102181
12.221305800718516
12.221305800334928
12.221305799951422
12.221305799568022
12.221305799184675
12.22130579880143
12.221305798418262
12.221305798035171
12.221305797652175
12.22130579726925
12.221305796886414
12.221305796503666
12.221305796120994
12.221305795738413
12.221305795355903
12.221305794973496
12.22130579459114
12.221305794208886
12.221305793826717
12.221305793444635
12.221305793062626
12.221305792680711
12.221305792298864
12.221305791917109
12.221305791535432
12.221305791153844
12.221305790772336
12.221305790390918
12.221305790009561
12.221305789628307
12.221305789247133
12.221305788866033
12.22130578848502
12.221305788104095
12.22130578772325
12.221305787342487
12.221305786961807
12.221305786581203
12.221305786200695
12.221305785820254
12.221305785439904
12.221305785059641
12.221305784679455
12.221305784299346
12.22130578391933
12.221305783539401
12.221305783159531
12.22130578277976
12.221305782400075
12.221305782020464
12.221305781640943
12.221305781261494
12.221305780882131
12.221305780502853
12.221305780123654
12.22130577974454
12.221305779365514
12.221305778986563
12.221305778607706
12.221305778228908
12.221305777850205
12.221305777471576
12.221305777093047
12.221305776714589
12.221305776336216
12.221305775957932
12.221305775579722
12.221305775201587
12.22130577482354
12.221305774445579
12.221305774067693
12.221305773689892
12.22130577331218
12.22130577293454
12.221305772556988
12.221305772179523
12.221305771802127
12.221305771424818
12.221305771047588
12.221305770670456
12.221305770293379
12.221305769916405
12.221305769539516
12.221305769162688
12.22130576878595
12.221305768409303
12.221305768032735
12.221305767656249
12.22130576727983
12.221305766903505
12.221305766527257
12.221305766151092
12.221305765775018
12.221305765399016
12.2213057650231
12.22130576464726
12.221305764271507
12.22130576389584
12.221305763520244
12.22130576314473
12.221305762769305
12.221305762393955
12.22130576201869
12.221305761643512
12.221305761268397
12.221305760893385
12.221305760518442
12.22130576014358
12.221305759768807
12.221305759394106
12.221305759019495
12.221305758644961
12.221305758270503
12.22130575789613
12.221305757521845
12.221305757147634
12.221305756773509
12.221305756399467
12.2213057560255
12.221305755651619
12.221305755277816
12.221305754904096
12.22130575453045
12.221305754156889
12.221305753783422
12.221305753410025
12.2213057530367
12.221305752663469
12.221305752290307
12.221305751917226
12.221305751544245
12.22130575117134
12.221305750798505
12.221305750425758
12.221305750053084
12.2213057496805
12.221305749307987
12.221305748935569
12.221305748563223
12.221305748190955
12.221305747818777
12.221305747446673
12.221305747074656
12.22130574670271
12.22130574633085
12.221305745959073
12.221305745587369
12.221305745215753
12.221305744844221
12.221305744472753
12.221305744101386
12.22130574373009
12.221305743358876

12.221305742987742
12.221305742616686
12.22130574224571
12.221305741874819
12.221305741504004
12.221305741133275
12.221305740762626
12.22130574039205
12.221305740021563
12.221305739651152
12.221305739280817
12.221305738910576
12.221305738540405
12.221305738170317
12.221305737800302
12.221305737430376
12.22130573706053
12.221305736690763
12.221305736321074
12.221305735951466
12.221305735581947
12.221305735212496
12.221305734843126
12.221305734473853
12.221305734104632
12.22130573373551
12.22130573336647
12.221305732997502
12.221305732628613
12.221305732259813
12.221305731891087
12.221305731522442
12.221305731153874
12.221305730785387
12.221305730416976
12.221305730048654
12.221305729680418
12.221305729312247
12.221305728944163
12.221305728576153
12.22130572820823
12.221305727840383
12.221305727472611
12.221305727104934
12.221305726737324
12.221305726369797
12.22130572600235
12.221305725634986
12.221305725267692
12.221305724900489
12.221305724533359
12.22130572416631
12.221305723799343
12.22130572343246
12.221305723065646
12.221305722698917
12.221305722332266
12.221305721965697
12.221305721599203
12.221305721232786
12.221305720866464
12.22130572050021
12.221305720134033
12.22130571976794
12.221305719401927
12.221305719035989
12.221305718670138
12.221305718304356
12.221305717938662
12.221305717573046
12.22130571720751
12.221305716842052
12.22130571647667
12.22130571611137
12.221305715746155
12.22130571538101
12.221305715015944
12.221305714650967
12.221305714286064
12.22130571392124
12.221305713556497
12.221305713191821
12.221305712827236
12.221305712462735
12.221305712098307
12.22130571173395
12.221305711369691
12.221305711005485
12.221305710641387
12.221305710277345
12.221305709913393
12.221305709549515
12.22130570918572
12.221305708822003
12.221305708458365
12.221305708094802
12.221305707731318
12.221305707367927
12.2213057070046
12.221305706641363
12.221305706278198
12.221305705915109
12.2213057055521
12.221305705189174
12.221305704826323
12.221305704463555
12.221305704100862
12.221305703738244
12.221305703375704
12.22130570301325
12.221305702650882
12.22130570228858
12.221305701926362
12.221305701564217
12.22130570120215
12.22130570084016
12.221305700478267
12.221305700116437
12.22130569975468
12.221305699393016
12.22130569903142
12.221305698669916
12.221305698308473
12.221305697947114
12.221305697585837
12.221305697224645
12.221305696863524
12.22130569650248
12.221305696141512
12.221305695780622
12.221305695419822
12.221305695059094
12.221305694698442
12.221305694337863
12.22130569397737
12.221305693616957
12.221305693256621
12.221305692896358
12.221305692536186
12.221305692176076
12.221305691816053
12.221305691456106
12.221305691096232
12.22130569073644
12.22130569037673
12.221305690017092
12.221305689657541
12.221305689298058
12.221305688938655
12.221305688579342
12.22130568822009
12.221305687860921
12.22130568750183
12.221305687142817
12.221305686783895
12.221305686425039
12.221305686066264
12.221305685707565
12.221305685348936
12.221305684990394
12.22130568463193
12.221305684273537
12.221305683915233
12.221305683556995
12.221305683198848
12.221305682840772
12.221305682482772
12.221305682124852
12.221305681767014
12.22130568140924
12.221305681051547
12.221305680693934
12.221305680336407
12.221305679978952
12.221305679621567
12.221305679264272
12.221305678907049
12.221305678549903
12.22130567819283
12.221305677835844
12.22130567747893
12.221305677122094
12.221305676765342
12.221305676408655
12.22130567605206
12.22130567569553
12.221305675339082
12.221305674982714
12.221305674626416
12.221305674270196
12.221305673914067
12.221305673558003
12.221305673202018
12.221305672846107
12.22130567249028
12.221305672134529
12.221305671778854
12.221305671423258
12.221305671067736
12.221305670712288
12.221305670356925
12.221305670001634
12.221305669646418
12.221305669291283
12.221305668936225
12.221305668581245
12.221305668226336
12.22130566787151
12.22130566751676
12.221305667162094
12.221305666807499
12.22130566645298
12.221305666098543
12.221305665744163
12.221305665389883
12.221305665035667
12.22130566468154
12.221305664327474
12.22130566397349
12.221305663619587
12.221305663265765
12.221305662912014
12.221305662558345
12.221305662204745
12.221305661851227
12.221305661497787
12.221305661144415
12.221305660791122
12.221305660437912
12.221305660084775
12.22130565973172
12.221305659378727
12.22130565902583
12.221305658672994
12.221305658320242
12.221305657967562
12.221305657614966
12.221305657262441
12.221305656909982
12.221305656557622
12.221305656205327
12.221305655853111
12.221305655500961
12.221305655148903
12.221305654796918
12.221305654445
12.221305654093165
12.221305653741409
12.221305653389724
12.221305653038115
12.221305652686588
12.22130565233513
12.221305651983755
12.221305651632454
12.22130565128123
12.221305650930079
12.221305650579005
12.22130565022801
12.221305649877088
12.22130564952624
12.22130564917547
12.221305648824782
12.221305648474166
12.221305648123622
12.221305647773166
12.221305647422774
12.221305647072462
12.221305646722229
12.221305646372068
12.221305646021982
12.221305645671977
12.221305645322044
12.221305644972196
12.221305644622406
12.221305644272705
12.221305643923076
12.221305643573517
12.221305643224046
12.221305642874647
12.221305642525325
12.221305642176077
12.221305641826897
12.221305641477803
12.221305641128787
12.221305640779834
12.221305640430971
12.221305640082171
12.221305639733458
12.221305639384813
12.221305639036247
12.221305638687747
12.221305638339336
12.221305637990996
12.221305637642732
12.221305637294545
12.221305636946433
12.221305636598387
12.221305636250435
12.221305635902544
12.221305635554733
12.221305635206994
12.221305634859343
12.221305634511756
12.221305634164244
12.221305633816806
12.221305633469447
12.221305633122167
12.221305632774962
12.22130563242782
12.22130563208076
12.221305631733788
12.22130563138688
12.221305631040046
12.221305630693298
12.221305630346615
12.221305630000007
12.221305629653477
12.221305629307023
12.221305628960637
12.221305628614346
12.221305628268112
12.221305627921952
12.221305627575877
12.221305627229874
12.22130562688394
12.221305626538083
12.221305626192315
12.221305625846613
12.221305625500978
12.221305625155424
12.221305624809947
12.22130562446454
12.221305624119212
12.221305623773961
12.221305623428787
12.221305623083682
12.22130562273865
12.221305622393691
12.221305622048822
12.221305621704014
12.221305621359289
12.221305621014626
12.221305620670044
12.22130562032554
12.221305619981111
12.221305619636757
12.221305619292472
12.22130561894827
12.221305618604141
12.22130561826009
12.221305617916098
12.221305617572193
12.221305617228365
12.221305616884596
12.221305616540924
12.221305616197304
12.221305615853778
12.221305615510312
12.22130561516693
12.221305614823615
12.221305614480388
12.221305614137218
12.221305613794133
12.221305613451129
12.22130561310818
12.221305612765319
12.221305612422535
12.221305612079814
12.221305611737172
12.221305611394614
12.221305611052118
12.221305610709702
12.22130561036735
12.221305610025086
12.221305609682895
12.221305609340776
12.221305608998726
12.221305608656749
12.221305608314863
12.221305607973038
12.221305607631287
12.221305607289612
12.221305606948006
12.221305606606483
12.22130560626503
12.221305605923657
12.221305605582344
12.22130560524111
12.221305604899966
12.221305604558871
12.221305604217868
12.22130560387694
12.221305603536075
12.22130560319529
12.221305602854574
12.221305602513937
12.221305602173375
12.221305601832883
12.221305601492473
12.221305601152123
12.221305600811853
12.221305600471664
12.22130560013154
12.221305599791492
12.221305599451517
12.221305599111618
12.221305598771792
12.221305598432037
12.221305598092362
12.221305597752767
12.221305597413231
12.221305597073767
12.22130559673438
12.22130559639508
12.221305596055837
12.221305595716675
12.22130559537758
12.221305595038576
12.22130559469963
12.22130559436076
12.221305594021965
12.22130559368325
12.221305593344598
12.221305593006027
12.22130559266753
12.221305592329093
12.221305591990744
12.221305591652468
12.221305591314257
12.221305590976124
12.22130559063806
12.221305590300073
12.221305589962162
12.221305589624325
12.221305589286551
12.221305588948864
12.221305588611246
12.221305588273696
12.221305587936225
12.221305587598824
12.221305587261496
12.221305586924245
12.221305586587068
12.221305586249956
12.221305585912923
12.221305585575962
12.221305585239067
12.221305584902256
12.221305584565517
12.221305584228844
12.221305583892253
12.221305583555727
12.22130558321928
12.2213055828829
12.221305582546597
12.221305582210366
12.221305581874212
12.221305581538124
12.22130558120211
12.221305580866176
12.221305580530307
12.221305580194516
12.221305579858795
12.221305579523147
12.221305579187572
12.221305578852075
12.221305578516645
12.221305578181285
12.221305577846003
12.221305577510794
12.221305577175658
12.221305576840592
12.221305576505602
12.221305576170684
12.221305575835839
12.221305575501072
12.221305575166358
12.221305574831739
12.221305574497174
12.221305574162692
12.221305573828282
12.221305573493948
12.22130557315968
12.221305572825491
12.221305572491373
12.221305572157322
12.221305571823349
12.221305571489442
12.221305571155607
12.221305570821855
12.221305570488168
12.221305570154556
12.221305569821011
12.22130556948755
12.221305569154147
12.221305568820823
12.221305568487574
12.221305568154396
12.22130556782129
12.221305567488251
12.2213055671553
12.221305566822398
12.221305566489578
12.221305566156833
12.22130556582417
12.22130556549156
12.221305565159035
12.221305564826576
12.221305564494193
12.221305564161879
12.221305563829645
12.22130556349747
12.221305563165377
12.221305562833352
12.221305562501398
12.22130556216952
12.221305561837713
12.221305561505977
12.221305561174319
12.22130556084273
12.221305560511203
12.221305560179761
12.221305559848382
12.221305559517077
12.221305559185849
12.221305558854683
12.221305558523602
12.22130555819259
12.221305557861635
12.22130555753076
12.221305557199964
12.221305556869234
12.22130555653858
12.221305556207994
12.221305555877475
12.221305555547037
12.221305555216672
12.221305554886369
12.221305554556144
12.221305554225983
12.221305553895897
12.22130555356589
12.221305553235949
12.221305552906077
12.221305552576284
12.221305552246562
12.221305551916902
12.221305551587323

12.221305551257812
12.221305550928369
12.221305550598997
12.221305550269705
12.221305549940483
12.221305549611328
12.221305549282247
12.221305548953234
12.221305548624303
12.221305548295426
12.22130554796663
12.221305547637915
12.221305547309258
12.221305546980675
12.221305546652161
12.221305546323721
12.221305545995355
12.221305545667052
12.221305545338831
12.22130554501068
12.221305544682595
12.221305544354584
12.221305544026638
12.221305543698763
12.22130554337098
12.22130554304324
12.22130554271559
12.221305542388007
12.221305542060488
12.221305541733043
12.221305541405671
12.221305541078369
12.221305540751146
12.221305540423984
12.22130554009689
12.221305539769881
12.221305539442934
12.221305539116063
12.22130553878926
12.22130553846252
12.221305538135862
12.221305537809265
12.221305537482746
12.221305537156292
12.221305536829924
12.221305536503614
12.221305536177374
12.2213055358512
12.221305535525117
12.22130553519909
12.22130553487314
12.221305534547255
12.221305534221436
12.221305533895697
12.221305533570026
12.221305533244431
12.221305532918894
12.221305532593432
12.221305532268051
12.221305531942729
12.221305531617492
12.221305531292312
12.2213055309672
12.221305530642173
12.221305530317203
12.221305529992305
12.221305529667493
12.22130552934273
12.22130552901805
12.221305528693435
12.221305528368902
12.221305528044425
12.221305527720022
12.221305527395694
12.221305527071435
12.221305526747246
12.221305526423125
12.221305526099082
12.221305525775096
12.221305525451184
12.221305525127349
12.221305524803585
12.221305524479886
12.221305524156254
12.2213055238327
12.22130552350921
12.2213055231858
12.221305522862455
12.221305522539177
12.221305522215967
12.221305521892832
12.221305521569766
12.221305521246776
12.221305520923847
12.221305520601
12.221305520278204
12.221305519955493
12.22130551963285
12.221305519310276
12.22130551898776
12.221305518665327
12.221305518342971
12.221305518020667
12.221305517698447
12.22130551737629
12.22130551705421
12.221305516732187
12.221305516410249
12.221305516088368
12.221305515766568
12.221305515444822
12.221305515123161
12.221305514801559
12.221305514480042
12.221305514158574
12.22130551383719
12.221305513515873
12.221305513194627
12.22130551287345
12.221305512552345
12.221305512231305
12.221305511910334
12.22130551158943
12.221305511268612
12.221305510947847
12.221305510627152
12.22130551030654
12.221305509985989
12.221305509665507
12.221305509345093
12.221305509024754
12.221305508704473
12.221305508384274
12.221305508064143
12.221305507744077
12.221305507424086
12.221305507104164
12.221305506784294
12.221305506464518
12.2213055061448
12.221305505825155
12.221305505505573
12.221305505186066
12.22130550486662
12.221305504547251
12.221305504227955
12.221305503908722
12.221305503589562
12.221305503270466
12.22130550295144
12.221305502632488
12.221305502313601
12.221305501994786
12.221305501676044
12.221305501357364
12.221305501038747
12.221305500720213
12.221305500401748
12.221305500083346
12.221305499765014
12.221305499446746
12.221305499128562
12.221305498810427
12.221305498492372
12.221305498174388
12.221305497856465
12.221305497538625
12.221305497220841
12.221305496903137
12.22130549658549
12.221305496267915
12.221305495950414
12.221305495632976
12.221305495315613
12.221305494998317
12.221305494681083
12.221305494363932
12.221305494046838
12.221305493729812
12.221305493412865
12.22130549309598
12.221305492779159
12.221305492462415
12.221305492145744
12.221305491829131
12.22130549151259
12.221305491196114
12.22130549087972
12.221305490563378
12.221305490247115
12.22130548993092
12.221305489614783
12.221305489298727
12.221305488982738
12.221305488666815
12.221305488350964
12.221305488035169
12.221305487719462
12.221305487403814
12.221305487088229
12.221305486772719
12.221305486457275
12.221305486141905
12.22130548582659
12.22130548551136
12.221305485196195
12.221305484881091
12.221305484566054
12.221305484251095
12.221305483936197
12.221305483621366
12.221305483306601
12.22130548299192
12.2213054826773
12.221305482362737
12.221305482048258
12.22130548173384
12.221305481419492
12.221305481105206
12.221305480790996
12.221305480476854
12.221305480162783
12.221305479848764
12.221305479534829
12.221305479220955
12.22130547890715
12.221305478593415
12.221305478279746
12.22130547796615
12.221305477652619
12.221305477339158
12.221305477025766
12.22130547671243
12.221305476399177
12.22130547608598
12.22130547577286
12.2213054754598
12.221305475146812
12.221305474833898
12.221305474521039
12.22130547420826
12.221305473895542
12.221305473582897
12.221305473270318
12.221305472957795
12.221305472645366
12.221305472332977
12.221305472020678
12.221305471708433
12.221305471396258
12.221305471084152
12.22130547077211
12.221305470460145
12.221305470148234
12.221305469836407
12.221305469524637
12.221305469212943
12.221305468901315
12.221305468589748
12.221305468278258
12.221305467966824
12.22130546765546
12.221305467344173
12.221305467032943
12.22130546672178
12.221305466410694
12.221305466099665
12.221305465788717
12.221305465477824
12.221305465167005
12.221305464856242
12.22130546454556
12.221305464234954
12.221305463924399
12.221305463613914
12.221305463303496
12.221305462993147
12.22130546268286
12.221305462372651
12.221305462062505
12.221305461752427
12.22130546144241
12.221305461132465
12.221305460822588
12.22130546051278
12.221305460203034
12.221305459893358
12.221305459583753
12.221305459274207
12.221305458964732
12.221305458655323
12.221305458345984
12.221305458036715
12.221305457727505
12.221305457418373
12.221305457109295
12.22130545680029
12.221305456491363
12.221305456182481
12.221305455873681
12.221305455564941
12.221305455256278
12.221305454947677
12.221305454639138
12.221305454330668
12.221305454022268
12.221305453713933
12.221305453405664
12.22130545309746
12.22130545278933
12.22130545248127
12.221305452173267
12.22130545186534
12.22130545155746
12.221305451249664
12.221305450941937
12.221305450634274
12.221305450326662
12.22130545001914
12.221305449711666
12.221305449404266
12.221305449096938
12.22130544878967
12.221305448482473
12.221305448175332
12.221305447868275
12.221305447561278
12.221305447254348
12.221305446947476
12.22130544664068
12.221305446333949
12.221305446027282
12.221305445720688
12.221305445414151
12.221305445107685
12.221305444801281
12.22130544449496
12.221305444188694
12.221305443882487
12.221305443576352
12.221305443270284
12.221305442964281
12.221305442658345
12.221305442352476
12.22130544204669
12.221305441740943
12.221305441435277
12.221305441129672
12.221305440824137
12.221305440518663
12.221305440213264
12.221305439907926
12.221305439602657
12.221305439297453
12.221305438992314
12.221305438687239
12.22130543838223
12.221305438077291
12.221305437772415
12.221305437467612
12.221305437162872
12.221305436858197
12.221305436553589
12.221305436249043
12.221305435944563
12.221305435640161
12.221305435335811
12.221305435031528
12.221305434727324
12.221305434423167
12.221305434119095
12.221305433815074
12.221305433511128
12.221305433207252
12.221305432903426
12.22130543259968
12.221305432295997
12.221305431992375
12.221305431688824
12.22130543138534
12.221305431081918
12.22130543077856
12.221305430475272
12.221305430172054
12.221305429868895
12.221305429565797
12.221305429262767
12.221305428959809
12.221305428656912
12.221305428354084
12.221305428051323
12.221305427748623
12.221305427445989
12.221305427143433
12.221305426840924
12.221305426538494
12.221305426236126
12.221305425933819
12.221305425631584
12.221305425329408
12.2213054250273
12.221305424725257
12.221305424423281
12.22130542412138
12.221305423819528
12.221305423517748
12.22130542321603
12.221305422914396
12.2213054226128
12.221305422311282
12.22130542200984
12.221305421708447
12.221305421407129
12.221305421105875
12.221305420804688
12.221305420503557
12.221305420202503
12.221305419901512
12.221305419600585
12.221305419299714
12.221305418998913
12.221305418698186
12.221305418397515
12.221305418096915
12.221305417796385
12.221305417495907
12.221305417195493
12.22130541689516
12.221305416594888
12.22130541629467
12.221305415994527
12.221305415694445
12.221305415394431
12.221305415094477
12.2213054147946
12.221305414494774
12.221305414195015
12.221305413895326
12.221305413595706
12.221305413296143
12.22130541299665
12.221305412697218
12.221305412397856
12.221305412098557
12.221305411799321
12.221305411500152
12.221305411201042
12.221305410902007
12.22130541060303
12.22130541030412
12.221305410005268
12.2213054097065
12.221305409407776
12.221305409109126
12.221305408810542
12.221305408512011
12.221305408213558
12.221305407915168
12.221305407616844
12.22130540731858
12.221305407020383
12.221305406722248
12.221305406424179
12.221305406126168
12.221305405828238
12.221305405530364
12.221305405232561
12.221305404934807
12.221305404637123
12.221305404339518
12.221305404041964
12.221305403744477
12.221305403447056
12.221305403149701
12.221305402852408
12.221305402555181
12.221305402258022
12.221305401960914
12.221305401663884
12.221305401366916
12.221305401070014
12.221305400773167
12.221305400476384
12.221305400179672
12.221305399883022
12.22130539958644
12.22130539928992
12.221305398993465
12.221305398697078
12.22130539840075
12.221305398104489
12.221305397808289
12.22130539751216
12.22130539721609
12.22130539692008
12.221305396624137
12.221305396328269
12.221305396032454
12.221305395736701
12.221305395441021
12.221305395145405
12.221305394849846
12.221305394554355
12.221305394258925
12.221305393963563
12.22130539366827
12.221305393373031
12.221305393077865
12.221305392782758
12.22130539248771
12.22130539219274
12.221305391897822
12.221305391602971
12.221305391308185
12.221305391013455
12.2213053907188
12.221305390424206
12.221305390129668
12.221305389835198
12.221305389540808
12.221305389246472
12.22130538895219
12.22130538865798
12.221305388363843
12.221305388069748
12.221305387775734
12.221305387481774
12.221305387187888
12.221305386894056
12.221305386600289
12.221305386306593
12.221305386012952
12.22130538571938
12.221305385425866
12.221305385132425
12.221305384839036
12.221305384545726
12.221305384252473
12.221305383959274
12.221305383666156
12.221305383373089
12.221305383080086
12.221305382787158
12.221305382494277
12.221305382201468
12.221305381908726
12.221305381616041
12.221305381323424
12.221305381030865
12.221305380738363
12.221305380445942
12.221305380153584
12.221305379861276
12.221305379569047
12.221305379276869
12.221305378984756
12.221305378692701
12.221305378400723
12.221305378108804
12.221305377816947
12.22130537752515
12.22130537723342
12.22130537694175
12.22130537665015
12.221305376358611
12.22130537606712
12.221305375775716
12.22130537548437
12.221305375193076
12.22130537490185
12.221305374610692
12.221305374319591
12.221305374028555
12.221305373737582
12.221305373446674
12.221305373155829
12.221305372865041
12.221305372574326
12.221305372283666
12.221305371993077
12.221305371702545
12.221305371412083
12.22130537112167
12.221305370831331
12.221305370541053
12.221305370250848
12.22130536996069
12.221305369670603
12.221305369380575
12.221305369090619
12.221305368800705
12.221305368510869
12.221305368221099
12.22130536793139
12.221305367641744
12.221305367352155
12.221305367062628
12.22130536677317
12.221305366483774
12.221305366194438
12.221305365905161
12.22130536561596
12.221305365326803
12.221305365037727
12.221305364748709
12.221305364459747
12.221305364170854
12.221305363882019
12.22130536359325
12.221305363304545
12.221305363015897
12.221305362727312
12.221305362438802
12.221305362150343
12.221305361861948
12.221305361573624
12.221305361285344
12.22130536099714
12.221305360709001
12.221305360420917
12.221305360132897
12.221305359844946
12.22130535955705
12.221305359269214
12.221305358981455
12.221305358693737
12.221305358406102
12.221305358118519
12.221305357831003
12.221305357543548
12.221305357256151
12.221305356968822
12.221305356681553
12.221305356394346
12.221305356107202
12.221305355820117
12.221305355533099
12.221305355246136
12.221305354959242
12.221305354672413
12.221305354385642
12.221305354098934

12.221305353812287
12.221305353525704
12.22130535323918
12.221305352952719
12.22130535266632
12.22130535237999
12.221305352093713
12.221305351807503
12.221305351521352
12.221305351235264
12.221305350949248
12.221305350663279
12.221305350377378
12.221305350091537
12.22130534980576
12.221305349520048
12.221305349234399
12.221305348948807
12.221305348663279
12.221305348377811
12.221305348092402
12.22130534780706
12.221305347521781
12.221305347236564
12.221305346951413
12.221305346666314
12.22130534638128
12.221305346096306
12.221305345811395
12.221305345526556
12.221305345241767
12.221305344957035
12.221305344672379
12.22130534438778
12.221305344103241
12.22130534381876
12.221305343534347
12.221305343249993
12.22130534296571
12.221305342681475
12.221305342397299
12.221305342113192
12.221305341829154
12.22130534154517
12.221305341261248
12.221305340977395
12.221305340693592
12.221305340409856
12.221305340126174
12.221305339842568
12.221305339559017
12.22130533927552
12.221305338992096
12.22130533870873
12.22130533842542
12.221305338142178
12.221305337858983
12.22130533757587
12.221305337292808
12.221305337009811
12.221305336726875
12.221305336444006
12.221305336161192
12.221305335878432
12.221305335595739
12.221305335313112
12.221305335030541
12.221305334748026
12.221305334465594
12.2213053341832
12.221305333900881
12.22130533361862
12.221305333336414
12.221305333054273
12.221305332772197
12.221305332490182
12.221305332208228
12.22130533192633
12.221305331644494
12.221305331362723
12.221305331081012
12.221305330799364
12.221305330517769
12.221305330236246
12.221305329954777
12.221305329673369
12.22130532939202
12.221305329110741
12.221305328829521
12.221305328548357
12.221305328267263
12.221305327986217
12.221305327705243
12.221305327424327
12.221305327143467
12.22130532686267
12.221305326581934
12.221305326301264
12.221305326020644
12.221305325740095
12.2213053254596
12.221305325179175
12.221305324898804
12.221305324618497
12.221305324338248
12.221305324058061
12.221305323777928
12.221305323497875
12.221305323217864
12.221305322937923
12.221305322658038
12.221305322378218
12.221305322098456
12.221305321818756
12.221305321539118
12.221305321259539
12.221305320980024
12.221305320700557
12.221305320421163
12.221305320141823
12.221305319862548
12.221305319583333
12.221305319304179
12.22130531902508
12.221305318746053
12.221305318467076
12.221305318188165
12.221305317909312
12.221305317630526
12.221305317351787
12.221305317073115
12.221305316794515
12.221305316515963
12.221305316237476
12.221305315959043
12.221305315680675
12.221305315402367
12.221305315124123
12.221305314845939
12.221305314567813
12.22130531428974
12.221305314011735
12.221305313733785
12.221305313455904
12.221305313178085
12.22130531290031
12.221305312622606
12.221305312344967
12.221305312067383
12.22130531178986
12.221305311512397
12.221305311234998
12.221305310957641
12.221305310680371
12.22130531040315
12.221305310125976
12.221305309848884
12.221305309571829
12.221305309294863
12.221305309017936
12.221305308741073
12.221305308464279
12.22130530818753
12.221305307910848
12.221305307634228
12.221305307357671
12.221305307081167
12.221305306804734
12.221305306528341
12.221305306252027
12.221305305975754
12.221305305699564
12.221305305423414
12.221305305147338
12.221305304871315
12.221305304595356
12.221305304319452
12.221305304043605
12.221305303767824
12.221305303492107
12.22130530321645
12.22130530294084
12.221305302665302
12.221305302389814
12.221305302114397
12.221305301839024
12.221305301563731
12.221305301288483
12.221305301013299
12.221305300738175
12.221305300463111
12.221305300188103
12.22130529991316
12.221305299638274
12.221305299363452
12.221305299088687
12.22130529881398
12.221305298539331
12.221305298264744
12.221305297990213
12.221305297715753
12.221305297441333
12.22130529716699
12.221305296892707
12.221305296618466
12.221305296344298
12.221305296070192
12.221305295796137
12.221305295522146
12.221305295248207
12.221305294974336
12.221305294700526
12.221305294426774
12.221305294153073
12.221305293879444
12.221305293605868
12.221305293332355
12.221305293058895
12.221305292785495
12.22130529251216
12.22130529223888
12.221305291965667
12.221305291692502
12.221305291419398
12.221305291146356
12.221305290873378
12.221305290600457
12.221305290327583
12.22130529005478
12.22130528978204
12.221305289509349
12.221305289236724
12.221305288964155
12.221305288691644
12.221305288419186
12.22130528814681
12.22130528787447
12.221305287602199
12.22130528732999
12.221305287057834
12.221305286785736
12.221305286513703
12.22130528624172
12.22130528596981
12.221305285697952
12.221305285426153
12.221305285154408
12.221305284882726
12.221305284611095
12.221305284339536
12.221305284068034
12.221305283796589
12.221305283525199
12.221305283253868
12.221305282982593
12.221305282711397
12.221305282440238
12.221305282169148
12.221305281898118
12.221305281627135
12.22130528135622
12.221305281085362
12.221305280814562
12.22130528054382
12.221305280273144
12.221305280002516
12.221305279731954
12.221305279461449
12.221305279191
12.221305278920616
12.221305278650286
12.221305278380012
12.221305278109801
12.221305277839646
12.221305277569556
12.221305277299516
12.221305277029538
12.22130527675963
12.221305276489762
12.221305276219972
12.221305275950224
12.221305275680535
12.22130527541091
12.221305275141347
12.221305274871833
12.221305274602388
12.221305274332993
12.221305274063663
12.221305273794389
12.221305273525168
12.221305273256014
12.221305272986907
12.221305272717872
12.221305272448875
12.221305272179963
12.221305271911094
12.22130527164229
12.221305271373536
12.221305271104843
12.221305270836215
12.221305270567639
12.221305270299121
12.221305270030665
12.221305269762272
12.221305269493929
12.221305269225647
12.221305268957416
12.221305268689253
12.221305268421142
12.221305268153095
12.221305267885093
12.221305267617169
12.221305267349296
12.221305267081476
12.221305266813715
12.221305266546011
12.221305266278373
12.221305266010784
12.22130526574326
12.221305265475786
12.221305265208377
12.221305264941025
12.221305264673722
12.221305264406496
12.221305264139316
12.2213052638722
12.221305263605133
12.221305263338126
12.221305263071182
12.221305262804293
12.22130526253746
12.221305262270688
12.221305262003973
12.221305261737314
12.22130526147072
12.221305261204176
12.221305260937694
12.22130526067126
12.2213052604049
12.221305260138593
12.221305259872329
12.22130525960614
12.221305259340003
12.221305259073922
12.221305258807904
12.221305258541943
12.221305258276038
12.221305258010188
12.221305257744394
12.221305257478658
12.221305257212977
12.22130525694737
12.221305256681806
12.221305256416306
12.221305256150863
12.22130525588547
12.221305255620143
12.221305255354876
12.221305255089664
12.221305254824506
12.221305254559415
12.221305254294363
12.221305254029378
12.221305253764452
12.221305253499585
12.22130525323477
12.221305252970014
12.221305252705326
12.221305252440681
12.221305252176101
12.221305251911575
12.221305251647108
12.2213052513827
12.221305251118348
12.221305250854055
12.22130525058982
12.221305250325637
12.221305250061512
12.221305249797446
12.221305249533437
12.221305249269484
12.2213052490056
12.221305248741755
12.221305248477982
12.221305248214259
12.221305247950601
12.221305247686992
12.221305247423441
12.221305247159952
12.22130524689651
12.221305246633131
12.221305246369809
12.221305246106553
12.221305245843341
12.221305245580195
12.221305245317097
12.221305245054065
12.22130524479108
12.221305244528164
12.221305244265306
12.221305244002494
12.221305243739746
12.221305243477047
12.221305243214418
12.221305242951832
12.221305242689313
12.221305242426851
12.221305242164433
12.221305241902085
12.221305241639794
12.221305241377555
12.221305241115376
12.221305240853255
12.221305240591187
12.221305240329178
12.22130524006722
12.221305239805332
12.221305239543488
12.221305239281705
12.221305239019987
12.221305238758312
12.221305238496702
12.221305238235152
12.221305237973652
12.221305237712203
12.221305237450812
12.221305237189496
12.221305236928215
12.221305236667005
12.221305236405849
12.221305236144746
12.221305235883701
12.221305235622717
12.221305235361779
12.221305235100905
12.221305234840093
12.221305234579336
12.22130523431863
12.221305234057978
12.221305233797377
12.221305233536848
12.221305233276373
12.221305233015945
12.221305232755588
12.221305232495272
12.221305232235022
12.221305231974831
12.22130523171468
12.221305231454606
12.221305231194574
12.22130523093461
12.22130523067468

12.22130523041484
12.22130523015504
12.22130522989529
12.221305229635602
12.221305229375972
12.221305229116393
12.221305228856874
12.221305228597409
12.22130522833801
12.221305228078652
12.221305227819364
12.221305227560125
12.22130522730094
12.221305227041826
12.221305226782743
12.221305226523736
12.221305226264782
12.221305226005876
12.22130522574704
12.221305225488246
12.22130522522952
12.22130522497084
12.221305224712221
12.221305224453657
12.221305224195152
12.221305223936696
12.221305223678304
12.221305223419971
12.221305223161679
12.221305222903455
12.221305222645286
12.221305222387178
12.221305222129116
12.221305221871106
12.221305221613164
12.221305221355273
12.221305221097445
12.221305220839662
12.221305220581941
12.221305220324272
12.221305220066661
12.221305219809102
12.221305219551608
12.221305219294159
12.221305219036777
12.221305218779447
12.221305218522172
12.221305218264948
12.221305218007782
12.221305217750675
12.221305217493622
12.221305217236633
12.22130521697969
12.221305216722802
12.221305216465966
12.221305216209203
12.22130521595248
12.221305215695825
12.221305215439218
12.221305215182662
12.221305214926167
12.221305214669732
12.221305214413347
12.221305214157024
12.221305213900745
12.221305213644525
12.221305213388368
12.221305213132272
12.221305212876219
12.221305212620225
12.221305212364287
12.221305212108396
12.221305211852572
12.221305211596801
12.221305211341086
12.221305211085426
12.221305210829815
12.22130521057427
12.221305210318771
12.221305210063335
12.22130520980794
12.221305209552614
12.221305209297347
12.221305209042129
12.221305208786966
12.22130520853186
12.221305208276815
12.221305208021818
12.221305207766875
12.221305207511987
12.221305207257158
12.221305207002386
12.221305206747664
12.221305206492998
12.221305206238387
12.221305205983839
12.221305205729337
12.2213052054749
12.221305205220508
12.221305204966178
12.2213052047119
12.221305204457675
12.221305204203508
12.221305203949406
12.22130520369534
12.22130520344134
12.221305203187386
12.221305202933502
12.221305202679666
12.221305202425887
12.22130520217215
12.221305201918492
12.221305201664876
12.221305201411308
12.221305201157808
12.221305200904363
12.221305200650955
12.221305200397614
12.221305200144327
12.221305199891091
12.221305199637932
12.221305199384801
12.221305199131745
12.22130519887873
12.221305198625771
12.221305198372873
12.221305198120023
12.221305197867231
12.2213051976145
12.221305197361817
12.22130519710919
12.221305196856614
12.221305196604105
12.221305196351638
12.221305196099234
12.22130519584687
12.221305195594576
12.221305195342335
12.22130519509015
12.221305194838015
12.221305194585934
12.221305194333905
12.221305194081937
12.221305193830025
12.221305193578166
12.22130519332636
12.221305193074606
12.221305192822909
12.221305192571268
12.221305192319685
12.221305192068153
12.221305191816674
12.221305191565246
12.221305191313872
12.221305191062568
12.221305190811306
12.221305190560093
12.221305190308946
12.221305190057858
12.22130518980681
12.221305189555826
12.221305189304887
12.221305189054021
12.221305188803191
12.221305188552424
12.221305188301704
12.221305188051048
12.221305187800445
12.2213051875499
12.221305187299398
12.221305187048952
12.221305186798558
12.221305186548225
12.221305186297949
12.221305186047724
12.221305185797547
12.221305185547434
12.221305185297368
12.221305185047367
12.221305184797416
12.221305184547512
12.221305184297663
12.22130518404788
12.221305183798131
12.221305183548456
12.221305183298822
12.221305183049255
12.221305182799732
12.221305182550262
12.221305182300853
12.221305182051502
12.221305181802192
12.221305181552948
12.221305181303745
12.2213051810546
12.221305180805519
12.221305180556485
12.221305180307505
12.221305180058575
12.221305179809708
12.221305179560888
12.22130517931213
12.22130517906342
12.22130517881476
12.221305178566162
12.221305178317614
12.221305178069121
12.221305177820685
12.221305177572294
12.221305177323963
12.221305177075681
12.221305176827462
12.221305176579289
12.22130517633118
12.221305176083117
12.221305175835102
12.221305175587151
12.221305175339252
12.221305175091402
12.221305174843609
12.221305174595877
12.221305174348183
12.221305174100562
12.22130517385297
12.221305173605453
12.22130517335798
12.221305173110567
12.221305172863195
12.221305172615889
12.22130517236864
12.22130517212144
12.221305171874281
12.221305171627188
12.221305171380155
12.221305171133164
12.221305170886234
12.221305170639342
12.221305170392522
12.221305170145746
12.221305169899031
12.221305169652359
12.221305169405749
12.221305169159189
12.221305168912684
12.221305168666232
12.221305168419828
12.221305168173485
12.221305167927195
12.221305167680962
12.221305167434775
12.22130516718864
12.221305166942566
12.221305166696538
12.221305166450563
12.221305166204653
12.221305165958787
12.22130516571297
12.221305165467223
12.221305165221516
12.221305164975865
12.221305164730262
12.221305164484724
12.221305164239233
12.221305163993794
12.221305163748408
12.221305163503079
12.221305163257801
12.221305163012575
12.221305162767413
12.221305162522286
12.22130516227722
12.221305162032207
12.221305161787251
12.221305161542341
12.221305161297495
12.221305161052697
12.221305160807944
12.22130516056325
12.22130516031862
12.22130516007403
12.221305159829495
12.22130515958501
12.221305159340586
12.221305159096211
12.221305158851893
12.221305158607617
12.221305158363409
12.22130515811924
12.22130515787513
12.221305157631079
12.221305157387082
12.221305157143124
12.22130515689923
12.221305156655383
12.221305156411587
12.221305156167857
12.221305155924174
12.221305155680536
12.221305155436953
12.221305155193424
12.221305154949949
12.221305154706531
12.221305154463149
12.221305154219845
12.221305153976582
12.221305153733374
12.22130515349022
12.221305153247112
12.221305153004057
12.221305152761063
12.221305152518111
12.221305152275223
12.221305152032377
12.221305151789595
12.22130515154686
12.22130515130417
12.221305151061548
12.22130515081897
12.221305150576445
12.221305150333968
12.221305150091549
12.221305149849181
12.221305149606865
12.22130514936461
12.221305149122397
12.22130514888025
12.221305148638136
12.22130514839609
12.221305148154087
12.221305147912137
12.221305147670241
12.22130514742841
12.22130514718661
12.221305146944873
12.221305146703196
12.221305146461562
12.221305146219986
12.221305145978462
12.221305145736984
12.221305145495558
12.221305145254194
12.221305145012877
12.221305144771609
12.221305144530403
12.221305144289241
12.221305144048141
12.221305143807074
12.221305143566076
12.221305143325123
12.221305143084217
12.221305142843377
12.22130514260259
12.221305142361837
12.221305142121153
12.221305141880514
12.221305141639936
12.221305141399398
12.22130514115891
12.221305140918492
12.221305140678108
12.221305140437792
12.221305140197517
12.2213051399573
12.221305139717137
12.221305139477021
12.221305139236952
12.221305138996943
12.221305138756989
12.221305138517076
12.221305138277222
12.221305138037417
12.221305137797676
12.221305137557973
12.221305137318327
12.221305137078732
12.221305136839193
12.221305136599696
12.221305136360257
12.221305136120863
12.221305135881536
12.22130513564226
12.221305135403025
12.221305135163844
12.221305134924721
12.221305134685645
12.221305134446625
12.22130513420765
12.221305133968729
12.221305133729865
12.221305133491049
12.221305133252287
12.221305133013574
12.221305132774908
12.221305132536301
12.221305132297745
12.221305132059243
12.221305131820792
12.221305131582383
12.221305131344037
12.221305131105742
12.221305130867492
12.221305130629299
12.22130513039115
12.221305130153072
12.221305129915033
12.22130512967703
12.221305129439099
12.221305129201214
12.221305128963383
12.221305128725607
12.221305128487879
12.221305128250197
12.221305128012572
12.221305127775
12.221305127537468
12.221305127300003
12.22130512706258
12.22130512682521
12.2213051265879
12.221305126350632
12.221305126113414
12.221305125876256
12.221305125639155
12.221305125402088
12.221305125165076
12.221305124928111
12.221305124691215
12.22130512445436
12.221305124217565
12.221305123980805
12.221305123744111
12.221305123507461
12.221305123270861
12.221305123034309
12.221305122797824
12.221305122561375
12.221305122324983
12.221305122088642
12.221305121852359
12.221305121616115
12.221305121379938
12.221305121143795
12.221305120907711
12.221305120671683
12.221305120435703
12.221305120199771
12.22130511996389
12.221305119728065
12.221305119492282
12.221305119256565
12.221305119020885
12.221305118785265
12.221305118549695
12.221305118314167
12.221305118078696
12.221305117843277
12.221305117607914
12.221305117372593
12.221305117137334
12.22130511690212
12.22130511666695
12.221305116431843
12.221305116196785
12.221305115961764
12.22130511572681
12.221305115491903
12.221305115257048
12.221305115022243
12.221305114787489
12.221305114552782
12.221305114318124
12.221305114083528
12.22130511384898
12.221305113614475
12.221305113380021
12.221305113145624
12.221305112911276
12.221305112676987
12.221305112442733
12.221305112208542
12.221305111974392
12.2213051117403
12.221305111506252
12.22130511127226
12.22130511103832
12.221305110804426
12.221305110570597
12.221305110336798
12.22130511010307
12.221305109869379
12.22130510963574
12.22130510940216
12.221305109168622
12.221305108935134
12.22130510870171
12.221305108468314
12.221305108234986
12.2213051080017
12.221305107768476
12.221305107535294
12.221305107302163
12.221305107069083
12.221305106836054
12.221305106603076
12.221305106370147
12.221305106137278
12.221305105904445
12.221305105671666
12.221305105438935
12.221305105206268
12.221305104973641
12.221305104741067
12.221305104508543
12.22130510427607
12.221305104043655
12.221305103811272
12.221305103578953
12.221305103346683
12.221305103114464
12.221305102882287
12.221305102650176
12.221305102418098
12.221305102186083
12.22130510195411
12.221305101722193
12.221305101490326
12.221305101258508
12.221305101026749
12.221305100795018
12.221305100563344
12.221305100331742
12.221305100100174
12.22130509986865
12.221305099637194
12.22130509940577
12.221305099174405
12.221305098943096
12.221305098711825
12.221305098480608
12.221305098249447
12.22130509801833
12.221305097787262
12.221305097556245
12.221305097325285
12.221305097094374
12.221305096863508
12.221305096632697
12.221305096401936
12.22130509617122
12.221305095940554

12.221305095709937
12.221305095479376
12.221305095248859
12.221305095018408
12.22130509478799
12.22130509455762
12.221305094327315
12.221305094097048
12.22130509386683
12.221305093636673
12.221305093406563
12.221305093176495
12.221305092946482
12.221305092716516
12.221305092486602
12.221305092256733
12.221305092026922
12.221305091797161
12.221305091567451
12.221305091337781
12.221305091108167
12.221305090878605
12.221305090649086
12.221305090419621
12.221305090190208
12.221305089960838
12.22130508973153
12.221305089502259
12.221305089273043
12.221305089043872
12.22130508881476
12.221305088585689
12.221305088356672
12.221305088127707
12.22130508789879
12.221305087669924
12.221305087441106
12.221305087212338
12.22130508698362
12.221305086754946
12.221305086526323
12.221305086297756
12.221305086069236
12.221305085840768
12.221305085612345
12.221305085383964
12.221305085155645
12.221305084927375
12.221305084699155
12.22130508447098
12.221305084242859
12.221305084014773
12.221305083786755
12.221305083558786
12.221305083330856
12.221305083102978
12.221305082875153
12.22130508264738
12.221305082419644
12.221305082191964
12.221305081964339
12.221305081736759
12.221305081509222
12.221305081281747
12.22130508105431
12.221305080826928
12.221305080599596
12.221305080372312
12.221305080145083
12.22130507991789
12.221305079690756
12.221305079463674
12.221305079236629
12.221305079009639
12.221305078782704
12.221305078555817
12.221305078328978
12.22130507810219
12.221305077875437
12.22130507764875
12.221305077422103
12.221305077195513
12.22130507696897
12.221305076742473
12.221305076516035
12.221305076289632
12.221305076063281
12.221305075836977
12.221305075610733
12.221305075384528
12.221305075158373
12.221305074932271
12.221305074706217
12.221305074480213
12.22130507425426
12.221305074028363
12.221305073802501
12.221305073576687
12.221305073350928
12.221305073125217
12.221305072899552
12.221305072673943
12.22130507244838
12.221305072222869
12.221305071997408
12.221305071771988
12.221305071546618
12.221305071321297
12.22130507109603
12.22130507087081
12.221305070645638
12.221305070420515
12.221305070195438
12.221305069970409
12.221305069745439
12.221305069520506
12.221305069295633
12.221305069070802
12.221305068846013
12.22130506862128
12.2213050683966
12.221305068171963
12.22130506794738
12.22130506772284
12.221305067498351
12.221305067273914
12.22130506704951
12.221305066825176
12.221305066600873
12.221305066376637
12.221305066152436
12.22130506592829
12.221305065704195
12.221305065480136
12.221305065256137
12.221305065032189
12.22130506480828
12.221305064584426
12.221305064360616
12.221305064136853
12.221305063913142
12.22130506368948
12.221305063465874
12.221305063242305
12.221305063018791
12.22130506279532
12.221305062571895
12.221305062348526
12.221305062125209
12.22130506190193
12.221305061678711
12.22130506145553
12.221305061232409
12.221305061009321
12.221305060786285
12.221305060563308
12.221305060340372
12.221305060117485
12.221305059894643
12.221305059671854
12.221305059449122
12.221305059226426
12.221305059003784
12.221305058781178
12.221305058558633
12.221305058336137
12.221305058113678
12.221305057891279
12.221305057668918
12.221305057446614
12.221305057224365
12.221305057002144
12.221305056779991
12.22130505655788
12.221305056335797
12.22130505611379
12.221305055891822
12.2213050556699
12.22130505544803
12.221305055226201
12.221305055004423
12.2213050547827
12.221305054561013
12.221305054339382
12.221305054117796
12.221305053896263
12.221305053674772
12.221305053453342
12.22130505323194
12.221305053010598
12.221305052789303
12.221305052568058
12.22130505234686
12.221305052125699
12.2213050519046
12.221305051683546
12.221305051462533
12.22130505124158
12.22130505102067
12.221305050799803
12.221305050578994
12.221305050358215
12.221305050137495
12.221305049916825
12.221305049696202
12.221305049475625
12.221305049255097
12.221305049034623
12.22130504881418
12.221305048593804
12.221305048373466
12.221305048153173
12.221305047932933
12.221305047712745
12.2213050474926
12.221305047272491
12.221305047052441
12.221305046832445
12.221305046612487
12.221305046392581
12.221305046172725
12.221305045952905
12.221305045733144
12.221305045513432
12.221305045293757
12.221305045074137
12.221305044854573
12.221305044635042
12.221305044415562
12.22130504419613
12.221305043976747
12.221305043757416
12.221305043538127
12.221305043318885
12.221305043099703
12.221305042880559
12.22130504266146
12.2213050424424
12.22130504222341
12.221305042004445
12.221305041785545
12.221305041566689
12.221305041347875
12.221305041129112
12.221305040910387
12.221305040691725
12.221305040473101
12.221305040254522
12.221305040036
12.22130503981752
12.22130503959909
12.221305039380706
12.221305039162372
12.221305038944077
12.221305038725829
12.221305038507637
12.221305038289486
12.221305038071389
12.221305037853337
12.22130503763533
12.221305037417382
12.221305037199462
12.221305036981594
12.221305036763788
12.221305036546012
12.22130503632828
12.22130503611061
12.221305035892989
12.221305035675407
12.221305035457872
12.221305035240391
12.221305035022946
12.221305034805555
12.221305034588212
12.221305034370918
12.221305034153668
12.221305033936467
12.221305033719306
12.221305033502192
12.221305033285137
12.221305033068116
12.221305032851154
12.221305032634234
12.221305032417362
12.221305032200533
12.221305031983762
12.221305031767026
12.22130503155034
12.221305031333701
12.221305031117108
12.22130503090057
12.221305030684071
12.221305030467624
12.221305030251218
12.221305030034863
12.221305029818549
12.221305029602282
12.221305029386068
12.221305029169908
12.221305028953783
12.221305028737714
12.221305028521684
12.221305028305705
12.221305028089768
12.221305027873884
12.221305027658042
12.221305027442245
12.221305027226508
12.221305027010803
12.221305026795154
12.221305026579543
12.221305026363986
12.221305026148471
12.221305025933015
12.221305025717593
12.22130502550222
12.221305025286894
12.221305025071619
12.221305024856392
12.221305024641207
12.221305024426059
12.221305024210977
12.221305023995924
12.221305023780925
12.221305023565973
12.22130502335107
12.22130502313621
12.221305022921406
12.221305022706634
12.221305022491922
12.221305022277244
12.221305022062616
12.221305021848048
12.221305021633508
12.221305021419028
12.221305021204586
12.221305020990195
12.221305020775853
12.221305020561546
12.221305020347296
12.221305020133093
12.221305019918933
12.221305019704822
12.221305019490751
12.221305019276732
12.22130501906276
12.221305018848831
12.22130501863495
12.221305018421116
12.221305018207321
12.221305017993581
12.221305017779885
12.221305017566232
12.221305017352643
12.221305017139084
12.221305016925577
12.221305016712105
12.221305016498691
12.22130501628532
12.221305016071993
12.221305015858725
12.22130501564548
12.221305015432304
12.221305015219166
12.221305015006068
12.221305014793021
12.221305014580022
12.221305014367065
12.221305014154147
12.221305013941302
12.221305013728479
12.221305013515718
12.221305013302983
12.221305013090312
12.221305012877682
12.221305012665095
12.221305012452557
12.221305012240066
12.221305012027612
12.221305011815218
12.221305011602865
12.221305011390545
12.221305011178291
12.22130501096607
12.221305010753898
12.22130501054178
12.221305010329697
12.221305010117673
12.221305009905691
12.221305009693749
12.221305009481854
12.221305009270004
12.2213050090582
12.221305008846445
12.221305008634731
12.221305008423075
12.221305008211457
12.22130500799988
12.221305007788354
12.221305007576872
12.221305007365432
12.221305007154056
12.22130500694271
12.221305006731411
12.221305006520161
12.221305006308949
12.221305006097799
12.221305005886682
12.221305005675621
12.221305005464593
12.221305005253624
12.221305005042685
12.221305004831796
12.221305004620966
12.221305004410178
12.22130500419943
12.221305003988723
12.221305003778067
12.221305003567455
12.221305003356893
12.22130500314638
12.221305002935903
12.221305002725476
12.221305002515102
12.22130500230476
12.22130500209447
12.221305001884225
12.221305001674027
12.22130500146387
12.221305001253766
12.221305001043701
12.221305000833693
12.221305000623717
12.221305000413789
12.22130500020391
12.221304999994071
12.221304999784287
12.22130499957455
12.221304999364843
12.221304999155201
12.221304998945588
12.221304998736038
12.221304998526513
12.221304998317038
12.221304998107618
12.22130499789824
12.221304997688906
12.22130499747962
12.221304997270376
12.221304997061177
12.221304996852025
12.221304996642916
12.221304996433862
12.221304996224836
12.221304996015869

12.22130499580695
12.221304995598063
12.221304995389236
12.221304995180443
12.221304994971698
12.221304994762995
12.221304994554348
12.221304994345743
12.221304994137183
12.221304993928658
12.221304993720183
12.221304993511758
12.221304993303374
12.221304993095044
12.221304992886747
12.221304992678503
12.221304992470305
12.22130499226215
12.221304992054042
12.221304991845969
12.221304991637949
12.22130499142998
12.221304991222047
12.22130499101416
12.221304990806331
12.221304990598531
12.221304990390783
12.22130499018308
12.221304989975422
12.221304989767802
12.221304989560235
12.22130498935271
12.221304989145233
12.221304988937801
12.221304988730408
12.221304988523064
12.221304988315765
12.221304988108516
12.221304987901307
12.221304987694143
12.221304987487017
12.221304987279952
12.221304987072916
12.221304986865938
12.221304986658987
12.221304986452104
12.221304986245253
12.221304986038449
12.221304985831685
12.221304985624972
12.221304985418305
12.22130498521168
12.221304985005101
12.221304984798563
12.221304984592065
12.221304984385633
12.221304984179222
12.22130498397287
12.221304983766556
12.221304983560294
12.221304983354068
12.221304983147887
12.221304982941755
12.221304982735674
12.221304982529636
12.221304982323627
12.22130498211768
12.221304981911775
12.221304981705913
12.221304981500092
12.221304981294312
12.221304981088585
12.221304980882897
12.221304980677264
12.221304980471661
12.221304980266108
12.2213049800606
12.221304979855145
12.221304979649721
12.221304979444357
12.221304979239024
12.221304979033741
12.2213049788285
12.221304978623305
12.22130497841816
12.221304978213055
12.221304978007993
12.221304977802976
12.221304977598
12.221304977393075
12.221304977188188
12.221304976983348
12.221304976778558
12.221304976573803
12.221304976369101
12.221304976164438
12.221304975959827
12.221304975755254
12.221304975550728
12.221304975346237
12.221304975141804
12.221304974937414
12.221304974733055
12.221304974528755
12.22130497432449
12.221304974120274
12.221304973916098
12.221304973711975
12.221304973507891
12.22130497330385
12.221304973099858
12.221304972895904
12.221304972691996
12.221304972488136
12.221304972284319
12.221304972080537
12.22130497187681
12.221304971673122
12.221304971469479
12.221304971265885
12.221304971062336
12.221304970858823
12.22130497065536
12.221304970451932
12.221304970248559
12.22130497004523
12.221304969841944
12.2213049696387
12.221304969435497
12.221304969232344
12.221304969029239
12.221304968826166
12.221304968623135
12.221304968420158
12.221304968217227
12.22130496801433
12.221304967811486
12.221304967608681
12.221304967405922
12.221304967203212
12.221304967000535
12.22130496679791
12.221304966595323
12.221304966392786
12.221304966190283
12.221304965987843
12.221304965785432
12.221304965583071
12.221304965380748
12.221304965178465
12.221304964976241
12.221304964774056
12.22130496457191
12.221304964369805
12.221304964167745
12.221304963965746
12.221304963763773
12.221304963561847
12.221304963359973
12.221304963158126
12.221304962956333
12.221304962754584
12.221304962552878
12.221304962351212
12.2213049621496
12.221304961948023
12.221304961746496
12.221304961545004
12.221304961343561
12.22130496114216
12.221304960940802
12.221304960739493
12.221304960538227
12.221304960337003
12.221304960135821
12.221304959934681
12.221304959733581
12.221304959532535
12.221304959331535
12.221304959130565
12.221304958929649
12.221304958728776
12.22130495852794
12.221304958327156
12.221304958126412
12.221304957925707
12.221304957725048
12.221304957524433
12.221304957323868
12.221304957123346
12.22130495692286
12.221304956722417
12.221304956522017
12.221304956321664
12.221304956121358
12.221304955921092
12.221304955720873
12.221304955520685
12.22130495532055
12.221304955120461
12.221304954920418
12.221304954720406
12.221304954520447
12.221304954320532
12.221304954120647
12.221304953920816
12.221304953721033
12.22130495352128
12.221304953321582
12.221304953121926
12.221304952922306
12.221304952722742
12.221304952523205
12.221304952323727
12.221304952124276
12.221304951924882
12.22130495172553
12.22130495152622
12.221304951326951
12.221304951127724
12.22130495092855
12.221304950729404
12.221304950530307
12.221304950331254
12.221304950132243
12.221304949933275
12.22130494973435
12.221304949535478
12.221304949336636
12.221304949137847
12.22130494893909
12.221304948740393
12.221304948541713
12.221304948343104
12.221304948144516
12.22130494794599
12.221304947747504
12.221304947549045
12.22130494735064
12.221304947152278
12.221304946953959
12.221304946755682
12.22130494655745
12.22130494635927
12.221304946161112
12.221304945963006
12.221304945764944
12.22130494556693
12.22130494536896
12.221304945171028
12.221304944973133
12.22130494477529
12.221304944577486
12.221304944379723
12.221304944182007
12.22130494398433
12.221304943786699
12.22130494358911
12.221304943391566
12.221304943194053
12.221304942996602
12.221304942799188
12.221304942601803
12.221304942404473
12.221304942207194
12.221304942009944
12.22130494181274
12.221304941615578
12.221304941418463
12.221304941221389
12.221304941024352
12.221304940827364
12.221304940630425
12.221304940433518
12.22130494023666
12.221304940039836
12.221304939843062
12.22130493964633
12.221304939449638
12.22130493925299
12.221304939056385
12.221304938859827
12.221304938663298
12.221304938466826
12.221304938270391
12.221304938074002
12.221304937877647
12.22130493768134
12.221304937485082
12.221304937288865
12.22130493709268
12.221304936896543
12.22130493670045
12.221304936504405
12.221304936308394
12.22130493611243
12.221304935916505
12.221304935720626
12.221304935524788
12.221304935328998
12.221304935133238
12.221304934937528
12.22130493474186
12.221304934546227
12.22130493435065
12.221304934155107
12.221304933959603
12.221304933764156
12.221304933568744
12.221304933373371
12.221304933178043
12.221304932982749
12.221304932787511
12.22130493259231
12.221304932397146
12.221304932202042
12.22130493200696
12.221304931811929
12.22130493161694
12.221304931421988
12.221304931227085
12.221304931032218
12.221304930837404
12.221304930642619
12.221304930447886
12.221304930253188
12.221304930058542
12.221304929863933
12.221304929669364
12.22130492947484
12.221304929280357
12.221304929085925
12.221304928891518
12.22130492869716
12.221304928502848
12.22130492830858
12.221304928114344
12.221304927920162
12.221304927726022
12.221304927531909
12.221304927337853
12.221304927143835
12.221304926949859
12.221304926755924
12.221304926562027
12.221304926368184
12.221304926174374
12.221304925980611
12.22130492578688
12.221304925593198
12.22130492539956
12.22130492520596
12.221304925012412
12.221304924818888
12.221304924625418
12.22130492443199
12.221304924238602
12.221304924045254
12.221304923851953
12.22130492365869
12.221304923465466
12.221304923272289
12.221304923079161
12.221304922886057
12.221304922693015
12.221304922499995
12.221304922307032
12.221304922114104
12.221304921921213
12.221304921728375
12.221304921535573
12.221304921342815
12.221304921150098
12.221304920957428
12.221304920764785
12.221304920572207
12.221304920379644
12.221304920187137
12.221304919994667
12.221304919802247
12.221304919609864
12.221304919417522
12.221304919225222
12.221304919032963
12.221304918840751
12.221304918648576
12.221304918456434
12.221304918264353
12.221304918072306
12.221304917880294
12.221304917688322
12.221304917496404
12.221304917304522
12.221304917112676
12.221304916920882
12.221304916729125
12.22130491653741
12.221304916345728
12.221304916154095
12.22130491596251
12.221304915770958
12.221304915579454
12.221304915387988
12.221304915196558
12.221304915005177
12.221304914813826
12.22130491462253
12.221304914431276
12.221304914240058
12.221304914048876
12.221304913857745
12.221304913666648
12.221304913475603
12.221304913284587
12.221304913093629
12.221304912902701
12.221304912711812
12.221304912520965
12.221304912330167
12.221304912139406
12.221304911948685
12.221304911758008
12.221304911567367
12.221304911376773
12.22130491118621
12.221304910995705
12.221304910805229
12.221304910614807
12.22130491042441
12.221304910234075
12.221304910043761
12.221304909853501
12.22130490966327
12.22130490947309
12.22130490928294
12.221304909092842
12.221304908902793
12.221304908712776
12.221304908522798
12.221304908332865
12.221304908142969
12.221304907953119
12.221304907763304
12.221304907573533
12.221304907383805
12.221304907194119
12.221304907004471
12.221304906814863
12.221304906625301
12.22130490643578
12.2213049062463
12.221304906056861
12.221304905867454
12.221304905678096
12.221304905488777
12.221304905299505
12.22130490511027
12.221304904921075
12.221304904731923
12.221304904542805
12.221304904353735
12.221304904164707
12.221304903975714
12.221304903786772
12.221304903597861
12.221304903408992
12.22130490322017
12.221304903031394
12.221304902842649
12.221304902653939
12.221304902465281
12.22130490227666
12.221304902088082
12.221304901899549
12.22130490171105
12.221304901522593
12.22130490133417
12.221304901145801
12.221304900957463
12.221304900769178
12.221304900580922
12.221304900392715
12.221304900204542
12.221304900016417
12.22130489982833
12.221304899640279
12.221304899452267
12.221304899264307
12.221304899076378
12.22130489888849
12.221304898700645
12.221304898512845
12.221304898325087
12.221304898137358
12.22130489794968
12.221304897762037
12.22130489757444
12.221304897386874
12.221304897199367
12.221304897011887
12.22130489682445
12.22130489663705
12.2213048964497
12.221304896262382

12.221304896075114
12.221304895887878
12.221304895700692
12.221304895513537
12.221304895326421
12.221304895139351
12.22130489495232
12.22130489476533
12.221304894578383
12.221304894391475
12.221304894204604
12.221304894017774
12.221304893831
12.221304893644254
12.221304893457548
12.221304893270878
12.221304893084252
12.221304892897674
12.221304892711125
12.22130489252461
12.221304892338159
12.221304892151736
12.221304891965355
12.22130489177902
12.221304891592712
12.221304891406458
12.221304891220235
12.22130489103406
12.221304890847918
12.221304890661814
12.22130489047576
12.221304890289737
12.221304890103765
12.221304889917823
12.221304889731925
12.221304889546069
12.221304889360258
12.22130488917448
12.22130488898874
12.221304888803044
12.221304888617393
12.221304888431778
12.22130488824621
12.221304888060667
12.221304887875176
12.221304887689723
12.22130488750431
12.221304887318942
12.221304887133611
12.221304886948312
12.221304886763063
12.221304886577846
12.221304886392678
12.221304886207545
12.22130488602246
12.22130488583741
12.221304885652394
12.22130488546742
12.22130488528249
12.221304885097604
12.221304884912753
12.221304884727935
12.221304884543168
12.22130488435844
12.22130488417375
12.221304883989106
12.22130488380449
12.221304883619922
12.221304883435389
12.2213048832509
12.221304883066452
12.221304882882048
12.22130488269767
12.221304882513339
12.221304882329049
12.221304882144803
12.221304881960595
12.221304881776431
12.221304881592298
12.221304881408201
12.221304881224153
12.221304881040144
12.22130488085617
12.221304880672252
12.221304880488356
12.221304880304501
12.221304880120698
12.221304879936927
12.221304879753195
12.221304879569507
12.221304879385853
12.221304879202249
12.22130487901867
12.221304878835141
12.22130487865165
12.221304878468198
12.221304878284787
12.22130487810141
12.221304877918081
12.221304877734791
12.221304877551535
12.22130487736833
12.221304877185155
12.22130487700202
12.221304876818921
12.221304876635873
12.221304876452855
12.221304876269883
12.221304876086947
12.221304875904059
12.221304875721195
12.221304875538381
12.221304875355612
12.221304875172871
12.221304874990178
12.221304874807519
12.2213048746249
12.22130487444233
12.221304874259785
12.221304874077283
12.221304873894834
12.221304873712409
12.221304873530032
12.22130487334769
12.221304873165394
12.221304872983135
12.221304872800907
12.221304872618722
12.22130487243659
12.221304872254484
12.221304872072418
12.221304871890398
12.221304871708416
12.221304871526469
12.221304871344563
12.221304871162705
12.221304870980871
12.22130487079909
12.22130487061734
12.22130487043563
12.221304870253963
12.221304870072334
12.221304869890742
12.221304869709192
12.221304869527682
12.221304869346215
12.221304869164785
12.221304868983395
12.221304868802045
12.221304868620724
12.221304868439447
12.221304868258215
12.221304868077018
12.221304867895858
12.221304867714748
12.221304867533672
12.22130486735263
12.221304867171629
12.22130486699067
12.221304866809753
12.22130486662887
12.221304866448028
12.221304866267218
12.22130486608646
12.22130486590574
12.221304865725054
12.221304865544402
12.2213048653638
12.22130486518323
12.2213048650027
12.221304864822214
12.221304864641764
12.221304864461356
12.221304864280988
12.221304864100652
12.221304863920357
12.221304863740105
12.22130486355989
12.22130486337971
12.221304863199578
12.221304863019482
12.221304862839428
12.221304862659398
12.221304862479418
12.221304862299478
12.22130486211957
12.221304861939718
12.221304861759888
12.221304861580103
12.22130486140036
12.221304861220654
12.221304861040979
12.221304860861354
12.221304860681762
12.221304860502217
12.221304860322707
12.221304860143226
12.221304859963787
12.221304859784398
12.221304859605047
12.221304859425722
12.221304859246445
12.221304859067207
12.221304858887999
12.221304858708839
12.221304858529722
12.22130485835064
12.221304858171585
12.221304857992592
12.22130485781362
12.221304857634696
12.221304857455802
12.221304857276943
12.221304857098144
12.221304856919366
12.221304856740634
12.221304856561936
12.221304856383279
12.221304856204661
12.221304856026075
12.221304855847539
12.22130485566903
12.221304855490578
12.221304855312146
12.221304855133768
12.221304854955418
12.221304854777111
12.221304854598847
12.221304854420602
12.221304854242417
12.221304854064263
12.221304853886151
12.221304853708073
12.221304853530027
12.221304853352034
12.221304853174075
12.221304852996154
12.221304852818271
12.221304852640422
12.221304852462618
12.221304852284856
12.221304852107119
12.221304851929428
12.22130485175178
12.221304851574168
12.221304851396598
12.221304851219061
12.221304851041563
12.221304850864103
12.221304850686682
12.221304850509302
12.221304850331958
12.221304850154654
12.221304849977386
12.221304849800157
12.221304849622971
12.221304849445819
12.22130484926871
12.221304849091634
12.221304848914594
12.221304848737603
12.221304848560644
12.22130484838372
12.221304848206842
12.22130484803
12.221304847853194
12.221304847676429
12.221304847499702
12.221304847323003
12.22130484714635
12.22130484696974
12.221304846793162
12.221304846616631
12.221304846440136
12.221304846263672
12.22130484608725
12.221304845910863
12.221304845734522
12.221304845558212
12.221304845381944
12.221304845205722
12.221304845029517
12.22130484485338
12.221304844677254
12.221304844501175
12.221304844325141
12.221304844149138
12.221304843973178
12.221304843797261
12.221304843621361
12.221304843445516
12.221304843269703
12.221304843093934
12.221304842918206
12.221304842742502
12.221304842566855
12.221304842391229
12.22130484221565
12.221304842040102
12.221304841864603
12.221304841689138
12.221304841513708
12.221304841338315
12.221304841162963
12.221304840987646
12.221304840812369
12.221304840637131
12.221304840461928
12.221304840286766
12.221304840111642
12.221304839936556
12.221304839761501
12.221304839586493
12.22130483941153
12.221304839236591
12.221304839061698
12.221304838886839
12.221304838712019
12.221304838537232
12.221304838362483
12.221304838187782
12.221304838013117
12.22130483783848
12.221304837663896
12.22130483748933
12.221304837314811
12.221304837140336
12.221304836965894
12.221304836791486
12.221304836617131
12.2213048364428
12.221304836268509
12.221304836094255
12.221304835920044
12.221304835745865
12.221304835571727
12.221304835397625
12.221304835223552
12.221304835049535
12.221304834875548
12.221304834701595
12.221304834527686
12.221304834353813
12.221304834179978
12.221304834006176
12.221304833832413
12.221304833658689
12.221304833485004
12.221304833311352
12.221304833137744
12.22130483296418
12.221304832790645
12.221304832617141
12.221304832443682
12.221304832270262
12.221304832096871
12.221304831923527
12.221304831750224
12.221304831576942
12.221304831403712
12.221304831230514
12.221304831057362
12.221304830884238
12.221304830711157
12.221304830538113
12.221304830365106
12.22130483019213
12.221304830019198
12.2213048298463
12.221304829673445
12.221304829500621
12.221304829327837
12.221304829155097
12.221304828982385
12.221304828809716
12.221304828637072
12.221304828464485
12.221304828291924
12.221304828119404
12.221304827946918
12.221304827774478
12.221304827602061
12.221304827429687
12.221304827257354
12.221304827085062
12.221304826912803
12.221304826740585
12.221304826568398
12.221304826396246
12.22130482622414
12.221304826052073
12.22130482588004
12.221304825708037
12.221304825536082
12.221304825364152
12.221304825192266
12.221304825020427
12.221304824848614
12.221304824676835
12.2213048245051
12.221304824333396
12.221304824161733
12.22130482399011
12.221304823818528
12.22130482364698
12.221304823475464
12.221304823303987
12.221304823132558
12.22130482296115
12.221304822789788
12.221304822618459
12.221304822447168
12.221304822275922
12.221304822104704
12.221304821933526
12.221304821762386
12.221304821591279
12.22130482142022
12.22130482124919
12.221304821078196
12.221304820907235
12.221304820736318
12.221304820565438
12.2213048203946
12.221304820223784
12.221304820053016
12.221304819882281
12.221304819711596
12.221304819540922
12.22130481937031
12.221304819199728
12.221304819029173
12.221304818858663
12.22130481868819
12.221304818517758
12.22130481834736
12.221304818176993
12.221304818006665
12.221304817836383
12.221304817666129
12.22130481749591
12.221304817325734
12.221304817155595
12.22130481698549
12.221304816815422
12.221304816645388
12.221304816475406
12.221304816305445
12.221304816135529
12.221304815965647
12.221304815795804
12.221304815625984
12.22130481545622
12.221304815286484
12.221304815116781
12.221304814947121
12.2213048147775
12.221304814607914
12.221304814438364
12.221304814268848
12.221304814099375
12.221304813929931
12.22130481376052
12.221304813591159
12.221304813421828
12.221304813252537
12.221304813083277
12.221304812914065
12.221304812744876
12.221304812575731
12.221304812406617
12.221304812237548
12.221304812068507
12.221304811899511
12.221304811730551
12.221304811561614
12.221304811392733
12.221304811223884
12.221304811055061
12.221304810886284
12.221304810717534
12.221304810548837
12.221304810380158
12.221304810211533
12.221304810042936
12.221304809874368
12.221304809705845
12.221304809537358
12.221304809368915
12.221304809200499
12.221304809032125
12.221304808863776
12.221304808695477
12.22130480852721
12.22130480835898
12.221304808190778
12.221304808022625
12.221304807854507
12.221304807686412
12.221304807518369
12.221304807350352

12.22130480718238
12.221304807014437
12.221304806846538
12.221304806678678
12.22130480651085
12.221304806343047
12.221304806175285
12.22130480600757
12.22130480583988
12.221304805672242
12.221304805504637
12.22130480533706
12.221304805169513
12.221304805002012
12.221304804834544
12.221304804667119
12.22130480449972
12.221304804332368
12.22130480416504
12.221304803997757
12.221304803830519
12.221304803663303
12.221304803496132
12.221304803328987
12.221304803161882
12.221304802994819
12.221304802827794
12.221304802660795
12.221304802493826
12.221304802326918
12.221304802160034
12.221304801993183
12.221304801826367
12.221304801659588
12.221304801492852
12.221304801326143
12.22130480115948
12.221304800992844
12.221304800826255
12.221304800659695
12.221304800493165
12.221304800326683
12.22130480016023
12.221304799993817
12.221304799827436
12.221304799661095
12.221304799494787
12.22130479932851
12.221304799162281
12.221304798996082
12.221304798829927
12.221304798663798
12.221304798497698
12.22130479833165
12.221304798165628
12.221304797999645
12.221304797833701
12.22130479766779
12.221304797501922
12.221304797336082
12.221304797170278
12.221304797004509
12.22130479683878
12.22130479667309
12.221304796507429
12.221304796341808
12.221304796176222
12.221304796010669
12.221304795845159
12.221304795679682
12.221304795514236
12.22130479534883
12.221304795183464
12.221304795018131
12.221304794852824
12.221304794687562
12.221304794522332
12.22130479435715
12.221304794191996
12.221304794026869
12.22130479386178
12.22130479369674
12.221304793531727
12.221304793366743
12.221304793201805
12.221304793036909
12.221304792872036
12.221304792707206
12.221304792542405
12.221304792377644
12.221304792212917
12.221304792048224
12.221304791883572
12.221304791718953
12.22130479155437
12.221304791389825
12.221304791225316
12.22130479106084
12.221304790896399
12.221304790731992
12.221304790567626
12.2213047904033
12.221304790238992
12.22130479007473
12.2213047899105
12.22130478974631
12.221304789582165
12.221304789418037
12.221304789253962
12.221304789089912
12.221304788925897
12.221304788761918
12.221304788597985
12.221304788434072
12.221304788270206
12.22130478810637
12.221304787942568
12.22130478777881
12.22130478761508
12.221304787451388
12.221304787287728
12.22130478712411
12.221304786960529
12.221304786796967
12.221304786633459
12.221304786469977
12.221304786306536
12.221304786143135
12.221304785979761
12.22130478581642
12.221304785653114
12.221304785489853
12.221304785326625
12.221304785163426
12.221304785000267
12.22130478483714
12.221304784674055
12.221304784511007
12.22130478434798
12.221304784185001
12.22130478402205
12.221304783859141
12.221304783696258
12.221304783533418
12.221304783370616
12.221304783207836
12.221304783045102
12.221304782882411
12.22130478271974
12.221304782557112
12.221304782394514
12.22130478223196
12.221304782069438
12.221304781906944
12.221304781744493
12.221304781582077
12.221304781419692
12.221304781257334
12.221304781095029
12.221304780932758
12.221304780770508
12.221304780608303
12.221304780446134
12.221304780283996
12.221304780121894
12.221304779959826
12.221304779797803
12.221304779635805
12.22130477947385
12.221304779311923
12.22130477915003
12.221304778988179
12.22130477882636
12.221304778664573
12.221304778502828
12.221304778341104
12.221304778179425
12.221304778017789
12.221304777856181
12.2213047776946
12.221304777533057
12.221304777371556
12.221304777210088
12.221304777048655
12.221304776887257
12.221304776725892
12.221304776564564
12.22130477640328
12.221304776242011
12.22130477608079
12.221304775919606
12.221304775758442
12.22130477559733
12.221304775436245
12.221304775275197
12.22130477511418
12.2213047749532
12.22130477479226
12.22130477463136
12.221304774470472
12.221304774309642
12.22130477414883
12.221304773988074
12.221304773827331
12.221304773666631
12.22130477350596
12.221304773345336
12.221304773184743
12.221304773024183
12.221304772863656
12.221304772703167
12.221304772542714
12.221304772382297
12.221304772221906
12.22130477206155
12.221304771901236
12.22130477174096
12.22130477158071
12.221304771420499
12.221304771260318
12.221304771100176
12.221304770940074
12.221304770779994
12.221304770619954
12.221304770459948
12.22130477029999
12.221304770140058
12.22130476998015
12.221304769820303
12.221304769660462
12.221304769500666
12.221304769340902
12.221304769181177
12.221304769021485
12.221304768861833
12.221304768702204
12.221304768542627
12.221304768383071
12.221304768223549
12.221304768064067
12.221304767904616
12.221304767745206
12.221304767585831
12.221304767426478
12.221304767267169
12.221304767107895
12.221304766948652
12.221304766789448
12.221304766630276
12.22130476647114
12.221304766312029
12.221304766152969
12.221304765993937
12.22130476583493
12.221304765675974
12.221304765517042
12.221304765358138
12.221304765199276
12.221304765040452
12.22130476488166
12.221304764722898
12.221304764564177
12.221304764405492
12.221304764246836
12.221304764088213
12.221304763929629
12.221304763771082
12.221304763612565
12.22130476345408
12.221304763295631
12.221304763137216
12.221304762978836
12.221304762820493
12.221304762662184
12.22130476250391
12.221304762345659
12.221304762187462
12.221304762029286
12.221304761871142
12.221304761713043
12.221304761554975
12.221304761396933
12.221304761238937
12.221304761080965
12.221304760923037
12.221304760765127
12.22130476060727
12.22130476044944
12.221304760291645
12.221304760133886
12.221304759976153
12.221304759818464
12.221304759660809
12.22130475950318
12.221304759345593
12.221304759188028
12.221304759030515
12.221304758873021
12.221304758715572
12.221304758558142
12.221304758400771
12.221304758243411
12.221304758086102
12.221304757928818
12.221304757771561
12.22130475761435
12.221304757457169
12.221304757300029
12.221304757142908
12.221304756985838
12.221304756828792
12.22130475667178
12.2213047565148
12.221304756357867
12.22130475620095
12.221304756044084
12.221304755887237
12.221304755730433
12.221304755573671
12.22130475541692
12.221304755260222
12.221304755103551
12.221304754946912
12.22130475479032
12.221304754633746
12.22130475447721
12.221304754320716
12.221304754164246
12.221304754007814
12.221304753851417
12.221304753695055
12.221304753538723
12.221304753382437
12.221304753226171
12.22130475306994
12.22130475291375
12.221304752757582
12.22130475260146
12.22130475244537
12.221304752289306
12.22130475213328
12.221304751977291
12.22130475182134
12.221304751665416
12.221304751509523
12.221304751353667
12.221304751197838
12.221304751042053
12.221304750886304
12.221304750730576
12.221304750574895
12.221304750419245
12.221304750263627
12.221304750108038
12.221304749952479
12.221304749796968
12.221304749641487
12.221304749486043
12.221304749330622
12.221304749175236
12.221304749019891
12.221304748864574
12.221304748709292
12.22130474855405
12.221304748398833
12.221304748243652
12.221304748088507
12.221304747933397
12.221304747778316
12.22130474762327
12.221304747468256
12.22130474731327
12.22130474715833
12.22130474700342
12.221304746848542
12.221304746693693
12.221304746538895
12.221304746384112
12.22130474622937
12.221304746074662
12.22130474591998
12.221304745765341
12.22130474561074
12.221304745456159
12.221304745301618
12.22130474514711
12.221304744992635
12.221304744838198
12.221304744683781
12.221304744529421
12.221304744375072
12.221304744220769
12.221304744066488
12.22130474391225
12.221304743758042
12.221304743603863
12.22130474344973
12.22130474329562
12.221304743141548
12.221304742987511
12.221304742833501
12.221304742679532
12.221304742525598
12.221304742371693
12.22130474221782
12.221304742063984
12.221304741910176
12.221304741756406
12.221304741602664
12.22130474144896
12.221304741295288
12.221304741141648
12.221304740988037
12.221304740834467
12.221304740680935
12.221304740527424
12.221304740373958
12.221304740220523
12.22130474006711
12.221304739913741
12.221304739760408
12.221304739607097
12.221304739453826
12.221304739300583
12.221304739147381
12.221304738994204
12.221304738841065
12.221304738687959
12.221304738534895
12.221304738381852
12.221304738228843
12.221304738075874
12.221304737922935
12.221304737770023
12.22130473761715
12.221304737464315
12.221304737311504
12.221304737158732
12.221304737005998
12.22130473685328
12.22130473670061
12.22130473654797
12.22130473639536
12.221304736242784
12.221304736090246
12.22130473593773
12.221304735785262
12.221304735632813

12.221304735480402
12.221304735328031
12.22130473517569
12.221304735023383
12.221304734871099
12.221304734718855
12.22130473456664
12.221304734414463
12.221304734262324
12.22130473411021
12.221304733958135
12.221304733806083
12.22130473365407
12.221304733502087
12.221304733350145
12.221304733198231
12.221304733046349
12.221304732894504
12.221304732742688
12.221304732590907
12.221304732439156
12.221304732287443
12.221304732135756
12.221304731984102
12.221304731832488
12.221304731680897
12.221304731529345
12.221304731377831
12.221304731226343
12.22130473107489
12.221304730923473
12.221304730772083
12.221304730620732
12.22130473046941
12.221304730318115
12.22130473016686
12.22130473001564
12.221304729864451
12.221304729713285
12.221304729562167
12.221304729411079
12.221304729260012
12.221304729108985
12.221304728958001
12.221304728807032
12.221304728656111
12.221304728505213
12.221304728354351
12.221304728203526
12.221304728052719
12.221304727901964
12.221304727751225
12.221304727600527
12.221304727449862
12.221304727299232
12.221304727148626
12.22130472699807
12.221304726847526
12.221304726697026
12.221304726546563
12.221304726396122
12.221304726245709
12.221304726095338
12.221304725945002
12.221304725794695
12.221304725644421
12.221304725494177
12.221304725343964
12.221304725193795
12.221304725043655
12.221304724893539
12.221304724743455
12.221304724593413
12.221304724443396
12.221304724293423
12.221304724143478
12.221304723993557
12.22130472384367
12.221304723693823
12.221304723544002
12.22130472339422
12.221304723244462
12.221304723094743
12.221304722945058
12.221304722795397
12.221304722645776
12.221304722496193
12.221304722346627
12.2213047221971
12.221304722047607
12.221304721898147
12.221304721748721
12.221304721599322
12.221304721449961
12.22130472130062
12.22130472115133
12.221304721002065
12.221304720852828
12.221304720703623
12.221304720554457
12.221304720405323
12.221304720256219
12.221304720107144
12.221304719958102
12.2213047198091
12.221304719660123
12.22130471951118
12.221304719362264
12.221304719213387
12.221304719064543
12.22130471891574
12.221304718766953
12.221304718618207
12.221304718469487
12.221304718320805
12.221304718172153
12.22130471802353
12.221304717874947
12.22130471772639
12.221304717577862
12.221304717429373
12.221304717280919
12.221304717132488
12.221304716984095
12.221304716835737
12.221304716687408
12.22130471653911
12.221304716390843
12.221304716242614
12.221304716094405
12.221304715946248
12.221304715798107
12.221304715649996
12.221304715501926
12.221304715353895
12.221304715205882
12.2213047150579
12.221304714909962
12.221304714762052
12.221304714614165
12.221304714466317
12.221304714318503
12.221304714170726
12.221304714022965
12.221304713875252
12.22130471372756
12.221304713579917
12.221304713432291
12.221304713284704
12.22130471313714
12.221304712989618
12.221304712842112
12.221304712694657
12.221304712547225
12.221304712399826
12.221304712252458
12.221304712105121
12.221304711957824
12.221304711810552
12.221304711663308
12.221304711516108
12.221304711368925
12.221304711221785
12.221304711074671
12.22130471092759
12.221304710780544
12.221304710633527
12.221304710486548
12.221304710339606
12.221304710192681
12.221304710045795
12.22130470989894
12.221304709752106
12.221304709605324
12.22130470945856
12.221304709311827
12.221304709165132
12.22130470901846
12.221304708871836
12.221304708725238
12.221304708578664
12.221304708432129
12.221304708285624
12.22130470813915
12.221304707992708
12.221304707846297
12.221304707699915
12.22130470755357
12.221304707407258
12.22130470726097
12.221304707114719
12.221304706968498
12.22130470682231
12.22130470667616
12.221304706530036
12.221304706383949
12.221304706237879
12.22130470609185
12.22130470594585
12.22130470579988
12.22130470565395
12.221304705508048
12.221304705362169
12.22130470521634
12.221304705070532
12.221304704924757
12.221304704779012
12.22130470463329
12.221304704487624
12.221304704341971
12.221304704196347
12.221304704050766
12.221304703905206
12.221304703759682
12.221304703614193
12.22130470346873
12.221304703323302
12.221304703177907
12.22130470303255
12.221304702887206
12.221304702741907
12.221304702596635
12.221304702451398
12.221304702306188
12.221304702161019
12.22130470201587
12.221304701870757
12.221304701725677
12.221304701580625
12.221304701435608
12.221304701290617
12.221304701145666
12.221304701000744
12.221304700855852
12.221304700710984
12.22130470056616
12.221304700421358
12.22130470027659
12.221304700131858
12.221304699987158
12.221304699842475
12.22130469969784
12.221304699553231
12.221304699408648
12.221304699264104
12.221304699119585
12.221304698975102
12.221304698830652
12.221304698686227
12.221304698541834
12.221304698397475
12.221304698253157
12.22130469810886
12.221304697964584
12.221304697820358
12.221304697676151
12.221304697531984
12.221304697387835
12.22130469724373
12.22130469709966
12.22130469695561
12.221304696811597
12.221304696667612
12.221304696523664
12.22130469637974
12.221304696235851
12.221304696091982
12.221304695948161
12.221304695804372
12.221304695660601
12.221304695516874
12.221304695373165
12.221304695229495
12.221304695085857
12.221304694942248
12.221304694798667
12.221304694655123
12.221304694511618
12.221304694368127
12.221304694224672
12.221304694081248
12.221304693937864
12.221304693794497
12.221304693651168
12.22130469350787
12.22130469336461
12.221304693221368
12.22130469307817
12.221304692934988
12.221304692791854
12.22130469264874
12.221304692505662
12.221304692362617
12.221304692219599
12.221304692076606
12.22130469193365
12.22130469179073
12.221304691647834
12.22130469150497
12.22130469136214
12.221304691219343
12.221304691076567
12.221304690933835
12.221304690791122
12.221304690648438
12.221304690505798
12.221304690363187
12.2213046902206
12.22130469007805
12.22130468993553
12.221304689793042
12.221304689650582
12.221304689508145
12.221304689365747
12.22130468922338
12.221304689081043
12.221304688938734
12.221304688796467
12.221304688654223
12.221304688512008
12.221304688369822
12.221304688227676
12.221304688085555
12.221304687943464
12.2213046878014
12.221304687659376
12.22130468751738
12.221304687375422
12.221304687233477
12.22130468709158
12.221304686949697
12.221304686807859
12.221304686666048
12.221304686524272
12.221304686382522
12.221304686240792
12.221304686099119
12.221304685957453
12.221304685815822
12.221304685674232
12.22130468553266
12.221304685391123
12.221304685249617
12.22130468510814
12.221304684966704
12.221304684825295
12.22130468468391
12.221304684542556
12.221304684401241
12.221304684259948
12.221304684118689
12.221304683977465
12.22130468383626
12.221304683695092
12.22130468355396
12.221304683412848
12.22130468327177
12.221304683130738
12.22130468298972
12.221304682848737
12.22130468270778
12.22130468256686
12.22130468242596
12.221304682285107
12.221304682144273
12.221304682003472
12.221304681862708
12.221304681721971
12.221304681581257
12.221304681440586
12.221304681299936
12.221304681159314
12.221304681018733
12.221304680878177
12.221304680737653
12.221304680597152
12.221304680456694
12.221304680316255
12.221304680175862
12.221304680035484
12.22130467989514
12.221304679754828
12.221304679614544
12.221304679474299
12.221304679334072
12.221304679193889
12.221304679053727
12.221304678913596
12.221304678773496
12.221304678633434
12.221304678493391
12.221304678353386
12.221304678213414
12.221304678073459
12.221304677933542
12.221304677793661
12.221304677653798
12.221304677513984
12.221304677374185
12.22130467723442
12.221304677094684
12.221304676954976
12.221304676815308
12.221304676675667
12.221304676536056
12.221304676396475
12.22130467625692
12.221304676117402
12.221304675977901
12.221304675838445
12.221304675699006
12.221304675559614
12.221304675420242
12.221304675280905
12.221304675141594
12.221304675002305
12.22130467486306
12.22130467472384
12.221304674584642
12.221304674445495
12.221304674306356
12.221304674167262
12.22130467402819
12.221304673889156
12.221304673750144
12.221304673611172
12.22130467347222
12.221304673333306
12.22130467319442
12.221304673055558
12.22130467291673
12.22130467277794
12.221304672639167
12.221304672500432
12.221304672361729
12.221304672223052
12.221304672084399
12.22130467194578
12.221304671807202
12.221304671668644
12.221304671530117
12.221304671391621
12.221304671253158
12.221304671114718
12.221304670976313
12.221304670837942
12.221304670699599
12.221304670561274
12.22130467042299
12.221304670284733
12.221304670146507
12.221304670008314
12.221304669870143
12.221304669732014
12.2213046695939
12.221304669455833
12.221304669317785
12.221304669179762
12.221304669041782
12.221304668903821
12.221304668765898
12.221304668628003
12.22130466849014
12.221304668352305
12.221304668214497
12.221304668076721
12.221304667938972
12.221304667801256
12.221304667663569
12.221304667525906
12.221304667388283
12.221304667250692
12.221304667113117
12.221304666975579
12.221304666838076
12.221304666700595
12.221304666563148
12.221304666425727

12.221304666288347
12.221304666150983
12.221304666013657
12.221304665876348
12.221304665739087
12.22130466560185
12.221304665464638
12.221304665327459
12.221304665190313
12.221304665053191
12.221304664916097
12.221304664779035
12.221304664642009
12.221304664505006
12.221304664368038
12.221304664231088
12.22130466409418
12.221304663957298
12.22130466382045
12.221304663683622
12.221304663546825
12.221304663410068
12.221304663273337
12.221304663136628
12.221304662999955
12.221304662863316
12.221304662726698
12.22130466259011
12.221304662453555
12.22130466231703
12.221304662180536
12.22130466204406
12.221304661907624
12.221304661771217
12.22130466163485
12.221304661498497
12.221304661362172
12.221304661225892
12.22130466108963
12.221304660953397
12.221304660817196
12.221304660681025
12.221304660544883
12.221304660408775
12.22130466027269
12.221304660136635
12.22130466000061
12.221304659864625
12.22130465972867
12.221304659592722
12.221304659456816
12.221304659320934
12.221304659185096
12.221304659049276
12.221304658913489
12.221304658777735
12.221304658642001
12.221304658506309
12.221304658370638
12.221304658234992
12.221304658099386
12.2213046579638
12.221304657828258
12.221304657692729
12.221304657557239
12.221304657421777
12.22130465728634
12.22130465715094
12.221304657015567
12.221304656880221
12.221304656744898
12.221304656609613
12.221304656474352
12.221304656339125
12.221304656203927
12.221304656068757
12.22130465593362
12.22130465579851
12.221304655663422
12.221304655528368
12.221304655393354
12.22130465525836
12.221304655123394
12.221304654988455
12.221304654853554
12.221304654718676
12.221304654583827
12.221304654449012
12.22130465431422
12.22130465417946
12.221304654044728
12.22130465391003
12.221304653775363
12.221304653640718
12.221304653506106
12.22130465337152
12.221304653236968
12.22130465310244
12.221304652967943
12.22130465283348
12.221304652699038
12.221304652564632
12.221304652430247
12.221304652295899
12.221304652161578
12.221304652027293
12.221304651893021
12.221304651758784
12.221304651624584
12.221304651490408
12.22130465135626
12.221304651222145
12.221304651088056
12.221304650954
12.221304650819967
12.221304650685962
12.221304650551996
12.221304650418054
12.221304650284138
12.221304650150252
12.221304650016405
12.221304649882562
12.221304649748774
12.221304649615
12.221304649481262
12.221304649347557
12.221304649213874
12.221304649080226
12.221304648946596
12.221304648813005
12.221304648679437
12.221304648545901
12.221304648412401
12.221304648278917
12.221304648145464
12.221304648012044
12.221304647878656
12.221304647745294
12.221304647611959
12.221304647478648
12.221304647345372
12.221304647212133
12.221304647078908
12.221304646945725
12.221304646812557
12.221304646679434
12.22130464654633
12.221304646413255
12.22130464628022
12.221304646147194
12.221304646014206
12.22130464588125
12.221304645748324
12.221304645615426
12.221304645482551
12.221304645349708
12.221304645216891
12.22130464508411
12.221304644951354
12.221304644818625
12.22130464468592
12.22130464455325
12.221304644420618
12.221304644288004
12.221304644155424
12.221304644022865
12.221304643890338
12.221304643757847
12.221304643625375
12.22130464349294
12.221304643360527
12.22130464322814
12.221304643095783
12.22130464296347
12.221304642831175
12.2213046426989
12.221304642566668
12.221304642434452
12.22130464230227
12.221304642170121
12.221304642037996
12.221304641905895
12.221304641773838
12.221304641641803
12.221304641509791
12.221304641377813
12.221304641245856
12.221304641113933
12.221304640982044
12.22130464085018
12.221304640718339
12.221304640586531
12.221304640454752
12.221304640322998
12.22130464019128
12.221304640059582
12.221304639927915
12.221304639796278
12.221304639664668
12.221304639533086
12.221304639401536
12.221304639270022
12.22130463913853
12.221304639007057
12.22130463887562
12.221304638744204
12.221304638612834
12.221304638481481
12.221304638350155
12.22130463821886
12.221304638087597
12.221304637956356
12.221304637825147
12.221304637693969
12.221304637562817
12.221304637431695
12.2213046373006
12.221304637169537
12.22130463703849
12.221304636907481
12.221304636776505
12.22130463664555
12.22130463651463
12.221304636383731
12.22130463625287
12.221304636122024
12.221304635991208
12.22130463586043
12.221304635729679
12.221304635598948
12.22130463546825
12.221304635337587
12.221304635206943
12.22130463507633
12.221304634945742
12.221304634815189
12.221304634684657
12.221304634554164
12.221304634423694
12.221304634293249
12.221304634162843
12.221304634032446
12.221304633902092
12.221304633771764
12.221304633641468
12.221304633511199
12.22130463338095
12.221304633250735
12.221304633120546
12.221304632990387
12.22130463286026
12.22130463273016
12.221304632600079
12.221304632470034
12.221304632340008
12.221304632210025
12.221304632080065
12.221304631950128
12.221304631820225
12.221304631690343
12.221304631560502
12.221304631430673
12.22130463130088
12.22130463117112
12.22130463104138
12.221304630911671
12.221304630781992
12.22130463065234
12.221304630522718
12.221304630393126
12.22130463026356
12.221304630134014
12.221304630004513
12.221304629875027
12.221304629745568
12.22130462961614
12.221304629486749
12.22130462935737
12.22130462922802
12.221304629098718
12.221304628969428
12.221304628840167
12.221304628710941
12.221304628581732
12.221304628452563
12.221304628323407
12.2213046281943
12.221304628065209
12.221304627936144
12.221304627807113
12.221304627678107
12.221304627549127
12.221304627420173
12.221304627291252
12.221304627162361
12.22130462703349
12.221304626904653
12.221304626775847
12.221304626647065
12.221304626518311
12.221304626389582
12.221304626260885
12.221304626132216
12.221304626003569
12.221304625874954
12.221304625746367
12.221304625617813
12.221304625489285
12.221304625360778
12.221304625232298
12.221304625103855
12.221304624975433
12.221304624847036
12.221304624718679
12.221304624590346
12.22130462446204
12.221304624333756
12.221304624205505
12.221304624077288
12.221304623949077
12.221304623820911
12.221304623692772
12.221304623564668
12.221304623436584
12.221304623308518
12.221304623180485
12.221304623052484
12.221304622924507
12.221304622796564
12.221304622668649
12.221304622540758
12.221304622412895
12.221304622285059
12.221304622157248
12.221304622029475
12.221304621901707
12.22130462177399
12.221304621646299
12.221304621518623
12.221304621390988
12.221304621263373
12.22130462113579
12.221304621008228
12.221304620880703
12.221304620753202
12.221304620625727
12.221304620498268
12.221304620370857
12.221304620243458
12.221304620116099
12.221304619988759
12.221304619861453
12.221304619734177
12.22130461960692
12.221304619479696
12.221304619352496
12.22130461922532
12.221304619098174
12.221304618971057
12.22130461884397
12.221304618716909
12.221304618589885
12.221304618462877
12.221304618335894
12.221304618208942
12.221304618082016
12.221304617955125
12.221304617828263
12.221304617701419
12.221304617574608
12.221304617447823
12.221304617321064
12.221304617194331
12.221304617067632
12.221304616940952
12.221304616814308
12.221304616687693
12.221304616561095
12.221304616434528
12.221304616307997
12.221304616181481
12.221304616055003
12.221304615928545
12.221304615802126
12.22130461567572
12.221304615549334
12.221304615422998
12.221304615296678
12.221304615170387
12.22130461504412
12.221304614917885
12.221304614791682
12.221304614665504
12.22130461453935
12.221304614413215
12.221304614287119
12.221304614161049
12.221304614035011
12.22130461390899
12.221304613782994
12.221304613657034
12.221304613531101
12.221304613405199
12.221304613279317
12.221304613153455
12.22130461302764
12.221304612901834
12.221304612776068
12.221304612650316
12.221304612524603
12.221304612398914
12.221304612273256
12.221304612147625
12.221304612022013
12.22130461189643
12.221304611770883
12.221304611645353
12.221304611519862
12.221304611394386
12.221304611268938
12.221304611143523
12.22130461101813
12.22130461089277
12.221304610767435
12.221304610642134
12.221304610516844
12.221304610391602
12.221304610266369
12.22130461014117
12.221304610015997
12.22130460989085
12.221304609765738
12.221304609640653
12.221304609515583
12.221304609390545
12.221304609265538
12.221304609140558
12.221304609015608
12.221304608890685
12.221304608765776
12.221304608640905
12.221304608516057
12.221304608391232
12.221304608266445
12.221304608141681
12.22130460801694
12.22130460789223
12.221304607767554
12.221304607642892
12.221304607518265
12.221304607393662
12.221304607269085
12.221304607144535
12.221304607020015
12.221304606895519
12.221304606771055
12.221304606646619
12.221304606522201
12.221304606397815
12.221304606273453
12.22130460614912
12.221304606024818
12.221304605900539
12.221304605776282
12.22130460565206
12.221304605527864
12.221304605403697
12.221304605279553
12.221304605155431
12.221304605031344
12.221304604907287
12.22130460478324
12.221304604659242
12.221304604535257
12.221304604411305
12.22130460428737
12.22130460416347
12.22130460403959
12.221304603915748
12.22130460379193
12.221304603668141
12.221304603544365
12.221304603420625
12.22130460329691
12.221304603173229
12.221304603049573
12.221304602925931
12.221304602802327
12.221304602678751
12.221304602555199
12.22130460243168
12.221304602308173
12.221304602184702
12.221304602061261
12.221304601937835
12.221304601814445
12.221304601691084
12.221304601567745
12.221304601444444
12.22130460132115
12.221304601197891
12.22130460107467
12.221304600951466
12.221304600828285
12.221304600705137

12.221304600582007
12.221304600458918
12.22130460033584
12.221304600212797
12.221304600089779
12.22130459996679
12.221304599843831
12.221304599720892
12.221304599597985
12.221304599475104
12.221304599352244
12.221304599229411
12.221304599106611
12.221304598983838
12.221304598861076
12.221304598738364
12.221304598615664
12.221304598492994
12.221304598370343
12.221304598247732
12.221304598125144
12.22130459800258
12.221304597880044
12.221304597757534
12.22130459763504
12.221304597512582
12.221304597390157
12.221304597267757
12.221304597145371
12.22130459702302
12.2213045969007
12.221304596778399
12.221304596656132
12.221304596533889
12.221304596411663
12.221304596289475
12.221304596167315
12.221304596045176
12.221304595923057
12.221304595800978
12.22130459567892
12.22130459555688
12.221304595434878
12.221304595312896
12.221304595190945
12.221304595069022
12.221304594947116
12.221304594825241
12.22130459470339
12.221304594581577
12.221304594459781
12.221304594338012
12.221304594216264
12.221304594094557
12.221304593972862
12.221304593851194
12.22130459372957
12.221304593607961
12.221304593486376
12.221304593364819
12.221304593243289
12.22130459312178
12.221304593000305
12.221304592878848
12.221304592757425
12.221304592636029
12.221304592514658
12.221304592393313
12.221304592271993
12.221304592150696
12.22130459202943
12.22130459190819
12.221304591786975
12.221304591665794
12.221304591544625
12.221304591423484
12.221304591302381
12.221304591181298
12.221304591060244
12.221304590939216
12.221304590818203
12.221304590697239
12.221304590576281
12.221304590455357
12.221304590334453
12.221304590213588
12.221304590092734
12.221304589971913
12.221304589851119
12.221304589730359
12.221304589609616
12.221304589488897
12.221304589368211
12.221304589247545
12.221304589126904
12.221304589006293
12.221304588885713
12.221304588765152
12.22130458864462
12.221304588524113
12.221304588403635
12.22130458828319
12.22130458816275
12.221304588042358
12.221304587921978
12.221304587801637
12.221304587681306
12.221304587561008
12.22130458744073
12.221304587320494
12.221304587200276
12.221304587080086
12.221304586959912
12.221304586839778
12.22130458671966
12.221304586599576
12.221304586479512
12.221304586359473
12.221304586239466
12.221304586119478
12.221304585999523
12.221304585879594
12.221304585759693
12.221304585639805
12.221304585519954
12.221304585400123
12.221304585280327
12.221304585160542
12.221304585040796
12.221304584921073
12.22130458480137
12.221304584681699
12.22130458456206
12.221304584442438
12.22130458432284
12.221304584203278
12.221304584083741
12.221304583964217
12.221304583844733
12.221304583725262
12.221304583605823
12.221304583486416
12.22130458336703
12.22130458324767
12.221304583128324
12.221304583009022
12.221304582889745
12.221304582770482
12.221304582651253
12.221304582532047
12.221304582412865
12.22130458229372
12.221304582174579
12.221304582055483
12.221304581936407
12.221304581817357
12.22130458169834
12.221304581579336
12.221304581460366
12.221304581341418
12.2213045812225
12.221304581103599
12.221304580984727
12.221304580865894
12.221304580747075
12.221304580628281
12.221304580509512
12.22130458039078
12.221304580272056
12.221304580153372
12.221304580034703
12.221304579916067
12.221304579797454
12.221304579678867
12.221304579560314
12.221304579441775
12.22130457932327
12.221304579204785
12.221304579086334
12.221304578967894
12.221304578849496
12.221304578731118
12.221304578612758
12.221304578494433
12.221304578376131
12.22130457825785
12.221304578139598
12.22130457802137
12.221304577903169
12.221304577784997
12.221304577666851
12.221304577548729
12.221304577430637
12.22130457731256
12.22130457719451
12.221304577076495
12.22130457695849
12.221304576840524
12.221304576722577
12.221304576604659
12.221304576486764
12.221304576368906
12.221304576251063
12.221304576133248
12.221304576015452
12.221304575897687
12.221304575779952
12.221304575662236
12.221304575544547
12.22130457542688
12.221304575309244
12.221304575191644
12.221304575074056
12.221304574956493
12.221304574838948
12.221304574721449
12.221304574603955
12.221304574486503
12.22130457436907
12.221304574251665
12.221304574134281
12.221304574016926
12.221304573899596
12.221304573782295
12.221304573665009
12.22130457354776
12.22130457343053
12.22130457331332
12.221304573196146
12.221304573078987
12.221304572961863
12.221304572844758
12.221304572727682
12.221304572610627
12.221304572493604
12.221304572376603
12.221304572259633
12.22130457214268
12.221304572025753
12.221304571908863
12.221304571791983
12.221304571675136
12.221304571558314
12.221304571441514
12.221304571324739
12.221304571207996
12.221304571091272
12.221304570974576
12.221304570857912
12.221304570741264
12.22130457062464
12.221304570508057
12.221304570391474
12.221304570274935
12.221304570158422
12.22130457004192
12.221304569925449
12.221304569809012
12.221304569692593
12.221304569576201
12.221304569459841
12.221304569343499
12.221304569227174
12.221304569110888
12.22130456899462
12.221304568878379
12.221304568762164
12.22130456864597
12.221304568529797
12.221304568413665
12.221304568297548
12.221304568181457
12.221304568065394
12.221304567949353
12.221304567833341
12.221304567717356
12.221304567601393
12.221304567485456
12.221304567369542
12.22130456725365
12.22130456713779
12.22130456702195
12.221304566906138
12.22130456679035
12.221304566674588
12.221304566558851
12.221304566443132
12.221304566327449
12.221304566211781
12.221304566096151
12.221304565980539
12.221304565864951
12.221304565749392
12.221304565633853
12.221304565518349
12.221304565402855
12.221304565287396
12.221304565171957
12.22130456505654
12.221304564941159
12.221304564825797
12.22130456471046
12.221304564595144
12.221304564479864
12.221304564364603
12.221304564249367
12.221304564134158
12.221304564018975
12.221304563903809
12.22130456378867
12.221304563673558
12.22130456355848
12.221304563443407
12.221304563328383
12.221304563213367
12.221304563098379
12.22130456298342
12.221304562868484
12.221304562753573
12.221304562638686
12.221304562523834
12.221304562408992
12.221304562294174
12.221304562179395
12.22130456206463
12.221304561949895
12.221304561835181
12.221304561720492
12.221304561605834
12.221304561491193
12.221304561376579
12.22130456126199
12.221304561147434
12.221304561032893
12.221304560918377
12.221304560803892
12.221304560689422
12.221304560574985
12.221304560460574
12.221304560346189
12.221304560231824
12.221304560117483
12.22130456000317
12.221304559888884
12.221304559774614
12.22130455966038
12.22130455954616
12.221304559431973
12.221304559317812
12.221304559203665
12.221304559089548
12.22130455897546
12.221304558861393
12.221304558747349
12.221304558633339
12.221304558519343
12.221304558405373
12.221304558291429
12.221304558177511
12.221304558063627
12.221304557949754
12.22130455783591
12.221304557722098
12.221304557608295
12.221304557494525
12.221304557380783
12.22130455726706
12.221304557153365
12.221304557039694
12.221304556926052
12.221304556812436
12.22130455669883
12.221304556585256
12.221304556471711
12.221304556358186
12.221304556244693
12.22130455613122
12.22130455601777
12.221304555904343
12.221304555790944
12.221304555677568
12.221304555564217
12.221304555450896
12.221304555337591
12.221304555224306
12.221304555111065
12.221304554997838
12.221304554884627
12.221304554771455
12.221304554658294
12.221304554545167
12.221304554432066
12.221304554318982
12.221304554205926
12.221304554092894
12.22130455397989
12.221304553866904
12.221304553753946
12.22130455364102
12.221304553528107
12.22130455341523
12.221304553302357
12.221304553189528
12.221304553076722
12.221304552963934
12.22130455285117
12.221304552738435
12.221304552625723
12.221304552513033
12.22130455240037
12.221304552287739
12.22130455217512
12.221304552062527
12.221304551949952
12.221304551837422
12.221304551724902
12.221304551612416
12.221304551499937
12.221304551387497
12.221304551275082
12.221304551162683
12.221304551050311
12.22130455093797
12.221304550825641
12.221304550713347
12.221304550601074
12.221304550488826
12.221304550376598
12.221304550264398
12.221304550152222
12.221304550040074
12.221304549927945
12.221304549815839
12.221304549703765
12.221304549591713
12.221304549479687
12.221304549367682
12.221304549255704
12.221304549143742
12.221304549031807
12.221304548919901
12.221304548808016
12.221304548696157
12.221304548584323
12.221304548472506
12.22130454836072
12.221304548248952
12.221304548137214
12.22130454802551
12.22130454791382
12.221304547802154
12.22130454769051
12.221304547578892
12.221304547467302
12.22130454735574
12.221304547244188
12.22130454713267
12.22130454702118
12.221304546909705
12.221304546798253
12.22130454668683
12.221304546575436
12.221304546464069
12.221304546352707
12.221304546241381
12.22130454613008
12.221304546018796
12.221304545907545
12.221304545796313
12.221304545685108
12.221304545573927
12.221304545462768
12.221304545351638
12.221304545240528
12.221304545129438
12.221304545018382
12.221304544907346
12.221304544796332
12.221304544685339
12.221304544574375
12.221304544463433
12.221304544352522
12.22130454424163
12.221304544130758
12.221304544019917
12.221304543909092
12.221304543798295
12.221304543687532
12.221304543576782
12.221304543466054
12.221304543355359
12.221304543244678
12.221304543134021
12.221304543023397
12.221304542912794
12.221304542802217
12.221304542691659
12.22130454258113
12.221304542470614
12.221304542360134
12.22130454224967
12.221304542139244
12.221304542028829
12.221304541918437
12.221304541808072
12.22130454169773
12.22130454158742
12.22130454147713
12.221304541366855
12.221304541256613
12.221304541146386
12.221304541036199
12.22130454092602
12.221304540815872
12.221304540705749
12.221304540595648
12.221304540485571
12.221304540375506
12.22130454026549
12.221304540155476
12.2213045400455
12.221304539935543
12.221304539825608
12.221304539715701
12.22130453960582
12.22130453949595
12.221304539386116
12.221304539276296
12.221304539166509
12.221304539056744
12.221304538946995
12.221304538837275
12.221304538727582
12.221304538617915
12.221304538508264
12.221304538398648
12.221304538289044
12.221304538179464
12.221304538069916
12.221304537960382
12.221304537850878
12.221304537741394
12.221304537631942
12.221304537522506
12.221304537413094

12.22130453730371
12.221304537194342
12.221304537085011
12.22130453697569
12.221304536866398
12.22130453675713
12.221304536647894
12.221304536538673
12.221304536429473
12.221304536320298
12.221304536211152
12.221304536102032
12.221304535992912
12.221304535883851
12.221304535774783
12.221304535665759
12.221304535556753
12.22130453544777
12.221304535338811
12.221304535229875
12.221304535120964
12.22130453501207
12.221304534903213
12.221304534794363
12.221304534685551
12.221304534576753
12.221304534467992
12.221304534359234
12.221304534250514
12.22130453414181
12.221304534033136
12.221304533924483
12.221304533815859
12.221304533707245
12.22130453359867
12.221304533490109
12.221304533381575
12.22130453327307
12.221304533164567
12.221304533056113
12.22130453294767
12.221304532839257
12.221304532730858
12.221304532622492
12.22130453251414
12.22130453240582
12.221304532297522
12.221304532189242
12.221304532080993
12.221304531972768
12.22130453186456
12.22130453175638
12.221304531648222
12.221304531540083
12.221304531431974
12.221304531323879
12.22130453121582
12.22130453110777
12.22130453099976
12.221304530891768
12.221304530783796
12.221304530675841
12.221304530567927
12.221304530460024
12.221304530352151
12.221304530244293
12.221304530136461
12.221304530028657
12.221304529920873
12.221304529813114
12.221304529705371
12.221304529597662
12.221304529489972
12.221304529382307
12.221304529274663
12.221304529167039
12.22130452905945
12.221304528951874
12.221304528844326
12.221304528736795
12.221304528629291
12.221304528521816
12.221304528414358
12.22130452830693
12.221304528199507
12.221304528092128
12.221304527984763
12.221304527877425
12.221304527770108
12.221304527662816
12.221304527555544
12.221304527448302
12.221304527341072
12.22130452723387
12.2213045271267
12.221304527019557
12.221304526912412
12.221304526805316
12.221304526698221
12.221304526591167
12.221304526484127
12.221304526377109
12.221304526270119
12.221304526163149
12.2213045260562
12.221304525949284
12.22130452584239
12.221304525735512
12.221304525628662
12.221304525521836
12.221304525415027
12.221304525308245
12.221304525201488
12.221304525094746
12.221304524988037
12.221304524881345
12.221304524774682
12.221304524668046
12.221304524561425
12.221304524454816
12.221304524348248
12.221304524241697
12.221304524135173
12.221304524028662
12.221304523922184
12.221304523815729
12.221304523709296
12.22130452360288
12.221304523496489
12.221304523390128
12.221304523283782
12.221304523177462
12.221304523071167
12.221304522964894
12.221304522858645
12.221304522752417
12.221304522646212
12.22130452254003
12.22130452243387
12.221304522327737
12.221304522221626
12.221304522115538
12.221304522009467
12.22130452190343
12.221304521797405
12.221304521691417
12.221304521585438
12.221304521479482
12.221304521373554
12.22130452126765
12.221304521161777
12.221304521055911
12.221304520950085
12.22130452084426
12.221304520738473
12.221304520632701
12.22130452052696
12.221304520421231
12.221304520315542
12.221304520209868
12.22130452010422
12.221304519998586
12.221304519892978
12.221304519787399
12.221304519681837
12.221304519576298
12.22130451947078
12.221304519365292
12.221304519259816
12.221304519154376
12.221304519048951
12.221304518943553
12.221304518838176
12.22130451873282
12.22130451862748
12.22130451852218
12.22130451841689
12.221304518311634
12.221304518206386
12.22130451810117
12.221304517995977
12.221304517890808
12.221304517785654
12.221304517680526
12.221304517575428
12.221304517470351
12.221304517365285
12.221304517260254
12.221304517155241
12.221304517050246
12.221304516945281
12.221304516840341
12.221304516735424
12.221304516630527
12.221304516525652
12.22130451642079
12.221304516315955
12.221304516211163
12.221304516106374
12.2213045160016
12.221304515896872
12.221304515792157
12.22130451568746
12.221304515582789
12.221304515478145
12.221304515373511
12.221304515268923
12.221304515164338
12.221304515059781
12.221304514955241
12.221304514850729
12.221304514746242
12.221304514641771
12.221304514537335
12.221304514432909
12.221304514328514
12.221304514224137
12.22130451411978
12.221304514015456
12.221304513911145
12.221304513806865
12.221304513702597
12.221304513598355
12.221304513494138
12.221304513389942
12.221304513285775
12.22130451318162
12.221304513077497
12.221304512973399
12.221304512869308
12.221304512765252
12.221304512661217
12.221304512557206
12.221304512453209
12.22130451234924
12.221304512245295
12.221304512141367
12.22130451203747
12.221304511933596
12.221304511829734
12.221304511725904
12.221304511622089
12.221304511518309
12.22130451141453
12.221304511310793
12.221304511207073
12.221304511103382
12.221304510999701
12.221304510896044
12.221304510792425
12.221304510688805
12.221304510585227
12.221304510481655
12.221304510378111
12.221304510274603
12.221304510171104
12.22130451006763
12.221304509964185
12.221304509860747
12.221304509757342
12.221304509653967
12.221304509550595
12.221304509447265
12.221304509343947
12.221304509240644
12.221304509137374
12.221304509034127
12.2213045089309
12.221304508827698
12.221304508724513
12.221304508621353
12.22130450851822
12.221304508415106
12.221304508312006
12.22130450820895
12.221304508105899
12.221304508002868
12.22130450789986
12.22130450779689
12.221304507693933
12.221304507590991
12.221304507488076
12.221304507385188
12.221304507282317
12.221304507179472
12.221304507076653
12.221304506973848
12.221304506871071
12.221304506768316
12.221304506665575
12.221304506562864
12.221304506460175
12.221304506357507
12.22130450625486
12.221304506152233
12.22130450604963
12.221304505947058
12.221304505844502
12.221304505741964
12.221304505639456
12.221304505536962
12.221304505434487
12.221304505332055
12.221304505229625
12.221304505127224
12.221304505024843
12.221304504922495
12.221304504820152
12.221304504717844
12.221304504615553
12.221304504513288
12.22130450441104
12.221304504308817
12.221304504206616
12.221304504104436
12.221304504002287
12.221304503900146
12.221304503798036
12.221304503695945
12.221304503593878
12.221304503491828
12.221304503389812
12.221304503287802
12.221304503185824
12.22130450308387
12.221304502981932
12.221304502880017
12.221304502778125
12.221304502676258
12.221304502574418
12.221304502472588
12.221304502370781
12.221304502269005
12.22130450216725
12.221304502065514
12.2213045019638
12.221304501862106
12.22130450176043
12.221304501658782
12.221304501557164
12.22130450145556
12.221304501353979
12.221304501252408
12.221304501150877
12.221304501049362
12.221304500947864
12.221304500846397
12.221304500744948
12.22130450064352
12.221304500542116
12.22130450044073
12.221304500339368
12.221304500238032
12.221304500136709
12.221304500035416
12.221304499934138
12.221304499832897
12.221304499731664
12.22130449963045
12.221304499529273
12.221304499428099
12.221304499326965
12.221304499225843
12.221304499124747
12.221304499023672
12.221304498922617
12.221304498821585
12.221304498720576
12.221304498619583
12.221304498518625
12.221304498417684
12.221304498316757
12.221304498215847
12.221304498114973
12.221304498014119
12.221304497913287
12.221304497812469
12.221304497711683
12.221304497610914
12.221304497510163
12.221304497409436
12.221304497308726
12.221304497208049
12.221304497107397
12.22130449700675
12.221304496906138
12.221304496805544
12.22130449670497
12.221304496604423
12.221304496503892
12.221304496403386
12.221304496302896
12.221304496202443
12.221304496102
12.22130449600158
12.221304495901178
12.221304495800798
12.221304495700448
12.221304495600116
12.221304495499801
12.221304495399513
12.221304495299249
12.221304495199002
12.221304495098774
12.221304494998572
12.2213044948984
12.221304494798238
12.221304494698106
12.221304494597993
12.22130449449789
12.221304494397819
12.221304494297767
12.221304494197739
12.221304494097724
12.221304493997751
12.221304493897785
12.221304493797843
12.221304493697916
12.221304493598028
12.221304493498153
12.221304493398298
12.221304493298469
12.22130449319865
12.221304493098861
12.221304492999094
12.221304492899353
12.221304492799625
12.221304492699929
12.221304492600245
12.22130449250058
12.221304492400936
12.221304492301325
12.221304492201728
12.221304492102162
12.221304492002607
12.221304491903075
12.221304491803568
12.22130449170408
12.221304491604604
12.221304491505176
12.221304491405746
12.221304491306352
12.221304491206974
12.221304491107617
12.221304491008267
12.221304490908963
12.221304490809667
12.221304490710395
12.221304490611152
12.221304490511917
12.221304490412717
12.221304490313525
12.221304490214363
12.22130449011522
12.2213044900161
12.221304489917
12.221304489817928
12.221304489718872
12.221304489619843
12.22130448952082
12.22130448942184
12.221304489322863
12.221304489223915
12.221304489124988
12.221304489026085
12.2213044889272
12.221304488828336
12.221304488729498
12.221304488630679
12.221304488531876
12.221304488433104
12.221304488334345
12.22130448823561
12.221304488136894
12.221304488038207
12.221304487939534
12.221304487840893
12.22130448774227
12.221304487643652
12.221304487545078
12.221304487446508
12.221304487347968
12.221304487249446
12.221304487150958
12.221304487052484
12.22130448695402
12.221304486855587
12.221304486757171
12.221304486658788
12.221304486560417
12.221304486462067
12.221304486363731
12.221304486265433
12.221304486167146
12.221304486068885
12.22130448597064
12.221304485872418
12.221304485774217
12.221304485676042
12.221304485577893
12.221304485479749
12.221304485381639
12.22130448528354
12.221304485185474
12.22130448508742
12.221304484989393
12.221304484891386
12.221304484793393
12.221304484695434
12.221304484597482
12.22130448449956
12.221304484401665
12.221304484303781
12.221304484205918
12.221304484108089
12.221304484010265
12.221304483912474
12.221304483814707
12.221304483716946
12.221304483619212
12.221304483521509
12.221304483423815
12.22130448332615
12.221304483228495
12.221304483130877
12.221304483033272
12.221304482935686
12.221304482838125
12.221304482740582
12.221304482643061
12.221304482545568
12.22130448244809
12.221304482350638
12.221304482253203

12.221304482155778
12.221304482058391
12.22130448196102
12.221304481863667
12.22130448176634
12.221304481669033
12.221304481571739
12.221304481474478
12.22130448137723
12.221304481280008
12.221304481182806
12.221304481085626
12.221304480988463
12.221304480891321
12.22130448079421
12.221304480697109
12.221304480600033
12.221304480502983
12.221304480405944
12.221304480308932
12.221304480211936
12.221304480114968
12.22130448001802
12.221304479921088
12.221304479824179
12.221304479727296
12.221304479630428
12.221304479533584
12.221304479436762
12.221304479339958
12.221304479243178
12.221304479146413
12.221304479049673
12.221304478952959
12.221304478856265
12.221304478759583
12.22130447866293
12.221304478566294
12.221304478469676
12.22130447837309
12.221304478276512
12.221304478179967
12.221304478083434
12.221304477986921
12.221304477890438
12.221304477793973
12.221304477697519
12.221304477601096
12.22130447750469
12.221304477408317
12.221304477311953
12.221304477215606
12.221304477119283
12.221304477022986
12.221304476926713
12.221304476830447
12.221304476734216
12.221304476637998
12.221304476541803
12.221304476445631
12.221304476349474
12.221304476253344
12.221304476157224
12.22130447606114
12.221304475965068
12.221304475869022
12.221304475772993
12.221304475676979
12.221304475581004
12.22130447548504
12.221304475389084
12.221304475293163
12.221304475197257
12.22130447510138
12.221304475005521
12.221304474909674
12.221304474813858
12.221304474718062
12.221304474622281
12.22130447452652
12.221304474430786
12.221304474335067
12.221304474239373
12.2213044741437
12.22130447404804
12.221304473952417
12.221304473856803
12.221304473761203
12.221304473665636
12.221304473570093
12.221304473474559
12.221304473379048
12.221304473283556
12.221304473188098
12.221304473092651
12.221304472997225
12.221304472901814
12.221304472806436
12.22130447271107
12.221304472615728
12.221304472520407
12.221304472425105
12.221304472329821
12.221304472234559
12.221304472139321
12.221304472044102
12.221304471948905
12.22130447185373
12.221304471758572
12.221304471663439
12.221304471568324
12.221304471473223
12.221304471378147
12.2213044712831
12.221304471188066
12.221304471093053
12.221304470998064
12.22130447090309
12.221304470808139
12.221304470713214
12.221304470618302
12.221304470523416
12.221304470428537
12.221304470333695
12.221304470238875
12.22130447014406
12.22130447004928
12.221304469954514
12.221304469859765
12.22130446976505
12.221304469670342
12.221304469575662
12.221304469480991
12.221304469386356
12.221304469291733
12.221304469197134
12.221304469102552
12.221304469007986
12.221304468913456
12.221304468818936
12.221304468724442
12.221304468629958
12.221304468535509
12.221304468441065
12.221304468346641
12.221304468252258
12.221304468157884
12.221304468063531
12.221304467969194
12.221304467874878
12.22130446778059
12.22130446768631
12.221304467592063
12.221304467497832
12.221304467403618
12.221304467309427
12.22130446721525
12.221304467121099
12.22130446702698
12.221304466932867
12.22130446683877
12.221304466744714
12.221304466650665
12.221304466556637
12.22130446646263
12.221304466368641
12.221304466274667
12.221304466180726
12.221304466086805
12.2213044659929
12.22130446589901
12.221304465805153
12.221304465711302
12.22130446561748
12.221304465523682
12.221304465429895
12.22130446533613
12.221304465242392
12.221304465148672
12.221304465054965
12.221304464961284
12.221304464867632
12.22130446477399
12.221304464680367
12.22130446458677
12.221304464493187
12.221304464399628
12.221304464306094
12.221304464212574
12.221304464119074
12.221304464025593
12.22130446393213
12.221304463838695
12.221304463745284
12.22130446365188
12.221304463558507
12.22130446346515
12.221304463371816
12.221304463278498
12.221304463185204
12.221304463091927
12.22130446299867
12.221304462905437
12.22130446281222
12.221304462719035
12.221304462625856
12.221304462532698
12.221304462439564
12.221304462346453
12.221304462253359
12.221304462160292
12.221304462067238
12.221304461974208
12.221304461881186
12.2213044617882
12.221304461695235
12.221304461602276
12.221304461509337
12.221304461416434
12.221304461323538
12.22130446123067
12.22130446113782
12.221304461044987
12.221304460952183
12.221304460859386
12.221304460766614
12.221304460673867
12.221304460581138
12.221304460488419
12.221304460395737
12.221304460303067
12.221304460210415
12.221304460117782
12.221304460025182
12.221304459932584
12.221304459840013
12.221304459747476
12.22130445965494
12.221304459562438
12.221304459469945
12.22130445937748
12.221304459285024
12.221304459192593
12.221304459100189
12.221304459007792
12.221304458915432
12.22130445882309
12.221304458730753
12.221304458638445
12.221304458546152
12.221304458453892
12.221304458361637
12.221304458269412
12.221304458177196
12.221304458085013
12.221304457992842
12.221304457900693
12.221304457808573
12.221304457716453
12.221304457624369
12.221304457532305
12.221304457440258
12.221304457348232
12.22130445725622
12.221304457164239
12.221304457072259
12.221304456980311
12.221304456888388
12.221304456796478
12.22130445670459
12.221304456612721
12.22130445652087
12.221304456429042
12.22130445633723
12.221304456245448
12.221304456153668
12.221304456061922
12.221304455970195
12.221304455878489
12.2213044557868
12.22130445569513
12.221304455603486
12.221304455511849
12.22130445542024
12.22130445532865
12.221304455237085
12.221304455145534
12.221304455054
12.221304454962498
12.221304454871001
12.221304454779526
12.221304454688083
12.22130445459665
12.221304454505239
12.221304454413845
12.221304454322468
12.221304454231126
12.221304454139785
12.221304454048482
12.221304453957186
12.221304453865923
12.221304453774664
12.22130445368342
12.221304453592214
12.221304453501027
12.22130445340985
12.221304453318695
12.221304453227566
12.221304453136446
12.221304453045352
12.221304452954278
12.221304452863226
12.221304452772191
12.221304452681176
12.221304452590179
12.221304452499208
12.221304452408251
12.221304452317316
12.221304452226397
12.221304452135493
12.221304452044627
12.221304451953765
12.22130445186293
12.221304451772104
12.221304451681311
12.221304451590532
12.22130445149977
12.221304451409035
12.221304451318318
12.221304451227619
12.221304451136938
12.221304451046278
12.221304450955632
12.221304450865015
12.221304450774412
12.221304450683826
12.221304450593262
12.22130445050273
12.221304450412207
12.221304450321702
12.221304450231218
12.22130445014076
12.221304450050305
12.221304449959892
12.221304449869482
12.221304449779094
12.221304449688732
12.221304449598385
12.221304449508057
12.221304449417758
12.221304449327464
12.221304449237202
12.22130444914696
12.221304449056731
12.221304448966514
12.221304448876323
12.221304448786153
12.221304448695996
12.221304448605869
12.22130444851576
12.221304448425673
12.2213044483356
12.221304448245556
12.221304448155516
12.2213044480655
12.221304447975509
12.221304447885538
12.22130444779558
12.221304447705641
12.221304447615722
12.221304447525837
12.221304447435958
12.2213044473461
12.22130444725626
12.221304447166442
12.221304447076653
12.221304446986869
12.221304446897106
12.221304446807371
12.221304446717646
12.221304446627949
12.221304446538266
12.2213044464486
12.221304446358962
12.221304446269343
12.221304446179733
12.221304446090153
12.221304446000584
12.22130444591104
12.221304445821515
12.221304445732004
12.221304445642513
12.221304445553058
12.221304445463604
12.221304445374177
12.221304445284769
12.22130444519538
12.22130444510601
12.221304445016656
12.221304444927322
12.221304444838012
12.22130444474872
12.221304444659447
12.221304444570196
12.221304444480957
12.22130444439174
12.221304444302536
12.221304444213365
12.221304444124215
12.221304444035066
12.221304443945952
12.221304443856855
12.221304443767773
12.221304443678711
12.221304443589666
12.221304443500644
12.221304443411647
12.221304443322659
12.221304443233688
12.221304443144758
12.22130444305583
12.221304442966924
12.221304442878031
12.221304442789165
12.221304442700317
12.22130444261149
12.221304442522678
12.221304442433885
12.221304442345115
12.221304442256367
12.22130444216764
12.221304442078917
12.22130444199022
12.22130444190155
12.221304441812894
12.221304441724257
12.221304441635636
12.221304441547042
12.221304441458466
12.221304441369902
12.22130444128136
12.221304441192848
12.221304441104342
12.22130444101586
12.221304440927398
12.221304440838955
12.22130444075052
12.221304440662122
12.221304440573732
12.221304440485362
12.221304440397015
12.221304440308687
12.221304440220377
12.221304440132089
12.221304440043818
12.22130443995556
12.22130443986733
12.221304439779114
12.221304439690917
12.221304439602747
12.221304439514588
12.22130443942646
12.22130443933833
12.221304439250238
12.22130443916215
12.221304439074085
12.221304438986053
12.221304438898033
12.221304438810014
12.221304438722042
12.221304438634078
12.22130443854613
12.2213044384582
12.22130443837029
12.221304438282406
12.221304438194531
12.221304438106676
12.221304438018846
12.22130443793104
12.221304437843242
12.221304437755467
12.221304437667712
12.221304437579974
12.221304437492256
12.221304437404559
12.22130443731688
12.22130443722922
12.221304437141582
12.221304437053957
12.22130443696635
12.221304436878766
12.221304436791202
12.221304436703662
12.221304436616123
12.221304436528616
12.22130443644113
12.221304436353659
12.22130443626621
12.221304436178773
12.22130443609136
12.22130443600396
12.221304435916593
12.22130443582923
12.221304435741894
12.22130443565457
12.221304435567278
12.22130443548
12.221304435392737
12.22130443530549
12.221304435218268
12.221304435131064
12.221304435043878
12.221304434956707
12.221304434869557
12.221304434782436
12.221304434695321
12.221304434608228
12.22130443452116
12.221304434434105
12.221304434347067
12.221304434260055
12.221304434173057
12.221304434086072
12.221304433999116
12.221304433912175
12.221304433825257
12.221304433738348
12.221304433651472
12.221304433564606
12.221304433477757
12.221304433390927
12.22130443330412
12.221304433217336
12.221304433130559
12.22130443304381
12.221304432957071
12.221304432870358
12.221304432783672
12.221304432696995
12.221304432610333
12.221304432523699
12.221304432437075
12.221304432350477
12.221304432263887
12.221304432177323
12.22130443209078
12.221304432004256
12.221304431917746
12.221304431831255
12.22130443174479
12.221304431658337
12.221304431571895
12.221304431485484
12.221304431399098
12.221304431312712
12.22130443122636
12.221304431140023
12.221304431053706
12.221304430967406
12.221304430881117
12.22130443079486
12.22130443070861
12.221304430622386
12.221304430536179
12.221304430449981
12.22130443036381
12.221304430277668
12.221304430191525
12.22130443010542
12.22130443001932
12.221304429933241
12.22130442984719

12.221304429761146
12.221304429675122
12.221304429589127
12.221304429503142
12.22130442941717
12.221304429331227
12.221304429245308
12.221304429159396
12.221304429073504
12.221304428987635
12.221304428901785
12.22130442881595
12.221304428730132
12.221304428644338
12.22130442855856
12.2213044284728
12.221304428387056
12.221304428301337
12.221304428215632
12.221304428129947
12.221304428044277
12.221304427958628
12.221304427873005
12.221304427787391
12.221304427701803
12.221304427616221
12.221304427530665
12.22130442744513
12.221304427359616
12.221304427274122
12.22130442718864
12.221304427103176
12.22130442701773
12.221304426932308
12.221304426846903
12.221304426761504
12.221304426676141
12.221304426590788
12.221304426505457
12.22130442642014
12.221304426334855
12.221304426249567
12.221304426164313
12.221304426079081
12.221304425993846
12.22130442590865
12.221304425823465
12.22130442573829
12.221304425653155
12.221304425568027
12.221304425482915
12.22130442539782
12.221304425312749
12.221304425227684
12.221304425142657
12.221304425057642
12.221304424972635
12.221304424887647
12.221304424802689
12.221304424717745
12.221304424632827
12.221304424547917
12.221304424463023
12.221304424378156
12.221304424293308
12.221304424208466
12.221304424123652
12.221304424038859
12.221304423954075
12.22130442386932
12.221304423784574
12.221304423699856
12.221304423615146
12.221304423530459
12.221304423445787
12.221304423361136
12.22130442327651
12.221304423191896
12.221304423107304
12.221304423022726
12.221304422938163
12.221304422853631
12.221304422769103
12.2213044226846
12.221304422600124
12.22130442251565
12.221304422431203
12.221304422346773
12.221304422262358
12.221304422177973
12.221304422093596
12.22130442200924
12.2213044219249
12.221304421840582
12.221304421756285
12.221304421672
12.221304421587734
12.221304421503488
12.221304421419259
12.221304421335049
12.221304421250858
12.221304421166677
12.221304421082525
12.221304420998393
12.221304420914267
12.22130442083017
12.22130442074609
12.221304420662024
12.22130442057798
12.221304420493954
12.221304420409943
12.221304420325955
12.221304420241983
12.221304420158024
12.221304420074084
12.221304419990169
12.22130441990627
12.221304419822387
12.22130441973853
12.221304419654675
12.221304419570842
12.221304419487044
12.22130441940326
12.221304419319475
12.22130441923573
12.22130441915199
12.221304419068277
12.221304418984577
12.221304418900887
12.221304418817235
12.221304418733581
12.221304418649952
12.22130441856635
12.221304418482758
12.22130441839918
12.221304418315624
12.221304418232084
12.221304418148572
12.221304418065067
12.221304417981585
12.221304417898125
12.221304417814684
12.221304417731256
12.221304417647847
12.221304417564449
12.221304417481079
12.221304417397723
12.221304417314379
12.221304417231071
12.221304417147767
12.221304417064486
12.22130441698122
12.221304416897974
12.221304416814746
12.221304416731533
12.22130441664834
12.221304416565165
12.22130441648201
12.22130441639887
12.221304416315753
12.22130441623265
12.221304416149565
12.221304416066493
12.221304415983447
12.221304415900418
12.221304415817407
12.221304415734416
12.22130441565144
12.221304415568477
12.221304415485537
12.221304415402615
12.22130441531971
12.221304415236824
12.221304415153956
12.221304415071105
12.221304414988271
12.22130441490546
12.221304414822665
12.221304414739883
12.221304414657128
12.221304414574378
12.221304414491659
12.221304414408952
12.221304414326267
12.22130441424359
12.221304414160949
12.221304414078306
12.22130441399569
12.221304413913089
12.22130441383051
12.221304413747948
12.221304413665402
12.221304413582875
12.221304413500366
12.221304413417872
12.221304413335403
12.221304413252954
12.221304413170516
12.221304413088088
12.221304413005683
12.221304412923303
12.221304412840935
12.221304412758593
12.221304412676261
12.221304412593948
12.221304412511651
12.221304412429376
12.22130441234711
12.221304412264876
12.221304412182654
12.221304412100434
12.221304412018254
12.221304411936092
12.221304411853945
12.221304411771808
12.221304411689689
12.221304411607598
12.221304411525509
12.221304411443443
12.221304411361402
12.221304411279378
12.221304411197368
12.221304411115371
12.221304411033403
12.221304410951447
12.221304410869505
12.22130441078759
12.221304410705683
12.221304410623796
12.221304410541933
12.221304410460089
12.221304410378252
12.221304410296437
12.221304410214644
12.221304410132861
12.221304410051108
12.221304409969363
12.221304409887635
12.22130440980593
12.22130440972424
12.22130440964257
12.221304409560911
12.22130440947928
12.221304409397659
12.221304409316067
12.221304409234477
12.221304409152912
12.221304409071362
12.221304408989834
12.22130440890832
12.221304408826825
12.221304408745358
12.221304408663883
12.221304408582448
12.221304408501021
12.221304408419618
12.221304408338229
12.22130440825686
12.221304408175502
12.221304408094174
12.221304408012857
12.221304407931552
12.221304407850274
12.221304407769006
12.22130440768776
12.22130440760653
12.221304407525318
12.221304407444126
12.22130440736294
12.221304407281785
12.22130440720065
12.221304407119517
12.221304407038415
12.221304406957326
12.221304406876257
12.221304406795205
12.221304406714165
12.221304406633152
12.221304406552147
12.221304406471162
12.221304406390194
12.221304406309244
12.221304406228317
12.221304406147409
12.221304406066505
12.221304405985641
12.221304405904771
12.221304405823929
12.221304405743096
12.221304405662297
12.221304405581519
12.221304405500737
12.221304405419978
12.221304405339247
12.221304405258522
12.22130440517782
12.221304405097143
12.221304405016468
12.221304404935813
12.221304404855188
12.221304404774573
12.221304404693974
12.221304404613392
12.221304404532832
12.221304404452281
12.221304404371761
12.221304404291251
12.22130440421076
12.22130440413028
12.221304404049828
12.221304403969384
12.221304403888961
12.221304403808558
12.221304403728167
12.221304403647805
12.221304403567448
12.221304403487112
12.221304403406801
12.221304403326492
12.221304403246208
12.221304403165943
12.221304403085696
12.221304403005467
12.221304402925256
12.221304402845059
12.22130440276488
12.22130440268472
12.221304402604572
12.221304402524446
12.221304402444337
12.221304402364247
12.221304402284176
12.221304402204115
12.22130440212408
12.221304402044051
12.221304401964046
12.221304401884066
12.221304401804089
12.221304401724138
12.221304401644204
12.221304401564282
12.221304401484383
12.221304401404502
12.221304401324634
12.221304401244785
12.221304401164952
12.221304401085153
12.221304401005346
12.221304400925568
12.221304400845797
12.22130440076607
12.221304400686336
12.221304400606625
12.221304400526922
12.221304400447256
12.221304400367602
12.221304400287952
12.221304400208336
12.221304400128728
12.221304400049137
12.221304399969565
12.221304399890018
12.221304399810471
12.221304399730956
12.221304399651459
12.221304399571968
12.221304399492494
12.221304399413052
12.22130439933361
12.221304399254194
12.221304399174794
12.221304399095413
12.221304399016049
12.221304398936706
12.221304398857377
12.221304398778058
12.221304398698765
12.221304398619496
12.22130439854022
12.22130439846098
12.221304398381749
12.221304398302543
12.221304398223348
12.221304398144177
12.221304398065021
12.221304397985877
12.221304397906756
12.221304397827652
12.221304397748556
12.221304397669485
12.22130439759043
12.221304397511389
12.221304397432371
12.221304397353366
12.221304397274384
12.221304397195405
12.221304397116462
12.221304397037521
12.221304396958606
12.221304396879704
12.221304396800821
12.221304396721955
12.22130439664311
12.22130439656427
12.221304396485452
12.221304396406653
12.22130439632788
12.221304396249119
12.221304396170364
12.221304396091636
12.221304396012922
12.221304395934228
12.22130439585556
12.221304395776887
12.221304395698244
12.221304395619615
12.22130439554101
12.221304395462411
12.221304395383829
12.221304395305271
12.221304395226731
12.221304395148215
12.221304395069705
12.22130439499121
12.221304394912735
12.221304394834279
12.221304394755842
12.221304394677423
12.221304394599017
12.221304394520622
12.221304394442255
12.221304394363898
12.221304394285557
12.221304394207236
12.221304394128932
12.221304394050645
12.221304393972376
12.221304393894126
12.221304393815887
12.221304393737668
12.221304393659466
12.221304393581283
12.221304393503111
12.221304393424965
12.221304393346827
12.221304393268714
12.221304393190612
12.221304393112534
12.221304393034467
12.221304392956414
12.221304392878386
12.221304392800365
12.221304392722367
12.22130439264439
12.221304392566418
12.221304392488474
12.221304392410547
12.221304392332636
12.221304392254735
12.221304392176853
12.221304392098993
12.221304392021146
12.221304391943312
12.221304391865504
12.221304391787712
12.221304391709937
12.221304391632174
12.221304391554426
12.221304391476695
12.221304391398983
12.221304391321283
12.221304391243613
12.221304391165953
12.221304391088314
12.221304391010682
12.221304390933083
12.221304390855476
12.2213043907779
12.221304390700343
12.221304390622802
12.22130439054527
12.221304390467758
12.221304390390276
12.221304390312797
12.22130439023534
12.221304390157895
12.221304390080471
12.221304390003072
12.221304389925681
12.221304389848301
12.221304389770948
12.221304389693605
12.221304389616279
12.221304389538968
12.221304389461686
12.221304389384409
12.221304389307152
12.221304389229907
12.221304389152685
12.22130438907548
12.221304388998286
12.221304388921116
12.221304388843958
12.221304388766823
12.221304388689706
12.221304388612591
12.221304388535499
12.221304388458433
12.221304388381368
12.221304388304333
12.221304388227317
12.221304388150308
12.221304388073305
12.221304387996344
12.221304387919385
12.22130438784245
12.221304387765532
12.221304387688619
12.221304387611744
12.221304387534863
12.221304387458009
12.22130438738116
12.22130438730434
12.221304387227539
12.221304387150747
12.221304387073983
12.22130438699722
12.221304386920481
12.221304386843759
12.221304386767056
12.22130438669037
12.22130438661369
12.221304386537039
12.221304386460405
12.221304386383778
12.221304386307171
12.221304386230583
12.221304386154014
12.221304386077454
12.221304386000918
12.221304385924393
12.221304385847885
12.221304385771397
12.221304385694918
12.22130438561847
12.221304385542027
12.221304385465608

12.221304385389201
12.221304385312813
12.221304385236442
12.221304385160085
12.221304385083736
12.221304385007413
12.22130438493111
12.221304384854824
12.221304384778549
12.221304384702288
12.221304384626052
12.221304384549827
12.221304384473624
12.22130438439742
12.221304384321252
12.221304384245093
12.221304384168949
12.221304384092821
12.22130438401672
12.221304383940623
12.221304383864549
12.221304383788494
12.221304383712454
12.221304383636417
12.221304383560417
12.221304383484425
12.221304383408446
12.221304383332484
12.221304383256546
12.22130438318061
12.221304383104707
12.22130438302881
12.221304382952924
12.221304382877074
12.221304382801227
12.221304382725396
12.221304382649585
12.221304382573798
12.221304382498017
12.221304382422248
12.221304382346498
12.221304382270786
12.221304382195063
12.221304382119367
12.221304382043684
12.221304381968027
12.22130438189238
12.221304381816745
12.221304381741133
12.221304381665535
12.221304381589956
12.221304381514383
12.221304381438845
12.2213043813633
12.221304381287794
12.22130438121229
12.221304381136806
12.22130438106134
12.221304380985892
12.221304380910455
12.221304380835035
12.221304380759635
12.221304380684249
12.221304380608888
12.221304380533521
12.221304380458196
12.221304380382886
12.221304380307574
12.221304380232288
12.221304380157015
12.22130438008176
12.221304380006522
12.2213043799313
12.221304379856093
12.221304379780905
12.221304379705737
12.221304379630576
12.221304379555434
12.221304379480312
12.221304379405215
12.221304379330117
12.221304379255033
12.221304379179985
12.221304379104945
12.221304379029913
12.221304378954901
12.221304378879909
12.221304378804934
12.221304378729979
12.22130437865502
12.221304378580104
12.221304378505186
12.221304378430291
12.221304378355413
12.221304378280557
12.221304378205705
12.221304378130876
12.221304378056063
12.221304377981262
12.221304377906485
12.221304377831718
12.221304377756963
12.221304377682234
12.22130437760752
12.221304377532809
12.221304377458129
12.221304377383467
12.221304377308806
12.221304377234171
12.221304377159555
12.221304377084957
12.22130437701036
12.221304376935791
12.221304376861235
12.221304376786696
12.221304376712176
12.221304376637669
12.221304376563175
12.221304376488701
12.221304376414249
12.221304376339807
12.221304376265378
12.221304376190973
12.221304376116576
12.221304376042198
12.221304375967835
12.221304375893496
12.221304375819162
12.221304375744849
12.22130437567055
12.221304375596274
12.221304375522008
12.221304375447763
12.22130437537354
12.221304375299313
12.221304375225113
12.221304375150932
12.221304375076766
12.221304375002607
12.221304374928478
12.22130437485436
12.221304374780257
12.221304374706168
12.221304374632096
12.221304374558038
12.221304374484001
12.221304374409982
12.22130437433597
12.221304374261985
12.221304374188014
12.22130437411405
12.221304374040104
12.221304373966177
12.221304373892266
12.221304373818372
12.221304373744498
12.22130437367064
12.22130437359679
12.221304373522962
12.221304373449142
12.221304373375348
12.22130437330156
12.2213043732278
12.221304373154043
12.22130437308031
12.221304373006598
12.221304372932895
12.221304372859208
12.221304372785536
12.221304372711884
12.221304372638246
12.221304372564628
12.221304372491021
12.221304372417425
12.22130437234385
12.221304372270296
12.22130437219675
12.221304372123221
12.221304372049712
12.22130437197622
12.22130437190274
12.221304371829278
12.22130437175583
12.221304371682406
12.221304371608982
12.22130437153559
12.2213043714622
12.221304371388827
12.221304371315487
12.221304371242145
12.221304371168833
12.221304371095535
12.22130437102224
12.22130437094897
12.221304370875716
12.221304370802473
12.221304370729253
12.221304370656044
12.221304370582851
12.221304370509671
12.221304370436515
12.22130437036337
12.22130437029024
12.221304370217121
12.221304370144033
12.221304370070953
12.221304369997886
12.221304369924837
12.221304369851806
12.221304369778789
12.221304369705782
12.221304369632797
12.221304369559832
12.221304369486871
12.221304369413943
12.221304369341013
12.221304369268116
12.221304369195217
12.221304369122343
12.221304369049479
12.22130436897664
12.221304368903812
12.221304368831005
12.221304368758208
12.22130436868543
12.22130436861266
12.22130436853991
12.221304368467178
12.221304368394474
12.22130436832176
12.221304368249083
12.221304368176414
12.221304368103757
12.221304368031117
12.221304367958492
12.221304367885883
12.221304367813296
12.221304367740727
12.22130436766816
12.22130436759561
12.22130436752309
12.221304367450578
12.221304367378085
12.221304367305596
12.22130436723314
12.221304367160691
12.221304367088257
12.22130436701584
12.221304366943432
12.221304366871049
12.221304366798673
12.221304366726324
12.221304366653985
12.221304366581665
12.221304366509363
12.221304366437064
12.22130436636479
12.221304366292523
12.22130436622028
12.221304366148054
12.221304366075836
12.221304366003642
12.221304365931454
12.221304365859291
12.221304365787137
12.221304365715007
12.22130436564288
12.221304365570782
12.221304365498689
12.221304365426624
12.221304365354559
12.221304365282522
12.221304365210498
12.221304365138481
12.2213043650665
12.221304364994516
12.221304364922545
12.221304364850598
12.221304364778671
12.221304364706745
12.221304364634857
12.221304364562972
12.221304364491093
12.221304364419247
12.2213043643474
12.221304364275584
12.221304364203778
12.221304364131985
12.221304364060199
12.221304363988445
12.221304363916705
12.221304363844974
12.221304363773259
12.221304363701567
12.221304363629878
12.221304363558215
12.221304363486556
12.221304363414925
12.221304363343302
12.221304363271695
12.221304363200115
12.221304363128535
12.221304363056984
12.221304362985439
12.221304362913909
12.221304362842405
12.221304362770907
12.221304362699415
12.221304362627956
12.22130436255651
12.221304362485075
12.221304362413653
12.221304362342256
12.221304362270871
12.221304362199493
12.221304362128134
12.221304362056797
12.221304361985467
12.221304361914166
12.221304361842865
12.221304361771587
12.221304361700321
12.221304361629072
12.221304361557841
12.22130436148662
12.221304361415418
12.221304361344242
12.221304361273068
12.221304361201911
12.221304361130766
12.221304361059648
12.221304360988533
12.221304360917449
12.221304360846359
12.221304360775306
12.221304360704254
12.221304360633223
12.221304360562211
12.221304360491201
12.221304360420223
12.22130436034925
12.221304360278292
12.22130436020736
12.221304360136433
12.221304360065519
12.221304359994631
12.22130435992375
12.221304359852889
12.221304359782039
12.221304359711215
12.22130435964039
12.221304359569585
12.22130435949881
12.221304359428038
12.221304359357271
12.22130435928654
12.22130435921582
12.221304359145105
12.221304359074413
12.221304359003735
12.221304358933068
12.221304358862428
12.221304358791796
12.221304358721177
12.221304358650569
12.221304358579994
12.221304358509414
12.221304358438863
12.221304358368323
12.221304358297798
12.221304358227275
12.221304358156793
12.221304358086316
12.221304358015852
12.221304357945401
12.221304357874963
12.22130435780455
12.221304357734143
12.221304357663758
12.221304357593386
12.221304357523032
12.221304357452691
12.221304357382364
12.221304357312055
12.221304357241756
12.221304357171473
12.221304357101209
12.221304357030963
12.221304356960722
12.221304356890496
12.221304356820307
12.221304356750112
12.221304356679944
12.221304356609787
12.221304356539637
12.22130435646951
12.221304356399393
12.221304356329302
12.22130435625921
12.221304356189155
12.2213043561191
12.22130435604907
12.221304355979044
12.221304355909036
12.221304355839045
12.221304355769066
12.221304355699107
12.221304355629158
12.221304355559228
12.221304355489316
12.221304355419413
12.221304355349533
12.221304355279655
12.221304355209812
12.221304355139967
12.22130435507014
12.221304355000333
12.22130435493054
12.221304354860761
12.22130435479099
12.221304354721251
12.22130435465152
12.22130435458179
12.221304354512098
12.2213043544424
12.221304354372736
12.221304354303074
12.221304354233439
12.221304354163806
12.221304354094187
12.221304354024591
12.221304353955004
12.221304353885449
12.221304353815892
12.221304353746358
12.221304353676835
12.22130435360733
12.22130435353784
12.22130435346836
12.221304353398903
12.22130435332945
12.221304353260022
12.221304353190604
12.221304353121203
12.221304353051824
12.221304352982443
12.221304352913089
12.221304352843744
12.221304352774425
12.221304352705117
12.221304352635817
12.221304352566534
12.22130435249727
12.221304352428016
12.22130435235879
12.221304352289563
12.221304352220365
12.221304352151169
12.22130435208199
12.221304352012831
12.221304351943687
12.221304351874558
12.221304351805443
12.221304351736348
12.221304351667248
12.221304351598183
12.221304351529124
12.221304351460091
12.221304351391058
12.22130435132205
12.221304351253059
12.221304351184079
12.221304351115112
12.221304351046156
12.221304350977219
12.221304350908305
12.221304350839393
12.221304350770511
12.221304350701635
12.221304350632767
12.221304350563923
12.221304350495089
12.22130435042628
12.221304350357471
12.22130435028869
12.221304350219915
12.221304350151165
12.221304350082418
12.221304350013696
12.221304349944976
12.221304349876284
12.221304349807601
12.221304349738944
12.221304349670284
12.221304349601652
12.221304349533028
12.221304349464418
12.221304349395826
12.22130434932725
12.221304349258688
12.221304349190136
12.221304349121606
12.221304349053089
12.221304348984585
12.221304348916092
12.221304348847617
12.221304348779165
12.22130434871072
12.221304348642295
12.221304348573879
12.22130434850548
12.221304348437103
12.221304348368719
12.221304348300372
12.221304348232033
12.221304348163704
12.2213043480954
12.221304348027095
12.22130434795882
12.221304347890555
12.2213043478223
12.22130434775407
12.221304347685843
12.22130434761764
12.221304347549443
12.221304347481265
12.221304347413103
12.221304347344963
12.221304347276831
12.221304347208708
12.221304347140611
12.22130434707252
12.221304347004448
12.221304346936385
12.221304346868342
12.221304346800318
12.221304346732303
12.221304346664304
12.221304346596321
12.221304346528349
12.221304346460391
12.221304346392449
12.221304346324526
12.221304346256618
12.221304346188722
12.221304346120839
12.221304346052971
12.221304345985121
12.221304345917286

12.22130434584947
12.221304345781654
12.221304345713863
12.221304345646088
12.221304345578325
12.221304345510573
12.221304345442846
12.221304345375115
12.22130434530741
12.221304345239714
12.221304345172047
12.221304345104388
12.221304345036737
12.221304344969111
12.221304344901487
12.221304344833888
12.221304344766304
12.221304344698732
12.221304344631172
12.221304344563627
12.221304344496104
12.221304344428589
12.221304344361089
12.221304344293607
12.221304344226127
12.221304344158675
12.221304344091232
12.221304344023803
12.2213043439564
12.221304343888994
12.221304343821622
12.221304343754253
12.221304343686901
12.221304343619552
12.221304343552237
12.221304343484922
12.22130434341763
12.221304343350353
12.221304343283087
12.221304343215838
12.221304343148605
12.221304343081382
12.221304343014168
12.221304342946983
12.221304342879801
12.221304342812635
12.221304342745487
12.221304342678353
12.221304342611232
12.22130434254413
12.22130434247704
12.22130434240997
12.221304342342906
12.221304342275848
12.221304342208821
12.221304342141805
12.221304342074806
12.221304342007814
12.221304341940842
12.22130434187388
12.22130434180694
12.221304341740007
12.221304341673093
12.221304341606192
12.2213043415393
12.221304341472436
12.221304341405574
12.221304341338723
12.2213043412719
12.221304341205087
12.221304341138284
12.221304341071505
12.22130434100473
12.221304340937978
12.221304340871233
12.221304340804506
12.221304340737792
12.221304340671095
12.221304340604409
12.221304340537749
12.221304340471086
12.221304340404448
12.221304340337822
12.221304340271212
12.22130434020461
12.221304340138033
12.221304340071462
12.221304340004911
12.221304339938367
12.221304339871844
12.22130433980533
12.221304339738843
12.221304339672356
12.221304339605888
12.221304339539437
12.221304339472992
12.221304339406576
12.22130433934017
12.221304339273773
12.221304339207391
12.221304339141021
12.221304339074669
12.221304339008329
12.22130433894201
12.221304338875704
12.221304338809405
12.22130433874312
12.221304338676864
12.221304338610611
12.221304338544382
12.221304338478156
12.221304338411947
12.221304338345757
12.221304338279571
12.221304338213407
12.221304338147249
12.221304338081124
12.221304338015008
12.221304337948887
12.221304337882799
12.22130433781672
12.221304337750654
12.221304337684609
12.221304337618571
12.221304337552551
12.221304337486547
12.221304337420557
12.221304337354573
12.221304337288618
12.221304337222659
12.221304337156722
12.221304337090805
12.221304337024902
12.221304336959001
12.22130433689312
12.221304336827268
12.221304336761413
12.221304336695583
12.221304336629753
12.221304336563952
12.221304336498159
12.221304336432384
12.22130433636662
12.221304336300872
12.221304336235127
12.221304336169407
12.221304336103701
12.221304336038015
12.221304335972336
12.221304335906668
12.22130433584102
12.22130433577538
12.221304335709764
12.22130433564415
12.221304335578566
12.221304335512983
12.221304335447421
12.221304335381868
12.221304335316336
12.221304335250814
12.221304335185298
12.22130433511981
12.221304335054331
12.221304334988867
12.221304334923422
12.221304334857988
12.221304334792553
12.22130433472715
12.221304334661763
12.221304334596384
12.221304334531014
12.221304334465662
12.221304334400331
12.22130433433501
12.22130433426969
12.221304334204397
12.221304334139116
12.221304334073858
12.221304334008604
12.221304333943362
12.221304333878141
12.221304333812922
12.221304333747737
12.221304333682559
12.221304333617383
12.22130433355224
12.221304333487094
12.221304333421974
12.22130433335686
12.221304333291766
12.221304333226682
12.221304333161614
12.221304333096557
12.221304333031519
12.221304332966504
12.22130433290148
12.221304332836484
12.221304332771503
12.221304332706541
12.221304332641573
12.221304332576638
12.221304332511705
12.221304332446802
12.221304332381898
12.221304332317013
12.221304332252139
12.22130433218729
12.221304332122443
12.221304332057617
12.221304331992807
12.221304331928005
12.221304331863209
12.221304331798441
12.221304331733688
12.221304331668938
12.221304331604207
12.221304331539494
12.221304331474794
12.221304331410101
12.221304331345426
12.221304331280777
12.221304331216128
12.22130433115149
12.221304331086873
12.221304331022276
12.221304330957684
12.221304330893107
12.221304330828545
12.221304330763997
12.221304330699468
12.221304330634949
12.221304330570446
12.221304330505951
12.22130433044147
12.22130433037701
12.221304330312567
12.221304330248124
12.221304330183711
12.221304330119295
12.2213043300549
12.221304329990526
12.221304329926156
12.221304329861804
12.221304329797468
12.221304329733151
12.221304329668836
12.221304329604541
12.221304329540251
12.221304329475991
12.221304329411733
12.221304329347495
12.221304329283265
12.22130432921906
12.221304329154854
12.221304329090673
12.221304329026498
12.221304328962352
12.221304328898196
12.221304328834067
12.22130432876996
12.22130432870586
12.221304328641772
12.221304328577693
12.221304328513646
12.221304328449593
12.221304328385562
12.221304328321546
12.22130432825754
12.221304328193552
12.221304328129575
12.221304328065616
12.221304328001672
12.221304327937741
12.221304327873813
12.22130432780991
12.22130432774602
12.221304327682137
12.221304327618281
12.221304327554428
12.221304327490586
12.221304327426768
12.221304327362954
12.22130432729916
12.221304327235385
12.221304327171609
12.22130432710785
12.221304327044123
12.221304326980388
12.22130432691668
12.221304326852984
12.221304326789298
12.22130432672563
12.221304326661969
12.221304326598325
12.221304326534701
12.221304326471083
12.221304326407482
12.221304326343889
12.221304326280324
12.221304326216751
12.221304326153215
12.221304326089678
12.221304326026152
12.221304325962652
12.221304325899164
12.221304325835687
12.221304325772225
12.221304325708772
12.221304325645338
12.221304325581917
12.221304325518503
12.221304325455105
12.221304325391728
12.221304325328362
12.221304325265004
12.221304325201668
12.22130432513834
12.221304325075025
12.221304325011726
12.221304324948445
12.22130432488517
12.221304324821913
12.221304324758677
12.221304324695437
12.221304324632218
12.221304324569017
12.221304324505834
12.221304324442656
12.221304324379497
12.221304324316346
12.221304324253213
12.221304324190093
12.22130432412699
12.221304324063892
12.221304324000817
12.221304323937758
12.221304323874692
12.22130432381166
12.221304323748631
12.22130432368562
12.221304323622634
12.22130432355964
12.221304323496673
12.221304323433724
12.221304323370777
12.221304323307846
12.221304323244926
12.221304323182029
12.221304323119146
12.221304323056263
12.221304322993404
12.22130432293056
12.221304322867729
12.221304322804905
12.221304322742107
12.22130432267931
12.22130432261653
12.221304322553765
12.221304322491013
12.221304322428278
12.22130432236555
12.221304322302837
12.22130432224014
12.221304322177456
12.221304322114792
12.221304322052132
12.22130432198949
12.221304321926858
12.221304321864245
12.221304321801647
12.221304321739057
12.221304321676485
12.22130432161392
12.221304321551376
12.221304321488839
12.221304321426315
12.22130432136381
12.22130432130132
12.221304321238838
12.22130432117638
12.221304321113921
12.22130432105148
12.22130432098905
12.22130432092665
12.221304320864247
12.221304320801861
12.221304320739494
12.221304320677136
12.221304320614788
12.221304320552461
12.221304320490148
12.221304320427837
12.221304320365547
12.221304320303275
12.221304320241002
12.221304320178755
12.221304320116525
12.221304320054301
12.221304319992093
12.221304319929901
12.221304319867713
12.221304319805546
12.221304319743394
12.22130431968125
12.221304319619124
12.22130431955701
12.221304319494905
12.22130431943282
12.221304319370743
12.22130431930868
12.221304319246636
12.221304319184602
12.221304319122584
12.221304319060573
12.221304318998584
12.221304318936603
12.221304318874635
12.221304318812686
12.221304318750748
12.22130431868882
12.221304318626911
12.221304318565007
12.221304318503117
12.221304318441248
12.221304318379389
12.221304318317546
12.221304318255712
12.221304318193901
12.221304318132093
12.2213043180703
12.221304318008517
12.221304317946753
12.221304317884998
12.221304317823261
12.221304317761538
12.221304317699827
12.221304317638133
12.221304317576447
12.221304317514772
12.221304317453114
12.221304317391466
12.221304317329839
12.221304317268228
12.221304317206618
12.221304317145028
12.221304317083453
12.221304317021884
12.221304316960335
12.221304316898795
12.221304316837271
12.221304316775763
12.22130431671427
12.22130431665278
12.22130431659131
12.221304316529855
12.221304316468409
12.221304316406982
12.22130431634556
12.22130431628416
12.221304316222765
12.221304316161396
12.221304316100028
12.221304316038667
12.221304315977333
12.221304315916022
12.221304315854699
12.221304315793407
12.221304315732127
12.221304315670851
12.221304315609592
12.221304315548345
12.221304315487123
12.221304315425904
12.22130431536469
12.2213043153035
12.221304315242323
12.221304315181158
12.221304315120008
12.22130431505887
12.221304314997743
12.221304314936638
12.221304314875534
12.221304314814452
12.221304314753382
12.221304314692327
12.221304314631276
12.22130431457025
12.22130431450923
12.221304314448222
12.221304314387229
12.221304314326252
12.22130431426528
12.221304314204335
12.221304314143387
12.221304314082472
12.221304314021552
12.22130431396065
12.22130431389977
12.221304313838894
12.221304313778033
12.221304313717193
12.221304313656356
12.221304313595537
12.221304313534738
12.221304313473933
12.221304313413151
12.221304313352382
12.22130431329163
12.22130431323089
12.221304313170162
12.221304313109446
12.221304313048739
12.221304312988053
12.22130431292739
12.221304312866723
12.221304312806073
12.221304312745442
12.221304312684808
12.221304312624195
12.221304312563605
12.22130431250302
12.22130431244245
12.221304312381903
12.221304312321353
12.221304312260822
12.221304312200305
12.221304312139806
12.221304312079312
12.221304312018834
12.221304311958365
12.221304311897917
12.221304311837478
12.221304311777043
12.22130431171664
12.22130431165624
12.221304311595853
12.221304311535485
12.221304311475114
12.221304311414764
12.221304311354439
12.221304311294118
12.221304311233808
12.221304311173517
12.221304311113231
12.221304311052966
12.221304310992714
12.221304310932474
12.22130431087224
12.221304310812032
12.221304310751824
12.22130431069163
12.22130431063145
12.221304310571286
12.221304310511146
12.221304310451004
12.221304310390872
12.22130431033077
12.22130431027067
12.221304310210588
12.221304310150506
12.221304310090455
12.221304310030405
12.221304309970368
12.221304309910348
12.22130430985034
12.221304309790353

12.221304309730366
12.221304309670403
12.22130430961044
12.221304309550504
12.221304309490575
12.22130430943066
12.221304309370751
12.221304309310868
12.221304309250993
12.221304309191126
12.221304309131272
12.22130430907143
12.22130430901161
12.221304308951797
12.221304308891998
12.221304308832213
12.221304308772435
12.221304308712671
12.221304308652925
12.221304308593195
12.221304308533472
12.221304308473766
12.22130430841407
12.221304308354387
12.221304308294716
12.221304308235064
12.221304308175416
12.221304308115787
12.221304308056173
12.221304307996565
12.221304307936974
12.221304307877396
12.221304307817826
12.22130430775827
12.221304307698732
12.221304307639201
12.221304307579693
12.221304307520194
12.221304307460708
12.221304307401226
12.221304307341766
12.221304307282308
12.22130430722288
12.221304307163457
12.221304307104049
12.221304307044644
12.221304306985262
12.221304306925894
12.221304306866527
12.221304306807184
12.221304306747848
12.221304306688525
12.221304306629218
12.221304306569923
12.221304306510643
12.221304306451374
12.221304306392115
12.221304306332875
12.221304306273645
12.221304306214417
12.221304306155217
12.221304306096025
12.221304306036853
12.221304305977673
12.221304305918531
12.221304305859388
12.221304305800256
12.221304305741139
12.221304305682041
12.221304305622956
12.221304305563875
12.22130430550481
12.221304305445761
12.221304305386724
12.221304305327699
12.221304305268687
12.221304305209678
12.22130430515069
12.22130430509172
12.221304305032763
12.221304304973815
12.221304304914872
12.221304304855959
12.221304304797046
12.221304304738142
12.221304304679263
12.221304304620386
12.221304304561535
12.22130430450268
12.221304304443853
12.221304304385034
12.221304304326218
12.221304304267427
12.221304304208646
12.22130430414987
12.221304304091117
12.221304304032373
12.221304303973634
12.221304303914918
12.221304303856224
12.221304303797524
12.221304303738838
12.221304303680178
12.221304303621515
12.22130430356288
12.221304303504251
12.221304303445633
12.221304303387031
12.221304303328443
12.221304303269854
12.221304303211294
12.22130430315273
12.221304303094207
12.221304303035666
12.221304302977156
12.221304302918659
12.22130430286016
12.221304302801688
12.221304302743215
12.221304302684771
12.221304302626327
12.221304302567905
12.221304302509493
12.221304302451093
12.221304302392703
12.221304302334325
12.221304302275966
12.22130430221761
12.22130430215927
12.221304302100949
12.221304302042633
12.22130430198434
12.221304301926056
12.221304301867779
12.221304301809525
12.221304301751271
12.221304301693031
12.221304301634806
12.221304301576598
12.2213043015184
12.221304301460217
12.221304301402041
12.221304301343872
12.22130430128573
12.221304301227594
12.221304301169475
12.221304301111362
12.221304301053268
12.221304300995184
12.22130430093711
12.221304300879043
12.221304300821007
12.22130430076297
12.221304300704947
12.221304300646931
12.221304300588937
12.221304300530957
12.221304300472985
12.221304300415019
12.22130430035709
12.221304300299138
12.22130430024123
12.221304300183318
12.221304300125421
12.221304300067535
12.221304300009669
12.22130429995181
12.22130429989396
12.221304299836124
12.221304299778307
12.221304299720497
12.221304299662702
12.221304299604911
12.221304299547148
12.221304299489391
12.221304299431644
12.221304299373912
12.221304299316197
12.221304299258483
12.221304299200796
12.221304299143105
12.221304299085437
12.221304299027786
12.221304298970127
12.221304298912496
12.22130429885488
12.221304298797275
12.221304298739675
12.221304298682103
12.221304298624526
12.221304298566961
12.221304298509425
12.221304298451892
12.22130429839437
12.221304298336863
12.22130429827937
12.221304298221886
12.221304298164414
12.221304298106956
12.22130429804951
12.22130429799208
12.221304297934658
12.221304297877253
12.221304297819852
12.221304297762478
12.221304297705098
12.221304297647743
12.221304297590395
12.221304297533063
12.221304297475745
12.221304297418438
12.221304297361142
12.221304297303854
12.221304297246581
12.221304297189326
12.221304297132082
12.221304297074845
12.221304297017628
12.221304296960412
12.221304296903222
12.221304296846036
12.221304296788865
12.221304296731702
12.221304296674553
12.22130429661742
12.221304296560305
12.221304296503188
12.22130429644609
12.22130429638901
12.221304296331931
12.221304296274878
12.221304296217824
12.221304296160802
12.221304296103767
12.221304296046764
12.221304295989764
12.221304295932772
12.221304295875806
12.22130429581883
12.221304295761893
12.221304295704954
12.221304295648023
12.221304295591125
12.221304295534226
12.221304295477335
12.221304295420458
12.2213042953636
12.22130429530675
12.221304295249913
12.22130429519308
12.221304295136276
12.221304295079475
12.221304295022684
12.221304294965908
12.221304294909146
12.221304294852402
12.221304294795651
12.22130429473893
12.221304294682211
12.221304294625513
12.22130429456882
12.221304294512139
12.221304294455482
12.221304294398829
12.221304294342186
12.221304294285558
12.221304294228945
12.221304294172334
12.221304294115749
12.221304294059161
12.221304294002598
12.221304293946055
12.221304293889501
12.22130429383297
12.221304293776452
12.221304293719951
12.221304293663458
12.221304293606979
12.22130429355051
12.221304293494049
12.221304293437612
12.221304293381174
12.221304293324756
12.221304293268348
12.22130429321195
12.221304293155573
12.221304293099196
12.221304293042838
12.2213042929865
12.22130429293016
12.221304292873837
12.221304292817527
12.221304292761234
12.221304292704954
12.221304292648675
12.221304292592416
12.221304292536168
12.221304292479925
12.221304292423705
12.221304292367485
12.22130429231129
12.221304292255113
12.221304292198926
12.221304292142767
12.221304292086616
12.221304292030478
12.221304291974345
12.221304291918239
12.221304291862133
12.22130429180605
12.22130429174997
12.221304291693903
12.221304291637853
12.221304291581808
12.221304291525781
12.221304291469764
12.221304291413759
12.221304291357766
12.221304291301783
12.221304291245819
12.22130429118986
12.221304291133915
12.221304291077985
12.22130429102206
12.22130429096615
12.221304290910266
12.221304290854375
12.221304290798503
12.221304290742644
12.221304290686803
12.221304290630968
12.221304290575146
12.221304290519335
12.22130429046353
12.22130429040774
12.221304290351972
12.221304290296217
12.221304290240461
12.221304290184724
12.221304290128998
12.221304290073286
12.221304290017587
12.221304289961898
12.221304289906218
12.221304289850554
12.22130428979489
12.221304289739255
12.221304289683632
12.221304289628007
12.221304289572403
12.221304289516807
12.221304289461232
12.221304289405658
12.221304289350106
12.221304289294562
12.221304289239022
12.221304289183504
12.221304289127996
12.221304289072508
12.221304289017011
12.221304288961539
12.221304288906083
12.22130428885064
12.221304288795192
12.221304288739772
12.22130428868436
12.22130428862896
12.22130428857358
12.221304288518194
12.221304288462838
12.221304288407477
12.22130428835214
12.22130428829682
12.221304288241496
12.221304288186191
12.221304288130899
12.22130428807562
12.22130428802035
12.221304287965102
12.221304287909852
12.221304287854625
12.22130428779941
12.221304287744188
12.221304287688998
12.221304287633814
12.221304287578642
12.22130428752348
12.221304287468332
12.22130428741319
12.221304287358072
12.221304287302958
12.22130428724786
12.221304287192773
12.22130428713769
12.221304287082628
12.221304287027579
12.221304286972536
12.22130428691751
12.221304286862487
12.221304286807486
12.221304286752492
12.22130428669751
12.221304286642546
12.221304286587594
12.221304286532646
12.221304286477709
12.221304286422779
12.221304286367875
12.221304286312984
12.221304286258098
12.221304286203216
12.22130428614836
12.221304286093511
12.221304286038672
12.221304285983848
12.221304285929026
12.221304285874231
12.221304285819441
12.221304285764656
12.221304285709897
12.221304285655144
12.221304285600397
12.221304285545664
12.221304285490957
12.221304285436245
12.22130428538155
12.221304285326864
12.221304285272193
12.22130428521753
12.221304285162889
12.221304285108245
12.22130428505362
12.221304284999006
12.221304284944411
12.221304284889824
12.221304284835243
12.221304284780684
12.221304284726129
12.22130428467159
12.221304284617059
12.221304284562544
12.22130428450803
12.221304284453542
12.221304284399059
12.221304284344598
12.221304284290133
12.221304284235686
12.22130428418125
12.221304284126829
12.221304284072417
12.221304284018013
12.221304283963633
12.22130428390925
12.22130428385489
12.221304283800539
12.221304283746202
12.22130428369187
12.221304283637553
12.22130428358325

12.22130428352896
12.22130428347468
12.221304283420404
12.221304283366148
12.2213042833119
12.221304283257673
12.221304283203448
12.221304283149232
12.22130428309504
12.22130428304085
12.221304282986672
12.22130428293251
12.221304282878362
12.221304282824214
12.221304282770088
12.221304282715975
12.22130428266187
12.221304282607775
12.221304282553689
12.221304282499627
12.221304282445567
12.221304282391525
12.221304282337488
12.221304282283462
12.221304282229456
12.221304282175451
12.22130428212147
12.221304282067496
12.221304282013525
12.221304281959572
12.221304281905638
12.221304281851705
12.221304281797797
12.22130428174388
12.221304281689985
12.221304281636108
12.221304281582231
12.22130428152838
12.221304281474524
12.221304281420698
12.221304281366873
12.221304281313063
12.22130428125926
12.221304281205473
12.221304281151694
12.221304281097927
12.221304281044176
12.221304280990436
12.221304280936698
12.221304280882979
12.22130428082928
12.221304280775584
12.221304280721895
12.221304280668223
12.221304280614572
12.221304280560922
12.221304280507274
12.221304280453653
12.221304280400044
12.221304280346441
12.22130428029285
12.221304280239275
12.2213042801857
12.221304280132145
12.221304280078602
12.22130428002507
12.22130427997155
12.221304279918039
12.221304279864551
12.22130427981106
12.221304279757586
12.22130427970412
12.221304279650672
12.221304279597232
12.221304279543803
12.22130427949039
12.221304279436989
12.221304279383588
12.22130427933021
12.22130427927684
12.221304279223483
12.22130427917013
12.221304279116799
12.221304279063474
12.221304279010162
12.221304278956865
12.221304278903567
12.221304278850296
12.221304278797032
12.221304278743776
12.221304278690537
12.221304278637298
12.22130427858408
12.221304278530873
12.221304278477676
12.221304278424492
12.221304278371317
12.221304278318158
12.221304278265006
12.221304278211871
12.221304278158742
12.221304278105627
12.221304278052525
12.22130427799943
12.221304277946345
12.221304277893285
12.221304277840227
12.221304277787176
12.221304277734138
12.221304277681114
12.221304277628104
12.221304277575102
12.221304277522119
12.221304277469136
12.221304277416172
12.22130427736322
12.221304277310276
12.221304277257348
12.221304277204428
12.221304277151516
12.22130427709861
12.221304277045732
12.22130427699285
12.221304276939994
12.221304276887146
12.221304276834305
12.221304276781474
12.221304276728663
12.221304276675854
12.221304276623057
12.221304276570281
12.221304276517504
12.221304276464753
12.221304276411999
12.221304276359264
12.221304276306533
12.221304276253822
12.221304276201124
12.22130427614843
12.221304276095754
12.221304276043083
12.221304275990427
12.221304275937795
12.22130427588515
12.221304275832525
12.221304275779914
12.221304275727316
12.221304275674724
12.221304275622154
12.221304275569583
12.221304275517035
12.221304275464492
12.22130427541196
12.221304275359442
12.221304275306931
12.221304275254438
12.221304275201957
12.221304275149475
12.221304275097017
12.221304275044568
12.22130427499213
12.221304274939696
12.221304274887279
12.221304274834873
12.22130427478248
12.221304274730091
12.221304274677724
12.221304274625362
12.221304274573008
12.22130427452068
12.22130427446835
12.221304274416045
12.221304274363735
12.221304274311445
12.22130427425916
12.221304274206892
12.221304274154633
12.221304274102387
12.221304274050153
12.221304273997923
12.221304273945714
12.221304273893514
12.221304273841326
12.221304273789148
12.221304273736983
12.221304273684824
12.221304273632676
12.221304273580547
12.221304273528423
12.221304273476319
12.221304273424217
12.221304273372128
12.221304273320051
12.221304273267986
12.221304273215926
12.221304273163891
12.221304273111858
12.221304273059841
12.221304273007826
12.22130427295583
12.221304272903842
12.221304272851873
12.221304272799907
12.221304272747954
12.221304272696011
12.221304272644074
12.221304272592159
12.22130427254025
12.221304272488364
12.22130427243647
12.221304272384593
12.22130427233274
12.22130427228089
12.221304272229046
12.221304272177216
12.221304272125403
12.221304272073597
12.2213042720218
12.221304271970016
12.22130427191824
12.221304271866481
12.221304271814734
12.221304271762998
12.22130427171127
12.221304271659552
12.221304271607842
12.221304271556154
12.221304271504465
12.2213042714528
12.221304271401145
12.22130427134949
12.221304271297855
12.221304271246225
12.22130427119461
12.221304271143016
12.221304271091418
12.22130427103983
12.221304270988263
12.221304270936699
12.22130427088515
12.221304270833622
12.221304270782099
12.221304270730576
12.221304270679077
12.22130427062758
12.221304270576098
12.22130427052463
12.221304270473173
12.221304270421719
12.221304270370283
12.22130427031886
12.221304270267451
12.221304270216043
12.221304270164651
12.221304270113269
12.221304270061909
12.22130427001055
12.221304269959203
12.221304269907867
12.221304269856535
12.221304269805225
12.221304269753919
12.221304269702625
12.22130426965135
12.221304269600083
12.221304269548819
12.221304269497573
12.22130426944634
12.221304269395121
12.221304269343902
12.221304269292704
12.221304269241507
12.221304269190325
12.221304269139166
12.221304269088003
12.221304269036855
12.221304268985719
12.221304268934597
12.221304268883475
12.221304268832379
12.221304268781287
12.221304268730208
12.221304268679141
12.221304268628083
12.22130426857703
12.221304268526
12.221304268474972
12.221304268423959
12.22130426837295
12.221304268321958
12.221304268270982
12.221304268220019
12.221304268169058
12.221304268118102
12.221304268067168
12.22130426801625
12.22130426796533
12.221304267914427
12.221304267863534
12.221304267812656
12.221304267761786
12.221304267710925
12.221304267660082
12.221304267609243
12.221304267558416
12.221304267507607
12.221304267456798
12.221304267406005
12.221304267355222
12.22130426730445
12.221304267253693
12.221304267202939
12.221304267152206
12.221304267101484
12.221304267050762
12.221304267000058
12.221304266949364
12.221304266898686
12.221304266848012
12.22130426679735
12.221304266746694
12.22130426669606
12.221304266645431
12.221304266594816
12.221304266544209
12.221304266493613
12.221304266443033
12.221304266392467
12.2213042663419
12.221304266291344
12.221304266240807
12.221304266190275
12.221304266139759
12.221304266089259
12.221304266038755
12.221304265988271
12.2213042659378
12.221304265887333
12.221304265836881
12.221304265786442
12.221304265736014
12.221304265685601
12.221304265635181
12.221304265584786
12.2213042655344
12.221304265484026
12.221304265433657
12.221304265383306
12.22130426533296
12.22130426528263
12.221304265232313
12.221304265182003
12.2213042651317
12.221304265081416
12.221304265031133
12.22130426498087
12.221304264930623
12.22130426488037
12.221304264830136
12.221304264779913
12.221304264729703
12.2213042646795
12.221304264629309
12.22130426457913
12.221304264528968
12.221304264478809
12.22130426442866
12.221304264378526
12.221304264328408
12.22130426427829
12.221304264228188
12.221304264178091
12.221304264128007
12.221304264077938
12.221304264027877
12.221304263977839
12.221304263927795
12.22130426387777
12.221304263827758
12.221304263777752
12.221304263727754
12.221304263677768
12.221304263627802
12.22130426357783
12.22130426352789
12.221304263477949
12.22130426342802
12.221304263378096
12.221304263328197
12.221304263278293
12.22130426322841
12.221304263178537
12.22130426312866
12.221304263078817
12.221304263028976
12.221304262979135
12.221304262929323
12.221304262879508
12.221304262829708
12.221304262779924
12.22130426273014
12.221304262680375
12.221304262630625
12.221304262580869
12.221304262531135
12.22130426248142
12.221304262431703
12.221304262382011
12.221304262332312
12.221304262282624
12.221304262232966
12.221304262183295
12.22130426213365
12.22130426208401
12.221304262034389
12.221304261984773
12.221304261935174
12.221304261885578
12.221304261835991
12.22130426178642
12.221304261736856
12.221304261687305
12.221304261637767
12.221304261588234
12.221304261538716
12.221304261489205
12.221304261439709
12.22130426139022
12.221304261340746
12.221304261291284
12.221304261241825
12.22130426119238
12.221304261142947
12.221304261093529
12.221304261044118
12.221304260994712
12.221304260945324
12.221304260895943
12.221304260846573
12.22130426079722
12.221304260747866
12.22130426069854
12.221304260649203
12.221304260599897
12.22130426055059
12.221304260501292
12.22130426045201
12.221304260402741
12.221304260353477
12.221304260304231
12.221304260254987
12.221304260205754
12.221304260156538
12.221304260107335
12.221304260058133
12.221304260008942
12.221304259959773
12.221304259910603
12.22130425986145
12.221304259812303
12.221304259763167
12.221304259714046
12.221304259664937
12.221304259615831
12.221304259566747
12.22130425951766
12.221304259468594
12.221304259419535
12.221304259370486
12.221304259321444
12.22130425927242
12.2213042592234
12.221304259174403
12.221304259125402
12.221304259076422
12.221304259027448
12.221304258978481
12.22130425892953
12.221304258880588
12.22130425883166
12.221304258782736
12.221304258733834
12.221304258684917
12.221304258636033
12.22130425858716
12.22130425853829
12.221304258489429
12.221304258440593
12.221304258391754
12.221304258342927
12.221304258294111
12.221304258245304
12.221304258196518
12.221304258147729
12.221304258098959
12.221304258050198
12.221304258001442
12.221304257952703
12.221304257903977
12.22130425785526
12.221304257806551
12.221304257757849
12.221304257709157
12.221304257660488
12.221304257611816
12.221304257563158
12.221304257514518
12.22130425746588
12.221304257417255
12.221304257368642
12.221304257320039
12.221304257271447
12.221304257222863
12.221304257174294
12.221304257125727
12.221304257077183
12.221304257028645
12.22130425698012
12.221304256931598
12.22130425688309
12.22130425683459
12.221304256786107
12.221304256737621
12.221304256689157
12.221304256640702
12.221304256592264
12.221304256543817
12.221304256495394
12.221304256446988
12.221304256398586
12.221304256350187
12.221304256301806
12.221304256253429
12.221304256205082
12.221304256156724
12.221304256108382
12.221304256060058
12.221304256011727
12.221304255963432
12.221304255915129
12.221304255866846
12.221304255818563
12.2213042557703
12.22130425572204
12.221304255673802
12.221304255625562
12.221304255577339
12.221304255529123
12.221304255480915
12.22130425543272
12.221304255384542
12.221304255336372
12.221304255288214
12.221304255240055
12.22130425519191
12.221304255143787
12.22130425509566
12.221304255047544
12.22130425499945
12.221304254951356
12.221304254903288
12.22130425485522
12.221304254807158
12.221304254759117
12.221304254711079
12.221304254663053
12.221304254615031
12.22130425456703
12.221304254519035
12.221304254471047
12.221304254423073
12.221304254375111
12.22130425432716

12.221304254279213
12.221304254231278
12.221304254183357
12.22130425413544
12.221304254087542
12.221304254039659
12.221304253991779
12.221304253943902
12.221304253896033
12.221304253848189
12.221304253800353
12.221304253752523
12.221304253704703
12.221304253656896
12.221304253609105
12.221304253561312
12.221304253513539
12.221304253465775
12.221304253418012
12.221304253370272
12.221304253322524
12.221304253274814
12.221304253227094
12.221304253179392
12.221304253131697
12.221304253084012
12.221304253036338
12.221304252988679
12.221304252941033
12.221304252893383
12.221304252845751
12.22130425279813
12.22130425275052
12.22130425270291
12.221304252655333
12.221304252607748
12.221304252560182
12.221304252512619
12.221304252465071
12.221304252417534
12.221304252370002
12.221304252322485
12.221304252274974
12.221304252227473
12.221304252179996
12.221304252132514
12.221304252085044
12.221304252037585
12.22130425199014
12.221304251942705
12.221304251895281
12.221304251847867
12.221304251800463
12.221304251753066
12.221304251705678
12.221304251658314
12.221304251610947
12.221304251563597
12.221304251516246
12.221304251468911
12.221304251421584
12.221304251374278
12.221304251326973
12.221304251279681
12.221304251232402
12.221304251185131
12.221304251137868
12.221304251090618
12.221304251043383
12.221304250996155
12.221304250948933
12.221304250901722
12.221304250854525
12.221304250807332
12.221304250760145
12.22130425071299
12.221304250665826
12.22130425061868
12.22130425057154
12.221304250524414
12.221304250477296
12.221304250430176
12.221304250383083
12.221304250336003
12.22130425028892
12.221304250241861
12.221304250194802
12.221304250147755
12.221304250100719
12.221304250053691
12.221304250006675
12.22130424995967
12.221304249912675
12.221304249865696
12.22130424981872
12.221304249771753
12.221304249724803
12.221304249677855
12.221304249630924
12.221304249584005
12.22130424953709
12.221304249490183
12.221304249443286
12.221304249396415
12.221304249349533
12.221304249302673
12.221304249255814
12.221304249208975
12.221304249162145
12.221304249115317
12.221304249068508
12.221304249021706
12.221304248974919
12.221304248928137
12.221304248881363
12.221304248834606
12.221304248787844
12.221304248741113
12.22130424869438
12.221304248647664
12.221304248600951
12.221304248554246
12.221304248507563
12.221304248460877
12.22130424841421
12.221304248367558
12.221304248320902
12.221304248274263
12.221304248227629
12.22130424818101
12.221304248134402
12.221304248087813
12.22130424804122
12.221304247994636
12.221304247948071
12.221304247901513
12.22130424785496
12.221304247808428
12.221304247761896
12.22130424771538
12.221304247668872
12.221304247622369
12.221304247575885
12.221304247529405
12.22130424748294
12.221304247436482
12.221304247390034
12.221304247343602
12.22130424729717
12.221304247250757
12.221304247204348
12.221304247157953
12.221304247111561
12.221304247065186
12.22130424701882
12.221304246972458
12.221304246926124
12.22130424687978
12.221304246833453
12.221304246787131
12.22130424674083
12.221304246694535
12.221304246648247
12.221304246601973
12.2213042465557
12.221304246509447
12.221304246463205
12.221304246416965
12.22130424637074
12.221304246324516
12.221304246278313
12.221304246232119
12.221304246185932
12.221304246139756
12.221304246093585
12.221304246047433
12.22130424600129
12.221304245955158
12.221304245909023
12.221304245862916
12.22130424581681
12.221304245770709
12.22130424572463
12.221304245678555
12.221304245632487
12.221304245586428
12.221304245540388
12.221304245494336
12.221304245448323
12.221304245402301
12.221304245356295
12.221304245310302
12.221304245264312
12.221304245218345
12.221304245172375
12.221304245126424
12.221304245080473
12.221304245034538
12.221304244988605
12.221304244942697
12.22130424489679
12.22130424485089
12.221304244805012
12.221304244759127
12.221304244713266
12.221304244667413
12.221304244621559
12.221304244575721
12.221304244529895
12.221304244484084
12.221304244438274
12.22130424439248
12.221304244346692
12.221304244300912
12.221304244255153
12.221304244209392
12.221304244163646
12.221304244117906
12.221304244072183
12.221304244026463
12.221304243980752
12.221304243935055
12.221304243889373
12.221304243843692
12.221304243798025
12.221304243752371
12.221304243706719
12.221304243661086
12.221304243615453
12.221304243569831
12.221304243524221
12.221304243478635
12.22130424343304
12.221304243387465
12.221304243341896
12.221304243296336
12.221304243250794
12.221304243205253
12.221304243159713
12.221304243114197
12.221304243068692
12.221304243023196
12.221304242977697
12.221304242932217
12.221304242886758
12.221304242841294
12.22130424279584
12.221304242750405
12.221304242704973
12.221304242659548
12.221304242614142
12.221304242568735
12.221304242523349
12.221304242477967
12.2213042424326
12.221304242387234
12.221304242341887
12.221304242296542
12.221304242251207
12.221304242205884
12.221304242160569
12.221304242115274
12.221304242069985
12.221304242024694
12.221304241979432
12.221304241934163
12.221304241888907
12.221304241843665
12.221304241798435
12.221304241753208
12.221304241707996
12.221304241662788
12.221304241617593
12.22130424157241
12.221304241527239
12.221304241482079
12.221304241436915
12.22130424139177
12.221304241346635
12.221304241301514
12.221304241256398
12.221304241211293
12.221304241166196
12.221304241121103
12.221304241076023
12.221304241030962
12.221304240985907
12.221304240940851
12.221304240895819
12.221304240850793
12.221304240805775
12.221304240760766
12.221304240715769
12.221304240670788
12.2213042406258
12.221304240580837
12.221304240535876
12.221304240490923
12.221304240445981
12.22130424040105
12.221304240356128
12.221304240311225
12.221304240266328
12.221304240221428
12.221304240176538
12.221304240131678
12.221304240086809
12.221304240041958
12.221304239997117
12.221304239952287
12.22130423990747
12.22130423986265
12.221304239817849
12.22130423977305
12.22130423972827
12.221304239683493
12.221304239638734
12.22130423959398
12.221304239549237
12.221304239504498
12.221304239459771
12.22130423941505
12.221304239370346
12.22130423932565
12.221304239280961
12.22130423923629
12.221304239191614
12.221304239146962
12.221304239102308
12.221304239057671
12.221304239013046
12.22130423896842
12.221304238923816
12.221304238879222
12.221304238834627
12.221304238790045
12.22130423874547
12.22130423870091
12.221304238656362
12.221304238611824
12.221304238567287
12.221304238522764
12.221304238478254
12.221304238433751
12.221304238389259
12.221304238344764
12.221304238300297
12.22130423825583
12.22130423821138
12.221304238166944
12.221304238122498
12.221304238078071
12.221304238033662
12.221304237989253
12.221304237944862
12.221304237900465
12.221304237856087
12.22130423781172
12.221304237767368
12.221304237723015
12.221304237678678
12.221304237634348
12.221304237590026
12.221304237545715
12.221304237501414
12.22130423745712
12.221304237412841
12.221304237368562
12.221304237324311
12.221304237280053
12.221304237235811
12.221304237191584
12.221304237147349
12.221304237103148
12.221304237058936
12.221304237014742
12.221304236970557
12.22130423692638
12.221304236882213
12.22130423683806
12.221304236793907
12.221304236749774
12.221304236705654
12.22130423666153
12.221304236617419
12.22130423657332
12.221304236529232
12.221304236485148
12.22130423644108
12.22130423639702
12.221304236352966
12.221304236308928
12.221304236264896
12.221304236220874
12.221304236176861
12.22130423613285
12.221304236088862
12.221304236044876
12.221304236000892
12.221304235956936
12.221304235912982
12.22130423586903
12.221304235825095
12.221304235781176
12.22130423573725
12.22130423569334
12.221304235649441
12.22130423560555
12.221304235561677
12.221304235517806
12.221304235473944
12.221304235430093
12.22130423538625
12.22130423534243
12.221304235298597
12.22130423525479
12.22130423521098
12.221304235167185
12.2213042351234
12.221304235079634
12.221304235035856
12.221304234992107
12.221304234948363
12.221304234904625
12.221304234860897
12.221304234817177
12.221304234773472
12.221304234729768
12.221304234686084
12.221304234642405
12.221304234598726
12.221304234555072
12.221304234511415
12.221304234467771
12.221304234424146
12.221304234380518
12.2213042343369
12.221304234293301
12.221304234249711
12.221304234206123
12.221304234162552
12.221304234118978
12.221304234075422
12.221304234031878
12.221304233988336
12.221304233944817
12.221304233901288
12.221304233857788
12.221304233814289
12.221304233770793
12.22130423372731
12.221304233683838
12.221304233640373
12.221304233596927
12.221304233553479
12.22130423351005
12.221304233466617
12.221304233423202
12.221304233379804
12.221304233336404
12.221304233293017
12.221304233249638
12.221304233206272
12.22130423316291
12.22130423311956
12.22130423307622
12.22130423303289
12.221304232989569
12.221304232946256
12.22130423290295
12.221304232859666
12.221304232816385
12.221304232773104
12.221304232729839
12.221304232686576
12.221304232643334
12.221304232600103
12.221304232556884
12.221304232513653
12.22130423247045
12.221304232427247
12.221304232384059
12.221304232340882
12.221304232297717
12.221304232254548
12.221304232211402
12.221304232168249
12.221304232125114
12.221304232081998
12.221304232038879
12.22130423199577
12.221304231952676
12.221304231909592
12.221304231866508
12.22130423182344
12.221304231780394
12.221304231737339
12.221304231694292
12.221304231651276
12.22130423160825
12.221304231565238
12.221304231522238
12.22130423147924
12.221304231436259
12.221304231393287
12.221304231350311
12.221304231307363
12.22130423126441
12.221304231221476
12.221304231178548
12.221304231135633
12.22130423109272
12.22130423104982
12.221304231006926
12.221304230964043
12.221304230921177
12.221304230878317
12.221304230835472
12.221304230792617
12.221304230749785
12.221304230706952
12.221304230664144
12.221304230621325
12.22130423057854
12.22130423053575
12.221304230492965
12.221304230450192
12.221304230407435
12.221304230364678
12.221304230321945
12.221304230279214
12.221304230236484
12.221304230193772
12.22130423015107
12.221304230108373
12.221304230065684
12.221304230023
12.221304229980344
12.221304229937678
12.221304229895033
12.221304229852397
12.221304229809762
12.221304229767139
12.221304229724524
12.221304229681923
12.221304229639326
12.221304229596742
12.221304229554164
12.2213042295116
12.221304229469052
12.221304229426508
12.221304229383954
12.22130422934143
12.221304229298916
12.221304229256399
12.221304229213896
12.221304229171398

12.221304229128927
12.221304229086451
12.221304229043984
12.221304229001529
12.221304228959083
12.221304228916646
12.221304228874216
12.221304228831801
12.221304228789391
12.22130422874699
12.221304228704607
12.221304228662227
12.22130422861985
12.221304228577482
12.22130422853513
12.221304228492786
12.221304228450451
12.221304228408124
12.221304228365803
12.221304228323495
12.221304228281193
12.221304228238914
12.221304228196628
12.221304228154358
12.221304228112091
12.221304228069844
12.221304228027593
12.22130422798536
12.221304227943138
12.22130422790092
12.221304227858711
12.221304227816516
12.221304227774327
12.221304227732153
12.221304227689975
12.221304227647819
12.22130422760566
12.221304227563522
12.22130422752138
12.22130422747926
12.221304227437143
12.22130422739504
12.221304227352944
12.221304227310846
12.221304227268767
12.221304227226703
12.221304227184635
12.221304227142591
12.221304227100545
12.221304227058516
12.221304227016489
12.221304226974466
12.221304226932464
12.221304226890478
12.221304226848481
12.221304226806508
12.221304226764536
12.221304226722571
12.22130422668062
12.22130422663868
12.221304226596741
12.221304226554823
12.221304226512904
12.221304226471004
12.2213042264291
12.221304226387215
12.221304226345337
12.22130422630346
12.221304226261612
12.221304226219761
12.221304226177914
12.22130422613608
12.221304226094253
12.22130422605243
12.221304226010629
12.221304225968838
12.22130422592705
12.221304225885271
12.221304225843507
12.221304225801742
12.221304225759987
12.221304225718244
12.221304225676509
12.221304225634785
12.221304225593071
12.221304225551366
12.221304225509675
12.221304225467978
12.221304225426303
12.22130422538463
12.221304225342976
12.221304225301317
12.221304225259678
12.221304225218047
12.221304225176416
12.221304225134805
12.221304225093197
12.221304225051593
12.221304225009998
12.22130422496843
12.221304224926854
12.221304224885287
12.221304224843742
12.221304224802195
12.221304224760663
12.221304224719143
12.221304224677619
12.221304224636118
12.221304224594615
12.22130422455312
12.221304224511643
12.221304224470174
12.221304224428712
12.22130422438726
12.221304224345811
12.221304224304381
12.221304224262944
12.221304224221528
12.221304224180122
12.221304224138725
12.22130422409733
12.221304224055949
12.221304224014576
12.221304223973215
12.221304223931856
12.22130422389051
12.22130422384918
12.221304223807852
12.221304223766541
12.22130422372522
12.221304223683921
12.221304223642626
12.221304223601338
12.221304223560065
12.221304223518805
12.221304223477546
12.221304223436297
12.221304223395068
12.22130422335383
12.221304223312615
12.221304223271401
12.221304223230202
12.221304223189009
12.221304223147824
12.221304223106648
12.22130422306548
12.221304223024319
12.221304222983164
12.221304222942033
12.221304222900901
12.22130422285978
12.221304222818665
12.221304222777558
12.221304222736475
12.221304222695382
12.221304222654304
12.221304222613236
12.221304222572185
12.221304222531128
12.221304222490085
12.221304222449051
12.221304222408024
12.22130422236701
12.221304222326006
12.221304222285006
12.221304222244022
12.221304222203042
12.221304222162072
12.22130422212111
12.22130422208016
12.221304222039212
12.221304221998277
12.221304221957352
12.221304221916434
12.221304221875522
12.221304221834632
12.221304221793737
12.221304221752861
12.221304221711986
12.221304221671113
12.221304221630263
12.221304221589415
12.221304221548579
12.221304221507749
12.221304221466934
12.221304221426118
12.221304221385319
12.221304221344527
12.221304221303734
12.221304221262972
12.221304221222201
12.221304221181434
12.221304221140688
12.221304221099949
12.221304221059219
12.221304221018492
12.221304220977782
12.221304220937075
12.221304220896384
12.221304220855695
12.221304220815012
12.221304220774343
12.221304220733685
12.221304220693042
12.221304220652398
12.221304220611756
12.221304220571133
12.221304220530513
12.221304220489907
12.221304220449309
12.221304220408722
12.22130422036814
12.22130422032757
12.221304220287
12.221304220246447
12.221304220205907
12.221304220165367
12.22130422012484
12.221304220084326
12.221304220043809
12.221304220003308
12.221304219962818
12.221304219922327
12.221304219881858
12.221304219841386
12.221304219800931
12.221304219760482
12.22130421972004
12.221304219679615
12.22130421963919
12.22130421959877
12.221304219558364
12.221304219517974
12.221304219477581
12.221304219437204
12.221304219396833
12.221304219356465
12.22130421931612
12.221304219275776
12.221304219235442
12.221304219195115
12.221304219154792
12.221304219114485
12.221304219074188
12.221304219033899
12.221304218993609
12.22130421895334
12.221304218913078
12.221304218872822
12.221304218832566
12.22130421879233
12.221304218752099
12.221304218711877
12.22130421867167
12.22130421863146
12.221304218591266
12.221304218551076
12.221304218510904
12.221304218470735
12.22130421843057
12.221304218390419
12.22130421835028
12.221304218310147
12.221304218270022
12.221304218229902
12.221304218189788
12.221304218149694
12.221304218109603
12.221304218069521
12.221304218029452
12.221304217989383
12.22130421794933
12.221304217909276
12.221304217869239
12.221304217829212
12.221304217789191
12.221304217749177
12.221304217709184
12.22130421766918
12.221304217629191
12.22130421758922
12.221304217549248
12.22130421750929
12.22130421746933
12.221304217429392
12.221304217389456
12.221304217349534
12.221304217309612
12.221304217269706
12.221304217229802
12.221304217189918
12.221304217150033
12.221304217110157
12.221304217070298
12.221304217030433
12.221304216990596
12.221304216950744
12.221304216910921
12.221304216871092
12.221304216831278
12.221304216791479
12.22130421675169
12.221304216711898
12.221304216672117
12.22130421663235
12.221304216592577
12.221304216552838
12.221304216513088
12.221304216473344
12.221304216433632
12.2213042163939
12.221304216354193
12.221304216314493
12.221304216274802
12.221304216235122
12.221304216195449
12.221304216155774
12.221304216116119
12.221304216076476
12.221304216036836
12.221304215997199
12.221304215957565
12.221304215917959
12.22130421587835
12.221304215838755
12.221304215799163
12.221304215759579
12.221304215720018
12.221304215680446
12.221304215640892
12.221304215601352
12.221304215561815
12.221304215522283
12.221304215482757
12.22130421544325
12.22130421540375
12.221304215364254
12.221304215324762
12.221304215285288
12.22130421524582
12.221304215206356
12.22130421516691
12.221304215127457
12.22130421508803
12.221304215048594
12.221304215009189
12.221304214969773
12.221304214930372
12.221304214890978
12.2213042148516
12.221304214812221
12.22130421477286
12.221304214733504
12.221304214694149
12.221304214654804
12.221304214615477
12.221304214576145
12.221304214536836
12.221304214497524
12.221304214458232
12.221304214418941
12.221304214379662
12.221304214340398
12.22130421430113
12.221304214261862
12.221304214222622
12.221304214183384
12.221304214144151
12.221304214104935
12.221304214065718
12.221304214026523
12.22130421398732
12.22130421394813
12.22130421390896
12.22130421386979
12.22130421383062
12.221304213791466
12.221304213752326
12.221304213713182
12.221304213674063
12.221304213634946
12.221304213595825
12.221304213556735
12.221304213517636
12.221304213478543
12.221304213439467
12.221304213400407
12.221304213361343
12.22130421332229
12.22130421328325
12.22130421324421
12.22130421320519
12.221304213166174
12.221304213127164
12.221304213088155
12.221304213049175
12.221304213010182
12.221304212971209
12.221304212932242
12.22130421289328
12.221304212854337
12.221304212815392
12.221304212776461
12.22130421273754
12.221304212698621
12.221304212659707
12.221304212620815
12.221304212581918
12.221304212543036
12.221304212504169
12.2213042124653
12.221304212426443
12.221304212387595
12.221304212348759
12.221304212309926
12.221304212271097
12.221304212232283
12.221304212193473
12.221304212154685
12.221304212115891
12.221304212077106
12.221304212038339
12.221304211999568
12.22130421196082
12.22130421192207
12.221304211883329
12.2213042118446
12.221304211805878
12.221304211767162
12.221304211728453
12.221304211689763
12.221304211651074
12.221304211612393
12.22130421157372
12.221304211535058
12.221304211496403
12.22130421145775
12.22130421141912
12.221304211380483
12.221304211341863
12.22130421130326
12.22130421126465
12.221304211226053
12.221304211187459
12.22130421114888
12.221304211110317
12.221304211071747
12.221304211033198
12.221304210994647
12.221304210956115
12.221304210917586
12.221304210879056
12.221304210840549
12.22130421080204
12.221304210763549
12.22130421072506
12.221304210686581
12.221304210648103
12.221304210609649
12.221304210571189
12.22130421053275
12.221304210494306
12.221304210455878
12.22130421041746
12.22130421037905
12.22130421034064
12.221304210302245
12.221304210263854
12.221304210225483
12.221304210187116
12.221304210148745
12.221304210110393
12.221304210072047
12.221304210033708
12.221304209995377
12.221304209957058
12.221304209918744
12.221304209880442
12.221304209842145
12.221304209803865
12.221304209765576
12.2213042097273
12.221304209689043
12.221304209650786
12.221304209612546
12.22130420957431
12.221304209536079

12.221304209497857
12.22130420945965
12.221304209421438
12.221304209383236
12.221304209345059
12.221304209306872
12.221304209268707
12.221304209230537
12.221304209192382
12.221304209154239
12.2213042091161
12.221304209077974
12.221304209039847
12.22130420900174
12.221304208963623
12.221304208925533
12.221304208887442
12.221304208849366
12.221304208811292
12.221304208773232
12.221304208735168
12.221304208697118
12.221304208659085
12.221304208621058
12.22130420858303
12.221304208545018
12.22130420850701
12.221304208469009
12.221304208431022
12.221304208393038
12.22130420835507
12.221304208317104
12.22130420827915
12.221304208241193
12.221304208203259
12.221304208165325
12.221304208127401
12.221304208089496
12.221304208051581
12.221304208013684
12.22130420797579
12.221304207937912
12.221304207900037
12.221304207862165
12.221304207824309
12.221304207786456
12.221304207748624
12.221304207710787
12.221304207672956
12.221304207635146
12.22130420759734
12.221304207559529
12.221304207521742
12.22130420748396
12.221304207446185
12.221304207408417
12.221304207370656
12.221304207332903
12.221304207295164
12.221304207257429
12.2213042072197
12.221304207181982
12.22130420714427
12.221304207106568
12.221304207068878
12.22130420703119
12.221304206993507
12.221304206955846
12.22130420691818
12.221304206880534
12.221304206842877
12.221304206805248
12.221304206767616
12.221304206729995
12.221304206692384
12.221304206654782
12.221304206617184
12.221304206579603
12.221304206542019
12.22130420650445
12.221304206466892
12.221304206429332
12.22130420639178
12.221304206354244
12.221304206316717
12.221304206279196
12.221304206241683
12.22130420620417
12.221304206166675
12.221304206129183
12.2213042060917
12.22130420605423
12.221304206016763
12.221304205979308
12.221304205941857
12.221304205904412
12.221304205866975
12.221304205829554
12.221304205792134
12.221304205754732
12.221304205717326
12.221304205679935
12.221304205642552
12.221304205605177
12.221304205567808
12.221304205530448
12.2213042054931
12.221304205455748
12.221304205418424
12.221304205381093
12.221304205343777
12.221304205306451
12.22130420526916
12.221304205231869
12.221304205194576
12.221304205157303
12.22130420512003
12.221304205082761
12.22130420504551
12.221304205008261
12.221304204971023
12.221304204933794
12.221304204896574
12.221304204859356
12.221304204822154
12.221304204784948
12.221304204747762
12.221304204710577
12.221304204673405
12.221304204636239
12.221304204599088
12.221304204561937
12.221304204524793
12.221304204487659
12.221304204450531
12.221304204413414
12.221304204376302
12.221304204339203
12.221304204302113
12.22130420426502
12.221304204227946
12.221304204190886
12.22130420415382
12.221304204116768
12.22130420407972
12.221304204042683
12.221304204005657
12.221304203968629
12.22130420393162
12.221304203894617
12.221304203857624
12.221304203820628
12.221304203783653
12.221304203746678
12.22130420370971
12.22130420367276
12.221304203635809
12.221304203598875
12.221304203561937
12.221304203525017
12.221304203488094
12.221304203451183
12.22130420341429
12.22130420337739
12.221304203340514
12.221304203303626
12.221304203266767
12.221304203229906
12.221304203193053
12.22130420315621
12.221304203119365
12.221304203082543
12.221304203045717
12.22130420300891
12.221304202972105
12.221304202935302
12.221304202898525
12.221304202861745
12.22130420282497
12.2213042027882
12.221304202751448
12.221304202714695
12.221304202677954
12.221304202641228
12.221304202604495
12.221304202567786
12.221304202531076
12.221304202494377
12.221304202457675
12.221304202420992
12.221304202384315
12.221304202347648
12.221304202310984
12.221304202274332
12.221304202237691
12.221304202201052
12.221304202164418
12.2213042021278
12.221304202091194
12.221304202054585
12.221304202017985
12.221304201981399
12.221304201944813
12.221304201908243
12.221304201871682
12.221304201835114
12.221304201798565
12.221304201762033
12.221304201725486
12.221304201688966
12.221304201652448
12.221304201615938
12.221304201579438
12.221304201542944
12.221304201506456
12.221304201469975
12.221304201433508
12.221304201397041
12.221304201360596
12.221304201324138
12.221304201287701
12.221304201251273
12.22130420121486
12.221304201178432
12.221304201142024
12.221304201105632
12.22130420106924
12.221304201032845
12.221304200996476
12.221304200960114
12.221304200923749
12.221304200887403
12.221304200851057
12.221304200814721
12.221304200778375
12.221304200742072
12.221304200705752
12.221304200669453
12.221304200633156
12.22130420059687
12.221304200560585
12.221304200524314
12.221304200488046
12.22130420045179
12.221304200415537
12.2213042003793
12.221304200343067
12.221304200306841
12.221304200270623
12.221304200234412
12.221304200198205
12.221304200162015
12.221304200125827
12.221304200089655
12.221304200053485
12.221304200017304
12.22130419998116
12.221304199945019
12.22130419990887
12.221304199872742
12.221304199836624
12.221304199800503
12.221304199764392
12.221304199728293
12.221304199692208
12.221304199656112
12.221304199620034
12.221304199583974
12.221304199547912
12.22130419951186
12.221304199475814
12.22130419943977
12.221304199403745
12.22130419936773
12.221304199331707
12.221304199295702
12.221304199259702
12.221304199223711
12.221304199187735
12.221304199151755
12.221304199115778
12.22130419907983
12.221304199043875
12.22130419900793
12.22130419897199
12.221304198936062
12.221304198900144
12.221304198864239
12.22130419882833
12.22130419879243
12.221304198756537
12.221304198720665
12.221304198684782
12.221304198648921
12.221304198613065
12.221304198577212
12.221304198541372
12.221304198505532
12.221304198469708
12.22130419843389
12.22130419839808
12.221304198362276
12.221304198326473
12.221304198290689
12.221304198254913
12.22130419821914
12.221304198183372
12.221304198147621
12.221304198111866
12.22130419807612
12.221304198040391
12.221304198004662
12.22130419796895
12.221304197933234
12.221304197897528
12.221304197861837
12.221304197826154
12.221304197790467
12.221304197754801
12.221304197719135
12.221304197683477
12.22130419764783
12.22130419761218
12.22130419757656
12.221304197540928
12.221304197505312
12.221304197469705
12.2213041974341
12.221304197398508
12.221304197362915
12.221304197327342
12.221304197291767
12.221304197256204
12.221304197220647
12.221304197185104
12.221304197149559
12.221304197114028
12.221304197078492
12.22130419704299
12.221304197007466
12.22130419697197
12.221304196936472
12.221304196900991
12.221304196865514
12.221304196830037
12.22130419679458
12.221304196759124
12.221304196723677
12.221304196688243
12.22130419665281
12.221304196617375
12.221304196581967
12.221304196546546
12.221304196511145
12.22130419647576
12.221304196440364
12.221304196404994
12.22130419636962
12.221304196334254
12.2213041962989
12.22130419626355
12.221304196228209
12.221304196192875
12.22130419615756
12.221304196122235
12.221304196086928
12.22130419605163
12.22130419601633
12.22130419598104
12.22130419594576
12.221304195910491
12.22130419587523
12.22130419583997
12.221304195804723
12.221304195769484
12.221304195734247
12.221304195699023
12.2213041956638
12.221304195628601
12.221304195593387
12.221304195558197
12.221304195523011
12.221304195487827
12.221304195452666
12.221304195417495
12.221304195382341
12.221304195347189
12.221304195312046
12.221304195276915
12.221304195241785
12.221304195206663
12.221304195171555
12.22130419513645
12.221304195101364
12.221304195066272
12.221304195031198
12.22130419499611
12.221304194961052
12.22130419492599
12.221304194890944
12.2213041948559
12.22130419482087
12.221304194785839
12.221304194750822
12.2213041947158
12.221304194680803
12.221304194645807
12.221304194610815
12.221304194575833
12.22130419454086
12.22130419450589
12.221304194470934
12.221304194435985
12.221304194401034
12.221304194366107
12.221304194331173
12.221304194296252
12.221304194261341
12.221304194226432
12.221304194191536
12.221304194156644
12.22130419412176
12.221304194086887
12.221304194052017
12.22130419401716
12.221304193982307
12.221304193947459
12.221304193912623
12.221304193877788
12.221304193842972
12.221304193808155
12.221304193773337
12.22130419373855
12.221304193703755
12.221304193668963
12.22130419363419
12.221304193599414
12.221304193564668
12.221304193529901
12.221304193495154
12.221304193460414
12.221304193425683
12.221304193390965
12.221304193356247
12.221304193321538
12.221304193286837
12.221304193252132
12.221304193217456
12.221304193182775
12.221304193148098
12.221304193113431
12.221304193078778
12.22130419304413
12.221304193009487
12.221304192974857
12.221304192940227
12.221304192905608
12.221304192870996
12.221304192836389
12.2213041928018
12.221304192767214
12.221304192732624
12.221304192698055
12.221304192663489
12.221304192628928
12.221304192594378
12.22130419255983
12.221304192525295
12.22130419249077
12.221304192456243
12.22130419242173
12.221304192387224
12.221304192352724
12.221304192318236
12.221304192283753
12.22130419224927
12.22130419221481
12.221304192180343
12.221304192145878
12.22130419211144
12.221304192077
12.221304192042565
12.221304192008148
12.221304191973728
12.221304191939323
12.221304191904919
12.221304191870528
12.221304191836126
12.221304191801758
12.221304191767388
12.221304191733017
12.22130419169866
12.221304191664322
12.22130419162997
12.221304191595635
12.22130419156131
12.221304191526997
12.221304191492678
12.221304191458364
12.22130419142408
12.221304191389777
12.2213041913555
12.221304191321227
12.221304191286961

12.221304191252695
12.221304191218445
12.221304191184199
12.221304191149956
12.221304191115724
12.22130419108151
12.22130419104729
12.221304191013088
12.221304190978882
12.221304190944693
12.22130419091051
12.22130419087633
12.221304190842144
12.221304190807997
12.22130419077384
12.221304190739687
12.22130419070554
12.22130419067141
12.221304190637278
12.221304190603167
12.221304190569056
12.221304190534942
12.221304190500849
12.221304190466764
12.22130419043268
12.221304190398598
12.221304190364531
12.221304190330478
12.221304190296415
12.22130419026238
12.221304190228343
12.221304190194308
12.221304190160287
12.221304190126274
12.221304190092267
12.221304190058268
12.221304190024268
12.22130418999029
12.221304189956307
12.22130418992233
12.221304189888368
12.221304189854404
12.22130418982046
12.221304189786519
12.221304189752589
12.221304189718651
12.221304189684735
12.22130418965083
12.221304189616928
12.221304189583028
12.221304189549134
12.221304189515243
12.221304189481376
12.2213041894475
12.221304189413638
12.221304189379797
12.221304189345945
12.221304189312107
12.221304189278275
12.221304189244448
12.221304189210626
12.221304189176823
12.221304189143027
12.221304189109222
12.221304189075443
12.221304189041657
12.221304189007881
12.221304188974116
12.221304188940362
12.221304188906602
12.221304188872868
12.221304188839133
12.221304188805396
12.221304188771676
12.221304188737966
12.221304188704268
12.221304188670564
12.221304188636873
12.221304188603183
12.221304188569496
12.221304188535832
12.22130418850217
12.221304188468517
12.221304188434862
12.221304188401222
12.221304188367588
12.221304188333965
12.221304188300346
12.22130418826673
12.22130418823313
12.22130418819953
12.221304188165943
12.221304188132354
12.221304188098783
12.221304188065218
12.22130418803165
12.221304187998099
12.221304187964549
12.221304187931008
12.221304187897488
12.221304187863955
12.22130418783044
12.221304187796932
12.221304187763433
12.221304187729936
12.22130418769644
12.22130418766296
12.221304187629494
12.221304187596022
12.221304187562563
12.22130418752912
12.221304187495665
12.221304187462229
12.221304187428796
12.221304187395374
12.22130418736196
12.221304187328547
12.221304187295155
12.221304187261756
12.221304187228366
12.221304187194988
12.22130418716162
12.22130418712825
12.221304187094894
12.22130418706154
12.221304187028203
12.221304186994875
12.221304186961532
12.221304186928213
12.2213041868949
12.221304186861596
12.22130418682829
12.221304186795003
12.221304186761719
12.221304186728442
12.221304186695171
12.221304186661904
12.22130418662865
12.221304186595397
12.221304186562158
12.221304186528918
12.221304186495694
12.221304186462481
12.221304186429261
12.221304186396058
12.221304186362854
12.221304186329661
12.221304186296482
12.221304186263307
12.221304186230139
12.22130418619697
12.221304186163813
12.22130418613067
12.221304186097527
12.221304186064392
12.221304186031263
12.221304185998141
12.221304185965032
12.221304185931928
12.221304185898832
12.221304185865735
12.22130418583266
12.221304185799585
12.221304185766513
12.221304185733445
12.221304185700388
12.221304185667348
12.221304185634299
12.221304185601273
12.221304185568247
12.221304185535224
12.221304185502214
12.22130418546921
12.221304185436216
12.221304185403213
12.221304185370235
12.221304185337265
12.221304185304286
12.221304185271334
12.221304185238381
12.221304185205433
12.221304185172492
12.22130418513956
12.22130418510663
12.22130418507371
12.2213041850408
12.221304185007899
12.221304184975
12.22130418494211
12.22130418490923
12.22130418487635
12.22130418484348
12.221304184810611
12.221304184777761
12.221304184744914
12.221304184712073
12.22130418467925
12.221304184646412
12.221304184613595
12.221304184580783
12.221304184547979
12.221304184515182
12.221304184482396
12.221304184449604
12.22130418441683
12.221304184384067
12.2213041843513
12.221304184318544
12.221304184285795
12.221304184253063
12.22130418422033
12.2213041841876
12.221304184154883
12.221304184122166
12.22130418408946
12.221304184056763
12.221304184024078
12.221304183991393
12.221304183958708
12.221304183926039
12.221304183893382
12.221304183860726
12.221304183828078
12.221304183795436
12.2213041837628
12.221304183730169
12.221304183697551
12.221304183664943
12.221304183632341
12.221304183599738
12.221304183567147
12.221304183534556
12.221304183501985
12.221304183469412
12.221304183436846
12.221304183404293
12.221304183371737
12.221304183339203
12.221304183306671
12.221304183274137
12.221304183241616
12.221304183209106
12.221304183176592
12.22130418314409
12.221304183111599
12.221304183079113
12.221304183046637
12.221304183014164
12.221304182981699
12.221304182949238
12.221304182916786
12.221304182884346
12.221304182851911
12.221304182819484
12.221304182787057
12.221304182754649
12.221304182722232
12.221304182689835
12.221304182657438
12.221304182625042
12.221304182592668
12.221304182560294
12.221304182527932
12.221304182495572
12.221304182463218
12.221304182430876
12.221304182398537
12.22130418236621
12.221304182333892
12.221304182301566
12.221304182269257
12.221304182236954
12.221304182204657
12.22130418217237
12.221304182140088
12.221304182107817
12.221304182075546
12.22130418204328
12.221304182011023
12.221304181978782
12.221304181946538
12.221304181914308
12.22130418188209
12.221304181849867
12.221304181817652
12.221304181785445
12.221304181753247
12.22130418172107
12.221304181688875
12.221304181656702
12.221304181624527
12.221304181592364
12.221304181560203
12.22130418152806
12.22130418149592
12.221304181463783
12.221304181431652
12.221304181399537
12.221304181367417
12.221304181335304
12.221304181303216
12.221304181271119
12.221304181239034
12.221304181206955
12.221304181174883
12.221304181142811
12.22130418111076
12.22130418107871
12.221304181046655
12.221304181014617
12.221304180982592
12.221304180950568
12.221304180918544
12.22130418088654
12.221304180854531
12.221304180822544
12.221304180790554
12.221304180758572
12.221304180726596
12.22130418069463
12.221304180662674
12.221304180630712
12.221304180598766
12.221304180566824
12.221304180534894
12.22130418050296
12.221304180471044
12.221304180439132
12.221304180407225
12.22130418037533
12.22130418034344
12.22130418031155
12.221304180279676
12.2213041802478
12.221304180215935
12.22130418018408
12.221304180152227
12.22130418012038
12.221304180088547
12.221304180056721
12.221304180024903
12.221304179993082
12.221304179961276
12.221304179929476
12.221304179897679
12.221304179865886
12.221304179834103
12.221304179802333
12.221304179770561
12.221304179738796
12.221304179707047
12.221304179675297
12.221304179643566
12.221304179611831
12.221304179580107
12.221304179548381
12.221304179516672
12.221304179484967
12.221304179453263
12.221304179421573
12.221304179389895
12.22130417935821
12.221304179326536
12.221304179294872
12.221304179263218
12.22130417923157
12.221304179199922
12.221304179168289
12.221304179136657
12.221304179105047
12.221304179073414
12.221304179041805
12.221304179010211
12.221304178978611
12.221304178947024
12.22130417891544
12.221304178883866
12.221304178852291
12.22130417882073
12.221304178789179
12.221304178757634
12.221304178726093
12.221304178694565
12.22130417866303
12.22130417863151
12.221304178599999
12.22130417856849
12.221304178536988
12.221304178505505
12.221304178474012
12.221304178442535
12.221304178411058
12.221304178379592
12.221304178348138
12.221304178316688
12.221304178285243
12.2213041782538
12.221304178222368
12.221304178190945
12.221304178159526
12.221304178128117
12.22130417809671
12.221304178065315
12.221304178033918
12.221304178002542
12.221304177971161
12.221304177939793
12.221304177908435
12.22130417787707
12.221304177845724
12.221304177814384
12.221304177783047
12.221304177751714
12.221304177720391
12.221304177689074
12.221304177657766
12.221304177626468
12.221304177595174
12.221304177563884
12.2213041775326
12.22130417750133
12.221304177470056
12.221304177438794
12.221304177407545
12.221304177376295
12.221304177345047
12.221304177313815
12.221304177282594
12.221304177251367
12.221304177220155
12.221304177188957
12.221304177157748
12.221304177126559
12.22130417709537
12.221304177064189
12.22130417703302
12.221304177001851
12.22130417697069
12.221304176939542
12.22130417690839
12.221304176877247
12.221304176846116
12.221304176814991
12.221304176783878
12.221304176752756
12.221304176721652
12.221304176690557
12.22130417665947
12.221304176628378
12.2213041765973
12.221304176566232
12.221304176535165
12.221304176504109
12.221304176473048
12.221304176441999
12.221304176410973
12.221304176379936
12.221304176348914
12.221304176317894
12.221304176286884
12.22130417625588
12.221304176224878
12.221304176193886
12.22130417616291
12.221304176131932
12.221304176100958
12.22130417606999
12.221304176039038
12.22130417600809
12.22130417597715
12.221304175946205
12.221304175915275
12.22130417588435
12.221304175853428
12.221304175822521
12.221304175791609
12.221304175760725
12.22130417572983
12.22130417569895
12.22130417566807
12.221304175637195
12.221304175606328
12.221304175575483
12.22130417554463
12.22130417551379
12.22130417548295
12.22130417545213
12.221304175421292
12.22130417539048
12.22130417535967
12.221304175328864
12.221304175298062
12.22130417526728
12.221304175236499
12.221304175205717
12.221304175174954
12.221304175144187
12.221304175113435
12.221304175082683
12.221304175051937
12.221304175021205
12.221304174990468
12.221304174959752
12.221304174929033
12.221304174898327
12.221304174867623
12.221304174836918
12.221304174806233
12.221304174775552
12.221304174744878
12.221304174714197
12.221304174683542
12.221304174652886
12.221304174622238
12.221304174591587
12.221304174560956
12.221304174530315
12.2213041744997
12.221304174469083
12.22130417443847
12.221304174407868
12.22130417437727
12.22130417434668
12.221304174316092
12.221304174285525
12.221304174254948
12.221304174224384
12.221304174193836
12.221304174163286
12.221304174132742
12.2213041741022
12.22130417407167
12.221304174041144
12.221304174010628
12.221304173980124
12.221304173949616
12.22130417391912
12.221304173888633
12.221304173858142
12.221304173827667
12.221304173797199
12.221304173766727
12.221304173736277
12.22130417370582
12.221304173675378
12.221304173644944
12.221304173614506
12.221304173584084
12.221304173553666
12.22130417352326
12.221304173492856
12.221304173462459
12.221304173432058
12.22130417340168
12.221304173371305
12.221304173340929
12.221304173310566
12.221304173280206
12.221304173249855
12.221304173219503
12.221304173189164
12.221304173158838
12.221304173128514
12.221304173098192
12.22130417306788
12.221304173037574
12.221304173007272
12.221304172976977
12.22130417294669
12.221304172916412
12.221304172886137
12.221304172855877
12.221304172825615
12.221304172795355
12.22130417276511
12.221304172734875
12.221304172704642
12.221304172674415
12.221304172644187
12.221304172613982
12.22130417258378
12.221304172553575
12.221304172523382
12.221304172493188
12.22130417246301
12.22130417243283
12.221304172402666
12.221304172372507
12.22130417234235
12.221304172312204

12.221304172282055
12.221304172251925
12.221304172221792
12.221304172191674
12.221304172161561
12.221304172131449
12.22130417210135
12.221304172071251
12.221304172041165
12.221304172011079
12.221304171981
12.221304171950935
12.221304171920872
12.221304171890814
12.221304171860764
12.221304171830715
12.221304171800675
12.221304171770653
12.22130417174063
12.221304171710614
12.22130417168059
12.2213041716506
12.221304171620595
12.221304171590601
12.221304171560615
12.221304171530633
12.221304171500663
12.221304171470694
12.221304171440742
12.221304171410782
12.221304171380842
12.221304171350898
12.221304171320964
12.22130417129104
12.221304171261123
12.221304171231203
12.2213041712013
12.2213041711714
12.221304171141504
12.221304171111612
12.221304171081739
12.22130417105186
12.221304171021988
12.221304170992136
12.221304170962274
12.221304170932429
12.221304170902583
12.22130417087275
12.221304170842924
12.221304170813095
12.22130417078328
12.22130417075347
12.221304170723672
12.221304170693873
12.221304170664077
12.221304170634287
12.22130417060452
12.221304170574744
12.22130417054498
12.221304170515221
12.221304170485473
12.221304170455726
12.221304170425984
12.221304170396248
12.221304170366526
12.221304170336802
12.221304170307096
12.221304170277392
12.221304170247684
12.221304170217996
12.221304170188306
12.221304170158623
12.221304170128953
12.22130417009928
12.22130417006963
12.221304170039971
12.221304170010315
12.221304169980671
12.221304169951045
12.221304169921408
12.221304169891797
12.221304169862172
12.221304169832559
12.22130416980296
12.221304169773358
12.221304169743773
12.221304169714193
12.221304169684606
12.221304169655033
12.221304169625475
12.221304169595916
12.221304169566356
12.221304169536815
12.221304169507277
12.221304169477744
12.221304169448215
12.221304169418694
12.221304169389185
12.221304169359678
12.221304169330166
12.221304169300678
12.221304169271193
12.221304169241707
12.221304169212232
12.221304169182762
12.221304169153296
12.221304169123849
12.221304169094397
12.221304169064943
12.221304169035518
12.221304169006089
12.221304168976664
12.221304168947242
12.221304168917834
12.221304168888427
12.221304168859032
12.221304168829635
12.221304168800247
12.22130416877087
12.221304168741497
12.221304168712123
12.221304168682764
12.221304168653417
12.221304168624068
12.221304168594724
12.22130416856539
12.221304168536061
12.221304168506741
12.221304168477424
12.221304168448112
12.221304168418815
12.221304168389517
12.221304168360225
12.221304168330942
12.221304168301662
12.22130416827239
12.22130416824313
12.221304168213871
12.221304168184613
12.221304168155372
12.221304168126128
12.221304168096895
12.221304168067672
12.221304168038444
12.221304168009235
12.221304167980026
12.221304167950832
12.221304167921637
12.221304167892443
12.221304167863265
12.221304167834084
12.221304167804913
12.221304167775749
12.221304167746586
12.221304167717438
12.221304167688304
12.22130416765916
12.221304167630022
12.2213041676009
12.22130416757178
12.22130416754267
12.221304167513567
12.22130416748446
12.221304167455363
12.22130416742628
12.221304167397195
12.221304167368123
12.221304167339058
12.221304167309997
12.221304167280937
12.221304167251889
12.221304167222842
12.221304167193802
12.221304167164778
12.221304167135747
12.221304167106728
12.221304167077724
12.221304167048713
12.221304167019717
12.221304166990722
12.221304166961733
12.221304166932754
12.221304166903778
12.221304166874816
12.221304166845847
12.221304166816896
12.22130416678795
12.221304166759003
12.22130416673007
12.22130416670114
12.221304166672217
12.221304166643298
12.221304166614383
12.221304166585478
12.221304166556578
12.221304166527684
12.22130416649881
12.221304166469915
12.22130416644105
12.221304166412176
12.22130416638331
12.221304166354463
12.221304166325615
12.22130416629677
12.221304166267936
12.221304166239113
12.221304166210277
12.221304166181465
12.221304166152652
12.221304166123847
12.22130416609505
12.22130416606626
12.22130416603747
12.221304166008693
12.22130416597992
12.221304165951144
12.221304165922389
12.221304165893637
12.221304165864886
12.221304165836141
12.221304165807409
12.221304165778678
12.22130416574995
12.221304165721234
12.221304165692521
12.221304165663819
12.221304165635116
12.221304165606425
12.221304165577745
12.221304165549059
12.221304165520385
12.221304165491716
12.221304165463053
12.2213041654344
12.221304165405758
12.221304165377104
12.221304165348476
12.221304165319847
12.221304165291215
12.221304165262604
12.221304165233988
12.221304165205385
12.22130416517679
12.221304165148197
12.221304165119605
12.221304165091027
12.221304165062447
12.22130416503388
12.221304165005323
12.22130416497677
12.22130416494821
12.221304164919667
12.221304164891134
12.221304164862604
12.221304164834079
12.221304164805561
12.221304164777049
12.221304164748545
12.22130416472004
12.221304164691546
12.22130416466305
12.221304164634581
12.221304164606101
12.221304164577635
12.221304164549172
12.22130416452071
12.221304164492262
12.221304164463817
12.221304164435384
12.221304164406943
12.221304164378518
12.221304164350101
12.221304164321689
12.221304164293278
12.221304164264877
12.22130416423648
12.221304164208089
12.22130416417971
12.22130416415133
12.221304164122964
12.221304164094597
12.221304164066241
12.221304164037889
12.22130416400954
12.221304163981202
12.221304163952873
12.221304163924543
12.221304163896223
12.221304163867899
12.221304163839601
12.221304163811295
12.221304163782996
12.22130416375471
12.221304163726423
12.22130416369814
12.221304163669876
12.221304163641602
12.221304163613343
12.221304163585097
12.221304163556846
12.221304163528599
12.221304163500372
12.221304163472144
12.221304163443907
12.2213041634157
12.221304163387487
12.221304163359282
12.221304163331087
12.221304163302896
12.221304163274704
12.221304163246526
12.221304163218356
12.221304163190176
12.221304163162023
12.221304163133864
12.221304163105717
12.221304163077578
12.221304163049433
12.221304163021296
12.221304162993182
12.22130416296506
12.221304162936946
12.221304162908831
12.22130416288074
12.221304162852649
12.221304162824547
12.221304162796468
12.221304162768394
12.221304162740322
12.221304162712256
12.22130416268421
12.221304162656146
12.221304162628101
12.221304162600065
12.221304162572029
12.221304162544005
12.221304162515981
12.221304162487963
12.221304162459953
12.221304162431949
12.221304162403964
12.221304162375962
12.221304162347973
12.221304162320008
12.221304162292025
12.221304162264053
12.221304162236095
12.221304162208138
12.221304162180193
12.221304162152247
12.22130416212431
12.221304162096382
12.221304162068456
12.221304162040537
12.221304162012625
12.221304161984719
12.22130416195682
12.221304161928929
12.221304161901042
12.221304161873155
12.221304161845278
12.221304161817411
12.221304161789545
12.221304161761687
12.221304161733839
12.22130416170599
12.221304161678155
12.22130416165032
12.221304161622484
12.221304161594674
12.221304161566854
12.221304161539049
12.221304161511245
12.221304161483445
12.221304161455645
12.221304161427863
12.221304161400086
12.221304161372315
12.22130416134454
12.221304161316786
12.221304161289037
12.221304161261278
12.221304161233537
12.2213041612058
12.221304161178072
12.221304161150336
12.221304161122626
12.221304161094904
12.221304161067206
12.221304161039503
12.221304161011812
12.22130416098412
12.221304160956432
12.221304160928756
12.221304160901084
12.221304160873425
12.221304160845765
12.221304160818107
12.221304160790462
12.221304160762822
12.221304160735183
12.221304160707552
12.221304160679933
12.221304160652318
12.221304160624706
12.221304160597096
12.221304160569503
12.221304160541909
12.221304160514324
12.22130416048674
12.221304160459168
12.221304160431599
12.221304160404028
12.221304160376475
12.22130416034893
12.221304160321377
12.221304160293837
12.221304160266307
12.221304160238786
12.221304160211254
12.22130416018374
12.221304160156228
12.22130416012873
12.221304160101235
12.22130416007374
12.22130416004625
12.221304160018777
12.221304159991302
12.221304159963832
12.22130415993637
12.221304159908916
12.221304159881466
12.221304159854032
12.221304159826584
12.221304159799157
12.221304159771728
12.221304159744312
12.221304159716892
12.221304159689492
12.221304159662084
12.221304159634693
12.221304159607296
12.221304159579912
12.221304159552536
12.221304159525166
12.2213041594978
12.221304159470437
12.221304159443084
12.22130415941573
12.22130415938839

12.22130415936106
12.22130415933372
12.221304159306397
12.221304159279079
12.221304159251767
12.221304159224456
12.221304159197151
12.221304159169865
12.221304159142576
12.221304159115286
12.221304159088008
12.221304159060743
12.22130415903347
12.221304159006216
12.221304158978967
12.221304158951707
12.221304158924472
12.221304158897235
12.221304158870009
12.221304158842777
12.221304158815569
12.221304158788346
12.221304158761146
12.221304158733949
12.221304158706745
12.22130415867956
12.221304158652389
12.221304158625202
12.221304158598029
12.22130415857087
12.2213041585437
12.221304158516546
12.221304158489403
12.221304158462251
12.22130415843513
12.221304158407994
12.221304158380871
12.221304158353757
12.22130415832664
12.221304158299537
12.22130415827243
12.221304158245346
12.221304158218254
12.221304158191167
12.22130415816409
12.221304158137025
12.221304158109962
12.221304158082885
12.221304158055844
12.2213041580288
12.22130415800176
12.221304157974721
12.221304157947692
12.221304157920668
12.22130415789365
12.221304157866626
12.221304157839617
12.221304157812629
12.221304157785628
12.22130415775864
12.221304157731668
12.221304157704674
12.221304157677709
12.221304157650744
12.221304157623788
12.221304157596833
12.221304157569893
12.221304157542946
12.221304157516009
12.22130415748908
12.22130415746215
12.221304157435226
12.221304157408326
12.221304157381416
12.221304157354513
12.221304157327618
12.221304157300727
12.221304157273844
12.221304157246967
12.221304157220088
12.221304157193227
12.221304157166365
12.221304157139508
12.22130415711266
12.221304157085818
12.22130415705898
12.221304157032156
12.221304157005331
12.221304156978512
12.221304156951696
12.221304156924887
12.221304156898077
12.22130415687129
12.221304156844498
12.221304156817716
12.221304156790932
12.221304156764157
12.221304156737398
12.221304156710628
12.221304156683882
12.221304156657117
12.221304156630389
12.22130415660365
12.221304156576924
12.221304156550184
12.22130415652347
12.221304156496755
12.22130415647004
12.221304156443335
12.221304156416638
12.221304156389944
12.221304156363265
12.221304156336586
12.22130415630991
12.221304156283237
12.221304156256572
12.221304156229923
12.22130415620327
12.221304156176625
12.221304156149984
12.221304156123347
12.221304156096723
12.221304156070104
12.221304156043487
12.221304156016876
12.22130415599027
12.221304155963665
12.221304155937075
12.221304155910484
12.221304155883905
12.22130415585733
12.221304155830762
12.22130415580419
12.221304155777634
12.221304155751085
12.221304155724539
12.221304155697993
12.221304155671458
12.221304155644933
12.221304155618402
12.22130415559189
12.221304155565376
12.22130415553887
12.221304155512366
12.221304155485871
12.221304155459382
12.221304155432897
12.22130415540642
12.221304155379949
12.221304155353485
12.221304155327017
12.22130415530056
12.221304155274114
12.221304155247669
12.221304155221231
12.2213041551948
12.221304155168372
12.221304155141947
12.22130415511554
12.221304155089125
12.22130415506272
12.221304155036329
12.221304155009937
12.221304154983539
12.221304154957169
12.22130415493079
12.221304154904418
12.221304154878064
12.221304154851708
12.221304154825349
12.221304154799002
12.221304154772668
12.221304154746324
12.221304154719995
12.221304154693678
12.221304154667356
12.22130415464105
12.22130415461474
12.221304154588442
12.22130415456214
12.221304154535861
12.221304154509566
12.221304154483294
12.221304154457021
12.221304154430754
12.2213041544045
12.221304154378235
12.22130415435199
12.221304154325741
12.221304154299501
12.221304154273277
12.221304154247042
12.221304154220832
12.221304154194614
12.221304154168406
12.221304154142196
12.221304154115998
12.22130415408981
12.221304154063626
12.221304154037439
12.221304154011262
12.221304153985102
12.221304153958933
12.221304153932776
12.22130415390662
12.221304153880473
12.221304153854334
12.221304153828196
12.221304153802063
12.221304153775938
12.221304153749822
12.221304153723716
12.2213041536976
12.221304153671506
12.221304153645399
12.221304153619315
12.221304153593232
12.221304153567154
12.221304153541082
12.221304153515018
12.221304153488948
12.22130415346289
12.221304153436845
12.221304153410793
12.221304153384766
12.221304153358721
12.221304153332701
12.221304153306676
12.22130415328066
12.221304153254643
12.221304153228644
12.221304153202642
12.22130415317665
12.221304153150657
12.221304153124679
12.221304153098703
12.22130415307273
12.221304153046757
12.2213041530208
12.221304152994849
12.2213041529689
12.221304152942945
12.221304152917021
12.221304152891081
12.221304152865157
12.221304152839233
12.221304152813321
12.221304152787406
12.221304152761505
12.221304152735604
12.221304152709719
12.221304152683826
12.221304152657945
12.221304152632072
12.221304152606203
12.221304152580336
12.221304152554476
12.221304152528623
12.221304152502787
12.22130415247694
12.22130415245109
12.221304152425269
12.221304152399444
12.221304152373623
12.221304152347804
12.221304152321993
12.221304152296199
12.2213041522704
12.221304152244606
12.221304152218819
12.221304152193039
12.221304152167258
12.2213041521415
12.221304152115728
12.221304152089976
12.221304152064222
12.221304152038476
12.221304152012726
12.221304151986997
12.22130415196127
12.221304151935541
12.22130415190982
12.221304151884103
12.2213041518584
12.221304151832697
12.221304151807002
12.221304151781304
12.221304151755623
12.22130415172994
12.221304151704269
12.221304151678604
12.221304151652943
12.221304151627281
12.221304151601622
12.221304151575973
12.22130415155034
12.221304151524711
12.221304151499076
12.221304151473447
12.221304151447827
12.221304151422213
12.221304151396613
12.221304151371005
12.221304151345414
12.221304151319815
12.221304151294234
12.221304151268653
12.221304151243077
12.221304151217511
12.221304151191946
12.221304151166393
12.221304151140835
12.221304151115291
12.221304151089743
12.221304151064212
12.221304151038693
12.22130415101316
12.22130415098764
12.221304150962125
12.221304150936616
12.221304150911115
12.221304150885626
12.221304150860126
12.221304150834646
12.22130415080916
12.221304150783686
12.221304150758225
12.22130415073275
12.221304150707294
12.221304150681847
12.221304150656398
12.221304150630958
12.221304150605521
12.22130415058009
12.22130415055467
12.22130415052925
12.221304150503828
12.221304150478424
12.221304150453015
12.221304150427626
12.221304150402231
12.221304150376847
12.221304150351465
12.221304150326095
12.221304150300723
12.221304150275351
12.221304150249996
12.221304150224638
12.221304150199293
12.221304150173951
12.221304150148613
12.22130415012328
12.221304150097962
12.221304150072639
12.221304150047326
12.221304150022013
12.221304149996714
12.221304149971417
12.221304149946123
12.22130414992083
12.22130414989555
12.221304149870273
12.221304149845004
12.221304149819733
12.221304149794483
12.221304149769225
12.221304149743977
12.22130414971873
12.221304149693495
12.221304149668265
12.221304149643036
12.221304149617806
12.221304149592598
12.221304149567384
12.22130414954218
12.22130414951698
12.221304149491788
12.221304149466604
12.221304149441416
12.221304149416238
12.221304149391063
12.221304149365896
12.221304149340735
12.221304149315584
12.221304149290432
12.221304149265285
12.221304149240147
12.221304149215008
12.221304149189884
12.221304149164755
12.22130414913964
12.221304149114529
12.221304149089423
12.221304149064329
12.22130414903922
12.22130414901414
12.221304148989056
12.221304148963972
12.221304148938895
12.221304148913829
12.22130414888877
12.221304148863704
12.221304148838657
12.221304148813612
12.221304148788569
12.221304148763526
12.221304148738495
12.221304148713482
12.221304148688452
12.221304148663446
12.221304148638431
12.221304148613424
12.221304148588427
12.22130414856343
12.221304148538445
12.221304148513472
12.221304148488489
12.22130414846352
12.221304148438557
12.221304148413594
12.221304148388638
12.221304148363695
12.221304148338744
12.221304148313813
12.221304148288878
12.221304148263956
12.221304148239023
12.221304148214113
12.221304148189201
12.221304148164288
12.22130414813939
12.221304148114498
12.221304148089603
12.221304148064718
12.221304148039843
12.221304148014971
12.221304147990102
12.221304147965242
12.221304147940376
12.22130414791553
12.221304147890681
12.221304147865837
12.221304147841005
12.221304147816177
12.22130414779135
12.221304147766533
12.221304147741717
12.221304147716905
12.221304147692102
12.221304147667302
12.221304147642504
12.221304147617731
12.221304147592948
12.221304147568159
12.221304147543401
12.22130414751863
12.22130414749387
12.221304147469118
12.221304147444366
12.221304147419612
12.221304147394886
12.22130414737015
12.22130414734542
12.22130414732069
12.22130414729598
12.221304147271269
12.221304147246569
12.221304147221865
12.221304147197158
12.221304147172477
12.221304147147782
12.221304147123105
12.221304147098431
12.221304147073768
12.2213041470491
12.221304147024442
12.221304146999792
12.221304146975136
12.221304146950503
12.221304146925858
12.221304146901229
12.221304146876605
12.221304146851985
12.221304146827368
12.221304146802764
12.221304146778145
12.22130414675355
12.221304146728956
12.221304146704364
12.221304146679781
12.221304146655205
12.221304146630635
12.221304146606071
12.221304146581502
12.221304146556943
12.221304146532391
12.221304146507846
12.221304146483305
12.221304146458769
12.221304146434234
12.221304146409716
12.221304146385199
12.221304146360676
12.22130414633617
12.221304146311672
12.221304146287169
12.221304146262675
12.221304146238191
12.221304146213702
12.221304146189222
12.221304146164751
12.22130414614029
12.221304146115829
12.221304146091368

12.221304146066922
12.221304146042478
12.221304146018037
12.221304145993605
12.221304145969171
12.22130414594475
12.221304145920332
12.221304145895918
12.221304145871509
12.221304145847105
12.221304145822707
12.221304145798316
12.221304145773919
12.221304145749547
12.221304145725163
12.221304145700795
12.22130414567643
12.221304145652072
12.22130414562771
12.22130414560337
12.221304145579019
12.221304145554681
12.221304145530345
12.22130414550601
12.221304145481694
12.221304145457372
12.221304145433063
12.221304145408752
12.22130414538446
12.221304145360163
12.221304145335864
12.22130414531158
12.221304145287299
12.22130414526302
12.221304145238749
12.22130414521448
12.221304145190222
12.22130414516597
12.221304145141712
12.221304145117479
12.221304145093232
12.221304145069006
12.22130414504477
12.221304145020545
12.221304144996333
12.221304144972107
12.221304144947911
12.221304144923705
12.221304144899507
12.221304144875322
12.221304144851135
12.221304144826941
12.22130414480277
12.221304144778598
12.221304144754436
12.221304144730269
12.221304144706123
12.221304144681978
12.221304144657816
12.221304144633683
12.221304144609551
12.221304144585421
12.221304144561298
12.221304144537184
12.221304144513063
12.221304144488952
12.22130414446486
12.221304144440762
12.221304144416665
12.221304144392576
12.221304144368498
12.221304144344417
12.221304144320348
12.22130414429628
12.221304144272217
12.221304144248164
12.221304144224117
12.221304144200072
12.22130414417603
12.221304144151993
12.221304144127961
12.221304144103938
12.221304144079925
12.221304144055901
12.221304144031896
12.221304144007886
12.221304143983897
12.221304143959903
12.221304143935917
12.221304143911926
12.221304143887952
12.22130414386398
12.221304143840019
12.221304143816058
12.221304143792096
12.221304143768148
12.221304143744193
12.221304143720259
12.221304143696317
12.221304143672393
12.221304143648464
12.221304143624543
12.22130414360062
12.221304143576722
12.221304143552812
12.221304143528915
12.221304143505023
12.221304143481133
12.22130414345724
12.221304143433368
12.22130414340949
12.221304143385622
12.221304143361762
12.221304143337901
12.221304143314049
12.221304143290197
12.221304143266366
12.221304143242529
12.22130414321869
12.22130414319486
12.221304143171041
12.221304143147224
12.221304143123417
12.221304143099609
12.221304143075805
12.22130414305201
12.221304143028219
12.221304143004428
12.221304142980644
12.221304142956871
12.2213041429331
12.221304142909336
12.22130414288558
12.221304142861825
12.22130414283808
12.221304142814331
12.221304142790588
12.221304142766861
12.22130414274313
12.221304142719413
12.22130414269569
12.221304142671974
12.221304142648265
12.221304142624565
12.221304142600863
12.221304142577162
12.221304142553487
12.2213041425298
12.221304142506114
12.221304142482449
12.221304142458786
12.221304142435118
12.221304142411459
12.221304142387813
12.221304142364156
12.221304142340522
12.221304142316889
12.221304142293253
12.221304142269629
12.221304142246009
12.221304142222383
12.221304142198777
12.22130414217517
12.221304142151572
12.22130414212798
12.221304142104385
12.221304142080799
12.221304142057214
12.22130414203365
12.221304142010077
12.221304141986511
12.221304141962953
12.2213041419394
12.221304141915848
12.221304141892304
12.221304141868764
12.22130414184523
12.2213041418217
12.221304141798173
12.221304141774649
12.221304141751144
12.221304141727632
12.221304141704135
12.22130414168063
12.221304141657141
12.221304141633652
12.221304141610164
12.221304141586685
12.221304141563213
12.221304141539752
12.221304141516294
12.221304141492826
12.221304141469382
12.221304141445923
12.22130414142248
12.221304141399052
12.221304141375615
12.221304141352187
12.221304141328766
12.221304141305348
12.22130414128194
12.221304141258535
12.221304141235136
12.221304141211741
12.221304141188341
12.22130414116496
12.221304141141577
12.221304141118198
12.221304141094828
12.221304141071464
12.221304141048098
12.221304141024735
12.221304141001392
12.221304140978047
12.221304140954706
12.221304140931371
12.221304140908039
12.221304140884715
12.221304140861399
12.22130414083808
12.221304140814766
12.221304140791464
12.22130414076816
12.221304140744868
12.221304140721582
12.221304140698289
12.22130414067501
12.22130414065173
12.221304140628469
12.2213041406052
12.22130414058194
12.221304140558685
12.221304140535443
12.221304140512187
12.221304140488948
12.22130414046572
12.221304140442491
12.22130414041926
12.221304140396038
12.22130414037283
12.221304140349618
12.22130414032642
12.221304140303216
12.221304140280024
12.221304140256834
12.22130414023365
12.221304140210469
12.221304140187291
12.221304140164124
12.221304140140964
12.221304140117796
12.221304140094645
12.221304140071492
12.221304140048355
12.221304140025216
12.221304140002081
12.221304139978955
12.221304139955828
12.22130413993271
12.2213041399096
12.221304139886492
12.22130413986338
12.221304139840285
12.22130413981719
12.221304139794107
12.221304139771016
12.221304139747938
12.221304139724868
12.221304139701791
12.221304139678736
12.221304139655674
12.221304139632622
12.221304139609572
12.221304139586524
12.221304139563493
12.221304139540457
12.221304139517423
12.221304139494402
12.22130413947138
12.221304139448371
12.22130413942536
12.221304139402358
12.221304139379361
12.221304139356366
12.221304139333371
12.22130413931039
12.221304139287412
12.221304139264435
12.221304139241472
12.221304139218502
12.221304139195546
12.221304139172592
12.221304139149645
12.221304139126705
12.221304139103758
12.221304139080832
12.221304139057892
12.22130413903497
12.221304139012057
12.221304138989133
12.221304138966234
12.22130413894333
12.221304138920429
12.22130413889753
12.221304138874649
12.221304138851767
12.221304138828883
12.221304138806
12.221304138783132
12.221304138760273
12.221304138737407
12.221304138714562
12.221304138691705
12.221304138668865
12.22130413864602
12.221304138623186
12.221304138600361
12.221304138577537
12.221304138554716
12.2213041385319
12.2213041385091
12.221304138486282
12.221304138463484
12.221304138440697
12.221304138417903
12.22130413839512
12.221304138372332
12.221304138349561
12.221304138326785
12.221304138304024
12.221304138281264
12.221304138258509
12.22130413823576
12.221304138213013
12.221304138190277
12.221304138167527
12.221304138144808
12.221304138122086
12.221304138099358
12.221304138076638
12.22130413805393
12.221304138031227
12.221304138008525
12.221304137985824
12.22130413796314
12.221304137940447
12.221304137917771
12.2213041378951
12.221304137872425
12.221304137849753
12.221304137827094
12.221304137804434
12.221304137781782
12.22130413775913
12.221304137736494
12.221304137713863
12.221304137691227
12.221304137668598
12.221304137645976
12.22130413762336
12.221304137600747
12.221304137578135
12.221304137555538
12.221304137532934
12.22130413751034
12.221304137487754
12.221304137465175
12.221304137442594
12.221304137420026
12.22130413739745
12.221304137374881
12.221304137352329
12.22130413732977
12.221304137307229
12.221304137284683
12.221304137262141
12.221304137239608
12.221304137217086
12.221304137194561
12.221304137172035
12.221304137149517
12.221304137127014
12.221304137104507
12.221304137082004
12.221304137059509
12.221304137037016
12.221304137014538
12.221304136992048
12.221304136969577
12.22130413694711
12.221304136924637
12.22130413690218
12.22130413687972
12.221304136857276
12.221304136834823
12.221304136812384
12.221304136789952
12.221304136767522
12.221304136745086
12.221304136722667
12.221304136700246
12.221304136677837
12.221304136655434
12.221304136633032
12.221304136610627
12.221304136588238
12.221304136565852
12.221304136543466
12.221304136521088
12.221304136498714
12.221304136476345
12.221304136453982
12.221304136431622
12.221304136409259
12.221304136386921
12.221304136364578
12.221304136342233
12.221304136319901
12.221304136297574
12.221304136275247
12.22130413625292
12.221304136230614
12.221304136208301
12.221304136185992
12.221304136163695
12.221304136141399
12.221304136119114
12.221304136096823
12.221304136074533
12.221304136052263
12.221304136029993
12.221304136007728
12.221304135985473
12.221304135963209
12.221304135940947
12.221304135918718
12.221304135896462
12.221304135874224

12.22130413585199
12.221304135829765
12.221304135807543
12.221304135785317
12.221304135763106
12.2213041357409
12.221304135718702
12.221304135696494
12.221304135674304
12.221304135652105
12.22130413562993
12.22130413560775
12.221304135585573
12.221304135563397
12.221304135541232
12.221304135519077
12.22130413549692
12.221304135474764
12.221304135452618
12.221304135430483
12.221304135408342
12.221304135386214
12.221304135364086
12.221304135341958
12.221304135319839
12.221304135297734
12.221304135275622
12.221304135253524
12.221304135231419
12.221304135209326
12.22130413518724
12.221304135165159
12.221304135143079
12.221304135121004
12.221304135098933
12.221304135076865
12.22130413505481
12.221304135032744
12.221304135010698
12.221304134988658
12.221304134966616
12.22130413494458
12.221304134922551
12.221304134900523
12.221304134878501
12.221304134856478
12.22130413483447
12.221304134812463
12.221304134790461
12.221304134768463
12.221304134746477
12.221304134724477
12.2213041347025
12.221304134680524
12.22130413465854
12.221304134636577
12.221304134614613
12.221304134592657
12.221304134570696
12.221304134548749
12.22130413452681
12.221304134504862
12.221304134482923
12.221304134461
12.221304134439071
12.221304134417151
12.221304134395227
12.221304134373318
12.221304134351417
12.221304134329506
12.221304134307616
12.221304134285718
12.22130413426383
12.221304134241947
12.221304134220063
12.221304134198196
12.22130413417632
12.221304134154462
12.221304134132597
12.221304134110747
12.221304134088893
12.221304134067047
12.221304134045209
12.22130413402337
12.221304134001542
12.221304133979718
12.22130413395789
12.221304133936068
12.221304133914256
12.221304133892454
12.221304133870651
12.221304133848848
12.221304133827065
12.221304133805278
12.221304133783493
12.221304133761711
12.22130413373993
12.22130413371816
12.221304133696401
12.221304133674643
12.221304133652875
12.22130413363113
12.221304133609385
12.221304133587653
12.221304133565903
12.22130413354417
12.22130413352245
12.221304133500727
12.221304133479007
12.221304133457295
12.22130413343558
12.22130413341388
12.221304133392186
12.221304133370486
12.221304133348806
12.221304133327113
12.221304133305441
12.221304133283766
12.221304133262086
12.221304133240414
12.221304133218757
12.221304133197094
12.221304133175456
12.221304133153803
12.22130413313216
12.221304133110525
12.221304133088891
12.221304133067266
12.221304133045638
12.221304133024022
12.221304133002404
12.22130413298079
12.221304132959185
12.221304132937584
12.221304132915995
12.221304132894396
12.221304132872822
12.221304132851232
12.22130413282966
12.221304132808088
12.221304132786523
12.22130413276495
12.221304132743398
12.221304132721848
12.221304132700299
12.221304132678753
12.221304132657204
12.221304132635677
12.221304132614145
12.221304132592621
12.221304132571099
12.221304132549585
12.221304132528067
12.221304132506566
12.221304132485066
12.221304132463565
12.221304132442073
12.221304132420585
12.221304132399105
12.221304132377618
12.22130413235615
12.221304132334684
12.221304132313215
12.221304132291756
12.221304132270296
12.22130413224885
12.221304132227395
12.221304132205958
12.221304132184526
12.221304132163091
12.221304132141672
12.221304132120242
12.221304132098819
12.221304132077407
12.221304132056
12.221304132034595
12.221304132013191
12.221304131991799
12.221304131970413
12.221304131949026
12.221304131927651
12.221304131906264
12.221304131884898
12.221304131863535
12.221304131842167
12.221304131820812
12.221304131799457
12.221304131778105
12.221304131756764
12.22130413173543
12.221304131714087
12.221304131692754
12.221304131671436
12.221304131650115
12.221304131628797
12.22130413160748
12.221304131586182
12.221304131564878
12.221304131543572
12.221304131522283
12.221304131500997
12.22130413147971
12.22130413145843
12.221304131437158
12.221304131415888
12.221304131394623
12.221304131373364
12.2213041313521
12.221304131330854
12.221304131309608
12.22130413128837
12.221304131267129
12.221304131245896
12.221304131224665
12.221304131203444
12.221304131182222
12.221304131161007
12.2213041311398
12.221304131118591
12.22130413109739
12.221304131076199
12.22130413105501
12.221304131033818
12.221304131012639
12.22130413099146
12.22130413097028
12.221304130949111
12.221304130927951
12.221304130906791
12.221304130885635
12.221304130864484
12.221304130843338
12.221304130822201
12.221304130801062
12.221304130779934
12.22130413075881
12.221304130737686
12.221304130716556
12.22130413069545
12.221304130674339
12.221304130653238
12.22130413063213
12.221304130611042
12.221304130589946
12.221304130568859
12.22130413054778
12.2213041305267
12.221304130505635
12.221304130484565
12.2213041304635
12.221304130442444
12.221304130421382
12.221304130400345
12.221304130379298
12.221304130358257
12.221304130337218
12.22130413031619
12.221304130295161
12.221304130274135
12.22130413025312
12.22130413023211
12.221304130211097
12.221304130190095
12.221304130169099
12.221304130148104
12.221304130127107
12.221304130106121
12.221304130085144
12.22130413006417
12.2213041300432
12.221304130022235
12.221304130001268
12.22130412998031
12.221304129959352
12.221304129938403
12.221304129917458
12.221304129896522
12.221304129875588
12.221304129854655
12.221304129833728
12.221304129812806
12.221304129791886
12.221304129770974
12.22130412975007
12.22130412972916
12.221304129708264
12.221304129687361
12.221304129666475
12.22130412964559
12.221304129624702
12.221304129603835
12.221304129582956
12.2213041295621
12.221304129541235
12.22130412952037
12.22130412949952
12.221304129478675
12.22130412945782
12.221304129436989
12.22130412941615
12.221304129395318
12.221304129374492
12.221304129353666
12.221304129332855
12.221304129312037
12.221304129291234
12.221304129270425
12.22130412924962
12.221304129228825
12.221304129208042
12.221304129187253
12.221304129166475
12.221304129145695
12.221304129124917
12.22130412910415
12.22130412908339
12.221304129062627
12.221304129041878
12.221304129021124
12.22130412900038
12.22130412897964
12.221304128958906
12.22130412893817
12.221304128917437
12.221304128896717
12.221304128875996
12.221304128855293
12.22130412883458
12.221304128813872
12.221304128793179
12.221304128772474
12.221304128751775
12.221304128731095
12.221304128710413
12.221304128689738
12.221304128669063
12.221304128648395
12.22130412862773
12.22130412860707
12.221304128586414
12.221304128565762
12.22130412854512
12.221304128524473
12.221304128503839
12.2213041284832
12.221304128462574
12.221304128441949
12.221304128421327
12.221304128400709
12.221304128380101
12.221304128359495
12.221304128338891
12.221304128318291
12.221304128297707
12.221304128277119
12.221304128256525
12.221304128235944
12.221304128215376
12.221304128194802
12.221304128174234
12.221304128153673
12.221304128133117
12.221304128112571
12.221304128092022
12.221304128071472
12.221304128050939
12.221304128030399
12.221304128009871
12.221304127989345
12.221304127968816
12.221304127948304
12.221304127927793
12.221304127907281
12.22130412788678
12.221304127866283
12.221304127845787
12.22130412782529
12.221304127804805
12.221304127784332
12.221304127763847
12.221304127743375
12.221304127722913
12.221304127702444
12.221304127681984
12.22130412766153
12.221304127641073
12.221304127620634
12.221304127600186
12.22130412757975
12.22130412755932
12.221304127538895
12.221304127518474
12.221304127498053
12.221304127477637
12.221304127457223
12.221304127436818
12.221304127416417
12.221304127396017
12.221304127375628
12.22130412735524
12.221304127334854
12.221304127314468
12.221304127294102
12.221304127273731
12.22130412725336
12.221304127233005
12.221304127212644
12.221304127192287
12.221304127171942
12.221304127151596
12.221304127131258
12.221304127110924
12.221304127090589
12.221304127070265
12.22130412704994
12.22130412702962
12.221304127009313
12.221304126989002
12.221304126968699
12.221304126948398
12.221304126928096
12.221304126907803
12.221304126887528
12.221304126867237
12.221304126846963
12.221304126826684
12.22130412680642
12.221304126786157
12.221304126765888
12.221304126745641
12.221304126725382
12.221304126705146
12.221304126684903
12.221304126664654
12.221304126644421
12.221304126624196
12.221304126603968
12.221304126583744
12.221304126563531
12.221304126543318
12.221304126523105
12.2213041265029
12.221304126482707
12.221304126462517
12.221304126442327
12.221304126422133
12.221304126401959
12.221304126381776
12.221304126361602
12.22130412634143
12.221304126321272
12.221304126301112
12.221304126280968
12.221304126260813
12.22130412624066
12.221304126220522
12.221304126200382
12.221304126180252
12.221304126160112
12.221304126140002
12.221304126119877
12.221304126099763
12.221304126079643
12.221304126059533
12.221304126039437
12.221304126019339
12.221304125999248
12.221304125979158
12.221304125959067
12.221304125938993
12.221304125918916
12.22130412589884
12.221304125878765
12.221304125858703
12.221304125838644
12.22130412581859
12.221304125798545
12.221304125778497
12.221304125758452
12.221304125738422
12.221304125718383
12.221304125698358
12.221304125678332
12.221304125658316
12.221304125638303
12.221304125618285
12.221304125598277
12.221304125578273
12.221304125558277
12.221304125538282
12.221304125518294
12.221304125498305
12.221304125478325
12.221304125458353
12.221304125438387
12.221304125418404
12.221304125398445
12.22130412537849
12.221304125358532
12.221304125338577
12.221304125318632
12.22130412529869
12.221304125278756
12.221304125258818
12.221304125238897
12.221304125218975
12.22130412519905

12.22130412517913
12.221304125159223
12.22130412513931
12.221304125119405
12.221304125099511
12.221304125079614
12.221304125059726
12.221304125039847
12.221304125019964
12.22130412500009
12.221304124980206
12.221304124960342
12.221304124940474
12.22130412492062
12.221304124900767
12.221304124880902
12.221304124861062
12.221304124841218
12.221304124821376
12.22130412480154
12.221304124781717
12.221304124761891
12.221304124742067
12.221304124722252
12.221304124702444
12.221304124682637
12.221304124662826
12.221304124643027
12.221304124623234
12.221304124603451
12.221304124583652
12.221304124563872
12.221304124544101
12.221304124524321
12.22130412450455
12.221304124484783
12.22130412446502
12.221304124445279
12.221304124425522
12.221304124405767
12.221304124386027
12.221304124366288
12.221304124346553
12.221304124326824
12.221304124307094
12.221304124287379
12.221304124267656
12.221304124247938
12.221304124228231
12.221304124208535
12.22130412418882
12.221304124169121
12.22130412414943
12.221304124129746
12.221304124110059
12.221304124090382
12.221304124070706
12.221304124051038
12.221304124031372
12.22130412401171
12.221304123992052
12.221304123972402
12.221304123952741
12.2213041239331
12.221304123913452
12.221304123893821
12.22130412387419
12.221304123854566
12.22130412383493
12.22130412381531
12.2213041237957
12.221304123776083
12.221304123756479
12.221304123736878
12.22130412371728
12.221304123697687
12.221304123678092
12.22130412365851
12.221304123638921
12.221304123619346
12.221304123599776
12.221304123580204
12.22130412356064
12.221304123541081
12.22130412352153
12.221304123501975
12.221304123482428
12.221304123462883
12.221304123443343
12.22130412342381
12.221304123404279
12.221304123384751
12.221304123365224
12.221304123345714
12.221304123326204
12.221304123306682
12.22130412328718
12.221304123267682
12.221304123248185
12.221304123228688
12.221304123209201
12.221304123189718
12.221304123170235
12.22130412315077
12.22130412313129
12.221304123111828
12.221304123092356
12.2213041230729
12.221304123053448
12.221304123034002
12.221304123014551
12.221304122995113
12.221304122975669
12.221304122956242
12.221304122936806
12.221304122917386
12.221304122897964
12.221304122878557
12.221304122859134
12.221304122839724
12.221304122820326
12.221304122800921
12.221304122781532
12.22130412276214
12.221304122742751
12.221304122723367
12.221304122703984
12.22130412268462
12.221304122665241
12.221304122645874
12.221304122626513
12.221304122607162
12.221304122587807
12.221304122568455
12.221304122549114
12.221304122529773
12.221304122510437
12.2213041224911
12.221304122471778
12.221304122452452
12.221304122433128
12.22130412241381
12.2213041223945
12.2213041223752
12.221304122355892
12.221304122336587
12.221304122317301
12.221304122298006
12.22130412227872
12.22130412225944
12.22130412224016
12.221304122220886
12.221304122201609
12.221304122182353
12.22130412216309
12.221304122143836
12.22130412212458
12.221304122105325
12.221304122086096
12.221304122066844
12.221304122047613
12.221304122028377
12.22130412200915
12.221304121989931
12.221304121970704
12.221304121951498
12.22130412193228
12.221304121913066
12.221304121893874
12.221304121874676
12.22130412185548
12.221304121836294
12.221304121817104
12.221304121797921
12.221304121778738
12.221304121759568
12.221304121740403
12.221304121721227
12.221304121702072
12.221304121682916
12.22130412166376
12.221304121644614
12.221304121625469
12.22130412160633
12.221304121587192
12.22130412156806
12.221304121548933
12.22130412152981
12.221304121510693
12.221304121491574
12.221304121472459
12.221304121453349
12.221304121434256
12.221304121415162
12.221304121396058
12.221304121376965
12.221304121357877
12.221304121338802
12.221304121319724
12.221304121300653
12.221304121281575
12.221304121262516
12.221304121243449
12.221304121224392
12.221304121205335
12.221304121186291
12.22130412116725
12.221304121148211
12.221304121129172
12.221304121110135
12.221304121091112
12.221304121072077
12.221304121053063
12.221304121034049
12.221304121015034
12.221304120996033
12.221304120977019
12.221304120958024
12.221304120939028
12.22130412092003
12.221304120901044
12.221304120882062
12.221304120863085
12.221304120844112
12.22130412082514
12.221304120806172
12.221304120787215
12.221304120768252
12.221304120749299
12.221304120730348
12.2213041207114
12.221304120692457
12.221304120673517
12.22130412065459
12.22130412063566
12.221304120616736
12.221304120597802
12.221304120578894
12.221304120559985
12.221304120541067
12.221304120522168
12.22130412050327
12.221304120484369
12.221304120465467
12.22130412044659
12.221304120427705
12.221304120408828
12.221304120389945
12.221304120371071
12.2213041203522
12.221304120333338
12.221304120314484
12.221304120295624
12.221304120276772
12.22130412025793
12.221304120239083
12.221304120220243
12.221304120201408
12.221304120182577
12.221304120163751
12.22130412014493
12.22130412012611
12.221304120107293
12.221304120088487
12.221304120069675
12.221304120050872
12.22130412003208
12.221304120013277
12.221304119994485
12.2213041199757
12.221304119956924
12.221304119938141
12.221304119919372
12.221304119900598
12.221304119881827
12.221304119863067
12.221304119844312
12.221304119825556
12.221304119806808
12.22130411978806
12.22130411976932
12.221304119750585
12.221304119731851
12.221304119713125
12.221304119694386
12.221304119675674
12.221304119656955
12.221304119638242
12.221304119619534
12.221304119600832
12.221304119582127
12.221304119563435
12.22130411954474
12.221304119526057
12.221304119507366
12.221304119488675
12.221304119470005
12.221304119451334
12.221304119432668
12.221304119414004
12.221304119395345
12.221304119376688
12.221304119358033
12.221304119339383
12.22130411932074
12.2213041193021
12.221304119283463
12.22130411926483
12.221304119246208
12.221304119227588
12.221304119208964
12.221304119190341
12.221304119171734
12.221304119153121
12.221304119134528
12.221304119115922
12.221304119097328
12.221304119078736
12.221304119060143
12.22130411904156
12.221304119022982
12.221304119004406
12.221304118985838
12.22130411896727
12.221304118948712
12.221304118930142
12.22130411891159
12.221304118893038
12.221304118874489
12.221304118855945
12.22130411883741
12.22130411881887
12.221304118800344
12.221304118781823
12.221304118763292
12.22130411874478
12.22130411872626
12.221304118707751
12.22130411868924
12.221304118670743
12.22130411865224
12.221304118633737
12.221304118615256
12.221304118596768
12.221304118578281
12.221304118559805
12.221304118541324
12.22130411852286
12.221304118504394
12.221304118485929
12.221304118467465
12.221304118449014
12.22130411843056
12.221304118412112
12.221304118393661
12.221304118375233
12.221304118356795
12.221304118338365
12.221304118319942
12.221304118301513
12.221304118283099
12.221304118264685
12.221304118246275
12.221304118227863
12.221304118209469
12.221304118191059
12.221304118172675
12.221304118154276
12.22130411813589
12.22130411811752
12.221304118099132
12.221304118080761
12.221304118062381
12.221304118044015
12.22130411802565
12.221304118007295
12.22130411798894
12.22130411797059
12.221304117952242
12.221304117933894
12.221304117915558
12.221304117897226
12.221304117878892
12.22130411786057
12.22130411784224
12.221304117823923
12.221304117805609
12.221304117787296
12.22130411776899
12.221304117750687
12.221304117732384
12.221304117714084
12.221304117695796
12.221304117677517
12.221304117659228
12.221304117640955
12.221304117622676
12.221304117604403
12.221304117586136
12.221304117567868
12.221304117549604
12.221304117531353
12.221304117513105
12.221304117494864
12.221304117476606
12.221304117458375
12.221304117440132
12.221304117421907
12.221304117403674
12.221304117385447
12.221304117367232
12.221304117349016
12.221304117330805
12.221304117312599
12.221304117294395
12.221304117276192
12.221304117257997
12.221304117239804
12.221304117221614
12.221304117203426
12.221304117185241
12.22130411716707
12.221304117148897
12.221304117130721
12.221304117112567
12.221304117094407
12.22130411707625
12.221304117058096
12.221304117039944
12.2213041170218
12.221304117003658
12.221304116985515
12.22130411696738
12.221304116949257
12.221304116931138
12.221304116913013
12.221304116894897
12.221304116876775
12.221304116858665
12.22130411684056
12.221304116822468
12.221304116804374
12.221304116786271
12.22130411676818
12.221304116750101
12.22130411673201
12.221304116713936
12.221304116695869
12.221304116677787
12.221304116659724
12.221304116641665
12.221304116623603
12.221304116605548
12.2213041165875
12.221304116569451
12.221304116551417
12.221304116533375
12.221304116515327
12.221304116497302
12.221304116479278
12.221304116461248
12.221304116443232
12.221304116425218
12.221304116407206
12.2213041163892
12.221304116371195
12.221304116353192
12.22130411633519
12.221304116317205
12.221304116299219
12.221304116281233
12.22130411626325
12.221304116245275
12.221304116227305
12.221304116209339
12.221304116191371
12.221304116173407
12.221304116155448
12.221304116137501
12.221304116119546
12.221304116101603
12.221304116083662
12.221304116065726
12.221304116047783
12.221304116029868
12.22130411601194
12.22130411599401
12.221304115976102

12.221304115958178
12.221304115940264
12.221304115922365
12.221304115904465
12.221304115886568
12.221304115868664
12.221304115850781
12.22130411583289
12.22130411581501
12.221304115797132
12.221304115779253
12.22130411576138
12.22130411574351
12.22130411572565
12.221304115707786
12.22130411568993
12.221304115672085
12.221304115654236
12.221304115636391
12.221304115618546
12.22130411560071
12.221304115582875
12.221304115565053
12.221304115547225
12.221304115529405
12.221304115511593
12.221304115493773
12.221304115475967
12.221304115458159
12.221304115440354
12.221304115422559
12.221304115404767
12.221304115386978
12.221304115369197
12.221304115351408
12.221304115333625
12.221304115315855
12.221304115298077
12.221304115280319
12.22130411526255
12.22130411524479
12.221304115227037
12.221304115209287
12.221304115191538
12.221304115173798
12.221304115156052
12.221304115138324
12.22130411512058
12.221304115102857
12.221304115085136
12.221304115067412
12.221304115049703
12.221304115031987
12.22130411501427
12.221304114996567
12.221304114978865
12.22130411496117
12.221304114943472
12.221304114925783
12.221304114908095
12.221304114890419
12.221304114872737
12.221304114855066
12.221304114837386
12.221304114819727
12.221304114802058
12.221304114784404
12.221304114766745
12.221304114749094
12.221304114731453
12.221304114713801
12.221304114696162
12.221304114678526
12.221304114660892
12.22130411464326
12.221304114625644
12.22130411460801
12.221304114590408
12.221304114572787
12.221304114555176
12.221304114537576
12.221304114519967
12.221304114502374
12.221304114484777
12.221304114467184
12.221304114449598
12.22130411443202
12.221304114414433
12.22130411439686
12.221304114379294
12.221304114361725
12.221304114344159
12.221304114326605
12.22130411430904
12.221304114291488
12.221304114273948
12.221304114256403
12.221304114238857
12.22130411422132
12.221304114203779
12.221304114186262
12.221304114168731
12.22130411415121
12.22130411413369
12.221304114116172
12.221304114098665
12.22130411408117
12.221304114063651
12.221304114046156
12.221304114028658
12.221304114011176
12.221304113993684
12.221304113976203
12.22130411395872
12.221304113941244
12.22130411392377
12.221304113906298
12.22130411388884
12.221304113871378
12.22130411385392
12.221304113836457
12.221304113819018
12.221304113801565
12.221304113784129
12.221304113766696
12.221304113749252
12.221304113731824
12.221304113714398
12.221304113696972
12.221304113679556
12.221304113662141
12.221304113644733
12.221304113627316
12.22130411360991
12.22130411359251
12.22130411357511
12.221304113557723
12.221304113540333
12.221304113522947
12.221304113505564
12.22130411348818
12.22130411347082
12.221304113453442
12.221304113436073
12.221304113418716
12.221304113401361
12.221304113384003
12.221304113366642
12.221304113349301
12.221304113331966
12.221304113314615
12.221304113297274
12.221304113279945
12.221304113262617
12.221304113245296
12.221304113227967
12.221304113210651
12.221304113193344
12.221304113176021
12.22130411315872
12.221304113141413
12.221304113124123
12.221304113106827
12.221304113089529
12.221304113072241
12.221304113054963
12.221304113037679
12.221304113020404
12.221304113003136
12.221304112985862
12.221304112968605
12.221304112951337
12.221304112934073
12.221304112916828
12.22130411289957
12.221304112882326
12.221304112865086
12.22130411284785
12.221304112830616
12.221304112813385
12.221304112796151
12.221304112778926
12.221304112761713
12.221304112744491
12.221304112727278
12.22130411271007
12.221304112692861
12.221304112675663
12.221304112658466
12.22130411264127
12.221304112624082
12.221304112606894
12.221304112589715
12.221304112572534
12.221304112555355
12.221304112538183
12.221304112521015
12.221304112503853
12.221304112486687
12.22130411246954
12.221304112452378
12.221304112435238
12.221304112418084
12.221304112400947
12.221304112383805
12.221304112366669
12.221304112349545
12.221304112332414
12.221304112315293
12.221304112298167
12.221304112281059
12.221304112263944
12.221304112246834
12.221304112229737
12.221304112212623
12.221304112195538
12.221304112178437
12.221304112161343
12.22130411214426
12.221304112127187
12.2213041121101
12.221304112093032
12.221304112075954
12.221304112058885
12.22130411204182
12.22130411202476
12.2213041120077
12.221304111990655
12.221304111973605
12.221304111956561
12.221304111939514
12.221304111922478
12.221304111905447
12.221304111888413
12.221304111871385
12.221304111854362
12.221304111837343
12.221304111820327
12.221304111803311
12.221304111786303
12.221304111769305
12.221304111752303
12.221304111735309
12.221304111718313
12.22130411170132
12.221304111684336
12.221304111667347
12.221304111650378
12.22130411163339
12.221304111616428
12.221304111599455
12.221304111582496
12.221304111565525
12.221304111548573
12.221304111531623
12.221304111514671
12.221304111497728
12.221304111480787
12.221304111463844
12.221304111446916
12.22130411142998
12.221304111413051
12.221304111396131
12.221304111379206
12.221304111362286
12.22130411134538
12.221304111328465
12.221304111311559
12.221304111294653
12.221304111277771
12.22130411126087
12.221304111243985
12.221304111227091
12.221304111210205
12.221304111193335
12.221304111176455
12.221304111159581
12.221304111142711
12.221304111125852
12.221304111108987
12.221304111092133
12.221304111075279
12.22130411105842
12.221304111041578
12.221304111024736
12.221304111007889
12.22130411099106
12.221304110974224
12.221304110957394
12.221304110940572
12.22130411092376
12.221304110906937
12.221304110890118
12.221304110873318
12.221304110856497
12.221304110839702
12.221304110822901
12.221304110806104
12.22130411078931
12.221304110772516
12.221304110755735
12.221304110738958
12.221304110722178
12.221304110705406
12.221304110688637
12.221304110671868
12.221304110655112
12.221304110638348
12.22130411062159
12.22130411060484
12.221304110588095
12.221304110571342
12.221304110554605
12.221304110537867
12.221304110521132
12.221304110504402
12.221304110487676
12.221304110470951
12.221304110454232
12.221304110437522
12.221304110420808
12.2213041104041
12.221304110387395
12.22130411037069
12.221304110353993
12.2213041103373
12.221304110320602
12.221304110303917
12.22130411028724
12.221304110270564
12.221304110253886
12.221304110237213
12.221304110220547
12.221304110203887
12.221304110187212
12.221304110170559
12.221304110153913
12.221304110137257
12.221304110120604
12.221304110103963
12.221304110087319
12.22130411007069
12.221304110054058
12.221304110037432
12.221304110020803
12.221304110004175
12.221304109987564
12.221304109970946
12.221304109954337
12.221304109937734
12.221304109921132
12.221304109904525
12.221304109887932
12.221304109871335
12.221304109854751
12.221304109838163
12.22130410982158
12.221304109805006
12.221304109788438
12.221304109771856
12.22130410975529
12.221304109738728
12.221304109722167
12.221304109705615
12.221304109689056
12.221304109672504
12.22130410965596
12.22130410963942
12.22130410962288
12.221304109606342
12.221304109589811
12.221304109573287
12.221304109556764
12.22130410954024
12.221304109523722
12.221304109507207
12.221304109490694
12.221304109474193
12.221304109457684
12.221304109441189
12.221304109424697
12.221304109408205
12.22130410939171
12.221304109375232
12.221304109358748
12.221304109342272
12.221304109325796
12.22130410930932
12.22130410929286
12.221304109276396
12.22130410925993
12.221304109243475
12.221304109227026
12.221304109210578
12.221304109194126
12.221304109177687
12.22130410916125
12.221304109144809
12.22130410912838
12.221304109111953
12.221304109095533
12.221304109079103
12.221304109062693
12.221304109046278
12.22130410902987
12.221304109013463
12.221304108997055
12.221304108980659
12.221304108964256
12.221304108947864
12.221304108931484
12.221304108915094
12.221304108898712
12.22130410888233
12.22130410886596
12.221304108849596
12.221304108833225
12.221304108816856
12.221304108800503
12.22130410878414
12.221304108767791
12.221304108751438
12.2213041087351
12.221304108718744
12.221304108702409
12.221304108686072
12.221304108669749
12.221304108653417
12.221304108637092
12.221304108620766
12.22130410860446
12.221304108588138
12.221304108571827
12.22130410855552
12.221304108539215
12.22130410852291
12.221304108506622
12.221304108490331
12.221304108474037
12.22130410845775
12.221304108441466
12.22130410842519
12.221304108408914
12.22130410839265
12.22130410837638
12.221304108360114
12.22130410834385
12.221304108327583
12.221304108311335
12.22130410829508
12.221304108278838
12.221304108262597
12.221304108246352
12.221304108230122
12.221304108213888
12.221304108197659
12.221304108181432
12.221304108165208
12.221304108148992
12.221304108132774
12.22130410811656
12.221304108100352
12.221304108084146
12.22130410806794
12.221304108051747
12.221304108035552
12.221304108019364
12.221304108003183
12.221304107986995
12.221304107970814
12.22130410795464
12.221304107938469
12.221304107922299
12.221304107906128
12.221304107889969
12.221304107873806
12.221304107857653
12.221304107841506
12.221304107825349
12.221304107809207
12.221304107793072
12.221304107776932
12.221304107760794
12.22130410774466
12.221304107728526
12.221304107712406
12.221304107696291
12.221304107680176
12.221304107664055
12.221304107647946
12.221304107631841
12.221304107615733
12.221304107599641
12.22130410758354
12.22130410756745
12.221304107551363
12.221304107535275
12.221304107519195
12.221304107503116
12.22130410748704
12.221304107470967
12.221304107454904
12.221304107438836
12.221304107422773
12.22130410740671
12.221304107390658
12.221304107374612
12.221304107358566
12.221304107342519
12.221304107326477
12.221304107310441
12.221304107294403
12.22130410727838
12.221304107262355
12.221304107246327
12.22130410723031
12.221304107214298
12.221304107198277
12.221304107182274
12.221304107166269
12.221304107150267
12.221304107134266
12.221304107118266
12.221304107102275
12.221304107086288
12.221304107070303
12.221304107054324
12.221304107038355
12.221304107022373
12.221304107006398
12.22130410699044
12.221304106974472
12.221304106958517
12.221304106942547
12.221304106926606
12.22130410691065
12.221304106894705
12.221304106878764
12.22130410686282
12.221304106846885
12.221304106830951
12.221304106815026
12.221304106799101
12.22130410678317
12.221304106767251
12.221304106751338
12.221304106735428
12.22130410671952
12.221304106703608
12.221304106687711
12.221304106671822
12.221304106655925
12.22130410664003
12.22130410662414
12.221304106608251
12.221304106592378
12.221304106576499
12.221304106560629
12.221304106544752
12.221304106528892
12.221304106513026
12.221304106497165
12.221304106481305
12.22130410646546
12.221304106449603
12.221304106433756
12.221304106417916
12.221304106402071
12.22130410638624
12.221304106370408
12.221304106354568
12.221304106338751
12.221304106322922
12.221304106307107
12.221304106291294
12.221304106275479
12.221304106259673
12.221304106243865
12.221304106228068
12.221304106212264
12.221304106196467
12.221304106180677
12.221304106164892
12.221304106149105
12.221304106133326
12.22130410611755
12.221304106101773
12.221304106086002
12.221304106070239
12.221304106054466
12.221304106038712
12.221304106022952
12.221304106007196
12.22130410599145
12.221304105975701
12.221304105959948
12.221304105944226
12.221304105928478
12.221304105912754
12.22130410589701
12.221304105881288
12.221304105865572
12.221304105849843
12.22130410583413
12.221304105818419
12.221304105802709
12.221304105787006
12.221304105771294
12.221304105755598
12.2213041057399
12.221304105724215
12.221304105708525
12.221304105692838
12.221304105677154
12.221304105661478
12.221304105645801
12.221304105630129
12.221304105614465
12.221304105598792
12.221304105583135
12.221304105567471
12.221304105551823
12.221304105536165
12.221304105520517
12.221304105504881
12.22130410548923
12.221304105473594
12.221304105457966
12.221304105442336
12.221304105426704
12.221304105411075
12.22130410539545
12.221304105379835
12.22130410536423
12.221304105348613
12.22130410533301
12.221304105317405
12.221304105301806
12.221304105286206
12.22130410527061
12.221304105255024
12.221304105239431
12.221304105223851

12.221304105208272
12.221304105192692
12.221304105177122
12.221304105161545
12.221304105145975
12.221304105130415
12.221304105114854
12.221304105099298
12.221304105083748
12.221304105068208
12.22130410505265
12.221304105037111
12.221304105021565
12.22130410500603
12.2213041049905
12.221304104974962
12.221304104959444
12.221304104943911
12.221304104928391
12.22130410491288
12.22130410489737
12.221304104881861
12.221304104866352
12.221304104850859
12.221304104835346
12.22130410481985
12.221304104804359
12.22130410478887
12.221304104773385
12.221304104757904
12.221304104742424
12.221304104726952
12.22130410471148
12.221304104696003
12.221304104680538
12.221304104665084
12.221304104649613
12.221304104634159
12.22130410461871
12.221304104603261
12.221304104587816
12.221304104572368
12.221304104556937
12.221304104541492
12.221304104526064
12.22130410451064
12.22130410449521
12.221304104479788
12.221304104464368
12.22130410444895
12.221304104433544
12.221304104418131
12.221304104402726
12.221304104387324
12.221304104371928
12.221304104356532
12.221304104341138
12.221304104325757
12.22130410431036
12.221304104294983
12.221304104279605
12.221304104264231
12.22130410424885
12.221304104233484
12.22130410421812
12.221304104202764
12.221304104187404
12.221304104172049
12.22130410415669
12.221304104141339
12.221304104125995
12.221304104110661
12.221304104095323
12.221304104079987
12.221304104064656
12.22130410404932
12.221304104033996
12.221304104018671
12.221304104003355
12.221304103988041
12.221304103972729
12.221304103957424
12.22130410394211
12.221304103926814
12.221304103911512
12.22130410389622
12.221304103880922
12.221304103865629
12.221304103850352
12.221304103835068
12.221304103819785
12.221304103804519
12.22130410378924
12.221304103773967
12.2213041037587
12.221304103743439
12.221304103728183
12.221304103712924
12.22130410369767
12.221304103682419
12.221304103667181
12.221304103651942
12.2213041036367
12.221304103621458
12.221304103606235
12.221304103590997
12.221304103575775
12.221304103560557
12.221304103545327
12.22130410353012
12.221304103514901
12.221304103499694
12.221304103484478
12.221304103469285
12.221304103454079
12.221304103438888
12.221304103423691
12.221304103408508
12.221304103393319
12.221304103378134
12.221304103362955
12.22130410334778
12.221304103332605
12.221304103317435
12.221304103302279
12.221304103287107
12.22130410327195
12.22130410325679
12.221304103241634
12.221304103226487
12.221304103211338
12.221304103196198
12.221304103181053
12.221304103165915
12.22130410315078
12.221304103135651
12.221304103120529
12.221304103105405
12.221304103090286
12.221304103075166
12.221304103060055
12.221304103044938
12.221304103029837
12.221304103014731
12.221304102999627
12.221304102984526
12.221304102969432
12.22130410295434
12.221304102939255
12.221304102924172
12.221304102909093
12.221304102894008
12.221304102878932
12.22130410286387
12.2213041028488
12.221304102833733
12.221304102818673
12.221304102803613
12.221304102788551
12.221304102773503
12.221304102758454
12.221304102743412
12.221304102728377
12.221304102713331
12.221304102698296
12.221304102683261
12.221304102668237
12.221304102653207
12.221304102638188
12.221304102623169
12.221304102608153
12.22130410259313
12.22130410257813
12.221304102563124
12.221304102548112
12.221304102533118
12.221304102518124
12.221304102503131
12.221304102488135
12.221304102473155
12.221304102458168
12.221304102443188
12.221304102428215
12.221304102413237
12.221304102398264
12.221304102383302
12.221304102368336
12.221304102353375
12.221304102338419
12.221304102323465
12.221304102308517
12.221304102293571
12.221304102278626
12.221304102263684
12.221304102248745
12.221304102233805
12.221304102218879
12.221304102203952
12.221304102189025
12.221304102174106
12.22130410215918
12.22130410214427
12.221304102129357
12.221304102114447
12.221304102099543
12.221304102084641
12.221304102069743
12.22130410205484
12.221304102039943
12.22130410202507
12.221304102010171
12.22130410199529
12.221304101980413
12.221304101965538
12.221304101950661
12.221304101935793
12.221304101920932
12.22130410190606
12.221304101891205
12.221304101876353
12.221304101861493
12.221304101846647
12.221304101831784
12.221304101816951
12.22130410180211
12.221304101787265
12.221304101772436
12.221304101757609
12.221304101742781
12.221304101727949
12.22130410171313
12.221304101698312
12.221304101683499
12.221304101668688
12.221304101653878
12.22130410163907
12.221304101624266
12.221304101609467
12.221304101594678
12.221304101579875
12.22130410156509
12.221304101550302
12.22130410153552
12.22130410152074
12.221304101505968
12.22130410149119
12.221304101476418
12.221304101461657
12.221304101446897
12.221304101432128
12.221304101417374
12.221304101402607
12.221304101387865
12.221304101373125
12.221304101358374
12.221304101343627
12.2213041013289
12.221304101314162
12.221304101299427
12.221304101284696
12.221304101269972
12.221304101255253
12.221304101240534
12.221304101225813
12.221304101211105
12.221304101196393
12.22130410118168
12.22130410116698
12.221304101152283
12.22130410113759
12.2213041011229
12.221304101108199
12.221304101093518
12.221304101078836
12.221304101064154
12.221304101049478
12.2213041010348
12.22130410102013
12.221304101005463
12.2213041009908
12.221304100976129
12.221304100961472
12.221304100946819
12.221304100932167
12.221304100917521
12.221304100902874
12.221304100888238
12.22130410087359
12.221304100858957
12.221304100844323
12.221304100829697
12.221304100815061
12.221304100800438
12.221304100785815
12.221304100771206
12.22130410075659
12.221304100741976
12.221304100727368
12.221304100712771
12.221304100698168
12.221304100683568
12.221304100668972
12.221304100654383
12.221304100639795
12.221304100625202
12.221304100610624
12.221304100596049
12.221304100581468
12.221304100566892
12.221304100552327
12.221304100537758
12.2213041005232
12.221304100508638
12.221304100494088
12.221304100479522
12.221304100464975
12.221304100450425
12.221304100435884
12.22130410042134
12.221304100406808
12.221304100392267
12.221304100377738
12.221304100363218
12.221304100348682
12.22130410033416
12.221304100319646
12.221304100305122
12.22130410029061
12.221304100276106
12.221304100261596
12.221304100247096
12.221304100232592
12.221304100218095
12.2213041002036
12.221304100189116
12.221304100174628
12.221304100160134
12.221304100145657
12.221304100131182
12.221304100116704
12.221304100102243
12.22130410008777
12.221304100073294
12.221304100058836
12.221304100044382
12.22130410002992
12.221304100015468
12.22130410000102
12.221304099986574
12.221304099972121
12.221304099957685
12.221304099943252
12.221304099928814
12.221304099914388
12.221304099899958
12.221304099885526
12.221304099871102
12.221304099856692
12.22130409984228
12.221304099827861
12.22130409981345
12.221304099799049
12.221304099784643
12.221304099770238
12.221304099755852
12.221304099741452
12.22130409972706
12.221304099712672
12.221304099698298
12.221304099683913
12.221304099669533
12.221304099655166
12.22130409964079
12.221304099626414
12.22130409961205
12.221304099597688
12.221304099583328
12.221304099568973
12.221304099554619
12.221304099540271
12.221304099525927
12.221304099511583
12.221304099497244
12.221304099482898
12.221304099468565
12.221304099454233
12.221304099439907
12.221304099425575
12.221304099411267
12.221304099396946
12.221304099382625
12.221304099368313
12.221304099354002
12.221304099339696
12.221304099325394
12.221304099311094
12.221304099296795
12.221304099282507
12.221304099268211
12.221304099253928
12.221304099239637
12.221304099225359
12.221304099211082
12.2213040991968
12.221304099182534
12.221304099168263
12.221304099153999
12.221304099139736
12.221304099125467
12.221304099111222
12.221304099096969
12.221304099082712
12.221304099068462
12.22130409905422
12.221304099039981
12.22130409902574
12.221304099011503
12.221304098997278
12.221304098983044
12.22130409896882
12.2213040989546
12.221304098940383
12.221304098926158
12.22130409891194
12.221304098897733
12.221304098883527
12.221304098869322
12.22130409885512
12.22130409884093
12.221304098826733
12.22130409881254
12.221304098798349
12.221304098784167
12.221304098769977
12.221304098755798
12.22130409874163
12.22130409872745
12.221304098713281
12.221304098699107
12.221304098684953
12.221304098670783
12.221304098656624
12.221304098642475
12.221304098628316
12.221304098614173
12.221304098600028
12.221304098585879
12.221304098571746
12.221304098557612
12.221304098543477
12.221304098529352
12.221304098515215
12.221304098501099
12.221304098486975
12.221304098472848
12.22130409845874
12.221304098444632
12.221304098430517
12.221304098416418
12.221304098402303
12.22130409838821
12.221304098374112
12.221304098360015
12.221304098345927
12.221304098331837
12.221304098317754
12.22130409830367
12.2213040982896
12.22130409827552
12.221304098261449
12.221304098247373
12.22130409823331
12.221304098219248
12.221304098205191
12.221304098191139
12.22130409817708
12.221304098163024
12.221304098148975
12.221304098134938
12.221304098120896
12.221304098106847
12.22130409809282
12.221304098078784
12.221304098064758
12.221304098050727
12.221304098036706
12.221304098022683
12.221304098008666
12.221304097994652
12.221304097980639
12.221304097966636
12.221304097952627
12.221304097938628

12.221304097924627
12.221304097910625
12.221304097896633
12.221304097882642
12.221304097868664
12.221304097854679
12.221304097840694
12.221304097826716
12.221304097812741
12.221304097798773
12.221304097784797
12.221304097770835
12.221304097756871
12.221304097742912
12.221304097728956
12.221304097715
12.221304097701053
12.221304097687106
12.221304097673167
12.221304097659218
12.221304097645277
12.221304097631347
12.221304097617411
12.221304097603488
12.22130409758956
12.221304097575633
12.221304097561719
12.221304097547794
12.221304097533883
12.22130409751997
12.221304097506058
12.221304097492153
12.221304097478253
12.221304097464353
12.221304097450455
12.221304097436567
12.221304097422678
12.221304097408792
12.2213040973949
12.221304097381024
12.221304097367145
12.221304097353267
12.221304097339399
12.221304097325527
12.221304097311661
12.221304097297804
12.221304097283932
12.221304097270085
12.221304097256235
12.221304097242374
12.221304097228526
12.221304097214684
12.221304097200843
12.221304097187003
12.221304097173162
12.221304097159335
12.2213040971455
12.221304097131682
12.221304097117857
12.221304097104037
12.221304097090211
12.2213040970764
12.221304097062589
12.221304097048774
12.221304097034968
12.22130409702116
12.221304097007366
12.221304096993567
12.221304096979777
12.221304096965982
12.221304096952196
12.221304096938411
12.22130409692463
12.221304096910847
12.221304096897066
12.221304096883301
12.221304096869527
12.221304096855764
12.221304096842003
12.221304096828234
12.22130409681448
12.221304096800726
12.221304096786971
12.22130409677322
12.221304096759473
12.221304096745737
12.221304096731997
12.22130409671826
12.22130409670452
12.22130409669079
12.221304096677063
12.221304096663333
12.221304096649606
12.221304096635892
12.221304096622179
12.22130409660847
12.221304096594759
12.221304096581045
12.221304096567343
12.221304096553645
12.22130409653994
12.221304096526246
12.221304096512556
12.221304096498866
12.22130409648518
12.22130409647149
12.22130409645781
12.221304096444133
12.221304096430462
12.221304096416786
12.221304096403124
12.221304096389456
12.22130409637579
12.22130409636213
12.221304096348465
12.22130409633482
12.221304096321168
12.221304096307522
12.221304096293872
12.221304096280228
12.221304096266593
12.221304096252954
12.221304096239328
12.221304096225696
12.221304096212068
12.221304096198438
12.221304096184818
12.221304096171199
12.221304096157592
12.22130409614397
12.221304096130362
12.221304096116759
12.221304096103152
12.221304096089549
12.22130409607596
12.221304096062354
12.221304096048769
12.22130409603518
12.221304096021598
12.22130409600801
12.221304095994423
12.221304095980848
12.221304095967275
12.221304095953704
12.221304095940132
12.22130409592657
12.221304095913014
12.221304095899452
12.221304095885893
12.221304095872341
12.221304095858791
12.221304095845237
12.221304095831691
12.221304095818152
12.22130409580461
12.22130409579108
12.221304095777551
12.221304095764022
12.221304095750488
12.22130409573696
12.221304095723442
12.221304095709925
12.221304095696407
12.221304095682896
12.221304095669389
12.221304095655885
12.221304095642376
12.221304095628879
12.221304095615384
12.221304095601882
12.22130409558839
12.221304095574906
12.221304095561418
12.221304095547941
12.221304095534448
12.221304095520978
12.221304095507499
12.221304095494032
12.221304095480562
12.221304095467092
12.221304095453636
12.221304095440175
12.22130409542671
12.221304095413268
12.221304095399814
12.221304095386365
12.221304095372913
12.221304095359473
12.221304095346033
12.221304095332595
12.221304095319164
12.221304095305733
12.22130409529231
12.221304095278885
12.22130409526546
12.221304095252036
12.221304095238624
12.221304095225213
12.2213040952118
12.22130409519839
12.221304095184994
12.221304095171588
12.221304095158194
12.221304095144793
12.2213040951314
12.22130409511802
12.221304095104625
12.221304095091241
12.22130409507786
12.221304095064482
12.221304095051105
12.221304095037736
12.221304095024362
12.221304095011
12.221304094997631
12.221304094984273
12.221304094970922
12.22130409495756
12.221304094944214
12.221304094930861
12.221304094917516
12.221304094904168
12.221304094890833
12.221304094877494
12.221304094864152
12.22130409485082
12.221304094837508
12.22130409482417
12.22130409481085
12.221304094797524
12.22130409478421
12.221304094770888
12.221304094757574
12.22130409474427
12.221304094730964
12.221304094717658
12.221304094704355
12.221304094691062
12.22130409467777
12.22130409466448
12.221304094651193
12.221304094637903
12.221304094624626
12.221304094611337
12.22130409459807
12.22130409458479
12.221304094571524
12.221304094558253
12.221304094544982
12.221304094531723
12.221304094518462
12.221304094505209
12.221304094491956
12.221304094478707
12.221304094465456
12.221304094452211
12.221304094438965
12.221304094425724
12.221304094412488
12.221304094399255
12.221304094386028
12.22130409437279
12.221304094359578
12.221304094346353
12.22130409433313
12.22130409431992
12.221304094306696
12.221304094293489
12.22130409428028
12.22130409426707
12.221304094253874
12.221304094240677
12.221304094227476
12.221304094214286
12.221304094201097
12.221304094187907
12.22130409417472
12.221304094161539
12.22130409414836
12.221304094135183
12.221304094122011
12.221304094108836
12.221304094095672
12.221304094082507
12.221304094069342
12.221304094056187
12.221304094043026
12.221304094029872
12.22130409401672
12.221304094003571
12.22130409399043
12.221304093977285
12.221304093964141
12.221304093951003
12.22130409393788
12.221304093924747
12.221304093911618
12.221304093898487
12.221304093885374
12.221304093872256
12.221304093859132
12.221304093846022
12.221304093832904
12.2213040938198
12.221304093806692
12.221304093793595
12.221304093780493
12.221304093767394
12.221304093754304
12.221304093741207
12.22130409372813
12.221304093715041
12.221304093701958
12.221304093688877
12.221304093675807
12.221304093662724
12.221304093649653
12.221304093636586
12.221304093623523
12.22130409361046
12.221304093597398
12.221304093584346
12.221304093571282
12.221304093558235
12.221304093545191
12.221304093532144
12.2213040935191
12.221304093506054
12.221304093493025
12.221304093479992
12.221304093466953
12.221304093453929
12.221304093440901
12.221304093427877
12.221304093414854
12.221304093401836
12.221304093388822
12.221304093375812
12.221304093362813
12.2213040933498
12.221304093336796
12.221304093323804
12.221304093310799
12.221304093297801
12.221304093284807
12.221304093271819
12.221304093258842
12.221304093245857
12.221304093232872
12.221304093219903
12.221304093206925
12.221304093193954
12.221304093180985
12.221304093168017
12.221304093155045
12.221304093142091
12.22130409312913
12.221304093116174
12.221304093103223
12.221304093090273
12.221304093077329
12.221304093064381
12.221304093051438
12.221304093038503
12.221304093025564
12.22130409301263
12.221304092999704
12.221304092986777
12.221304092973856
12.221304092960937
12.22130409294801
12.221304092935098
12.221304092922175
12.22130409290927
12.221304092896364
12.221304092883463
12.221304092870554
12.221304092857661
12.22130409284476
12.221304092831872
12.221304092818977
12.22130409280609
12.2213040927932
12.221304092780322
12.221304092767442
12.221304092754565
12.221304092741692
12.221304092728822
12.221304092715952
12.221304092703086
12.221304092690227
12.221304092677363
12.221304092664505
12.221304092651648
12.22130409263879
12.22130409262595
12.221304092613103
12.221304092600253
12.221304092587424
12.22130409257459
12.221304092561748
12.22130409254892
12.221304092536084
12.221304092523255
12.221304092510435
12.221304092497618
12.221304092484795
12.221304092471978
12.221304092459171
12.221304092446358
12.221304092433552
12.221304092420748
12.221304092407943
12.22130409239515
12.22130409238235
12.221304092369559
12.22130409235677
12.221304092343983
12.221304092331192
12.22130409231841
12.221304092305628
12.221304092292854
12.221304092280079
12.221304092267308
12.221304092254545
12.221304092241775
12.221304092229017
12.221304092216265
12.2213040922035
12.221304092190746
12.221304092177997
12.221304092165246
12.221304092152506
12.221304092139755
12.221304092127008
12.221304092114279
12.221304092101542
12.221304092088806
12.221304092076082
12.221304092063356
12.221304092050627
12.221304092037904
12.221304092025186
12.221304092012472
12.221304091999759
12.221304091987056
12.221304091974343
12.221304091961636

12.221304091948936
12.221304091936235
12.22130409192354
12.221304091910849
12.221304091898162
12.221304091885463
12.221304091872785
12.2213040918601
12.221304091847419
12.221304091834744
12.221304091822068
12.2213040918094
12.221304091796723
12.221304091784065
12.221304091771394
12.221304091758741
12.221304091746081
12.221304091733423
12.221304091720777
12.221304091708124
12.221304091695472
12.221304091682835
12.221304091670191
12.221304091657556
12.22130409164492
12.221304091632286
12.22130409161965
12.221304091607024
12.221304091594401
12.221304091581779
12.221304091569161
12.221304091556542
12.221304091543926
12.221304091531318
12.2213040915187
12.221304091506108
12.2213040914935
12.221304091480905
12.221304091468301
12.2213040914557
12.221304091443114
12.221304091430527
12.221304091417936
12.221304091405353
12.221304091392776
12.221304091380201
12.221304091367614
12.221304091355053
12.221304091342477
12.221304091329907
12.221304091317338
12.22130409130478
12.221304091292218
12.22130409127967
12.221304091267113
12.221304091254554
12.221304091242013
12.221304091229465
12.22130409121692
12.221304091204384
12.221304091191847
12.221304091179318
12.221304091166774
12.221304091154243
12.221304091141716
12.221304091129198
12.221304091116677
12.221304091104162
12.221304091091643
12.221304091079126
12.221304091066617
12.22130409105411
12.221304091041608
12.221304091029106
12.221304091016608
12.221304091004109
12.221304090991618
12.22130409097912
12.221304090966632
12.221304090954145
12.221304090941663
12.221304090929184
12.221304090916705
12.221304090904232
12.22130409089176
12.221304090879295
12.221304090866823
12.221304090854357
12.221304090841892
12.221304090829436
12.221304090816986
12.221304090804537
12.22130409079207
12.22130409077963
12.221304090767182
12.22130409075474
12.2213040907423
12.22130409072987
12.221304090717428
12.221304090704992
12.221304090692573
12.221304090680142
12.221304090667722
12.221304090655297
12.221304090642876
12.221304090630461
12.221304090618052
12.221304090605651
12.22130409059323
12.221304090580825
12.221304090568422
12.221304090556018
12.221304090543628
12.221304090531236
12.221304090518844
12.221304090506457
12.221304090494069
12.221304090481684
12.221304090469312
12.221304090456925
12.221304090444546
12.221304090432175
12.221304090419801
12.221304090407441
12.22130409039508
12.221304090382718
12.221304090370356
12.221304090357997
12.22130409034564
12.221304090333296
12.221304090320945
12.221304090308593
12.22130409029626
12.221304090283915
12.22130409027158
12.221304090259245
12.221304090246914
12.221304090234582
12.221304090222256
12.221304090209928
12.221304090197604
12.221304090185289
12.221304090172971
12.221304090160661
12.221304090148353
12.221304090136039
12.221304090123738
12.221304090111431
12.221304090099132
12.221304090086836
12.221304090074534
12.221304090062246
12.221304090049959
12.22130409003767
12.221304090025386
12.221304090013106
12.22130409000082
12.221304089988546
12.221304089976272
12.221304089964002
12.221304089951737
12.221304089939466
12.221304089927205
12.221304089914947
12.22130408990269
12.221304089890435
12.22130408987818
12.221304089865926
12.221304089853687
12.221304089841437
12.221304089829198
12.221304089816957
12.221304089804727
12.221304089792485
12.221304089780254
12.221304089768033
12.221304089755801
12.221304089743581
12.22130408973136
12.221304089719135
12.221304089706923
12.221304089694714
12.221304089682508
12.221304089670296
12.22130408965809
12.221304089645887
12.221304089633692
12.221304089621496
12.2213040896093
12.221304089597108
12.221304089584915
12.221304089572742
12.22130408956055
12.221304089548374
12.221304089536188
12.221304089524015
12.221304089511843
12.221304089499673
12.221304089487507
12.221304089475339
12.221304089463176
12.22130408945102
12.221304089438863
12.221304089426708
12.22130408941456
12.221304089402402
12.221304089390262
12.221304089378124
12.221304089365974
12.221304089353838
12.221304089341702
12.221304089329568
12.22130408931744
12.221304089305312
12.221304089293188
12.221304089281055
12.22130408926894
12.22130408925683
12.221304089244711
12.221304089232591
12.221304089220489
12.221304089208386
12.221304089196272
12.221304089184171
12.221304089172069
12.221304089159979
12.221304089147884
12.221304089135797
12.221304089123704
12.221304089111614
12.221304089099533
12.221304089087454
12.221304089075373
12.221304089063299
12.221304089051225
12.22130408903916
12.221304089027086
12.221304089015025
12.221304089002961
12.221304088990902
12.221304088978851
12.221304088966795
12.221304088954744
12.221304088942693
12.221304088930642
12.221304088918602
12.221304088906555
12.221304088894522
12.221304088882487
12.221304088870452
12.22130408885842
12.221304088846392
12.221304088834358
12.221304088822352
12.221304088810323
12.221304088798309
12.221304088786287
12.221304088774282
12.221304088762267
12.221304088750266
12.221304088738256
12.221304088726253
12.221304088714252
12.22130408870225
12.221304088690262
12.22130408867827
12.221304088666278
12.22130408865429
12.221304088642311
12.221304088630326
12.221304088618352
12.221304088606376
12.221304088594394
12.221304088582428
12.221304088570452
12.221304088558487
12.221304088546534
12.221304088534568
12.221304088522611
12.221304088510658
12.221304088498702
12.221304088486754
12.221304088474803
12.221304088462864
12.221304088450923
12.221304088438977
12.221304088427045
12.2213040884151
12.221304088403175
12.221304088391243
12.221304088379311
12.221304088367388
12.221304088355467
12.221304088343551
12.22130408833163
12.22130408831972
12.22130408830781
12.221304088295906
12.221304088283999
12.221304088272086
12.221304088260183
12.221304088248292
12.221304088236389
12.221304088224498
12.22130408821261
12.221304088200723
12.221304088188836
12.22130408817695
12.221304088165068
12.221304088153195
12.221304088141316
12.221304088129445
12.221304088117572
12.221304088105704
12.221304088093838
12.22130408808199
12.221304088070124
12.221304088058266
12.221304088046418
12.221304088034552
12.221304088022704
12.221304088010863
12.221304087999018
12.221304087987177
12.22130408797534
12.2213040879635
12.221304087951662
12.221304087939828
12.22130408792801
12.221304087916181
12.221304087904354
12.221304087892532
12.221304087880714
12.221304087868894
12.221304087857092
12.22130408784527
12.221304087833461
12.22130408782166
12.221304087809855
12.221304087798059
12.221304087786258
12.221304087774469
12.221304087762672
12.221304087750879
12.221304087739087
12.221304087727306
12.221304087715517
12.221304087703741
12.22130408769196
12.22130408768019
12.221304087668411
12.221304087656648
12.221304087644874
12.221304087633118
12.221304087621354
12.221304087609589
12.221304087597824
12.221304087586084
12.221304087574325
12.221304087562576
12.221304087550827
12.221304087539087
12.221304087527336
12.221304087515602
12.221304087503865
12.221304087492124
12.221304087480402
12.221304087468669
12.221304087456943
12.221304087445217
12.221304087433499
12.22130408742178
12.221304087410072
12.221304087398346
12.221304087386637
12.221304087374934
12.22130408736322
12.221304087351522
12.221304087339814
12.221304087328118
12.221304087316417
12.22130408730473
12.221304087293044
12.221304087281348
12.221304087269662
12.221304087257973
12.221304087246299
12.221304087234616
12.221304087222947
12.221304087211275
12.2213040871996
12.221304087187931
12.221304087176266
12.221304087164604
12.221304087152935
12.221304087141286
12.221304087129631
12.221304087117973
12.221304087106324
12.221304087094676
12.221304087083032
12.221304087071385
12.221304087059753
12.22130408704811
12.221304087036474
12.22130408702484
12.22130408701321
12.221304087001577
12.221304086989962
12.22130408697834
12.221304086966716
12.221304086955106
12.221304086943482
12.221304086931868
12.221304086920265
12.221304086908647
12.221304086897044
12.221304086885436
12.221304086873845
12.221304086862249
12.22130408685065
12.221304086839057
12.221304086827468
12.221304086815882
12.221304086804295
12.221304086792713
12.221304086781133
12.221304086769546
12.221304086757975
12.221304086746411
12.221304086734841
12.221304086723277
12.22130408671171
12.221304086700147
12.221304086688582
12.221304086677032
12.221304086665466
12.221304086653914
12.221304086642371
12.221304086630818
12.221304086619282
12.221304086607734
12.221304086596195
12.221304086584658
12.221304086573124
12.221304086561593
12.221304086550063
12.221304086538535
12.221304086527011
12.22130408651549
12.221304086503965
12.221304086492454
12.221304086480933
12.221304086469418
12.22130408645791
12.221304086446404
12.2213040864349
12.221304086423396
12.221304086411898
12.2213040864004
12.221304086388901
12.221304086377403

12.221304086365922
12.221304086354433
12.221304086342949
12.221304086331465
12.221304086319988
12.221304086308509
12.22130408629704
12.221304086285562
12.221304086274092
12.22130408626262
12.221304086251155
12.221304086239698
12.221304086228248
12.221304086216774
12.221304086205329
12.221304086193872
12.221304086182428
12.221304086170981
12.221304086159533
12.22130408614809
12.221304086136643
12.22130408612521
12.221304086113776
12.221304086102343
12.221304086090914
12.221304086079487
12.22130408606806
12.221304086056634
12.221304086045212
12.221304086033804
12.221304086022384
12.221304086010976
12.221304085999554
12.221304085988155
12.221304085976747
12.221304085965352
12.221304085953943
12.22130408594254
12.221304085931152
12.221304085919764
12.221304085908367
12.221304085896978
12.221304085885588
12.22130408587421
12.22130408586283
12.22130408585145
12.221304085840067
12.221304085828702
12.221304085817334
12.221304085805965
12.221304085794603
12.221304085783236
12.221304085771871
12.221304085760504
12.221304085749152
12.221304085737815
12.221304085726457
12.221304085715104
12.221304085703752
12.221304085692417
12.221304085681078
12.221304085669741
12.221304085658392
12.221304085647066
12.221304085635733
12.221304085624402
12.221304085613081
12.221304085601759
12.221304085590434
12.221304085579117
12.221304085567791
12.221304085556481
12.221304085545176
12.221304085533859
12.221304085522556
12.221304085511255
12.221304085499956
12.221304085488645
12.221304085477355
12.221304085466054
12.221304085454776
12.221304085443487
12.221304085432193
12.221304085420911
12.22130408540962
12.221304085398343
12.221304085387063
12.221304085375788
12.221304085364524
12.22130408535325
12.22130408534198
12.221304085330717
12.22130408531945
12.22130408530819
12.22130408529694
12.221304085285684
12.221304085274427
12.221304085263178
12.221304085251933
12.221304085240678
12.22130408522944
12.221304085218197
12.221304085206956
12.221304085195728
12.22130408518449
12.22130408517326
12.221304085162032
12.221304085150802
12.221304085139579
12.221304085128358
12.221304085117147
12.221304085105924
12.221304085094712
12.221304085083498
12.221304085072292
12.221304085061094
12.22130408504988
12.221304085038678
12.221304085027478
12.22130408501628
12.22130408500509
12.221304084993891
12.221304084982703
12.221304084971521
12.22130408496034
12.221304084949153
12.221304084937971
12.22130408492679
12.22130408491562
12.221304084904457
12.221304084893275
12.22130408488211
12.221304084870944
12.221304084859787
12.221304084848624
12.221304084837465
12.221304084826306
12.221304084815154
12.221304084804004
12.221304084792852
12.221304084781714
12.221304084770567
12.221304084759426
12.221304084748283
12.221304084737149
12.221304084726011
12.221304084714886
12.221304084703757
12.22130408469263
12.221304084681504
12.221304084670395
12.221304084659259
12.221304084648146
12.22130408463703
12.221304084625919
12.22130408461481
12.221304084603696
12.221304084592592
12.221304084581497
12.221304084570399
12.221304084559291
12.221304084548207
12.221304084537117
12.22130408452602
12.221304084514932
12.221304084503844
12.221304084492761
12.22130408448169
12.221304084470605
12.221304084459526
12.221304084448448
12.221304084437383
12.221304084426317
12.22130408441525
12.221304084404185
12.221304084393124
12.221304084382062
12.221304084371004
12.221304084359955
12.221304084348906
12.221304084337852
12.221304084326801
12.221304084315756
12.221304084304714
12.221304084293678
12.221304084282647
12.221304084271601
12.221304084260572
12.221304084249542
12.221304084238515
12.221304084227484
12.221304084216458
12.221304084205437
12.221304084194418
12.221304084183409
12.221304084172395
12.221304084161382
12.221304084150377
12.221304084139373
12.221304084128354
12.221304084117355
12.221304084106363
12.221304084095364
12.22130408408437
12.221304084073378
12.22130408406239
12.221304084051404
12.22130408404041
12.221304084029432
12.221304084018456
12.221304084007475
12.221304083996495
12.22130408398553
12.221304083974553
12.221304083963588
12.221304083952619
12.221304083941659
12.221304083930692
12.221304083919737
12.22130408390878
12.221304083897829
12.221304083886874
12.221304083875921
12.221304083864977
12.221304083854038
12.221304083843092
12.221304083832152
12.221304083821218
12.221304083810278
12.221304083799351
12.221304083788418
12.221304083777486
12.221304083766562
12.22130408375564
12.221304083744718
12.221304083733797
12.22130408372289
12.22130408371197
12.221304083701064
12.22130408369015
12.22130408367924
12.221304083668336
12.221304083657449
12.22130408364654
12.221304083635637
12.22130408362475
12.221304083613862
12.221304083602968
12.221304083592075
12.221304083581195
12.221304083570306
12.221304083559431
12.221304083548555
12.221304083537678
12.221304083526805
12.221304083515935
12.22130408350506
12.2213040834942
12.221304083483336
12.22130408347247
12.221304083461606
12.22130408345075
12.221304083439893
12.221304083429047
12.221304083418197
12.22130408340735
12.221304083396511
12.221304083385657
12.221304083374818
12.221304083363982
12.221304083353147
12.221304083342314
12.221304083331484
12.221304083320652
12.221304083309825
12.221304083299
12.221304083288189
12.221304083277362
12.22130408326654
12.22130408325573
12.221304083244917
12.22130408323411
12.221304083223302
12.221304083212496
12.221304083201694
12.221304083190892
12.221304083180094
12.221304083169294
12.2213040831585
12.221304083147718
12.221304083136921
12.22130408312614
12.221304083115355
12.221304083104572
12.221304083093786
12.221304083083012
12.22130408307224
12.221304083061467
12.22130408305069
12.221304083039925
12.22130408302916
12.221304083018394
12.221304083007643
12.221304082996888
12.221304082986123
12.22130408297537
12.221304082964627
12.22130408295387
12.221304082943124
12.221304082932384
12.221304082921638
12.2213040829109
12.221304082900158
12.22130408288942
12.221304082878689
12.221304082867965
12.221304082857236
12.221304082846505
12.22130408283578
12.221304082825062
12.221304082814344
12.221304082803629
12.221304082792914
12.221304082782206
12.221304082771498
12.221304082760781
12.221304082750077
12.22130408273938
12.221304082728679
12.221304082717973
12.221304082707288
12.22130408269659
12.221304082685903
12.22130408267521
12.221304082664522
12.221304082653841
12.221304082643156
12.221304082632482
12.2213040826218
12.22130408261113
12.221304082600454
12.221304082589784
12.221304082579115
12.221304082568453
12.221304082557788
12.221304082547128
12.22130408253647
12.221304082525808
12.221304082515163
12.221304082504505
12.221304082493862
12.221304082483206
12.221304082472566
12.221304082461923
12.221304082451285
12.22130408244065
12.22130408243001
12.22130408241938
12.221304082408745
12.221304082398118
12.221304082387498
12.221304082376877
12.221304082366244
12.221304082355626
12.221304082345014
12.221304082334395
12.221304082323782
12.221304082313175
12.22130408230257
12.221304082291969
12.221304082281359
12.221304082270764
12.221304082260156
12.221304082249564
12.22130408223897
12.221304082228379
12.221304082217786
12.221304082207205
12.221304082196621
12.221304082186037
12.221304082175456
12.221304082164883
12.2213040821543
12.221304082143728
12.221304082133154
12.221304082122582
12.22130408211202
12.221304082101458
12.221304082090894
12.221304082080334
12.221304082069777
12.221304082059222
12.22130408204867
12.221304082038118
12.221304082027574
12.221304082017026
12.221304082006482
12.221304081995939
12.221304081985405
12.221304081974868
12.221304081964334
12.221304081953798
12.221304081943272
12.221304081932745
12.221304081922217
12.221304081911695
12.221304081901172
12.221304081890658
12.221304081880138
12.221304081869631
12.22130408185912
12.221304081848613
12.2213040818381
12.221304081827592
12.221304081817095
12.221304081806593
12.221304081796085
12.221304081785597
12.221304081775106
12.22130408176462
12.221304081754123
12.221304081743643
12.221304081733164
12.221304081722671
12.2213040817122
12.221304081701714
12.221304081691247
12.221304081680767
12.221304081670297
12.221304081659827
12.221304081649361
12.221304081638907
12.22130408162844
12.221304081617978
12.221304081607522
12.221304081597069
12.221304081586617
12.22130408157617
12.22130408156572
12.221304081555274
12.221304081544831
12.221304081534392
12.22130408152395
12.221304081513512
12.221304081503078
12.22130408149265
12.22130408148222
12.221304081471787
12.221304081461362
12.221304081450944
12.221304081440524
12.221304081430105
12.221304081419682
12.221304081409272
12.221304081398864
12.221304081388451
12.221304081378053
12.22130408136764
12.221304081357237
12.221304081346837
12.221304081336443
12.221304081326048
12.221304081315644
12.221304081305261
12.221304081294868
12.221304081284487
12.221304081274104
12.221304081263714
12.221304081253342
12.22130408124296
12.221304081232583
12.22130408122221
12.221304081211839
12.221304081201476
12.221304081191104
12.221304081180739
12.221304081170382
12.22130408116002
12.221304081149661
12.2213040811393
12.221304081128952
12.221304081118607
12.221304081108253
12.22130408109791
12.221304081087567
12.221304081077221
12.22130408106688
12.221304081056548
12.22130408104621
12.221304081035886
12.221304081025547
12.221304081015221
12.221304081004893
12.221304080994573
12.221304080984241
12.221304080973933
12.221304080963607
12.221304080953297
12.221304080942993
12.221304080932674
12.22130408092236

12.221304080912061
12.221304080901756
12.22130408089146
12.221304080881161
12.221304080870864
12.22130408086057
12.22130408085027
12.221304080839985
12.221304080829697
12.22130408081941
12.221304080809123
12.22130408079885
12.22130408078857
12.221304080778285
12.221304080768016
12.221304080757736
12.221304080747474
12.221304080737198
12.221304080726938
12.221304080716674
12.22130408070641
12.221304080696152
12.221304080685895
12.221304080675644
12.221304080665389
12.221304080655136
12.221304080644895
12.221304080634644
12.221304080624407
12.221304080614155
12.22130408060392
12.22130408059369
12.221304080583451
12.22130408057322
12.221304080562991
12.221304080552763
12.221304080542538
12.221304080532306
12.221304080522094
12.221304080511874
12.221304080501652
12.221304080491441
12.221304080481229
12.221304080471016
12.22130408046082
12.2213040804506
12.221304080440397
12.221304080430201
12.221304080420001
12.221304080409803
12.221304080399614
12.221304080389421
12.221304080379234
12.221304080369038
12.221304080358854
12.221304080348673
12.22130408033849
12.221304080328313
12.221304080318129
12.221304080307954
12.221304080297783
12.221304080287618
12.221304080277452
12.221304080267288
12.221304080257122
12.221304080246963
12.221304080236795
12.22130408022665
12.22130408021648
12.221304080206329
12.22130408019618
12.221304080186037
12.221304080175893
12.22130408016575
12.221304080155601
12.221304080145462
12.221304080135331
12.221304080125199
12.22130408011505
12.221304080104934
12.2213040800948
12.221304080084671
12.22130408007455
12.221304080064424
12.221304080054306
12.221304080044197
12.221304080034072
12.22130408002396
12.221304080013844
12.221304080003746
12.221304079993642
12.221304079983534
12.221304079973434
12.221304079963332
12.221304079953233
12.221304079943133
12.22130407993304
12.221304079922945
12.221304079912867
12.221304079902772
12.22130407989269
12.221304079882609
12.221304079872526
12.221304079862453
12.221304079852379
12.221304079842298
12.221304079832233
12.221304079822161
12.2213040798121
12.221304079802037
12.221304079791965
12.221304079781905
12.221304079771842
12.22130407976179
12.221304079751741
12.221304079741687
12.221304079731635
12.22130407972159
12.221304079711533
12.221304079701504
12.221304079691462
12.221304079681426
12.221304079671388
12.221304079661353
12.221304079651311
12.22130407964129
12.22130407963126
12.221304079621238
12.221304079611214
12.221304079601188
12.221304079591173
12.221304079581152
12.221304079571139
12.221304079561126
12.221304079551112
12.22130407954111
12.221304079531105
12.221304079521095
12.221304079511096
12.221304079501095
12.221304079491102
12.221304079481106
12.221304079471107
12.221304079461117
12.221304079451135
12.22130407944114
12.221304079431158
12.221304079421175
12.2213040794112
12.221304079401223
12.221304079391249
12.221304079381271
12.221304079371299
12.22130407936133
12.221304079351356
12.221304079341403
12.221304079331432
12.221304079321474
12.221304079311514
12.22130407930156
12.221304079291604
12.221304079281664
12.22130407927171
12.221304079261758
12.221304079251814
12.221304079241866
12.221304079231926
12.221304079221989
12.221304079212048
12.221304079202122
12.22130407919219
12.221304079182257
12.221304079172329
12.221304079162405
12.221304079152471
12.221304079142554
12.221304079132628
12.221304079122719
12.221304079112793
12.221304079102886
12.221304079092983
12.221304079083064
12.221304079073162
12.221304079063259
12.221304079053356
12.221304079043458
12.221304079033562
12.221304079023662
12.221304079013771
12.221304079003882
12.221304078993988
12.221304078984101
12.221304078974217
12.221304078964334
12.221304078954452
12.221304078944566
12.221304078934702
12.221304078924819
12.22130407891495
12.221304078905074
12.22130407889521
12.221304078885344
12.221304078875484
12.221304078865622
12.221304078855761
12.221304078845906
12.221304078836042
12.221304078826192
12.221304078816344
12.221304078806492
12.22130407879665
12.221304078786803
12.221304078776965
12.221304078767117
12.221304078757283
12.221304078747451
12.221304078737617
12.221304078727782
12.221304078717953
12.221304078708128
12.22130407869829
12.22130407868847
12.221304078678656
12.221304078668835
12.22130407865902
12.221304078649208
12.22130407863939
12.221304078629581
12.221304078619776
12.221304078609968
12.22130407860016
12.221304078590359
12.221304078580559
12.221304078570762
12.221304078560962
12.221304078551173
12.221304078541383
12.221304078531597
12.221304078521811
12.221304078512023
12.22130407850224
12.221304078492459
12.221304078482682
12.221304078472913
12.221304078463133
12.221304078453358
12.221304078443593
12.221304078433821
12.221304078424058
12.221304078414295
12.221304078404533
12.221304078394772
12.221304078385018
12.221304078375262
12.221304078365508
12.221304078355756
12.22130407834601
12.22130407833626
12.221304078326519
12.221304078316768
12.221304078307034
12.221304078297301
12.221304078287558
12.22130407827782
12.221304078268089
12.221304078258363
12.221304078248632
12.22130407823891
12.221304078229183
12.221304078219461
12.221304078209748
12.221304078200024
12.221304078190316
12.2213040781806
12.221304078170887
12.221304078161186
12.221304078151475
12.221304078141776
12.221304078132064
12.221304078122374
12.221304078112674
12.221304078102976
12.22130407809328
12.221304078083591
12.221304078073898
12.221304078064207
12.221304078054523
12.221304078044838
12.221304078035162
12.221304078025485
12.221304078015805
12.22130407800613
12.221304077996455
12.221304077986783
12.221304077977114
12.221304077967453
12.221304077957788
12.221304077948126
12.22130407793846
12.221304077928803
12.221304077919152
12.221304077909492
12.22130407789984
12.221304077890185
12.221304077880546
12.221304077870906
12.221304077861252
12.221304077851613
12.221304077841975
12.221304077832334
12.221304077822706
12.221304077813063
12.221304077803447
12.221304077793812
12.221304077784186
12.221304077774558
12.221304077764932
12.221304077755313
12.2213040777457
12.221304077736082
12.221304077726469
12.221304077716852
12.221304077707241
12.221304077697631
12.221304077688034
12.221304077678427
12.221304077668819
12.221304077659221
12.221304077649629
12.221304077640035
12.22130407763044
12.221304077620854
12.221304077611261
12.221304077601669
12.221304077592087
12.221304077582502
12.221304077572922
12.221304077563344
12.221304077553759
12.221304077544188
12.221304077534628
12.221304077525051
12.221304077515482
12.22130407750591
12.221304077496347
12.221304077486785
12.221304077477225
12.221304077467671
12.221304077458115
12.221304077448563
12.221304077439006
12.221304077429464
12.22130407741991
12.22130407741036
12.221304077400823
12.221304077391276
12.221304077381737
12.221304077372205
12.221304077362666
12.22130407735313
12.221304077343598
12.221304077334075
12.221304077324548
12.221304077315017
12.2213040773055
12.221304077295976
12.221304077286458
12.221304077276939
12.221304077267426
12.22130407725792
12.2213040772484
12.221304077238898
12.221304077229387
12.22130407721988
12.221304077210382
12.22130407720088
12.221304077191384
12.22130407718189
12.221304077172388
12.221304077162898
12.221304077153412
12.22130407714392
12.221304077134432
12.221304077124953
12.221304077115477
12.221304077105987
12.221304077096525
12.221304077087042
12.22130407707757
12.221304077068096
12.221304077058626
12.22130407704916
12.221304077039697
12.22130407703023
12.221304077020767
12.221304077011311
12.221304077001854
12.221304076992398
12.221304076982946
12.221304076973496
12.221304076964053
12.221304076954596
12.221304076945152
12.221304076935713
12.221304076926272
12.221304076916834
12.221304076907394
12.221304076897963
12.221304076888531
12.2213040768791
12.221304076869677
12.221304076860243
12.221304076850815
12.221304076841404
12.221304076831979
12.221304076822562
12.221304076813144
12.221304076803733
12.221304076794326
12.22130407678491
12.221304076775501
12.221304076766097
12.221304076756686
12.22130407674729
12.221304076737894
12.221304076728496
12.221304076719107
12.221304076709702
12.221304076700314
12.221304076690917
12.22130407668154
12.22130407667216
12.221304076662765
12.221304076653384
12.221304076644001
12.221304076634631
12.221304076625254
12.221304076615885
12.22130407660651
12.221304076597137
12.221304076587773
12.22130407657841
12.221304076569043
12.221304076559678
12.221304076550327
12.22130407654097
12.22130407653161
12.221304076522262
12.221304076512912
12.221304076503557
12.221304076494214
12.22130407648487
12.221304076475526
12.221304076466186
12.221304076456846
12.221304076447502
12.221304076438177
12.221304076428838
12.221304076419518
12.221304076410188
12.221304076400857
12.221304076391531
12.221304076382209
12.221304076372899
12.221304076363577
12.22130407635425
12.221304076344943
12.221304076335633
12.221304076326323
12.221304076317013
12.221304076307705
12.221304076298402
12.221304076289098
12.2213040762798
12.221304076270503
12.221304076261204
12.221304076251906
12.221304076242612
12.221304076233327
12.221304076224031
12.221304076214754
12.22130407620547
12.22130407619619
12.221304076186907
12.22130407617763
12.221304076168352
12.221304076159077
12.221304076149808
12.22130407614053
12.221304076131265
12.221304076122
12.221304076112741
12.221304076103474
12.221304076094215
12.221304076084959
12.221304076075704
12.221304076066453
12.221304076057198
12.221304076047943
12.221304076038697
12.221304076029451
12.221304076020207
12.22130407601097
12.221304076001728
12.22130407599249
12.221304075983252
12.221304075974022
12.221304075964788
12.221304075955567
12.221304075946332
12.221304075937098
12.221304075927884
12.221304075918658
12.221304075909435
12.221304075900221
12.221304075891009
12.221304075881791
12.22130407587258
12.221304075863372
12.22130407585416
12.221304075844955
12.221304075835752
12.221304075826557
12.221304075817354
12.22130407580815
12.221304075798958
12.221304075789766
12.221304075780578
12.221304075771382
12.221304075762195
12.221304075753004
12.221304075743822
12.221304075734643
12.22130407572546
12.221304075716292
12.221304075707106
12.221304075697937
12.221304075688764
12.221304075679598
12.221304075670423
12.221304075661259
12.2213040756521
12.221304075642932
12.22130407563378
12.221304075624621
12.221304075615457
12.221304075606303
12.221304075597153
12.221304075588003
12.221304075578855
12.221304075569705
12.22130407556057
12.22130407555142
12.221304075542285
12.221304075533146
12.221304075524007
12.221304075514869

12.221304075505746
12.221304075496612
12.221304075487486
12.221304075478354
12.221304075469233
12.221304075460107
12.221304075450993
12.221304075441877
12.221304075432752
12.221304075423642
12.221304075414528
12.221304075405415
12.221304075396313
12.221304075387199
12.221304075378102
12.221304075369
12.2213040753599
12.221304075350798
12.2213040753417
12.2213040753326
12.221304075323513
12.221304075314421
12.221304075305339
12.221304075296253
12.221304075287163
12.221304075278077
12.221304075269009
12.221304075259921
12.221304075250846
12.221304075241774
12.221304075232704
12.221304075223625
12.221304075214553
12.221304075205492
12.221304075196423
12.221304075187364
12.221304075178303
12.221304075169252
12.221304075160182
12.22130407515113
12.221304075142076
12.221304075133022
12.221304075123985
12.221304075114931
12.221304075105888
12.221304075096835
12.2213040750878
12.221304075078761
12.221304075069721
12.221304075060683
12.221304075051652
12.221304075042621
12.221304075033592
12.221304075024566
12.221304075015533
12.221304075006515
12.221304074997493
12.221304074988469
12.221304074979459
12.221304074970433
12.221304074961425
12.22130407495242
12.221304074943406
12.221304074934395
12.221304074925389
12.22130407491638
12.22130407490738
12.221304074898383
12.221304074889382
12.221304074880386
12.2213040748714
12.221304074862394
12.221304074853405
12.221304074844426
12.221304074835432
12.221304074826456
12.221304074817471
12.221304074808481
12.221304074799509
12.221304074790533
12.22130407478155
12.221304074772585
12.221304074763614
12.221304074754638
12.221304074745673
12.221304074736707
12.221304074727751
12.221304074718788
12.221304074709824
12.22130407470087
12.221304074691911
12.221304074682955
12.22130407467401
12.22130407466506
12.221304074656112
12.221304074647168
12.221304074638223
12.22130407462928
12.221304074620337
12.2213040746114
12.221304074602463
12.221304074593528
12.221304074584596
12.221304074575668
12.221304074566735
12.221304074557812
12.22130407454889
12.221304074539965
12.22130407453105
12.221304074522129
12.22130407451321
12.221304074504289
12.221304074495384
12.221304074486468
12.221304074477562
12.221304074468662
12.221304074459756
12.221304074450853
12.221304074441951
12.221304074433048
12.22130407442415
12.22130407441526
12.221304074406353
12.221304074397464
12.22130407438858
12.22130407437969
12.2213040743708
12.221304074361917
12.221304074353037
12.22130407434416
12.221304074335283
12.22130407432641
12.221304074317533
12.221304074308652
12.22130407429979
12.221304074290918
12.221304074282056
12.221304074273192
12.221304074264328
12.22130407425547
12.221304074246609
12.221304074237755
12.221304074228897
12.221304074220042
12.221304074211192
12.22130407420234
12.221304074193505
12.22130407418465
12.2213040741758
12.22130407416697
12.221304074158128
12.221304074149282
12.221304074140448
12.221304074131616
12.221304074122791
12.221304074113956
12.221304074105129
12.22130407409631
12.221304074087477
12.221304074078652
12.221304074069836
12.221304074061017
12.2213040740522
12.221304074043385
12.221304074034567
12.221304074025754
12.22130407401695
12.221304074008138
12.221304073999335
12.221304073990536
12.221304073981736
12.221304073972936
12.221304073964143
12.221304073955343
12.22130407394655
12.221304073937752
12.221304073928966
12.221304073920178
12.221304073911393
12.22130407390261
12.22130407389383
12.221304073885047
12.221304073876265
12.221304073867493
12.221304073858708
12.221304073849943
12.221304073841173
12.221304073832405
12.221304073823632
12.221304073814876
12.221304073806108
12.221304073797349
12.22130407378859
12.221304073779832
12.22130407377108
12.221304073762326
12.221304073753572
12.22130407374482
12.221304073736075
12.221304073727323
12.221304073718576
12.22130407370984
12.221304073701097
12.221304073692359
12.221304073683632
12.221304073674887
12.22130407366616
12.221304073657425
12.221304073648694
12.22130407363997
12.221304073631245
12.221304073622525
12.2213040736138
12.221304073605074
12.221304073596361
12.221304073587644
12.221304073578935
12.221304073570213
12.221304073561502
12.221304073552801
12.221304073544093
12.221304073535388
12.221304073526687
12.221304073517985
12.221304073509286
12.221304073500598
12.221304073491897
12.221304073483207
12.221304073474517
12.221304073465818
12.221304073457134
12.221304073448445
12.221304073439772
12.221304073431089
12.221304073422406
12.22130407341373
12.221304073405053
12.221304073396375
12.221304073387712
12.22130407337903
12.221304073370364
12.221304073361692
12.221304073353037
12.221304073344378
12.22130407333571
12.221304073327047
12.221304073318398
12.221304073309739
12.221304073301088
12.221304073292437
12.221304073283784
12.221304073275142
12.22130407326649
12.221304073257848
12.221304073249204
12.221304073240566
12.221304073231927
12.221304073223289
12.221304073214649
12.221304073206019
12.22130407319739
12.221304073188765
12.221304073180136
12.221304073171506
12.221304073162885
12.221304073154261
12.22130407314564
12.22130407313702
12.22130407312841
12.221304073119795
12.221304073111183
12.221304073102571
12.22130407309396
12.221304073085358
12.221304073076753
12.221304073068149
12.22130407305955
12.221304073050945
12.221304073042349
12.221304073033757
12.221304073025165
12.221304073016569
12.22130407300798
12.22130407299939
12.221304072990804
12.221304072982228
12.221304072973643
12.221304072965056
12.221304072956485
12.221304072947902
12.221304072939327
12.22130407293075
12.221304072922178
12.221304072913615
12.221304072905047
12.221304072896483
12.221304072887916
12.221304072879352
12.221304072870794
12.221304072862235
12.221304072853679
12.221304072845124
12.22130407283657
12.22130407282802
12.221304072819471
12.221304072810916
12.221304072802381
12.221304072793835
12.221304072785292
12.221304072776753
12.22130407276821
12.221304072759677
12.221304072751142
12.221304072742614
12.22130407273408
12.221304072725557
12.221304072717032
12.221304072708506
12.22130407269998
12.221304072691462
12.22130407268294
12.22130407267442
12.221304072665907
12.221304072657391
12.221304072648877
12.221304072640365
12.221304072631863
12.221304072623358
12.221304072614853
12.22130407260635
12.221304072597851
12.221304072589357
12.221304072580853
12.221304072572353
12.221304072563864
12.221304072555368
12.221304072546879
12.221304072538393
12.22130407252991
12.221304072521423
12.221304072512938
12.221304072504457
12.221304072495984
12.2213040724875
12.221304072479027
12.221304072470556
12.22130407246209
12.221304072453615
12.22130407244515
12.22130407243668
12.221304072428214
12.221304072419754
12.221304072411296
12.221304072402837
12.22130407239438
12.221304072385923
12.221304072377478
12.221304072369021
12.221304072360569
12.221304072352124
12.221304072343676
12.221304072335233
12.221304072326785
12.221304072318352
12.221304072309911
12.221304072301475
12.221304072293037
12.221304072284614
12.221304072276178
12.221304072267747
12.221304072259318
12.221304072250891
12.221304072242472
12.221304072234055
12.221304072225632
12.221304072217212
12.221304072208797
12.221304072200386
12.221304072191973
12.221304072183559
12.221304072175144
12.221304072166742
12.221304072158341
12.221304072149934
12.221304072141534
12.22130407213313
12.221304072124736
12.221304072116334
12.221304072107943
12.221304072099544
12.221304072091163
12.221304072082768
12.22130407207438
12.221304072065992
12.221304072057613
12.22130407204923
12.221304072040848
12.221304072032472
12.221304072024097
12.221304072015721
12.22130407200735
12.22130407199899
12.221304071990613
12.221304071982239
12.22130407197387
12.221304071965513
12.22130407195715
12.221304071948797
12.221304071940432
12.221304071932078
12.221304071923722
12.221304071915366
12.221304071907019
12.221304071898674
12.221304071890321
12.221304071881974
12.221304071873636
12.221304071865287
12.221304071856956
12.221304071848616
12.221304071840274
12.221304071831943
12.221304071823605
12.221304071815275
12.221304071806948
12.221304071798627
12.2213040717903
12.221304071781978
12.22130407177365
12.221304071765335
12.221304071757013
12.221304071748687
12.221304071740377
12.221304071732064
12.221304071723765
12.221304071715451
12.221304071707138
12.22130407169883
12.221304071690527
12.221304071682228
12.221304071673934
12.22130407166563
12.221304071657334
12.22130407164904

12.221304071640743
12.221304071632458
12.221304071624163
12.221304071615876
12.221304071607586
12.221304071599302
12.22130407159102
12.221304071582747
12.221304071574467
12.221304071566188
12.22130407155791
12.221304071549639
12.221304071541365
12.221304071533101
12.221304071524823
12.221304071516562
12.221304071508298
12.221304071500034
12.221304071491774
12.221304071483514
12.221304071475256
12.221304071467006
12.221304071458757
12.221304071450504
12.22130407144225
12.221304071434005
12.221304071425756
12.221304071417508
12.221304071409275
12.221304071401025
12.221304071392785
12.22130407138455
12.221304071376315
12.22130407136808
12.22130407135985
12.221304071351616
12.221304071343388
12.221304071335163
12.221304071326934
12.221304071318716
12.221304071310495
12.221304071302274
12.221304071294053
12.221304071285836
12.221304071277624
12.221304071269412
12.221304071261203
12.221304071252993
12.221304071244786
12.22130407123658
12.22130407122837
12.22130407122018
12.22130407121197
12.221304071203779
12.22130407119559
12.22130407118739
12.221304071179192
12.221304071171001
12.221304071162814
12.221304071154623
12.221304071146443
12.221304071138256
12.221304071130078
12.221304071121889
12.221304071113718
12.221304071105537
12.221304071097364
12.22130407108918
12.221304071081013
12.221304071072842
12.22130407106468
12.221304071056512
12.221304071048346
12.221304071040187
12.221304071032023
12.221304071023857
12.22130407101571
12.221304071007554
12.221304070999395
12.221304070991243
12.221304070983098
12.221304070974941
12.221304070966806
12.221304070958661
12.221304070950517
12.221304070942375
12.221304070934233
12.221304070926088
12.221304070917952
12.221304070909826
12.22130407090169
12.22130407089356
12.221304070885422
12.221304070877302
12.221304070869182
12.221304070861054
12.22130407085293
12.221304070844806
12.221304070836688
12.221304070828573
12.221304070820464
12.221304070812344
12.221304070804242
12.221304070796128
12.22130407078802
12.221304070779912
12.22130407077181
12.221304070763702
12.221304070755606
12.221304070747502
12.221304070739405
12.221304070731318
12.221304070723216
12.221304070715128
12.221304070707037
12.221304070698947
12.221304070690856
12.221304070682772
12.22130407067469
12.221304070666607
12.221304070658533
12.22130407065045
12.221304070642368
12.221304070634297
12.221304070626221
12.22130407061816
12.22130407061009
12.221304070602018
12.221304070593956
12.221304070585893
12.221304070577828
12.221304070569763
12.221304070561708
12.221304070553655
12.2213040705456
12.22130407053754
12.221304070529484
12.221304070521434
12.221304070513394
12.221304070505349
12.2213040704973
12.221304070489252
12.221304070481212
12.221304070473172
12.221304070465136
12.221304070457105
12.221304070449063
12.221304070441034
12.221304070433009
12.221304070424972
12.221304070416949
12.221304070408918
12.221304070400898
12.22130407039288
12.221304070384848
12.221304070376833
12.22130407036882
12.221304070360807
12.221304070352794
12.22130407034477
12.221304070336773
12.22130407032876
12.22130407032075
12.22130407031275
12.221304070304745
12.22130407029674
12.22130407028874
12.22130407028075
12.221304070272753
12.22130407026476
12.221304070256764
12.221304070248769
12.221304070240782
12.221304070232796
12.221304070224813
12.221304070216828
12.221304070208843
12.221304070200862
12.221304070192888
12.221304070184907
12.221304070176933
12.221304070168957
12.221304070160988
12.221304070153016
12.221304070145045
12.221304070137077
12.221304070129117
12.221304070121157
12.221304070113193
12.221304070105242
12.221304070097272
12.221304070089323
12.221304070081361
12.221304070073415
12.221304070065461
12.221304070057508
12.22130407004956
12.221304070041619
12.221304070033673
12.221304070025733
12.22130407001779
12.221304070009849
12.221304070001915
12.221304069993979
12.221304069986044
12.221304069978109
12.221304069970186
12.221304069962251
12.221304069954325
12.2213040699464
12.22130406993847
12.221304069930556
12.221304069922637
12.221304069914718
12.221304069906799
12.221304069898885
12.221304069890966
12.221304069883058
12.221304069875154
12.221304069867244
12.221304069859334
12.22130406985143
12.221304069843532
12.221304069835634
12.221304069827728
12.221304069819832
12.221304069811936
12.221304069804045
12.221304069796155
12.221304069788248
12.221304069780366
12.221304069772486
12.22130406976459
12.221304069756712
12.221304069748822
12.22130406974095
12.221304069733064
12.221304069725196
12.221304069717318
12.221304069709438
12.221304069701564
12.221304069693696
12.221304069685829
12.221304069677968
12.221304069670095
12.221304069662233
12.221304069654368
12.221304069646507
12.221304069638652
12.221304069630788
12.221304069622938
12.221304069615085
12.221304069607232
12.221304069599384
12.221304069591541
12.22130406958369
12.221304069575845
12.221304069568001
12.221304069560166
12.221304069552321
12.221304069544482
12.221304069536648
12.221304069528811
12.221304069520981
12.221304069513144
12.221304069505328
12.221304069497489
12.221304069489674
12.221304069481835
12.221304069474026
12.221304069466203
12.221304069458377
12.221304069450559
12.221304069442747
12.221304069434927
12.221304069427129
12.22130406941931
12.221304069411504
12.221304069403688
12.221304069395885
12.22130406938807
12.221304069380285
12.221304069372477
12.221304069364678
12.221304069356888
12.221304069349081
12.22130406934129
12.221304069333499
12.221304069325717
12.22130406931792
12.221304069310133
12.221304069302343
12.221304069294565
12.221304069286784
12.221304069279007
12.22130406927122
12.221304069263452
12.221304069255678
12.221304069247905
12.221304069240121
12.221304069232358
12.22130406922459
12.221304069216826
12.221304069209054
12.22130406920129
12.221304069193529
12.221304069185765
12.221304069178014
12.221304069170255
12.221304069162507
12.221304069154744
12.221304069146996
12.221304069139238
12.221304069131497
12.221304069123752
12.221304069116005
12.221304069108259
12.221304069100519
12.221304069092776
12.221304069085038
12.221304069077291
12.221304069069582
12.221304069061835
12.221304069054105
12.221304069046374
12.221304069038645
12.221304069030923
12.221304069023198
12.221304069015467
12.221304069007749
12.221304069000027
12.221304068992312
12.22130406898459
12.221304068976886
12.221304068969165
12.221304068961448
12.221304068953746
12.221304068946043
12.22130406893833
12.221304068930632
12.22130406892292
12.221304068915224
12.221304068907525
12.221304068899824
12.221304068892128
12.221304068884434
12.22130406887674
12.221304068869049
12.221304068861356
12.221304068853668
12.221304068845988
12.221304068838299
12.22130406883062
12.221304068822935
12.221304068815261
12.221304068807578
12.221304068799899
12.221304068792232
12.221304068784558
12.22130406877689
12.221304068769209
12.221304068761542
12.221304068753877
12.221304068746209
12.221304068738556
12.221304068730891
12.221304068723224
12.221304068715572
12.221304068707916
12.221304068700258
12.221304068692607
12.221304068684956
12.221304068677307
12.221304068669664
12.221304068662013
12.221304068654367
12.221304068646727
12.221304068639078
12.221304068631447
12.22130406862381
12.22130406861617
12.22130406860853
12.2213040686009
12.221304068593268
12.22130406858564
12.22130406857801
12.22130406857038
12.221304068562755
12.221304068555138
12.221304068547513
12.221304068539894
12.221304068532284
12.221304068524661
12.221304068517044
12.221304068509431
12.221304068501823
12.221304068494208
12.221304068486607
12.22130406847899
12.22130406847139
12.221304068463791
12.221304068456181
12.221304068448589
12.221304068440986
12.221304068433396
12.221304068425795
12.221304068418203
12.221304068410602
12.221304068403027
12.221304068395426
12.22130406838784
12.221304068380261
12.221304068372682
12.221304068365095
12.221304068357512
12.221304068349939
12.221304068342361
12.221304068334776
12.221304068327205
12.221304068319636
12.221304068312065
12.22130406830449
12.221304068296932
12.221304068289363
12.221304068281798
12.221304068274238
12.221304068266681
12.221304068259112
12.221304068251557
12.221304068244004
12.221304068236451
12.221304068228898
12.221304068221347
12.221304068213797
12.221304068206253
12.221304068198702
12.221304068191163
12.221304068183613
12.221304068176076
12.221304068168537
12.221304068161004
12.22130406815347
12.221304068145932
12.2213040681384
12.22130406813087
12.221304068123343
12.221304068115812
12.221304068108278
12.221304068100762
12.221304068093234
12.221304068085713
12.221304068078192
12.221304068070674
12.221304068063159
12.221304068055645
12.221304068048127
12.221304068040618
12.22130406803311
12.221304068025605
12.221304068018094
12.221304068010587
12.22130406800309
12.221304067995582
12.22130406798809
12.221304067980585
12.22130406797309
12.221304067965596
12.2213040679581
12.221304067950605
12.221304067943114
12.221304067935629

12.221304067928148
12.221304067920661
12.221304067913175
12.221304067905688
12.221304067898213
12.221304067890728
12.221304067883251
12.221304067875778
12.221304067868305
12.221304067860832
12.22130406785336
12.221304067845894
12.221304067838423
12.221304067830957
12.221304067823498
12.22130406781603
12.221304067808571
12.221304067801114
12.221304067793659
12.221304067786193
12.221304067778739
12.221304067771287
12.221304067763839
12.221304067756387
12.221304067748937
12.22130406774149
12.22130406773405
12.221304067726606
12.22130406771917
12.221304067711722
12.221304067704287
12.221304067696847
12.221304067689406
12.221304067681972
12.221304067674547
12.22130406766712
12.22130406765969
12.221304067652252
12.221304067644828
12.22130406763741
12.221304067629989
12.221304067622565
12.221304067615147
12.22130406760773
12.221304067600315
12.2213040675929
12.221304067585491
12.221304067578073
12.221304067570664
12.221304067563251
12.221304067555849
12.221304067548445
12.221304067541041
12.221304067533643
12.221304067526244
12.221304067518846
12.22130406751145
12.221304067504056
12.221304067496662
12.22130406748927
12.221304067481876
12.22130406747449
12.221304067467102
12.221304067459716
12.221304067452332
12.221304067444951
12.221304067437565
12.221304067430196
12.221304067422814
12.221304067415435
12.221304067408065
12.221304067400684
12.221304067393325
12.221304067385953
12.221304067378584
12.221304067371216
12.221304067363851
12.221304067356495
12.221304067349127
12.221304067341762
12.221304067334401
12.22130406732705
12.221304067319696
12.221304067312344
12.221304067304997
12.221304067297647
12.22130406729029
12.221304067282947
12.221304067275593
12.221304067268253
12.221304067260917
12.221304067253572
12.22130406724624
12.221304067238894
12.221304067231564
12.221304067224231
12.221304067216895
12.221304067209557
12.221304067202233
12.221304067194902
12.22130406718758
12.221304067180254
12.221304067172928
12.221304067165608
12.221304067158293
12.221304067150975
12.221304067143652
12.221304067136337
12.22130406712903
12.221304067121707
12.221304067114403
12.221304067107097
12.221304067099789
12.221304067092488
12.221304067085178
12.221304067077876
12.221304067070577
12.221304067063285
12.22130406705598
12.221304067048683
12.221304067041382
12.221304067034094
12.221304067026805
12.221304067019513
12.221304067012225
12.221304067004935
12.221304066997657
12.221304066990365
12.22130406698309
12.221304066975806
12.221304066968527
12.221304066961252
12.221304066953977
12.221304066946702
12.22130406693942
12.22130406693216
12.22130406692489
12.221304066917622
12.221304066910353
12.221304066903091
12.221304066895831
12.22130406688856
12.221304066881297
12.221304066874051
12.221304066866791
12.221304066859533
12.22130406685228
12.22130406684503
12.221304066837781
12.221304066830534
12.221304066823286
12.22130406681603
12.221304066808793
12.221304066801547
12.221304066794314
12.22130406678707
12.221304066779828
12.221304066772593
12.221304066765363
12.221304066758128
12.221304066750898
12.221304066743665
12.221304066736435
12.221304066729214
12.221304066721988
12.221304066714762
12.221304066707537
12.221304066700323
12.2213040666931
12.221304066685885
12.221304066678673
12.221304066671456
12.221304066664242
12.221304066657032
12.221304066649816
12.221304066642613
12.221304066635406
12.221304066628196
12.221304066620997
12.221304066613786
12.221304066606594
12.221304066599394
12.221304066592197
12.221304066585008
12.221304066577812
12.221304066570621
12.221304066563423
12.22130406655624
12.221304066549054
12.221304066541864
12.221304066534682
12.221304066527502
12.221304066520318
12.221304066513136
12.221304066505956
12.221304066498782
12.22130406649161
12.221304066484432
12.221304066477261
12.221304066470093
12.221304066462915
12.221304066455753
12.221304066448585
12.221304066441421
12.221304066434257
12.221304066427097
12.221304066419936
12.221304066412781
12.221304066405624
12.221304066398464
12.221304066391316
12.221304066384166
12.22130406637701
12.22130406636986
12.221304066362713
12.221304066355568
12.221304066348429
12.221304066341286
12.221304066334142
12.221304066327004
12.22130406631987
12.221304066312728
12.221304066305594
12.22130406629846
12.221304066291328
12.221304066284196
12.221304066277069
12.22130406626995
12.221304066262817
12.22130406625569
12.22130406624857
12.22130406624145
12.221304066234332
12.221304066227216
12.221304066220096
12.221304066212976
12.221304066205867
12.221304066198757
12.221304066191646
12.22130406618454
12.221304066177435
12.221304066170328
12.221304066163226
12.221304066156119
12.221304066149017
12.221304066141917
12.221304066134824
12.221304066127718
12.221304066120622
12.221304066113534
12.221304066106446
12.221304066099355
12.22130406609226
12.221304066085182
12.221304066078096
12.22130406607101
12.221304066063926
12.221304066056847
12.221304066049765
12.221304066042693
12.221304066035607
12.22130406602854
12.221304066021466
12.22130406601439
12.22130406600732
12.221304066000258
12.221304065993188
12.221304065986121
12.221304065979057
12.221304065971998
12.221304065964937
12.221304065957876
12.221304065950818
12.221304065943762
12.221304065936707
12.221304065929655
12.221304065922599
12.22130406591555
12.2213040659085
12.221304065901455
12.221304065894408
12.221304065887367
12.22130406588032
12.221304065873285
12.221304065866244
12.221304065859204
12.221304065852168
12.221304065845127
12.221304065838103
12.22130406583107
12.221304065824036
12.22130406581701
12.221304065809974
12.221304065802963
12.221304065795938
12.221304065788917
12.22130406578188
12.221304065774873
12.221304065767855
12.22130406576083
12.22130406575382
12.221304065746805
12.221304065739798
12.221304065732781
12.221304065725773
12.221304065718774
12.221304065711763
12.221304065704752
12.221304065697758
12.22130406569075
12.221304065683753
12.22130406567675
12.221304065669765
12.221304065662762
12.22130406565577
12.22130406564878
12.221304065641785
12.221304065634795
12.221304065627809
12.221304065620824
12.221304065613838
12.221304065606857
12.221304065599876
12.221304065592896
12.221304065585914
12.22130406557894
12.221304065571958
12.221304065564988
12.221304065558007
12.221304065551044
12.221304065544075
12.221304065537108
12.221304065530138
12.221304065523176
12.221304065516208
12.221304065509246
12.221304065502288
12.221304065495328
12.221304065488374
12.221304065481418
12.221304065474456
12.221304065467502
12.221304065460558
12.221304065453616
12.221304065446652
12.221304065439707
12.221304065432774
12.221304065425823
12.22130406541888
12.221304065411937
12.221304065405002
12.221304065398062
12.221304065391124
12.22130406538419
12.221304065377257
12.221304065370322
12.221304065363391
12.221304065356465
12.221304065349537
12.221304065342617
12.221304065335685
12.221304065328766
12.221304065321847
12.221304065314929
12.221304065308006
12.22130406530109
12.22130406529418
12.221304065287264
12.221304065280354
12.221304065273438
12.221304065266523
12.22130406525962
12.221304065252719
12.221304065245803
12.221304065238908
12.221304065232012
12.2213040652251
12.22130406521821
12.22130406521131
12.221304065204414
12.22130406519752
12.221304065190623
12.221304065183736
12.22130406517684
12.221304065169955
12.221304065163068
12.22130406515618
12.221304065149301
12.221304065142423
12.22130406513554
12.22130406512866
12.221304065121778
12.221304065114905
12.221304065108027
12.221304065101151
12.221304065094277
12.221304065087411
12.221304065080542
12.22130406507367
12.221304065066818
12.221304065059943
12.221304065053086
12.22130406504622
12.221304065039362
12.221304065032498
12.221304065025645
12.221304065018792
12.221304065011937
12.221304065005084
12.221304064998233
12.221304064991385
12.221304064984535
12.22130406497769
12.221304064970845
12.221304064964002
12.22130406495716
12.221304064950317
12.221304064943483
12.221304064936641
12.221304064929804
12.221304064922967
12.221304064916138
12.221304064909305
12.221304064902478
12.22130406489565
12.221304064888814
12.221304064882
12.221304064875161
12.221304064868349
12.221304064861524
12.221304064854703
12.221304064847887
12.22130406484107
12.221304064834252
12.221304064827441
12.22130406482062
12.221304064813816
12.221304064807008
12.221304064800199
12.22130406479339
12.22130406478659
12.22130406477978
12.221304064772985
12.221304064766185
12.221304064759385
12.221304064752587
12.221304064745782
12.221304064738996
12.221304064732202
12.221304064725405
12.221304064718616
12.221304064711832
12.221304064705043
12.22130406469826
12.221304064691473
12.221304064684684
12.22130406467791
12.22130406467113
12.221304064664348
12.221304064657568
12.221304064650795
12.22130406464402
12.221304064637248
12.221304064630482
12.221304064623714
12.221304064616936
12.221304064610168
12.221304064603407
12.221304064596639
12.22130406458988
12.221304064583117
12.221304064576355
12.221304064569603
12.22130406456285
12.221304064556087
12.221304064549338
12.221304064542593
12.221304064535829
12.221304064529084
12.221304064522338
12.221304064515586
12.221304064508852
12.221304064502098
12.221304064495362
12.22130406448862
12.221304064481881
12.221304064475143
12.221304064468411
12.221304064461668
12.221304064454943
12.221304064448205
12.221304064441473
12.221304064434747
12.22130406442802
12.221304064421298
12.221304064414575
12.22130406440785
12.221304064401128
12.221304064394406
12.221304064387688
12.221304064380977
12.221304064374255
12.22130406436754
12.221304064360831
12.221304064354117
12.221304064347407
12.221304064340696
12.221304064333992
12.221304064327287
12.221304064320588
12.221304064313884
12.221304064307175
12.221304064300478
12.22130406429378
12.22130406428709
12.221304064280389
12.221304064273697
12.221304064267011
12.22130406426031
12.221304064253625
12.221304064246947
12.22130406424025
12.22130406423357
12.221304064226883
12.221304064220194
12.221304064213518
12.221304064206844
12.22130406420016
12.221304064193484
12.221304064186805
12.221304064180131
12.221304064173461
12.2213040641668
12.22130406416013
12.221304064153454
12.221304064146793
12.221304064140133
12.22130406413347
12.221304064126805
12.22130406412014
12.221304064113486
12.221304064106821
12.221304064100169
12.221304064093518
12.22130406408686
12.221304064080204
12.221304064073559
12.221304064066913
12.221304064060263
12.221304064053621
12.221304064046976
12.221304064040329
12.221304064033683
12.221304064027045
12.221304064020416
12.221304064013777
12.221304064007136
12.221304064000508
12.221304063993871
12.22130406398724
12.221304063980607
12.221304063973975
12.221304063967354
12.221304063960728
12.221304063954099
12.22130406394748
12.221304063940856
12.22130406393424
12.221304063927617
12.221304063921
12.221304063914383
12.22130406390777
12.221304063901162
12.221304063894546
12.221304063887944
12.221304063881327
12.221304063874726
12.221304063868114
12.221304063861513
12.221304063854909
12.221304063848303
12.221304063841698

12.221304063835111
12.221304063828514
12.221304063821918
12.221304063815323
12.221304063808734
12.22130406380214
12.221304063795541
12.221304063788958
12.221304063782377
12.22130406377579
12.221304063769203
12.221304063762618
12.221304063756042
12.221304063749454
12.22130406374288
12.22130406373629
12.221304063729727
12.221304063723158
12.22130406371658
12.22130406371001
12.221304063703435
12.22130406369687
12.221304063690305
12.221304063683734
12.221304063677179
12.22130406367061
12.221304063664045
12.221304063657492
12.221304063650924
12.221304063644371
12.221304063637819
12.22130406363126
12.2213040636247
12.221304063618158
12.2213040636116
12.22130406360506
12.22130406359851
12.221304063591962
12.22130406358542
12.22130406357888
12.221304063572344
12.221304063565794
12.221304063559257
12.221304063552719
12.221304063546189
12.221304063539655
12.221304063533124
12.22130406352659
12.22130406352006
12.221304063513525
12.221304063507004
12.221304063500476
12.221304063493951
12.221304063487429
12.221304063480906
12.22130406347438
12.221304063467867
12.221304063461348
12.221304063454838
12.22130406344832
12.221304063441806
12.221304063435289
12.221304063428788
12.221304063422274
12.22130406341576
12.221304063409258
12.221304063402757
12.221304063396252
12.221304063389747
12.221304063383242
12.221304063376754
12.221304063370251
12.221304063363768
12.221304063357264
12.221304063350772
12.221304063344286
12.221304063337785
12.221304063331297
12.22130406332481
12.221304063318327
12.221304063311834
12.221304063305356
12.221304063298879
12.22130406329239
12.221304063285912
12.221304063279433
12.221304063272955
12.221304063266484
12.221304063260003
12.221304063253537
12.221304063247068
12.221304063240597
12.221304063234127
12.22130406322766
12.221304063221202
12.221304063214737
12.221304063208265
12.221304063201808
12.221304063195353
12.221304063188892
12.221304063182432
12.221304063175982
12.221304063169523
12.221304063163075
12.221304063156625
12.221304063150173
12.221304063143723
12.221304063137275
12.22130406313083
12.221304063124387
12.221304063117946
12.221304063111505
12.221304063105059
12.221304063098621
12.221304063092184
12.221304063085752
12.221304063079318
12.221304063072886
12.221304063066459
12.221304063060028
12.221304063053598
12.221304063047162
12.221304063040739
12.221304063034308
12.221304063027896
12.22130406302147
12.221304063015051
12.221304063008635
12.221304063002208
12.2213040629958
12.221304062989379
12.221304062982968
12.221304062976555
12.221304062970143
12.221304062963736
12.22130406295733
12.221304062950923
12.221304062944524
12.221304062938108
12.22130406293171
12.221304062925308
12.221304062918907
12.221304062912505
12.221304062906112
12.221304062899717
12.22130406289332
12.221304062886936
12.221304062880533
12.22130406287415
12.22130406286776
12.221304062861376
12.221304062854992
12.221304062848601
12.22130406284223
12.221304062835836
12.221304062829459
12.221304062823075
12.221304062816703
12.221304062810328
12.221304062803952
12.221304062797582
12.221304062791205
12.221304062784839
12.221304062778465
12.221304062772097
12.221304062765725
12.221304062759367
12.221304062753001
12.221304062746638
12.221304062740286
12.221304062733921
12.221304062727569
12.221304062721211
12.221304062714848
12.221304062708503
12.221304062702151
12.2213040626958
12.22130406268945
12.221304062683101
12.221304062676758
12.221304062670395
12.221304062664059
12.221304062657719
12.221304062651372
12.22130406264504
12.221304062638698
12.221304062632354
12.221304062626025
12.221304062619682
12.221304062613358
12.221304062607025
12.221304062600689
12.221304062594356
12.221304062588034
12.221304062581703
12.221304062575381
12.221304062569065
12.221304062562739
12.221304062556415
12.221304062550097
12.221304062543782
12.221304062537456
12.221304062531143
12.221304062524831
12.221304062518513
12.22130406251221
12.221304062505896
12.221304062499588
12.221304062493278
12.221304062486979
12.221304062480675
12.221304062474369
12.221304062468066
12.221304062461765
12.22130406245546
12.221304062449171
12.221304062442872
12.221304062436575
12.221304062430285
12.221304062423993
12.221304062417707
12.221304062411415
12.22130406240513
12.221304062398838
12.221304062392552
12.221304062386269
12.221304062379984
12.221304062373704
12.221304062367418
12.221304062361146
12.221304062354864
12.221304062348596
12.221304062342314
12.221304062336047
12.22130406232977
12.221304062323503
12.221304062317238
12.221304062310969
12.221304062304693
12.221304062298433
12.221304062292182
12.221304062285906
12.22130406227965
12.221304062273388
12.221304062267132
12.22130406226087
12.221304062254625
12.22130406224837
12.221304062242105
12.221304062235868
12.221304062229615
12.22130406222336
12.221304062217113
12.221304062210868
12.22130406220462
12.221304062198385
12.221304062192134
12.221304062185894
12.221304062179659
12.221304062173424
12.22130406216719
12.221304062160948
12.221304062154715
12.221304062148478
12.221304062142252
12.221304062136022
12.221304062129798
12.221304062123572
12.221304062117346
12.221304062111116
12.221304062104895
12.221304062098666
12.22130406209245
12.221304062086233
12.221304062080018
12.221304062073797
12.221304062067588
12.221304062061378
12.221304062055168
12.221304062048958
12.221304062042744
12.221304062036532
12.22130406203033
12.221304062024117
12.221304062017923
12.221304062011711
12.221304062005512
12.221304061999314
12.221304061993113
12.221304061986915
12.22130406198072
12.22130406197452
12.221304061968336
12.221304061962142
12.221304061955957
12.221304061949752
12.221304061943568
12.221304061937387
12.2213040619312
12.221304061925018
12.221304061918834
12.221304061912655
12.221304061906475
12.221304061900298
12.22130406189412
12.221304061887945
12.221304061881773
12.221304061875605
12.221304061869425
12.221304061863254
12.221304061857083
12.221304061850919
12.221304061844751
12.22130406183859
12.221304061832425
12.221304061826263
12.221304061820094
12.221304061813937
12.221304061807777
12.221304061801625
12.221304061795461
12.221304061789308
12.221304061783163
12.221304061777007
12.221304061770857
12.221304061764709
12.221304061758557
12.221304061752416
12.221304061746267
12.221304061740128
12.221304061733985
12.221304061727842
12.221304061721696
12.221304061715566
12.221304061709422
12.22130406170329
12.221304061697149
12.22130406169102
12.221304061684888
12.221304061678763
12.221304061672635
12.221304061666503
12.221304061660375
12.22130406165425
12.22130406164813
12.221304061642005
12.221304061635882
12.221304061629768
12.22130406162365
12.22130406161753
12.221304061611416
12.221304061605297
12.221304061599186
12.221304061593074
12.221304061586968
12.22130406158085
12.221304061574749
12.221304061568642
12.221304061562535
12.221304061556433
12.221304061550324
12.221304061544226
12.221304061538126
12.22130406153203
12.221304061525931
12.221304061519836
12.221304061513745
12.221304061507654
12.221304061501558
12.221304061495461
12.221304061489375
12.221304061483286
12.221304061477198
12.221304061471121
12.221304061465036
12.221304061458952
12.221304061452866
12.221304061446785
12.221304061440714
12.221304061434632
12.221304061428558
12.221304061422483
12.22130406141641
12.22130406141034
12.221304061404268
12.221304061398198
12.221304061392125
12.221304061386064
12.22130406137999
12.221304061373933
12.221304061367873
12.221304061361808
12.221304061355749
12.221304061349683
12.22130406134363
12.22130406133757
12.221304061331521
12.221304061325466
12.221304061319413
12.22130406131336
12.221304061307306
12.221304061301266
12.221304061295223
12.221304061289176
12.221304061283128
12.221304061277078
12.221304061271036
12.221304061265005
12.221304061258959
12.221304061252926
12.221304061246885
12.221304061240849
12.22130406123482
12.221304061228786
12.221304061222753
12.221304061216724
12.2213040612107
12.22130406120467
12.221304061198646
12.22130406119262
12.221304061186597
12.221304061180573
12.221304061174546
12.221304061168528
12.22130406116251
12.221304061156502
12.221304061150473
12.221304061144467
12.22130406113845
12.221304061132441
12.221304061126423
12.221304061120415
12.22130406111441
12.221304061108404
12.221304061102403
12.221304061096394
12.22130406109039
12.221304061084396
12.221304061078392
12.22130406107239
12.22130406106639
12.221304061060398
12.221304061054411
12.221304061048402
12.221304061042416
12.221304061036426
12.221304061030436
12.22130406102445
12.22130406101846
12.221304061012473
12.22130406100649
12.221304061000504
12.221304060994528
12.221304060988547
12.221304060982572
12.221304060976587
12.221304060970615
12.22130406096464
12.22130406095866
12.221304060952695
12.221304060946721
12.22130406094075
12.221304060934779
12.221304060928812
12.221304060922847
12.221304060916882
12.221304060910924
12.221304060904957
12.221304060898992
12.221304060893036
12.221304060887077
12.221304060881115
12.221304060875166
12.221304060869205
12.22130406086326
12.221304060857305
12.22130406085135
12.2213040608454
12.22130406083945
12.221304060833505
12.221304060827556
12.221304060821618
12.221304060815678
12.221304060809734

12.2213040608038
12.221304060797856
12.221304060791914
12.221304060785988
12.221304060780042
12.221304060774107
12.221304060768173
12.221304060762249
12.221304060756312
12.221304060750384
12.221304060744455
12.221304060738527
12.221304060732601
12.221304060726682
12.221304060720755
12.221304060714836
12.221304060708926
12.221304060702998
12.221304060697088
12.221304060691175
12.221304060685256
12.221304060679332
12.221304060673424
12.221304060667514
12.221304060661607
12.221304060655697
12.22130406064979
12.221304060643886
12.221304060637978
12.22130406063208
12.221304060626172
12.22130406062027
12.221304060614374
12.221304060608476
12.221304060602586
12.221304060596689
12.22130406059079
12.221304060584897
12.221304060579016
12.221304060573118
12.221304060567235
12.221304060561335
12.221304060555454
12.221304060549569
12.221304060543686
12.221304060537808
12.221304060531923
12.221304060526043
12.221304060520167
12.221304060514283
12.221304060508404
12.221304060502531
12.221304060496655
12.221304060490787
12.221304060484915
12.22130406047905
12.221304060473175
12.22130406046731
12.22130406046144
12.221304060455584
12.221304060449716
12.221304060443853
12.221304060437989
12.22130406043214
12.221304060426274
12.221304060420417
12.221304060414564
12.221304060408707
12.221304060402852
12.221304060396998
12.221304060391148
12.2213040603853
12.221304060379452
12.221304060373601
12.221304060367762
12.221304060361911
12.22130406035607
12.22130406035023
12.221304060344385
12.22130406033855
12.221304060332711
12.221304060326867
12.221304060321035
12.221304060315205
12.221304060309373
12.221304060303538
12.221304060297703
12.221304060291883
12.221304060286052
12.221304060280227
12.221304060274395
12.221304060268572
12.22130406026275
12.221304060256928
12.221304060251109
12.221304060245288
12.221304060239468
12.221304060233654
12.221304060227846
12.221304060222028
12.221304060216218
12.221304060210393
12.221304060204591
12.221304060198781
12.221304060192978
12.221304060187167
12.22130406018136
12.221304060175552
12.221304060169755
12.221304060163957
12.22130406015815
12.221304060152356
12.22130406014655
12.22130406014076
12.221304060134958
12.221304060129173
12.22130406012338
12.221304060117584
12.221304060111793
12.221304060106009
12.221304060100225
12.221304060094429
12.221304060088645
12.22130406008286
12.221304060077086
12.221304060071303
12.221304060065513
12.221304060059738
12.221304060053967
12.221304060048185
12.221304060042412
12.22130406003664
12.221304060030866
12.221304060025089
12.22130406001932
12.221304060013555
12.221304060007782
12.221304060002014
12.221304059996251
12.221304059990496
12.221304059984726
12.22130405997897
12.221304059973209
12.22130405996744
12.22130405996169
12.22130405995594
12.221304059950171
12.221304059944417
12.22130405993867
12.22130405993292
12.221304059927169
12.221304059921426
12.22130405991568
12.221304059909935
12.221304059904188
12.221304059898445
12.221304059892699
12.221304059886954
12.221304059881215
12.221304059875477
12.221304059869748
12.221304059864005
12.221304059858264
12.221304059852534
12.221304059846803
12.221304059841074
12.221304059835337
12.221304059829608
12.22130405982388
12.221304059818147
12.22130405981243
12.221304059806709
12.221304059800985
12.221304059795262
12.221304059789539
12.221304059783817
12.221304059778102
12.221304059772386
12.22130405976667
12.221304059760955
12.22130405975524
12.221304059749533
12.221304059743824
12.221304059738115
12.221304059732407
12.221304059726698
12.221304059720993
12.221304059715285
12.22130405970959
12.221304059703888
12.22130405969819
12.221304059692493
12.221304059686783
12.221304059681096
12.221304059675393
12.221304059669697
12.221304059664007
12.221304059658316
12.221304059652626
12.221304059646942
12.221304059641254
12.22130405963556
12.22130405962988
12.221304059624194
12.221304059618506
12.22130405961283
12.221304059607139
12.221304059601469
12.221304059595782
12.221304059590114
12.22130405958444
12.221304059578765
12.221304059573086
12.22130405956741
12.221304059561739
12.22130405955607
12.221304059550404
12.221304059544739
12.22130405953907
12.221304059533407
12.221304059527748
12.221304059522083
12.221304059516424
12.22130405951076
12.221304059505107
12.221304059499444
12.221304059493793
12.22130405948814
12.221304059482483
12.221304059476825
12.221304059471183
12.221304059465528
12.221304059459875
12.221304059454239
12.221304059448585
12.221304059442945
12.221304059437298
12.221304059431652
12.221304059426021
12.22130405942038
12.221304059414738
12.221304059409098
12.221304059403456
12.221304059397823
12.221304059392192
12.221304059386563
12.221304059380925
12.221304059375298
12.221304059369668
12.221304059364039
12.221304059358415
12.22130405935279
12.221304059347164
12.221304059341549
12.221304059335921
12.221304059330292
12.221304059324686
12.221304059319067
12.221304059313448
12.221304059307831
12.221304059302216
12.221304059296601
12.221304059290995
12.221304059285378
12.221304059279772
12.221304059274164
12.221304059268554
12.22130405926295
12.221304059257346
12.221304059251745
12.221304059246135
12.221304059240534
12.221304059234933
12.221304059229336
12.22130405922374
12.221304059218141
12.221304059212546
12.221304059206958
12.221304059201364
12.221304059195775
12.221304059190185
12.221304059184591
12.221304059179003
12.22130405917342
12.221304059167831
12.221304059162247
12.221304059156665
12.221304059151088
12.22130405914551
12.221304059139923
12.221304059134347
12.221304059128766
12.221304059123195
12.221304059117625
12.22130405911205
12.221304059106478
12.221304059100905
12.221304059095337
12.221304059089762
12.2213040590842
12.221304059078635
12.221304059073068
12.2213040590675
12.221304059061946
12.22130405905638
12.221304059050828
12.221304059045261
12.221304059039706
12.221304059034148
12.221304059028592
12.221304059023039
12.221304059017488
12.221304059011942
12.221304059006389
12.221304059000834
12.22130405899529
12.221304058989743
12.221304058984199
12.22130405897865
12.2213040589731
12.221304058967572
12.22130405896203
12.22130405895649
12.221304058950949
12.221304058945408
12.22130405893988
12.221304058934338
12.22130405892881
12.22130405892328
12.22130405891774
12.221304058912212
12.221304058906686
12.221304058901154
12.221304058895631
12.221304058890109
12.221304058884582
12.221304058879056
12.221304058873539
12.221304058868022
12.221304058862506
12.221304058856985
12.221304058851471
12.221304058845956
12.221304058840438
12.221304058834919
12.221304058829407
12.221304058823904
12.221304058818397
12.221304058812883
12.221304058807378
12.221304058801868
12.221304058796367
12.221304058790864
12.22130405878536
12.221304058779866
12.221304058774361
12.22130405876886
12.221304058763362
12.221304058757868
12.221304058752375
12.22130405874688
12.221304058741394
12.221304058735894
12.221304058730404
12.221304058724915
12.221304058719427
12.221304058713946
12.221304058708453
12.221304058702975
12.221304058697484
12.221304058692004
12.22130405868653
12.221304058681048
12.221304058675566
12.22130405867009
12.221304058664614
12.22130405865914
12.22130405865367
12.221304058648196
12.221304058642723
12.221304058637251
12.22130405863178
12.221304058626314
12.22130405862085
12.221304058615377
12.221304058609915
12.221304058604451
12.221304058599
12.22130405859353
12.221304058588075
12.221304058582614
12.221304058577156
12.221304058571702
12.221304058566245
12.2213040585608
12.22130405855534
12.221304058549883
12.221304058544444
12.221304058538998
12.221304058533539
12.221304058528098
12.221304058522659
12.221304058517209
12.22130405851177
12.22130405850633
12.221304058500888
12.221304058495441
12.221304058490007
12.221304058484563
12.221304058479129
12.221304058473699
12.221304058468261
12.221304058462835
12.221304058457399
12.221304058451967
12.221304058446544
12.221304058441115
12.221304058435688
12.221304058430256
12.221304058424838
12.221304058419424
12.221304058413995
12.221304058408576
12.221304058403152
12.221304058397742
12.221304058392324
12.221304058386908
12.221304058381493
12.221304058376075
12.221304058370661
12.22130405836526
12.221304058359847
12.221304058354432
12.221304058349027
12.221304058343625
12.221304058338212
12.221304058332807
12.221304058327414
12.22130405832201
12.221304058316607
12.221304058311208
12.221304058305812
12.22130405830041
12.221304058295019
12.221304058289617
12.22130405828423
12.221304058278841
12.221304058273448
12.221304058268062
12.221304058262662
12.221304058257282
12.221304058251897
12.221304058246506
12.221304058241122
12.22130405823574
12.221304058230363
12.221304058224986
12.221304058219594
12.221304058214223
12.221304058208847
12.221304058203467
12.221304058198092
12.22130405819272
12.221304058187345
12.221304058181975
12.221304058176605
12.221304058171237
12.221304058165869
12.2213040581605
12.221304058155138
12.221304058149771
12.221304058144407
12.221304058139046
12.221304058133684
12.22130405812833
12.221304058122975
12.221304058117616
12.221304058112256
12.221304058106899
12.221304058101554
12.221304058096194
12.221304058090835
12.221304058085488
12.221304058080142
12.221304058074795
12.221304058069453
12.221304058064097
12.221304058058754
12.221304058053413
12.221304058048071
12.221304058042735
12.22130405803739
12.221304058032052
12.221304058026712
12.221304058021378
12.221304058016047
12.221304058010714
12.221304058005375
12.221304058000042
12.221304057994711
12.221304057989382
12.221304057984057
12.221304057978736

12.221304057973404
12.221304057968078
12.22130405796275
12.22130405795744
12.221304057952109
12.221304057946789
12.22130405794147
12.221304057936155
12.221304057930837
12.221304057925519
12.221304057920209
12.221304057914898
12.22130405790958
12.22130405790427
12.22130405789896
12.22130405789365
12.221304057888345
12.22130405788304
12.221304057877733
12.22130405787243
12.221304057867123
12.221304057861822
12.221304057856521
12.221304057851222
12.22130405784592
12.221304057840632
12.22130405783533
12.221304057830041
12.22130405782475
12.22130405781945
12.22130405781416
12.221304057808876
12.221304057803577
12.221304057798298
12.221304057793008
12.221304057787723
12.221304057782435
12.221304057777148
12.221304057771865
12.221304057766583
12.221304057761305
12.221304057756024
12.221304057750753
12.221304057745474
12.221304057740202
12.221304057734928
12.22130405772966
12.221304057724375
12.221304057719111
12.221304057713837
12.221304057708581
12.221304057703303
12.22130405769803
12.221304057692778
12.221304057687504
12.22130405768225
12.221304057676988
12.221304057671725
12.221304057666458
12.22130405766121
12.221304057655955
12.221304057650693
12.221304057645447
12.22130405764019
12.221304057634935
12.221304057629684
12.221304057624428
12.221304057619184
12.221304057613935
12.221304057608688
12.221304057603446
12.2213040575982
12.221304057592954
12.221304057587714
12.221304057582469
12.221304057577234
12.221304057571993
12.22130405756675
12.221304057561518
12.22130405755628
12.221304057551054
12.221304057545812
12.221304057540591
12.221304057535349
12.221304057530121
12.221304057524891
12.22130405751967
12.221304057514443
12.221304057509215
12.22130405750399
12.221304057498775
12.221304057493542
12.221304057488325
12.221304057483103
12.221304057477887
12.221304057472665
12.221304057467446
12.221304057462243
12.221304057457033
12.221304057451807
12.221304057446602
12.221304057441394
12.221304057436184
12.221304057430972
12.221304057425762
12.221304057420559
12.221304057415354
12.221304057410153
12.22130405740495
12.221304057399747
12.221304057394542
12.221304057389347
12.221304057384149
12.22130405737895
12.22130405737376
12.221304057368563
12.221304057363366
12.22130405735818
12.221304057352995
12.2213040573478
12.221304057342607
12.22130405733742
12.22130405733223
12.221304057327044
12.221304057321863
12.221304057316676
12.221304057311496
12.221304057306313
12.221304057301131
12.22130405729596
12.221304057290777
12.221304057285604
12.221304057280424
12.221304057275255
12.221304057270075
12.221304057264906
12.221304057259735
12.221304057254564
12.221304057249396
12.221304057244227
12.221304057239063
12.221304057233896
12.22130405722873
12.221304057223566
12.2213040572184
12.221304057213244
12.221304057208087
12.221304057202925
12.221304057197768
12.221304057192611
12.221304057187455
12.221304057182309
12.22130405717715
12.221304057171997
12.221304057166844
12.22130405716169
12.221304057156551
12.2213040571514
12.221304057146252
12.22130405714111
12.22130405713596
12.221304057130824
12.221304057125678
12.221304057120541
12.221304057115399
12.221304057110252
12.221304057105117
12.221304057099996
12.221304057094851
12.221304057089714
12.221304057084582
12.221304057079449
12.221304057074322
12.221304057069192
12.22130405706406
12.22130405705894
12.22130405705381
12.221304057048687
12.221304057043556
12.22130405703844
12.221304057033317
12.221304057028197
12.221304057023078
12.221304057017953
12.221304057012844
12.221304057007723
12.221304057002614
12.221304056997493
12.221304056992386
12.221304056987272
12.221304056982158
12.221304056977049
12.221304056971935
12.22130405696683
12.221304056961722
12.22130405695662
12.221304056951517
12.22130405694641
12.221304056941314
12.221304056936209
12.221304056931105
12.221304056926018
12.221304056920912
12.221304056915825
12.22130405691072
12.221304056905629
12.221304056900538
12.221304056895445
12.221304056890354
12.221304056885272
12.221304056880177
12.221304056875091
12.221304056869993
12.221304056864918
12.22130405685983
12.221304056854748
12.221304056849666
12.221304056844584
12.221304056839502
12.221304056834427
12.22130405682935
12.22130405682427
12.221304056819193
12.221304056814121
12.221304056809046
12.221304056803973
12.221304056798909
12.221304056793837
12.22130405678877
12.221304056783708
12.22130405677863
12.221304056773572
12.221304056768505
12.221304056763438
12.221304056758376
12.221304056753317
12.221304056748258
12.221304056743193
12.221304056738143
12.221304056733084
12.221304056728023
12.221304056722976
12.221304056717923
12.221304056712864
12.22130405670782
12.221304056702763
12.221304056697717
12.221304056692677
12.221304056687632
12.221304056682577
12.221304056677534
12.221304056672487
12.22130405666745
12.221304056662406
12.22130405665737
12.221304056652324
12.221304056647286
12.221304056642252
12.221304056637216
12.221304056632182
12.221304056627146
12.221304056622108
12.221304056617079
12.221304056612045
12.221304056607025
12.221304056601996
12.221304056596967
12.22130405659194
12.221304056586913
12.221304056581891
12.221304056576864
12.221304056571844
12.221304056566828
12.221304056561806
12.221304056556791
12.221304056551771
12.221304056546751
12.22130405654174
12.221304056536725
12.22130405653171
12.221304056526698
12.22130405652169
12.22130405651668
12.221304056511674
12.221304056506664
12.221304056501653
12.221304056496647
12.22130405649165
12.22130405648664
12.22130405648164
12.221304056476642
12.221304056471643
12.22130405646664
12.221304056461646
12.221304056456647
12.221304056451658
12.22130405644665
12.221304056441667
12.221304056436676
12.221304056431672
12.221304056426687
12.221304056421703
12.221304056416715
12.221304056411721
12.221304056406737
12.221304056401758
12.22130405639677
12.221304056391789
12.221304056386813
12.221304056381825
12.221304056376846
12.221304056371869
12.22130405636689
12.221304056361923
12.221304056356947
12.221304056351968
12.221304056347
12.221304056342024
12.221304056337056
12.22130405633208
12.221304056327115
12.22130405632214
12.221304056317177
12.221304056312215
12.221304056307243
12.221304056302282
12.221304056297333
12.221304056292361
12.221304056287401
12.221304056282444
12.221304056277491
12.221304056272528
12.22130405626757
12.221304056262614
12.221304056257663
12.221304056252706
12.221304056247758
12.22130405624281
12.221304056237864
12.221304056232919
12.221304056227968
12.221304056223026
12.221304056218077
12.221304056213135
12.221304056208186
12.22130405620325
12.221304056198303
12.221304056193365
12.221304056188428
12.221304056183493
12.221304056178557
12.221304056173624
12.221304056168686
12.221304056163751
12.221304056158822
12.221304056153896
12.221304056148966
12.221304056144032
12.221304056139104
12.22130405613418
12.22130405612925
12.221304056124328
12.221304056119404
12.221304056114477
12.221304056109561
12.221304056104636
12.221304056099715
12.221304056094803
12.221304056089883
12.221304056084971
12.221304056080054
12.221304056075136
12.221304056070222
12.22130405606532
12.2213040560604
12.221304056055489
12.221304056050592
12.22130405604568
12.221304056040768
12.22130405603586
12.221304056030965
12.221304056026066
12.22130405602116
12.221304056016256
12.221304056011357
12.221304056006458
12.221304056001557
12.221304055996665
12.221304055991766
12.221304055986872
12.221304055981983
12.221304055977082
12.221304055972192
12.221304055967304
12.221304055962419
12.221304055957527
12.221304055952634
12.221304055947753
12.22130405594287
12.221304055937985
12.221304055933098
12.221304055928217
12.221304055923333
12.221304055918463
12.221304055913581
12.221304055908696
12.221304055903826
12.221304055898946
12.22130405589407
12.221304055889197
12.221304055884332
12.221304055879457
12.221304055874585
12.22130405586972
12.221304055864854
12.221304055859978
12.221304055855109
12.22130405585025
12.221304055845385
12.22130405584053
12.221304055835663
12.2213040558308
12.22130405582594
12.221304055821081
12.221304055816223
12.22130405581137
12.221304055806515
12.22130405580166
12.221304055796805
12.221304055791961
12.221304055787101
12.221304055782248
12.221304055777408
12.221304055772547
12.221304055767705
12.221304055762857
12.221304055758017
12.221304055753176
12.221304055748325
12.221304055743477
12.221304055738646
12.22130405573381
12.221304055728966
12.221304055724127
12.221304055719296
12.221304055714457
12.221304055709625
12.22130405570479
12.221304055699964
12.22130405569513
12.221304055690291
12.221304055685465
12.221304055680642
12.221304055675809
12.221304055670988
12.22130405566616
12.22130405566133
12.22130405565651
12.221304055651693
12.221304055646872
12.221304055642051
12.221304055637232
12.221304055632412
12.221304055627598
12.221304055622783
12.221304055617967
12.221304055613153
12.22130405560834
12.22130405560353
12.22130405559872
12.221304055593906
12.2213040555891
12.221304055584302
12.221304055579488
12.22130405557468
12.221304055569876
12.221304055565076
12.22130405556027
12.22130405555547
12.221304055550675
12.221304055545872
12.221304055541074
12.221304055536281
12.221304055531482
12.221304055526689
12.221304055521895
12.221304055517107
12.22130405551231
12.221304055507513
12.221304055502726
12.221304055497933
12.221304055493153
12.221304055488362
12.221304055483577
12.221304055478804
12.221304055474004
12.221304055469227
12.221304055464444
12.221304055459669
12.221304055454894
12.221304055450105
12.221304055445339
12.221304055440559
12.221304055435779
12.221304055431009
12.221304055426238
12.221304055421463
12.221304055416695
12.221304055411919
12.221304055407156
12.22130405540238
12.221304055397612
12.221304055392858
12.221304055388087
12.221304055383321
12.221304055378559
12.2213040553738
12.221304055369048
12.22130405536428
12.221304055359521
12.221304055354755
12.221304055350009
12.221304055345241
12.221304055340486
12.221304055335745
12.221304055331
12.221304055326241
12.221304055321497
12.221304055316736
12.221304055311988
12.221304055307243
12.221304055302504
12.22130405529775
12.221304055293004
12.221304055288266
12.221304055283527
12.22130405527878
12.221304055274045
12.221304055269306
12.221304055264564
12.221304055259836
12.221304055255091
12.221304055250362
12.221304055245627
12.2213040552409
12.22130405523616
12.221304055231437
12.22130405522671
12.221304055221974
12.221304055217248
12.221304055212519
12.221304055207796
12.22130405520306
12.221304055198344
12.221304055193622
12.221304055188902
12.22130405518418
12.22130405517946
12.221304055174741
12.221304055170021
12.221304055165305
12.221304055160596
12.221304055155878
12.221304055151165
12.22130405514646
12.22130405514174
12.22130405513703
12.22130405513232
12.22130405512761
12.221304055122912
12.221304055118207
12.221304055113501
12.221304055108792
12.221304055104087
12.221304055099385
12.221304055094684
12.221304055089988
12.221304055085286
12.221304055080589
12.221304055075892
12.221304055071194
12.221304055066506
12.221304055061804
12.221304055057113
12.221304055052416
12.221304055047733
12.221304055043044

12.221304055038342
12.22130405503366
12.221304055028972
12.221304055024294
12.221304055019605
12.221304055014917
12.221304055010236
12.221304055005561
12.22130405500088
12.221304054996208
12.221304054991515
12.221304054986842
12.221304054982165
12.22130405497749
12.221304054972814
12.22130405496814
12.221304054963472
12.221304054958802
12.221304054954127
12.221304054949458
12.221304054944783
12.221304054940124
12.221304054935457
12.221304054930792
12.221304054926124
12.221304054921461
12.221304054916803
12.221304054912139
12.22130405490748
12.221304054902815
12.221304054898155
12.221304054893507
12.221304054888845
12.221304054884191
12.221304054879543
12.221304054874887
12.221304054870235
12.221304054865586
12.221304054860926
12.221304054856281
12.221304054851633
12.221304054846982
12.221304054842335
12.221304054837688
12.221304054833046
12.221304054828412
12.221304054823763
12.22130405481912
12.221304054814482
12.221304054809842
12.22130405480521
12.221304054800564
12.221304054795933
12.221304054791297
12.221304054786664
12.221304054782028
12.221304054777397
12.22130405477277
12.221304054768133
12.221304054763506
12.22130405475888
12.221304054754254
12.221304054749632
12.221304054745
12.22130405474038
12.22130405473575
12.221304054731128
12.22130405472651
12.22130405472189
12.221304054717272
12.221304054712654
12.22130405470803
12.221304054703419
12.221304054698802
12.221304054694187
12.221304054689577
12.221304054684968
12.221304054680354
12.221304054675741
12.221304054671135
12.22130405466653
12.221304054661923
12.221304054657313
12.22130405465271
12.221304054648105
12.221304054643506
12.221304054638898
12.221304054634295
12.221304054629702
12.221304054625097
12.221304054620502
12.221304054615901
12.22130405461131
12.221304054606714
12.221304054602122
12.221304054597525
12.221304054592938
12.221304054588337
12.221304054583747
12.221304054579171
12.221304054574574
12.221304054569986
12.221304054565403
12.221304054560814
12.221304054556235
12.221304054551652
12.22130405454707
12.22130405454248
12.221304054537907
12.221304054533327
12.221304054528755
12.22130405452417
12.221304054519601
12.221304054515029
12.221304054510451
12.221304054505874
12.221304054501305
12.221304054496729
12.221304054492164
12.221304054487593
12.221304054483024
12.221304054478457
12.221304054473887
12.221304054469329
12.221304054464762
12.221304054460195
12.221304054455633
12.22130405445107
12.221304054446515
12.221304054441951
12.22130405443739
12.221304054432839
12.221304054428279
12.221304054423722
12.221304054419166
12.221304054414613
12.221304054410059
12.221304054405511
12.22130405440096
12.221304054396414
12.221304054391872
12.221304054387316
12.221304054382768
12.221304054378232
12.221304054373679
12.221304054369137
12.221304054364602
12.221304054360058
12.221304054355516
12.22130405435098
12.221304054346437
12.2213040543419
12.221304054337361
12.221304054332819
12.221304054328286
12.22130405432376
12.221304054319226
12.22130405431469
12.221304054310163
12.221304054305635
12.221304054301104
12.221304054296578
12.22130405429205
12.221304054287517
12.221304054283
12.221304054278471
12.221304054273949
12.221304054269424
12.221304054264909
12.221304054260388
12.22130405425587
12.221304054251357
12.22130405424684
12.221304054242317
12.221304054237804
12.221304054233288
12.221304054228778
12.221304054224268
12.221304054219758
12.221304054215246
12.221304054210739
12.221304054206229
12.221304054201719
12.221304054197214
12.221304054192705
12.221304054188199
12.22130405418371
12.221304054179194
12.221304054174697
12.221304054170197
12.221304054165696
12.221304054161202
12.221304054156702
12.221304054152206
12.221304054147708
12.221304054143214
12.221304054138729
12.22130405413423
12.221304054129737
12.22130405412525
12.221304054120756
12.221304054116272
12.221304054111778
12.2213040541073
12.221304054102808
12.221304054098324
12.221304054093837
12.221304054089359
12.221304054084879
12.221304054080397
12.221304054075919
12.221304054071432
12.221304054066955
12.221304054062482
12.221304054058008
12.221304054053531
12.221304054049051
12.221304054044587
12.221304054040115
12.221304054035647
12.221304054031165
12.221304054026701
12.221304054022234
12.221304054017764
12.221304054013299
12.221304054008838
12.221304054004367
12.2213040539999
12.221304053995441
12.221304053990979
12.221304053986524
12.221304053982063
12.221304053977601
12.221304053973142
12.221304053968684
12.22130405396424
12.221304053959779
12.221304053955325
12.221304053950869
12.221304053946422
12.221304053941966
12.221304053937516
12.221304053933075
12.221304053928622
12.221304053924174
12.22130405391973
12.221304053915294
12.221304053910838
12.2213040539064
12.221304053901955
12.221304053897521
12.221304053893082
12.221304053888632
12.221304053884202
12.221304053879757
12.221304053875324
12.221304053870888
12.221304053866458
12.22130405386202
12.221304053857597
12.221304053853153
12.221304053848728
12.221304053844296
12.22130405383987
12.221304053835437
12.22130405383102
12.221304053826588
12.221304053822161
12.221304053817741
12.22130405381331
12.221304053808899
12.221304053804472
12.221304053800054
12.221304053795633
12.221304053791213
12.221304053786799
12.221304053782383
12.221304053777969
12.221304053773556
12.22130405376914
12.22130405376473
12.221304053760322
12.221304053755908
12.221304053751492
12.221304053747087
12.221304053742683
12.221304053738281
12.221304053733867
12.221304053729465
12.22130405372506
12.221304053720662
12.221304053716256
12.221304053711853
12.221304053707454
12.221304053703061
12.221304053698658
12.221304053694263
12.221304053689867
12.221304053685465
12.221304053681079
12.221304053676683
12.221304053672288
12.221304053667904
12.221304053663513
12.221304053659125
12.22130405365473
12.221304053650346
12.221304053645966
12.221304053641575
12.221304053637189
12.2213040536328
12.221304053628426
12.221304053624038
12.221304053619656
12.221304053615276
12.22130405361089
12.221304053606527
12.221304053602138
12.22130405359777
12.22130405359339
12.22130405358902
12.221304053584655
12.221304053580269
12.221304053575905
12.221304053571536
12.221304053567168
12.22130405356279
12.221304053558436
12.221304053554066
12.221304053549698
12.22130405354533
12.221304053540965
12.221304053536603
12.22130405353224
12.221304053527883
12.221304053523523
12.221304053519159
12.221304053514807
12.22130405351044
12.221304053506085
12.221304053501743
12.221304053497388
12.22130405349303
12.221304053488677
12.22130405348432
12.221304053479976
12.221304053475624
12.221304053471277
12.221304053466934
12.221304053462582
12.221304053458233
12.221304053453883
12.221304053449543
12.221304053445207
12.221304053440862
12.221304053436523
12.22130405343218
12.221304053427842
12.221304053423507
12.221304053419168
12.22130405341483
12.221304053410497
12.22130405340616
12.221304053401823
12.221304053397494
12.22130405339316
12.221304053388828
12.221304053384502
12.221304053380171
12.221304053375851
12.221304053371517
12.221304053367195
12.221304053362863
12.221304053358544
12.221304053354217
12.221304053349895
12.221304053345575
12.221304053341258
12.221304053336935
12.221304053332613
12.221304053328309
12.221304053323985
12.221304053319667
12.221304053315354
12.221304053311039
12.221304053306726
12.22130405330241
12.2213040532981
12.221304053293798
12.221304053289488
12.22130405328517
12.221304053280871
12.221304053276562
12.22130405327226
12.221304053267954
12.221304053263653
12.221304053259352
12.221304053255048
12.221304053250746
12.221304053246442
12.221304053242147
12.221304053237846
12.221304053233547
12.221304053229254
12.221304053224952
12.221304053220662
12.221304053216373
12.221304053212082
12.221304053207788
12.221304053203498
12.221304053199201
12.22130405319492
12.221304053190636
12.221304053186346
12.221304053182061
12.221304053177779
12.221304053173492
12.221304053169206
12.221304053164923
12.221304053160647
12.221304053156365
12.221304053152082
12.221304053147806
12.221304053143534
12.221304053139255
12.221304053134984
12.221304053130702
12.221304053126433
12.221304053122156
12.221304053117887
12.221304053113611
12.221304053109343
12.221304053105074
12.221304053100804
12.221304053096535
12.22130405309227
12.221304053088005
12.22130405308374
12.221304053079484
12.221304053075214
12.22130405307096
12.221304053066694
12.221304053062438
12.221304053058173
12.221304053053917
12.221304053049659
12.221304053045403
12.221304053041152
12.221304053036897
12.22130405303264
12.221304053028383
12.221304053024136
12.221304053019884
12.22130405301564
12.22130405301139
12.221304053007138
12.221304053002891
12.221304052998649
12.2213040529944
12.221304052990163
12.22130405298591
12.221304052981669
12.221304052977436
12.221304052973194
12.221304052968959
12.221304052964715
12.221304052960475
12.221304052956238
12.221304052952005
12.221304052947767
12.221304052943537
12.221304052939299
12.221304052935071
12.221304052930837
12.221304052926607
12.22130405292238
12.221304052918157
12.221304052913926
12.221304052909698
12.221304052905465
12.221304052901246
12.22130405289702
12.221304052892794
12.221304052888575
12.221304052884353
12.221304052880132
12.221304052875917
12.221304052871693
12.221304052867483
12.221304052863267
12.221304052859049
12.221304052854832
12.221304052850616
12.221304052846401
12.221304052842195
12.221304052837981
12.221304052833768
12.221304052829563
12.221304052825358
12.221304052821148
12.221304052816933
12.221304052812735
12.221304052808533
12.221304052804332
12.221304052800114
12.22130405279592
12.221304052791723
12.22130405278752
12.221304052783315
12.221304052779125
12.221304052774922
12.221304052770723
12.221304052766534
12.221304052762338
12.221304052758141
12.22130405275395
12.22130405274976
12.221304052745573
12.221304052741376
12.221304052737185
12.221304052732998
12.22130405272881
12.22130405272463
12.221304052720445
12.221304052716254
12.221304052712073
12.221304052707893
12.221304052703712
12.221304052699534
12.221304052695347
12.221304052691163
12.221304052686989
12.221304052682813
12.221304052678637
12.221304052674464
12.221304052670282
12.221304052666111
12.221304052661948
12.22130405265777
12.221304052653592
12.221304052649424
12.221304052645253
12.22130405264109
12.221304052636924
12.221304052632759
12.221304052628591
12.221304052624422
12.221304052620253
12.22130405261609
12.221304052611933
12.221304052607774
12.221304052603614
12.221304052599457
12.221304052595293
12.221304052591133
12.221304052586984
12.221304052582827
12.221304052578665
12.221304052574524
12.221304052570355
12.221304052566209
12.221304052562058
12.221304052557915
12.221304052553753
12.221304052549613
12.221304052545458
12.221304052541319
12.221304052537175
12.22130405253303
12.221304052528884
12.221304052524745
12.2213040525206
12.22130405251646
12.221304052512318
12.221304052508176
12.221304052504035
12.221304052499894
12.221304052495764
12.221304052491627
12.22130405248749
12.221304052483358
12.221304052479223
12.221304052475087
12.221304052470959
12.22130405246683
12.221304052462694
12.221304052458578
12.221304052454443
12.221304052450318
12.221304052446179
12.221304052442072
12.221304052437944
12.22130405243382
12.221304052429698
12.221304052425575
12.221304052421463
12.221304052417336
12.221304052413222
12.221304052409105
12.221304052404976
12.221304052400859
12.221304052396745
12.221304052392636
12.22130405238852
12.221304052384403
12.221304052380296
12.221304052376187
12.221304052372073
12.221304052367973
12.221304052363854
12.221304052359752
12.221304052355642
12.221304052351536
12.221304052347433
12.221304052343328
12.221304052339224
12.221304052335126
12.221304052331025
12.221304052326925
12.22130405232283
12.221304052318727
12.221304052314627
12.221304052310535
12.221304052306436
12.221304052302347
12.22130405229825

12.22130405229416
12.22130405229006
12.221304052285966
12.221304052281878
12.221304052277794
12.221304052273696
12.221304052269618
12.221304052265529
12.221304052261445
12.22130405225736
12.22130405225327
12.221304052249188
12.221304052245111
12.221304052241022
12.221304052236945
12.221304052232863
12.221304052228788
12.221304052224706
12.221304052220633
12.221304052216562
12.221304052212487
12.221304052208408
12.221304052204339
12.221304052200258
12.221304052196189
12.221304052192117
12.221304052188048
12.221304052183978
12.221304052179905
12.221304052175844
12.22130405217178
12.221304052167715
12.221304052163646
12.221304052159585
12.22130405215552
12.221304052151448
12.221304052147401
12.221304052143338
12.221304052139272
12.221304052135217
12.221304052131162
12.221304052127108
12.221304052123052
12.221304052118994
12.221304052114936
12.221304052110883
12.221304052106833
12.22130405210278
12.22130405209873
12.221304052094677
12.22130405209063
12.22130405208658
12.22130405208254
12.221304052078487
12.221304052074442
12.221304052070401
12.221304052066357
12.221304052062317
12.221304052058274
12.221304052054222
12.221304052050193
12.221304052046152
12.221304052042118
12.221304052038073
12.221304052034041
12.221304052030005
12.221304052025971
12.221304052021937
12.221304052017905
12.221304052013867
12.22130405200984
12.221304052005806
12.221304052001779
12.221304051997748
12.221304051993723
12.221304051989689
12.221304051985674
12.221304051981644
12.221304051977622
12.221304051973599
12.221304051969577
12.22130405196555
12.22130405196153
12.221304051957501
12.221304051953494
12.22130405194946
12.221304051945458
12.221304051941443
12.221304051937425
12.221304051933405
12.221304051929398
12.22130405192538
12.221304051921374
12.221304051917357
12.221304051913352
12.221304051909344
12.221304051905323
12.221304051901319
12.221304051897313
12.221304051893314
12.221304051889303
12.2213040518853
12.221304051881303
12.221304051877292
12.22130405187329
12.221304051869287
12.221304051865289
12.221304051861289
12.221304051857292
12.221304051853302
12.221304051849305
12.2213040518453
12.221304051841308
12.221304051837313
12.221304051833323
12.221304051829334
12.221304051825339
12.221304051821347
12.221304051817361
12.221304051813364
12.221304051809383
12.2213040518054
12.221304051801408
12.221304051797425
12.221304051793437
12.22130405178946
12.221304051785475
12.22130405178149
12.221304051777514
12.221304051773533
12.221304051769561
12.221304051765573
12.221304051761594
12.221304051757624
12.221304051753648
12.221304051749673
12.221304051745689
12.221304051741726
12.221304051737746
12.22130405173378
12.221304051729813
12.221304051725838
12.221304051721866
12.221304051717903
12.221304051713938
12.221304051709971
12.221304051706008
12.221304051702043
12.221304051698075
12.22130405169411
12.221304051690156
12.221304051686191
12.221304051682232
12.22130405167827
12.221304051674315
12.221304051670348
12.221304051666396
12.221304051662447
12.221304051658489
12.221304051654538
12.221304051650582
12.221304051646626
12.22130405164267
12.221304051638732
12.221304051634775
12.221304051630824
12.221304051626872
12.221304051622926
12.221304051618985
12.221304051615043
12.221304051611094
12.221304051607142
12.221304051603205
12.221304051599262
12.22130405159532
12.221304051591385
12.221304051587445
12.221304051583504
12.221304051579567
12.221304051575633
12.221304051571698
12.221304051567762
12.221304051563822
12.221304051559887
12.221304051555954
12.22130405155202
12.221304051548092
12.221304051544163
12.221304051540232
12.221304051536308
12.22130405153238
12.221304051528449
12.221304051524525
12.221304051520606
12.221304051516675
12.221304051512757
12.221304051508834
12.221304051504907
12.221304051500987
12.221304051497064
12.221304051493153
12.221304051489229
12.221304051485317
12.221304051481393
12.221304051477476
12.221304051473568
12.22130405146965
12.22130405146574
12.221304051461829
12.221304051457919
12.221304051454002
12.221304051450094
12.22130405144618
12.22130405144228
12.221304051438365
12.221304051434464
12.221304051430558
12.22130405142665
12.221304051422747
12.221304051418848
12.221304051414942
12.221304051411048
12.221304051407145
12.22130405140324
12.221304051399343
12.221304051395444
12.221304051391543
12.221304051387651
12.221304051383752
12.221304051379857
12.221304051375967
12.221304051372075
12.221304051368184
12.221304051364289
12.221304051360395
12.22130405135651
12.221304051352623
12.221304051348733
12.22130405134485
12.22130405134096
12.221304051337079
12.221304051333188
12.221304051329307
12.22130405132543
12.22130405132155
12.22130405131766
12.221304051313782
12.221304051309904
12.221304051306024
12.221304051302146
12.221304051298272
12.221304051294398
12.221304051290524
12.221304051286648
12.22130405128277
12.221304051278906
12.221304051275027
12.221304051271158
12.221304051267282
12.221304051263415
12.221304051259544
12.22130405125569
12.221304051251812
12.221304051247948
12.221304051244084
12.22130405124021
12.221304051236356
12.221304051232488
12.221304051228632
12.221304051224765
12.221304051220908
12.221304051217055
12.221304051213194
12.221304051209335
12.221304051205475
12.221304051201628
12.221304051197771
12.221304051193915
12.22130405119006
12.221304051186209
12.22130405118236
12.221304051178508
12.221304051174657
12.221304051170806
12.221304051166959
12.221304051163102
12.22130405115927
12.221304051155414
12.221304051151574
12.221304051147731
12.22130405114389
12.221304051140036
12.221304051136205
12.221304051132362
12.221304051128516
12.221304051124676
12.221304051120846
12.221304051117006
12.221304051113163
12.221304051109335
12.221304051105497
12.221304051101663
12.221304051097826
12.22130405109399
12.221304051090176
12.22130405108633
12.221304051082507
12.221304051078675
12.22130405107485
12.22130405107102
12.221304051067193
12.221304051063365
12.22130405105954
12.221304051055712
12.221304051051899
12.22130405104807
12.221304051044251
12.221304051040429
12.2213040510366
12.221304051032787
12.221304051028973
12.221304051025157
12.22130405102134
12.22130405101753
12.221304051013705
12.221304051009888
12.22130405100608
12.221304051002267
12.221304050998457
12.221304050994648
12.221304050990833
12.221304050987024
12.221304050983223
12.221304050979413
12.221304050975608
12.221304050971792
12.221304050967989
12.221304050964184
12.221304050960383
12.221304050956574
12.221304050952778
12.221304050948985
12.221304050945173
12.221304050941374
12.221304050937576
12.22130405093378
12.221304050929982
12.221304050926193
12.221304050922397
12.221304050918597
12.221304050914805
12.22130405091101
12.221304050907214
12.22130405090343
12.22130405089964
12.221304050895846
12.221304050892064
12.221304050888278
12.22130405088449
12.221304050880699
12.221304050876912
12.221304050873128
12.22130405086935
12.22130405086557
12.221304050861784
12.221304050858002
12.221304050854219
12.221304050850442
12.221304050846662
12.221304050842885
12.221304050839109
12.22130405083533
12.221304050831554
12.221304050827785
12.221304050824003
12.22130405082023
12.221304050816459
12.221304050812691
12.221304050808925
12.221304050805148
12.221304050801379
12.221304050797615
12.221304050793847
12.221304050790074
12.221304050786312
12.221304050782548
12.221304050778777
12.221304050775025
12.221304050771254
12.221304050767497
12.221304050763734
12.221304050759974
12.22130405075622
12.22130405075246
12.221304050748703
12.221304050744944
12.221304050741187
12.221304050737439
12.221304050733675
12.221304050729925
12.221304050726175
12.221304050722418
12.221304050718674
12.221304050714922
12.221304050711172
12.221304050707415
12.22130405070367
12.221304050699928
12.221304050696176
12.22130405069243
12.221304050688689
12.221304050684944
12.221304050681196
12.221304050677457
12.221304050673718
12.221304050669977
12.221304050666236
12.221304050662503
12.221304050658771
12.22130405065503
12.221304050651286
12.221304050647557
12.221304050643822
12.221304050640082
12.221304050636355
12.221304050632623
12.221304050628891
12.221304050625164
12.221304050621432
12.2213040506177
12.22130405061397
12.221304050610243
12.221304050606518
12.22130405060279
12.221304050599068
12.221304050595341
12.22130405059162
12.221304050587898
12.221304050584171
12.221304050580446
12.221304050576734
12.221304050573018
12.221304050569293
12.221304050565575
12.221304050561857
12.221304050558143
12.221304050554423
12.22130405055071
12.221304050547001
12.221304050543289
12.22130405053958
12.22130405053586
12.221304050532149
12.22130405052844
12.221304050524736
12.221304050521018
12.221304050517318
12.22130405051361
12.221304050509909
12.221304050506197
12.2213040505025
12.221304050498802
12.22130405049509
12.22130405049139
12.221304050487685
12.221304050483994
12.221304050480288
12.221304050476595
12.221304050472893
12.221304050469195
12.2213040504655
12.221304050461805
12.221304050458098
12.221304050454421
12.221304050450719
12.221304050447042
12.221304050443338
12.221304050439649
12.221304050435963
12.221304050432272
12.221304050428587
12.221304050424896
12.221304050421208
12.221304050417526
12.221304050413838
12.221304050410149
12.22130405040647
12.221304050402791
12.221304050399112
12.221304050395428
12.221304050391744
12.221304050388069
12.221304050384392
12.221304050380716
12.221304050377032
12.221304050373359
12.221304050369685
12.22130405036601
12.221304050362336
12.22130405035867
12.221304050354991
12.221304050351314
12.22130405034765
12.22130405034398
12.221304050340306
12.221304050336647
12.221304050332977
12.221304050329305
12.221304050325639
12.221304050321978
12.221304050318318
12.22130405031465
12.22130405031099
12.221304050307321
12.221304050303662
12.221304050300008
12.221304050296348
12.221304050292684
12.221304050289016
12.221304050285372
12.22130405028172
12.221304050278071
12.221304050274405
12.221304050270755
12.221304050267106
12.221304050263447
12.221304050259796
12.221304050256153
12.221304050252497
12.22130405024885
12.221304050245202
12.221304050241555
12.221304050237906
12.221304050234258
12.22130405023061
12.22130405022697
12.221304050223335
12.22130405021968
12.221304050216046
12.221304050212405
12.221304050208763
12.221304050205127
12.221304050201484
12.221304050197839
12.221304050194206

12.221304050190566
12.221304050186939
12.221304050183303
12.221304050179667
12.221304050176034
12.221304050172394
12.221304050168778
12.221304050165136
12.221304050161514
12.22130405015788
12.221304050154249
12.221304050150621
12.221304050146998
12.221304050143374
12.221304050139741
12.221304050136116
12.221304050132492
12.221304050128866
12.221304050125244
12.221304050121628
12.221304050118006
12.22130405011439
12.221304050110769
12.221304050107149
12.221304050103534
12.221304050099917
12.221304050096304
12.221304050092689
12.221304050089074
12.221304050085461
12.221304050081843
12.22130405007823
12.221304050074624
12.221304050071014
12.221304050067406
12.221304050063802
12.221304050060176
12.221304050056581
12.221304050052975
12.221304050049364
12.221304050045758
12.221304050042153
12.221304050038551
12.22130405003495
12.221304050031344
12.221304050027747
12.221304050024148
12.221304050020553
12.221304050016945
12.221304050013355
12.221304050009756
12.221304050006161
12.22130405000256
12.221304049998965
12.22130404999538
12.221304049991776
12.221304049988188
12.221304049984598
12.221304049981008
12.221304049977412
12.221304049973828
12.221304049970247
12.22130404996665
12.221304049963065
12.221304049959478
12.221304049955895
12.221304049952307
12.22130404994872
12.221304049945147
12.221304049941567
12.22130404993798
12.221304049934393
12.221304049930815
12.221304049927234
12.221304049923658
12.221304049920077
12.221304049916501
12.221304049912929
12.221304049909353
12.221304049905779
12.221304049902207
12.221304049898631
12.221304049895062
12.221304049891481
12.221304049887912
12.221304049884344
12.221304049880777
12.221304049877208
12.221304049873643
12.221304049870072
12.221304049866506
12.221304049862942
12.221304049859372
12.221304049855815
12.22130404985225
12.221304049848687
12.221304049845132
12.22130404984157
12.221304049838011
12.221304049834448
12.221304049830893
12.221304049827337
12.221304049823775
12.221304049820224
12.221304049816668
12.221304049813106
12.221304049809554
12.221304049805996
12.221304049802452
12.221304049798903
12.221304049795355
12.2213040497918
12.221304049788248
12.221304049784699
12.22130404978115
12.221304049777602
12.22130404977406
12.22130404977052
12.221304049766978
12.221304049763432
12.221304049759885
12.221304049756341
12.221304049752808
12.22130404974926
12.221304049745722
12.221304049742184
12.221304049738642
12.221304049735103
12.221304049731575
12.221304049728031
12.2213040497245
12.221304049720965
12.22130404971743
12.221304049713897
12.221304049710367
12.221304049706838
12.221304049703308
12.221304049699771
12.221304049696242
12.221304049692712
12.22130404968919
12.221304049685658
12.221304049682136
12.221304049678615
12.221304049675085
12.221304049671565
12.221304049668037
12.221304049664521
12.221304049660995
12.221304049657475
12.22130404965396
12.221304049650435
12.221304049646918
12.221304049643406
12.221304049639885
12.221304049636371
12.221304049632854
12.221304049629339
12.221304049625823
12.221304049622322
12.221304049618809
12.22130404961529
12.22130404961178
12.221304049608268
12.221304049604756
12.221304049601253
12.22130404959774
12.221304049594238
12.221304049590728
12.221304049587225
12.221304049583724
12.22130404958022
12.221304049576716
12.221304049573215
12.221304049569705
12.221304049566212
12.22130404956271
12.221304049559205
12.221304049555714
12.221304049552218
12.221304049548717
12.221304049545218
12.221304049541725
12.221304049538233
12.221304049534734
12.22130404953124
12.221304049527749
12.221304049524257
12.221304049520764
12.221304049517272
12.221304049513789
12.221304049510305
12.221304049506816
12.221304049503328
12.221304049499839
12.221304049496359
12.22130404949287
12.221304049489387
12.221304049485894
12.221304049482416
12.221304049478931
12.221304049475462
12.221304049471971
12.221304049468497
12.22130404946502
12.221304049461535
12.221304049458055
12.221304049454583
12.221304049451112
12.221304049447637
12.221304049444157
12.221304049440684
12.221304049437217
12.221304049433735
12.221304049430268
12.221304049426795
12.221304049423331
12.22130404941987
12.221304049416386
12.221304049412922
12.22130404940946
12.221304049405989
12.22130404940253
12.221304049399059
12.221304049395592
12.221304049392133
12.221304049388664
12.22130404938521
12.221304049381745
12.221304049378288
12.221304049374824
12.221304049371371
12.22130404936791
12.221304049364461
12.221304049361
12.221304049357547
12.22130404935408
12.221304049350639
12.221304049347182
12.22130404934373
12.221304049340276
12.221304049336824
12.221304049333376
12.221304049329929
12.221304049326477
12.221304049323033
12.221304049319581
12.221304049316137
12.221304049312687
12.221304049309252
12.221304049305804
12.221304049302356
12.22130404929891
12.221304049295473
12.221304049292026
12.2213040492886
12.221304049285143
12.221304049281704
12.221304049278267
12.22130404927484
12.221304049271398
12.221304049267964
12.22130404926453
12.221304049261096
12.221304049257661
12.221304049254227
12.22130404925079
12.22130404924736
12.22130404924393
12.221304049240498
12.221304049237082
12.221304049233652
12.221304049230215
12.22130404922679
12.221304049223368
12.221304049219937
12.221304049216519
12.221304049213082
12.221304049209664
12.22130404920625
12.22130404920282
12.221304049199395
12.221304049195979
12.221304049192552
12.221304049189138
12.221304049185724
12.221304049182297
12.221304049178888
12.221304049175473
12.221304049172057
12.221304049168639
12.22130404916523
12.22130404916181
12.221304049158398
12.221304049154993
12.221304049151577
12.221304049148166
12.221304049144761
12.221304049141347
12.221304049137942
12.221304049134538
12.221304049131133
12.221304049127726
12.221304049124317
12.221304049120919
12.221304049117508
12.221304049114114
12.221304049110712
12.22130404910731
12.221304049103903
12.221304049100501
12.22130404909711
12.22130404909371
12.22130404909031
12.221304049086921
12.221304049083516
12.221304049080128
12.22130404907673
12.221304049073336
12.22130404906994
12.22130404906655
12.221304049063155
12.221304049059766
12.221304049056373
12.221304049052987
12.221304049049598
12.221304049046209
12.221304049042825
12.221304049039436
12.221304049036048
12.221304049032671
12.221304049029285
12.221304049025894
12.22130404902252
12.221304049019135
12.221304049015751
12.22130404901237
12.22130404900899
12.221304049005605
12.221304049002233
12.221304048998858
12.221304048995476
12.221304048992108
12.221304048988726
12.221304048985356
12.221304048981983
12.221304048978613
12.22130404897523
12.22130404897186
12.221304048968483
12.221304048965118
12.22130404896175
12.221304048958388
12.221304048955016
12.221304048951641
12.22130404894828
12.221304048944912
12.221304048941548
12.221304048938189
12.221304048934812
12.221304048931463
12.221304048928097
12.221304048924734
12.221304048921372
12.221304048918014
12.221304048914654
12.221304048911296
12.221304048907932
12.221304048904582
12.221304048901223
12.221304048897869
12.221304048894511
12.221304048891158
12.221304048887802
12.221304048884452
12.221304048881093
12.22130404887775
12.221304048874394
12.22130404887105
12.221304048867703
12.221304048864349
12.22130404886101
12.221304048857657
12.221304048854314
12.22130404885097
12.22130404884762
12.221304048844274
12.221304048840928
12.221304048837586
12.221304048834241
12.22130404883091
12.221304048827562
12.221304048824228
12.221304048820887
12.221304048817547
12.221304048814213
12.221304048810877
12.221304048807534
12.221304048804203
12.221304048800866
12.221304048797544
12.221304048794195
12.22130404879087
12.221304048787532
12.22130404878421
12.22130404878087
12.221304048777544
12.22130404877422
12.221304048770888
12.221304048767557
12.221304048764237
12.22130404876091
12.221304048757583
12.22130404875426
12.221304048750932
12.221304048747612
12.221304048744285
12.22130404874097
12.221304048737649
12.221304048734329
12.221304048731009
12.22130404872768
12.221304048724374
12.221304048721054
12.22130404871774
12.221304048714417
12.22130404871111
12.221304048707783
12.22130404870448
12.221304048701162
12.221304048697847
12.221304048694536
12.221304048691227
12.22130404868792
12.221304048684601
12.221304048681295
12.221304048677995
12.221304048674682
12.221304048671376
12.22130404866807
12.221304048664766
12.221304048661459
12.221304048658153
12.221304048654854
12.221304048651549
12.22130404864826
12.221304048644951
12.221304048641645
12.221304048638356
12.221304048635051
12.221304048631758
12.221304048628456
12.221304048625164
12.221304048621862
12.22130404861857
12.221304048615277
12.221304048611984
12.221304048608689
12.221304048605406
12.221304048602109
12.221304048598812
12.221304048595528
12.221304048592241
12.221304048588944
12.221304048585658
12.221304048582374
12.221304048579086
12.221304048575801
12.221304048572517
12.221304048569229
12.22130404856595
12.221304048562668
12.221304048559384
12.221304048556103
12.221304048552813
12.221304048549543
12.22130404854626
12.221304048542978
12.221304048539706
12.221304048536432
12.221304048533145
12.221304048529873
12.221304048526598
12.221304048523319
12.221304048520047
12.221304048516782
12.221304048513508
12.22130404851023
12.221304048506969
12.221304048503697
12.221304048500429
12.221304048497153
12.221304048493877
12.221304048490621
12.221304048487353
12.221304048484088
12.221304048480818
12.221304048477558
12.22130404847429
12.22130404847103
12.221304048467772
12.221304048464507
12.221304048461242
12.221304048457986
12.221304048454725
12.221304048451469
12.221304048448205
12.221304048444955
12.22130404844169
12.221304048438434
12.221304048435186
12.22130404843193
12.221304048428676
12.221304048425427
12.221304048422168
12.221304048418927
12.221304048415659
12.221304048412408
12.221304048409163
12.221304048405914

12.221304048402668
12.221304048399421
12.221304048396169
12.221304048392925
12.221304048389689
12.221304048386441
12.221304048383194
12.221304048379952
12.221304048376712
12.221304048373465
12.221304048370227
12.221304048366987
12.221304048363745
12.221304048360498
12.221304048357265
12.221304048354028
12.221304048350795
12.221304048347553
12.221304048344319
12.221304048341088
12.221304048337856
12.221304048334613
12.221304048331389
12.221304048328154
12.221304048324917
12.221304048321699
12.22130404831846
12.221304048315238
12.221304048312007
12.221304048308776
12.221304048305553
12.221304048302326
12.221304048299096
12.221304048295867
12.221304048292648
12.22130404828942
12.221304048286202
12.221304048282985
12.22130404827975
12.221304048276535
12.22130404827332
12.221304048270094
12.22130404826688
12.221304048263661
12.221304048260448
12.221304048257224
12.221304048254014
12.221304048250797
12.221304048247584
12.221304048244365
12.221304048241148
12.221304048237936
12.221304048234732
12.221304048231518
12.221304048228301
12.221304048225097
12.22130404822189
12.221304048218679
12.22130404821548
12.221304048212264
12.22130404820906
12.221304048205853
12.221304048202652
12.221304048199455
12.221304048196238
12.22130404819304
12.221304048189834
12.221304048186637
12.221304048183429
12.221304048180242
12.22130404817703
12.221304048173835
12.221304048170635
12.221304048167445
12.221304048164239
12.221304048161059
12.221304048157853
12.221304048154657
12.221304048151469
12.22130404814828
12.221304048145086
12.221304048141896
12.221304048138704
12.221304048135512
12.221304048132325
12.221304048129127
12.221304048125937
12.221304048122759
12.22130404811957
12.221304048116387
12.221304048113197
12.221304048110015
12.221304048106829
12.221304048103645
12.221304048100464
12.221304048097279
12.221304048094096
12.221304048090918
12.221304048087736
12.221304048084551
12.221304048081384
12.221304048078206
12.221304048075023
12.221304048071845
12.221304048068674
12.221304048065502
12.221304048062322
12.221304048059151
12.221304048055975
12.221304048052803
12.221304048049634
12.221304048046461
12.221304048043299
12.221304048040125
12.221304048036963
12.221304048033785
12.221304048030616
12.221304048027458
12.221304048024287
12.221304048021121
12.221304048017956
12.221304048014794
12.221304048011623
12.221304048008461
12.221304048005301
12.22130404800214
12.22130404799898
12.221304047995826
12.221304047992659
12.221304047989499
12.221304047986356
12.221304047983187
12.221304047980034
12.221304047976874
12.22130404797372
12.221304047970573
12.221304047967415
12.221304047964265
12.221304047961107
12.221304047957961
12.221304047954803
12.221304047951651
12.221304047948507
12.221304047945361
12.221304047942203
12.221304047939062
12.221304047935913
12.221304047932767
12.221304047929618
12.221304047926475
12.221304047923331
12.221304047920196
12.22130404791705
12.221304047913911
12.221304047910763
12.221304047907617
12.221304047904479
12.221304047901349
12.221304047898206
12.221304047895064
12.221304047891929
12.221304047888795
12.221304047885662
12.22130404788252
12.221304047879386
12.221304047876254
12.221304047873124
12.22130404786999
12.221304047866859
12.22130404786372
12.221304047860588
12.221304047857458
12.221304047854336
12.221304047851206
12.221304047848085
12.221304047844953
12.22130404784183
12.221304047838698
12.221304047835574
12.221304047832447
12.221304047829326
12.221304047826202
12.22130404782308
12.221304047819958
12.221304047816842
12.221304047813716
12.221304047810598
12.221304047807482
12.22130404780436
12.22130404780124
12.221304047798125
12.221304047795007
12.221304047791897
12.221304047788777
12.22130404778566
12.221304047782548
12.221304047779437
12.221304047776325
12.221304047773216
12.22130404777011
12.221304047766996
12.221304047763885
12.22130404776078
12.221304047757672
12.22130404775456
12.221304047751453
12.221304047748342
12.221304047745235
12.221304047742134
12.221304047739034
12.221304047735929
12.221304047732824
12.221304047729726
12.221304047726628
12.221304047723514
12.221304047720421
12.221304047717322
12.221304047714225
12.221304047711122
12.22130404770803
12.221304047704926
12.221304047701832
12.221304047698741
12.221304047695645
12.221304047692552
12.221304047689452
12.221304047686369
12.221304047683267
12.221304047680185
12.221304047677082
12.221304047674
12.221304047670907
12.221304047667816
12.221304047664733
12.221304047661649
12.221304047658563
12.221304047655476
12.221304047652389
12.221304047649296
12.221304047646216
12.221304047643137
12.221304047640045
12.22130404763697
12.221304047633888
12.221304047630811
12.221304047627724
12.221304047624649
12.221304047621578
12.221304047618489
12.221304047615419
12.221304047612339
12.22130404760926
12.221304047606187
12.221304047603121
12.221304047600043
12.221304047596963
12.221304047593895
12.221304047590818
12.221304047587745
12.221304047584685
12.221304047581611
12.221304047578538
12.221304047575476
12.221304047572408
12.221304047569337
12.221304047566274
12.221304047563194
12.221304047560146
12.221304047557073
12.22130404755401
12.221304047550948
12.221304047547887
12.221304047544825
12.221304047541764
12.2213040475387
12.221304047535645
12.221304047532575
12.221304047529523
12.221304047526461
12.221304047523404
12.221304047520357
12.221304047517293
12.221304047514232
12.22130404751118
12.221304047508125
12.221304047505079
12.221304047502025
12.221304047498972
12.221304047495918
12.22130404749287
12.221304047489815
12.221304047486763
12.221304047483722
12.221304047480677
12.221304047477625
12.221304047474577
12.22130404747153
12.221304047468491
12.221304047465441
12.221304047462404
12.221304047459352
12.221304047456318
12.221304047453273
12.221304047450227
12.221304047447186
12.221304047444146
12.221304047441109
12.221304047438071
12.22130404743503
12.221304047431994
12.221304047428955
12.221304047425917
12.221304047422883
12.221304047419855
12.221304047416819
12.221304047413781
12.221304047410753
12.221304047407722
12.221304047404681
12.221304047401652
12.22130404739862
12.221304047395602
12.221304047392566
12.221304047389538
12.22130404738651
12.221304047383489
12.221304047380459
12.221304047377437
12.221304047374412
12.221304047371387
12.22130404736836
12.221304047365344
12.221304047362317
12.221304047359293
12.221304047356272
12.22130404735325
12.221304047350236
12.221304047347216
12.221304047344185
12.221304047341176
12.221304047338151
12.221304047335137
12.221304047332126
12.22130404732911
12.221304047326099
12.221304047323077
12.221304047320073
12.22130404731705
12.22130404731405
12.221304047311033
12.221304047308019
12.221304047305013
12.221304047301999
12.221304047298995
12.221304047295984
12.22130404729298
12.221304047289976
12.221304047286964
12.221304047283963
12.221304047280956
12.22130404727795
12.221304047274947
12.221304047271943
12.221304047268946
12.221304047265946
12.221304047262942
12.221304047259938
12.221304047256945
12.221304047253941
12.221304047250946
12.221304047247942
12.22130404724495
12.221304047241956
12.221304047238958
12.221304047235963
12.22130404723297
12.221304047229976
12.221304047226978
12.221304047223994
12.221304047221
12.22130404721801
12.221304047215016
12.221304047212023
12.22130404720904
12.221304047206054
12.221304047203057
12.221304047200075
12.221304047197084
12.221304047194108
12.221304047191117
12.221304047188127
12.221304047185143
12.22130404718217
12.221304047179189
12.221304047176211
12.221304047173215
12.221304047170241
12.22130404716726
12.221304047164278
12.221304047161308
12.221304047158327
12.221304047155343
12.221304047152367
12.221304047149394
12.221304047146415
12.221304047143441
12.221304047140464
12.221304047137496
12.221304047134527
12.221304047131548
12.221304047128575
12.221304047125612
12.221304047122642
12.221304047119666
12.221304047116696
12.221304047113726
12.221304047110767
12.221304047107795
12.221304047104825
12.221304047101865
12.221304047098895
12.221304047095936
12.221304047092971
12.221304047090008
12.221304047087044
12.221304047084075
12.221304047081118
12.221304047078162
12.221304047075204
12.221304047072241
12.221304047069276
12.221304047066324
12.221304047063363
12.22130404706041
12.22130404705745
12.221304047054495
12.22130404705154
12.22130404704859
12.221304047045638
12.221304047042684
12.22130404703973
12.22130404703677
12.221304047033833
12.221304047030879
12.22130404702792
12.221304047024974
12.221304047022027
12.221304047019078
12.22130404701613
12.221304047013186
12.221304047010243
12.22130404700729
12.221304047004354
12.221304047001405
12.221304046998464
12.22130404699552
12.22130404699258
12.221304046989639
12.221304046986694
12.221304046983754
12.221304046980812
12.221304046977878
12.221304046974938
12.221304046972
12.221304046969065
12.221304046966125
12.221304046963192
12.221304046960261
12.221304046957322
12.221304046954385
12.221304046951458
12.221304046948521
12.221304046945592
12.221304046942663
12.221304046939727
12.2213040469368
12.22130404693387
12.221304046930943
12.221304046928015
12.221304046925088

12.221304046922162
12.221304046919235
12.221304046916304
12.221304046913383
12.22130404691046
12.221304046907541
12.221304046904613
12.221304046901693
12.22130404689877
12.22130404689585
12.221304046892927
12.221304046890008
12.221304046887083
12.22130404688417
12.22130404688125
12.221304046878334
12.221304046875419
12.221304046872508
12.221304046869587
12.221304046866672
12.221304046863757
12.221304046860842
12.221304046857927
12.221304046855016
12.221304046852111
12.221304046849198
12.221304046846287
12.221304046843379
12.221304046840462
12.221304046837558
12.221304046834643
12.221304046831746
12.221304046828836
12.22130404682593
12.221304046823027
12.221304046820123
12.221304046817215
12.22130404681431
12.221304046811406
12.221304046808504
12.221304046805605
12.22130404680271
12.221304046799812
12.221304046796908
12.221304046794014
12.2213040467911
12.221304046788212
12.22130404678532
12.221304046782414
12.221304046779519
12.221304046776627
12.221304046773731
12.221304046770843
12.221304046767946
12.221304046765049
12.221304046762159
12.221304046759267
12.22130404675638
12.221304046753492
12.221304046750593
12.221304046747704
12.221304046744821
12.221304046741935
12.221304046739052
12.22130404673616
12.221304046733275
12.221304046730388
12.221304046727502
12.221304046724624
12.221304046721736
12.221304046718858
12.221304046715979
12.221304046713092
12.221304046710207
12.22130404670733
12.221304046704448
12.221304046701576
12.221304046698688
12.221304046695819
12.221304046692937
12.221304046690065
12.221304046687182
12.221304046684313
12.221304046681437
12.221304046678558
12.221304046675693
12.221304046672815
12.221304046669946
12.22130404666707
12.221304046664198
12.221304046661333
12.22130404665846
12.221304046655586
12.221304046652728
12.221304046649859
12.22130404664699
12.22130404664412
12.221304046641256
12.221304046638389
12.221304046635526
12.221304046632667
12.221304046629806
12.22130404662694
12.221304046624073
12.221304046621214
12.22130404661836
12.221304046615492
12.221304046612632
12.221304046609774
12.221304046606914
12.221304046604057
12.221304046601194
12.22130404659835
12.221304046595495
12.221304046592632
12.221304046589779
12.221304046586923
12.221304046584072
12.221304046581219
12.221304046578364
12.221304046575511
12.221304046572662
12.22130404656981
12.221304046566964
12.22130404656411
12.221304046561263
12.22130404655842
12.221304046555568
12.221304046552723
12.221304046549882
12.221304046547036
12.221304046544185
12.22130404654135
12.221304046538508
12.221304046535659
12.221304046532818
12.221304046529973
12.221304046527143
12.221304046524294
12.221304046521457
12.221304046518611
12.221304046515769
12.221304046512936
12.221304046510104
12.22130404650726
12.221304046504427
12.22130404650159
12.221304046498757
12.221304046495918
12.221304046493088
12.221304046490248
12.221304046487417
12.221304046484589
12.221304046481755
12.221304046478929
12.221304046476105
12.221304046473273
12.221304046470442
12.221304046467617
12.22130404646479
12.22130404646196
12.221304046459132
12.221304046456305
12.22130404645348
12.221304046450648
12.22130404644783
12.221304046445011
12.22130404644219
12.221304046439363
12.221304046436542
12.221304046433717
12.221304046430905
12.221304046428083
12.221304046425256
12.221304046422441
12.221304046419627
12.221304046416812
12.221304046413994
12.221304046411174
12.221304046408365
12.221304046405548
12.221304046402738
12.221304046399924
12.221304046397107
12.221304046394295
12.221304046391483
12.22130404638867
12.221304046385862
12.221304046383052
12.221304046380242
12.22130404637744
12.221304046374632
12.221304046371822
12.221304046369019
12.221304046366212
12.221304046363402
12.221304046360592
12.221304046357798
12.221304046354987
12.22130404635219
12.221304046349383
12.22130404634658
12.221304046343786
12.221304046340979
12.221304046338183
12.22130404633538
12.221304046332579
12.221304046329779
12.221304046326988
12.22130404632419
12.2213040463214
12.221304046318597
12.221304046315804
12.221304046313007
12.221304046310218
12.221304046307429
12.221304046304631
12.221304046301832
12.221304046299041
12.221304046296254
12.221304046293461
12.221304046290678
12.221304046287882
12.221304046285098
12.221304046282304
12.221304046279522
12.221304046276734
12.221304046273948
12.221304046271165
12.22130404626838
12.221304046265589
12.221304046262802
12.221304046260022
12.221304046257245
12.221304046254453
12.221304046251676
12.221304046248894
12.22130404624612
12.221304046243336
12.221304046240563
12.221304046237787
12.221304046235007
12.221304046232229
12.22130404622945
12.221304046226669
12.221304046223898
12.221304046221125
12.221304046218346
12.221304046215577
12.221304046212806
12.221304046210026
12.22130404620726
12.221304046204493
12.221304046201727
12.221304046198947
12.221304046196181
12.221304046193415
12.221304046190646
12.221304046187882
12.221304046185116
12.221304046182345
12.221304046179581
12.221304046176813
12.221304046174053
12.221304046171289
12.221304046168518
12.221304046165757
12.221304046162999
12.221304046160238
12.221304046157478
12.221304046154723
12.221304046151957
12.22130404614919
12.221304046146441
12.221304046143686
12.221304046140926
12.22130404613817
12.221304046135414
12.221304046132653
12.221304046129902
12.221304046127143
12.221304046124391
12.221304046121638
12.221304046118883
12.221304046116135
12.221304046113383
12.22130404611064
12.22130404610789
12.221304046105137
12.22130404610238
12.22130404609963
12.22130404609689
12.221304046094136
12.221304046091397
12.22130404608865
12.221304046085908
12.221304046083164
12.221304046080421
12.221304046077673
12.221304046074927
12.221304046072198
12.221304046069438
12.221304046066708
12.221304046063958
12.22130404606122
12.221304046058487
12.22130404605575
12.221304046053007
12.221304046050271
12.221304046047537
12.221304046044798
12.22130404604206
12.221304046039327
12.221304046036593
12.221304046033863
12.221304046031127
12.221304046028395
12.221304046025654
12.221304046022924
12.221304046020196
12.22130404601747
12.221304046014737
12.221304046012014
12.221304046009276
12.22130404600655
12.221304046003821
12.221304046001098
12.221304045998366
12.22130404599565
12.221304045992916
12.221304045990196
12.221304045987475
12.221304045984745
12.221304045982029
12.221304045979302
12.221304045976584
12.221304045973863
12.221304045971142
12.221304045968413
12.221304045965699
12.221304045962983
12.221304045960258
12.221304045957542
12.22130404595483
12.221304045952115
12.221304045949399
12.221304045946688
12.221304045943976
12.22130404594125
12.221304045938542
12.221304045935826
12.221304045933119
12.221304045930411
12.2213040459277
12.221304045924981
12.221304045922274
12.221304045919567
12.221304045916858
12.221304045914149
12.221304045911445
12.221304045908736
12.221304045906027
12.221304045903327
12.22130404590062
12.221304045897913
12.221304045895213
12.221304045892508
12.221304045889806
12.2213040458871
12.221304045884398
12.221304045881697
12.221304045879002
12.221304045876296
12.221304045873593
12.221304045870898
12.22130404586821
12.221304045865512
12.221304045862812
12.221304045860116
12.22130404585742
12.221304045854723
12.221304045852015
12.221304045849337
12.221304045846642
12.221304045843945
12.221304045841253
12.221304045838563
12.221304045835874
12.221304045833177
12.22130404583049
12.221304045827804
12.221304045825113
12.221304045822427
12.221304045819739
12.221304045817051
12.221304045814362
12.221304045811683
12.221304045809001
12.221304045806317
12.22130404580363
12.22130404580094
12.221304045798261
12.221304045795574
12.221304045792898
12.22130404579021
12.221304045787532
12.221304045784859
12.221304045782166
12.221304045779497
12.22130404577682
12.221304045774138
12.221304045771467
12.221304045768788
12.22130404576611
12.221304045763434
12.221304045760764
12.221304045758092
12.221304045755408
12.221304045752742
12.221304045750069
12.221304045747397
12.221304045744727
12.221304045742054
12.221304045739386
12.221304045736712
12.22130404573405
12.221304045731376
12.221304045728708
12.221304045726047
12.221304045723375
12.221304045720709
12.221304045718043
12.221304045715382
12.22130404571272
12.221304045710049
12.221304045707397
12.22130404570472
12.221304045702063
12.221304045699403
12.221304045696744
12.221304045694083
12.221304045691424
12.221304045688763
12.2213040456861
12.221304045683453
12.22130404568079
12.221304045678135
12.221304045675483
12.221304045672822
12.221304045670166
12.22130404566751
12.221304045664862
12.221304045662208
12.221304045659554
12.221304045656902
12.221304045654248
12.221304045651596
12.221304045648944
12.221304045646301
12.22130404564365
12.221304045640995
12.221304045638353
12.221304045635708
12.221304045633063
12.221304045630408
12.221304045627761
12.221304045625121
12.221304045622473
12.221304045619835
12.22130404561719
12.221304045614543
12.221304045611905
12.221304045609255
12.221304045606617
12.221304045603976
12.221304045601341
12.221304045598703
12.221304045596058
12.221304045593424
12.221304045590783
12.221304045588152
12.221304045585512
12.221304045582885
12.221304045580235
12.2213040455776
12.22130404557497
12.221304045572328
12.22130404556971
12.221304045567074
12.221304045564436
12.221304045561807
12.22130404555917
12.221304045556538
12.221304045553916
12.221304045551287
12.221304045548662
12.221304045546027
12.2213040455434
12.221304045540778
12.221304045538144
12.221304045535526
12.2213040455329
12.221304045530271
12.221304045527653
12.221304045525025
12.221304045522405
12.221304045519778
12.221304045517158
12.22130404551453
12.221304045511912
12.2213040455093
12.221304045506683
12.221304045504057
12.221304045501444
12.221304045498822
12.221304045496206

12.221304045493586
12.221304045490966
12.221304045488358
12.221304045485736
12.221304045483132
12.221304045480512
12.221304045477911
12.221304045475293
12.221304045472676
12.221304045470076
12.22130404546746
12.221304045464843
12.22130404546223
12.221304045459622
12.221304045457014
12.221304045454398
12.221304045451799
12.221304045449198
12.221304045446576
12.221304045443981
12.221304045441379
12.221304045438771
12.221304045436163
12.221304045433557
12.221304045430955
12.221304045428358
12.221304045425752
12.221304045423153
12.221304045420554
12.221304045417948
12.221304045415351
12.221304045412749
12.22130404541015
12.221304045407546
12.221304045404958
12.22130404540236
12.221304045399762
12.221304045397165
12.221304045394572
12.22130404539197
12.22130404538939
12.221304045386795
12.221304045384201
12.221304045381606
12.22130404537901
12.221304045376433
12.221304045373834
12.221304045371241
12.22130404536865
12.221304045366063
12.221304045363471
12.221304045360894
12.221304045358304
12.22130404535572
12.22130404535313
12.221304045350545
12.22130404534796
12.221304045345372
12.221304045342794
12.221304045340204
12.221304045337614
12.22130404533504
12.221304045332456
12.221304045329871
12.221304045327292
12.221304045324713
12.22130404532214
12.221304045319563
12.221304045316977
12.221304045314405
12.221304045311829
12.22130404530925
12.221304045306674
12.221304045304104
12.22130404530153
12.221304045298943
12.221304045296375
12.221304045293804
12.221304045291228
12.221304045288656
12.221304045286079
12.221304045283512
12.221304045280943
12.221304045278375
12.221304045275797
12.221304045273236
12.221304045270664
12.221304045268095
12.22130404526553
12.221304045262965
12.2213040452604
12.221304045257835
12.221304045255268
12.221304045252705
12.221304045250136
12.221304045247571
12.22130404524501
12.22130404524245
12.221304045239888
12.221304045237328
12.22130404523477
12.221304045232207
12.221304045229648
12.22130404522709
12.221304045224533
12.22130404522197
12.221304045219412
12.221304045216863
12.221304045214296
12.221304045211749
12.221304045209193
12.221304045206644
12.221304045204093
12.221304045201531
12.221304045198975
12.221304045196426
12.221304045193879
12.221304045191323
12.221304045188779
12.221304045186217
12.221304045183668
12.221304045181125
12.221304045178574
12.221304045176025
12.22130404517348
12.221304045170935
12.22130404516839
12.221304045165844
12.221304045163302
12.221304045160759
12.221304045158208
12.22130404515567
12.221304045153126
12.221304045150589
12.221304045148045
12.221304045145502
12.221304045142956
12.221304045140416
12.221304045137877
12.221304045135344
12.221304045132797
12.221304045130271
12.221304045127726
12.221304045125189
12.221304045122658
12.221304045120117
12.221304045117588
12.221304045115058
12.22130404511252
12.221304045109983
12.221304045107448
12.221304045104912
12.221304045102384
12.221304045099846
12.221304045097323
12.22130404509479
12.221304045092262
12.22130404508974
12.221304045087205
12.221304045084672
12.221304045082151
12.221304045079625
12.22130404507709
12.221304045074575
12.22130404507205
12.221304045069521
12.221304045066997
12.221304045064473
12.221304045061949
12.221304045059425
12.221304045056913
12.221304045054389
12.22130404505186
12.221304045049344
12.221304045046823
12.221304045044302
12.221304045041789
12.22130404503927
12.221304045036753
12.221304045034236
12.221304045031715
12.221304045029209
12.221304045026697
12.221304045024176
12.221304045021663
12.221304045019146
12.221304045016632
12.22130404501412
12.221304045011607
12.221304045009099
12.221304045006587
12.221304045004073
12.221304045001565
12.22130404499906
12.22130404499654
12.221304044994037
12.221304044991527
12.221304044989024
12.22130404498652
12.221304044984016
12.221304044981505
12.221304044978998
12.221304044976504
12.221304044973994
12.221304044971482
12.221304044968983
12.221304044966486
12.221304044963981
12.221304044961476
12.221304044958984
12.22130404495648
12.221304044953982
12.221304044951475
12.221304044948987
12.221304044946482
12.221304044943986
12.221304044941489
12.221304044938988
12.221304044936504
12.221304044934007
12.221304044931511
12.22130404492902
12.221304044926526
12.221304044924036
12.22130404492153
12.221304044919048
12.221304044916558
12.221304044914064
12.221304044911575
12.221304044909083
12.221304044906594
12.221304044904109
12.221304044901618
12.221304044899124
12.22130404489664
12.221304044894156
12.221304044891667
12.221304044889184
12.2213040448867
12.221304044884215
12.221304044881729
12.221304044879247
12.221304044876758
12.221304044874278
12.221304044871806
12.221304044869317
12.221304044866839
12.221304044864361
12.221304044861876
12.221304044859403
12.221304044856923
12.221304044854442
12.22130404485197
12.221304044849482
12.221304044847011
12.221304044844537
12.22130404484207
12.221304044839593
12.22130404483711
12.221304044834636
12.221304044832165
12.221304044829692
12.221304044827225
12.221304044824743
12.22130404482228
12.221304044819801
12.221304044817334
12.221304044814874
12.221304044812396
12.221304044809937
12.22130404480746
12.221304044805
12.22130404480253
12.221304044800071
12.221304044797607
12.221304044795135
12.221304044792667
12.221304044790203
12.221304044787749
12.221304044785278
12.221304044782812
12.221304044780352
12.221304044777888
12.221304044775437
12.221304044772978
12.221304044770509
12.221304044768054
12.221304044765603
12.221304044763137
12.221304044760673
12.22130404475822
12.221304044755762
12.221304044753309
12.221304044750852
12.221304044748399
12.221304044745942
12.221304044743489
12.221304044741037
12.221304044738586
12.221304044736133
12.221304044733682
12.221304044731232
12.221304044728786
12.221304044726331
12.221304044723881
12.221304044721432
12.22130404471898
12.221304044716542
12.221304044714088
12.22130404471164
12.22130404470919
12.221304044706741
12.221304044704302
12.221304044701863
12.221304044699414
12.221304044696968
12.221304044694524
12.221304044692085
12.221304044689644
12.221304044687205
12.221304044684757
12.221304044682316
12.221304044679883
12.221304044677437
12.221304044675001
12.221304044672562
12.221304044670122
12.221304044667685
12.221304044665251
12.221304044662821
12.221304044660382
12.221304044657938
12.221304044655506
12.221304044653069
12.221304044650646
12.221304044648203
12.221304044645773
12.221304044643343
12.221304044640906
12.221304044638476
12.221304044636053
12.221304044633612
12.221304044631188
12.221304044628754
12.221304044626335
12.221304044623903
12.221304044621474
12.221304044619048
12.221304044616623
12.221304044614204
12.221304044611772
12.221304044609349
12.221304044606928
12.221304044604501
12.221304044602075
12.221304044599652
12.221304044597227
12.221304044594802
12.221304044592394
12.22130404458997
12.221304044587544
12.221304044585127
12.221304044582707
12.22130404458029
12.22130404457788
12.221304044575456
12.22130404457304
12.221304044570633
12.221304044568214
12.22130404456579
12.22130404456338
12.221304044560968
12.22130404455855
12.221304044556135
12.221304044553722
12.221304044551319
12.221304044548896
12.221304044546493
12.221304044544082
12.221304044541672
12.221304044539263
12.221304044536849
12.221304044534433
12.221304044532033
12.221304044529624
12.221304044527214
12.221304044524816
12.22130404452241
12.22130404452
12.221304044517602
12.221304044515186
12.22130404451279
12.221304044510386
12.22130404450798
12.221304044505583
12.22130404450318
12.221304044500775
12.221304044498382
12.221304044495978
12.221304044493573
12.221304044491175
12.221304044488777
12.221304044486384
12.221304044483992
12.221304044481583
12.221304044479187
12.221304044476799
12.221304044474396
12.221304044472008
12.221304044469617
12.221304044467228
12.221304044464823
12.221304044462434
12.221304044460046
12.221304044457652
12.221304044455255
12.221304044452864
12.221304044450472
12.221304044448079
12.22130404444569
12.22130404444331
12.22130404444092
12.22130404443853
12.221304044436145
12.221304044433753
12.221304044431365
12.22130404442899
12.221304044426603
12.221304044424222
12.221304044421833
12.221304044419444
12.221304044417067
12.221304044414678
12.221304044412305
12.22130404440992
12.221304044407542
12.221304044405164
12.22130404440278
12.221304044400394
12.221304044398027
12.22130404439565
12.221304044393262
12.221304044390891
12.22130404438851
12.221304044386136
12.221304044383764
12.22130404438138
12.221304044379002
12.221304044376634
12.221304044374264
12.221304044371887
12.22130404436952
12.221304044367145
12.221304044364775
12.221304044362402
12.221304044360027
12.221304044357655
12.221304044355282
12.221304044352925
12.221304044350552
12.22130404434818
12.221304044345814
12.221304044343453
12.221304044341085
12.221304044338718
12.221304044336353
12.221304044333994
12.221304044331623
12.221304044329255
12.221304044326898
12.221304044324537
12.22130404432217
12.221304044319806
12.221304044317456
12.22130404431508
12.22130404431273
12.22130404431037
12.221304044308008
12.221304044305647
12.221304044303293
12.221304044300934
12.221304044298574
12.221304044296216
12.221304044293857
12.221304044291506
12.22130404428915
12.221304044286793
12.221304044284436
12.221304044282084
12.221304044279737
12.22130404427738
12.221304044275032
12.221304044272681
12.221304044270333
12.22130404426798
12.221304044265626
12.22130404426328
12.221304044260933
12.221304044258586
12.221304044256232
12.221304044253882
12.221304044251534
12.221304044249187
12.221304044246848
12.221304044244501
12.22130404424216
12.221304044239814
12.221304044237465
12.221304044235124
12.22130404423278
12.221304044230449
12.221304044228102
12.221304044225754
12.22130404422341
12.221304044221073
12.221304044218728
12.221304044216394
12.221304044214056
12.221304044211715
12.221304044209377
12.221304044207049
12.2213040442047
12.221304044202363
12.221304044200032
12.221304044197694
12.221304044195367
12.221304044193024
12.221304044190699
12.221304044188356
12.221304044186027
12.221304044183697
12.221304044181364
12.221304044179032
12.221304044176701
12.221304044174367
12.221304044172038
12.22130404416971
12.221304044167386
12.221304044165054
12.221304044162727
12.2213040441604
12.221304044158076
12.221304044155742
12.22130404415342
12.2213040441511
12.221304044148772
12.221304044146452
12.221304044144123
12.2213040441418
12.22130404413948
12.221304044137161
12.22130404413483
12.221304044132516
12.221304044130191
12.221304044127868

12.221304044125556
12.221304044123231
12.221304044120917
12.22130404411859
12.221304044116275
12.221304044113959
12.221304044111646
12.221304044109324
12.221304044107006
12.221304044104695
12.221304044102384
12.221304044100068
12.221304044097753
12.22130404409544
12.221304044093134
12.22130404409082
12.221304044088509
12.221304044086189
12.22130404408388
12.221304044081569
12.221304044079261
12.221304044076959
12.221304044074646
12.221304044072335
12.221304044070026
12.221304044067718
12.221304044065413
12.221304044063116
12.221304044060807
12.2213040440585
12.221304044056195
12.221304044053891
12.221304044051593
12.221304044049282
12.221304044046983
12.221304044044677
12.221304044042379
12.221304044040076
12.221304044037778
12.221304044035481
12.221304044033168
12.221304044030878
12.221304044028583
12.221304044026274
12.221304044023977
12.221304044021688
12.221304044019398
12.221304044017092
12.221304044014799
12.221304044012504
12.221304044010205
12.22130404400791
12.221304044005613
12.221304044003322
12.221304044001029
12.22130404399874
12.221304043996446
12.221304043994156
12.221304043991871
12.221304043989575
12.221304043987294
12.221304043984999
12.221304043982718
12.221304043980425
12.221304043978138
12.221304043975845
12.22130404397356
12.221304043971275
12.221304043968985
12.221304043966702
12.221304043964416
12.221304043962133
12.221304043959849
12.221304043957561
12.221304043955282
12.221304043952996
12.22130404395072
12.221304043948443
12.221304043946159
12.22130404394388
12.221304043941595
12.221304043939321
12.221304043937039
12.221304043934758
12.221304043932477
12.221304043930205
12.221304043927926
12.221304043925645
12.221304043923377
12.221304043921103
12.22130404391883
12.22130404391655
12.221304043914282
12.221304043912008
12.221304043909736
12.221304043907466
12.22130404390519
12.22130404390292
12.221304043900648
12.221304043898376
12.221304043896106
12.221304043893833
12.221304043891564
12.221304043889301
12.221304043887038
12.221304043884762
12.221304043882498
12.221304043880235
12.221304043877966
12.221304043875698
12.221304043873435
12.22130404387117
12.221304043868908
12.221304043866638
12.221304043864384
12.221304043862117
12.221304043859858
12.22130404385759
12.221304043855339
12.221304043853074
12.22130404385082
12.22130404384855
12.221304043846294
12.221304043844032
12.221304043841778
12.221304043839524
12.221304043837263
12.221304043835012
12.22130404383275
12.221304043830495
12.221304043828237
12.221304043825993
12.221304043823734
12.221304043821474
12.221304043819222
12.221304043816977
12.22130404381472
12.221304043812468
12.221304043810216
12.221304043807967
12.221304043805716
12.221304043803467
12.221304043801217
12.221304043798966
12.221304043796717
12.22130404379447
12.22130404379223
12.221304043789976
12.221304043787724
12.221304043785484
12.221304043783237
12.221304043780997
12.221304043778751
12.221304043776508
12.221304043774257
12.221304043772017
12.221304043769775
12.221304043767534
12.221304043765292
12.221304043763057
12.221304043760808
12.221304043758572
12.221304043756337
12.221304043754087
12.221304043751857
12.221304043749617
12.221304043747383
12.221304043745148
12.221304043742903
12.221304043740671
12.221304043738433
12.221304043736204
12.221304043733971
12.221304043731728
12.221304043729491
12.22130404372726
12.22130404372503
12.221304043722794
12.22130404372057
12.22130404371834
12.221304043716104
12.221304043713875
12.221304043711648
12.221304043709411
12.221304043707189
12.221304043704958
12.22130404370273
12.221304043700501
12.22130404369828
12.221304043696062
12.221304043693827
12.221304043691594
12.221304043689372
12.221304043687148
12.221304043684919
12.2213040436827
12.221304043680474
12.221304043678257
12.221304043676035
12.221304043673815
12.22130404367159
12.22130404366937
12.22130404366715
12.221304043664926
12.221304043662714
12.22130404366049
12.221304043658275
12.221304043656051
12.221304043653832
12.221304043651617
12.22130404364941
12.22130404364719
12.22130404364497
12.221304043642762
12.221304043640542
12.221304043638332
12.221304043636119
12.221304043633907
12.221304043631687
12.221304043629486
12.221304043627269
12.221304043625059
12.22130404362284
12.22130404362063
12.221304043618428
12.221304043616218
12.221304043614008
12.221304043611804
12.221304043609592
12.221304043607388
12.221304043605178
12.221304043602972
12.221304043600771
12.221304043598565
12.221304043596357
12.22130404359415
12.221304043591951
12.221304043589749
12.221304043587544
12.221304043585342
12.221304043583148
12.221304043580938
12.221304043578735
12.221304043576534
12.221304043574335
12.221304043572134
12.22130404356994
12.221304043567741
12.221304043565542
12.221304043563348
12.221304043561146
12.221304043558955
12.221304043556755
12.22130404355456
12.221304043552362
12.221304043550164
12.22130404354798
12.221304043545784
12.221304043543585
12.221304043541387
12.2213040435392
12.221304043537005
12.221304043534811
12.221304043532625
12.221304043530436
12.221304043528246
12.22130404352606
12.22130404352387
12.221304043521679
12.221304043519492
12.221304043517302
12.221304043515111
12.221304043512934
12.221304043510743
12.221304043508562
12.221304043506372
12.221304043504189
12.221304043502005
12.221304043499822
12.221304043497641
12.221304043495456
12.221304043493275
12.221304043491088
12.221304043488914
12.221304043486729
12.221304043484539
12.221304043482366
12.221304043480188
12.221304043478002
12.221304043475829
12.22130404347365
12.221304043471466
12.221304043469294
12.221304043467114
12.22130404346494
12.22130404346277
12.221304043460584
12.221304043458415
12.221304043456247
12.221304043454069
12.221304043451891
12.221304043449718
12.221304043447548
12.221304043445377
12.221304043443203
12.221304043441036
12.221304043438863
12.221304043436692
12.221304043434525
12.221304043432356
12.221304043430182
12.221304043428015
12.22130404342585
12.221304043423675
12.221304043421508
12.221304043419341
12.22130404341718
12.221304043415019
12.221304043412855
12.22130404341069
12.221304043408521
12.221304043406365
12.221304043404198
12.221304043402041
12.221304043399874
12.221304043397708
12.22130404339555
12.221304043393394
12.22130404339123
12.221304043389063
12.221304043386912
12.221304043384746
12.221304043382595
12.221304043380432
12.22130404337828
12.221304043376122
12.221304043373966
12.22130404337181
12.221304043369647
12.221304043367507
12.221304043365341
12.221304043363192
12.221304043361041
12.22130404335888
12.221304043356731
12.221304043354573
12.221304043352422
12.221304043350273
12.221304043348127
12.221304043345976
12.221304043343817
12.221304043341675
12.221304043339519
12.221304043337378
12.221304043335227
12.221304043333076
12.221304043330933
12.221304043328791
12.221304043326636
12.221304043324494
12.221304043322347
12.221304043320197
12.221304043318055
12.221304043315916
12.221304043313772
12.221304043311628
12.221304043309486
12.22130404330735
12.221304043305206
12.22130404330307
12.22130404330092
12.221304043298778
12.221304043296643
12.221304043294507
12.221304043292363
12.221304043290223
12.221304043288084
12.221304043285949
12.221304043283805
12.221304043281675
12.221304043279542
12.221304043277405
12.221304043275266
12.22130404327313
12.221304043271001
12.221304043268866
12.221304043266736
12.221304043264606
12.221304043262466
12.221304043260334
12.221304043258208
12.221304043256074
12.221304043253944
12.221304043251816
12.221304043249681
12.221304043247553
12.22130404324543
12.221304043243308
12.221304043241163
12.221304043239044
12.221304043236916
12.22130404323479
12.221304043232667
12.221304043230539
12.221304043228411
12.221304043226286
12.221304043224164
12.221304043222045
12.221304043219913
12.22130404321779
12.221304043215675
12.221304043213554
12.221304043211429
12.22130404320931
12.221304043207187
12.221304043205073
12.221304043202947
12.221304043200837
12.22130404319871
12.221304043196598
12.221304043194483
12.221304043192363
12.22130404319025
12.221304043188123
12.221304043186011
12.221304043183897
12.22130404318178
12.221304043179671
12.221304043177556
12.221304043175444
12.221304043173326
12.221304043171212
12.221304043169104
12.221304043166993
12.221304043164876
12.221304043162771
12.221304043160654
12.22130404315854
12.221304043156442
12.22130404315433
12.221304043152227
12.22130404315011
12.221304043147999
12.221304043145903
12.221304043143789
12.221304043141682
12.221304043139583
12.221304043137476
12.221304043135369
12.22130404313327
12.221304043131166
12.221304043129065
12.221304043126956
12.221304043124851
12.221304043122753
12.221304043120655
12.221304043118549
12.221304043116456
12.221304043114351
12.22130404311225
12.221304043110157
12.221304043108058
12.221304043105953
12.221304043103864
12.221304043101759
12.221304043099666
12.221304043097573
12.221304043095468
12.221304043093376
12.221304043091274
12.221304043089189
12.22130404308709
12.221304043084997
12.221304043082904
12.221304043080806
12.221304043078717
12.221304043076623
12.221304043074538
12.221304043072443
12.221304043070361
12.221304043068258
12.221304043066175
12.22130404306408
12.221304043061995
12.221304043059902
12.221304043057815
12.221304043055728
12.221304043053644
12.221304043051557
12.221304043049471
12.221304043047384
12.221304043045302
12.221304043043215
12.221304043041128
12.221304043039048
12.221304043036966
12.221304043034882
12.221304043032795
12.221304043030717
12.221304043028637
12.221304043026558
12.221304043024475
12.221304043022394
12.221304043020309
12.22130404301824
12.221304043016156
12.22130404301408
12.221304043012
12.221304043009926
12.221304043007839
12.221304043005773
12.22130404300369
12.221304043001616
12.221304042999538
12.22130404299746
12.22130404299539
12.221304042993314
12.221304042991243
12.221304042989173
12.22130404298711
12.221304042985025
12.221304042982958
12.221304042980886
12.221304042978822
12.221304042976744
12.221304042974676
12.221304042972605
12.221304042970532
12.221304042968468
12.221304042966404
12.221304042964329
12.221304042962265
12.221304042960199
12.221304042958131
12.22130404295606
12.221304042953998
12.221304042951934
12.22130404294987
12.221304042947807
12.221304042945743
12.221304042943682
12.22130404294162
12.221304042939552
12.221304042937494
12.221304042935431
12.221304042933372
12.221304042931317
12.221304042929253
12.221304042927198
12.221304042925134
12.221304042923068
12.221304042921021
12.221304042918955
12.221304042916902
12.22130404291485
12.22130404291279
12.221304042910736
12.221304042908677
12.221304042906619
12.221304042904567
12.221304042902508
12.221304042900462
12.22130404289841
12.221304042896355
12.221304042894296
12.221304042892246
12.221304042890198
12.221304042888148
12.221304042886093
12.221304042884046
12.221304042882002
12.221304042879943
12.221304042877893
12.221304042875852
12.221304042873797
12.22130404287175
12.221304042869713
12.221304042867658
12.22130404286561
12.221304042863569
12.221304042861522
12.221304042859474
12.221304042857435
12.221304042855387
12.22130404285335
12.221304042851303
12.221304042849251

12.221304042847212
12.221304042845173
12.221304042843142
12.221304042841096
12.221304042839055
12.221304042837009
12.221304042834973
12.221304042832935
12.221304042830898
12.22130404282886
12.22130404282682
12.22130404282478
12.22130404282274
12.221304042820705
12.221304042818675
12.22130404281663
12.221304042814602
12.221304042812571
12.221304042810536
12.221304042808503
12.221304042806471
12.221304042804435
12.221304042802398
12.22130404280037
12.22130404279834
12.221304042796305
12.221304042794278
12.22130404279225
12.221304042790216
12.22130404278819
12.221304042786159
12.221304042784125
12.221304042782101
12.221304042780073
12.221304042778051
12.221304042776024
12.221304042773994
12.221304042771967
12.221304042769942
12.221304042767915
12.22130404276589
12.221304042763867
12.221304042761842
12.221304042759831
12.2213040427578
12.221304042755774
12.221304042753754
12.221304042751731
12.221304042749706
12.221304042747693
12.22130404274567
12.221304042743657
12.221304042741629
12.221304042739613
12.221304042737598
12.221304042735586
12.22130404273356
12.221304042731546
12.22130404272953
12.22130404272751
12.221304042725494
12.221304042723483
12.221304042721464
12.221304042719451
12.22130404271744
12.221304042715419
12.221304042713408
12.221304042711393
12.221304042709383
12.221304042707379
12.221304042705365
12.221304042703348
12.221304042701343
12.221304042699334
12.22130404269732
12.22130404269531
12.221304042693301
12.221304042691298
12.221304042689285
12.221304042687278
12.22130404268527
12.221304042683261
12.221304042681263
12.221304042679254
12.22130404267725
12.221304042675246
12.22130404267324
12.221304042671235
12.221304042669226
12.22130404266723
12.221304042665226
12.221304042663226
12.221304042661224
12.221304042659218
12.221304042657225
12.221304042655218
12.221304042653214
12.221304042651225
12.221304042649214
12.221304042647217
12.221304042645231
12.221304042643224
12.221304042641231
12.221304042639227
12.221304042637238
12.221304042635238
12.22130404263324
12.221304042631253
12.221304042629251
12.221304042627258
12.221304042625267
12.221304042623268
12.221304042621277
12.221304042619286
12.221304042617286
12.221304042615305
12.221304042613319
12.221304042611317
12.221304042609338
12.221304042607343
12.221304042605347
12.221304042603364
12.221304042601375
12.221304042599385
12.221304042597392
12.221304042595403
12.221304042593424
12.221304042591425
12.221304042589454
12.221304042587462
12.221304042585473
12.221304042583487
12.221304042581506
12.221304042579513
12.221304042577536
12.221304042575552
12.221304042573573
12.221304042571596
12.221304042569615
12.221304042567628
12.221304042565638
12.221304042563665
12.22130404256168
12.221304042559707
12.221304042557732
12.22130404255575
12.221304042553774
12.221304042551795
12.221304042549814
12.221304042547835
12.221304042545858
12.221304042543888
12.221304042541902
12.22130404253993
12.221304042537957
12.22130404253598
12.221304042534008
12.221304042532038
12.221304042530058
12.221304042528086
12.221304042526118
12.221304042524142
12.22130404252217
12.221304042520204
12.221304042518232
12.221304042516255
12.221304042514298
12.221304042512328
12.221304042510347
12.221304042508384
12.22130404250641
12.221304042504453
12.22130404250248
12.221304042500506
12.221304042498545
12.221304042496577
12.221304042494612
12.221304042492646
12.221304042490688
12.221304042488724
12.221304042486752
12.221304042484785
12.22130404248283
12.221304042480863
12.221304042478906
12.221304042476948
12.221304042474978
12.221304042473022
12.221304042471063
12.2213040424691
12.221304042467139
12.221304042465174
12.221304042463222
12.221304042461265
12.221304042459304
12.221304042457351
12.22130404245539
12.221304042453436
12.22130404245148
12.22130404244953
12.221304042447573
12.22130404244561
12.221304042443657
12.221304042441703
12.221304042439757
12.221304042437797
12.221304042435849
12.221304042433895
12.22130404243194
12.22130404242999
12.221304042428034
12.22130404242608
12.221304042424133
12.221304042422192
12.221304042420243
12.221304042418286
12.221304042416344
12.22130404241439
12.221304042412445
12.221304042410496
12.22130404240854
12.221304042406603
12.221304042404654
12.221304042402714
12.221304042400769
12.221304042398824
12.221304042396872
12.221304042394934
12.221304042392987
12.221304042391042
12.221304042389095
12.221304042387166
12.221304042385222
12.221304042383284
12.221304042381336
12.221304042379394
12.22130404237745
12.221304042375513
12.22130404237358
12.221304042371633
12.221304042369695
12.22130404236776
12.221304042365825
12.221304042363887
12.221304042361947
12.22130404236001
12.221304042358083
12.221304042356131
12.221304042354207
12.221304042352264
12.221304042350344
12.221304042348399
12.22130404234647
12.22130404234454
12.2213040423426
12.221304042340668
12.221304042338737
12.2213040423368
12.22130404233488
12.221304042332944
12.221304042331019
12.221304042329091
12.221304042327152
12.221304042325233
12.221304042323304
12.221304042321371
12.221304042319444
12.221304042317517
12.221304042315586
12.221304042313665
12.22130404231174
12.221304042309816
12.22130404230789
12.221304042305963
12.221304042304038
12.221304042302119
12.221304042300194
12.221304042298277
12.221304042296348
12.221304042294427
12.221304042292502
12.221304042290583
12.221304042288658
12.22130404228674
12.221304042284823
12.221304042282904
12.221304042280984
12.221304042279066
12.22130404227714
12.22130404227523
12.221304042273307
12.22130404227139
12.221304042269479
12.221304042267557
12.22130404226564
12.221304042263727
12.221304042261812
12.221304042259892
12.221304042257984
12.221304042256067
12.22130404225416
12.221304042252246
12.22130404225032
12.221304042248413
12.221304042246507
12.221304042244597
12.221304042242691
12.221304042240773
12.221304042238858
12.221304042236955
12.221304042235039
12.221304042233138
12.22130404223123
12.221304042229315
12.221304042227414
12.221304042225503
12.221304042223599
12.221304042221684
12.221304042219787
12.221304042217879
12.221304042215975
12.221304042214067
12.22130404221216
12.22130404221026
12.221304042208354
12.221304042206453
12.221304042204554
12.221304042202656
12.22130404220075
12.221304042198849
12.221304042196945
12.22130404219505
12.22130404219315
12.22130404219125
12.221304042189347
12.221304042187445
12.221304042185555
12.221304042183645
12.221304042181753
12.221304042179854
12.221304042177957
12.221304042176062
12.221304042174165
12.221304042172266
12.221304042170372
12.221304042168471
12.221304042166581
12.221304042164686
12.221304042162796
12.221304042160908
12.221304042159009
12.221304042157115
12.221304042155232
12.221304042153342
12.221304042151445
12.221304042149557
12.221304042147661
12.221304042145778
12.221304042143885
12.221304042141998
12.22130404214011
12.221304042138224
12.221304042136333
12.221304042134438
12.221304042132555
12.22130404213067
12.221304042128777
12.221304042126896
12.22130404212502
12.22130404212313
12.221304042121245
12.221304042119357
12.22130404211747
12.221304042115595
12.221304042113708
12.221304042111825
12.22130404210994
12.22130404210806
12.221304042106185
12.2213040421043
12.221304042102421
12.221304042100542
12.221304042098659
12.221304042096776
12.221304042094898
12.221304042093019
12.22130404209115
12.221304042089264
12.221304042087391
12.22130404208551
12.221304042083634
12.221304042081757
12.221304042079886
12.221304042078012
12.221304042076142
12.221304042074264
12.221304042072381
12.22130404207052
12.221304042068642
12.221304042066766
12.221304042064892
12.22130404206303
12.221304042061153
12.221304042059279
12.221304042057412
12.22130404205554
12.221304042053669
12.2213040420518
12.221304042049931
12.221304042048065
12.221304042046198
12.221304042044332
12.22130404204246
12.221304042040593
12.221304042038723
12.221304042036857
12.221304042035001
12.221304042033136
12.221304042031262
12.221304042029402
12.221304042027532
12.221304042025668
12.221304042023814
12.221304042021941
12.221304042020078
12.221304042018225
12.221304042016362
12.221304042014497
12.221304042012632
12.221304042010773
12.221304042008919
12.221304042007057
12.221304042005194
12.221304042003338
12.221304042001478
12.221304041999627
12.22130404199776
12.221304041995909
12.221304041994053
12.221304041992195
12.221304041990336
12.22130404198848
12.22130404198663
12.221304041984773
12.221304041982913
12.221304041981066
12.221304041979202
12.221304041977351
12.2213040419755
12.221304041973648
12.221304041971798
12.221304041969955
12.221304041968091
12.221304041966242
12.221304041964395
12.22130404196254
12.2213040419607
12.221304041958845
12.221304041956992
12.221304041955145
12.221304041953307
12.221304041951448
12.221304041949601
12.221304041947748
12.221304041945906
12.221304041944059
12.221304041942215
12.22130404194037
12.221304041938529
12.221304041936685
12.22130404193484
12.221304041932992
12.221304041931148
12.22130404192931
12.221304041927464
12.221304041925618
12.221304041923789
12.221304041921941
12.221304041920101
12.221304041918259
12.221304041916415
12.22130404191458
12.221304041912736
12.221304041910894
12.221304041909063
12.221304041907228
12.221304041905382
12.22130404190355
12.221304041901716
12.221304041899883
12.221304041898039
12.221304041896211
12.221304041894367
12.221304041892536
12.221304041890708
12.221304041888871
12.221304041887032
12.221304041885196
12.221304041883371
12.221304041881535
12.221304041879698
12.221304041877872

12.221304041876039
12.221304041874207
12.221304041872378
12.221304041870546
12.221304041868718
12.221304041866897
12.221304041865055
12.221304041863231
12.221304041861398
12.221304041859575
12.221304041857746
12.221304041855912
12.22130404185409
12.22130404185227
12.221304041850432
12.221304041848617
12.221304041846789
12.221304041844974
12.22130404184314
12.221304041841321
12.221304041839499
12.221304041837673
12.221304041835852
12.221304041834031
12.221304041832203
12.22130404183039
12.22130404182856
12.221304041826743
12.221304041824926
12.2213040418231
12.221304041821275
12.221304041819467
12.221304041817646
12.221304041815825
12.221304041814012
12.221304041812187
12.221304041810376
12.221304041808564
12.221304041806745
12.221304041804931
12.22130404180311
12.221304041801288
12.221304041799481
12.221304041797666
12.221304041795856
12.221304041794033
12.221304041792225
12.221304041790408
12.221304041788601
12.221304041786786
12.221304041784974
12.221304041783162
12.221304041781359
12.221304041779543
12.221304041777739
12.22130404177592
12.221304041774117
12.221304041772303
12.221304041770496
12.221304041768684
12.221304041766881
12.221304041765075
12.221304041763268
12.22130404176146
12.221304041759662
12.22130404175785
12.221304041756037
12.22130404175424
12.221304041752438
12.221304041750633
12.22130404174883
12.221304041747027
12.221304041745219
12.22130404174343
12.221304041741613
12.221304041739817
12.22130404173801
12.221304041736209
12.221304041734408
12.221304041732612
12.221304041730816
12.221304041729013
12.221304041727219
12.221304041725421
12.221304041723618
12.221304041721819
12.22130404172002
12.221304041718222
12.22130404171643
12.22130404171463
12.221304041712838
12.221304041711042
12.221304041709248
12.221304041707448
12.22130404170566
12.22130404170387
12.221304041702064
12.221304041700275
12.221304041698486
12.221304041696692
12.221304041694898
12.221304041693106
12.221304041691315
12.22130404168953
12.221304041687734
12.221304041685952
12.221304041684162
12.221304041682359
12.221304041680572
12.221304041678792
12.221304041676996
12.221304041675209
12.221304041673429
12.221304041671646
12.221304041669855
12.221304041668072
12.221304041666283
12.221304041664501
12.221304041662707
12.221304041660927
12.22130404165914
12.221304041657358
12.221304041655573
12.221304041653795
12.22130404165201
12.22130404165023
12.221304041648445
12.22130404164666
12.22130404164488
12.2213040416431
12.221304041641316
12.22130404163954
12.221304041637758
12.22130404163598
12.221304041634202
12.221304041632425
12.221304041630647
12.22130404162887
12.221304041627084
12.221304041625304
12.221304041623531
12.221304041621766
12.22130404161999
12.221304041618211
12.221304041616435
12.221304041614653
12.221304041612882
12.221304041611114
12.221304041609336
12.22130404160757
12.22130404160579
12.221304041604014
12.221304041602247
12.221304041600478
12.221304041598703
12.221304041596937
12.221304041595165
12.221304041593392
12.221304041591626
12.221304041589853
12.22130404158809
12.221304041586317
12.22130404158455
12.221304041582785
12.22130404158102
12.221304041579245
12.221304041577488
12.221304041575719
12.221304041573955
12.221304041572182
12.22130404157042
12.22130404156865
12.221304041566896
12.22130404156513
12.221304041563364
12.221304041561599
12.221304041559836
12.221304041558076
12.22130404155632
12.221304041554557
12.221304041552793
12.221304041551027
12.221304041549265
12.22130404154751
12.221304041545746
12.221304041543988
12.221304041542236
12.221304041540474
12.221304041538714
12.221304041536953
12.221304041535207
12.221304041533443
12.221304041531685
12.221304041529928
12.221304041528173
12.221304041526416
12.221304041524665
12.221304041522906
12.221304041521154
12.221304041519401
12.22130404151765
12.221304041515896
12.221304041514145
12.221304041512386
12.221304041510631
12.22130404150889
12.221304041507134
12.221304041505386
12.221304041503636
12.221304041501886
12.22130404150014
12.221304041498387
12.22130404149663
12.22130404149489
12.221304041493136
12.221304041491395
12.221304041489644
12.221304041487894
12.22130404148615
12.221304041484409
12.221304041482664
12.221304041480918
12.221304041479167
12.221304041477422
12.221304041475685
12.221304041473934
12.221304041472191
12.221304041470445
12.221304041468706
12.22130404146696
12.221304041465215
12.221304041463478
12.22130404146174
12.221304041459994
12.221304041458257
12.221304041456513
12.221304041454776
12.221304041453037
12.221304041451294
12.221304041449558
12.221304041447816
12.22130404144608
12.22130404144435
12.221304041442606
12.221304041440872
12.221304041439144
12.221304041437394
12.221304041435662
12.221304041433923
12.221304041432191
12.221304041430457
12.221304041428724
12.221304041426988
12.221304041425256
12.221304041423528
12.221304041421792
12.221304041420057
12.221304041418325
12.221304041416591
12.221304041414864
12.22130404141314
12.221304041411399
12.221304041409667
12.221304041407942
12.221304041406212
12.221304041404476
12.221304041402759
12.221304041401032
12.221304041399295
12.221304041397573
12.221304041395838
12.221304041394118
12.221304041392392
12.221304041390663
12.22130404138894
12.221304041387217
12.221304041385487
12.221304041383767
12.221304041382044
12.221304041380325
12.221304041378595
12.221304041376873
12.221304041375149
12.221304041373422
12.2213040413717
12.22130404136998
12.22130404136826
12.221304041366542
12.221304041364832
12.2213040413631
12.221304041361376
12.221304041359659
12.221304041357941
12.22130404135622
12.221304041354507
12.221304041352782
12.221304041351068
12.221304041349347
12.22130404134764
12.221304041345924
12.221304041344204
12.221304041342492
12.221304041340773
12.221304041339065
12.221304041337346
12.221304041335634
12.22130404133392
12.2213040413322
12.221304041330484
12.221304041328777
12.221304041327066
12.221304041325356
12.22130404132364
12.221304041321927
12.22130404132022
12.221304041318513
12.221304041316797
12.221304041315085
12.221304041313378
12.221304041311676
12.221304041309969
12.221304041308258
12.22130404130655
12.221304041304844
12.221304041303135
12.22130404130143
12.22130404129973
12.221304041298021
12.22130404129631
12.221304041294609
12.2213040412929
12.221304041291193
12.221304041289494
12.22130404128779
12.221304041286087
12.22130404128439
12.221304041282677
12.221304041280979
12.221304041279277
12.221304041277572
12.221304041275879
12.221304041274175
12.221304041272482
12.221304041270772
12.221304041269079
12.221304041267375
12.221304041265679
12.221304041263977
12.221304041262284
12.221304041260579
12.22130404125888
12.221304041257198
12.221304041255495
12.221304041253797
12.221304041252102
12.221304041250402
12.221304041248708
12.221304041247016
12.221304041245327
12.221304041243627
12.221304041241936
12.221304041240241
12.221304041238549
12.221304041236852
12.22130404123516
12.221304041233466
12.221304041231775
12.22130404123009
12.221304041228393
12.221304041226704
12.221304041225013
12.221304041223323
12.22130404122164
12.22130404121995
12.221304041218255
12.221304041216568
12.221304041214886
12.2213040412132
12.221304041211514
12.221304041209823
12.221304041208137
12.221304041206448
12.221304041204764
12.221304041203084
12.221304041201398
12.22130404119971
12.221304041198023
12.221304041196337
12.221304041194658
12.221304041192974
12.221304041191294
12.221304041189605
12.22130404118793
12.221304041186247
12.221304041184569
12.221304041182881
12.221304041181206
12.221304041179527
12.221304041177847
12.221304041176166
12.221304041174491
12.221304041172809
12.221304041171127
12.22130404116945
12.221304041167773
12.221304041166096
12.221304041164418
12.221304041162744
12.221304041161062
12.2213040411594
12.221304041157714
12.221304041156042
12.221304041154369
12.221304041152694
12.22130404115102
12.221304041149345
12.221304041147674
12.221304041145993
12.22130404114433
12.221304041142654
12.221304041140984
12.221304041139314
12.221304041137639
12.221304041135967
12.221304041134305
12.221304041132623
12.221304041130955
12.221304041129295
12.221304041127624
12.221304041125952
12.22130404112429
12.221304041122616
12.221304041120943
12.221304041119287
12.221304041117618
12.221304041115948
12.221304041114285
12.221304041112624
12.221304041110947
12.221304041109281
12.221304041107615
12.221304041105965
12.221304041104293
12.221304041102636
12.221304041100971
12.221304041099303
12.221304041097639
12.221304041095978
12.22130404109432
12.221304041092667
12.221304041090997

12.22130404108934
12.221304041087674
12.221304041086015
12.221304041084357
12.2213040410827
12.22130404108104
12.221304041079378
12.221304041077719
12.221304041076067
12.221304041074408
12.221304041072756
12.221304041071097
12.221304041069441
12.221304041067787
12.221304041066135
12.221304041064469
12.221304041062815
12.221304041061162
12.221304041059508
12.22130404105786
12.221304041056205
12.221304041054545
12.221304041052894
12.221304041051246
12.221304041049592
12.221304041047938
12.22130404104629
12.221304041044638
12.221304041042993
12.221304041041343
12.221304041039682
12.221304041038039
12.221304041036394
12.221304041034738
12.22130404103309
12.221304041031445
12.221304041029798
12.221304041028153
12.221304041026501
12.22130404102486
12.221304041023211
12.221304041021563
12.221304041019922
12.22130404101828
12.221304041016628
12.221304041014987
12.22130404101334
12.221304041011695
12.22130404101005
12.221304041008414
12.221304041006771
12.221304041005125
12.22130404100349
12.221304041001838
12.221304041000199
12.221304040998561
12.221304040996918
12.22130404099528
12.221304040993637
12.221304040991997
12.221304040990367
12.221304040988718
12.221304040987086
12.221304040985443
12.22130404098381
12.221304040982174
12.221304040980536
12.221304040978904
12.221304040977259
12.221304040975623
12.221304040973997
12.221304040972354
12.221304040970725
12.221304040969086
12.221304040967453
12.221304040965817
12.221304040964188
12.221304040962552
12.22130404096092
12.221304040959293
12.221304040957655
12.22130404095602
12.221304040954392
12.221304040952768
12.221304040951134
12.2213040409495
12.22130404094787
12.221304040946244
12.22130404094462
12.221304040942982
12.221304040941362
12.221304040939728
12.2213040409381
12.221304040936472
12.221304040934838
12.221304040933212
12.221304040931596
12.22130404092997
12.221304040928343
12.221304040926718
12.221304040925085
12.221304040923469
12.221304040921837
12.22130404092022
12.221304040918598
12.221304040916978
12.221304040915346
12.22130404091373
12.221304040912104
12.221304040910486
12.221304040908858
12.22130404090724
12.221304040905617
12.221304040904
12.221304040902385
12.221304040900764
12.221304040899142
12.221304040897522
12.221304040895905
12.221304040894283
12.221304040892667
12.221304040891052
12.221304040889441
12.22130404088782
12.2213040408862
12.221304040884583
12.221304040882972
12.221304040881359
12.221304040879737
12.221304040878126
12.221304040876507
12.221304040874898
12.221304040873282
12.221304040871669
12.221304040870052
12.221304040868445
12.221304040866832
12.221304040865219
12.22130404086361
12.221304040861998
12.221304040860392
12.221304040858776
12.221304040857161
12.221304040855559
12.221304040853944
12.221304040852338
12.221304040850724
12.221304040849116
12.221304040847512
12.22130404084591
12.221304040844293
12.221304040842682
12.221304040841074
12.221304040839474
12.221304040837872
12.22130404083626
12.221304040834655
12.221304040833049
12.221304040831452
12.221304040829848
12.22130404082824
12.221304040826634
12.221304040825043
12.221304040823433
12.221304040821831
12.221304040820225
12.221304040818621
12.221304040817024
12.22130404081543
12.221304040813823
12.221304040812223
12.221304040810622
12.221304040809025
12.221304040807418
12.221304040805826
12.221304040804233
12.221304040802627
12.221304040801028
12.221304040799435
12.221304040797829
12.221304040796232
12.22130404079464
12.221304040793044
12.221304040791452
12.221304040789859
12.221304040788254
12.221304040786665
12.22130404078507
12.221304040783469
12.221304040781877
12.221304040780286
12.221304040778694
12.221304040777103
12.22130404077551
12.221304040773916
12.221304040772324
12.221304040770727
12.221304040769143
12.221304040767556
12.221304040765967
12.221304040764377
12.221304040762782
12.221304040761193
12.22130404075961
12.221304040758014
12.221304040756428
12.221304040754845
12.221304040753251
12.221304040751663
12.221304040750073
12.22130404074849
12.221304040746904
12.221304040745322
12.22130404074373
12.221304040742151
12.221304040740565
12.22130404073898
12.221304040737396
12.22130404073581
12.22130404073423
12.221304040732642
12.221304040731065
12.221304040729478
12.221304040727906
12.221304040726316
12.221304040724737
12.221304040723158
12.221304040721577
12.22130404071999
12.22130404071841
12.22130404071683
12.221304040715257
12.221304040713672
12.221304040712093
12.221304040710516
12.221304040708938
12.221304040707361
12.221304040705782
12.221304040704203
12.221304040702629
12.221304040701057
12.22130404069947
12.2213040406979
12.221304040696326
12.221304040694758
12.221304040693179
12.221304040691603
12.221304040690029
12.221304040688455
12.221304040686881
12.221304040685313
12.22130404068374
12.221304040682169
12.221304040680598
12.221304040679023
12.221304040677452
12.22130404067588
12.221304040674315
12.221304040672743
12.221304040671173
12.221304040669596
12.221304040668038
12.221304040666466
12.221304040664894
12.221304040663323
12.221304040661764
12.221304040660188
12.221304040658627
12.221304040657058
12.221304040655493
12.221304040653923
12.22130404065236
12.221304040650795
12.221304040649231
12.221304040647663
12.221304040646098
12.221304040644538
12.221304040642972
12.22130404064141
12.221304040639852
12.22130404063829
12.221304040636724
12.221304040635161
12.2213040406336
12.22130404063204
12.221304040630482
12.221304040628915
12.221304040627354
12.221304040625798
12.221304040624238
12.22130404062268
12.221304040621124
12.221304040619557
12.221304040618005
12.221304040616445
12.22130404061488
12.221304040613322
12.221304040611766
12.221304040610216
12.22130404060866
12.221304040607105
12.221304040605547
12.221304040603997
12.221304040602439
12.221304040600884
12.221304040599334
12.221304040597774
12.221304040596227
12.221304040594665
12.22130404059312
12.221304040591559
12.221304040590018
12.221304040588468
12.221304040586906
12.221304040585354
12.221304040583806
12.221304040582256
12.221304040580705
12.221304040579154
12.221304040577603
12.221304040576056
12.22130404057451
12.221304040572962
12.221304040571411
12.221304040569862
12.221304040568318
12.221304040566778
12.221304040565222
12.221304040563677
12.221304040562131
12.221304040560586
12.221304040559037
12.22130404055749
12.221304040555953
12.22130404055441
12.221304040552859
12.22130404055132
12.221304040549782
12.221304040548233
12.221304040546688
12.221304040545144
12.22130404054361
12.221304040542062
12.221304040540517
12.221304040538984
12.221304040537438
12.221304040535893
12.22130404053436
12.221304040532821
12.221304040531283
12.221304040529734
12.221304040528207
12.22130404052667
12.221304040525123
12.221304040523592
12.221304040522059
12.221304040520515
12.221304040518985
12.221304040517438
12.221304040515903
12.221304040514367
12.221304040512837
12.221304040511303
12.221304040509768
12.221304040508224
12.2213040405067
12.221304040505162
12.221304040503627
12.221304040502092
12.221304040500563
12.221304040499028
12.221304040497495
12.221304040495964
12.22130404049443
12.221304040492901
12.221304040491377
12.221304040489846
12.221304040488318
12.22130404048678
12.22130404048525
12.221304040483723
12.221304040482199
12.22130404048067
12.221304040479133
12.221304040477618
12.221304040476081
12.221304040474552
12.221304040473028
12.221304040471509
12.221304040469978
12.221304040468455
12.22130404046693
12.2213040404654
12.22130404046387
12.221304040462346
12.221304040460826
12.221304040459309
12.221304040457778
12.221304040456257
12.221304040454726
12.221304040453214
12.22130404045169
12.221304040450168
12.221304040448647
12.221304040447125
12.221304040445606
12.221304040444084
12.22130404044256
12.221304040441042
12.221304040439524
12.221304040438
12.22130404043649
12.22130404043497
12.22130404043345
12.22130404043194
12.22130404043042
12.221304040428894
12.221304040427384
12.22130404042586
12.221304040424348
12.221304040422831
12.221304040421316
12.221304040419804
12.221304040418287
12.221304040416774
12.221304040415259
12.221304040413743
12.22130404041223
12.221304040410725
12.221304040409207
12.22130404040769
12.221304040406181
12.221304040404672
12.221304040403151
12.22130404040164
12.221304040400133
12.221304040398621
12.221304040397113
12.221304040395598
12.22130404039409
12.221304040392585
12.221304040391074
12.221304040389565
12.221304040388054
12.221304040386553
12.221304040385043
12.221304040383535
12.22130404038203
12.221304040380518
12.22130404037902
12.221304040377508
12.221304040376005
12.221304040374507
12.221304040372988
12.221304040371484
12.22130404036998
12.22130404036848
12.221304040366977
12.221304040365476
12.22130404036397
12.221304040362469
12.221304040360966

12.221304040359461
12.221304040357962
12.221304040356463
12.221304040354953
12.221304040353465
12.221304040351962
12.22130404035046
12.221304040348958
12.221304040347459
12.22130404034597
12.22130404034446
12.221304040342963
12.221304040341463
12.221304040339962
12.221304040338467
12.221304040336973
12.221304040335477
12.22130404033398
12.221304040332486
12.221304040330981
12.221304040329485
12.221304040327992
12.221304040326505
12.22130404032501
12.221304040323519
12.22130404032202
12.221304040320529
12.221304040319032
12.221304040317532
12.221304040316042
12.221304040314552
12.221304040313061
12.22130404031158
12.22130404031008
12.221304040308583
12.221304040307096
12.221304040305606
12.221304040304112
12.221304040302618
12.221304040301142
12.221304040299641
12.221304040298156
12.221304040296676
12.221304040295182
12.221304040293694
12.221304040292207
12.221304040290718
12.221304040289237
12.221304040287752
12.221304040286263
12.221304040284767
12.221304040283286
12.221304040281803
12.221304040280318
12.221304040278836
12.221304040277358
12.221304040275864
12.221304040274383
12.221304040272901
12.221304040271418
12.22130404026993
12.221304040268446
12.22130404026697
12.221304040265492
12.221304040264
12.221304040262526
12.221304040261044
12.221304040259557
12.221304040258087
12.221304040256602
12.221304040255118
12.221304040253644
12.221304040252166
12.221304040250695
12.221304040249212
12.221304040247732
12.221304040246256
12.22130404024477
12.221304040243302
12.22130404024183
12.221304040240344
12.221304040238874
12.221304040237394
12.221304040235918
12.221304040234445
12.22130404023297
12.221304040231496
12.221304040230027
12.221304040228556
12.221304040227075
12.221304040225604
12.221304040224128
12.221304040222655
12.221304040221188
12.22130404021972
12.221304040218243
12.22130404021677
12.221304040215305
12.221304040213838
12.221304040212358
12.221304040210894
12.221304040209423
12.22130404020795
12.221304040206489
12.221304040205005
12.221304040203545
12.22130404020208
12.221304040200609
12.22130404019914
12.221304040197678
12.2213040401962
12.221304040194742
12.22130404019328
12.221304040191805
12.22130404019034
12.221304040188878
12.221304040187412
12.221304040185945
12.22130404018449
12.221304040183023
12.221304040181556
12.221304040180097
12.221304040178639
12.221304040177177
12.22130404017571
12.221304040174253
12.221304040172786
12.221304040171324
12.221304040169864
12.2213040401684
12.221304040166945
12.221304040165485
12.221304040164027
12.221304040162568
12.2213040401611
12.221304040159646
12.221304040158191
12.221304040156733
12.221304040155268
12.221304040153813
12.221304040152358
12.221304040150901
12.221304040149448
12.221304040147993
12.221304040146535
12.221304040145078
12.221304040143623
12.221304040142165
12.221304040140714
12.221304040139259
12.221304040137806
12.221304040136348
12.2213040401349
12.221304040133447
12.221304040131992
12.221304040130542
12.221304040129088
12.221304040127636
12.221304040126187
12.221304040124734
12.221304040123284
12.22130404012183
12.221304040120373
12.221304040118934
12.221304040117486
12.221304040116037
12.221304040114589
12.22130404011313
12.22130404011169
12.221304040110235
12.22130404010879
12.221304040107341
12.221304040105895
12.221304040104453
12.221304040103007
12.221304040101561
12.221304040100119
12.221304040098662
12.221304040097214
12.221304040095777
12.22130404009433
12.22130404009289
12.221304040091436
12.221304040089995
12.221304040088555
12.22130404008711
12.221304040085673
12.221304040084235
12.221304040082785
12.22130404008134
12.221304040079906
12.221304040078465
12.22130404007702
12.221304040075575
12.221304040074148
12.221304040072699
12.221304040071265
12.221304040069827
12.221304040068384
12.221304040066943
12.221304040065506
12.221304040064068
12.221304040062627
12.221304040061195
12.221304040059756
12.221304040058321
12.221304040056888
12.221304040055452
12.221304040054017
12.221304040052583
12.221304040051152
12.221304040049707
12.221304040048272
12.221304040046835
12.221304040045409
12.221304040043975
12.221304040042542
12.221304040041101
12.221304040039675
12.221304040038238
12.2213040400368
12.22130404003537
12.221304040033944
12.221304040032516
12.221304040031086
12.221304040029647
12.221304040028222
12.221304040026794
12.221304040025357
12.221304040023936
12.221304040022503
12.221304040021078
12.221304040019646
12.221304040018218
12.221304040016793
12.22130404001537
12.22130404001394
12.221304040012512
12.221304040011088
12.221304040009649
12.22130404000823
12.221304040006801
12.221304040005384
12.22130404000396
12.221304040002531
12.22130404000111
12.221304039999684
12.22130403999826
12.22130403999683
12.221304039995411
12.221304039993987
12.221304039992566
12.22130403999115
12.221304039989727
12.2213040399883
12.22130403998688
12.221304039985462
12.221304039984036
12.22130403998262
12.2213040399812
12.22130403997978
12.221304039978357
12.221304039976943
12.221304039975529
12.2213040399741
12.221304039972686
12.22130403997127
12.221304039969857
12.22130403996844
12.22130403996702
12.221304039965604
12.221304039964185
12.221304039962773
12.221304039961352
12.221304039959936
12.221304039958518
12.221304039957111
12.221304039955688
12.221304039954276
12.221304039952868
12.221304039951452
12.221304039950045
12.221304039948626
12.221304039947205
12.221304039945798
12.221304039944393
12.221304039942984
12.221304039941565
12.22130403994016
12.221304039938744
12.221304039937333
12.221304039935916
12.221304039934509
12.221304039933106
12.221304039931695
12.221304039930287
12.221304039928873
12.221304039927466
12.221304039926066
12.221304039924654
12.221304039923247
12.221304039921836
12.22130403992043
12.221304039919023
12.221304039917614
12.221304039916223
12.221304039914811
12.2213040399134
12.221304039912
12.221304039910592
12.221304039909192
12.221304039907784
12.221304039906377
12.221304039904972
12.221304039903574
12.22130403990217
12.22130403990077
12.221304039899366
12.221304039897966
12.221304039896568
12.22130403989516
12.221304039893763
12.221304039892363
12.221304039890963
12.221304039889562
12.221304039888164
12.22130403988676
12.221304039885357
12.221304039883963
12.221304039882567
12.22130403988117
12.221304039879767
12.221304039878376
12.221304039876975
12.221304039875573
12.221304039874184
12.221304039872786
12.221304039871391
12.221304039869993
12.221304039868594
12.2213040398672
12.221304039865803
12.221304039864414
12.221304039863014
12.221304039861627
12.221304039860232
12.221304039858838
12.221304039857442
12.221304039856047
12.221304039854648
12.221304039853262
12.221304039851871
12.221304039850484
12.22130403984909
12.2213040398477
12.221304039846304
12.221304039844917
12.22130403984353
12.221304039842133
12.221304039840755
12.221304039839355
12.221304039837971
12.221304039836582
12.221304039835195
12.221304039833802
12.221304039832416
12.22130403983103
12.221304039829649
12.221304039828249
12.221304039826878
12.221304039825482
12.221304039824103
12.22130403982271
12.221304039821336
12.221304039819946
12.22130403981856
12.221304039817174
12.221304039815788
12.221304039814402
12.221304039813022
12.221304039811644
12.221304039810255
12.221304039808878
12.221304039807489
12.22130403980611
12.221304039804728
12.221304039803346
12.22130403980196
12.221304039800588
12.221304039799204
12.22130403979782
12.221304039796445
12.221304039795063
12.221304039793688
12.221304039792297
12.221304039790928
12.221304039789555
12.221304039788174
12.221304039786796
12.221304039785416
12.22130403978404
12.22130403978266
12.221304039781284
12.221304039779907
12.22130403977854
12.221304039777156
12.22130403977578
12.221304039774404
12.221304039773033
12.221304039771661
12.221304039770281
12.221304039768908
12.221304039767535
12.221304039766165
12.22130403976479
12.221304039763417
12.221304039762046
12.221304039760676
12.221304039759296
12.221304039757932
12.221304039756555
12.221304039755188
12.221304039753813
12.22130403975245
12.221304039751072
12.221304039749711
12.22130403974833
12.221304039746961
12.221304039745599
12.221304039744233
12.221304039742858
12.221304039741495
12.221304039740131
12.221304039738762
12.221304039737397
12.221304039736026
12.22130403973466
12.221304039733297
12.221304039731933
12.221304039730564
12.221304039729198
12.221304039727826
12.221304039726464
12.2213040397251
12.221304039723744
12.22130403972237
12.221304039721012
12.22130403971965
12.221304039718278
12.221304039716923
12.221304039715568
12.221304039714191
12.22130403971284
12.22130403971147
12.22130403971012
12.221304039708754
12.221304039707393
12.221304039706029
12.221304039704668
12.221304039703314
12.221304039701957
12.221304039700591

12.221304039699236
12.221304039697879
12.221304039696516
12.221304039695159
12.2213040396938
12.221304039692448
12.221304039691093
12.221304039689736
12.221304039688377
12.22130403968702
12.221304039685663
12.221304039684314
12.22130403968295
12.221304039681597
12.221304039680241
12.221304039678891
12.22130403967754
12.221304039676177
12.221304039674827
12.221304039673473
12.221304039672123
12.22130403967077
12.221304039669414
12.221304039668068
12.221304039666716
12.221304039665362
12.221304039664012
12.221304039662662
12.22130403966131
12.221304039659962
12.221304039658609
12.221304039657257
12.22130403965591
12.221304039654564
12.221304039653207
12.221304039651859
12.221304039650509
12.22130403964917
12.22130403964782
12.221304039646478
12.221304039645126
12.221304039643778
12.221304039642433
12.22130403964109
12.221304039639737
12.221304039638403
12.22130403963705
12.221304039635708
12.221304039634363
12.22130403963302
12.221304039631672
12.221304039630331
12.221304039628981
12.221304039627645
12.221304039626297
12.221304039624963
12.221304039623613
12.221304039622277
12.22130403962093
12.221304039619595
12.221304039618254
12.221304039616903
12.221304039615566
12.221304039614223
12.221304039612887
12.22130403961155
12.221304039610205
12.221304039608865
12.221304039607528
12.221304039606188
12.221304039604854
12.221304039603517
12.221304039602172
12.221304039600838
12.221304039599504
12.221304039598166
12.22130403959683
12.221304039595486
12.221304039594163
12.22130403959282
12.221304039591484
12.221304039590146
12.221304039588812
12.221304039587482
12.221304039586142
12.221304039584817
12.221304039583487
12.221304039582149
12.221304039580819
12.22130403957948
12.22130403957815
12.221304039576815
12.221304039575488
12.22130403957415
12.22130403957282
12.221304039571498
12.22130403957016
12.221304039568828
12.221304039567498
12.221304039566167
12.221304039564837
12.22130403956351
12.22130403956218
12.221304039560852
12.221304039559518
12.221304039558195
12.22130403955687
12.22130403955554
12.22130403955422
12.221304039552887
12.221304039551555
12.22130403955023
12.22130403954891
12.221304039547578
12.22130403954626
12.221304039544926
12.221304039543604
12.221304039542275
12.22130403954096
12.221304039539634
12.221304039538312
12.221304039536987
12.221304039535664
12.221304039534342
12.22130403953302
12.221304039531697
12.221304039530368
12.221304039529052
12.221304039527736
12.221304039526412
12.221304039525085
12.22130403952376
12.221304039522451
12.221304039521126
12.221304039519799
12.221304039518479
12.221304039517175
12.221304039515848
12.22130403951453
12.221304039513209
12.221304039511892
12.221304039510578
12.221304039509262
12.221304039507933
12.221304039506618
12.221304039505304
12.221304039503988
12.221304039502675
12.221304039501353
12.221304039500048
12.221304039498728
12.221304039497413
12.221304039496104
12.22130403949479
12.221304039493468
12.221304039492152
12.22130403949084
12.22130403948953
12.221304039488219
12.221304039486904
12.221304039485599
12.221304039484274
12.221304039482968
12.221304039481652
12.221304039480346
12.221304039479032
12.221304039477726
12.22130403947641
12.221304039475095
12.221304039473788
12.221304039472484
12.221304039471176
12.221304039469867
12.221304039468553
12.221304039467247
12.221304039465936
12.221304039464632
12.221304039463323
12.221304039462018
12.221304039460712
12.22130403945941
12.221304039458097
12.221304039456792
12.221304039455482
12.22130403945418
12.221304039452882
12.221304039451573
12.221304039450267
12.221304039448961
12.221304039447652
12.221304039446354
12.221304039445048
12.22130403944374
12.221304039442447
12.221304039441135
12.221304039439833
12.221304039438536
12.221304039437232
12.221304039435935
12.221304039434632
12.221304039433326
12.221304039432033
12.22130403943073
12.221304039429427
12.221304039428123
12.22130403942683
12.221304039425533
12.221304039424233
12.221304039422929
12.221304039421632
12.221304039420335
12.221304039419035
12.22130403941774
12.22130403941644
12.221304039415148
12.22130403941386
12.221304039412553
12.221304039411253
12.221304039409953
12.221304039408663
12.221304039407364
12.221304039406073
12.221304039404782
12.221304039403483
12.221304039402186
12.221304039400895
12.221304039399602
12.221304039398314
12.221304039397017
12.221304039395726
12.221304039394436
12.221304039393143
12.221304039391848
12.221304039390558
12.22130403938927
12.221304039387965
12.221304039386673
12.221304039385386
12.221304039384094
12.221304039382808
12.221304039381522
12.221304039380225
12.221304039378941
12.221304039377648
12.221304039376356
12.22130403937507
12.221304039373786
12.221304039372496
12.221304039371212
12.221304039369919
12.221304039368636
12.22130403936734
12.221304039366062
12.22130403936478
12.221304039363497
12.22130403936221
12.22130403936092
12.221304039359635
12.221304039358346
12.22130403935707
12.221304039355775
12.2213040393545
12.221304039353216
12.22130403935193
12.221304039350644
12.221304039349368
12.221304039348077
12.221304039346805
12.221304039345517
12.221304039344236
12.221304039342956
12.221304039341673
12.221304039340389
12.221304039339117
12.22130403933783
12.22130403933655
12.221304039335273
12.22130403933399
12.22130403933271
12.221304039331436
12.22130403933016
12.221304039328887
12.2213040393276
12.221304039326327
12.221304039325044
12.221304039323767
12.221304039322487
12.221304039321213
12.221304039319943
12.221304039318657
12.22130403931738
12.221304039316108
12.221304039314838
12.221304039313559
12.221304039312285
12.221304039311015
12.221304039309738
12.221304039308462
12.221304039307196
12.221304039305913
12.22130403930464
12.22130403930337
12.221304039302101
12.221304039300827
12.221304039299556
12.221304039298275
12.22130403929701
12.22130403929574
12.22130403929447
12.2213040392932
12.22130403929193
12.221304039290654
12.221304039289391
12.221304039288116
12.221304039286853
12.22130403928558
12.22130403928431
12.22130403928304
12.221304039281772
12.221304039280508
12.221304039279243
12.221304039277967
12.221304039276706
12.22130403927544
12.221304039274166
12.221304039272901
12.221304039271637
12.221304039270382
12.221304039269102
12.22130403926784
12.221304039266577
12.221304039265306
12.221304039264046
12.221304039262787
12.221304039261522
12.221304039260254
12.221304039258998
12.221304039257735
12.22130403925647
12.22130403925521
12.221304039253948
12.22130403925268
12.22130403925142
12.221304039250164
12.221304039248901
12.22130403924764
12.221304039246386
12.221304039245117
12.221304039243858
12.221304039242602
12.221304039241343
12.221304039240078
12.221304039238818
12.221304039237564
12.221304039236303
12.22130403923505
12.22130403923379
12.221304039232539
12.221304039231274
12.221304039230013
12.221304039228759
12.221304039227507
12.221304039226252
12.221304039224997
12.221304039223732
12.22130403922248
12.221304039221232
12.221304039219973
12.221304039218715
12.221304039217465
12.221304039216207
12.221304039214953
12.221304039213702
12.221304039212447
12.221304039211194
12.221304039209945
12.221304039208695
12.22130403920744
12.22130403920619
12.221304039204936
12.221304039203682
12.221304039202439
12.22130403920118
12.221304039199941
12.221304039198685
12.221304039197435
12.22130403919619
12.221304039194939
12.221304039193692
12.221304039192441
12.221304039191198
12.221304039189947
12.221304039188697
12.221304039187444
12.221304039186201
12.221304039184949
12.221304039183705
12.221304039182451
12.221304039181211
12.221304039179962
12.221304039178717
12.221304039177475
12.221304039176236
12.221304039174983
12.221304039173742
12.221304039172495
12.221304039171253
12.221304039170008
12.221304039168755
12.221304039167519
12.22130403916628
12.221304039165041
12.2213040391638
12.22130403916255
12.221304039161307
12.221304039160065
12.221304039158822
12.221304039157584
12.22130403915634
12.221304039155106
12.221304039153859
12.22130403915262
12.221304039151383
12.22130403915014
12.2213040391489
12.221304039147663
12.221304039146428
12.22130403914519
12.22130403914395
12.221304039142716
12.22130403914147
12.22130403914024
12.221304039139003
12.22130403913776
12.221304039136522
12.221304039135285
12.221304039134047
12.221304039132814
12.221304039131581
12.221304039130345
12.22130403912911
12.221304039127872
12.22130403912664
12.221304039125407
12.221304039124172
12.221304039122938
12.221304039121701
12.221304039120467
12.221304039119241
12.221304039118008
12.221304039116772
12.221304039115543
12.221304039114312
12.22130403911308
12.221304039111848
12.22130403911062
12.221304039109386
12.221304039108157
12.221304039106933
12.221304039105705
12.221304039104467
12.221304039103234
12.221304039102014
12.221304039100776
12.221304039099554
12.221304039098333
12.221304039097095
12.221304039095866
12.221304039094642
12.221304039093413
12.221304039092184
12.221304039090965
12.221304039089732
12.221304039088514
12.221304039087283
12.22130403908605
12.221304039084826
12.221304039083606
12.221304039082383
12.221304039081152
12.221304039079937
12.221304039078706
12.221304039077479
12.221304039076262
12.221304039075035
12.221304039073816
12.221304039072592
12.221304039071368
12.22130403907015
12.221304039068924
12.221304039067702
12.221304039066482
12.221304039065263
12.221304039064037
12.221304039062815
12.2213040390616
12.221304039060378
12.221304039059163
12.221304039057944
12.22130403905672
12.221304039055502
12.22130403905428
12.221304039053067
12.221304039051848
12.221304039050626
12.221304039049405
12.221304039048187
12.221304039046977
12.221304039045751
12.221304039044538
12.221304039043323
12.221304039042106
12.221304039040893
12.221304039039678
12.221304039038461
12.221304039037241
12.221304039036037
12.221304039034829
12.221304039033607
12.22130403903239
12.221304039031171
12.221304039029963
12.221304039028752
12.221304039027535
12.221304039026322
12.221304039025112
12.221304039023899

12.221304039022687
12.22130403902148
12.221304039020264
12.22130403901905
12.221304039017841
12.221304039016633
12.221304039015422
12.221304039014216
12.221304039013006
12.221304039011795
12.221304039010581
12.22130403900937
12.221304039008158
12.221304039006961
12.22130403900575
12.22130403900454
12.221304039003327
12.221304039002126
12.221304039000918
12.221304038999715
12.221304038998504
12.221304038997301
12.221304038996086
12.221304038994884
12.22130403899368
12.221304038992475
12.221304038991269
12.221304038990066
12.221304038988865
12.221304038987654
12.221304038986451
12.221304038985254
12.22130403898404
12.221304038982844
12.221304038981637
12.221304038980437
12.22130403897924
12.221304038978026
12.221304038976834
12.221304038975624
12.221304038974425
12.221304038973228
12.221304038972026
12.221304038970832
12.221304038969619
12.221304038968423
12.221304038967233
12.221304038966025
12.221304038964824
12.221304038963629
12.221304038962426
12.221304038961227
12.221304038960037
12.221304038958834
12.221304038957634
12.22130403895644
12.221304038955239
12.221304038954045
12.221304038952843
12.221304038951645
12.221304038950452
12.221304038949262
12.22130403894806
12.22130403894687
12.221304038945672
12.221304038944483
12.221304038943279
12.221304038942085
12.221304038940888
12.221304038939698
12.221304038938506
12.22130403893732
12.221304038936118
12.22130403893493
12.22130403893373
12.221304038932542
12.22130403893135
12.221304038930159
12.221304038928968
12.22130403892777
12.221304038926577
12.221304038925398
12.221304038924206
12.221304038923016
12.22130403892183
12.221304038920636
12.221304038919442
12.221304038918259
12.221304038917065
12.221304038915882
12.221304038914688
12.221304038913498
12.221304038912313
12.221304038911123
12.221304038909944
12.221304038908753
12.221304038907556
12.221304038906382
12.221304038905197
12.221304038904004
12.22130403890282
12.221304038901634
12.221304038900447
12.221304038899266
12.221304038898076
12.221304038896891
12.221304038895708
12.221304038894527
12.221304038893342
12.221304038892166
12.221304038890974
12.22130403888979
12.221304038888604
12.221304038887428
12.221304038886242
12.221304038885062
12.221304038883876
12.221304038882698
12.221304038881518
12.221304038880335
12.221304038879154
12.221304038877971
12.221304038876797
12.221304038875623
12.22130403887443
12.221304038873251
12.221304038872074
12.221304038870892
12.22130403886972
12.221304038868542
12.221304038867357
12.221304038866185
12.22130403886501
12.22130403886383
12.22130403886265
12.221304038861469
12.221304038860294
12.221304038859124
12.221304038857953
12.221304038856772
12.22130403885559
12.221304038854424
12.221304038853246
12.221304038852068
12.2213040388509
12.221304038849715
12.221304038848547
12.221304038847371
12.2213040388462
12.221304038845027
12.221304038843861
12.221304038842682
12.221304038841502
12.221304038840326
12.221304038839165
12.221304038837989
12.221304038836822
12.221304038835651
12.221304038834479
12.221304038833306
12.221304038832137
12.221304038830963
12.221304038829789
12.221304038828631
12.221304038827455
12.221304038826283
12.221304038825119
12.221304038823948
12.221304038822783
12.221304038821613
12.221304038820447
12.22130403881928
12.221304038818108
12.221304038816942
12.221304038815777
12.221304038814607
12.221304038813443
12.221304038812276
12.221304038811109
12.221304038809942
12.221304038808775
12.221304038807617
12.221304038806448
12.22130403880528
12.221304038804117
12.221304038802957
12.221304038801797
12.221304038800628
12.22130403879946
12.221304038798305
12.221304038797145
12.22130403879597
12.221304038794814
12.221304038793653
12.22130403879249
12.22130403879133
12.221304038790166
12.22130403878901
12.221304038787835
12.221304038786688
12.221304038785522
12.221304038784362
12.221304038783199
12.221304038782039
12.221304038780884
12.221304038779728
12.221304038778568
12.221304038777408
12.221304038776248
12.221304038775088
12.221304038773924
12.22130403877277
12.221304038771624
12.221304038770462
12.2213040387693
12.221304038768151
12.221304038766995
12.221304038765835
12.221304038764684
12.221304038763533
12.22130403876237
12.221304038761211
12.22130403876006
12.22130403875891
12.221304038757747
12.221304038756598
12.221304038755441
12.221304038754285
12.221304038753134
12.221304038751986
12.22130403875083
12.221304038749679
12.221304038748528
12.221304038747368
12.221304038746222
12.22130403874507
12.221304038743918
12.221304038742764
12.221304038741623
12.221304038740467
12.221304038739317
12.22130403873816
12.22130403873702
12.221304038735866
12.221304038734715
12.221304038733571
12.221304038732422
12.221304038731265
12.221304038730114
12.22130403872897
12.221304038727823
12.221304038726677
12.22130403872553
12.221304038724385
12.221304038723233
12.221304038722092
12.221304038720934
12.221304038719788
12.22130403871865
12.221304038717506
12.221304038716363
12.221304038715207
12.221304038714065
12.221304038712931
12.221304038711777
12.221304038710628
12.221304038709492
12.22130403870835
12.221304038707208
12.22130403870606
12.221304038704922
12.221304038703776
12.221304038702632
12.221304038701492
12.221304038700351
12.221304038699213
12.221304038698065
12.221304038696923
12.22130403869578
12.221304038694647
12.22130403869351
12.221304038692368
12.221304038691224
12.221304038690082
12.221304038688945
12.221304038687808
12.22130403868667
12.221304038685526
12.221304038684387
12.22130403868325
12.221304038682117
12.221304038680971
12.221304038679841
12.221304038678698
12.221304038677564
12.221304038676427
12.221304038675294
12.221304038674154
12.221304038673022
12.221304038671882
12.22130403867075
12.221304038669613
12.221304038668478
12.221304038667347
12.221304038666208
12.221304038665073
12.221304038663934
12.221304038662806
12.221304038661676
12.22130403866054
12.221304038659406
12.221304038658273
12.221304038657134
12.221304038656003
12.221304038654882
12.221304038653743
12.221304038652615
12.221304038651487
12.221304038650352
12.221304038649224
12.221304038648091
12.221304038646958
12.221304038645837
12.221304038644696
12.221304038643574
12.221304038642439
12.22130403864131
12.221304038640188
12.221304038639056
12.221304038637927
12.221304038636788
12.22130403863567
12.221304038634543
12.22130403863342
12.221304038632288
12.221304038631164
12.221304038630045
12.22130403862891
12.221304038627784
12.221304038626657
12.22130403862553
12.22130403862441
12.221304038623279
12.221304038622156
12.221304038621028
12.221304038619907
12.221304038618781
12.221304038617658
12.221304038616536
12.22130403861541
12.221304038614294
12.22130403861315
12.221304038612047
12.22130403861092
12.221304038609794
12.221304038608674
12.221304038607553
12.221304038606426
12.221304038605307
12.221304038604199
12.221304038603074
12.221304038601948
12.221304038600827
12.221304038599715
12.221304038598584
12.221304038597474
12.221304038596353
12.22130403859523
12.22130403859411
12.22130403859299
12.221304038591867
12.22130403859075
12.221304038589626
12.22130403858852
12.221304038587405
12.221304038586293
12.221304038585169
12.221304038584048
12.221304038582934
12.221304038581819
12.221304038580705
12.221304038579591
12.22130403857847
12.221304038577358
12.221304038576244
12.221304038575118
12.221304038574019
12.2213040385729
12.221304038571786
12.221304038570672
12.221304038569556
12.221304038568448
12.221304038567329
12.221304038566222
12.221304038565112
12.221304038563986
12.22130403856288
12.221304038561764
12.221304038560664
12.221304038559543
12.221304038558433
12.221304038557328
12.221304038556216
12.22130403855511
12.221304038553995
12.221304038552885
12.221304038551782
12.221304038550661
12.221304038549547
12.221304038548448
12.22130403854734
12.221304038546226
12.221304038545123
12.221304038544014
12.221304038542906
12.221304038541799
12.221304038540694
12.22130403853958
12.221304038538477
12.221304038537376
12.221304038536262
12.221304038535159
12.221304038534054
12.221304038532951
12.221304038531844
12.221304038530738
12.22130403852963
12.221304038528537
12.221304038527421
12.221304038526322
12.221304038525222
12.22130403852411
12.221304038523009
12.22130403852191
12.221304038520806
12.221304038519698
12.2213040385186
12.221304038517497
12.22130403851639
12.22130403851529
12.221304038514193
12.221304038513088
12.221304038511988
12.221304038510883
12.221304038509784
12.221304038508688
12.221304038507592
12.22130403850649
12.221304038505394
12.22130403850429
12.221304038503192
12.22130403850209
12.221304038500984
12.221304038499895
12.221304038498802
12.2213040384977
12.2213040384966
12.2213040384955
12.22130403849441
12.221304038493306
12.22130403849221
12.221304038491112
12.221304038490008
12.221304038488924
12.221304038487826
12.221304038486734
12.221304038485638
12.221304038484543
12.221304038483444
12.221304038482355
12.221304038481259
12.22130403848016
12.22130403847907
12.221304038477976
12.221304038476886
12.221304038475788
12.221304038474697
12.2213040384736
12.221304038472505
12.221304038471416
12.221304038470326
12.221304038469231
12.221304038468151
12.22130403846705
12.221304038465961
12.221304038464876
12.221304038463778
12.221304038462687
12.221304038461598
12.22130403846051
12.221304038459424
12.22130403845833
12.221304038457232
12.221304038456157
12.221304038455061
12.22130403845397
12.22130403845289
12.221304038451803
12.221304038450713
12.221304038449617
12.221304038448535
12.221304038447451
12.221304038446366
12.221304038445277
12.221304038444185
12.221304038443105
12.221304038442021
12.221304038440932

12.221304038439847
12.221304038438765
12.221304038437681
12.221304038436584
12.221304038435505
12.221304038434429
12.221304038433338
12.22130403843225
12.221304038431168
12.22130403843009
12.221304038429007
12.221304038427927
12.221304038426839
12.221304038425753
12.221304038424673
12.221304038423591
12.221304038422518
12.221304038421431
12.221304038420353
12.221304038419271
12.221304038418197
12.221304038417108
12.221304038416024
12.221304038414951
12.221304038413862
12.22130403841279
12.221304038411708
12.221304038410633
12.221304038409553
12.22130403840848
12.221304038407395
12.221304038406316
12.221304038405238
12.221304038404169
12.221304038403085
12.221304038402012
12.22130403840093
12.221304038399854
12.221304038398774
12.221304038397703
12.221304038396626
12.221304038395546
12.221304038394475
12.221304038393406
12.221304038392327
12.221304038391242
12.221304038390176
12.2213040383891
12.221304038388023
12.221304038386952
12.221304038385883
12.221304038384812
12.22130403838373
12.221304038382662
12.221304038381591
12.221304038380511
12.221304038379442
12.221304038378372
12.2213040383773
12.221304038376225
12.221304038375155
12.221304038374083
12.221304038373013
12.221304038371942
12.221304038370867
12.221304038369807
12.221304038368725
12.221304038367668
12.221304038366588
12.221304038365531
12.221304038364451
12.221304038363384
12.221304038362316
12.221304038361252
12.221304038360188
12.221304038359113
12.22130403835804
12.221304038356982
12.221304038355914
12.221304038354848
12.22130403835378
12.22130403835271
12.221304038351644
12.221304038350583
12.22130403834951
12.221304038348444
12.22130403834738
12.221304038346318
12.221304038345258
12.221304038344192
12.221304038343126
12.22130403834206
12.221304038340998
12.221304038339936
12.221304038338872
12.221304038337811
12.221304038336747
12.221304038335683
12.221304038334623
12.221304038333553
12.221304038332494
12.221304038331432
12.221304038330373
12.221304038329315
12.221304038328242
12.221304038327181
12.221304038326128
12.221304038325062
12.221304038324005
12.221304038322943
12.22130403832189
12.22130403832083
12.22130403831977
12.221304038318708
12.221304038317653
12.221304038316589
12.221304038315534
12.221304038314475
12.221304038313413
12.22130403831236
12.2213040383113
12.221304038310242
12.221304038309187
12.221304038308128
12.221304038307077
12.221304038306016
12.221304038304968
12.221304038303906
12.221304038302852
12.221304038301799
12.221304038300735
12.221304038299687
12.221304038298632
12.221304038297578
12.22130403829652
12.221304038295472
12.221304038294413
12.221304038293361
12.221304038292313
12.22130403829125
12.221304038290201
12.22130403828915
12.221304038288096
12.221304038287043
12.22130403828599
12.221304038284943
12.22130403828388
12.221304038282836
12.221304038281792
12.221304038280735
12.221304038279685
12.22130403827863
12.221304038277584
12.221304038276537
12.221304038275475
12.221304038274436
12.22130403827339
12.22130403827234
12.221304038271294
12.221304038270235
12.221304038269192
12.221304038268148
12.221304038267098
12.221304038266046
12.221304038265005
12.221304038263954
12.221304038262906
12.221304038261863
12.221304038260813
12.221304038259772
12.221304038258724
12.221304038257676
12.221304038256623
12.221304038255585
12.221304038254534
12.221304038253495
12.221304038252452
12.221304038251409
12.221304038250366
12.22130403824932
12.221304038248274
12.221304038247224
12.221304038246185
12.221304038245146
12.2213040382441
12.22130403824306
12.221304038242017
12.221304038240977
12.221304038239927
12.221304038238886
12.22130403823785
12.221304038236802
12.221304038235758
12.221304038234724
12.221304038233683
12.22130403823264
12.221304038231604
12.221304038230558
12.221304038229523
12.221304038228483
12.22130403822745
12.221304038226403
12.221304038225371
12.221304038224329
12.221304038223295
12.221304038222256
12.221304038221213
12.221304038220186
12.22130403821914
12.221304038218099
12.221304038217074
12.221304038216028
12.221304038214996
12.221304038213951
12.221304038212919
12.221304038211885
12.221304038210851
12.22130403820982
12.221304038208773
12.22130403820775
12.221304038206712
12.221304038205675
12.22130403820464
12.221304038203606
12.221304038202573
12.221304038201534
12.221304038200508
12.221304038199472
12.221304038198435
12.2213040381974
12.221304038196374
12.22130403819534
12.221304038194306
12.22130403819328
12.22130403819225
12.221304038191217
12.221304038190178
12.221304038189158
12.221304038188125
12.221304038187089
12.22130403818606
12.221304038185037
12.221304038184
12.221304038182973
12.221304038181941
12.221304038180913
12.22130403817989
12.221304038178854
12.221304038177829
12.221304038176797
12.221304038175774
12.221304038174738
12.221304038173713
12.22130403817269
12.221304038171661
12.221304038170635
12.221304038169611
12.221304038168583
12.221304038167558
12.22130403816653
12.221304038165504
12.221304038164481
12.221304038163447
12.221304038162424
12.221304038161405
12.221304038160381
12.221304038159357
12.221304038158321
12.221304038157308
12.221304038156282
12.221304038155255
12.221304038154237
12.221304038153209
12.221304038152184
12.221304038151166
12.221304038150144
12.221304038149114
12.221304038148098
12.22130403814708
12.221304038146048
12.22130403814503
12.221304038144014
12.22130403814299
12.221304038141971
12.221304038140946
12.22130403813993
12.22130403813891
12.221304038137895
12.221304038136871
12.221304038135854
12.221304038134825
12.221304038133812
12.221304038132791
12.221304038131779
12.22130403813076
12.221304038129748
12.221304038128723
12.221304038127702
12.22130403812669
12.22130403812567
12.221304038124655
12.22130403812364
12.221304038122621
12.221304038121607
12.221304038120593
12.22130403811957
12.221304038118557
12.221304038117543
12.221304038116527
12.221304038115509
12.221304038114496
12.221304038113475
12.221304038112462
12.221304038111455
12.221304038110437
12.221304038109423
12.221304038108414
12.221304038107405
12.221304038106384
12.22130403810538
12.221304038104362
12.221304038103346
12.221304038102334
12.221304038101323
12.221304038100314
12.221304038099309
12.22130403809829
12.221304038097287
12.221304038096271
12.221304038095262
12.221304038094248
12.22130403809323
12.221304038092226
12.221304038091217
12.221304038090212
12.221304038089198
12.221304038088196
12.221304038087185
12.221304038086172
12.221304038085165
12.22130403808416
12.22130403808315
12.221304038082135
12.221304038081131
12.221304038080131
12.221304038079122
12.221304038078108
12.221304038077099
12.221304038076106
12.221304038075091
12.221304038074088
12.22130403807308
12.221304038072077
12.221304038071073
12.221304038070066
12.221304038069059
12.221304038068062
12.221304038067052
12.221304038066046
12.221304038065036
12.221304038064035
12.221304038063039
12.221304038062035
12.221304038061024
12.221304038060028
12.221304038059023
12.221304038058019
12.221304038057022
12.221304038056017
12.22130403805502
12.22130403805402
12.221304038053008
12.221304038052013
12.221304038051017
12.221304038050015
12.221304038049013
12.221304038048007
12.221304038047005
12.221304038046014
12.22130403804501
12.22130403804401
12.221304038043014
12.221304038042012
12.221304038041009
12.221304038040016
12.22130403803901
12.221304038038024
12.22130403803702
12.221304038036026
12.221304038035026
12.221304038034027
12.221304038033026
12.22130403803204
12.221304038031034
12.221304038030045
12.221304038029047
12.221304038028041
12.221304038027052
12.221304038026062
12.221304038025062
12.221304038024073
12.221304038023074
12.221304038022074
12.221304038021083
12.221304038020092
12.221304038019097
12.221304038018099
12.221304038017108
12.22130403801612
12.221304038015123
12.221304038014136
12.22130403801314
12.221304038012146
12.221304038011146
12.221304038010162
12.221304038009164
12.221304038008176
12.221304038007178
12.22130403800619
12.221304038005197
12.221304038004213
12.221304038003224
12.221304038002232
12.221304038001236
12.221304038000254
12.22130403799927
12.221304037998273
12.221304037997289
12.221304037996296
12.221304037995305
12.221304037994319
12.221304037993324
12.221304037992343
12.22130403799135
12.221304037990366
12.22130403798938
12.221304037988386
12.221304037987403
12.22130403798641
12.22130403798543
12.22130403798444
12.221304037983451
12.221304037982465
12.221304037981483
12.221304037980504
12.221304037979511
12.221304037978529
12.221304037977545
12.221304037976555
12.221304037975571
12.22130403797459
12.221304037973603
12.22130403797262
12.221304037971644
12.221304037970652
12.221304037969666
12.221304037968688
12.2213040379677
12.221304037966721
12.221304037965734
12.221304037964755
12.221304037963774
12.221304037962794
12.22130403796181
12.221304037960836
12.221304037959847
12.221304037958866
12.22130403795788
12.221304037956916
12.22130403795592
12.221304037954946
12.221304037953967
12.221304037952986
12.22130403795201
12.221304037951027
12.221304037950047
12.221304037949075
12.22130403794809
12.221304037947117
12.221304037946133
12.221304037945163
12.221304037944186
12.221304037943213
12.221304037942227
12.221304037941248
12.22130403794027
12.221304037939294
12.221304037938326
12.221304037937339
12.221304037936358
12.221304037935388
12.221304037934416
12.221304037933436
12.221304037932468
12.221304037931489
12.221304037930514
12.221304037929544
12.221304037928567
12.221304037927599
12.221304037926616
12.221304037925643
12.221304037924677
12.221304037923693
12.221304037922723
12.221304037921755
12.221304037920778
12.2213040379198
12.221304037918832
12.221304037917866
12.221304037916891
12.221304037915916
12.221304037914948
12.22130403791397
12.221304037913
12.221304037912034
12.221304037911064
12.221304037910093
12.221304037909123
12.221304037908151
12.22130403790718
12.221304037906217
12.221304037905245
12.221304037904273
12.22130403790331
12.221304037902335
12.221304037901369
12.2213040379004
12.221304037899433
12.221304037898465
12.221304037897491
12.221304037896534
12.221304037895564
12.221304037894598
12.221304037893626
12.221304037892665
12.221304037891699
12.22130403789073
12.221304037889764
12.221304037888801
12.221304037887833
12.22130403788687
12.221304037885902
12.221304037884936
12.221304037883971
12.221304037883007
12.221304037882046
12.221304037881076
12.221304037880113
12.221304037879149
12.221304037878193
12.221304037877227

12.221304037876262
12.221304037875303
12.22130403787434
12.221304037873377
12.221304037872413
12.221304037871455
12.221304037870494
12.221304037869537
12.221304037868569
12.221304037867608
12.221304037866648
12.22130403786568
12.221304037864718
12.221304037863767
12.221304037862806
12.221304037861847
12.221304037860886
12.221304037859927
12.221304037858964
12.221304037858014
12.22130403785704
12.221304037856086
12.221304037855125
12.221304037854175
12.22130403785321
12.221304037852258
12.221304037851302
12.221304037850343
12.22130403784939
12.221304037848428
12.221304037847469
12.221304037846512
12.221304037845554
12.221304037844604
12.221304037843645
12.221304037842682
12.221304037841731
12.221304037840781
12.221304037839818
12.221304037838872
12.221304037837918
12.221304037836955
12.221304037836006
12.221304037835054
12.221304037834097
12.221304037833148
12.221304037832189
12.221304037831235
12.22130403783028
12.221304037829327
12.221304037828377
12.221304037827425
12.221304037826469
12.221304037825522
12.221304037824567
12.221304037823618
12.22130403782267
12.22130403782171
12.221304037820778
12.221304037819811
12.221304037818866
12.221304037817916
12.221304037816962
12.221304037816017
12.22130403781506
12.221304037814118
12.221304037813164
12.221304037812217
12.221304037811269
12.221304037810324
12.221304037809372
12.221304037808427
12.221304037807469
12.22130403780653
12.221304037805576
12.221304037804634
12.221304037803685
12.221304037802735
12.221304037801794
12.22130403780085
12.2213040377999
12.221304037798944
12.221304037798005
12.221304037797061
12.221304037796115
12.221304037795168
12.221304037794221
12.221304037793278
12.221304037792338
12.221304037791388
12.221304037790446
12.221304037789501
12.221304037788554
12.221304037787608
12.221304037786666
12.221304037785721
12.221304037784787
12.221304037783838
12.221304037782899
12.221304037781945
12.221304037781012
12.221304037780065
12.221304037779129
12.221304037778184
12.221304037777244
12.221304037776301
12.221304037775365
12.221304037774425
12.221304037773479
12.221304037772537
12.221304037771601
12.22130403777066
12.221304037769723
12.221304037768776
12.221304037767837
12.221304037766899
12.221304037765961
12.221304037765027
12.221304037764092
12.221304037763145
12.221304037762208
12.221304037761273
12.221304037760335
12.221304037759397
12.221304037758456
12.221304037757518
12.221304037756578
12.221304037755646
12.221304037754708
12.221304037753775
12.22130403775283
12.221304037751898
12.221304037750965
12.221304037750025
12.221304037749096
12.221304037748165
12.221304037747226
12.22130403774629
12.221304037745364
12.221304037744419
12.221304037743487
12.221304037742552
12.221304037741616
12.221304037740685
12.221304037739754
12.221304037738818
12.221304037737884
12.221304037736957
12.22130403773602
12.221304037735088
12.221304037734155
12.221304037733221
12.221304037732294
12.221304037731361
12.22130403773043
12.221304037729494
12.221304037728565
12.221304037727634
12.221304037726703
12.22130403772578
12.22130403772484
12.221304037723922
12.22130403772298
12.221304037722057
12.221304037721126
12.221304037720198
12.221304037719273
12.221304037718339
12.221304037717413
12.221304037716486
12.221304037715559
12.221304037714624
12.221304037713706
12.221304037712777
12.221304037711842
12.221304037710924
12.221304037709993
12.22130403770906
12.221304037708135
12.221304037707212
12.221304037706286
12.221304037705366
12.221304037704435
12.221304037703502
12.221304037702588
12.221304037701659
12.221304037700733
12.221304037699808
12.221304037698884
12.221304037697957
12.221304037697035
12.221304037696116
12.221304037695187
12.221304037694264
12.221304037693347
12.221304037692416
12.2213040376915
12.221304037690581
12.22130403768965
12.22130403768873
12.221304037687807
12.221304037686888
12.221304037685963
12.221304037685044
12.221304037684122
12.221304037683199
12.221304037682279
12.221304037681357
12.221304037680435
12.22130403767951
12.221304037678594
12.221304037677674
12.221304037676763
12.22130403767584
12.221304037674917
12.221304037673999
12.22130403767308
12.22130403767216
12.221304037671242
12.221304037670327
12.221304037669409
12.221304037668487
12.22130403766757
12.22130403766665
12.221304037665742
12.22130403766482
12.221304037663902
12.221304037662987
12.22130403766207
12.221304037661149
12.221304037660243
12.221304037659324
12.221304037658411
12.221304037657491
12.221304037656575
12.221304037655663
12.221304037654743
12.221304037653832
12.221304037652915
12.221304037652004
12.221304037651088
12.221304037650174
12.221304037649254
12.221304037648347
12.221304037647426
12.221304037646524
12.221304037645606
12.221304037644693
12.221304037643776
12.221304037642874
12.221304037641959
12.221304037641042
12.221304037640131
12.221304037639218
12.221304037638305
12.221304037637402
12.221304037636491
12.221304037635571
12.221304037634672
12.221304037633763
12.22130403763285
12.221304037631933
12.22130403763102
12.221304037630118
12.221304037629206
12.221304037628297
12.22130403762739
12.221304037626476
12.221304037625568
12.22130403762467
12.221304037623751
12.221304037622843
12.221304037621934
12.221304037621033
12.221304037620126
12.22130403761922
12.221304037618305
12.221304037617408
12.221304037616498
12.221304037615583
12.221304037614688
12.221304037613779
12.221304037612871
12.221304037611965
12.22130403761106
12.221304037610157
12.22130403760925
12.22130403760835
12.22130403760744
12.221304037606538
12.22130403760563
12.221304037604728
12.221304037603831
12.221304037602923
12.221304037602017
12.221304037601113
12.221304037600216
12.221304037599305
12.221304037598406
12.221304037597502
12.221304037596605
12.221304037595694
12.221304037594798
12.221304037593894
12.221304037592995
12.221304037592088
12.2213040375912
12.221304037590295
12.221304037589388
12.221304037588485
12.221304037587586
12.221304037586693
12.221304037585789
12.221304037584886
12.221304037583991
12.221304037583094
12.221304037582193
12.221304037581296
12.22130403758039
12.221304037579497
12.221304037578594
12.221304037577703
12.221304037576797
12.221304037575898
12.221304037575006
12.22130403757412
12.22130403757321
12.221304037572315
12.221304037571413
12.221304037570516
12.221304037569622
12.221304037568729
12.221304037567833
12.221304037566934
12.221304037566046
12.221304037565147
12.221304037564252
12.221304037563362
12.221304037562462
12.221304037561568
12.22130403756067
12.221304037559777
12.221304037558884
12.221304037557989
12.221304037557095
12.221304037556209
12.221304037555308
12.221304037554415
12.221304037553528
12.221304037552626
12.221304037551736
12.221304037550844
12.221304037549952
12.221304037549059
12.221304037548169
12.221304037547275
12.221304037546389
12.221304037545499
12.221304037544606
12.22130403754371
12.221304037542819
12.221304037541934
12.22130403754104
12.221304037540152
12.221304037539262
12.221304037538378
12.221304037537488
12.221304037536596
12.221304037535706
12.22130403753482
12.221304037533923
12.221304037533045
12.22130403753215
12.221304037531254
12.221304037530373
12.221304037529485
12.221304037528595
12.221304037527718
12.221304037526824
12.221304037525929
12.22130403752505
12.22130403752416
12.22130403752328
12.22130403752239
12.221304037521502
12.221304037520623
12.221304037519737
12.22130403751885
12.221304037517966
12.221304037517077
12.221304037516193
12.221304037515308
12.221304037514422
12.221304037513537
12.221304037512658
12.221304037511771
12.22130403751089
12.221304037509999
12.22130403750912
12.221304037508235
12.221304037507355
12.221304037506474
12.221304037505595
12.221304037504712
12.221304037503824
12.221304037502943
12.22130403750206
12.221304037501179
12.22130403750029
12.221304037499412
12.221304037498536
12.221304037497653
12.221304037496775
12.221304037495894
12.221304037495019
12.221304037494138
12.221304037493258
12.221304037492372
12.221304037491496
12.221304037490619
12.221304037489741
12.221304037488862
12.22130403748798
12.221304037487107
12.221304037486226
12.221304037485341
12.221304037484467
12.221304037483588
12.221304037482716
12.22130403748183
12.221304037480964
12.221304037480088
12.221304037479209
12.22130403747833
12.221304037477461
12.221304037476584
12.221304037475695
12.221304037474823
12.221304037473939
12.221304037473072
12.221304037472196
12.221304037471327
12.221304037470443
12.221304037469567
12.221304037468702
12.221304037467817
12.221304037466947
12.221304037466073
12.221304037465195
12.221304037464327
12.221304037463453
12.221304037462579
12.2213040374617
12.221304037460836
12.221304037459964
12.22130403745909
12.221304037458223
12.221304037457346
12.221304037456477
12.221304037455598
12.221304037454724
12.221304037453855
12.221304037452986
12.221304037452121
12.22130403745125
12.221304037450377
12.221304037449507
12.22130403744863
12.221304037447764
12.221304037446895
12.22130403744603
12.221304037445154
12.221304037444286
12.221304037443415
12.221304037442547
12.22130403744168
12.221304037440817
12.221304037439946
12.221304037439076
12.221304037438209
12.221304037437344
12.22130403743647
12.221304037435605
12.221304037434736
12.221304037433866
12.221304037433008
12.221304037432136
12.221304037431272
12.221304037430404
12.221304037429537
12.221304037428673
12.221304037427807
12.221304037426947
12.221304037426082
12.221304037425213
12.221304037424348
12.221304037423481
12.221304037422623
12.221304037421753
12.221304037420888
12.221304037420037
12.221304037419161
12.221304037418305
12.221304037417436
12.221304037416568
12.221304037415713
12.221304037414848
12.221304037413987
12.22130403741312
12.221304037412258
12.221304037411395
12.221304037410537
12.221304037409668
12.221304037408814
12.221304037407945
12.221304037407085
12.221304037406224
12.221304037405371
12.221304037404503
12.221304037403646
12.221304037402783
12.221304037401932
12.221304037401064
12.221304037400213
12.221304037399346
12.221304037398488
12.221304037397628
12.221304037396772
12.221304037395917
12.22130403739505
12.221304037394194
12.221304037393331
12.221304037392478
12.22130403739162
12.221304037390766
12.221304037389912
12.221304037389045
12.221304037388192
12.221304037387334
12.221304037386476
12.221304037385622
12.221304037384769
12.22130403738391
12.221304037383057
12.221304037382202
12.22130403738134
12.221304037380486
12.22130403737963
12.221304037378776
12.221304037377921
12.22130403737707
12.221304037376214
12.221304037375356
12.221304037374509
12.221304037373647
12.221304037372796
12.221304037371942
12.221304037371091
12.221304037370233
12.221304037369382
12.221304037368528
12.221304037367682
12.22130403736682
12.221304037365972
12.22130403736512
12.221304037364275
12.221304037363417
12.221304037362568
12.221304037361719
12.221304037360857
12.221304037360008
12.221304037359165
12.221304037358312
12.221304037357465
12.221304037356605
12.221304037355761
12.221304037354908

12.221304037354058
12.221304037353217
12.221304037352366
12.221304037351514
12.22130403735067
12.221304037349814
12.221304037348965
12.221304037348123
12.221304037347272
12.22130403734642
12.221304037345565
12.221304037344733
12.221304037343875
12.221304037343033
12.22130403734218
12.221304037341339
12.221304037340492
12.221304037339642
12.2213040373388
12.221304037337953
12.221304037337116
12.221304037336267
12.221304037335416
12.221304037334571
12.221304037333722
12.221304037332878
12.221304037332038
12.221304037331196
12.221304037330341
12.22130403732951
12.221304037328652
12.22130403732781
12.221304037326973
12.221304037326137
12.221304037325282
12.22130403732444
12.221304037323597
12.221304037322753
12.221304037321904
12.221304037321065
12.221304037320227
12.221304037319381
12.221304037318546
12.221304037317699
12.221304037316854
12.221304037316017
12.221304037315173
12.22130403731434
12.221304037313496
12.221304037312656
12.221304037311812
12.221304037310972
12.22130403731013
12.221304037309288
12.221304037308458
12.221304037307613
12.221304037306776
12.221304037305936
12.2213040373051
12.221304037304261
12.221304037303423
12.221304037302575
12.22130403730174
12.221304037300909
12.221304037300067
12.221304037299229
12.221304037298395
12.22130403729756
12.221304037296719
12.221304037295877
12.221304037295047
12.221304037294205
12.221304037293377
12.221304037292535
12.221304037291706
12.221304037290864
12.22130403729003
12.221304037289194
12.221304037288366
12.221304037287515
12.221304037286686
12.221304037285847
12.221304037285018
12.221304037284183
12.221304037283344
12.221304037282513
12.221304037281682
12.221304037280847
12.221304037280014
12.221304037279177
12.221304037278344
12.22130403727751
12.221304037276683
12.221304037275852
12.221304037275015
12.221304037274182
12.22130403727335
12.221304037272516
12.221304037271688
12.221304037270858
12.221304037270029
12.221304037269196
12.221304037268359
12.221304037267537
12.2213040372667
12.221304037265874
12.221304037265044
12.221304037264211
12.221304037263382
12.221304037262556
12.22130403726172
12.221304037260897
12.221304037260063
12.221304037259236
12.221304037258394
12.221304037257578
12.221304037256745
12.221304037255917
12.22130403725509
12.22130403725426
12.221304037253432
12.221304037252613
12.221304037251777
12.221304037250949
12.221304037250128
12.221304037249302
12.221304037248473
12.221304037247652
12.221304037246826
12.221304037245991
12.221304037245167
12.221304037244343
12.221304037243511
12.221304037242689
12.22130403724186
12.221304037241039
12.22130403724021
12.221304037239387
12.221304037238566
12.221304037237738
12.221304037236923
12.221304037236091
12.221304037235265
12.221304037234447
12.221304037233617
12.221304037232798
12.221304037231976
12.221304037231151
12.221304037230338
12.221304037229501
12.221304037228684
12.221304037227865
12.22130403722704
12.221304037226222
12.2213040372254
12.221304037224577
12.221304037223756
12.221304037222936
12.221304037222113
12.22130403722129
12.221304037220467
12.221304037219648
12.221304037218827
12.221304037218008
12.221304037217187
12.221304037216374
12.221304037215555
12.22130403721473
12.221304037213917
12.221304037213088
12.221304037212265
12.221304037211457
12.221304037210631
12.22130403720981
12.221304037209007
12.221304037208187
12.221304037207366
12.22130403720654
12.221304037205732
12.221304037204911
12.221304037204101
12.22130403720328
12.22130403720246
12.22130403720164
12.221304037200838
12.221304037200012
12.221304037199197
12.22130403719838
12.221304037197562
12.221304037196758
12.221304037195935
12.221304037195114
12.221304037194304
12.221304037193494
12.221304037192683
12.221304037191864
12.221304037191043
12.221304037190226
12.221304037189423
12.2213040371886
12.221304037187792
12.221304037186979
12.221304037186163
12.221304037185348
12.221304037184538
12.221304037183728
12.221304037182918
12.221304037182101
12.221304037181286
12.221304037180476
12.22130403717967
12.221304037178864
12.221304037178042
12.221304037177227
12.221304037176418
12.221304037175608
12.221304037174805
12.22130403717399
12.221304037173176
12.221304037172361
12.221304037171556
12.221304037170745
12.221304037169942
12.221304037169125
12.22130403716832
12.22130403716751
12.221304037166709
12.22130403716589
12.221304037165085
12.221304037164266
12.221304037163476
12.22130403716266
12.221304037161852
12.221304037161046
12.221304037160243
12.221304037159426
12.221304037158623
12.221304037157813
12.221304037157006
12.221304037156202
12.221304037155395
12.221304037154589
12.221304037153779
12.221304037152978
12.221304037152168
12.22130403715136
12.22130403715056
12.221304037149757
12.22130403714895
12.22130403714815
12.221304037147336
12.221304037146531
12.221304037145725
12.221304037144925
12.221304037144122
12.221304037143325
12.221304037142513
12.22130403714171
12.221304037140905
12.221304037140104
12.221304037139303
12.2213040371385
12.221304037137694
12.221304037136893
12.221304037136086
12.221304037135296
12.221304037134493
12.22130403713369
12.22130403713288
12.22130403713208
12.221304037131285
12.221304037130475
12.221304037129677
12.221304037128878
12.221304037128071
12.22130403712728
12.221304037126473
12.221304037125684
12.221304037124876
12.22130403712408
12.221304037123275
12.221304037122477
12.221304037121676
12.221304037120875
12.221304037120081
12.221304037119289
12.221304037118482
12.221304037117688
12.221304037116886
12.221304037116088
12.221304037115297
12.22130403711449
12.221304037113695
12.221304037112905
12.2213040371121
12.22130403711131
12.221304037110508
12.221304037109709
12.221304037108915
12.22130403710812
12.221304037107316
12.221304037106528
12.221304037105734
12.221304037104932
12.221304037104138
12.221304037103351
12.221304037102552
12.221304037101762
12.221304037100962
12.22130403710017
12.221304037099376
12.221304037098578
12.22130403709778
12.22130403709699
12.221304037096196
12.221304037095402
12.221304037094603
12.221304037093816
12.221304037093024
12.221304037092228
12.221304037091443
12.22130403709064
12.221304037089858
12.221304037089059
12.221304037088268
12.22130403708748
12.22130403708669
12.221304037085899
12.221304037085114
12.221304037084309
12.221304037083517
12.22130403708273
12.221304037081937
12.22130403708115
12.221304037080365
12.221304037079571
12.221304037078774
12.22130403707799
12.221304037077209
12.221304037076413
12.221304037075617
12.221304037074827
12.221304037074043
12.221304037073256
12.221304037072471
12.221304037071679
12.221304037070887
12.221304037070105
12.221304037069311
12.22130403706852
12.221304037067743
12.22130403706695
12.22130403706616
12.221304037065376
12.221304037064586
12.221304037063808
12.221304037063025
12.221304037062225
12.221304037061449
12.221304037060658
12.221304037059868
12.221304037059086
12.221304037058307
12.22130403705752
12.22130403705673
12.22130403705595
12.221304037055168
12.221304037054379
12.221304037053597
12.221304037052807
12.221304037052027
12.22130403705124
12.221304037050462
12.221304037049673
12.221304037048887
12.221304037048116
12.221304037047323
12.221304037046542
12.221304037045767
12.221304037044979
12.221304037044195
12.22130403704341
12.221304037042632
12.221304037041852
12.221304037041065
12.221304037040289
12.221304037039502
12.221304037038728
12.221304037037944
12.22130403703716
12.221304037036377
12.221304037035598
12.221304037034823
12.22130403703404
12.221304037033264
12.22130403703248
12.221304037031699
12.221304037030919
12.221304037030146
12.22130403702936
12.221304037028581
12.221304037027807
12.221304037027023
12.221304037026256
12.221304037025464
12.221304037024687
12.221304037023915
12.221304037023135
12.22130403702236
12.221304037021575
12.221304037020804
12.221304037020026
12.221304037019246
12.221304037018472
12.221304037017697
12.221304037016923
12.221304037016148
12.221304037015368
12.221304037014589
12.221304037013816
12.221304037013038
12.221304037012262
12.221304037011492
12.221304037010714
12.221304037009945
12.22130403700916
12.22130403700839
12.221304037007611
12.221304037006837
12.221304037006064
12.221304037005293
12.221304037004517
12.22130403700375
12.221304037002973
12.221304037002197
12.221304037001431
12.221304037000657
12.221304036999879
12.221304036999108
12.221304036998337
12.221304036997559
12.221304036996788
12.221304036996019
12.221304036995242
12.221304036994479
12.221304036993706
12.221304036992933
12.221304036992166
12.22130403699139
12.221304036990622
12.221304036989846
12.221304036989077
12.22130403698831
12.221304036987544
12.22130403698677
12.221304036986002
12.22130403698523
12.22130403698446
12.221304036983694
12.221304036982927
12.221304036982152
12.221304036981387
12.22130403698061
12.221304036979852
12.221304036979083
12.221304036978312
12.221304036977548
12.221304036976779
12.221304036976012
12.221304036975239
12.221304036974473
12.221304036973702
12.221304036972931
12.221304036972176
12.221304036971404
12.22130403697064
12.221304036969876
12.22130403696911
12.221304036968343
12.221304036967574
12.221304036966803
12.22130403696605
12.221304036965286
12.221304036964515
12.221304036963753
12.221304036962987
12.221304036962223
12.221304036961458
12.221304036960692
12.221304036959928
12.221304036959172
12.221304036958404
12.221304036957644
12.221304036956878
12.221304036956113
12.221304036955356
12.221304036954587
12.221304036953821
12.221304036953054
12.221304036952304
12.221304036951535
12.221304036950773
12.221304036950011
12.221304036949252
12.221304036948483
12.221304036947725
12.221304036946972

12.221304036946206
12.221304036945446
12.221304036944684
12.221304036943916
12.221304036943158
12.2213040369424
12.221304036941644
12.221304036940882
12.22130403694012
12.221304036939362
12.221304036938605
12.221304036937841
12.221304036937084
12.22130403693633
12.221304036935571
12.221304036934805
12.221304036934045
12.221304036933288
12.221304036932535
12.221304036931787
12.221304036931008
12.221304036930258
12.221304036929503
12.22130403692875
12.221304036927984
12.221304036927235
12.221304036926476
12.22130403692572
12.221304036924952
12.221304036924202
12.221304036923447
12.221304036922694
12.221304036921936
12.221304036921175
12.221304036920422
12.221304036919673
12.221304036918907
12.221304036918161
12.221304036917408
12.221304036916655
12.221304036915889
12.221304036915148
12.22130403691438
12.221304036913626
12.221304036912878
12.221304036912123
12.221304036911375
12.221304036910622
12.221304036909865
12.22130403690911
12.221304036908357
12.221304036907611
12.22130403690685
12.221304036906105
12.221304036905343
12.2213040369046
12.221304036903842
12.221304036903096
12.221304036902339
12.221304036901595
12.221304036900845
12.22130403690009
12.221304036899342
12.221304036898589
12.22130403689784
12.221304036897086
12.221304036896337
12.221304036895589
12.221304036894836
12.221304036894088
12.22130403689334
12.221304036892585
12.221304036891844
12.221304036891087
12.221304036890347
12.221304036889588
12.221304036888839
12.221304036888094
12.221304036887348
12.221304036886604
12.221304036885854
12.221304036885098
12.221304036884359
12.221304036883609
12.221304036882856
12.221304036882112
12.221304036881367
12.22130403688062
12.221304036879873
12.221304036879122
12.221304036878381
12.221304036877635
12.221304036876887
12.221304036876143
12.221304036875397
12.221304036874653
12.221304036873905
12.221304036873159
12.221304036872414
12.221304036871674
12.221304036870919
12.221304036870182
12.221304036869439
12.22130403686869
12.221304036867945
12.221304036867211
12.221304036866453
12.221304036865714
12.221304036864975
12.221304036864233
12.221304036863486
12.221304036862737
12.221304036862003
12.22130403686126
12.221304036860518
12.221304036859765
12.221304036859037
12.22130403685829
12.22130403685755
12.221304036856802
12.221304036856063
12.221304036855319
12.221304036854587
12.221304036853837
12.221304036853098
12.221304036852361
12.221304036851617
12.221304036850885
12.221304036850137
12.221304036849398
12.221304036848665
12.221304036847917
12.221304036847181
12.221304036846437
12.221304036845702
12.221304036844955
12.221304036844222
12.22130403684348
12.221304036842746
12.221304036842003
12.22130403684127
12.22130403684053
12.221304036839795
12.221304036839054
12.221304036838315
12.221304036837576
12.221304036836836
12.221304036836102
12.221304036835363
12.221304036834622
12.22130403683389
12.221304036833155
12.22130403683242
12.221304036831683
12.221304036830944
12.221304036830215
12.221304036829473
12.22130403682874
12.221304036828007
12.221304036827272
12.221304036826533
12.221304036825803
12.221304036825066
12.221304036824332
12.2213040368236
12.221304036822856
12.221304036822122
12.221304036821394
12.221304036820658
12.221304036819923
12.221304036819193
12.221304036818465
12.221304036817719
12.221304036816997
12.221304036816253
12.221304036815532
12.221304036814796
12.22130403681406
12.22130403681333
12.221304036812603
12.22130403681187
12.221304036811132
12.221304036810404
12.221304036809675
12.221304036808945
12.22130403680821
12.221304036807478
12.22130403680674
12.221304036806018
12.221304036805291
12.221304036804552
12.22130403680383
12.221304036803092
12.221304036802366
12.221304036801639
12.221304036800905
12.221304036800175
12.22130403679945
12.221304036798719
12.221304036797987
12.221304036797262
12.221304036796528
12.221304036795804
12.22130403679508
12.221304036794345
12.22130403679362
12.22130403679289
12.221304036792167
12.221304036791436
12.221304036790714
12.221304036789983
12.221304036789252
12.22130403678853
12.221304036787805
12.221304036787073
12.221304036786348
12.221304036785629
12.221304036784895
12.221304036784172
12.221304036783446
12.221304036782708
12.221304036782003
12.221304036781268
12.221304036780541
12.221304036779818
12.221304036779092
12.221304036778374
12.221304036777648
12.221304036776925
12.221304036776194
12.221304036775473
12.221304036774747
12.221304036774022
12.221304036773303
12.221304036772578
12.221304036771853
12.221304036771132
12.221304036770407
12.22130403676969
12.221304036768961
12.221304036768238
12.22130403676752
12.221304036766796
12.221304036766071
12.221304036765348
12.221304036764632
12.221304036763913
12.221304036763193
12.221304036762463
12.221304036761747
12.221304036761023
12.221304036760309
12.221304036759587
12.221304036758863
12.22130403675815
12.221304036757422
12.221304036756703
12.221304036755981
12.221304036755264
12.221304036754544
12.221304036753827
12.2213040367531
12.221304036752382
12.221304036751665
12.221304036750944
12.221304036750235
12.221304036749505
12.221304036748794
12.221304036748075
12.221304036747352
12.221304036746638
12.221304036745922
12.221304036745204
12.221304036744487
12.221304036743769
12.221304036743051
12.22130403674234
12.221304036741625
12.2213040367409
12.221304036740191
12.221304036739477
12.221304036738758
12.221304036738033
12.221304036737322
12.221304036736603
12.221304036735892
12.221304036735175
12.221304036734459
12.221304036733754
12.221304036733038
12.221304036732315
12.221304036731599
12.221304036730892
12.221304036730178
12.221304036729459
12.22130403672875
12.221304036728037
12.221304036727316
12.22130403672661
12.221304036725892
12.221304036725176
12.221304036724463
12.22130403672375
12.221304036723042
12.221304036722332
12.221304036721616
12.221304036720905
12.221304036720186
12.221304036719477
12.221304036718772
12.221304036718053
12.22130403671734
12.221304036716637
12.221304036715926
12.221304036715221
12.221304036714505
12.221304036713784
12.221304036713079
12.221304036712365
12.221304036711663
12.221304036710956
12.221304036710242
12.221304036709526
12.221304036708819
12.221304036708112
12.221304036707403
12.221304036706695
12.221304036705986
12.221304036705277
12.221304036704561
12.221304036703856
12.22130403670315
12.221304036702447
12.221304036701733
12.221304036701028
12.221304036700316
12.221304036699612
12.221304036698902
12.2213040366982
12.221304036697495
12.22130403669678
12.221304036696074
12.22130403669537
12.221304036694665
12.22130403669396
12.221304036693255
12.221304036692537
12.22130403669184
12.221304036691134
12.221304036690423
12.221304036689723
12.221304036689014
12.221304036688311
12.221304036687611
12.221304036686895
12.221304036686194
12.221304036685487
12.22130403668479
12.221304036684081
12.221304036683376
12.221304036682676
12.221304036681971
12.221304036681268
12.221304036680566
12.221304036679857
12.22130403667916
12.221304036678458
12.221304036677752
12.221304036677045
12.221304036676344
12.221304036675644
12.221304036674946
12.221304036674237
12.221304036673542
12.22130403667283
12.22130403667213
12.221304036671436
12.221304036670736
12.221304036670038
12.221304036669327
12.22130403666863
12.221304036667927
12.221304036667224
12.221304036666522
12.221304036665826
12.221304036665131
12.221304036664433
12.221304036663733
12.221304036663032
12.221304036662334
12.221304036661632
12.221304036660932
12.221304036660229
12.221304036659534
12.221304036658836
12.221304036658138
12.22130403665743
12.221304036656743
12.221304036656038
12.221304036655342
12.22130403665465
12.221304036653951
12.221304036653253
12.221304036652556
12.221304036651857
12.22130403665116
12.22130403665046
12.22130403664977
12.221304036649071
12.221304036648371
12.221304036647675
12.221304036646979
12.221304036646284
12.221304036645593
12.22130403664489
12.22130403664419
12.2213040366435
12.221304036642808
12.22130403664211
12.22130403664142
12.221304036640722
12.221304036640026
12.221304036639332
12.221304036638639
12.221304036637946
12.221304036637255
12.221304036636557
12.221304036635862
12.221304036635168
12.221304036634475
12.221304036633784
12.221304036633084
12.221304036632395
12.221304036631704
12.221304036631013
12.22130403663032
12.22130403662962
12.221304036628942
12.221304036628233
12.221304036627552
12.221304036626865
12.22130403662617
12.221304036625474
12.221304036624783
12.221304036624089
12.221304036623396
12.221304036622712
12.221304036622026
12.221304036621332
12.221304036620646
12.221304036619948
12.221304036619255
12.221304036618575
12.221304036617886
12.221304036617193
12.221304036616498
12.221304036615809
12.22130403661512
12.22130403661443
12.221304036613738
12.221304036613057
12.22130403661236
12.221304036611672
12.221304036610988
12.2213040366103
12.221304036609617
12.22130403660892
12.221304036608236
12.221304036607552
12.221304036606861
12.22130403660618
12.221304036605488
12.221304036604797
12.221304036604113
12.221304036603426
12.221304036602739
12.221304036602055
12.221304036601369
12.22130403660068
12.221304036600001
12.22130403659931
12.221304036598623
12.221304036597935
12.221304036597251
12.221304036596573
12.22130403659589
12.221304036595205
12.221304036594507
12.221304036593832
12.221304036593146
12.22130403659246
12.221304036591775
12.221304036591091
12.221304036590414
12.221304036589725
12.22130403658904
12.221304036588357
12.221304036587673
12.221304036586991
12.221304036586304
12.221304036585622
12.221304036584945
12.221304036584261
12.221304036583579
12.221304036582897
12.221304036582218
12.221304036581532
12.221304036580849
12.221304036580168
12.221304036579491
12.22130403657881
12.22130403657812
12.22130403657744
12.221304036576758
12.221304036576086
12.2213040365754
12.221304036574724
12.221304036574045
12.221304036573363
12.22130403657268
12.221304036572
12.22130403657132
12.22130403657064
12.221304036569967
12.221304036569283
12.221304036568602
12.221304036567927
12.221304036567247
12.22130403656657
12.221304036565892
12.22130403656521
12.221304036564531
12.221304036563852
12.221304036563179
12.221304036562504
12.22130403656182
12.221304036561143
12.221304036560468
12.22130403655979
12.221304036559117
12.221304036558436
12.221304036557756
12.221304036557077
12.221304036556408
12.221304036555733
12.221304036555058
12.22130403655438
12.221304036553702
12.221304036553022
12.221304036552345
12.221304036551679
12.221304036551
12.221304036550322
12.221304036549657
12.221304036548972
12.221304036548302
12.221304036547629
12.221304036546949
12.221304036546274
12.221304036545598
12.22130403654493
12.221304036544252
12.22130403654358
12.2213040365429
12.221304036542238
12.221304036541556
12.221304036540888
12.221304036540209
12.22130403653955
12.221304036538864
12.221304036538195
12.221304036537532
12.221304036536853
12.221304036536178
12.221304036535509
12.221304036534837
12.221304036534162
12.22130403653349
12.221304036532823
12.221304036532146
12.221304036531476
12.221304036530809
12.221304036530135
12.221304036529457
12.221304036528794
12.221304036528124
12.221304036527455
12.221304036526787

12.221304036526119
12.221304036525448
12.221304036524778
12.22130403652411
12.22130403652344
12.22130403652277
12.221304036522099
12.221304036521428
12.221304036520763
12.221304036520092
12.221304036519433
12.221304036518763
12.221304036518086
12.221304036517425
12.22130403651675
12.221304036516079
12.22130403651542
12.22130403651475
12.22130403651408
12.221304036513413
12.221304036512748
12.221304036512084
12.22130403651142
12.22130403651075
12.221304036510077
12.221304036509418
12.22130403650875
12.221304036508084
12.221304036507416
12.221304036506755
12.221304036506082
12.221304036505428
12.221304036504755
12.221304036504092
12.22130403650343
12.221304036502762
12.221304036502096
12.221304036501436
12.221304036500769
12.221304036500104
12.221304036499438
12.221304036498777
12.221304036498113
12.221304036497445
12.221304036496782
12.22130403649612
12.221304036495463
12.221304036494793
12.221304036494132
12.22130403649348
12.221304036492807
12.221304036492153
12.221304036491482
12.221304036490826
12.221304036490155
12.221304036489498
12.221304036488837
12.221304036488176
12.221304036487506
12.221304036486842
12.221304036486186
12.22130403648553
12.221304036484865
12.221304036484206
12.22130403648355
12.221304036482882
12.221304036482222
12.22130403648157
12.221304036480912
12.221304036480246
12.221304036479582
12.221304036478925
12.22130403647827
12.221304036477607
12.221304036476942
12.221304036476283
12.221304036475631
12.22130403647497
12.221304036474308
12.221304036473656
12.221304036472995
12.221304036472333
12.221304036471677
12.221304036471022
12.221304036470364
12.221304036469704
12.221304036469055
12.221304036468391
12.221304036467737
12.221304036467073
12.221304036466417
12.221304036465764
12.2213040364651
12.221304036464455
12.221304036463792
12.221304036463133
12.221304036462488
12.221304036461826
12.22130403646117
12.221304036460522
12.221304036459857
12.221304036459195
12.221304036458537
12.221304036457898
12.221304036457235
12.221304036456583
12.22130403645593
12.22130403645527
12.221304036454619
12.221304036453969
12.221304036453306
12.221304036452661
12.221304036452004
12.221304036451356
12.221304036450698
12.221304036450048
12.221304036449396
12.221304036448743
12.221304036448082
12.22130403644743
12.22130403644677
12.221304036446124
12.221304036445474
12.221304036444824
12.221304036444174
12.221304036443525
12.221304036442866
12.221304036442211
12.221304036441568
12.221304036440907
12.221304036440257
12.221304036439609
12.221304036438958
12.221304036438301
12.221304036437648
12.22130403643701
12.22130403643635
12.221304036435713
12.221304036435054
12.221304036434404
12.22130403643376
12.221304036433107
12.221304036432452
12.221304036431803
12.22130403643115
12.22130403643051
12.221304036429856
12.22130403642921
12.221304036428554
12.221304036427917
12.221304036427265
12.221304036426613
12.221304036425966
12.221304036425318
12.22130403642467
12.221304036424018
12.221304036423378
12.221304036422726
12.221304036422081
12.22130403642144
12.221304036420786
12.221304036420138
12.22130403641949
12.221304036418852
12.221304036418202
12.221304036417555
12.221304036416914
12.221304036416258
12.221304036415612
12.221304036414965
12.221304036414322
12.221304036413674
12.221304036413036
12.221304036412391
12.221304036411743
12.221304036411098
12.22130403641045
12.221304036409816
12.22130403640917
12.221304036408522
12.22130403640787
12.221304036407231
12.221304036406584
12.22130403640594
12.221304036405298
12.221304036404655
12.221304036404014
12.221304036403366
12.221304036402724
12.221304036402092
12.221304036401445
12.221304036400797
12.221304036400163
12.221304036399514
12.22130403639887
12.221304036398237
12.221304036397585
12.22130403639695
12.221304036396305
12.221304036395662
12.22130403639502
12.221304036394379
12.221304036393743
12.221304036393096
12.221304036392452
12.221304036391812
12.221304036391176
12.221304036390535
12.221304036389892
12.221304036389256
12.221304036388613
12.221304036387979
12.221304036387338
12.221304036386696
12.221304036386051
12.221304036385424
12.221304036384778
12.221304036384138
12.221304036383499
12.22130403638286
12.221304036382222
12.221304036381587
12.221304036380944
12.221304036380307
12.221304036379669
12.221304036379031
12.221304036378395
12.221304036377756
12.221304036377129
12.22130403637648
12.221304036375846
12.221304036375207
12.221304036374569
12.221304036373937
12.221304036373292
12.221304036372658
12.221304036372024
12.221304036371386
12.221304036370748
12.221304036370112
12.221304036369476
12.221304036368844
12.22130403636821
12.221304036367567
12.22130403636693
12.221304036366295
12.221304036365666
12.22130403636503
12.221304036364398
12.221304036363765
12.221304036363124
12.221304036362486
12.221304036361847
12.221304036361222
12.221304036360593
12.221304036359953
12.22130403635932
12.221304036358687
12.221304036358056
12.221304036357418
12.221304036356788
12.221304036356148
12.221304036355525
12.22130403635489
12.221304036354256
12.221304036353626
12.221304036352992
12.221304036352365
12.221304036351732
12.221304036351098
12.221304036350467
12.221304036349837
12.221304036349201
12.221304036348577
12.221304036347936
12.221304036347307
12.221304036346677
12.221304036346044
12.221304036345416
12.22130403634479
12.221304036344158
12.221304036343522
12.221304036342893
12.221304036342266
12.221304036341632
12.221304036341001
12.221304036340374
12.221304036339749
12.22130403633912
12.221304036338484
12.22130403633786
12.22130403633723
12.2213040363366
12.221304036335974
12.221304036335349
12.221304036334718
12.221304036334093
12.221304036333459
12.22130403633283
12.221304036332205
12.22130403633158
12.221304036330949
12.221304036330318
12.22130403632969
12.221304036329068
12.22130403632844
12.221304036327812
12.221304036327192
12.221304036326561
12.221304036325936
12.221304036325309
12.221304036324677
12.221304036324055
12.22130403632343
12.221304036322804
12.221304036322177
12.221304036321554
12.221304036320928
12.221304036320298
12.221304036319676
12.221304036319053
12.221304036318427
12.2213040363178
12.221304036317182
12.221304036316557
12.221304036315924
12.221304036315306
12.221304036314681
12.221304036314065
12.221304036313432
12.221304036312809
12.221304036312183
12.221304036311563
12.221304036310935
12.22130403631032
12.221304036309697
12.22130403630907
12.22130403630845
12.22130403630783
12.221304036307208
12.221304036306583
12.221304036305957
12.221304036305343
12.221304036304714
12.221304036304097
12.22130403630347
12.221304036302856
12.221304036302238
12.22130403630161
12.22130403630099
12.221304036300362
12.221304036299745
12.221304036299127
12.221304036298505
12.221304036297886
12.221304036297267
12.221304036296642
12.221304036296027
12.2213040362954
12.221304036294788
12.221304036294162
12.221304036293542
12.221304036292924
12.221304036292306
12.221304036291693
12.22130403629107
12.221304036290459
12.221304036289844
12.221304036289215
12.221304036288599
12.221304036287979
12.221304036287364
12.221304036286744
12.22130403628612
12.221304036285508
12.22130403628489
12.221304036284273
12.221304036283655
12.221304036283033
12.22130403628242
12.221304036281806
12.22130403628119
12.22130403628057
12.221304036279955
12.221304036279346
12.221304036278726
12.221304036278108
12.221304036277491
12.22130403627687
12.221304036276264
12.221304036275644
12.221304036275031
12.221304036274413
12.221304036273793
12.22130403627318
12.221304036272572
12.221304036271952
12.221304036271343
12.22130403627072
12.221304036270109
12.221304036269494
12.22130403626888
12.221304036268258
12.221304036267652
12.221304036267039
12.221304036266426
12.221304036265817
12.2213040362652
12.221304036264586
12.221304036263968
12.221304036263362
12.221304036262744
12.221304036262135
12.22130403626152
12.221304036260918
12.221304036260303
12.221304036259681
12.22130403625908
12.221304036258461
12.221304036257845
12.221304036257244
12.221304036256628
12.221304036256017
12.221304036255402
12.221304036254793
12.22130403625418
12.221304036253574
12.221304036252963
12.221304036252352
12.221304036251746
12.221304036251126
12.221304036250524
12.221304036249913
12.221304036249297
12.221304036248688
12.221304036248084
12.221304036247478
12.22130403624686
12.22130403624625
12.221304036245643
12.221304036245037
12.221304036244431
12.221304036243822
12.221304036243216
12.221304036242604
12.221304036241996
12.221304036241383
12.221304036240777
12.221304036240173
12.221304036239559
12.221304036238955
12.22130403623835
12.221304036237745
12.221304036237138
12.221304036236528
12.221304036235924
12.221304036235315
12.22130403623471
12.221304036234102
12.221304036233501
12.22130403623288
12.221304036232283
12.221304036231675
12.221304036231063
12.22130403623047
12.22130403622986
12.221304036229254
12.221304036228643
12.221304036228046
12.221304036227439
12.22130403622683
12.221304036226229
12.221304036225622
12.22130403622502
12.22130403622441
12.221304036223817
12.221304036223202
12.2213040362226
12.221304036221998
12.221304036221397
12.221304036220788
12.221304036220182
12.221304036219584
12.221304036218982
12.22130403621838
12.221304036217777
12.221304036217168
12.221304036216571
12.221304036215976
12.221304036215367
12.221304036214761
12.22130403621416
12.221304036213558
12.221304036212954
12.221304036212352
12.221304036211748
12.22130403621115
12.22130403621054
12.221304036209958
12.221304036209352
12.221304036208744
12.221304036208146
12.221304036207545
12.221304036206943
12.221304036206346
12.221304036205746
12.221304036205144
12.221304036204545
12.221304036203948
12.221304036203339
12.221304036202742
12.221304036202135
12.221304036201545
12.221304036200948
12.221304036200353
12.221304036199747
12.22130403619915
12.221304036198553
12.221304036197953

12.221304036197358
12.221304036196754
12.221304036196155
12.221304036195562
12.22130403619496
12.221304036194365
12.221304036193766
12.22130403619317
12.221304036192569
12.221304036191972
12.221304036191373
12.221304036190775
12.221304036190178
12.221304036189581
12.221304036188991
12.221304036188393
12.221304036187794
12.221304036187199
12.221304036186599
12.221304036186005
12.221304036185412
12.22130403618481
12.221304036184216
12.221304036183618
12.221304036183025
12.221304036182433
12.221304036181836
12.221304036181241
12.221304036180648
12.221304036180051
12.221304036179456
12.221304036178868
12.221304036178275
12.221304036177676
12.221304036177079
12.221304036176484
12.22130403617589
12.221304036175304
12.221304036174706
12.221304036174118
12.221304036173517
12.221304036172926
12.221304036172329
12.221304036171732
12.221304036171148
12.22130403617055
12.221304036169961
12.221304036169371
12.221304036168776
12.221304036168185
12.221304036167597
12.221304036167002
12.221304036166407
12.221304036165813
12.221304036165222
12.221304036164637
12.221304036164046
12.221304036163453
12.22130403616286
12.221304036162266
12.22130403616168
12.221304036161088
12.221304036160493
12.221304036159903
12.221304036159323
12.221304036158731
12.22130403615814
12.221304036157555
12.221304036156958
12.221304036156372
12.221304036155784
12.221304036155189
12.221304036154606
12.221304036154013
12.221304036153422
12.221304036152837
12.22130403615225
12.22130403615166
12.221304036151071
12.221304036150483
12.221304036149894
12.221304036149299
12.22130403614871
12.221304036148119
12.221304036147535
12.221304036146956
12.221304036146364
12.221304036145778
12.221304036145186
12.221304036144597
12.221304036144012
12.221304036143431
12.221304036142836
12.221304036142255
12.22130403614167
12.221304036141092
12.221304036140497
12.221304036139903
12.221304036139323
12.221304036138736
12.221304036138156
12.22130403613757
12.221304036136985
12.221304036136397
12.221304036135809
12.221304036135221
12.22130403613464
12.221304036134061
12.221304036133475
12.221304036132894
12.221304036132299
12.221304036131714
12.22130403613113
12.22130403613055
12.221304036129968
12.221304036129386
12.221304036128803
12.221304036128213
12.22130403612763
12.221304036127053
12.221304036126469
12.221304036125883
12.2213040361253
12.221304036124714
12.22130403612413
12.221304036123554
12.221304036122971
12.221304036122392
12.221304036121811
12.221304036121225
12.221304036120644
12.221304036120056
12.22130403611948
12.2213040361189
12.22130403611831
12.221304036117736
12.221304036117154
12.221304036116576
12.221304036115987
12.221304036115407
12.221304036114828
12.221304036114253
12.221304036113676
12.221304036113082
12.221304036112507
12.221304036111931
12.22130403611135
12.221304036110771
12.22130403611019
12.22130403610961
12.221304036109029
12.221304036108457
12.221304036107876
12.221304036107297
12.22130403610671
12.22130403610614
12.22130403610556
12.221304036104982
12.2213040361044
12.221304036103827
12.22130403610324
12.221304036102671
12.221304036102088
12.221304036101513
12.221304036100934
12.22130403610036
12.221304036099779
12.221304036099198
12.221304036098617
12.221304036098045
12.221304036097473
12.2213040360969
12.221304036096313
12.221304036095749
12.22130403609517
12.221304036094589
12.221304036094013
12.221304036093438
12.221304036092864
12.221304036092285
12.221304036091713
12.221304036091135
12.221304036090563
12.221304036089993
12.221304036089407
12.221304036088831
12.221304036088263
12.221304036087682
12.221304036087112
12.221304036086538
12.221304036085966
12.221304036085385
12.221304036084812
12.221304036084234
12.221304036083668
12.221304036083094
12.221304036082518
12.221304036081944
12.22130403608137
12.221304036080797
12.221304036080223
12.221304036079653
12.221304036079081
12.221304036078509
12.22130403607794
12.221304036077363
12.22130403607678
12.22130403607621
12.221304036075644
12.221304036075074
12.221304036074509
12.22130403607393
12.221304036073358
12.221304036072782
12.22130403607222
12.221304036071652
12.221304036071073
12.221304036070496
12.221304036069931
12.221304036069355
12.221304036068787
12.221304036068215
12.221304036067645
12.221304036067082
12.22130403606651
12.221304036065941
12.22130403606537
12.221304036064796
12.22130403606423
12.221304036063662
12.221304036063087
12.221304036062522
12.221304036061946
12.221304036061385
12.221304036060806
12.221304036060248
12.22130403605968
12.221304036059113
12.221304036058543
12.221304036057976
12.221304036057402
12.22130403605683
12.221304036056269
12.2213040360557
12.221304036055134
12.221304036054566
12.221304036053999
12.221304036053432
12.221304036052862
12.221304036052294
12.221304036051722
12.221304036051166
12.221304036050594
12.221304036050032
12.22130403604946
12.2213040360489
12.22130403604833
12.221304036047767
12.221304036047197
12.221304036046627
12.22130403604607
12.221304036045506
12.221304036044938
12.221304036044373
12.221304036043804
12.22130403604324
12.221304036042675
12.221304036042108
12.221304036041545
12.221304036040982
12.221304036040417
12.221304036039859
12.22130403603929
12.221304036038724
12.22130403603816
12.221304036037589
12.221304036037028
12.221304036036472
12.221304036035898
12.221304036035344
12.221304036034786
12.221304036034212
12.221304036033654
12.221304036033088
12.221304036032528
12.221304036031976
12.221304036031407
12.221304036030842
12.22130403603028
12.221304036029712
12.221304036029153
12.221304036028593
12.221304036028032
12.221304036027467
12.221304036026904
12.221304036026352
12.221304036025781
12.221304036025229
12.221304036024666
12.221304036024097
12.221304036023534
12.221304036022982
12.221304036022424
12.22130403602186
12.2213040360213
12.221304036020744
12.221304036020177
12.221304036019625
12.221304036019056
12.221304036018498
12.221304036017935
12.22130403601738
12.221304036016821
12.221304036016262
12.221304036015704
12.221304036015145
12.22130403601458
12.221304036014025
12.22130403601346
12.221304036012906
12.221304036012349
12.221304036011793
12.221304036011237
12.22130403601068
12.221304036010116
12.221304036009562
12.221304036009004
12.221304036008448
12.221304036007886
12.221304036007329
12.221304036006776
12.22130403600622
12.221304036005662
12.221304036005106
12.221304036004545
12.221304036003989
12.221304036003435
12.221304036002875
12.221304036002323
12.221304036001762
12.221304036001207
12.221304036000655
12.221304036000094
12.221304035999548
12.221304035998982
12.221304035998434
12.221304035997875
12.221304035997322
12.221304035996765
12.221304035996212
12.221304035995654
12.2213040359951
12.221304035994542
12.22130403599399
12.221304035993445
12.221304035992883
12.221304035992329
12.221304035991777
12.221304035991224
12.22130403599067
12.221304035990116
12.22130403598956
12.221304035989005
12.221304035988451
12.221304035987904
12.221304035987353
12.221304035986792
12.22130403598624
12.221304035985689
12.221304035985137
12.221304035984584
12.221304035984039
12.221304035983481
12.221304035982929
12.221304035982381
12.221304035981827
12.221304035981278
12.221304035980724
12.221304035980163
12.221304035979623
12.221304035979067
12.221304035978513
12.221304035977969
12.221304035977415
12.221304035976864
12.221304035976312
12.22130403597577
12.221304035975216
12.221304035974661
12.22130403597412
12.221304035973565
12.221304035973017
12.221304035972464
12.221304035971913
12.22130403597137
12.221304035970814
12.221304035970274
12.221304035969723
12.221304035969169
12.221304035968618
12.221304035968064
12.22130403596753
12.221304035966977
12.221304035966428
12.221304035965877
12.221304035965328
12.221304035964781
12.221304035964243
12.22130403596369
12.22130403596314
12.221304035962598
12.221304035962046
12.221304035961499
12.221304035960953
12.2213040359604
12.221304035959857
12.221304035959312
12.221304035958761
12.221304035958216
12.221304035957672
12.22130403595712
12.221304035956578
12.221304035956035
12.22130403595549
12.22130403595494
12.221304035954395
12.221304035953848
12.221304035953311
12.221304035952757
12.22130403595221
12.22130403595167
12.221304035951123
12.221304035950581
12.221304035950032
12.221304035949483
12.22130403594894
12.221304035948398
12.221304035947853
12.221304035947314
12.221304035946769
12.221304035946229
12.221304035945675
12.221304035945131
12.22130403594459
12.221304035944042
12.221304035943504
12.221304035942962
12.221304035942417
12.221304035941877
12.221304035941332
12.22130403594079
12.221304035940245
12.221304035939704
12.221304035939161
12.221304035938614
12.221304035938074
12.221304035937534
12.221304035936994
12.221304035936452
12.221304035935908
12.221304035935367
12.221304035934818
12.22130403593428
12.221304035933738
12.221304035933201
12.22130403593266
12.221304035932121
12.221304035931576
12.221304035931038
12.221304035930503
12.221304035929956
12.22130403592942
12.22130403592888
12.221304035928336
12.221304035927798
12.221304035927247
12.221304035926723
12.221304035926172
12.221304035925638
12.2213040359251
12.221304035924557
12.22130403592402
12.221304035923476
12.221304035922948
12.221304035922406
12.221304035921861
12.221304035921321
12.221304035920783
12.22130403592025
12.221304035919717
12.221304035919175
12.221304035918635
12.221304035918092
12.221304035917555
12.221304035917015
12.221304035916482
12.22130403591594
12.221304035915407
12.221304035914871
12.221304035914331
12.221304035913786
12.221304035913262
12.221304035912725
12.221304035912185
12.221304035911649
12.22130403591111
12.22130403591058
12.221304035910038
12.221304035909506
12.22130403590897
12.22130403590843
12.221304035907895
12.221304035907362
12.221304035906831
12.221304035906291
12.221304035905758
12.221304035905222
12.221304035904682
12.221304035904149
12.22130403590362
12.22130403590308
12.22130403590255
12.221304035902014
12.221304035901484
12.221304035900939
12.221304035900408
12.221304035899877
12.221304035899339
12.22130403589881
12.22130403589828
12.22130403589774
12.22130403589721
12.221304035896674
12.221304035896141
12.221304035895614
12.221304035895075
12.221304035894544
12.221304035894002
12.221304035893473
12.221304035892945
12.221304035892409
12.221304035891885
12.221304035891345
12.221304035890814
12.22130403589029
12.221304035889748
12.221304035889219
12.221304035888695
12.221304035888158

12.221304035887627
12.221304035887103
12.221304035886568
12.221304035886032
12.221304035885506
12.221304035884973
12.221304035884451
12.221304035883911
12.221304035883378
12.221304035882856
12.22130403588233
12.221304035881793
12.221304035881268
12.221304035880728
12.221304035880205
12.221304035879669
12.221304035879145
12.221304035878617
12.221304035878088
12.221304035877559
12.221304035877028
12.221304035876502
12.22130403587597
12.221304035875438
12.22130403587491
12.221304035874386
12.221304035873855
12.221304035873326
12.2213040358728
12.221304035872267
12.221304035871743
12.221304035871214
12.221304035870693
12.221304035870158
12.22130403586963
12.221304035869112
12.221304035868583
12.221304035868055
12.22130403586753
12.221304035867
12.221304035866472
12.221304035865943
12.22130403586541
12.221304035864893
12.221304035864366
12.221304035863838
12.221304035863312
12.221304035862794
12.22130403586226
12.221304035861738
12.221304035861207
12.221304035860687
12.22130403586016
12.22130403585964
12.221304035859115
12.221304035858589
12.221304035858058
12.221304035857539
12.221304035857012
12.221304035856486
12.221304035855955
12.221304035855443
12.221304035854912
12.22130403585439
12.221304035853866
12.221304035853345
12.221304035852814
12.221304035852297
12.221304035851775
12.221304035851253
12.221304035850727
12.221304035850205
12.221304035849682
12.22130403584915
12.221304035848636
12.221304035848116
12.221304035847584
12.22130403584707
12.221304035846542
12.221304035846023
12.221304035845499
12.22130403584498
12.221304035844458
12.221304035843932
12.22130403584341
12.221304035842886
12.221304035842369
12.221304035841847
12.221304035841323
12.221304035840802
12.221304035840284
12.221304035839763
12.221304035839243
12.221304035838724
12.221304035838202
12.221304035837683
12.221304035837164
12.221304035836637
12.221304035836116
12.221304035835606
12.221304035835075
12.221304035834562
12.22130403583404
12.221304035833517
12.221304035833
12.221304035832484
12.221304035831965
12.221304035831443
12.22130403583093
12.221304035830403
12.221304035829885
12.221304035829363
12.221304035828853
12.22130403582833
12.221304035827819
12.221304035827291
12.22130403582678
12.221304035826257
12.221304035825742
12.221304035825225
12.221304035824705
12.221304035824193
12.22130403582367
12.221304035823152
12.221304035822644
12.221304035822119
12.221304035821605
12.221304035821083
12.221304035820571
12.221304035820053
12.221304035819534
12.22130403581902
12.221304035818507
12.221304035817981
12.221304035817473
12.221304035816951
12.221304035816438
12.221304035815926
12.221304035815413
12.221304035814898
12.221304035814375
12.221304035813858
12.221304035813349
12.221304035812834
12.221304035812315
12.2213040358118
12.221304035811286
12.221304035810771
12.22130403581026
12.221304035809753
12.221304035809228
12.221304035808712
12.221304035808194
12.22130403580769
12.22130403580717
12.221304035806662
12.221304035806142
12.221304035805632
12.22130403580512
12.221304035804607
12.221304035804094
12.221304035803579
12.221304035803069
12.221304035802559
12.22130403580204
12.221304035801525
12.221304035801017
12.221304035800504
12.221304035799994
12.221304035799479
12.221304035798967
12.221304035798456
12.221304035797944
12.221304035797438
12.221304035796928
12.221304035796408
12.2213040357959
12.221304035795393
12.221304035794875
12.221304035794361
12.221304035793858
12.221304035793345
12.22130403579283
12.221304035792322
12.22130403579181
12.221304035791295
12.221304035790789
12.221304035790284
12.221304035789775
12.221304035789261
12.221304035788757
12.221304035788242
12.221304035787732
12.221304035787226
12.221304035786718
12.221304035786204
12.2213040357857
12.221304035785192
12.22130403578468
12.221304035784174
12.221304035783657
12.221304035783149
12.221304035782637
12.221304035782136
12.221304035781626
12.221304035781117
12.221304035780607
12.221304035780097
12.221304035779593
12.221304035779083
12.221304035778584
12.22130403577807
12.221304035777553
12.221304035777063
12.22130403577655
12.221304035776038
12.221304035775537
12.221304035775033
12.221304035774526
12.22130403577401
12.221304035773509
12.221304035773
12.221304035772492
12.22130403577199
12.221304035771482
12.221304035770972
12.221304035770467
12.221304035769965
12.221304035769462
12.221304035768963
12.221304035768448
12.221304035767938
12.221304035767442
12.22130403576693
12.221304035766432
12.221304035765924
12.221304035765423
12.22130403576492
12.221304035764414
12.221304035763902
12.221304035763398
12.221304035762893
12.221304035762394
12.221304035761888
12.221304035761383
12.221304035760884
12.221304035760376
12.221304035759877
12.221304035759378
12.221304035758871
12.221304035758362
12.22130403575786
12.221304035757358
12.221304035756855
12.221304035756344
12.221304035755852
12.221304035755344
12.22130403575484
12.221304035754345
12.221304035753848
12.22130403575334
12.221304035752832
12.22130403575233
12.221304035751835
12.221304035751333
12.22130403575083
12.221304035750327
12.221304035749828
12.221304035749325
12.221304035748823
12.221304035748323
12.221304035747815
12.221304035747325
12.221304035746828
12.221304035746325
12.221304035745822
12.221304035745316
12.22130403574482
12.221304035744312
12.221304035743826
12.221304035743323
12.221304035742822
12.22130403574232
12.221304035741818
12.221304035741325
12.221304035740818
12.221304035740328
12.221304035739825
12.221304035739324
12.221304035738823
12.221304035738324
12.22130403573783
12.221304035737335
12.221304035736829
12.221304035736331
12.221304035735828
12.221304035735333
12.221304035734835
12.221304035734342
12.221304035733835
12.221304035733347
12.221304035732848
12.221304035732347
12.221304035731844
12.221304035731354
12.221304035730853
12.221304035730357
12.221304035729865
12.221304035729368
12.221304035728865
12.221304035728368
12.221304035727872
12.22130403572738
12.221304035726885
12.221304035726382
12.221304035725888
12.221304035725392
12.221304035724902
12.2213040357244
12.221304035723906
12.221304035723405
12.221304035722914
12.221304035722419
12.22130403572192
12.22130403572143
12.221304035720932
12.221304035720438
12.22130403571994
12.221304035719452
12.22130403571896
12.22130403571846
12.221304035717967
12.221304035717472
12.221304035716981
12.221304035716484
12.221304035715985
12.221304035715493
12.221304035714997
12.221304035714507
12.221304035714015
12.221304035713525
12.221304035713025
12.221304035712535
12.221304035712043
12.22130403571155
12.221304035711054
12.221304035710556
12.221304035710071
12.22130403570958
12.22130403570908
12.22130403570859
12.221304035708094
12.22130403570761
12.221304035707114
12.221304035706622
12.221304035706122
12.22130403570564
12.221304035705147
12.221304035704657
12.221304035704156
12.221304035703678
12.221304035703177
12.22130403570269
12.221304035702197
12.22130403570171
12.221304035701218
12.22130403570073
12.22130403570023
12.221304035699747
12.221304035699253
12.221304035698761
12.221304035698275
12.221304035697782
12.221304035697296
12.221304035696805
12.22130403569632
12.221304035695828
12.221304035695338
12.221304035694857
12.221304035694361
12.221304035693866
12.221304035693382
12.221304035692887
12.221304035692393
12.221304035691908
12.221304035691416
12.221304035690933
12.221304035690443
12.221304035689963
12.221304035689467
12.221304035688977
12.221304035688489
12.221304035688004
12.221304035687522
12.221304035687025
12.221304035686543
12.221304035686057
12.221304035685572
12.221304035685082
12.221304035684595
12.22130403568411
12.221304035683625
12.22130403568313
12.22130403568264
12.221304035682161
12.221304035681676
12.221304035681182
12.221304035680703
12.221304035680221
12.22130403567973
12.221304035679244
12.221304035678758
12.22130403567827
12.221304035677779
12.2213040356773
12.221304035676814
12.221304035676322
12.221304035675837
12.221304035675363
12.221304035674871
12.221304035674386
12.221304035673903
12.221304035673414
12.221304035672937
12.221304035672444
12.22130403567196
12.221304035671476
12.221304035671
12.22130403567052
12.221304035670023
12.22130403566954
12.221304035669062
12.221304035668586
12.221304035668092
12.221304035667607
12.22130403566712
12.221304035666645
12.221304035666163
12.221304035665673
12.22130403566519
12.22130403566471
12.221304035664227
12.221304035663744
12.221304035663254
12.221304035662785
12.221304035662303
12.221304035661813
12.221304035661333
12.221304035660854
12.221304035660372
12.221304035659886
12.221304035659399
12.221304035658928
12.221304035658441
12.22130403565796
12.221304035657477
12.221304035656997
12.221304035656516
12.221304035656033
12.221304035655562
12.221304035655074
12.221304035654594
12.221304035654112
12.221304035653635
12.22130403565315
12.221304035652674
12.221304035652194
12.221304035651716
12.221304035651231
12.221304035650753
12.22130403565027
12.22130403564979
12.22130403564931
12.22130403564883
12.221304035648357
12.221304035647869
12.221304035647398
12.221304035646913
12.221304035646439
12.221304035645959
12.221304035645474
12.221304035644993
12.221304035644522
12.22130403564405
12.221304035643573
12.221304035643087
12.221304035642614
12.221304035642133
12.221304035641653
12.221304035641184
12.2213040356407
12.221304035640221
12.221304035639749
12.22130403563926
12.22130403563879
12.22130403563831
12.221304035637834
12.221304035637361
12.221304035636878
12.221304035636408
12.221304035635939
12.221304035635454
12.22130403563498
12.221304035634502
12.221304035634027
12.221304035633539
12.221304035633075
12.221304035632604
12.22130403563212
12.221304035631642
12.22130403563116
12.22130403563069
12.221304035630219
12.221304035629739
12.221304035629263
12.221304035628792
12.221304035628316
12.221304035627837
12.221304035627373
12.221304035626893
12.221304035626417
12.221304035625947
12.221304035625465
12.221304035624994
12.221304035624518
12.221304035624046
12.221304035623573
12.22130403562309
12.221304035622628
12.221304035622147
12.22130403562168

12.221304035621213
12.221304035620735
12.221304035620252
12.221304035619792
12.221304035619305
12.221304035618843
12.22130403561837
12.2213040356179
12.221304035617415
12.22130403561695
12.22130403561648
12.221304035616003
12.22130403561554
12.22130403561506
12.221304035614578
12.221304035614118
12.221304035613642
12.221304035613176
12.221304035612699
12.221304035612224
12.221304035611762
12.221304035611285
12.221304035610817
12.221304035610348
12.221304035609874
12.221304035609402
12.22130403560893
12.221304035608457
12.22130403560799
12.22130403560752
12.221304035607048
12.221304035606574
12.221304035606108
12.221304035605636
12.221304035605172
12.221304035604698
12.22130403560422
12.221304035603765
12.221304035603291
12.221304035602813
12.221304035602344
12.221304035601884
12.221304035601415
12.221304035600937
12.221304035600475
12.221304035600005
12.221304035599543
12.221304035599069
12.221304035598603
12.22130403559813
12.221304035597665
12.221304035597193
12.221304035596729
12.221304035596257
12.221304035595791
12.221304035595315
12.221304035594862
12.221304035594386
12.22130403559392
12.22130403559346
12.22130403559299
12.221304035592519
12.22130403559205
12.221304035591585
12.221304035591121
12.22130403559065
12.221304035590183
12.22130403558972
12.221304035589252
12.22130403558878
12.221304035588322
12.221304035587853
12.221304035587389
12.22130403558692
12.221304035586453
12.22130403558599
12.221304035585515
12.221304035585055
12.221304035584591
12.221304035584133
12.22130403558367
12.221304035583202
12.221304035582724
12.221304035582264
12.221304035581802
12.221304035581335
12.221304035580873
12.22130403558041
12.221304035579948
12.221304035579475
12.221304035579006
12.221304035578546
12.221304035578088
12.221304035577619
12.221304035577157
12.221304035576695
12.221304035576232
12.221304035575763
12.221304035575303
12.221304035574844
12.221304035574372
12.221304035573917
12.221304035573448
12.221304035572983
12.221304035572523
12.221304035572057
12.221304035571595
12.221304035571139
12.221304035570672
12.221304035570215
12.22130403556975
12.221304035569283
12.221304035568822
12.221304035568362
12.221304035567904
12.22130403556744
12.221304035566977
12.221304035566513
12.221304035566058
12.221304035565588
12.221304035565133
12.221304035564673
12.221304035564211
12.221304035563746
12.221304035563286
12.221304035562833
12.221304035562367
12.221304035561905
12.221304035561449
12.221304035560987
12.221304035560525
12.221304035560069
12.221304035559603
12.221304035559147
12.221304035558688
12.221304035558228
12.221304035557765
12.221304035557308
12.221304035556848
12.221304035556393
12.221304035555928
12.221304035555468
12.221304035555008
12.221304035554553
12.221304035554093
12.22130403555363
12.22130403555317
12.221304035552718
12.221304035552256
12.221304035551803
12.221304035551343
12.221304035550887
12.221304035550432
12.221304035549974
12.221304035549517
12.221304035549052
12.221304035548599
12.221304035548142
12.221304035547682
12.22130403554722
12.221304035546765
12.221304035546305
12.221304035545849
12.221304035545394
12.221304035544938
12.221304035544483
12.221304035544023
12.22130403554357
12.221304035543108
12.221304035542653
12.221304035542198
12.221304035541742
12.221304035541278
12.22130403554083
12.221304035540374
12.221304035539918
12.221304035539465
12.221304035538997
12.221304035538544
12.22130403553809
12.221304035537642
12.221304035537178
12.221304035536718
12.22130403553628
12.221304035535821
12.221304035535372
12.221304035534907
12.221304035534454
12.221304035533997
12.221304035533544
12.221304035533091
12.221304035532636
12.221304035532183
12.221304035531725
12.22130403553128
12.221304035530828
12.221304035530366
12.22130403552991
12.221304035529457
12.221304035529007
12.221304035528554
12.221304035528101
12.221304035527647
12.221304035527199
12.221304035526739
12.221304035526291
12.22130403552584
12.221304035525382
12.221304035524929
12.221304035524486
12.22130403552402
12.221304035523573
12.221304035523122
12.221304035522671
12.22130403552222
12.22130403552176
12.221304035521316
12.22130403552086
12.221304035520406
12.221304035519964
12.221304035519509
12.221304035519053
12.221304035518616
12.221304035518154
12.221304035517697
12.221304035517257
12.221304035516804
12.221304035516354
12.2213040355159
12.221304035515454
12.221304035514997
12.221304035514548
12.2213040355141
12.221304035513652
12.221304035513203
12.221304035512754
12.2213040355123
12.221304035511851
12.221304035511404
12.221304035510956
12.221304035510505
12.221304035510055
12.2213040355096
12.221304035509156
12.221304035508707
12.221304035508261
12.221304035507805
12.22130403550736
12.221304035506913
12.221304035506456
12.221304035506014
12.221304035505561
12.221304035505115
12.221304035504666
12.22130403550422
12.221304035503776
12.221304035503325
12.221304035502879
12.221304035502435
12.221304035501987
12.221304035501536
12.221304035501085
12.221304035500648
12.22130403550019
12.221304035499744
12.221304035499296
12.221304035498852
12.22130403549841
12.221304035497953
12.22130403549751
12.221304035497063
12.221304035496622
12.221304035496178
12.221304035495727
12.221304035495281
12.221304035494834
12.221304035494388
12.221304035493944
12.22130403549349
12.221304035493057
12.221304035492606
12.22130403549216
12.221304035491716
12.22130403549127
12.221304035490826
12.22130403549038
12.221304035489933
12.22130403548949
12.221304035489045
12.221304035488606
12.221304035488162
12.221304035487714
12.221304035487268
12.221304035486826
12.221304035486387
12.221304035485934
12.221304035485497
12.221304035485044
12.221304035484605
12.221304035484161
12.22130403548372
12.221304035483271
12.221304035482827
12.221304035482383
12.22130403548194
12.221304035481504
12.221304035481056
12.221304035480612
12.22130403548017
12.221304035479728
12.221304035479283
12.221304035478843
12.221304035478399
12.22130403547796
12.22130403547752
12.221304035477074
12.221304035476637
12.22130403547619
12.221304035475752
12.221304035475304
12.221304035474866
12.221304035474423
12.221304035473985
12.221304035473539
12.2213040354731
12.221304035472656
12.221304035472219
12.221304035471771
12.221304035471336
12.22130403547089
12.221304035470455
12.221304035470013
12.221304035469565
12.221304035469133
12.221304035468693
12.221304035468247
12.221304035467815
12.221304035467375
12.221304035466934
12.221304035466494
12.221304035466057
12.221304035465607
12.221304035465174
12.221304035464728
12.221304035464296
12.221304035463852
12.221304035463422
12.221304035462977
12.22130403546254
12.221304035462099
12.221304035461664
12.221304035461221
12.221304035460788
12.22130403546034
12.221304035459903
12.221304035459465
12.221304035459033
12.221304035458589
12.221304035458152
12.221304035457715
12.22130403545727
12.22130403545684
12.221304035456399
12.22130403545596
12.221304035455525
12.22130403545509
12.221304035454645
12.221304035454223
12.221304035453777
12.221304035453338
12.221304035452908
12.221304035452464
12.221304035452029
12.2213040354516
12.221304035451153
12.221304035450725
12.22130403545028
12.22130403544985
12.221304035449412
12.221304035448977
12.22130403544854
12.22130403544811
12.221304035447663
12.22130403544723
12.221304035446792
12.221304035446362
12.221304035445923
12.221304035445495
12.221304035445058
12.221304035444627
12.221304035444184
12.221304035443753
12.221304035443316
12.221304035442879
12.221304035442447
12.221304035442014
12.221304035441575
12.221304035441143
12.221304035440708
12.221304035440273
12.22130403543984
12.221304035439408
12.221304035438974
12.221304035438541
12.221304035438106
12.221304035437672
12.221304035437239
12.221304035436805
12.221304035436367
12.22130403543594
12.221304035435509
12.221304035435073
12.221304035434642
12.221304035434212
12.221304035433773
12.221304035433342
12.221304035432905
12.221304035432471
12.221304035432043
12.221304035431613
12.22130403543118
12.221304035430743
12.22130403543031
12.221304035429885
12.221304035429455
12.221304035429025
12.221304035428583
12.221304035428153
12.221304035427728
12.221304035427298
12.22130403542686
12.22130403542643
12.221304035425998
12.221304035425572
12.221304035425144
12.221304035424705
12.221304035424277
12.221304035423842
12.221304035423419
12.221304035422989
12.22130403542256
12.221304035422119
12.221304035421698
12.221304035421268
12.221304035420834
12.221304035420408
12.22130403541997
12.221304035419548
12.221304035419116
12.221304035418685
12.22130403541826
12.221304035417832
12.221304035417399
12.221304035416969
12.221304035416535
12.221304035416116
12.221304035415681
12.221304035415251
12.221304035414823
12.221304035414402
12.221304035413969
12.221304035413544
12.221304035413112
12.22130403541269
12.221304035412256
12.221304035411833
12.221304035411402
12.221304035410975
12.221304035410553
12.221304035410116
12.221304035409686
12.221304035409261
12.221304035408833
12.221304035408409
12.22130403540798
12.22130403540755
12.221304035407128
12.221304035406703
12.22130403540627
12.221304035405838
12.221304035405417
12.221304035404989
12.221304035404563
12.221304035404147
12.221304035403715
12.221304035403284
12.221304035402863
12.221304035402433
12.221304035402015
12.221304035401577
12.221304035401165
12.221304035400731
12.221304035400307
12.221304035399887
12.221304035399456
12.221304035399028
12.221304035398608
12.221304035398184
12.221304035397752
12.221304035397331
12.22130403539691
12.221304035396486
12.221304035396052
12.221304035395637
12.22130403539521
12.221304035394786
12.221304035394358
12.221304035393938
12.22130403539351
12.221304035393088
12.221304035392668
12.221304035392242
12.221304035391825
12.22130403539139
12.221304035390967
12.221304035390544
12.221304035390117
12.221304035389705
12.221304035389279
12.221304035388858
12.221304035388426
12.221304035388012
12.221304035387595
12.221304035387169
12.221304035386739
12.221304035386321
12.221304035385899
12.221304035385481
12.221304035385053
12.221304035384634
12.221304035384211
12.221304035383785
12.221304035383367
12.221304035382943
12.221304035382527
12.2213040353821
12.221304035381683
12.221304035381255
12.221304035380832
12.221304035380413
12.221304035379998
12.221304035379566
12.221304035379154
12.221304035378738
12.221304035378319
12.221304035377898
12.221304035377463
12.221304035377052
12.221304035376631
12.221304035376214
12.221304035375779
12.221304035375365
12.221304035374951
12.22130403537453
12.221304035374107
12.221304035373684
12.221304035373276
12.221304035372851
12.221304035372427
12.221304035372013
12.221304035371594
12.221304035371178
12.221304035370762
12.221304035370336
12.221304035369924
12.221304035369494
12.221304035369082
12.221304035368663

12.221304035368247
12.221304035367822
12.221304035367407
12.221304035366984
12.221304035366565
12.221304035366147
12.221304035365735
12.221304035365316
12.221304035364899
12.221304035364483
12.22130403536406
12.22130403536364
12.221304035363222
12.22130403536281
12.221304035362396
12.221304035361978
12.22130403536156
12.221304035361142
12.221304035360722
12.221304035360312
12.22130403535989
12.221304035359472
12.221304035359056
12.221304035358642
12.221304035358225
12.221304035357806
12.221304035357386
12.221304035356976
12.22130403535656
12.221304035356148
12.221304035355725
12.221304035355312
12.22130403535489
12.221304035354471
12.221304035354068
12.22130403535365
12.221304035353235
12.221304035352821
12.221304035352409
12.221304035351988
12.22130403535157
12.221304035351157
12.221304035350746
12.221304035350327
12.221304035349917
12.221304035349501
12.221304035349084
12.221304035348671
12.221304035348254
12.221304035347849
12.22130403534743
12.221304035347016
12.221304035346606
12.221304035346197
12.221304035345767
12.22130403534536
12.221304035344948
12.221304035344534
12.221304035344126
12.221304035343701
12.221304035343293
12.221304035342879
12.221304035342468
12.221304035342062
12.221304035341642
12.22130403534123
12.221304035340818
12.22130403534041
12.221304035339994
12.221304035339587
12.221304035339173
12.221304035338761
12.22130403533834
12.221304035337935
12.221304035337523
12.221304035337104
12.221304035336697
12.221304035336289
12.221304035335878
12.22130403533546
12.22130403533505
12.221304035334642
12.221304035334228
12.221304035333825
12.221304035333407
12.221304035332997
12.221304035332587
12.221304035332174
12.22130403533176
12.221304035331357
12.221304035330947
12.221304035330537
12.22130403533012
12.221304035329714
12.2213040353293
12.221304035328895
12.221304035328489
12.221304035328071
12.221304035327663
12.221304035327254
12.22130403532684
12.221304035326435
12.221304035326028
12.221304035325614
12.221304035325206
12.221304035324797
12.221304035324392
12.221304035323984
12.221304035323573
12.221304035323163
12.22130403532276
12.221304035322342
12.221304035321939
12.221304035321523
12.221304035321126
12.221304035320717
12.221304035320296
12.221304035319895
12.221304035319491
12.22130403531908
12.221304035318672
12.22130403531827
12.221304035317853
12.221304035317448
12.221304035317043
12.221304035316635
12.22130403531623
12.221304035315821
12.221304035315413
12.221304035315006
12.2213040353146
12.22130403531419
12.221304035313791
12.22130403531338
12.221304035312976
12.221304035312574
12.22130403531216
12.221304035311753
12.221304035311356
12.221304035310942
12.22130403531054
12.221304035310121
12.221304035309725
12.221304035309311
12.22130403530891
12.221304035308506
12.221304035308101
12.221304035307696
12.221304035307297
12.221304035306888
12.221304035306474
12.221304035306078
12.221304035305673
12.221304035305264
12.221304035304863
12.221304035304454
12.22130403530405
12.221304035303652
12.221304035303241
12.221304035302841
12.221304035302431
12.221304035302026
12.22130403530163
12.22130403530123
12.221304035300818
12.221304035300415
12.221304035300019
12.221304035299605
12.221304035299209
12.221304035298802
12.221304035298399
12.221304035298
12.221304035297592
12.221304035297191
12.221304035296782
12.22130403529638
12.22130403529598
12.221304035295576
12.221304035295173
12.221304035294775
12.221304035294363
12.221304035293969
12.221304035293564
12.221304035293164
12.221304035292759
12.22130403529235
12.221304035291952
12.221304035291551
12.22130403529115
12.221304035290752
12.22130403529035
12.221304035289956
12.221304035289547
12.221304035289142
12.221304035288739
12.22130403528835
12.22130403528794
12.221304035287542
12.221304035287137
12.221304035286739
12.221304035286334
12.221304035285936
12.221304035285536
12.221304035285137
12.221304035284735
12.22130403528433
12.22130403528393
12.221304035283534
12.221304035283136
12.221304035282742
12.221304035282346
12.221304035281936
12.221304035281532
12.221304035281133
12.221304035280736
12.221304035280337
12.221304035279937
12.221304035279546
12.221304035279138
12.22130403527874
12.221304035278346
12.221304035277937
12.221304035277548
12.221304035277146
12.221304035276749
12.22130403527635
12.221304035275953
12.221304035275548
12.221304035275157
12.221304035274756
12.221304035274356
12.221304035273958
12.221304035273565
12.221304035273159
12.22130403527276
12.221304035272366
12.22130403527197
12.221304035271572
12.221304035271176
12.221304035270776
12.221304035270377
12.221304035269984
12.221304035269586
12.221304035269185
12.221304035268794
12.221304035268394
12.221304035268004
12.221304035267595
12.22130403526721
12.221304035266803
12.221304035266412
12.221304035266018
12.221304035265621
12.221304035265224
12.221304035264827
12.22130403526443
12.221304035264035
12.221304035263636
12.221304035263243
12.22130403526285
12.221304035262447
12.221304035262056
12.221304035261666
12.221304035261264
12.221304035260863
12.221304035260474
12.221304035260081
12.221304035259688
12.221304035259294
12.221304035258896
12.221304035258495
12.22130403525811
12.221304035257715
12.221304035257317
12.221304035256917
12.221304035256527
12.221304035256127
12.221304035255745
12.221304035255347
12.221304035254956
12.221304035254557
12.22130403525416
12.221304035253771
12.221304035253379
12.221304035252992
12.221304035252588
12.2213040352522
12.221304035251809
12.221304035251409
12.221304035251016
12.221304035250618
12.221304035250233
12.221304035249846
12.221304035249446
12.22130403524905
12.221304035248668
12.221304035248265
12.22130403524788
12.221304035247478
12.221304035247087
12.221304035246698
12.221304035246304
12.221304035245918
12.221304035245524
12.221304035245135
12.221304035244742
12.22130403524435
12.221304035243959
12.221304035243568
12.221304035243174
12.221304035242783
12.22130403524239
12.221304035242008
12.221304035241612
12.221304035241213
12.221304035240825
12.221304035240436
12.221304035240042
12.221304035239653
12.221304035239264
12.221304035238875
12.221304035238491
12.221304035238095
12.221304035237702
12.221304035237315
12.221304035236923
12.221304035236537
12.221304035236153
12.22130403523576
12.22130403523536
12.221304035234981
12.221304035234587
12.221304035234198
12.221304035233809
12.221304035233418
12.221304035233029
12.221304035232645
12.221304035232253
12.221304035231872
12.22130403523148
12.22130403523109
12.221304035230693
12.221304035230311
12.221304035229926
12.221304035229526
12.22130403522914
12.221304035228753
12.221304035228366
12.22130403522798
12.221304035227586
12.221304035227197
12.221304035226817
12.22130403522643
12.22130403522604
12.22130403522565
12.22130403522526
12.221304035224875
12.221304035224493
12.221304035224097
12.221304035223717
12.221304035223332
12.221304035222934
12.22130403522256
12.22130403522217
12.221304035221783
12.221304035221392
12.221304035221008
12.221304035220625
12.22130403522024
12.221304035219843
12.221304035219461
12.221304035219083
12.221304035218692
12.221304035218308
12.221304035217925
12.221304035217534
12.221304035217148
12.221304035216766
12.221304035216376
12.221304035215997
12.221304035215601
12.221304035215221
12.221304035214834
12.221304035214452
12.221304035214066
12.22130403521368
12.221304035213285
12.221304035212906
12.221304035212526
12.221304035212144
12.221304035211755
12.221304035211373
12.221304035210986
12.221304035210602
12.221304035210217
12.221304035209837
12.221304035209453
12.22130403520907
12.221304035208679
12.221304035208293
12.221304035207917
12.221304035207531
12.22130403520715
12.22130403520677
12.221304035206385
12.221304035205996
12.221304035205623
12.221304035205236
12.221304035204849
12.221304035204463
12.22130403520408
12.2213040352037
12.221304035203321
12.221304035202934
12.221304035202555
12.22130403520217
12.221304035201785
12.221304035201406
12.221304035201024
12.221304035200639
12.221304035200257
12.22130403519987
12.22130403519949
12.221304035199115
12.221304035198735
12.221304035198347
12.221304035197974
12.221304035197583
12.22130403519721
12.221304035196827
12.221304035196438
12.221304035196063
12.22130403519568
12.2213040351953
12.221304035194914
12.22130403519453
12.221304035194157
12.221304035193775
12.221304035193391
12.221304035193016
12.221304035192631
12.221304035192256
12.22130403519187
12.221304035191494
12.221304035191118
12.22130403519074
12.221304035190352
12.221304035189975
12.221304035189595
12.221304035189213
12.221304035188835

12.221304035188455
12.221304035188078
12.221304035187696
12.22130403518731
12.221304035186936
12.221304035186558
12.221304035186177
12.2213040351858
12.221304035185423
12.221304035185048
12.221304035184664
12.221304035184286
12.22130403518391
12.221304035183534
12.221304035183154
12.22130403518278
12.221304035182383
12.221304035182014
12.221304035181637
12.22130403518126
12.221304035180884
12.22130403518051
12.221304035180127
12.221304035179752
12.221304035179374
12.221304035178996
12.22130403517862
12.221304035178244
12.221304035177864
12.22130403517749
12.221304035177113
12.221304035176727
12.22130403517636
12.221304035175978
12.221304035175608
12.221304035175224
12.221304035174846
12.221304035174471
12.221304035174098
12.22130403517372
12.221304035173349
12.221304035172968
12.221304035172597
12.221304035172214
12.221304035171842
12.221304035171462
12.221304035171093
12.22130403517071
12.22130403517034
12.221304035169966
12.22130403516959
12.221304035169213
12.221304035168835
12.221304035168455
12.221304035168089
12.22130403516771
12.221304035167341
12.22130403516696
12.221304035166588
12.221304035166211
12.221304035165836
12.22130403516546
12.22130403516509
12.221304035164717
12.221304035164339
12.221304035163971
12.221304035163591
12.221304035163218
12.22130403516284
12.221304035162467
12.221304035162092
12.221304035161724
12.221304035161355
12.22130403516098
12.221304035160601
12.221304035160232
12.221304035159857
12.221304035159482
12.221304035159113
12.221304035158738
12.221304035158369
12.221304035157988
12.221304035157617
12.22130403515724
12.221304035156871
12.221304035156496
12.221304035156125
12.221304035155756
12.221304035155388
12.221304035155004
12.221304035154636
12.221304035154265
12.221304035153894
12.22130403515352
12.221304035153148
12.221304035152782
12.221304035152404
12.221304035152043
12.221304035151663
12.221304035151293
12.221304035150924
12.22130403515055
12.221304035150176
12.221304035149803
12.221304035149437
12.221304035149066
12.221304035148691
12.221304035148325
12.221304035147952
12.221304035147577
12.22130403514721
12.221304035146844
12.221304035146474
12.221304035146101
12.221304035145732
12.221304035145362
12.221304035144994
12.22130403514462
12.221304035144255
12.221304035143875
12.221304035143513
12.221304035143138
12.221304035142769
12.221304035142408
12.221304035142031
12.221304035141664
12.221304035141289
12.221304035140925
12.22130403514055
12.221304035140186
12.221304035139815
12.221304035139456
12.221304035139076
12.22130403513871
12.22130403513834
12.221304035137976
12.221304035137601
12.22130403513724
12.22130403513687
12.2213040351365
12.221304035136132
12.221304035135764
12.221304035135406
12.221304035135024
12.22130403513466
12.221304035134292
12.221304035133915
12.221304035133556
12.221304035133198
12.221304035132825
12.221304035132453
12.221304035132093
12.22130403513172
12.221304035131354
12.221304035130997
12.221304035130622
12.22130403513025
12.221304035129883
12.221304035129515
12.221304035129155
12.221304035128789
12.22130403512843
12.221304035128057
12.221304035127682
12.221304035127316
12.221304035126957
12.221304035126593
12.221304035126225
12.22130403512586
12.221304035125495
12.22130403512513
12.22130403512476
12.221304035124396
12.221304035124032
12.22130403512367
12.2213040351233
12.221304035122934
12.221304035122571
12.221304035122207
12.221304035121843
12.221304035121474
12.221304035121111
12.221304035120744
12.221304035120376
12.221304035120017
12.221304035119646
12.221304035119287
12.22130403511892
12.22130403511856
12.221304035118193
12.221304035117834
12.221304035117464
12.221304035117104
12.221304035116738
12.221304035116374
12.22130403511601
12.22130403511564
12.221304035115281
12.221304035114917
12.221304035114548
12.221304035114192
12.221304035113828
12.221304035113464
12.221304035113102
12.221304035112741
12.221304035112375
12.221304035112013
12.22130403511165
12.221304035111295
12.221304035110922
12.221304035110556
12.221304035110206
12.221304035109835
12.221304035109473
12.221304035109117
12.221304035108751
12.221304035108389
12.221304035108025
12.221304035107663
12.221304035107304
12.221304035106943
12.221304035106574
12.221304035106217
12.22130403510586
12.221304035105495
12.22130403510513
12.22130403510477
12.221304035104412
12.221304035104048
12.22130403510369
12.221304035103334
12.22130403510297
12.221304035102607
12.221304035102243
12.221304035101882
12.221304035101525
12.221304035101161
12.221304035100804
12.221304035100438
12.221304035100085
12.221304035099717
12.221304035099367
12.221304035098996
12.221304035098644
12.221304035098285
12.221304035097925
12.221304035097555
12.221304035097203
12.221304035096841
12.22130403509649
12.22130403509613
12.221304035095763
12.221304035095404
12.221304035095049
12.221304035094688
12.221304035094327
12.221304035093967
12.22130403509361
12.221304035093246
12.221304035092892
12.221304035092535
12.221304035092174
12.22130403509182
12.221304035091462
12.2213040350911
12.221304035090744
12.221304035090382
12.22130403509002
12.22130403508967
12.221304035089306
12.22130403508895
12.221304035088593
12.221304035088234
12.22130403508788
12.221304035087527
12.221304035087163
12.221304035086805
12.22130403508645
12.22130403508609
12.221304035085735
12.221304035085375
12.221304035085016
12.221304035084664
12.221304035084303
12.221304035083948
12.221304035083595
12.221304035083236
12.221304035082884
12.221304035082518
12.221304035082168
12.221304035081808
12.221304035081458
12.221304035081097
12.221304035080738
12.221304035080387
12.221304035080028
12.221304035079672
12.221304035079319
12.221304035078955
12.221304035078605
12.22130403507825
12.221304035077898
12.221304035077544
12.221304035077186
12.221304035076832
12.221304035076473
12.221304035076118
12.221304035075763
12.221304035075402
12.22130403507505
12.221304035074699
12.221304035074347
12.221304035073995
12.221304035073638
12.221304035073281
12.221304035072922
12.221304035072574
12.22130403507222
12.221304035071864
12.221304035071512
12.221304035071151
12.221304035070798
12.221304035070448
12.221304035070093
12.221304035069737
12.221304035069391
12.221304035069032
12.221304035068686
12.221304035068323
12.221304035067979
12.22130403506762
12.221304035067266
12.221304035066911
12.221304035066556
12.221304035066206
12.22130403506585
12.221304035065502
12.221304035065145
12.2213040350648
12.221304035064442
12.22130403506409
12.221304035063742
12.221304035063387
12.221304035063039
12.221304035062678
12.22130403506233
12.221304035061973
12.221304035061623
12.221304035061273
12.22130403506093
12.22130403506057
12.221304035060223
12.221304035059868
12.221304035059516
12.221304035059172
12.22130403505882
12.22130403505846
12.221304035058107
12.221304035057756
12.22130403505741
12.22130403505706
12.221304035056708
12.221304035056356
12.22130403505601
12.221304035055656
12.221304035055304
12.221304035054956
12.221304035054603
12.221304035054251
12.221304035053901
12.221304035053558
12.221304035053207
12.221304035052848
12.2213040350525
12.221304035052148
12.221304035051803
12.221304035051453
12.221304035051102
12.22130403505075
12.221304035050407
12.221304035050048
12.221304035049705
12.221304035049348
12.221304035049005
12.221304035048655
12.221304035048314
12.221304035047957
12.22130403504761
12.221304035047265
12.221304035046913
12.221304035046568
12.221304035046215
12.221304035045872
12.221304035045515
12.221304035045165
12.221304035044817
12.221304035044467
12.221304035044128
12.221304035043778
12.221304035043435
12.22130403504308
12.221304035042735
12.22130403504239
12.221304035042042
12.221304035041689
12.22130403504134
12.221304035041001
12.221304035040642
12.221304035040308
12.221304035039951
12.221304035039607
12.221304035039262
12.221304035038909
12.221304035038571
12.221304035038221
12.221304035037873
12.221304035037527
12.221304035037187
12.221304035036832
12.221304035036486
12.221304035036136
12.221304035035793
12.221304035035445
12.221304035035105
12.221304035034748
12.221304035034409
12.221304035034068
12.221304035033718
12.221304035033372
12.221304035033025
12.221304035032674
12.22130403503233
12.221304035031983
12.221304035031643
12.221304035031302
12.221304035030952
12.221304035030602
12.221304035030263
12.221304035029918
12.22130403502957
12.221304035029233
12.22130403502889
12.221304035028536
12.221304035028197
12.221304035027845
12.221304035027504
12.221304035027158
12.22130403502681
12.221304035026467
12.22130403502613
12.221304035025778
12.221304035025438
12.22130403502509
12.221304035024747
12.221304035024405
12.221304035024064
12.221304035023717
12.221304035023373
12.22130403502303
12.221304035022694
12.221304035022348
12.221304035022001
12.22130403502166
12.221304035021316
12.22130403502097
12.221304035020626
12.221304035020285
12.221304035019946
12.221304035019605
12.221304035019259
12.221304035018912
12.22130403501857
12.22130403501823
12.221304035017885
12.221304035017543
12.221304035017203
12.22130403501685
12.221304035016514
12.221304035016178
12.221304035015839
12.22130403501549
12.221304035015153
12.22130403501481
12.221304035014464
12.221304035014125
12.221304035013782
12.221304035013434
12.2213040350131
12.221304035012759
12.221304035012414
12.221304035012075
12.221304035011736
12.221304035011395
12.221304035011054
12.221304035010716
12.221304035010366
12.221304035010032
12.221304035009691
12.221304035009348
12.22130403500901
12.221304035008671
12.221304035008329
12.221304035007982
12.22130403500765
12.221304035007309
12.221304035006964
12.22130403500663
12.22130403500629
12.221304035005948
12.221304035005607
12.221304035005266
12.221304035004925
12.221304035004586
12.221304035004245
12.22130403500391
12.221304035003568
12.221304035003227
12.221304035002895
12.221304035002552
12.221304035002216
12.221304035001875

12.221304035001538
12.221304035001202
12.221304035000857
12.22130403500052
12.221304035000182
12.22130403499984
12.22130403499951
12.221304034999163
12.221304034998825
12.221304034998486
12.221304034998152
12.221304034997818
12.221304034997473
12.221304034997141
12.221304034996802
12.221304034996457
12.221304034996122
12.221304034995788
12.221304034995446
12.221304034995109
12.221304034994773
12.221304034994436
12.221304034994098
12.221304034993764
12.22130403499342
12.22130403499309
12.22130403499275
12.22130403499241
12.221304034992077
12.22130403499174
12.221304034991402
12.221304034991066
12.221304034990728
12.221304034990395
12.221304034990057
12.221304034989723
12.221304034989386
12.221304034989055
12.221304034988714
12.221304034988378
12.221304034988039
12.22130403498771
12.221304034987368
12.221304034987034
12.221304034986689
12.221304034986362
12.221304034986026
12.221304034985687
12.22130403498536
12.221304034985023
12.221304034984685
12.221304034984351
12.221304034984012
12.221304034983673
12.221304034983337
12.221304034983005
12.221304034982676
12.221304034982339
12.221304034982008
12.221304034981669
12.221304034981337
12.221304034980996
12.221304034980662
12.22130403498034
12.221304034979994
12.221304034979665
12.221304034979328
12.221304034978996
12.221304034978662
12.221304034978324
12.221304034977996
12.221304034977663
12.22130403497733
12.221304034976988
12.221304034976665
12.221304034976328
12.221304034975992
12.221304034975653
12.221304034975331
12.221304034974994
12.221304034974656
12.221304034974322
12.221304034973999
12.221304034973663
12.221304034973333
12.221304034972995
12.221304034972665
12.22130403497233
12.221304034971997
12.22130403497167
12.22130403497134
12.221304034971
12.221304034970673
12.221304034970345
12.221304034970009
12.22130403496967
12.221304034969343
12.22130403496901
12.221304034968675
12.221304034968343
12.221304034968007
12.221304034967684
12.22130403496735
12.22130403496702
12.221304034966687
12.221304034966355
12.221304034966028
12.221304034965693
12.221304034965366
12.221304034965033
12.221304034964696
12.221304034964371
12.22130403496404
12.221304034963715
12.221304034963383
12.221304034963044
12.221304034962715
12.22130403496239
12.221304034962058
12.221304034961726
12.221304034961396
12.221304034961069
12.221304034960733
12.221304034960406
12.221304034960072
12.221304034959743
12.221304034959422
12.221304034959083
12.221304034958758
12.221304034958429
12.221304034958104
12.22130403495777
12.22130403495744
12.221304034957116
12.221304034956775
12.221304034956454
12.221304034956121
12.2213040349558
12.221304034955464
12.221304034955136
12.221304034954805
12.221304034954478
12.22130403495415
12.221304034953823
12.2213040349535
12.22130403495317
12.221304034952832
12.22130403495251
12.221304034952182
12.22130403495185
12.221304034951526
12.22130403495119
12.22130403495087
12.221304034950544
12.221304034950217
12.221304034949881
12.221304034949563
12.22130403494923
12.221304034948904
12.221304034948583
12.22130403494825
12.221304034947917
12.221304034947595
12.221304034947265
12.221304034946934
12.221304034946613
12.221304034946284
12.221304034945955
12.221304034945632
12.221304034945298
12.221304034944977
12.221304034944648
12.221304034944328
12.22130403494399
12.221304034943675
12.221304034943346
12.221304034943016
12.221304034942692
12.221304034942374
12.221304034942042
12.221304034941722
12.221304034941397
12.221304034941067
12.221304034940736
12.221304034940422
12.221304034940083
12.221304034939767
12.221304034939433
12.221304034939111
12.22130403493879
12.221304034938461
12.221304034938136
12.22130403493781
12.221304034937488
12.221304034937164
12.221304034936836
12.221304034936507
12.221304034936185
12.221304034935857
12.221304034935537
12.221304034935207
12.221304034934894
12.221304034934562
12.221304034934244
12.221304034933913
12.22130403493359
12.221304034933274
12.221304034932945
12.221304034932617
12.221304034932295
12.221304034931968
12.22130403493165
12.221304034931325
12.221304034930997
12.221304034930679
12.221304034930359
12.22130403493003
12.221304034929702
12.221304034929382
12.22130403492906
12.221304034928737
12.22130403492841
12.221304034928098
12.221304034927767
12.221304034927446
12.221304034927117
12.221304034926806
12.221304034926472
12.22130403492616
12.221304034925836
12.221304034925513
12.221304034925188
12.221304034924866
12.22130403492455
12.221304034924223
12.221304034923902
12.221304034923573
12.221304034923254
12.22130403492293
12.221304034922612
12.221304034922289
12.221304034921966
12.221304034921646
12.221304034921324
12.221304034921006
12.221304034920681
12.221304034920363
12.221304034920045
12.221304034919715
12.221304034919394
12.221304034919076
12.221304034918758
12.221304034918436
12.221304034918111
12.221304034917795
12.221304034917473
12.221304034917152
12.221304034916832
12.221304034916512
12.221304034916194
12.221304034915873
12.221304034915553
12.221304034915226
12.22130403491491
12.221304034914581
12.221304034914267
12.221304034913949
12.22130403491363
12.221304034913311
12.221304034912992
12.221304034912672
12.221304034912349
12.221304034912029
12.22130403491171
12.221304034911396
12.22130403491108
12.22130403491075
12.221304034910434
12.221304034910117
12.2213040349098
12.221304034909481
12.221304034909165
12.221304034908837
12.221304034908517
12.221304034908202
12.221304034907885
12.22130403490757
12.221304034907254
12.221304034906925
12.221304034906613
12.221304034906298
12.221304034905978
12.221304034905659
12.221304034905346
12.221304034905012
12.221304034904705
12.221304034904387
12.221304034904069
12.221304034903747
12.221304034903433
12.221304034903113
12.221304034902806
12.221304034902483
12.221304034902158
12.221304034901847
12.221304034901529
12.22130403490121
12.221304034900896
12.221304034900577
12.22130403490026
12.221304034899942
12.221304034899633
12.22130403489931
12.221304034898994
12.221304034898676
12.221304034898361
12.221304034898049
12.221304034897726
12.221304034897415
12.221304034897086
12.221304034896782
12.22130403489646
12.221304034896148
12.22130403489583
12.221304034895518
12.221304034895203
12.221304034894876
12.221304034894567
12.221304034894262
12.22130403489394
12.221304034893624
12.221304034893306
12.221304034892992
12.221304034892675
12.221304034892357
12.221304034892047
12.221304034891729
12.221304034891416
12.221304034891098
12.22130403489078
12.221304034890471
12.22130403489016
12.221304034889837
12.221304034889531
12.221304034889211
12.221304034888893
12.221304034888579
12.221304034888277
12.221304034887957
12.221304034887638
12.221304034887327
12.22130403488701
12.2213040348867
12.221304034886384
12.221304034886069
12.221304034885753
12.221304034885435
12.221304034885137
12.221304034884815
12.221304034884508
12.221304034884191
12.22130403488387
12.22130403488356
12.221304034883248
12.221304034882937
12.22130403488262
12.221304034882316
12.221304034881996
12.221304034881685
12.221304034881374
12.22130403488106
12.221304034880745
12.221304034880433
12.221304034880124
12.221304034879804
12.221304034879495
12.22130403487918
12.221304034878868
12.221304034878557
12.221304034878248
12.221304034877935
12.22130403487762
12.221304034877308
12.221304034876999
12.221304034876688
12.221304034876376
12.22130403487607
12.22130403487575
12.221304034875438
12.221304034875125
12.221304034874818
12.221304034874503
12.221304034874196
12.221304034873882
12.22130403487357
12.221304034873267
12.221304034872958
12.221304034872631
12.221304034872329
12.221304034872018
12.221304034871709
12.221304034871398
12.22130403487109
12.221304034870773
12.22130403487046
12.221304034870153
12.22130403486984
12.221304034869535
12.221304034869222
12.221304034868915
12.22130403486861
12.221304034868293
12.221304034867984
12.22130403486767
12.221304034867364
12.221304034867055
12.221304034866742
12.221304034866433
12.221304034866124
12.22130403486582
12.22130403486551
12.221304034865199
12.221304034864884
12.221304034864579
12.22130403486427
12.221304034863964
12.22130403486365
12.22130403486334
12.22130403486303
12.221304034862728
12.221304034862413
12.221304034862108
12.221304034861797
12.221304034861493
12.221304034861177
12.221304034860875
12.221304034860571
12.221304034860257
12.221304034859951
12.221304034859639
12.221304034859337
12.221304034859033
12.221304034858727
12.221304034858402
12.221304034858099
12.221304034857795
12.221304034857484
12.22130403485718
12.221304034856873
12.221304034856564
12.221304034856258
12.221304034855947
12.221304034855638
12.221304034855338
12.221304034855025
12.221304034854722
12.22130403485442
12.221304034854114
12.221304034853796
12.221304034853496
12.221304034853194
12.221304034852876
12.221304034852574
12.221304034852267
12.221304034851952
12.221304034851652
12.221304034851352
12.221304034851046
12.221304034850736
12.221304034850425
12.221304034850125
12.221304034849815
12.221304034849512
12.221304034849213
12.221304034848899
12.221304034848599
12.221304034848286
12.221304034847982
12.221304034847687
12.221304034847371
12.221304034847071
12.221304034846765
12.221304034846451
12.221304034846149
12.221304034845845
12.221304034845542
12.221304034845236
12.22130403484493
12.221304034844623
12.221304034844325
12.221304034844016
12.221304034843714
12.221304034843403
12.221304034843099
12.2213040348428
12.2213040348425
12.221304034842193
12.221304034841888
12.221304034841577
12.221304034841278
12.221304034840971
12.22130403484067
12.221304034840372
12.221304034840061
12.221304034839758
12.221304034839456
12.221304034839152
12.221304034838845
12.221304034838543
12.221304034838244
12.221304034837935
12.22130403483763
12.221304034837333
12.221304034837031
12.221304034836724
12.221304034836422
12.221304034836121
12.22130403483581
12.221304034835509
12.221304034835212
12.221304034834908
12.221304034834603
12.2213040348343
12.221304034833997
12.221304034833697
12.221304034833398
12.221304034833093
12.221304034832782
12.221304034832484
12.221304034832189
12.22130403483188
12.221304034831585
12.221304034831281
12.221304034830979
12.221304034830677
12.221304034830371
12.221304034830071
12.22130403482977
12.221304034829469
12.22130403482917
12.221304034828867
12.221304034828565
12.22130403482826
12.221304034827964
12.221304034827659
12.221304034827359
12.221304034827062
12.221304034826764
12.221304034826456
12.221304034826154
12.221304034825861
12.221304034825557
12.221304034825247
12.221304034824959
12.221304034824655

12.221304034824357
12.221304034824051
12.22130403482375
12.221304034823454
12.221304034823152
12.221304034822843
12.221304034822547
12.221304034822248
12.221304034821948
12.221304034821653
12.221304034821351
12.221304034821049
12.221304034820752
12.22130403482045
12.221304034820152
12.221304034819854
12.221304034819552
12.221304034819262
12.221304034818957
12.221304034818656
12.221304034818367
12.22130403481806
12.221304034817758
12.22130403481746
12.22130403481716
12.221304034816864
12.221304034816562
12.221304034816269
12.221304034815965
12.221304034815667
12.221304034815368
12.22130403481508
12.221304034814777
12.221304034814473
12.221304034814176
12.221304034813876
12.221304034813581
12.221304034813276
12.22130403481298
12.221304034812686
12.221304034812388
12.221304034812091
12.221304034811787
12.221304034811494
12.221304034811201
12.221304034810899
12.221304034810608
12.22130403481031
12.221304034810002
12.221304034809716
12.221304034809412
12.22130403480912
12.221304034808817
12.221304034808524
12.221304034808227
12.22130403480793
12.221304034807638
12.22130403480734
12.221304034807037
12.22130403480674
12.221304034806446
12.221304034806149
12.221304034805849
12.221304034805554
12.22130403480526
12.221304034804962
12.22130403480467
12.221304034804373
12.221304034804074
12.22130403480378
12.221304034803483
12.221304034803184
12.221304034802893
12.221304034802602
12.221304034802301
12.221304034802001
12.22130403480171
12.221304034801413
12.221304034801118
12.221304034800824
12.221304034800529
12.22130403480023
12.221304034799939
12.221304034799644
12.221304034799344
12.22130403479905
12.22130403479876
12.221304034798461
12.221304034798168
12.221304034797875
12.221304034797576
12.22130403479728
12.221304034796987
12.221304034796697
12.2213040347964
12.221304034796102
12.221304034795816
12.221304034795525
12.22130403479522
12.22130403479493
12.221304034794635
12.221304034794345
12.221304034794048
12.221304034793755
12.22130403479346
12.221304034793166
12.221304034792869
12.221304034792574
12.221304034792285
12.221304034791999
12.221304034791705
12.221304034791402
12.221304034791114
12.221304034790823
12.221304034790524
12.221304034790235
12.221304034789945
12.221304034789643
12.221304034789359
12.221304034789062
12.22130403478877
12.221304034788478
12.221304034788188
12.221304034787885
12.221304034787599
12.221304034787307
12.221304034787012
12.221304034786726
12.221304034786435
12.22130403478614
12.221304034785843
12.221304034785552
12.221304034785263
12.221304034784971
12.221304034784676
12.22130403478439
12.221304034784094
12.221304034783802
12.221304034783516
12.221304034783216
12.221304034782927
12.221304034782639
12.221304034782344
12.22130403478205
12.221304034781758
12.22130403478147
12.22130403478118
12.221304034780886
12.221304034780603
12.221304034780301
12.221304034780015
12.221304034779727
12.221304034779441
12.22130403477915
12.22130403477885
12.221304034778562
12.221304034778274
12.22130403477798
12.221304034777695
12.221304034777404
12.221304034777111
12.221304034776818
12.221304034776535
12.22130403477624
12.221304034775953
12.221304034775661
12.221304034775368
12.221304034775086
12.221304034774795
12.221304034774501
12.221304034774214
12.221304034773919
12.22130403477363
12.221304034773343
12.221304034773059
12.221304034772764
12.221304034772475
12.22130403477218
12.221304034771903
12.221304034771613
12.221304034771324
12.221304034771034
12.221304034770746
12.22130403477046
12.221304034770167
12.221304034769876
12.221304034769584
12.2213040347693
12.221304034769009
12.221304034768727
12.221304034768442
12.221304034768147
12.221304034767856
12.22130403476757
12.221304034767282
12.221304034767
12.221304034766709
12.221304034766419
12.221304034766135
12.221304034765843
12.221304034765554
12.221304034765277
12.221304034764975
12.221304034764698
12.221304034764401
12.22130403476412
12.221304034763834
12.221304034763545
12.22130403476326
12.221304034762971
12.221304034762682
12.221304034762397
12.221304034762111
12.221304034761822
12.221304034761538
12.221304034761252
12.221304034760966
12.221304034760681
12.221304034760387
12.221304034760104
12.221304034759818
12.221304034759529
12.22130403475924
12.22130403475896
12.221304034758674
12.221304034758381
12.221304034758097
12.22130403475781
12.221304034757528
12.221304034757239
12.22130403475696
12.221304034756667
12.221304034756383
12.221304034756098
12.221304034755807
12.22130403475553
12.221304034755244
12.221304034754962
12.221304034754668
12.22130403475439
12.221304034754095
12.22130403475382
12.22130403475353
12.221304034753253
12.221304034752956
12.221304034752677
12.2213040347524
12.221304034752109
12.221304034751826
12.221304034751537
12.221304034751252
12.221304034750974
12.221304034750684
12.221304034750396
12.221304034750116
12.221304034749831
12.221304034749542
12.22130403474926
12.221304034748979
12.221304034748691
12.221304034748403
12.221304034748123
12.221304034747844
12.221304034747561
12.221304034747277
12.221304034746996
12.221304034746705
12.221304034746424
12.221304034746135
12.221304034745856
12.221304034745572
12.221304034745291
12.221304034745007
12.221304034744724
12.221304034744442
12.22130403474416
12.221304034743877
12.221304034743593
12.221304034743309
12.22130403474303
12.221304034742746
12.221304034742461
12.22130403474218
12.221304034741891
12.221304034741612
12.221304034741333
12.221304034741047
12.221304034740765
12.221304034740479
12.2213040347402
12.221304034739925
12.221304034739632
12.221304034739353
12.221304034739068
12.2213040347388
12.221304034738512
12.221304034738228
12.221304034737946
12.221304034737674
12.221304034737383
12.221304034737106
12.221304034736816
12.221304034736537
12.221304034736255
12.22130403473598
12.221304034735692
12.221304034735414
12.221304034735137
12.221304034734857
12.221304034734569
12.221304034734297
12.221304034734006
12.221304034733732
12.221304034733453
12.221304034733167
12.221304034732894
12.221304034732599
12.221304034732327
12.22130403473204
12.221304034731764
12.221304034731489
12.221304034731205
12.221304034730922
12.221304034730641
12.22130403473036
12.221304034730082
12.221304034729807
12.221304034729522
12.22130403472925
12.221304034728966
12.221304034728684
12.221304034728412
12.221304034728126
12.221304034727847
12.221304034727572
12.22130403472729
12.221304034727012
12.221304034726725
12.22130403472645
12.221304034726172
12.221304034725893
12.221304034725614
12.221304034725332
12.221304034725057
12.22130403472478
12.221304034724499
12.22130403472422
12.221304034723941
12.221304034723657
12.221304034723385
12.221304034723113
12.221304034722833
12.221304034722547
12.221304034722266
12.221304034721985
12.221304034721715
12.221304034721431
12.221304034721152
12.22130403472087
12.221304034720609
12.221304034720317
12.22130403472005
12.221304034719767
12.221304034719488
12.22130403471921
12.221304034718933
12.221304034718655
12.221304034718374
12.221304034718106
12.221304034717829
12.22130403471755
12.221304034717274
12.221304034716995
12.221304034716713
12.221304034716434
12.221304034716166
12.221304034715887
12.221304034715606
12.221304034715333
12.22130403471505
12.22130403471478
12.221304034714507
12.221304034714228
12.221304034713949
12.221304034713674
12.2213040347134
12.221304034713123
12.221304034712848
12.22130403471257
12.221304034712295
12.221304034712023
12.221304034711746
12.221304034711466
12.221304034711192
12.221304034710917
12.22130403471064
12.22130403471036
12.221304034710084
12.221304034709808
12.221304034709528
12.22130403470926
12.221304034708984
12.221304034708709
12.221304034708437
12.221304034708156
12.221304034707886
12.22130403470761
12.221304034707332
12.221304034707059
12.221304034706785
12.221304034706508
12.22130403470623
12.221304034705955
12.221304034705682
12.221304034705406
12.221304034705131
12.221304034704865
12.221304034704586
12.221304034704316
12.221304034704042
12.221304034703763
12.221304034703486
12.221304034703218
12.221304034702944
12.221304034702664
12.221304034702396
12.221304034702124
12.221304034701848
12.22130403470156
12.221304034701289
12.221304034701026
12.221304034700752
12.221304034700479
12.221304034700202
12.221304034699926
12.221304034699664
12.221304034699385
12.221304034699106
12.221304034698834
12.221304034698559
12.221304034698289
12.221304034698019
12.221304034697747
12.221304034697463
12.221304034697196
12.221304034696928
12.22130403469665
12.221304034696383
12.221304034696105
12.221304034695835
12.22130403469556
12.22130403469529
12.221304034695013
12.221304034694743
12.221304034694477
12.221304034694203
12.221304034693928
12.221304034693661
12.22130403469338
12.221304034693112
12.22130403469284
12.22130403469258
12.221304034692295
12.221304034692029
12.221304034691753
12.221304034691482
12.221304034691212
12.221304034690936
12.221304034690668
12.221304034690398
12.221304034690126
12.221304034689854
12.221304034689584
12.221304034689318

12.22130403468904
12.221304034688771
12.221304034688497
12.221304034688224
12.221304034687964
12.221304034687684
12.221304034687412
12.221304034687147
12.221304034686877
12.221304034686607
12.22130403468633
12.221304034686067
12.221304034685796
12.22130403468552
12.221304034685254
12.221304034684987
12.22130403468471
12.221304034684438
12.221304034684172
12.221304034683905
12.221304034683627
12.221304034683358
12.221304034683094
12.221304034682824
12.221304034682559
12.221304034682289
12.221304034682014
12.221304034681744
12.221304034681479
12.2213040346812
12.221304034680937
12.221304034680664
12.221304034680395
12.22130403468013
12.221304034679855
12.221304034679589
12.221304034679319
12.221304034679052
12.221304034678791
12.221304034678512
12.221304034678251
12.221304034677976
12.22130403467771
12.221304034677438
12.221304034677173
12.221304034676905
12.221304034676635
12.221304034676367
12.221304034676102
12.221304034675832
12.221304034675564
12.221304034675295
12.221304034675022
12.221304034674754
12.22130403467449
12.221304034674223
12.22130403467395
12.221304034673688
12.22130403467342
12.22130403467315
12.221304034672885
12.221304034672622
12.221304034672347
12.221304034672087
12.221304034671816
12.221304034671542
12.221304034671274
12.221304034671014
12.221304034670748
12.22130403467048
12.221304034670215
12.221304034669942
12.221304034669679
12.221304034669405
12.221304034669147
12.221304034668876
12.221304034668615
12.22130403466835
12.221304034668071
12.22130403466781
12.221304034667543
12.221304034667279
12.22130403466701
12.221304034666748
12.221304034666485
12.22130403466621
12.221304034665941
12.221304034665684
12.221304034665417
12.221304034665147
12.221304034664882
12.221304034664625
12.221304034664351
12.221304034664087
12.221304034663815
12.221304034663556
12.221304034663293
12.221304034663024
12.221304034662765
12.221304034662497
12.221304034662234
12.221304034661967
12.221304034661701
12.22130403466143
12.221304034661173
12.221304034660903
12.221304034660642
12.221304034660376
12.22130403466011
12.221304034659843
12.221304034659578
12.221304034659314
12.221304034659045
12.221304034658784
12.221304034658525
12.22130403465826
12.221304034657992
12.22130403465773
12.221304034657468
12.221304034657201
12.221304034656926
12.221304034656672
12.221304034656404
12.221304034656148
12.221304034655878
12.221304034655619
12.221304034655354
12.221304034655097
12.221304034654832
12.221304034654562
12.221304034654297
12.221304034654032
12.221304034653768
12.221304034653503
12.221304034653246
12.221304034652983
12.221304034652722
12.221304034652452
12.221304034652192
12.221304034651931
12.221304034651672
12.221304034651405
12.221304034651142
12.221304034650881
12.221304034650622
12.22130403465035
12.22130403465009
12.221304034649828
12.221304034649565
12.221304034649306
12.22130403464904
12.221304034648783
12.221304034648517
12.22130403464825
12.22130403464799
12.221304034647728
12.221304034647464
12.221304034647199
12.221304034646947
12.221304034646685
12.22130403464642
12.221304034646163
12.221304034645893
12.22130403464564
12.221304034645378
12.221304034645115
12.221304034644854
12.221304034644591
12.221304034644321
12.221304034644074
12.221304034643806
12.221304034643548
12.221304034643282
12.22130403464302
12.22130403464276
12.221304034642499
12.221304034642232
12.221304034641971
12.221304034641715
12.22130403464145
12.221304034641184
12.221304034640932
12.221304034640674
12.221304034640415
12.221304034640156
12.221304034639896
12.221304034639632
12.221304034639378
12.221304034639111
12.221304034638852
12.221304034638594
12.221304034638338
12.221304034638075
12.221304034637816
12.221304034637546
12.221304034637292
12.221304034637031
12.221304034636772
12.22130403463651
12.221304034636253
12.221304034635994
12.221304034635734
12.221304034635473
12.221304034635216
12.221304034634958
12.221304034634699
12.221304034634436
12.221304034634183
12.221304034633919
12.221304034633661
12.221304034633402
12.221304034633143
12.221304034632887
12.221304034632622
12.221304034632366
12.221304034632109
12.221304034631855
12.221304034631586
12.221304034631334
12.221304034631078
12.221304034630823
12.22130403463056
12.221304034630297
12.221304034630043
12.22130403462979
12.221304034629526
12.221304034629267
12.221304034629012
12.221304034628748
12.221304034628487
12.221304034628234
12.221304034627975
12.22130403462772
12.221304034627455
12.221304034627211
12.221304034626938
12.22130403462669
12.221304034626431
12.221304034626174
12.221304034625913
12.221304034625662
12.221304034625401
12.221304034625147
12.22130403462489
12.221304034624628
12.221304034624369
12.221304034624117
12.221304034623861
12.221304034623609
12.221304034623348
12.22130403462309
12.221304034622836
12.221304034622582
12.221304034622326
12.221304034622067
12.221304034621808
12.221304034621548
12.22130403462129
12.221304034621038
12.221304034620777
12.221304034620523
12.221304034620275
12.221304034620012
12.22130403461976
12.2213040346195
12.221304034619246
12.221304034618983
12.22130403461873
12.221304034618479
12.221304034618218
12.221304034617958
12.22130403461771
12.22130403461746
12.221304034617194
12.221304034616946
12.221304034616693
12.221304034616429
12.221304034616178
12.221304034615919
12.221304034615663
12.22130403461542
12.221304034615153
12.221304034614906
12.22130403461465
12.221304034614384
12.221304034614137
12.221304034613887
12.221304034613627
12.221304034613372
12.221304034613112
12.221304034612864
12.221304034612613
12.221304034612356
12.221304034612102
12.221304034611846
12.221304034611594
12.221304034611338
12.221304034611089
12.22130403461083
12.221304034610572
12.221304034610322
12.221304034610073
12.221304034609815
12.221304034609563
12.221304034609311
12.221304034609053
12.221304034608798
12.221304034608544
12.22130403460829
12.221304034608043
12.221304034607785
12.221304034607536
12.221304034607273
12.221304034607023
12.22130403460677
12.221304034606526
12.221304034606273
12.221304034606014
12.221304034605758
12.221304034605513
12.221304034605255
12.221304034605005
12.221304034604746
12.221304034604502
12.221304034604241
12.221304034603987
12.221304034603742
12.221304034603483
12.221304034603245
12.22130403460298
12.221304034602726
12.221304034602477
12.221304034602221
12.221304034601967
12.221304034601717
12.221304034601465
12.22130403460121
12.221304034600958
12.221304034600708
12.221304034600463
12.221304034600209
12.221304034599951
12.221304034599708
12.22130403459945
12.221304034599202
12.22130403459895
12.221304034598704
12.22130403459844
12.221304034598198
12.22130403459794
12.221304034597692
12.221304034597445
12.221304034597198
12.22130403459694
12.22130403459669
12.221304034596438
12.221304034596189
12.221304034595939
12.221304034595686
12.221304034595438
12.221304034595189
12.221304034594931
12.221304034594684
12.221304034594429
12.221304034594187
12.22130403459393
12.221304034593684
12.221304034593429
12.221304034593178
12.221304034592935
12.221304034592672
12.221304034592432
12.221304034592183
12.221304034591936
12.221304034591682
12.221304034591435
12.221304034591183
12.221304034590933
12.221304034590684
12.221304034590434
12.221304034590181
12.221304034589926
12.221304034589686
12.221304034589433
12.221304034589181
12.221304034588934
12.221304034588686
12.221304034588435
12.221304034588192
12.221304034587938
12.221304034587684
12.221304034587439
12.221304034587193
12.221304034586943
12.2213040345867
12.221304034586444
12.22130403458619
12.221304034585943
12.221304034585696
12.221304034585453
12.221304034585206
12.221304034584952
12.221304034584703
12.221304034584454
12.221304034584206
12.221304034583962
12.221304034583715
12.221304034583465
12.221304034583213
12.221304034582971
12.221304034582714
12.221304034582472
12.221304034582221
12.221304034581982
12.221304034581731
12.22130403458148
12.22130403458123
12.221304034580982
12.221304034580738
12.221304034580484
12.221304034580246
12.221304034579997
12.221304034579752
12.221304034579495
12.221304034579255
12.221304034579006
12.22130403457876
12.221304034578512
12.221304034578264
12.221304034578022
12.221304034577768
12.221304034577514
12.22130403457728
12.221304034577027
12.22130403457678
12.221304034576537
12.221304034576285
12.221304034576045
12.221304034575788
12.221304034575553
12.221304034575306
12.221304034575061
12.221304034574814
12.221304034574569
12.221304034574324
12.221304034574068
12.221304034573826
12.22130403457358
12.221304034573329
12.221304034573091
12.221304034572842
12.2213040345726
12.22130403457235
12.22130403457211
12.221304034571858
12.22130403457162
12.221304034571368
12.221304034571125
12.22130403457088
12.221304034570638
12.221304034570387
12.221304034570144
12.221304034569895
12.22130403456965
12.221304034569409
12.22130403456916
12.221304034568924
12.221304034568673
12.221304034568428
12.221304034568183
12.22130403456794
12.221304034567693
12.22130403456745
12.221304034567206
12.221304034566954
12.221304034566707
12.221304034566476
12.221304034566224
12.22130403456598
12.22130403456574
12.221304034565494
12.221304034565255
12.221304034565009
12.221304034564769

12.221304034564517
12.22130403456427
12.221304034564028
12.221304034563783
12.22130403456354
12.221304034563303
12.221304034563055
12.221304034562808
12.221304034562568
12.221304034562325
12.221304034562086
12.221304034561834
12.22130403456159
12.221304034561353
12.221304034561106
12.221304034560859
12.221304034560623
12.221304034560376
12.221304034560136
12.221304034559893
12.22130403455965
12.221304034559402
12.22130403455916
12.22130403455892
12.221304034558678
12.22130403455844
12.221304034558191
12.221304034557944
12.221304034557704
12.221304034557459
12.22130403455722
12.221304034556981
12.221304034556743
12.221304034556496
12.221304034556251
12.221304034556013
12.221304034555764
12.22130403455553
12.221304034555285
12.221304034555043
12.221304034554805
12.221304034554556
12.221304034554308
12.221304034554073
12.221304034553837
12.221304034553585
12.221304034553349
12.221304034553105
12.221304034552862
12.221304034552626
12.221304034552382
12.221304034552144
12.221304034551903
12.221304034551654
12.221304034551418
12.22130403455118
12.221304034550938
12.221304034550695
12.221304034550457
12.22130403455022
12.221304034549972
12.221304034549728
12.22130403454948
12.221304034549247
12.221304034549004
12.22130403454877
12.221304034548536
12.221304034548288
12.221304034548043
12.221304034547806
12.22130403454756
12.221304034547328
12.221304034547085
12.221304034546849
12.221304034546604
12.221304034546366
12.221304034546126
12.221304034545883
12.221304034545643
12.221304034545401
12.221304034545165
12.221304034544927
12.221304034544684
12.221304034544447
12.2213040345442
12.221304034543968
12.22130403454373
12.221304034543484
12.221304034543243
12.22130403454301
12.221304034542772
12.221304034542527
12.221304034542293
12.221304034542056
12.221304034541815
12.221304034541571
12.221304034541335
12.221304034541092
12.221304034540859
12.221304034540614
12.221304034540385
12.221304034540143
12.221304034539907
12.221304034539664
12.221304034539424
12.221304034539186
12.221304034538946
12.221304034538704
12.221304034538475
12.221304034538234
12.221304034537992
12.221304034537757
12.221304034537518
12.221304034537285
12.221304034537038
12.221304034536805
12.221304034536564
12.221304034536326
12.221304034536091
12.221304034535853
12.221304034535615
12.221304034535374
12.221304034535144
12.221304034534898
12.221304034534668
12.221304034534427
12.221304034534189
12.221304034533956
12.221304034533714
12.221304034533476
12.221304034533242
12.221304034533006
12.221304034532768
12.221304034532531
12.22130403453229
12.221304034532054
12.221304034531824
12.221304034531583
12.22130403453135
12.221304034531109
12.221304034530867
12.221304034530633
12.221304034530396
12.221304034530156
12.221304034529927
12.221304034529684
12.221304034529448
12.221304034529213
12.221304034528982
12.221304034528742
12.22130403452851
12.22130403452827
12.221304034528028
12.2213040345278
12.221304034527561
12.221304034527328
12.22130403452709
12.221304034526852
12.221304034526613
12.221304034526387
12.221304034526149
12.221304034525915
12.221304034525678
12.221304034525437
12.221304034525206
12.221304034524968
12.221304034524735
12.221304034524495
12.221304034524264
12.221304034524033
12.221304034523799
12.221304034523557
12.221304034523314
12.22130403452309
12.221304034522856
12.221304034522618
12.221304034522383
12.221304034522152
12.221304034521918
12.221304034521678
12.221304034521442
12.221304034521214
12.221304034520971
12.221304034520744
12.221304034520507
12.221304034520271
12.221304034520037
12.221304034519804
12.22130403451957
12.221304034519337
12.221304034519097
12.221304034518868
12.221304034518631
12.221304034518399
12.221304034518157
12.221304034517924
12.2213040345177
12.22130403451746
12.221304034517228
12.221304034516997
12.221304034516763
12.221304034516526
12.221304034516292
12.221304034516065
12.22130403451583
12.221304034515592
12.221304034515356
12.221304034515123
12.221304034514901
12.22130403451466
12.221304034514429
12.221304034514198
12.221304034513958
12.221304034513727
12.2213040345135
12.22130403451326
12.221304034513029
12.221304034512798
12.221304034512563
12.221304034512327
12.221304034512093
12.221304034511864
12.221304034511636
12.221304034511402
12.22130403451117
12.221304034510942
12.221304034510712
12.22130403451047
12.221304034510238
12.221304034510007
12.221304034509776
12.221304034509538
12.22130403450931
12.221304034509071
12.221304034508842
12.221304034508611
12.221304034508387
12.22130403450815
12.221304034507918
12.221304034507687
12.22130403450746
12.221304034507224
12.221304034507
12.221304034506758
12.221304034506531
12.221304034506295
12.221304034506069
12.221304034505833
12.2213040345056
12.221304034505373
12.221304034505142
12.221304034504909
12.22130403450468
12.22130403450445
12.221304034504218
12.221304034503989
12.221304034503754
12.22130403450352
12.221304034503298
12.221304034503069
12.221304034502836
12.221304034502607
12.221304034502369
12.221304034502145
12.221304034501909
12.221304034501678
12.221304034501449
12.221304034501221
12.221304034500987
12.22130403450076
12.221304034500534
12.221304034500301
12.221304034500065
12.221304034499836
12.221304034499607
12.22130403449938
12.221304034499163
12.221304034498921
12.221304034498692
12.221304034498461
12.221304034498234
12.221304034497999
12.22130403449777
12.221304034497543
12.221304034497313
12.221304034497075
12.22130403449685
12.221304034496628
12.221304034496397
12.221304034496168
12.221304034495935
12.221304034495706
12.221304034495478
12.221304034495251
12.22130403449502
12.221304034494795
12.22130403449457
12.221304034494336
12.221304034494102
12.221304034493881
12.22130403449364
12.221304034493423
12.221304034493194
12.221304034492963
12.221304034492736
12.221304034492507
12.221304034492274
12.221304034492054
12.221304034491817
12.221304034491595
12.221304034491357
12.221304034491135
12.22130403449091
12.22130403449068
12.221304034490455
12.221304034490224
12.221304034489993
12.221304034489773
12.221304034489549
12.221304034489313
12.22130403448908
12.221304034488865
12.221304034488636
12.221304034488405
12.221304034488176
12.221304034487948
12.22130403448772
12.221304034487492
12.221304034487263
12.221304034487039
12.221304034486812
12.221304034486586
12.221304034486359
12.221304034486128
12.221304034485902
12.221304034485675
12.221304034485449
12.221304034485222
12.221304034484996
12.221304034484774
12.221304034484541
12.221304034484316
12.22130403448409
12.221304034483868
12.221304034483632
12.221304034483412
12.22130403448319
12.22130403448296
12.221304034482731
12.221304034482504
12.221304034482277
12.221304034482056
12.221304034481822
12.221304034481598
12.22130403448137
12.22130403448114
12.221304034480927
12.2213040344807
12.221304034480472
12.221304034480243
12.221304034480015
12.221304034479795
12.221304034479568
12.22130403447935
12.221304034479124
12.221304034478887
12.221304034478669
12.22130403447844
12.221304034478218
12.221304034477992
12.22130403447777
12.221304034477546
12.221304034477315
12.221304034477093
12.221304034476868
12.221304034476644
12.22130403447641
12.22130403447619
12.221304034475974
12.22130403447574
12.221304034475512
12.221304034475294
12.221304034475072
12.221304034474853
12.221304034474613
12.221304034474395
12.22130403447416
12.221304034473949
12.221304034473727
12.221304034473494
12.221304034473274
12.221304034473055
12.221304034472825
12.221304034472597
12.221304034472382
12.221304034472157
12.221304034471927
12.221304034471709
12.221304034471482
12.22130403447126
12.221304034471032
12.221304034470814
12.221304034470586
12.221304034470363
12.221304034470137
12.221304034469917
12.221304034469698
12.221304034469474
12.221304034469249
12.221304034469025
12.2213040344688
12.221304034468579
12.221304034468348
12.221304034468126
12.221304034467906
12.221304034467686
12.221304034467462
12.221304034467233
12.221304034467012
12.221304034466787
12.221304034466572
12.221304034466343
12.22130403446612
12.221304034465904
12.221304034465684
12.221304034465462
12.221304034465229
12.221304034465012
12.221304034464788
12.221304034464568
12.221304034464344
12.221304034464124
12.221304034463904
12.22130403446367
12.22130403446346
12.221304034463241
12.221304034463017
12.221304034462783
12.22130403446257
12.221304034462348
12.22130403446212
12.221304034461902
12.221304034461678
12.22130403446146
12.221304034461236
12.221304034461017
12.221304034460791
12.22130403446057
12.221304034460351
12.22130403446013
12.22130403445991
12.22130403445968
12.221304034459463
12.221304034459246
12.22130403445903
12.221304034458798
12.221304034458585
12.22130403445836
12.22130403445814
12.221304034457917
12.221304034457697
12.221304034457477
12.221304034457258
12.221304034457043
12.221304034456814
12.221304034456589
12.221304034456377
12.221304034456152
12.22130403445593
12.221304034455715
12.221304034455493
12.221304034455267
12.221304034455054
12.221304034454832
12.221304034454619
12.221304034454393
12.221304034454173
12.221304034453954
12.221304034453734
12.221304034453514
12.221304034453293
12.221304034453071
12.221304034452853
12.22130403445263
12.221304034452418
12.221304034452192
12.221304034451975
12.221304034451755
12.221304034451524
12.221304034451311
12.221304034451094

12.221304034450874
12.221304034450657
12.221304034450439
12.221304034450219
12.22130403445
12.22130403444978
12.221304034449558
12.221304034449346
12.22130403444912
12.221304034448908
12.22130403444868
12.221304034448469
12.221304034448245
12.221304034448025
12.22130403444781
12.221304034447591
12.221304034447373
12.221304034447154
12.221304034446936
12.221304034446716
12.221304034446499
12.221304034446277
12.221304034446062
12.221304034445843
12.221304034445629
12.221304034445408
12.221304034445188
12.22130403444497
12.221304034444756
12.22130403444453
12.221304034444316
12.221304034444106
12.221304034443879
12.221304034443664
12.221304034443445
12.221304034443232
12.22130403444301
12.221304034442799
12.221304034442573
12.22130403444236
12.22130403444214
12.221304034441925
12.221304034441705
12.221304034441484
12.22130403444127
12.221304034441058
12.221304034440843
12.221304034440626
12.221304034440397
12.221304034440184
12.221304034439965
12.221304034439745
12.22130403443954
12.221304034439319
12.221304034439099
12.221304034438885
12.221304034438672
12.221304034438443
12.221304034438232
12.221304034438019
12.221304034437802
12.22130403443758
12.221304034437365
12.221304034437152
12.221304034436937
12.221304034436715
12.221304034436503
12.221304034436287
12.22130403443607
12.221304034435855
12.221304034435637
12.221304034435422
12.221304034435212
12.221304034434997
12.221304034434777
12.221304034434558
12.221304034434345
12.221304034434125
12.221304034433917
12.2213040344337
12.221304034433482
12.221304034433267
12.22130403443305
12.221304034432833
12.221304034432615
12.221304034432405
12.221304034432189
12.221304034431975
12.221304034431759
12.221304034431546
12.22130403443133
12.221304034431107
12.221304034430899
12.22130403443068
12.221304034430464
12.221304034430249
12.221304034430041
12.221304034429822
12.221304034429608
12.221304034429398
12.221304034429181
12.221304034428972
12.221304034428753
12.221304034428533
12.221304034428318
12.221304034428112
12.22130403442789
12.221304034427682
12.221304034427467
12.221304034427243
12.221304034427037
12.221304034426822
12.221304034426604
12.221304034426392
12.221304034426183
12.221304034425968
12.221304034425748
12.221304034425538
12.221304034425323
12.22130403442511
12.221304034424897
12.221304034424689
12.221304034424465
12.221304034424255
12.22130403442404
12.221304034423824
12.221304034423612
12.221304034423396
12.221304034423191
12.221304034422971
12.221304034422758
12.221304034422543
12.221304034422337
12.221304034422118
12.221304034421914
12.22130403442169
12.22130403442148
12.221304034421266
12.221304034421056
12.22130403442085
12.221304034420633
12.22130403442042
12.221304034420205
12.221304034419994
12.22130403441978
12.221304034419571
12.221304034419353
12.221304034419143
12.22130403441893
12.22130403441872
12.221304034418505
12.2213040344183
12.221304034418079
12.221304034417864
12.221304034417658
12.221304034417448
12.221304034417232
12.22130403441702
12.221304034416807
12.2213040344166
12.221304034416383
12.221304034416175
12.22130403441596
12.221304034415747
12.22130403441554
12.221304034415322
12.221304034415118
12.221304034414908
12.221304034414691
12.22130403441448
12.221304034414265
12.221304034414054
12.221304034413835
12.221304034413633
12.221304034413428
12.221304034413212
12.221304034413
12.221304034412787
12.22130403441258
12.221304034412372
12.221304034412157
12.221304034411949
12.221304034411734
12.221304034411526
12.221304034411315
12.221304034411107
12.221304034410892
12.221304034410675
12.221304034410474
12.221304034410261
12.221304034410055
12.221304034409842
12.22130403440963
12.221304034409417
12.221304034409208
12.221304034409
12.221304034408794
12.221304034408575
12.22130403440837
12.221304034408158
12.22130403440795
12.221304034407735
12.221304034407526
12.221304034407316
12.221304034407101
12.221304034406893
12.221304034406684
12.221304034406478
12.221304034406277
12.22130403440606
12.221304034405847
12.221304034405643
12.221304034405433
12.221304034405225
12.221304034405012
12.2213040344048
12.221304034404591
12.221304034404382
12.221304034404174
12.221304034403968
12.221304034403758
12.221304034403545
12.221304034403337
12.221304034403122
12.221304034402927
12.221304034402714
12.221304034402499
12.221304034402296
12.221304034402083
12.22130403440187
12.221304034401669
12.22130403440146
12.221304034401246
12.22130403440104
12.22130403440083
12.221304034400621
12.221304034400415
12.2213040344002
12.221304034399997
12.221304034399795
12.221304034399584
12.221304034399372
12.22130403439917
12.221304034398958
12.221304034398752
12.221304034398543
12.221304034398337
12.221304034398123
12.221304034397916
12.22130403439771
12.221304034397503
12.221304034397301
12.221304034397086
12.221304034396882
12.221304034396667
12.221304034396464
12.221304034396258
12.22130403439605
12.221304034395846
12.221304034395635
12.221304034395422
12.221304034395219
12.221304034395018
12.221304034394805
12.221304034394601
12.22130403439439
12.221304034394182
12.221304034393983
12.22130403439377
12.221304034393562
12.221304034393357
12.221304034393155
12.221304034392942
12.221304034392741
12.221304034392533
12.221304034392325
12.221304034392114
12.221304034391911
12.221304034391709
12.221304034391492
12.221304034391295
12.221304034391089
12.221304034390874
12.221304034390672
12.221304034390466
12.221304034390265
12.221304034390055
12.22130403438985
12.22130403438964
12.221304034389433
12.221304034389231
12.221304034389027
12.221304034388817
12.221304034388611
12.221304034388407
12.221304034388199
12.22130403438799
12.221304034387789
12.221304034387579
12.221304034387378
12.221304034387172
12.221304034386964
12.221304034386762
12.221304034386554
12.221304034386348
12.221304034386147
12.221304034385945
12.221304034385733
12.22130403438553
12.22130403438533
12.221304034385122
12.221304034384916
12.221304034384705
12.221304034384508
12.2213040343843
12.221304034384096
12.221304034383891
12.221304034383687
12.221304034383472
12.22130403438328
12.221304034383067
12.221304034382863
12.221304034382662
12.221304034382458
12.221304034382252
12.221304034382053
12.221304034381845
12.221304034381639
12.221304034381436
12.221304034381237
12.221304034381026
12.221304034380825
12.221304034380617
12.221304034380413
12.221304034380207
12.221304034380001
12.221304034379804
12.2213040343796
12.221304034379397
12.221304034379191
12.221304034378983
12.221304034378782
12.221304034378578
12.221304034378377
12.221304034378171
12.221304034377972
12.221304034377768
12.22130403437756
12.22130403437736
12.221304034377145
12.221304034376953
12.221304034376749
12.221304034376553
12.221304034376342
12.221304034376141
12.22130403437594
12.221304034375736
12.221304034375528
12.221304034375333
12.221304034375121
12.221304034374924
12.221304034374716
12.221304034374516
12.221304034374315
12.221304034374107
12.221304034373906
12.221304034373714
12.2213040343735
12.221304034373297
12.221304034373096
12.221304034372897
12.221304034372693
12.221304034372494
12.221304034372292
12.221304034372086
12.221304034371883
12.22130403437168
12.22130403437147
12.22130403437127
12.221304034371071
12.221304034370869
12.221304034370677
12.221304034370466
12.221304034370274
12.221304034370068
12.221304034369867
12.22130403436967
12.22130403436946
12.221304034369263
12.221304034369059
12.221304034368858
12.22130403436865
12.221304034368456
12.221304034368252
12.221304034368059
12.221304034367845
12.221304034367654
12.221304034367447
12.221304034367238
12.221304034367039
12.221304034366842
12.221304034366643
12.221304034366442
12.221304034366236
12.221304034366035
12.221304034365842
12.22130403436564
12.221304034365433
12.221304034365238
12.221304034365035
12.221304034364836
12.221304034364636
12.22130403436443
12.221304034364232
12.221304034364028
12.221304034363824
12.22130403436363
12.221304034363419
12.221304034363229
12.221304034363031
12.221304034362829
12.221304034362623
12.22130403436243
12.221304034362223
12.221304034362028
12.22130403436183
12.221304034361628
12.221304034361431
12.221304034361227
12.221304034361028
12.22130403436083
12.221304034360625
12.221304034360431
12.221304034360228
12.22130403436003
12.22130403435984
12.221304034359637
12.221304034359434
12.221304034359234
12.221304034359035
12.221304034358834
12.221304034358633
12.221304034358438
12.22130403435824
12.221304034358038
12.221304034357841
12.22130403435764
12.221304034357441
12.221304034357239
12.22130403435705
12.221304034356839
12.221304034356642
12.221304034356447
12.221304034356248
12.221304034356049
12.221304034355851
12.221304034355647
12.221304034355455
12.221304034355253
12.221304034355063
12.221304034354853
12.221304034354656
12.22130403435446
12.221304034354258
12.221304034354057
12.221304034353865
12.22130403435367
12.22130403435346
12.221304034353269
12.221304034353068
12.221304034352872
12.221304034352672
12.22130403435247
12.221304034352277
12.221304034352086
12.221304034351883
12.22130403435169
12.221304034351487
12.221304034351293
12.22130403435109
12.221304034350894
12.2213040343507
12.221304034350503
12.221304034350302
12.221304034350105
12.221304034349911
12.221304034349712
12.221304034349513
12.221304034349322
12.221304034349115
12.221304034348924
12.221304034348728
12.221304034348524
12.221304034348329
12.221304034348128
12.221304034347934
12.221304034347732
12.221304034347538
12.221304034347341
12.22130403434714
12.221304034346947
12.22130403434675
12.221304034346558
12.221304034346367
12.221304034346163
12.221304034345971
12.221304034345776
12.221304034345566
12.221304034345376
12.221304034345184
12.221304034344978
12.221304034344788
12.221304034344595
12.221304034344403
12.221304034344197
12.221304034344007
12.221304034343811
12.22130403434361
12.22130403434342
12.22130403434322
12.221304034343028
12.221304034342836
12.221304034342632
12.221304034342433
12.221304034342241
12.221304034342047
12.221304034341848
12.221304034341653
12.22130403434146
12.221304034341259
12.221304034341077
12.221304034340868
12.221304034340676
12.221304034340479
12.221304034340289
12.221304034340084
12.221304034339903
12.221304034339704
12.221304034339504
12.221304034339305
12.22130403433912
12.221304034338921
12.221304034338718
12.221304034338527
12.221304034338337
12.221304034338141
12.221304034337944
12.221304034337756
12.22130403433755
12.221304034337356
12.221304034337166
12.221304034336972
12.221304034336775
12.221304034336574
12.221304034336388
12.221304034336189
12.221304034335994
12.221304034335802
12.221304034335608
12.221304034335414
12.221304034335224
12.22130403433503
12.221304034334832
12.221304034334642
12.221304034334446
12.221304034334253
12.221304034334057
12.221304034333869
12.221304034333663
12.221304034333475
12.221304034333277
12.221304034333086
12.221304034332896
12.221304034332704
12.22130403433251
12.221304034332316
12.221304034332118
12.221304034331922
12.221304034331734
12.221304034331538

12.221304034331348
12.221304034331153
12.221304034330952
12.221304034330768
12.221304034330572
12.221304034330377
12.221304034330188
12.221304034329988
12.221304034329798
12.221304034329606
12.221304034329412
12.221304034329222
12.221304034329034
12.221304034328835
12.221304034328645
12.221304034328448
12.221304034328256
12.221304034328066
12.22130403432787
12.22130403432768
12.221304034327487
12.221304034327295
12.2213040343271
12.221304034326906
12.221304034326709
12.221304034326524
12.221304034326334
12.221304034326142
12.221304034325945
12.221304034325751
12.221304034325561
12.221304034325373
12.221304034325176
12.221304034324984
12.221304034324795
12.2213040343246
12.221304034324415
12.221304034324216
12.221304034324023
12.221304034323834
12.22130403432364
12.221304034323447
12.221304034323259
12.22130403432307
12.221304034322873
12.221304034322682
12.221304034322497
12.221304034322307
12.221304034322106
12.22130403432192
12.221304034321733
12.22130403432154
12.22130403432135
12.22130403432115
12.22130403432097
12.221304034320776
12.221304034320584
12.221304034320392
12.221304034320198
12.221304034320006
12.22130403431981
12.22130403431962
12.221304034319436
12.221304034319248
12.221304034319054
12.221304034318852
12.221304034318665
12.221304034318484
12.221304034318296
12.2213040343181
12.221304034317917
12.221304034317717
12.22130403431753
12.221304034317345
12.221304034317146
12.221304034316958
12.221304034316768
12.22130403431657
12.221304034316391
12.221304034316201
12.221304034316015
12.221304034315818
12.221304034315626
12.221304034315438
12.221304034315251
12.221304034315063
12.221304034314871
12.221304034314674
12.221304034314485
12.221304034314302
12.221304034314109
12.221304034313924
12.221304034313725
12.221304034313535
12.221304034313347
12.221304034313157
12.221304034312974
12.221304034312782
12.221304034312595
12.221304034312404
12.22130403431221
12.221304034312023
12.221304034311839
12.221304034311649
12.221304034311453
12.22130403431127
12.221304034311075
12.22130403431089
12.221304034310702
12.221304034310512
12.221304034310322
12.221304034310135
12.221304034309943
12.221304034309759
12.221304034309574
12.221304034309378
12.221304034309188
12.221304034309002
12.221304034308817
12.221304034308629
12.221304034308444
12.221304034308249
12.221304034308062
12.22130403430787
12.221304034307682
12.221304034307494
12.221304034307305
12.221304034307119
12.221304034306925
12.221304034306746
12.221304034306554
12.221304034306362
12.221304034306181
12.221304034305993
12.221304034305806
12.221304034305623
12.22130403430543
12.221304034305243
12.221304034305055
12.22130403430486
12.221304034304676
12.221304034304493
12.221304034304307
12.221304034304117
12.221304034303921
12.221304034303737
12.22130403430355
12.22130403430337
12.221304034303179
12.221304034302994
12.2213040343028
12.221304034302618
12.221304034302424
12.22130403430224
12.22130403430205
12.221304034301866
12.221304034301681
12.221304034301498
12.221304034301303
12.221304034301118
12.221304034300934
12.221304034300745
12.221304034300562
12.221304034300372
12.221304034300188
12.221304034299996
12.221304034299811
12.22130403429962
12.221304034299445
12.22130403429925
12.221304034299067
12.221304034298884
12.221304034298694
12.221304034298516
12.221304034298324
12.221304034298138
12.221304034297953
12.221304034297766
12.22130403429758
12.221304034297393
12.221304034297203
12.221304034297022
12.221304034296836
12.221304034296647
12.221304034296466
12.221304034296278
12.221304034296084
12.221304034295905
12.221304034295718
12.221304034295539
12.221304034295338
12.221304034295171
12.221304034294976
12.221304034294793
12.22130403429461
12.221304034294421
12.22130403429424
12.22130403429405
12.221304034293873
12.221304034293679
12.221304034293496
12.221304034293306
12.22130403429312
12.22130403429294
12.221304034292748
12.221304034292569
12.221304034292379
12.2213040342922
12.221304034292013
12.221304034291823
12.221304034291641
12.22130403429146
12.221304034291276
12.221304034291094
12.221304034290911
12.221304034290725
12.221304034290544
12.221304034290352
12.22130403429017
12.22130403428998
12.2213040342898
12.221304034289616
12.221304034289428
12.221304034289247
12.221304034289068
12.221304034288874
12.221304034288694
12.221304034288508
12.221304034288327
12.221304034288142
12.221304034287959
12.221304034287774
12.221304034287584
12.221304034287401
12.221304034287225
12.22130403428704
12.221304034286858
12.221304034286668
12.22130403428649
12.221304034286302
12.22130403428612
12.221304034285936
12.221304034285755
12.221304034285568
12.221304034285389
12.221304034285206
12.22130403428502
12.221304034284834
12.221304034284652
12.221304034284474
12.221304034284278
12.221304034284104
12.221304034283916
12.221304034283738
12.221304034283557
12.221304034283373
12.221304034283186
12.221304034283012
12.22130403428283
12.221304034282639
12.221304034282456
12.221304034282268
12.221304034282097
12.221304034281903
12.221304034281735
12.22130403428154
12.221304034281365
12.221304034281182
12.221304034280992
12.221304034280811
12.221304034280628
12.221304034280445
12.22130403428026
12.221304034280083
12.221304034279898
12.22130403427972
12.221304034279543
12.22130403427935
12.221304034279182
12.22130403427899
12.22130403427882
12.221304034278626
12.221304034278456
12.221304034278264
12.221304034278079
12.221304034277908
12.221304034277715
12.221304034277537
12.221304034277356
12.221304034277171
12.221304034276988
12.221304034276804
12.22130403427663
12.221304034276452
12.221304034276262
12.221304034276088
12.221304034275901
12.221304034275718
12.221304034275539
12.221304034275356
12.221304034275187
12.221304034274999
12.22130403427481
12.221304034274647
12.221304034274452
12.221304034274274
12.221304034274093
12.221304034273913
12.221304034273727
12.221304034273551
12.221304034273373
12.221304034273189
12.221304034273002
12.221304034272825
12.221304034272647
12.221304034272466
12.22130403427229
12.221304034272105
12.221304034271927
12.221304034271741
12.221304034271556
12.221304034271386
12.221304034271203
12.221304034271016
12.22130403427084
12.221304034270663
12.221304034270478
12.2213040342703
12.22130403427012
12.221304034269941
12.221304034269762
12.22130403426958
12.221304034269398
12.221304034269224
12.221304034269039
12.221304034268854
12.221304034268686
12.221304034268503
12.22130403426832
12.221304034268137
12.221304034267959
12.22130403426778
12.221304034267613
12.221304034267424
12.221304034267245
12.221304034267062
12.221304034266876
12.221304034266694
12.221304034266524
12.221304034266344
12.221304034266167
12.22130403426599
12.22130403426581
12.221304034265634
12.221304034265449
12.221304034265282
12.221304034265096
12.221304034264916
12.221304034264733
12.221304034264552
12.22130403426438
12.221304034264193
12.221304034264014
12.221304034263843
12.221304034263666
12.221304034263476
12.2213040342633
12.221304034263127
12.221304034262948
12.221304034262767
12.221304034262593
12.22130403426241
12.221304034262229
12.221304034262058
12.221304034261872
12.221304034261696
12.221304034261516
12.221304034261344
12.221304034261165
12.221304034260987
12.2213040342608
12.221304034260621
12.221304034260456
12.221304034260275
12.221304034260095
12.221304034259921
12.221304034259738
12.22130403425957
12.221304034259383
12.221304034259212
12.221304034259024
12.221304034258855
12.221304034258676
12.221304034258495
12.221304034258326
12.221304034258146
12.221304034257962
12.221304034257793
12.221304034257606
12.221304034257424
12.221304034257255
12.221304034257084
12.2213040342569
12.22130403425672
12.221304034256548
12.221304034256363
12.221304034256184
12.22130403425601
12.221304034255835
12.22130403425565
12.221304034255478
12.221304034255308
12.22130403425513
12.221304034254953
12.221304034254773
12.221304034254604
12.221304034254423
12.221304034254246
12.221304034254068
12.221304034253894
12.221304034253714
12.221304034253535
12.221304034253357
12.221304034253183
12.221304034253004
12.221304034252833
12.221304034252658
12.221304034252482
12.221304034252299
12.221304034252126
12.221304034251947
12.221304034251773
12.221304034251597
12.221304034251428
12.221304034251245
12.221304034251071
12.221304034250894
12.221304034250723
12.221304034250544
12.221304034250364
12.221304034250185
12.221304034250018
12.221304034249842
12.221304034249663
12.221304034249492
12.221304034249307
12.22130403424914
12.221304034248957
12.221304034248785
12.22130403424861
12.221304034248433
12.221304034248265
12.221304034248083
12.221304034247904
12.221304034247732
12.221304034247558
12.221304034247385
12.221304034247213
12.221304034247035
12.22130403424685
12.221304034246689
12.221304034246506
12.22130403424633
12.22130403424616
12.221304034245982
12.22130403424581
12.221304034245632
12.22130403424546
12.221304034245282
12.221304034245113
12.221304034244932
12.221304034244753
12.221304034244588
12.221304034244413
12.221304034244236
12.221304034244065
12.221304034243888
12.221304034243714
12.221304034243541
12.22130403424336
12.221304034243193
12.221304034243023
12.221304034242843
12.221304034242669
12.221304034242488
12.221304034242323
12.221304034242142
12.22130403424197
12.221304034241799
12.221304034241628
12.22130403424145
12.22130403424128
12.221304034241104
12.221304034240934
12.22130403424075
12.221304034240584
12.22130403424041
12.221304034240228
12.22130403424006
12.221304034239887
12.221304034239715
12.221304034239541
12.221304034239369
12.221304034239193
12.221304034239019

12.22130403423885
12.221304034238672
12.221304034238496
12.221304034238324
12.221304034238145
12.22130403423798
12.221304034237805
12.221304034237631
12.221304034237463
12.221304034237281
12.22130403423712
12.221304034236942
12.221304034236768
12.221304034236594
12.221304034236422
12.221304034236248
12.221304034236077
12.22130403423591
12.22130403423573
12.221304034235564
12.221304034235393
12.221304034235217
12.221304034235047
12.22130403423487
12.221304034234691
12.221304034234523
12.221304034234354
12.221304034234176
12.221304034234011
12.221304034233833
12.221304034233665
12.22130403423349
12.221304034233324
12.221304034233148
12.221304034232979
12.2213040342328
12.221304034232634
12.221304034232462
12.221304034232293
12.221304034232118
12.221304034231947
12.221304034231771
12.2213040342316
12.22130403423143
12.22130403423126
12.221304034231085
12.221304034230911
12.221304034230746
12.221304034230572
12.221304034230394
12.221304034230227
12.221304034230048
12.221304034229883
12.221304034229714
12.221304034229538
12.221304034229373
12.221304034229204
12.22130403422903
12.221304034228856
12.221304034228687
12.221304034228517
12.221304034228337
12.221304034228174
12.221304034228005
12.221304034227831
12.221304034227664
12.221304034227492
12.221304034227323
12.221304034227149
12.221304034226971
12.22130403422681
12.221304034226627
12.221304034226463
12.221304034226291
12.221304034226122
12.221304034225955
12.221304034225787
12.221304034225618
12.221304034225446
12.221304034225273
12.2213040342251
12.221304034224932
12.221304034224762
12.221304034224591
12.22130403422442
12.221304034224252
12.221304034224078
12.22130403422391
12.221304034223744
12.221304034223568
12.221304034223401
12.221304034223229
12.221304034223067
12.221304034222891
12.221304034222717
12.22130403422255
12.221304034222376
12.221304034222216
12.221304034222046
12.221304034221877
12.22130403422171
12.221304034221532
12.221304034221363
12.221304034221195
12.221304034221024
12.221304034220863
12.221304034220681
12.221304034220514
12.221304034220342
12.221304034220188
12.221304034220008
12.221304034219838
12.221304034219674
12.221304034219505
12.221304034219328
12.22130403421916
12.221304034218997
12.221304034218823
12.221304034218656
12.221304034218482
12.221304034218322
12.221304034218155
12.221304034217976
12.221304034217809
12.221304034217638
12.221304034217473
12.221304034217304
12.221304034217141
12.22130403421697
12.22130403421681
12.221304034216635
12.221304034216464
12.221304034216296
12.221304034216123
12.22130403421596
12.22130403421579
12.22130403421562
12.221304034215455
12.221304034215285
12.221304034215118
12.221304034214947
12.22130403421478
12.221304034214612
12.221304034214443
12.221304034214283
12.22130403421411
12.22130403421394
12.221304034213768
12.221304034213611
12.221304034213434
12.22130403421327
12.221304034213103
12.221304034212936
12.221304034212766
12.221304034212594
12.221304034212435
12.221304034212265
12.221304034212096
12.22130403421193
12.221304034211757
12.221304034211599
12.221304034211427
12.22130403421126
12.22130403421109
12.221304034210926
12.221304034210757
12.221304034210585
12.221304034210423
12.221304034210254
12.221304034210087
12.221304034209913
12.221304034209759
12.221304034209586
12.221304034209423
12.221304034209256
12.221304034209089
12.221304034208922
12.22130403420875
12.221304034208584
12.221304034208417
12.221304034208256
12.221304034208085
12.221304034207922
12.22130403420775
12.22130403420758
12.221304034207417
12.221304034207254
12.221304034207083
12.221304034206923
12.221304034206753
12.221304034206584
12.22130403420643
12.221304034206254
12.221304034206089
12.221304034205922
12.221304034205755
12.221304034205595
12.221304034205426
12.221304034205255
12.221304034205094
12.221304034204929
12.221304034204763
12.221304034204595
12.221304034204433
12.221304034204268
12.221304034204088
12.22130403420392
12.221304034203772
12.221304034203596
12.22130403420343
12.22130403420327
12.22130403420311
12.221304034202937
12.22130403420277
12.2213040342026
12.221304034202438
12.221304034202271
12.221304034202108
12.221304034201946
12.221304034201783
12.221304034201614
12.221304034201454
12.221304034201284
12.221304034201125
12.221304034200958
12.22130403420079
12.221304034200621
12.22130403420046
12.2213040342003
12.221304034200127
12.221304034199958
12.221304034199804
12.221304034199632
12.221304034199461
12.221304034199305
12.221304034199141
12.221304034198978
12.221304034198814
12.221304034198644
12.221304034198486
12.221304034198313
12.221304034198154
12.221304034197988
12.221304034197827
12.22130403419766
12.221304034197493
12.221304034197333
12.221304034197164
12.221304034196997
12.221304034196837
12.221304034196674
12.221304034196509
12.221304034196347
12.22130403419618
12.22130403419602
12.221304034195859
12.221304034195692
12.221304034195523
12.221304034195365
12.221304034195196
12.221304034195034
12.221304034194866
12.221304034194702
12.221304034194544
12.221304034194384
12.221304034194219
12.22130403419405
12.221304034193892
12.22130403419372
12.221304034193565
12.2213040341934
12.221304034193238
12.221304034193073
12.221304034192906
12.221304034192746
12.221304034192583
12.221304034192423
12.221304034192253
12.221304034192094
12.221304034191933
12.221304034191762
12.221304034191604
12.221304034191435
12.221304034191279
12.221304034191114
12.221304034190952
12.221304034190785
12.221304034190622
12.221304034190464
12.221304034190299
12.22130403419014
12.22130403418997
12.221304034189819
12.22130403418965
12.221304034189485
12.221304034189322
12.221304034189156
12.221304034188996
12.221304034188835
12.221304034188671
12.221304034188512
12.221304034188343
12.221304034188192
12.221304034188025
12.221304034187868
12.221304034187707
12.22130403418754
12.221304034187375
12.221304034187217
12.221304034187051
12.221304034186893
12.221304034186726
12.221304034186568
12.221304034186398
12.221304034186245
12.221304034186083
12.221304034185918
12.22130403418576
12.221304034185598
12.22130403418543
12.221304034185275
12.22130403418511
12.221304034184943
12.221304034184788
12.221304034184628
12.221304034184463
12.221304034184298
12.221304034184138
12.221304034183982
12.221304034183817
12.221304034183651
12.221304034183492
12.221304034183333
12.22130403418317
12.221304034183008
12.221304034182848
12.221304034182685
12.221304034182522
12.221304034182364
12.221304034182204
12.22130403418205
12.221304034181884
12.221304034181722
12.22130403418156
12.2213040341814
12.221304034181237
12.221304034181074
12.221304034180918
12.221304034180763
12.221304034180598
12.22130403418044
12.221304034180276
12.221304034180113
12.22130403417995
12.22130403417979
12.221304034179628
12.22130403417947
12.22130403417931
12.221304034179152
12.221304034178987
12.221304034178829
12.221304034178674
12.221304034178504
12.221304034178347
12.221304034178198
12.221304034178031
12.221304034177866
12.221304034177708
12.22130403417755
12.221304034177388
12.221304034177226
12.221304034177068
12.221304034176915
12.221304034176748
12.22130403417659
12.221304034176429
12.221304034176267
12.221304034176116
12.221304034175947
12.22130403417579
12.221304034175635
12.221304034175477
12.221304034175319
12.221304034175152
12.221304034174997
12.221304034174834
12.221304034174672
12.221304034174521
12.221304034174356
12.2213040341742
12.221304034174038
12.22130403417388
12.221304034173714
12.221304034173563
12.221304034173404
12.22130403417324
12.221304034173091
12.221304034172922
12.221304034172766
12.221304034172611
12.221304034172453
12.22130403417229
12.221304034172125
12.221304034171975
12.221304034171812
12.221304034171654
12.221304034171494
12.221304034171338
12.221304034171176
12.221304034171022
12.221304034170855
12.221304034170705
12.221304034170542
12.221304034170382
12.221304034170227
12.221304034170066
12.221304034169911
12.221304034169753
12.221304034169592
12.221304034169428
12.22130403416928
12.221304034169124
12.22130403416896
12.2213040341688
12.221304034168645
12.221304034168485
12.221304034168321
12.221304034168169
12.22130403416801
12.221304034167849
12.221304034167696
12.221304034167536
12.221304034167376
12.221304034167225
12.221304034167066
12.221304034166913
12.221304034166751
12.2213040341666
12.22130403416643
12.221304034166275
12.22130403416612
12.22130403416597
12.2213040341658
12.22130403416565
12.221304034165495
12.22130403416533
12.221304034165176
12.221304034165021
12.221304034164863
12.221304034164705
12.22130403416455
12.221304034164383
12.22130403416423
12.22130403416407
12.221304034163918
12.22130403416376
12.221304034163602
12.22130403416345
12.221304034163289
12.221304034163131
12.22130403416297
12.221304034162822
12.221304034162658
12.221304034162504
12.221304034162346
12.22130403416219
12.221304034162037
12.22130403416188
12.221304034161724
12.22130403416156
12.221304034161404
12.221304034161252
12.2213040341611
12.221304034160935
12.221304034160795
12.22130403416063
12.221304034160472
12.221304034160308
12.221304034160163
12.221304034160005
12.221304034159846
12.221304034159687

12.221304034159525
12.221304034159376
12.221304034159225
12.22130403415906
12.22130403415891
12.22130403415876
12.221304034158598
12.221304034158438
12.22130403415829
12.221304034158136
12.221304034157978
12.221304034157814
12.22130403415766
12.22130403415751
12.221304034157356
12.221304034157193
12.221304034157042
12.221304034156883
12.221304034156734
12.221304034156573
12.221304034156422
12.221304034156267
12.22130403415611
12.221304034155953
12.221304034155793
12.22130403415564
12.221304034155485
12.221304034155336
12.221304034155178
12.221304034155025
12.221304034154866
12.221304034154707
12.22130403415455
12.221304034154405
12.22130403415425
12.221304034154091
12.221304034153944
12.221304034153784
12.221304034153626
12.221304034153471
12.221304034153317
12.221304034153164
12.221304034153007
12.221304034152858
12.221304034152704
12.22130403415254
12.221304034152391
12.221304034152233
12.221304034152084
12.221304034151924
12.221304034151766
12.221304034151617
12.221304034151464
12.221304034151311
12.221304034151153
12.221304034151004
12.221304034150846
12.221304034150696
12.22130403415054
12.22130403415038
12.221304034150226
12.221304034150078
12.221304034149925
12.22130403414976
12.221304034149616
12.221304034149458
12.221304034149302
12.221304034149147
12.221304034148986
12.221304034148844
12.22130403414869
12.221304034148543
12.221304034148385
12.221304034148229
12.221304034148075
12.221304034147916
12.22130403414777
12.221304034147616
12.221304034147463
12.221304034147302
12.221304034147154
12.221304034146996
12.221304034146847
12.221304034146696
12.22130403414654
12.221304034146387
12.221304034146234
12.221304034146081
12.221304034145927
12.221304034145778
12.221304034145616
12.22130403414547
12.221304034145312
12.221304034145165
12.221304034145009
12.221304034144856
12.221304034144703
12.221304034144552
12.221304034144401
12.221304034144246
12.221304034144094
12.221304034143937
12.221304034143781
12.221304034143646
12.221304034143479
12.22130403414333
12.221304034143177
12.221304034143019
12.221304034142873
12.221304034142717
12.221304034142568
12.221304034142408
12.22130403414226
12.221304034142117
12.221304034141959
12.221304034141808
12.221304034141657
12.2213040341415
12.221304034141351
12.221304034141198
12.221304034141042
12.221304034140895
12.221304034140744
12.22130403414059
12.22130403414044
12.221304034140285
12.221304034140129
12.221304034139994
12.221304034139838
12.221304034139681
12.221304034139528
12.221304034139369
12.221304034139221
12.221304034139079
12.22130403413892
12.22130403413877
12.221304034138619
12.221304034138466
12.221304034138308
12.22130403413816
12.221304034138011
12.221304034137859
12.221304034137713
12.22130403413756
12.2213040341374
12.221304034137246
12.221304034137098
12.221304034136951
12.221304034136802
12.221304034136653
12.221304034136505
12.22130403413634
12.221304034136194
12.221304034136047
12.221304034135892
12.221304034135743
12.221304034135592
12.221304034135438
12.221304034135292
12.221304034135139
12.221304034134985
12.221304034134835
12.221304034134683
12.221304034134532
12.221304034134384
12.221304034134228
12.22130403413409
12.221304034133938
12.221304034133786
12.221304034133638
12.221304034133484
12.22130403413333
12.221304034133183
12.221304034133032
12.221304034132881
12.221304034132725
12.221304034132578
12.22130403413243
12.221304034132277
12.221304034132128
12.22130403413198
12.221304034131835
12.221304034131679
12.221304034131526
12.221304034131375
12.221304034131228
12.221304034131085
12.221304034130933
12.221304034130782
12.221304034130624
12.221304034130474
12.221304034130325
12.221304034130176
12.221304034130029
12.221304034129881
12.221304034129735
12.221304034129583
12.221304034129435
12.221304034129288
12.221304034129131
12.221304034128984
12.221304034128833
12.22130403412869
12.221304034128535
12.221304034128385
12.221304034128233
12.22130403412808
12.22130403412794
12.221304034127789
12.221304034127641
12.221304034127485
12.221304034127343
12.221304034127195
12.221304034127048
12.2213040341269
12.221304034126746
12.221304034126598
12.221304034126444
12.221304034126295
12.221304034126149
12.221304034126003
12.22130403412585
12.221304034125701
12.221304034125556
12.221304034125406
12.221304034125254
12.221304034125108
12.221304034124959
12.221304034124811
12.221304034124659
12.221304034124515
12.221304034124366
12.221304034124222
12.221304034124069
12.22130403412392
12.221304034123776
12.221304034123628
12.221304034123477
12.221304034123328
12.22130403412318
12.221304034123028
12.22130403412288
12.22130403412273
12.221304034122587
12.221304034122442
12.221304034122285
12.221304034122142
12.221304034121996
12.221304034121843
12.2213040341217
12.221304034121552
12.2213040341214
12.221304034121252
12.221304034121108
12.221304034120966
12.221304034120811
12.221304034120664
12.221304034120516
12.22130403412037
12.221304034120225
12.221304034120068
12.221304034119925
12.22130403411978
12.221304034119635
12.221304034119488
12.221304034119342
12.221304034119191
12.221304034119036
12.2213040341189
12.221304034118749
12.2213040341186
12.221304034118448
12.22130403411831
12.221304034118157
12.221304034118011
12.221304034117868
12.221304034117717
12.221304034117571
12.221304034117425
12.22130403411727
12.221304034117129
12.221304034116985
12.22130403411684
12.221304034116688
12.221304034116542
12.221304034116393
12.221304034116246
12.221304034116109
12.221304034115953
12.221304034115807
12.221304034115667
12.221304034115516
12.22130403411537
12.22130403411522
12.221304034115082
12.221304034114931
12.221304034114791
12.221304034114638
12.221304034114489
12.221304034114336
12.221304034114201
12.221304034114064
12.221304034113905
12.221304034113759
12.221304034113613
12.221304034113468
12.221304034113329
12.22130403411318
12.221304034113025
12.221304034112881
12.221304034112736
12.221304034112599
12.221304034112446
12.221304034112299
12.221304034112151
12.22130403411201
12.221304034111862
12.221304034111714
12.22130403411157
12.221304034111423
12.221304034111274
12.221304034111133
12.221304034110986
12.221304034110844
12.221304034110696
12.221304034110558
12.221304034110407
12.221304034110261
12.221304034110112
12.221304034109972
12.221304034109831
12.22130403410968
12.221304034109538
12.22130403410939
12.22130403410924
12.221304034109096
12.221304034108956
12.221304034108813
12.22130403410866
12.221304034108519
12.221304034108377
12.221304034108229
12.221304034108089
12.221304034107936
12.221304034107792
12.221304034107645
12.221304034107504
12.221304034107359
12.221304034107217
12.22130403410707
12.221304034106922
12.221304034106781
12.22130403410664
12.22130403410649
12.221304034106355
12.221304034106199
12.221304034106058
12.221304034105914
12.221304034105762
12.221304034105621
12.221304034105472
12.221304034105339
12.221304034105188
12.221304034105044
12.2213040341049
12.22130403410476
12.221304034104609
12.22130403410447
12.221304034104326
12.221304034104188
12.221304034104039
12.221304034103904
12.22130403410375
12.221304034103602
12.221304034103465
12.221304034103321
12.221304034103174
12.22130403410303
12.221304034102898
12.221304034102737
12.221304034102602
12.22130403410245
12.221304034102312
12.221304034102163
12.221304034102024
12.22130403410189
12.221304034101733
12.221304034101603
12.221304034101445
12.221304034101308
12.221304034101163
12.221304034101017
12.221304034100879
12.221304034100738
12.221304034100596
12.22130403410045
12.221304034100303
12.221304034100159
12.221304034100019
12.221304034099875
12.221304034099733
12.221304034099589
12.221304034099449
12.221304034099303
12.221304034099163
12.221304034099015
12.221304034098873
12.221304034098727
12.221304034098589
12.221304034098445
12.221304034098301
12.221304034098157
12.221304034098013
12.221304034097875
12.221304034097727
12.221304034097592
12.221304034097445
12.221304034097304
12.221304034097159
12.221304034097018
12.221304034096873
12.22130403409673
12.221304034096585
12.221304034096447
12.221304034096304
12.221304034096157
12.22130403409602
12.221304034095873
12.221304034095732
12.22130403409559
12.221304034095454
12.221304034095313
12.221304034095162
12.221304034095024
12.221304034094878
12.221304034094738
12.221304034094606
12.221304034094462
12.221304034094313
12.221304034094175
12.221304034094036
12.22130403409389
12.221304034093752
12.221304034093603
12.221304034093457
12.22130403409332
12.221304034093174
12.22130403409304
12.2213040340929
12.221304034092759
12.22130403409261
12.221304034092476
12.221304034092336
12.221304034092189
12.22130403409204
12.221304034091903
12.22130403409177
12.221304034091617
12.22130403409148
12.22130403409134
12.221304034091192
12.221304034091055
12.221304034090915
12.221304034090778
12.221304034090638
12.221304034090496
12.221304034090354
12.22130403409021
12.221304034090076
12.221304034089927
12.221304034089787
12.221304034089643
12.221304034089506
12.221304034089366
12.221304034089224
12.221304034089089
12.221304034088938
12.221304034088801
12.221304034088673
12.221304034088517
12.221304034088377
12.221304034088243
12.221304034088094
12.221304034087956
12.221304034087824
12.221304034087682
12.221304034087533
12.221304034087401

12.221304034087256
12.221304034087114
12.221304034086979
12.221304034086833
12.22130403408669
12.221304034086561
12.221304034086419
12.221304034086268
12.221304034086135
12.221304034085994
12.221304034085854
12.221304034085716
12.221304034085579
12.221304034085431
12.221304034085298
12.221304034085156
12.221304034085014
12.221304034084874
12.221304034084735
12.2213040340846
12.221304034084458
12.221304034084316
12.221304034084179
12.221304034084032
12.221304034083893
12.221304034083762
12.22130403408362
12.221304034083472
12.22130403408334
12.2213040340832
12.221304034083065
12.221304034082912
12.221304034082776
12.221304034082639
12.221304034082499
12.221304034082364
12.221304034082225
12.221304034082078
12.221304034081944
12.221304034081815
12.221304034081667
12.221304034081527
12.221304034081383
12.221304034081248
12.221304034081108
12.22130403408097
12.221304034080832
12.221304034080688
12.22130403408055
12.221304034080415
12.221304034080276
12.221304034080141
12.22130403408
12.221304034079857
12.221304034079711
12.221304034079578
12.221304034079441
12.221304034079306
12.221304034079157
12.221304034079028
12.221304034078889
12.22130403407875
12.221304034078608
12.221304034078468
12.221304034078333
12.2213040340782
12.221304034078058
12.221304034077917
12.221304034077773
12.22130403407764
12.221304034077509
12.221304034077367
12.221304034077228
12.221304034077086
12.221304034076946
12.221304034076809
12.221304034076669
12.221304034076537
12.221304034076391
12.221304034076255
12.221304034076121
12.221304034075983
12.22130403407585
12.221304034075708
12.221304034075569
12.221304034075438
12.221304034075292
12.221304034075155
12.221304034075022
12.221304034074883
12.221304034074743
12.22130403407461
12.22130403407447
12.221304034074334
12.221304034074201
12.221304034074057
12.221304034073913
12.221304034073771
12.22130403407364
12.221304034073507
12.221304034073368
12.22130403407323
12.2213040340731
12.22130403407296
12.221304034072814
12.221304034072682
12.221304034072542
12.221304034072404
12.221304034072274
12.221304034072126
12.221304034071999
12.221304034071863
12.221304034071723
12.221304034071581
12.221304034071446
12.221304034071306
12.22130403407117
12.22130403407104
12.2213040340709
12.221304034070764
12.221304034070632
12.221304034070487
12.221304034070352
12.221304034070211
12.221304034070084
12.221304034069954
12.221304034069808
12.221304034069666
12.221304034069538
12.221304034069401
12.221304034069258
12.22130403406912
12.221304034068986
12.221304034068847
12.221304034068721
12.221304034068575
12.221304034068442
12.221304034068298
12.221304034068162
12.221304034068032
12.221304034067895
12.221304034067758
12.221304034067632
12.221304034067485
12.221304034067344
12.22130403406722
12.221304034067076
12.221304034066938
12.221304034066812
12.221304034066668
12.221304034066536
12.221304034066394
12.22130403406627
12.22130403406613
12.221304034065989
12.221304034065852
12.221304034065726
12.22130403406558
12.221304034065453
12.221304034065314
12.221304034065183
12.221304034065042
12.221304034064902
12.221304034064776
12.221304034064636
12.221304034064497
12.22130403406436
12.221304034064229
12.2213040340641
12.221304034063957
12.221304034063817
12.22130403406369
12.221304034063555
12.221304034063419
12.221304034063282
12.221304034063149
12.221304034063005
12.221304034062879
12.221304034062738
12.22130403406261
12.221304034062474
12.221304034062328
12.2213040340622
12.221304034062065
12.221304034061932
12.221304034061792
12.221304034061665
12.221304034061527
12.221304034061397
12.221304034061262
12.221304034061115
12.221304034060989
12.221304034060855
12.221304034060719
12.221304034060589
12.22130403406045
12.221304034060312
12.22130403406018
12.221304034060042
12.221304034059909
12.221304034059777
12.22130403405964
12.221304034059502
12.221304034059372
12.221304034059235
12.221304034059107
12.221304034058962
12.221304034058836
12.221304034058697
12.22130403405857
12.221304034058432
12.221304034058303
12.221304034058166
12.22130403405803
12.221304034057894
12.221304034057757
12.221304034057626
12.221304034057495
12.221304034057361
12.221304034057232
12.221304034057093
12.221304034056958
12.221304034056825
12.221304034056697
12.22130403405656
12.22130403405642
12.22130403405629
12.221304034056164
12.22130403405602
12.221304034055889
12.221304034055759
12.221304034055622
12.221304034055487
12.221304034055354
12.221304034055226
12.22130403405509
12.22130403405496
12.221304034054825
12.22130403405469
12.221304034054562
12.221304034054423
12.221304034054292
12.221304034054157
12.221304034054024
12.221304034053887
12.221304034053757
12.221304034053626
12.221304034053494
12.221304034053365
12.221304034053228
12.221304034053095
12.221304034052954
12.221304034052825
12.221304034052698
12.22130403405256
12.221304034052423
12.221304034052299
12.221304034052169
12.221304034052034
12.221304034051888
12.221304034051768
12.221304034051625
12.221304034051501
12.221304034051368
12.221304034051233
12.2213040340511
12.221304034050966
12.221304034050835
12.221304034050705
12.221304034050572
12.221304034050442
12.221304034050307
12.221304034050174
12.221304034050046
12.221304034049908
12.221304034049776
12.221304034049636
12.221304034049508
12.221304034049377
12.221304034049252
12.221304034049114
12.221304034048982
12.221304034048847
12.22130403404872
12.22130403404859
12.221304034048456
12.221304034048325
12.221304034048194
12.221304034048057
12.221304034047925
12.221304034047794
12.221304034047662
12.221304034047531
12.221304034047396
12.221304034047268
Weights: [-0.09823569  0.43247193  0.04719483  1.02369242] | Bias: -2.5130610897334766 | Final SSE: 12.221304034047268

**--Q11--(5 points)**
use the predict method to predict the output of test data set that selected in Q7. count and print the error which is defined as the number of unmatched prediction

In [7]:
outcome = Predict(test_data, l_weights, l_bias, 0)
error = 0
for x in range(len(outcome)):
    print('Prediction:', 'iris-virginica' if outcome[x] == 1 else 'not iris-virginica', ":", 'Target:',  'iris-virginica' if test_data.at[x, 'target'] == 1 else 'not iris-virginica')
    if outcome[x] != test_data.at[x, 'target']:
        error += 1
print('Errors:', error)

Prediction: not iris-virginica : Target: not iris-virginica
Prediction: not iris-virginica : Target: not iris-virginica
Prediction: not iris-virginica : Target: not iris-virginica
Prediction: not iris-virginica : Target: not iris-virginica
Prediction: not iris-virginica : Target: not iris-virginica
Prediction: iris-virginica : Target: iris-virginica
Prediction: iris-virginica : Target: iris-virginica
Prediction: iris-virginica : Target: iris-virginica
Prediction: iris-virginica : Target: iris-virginica
Prediction: iris-virginica : Target: iris-virginica
Errors: 0